### ISSUE TITLE
Get websocket data in exception handler

### ISSUE THREAD

**Issue by Romainpaulus** [miguelgrinberg/Flask-SocketIO#100]
I want to access the websocket data for exception logging, similarly to this example:
```
socketio = SocketIO()

@socketio.on_error_default
def error_handler(e):
    # Log the exception with event data
    pass

@socketio.on('my event')
def message_hander(data):
    raise RuntimeError()
```

From what I have seen so far, there is no simple way to get the `data` that was passed to the `message_handler` function inside the `error_handler`, unless overriding the `socketio.on` decorator. I want to submit a pull request that will achieve this, but I want to know first if there is a way to do this without changing the `socketio.on` method. Is there, for instance, a `request` attribute that contains the current websocket message and data?

**Comment by miguelgrinberg** [comment]
This is a good idea, I like it.

You need to keep in mind that there are a handful of events, and they all have different arguments. You have `message` (payload is a string), `json` (payload is a JSON blob), user-defined events (JSON payload), `connect` and `disconnect`.

The easiest way to achieve what you want is to add all the data to `request`. You can see [here](https://github.com/miguelgrinberg/Flask-SocketIO/blob/master/flask_socketio/__init__.py#L154) how I added the namespace. Maybe call it `request.event` and have it be a dict, something like this:

    {
        'message': <message name>,
        'args': <arg list>
    }

The message name can be `'message'`, `'json'`, `'connect'`, `'disconnect'` or a custom event name. The args can be a list of args if available, or `None` if the event does not take arguments.

Would something like this work for you?

**Comment by Romainpaulus** [comment]
Sounds good, I'm going to work on this.

**Comment by miguelgrinberg** [comment]
The upcoming version 1.0 will support this. You can use `request.event` to get a dictionary that contains two keys, `message` and `args`.

**Comment by miguelgrinberg** [comment]
Closing, since release 1.0 has been released.
