### ISSUE TITLE
Flask-SocketIO + gevent does not log GET and POST requests

### ISSUE THREAD

**Issue by patarapolw** [miguelgrinberg/Flask-SocketIO#1000]
```
socketio = SocketIO(app, logger=True, engineio_logger=True)
socketio.run(app, port=Config.PORT)
```

The only log shown ares `Server initialized for gevent.` and any socketIO events.

Even `logging.basicConfig(level=logging.DEBUG)` doesn't help.

**Comment by miguelgrinberg** [comment]
Add `log_output=True` to configure web server logging. The options that you enabled are strictly for Socket.IO and Engine.IO logging.

**Comment by patarapolw** [comment]
Thanks. More specifically, `socketio.run(app, log_output=True)`, right?

**Comment by miguelgrinberg** [comment]
Yes, sorry, that is configured in `app.run()`.
