### ISSUE TITLE
remote nginx reverse proxy gunicorn + eventlet not working

### ISSUE THREAD

**Issue by lgprobert** [miguelgrinberg/Flask-SocketIO#1001]
I can make reverse proxy worked if both Nginx and Gunicorn are on same box by setting `proxy_pass` to `proxy_pass http://127.0.0.1:5000;` as document. But with same working configuration but just replace the localhost with actual gunicorn listening IP address causes 404 error. 

Search on Google does not get much help and I had tried many possible configurations without luck. Are there further configurations that I need to on gunicorn? or on Nginx? 

Thanks

**Comment by miguelgrinberg** [comment]
Is the 404 coming from gunicorn or nginx? In other words, does the gunicorn process get the request? If not, can you send a request from your computer directly to the gunicorn server?

**Comment by lgprobert** [comment]
It turns out the issue on Nginx side. The Nginx instance I use have another `default.conf` sitting in `/etc/nginx/conf.d` which also listens to port 80. The port conflicts cause the forward policy not being picked up. Removes that file or changes the forward policy file port to non-80 port fix the issue. 

Now flask-socketio works expected and I will close the issue.

Thanks for the quick reply, that is very nice.
