### ISSUE TITLE
Server sends empty upgrades list client stuck in long polling

### ISSUE THREAD

**Issue by srikanth-nekt** [miguelgrinberg/Flask-SocketIO#1002]
After initial connect from client to '/socket.io', server sends back empty upgrades list. 
Then client never upgrades and keeps long polling. Unable to send emits to client sid.
Even tried setting 'allow_upgrades' engineio option (though the default is supposed to be 'True')

`socketio.init_app(  app,
                                message_queue=app.config['SOCKETIO_MESSAGE_QUEUE'],
                                allow_upgrades=True,
                                logger=True, engineio_logger=True)`

LOGS:
`7ba65df030894323a9f994a168cc3f38: Sending packet OPEN data {'pingInterval': 25000, 'pingTimeout': 60000, 'upgrades': [], 'sid': '7ba65df030894323a9f994a168cc3f38'}
7ba65df030894323a9f994a168cc3f38: Sending packet MESSAGE data 0
==> /var/log/gunicorn_err.log <==
7ba65df030894323a9f994a168cc3f38: Received packet MESSAGE data 2["login",{"userid":"e7d903d9-b6b1-4444-853c-e6dd71eec23e","install":732,"status":"connected"}]
received event "login" from 7ba65df030894323a9f994a168cc3f38 [/]`

Server Libs:
eventlet==0.19.0
Flask==0.10.1
Flask-Cors==3.0.2
Flask-Script==0.6.6
Flask-SocketIO==4.1.0
Flask-SQLAlchemy==2.1
Flask-SSLify==0.1.5
Flask-WTF==0.14.2
gunicorn==19.7.1
...
python-engineio==3.8.1
python-socketio==4.1.0
redis==2.10.5
requests==2.10.0
six==1.12.0

Client side: 
socket.io-client: 2.1.1

Thanks. Do let me know if more info is needed.

**Comment by srikanth-nekt** [comment]
Client side Recvd from server on initial https to '/socket.io':
_0{"pingInterval":25000,"pingTimeout":60000,"upgrades":[],"sid":"a53d4292dfa54b6e933a703d958ae4c8"}ÿ40_

**Comment by miguelgrinberg** [comment]
Can I see a complete log session for the server and the client?

**Comment by srikanth-nekt** [comment]
Server Logs:

**Comment by srikanth-nekt** [comment]
**Client (Web) Logs:**

`socket.io-client:url parse https://my-test-server.in +0ms
main.js:1 socket.io-client new io instance for https://my-test-server.in +0ms
main.js:1 socket.io-client:manager readyState closed +0ms
main.js:1 socket.io-client:manager opening https://my-test-server.in +2ms
main.js:1 engine.io-client:socket creating transport "polling" +0ms
main.js:1 engine.io-client:polling polling +0ms
main.js:1 engine.io-client:polling-xhr xhr poll +0ms
main.js:1 engine.io-client:polling-xhr xhr open GET: https://my-test-server.in/socket.io/?EIO=3&transport=polling&t=MjQyZeo +2ms
main.js:1 engine.io-client:polling-xhr xhr data null +4ms
main.js:1 engine.io-client:socket setting transport polling +17ms
main.js:1 socket.io-client:manager connect attempt will timeout after 20000 +25ms
main.js:1 socket.io-client:manager readyState opening +2ms

engine.io-client:polling polling got data ArrayBuffer(107) +340ms
main.js:1 engine.io-client:socket socket receive: type "open", data "{"pingInterval":25000,"pingTimeout":60000,"upgrades":[],"sid":"8ae3908a16504d689e4dac8cf98b46f5"}" +329ms
main.js:1 engine.io-client:socket socket open +1ms
main.js:1 socket.io-client:manager open +324ms
main.js:1 socket.io-client:manager cleanup +1ms
main.js:1 socket.io-client:socket transport is open - connecting +0ms
main.js:1 engine.io-client:socket starting upgrade probes +4ms
main.js:1 engine.io-client:socket socket receive: type "message", data "0" +1ms
main.js:1 socket.io-parser decoded 0 as {"type":0,"nsp":"/"} +0ms
main.js:1 socket.io-client:manager writing packet {"type":2,"data":["login",{"userid":"my-test-uid","installid":3766,"status":"connected"}],"options":{"compress":true},"nsp":"/"} +16ms
main.js:1 socket.io-parser encoding packet {"type":2,"data":["login",{"userid":"my-test-uid","installid":3766,"status":"connected"}],"options":{"compress":true},"nsp":"/"} +4ms
main.js:1 socket.io-parser encoded {"type":2,"data":["login",{"userid":"my-test-uid","installid":3766,"status":"connected"}],"options":{"compress":true},"nsp":"/"} as 2["login",{"userid":"my-test-uid","installid":3766,"status":"connected"}] +1ms
main.js:1 engine.io-client:socket flushing 1 packets in socket +18ms
main.js:1 engine.io-client:polling-xhr xhr open POST: https://my-test-server.in/socket.io/?EIO=3&transport=polling&t=MjQyZkX&sid=8ae3908a16504d689e4dac8cf98b46f5 +362ms
main.js:1 engine.io-client:polling-xhr xhr data 99:42["login",{"userid":"my-test-uid","installid":3766,"status":"connected"}] +1ms
main.js:1 engine.io-client:polling polling +35ms
main.js:1 engine.io-client:polling-xhr xhr poll +12ms
main.js:1 engine.io-client:polling-xhr xhr open GET: https://my-test-server.in/socket.io/?EIO=3&transport=polling&t=MjQyZkm&sid=8ae3908a16504d689e4dac8cf98b46f5 +2ms
main.js:1 engine.io-client:polling-xhr xhr data null +3ms

engine.io-client:socket writing ping packet - expecting pong within 60000ms +25s
main.js:1 engine.io-client:socket flushing 1 packets in socket +2ms
main.js:1 engine.io-client:polling-xhr xhr open POST: https://my-test-server.in/socket.io/?EIO=3&transport=polling&t=MjQyfrM&sid=8ae3908a16504d689e4dac8cf98b46f5 +25s
main.js:1 engine.io-client:polling-xhr xhr data 1:2 +2ms
main.js:1 engine.io-client:polling polling got data ArrayBuffer(4) +25s
main.js:1 engine.io-client:socket socket receive: type "pong", data "undefined" +480ms
main.js:1 engine.io-client:polling polling +50ms
main.js:1 engine.io-client:polling-xhr xhr poll +479ms
main.js:1 engine.io-client:polling-xhr xhr open GET: https://my-test-server.in/socket.io/?EIO=3&transport=polling&t=MjQyfyt&sid=8ae3908a16504d689e4dac8cf98b46f5 +1ms
main.js:1 engine.io-client:polling-xhr xhr data null +0ms
main.js:1 engine.io-client:socket writing ping packet - expecting pong within 60000ms +25s
main.js:1 engine.io-client:socket flushing 1 packets in socket +1ms
main.js:1 engine.io-client:polling-xhr xhr open POST: https://my-test-server.in/socket.io/?EIO=3&transport=polling&t=MjQym3W&sid=8ae3908a16504d689e4dac8cf98b46f5 +25s
main.js:1 engine.io-client:polling-xhr xhr data 1:2 +1ms
main.js:1 engine.io-client:polling polling got data ArrayBuffer(4) +25s
main.js:1 engine.io-client:socket socket receive: type "pong", data "undefined" +469ms
main.js:1 engine.io-client:polling polling +51ms
main.js:1 engine.io-client:polling-xhr xhr poll +468ms
main.js:1 engine.io-client:polling-xhr xhr open GET: https://my-test-server.in/socket.io/?EIO=3&transport=polling&t=MjQymAr&sid=8ae3908a16504d689e4dac8cf98b46f5 +0ms
main.js:1 engine.io-client:polling-xhr xhr data null +1ms
main.js:1 engine.io-client:socket writing ping packet - expecting pong within 60000ms +25s
main.js:1 engine.io-client:socket flushing 1 packets in socket +1ms
main.js:1 engine.io-client:polling-xhr xhr open POST: https://my-test-server.in/socket.io/?EIO=3&transport=polling&t=MjQysHW&sid=8ae3908a16504d689e4dac8cf98b46f5 +25s
main.js:1 engine.io-client:polling-xhr xhr data 1:2 +1ms
main.js:1 engine.io-client:polling polling got data ArrayBuffer(4) +25s
main.js:1 engine.io-client:socket socket receive: type "pong", data "undefined" +484ms
main.js:1 engine.io-client:polling polling +50ms
main.js:1 engine.io-client:polling-xhr xhr poll +483ms
main.js:1 engine.io-client:polling-xhr xhr open GET: https://my-test-server.in/socket.io/?EIO=3&transport=polling&t=MjQysP5&sid=8ae3908a16504d689e4dac8cf98b46f5 +1ms
main.js:1 engine.io-client:polling-xhr xhr data null +1ms
main.js:1 engine.io-client:socket writing ping packet - expecting pong within 60000ms +25s
main.js:1 engine.io-client:socket flushing 1 packets in socket +1ms
main.js:1 engine.io-client:polling-xhr xhr open POST: https://my-test-server.in/socket.io/?EIO=3&transport=polling&t=MjQyyVk&sid=8ae3908a16504d689e4dac8cf98b46f5 +25s
main.js:1 engine.io-client:polling-xhr xhr data 1:2 +2ms
main.js:1 engine.io-client:polling polling got data ArrayBuffer(4) +25s
main.js:1 engine.io-client:socket socket receive: type "pong", data "undefined" +509ms
main.js:1 engine.io-client:polling polling +63ms
main.js:1 engine.io-client:polling-xhr xhr poll +508ms
main.js:1 engine.io-client:polling-xhr xhr open GET: https://my-test-server.in/socket.io/?EIO=3&transport=polling&t=MjQyydj&sid=8ae3908a16504d689e4dac8cf98b46f5 +1ms
main.js:1 engine.io-client:polling-xhr xhr data null +1ms
main.js:1 engine.io-client:socket writing ping packet - expecting pong within 60000ms +25s
main.js:1 engine.io-client:socket flushing 1 packets in socket +1ms
main.js:1 engine.io-client:polling-xhr xhr open POST: https://my-test-server.in/socket.io/?EIO=3&transport=polling&t=MjQz2kK&sid=8ae3908a16504d689e4dac8cf98b46f5 +25s
main.js:1 engine.io-client:polling-xhr xhr data 1:2 +1ms
main.js:1 engine.io-client:polling polling got data ArrayBuffer(4) +25s
main.js:1 engine.io-client:socket socket receive: type "pong", data "undefined" +456ms
main.js:1 engine.io-client:polling polling +47ms
main.js:1 engine.io-client:polling-xhr xhr poll +456ms
main.js:1 engine.io-client:polling-xhr xhr open GET: https://my-test-server.in/socket.io/?EIO=3&transport=polling&t=MjQz2rT&sid=8ae3908a16504d689e4dac8cf98b46f5 +0ms
main.js:1 engine.io-client:polling-xhr xhr data null +1ms
main.js:1 engine.io-client:socket writing ping packet - expecting pong within 60000ms +25s
main.js:1 engine.io-client:socket flushing 1 packets in socket +0ms
main.js:1 engine.io-client:polling-xhr xhr open POST: https://my-test-server.in/socket.io/?EIO=3&transport=polling&t=MjQz8y5&sid=8ae3908a16504d689e4dac8cf98b46f5 +25s
main.js:1 engine.io-client:polling-xhr xhr data 1:2 +1ms
main.js:1 engine.io-client:polling polling got data ArrayBuffer(4) +25s
main.js:1 engine.io-client:socket socket receive: type "pong", data "undefined" +469ms
main.js:1 engine.io-client:polling polling +45ms
main.js:1 engine.io-client:polling-xhr xhr poll +468ms
main.js:1 engine.io-client:polling-xhr xhr open GET: https://my-test-server.in/socket.io/?EIO=3&transport=polling&t=MjQz93R&sid=8ae3908a16504d689e4dac8cf98b46f5 +1ms
main.js:1 engine.io-client:polling-xhr xhr data null +1ms
main.js:1 engine.io-client:socket writing ping packet - expecting pong within 60000ms +25s
main.js:1 engine.io-client:socket flushing 1 packets in socket +0ms
main.js:1 engine.io-client:polling-xhr xhr open POST: https://my-test-server.in/socket.io/?EIO=3&transport=polling&t=MjQzFA4&sid=8ae3908a16504d689e4dac8cf98b46f5 +25s
main.js:1 engine.io-client:polling-xhr xhr data 1:2 +1ms
main.js:1 engine.io-client:polling polling got data ArrayBuffer(4) +25s
main.js:1 engine.io-client:socket socket receive: type "pong", data "undefined" +462ms
main.js:1 engine.io-client:polling polling +52ms
main.js:1 engine.io-client:polling-xhr xhr poll +461ms
main.js:1 engine.io-client:polling-xhr xhr open GET: https://my-test-server.in/socket.io/?EIO=3&transport=polling&t=MjQzFHI&sid=8ae3908a16504d689e4dac8cf98b46f5 +0ms
main.js:1 engine.io-client:polling-xhr xhr data null +1ms
main.js:1 engine.io-client:socket writing ping packet - expecting pong within 60000ms +25s
main.js:1 engine.io-client:socket flushing 1 packets in socket +0ms
main.js:1 engine.io-client:polling-xhr xhr open POST: https://my-test-server.in/socket.io/?EIO=3&transport=polling&t=MjQzLNy&sid=8ae3908a16504d689e4dac8cf98b46f5 +25s
main.js:1 engine.io-client:polling-xhr xhr data 1:2 +1ms
main.js:1 engine.io-client:polling polling got data ArrayBuffer(4) +25s
main.js:1 engine.io-client:socket socket receive: type "pong", data "undefined" +503ms
main.js:1 engine.io-client:polling polling +34ms
main.js:1 engine.io-client:polling-xhr xhr poll +503ms
main.js:1 engine.io-client:polling-xhr xhr open GET: https://my-test-server.in/socket.io/?EIO=3&transport=polling&t=MjQzLVq&sid=8ae3908a16504d689e4dac8cf98b46f5 +0ms
main.js:1 engine.io-client:polling-xhr xhr data null +1ms
main.js:1 engine.io-client:socket writing ping packet - expecting pong within 60000ms +25s
main.js:1 engine.io-client:socket flushing 1 packets in socket +1ms
main.js:1 engine.io-client:polling-xhr xhr open POST: https://my-test-server.in/socket.io/?EIO=3&transport=polling&t=MjQzRcU&sid=8ae3908a16504d689e4dac8cf98b46f5 +25s
main.js:1 engine.io-client:polling-xhr xhr data 1:2 +1ms
main.js:1 engine.io-client:polling polling got data ArrayBuffer(4) +25s
main.js:1 engine.io-client:socket socket receive: type "pong", data "undefined" +449ms
main.js:1 engine.io-client:polling polling +43ms
main.js:1 engine.io-client:polling-xhr xhr poll +448ms
main.js:1 engine.io-client:polling-xhr xhr open GET: https://my-test-server.in/socket.io/?EIO=3&transport=polling&t=MjQzRjW&sid=8ae3908a16504d689e4dac8cf98b46f5 +2ms
main.js:1 engine.io-client:polling-xhr xhr data null +1ms
main.js:1 engine.io-client:socket writing ping packet - expecting pong within 60000ms +25s
main.js:1 engine.io-client:socket flushing 1 packets in socket +0ms
main.js:1 engine.io-client:polling-xhr xhr open POST: https://my-test-server.in/socket.io/?EIO=3&transport=polling&t=MjQzXq9&sid=8ae3908a16504d689e4dac8cf98b46f5 +25s
main.js:1 engine.io-client:polling-xhr xhr data 1:2 +1ms
main.js:1 engine.io-client:polling polling got data ArrayBuffer(4) +25s
main.js:1 engine.io-client:socket socket receive: type "pong", data "undefined" +449ms
main.js:1 engine.io-client:polling polling +54ms
main.js:1 engine.io-client:polling-xhr xhr poll +450ms
main.js:1 engine.io-client:polling-xhr xhr open GET: https://my-test-server.in/socket.io/?EIO=3&transport=polling&t=MjQzXxD&sid=8ae3908a16504d689e4dac8cf98b46f5 +2ms
main.js:1 engine.io-client:polling-xhr xhr data null +0ms
main.js:1 engine.io-client:socket writing ping packet - expecting pong within 60000ms +25s
main.js:1 engine.io-client:socket flushing 1 packets in socket +0ms
main.js:1 engine.io-client:polling-xhr xhr open POST: https://my-test-server.in/socket.io/?EIO=3&transport=polling&t=MjQze1p&sid=8ae3908a16504d689e4dac8cf98b46f5 +25s
main.js:1 engine.io-client:polling-xhr xhr data 1:2 +1ms
main.js:1 engine.io-client:polling polling got data ArrayBuffer(4) +25s
main.js:1 engine.io-client:socket socket receive: type "pong", data "undefined" +480ms
main.js:1 engine.io-client:polling polling +74ms
main.js:1 engine.io-client:polling-xhr xhr poll +481ms
main.js:1 engine.io-client:polling-xhr xhr open GET: https://my-test-server.in/socket.io/?EIO=3&transport=polling&t=MjQze9N&sid=8ae3908a16504d689e4dac8cf98b46f5 +2ms
main.js:1 engine.io-client:polling-xhr xhr data null +0ms
main.js:1 get all conversations list in =  {errorcode: "200", conversations: Array(100), errorstr: "DB Table updates exported successfully"}
main.js:1 engine.io-client:socket writing ping packet - expecting pong within 60000ms +25s
main.js:1 engine.io-client:socket flushing 1 packets in socket +0ms
main.js:1 engine.io-client:polling-xhr xhr open POST: https://my-test-server.in/socket.io/?EIO=3&transport=polling&t=MjQzkF-&sid=8ae3908a16504d689e4dac8cf98b46f5 +25s
main.js:1 engine.io-client:polling-xhr xhr data 1:2 +1ms
main.js:1 engine.io-client:polling polling got data ArrayBuffer(4) +25s
main.js:1 engine.io-client:socket socket receive: type "pong", data "undefined" +550ms
main.js:1 engine.io-client:polling polling +66ms
main.js:1 engine.io-client:polling-xhr xhr poll +551ms
main.js:1 engine.io-client:polling-xhr xhr open GET: https://my-test-server.in/socket.io/?EIO=3&transport=polling&t=MjQzkOc&sid=8ae3908a16504d689e4dac8cf98b46f5 +0ms
main.js:1 engine.io-client:polling-xhr xhr data null +1ms
main.js:1 engine.io-client:socket writing ping packet - expecting pong within 60000ms +25s
main.js:1 engine.io-client:socket flushing 1 packets in socket +1ms
main.js:1 engine.io-client:polling-xhr xhr open POST: https://my-test-server.in/socket.io/?EIO=3&transport=polling&t=MjQzqVF&sid=8ae3908a16504d689e4dac8cf98b46f5 +25s
main.js:1 engine.io-client:polling-xhr xhr data 1:2 +1ms
main.js:1 engine.io-client:polling polling got data ArrayBuffer(4) +25s
main.js:1 engine.io-client:socket socket receive: type "pong", data "undefined" +458ms
main.js:1 engine.io-client:polling polling +41ms
main.js:1 engine.io-client:polling-xhr xhr poll +458ms
main.js:1 engine.io-client:polling-xhr xhr open GET: https://my-test-server.in/socket.io/?EIO=3&transport=polling&t=MjQzqcQ&sid=8ae3908a16504d689e4dac8cf98b46f5 +0ms
main.js:1 engine.io-client:polling-xhr xhr data null +1ms
main.js:1 engine.io-client:socket writing ping packet - expecting pong within 60000ms +25s
main.js:1 engine.io-client:socket flushing 1 packets in socket +1ms
main.js:1 engine.io-client:polling-xhr xhr open POST: https://my-test-server.in/socket.io/?EIO=3&transport=polling&t=MjQzwj5&sid=8ae3908a16504d689e4dac8cf98b46f5 +25s
main.js:1 engine.io-client:polling-xhr xhr data 1:2 +2ms
main.js:1 engine.io-client:polling polling got data ArrayBuffer(4) +25s
main.js:1 engine.io-client:socket socket receive: type "pong", data "undefined" +463ms
main.js:1 engine.io-client:polling polling +49ms
main.js:1 engine.io-client:polling-xhr xhr poll +460ms
main.js:1 engine.io-client:polling-xhr xhr open GET: https://my-test-server.in/socket.io/?EIO=3&transport=polling&t=MjQzwqK&sid=8ae3908a16504d689e4dac8cf98b46f5 +1ms
main.js:1 engine.io-client:polling-xhr xhr data null +0ms
main.js:1 engine.io-client:socket writing ping packet - expecting pong within 60000ms +25s
main.js:1 engine.io-client:socket flushing 1 packets in socket +1ms
main.js:1 engine.io-client:polling-xhr xhr open POST: https://my-test-server.in/socket.io/?EIO=3&transport=polling&t=MjQ-0wy&sid=8ae3908a16504d689e4dac8cf98b46f5 +25s
main.js:1 engine.io-client:polling-xhr xhr data 1:2 +0ms
main.js:1 engine.io-client:polling polling got data ArrayBuffer(4) +25s
main.js:1 engine.io-client:socket socket receive: type "pong", data "undefined" +506ms
main.js:1 engine.io-client:polling polling +58ms
main.js:1 engine.io-client:polling-xhr xhr poll +506ms
main.js:1 engine.io-client:polling-xhr xhr open GET: https://my-test-server.in/socket.io/?EIO=3&transport=polling&t=MjQ-12u&sid=8ae3908a16504d689e4dac8cf98b46f5 +1ms
main.js:1 engine.io-client:polling-xhr xhr data null +1ms
main.js:1 engine.io-client:socket writing ping packet - expecting pong within 60000ms +25s
main.js:1 engine.io-client:socket flushing 1 packets in socket +1ms
main.js:1 engine.io-client:polling-xhr xhr open POST: https://my-test-server.in/socket.io/?EIO=3&transport=polling&t=MjQ-79W&sid=8ae3908a16504d689e4dac8cf98b46f5 +25s
main.js:1 engine.io-client:polling-xhr xhr data 1:2 +1ms
main.js:1 engine.io-client:polling polling got data ArrayBuffer(4) +25s
main.js:1 engine.io-client:socket socket receive: type "pong", data "undefined" +458ms
main.js:1 engine.io-client:polling polling +53ms
main.js:1 engine.io-client:polling-xhr xhr poll +457ms
main.js:1 engine.io-client:polling-xhr xhr open GET: https://my-test-server.in/socket.io/?EIO=3&transport=polling&t=MjQ-7Gg&sid=8ae3908a16504d689e4dac8cf98b46f5 +0ms
main.js:1 engine.io-client:polling-xhr xhr data null +1ms
main.js:1 engine.io-client:socket writing ping packet - expecting pong within 60000ms +25s
main.js:1 engine.io-client:socket flushing 1 packets in socket +0ms
main.js:1 engine.io-client:polling-xhr xhr open POST: https://my-test-server.in/socket.io/?EIO=3&transport=polling&t=MjQ-DNL&sid=8ae3908a16504d689e4dac8cf98b46f5 +25s
main.js:1 engine.io-client:polling-xhr xhr data 1:2 +3ms
main.js:1 engine.io-client:polling polling got data ArrayBuffer(4) +25s
main.js:1 engine.io-client:socket socket receive: type "pong", data "undefined" +473ms
main.js:1 engine.io-client:polling polling +50ms
main.js:1 engine.io-client:polling-xhr xhr poll +470ms
main.js:1 engine.io-client:polling-xhr xhr open GET: https://my-test-server.in/socket.io/?EIO=3&transport=polling&t=MjQ-DUl&sid=8ae3908a16504d689e4dac8cf98b46f5 +1ms
main.js:1 engine.io-client:polling-xhr xhr data null +1ms`

**Comment by miguelgrinberg** [comment]
I don't see anything wrong here. From the logs, it would appear as if you are sending `allow_upgrades=False`.

Do you have the code somewhere I can see it?

**Comment by srikanth-nekt** [comment]
Thanks for the prompt reply, Miguel.
There seems to be no options for _allow_upgrades_ to be set as per [socket.io-client docs](https://github.com/socketio/socket.io-client/blob/master/docs/API.md) ?

Fairly straightforward client side code (Angular - uses "socket.io-client": "2.1.1"):
Client does a simple connect using socket-service:
`import * as socketIo from 'socket.io-client';
export class SocketService {
    private socket;
    constructor(private router: Router) {}
    public initSocket(): void {
         this.socket = socketIo(SOCKETIO_BASE_URL);
	}
    public send(channel, message: {}): void {
        this.socket.emit(channel, message);
    }
    public onMessage(): Observable<{}> {
        return new Observable<{}>(observer => {
            this.socket.on('adds', (data: {}) => {
                console.log('adds socket data - ', data);
                observer.next(data);
            });
            this.socket.on('updates', (data: {}) => {
                console.log('updates socket data - ', data);
                observer.next(data);
            });
        });
    }
}`

socket-service is used as:

this.socket = socket.io-client('<base_url>/socket.io');
public send(chanel, message: {}): void { this.socket.emit(chanel, message); }
socket.send('login', { userid: userId, install: installid, status: 'connected' });

**Comment by miguelgrinberg** [comment]
The `allow_upgrades` is a server option, not client. I need to see your server code. If at all possible not a snippet, the actual code. I suspect this is going to end up being some obscure thing in your server code.

**Comment by srikanth-nekt** [comment]
Will soon create a minimal working example from server code which can (hopefully) reproduce the issue, thanks for the help.

**Comment by miguelgrinberg** [comment]
Please reopen when you are ready to continue troubleshooting this issue.
