### ISSUE TITLE
Flask-socketIO and Flask-Sqlalchemy

### ISSUE THREAD

**Issue by VionaGonsalves** [miguelgrinberg/Flask-SocketIO#1003]
Hi miguelgrinberg,

How do I use Flask-SocketIO and Flask-Sqlalchemy to continuously read from the database as new records come in. It would be really helpful if you give me an example of how it's done.

**Comment by miguelgrinberg** [comment]
Flask-SocketIO and Flask-SQLAlchemy have nothing in common. You can use each for its own purpose. In particular detecting when new records appear in a database table is usually done by polling at regular intervals, I don't believe there is a way to get an automatic notification when a new entry is added.
