### ISSUE TITLE
Sending messages from multiple servers to the same port

### ISSUE THREAD

**Issue by AmitRozner** [miguelgrinberg/Flask-SocketIO#1005]
I have multiple processes which include a message sending server. I would like to send all the messages to the same port, how is this possible? 
When using:
`socketio.run(app, host='0.0.0.0', debug=False, port=PortNumber)`

I get the following error:
`OSError: [Errno 98] Address already in use: ('0.0.0.0', 5000) `

**Comment by miguelgrinberg** [comment]
I don't understand what you want to do. You cannot run two servers on the same port if that is what you are asking.

**Comment by AmitRozner** [comment]
I would like the client to listen to a port and to send messages to the port from multiple processes

**Comment by miguelgrinberg** [comment]
This project is a server, not a client.

**Comment by AmitRozner** [comment]
Sorry for being unclear, I have little knowledge in this. The messages are sent by the servers to a single port. All the servers' processes run from the same machine, is it possible for all of them to send messages to a client via the same port? Something like a message queue? Thanks

**Comment by miguelgrinberg** [comment]
Sorry, but I still don't understand what you want to do. See if https://flask-socketio.readthedocs.io/en/latest/#emitting-from-an-external-process gives you what you need. Really if what you want isn't described in the documentation, then it's likely not something the package supports.
