### ISSUE TITLE
copy_current_request_context does not copy managed session data into new threads

### ISSUE THREAD

**Issue by DrewBarclay** [miguelgrinberg/Flask-SocketIO#1012]
When I use Flask's `copy_current_request_context`, it is supposed to copy both the session and the request. However, this seems broken: 

```
#!/usr/bin/env python
from threading import Lock
from flask import Flask, render_template, session, request, \
    copy_current_request_context
from flask_socketio import SocketIO, emit, join_room, leave_room, \
    close_room, rooms, disconnect
import eventlet

async_mode = 'eventlet'

app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app, async_mode=async_mode)

@app.route('/')
def index():
    return render_template('index.html', async_mode=socketio.async_mode)


@socketio.on('my_ping', namespace='/test')
def ping_pong():
    this_works = session['some_data_for_this_connection']

    @copy_current_request_context
    def do_something():
        this_throws_an_error = session['some_data_for_this_connection']
        return this_throws_an_error
    important_data = eventlet.spawn(do_something).wait()
    emit('my_pong', {'important_data': important_data, 'should_match_important_data': this_works})


@socketio.on('connect', namespace='/test')
def test_connect():
    session['some_data_for_this_connection'] = 5
    emit('my_response', {'data': 'Connected'})


@socketio.on('disconnect', namespace='/test')
def test_disconnect():
    print('Client disconnected', request.sid)


if __name__ == '__main__':
    socketio.run(app, debug=True, port=1234)
```

Sending a `my_ping` event throws the following error:
 ```
  File "<src_folder>/app.py", line 26, in do_something
    this_throws_an_error = session['some_data_for_this_connection']
  File "<virtualenv_folder>/flasktest/lib/python3.6/site-packages/werkzeug/local.py", line 378, in <lambda>
    __getitem__ = lambda x, i: x._get_current_object()[i]
  File "<virtualenv_folder>/flasktest/lib/python3.6/site-packages/flask/sessions.py", line 83, in __getitem__
    return super(SecureCookieSession, self).__getitem__(key)
KeyError: 'some_data_for_this_connection'
```

This can be ran with the Flask-SocketIO example index.html, or you can just remove that from the test case.

My expected behavior is that flask.session will be properly copied, but it is not.

Here's a requirements.txt in case it helps:
```
Click==7.0
dnspython==1.16.0
eventlet==0.25.0
Flask==1.0.3
Flask-SocketIO==4.1.0
greenlet==0.4.15
itsdangerous==1.1.0
Jinja2==2.10.1
MarkupSafe==1.1.1
monotonic==1.5
python-engineio==3.8.1
python-socketio==4.1.0
six==1.12.0
Werkzeug==0.15.4
``

**Comment by DrewBarclay** [comment]
I have the following hacky fix which is definitely not the best way to do this based on Flask-SocketIO's session management code:

```
from flask.globals import _request_ctx_stack as _request_ctx_stack
from functools import update_wrapper

def copy_current_request_context_v2(f):
    top = _request_ctx_stack.top
    if top is None:
        raise RuntimeError('This decorator can only be used at local scopes '
            'when a request context is on the stack.  For instance within '
            'view functions.')
    reqctx = top.copy()
    session = flask.session.copy()
    def wrapper(*args, **kwargs):
        with reqctx:
            _request_ctx_stack.top.session = session # this is the bit that is different from the normal flask copy_current_request_context - TODO find out why session is failed with flask-socketio
            return f(*args, **kwargs)
    return update_wrapper(wrapper, f)
```

Using this rather than `copy_current_request_context` fixes the issue, but it's absolutely awful. This seems like a bug in Flask-SocketIO.

**Comment by DrewBarclay** [comment]
As well, note that flask.request works correctly in new threads - it is only flask.session which fails to be copied correctly, presumably due to the code overriding Flask's normal session with a manged session object.

**Comment by miguelgrinberg** [comment]
This is sadly a consequence of the fact that there is no way for changes made to the session in a Socket.IO event handler to find their way to the real session held in a cookie. There is no vehicle to make updates to the cookie when the connection is WebSocket.

A possible solution would be for you to use server-side session storage (see Flask-Session for example). Then the session can be updated at any time, so there is no need for Flask-SocketIO to get involved, just set `manage_session=False` and Flask's own session handling will work just fine.

**Comment by DrewBarclay** [comment]
Perhaps I'm misunderstanding your response, but Flask-SocketIO's session handling works fine - changes to flask.session persist among multiple events, which is to say among different threads (`async_handlers=True`, which means each event gets its own thread). My example code shows this. I set a variable on connect, it persists through to the `'my_ping'` event.

The behavior is perfect and exactly what I want with `manage_session=True`... except that it doesn't correctly pass the data on to threads explicitly spawned by me with the `copy_current_request_context` annotation. Just to threads spawned the framework is spawning itself for new events.

Because of this, I don't see any reason why Flask's `copy_current_request_context` can't persist the managed session rather than the SecureCookieSession Flask is using by default. Or at least why the function I posted above, `copy_current_request_context_v2`, can't be included along with Flask-SocketIO to solve this issue.

(Though again, I feel like it's probably not the right solution?)

Sorry if I'm misunderstanding your request!

**Comment by miguelgrinberg** [comment]
@DrewBarclay The `copy_current_request_context` from Flask knows how to persist the Flask session. When you ask Flask-SocketIO to manage your session you are telling it to use its own sessions, not Flask's. So you can't have the Flask decorator persist a session that it does not know about.
