### ISSUE TITLE
SocketIO slow connection when Websocket (eventlet) installed

### ISSUE THREAD

**Issue by HimanshuSharma789** [miguelgrinberg/Flask-SocketIO#1016]
**AIM**
In this, image data from html file (client) is send to app.py flask (server) and then after some modification image is again send to the html page just like live streaming.

**OBSERVATION**
My flask-socket is working fine with Socketio - http (GET,POST) response, but the speed decreases when i installed eventlet for websocket transport.
I came to know that websockets are slower than the http response, when i use flask-socketio.
How can i increase the performance (speed) of data for real time application?

I used javascript Date() to calculate the time lag between the data transfer.

**Sample code**
app.py
```
from flask import Flask, render_template
from flask_socketio import SocketIO

app = Flask(__name__)
app.debug = True
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app)

###  MORE Code HERE   #####################

# issue with section below
count=0
@socketio.on('IMAGE_DATA_FROM_STREAMER')
def image(data, sec):
    global count
    count+=1
    print(count)
    print(sec)
```
index.html
```
video.addEventListener('play', function() {
	var $this = this; //cache
	(function loop() {
	   if (!$this.paused && !$this.ended) {
              context.drawImage($this, 0, 0,200,200);
              var date = new Date();
	      var data = canvas.toDataURL('image/png');

              //problem section javascript
             // **sending image data with Seconds data created**
              socket.compress(true).emit('IMAGE_DATA_FROM_STREAMER', data, date.getSeconds());
				    
	      // // specify the rate the function will iterate
	     setTimeout(loop, 1000 / 50); // drawing at 30fps	

         }
    })();
}, 0);
```

### **In simple conditions (before installing eventlet):**

I get real time data from the html page
Time in seconds emit from the index.html is received at same Second in app.py

![Annotation 2019-07-01 215430](https://user-images.githubusercontent.com/32963903/60453555-1595d080-9c4f-11e9-9286-cd91ac4429d1.png)
![Screenshot (12)_LI](https://user-images.githubusercontent.com/32963903/60453988-4aeeee00-9c50-11e9-98f0-61d4ae716ef2.jpg)

**As soon as I installed eventlet or gevent**
`pip install eventlet`

### **After installing eventlet**
![Annotation 2019-07-01 223936](https://user-images.githubusercontent.com/32963903/60454320-29dacd00-9c51-11e9-9f54-784e5b929827.png)
![Screenshot (15)_LI1](https://user-images.githubusercontent.com/32963903/60454785-665af880-9c52-11e9-9965-ee96f28c0984.jpg)

There is a difference of **atleast 5 sec** from data send (client side) to received (server side) and this **difference goes on increasing with time.**

HOW CAN I RESOLVE THE PROBLEM ??

**Comment by miguelgrinberg** [comment]
I don't have any benchmarks for eventlet under Windows, it could be that it's just not efficient on that platform, or maybe it's the fact that you are sending such large messages. The websocket implementation comes from eventlet, so I'm not really sure how I can help. I suggest you try other supported frameworks to try to characterize this problem better. You can also try running long-polling under eventlet to see if the performance is the same as with websocket.

**Comment by HimanshuSharma789** [comment]
> maybe it's the fact that you are sending such large messages. 

**The size of each data from is in Bytes.**
I don't think the size of message would be a problem for the delay.

![image](https://user-images.githubusercontent.com/32963903/60462018-d6bf4500-9c65-11e9-845a-bc2ea5c2aef5.png)


> try other supported framework

**Could you be more specific about the frameworks...?**
I don't have much experience in flask or flask-socketio.

_Little help would be great...._

**Comment by miguelgrinberg** [comment]
@HimanshuSharma789 sorry looks like I dropped the ball on this.

What I meant by other frameworks is to switch to something other than eventlet. The next logical choice would be to use gevent, which is a fairly similar network.
