### ISSUE TITLE
utf-8 problems again

### ISSUE THREAD

**Issue by arduinka55055** [miguelgrinberg/Flask-SocketIO#1018]

**Comment by arduinka55055** [comment]
server.py
`from flask import Flask, render_template
from flask_socketio import SocketIO
app = Flask(__name__)
hostIP='localhost'
socketio = SocketIO(app)

@socketio.on('my event')
def newRoom(json, methods=['GET', 'POST']):
    print('received my event: ' + json['name'])
    socketio.emit('my response', json)
@app.route('/' ,methods=['GET', 'POST'])
def index():
    return render_template('index.html')
if __name__ == '__main__':
    socketio.run(app, debug=True, host=hostIP,port=80)
`

index.html page:
`<!DOCTYPE html>
<html>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.7.3/socket.io.min.js"></script>
</head>
<body>
    <script>
        var socket = io.connect('http://' + document.domain + ':' + location.port);
        var testing='йцукен' //i am using russian letters
        socket.emit( 'my event', {name: testing,hello: 'hello world'} )
        socket.on( 'my response', function( msg ) {
        console.log( msg )
        })
    </script>
</body>
</html>`


at server console: received my event: Ð¹ÑÑÐºÐµÐ½
as mozilla console Object { name: "Ð¹Ñ\u0086Ñ\u0083ÐºÐµÐ½", hello: "hello world" }

**Comment by arduinka55055** [comment]
[test.zip](https://github.com/miguelgrinberg/Flask-SocketIO/files/3362793/test.zip)
my files.
flask-socketio version is 4.1.0

**Comment by arduinka55055** [comment]
i have fixed this problem:
at python side:
json_str = json['name'].encode('latin-1').decode('utf-8')
print('received my event: ' + json_str) 

at client side:
socket.on( 'my response', function( msg ) {
console.log(decodeURIComponent(escape(msg['name'])) )
})

simple magic with encoding and decoding )

**Comment by miguelgrinberg** [comment]
It seems your client is sending the russian string encoded as latin-1. Try using utf-8 encoding on your client.

**Comment by arduinka55055** [comment]
but i wrote <meta charset='UTF-8'> very strange
but problem is solved
i hope that this post will be useful to others
