### ISSUE TITLE
FLASK SOCKET-IO CONCURRENCY 

### ISSUE THREAD

**Issue by chandu7077** [miguelgrinberg/Flask-SocketIO#1019]

**Comment by chandu7077** [comment]
I am writing a small chat server where clients will be sending their messages to admin dashboard , a customer support kind of application and admin will select user and sends them the reply

I am using socket-io in flask so does it scale to as many users as requests come?

**Comment by miguelgrinberg** [comment]
> so does it scale to as many users as requests come?

Nothing can scale without limits, there's always going to be a limit. But when you reach that limit you can scale horizontally by adding more servers.

> if many users hit the send button then all users emit the message at same time so is server be able to get all the messages

This is impossible for me to say. The server will get all the messages, but what you do to handle each messages will determine how fast messages are handled.

**Comment by chandu7077** [comment]
I just store them in redis and in mysql db through sqlalchemy and now i am getting 400 bad request after 6 connections opened in browser on seventh connection the browser loads slowly and other six tabs which were opened get 400 bad request error I don't know whether its client issue in javascript or there is issue with my flask code

**Comment by chandu7077** [comment]
![Screenshot from 2019-07-06 12-41-42](https://user-images.githubusercontent.com/26523052/60753089-83dde880-9feb-11e9-91ad-9f88619b2faf.png)

**Comment by miguelgrinberg** [comment]
Enable logs in the server and then you will probably have more clues as to the reason of the failure. To enable logs add `logger=True, engineio_logger=True` to your `SocketIO()` constructor.

**Comment by chandu7077** [comment]
yeah I'll enable them please check my edited query?

**Comment by miguelgrinberg** [comment]
Maybe. Isn't it easier to try using multiple browsers than to ask me?

**Comment by chandu7077** [comment]
yeah that's the problem when I open in mozilla it was working fine and thank you for quick reply.
your answers have been always helpful
