### ISSUE TITLE
bdb.BdbQuit when debugging Flask app that uses Flask-SocketIO 

### ISSUE THREAD

**Issue by DevAerial** [miguelgrinberg/Flask-SocketIO#1020]
Not sure if it is problem of Flask-SocketIO. But when I'm trying to set a breakpoint in socketio endpoint or generally in any place in my app I recieve `bdb.BdbQuit` exception. This problem I already submitted to [SO](https://stackoverflow.com/questions/56656254/bdb-bdbquit-raises-when-using-pdb-in-flask-app-running-on-uwsgi-server) quite a time ago, but didn't recieve any answer. Is there any way to make python debugger work with Flask-SocketIO under gevent? Sorry, if this probelm is offtop.

**Comment by miguelgrinberg** [comment]
In general Python debuggers do not directly work with gevent or eventlet. I do not know if the bdb functions are compatible. Both PyCharm and VS Code have an option to enable gevent/eventlet support.
