### ISSUE TITLE
problem using ssl Cert

### ISSUE THREAD

**Issue by anagnostouJohn** [miguelgrinberg/Flask-SocketIO#1021]
I am using flask-socketio to serve a webpage. at the run field i a putting the certificates like this 
`socketio.run(app, debug=True, keyfile='key.key', certfile='cert.cert')`

The server starting but when i want to connect to interface i am taking the following message 
`ssl.SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:2292)`

furthermore from the browser (firefox) i am taking that message
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:5000/socket.io/?EIO=3&transport=polling&t=MlsiDhX. (Reason: CORS request did not succeed).`

those two issues are related? what i have to do?

**Comment by miguelgrinberg** [comment]
I would start by removing the SSL and determine if there are any other issues.

**Comment by anagnostouJohn** [comment]
If I remove ssl certificates everything works just fine.

**Comment by miguelgrinberg** [comment]
Why does the CORS error say `http://...` and not `https://...`? Any chance you are trying to connect over http by mistake?

**Comment by anagnostouJohn** [comment]
No I use https to connect to app. Is there any way to use anything else such as regular socketio or something else in order to achieve secured connection?

**Comment by miguelgrinberg** [comment]
If you are using https:// then why is the browser saying that you used http:// in the error message? That seems like a good clue that is related to your problem, so we need to understand what's going on there.
