### ISSUE TITLE
Flask SocketIo with RestAPI,Celery, RabbitMQ and Webhook

### ISSUE THREAD

**Issue by punit-anvaya** [miguelgrinberg/Flask-SocketIO#1023]
Am creating a flask app in which I have some rest APIs' and a webhook which passes the data to rabbitmq, then it is processed by celery. I have to pass the result of celery to my socket to generate realtime report. 
I want to know how to pass celery task to the socket as it's not called by my socket( calling it through webhook) as return it to socket.

**Comment by miguelgrinberg** [comment]
What you want to do is covered in the documentation: https://flask-socketio.readthedocs.io/en/latest/#emitting-from-an-external-process

**Comment by punit-anvaya** [comment]
I tried that and saw some example also, but all of them were calling the celery task from socket `celery_method_name.delay(args)` and then in celery task they are emitting the response.

But in my case, whenever webhook is called am sending that data to rabbitmq and then from that queue am running a celery process. So, this celery task is not defined in any socket event. but i have to return the result of that celery event to socket event on connect.

**Comment by miguelgrinberg** [comment]
Do you have a Socket.IO server running on your Flask app?

**Comment by punit-anvaya** [comment]
yes

**Comment by miguelgrinberg** [comment]
Then what I suggested is no different than your case. Your Celery worker can emit through the Socket.IO server in your main process as explained in the documentation link I sent above.
