### ISSUE TITLE
Decorators not registering with application

### ISSUE THREAD

**Issue by jreneew2** [miguelgrinberg/Flask-SocketIO#1026]
Hi,

I am trying to make a basic web application in Flask and I am trying to get the sample code working and integrated with my code. The issue is that my functions attached to the decorators are not working. I can see the debug events receiving the messages with the correct data, but I can't seem to print anything in the function below the decorator.

Here is the log from the event recieved:
`e38d65b85f2e4678bb84f83eca0cc500: Received packet MESSAGE data 2["my_event",{"data":"i am sending a msg"}]` 

Here is a link to my code:
https://github.com/jreneew2/mc_remote_console

**Comment by miguelgrinberg** [comment]
You are creating two applications in run.py.

First you initialize `SocketIO` passing `app`, which is an empty Flask. Then you run the server by passing the result of `create_app()`, which makes a different application instance.

**Comment by jreneew2** [comment]
Thanks for the help! I appreciate it, however now I am running into an issue where it cant find async_mode.

Here is what I have now:


    app = Flask(__name__)
    db = SQLAlchemy()
    socketio = SocketIO()

    def create_app():
        app.config['SECRET_KEY'] = '9f7b0dbc7661286b52531592'
        app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///db.sqlite'

    socketio.init_app(app)

    db.init_app(app)

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)


    # blueprint for auth routes in our app
    from auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    # blueprint for non-auth parts of app
    from main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from models import User
    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    socketio.run(app, debug=True)


However, it seems that when I load /profile, it says that socketio doesnt have async_mode as an attribute.

**Comment by jreneew2** [comment]
What I ended having was some issues with my routing... Thanks for the help again!
