### ISSUE TITLE
Heroku: You need to use gevent-socketio server

### ISSUE THREAD

**Issue by SebastienGllmt** [miguelgrinberg/Flask-SocketIO#103]
I have a program that uses Flask-SocketIO. 
It <b>works</b> when I run it locally on localhost
It <b>doesn't work</b> when I deploy my code to Heroku.

Here is a link to my repository: https://github.com/SebastienGllmt/Niteruka
Here is the error
```
Mar 30 02:33:14 niteruka heroku/router: at=info method=GET path="/?gameID=3dbdbe48-5cc8-4b8c-a4b8-6931d925f40b" host=niteruka.herokuapp.com request_id=7a0f57d9-1718-42d2-a22d-9751ec616183 fwd="64.180.190.118" dyno=web.1 connect=0ms service=3ms status=200 bytes=2126
Mar 30 02:33:15 niteruka heroku/router: at=info method=GET path="/socket.io/1/?t=1427707991121" host=niteruka.herokuapp.com request_id=047f05cf-8439-4681-a91c-97c5506d0589 fwd="64.180.190.118" dyno=web.1 connect=4ms service=2ms status=500 bytes=238
Mar 30 02:33:15 niteruka app/web.1: 2015-03-30 09:33:14 [9] [ERROR] Error handling request
Mar 30 02:33:15 niteruka app/web.1: Traceback (most recent call last):
Mar 30 02:33:15 niteruka app/web.1:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
Mar 30 02:33:15 niteruka app/web.1:     respiter = self.wsgi(environ, resp.start_response)
Mar 30 02:33:15 niteruka app/web.1:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
Mar 30 02:33:15 niteruka app/web.1:     return self.wsgi_app(environ, start_response)
Mar 30 02:33:15 niteruka app/web.1:   File "/app/.heroku/python/lib/python2.7/site-packages/flask_socketio/__init__.py", line 27, in __call__
Mar 30 02:33:15 niteruka app/web.1:     raise RuntimeError('You need to use a gevent-socketio server.')
Mar 30 02:33:15 niteruka app/web.1: RuntimeError: You need to use a gevent-socketio server. 
```

Note that I do launch my app through appmain.socketio.run inside main and that this app works when locally both on my laptop and on my desktop.

The app in its current state should work kind of like a chat client, where you create a chat room, then send the links to your friend. Once both in the chatroom, a person can input a message and when they send it, web sockets are used to emit the message to others in the same room.

Instructions for setup and launching are located inside my repository.

**Comment by miguelgrinberg** [comment]
Under Heroku your application will be executed using the command given in the Procfile. You need to update that command to run the gevent-socketio server, it is currently running the standard WSGI server.

See the docs for how to start a socketio app using gunicorn.

**Comment by SebastienGllmt** [comment]
Yes, thank you that was the issue. For those who run into this issue, look into the "Deployment" section of the docs under the section about gunicorn.

**Comment by Herant** [comment]
After struggeling with this for a few days i can confirm that in order for flask-socketio to work on heroku you need eventlet, which means that Procfile: **gunicorn --worker-class eventlet -w 1 name_of_your:app**

**Comment by Full-Stack-dev410** [comment]
web: gunicorn --worker-class eventlet -w 1 app:app
