### ISSUE TITLE
New flask break websockets?

### ISSUE THREAD

**Issue by drensin** [miguelgrinberg/Flask-SocketIO#1030]
I have an application that I host behind a cloud loadbalancer (GCLB on Google Cloud, to be specific.)  It has been working for weeks.  Today, I upgraded the flask-socketio version from 4.1 to 4.2.  Now, my client gets a:

index.js:83 WebSocket connection to 'wss://remixatron.dkrdomain.com/socket.io/?EIO=3&transport=websocket&sid=2dccf1f7c55143978358ca392435ba46' failed: WebSocket is closed before the connection is established.

and cannot connect to my server.  The server runs on regular HTTP on port 8000 behind the load balancer. The LB is terminating the HTTPS requests and passing requests back as HTTP. There are no errors being thrown for @socketio.on_error_default AFICT.

Rolling back to flask-socketio 4.1 fixes this.

**Comment by gil0109** [comment]
Are's is broken as well.

Request URL: wss://dev-theq.pathfinder.gov.bc.ca/api/v1/socket.io/?EIO=3&transport=websocket
Request Method: GET
Status Code: 400 BAD REQUEST

The strange this is we revert to 4.1.0, it still breaks as the dependencies seem to also be upgraded (I think)

httplib2=0.13.1
importlib-metadata==0.19
pyristent==0.15.4
python-engineio==3.9.0
python-socketio==4.3.0

**Comment by miguelgrinberg** [comment]
Okay, version 4.2 of Flask-SocketIO addresses a security issue, which requires you to set up CORS properly if you need cross-origin access. So basically your options are to downgrade python-engineio to 3.8.2 and then you will be fine, but with the security issue, or else upgrade, but then you need to configure CORS to allow your origin(s) to connect.

**Comment by drensin** [comment]
ah. ok. that fixed it, thank you.  For everyone else, the line you're looking for is something like:

socketio = SocketIO(app, cors_allowed_origins=['https://host.yourdomain.com','http://localhost'])
