### ISSUE TITLE
Handler function not sending returned values as arguments to client callback

### ISSUE THREAD

**Issue by avocadoras** [miguelgrinberg/Flask-SocketIO#1032]
https://flask-socketio.readthedocs.io/en/latest/#receiving-messages
says
...

> Clients may request an acknowledgement callback that confirms receipt of a message they sent. Any values returned from the handler function will be passed to the client as arguments in the callback function:
> ```
> @socketio.on('my event')
> def handle_my_custom_event(json):
>     print('received json: ' + str(json))
>     return 'one', 2
> ```
> In the above example, the client callback function will be invoked with two arguments, 'one' and 2. If a handler function does not return any values, the client callback function will be invoked without arguments.

What I understand is that, let's say, I'll have available `'one'` and `2` as arguments inside the client callback like
```javascript
socket.on('my event', (firstReturnedValue, secondReturnedValue) =>  {
...
});
```
where `firstReturnedValue` binds to `'one'` and `secondReturnedValue` binds to `2`.

I've written:
```python
@socketio.on('connect')
@authenticated_only
def handle_connect():
    """Set up user log in."""
    #  Return a value that gets handled in client callback indicating connection
    return session['username'], list(live_channels), "you're ready to chat!"
```

and on the client I have this
```javascript
  const socket = io.connect(location.protocol + '//' + document.domain + ':' + location.port);
  // Ask user to identiy yourself
  // if(!localStorage.getItem("username")) {
  //   const mainRow = document.querySelector("#main-row");
  //   setUsernameForm(mainRow, socket);
  // }

  // When connected, configure buttons
  socket.on('connect', (username, channels, message) => {

    console.log(username);
    console.log(channels);
    console.log(message);
....
}
```
But in the browser's console prints `undefined`.
![Screenshot from 2019-08-02 12-12-18](https://user-images.githubusercontent.com/36335687/62390172-d7762000-b51e-11e9-8bd1-7edfee1f0c2b.png)

 Am I misunderstanding this?
> Any values returned from the handler function will be passed to the client as arguments in the callback function

**Comment by miguelgrinberg** [comment]
No, that's not how this works.

First of all, the `connect` and `disconnect` events are not part of callbacks, so set those aside. This only applies to regular events.

The idea is that when one side emits an event to the other, it can get a completion callback. For example, here is a JS client side snippets that emits an event called `my event` and configures a callback:

```javascript
    socket.emit('my event', {'foo': 'bar'}, (first, second) => {
        // here first == 'one' and second == 2
    });
```

This emit will trigger the server handler to run:

```python
@socketio.on('my event')
def my_event(data):
    # here data == {"foo': "bar"}
    # the values that are returned will be sent to the client's callback
    return "one", 2
```

Hope this makes sense!

**Comment by avocadoras** [comment]
Thanks for the clarification
