### ISSUE TITLE
message handler error when run app

### ISSUE THREAD

**Issue by cankai** [miguelgrinberg/Flask-SocketIO#1036]
I am using socketio in my Flask project,
I run the app by: gunicorn -b 0.0.0.0:5000 --worker-class eventlet -w 1 manage:app
and my versions is:
Python 3.6.8
flask_socketio 4.2.1
I had set the engineio_logger=True
where I use  nginx as a proxy, It runs ok,
the nginx config is:
location /api/socket.io {
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_http_version 1.1;
            proxy_buffering off;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_pass http://127.0.0.1:5000/socket.io;
        }
but when I use the same config in nginx vhost(the vhost run at port 8000)
It runs error,  and the message is:
4bd3b2b45fe04569a2e8838a02f351c7: Sending packet OPEN data {'sid': '4bd3b2b45fe04569a2e8838a02f351c7', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
4bd3b2b45fe04569a2e8838a02f351c7: Sending packet MESSAGE data 0
4bd3b2b45fe04569a2e8838a02f351c7: Received packet MESSAGE data 0:8000
message handler error
Traceback (most recent call last):
  File "/data/apps/venv/lib/python3.6/site-packages/engineio/server.py", line 535, in _trigger_event
    return self.handlers[event](*args)
  File "/data/apps/venv/lib/python3.6/site-packages/socketio/server.py", line 703, in _handle_eio_message
    pkt = packet.Packet(encoded_packet=data)
  File "/data/apps/venv/lib/python3.6/site-packages/socketio/packet.py", line 43, in __init__
    self.attachment_count = self.decode(encoded_packet)
  File "/data/apps/venv/lib/python3.6/site-packages/socketio/packet.py", line 113, in decode
    self.data = self.json.loads(ep)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
4bd3b2b45fe04569a2e8838a02f351c7: Received request to upgrade to websocket
4bd3b2b45fe04569a2e8838a02f351c7: Upgrade to websocket successful
4bd3b2b45fe04569a2e8838a02f351c7: Received packet PING data None
4bd3b2b45fe04569a2e8838a02f351c7: Sending packet PONG data None

the js client is:
namespace = '/pop';
url_path = "/api/socket.io"
var socket = io.connect('http://' + location.host + ":8000" + namespace, {path: url_path});

the chrome debug info is:
![sock](https://user-images.githubusercontent.com/8059643/62940663-a511d000-be06-11e9-9ba7-aa1b47accbd5.PNG)

**Comment by miguelgrinberg** [comment]
What do you mean exactly by:

> but when I use the same config in nginx vhost(the vhost run at port 8000)

You haven't provided the details of this configuration.

**Comment by cankai** [comment]
my nginx vhost configuration is:
server {
    root /data/web_data;
    location /api/socket.io {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass http://127.0.0.1:5000/socket.io;
    }
}

**Comment by cankai** [comment]
I had modify my client code from 
var socket = io.connect(location.protocol + '//' + location.host + ':' + location.port + namespace, {path: url_path});
to 
var socket = io.connect(location.protocol + '//' + document.domain + ':' + location.port + namespace, {path: url_path});
and It runs ok now. thanks a lot.
