### ISSUE TITLE
connection refreshing automatically after emit event from Flask server. 

### ISSUE THREAD

**Issue by AkshayKumar007** [miguelgrinberg/Flask-SocketIO#1037]
I'm trying to create a simple chatroom style application with Flask and Flask-SocketIO. When users type messages and click 'submit' (submitting a form in html), it should create an unordered list of messages. The problem I'm facing is the message gets appended as list item but then after few seconds it disappears(it appears as though connection is refreshed). I want to turn off this behavior. Thanks in advance. :smile: 

Here is code snippet :

Flask:
```
@socketio.on('send messages')
def vote(data):
    messages = data['messages']
    emit('announce messages', {"messages":messages}, broadcast=True)
```
 
JavaScript:
```
document.addEventListener('DOMContentLoaded', () => {

    // Connect to websocket
    var socket = io.connect(location.protocol + '//' + document.domain + ':' + location.port);

    // When connected
    socket.on('connect', () => {
        document.querySelector('#form').onsubmit = () => {
            const messages = document.querySelector('#messages').value;
            socket.emit('send messages', {'messages': messages});
            return false;
        }
    });

    socket.on('announce messages', data => {
        const li = document.createElement('li');
        li.innerHTML = `${data.messages}`;
        document.querySelector('#push').append(li);
        return false;
    });    
});

```

**Comment by miguelgrinberg** [comment]
You will need to debug this and find out why the connection is interrupted (or whatever else is happening). There is nothing in the partial code snippets you provided that can help with that.

The server can log more data if you enable verbose logging. Add `logger=True, engineio_logger=True` to the `SocketIO()` constructor to turn that on.

**Comment by AkshayKumar007** [comment]
I found the solution. I just needed to add 'return false' in both event listeners. Nothing related to Flask-SocketIO. Thanks for responding btw.
