### ISSUE TITLE
flask_socketio not receiving messages from client

### ISSUE THREAD

**Issue by bchr73** [miguelgrinberg/Flask-SocketIO#1038]
I have a Flask server-app/React client-app into which I am trying to integrate flask_socketio. I have replicated the standard introductory example from the flask_socketio docs and it works fine with my React front-end. 

However, when I try to replicate the results in flask, using the exact same steps I cannot send or receive messages. I can see a client has connected in the output when I run my flask app, and in the browser console I have a console.log telling me I am connected to the server, but emit (or send) don't seem to work the way the intro example did. 

I have eventlet installed, and the docs say that flask_socketio should recognize this automatically. Here are some code snippets for reference. 

app/socket/__ init __.py
```python

from flask_socketio import SocketIO

socketio = SocketIO(cors_allowed_origins='http://localhost:3000')

```

app/socket/socket.py
```python

from flask_cors import cross_origin
from flask_socketio import send, emit

from . import socketio

@cross_origin
@socketio.on('connect')
def handle_connection():
    print('a user has connected')
    emit('mymessage', 'Hi client, I am server.') # I've tried `send` here too

@cross_origin
@socketio.on('mymessage')
def handle_message(message):
    print('Message from client: ' + message)
```
app/__ init __.py
```python
from flask import Flask
from flask_cors import CORS

from .socket import socketio


def create_app():
    app = Flask(__name__)

    # Cross Origin Resource Sharing
    CORS(app)

    # Socket.IO
    socketio.init_app(app)


    return (socketio, app)
```

app/app.py
```python

from . import create_app

socketio, app = create_app()

if __name__ == '__main__':
    socketio.run(app, host='localhost', port=5000)
    #app.run("0.0.0.0", port=5000, threaded=True, use_reloader=False)
```

React component
```javascript
const socket = io('http://localhost:5000');

class Figures extends React.Component {

  setSocketListeners () {

    socket.on('connect', () => {
      console.log('connected to socket');
      socket.emit('mymessage', 'Hi server, I am client.');
    })

    socket.on('mymessage', function(data) {
      console.log('Message from server: ' + data)
    })
  }

  componentDidMount() {
    this.setSocketListeners()
  }

...
```

Output:

terminal
```python
Server initialized for eventlet.
server starting on localhost:5000
 * Restarting with stat
Server initialized for eventlet.
server starting on localhost:5000
 * Debugger is active!
 * Debugger PIN: 216-814-307
(22037) wsgi starting up on http://[::1]:5000
(22037) accepted ('::1', 42946, 0, 0)
2de3ca98c4834994be88b383b6df5318: Sending packet OPEN data {'sid': '2de3ca98c4834994be88b383b6df5318', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
2de3ca98c4834994be88b383b6df5318: Sending packet MESSAGE data 0
::1 - - [14/Aug/2019 04:49:34] "GET /socket.io/?EIO=3&transport=polling&t=MoFKM-E HTTP/1.1" 200 401 0.002470
(22037) accepted ('::1', 42948, 0, 0)
2de3ca98c4834994be88b383b6df5318: Received request to upgrade to websocket
2de3ca98c4834994be88b383b6df5318: Received packet MESSAGE data 2["mymessage","Hi server, I am client."]
(22037) accepted ('::1', 42950, 0, 0)
::1 - - [14/Aug/2019 04:49:34] "POST /socket.io/?EIO=3&transport=polling&t=MoFKM-e&sid=2de3ca98c4834994be88b383b6df5318 HTTP/1.1" 200 219 0.002086
::1 - - [14/Aug/2019 04:49:34] "GET /socket.io/?EIO=3&transport=polling&t=MoFKM-i&sid=2de3ca98c4834994be88b383b6df5318 HTTP/1.1" 200 235 0.013794
2de3ca98c4834994be88b383b6df5318: Upgrade to websocket successful
2de3ca98c4834994be88b383b6df5318: Received packet PING data None
2de3ca98c4834994be88b383b6df5318: Sending packet PONG data None
2de3ca98c4834994be88b383b6df5318: Received packet PING data None
```
browser
```javascript
connected to socket
```

EDIT:

Preliminary debugging seems to suggest this is some issue with 'create_app()'. See [link][1] from @miguelgrinberg. Still no progress on how to fix the issue though.

Have enabled ```socketio.init_app(app, async_mode="eventlet", engineio_logger=True)``` and disabled debugging in flask to make sure werkzeug isn't being used. 

  [1]: https://github.com/miguelgrinberg/Flask-SocketIO/issues/731

**Comment by miguelgrinberg** [comment]
My guess is that you have two `socketio` objects in your application. You are registering the event handlers on one of them, but then starting the web server with the other.

Also, Flask-Cors has nothing to do with Flask-SocketIO, so the cors decorators should not be applied to event handlers.

**Comment by bchr73** [comment]
Noted.
> Also, Flask-Cors has nothing to do with Flask-SocketIO, so the cors decorators should not be applied to event handlers.

Maybe I'm missing something obvious, but it works using the following project structure:
```bash
test_socketio/
├── application/
│   ├── __init__.py    <---- 'socketio = SocketIO()'
│   └── socket.py      <---- 'from . import socketio'
└── socketio_test.py   <---- 'from application import socketio'
```
But not this...
```bash
test_socketio/
├── application/
│   ├── sockets/
│   │   ├── __init__.py    <---- 'socketio = SocketIO()'
│   │   └── socket.py      <---- 'from . import socketio'
│   └── __init__.py
└── socketio_test.py       <---- 'from application.sockets import socketio'
```
Also, I'm only instantiating ```socketio = SocketIO()``` one time. Outside my 'create_app' declaration. How can I have two instances? It's the same code as [#279](https://github.com/miguelgrinberg/Flask-SocketIO/issues/279).

**Comment by miguelgrinberg** [comment]
The structure is not the problem, there's got to be something else that is wrong there. Actually, are you importing application.sockets.socket? If you don't import the module, then your events would never be registered.

**Comment by bchr73** [comment]
This was the issue. I was importing 'socketio' from 'sockets/' but I wasn't importing 'sockets/socket.py' from 'sockets/__init__.py'.

Thank you. So it was something simple.
