### ISSUE TITLE
Client Receiving 400 error

### ISSUE THREAD

**Issue by Shamim56** [miguelgrinberg/Flask-SocketIO#1039]
Hello, 

I setup a very simple flask-socketio script to test. This is purely in a development environment and theres no reverse proxy like apache/nginx/etc or ssl. I have installed eventlet on my computer for it to use

```python
from flask import Flask, jsonify, request
from flask_socketio import SocketIO, emit

HOST = '0.0.0.0'
PORT = 7000

app = Flask(__name__)
app.config['SECRET_KEY'] = 'fjsalfj'
socketio = SocketIO(app)

notifications_feed = {}

@socketio.on('connect', namespace='/notifications')
def notifications_on_connect():
    notifications_feed[request.sid] = request.args['username']
    
@socketio.on('disconnect', namespace='/notifications')
def notifications_on_disconnect():
    notifications_feed.pop(request.sid, None)
    
if __name__ == '__main__':
	socketio.run(app, port=PORT, host=HOST)
```

and on my client nodejs application i have

```javascript
this.webSocket = io('localhost:7000/notifications', { transports: ['websocket'], query: {username: 'Test User'}});
this.webSocket.on('citations', (msg: any) => {
	console.log(msg);
});
```

Here is the request
![Screen Shot 2019-08-14 at 11 07 40 AM](https://user-images.githubusercontent.com/15659316/63032563-0d52c700-be84-11e9-9922-d0a4c3e11d8a.png)

The really weird part is that it works only **one** of my development computers -- but every single other computer i have tried it on receives this error in their development environment. I install eventlet, flask-socketio, flask - im not sure if i am missing something here?

**Comment by miguelgrinberg** [comment]
How many workers are you running? You should be running a single worker.

You can enable logging to see more details about the error. Add `engineio_logger=True` to your `SocketIO` object constructor.

**Comment by Shamim56** [comment]
I added the param to the contructor, now whenever the client attempts to connnect I receive the error 

'localhost:4200 is not an accepted origin'

I thought it should automatically allow other origins though

**Comment by Shamim56** [comment]
I got it fixed!  seems like a versioning issue - this is what worked on my end

python-engineio v.3.7.0
python-socketio v.4.0.3
flask-socketio v.4.0.0

This is what the other computers were automatically installing that were causing the error

python-engineio v.3.9.3
python-socketio v.4.3.1
flask-socketio v.4.2.1

**Comment by Shamim56** [comment]
Thank you for your help!

**Comment by miguelgrinberg** [comment]
@Shamim56 the solution you copied from the forum is not the best, sadly.

If you are going to work with cross-origin, it is best to explicitly declare the origins that your server intends to support. What you are doing is downgrading to an older version of the packages, so you will be missing out on upgrades and improvements.

**Comment by Shamim56** [comment]
I got it working in the most recent versions by setting 

```python
cors_allowed_origins="*"
```

how would i specify multiple domains? such as
localhost, localhost:4200, e.g.?

**Comment by miguelgrinberg** [comment]
Like this:

    cors_allowed_origins=["http://localhost", "http://localhost:4200"]

Using `'*'` sends you back to the insecure versions, don't use that unless it is for testing or internal apps.
