### ISSUE TITLE
v1.3.5

### ISSUE THREAD

**Issue by jaredmcqueen** [miguelgrinberg/Flask-SocketIO#104]
Miguel,
Great flask extension -- I've done a little searching but haven't been able to determine if your extension supports v1.3.5.  If not, is it on the roadmap?  Thanks!

**Comment by jaredmcqueen** [comment]
nevermind... see it here:

The 1.x releases of the Socket.IO client-side Javascript libraries are not compatible with project gevent-socketio. At this time the Socket.IO client release 0.9.16 has been found to be the most stable.

So my next question:  do you plan on supporting 1.x releases going forward?  Thanks!

**Comment by jquacinella** [comment]
+1 this. Would be willing to lend a hand in finding out wha the issues are (it seems like at a minimum, the new client libraries use a new URL setup)

**Comment by jaredmcqueen** [comment]
I could help as well

**Comment by miguelgrinberg** [comment]
The protocol details for Socket.IO are handled by gevent-socketio, which hasn't received much attention lately. That project would need to be updated to the 1.x Socket.IO protocol, or else I can also replace it with a different project that speaks Socket.IO 1.x. My understanding is that this isn't a trivial effort. I may look into this myself, given that the gevent-socketio mantainers do not seem to be planning to make this upgrade.

**Comment by jquacinella** [comment]
Looks like you are correct, esp referencing https://github.com/abourget/gevent-socketio/issues/192. According to that, it looks like you are right that it is not so simple. Maybe it makes sense to rewrite it from scratch? This might be above my abilities but I can certainly try to help :)

**Comment by miguelgrinberg** [comment]
Development release 1.0a1 has support for post 1.0 Socket.IO releases, using a new set of dependencies (authored by myself).

Closing this issue.
