### ISSUE TITLE
Messages are being queued and being sent only when the server returns a 200 response.

### ISSUE THREAD

**Issue by sajil13** [miguelgrinberg/Flask-SocketIO#1042]
I am working on a chat platform and I am using flask_socketio for that.
I am able to receive the messages on the chat interface just fine, but when there are more than one messages instead of sending the messages one by one. It sends all the three messages in a go.

After carefully looking into the issue it seems like the messages are being queued and only being sent once a 200 response is sent from the server.

**Comment by miguelgrinberg** [comment]
I'm confused about this, you need to give more details please. An example application that shows the problem would help.
