### ISSUE TITLE
Websockets fail when using multiple upstream proxies

### ISSUE THREAD

**Issue by dank69** [miguelgrinberg/Flask-SocketIO#1043]
I have a setup which makes use of `Flask-SocketIO`  behind 2 reverse nginx proxies. One proxy is at my "gateway" and acts as a generic forwarder, forwarding traffic upstream to a number of different web services. One of these web services is making use of the `Flask-SocketIO` package.

The relevant configuration at the gateway is as follows (you can see from the comments configuration options I have tried to resolve this issue):
```
   	location /socket.io {	    
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

      	    proxy_http_version 1.1;
      	    proxy_set_header Upgrade $http_upgrade;
      	    proxy_set_header Connection "Upgrade";
	    
            #proxy_buffering off;
            #proxy_redirect off;
            #proxy_buffers 8 32k;
            #proxy_connect_timeout 300;
            #proxy_request_buffering off;
      	    #proxy_read_timeout 86400;
            #tcp_nodelay on;
           
            #proxy_pass http://portal/socket.io;
            proxy_pass http://portal:5000/socket.io;
   	}
```
As can be seen, the `socket.io` traffic is being passed to the portal. The portal has the following configuration (making use of `uwsgi` and `nginx` to run the `Flask` application):
```
[program:uwsgi]
command=/usr/bin/uwsgi --http :5000 --wsgi-file run.py --callable app --master --gevent 1000 --http-websockets --vacuum --thunder-lock --single-interpreter --processes=1 --threads=1

[program:nginx]
command=/usr/sbin/nginx -c /etc/nginx/nginx.conf
```
The relevant `nginx` configuration of the portal:
```
        location /socket.io {
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

      	    proxy_http_version 1.1;
      	    proxy_set_header Upgrade $http_upgrade;
      	    proxy_set_header Connection "Upgrade";
            proxy_pass http://127.0.0.1:5000/socket.io;
        }
```
When I pass requests from the forwarder directly to the `uwsgi` service on port 5000, the socket connection works as expected. However, if I pass the requests from the forwarder to `nginx` on port 80 (which I want to do, so I can make use of aliases to serve static files), I receive 400 errors in my browser which I am struggling to debug (there is nothing relevant in the `error.log` files on either the forwarder or the portal):
```
WebSocket connection to 'wss://mysite.com/socket.io/?EIO=3&transport=websocket&sid=071292dfc86e4a6aa0686afe30958898' failed: Error during WebSocket handshake: Unexpected response code: 400
index.js:83 POST https://mysite.com/socket.io/?EIO=3&transport=polling&t=Mof2B5R&sid=071292dfc86e4a6aa0686afe30958898 400 (BAD REQUEST)
```

Does anybody have any experience or ideas on what could be causing this issue/how to resolve it?

**Comment by miguelgrinberg** [comment]
You can try enabling Socket.IO debug logs, maybe you can find something useful there. Just add a `engineio_logger=True` argument to your `SocketIO` object.

**Comment by dank69** [comment]
Thanks Miguel!

When running with the debug output, there is an error which stands out:
```
43c2f4ca080f476992c2b9588c7054a3: Sending packet MESSAGE data 0
https://mysite.com is not an accepted origin.
```

I expect this is because the `socket.io` connection is going via the forwarder to the portal and the origin therefore changes?

I tried to fix this on the `Flask` side (but probably also possible to fix from `nginx`), by changing the CORS settings based on the docs:
`socketio.init_app(app, manage_session=True, cors_allowed_origins="*")`

However, when running I receive a new error stating that the `HTTP_ORIGIN` key cannot be found (even though the origin is stated as a non-accepted origin in the error):
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask_socketio/__init__.py", line 44, in __call__
    start_response)
  File "/usr/lib/python2.7/site-packages/engineio/middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/usr/lib/python2.7/site-packages/socketio/server.py", line 428, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/usr/lib/python2.7/site-packages/engineio/server.py", line 411, in handle_request
    cors_headers = self._cors_headers(environ)
  File "/usr/lib/python2.7/site-packages/engineio/server.py", line 610, in _cors_headers
    headers = [('Access-Control-Allow-Origin', environ['HTTP_ORIGIN'])]
KeyError: 'HTTP_ORIGIN'
```

Do you have any suggestions for what's going wrong now?

**Comment by miguelgrinberg** [comment]
@dank69 Yes, this is a bug that's been fixed. Upgrade Flask-SocketIO, python-socketio and python-engineio to their latest versions.

**Comment by dank69** [comment]
Perfect, thanks this has fixed my issue.

For anyone else facing this issue, ensure you have at least the following libraries installed:
```
Flask-SocketIO==4.2.1
python-socketio==4.3.1
python-engineio==3.9.3
```

The 400 error fix (from the `Flask` perspective):
```
socketio = SocketIO()
socketio.init_app(app, manage_session=True, cors_allowed_origins="https://mysite.com")
```
