### ISSUE TITLE
Integration with Azure web app

### ISSUE THREAD

**Issue by TzlilClone** [miguelgrinberg/Flask-SocketIO#1044]
Hi,
I am trying to run flask with Flask-SocketIO on Azure webapp.
I am trying to use that command:
gunicorn --worker-class eventlet -w 1 module:app

but the error log says that 'module' is not recognised

can you please explain what is 'module:app'?

Thanks

**Comment by miguelgrinberg** [comment]
`module` here is supposed to be the name of the module that has your Flask application instance.

**Comment by TzlilClone** [comment]
Thank you very much
