### ISSUE TITLE
400 Error?

### ISSUE THREAD

**Issue by LeehoLim** [miguelgrinberg/Flask-SocketIO#1050]
Hi, I'm trying to spin up a simple socket connection w/ React + Flask... I'm unfortunately getting a 400 error... any thoughts around why this is? Happy to answer any questions around configs.

<img width="498" alt="Screen Shot 2019-08-27 at 2 44 14 PM" src="https://user-images.githubusercontent.com/11385142/63776473-620d2d80-c8d9-11e9-8c77-3e3f09791028.png">
<img width="448" alt="Screen Shot 2019-08-27 at 2 44 27 PM" src="https://user-images.githubusercontent.com/11385142/63776475-620d2d80-c8d9-11e9-8e7a-8f45cfd7410b.png">
<img width="784" alt="Screen Shot 2019-08-27 at 2 44 32 PM" src="https://user-images.githubusercontent.com/11385142/63776476-62a5c400-c8d9-11e9-8168-e4bb9b4b3b39.png">
<img width="791" alt="Screen Shot 2019-08-27 at 2 44 38 PM" src="https://user-images.githubusercontent.com/11385142/63776477-62a5c400-c8d9-11e9-8adb-63e0b445aaa8.png">
<img width="596" alt="Screen Shot 2019-08-27 at 2 44 45 PM" src="https://user-images.githubusercontent.com/11385142/63776479-62a5c400-c8d9-11e9-8d97-2ab361c1acd9.png">

**Comment by miguelgrinberg** [comment]
My guess is that this is a cross-origin error. You seem to be using a CORS configuration for your Flask app, but you have not configured origins for Socket.IO. See the `cors_allowed_origins` option in https://flask-socketio.readthedocs.io/en/latest/#flask_socketio.SocketIO.

**Comment by LeehoLim** [comment]
... @miguelgrinberg sorry for wasting your time. 

It was a versioning error... 
I spent 4 hours reading through documentation only to find out that there was nothing wrong with how I was writing my code!! ![bitmoji](https://render.bitstrips.com/v2/cpanel/e8577c17-750f-45ab-91bc-78d9f838acd0-145b25a1-1e0a-46ac-ac6f-3ddb6b138eb6-v1.png?transparent=1&palette=1&width=246)

**Comment by delewis13** [comment]
> ... @miguelgrinberg sorry for wasting your time.
> 
> It was a versioning error...
> I spent 4 hours reading through documentation only to find out that there was nothing wrong with how I was writing my code!! ![bitmoji](https://camo.githubusercontent.com/1035fc00228f8f380cb7a2a0bead7c2a8e88f801/68747470733a2f2f72656e6465722e6269747374726970732e636f6d2f76322f6370616e656c2f65383537376331372d373530662d343561622d393162632d3738643966383338616364302d31343562323561312d316530612d343661632d616336662d3364646236623133386562362d76312e706e673f7472616e73706172656e743d312670616c657474653d312677696474683d323436)

Encountering same issue - what versions worked for you?
