### ISSUE TITLE
SocketIO background task thread name

### ISSUE THREAD

**Issue by guesswh0** [miguelgrinberg/Flask-SocketIO#1051]
Is there is any possibility to set thread name of `sio.start_background_task(target=target)` method. I'm using it for testing/debugging stuff.

**Comment by miguelgrinberg** [comment]
The function returns the thread object, I think you should be able to call `setName()` on this object to change the thread's name to your liking.

**Comment by guesswh0** [comment]
I mean while creating thread object like we do in builtin `Thread(name=name, target=target)`, i know that you use all args/kwargs to pass to the target, thats why im asking. Just because i need thread name before my target function started.

**Comment by miguelgrinberg** [comment]
@guesswh0 You don't have to use this helper function if it doesn't do what you need. Just create the thread yourself if you need a different behavior.

**Comment by guesswh0** [comment]
i see, thank you.
