### ISSUE TITLE
How to control /socket.io/ endpoint

### ISSUE THREAD

**Issue by dank69** [miguelgrinberg/Flask-SocketIO#1053]
Hello,

This is less of an issue and more of a question, but is it possible to control the `/socket.io/` endpoint?

I am using `Flask-SocketIO` for authenticated users only, using the `authenticated_only` function wrapper:
```def authenticated_only(f):
    @functools.wraps(f)
    def wrapped(*args, **kwargs):
        if not current_user.is_authenticated:
            disconnect()
        else:
            return f(*args, **kwargs)
    return wrapped
```

All `@socketio.on` handlers are making use of this wrapper, including `@socketio.on('connect')`.

If an unauthenticated user makes a direct `GET` request to my server to the `/socket.io/` endpoint, for example `/socket.io/?EIO=3&transport=polling&t=MqK2tJx` this request will time-out and eventually result in a 502 error (`socket.io` is behind `nginx`).  But it seems to still be "stuck" in the async queue.

Is it possible to control the `/socket.io/` and immediately return a `403` for unauthenticated users?

Otherwise I eventually end up with errors as a core is "stuck" trying to manage this request `[DANGER] async queue is full !!!`

**Comment by dank69** [comment]
So the solution here seems to be to remove the `@authenticated_only` decorator from the `@socketio.on('connect')` handler, and instead just `return False` if the user is not authenticated:
```
@socketio.on('connect')
def connect_handler():
        if not current_user.is_authenticated:
            return False
        do_other_stuff_here()
```

**Comment by miguelgrinberg** [comment]
Yes, your solution of returning False is the correct one.
