### ISSUE TITLE
socketio.emit with callback doesn't work outside event context

### ISSUE THREAD

**Issue by FedeParola** [miguelgrinberg/Flask-SocketIO#1054]
socketio.emit with a callback raises an error if called outside a SocketIO event handler.
If I call it in a normal route handler, for example:
```python
@app.route('/test', methods=['GET'])
def test():
    def ack(data):
           print(data)
    socketio.emit('hello', 'hello', room=client_sid, callback=ack)
```
it throws error
```
File "C:\Program Files (x86)\Python37-32\lib\site-packages\flask_socketio\__init__.py", line 408, in emit
    sid = flask.request.sid
File "C:\Program Files (x86)\Python37-32\lib\site-packages\werkzeug\local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'sid'
```
For now I have resolved setting request.sid to the session id of the client I want to send my event to (same as the room), but I don't know if this could cause problems.

**Comment by miguelgrinberg** [comment]
This is actually a bug. When the emit is done outside of an event handler the callback also needs to be invoked w/o a context.

**Comment by EvanBldy** [comment]
I have the same problem, I fix this in my code with request.sid=the sid.
I'm interested in a fix for this.
Cordially
