### ISSUE TITLE
job from apscheduler with socketio on debug=True only runs once on python 3.8

### ISSUE THREAD

**Issue by ricardoSi** [miguelgrinberg/Flask-SocketIO#1056]
Hi,
I have the following code

**`routine_test.py`**
```
# -*- coding:utf-8 -*-
from app import app
from app import socketio

# app.run(host='0.0.0.0', port=5002, debug=True)
socketio.run(app, host='0.0.0.0', debug=True, port=5002)
```
**`app/__init__.py`**
```
# -*- coding:utf-8 -*-
import atexit
from flask import Flask
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.triggers.interval import IntervalTrigger

from app.data import socketio

app = Flask(__name__)

socketio.init_app(app)


def job_test():
    print("testing....")


mainScheduler = BackgroundScheduler()
mainScheduler.start()

mainScheduler.add_job(
    func=job_test,
    trigger=IntervalTrigger(seconds=30),
    id='test_job',
    name='TestJob',
    replace_existing=True)

# Shut down the scheduler when exiting the app
atexit.register(lambda: mainScheduler.shutdown())
```
**`app/data.py`**
```
from flask_socketio import SocketIO

socketio = SocketIO()
```
The job from mainScheduler runs only once when the debug flag is set to True. when the debug flag is set to False the background job runs every 30 seconds. 
If I just execute without socketio  `app.run(host='0.0.0.0', port=5002, debug=True)` the background job runs every 30 seconds as it should.
This is the package list:
```
APScheduler==3.6.1
Click==7.0
Flask==1.1.1
Flask-SocketIO==4.2.1
gevent==1.4.0
gevent-websocket==0.10.1
greenlet==0.4.15
itsdangerous==1.1.0
Jinja2==2.10.1
MarkupSafe==1.1.1
python-engineio==3.9.3
python-socketio==4.3.1
pytz==2019.2
six==1.12.0
tzlocal==2.0.0
```

I've tested this in python 3.8.b03 and 3.8.b04. 
Also tested in 3.5 and it works fine with debug flag set to True or False.

Side note: I'm using python 3.8 because of its new module shared_memory in multiprocessing

**Comment by miguelgrinberg** [comment]
This is likely an incompatibility between appscheduler and gevent. Just as a test, try uninstalling gevent to force the threading async mode. Unfortunately if it is a problem with gevent I'm not sure what I can do to help, this package does not really do anything that would prevent appscheduler to run.

**Comment by ricardoSi** [comment]
Uninstalled gevent and got the message

> WebSocket transport not available. Install eventlet or gevent and gevent-websocket for improved performance.

And everything seems fine, the job executed every 30 seconds as it should.

After I installed eventlet and everything also seems to work.
I guess I stick with eventlet for now, thanks

**Comment by miguelgrinberg** [comment]
The error about websocket is expected when neither evenlet nor gevent are installed.

If everything works for you then I guess there is nothing else to do, but be aware that async frameworks such as gevent and eventlet are likely to have issues so you may discover more problems. If at all possible my recommendation is that you move your scheduled tasks to a process other than the async server.

**Comment by sunrisa** [comment]
> The error about websocket is expected when neither evenlet nor gevent are installed.
> 
> If everything works for you then I guess there is nothing else to do, but be aware that async frameworks such as gevent and eventlet are likely to have issues so you may discover more problems. If at all possible my recommendation is that you move your scheduled tasks to a process other than the async server.

Hey @miguelgrinberg , I'm currently having issues with using `eventlet` (once a job is executed, socketio does not respond to emitted messages from clients) and am considering your recommendation of moving scheduled tasks to a separate process. How would you suggest facilitating communication between the process running the scheduled tasks and socketio? Would it be done through a message broker like RabbitMQ?

**Comment by miguelgrinberg** [comment]
@sunrisa What kind of communication do you need between the scheduled job and the server?

**Comment by sunrisa** [comment]
> @sunrisa What kind of communication do you need between the scheduled job and the server?

I start and stop scheduled jobs based on socketio events. I also would like functionality where if a scheduled job does not exist (when trying to stop a scheduled job), it can communicate this back to the server (and the server will respond to the client with an error message).

In summary, I need communication from the server to the job scheduler. In an ideal world, I would be able to do bidirectional communication between the server and job scheduler.

**Comment by miguelgrinberg** [comment]
@sunrisa Yeah. My first suggestion was going to be that you use cron or similar and to start/stop you edit the crontab file. If that is insufficient, then I agree, a little Flask web server should do what you need.

**Comment by philletourneau** [comment]
argh... I'm having the same issues. Any new info on this?
