### ISSUE TITLE
Unexpected behavior in testing with create_app()

### ISSUE THREAD

**Issue by pblankley** [miguelgrinberg/Flask-SocketIO#1059]
On setup in the unit test I use `create_app()` to make the app that I use for testing but the socketio connection never happens and the test fails.

On the flipside, when I use the app created without calling `create_app()` in the setup for the test class it works as expected.  This seems like a pretty standard use case for a larger app setup, so I'm not sure if it's something stupid I'm doing or something on the Flask-SocketIO side.

Minimal repro of the error is below. Thanks! 

```
Flask           1.1.1
Flask-SocketIO  4.2.1
```
 
```
import json
import unittest

from flask import Flask, session, request, json as flask_json
from flask_socketio import SocketIO, send, emit

socketio = SocketIO()

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'secret'
    socketio.init_app(app)
    return app

app = create_app()


@socketio.on('connect')
def on_connect():
    send('connected')
    send(json.dumps(request.args.to_dict(flat=False)))
    send(json.dumps({h: request.headers[h] for h in request.headers.keys()
                     if h not in ['Host', 'Content-Type', 'Content-Length']}))


@app.route('/session')
def session_route():
    session['foo'] = 'bar'
    return ''


class TestSocketIO(unittest.TestCase):

    def setUp(self):
        # self.app = app # Works
        self.app = create_app() # Doesn't work 
        self.socketio_client = socketio.test_client(self.app)

    def tearDown(self):
        pass

    def test_connect(self):
        client = self.socketio_client

        self.assertTrue(client.is_connected())
        received = client.get_received()
        self.assertEqual(len(received), 3)
        self.assertEqual(received[0]['args'], 'connected')
        self.assertEqual(received[1]['args'], '{}')
        self.assertEqual(received[2]['args'], '{}')
        client.disconnect()
        self.assertFalse(client.is_connected())


if __name__ == '__main__':
    unittest.main()
```

**Comment by miguelgrinberg** [comment]
You are not issuing a Socket.IO connection in your test, right? That is why you don't get one.

In the same way Flask has a test client, Flask-SocketIO also has a test client that you can use to connect over Socket.IO and send or receive events. See the [documentation](https://flask-socketio.readthedocs.io/en/latest/#flask_socketio.SocketIO.test_client).

**Comment by pblankley** [comment]
I thought I was issuing the connection with this line. Is that not the case?
```
self.socketio_client = socketio.test_client(self.app)
```
The tests pass when `self.app = app` but fail when I use the `create_app` function to make the app to use with the Flask-SocketIO test client

**Comment by miguelgrinberg** [comment]
Oh, so sorry, no idea how I missed it when I read your code.

The issue is actually much more subtle, and is related to your test using two methods of initialization for the app.

The app that you create in the global scope is made before any handlers are defined. The app that you create in the test is created after handlers are defined. The method in which handlers are initialized is different for these two cases, and the code does not expect both methods to be found in the same application, it's usually done one way or the other, but not both.

If you move the global `app = create_app()` right after the connect handler is defined, then everything works well.

**Comment by pblankley** [comment]
Oh, I see.

In my actual case, I'm using gunicorn as my server and export `app` (after I create it) from manage.py, and this has the same issue with failing tests.  How can I define the handlers "before" I create the app in manage.py (the handlers themselves are spread throughout blueprints)?

**Comment by miguelgrinberg** [comment]
@pblankley by "handlers" in this context I mean Flask-SocketIO handlers, in case it wasn't clear.

But in any case, why do you create the global scope app when you are running tests? As long as you use a single way to create the app and initialize the extension you should be fine. If you need a global app when you run on gunicorn, put that in a separate wsgi.py file or similar that is not imported during tests.

**Comment by pblankley** [comment]
Gotcha, that global scope app exists because I run tests / linting / etc with docker-compose exec commands.  I can figure out a different setup for running my tests through docker-compose.

Thanks for your help! Now I know what was going wrong in those tests. This issue is good to close, but it might be helpful to link to it if you have a list of "gotchas" for Flask-SocketIO.

**Comment by miguelgrinberg** [comment]
@pblankley Sorry to disagree, but your code, even with the fix of moving the app below the handlers is broken.

The second version of your code fixes the handlers for Flask-SocketIO, but the handlers for Flask routes are only attached to the global `app`, while any other application instances you create during the tests will have no Flask route handlers installed.

**Comment by pblankley** [comment]
Okay, that makes sense. Deleting that code block as it is misleading
