### ISSUE TITLE
IIS --> nginx --> Flask-SocketIO

### ISSUE THREAD

**Issue by jonfen** [miguelgrinberg/Flask-SocketIO#1060]
This issue plagued us, so I thought I would share.  We use IIS and docker.  IIS acts as a reverse proxy when we redirect to use SSL/TLS and rewrite requests to the docker servers running applications that don't have SSL/TLS natively.  Acknowledging the window of unencrypted traffic from IIS to the application, this method makes IT administration easier since all the SSL/TLS certificates are in one place.

However the websockets were unable to connect when they passed through IIS first.  So we turned on the logs.
> socketio = SocketIO(app, **logger=True, engineio_logger=True**)

The logs showed that the Origins were being denied.  After digging into the [Flask-SocketIO documentation](https://flask-socketio.readthedocs.io/en/latest/#module-flask_socketio) we found cors_allowed_origins had changed the default from allow to deny.

> **cors_allowed_origins** – Origin or list of origins that are allowed to connect to this server. Only the same origin is allowed by default. Set this argument to '*' to allow all origins, or to [] to disable CORS handling.

@miguelgrinberg: _while you have written some [documentation](https://flask-socketio.readthedocs.io/en/latest/#cross-origin-controls) around this.  I think it would be great to reference that section in other places so people might find it sooner.  Obviously where they are developing on their local machine they won't hit the issue, but the minute they try to deploy..._

So the issue didn't have to do with IIS, it had to do with the fact the origin (IIS) was not the same as the machine Flask-SocketIO was on.  This resolved our issue:

> socketio = SocketIO(app, logger=True, engineio_logger=True, **cors_allowed_origins='*'**)

**Given**
1. Windows Server 2012 running IIS 8.0, [ARR 3.0](https://www.iis.net/downloads/microsoft/application-request-routing), and Web Sockets enabled --> pointing to the nginx docker container
> Install-WindowsFeature -name Web-WebSockets
2. nginx server routing traffic to flask-socketio docker container(s)
3. docker container running Flask-SocketIO as an [embedded server](https://flask-socketio.readthedocs.io/en/latest/#embedded-server).

nginx.conf
>upstream web_upstream{
>    server app-web:5000;
>}
>
>upstream socket_upstream{
>    server app-socket:5005;
>}
>
>server {
>  listen 80 default_server;
>
>  server_name _;
>
>  location / {
>    try_files $uri \@web;
>  }
>
>  location /socket.io {
>    try_files $uri \@socket;
>  }
>
>  location \@web {
>    \# https://nginx.org/en/docs/http/ngx_http_uwsgi_module.html
>    \# https://serverfault.com/a/800729
>    include /etc/nginx/uwsgi_params;
>    uwsgi_pass web_upstream;
>    uwsgi_pass_header Content-Type;
>    uwsgi_pass_header X-Content-Type-Options;
>  }
>
>  location \@socket {
>    \# http://nginx.org/en/docs/http/websocket.html
>    \# https://nginx.org/en/docs/http/ngx_http_proxy_module.html
>    \# https://flask-socketio.readthedocs.io/en/latest/#using-nginx-as-a-websocket-reverse-proxy
>    \# https://socket.io/docs/using-multiple-nodes/#NginX-configuration
>    proxy_pass http://socket_upstream;
>    proxy_http_version 1.1;
>    proxy_set_header Upgrade $http_upgrade;
>    proxy_set_header Connection "upgrade";
>    proxy_set_header Host $host;
>    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>    proxy_buffering off;
>    proxy_read_timeout 120s;
>  }
>}

**Comment by miguelgrinberg** [comment]
> This resolved our issue:
> 
> socketio = SocketIO(app, logger=True, engineio_logger=True, cors_allowed_origins='*')

And with this you've made your server insecure and potentially vulnerable to attacks. I strongly advice that you set your origins appropriately, a wildcard is convenient, but not a good idea in most cases.
