### ISSUE TITLE
400 error occassionally shows up with heroku

### ISSUE THREAD

**Issue by HeatMint** [miguelgrinberg/Flask-SocketIO#1061]
I've tried using either eventlet and gevent but the same problem shows up.
![image](https://user-images.githubusercontent.com/24670423/65197036-333b3f00-dab4-11e9-8afa-1d93c3186534.png)
I've tried to use gunicorn 18.0 instead of gunicorn 19.9, but the programme can't find gevent-websocket in library. I tried to use eventlet in current version but the problem still occurs.
https://github.com/HeatMint/web-remote-gomoku-heroku-deploy
This is my repo I'm using to deploy on heroku

**Comment by miguelgrinberg** [comment]
A 400 can be returned for a few different situations. To have more information you may want to enable Socket.IO logs by adding `engineio_logger=True, logger=True` to your `SocketIO()` constructor.

**Comment by HeatMint** [comment]
I fixed this issue by changing Procfile from:
`web: gunicorn -k eventlet app:app`
to:
`web: gunicorn --worker-class eventlet -w 1 app:app`
This is my fault because I didn't read the docs.
How ever for gevent `gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 app:app` didn't work for me. Still don't know why
