### ISSUE TITLE
Cookies not being retrieved properly 

### ISSUE THREAD

**Issue by sajil13** [miguelgrinberg/Flask-SocketIO#1062]
I am developing a chat-based application. Which uses socketio for sending the message to the server which uses Flask-SocketIO.
I am setting a cookie once a user sends a message. And I can see in the browser that it's being set properly. But as soon as I close the browser a disconnect event will be called on the server-side. At that moment ideally, I shouldn't get the cookies from the browser but I am getting the cookies even after the browser has been closed. 

PS- I have set a default expiration time for the cookies i.e it will be deleted upon closing the browser.

PPS - I get the cookies using request module.

**Comment by miguelgrinberg** [comment]
You are setting the cookie from the client correct? Then your client owns the cookie, the server has nothing to do with it. If you set it as a session cookie then it will go away when you close the browser window.
