### ISSUE TITLE
Flask-SocketIO is not sending anything to my react frontend

### ISSUE THREAD

**Issue by tayshudong** [miguelgrinberg/Flask-SocketIO#1067]
I'm having issues running a simple example.

Currently, my react frontend is running in localhost 3000 on my desktop and my flask server is running in raspberry pi. both of them are connected in the same network.
I just wanted to make a simple program such that my frontend and my backend can communicate with each other.
Initially, there is some error so I include the transports: {websocket} and install gevent-websocket now there is no error but the message is not sent.
 REACT
![image](https://user-images.githubusercontent.com/42646183/65499019-87e51c80-deef-11e9-84c5-b64e76e09278.png)

FLASK - i'm hosting using my rpi ip address with port 3231
![image](https://user-images.githubusercontent.com/42646183/65492410-7138c880-dee3-11e9-8ce2-4ac13db2fec7.png)

REACT network - i dont really know what does switching protocol really mean is that important?
![image](https://user-images.githubusercontent.com/42646183/65489369-8ca0d500-dedd-11e9-95b7-2d33810728e2.png)

**Comment by miguelgrinberg** [comment]
Do you have logs from client and server? I can't really tell what's happening without the logs.

**Comment by tayshudong** [comment]
Thank for the quick response and I'm sorry. I can only do that tomorrow as I got no computer with me until tomorrow

**Comment by tayshudong** [comment]
Hi,
Apologize for the delay.

The Flask logger shows this:
![image](https://user-images.githubusercontent.com/42646183/65562344-a3483a00-df78-11e9-8197-f2fbf0653f2b.png)

The React console shows this repeatedly(is this sufficient):
![image](https://user-images.githubusercontent.com/42646183/65562729-f66ebc80-df79-11e9-8104-056d7b9116a6.png)

**Comment by tayshudong** [comment]
Hi Miguel,
I have solved it through one of your posts in the past. By the way, can I ask you why sometimes it requires Cors sometime not? 
![image](https://user-images.githubusercontent.com/42646183/65567462-f7f3b100-df88-11e9-941b-541f76f0fff1.png)

**Comment by miguelgrinberg** [comment]
CORS is a security feature. The change that you've made disables CORS, so it is not a good idea, you may want to set the correct origin(s) instead of `'*'`. For information on CORS see https://en.wikipedia.org/wiki/Cross-origin_resource_sharing.
