### ISSUE TITLE
blocking requests

### ISSUE THREAD

**Issue by patrickjahns** [miguelgrinberg/Flask-SocketIO#107]
Hi,

I`ve been reading the other posts slightly related to this issue, but none have related to solve my problem so far.

I have the problem, that multiple requests from the same client are buffered and executed in the order they arrived. I suppose money patching is working, since even when the request from 1 client is qeued, requests from other clients will be handled. So my question is, is this desired behaviour, that each client can only create linear requests and not asynchronous concurrent ones?

Sample code:
```
@socketio.on('my long event', namespace='/test')
def test_message(message):
    session['receive_count'] = session.get('receive_count', 0) + 1
    emit('my response',
         {'data': 'long task started', 'count': session['receive_count']},
         broadcast=True)
    time.sleep(10)
    emit('my response',
         {'data': 'long task finished', 'count': session['receive_count']},
         broadcast=True)

@socketio.on('my event', namespace='/test')
def test_message(message):
    session['receive_count'] = session.get('receive_count', 0) + 1
    emit('my response',
         {'data': short task, 'count': session['receive_count']},
         broadcast=True)
```

Scenario 1:
Assume client 1 sends `my long event` 1 time and the sends `my event` - it will return `long task started`, 10 seconds `long task finished` and then afterward `short task`
output:
```
c1 long task started
c1 long task finished
c1 short task
```

Scenario 2:
Same as one, but during the waittime, the client2 sends `my event` during the 10s where long task is running, the msg will be handled
output:
```
c1 long task started
c2 short task
c1 long task finished
c1 short task
```
Is this a limitation of gevent socket.io or of flask-socketio

Thanks for any input

**Comment by patrickjahns** [comment]
Never mind, need to read the documentation better, it clearly states: 
```
The main difference is that all the SocketIO events generated for a client occur in the context of a single long running request
```
Is there a way to create greenlets/threads per request? Or any other recommendations to handle this (besides going back to celery and tasks - which seem to much for a single page application that has very low traffic). The long running tasks are based on remote requests that can take up to several seconds to be finished. I was hoping that by asynchronous dealing over greenlets this would work

**Comment by miguelgrinberg** [comment]
@patrickjahns the idea of "long request" does not apply when you work with cooperative multi-tasking frameworks. Any time you do CPU intensive work you are blocking the event loop.

You can certainly spawn background greenlets to do work, but you can't have any task using the CPU for a long time without yielding.

**Comment by patrickjahns** [comment]
@miguelgrinberg 
Yes I do agree that for CPU intensive tasks this is not a good way to handle it. For my case, the long running task is not CPU but IO bound. Certain request will issue remote commands that may take some time to finish on the remote machine. Since the application is low traffic and these long running task requests will be below < 10 simultaneously it was thinking of avoiding the client -> flask-io -> redis -> celery -> redis -> flask-io > client setup. Thinking of what is required I wanted to ship the application in small size docker container to be run easily.

For the background greenlets, is it possible to make the request socket.io context available? Thanks for any hints
