### ISSUE TITLE
Transport websocket does not work and will result in 400 Return codes

### ISSUE THREAD

**Issue by Tyde** [miguelgrinberg/Flask-SocketIO#1072]
I am currently facing the following problem:
I basically followed [this](https://blog.miguelgrinberg.com/post/easy-websockets-with-flask-and-gevent) tutorial to establish a socketio connection between a flask server and the browser. This does work but the socket.io implementation only uses the polling transport method. When I try to force the transport to websocket by `io.connect({transports: ['websocket']});`, I do see websocket-requests from the browser resulting in Status 400 responses from the server. 

```
from flask import Flask, render_template, send_from_directory,request
import logging
from flask_socketio import SocketIO, emit

from utils import repeated_timer

app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
app.logger.setLevel(logging.DEBUG)
socketio = SocketIO(app)


@app.route('/')
def main_page():
    return render_template('main_page.html')


@socketio.on('connect')
def test_connect():
    print("Client connected")
    socketio.emit('res','answer')


@socketio.on('disconnect')
def test_connect():
    print("Client disconnect")

@socketio.on_error_default
def default_error_handler(e):
    print(request.event["message"])  # "my error event"
    print(request.event["args"])  # (data,)


def send_update():
    socketio.emit('dataupdate', {'data': 'no-data'})


if __name__ == '__main__':
    repeated_timer.RepeatedTimer(1, send_update)
    socketio.run(app)
```

On the server side I do get some "client connnected" and "Client disconnect", but there is no data transfer through the websocket.

**Comment by miguelgrinberg** [comment]
If you enable logging you will get more information about the failure. To do this, use:

    socketio = SocketIO(app, logger=True, engineio_logger=True)

**Comment by Tyde** [comment]
There seems to be nothing unusual looking at the logs:
```
Server initialized for gevent.
5fbdb4fbe2584c98929d0df83b69537c: Sending packet OPEN data {'sid': '5fbdb4fbe2584c98929d0df83b69537c', 'upgrades': [], 'pingTimeout': 60000, 'pingInterval': 25000}
[2019-10-01 16:54:24,150] INFO in main: client connected
5fbdb4fbe2584c98929d0df83b69537c: Sending packet MESSAGE data 0
5fbdb4fbe2584c98929d0df83b69537c: Received request to upgrade to websocket
Client connected
emitting event "dataupdate" to all [/]
5fbdb4fbe2584c98929d0df83b69537c: Sending packet MESSAGE data 2["dataupdate",{"data":"no-data"}]
```
Apparently the server thinks, that the connection is established and tries to send data.

**Comment by miguelgrinberg** [comment]
Anything in the browser console? There should be some information on these 400 errors somewhere.

The log that you included shows that a websocket upgrade was initiated, but it does not include the conclusion, which can be either a success or a failure. Both events are logged, I think.

**Comment by Tyde** [comment]
Sorry, the error was completely on my side, I did not read your documentation properly and used gevent instead of evently. I did change that now, and everything is working fine. Thanks for the help!
