### ISSUE TITLE
python app doest start after import from flask_socketio

### ISSUE THREAD

**Issue by engragy** [miguelgrinberg/Flask-SocketIO#1073]
i am using ubuntu 18.04 and trying to build a small chat website for a course using flask and js

the problem happens when i try to run python3 app.py instead of flask run as i read here, i did find that i need eventlet or gevent, gevent-websocket but after installing each at a time and try to run all i can see is that the command line blinking (hangs) and with gevent if i press ctrl+c i get this
> ^CKeyboardInterrupt
2019-10-01T15:20:30Z
Traceback (most recent call last):
  File "application.py", line 88, in <module>
    socketio.run(app)
  File "/home/kraytos/pyve/project2_env/lib/python3.6/site-packages/flask_socketio/__init__.py", line 602, in run
    self.wsgi_server.serve_forever()
  File "/home/kraytos/pyve/project2_env/lib/python3.6/site-packages/gevent/baseserver.py", line 369, in serve_forever
    self._stop_event.wait()
  File "src/gevent/event.py", line 127, in gevent._event.Event.wait
  File "src/gevent/_abstract_linkable.py", line 192, in gevent.__abstract_linkable.AbstractLinkable._wait
  File "src/gevent/_abstract_linkable.py", line 165, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 169, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 64, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
KeyboardInterrupt

 
here is pip freeze from inside my environment variable
> Click==7.0
dnspython==1.16.0
Flask==1.1.1
Flask-Session==0.3.1
Flask-SocketIO==4.2.1
gevent==1.4.0
gevent-websocket==0.10.1
greenlet==0.4.15
itsdangerous==1.1.0
Jinja2==2.10.1
MarkupSafe==1.1.1
monotonic==1.5
python-engineio==3.9.3
python-socketio==4.3.1
six==1.12.0
Werkzeug==0.16.0

this hang has nothing to do with the python or javascript code as it still hangs even if i remove all code lines except the imports like " from flask_socketio import SocketIO, emit "
any way this is the app python code

```
import os
from datetime import datetime
from flask import Flask, session, render_template, redirect, request, url_for, flash, jsonify
from flask_session import Session
from flask_socketio import SocketIO, emit

app = Flask(__name__)
app.config["SECRET_KEY"] = 'secrettt'
app.config["SESSION_PERMANENT"] = False
app.config["SESSION_TYPE"] = "filesystem"
Session(app)
socketio = SocketIO(app)

data = {}

@app.route("/", methods=["GET", "POST"])
def index():
    if request.method == 'POST':
        if request.form.get('display_name'):
            dis_name = request.form.get('display_name')
            session['username'] = dis_name
            return jsonify({"success": True, "dis_name": session['username']})

        elif request.form.get('channel_name'):
            ch_name = request.form.get('channel_name')
            session['active_channel'] = ch_name
            return jsonify({"success": True, "redirect": f"/channel/{session['active_channel']}"})
            # return redirect(url_for('channel', ch_name=ch_name))

        elif request.form.get('cr_name_name'):
            if 'username' in session:
                flash(f"you already have a display name '{session['username']}'", 'danger')
                return render_template('index.html', ch_list=list(data.keys()), title="Flack Home page")
            else:
                dis_name = request.form.get('cr_name_name')
                ch_list = list(data.keys())
                if not dis_name in ch_list:
                    flash(f"you have successfully entered a name '{dis_name}' for chatting", 'success')
                    session['username'] = dis_name
                    return render_template('index.html', dis_name=dis_name, ch_list=ch_list, title="Flack Home page")
                else:
                    flash(f"the name you have entered {dis_name} is the same as a channel name, choose another one", "danger")
                    return render_template('index.html', ch_list=ch_list, title="Flack Home page")


        elif request.form.get('cr_ch_name'):
            if 'username' in session:
                ch_name = request.form.get('cr_ch_name')
                ch_list = list(data.keys())
                if not ch_name in ch_list:
                    data.update({f"{ch_name}": []})
                    return render_template('index.html', dis_name=session['username'], ch_list=list(data.keys()), title="Flack Home page")
                else:
                    flash(f"the channel name you have entered {ch_name} already exists, choose another one", "danger")
                    return render_template('index.html', dis_name=session['username'], ch_list=ch_list, title="Flack Home page")
            else:
                flash(f"you have to get a display name first", "danger")
                return render_template('index.html', ch_list=list(data.keys()), title="Flack Home page")

    ch_list = list(data.keys())
    return render_template('index.html', ch_list=ch_list, title="Flack Home page")

@app.route("/channel/<ch_name>")
def channel(ch_name):
    if 'username' in session:
        msgs = data.get(f"{ch_name}")
        return render_template("channel.html", msgs=msgs, dis_name=session['username'])
    
    flash(f"you dont have access to chat untill you create display name ...", "danger")
    return redirect(url_for('index'))

if __name__ == '__main__':
    socketio.run(app)
```

**Comment by miguelgrinberg** [comment]
Does the application hang and is unresponsive? Any change the server starts, and you think it is hung but when you send a request it responds to it? You should not that when you use eventlet or gevent you are using a different web server, the output is going to be different than what you see when you run the Flask development web server.

**Comment by engragy** [comment]
when i have installed the eventlet or gevent and try to run the pogram it came up with only a blinking cursor and i do remember that i have tried to load page 127.0.0.1:5000 but it didn't work
yet now it is openning in the browser after uninstall and reinstall almost all flask related packages, really sorry after all
now one more thing the program has an index page " / " and a chat page "/channel/name", with different javascript for each of the two
the first page is working fine, the second page which is going to be socketio client is giving an error 
("ReferenceError: io is not defined") on the forth line to connect, am i doing something wrong here

`
document.addEventListener('DOMContentLoaded', () => {
  var u_name = localStorage.getItem('dis_name')
  var u_ch = localStorage.getItem('act_ch')
  var socket = io.connect(location.protocol + '//' + document.domain + ':' + location.port);
  // var socket = io('http://127.0.0.1:5000');
  // When connected, start configuring
  socket.on('connect', () => {
    document.querySelector('#send').onsubmit = () => {
      const text = document.querySelector('#send_txt').value;
      // emit an event to the web server
      socket.emit('submit msg', {"u_name": u_name, "u_msg": text, "ch_name": u_ch});
    };
  });

  // receive / wait for a named event that is broadcasted from the server
  // socket.on('all msgs', data => {});

  // receive / wait for new msg = {"name": , "timestamp": , "msg": }
  socket.on('new msg', data => {
    const new_msg = `<li class="list-group-item d-flex justify-content-between align-items-center">${data.name}
      <span class="badge badge-primxary badge-pill">${data.timestamp}</span>
      <p>${data.msg}</p>
    </li>`
    document.querySelector('#msgs_list').append(new_msg);
  });
});

`

**Comment by miguelgrinberg** [comment]
If `io` is not defined it means that you have not included the Socket.IO client JS code in your page.
