### ISSUE TITLE
Embedded Server not listening for ws:// or wss:// prefix

### ISSUE THREAD

**Issue by jonfen** [miguelgrinberg/Flask-SocketIO#1078]
When running the [embedded server](https://flask-socketio.readthedocs.io/en/latest/#embedded-server):

```
socketio.run(app, host='0.0.0.0', port=5005)
```

Using a the [socket.io](https://github.com/socketio/socket.io) client forcing websockets over polling:

```
let namespace = '/' + m_websocket_info['listener'] + '/' + m_user_location_id;
if (location.port === "5000") {
    namespace = location.protocol + '//' + location.hostname + ':5005' + namespace;
}
socket = io(namespace, { transports: ['websocket'] });
```

Despite `location.protocol` being `http:` the browser console shows the following error:

```
index.js:83 WebSocket connection to 'ws://localhost:5005/socket.io/?EIO=3&transport=websocket' failed: Unknown reason
```

When the traffic is routed through nginx there are no errors:

```
# https://uwsgi-docs.readthedocs.io/en/latest/Nginx.html

upstream web_upstream{
    server server-web:5000;
}

upstream socket_upstream{
    server server-socket:5005;
}

server {
  listen 80 default_server;

  # error_log /var/log/nginx/error.log debug;

  server_name _;

  location / {
    try_files $uri @web;
  }

  location /socket.io {
    try_files $uri @socket;
  }

  location @web {
    # https://nginx.org/en/docs/http/ngx_http_uwsgi_module.html
    # https://serverfault.com/a/800729
    proxy_pass http://web_upstream;
  }

  location @socket {
    # http://nginx.org/en/docs/http/websocket.html
    # https://nginx.org/en/docs/http/ngx_http_proxy_module.html
    # https://flask-socketio.readthedocs.io/en/latest/#using-nginx-as-a-websocket-reverse-proxy
    proxy_pass http://socket_upstream;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_buffering off;
    proxy_read_timeout 120s;
  }
}
```
Routing through nginx is used in production, however connecting indirectly to the container breaks debugging using the [vscode chrome debugger](https://github.com/Microsoft/vscode-chrome-debug).

**Comment by miguelgrinberg** [comment]
Look in the network tab to see what the actual status code for the ws:// request was. You can also see if removing `transports: ['websocket']` in your client allows the connection to be made, and if it is, then see if the polling transport was upgraded to websocket successfully.

**Comment by jonfen** [comment]
@miguelgrinberg you are a gentleman and a scholar.  Thank you.  By trying to force [websockets](https://socket.io/docs/using-multiple-nodes/) I was hiding the error that let me know 5005 was exposed, but not externally available to the client browser.
