### ISSUE TITLE
SocketIO don't work when deploying a Flask + Vue.js Application

### ISSUE THREAD

**Issue by rtadewald** [miguelgrinberg/Flask-SocketIO#1080]
**Describe the bug**
I'm creating an application that uses Flask (with Flask-SocketIO + threading.Thread) in the backend and Vue.js in frontend.

The application works like a charm in development servers, but when I change to production (using eventlet and calling python3 app.py), the application works nice until it starts to consume data from the flask app using socket.IO.

Using:
```
app = Flask(__name__)
CORS(app, resources={r'/*': {'origins': '*'}})
socketio = SocketIO(app, cors_allowed_origins="*", engineio_logger=True)
```
I was able to see in the console that the flask app is sending the data, but the templates are not.
My app uses a class that instantiates **threading.Thread**, I dunno if that could result in a problem.
In the frontend, the socket.io client is poiting to **http://localhost:5000**.

I really don't know where to start. Does anybody know anything?
Thanks.

**Comment by miguelgrinberg** [comment]
Did you monkey patch the standard library so that it is compatible with eventlet?

**Comment by rtadewald** [comment]
I used:
`import eventlet
eventlet.monkey_patch()`

in the beggining of my app.py, but I dunno if I'm doing it the right way...

**Comment by miguelgrinberg** [comment]
> I was able to see in the console that the flask app is sending the data, but the templates are not.

What do you mean by "the templates are not" exactly?

**Comment by rtadewald** [comment]
I'm sorry if I could not me 100% clear.
What's happenning is that the sockets between the frontend and backend in my app is not working when I change from development for production. 

I instantiated SocketIO with **engineio_logger=True** and I can see that the backend is sending data throught sockets, but the client methods that consume that data is not beeing triggered (It don't get the data). I've compiled the Vue app and put inside /template folder under my Flask app.

**Comment by rtadewald** [comment]
In development mode:
<img width="1344" alt="Captura de Tela 2019-10-17 às 20 59 28" src="https://user-images.githubusercontent.com/22618324/67056111-36f8ca80-f121-11e9-9edc-498f60f8d591.png">

Data from backend is feeding the books and there's a console.log printing "here"in the console:
<img width="1440" alt="Captura de Tela 2019-10-17 às 21 00 19" src="https://user-images.githubusercontent.com/22618324/67056175-5a237a00-f121-11e9-8e76-a95ba3516474.png">


But, when I install eventlet and switch to production:
<img width="1344" alt="Captura de Tela 2019-10-17 às 21 03 07" src="https://user-images.githubusercontent.com/22618324/67056274-aec6f500-f121-11e9-845e-79b919aa61d6.png">

Nothing happens in the frontend:
<img width="1440" alt="Captura de Tela 2019-10-17 às 21 03 51" src="https://user-images.githubusercontent.com/22618324/67056282-b5ee0300-f121-11e9-9119-ba3266b4a4b4.png">

And I can see that the data is beeing send by flask:
<img width="1344" alt="Captura de Tela 2019-10-17 às 21 04 01" src="https://user-images.githubusercontent.com/22618324/67056288-c1412e80-f121-11e9-9719-d7254fd3f6b9.png">

**Comment by miguelgrinberg** [comment]
What do the frontend logs for Socket.IO client look like in the working vs not working cases?

**Comment by rtadewald** [comment]
I just made it printed "here"when it recieves the data.

**Comment by miguelgrinberg** [comment]
Yes, but what I'm asking is for the lower level Socket.IO logs, matching those your are getting from the server.

**Comment by rtadewald** [comment]
I'm sorry, but I don't know how to access it. 

I'm very new to Vue and Socket.IO and i didn't make any special codes for logging in the client side... Do you anything about it?

**Comment by rtadewald** [comment]
Sorry, but I don't know how to access lower level logs of Socket.IO... I'm new to this and to Vue...

All I've done is to instantiate socket.io in my js script with:

```
import io from 'socket.io-client';
this.socket = io(this.$store.state.backend_url)
```
 and start using it..

**Comment by miguelgrinberg** [comment]
See the docs on logging here: https://socket.io/docs/logging-and-debugging/

**Comment by rtadewald** [comment]
Thank you again.

When I reload the page, I get this:
<img width="1440" alt="Captura de Tela 2019-10-17 às 22 45 53" src="https://user-images.githubusercontent.com/22618324/67059535-e472da80-f12f-11e9-93ca-72e8ca588bc4.png">

But when I click play (and start recieving data from socket) nothing changes.
(_Running the same thing under development, when I click play, I can see all the incoming data...)_

**Comment by miguelgrinberg** [comment]
You are going to need to get me better logs, your screenshots do not capture everything. If you can get complete log files of a session from the client and the server maybe I can find some clues there.

**Comment by rtadewald** [comment]
@miguelgrinberg, thank you for your help. I think I will give up on this. My application is huge (dozens of classes, and I think it will be to hard to investigate what monkey_patch is actually doing in all of it.

I'll change the setup and not deploy frontend and backend together, instead, I'll separete them over 2 VPSs. 

Thank you so much!

**Comment by miguelgrinberg** [comment]
@rtadewald Have you confirmed that deploying them separately works fine? That's interesting, then the problem could be in how your frontend files are exposed. Do they have a different URL in production compared to development?

Also note that you can deploy frontend and backend as separate processes but still use one VPS. You just need to use two different ports, which is what I believe you are doing for your development machine.

**Comment by rtadewald** [comment]
No, I didn,t. But, I've tryed here and seems to not work too.

Let give the last try:
That's the key points of my Python module:

`import json
import numpy as np
import copy
from asimov_strategy.strategies.strategies import *
from flask import Flask, jsonify, request, render_template
from flask_cors import CORS
from flask_socketio import SocketIO
import logging

import eventlet
eventlet.monkey_patch(socket=True)

app = Flask(__name__)
CORS(app, resources={r'/*': {'origins': '*'}})
socketio = SocketIO(app, cors_allowed_origins="*", engineio_logger=True)


# =======================================================
#  REST API
@app.route("/endpoint1", methods=['GET', 'POST'])
def endpoint1():
      ... numpy and pandas operations. ..
        return jsonify({ python dict... })

@app.route("/endpoint2", methods=['GET', 'POST'])
def endpoint2():
      ... numpy and pandas operations. ..
        return jsonify({ python dict... })
...

if __name__ == "__main__":
    # This class is instantiated in by one of the Rest methods, and the threading's start() method is called...
    class simulationManager (threading.Thread):
        huge class...
    def run(self):
        while true:
                 numpy and pandas operations...
                 numpy and pandas operations...
                socketio.emit('update', python dict)    

    socketio.run(app)

`

Do you see any big mistake in this high level abstraction?

**Comment by miguelgrinberg** [comment]
Okay. I do see a potential problem. How heavy are your numpy and pandas operations? Eventlet servers use cooperative multitasking, which means that a thread cannot spend large amounts of time doing CPU work, as that prevents other threads from running.

**Comment by rtadewald** [comment]
I use them a lot. The key idea of the application is to run heavy simulations using lots of CPU and RAM and display the result to the user...

**Comment by miguelgrinberg** [comment]
@rtadewald that unfortunately complicates things considerably. You will need to run your CPU heavy code in a separate thread (a "real" thread, not an eventlet green thread). See https://eventlet.net/doc/threading.html to learn more about this technique.

**Comment by rtadewald** [comment]
@miguelgrinberg I'll take a deep look. Thank you so much for you time and help.

Do you suggest any other deployment alternative?
Thanks!

**Comment by miguelgrinberg** [comment]
@rtadewald Are you familiar with the concept of microservices? One option you can explore is moving your CPU heavy tasks into a separate auxiliary service that you can run without eventlet. So then you have your API running asynchronously with eventlet, and your calculation service running on a synchronous web server, maybe gunicorn in sync mode, which is the default.

Your API service can then send a request to your calculations service when it needs some data. This will prevent eventlet from blocking, because the calculations are done in the context of a separate process.

**Comment by rtadewald** [comment]
That's a good idea. I'll study it more. 
Thank you so much for your help!

**Comment by rtadewald** [comment]
@miguelgrinberg, one last question: in your idea of microservices, would be a problem to use websockets  for communication between my API and my CPU intense microservice? Won't be a problem to use flask.SocketIO again inside the Docker, because I'll have to call it using gunicorn and eventlet? 

How do you suggest to setup the production enviroment of the microservice? Using only REST and pooling data from the API periodically?

**Comment by miguelgrinberg** [comment]
@rtadewald When you say "websocket" do you mean pure websocket or Flask-SocketIO? If you mean the latter, then your CPU process needs to be a client, not a server, because if you make that also a Flask-SocketIO server then you need eventlet and we are back where we started.

Your CPU intensive process can be a Socket.IO client using python-socketio's `Client()` class, which does not require an asynchronous implementation (only the server does). You will need some way to identify the client connection from the CPU task in the API server, because the server will now have client connections from web browser clients plus one more for the CPU heavy process.

**Comment by rtadewald** [comment]
I, now i see. Thank for your time and for sharing yout knowledge, @miguelgrinberg !
