### ISSUE TITLE
Broadcast large data to clients some of which are too slow

### ISSUE THREAD

**Issue by VladimirVLF** [miguelgrinberg/Flask-SocketIO#1081]
Hi,
I have several clients in a room and an image buffer (bytesarray) of let's say 1MB. In a background thread (`start_background_thread()`)  I periodically update the image buffer and emit broadcast to the room.
Typically all clients have received a new frame way before it is updated and ready to be sent again. But what happens if one of the clients has slow connection and cannot receive the whole image buffer before it is updated? And what if it can receive image buffer at a rate slower than the update rate? Will the buffer copies pile up and memory explode over time?

Honestly, I have no clear idea how the emit mechanism works regarding the data being sent, and therefore I ask here. Thanks in advance.

**Comment by VladimirVLF** [comment]
Did I ask about something that doesn't make sense?
Actually I would be happy to get any feedback even if I need to read-up some topic before asking this :)

**Comment by miguelgrinberg** [comment]
Sorry I haven't responded, I missed the notification for this issue.

This package does not do anything special to handle the case you mention, so the standard socket behavior will apply. I suppose once the client's receive buffer is full the server side socket's buffer will start to fill, and once it is full writes will block. If you keep pushing frames into this socket then those will stay in the Socket.IO queue. If your application does not have a way to adapt the stream to the client's capabilities, then I guess your Python process will start using more RAM and once it takes it all it will die.

There are better ways to stream video with adaptive bitrates. I'm not sure streaming over Socket.IO is a good idea if you have to account for clients with such different needs.

**Comment by VladimirVLF** [comment]
OK I see, thanks for the answer. I think I get it.
Though it does not concern video streaming, but frame by frame image streaming, but the problem looks quite the same. I will try to find a better method maybe. Thanks!

**Comment by VladimirVLF** [comment]
For those who interested, I made this the other way around: Now I emit a URL to the new frame to the user browser and it has to fetch it itself. This way no big data is transferred over websockets, and clients can download fresh images as fast/slow as they can.  Also this way websocket server is unloaded from heavy IO operations. Fetching is setup to be served by nginx.
Hope its OK I close this thread.

**Comment by miguelgrinberg** [comment]
@VladimirVLF thanks for providing the solution to your problem.
