### ISSUE TITLE
Flask-SocketIO on Azure App Service - Windows - Reconnects every 25-30 seconds

### ISSUE THREAD

**Issue by etomer123** [miguelgrinberg/Flask-SocketIO#1082]
**Your question**
Hello
I've been struggling to get a Flask-SocketIO functioning correctly on Azure App Services. It runs fine locally but on Azure it keeps reconnecting every 25-30 seconds. Most of the XHR request return with a status of 200 but sometimes a status 400 is returned causing the connection to reconnect. When  a 400 (Bad Request) status is returned its always a POST request.
You can see it happening here:
http://instantfeedbacktr2.azurewebsites.net/

And here is the web.config:

[web.config.txt](https://github.com/miguelgrinberg/Flask-SocketIO/files/3748152/web.config.txt)

I'm at a complete lost so I hope you'll be able to shed some light.

**Logs**

Google Dev Tools
[instantfeedbacktr2.azurewebsites.net.har.txt](https://github.com/miguelgrinberg/Flask-SocketIO/files/3748162/instantfeedbacktr2.azurewebsites.net.har.txt)

Azure
[Azure log stream.txt](https://github.com/miguelgrinberg/Flask-SocketIO/files/3748167/Azure.log.stream.txt)

**Comment by miguelgrinberg** [comment]
Where are the logs?

**Comment by etomer123** [comment]
Hi, I just updated with some of the logs

**Comment by etomer123** [comment]
web server logs
[web server logs.txt](https://github.com/miguelgrinberg/Flask-SocketIO/files/3748172/web.server.logs.txt)

**Comment by etomer123** [comment]
And here is the client side 

[login.js.txt](https://github.com/miguelgrinberg/Flask-SocketIO/files/3748173/login.js.txt)

**Comment by miguelgrinberg** [comment]
Please re-read the instructions on how to get logs from the Socket.IO server and client (copied below for your convenience). None of the files you provided are what I need to diagnose the problem.

**Logs**
Please provide relevant logs from the server and the client. On the server, add the `logger=True` and `engineio_logger=True` arguments to your `SockertIO()` object to get logs dumped on your terminal. The same arguments can be used on the [python-socketio's client](https://github.com/miguelgrinberg/python-socketio). If you are using the JavaScript client, see [here](https://socket.io/docs/logging-and-debugging/) for how to enable logs.

**Comment by etomer123** [comment]
Here are the client logs

[client_logs.txt](https://github.com/miguelgrinberg/Flask-SocketIO/files/3748194/client_logs.txt)

**Comment by miguelgrinberg** [comment]
And the server logs?

**Comment by etomer123** [comment]
Hi
I've added the logging settings but I'm struggling on where to find them on the server, All of the log files I've looked at don't seem to contain the data you're interested in

**Comment by etomer123** [comment]
I dont think this is the log you are requesting

[329f75-201910200359.log](https://github.com/miguelgrinberg/Flask-SocketIO/files/3748257/329f75-201910200359.log)

**Comment by miguelgrinberg** [comment]
The web server log is what goes out to stdout, as indicated in the instructions, it is not written to a file.

**Comment by miguelgrinberg** [comment]
Please reopen once you can provide the requested logging.

**Comment by krunal3** [comment]
@miguelgrinberg .I am facing the same issue. did you get any solution?
