### ISSUE TITLE
Can not work with eventlet by using socketio.init_app() function in factory function.

### ISSUE THREAD

**Issue by dilless** [miguelgrinberg/Flask-SocketIO#1083]
I have a factory function to create app, and use socketio.init_app() to init socketio.
But i get this warning:  Flask-SocketIO is Running under Werkzeug, WebSocket is not available.
I have installed eventlet, but it still not work. 
THX.
Here is my codes:
``` python
__init__.py

from catchat.extensions import socketio
def create_app(config_name=None):  
    if config_name is None:  
        config_name = os.getenv('FLASK_CONFIG', 'production')  
  
    app = Flask('catchat')  
    app.config.from_object(config[config_name])  
    ...
    register_extensions(app)  
    return app  
 
def register_extensions(app):  
    ...  
    socketio.init_app(app)
    
if __name__ == '__main__':  
    app = create_app()  
    socketio.run(app)
```

``` python
extensions.py

from flask_socketio import SocketIO  
  
...
socketio = SocketIO()
```

**Comment by miguelgrinberg** [comment]
A snippet does not help, unfortunately. I have lots of apps that use the `init_app()` style of initialization and they detect eventlet just fine. Can you provide a complete example that I can use to reproduce this issue please?

**Comment by dilless** [comment]
> A snippet does not help, unfortunately. I have lots of apps that use the `init_app()` style of initialization and they detect eventlet just fine. Can you provide a complete example that I can use to reproduce this issue please?

Thanks for your reply. I may have found the problem.
When i use pycharm to run this script, pycharm automaticlly configure the script as flask server. Then i use the system console to run this script, everything goes well.

**Comment by miguelgrinberg** [comment]
Ah okay, so you need to change pycharm to run the app by running the script, not by running `flask run`. That should fix this.
