### ISSUE TITLE
Requests are not handled concurrently deployed with gevent_uwsgi Server

### ISSUE THREAD

**Issue by henkesde** [miguelgrinberg/Flask-SocketIO#1086]
**Your question**
We have the following setup:

* nginx
--> uwgi_pass socket file (unix://)
* uwsgi process started like this: uwsgi -i uwsgi.ini
* uwsgi starting the flask/flask_socketio server

#### nginx config
```
location ~ /socketio-dummy/?(?<rest_url>.*) {
    include uwsgi_params;
    uwsgi_pass      unix:/opt/ls/lx/.web/dev/socks/lx__socket__dev__dhe__dhe.sock;
}
```

#### uwsgi ini
```
[uwsgi]
mount=/socketio-dummy=ls_socketio_dummy.api.app:flask_app

# --------- GENERAL ---------
master=1
pidfile=/tmp/uwsgi__dhe.pid
master-fifo=/tmp/uwsgi__dhe.fifo

# Tell uWSGI to rewrite PATH_INFO and SCRIPT_NAME according to mount-points
manage-script-name=1
socket=unix:/opt/ls/lx/.web/dev/socks/lx__socket__dev__dhe__dhe.sock;
chmod-socket=777

# Allow larger URLs
buffer-size=8192

# These options change the name of the uwsgi-processes in the process-list of Linux (grep processes on 'uWSGI')
auto-procname=1
procname-prefix-spaced=lx_socketio_dummy_dhe

gevent = 1000

```

#### python app
```
flask_app = Flask()
socketio = SocketIO(flask_app)

@socketio.on('test_ping')
def ping(event):
    for i in range(1,6):
        emit('update', i)
        sleep(1)

if __name__ == '__main__':
    def __run_app(host='0.0.0.0', port=8086):
        socketio.run(flask_app, host=host, port=port, log_output=logger)

    run(__run_app, argv=locals().get('argv', None))  # LXScript and py compatible
```

#### used versions
```
Flask==0.12.2
Flask-SocketIO==2.8.5
gevent==1.4.0
uWSGI==2.0.15
```

But with this setup, we don't have any concurreny. 
When we use eventlet (with monkey patching) and start the application using python3 -m (__name__ == '__main__'), this works fine, but we would like to get it running uWSGI because we already have many applications deployed with uWSGI.

Is there a possibility to get this running with uWSGI and gevent?
I know that this is not a problem on Flask-SocketIO, but I have aspiration that you might know the solution quickly.

**Logs**
We see the following line in the uwsgi logs:

```2019-10-24 17:21:30,156 - Server initialized for gevent_uwsgi.```

**Comment by miguelgrinberg** [comment]
Regarding your issue, are you monkey patching on the gevent + uwsgi app? The sleep function that you are using needs to be monkey patched, or else you have to use `gevent.sleep()` or `socketio.sleep()` which will forward the call to the gevent-compatible sleep.

As an additional note, I'm not sure WebSocket will work with your current configuration. My understanding is that uwsgi_pass only supports HTTP proxying. If you want HTTP + WebSocket you will need to switch to proxy_pass, and run your uWSGI  process in HTTP mode. Correct me if I'm wrong about this, it's been a while since I tested this set up, so things may have improved since then.

**Comment by henkesde** [comment]
Hey @miguelgrinberg 

Thanks for your help and for your fast reply. Using gevent sleep does solve the concurrency problem.
Regarding uwsgi_pass, I think this seems to work since I see this in the uwsgi logs: 

```7a83fa7a837a4424807bed43f5fc8a72: Upgrade to websocket successful```

Now, I only have one more problem. The client only receives the emits in batches. Like "Update 1" to "Update 5" messages at once. Do I need to flush the emits somehow or am I missing something else with gevent?

**Comment by miguelgrinberg** [comment]
@henkesde you need to call sleep(0) to release the CPU to other tasks running concurrently.

**Comment by henkesde** [comment]
Hm @miguelgrinberg ,

![socketio](https://user-images.githubusercontent.com/53251944/67669308-ec255100-f971-11e9-9d6c-27408af7e8e0.gif)

On the right site, you see my backend working, doing an emit() and gevent.sleep(0) on each loop (looping is now done by a random subprocess.check_output operation) and on the client, we see the updates only coming all at once. Not sure if I implemented your suggestion to use sleep(0) correctly though.

```
@socketio.on('test_ping')
def ping(event):
    env = ls.getEnv()
    instance = ls.getInstance()

    for i in range(1, 6):
        logger.info('before')
        bash_result = check_output([f". initLXEnv.sh {env} {instance}; echo $CUR_RELEASE; python3 -c 'from ls_config import read_config; print(read_config(\"lx.conf\", config_name=\"instance_disabled\", default=False, encoding=\"utf-8\"))'"],
                                   shell=True).decode('utf-8')
        logger.info('after')
        release = bash_result.splitlines()[0].strip().lower()
        instance_disabled = bash_result.splitlines()[1].strip()
        logger.info(f'{release} - {instance_disabled}')
        emit('update', f'update {i}')
        gevent.sleep(0)
```

**Comment by miguelgrinberg** [comment]
You didn't answer if you are monkey patching. The `check_output()` call also needs the monkey patching as it is blocking.

**Comment by henkesde** [comment]
Hey @miguelgrinberg 

Sorry for my late response, only getting back to this now.

When I add the following code after importing check_output, I still have the same result. 

```
from gevent import monkey
monkey.patch_all()
```

**Comment by miguelgrinberg** [comment]
Have you tried monkey patching at the very top of the script, above all other imports? Sometimes this is necessary.

**Comment by henkesde** [comment]
Just tried it, same result.

The same works when I use eventlet. But we can't just switch to eventlet because we already have a big stack using uWSGI. That's why I will have to get it running with gevent. (We use the same interpreter for our project, so working with eventlet will result in our uWSGI specific stuff not working anymore)

When I remove the check_output and replace gevent.sleep(0) by gevent.sleep(1), I still have the same behaviour as described above.

**Comment by miguelgrinberg** [comment]
I was under the assumption that the check_output call was blocking your server, but if you replace it with sleep(1) and you are still blocking then I don't really know what can be the problem.

You are saying that eventlet works fine. Have you tried using gevent w/o uWSGI? Unfortunately I'm not sure I can help with this, it seems you have hit a problem with either uWSGI or gevent. I don't personally use uWSGI in any of my active projects, but I do use gevent and never had concurrency issues with it, so my guess is that the version of uWSGI that you are using is the culprit.
