### ISSUE TITLE
Integration of socket-io from swagger flask server generator

### ISSUE THREAD

**Issue by selden-lin** [miguelgrinberg/Flask-SocketIO#1087]
**Your question**
Hi, I am using https://editor.swagger.io to generate a flask server and when I try and run the server after adding the socketio.run line in the main file I am getting "AttributeError: 'FlaskApp' object has no attribute 'wsgi_app'". It is because swagger uses a swagger yaml file to setup the flaskApp instead of using a flask object. I am wondering what the wsgi_app attribute is so that I can maybe get around this issue. Running the server normally does not hit this issue. You can replicate this by going to the site and generating a server and then adding     
socketio = SocketIO(app)
socketio.run(app, port=8080)
in the __main__ file in /swagger_server

**Logs**

**Comment by miguelgrinberg** [comment]
Can I see the code that this tool generated for you?

**Comment by selden-lin** [comment]
---
swagger: "2.0"
info:
  description: "Mosaic rest api"
  version: "1.0.0"
  title: "18Q app"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "mosaic.io"
basePath: "/"
tags:
- name: "user"
  description: "user actions"
- name: "supervisor"
  description: "supervisor actions"
schemes:
- "https"
- "http"
paths:
  /user/createRoom:
    post:
      tags:
      - "user"
      summary: "create room with no supervisor and add name to the user table"
      operationId: "create_user_room"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "name"
        description: "name of user"
        required: true
        schema:
          type: "string"
      responses:
        200:
          description: "success"
          schema:
            $ref: "#/definitions/UserAndRoomId"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.user_controller"
  /user/joinRoom:
    post:
      tags:
      - "user"
      summary: "join a room providing user hash and name by adding user to the table"
      operationId: "join_user_room"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "hash of person joining room and room id they will join"
        required: true
        schema:
          $ref: "#/definitions/UserAndRoomId"
      responses:
        405:
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.user_controller"
  /user/submitFeedback:
    post:
      tags:
      - "user"
      summary: "submit feedback to the user table"
      operationId: "submit_feedback"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "user hash and the feedback data"
        required: true
        schema:
          $ref: "#/definitions/UserFeedback"
      responses:
        405:
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.user_controller"
  /user/submitReview:
    post:
      tags:
      - "user"
      summary: "submit review to the users table"
      operationId: "submit_review"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "user hash and review string"
        required: true
        schema:
          $ref: "#/definitions/UserData"
      responses:
        405:
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.user_controller"
  /user/submitQuestion:
    post:
      tags:
      - "user"
      summary: "submit question and have it be judged for meaningfulness and store\
        \ result in table"
      operationId: "submit_question"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "user hash, question number and their answer meaningfulness level"
        required: true
        schema:
          $ref: "#/definitions/UserQuestionData"
      responses:
        405:
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.user_controller"
  /supervisor/createRoom:
    post:
      tags:
      - "supervisor"
      summary: "create a room"
      operationId: "create_supervisor_room"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: ""
        description: ""
        required: true
        schema:
          $ref: "#/definitions/Users"
      responses:
        405:
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.supervisor_controller"
  /supervisor/getUserData:
    get:
      tags:
      - "supervisor"
      summary: "get data for users who are under this supervisor"
      operationId: "get_supervisor_user_data"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "hashId"
        description: "supervisor hash value"
        required: true
        schema:
          type: "string"
      responses:
        200:
          description: "User data for people under the supervisor"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Users"
        404:
          description: "Session not done yet"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.supervisor_controller"
definitions:
  Users:
    type: "object"
    required:
    - "name"
    properties:
      name:
        type: "string"
        description: "name of user"
      passcode:
        type: "string"
        description: "auto generated hash"
      supervisorCode:
        type: "string"
        description: "if room was generated by a supervisor then its filled"
      questionAnswers:
        type: "array"
        items:
          type: "string"
          description: "list of answers for 18qs on how meaningful their responses\
            \ are"
      feedback:
        type: "array"
        items:
          type: "string"
          description: "answers to feedback questions"
      review:
        type: "string"
        description: "answer to what they thought of exercise"
    example:
      feedback:
      - "feedback"
      - "feedback"
      questionAnswers:
      - "questionAnswers"
      - "questionAnswers"
      review: "review"
      name: "name"
      supervisorCode: "supervisorCode"
      passcode: "passcode"
  UserAndRoomId:
    type: "object"
    properties:
      userHash:
        type: "string"
      roomId:
        type: "integer"
    example:
      userHash: "userHash"
      roomId: 0
  UserData:
    type: "object"
    properties:
      data:
        type: "string"
      userHash:
        type: "string"
    example:
      userHash: "userHash"
      data: "data"
  UserFeedback:
    type: "object"
    properties:
      userHash:
        type: "string"
      answers:
        type: "array"
        items:
          type: "string"
    example:
      userHash: "userHash"
      answers:
      - "answers"
      - "answers"
  UserQuestionData:
    type: "object"
    properties:
      userHash:
        type: "string"
      questionNum:
        type: "integer"
      meaningfulnessLevel:
        type: "integer"
    example:
      userHash: "userHash"
      questionNum: 0
      meaningfulnessLevel: 6

**Comment by selden-lin** [comment]
It uses that yaml file to get the app object using this code
```
#!/usr/bin/env python3

import connexion
from flask_socketio import SocketIO
from swagger_server import encoder



def main():
    app = connexion.App(__name__, specification_dir='./swagger/')
    app.app.json_encoder = encoder.JSONEncoder
    app.add_api('swagger.yaml', arguments={'title': '18Q app'})
    socketio = SocketIO(app)
    socketio.run(app, port=8080)

if __name__ == '__main__':
    main()

```

**Comment by miguelgrinberg** [comment]
You have to use `app.app` to access the Flask application wrapped by connexion. Try this:

```python
#!/usr/bin/env python3

import connexion
from flask_socketio import SocketIO
from swagger_server import encoder



def main():
    app = connexion.App(__name__, specification_dir='./swagger/')
    app.app.json_encoder = encoder.JSONEncoder
    app.add_api('swagger.yaml', arguments={'title': '18Q app'})
    socketio = SocketIO(app.app)
    socketio.run(app.app, port=8080)

if __name__ == '__main__':
    main()
```

**Comment by selden-lin** [comment]
Ok thanks, this resolved this
