### ISSUE TITLE
Respond with a 400 error

### ISSUE THREAD

**Issue by jojofeng** [miguelgrinberg/Flask-SocketIO#1089]
**Your question**
Is there a way I can manually trigger a 400 error in an event handler? For example, I'd like to be able to respond with a 400 error upon receiving a `chat_message`. Is there something I could put in my `on_chat_message` handler to send a 400 error to my client? I'm trying to test my client's error-handling behavior. Thank you!

**Comment by miguelgrinberg** [comment]
HTTP responses are not part of the Socket.IO protocol, in fact in most cases clients will be using WebSocket, which is not even HTTP.

A 400 response is triggered during the long polling exchanges and also in the WebSocket connection in certain conditions, but I'm not sure this is what you want, since these are not generated in response to an event.

**Comment by jojofeng** [comment]
Got it, thank you for the quick response!

I'm wondering, then, if there's any way I can force a 400 response in any way on the server, not necessarily in response to a specific event. One of my users received a 400 response with the message `Failed to load resource: the server responded with a status of 400 ()` but was not able to reproduce the issue. I filed a fix that catches "connect_errors" with code 400, but want to try testing to make sure the error is actually caught. Any advice?

**Comment by miguelgrinberg** [comment]
@jojofeng there are several error conditions that generate a 400 error, but these are mostly internal, not something that you can control from the Socket.IO client. One that might work is requesting an invalid transport. The only valid transports are `polling` and `websocket`. If your client allows you send something else, then that will trigger a 400. See https://github.com/miguelgrinberg/python-engineio/blob/master/engineio/server.py#L363.
