### ISSUE TITLE
can not access demo page directly

### ISSUE THREAD

**Issue by chendongxtu** [miguelgrinberg/Flask-SocketIO#1092]
Hi, miguelgrinberg!
    i'm sorry to trouble you again, i have some problems on socketio connections.
the problem's backgroud:
1.  i  use gevent as the async-mode

2. i use multi-workers to deploy my program with k8s

3.  several months ago, the program worked well, i can access the demo page and join or leave room

4.  lately,  i wanna use  ConnectionRefusedError in my connect event, then i push the code to git, and deploy it, when i access the demo page, no message occurred, i can not join or leave room, can not send message, when see the ws, i can see that the channel was not connected(see picture one)

5. then i pulled my master branch and push it to git and  deploy directly, then i access the demo page, the same problem occurred,  unbelieveable!

6. i think maybe something wrong with the package dependency, so i checked the branch which can work correctly ,then  i changed the package version in the branch which can not access  as the same as the branch which  worked well.  then i delpoyed  it and accessed the demo page, the connection was not established too, i am confused!

7.  then i use k8s port-forward command , and access to the demo page(the proj which can not  join or lean room), i can see the consume time, and i can join, leave room ,send msg. how strange it is! i just do not know why this problem happend!

fllowing is the two pics:
pic1: access the demo page directly:
![截图2](https://user-images.githubusercontent.com/32007225/68015928-4f92e400-fcce-11e9-8b7b-a285ff89c0af.png)

pic2:  access the demo page through port-forward
![截图1](https://user-images.githubusercontent.com/32007225/68015920-47d33f80-fcce-11e9-91d6-181855fd2836.png)

can you have any idea, thanks?
here is my requirements content:
```python
alembic==0.9.6
attrs==17.4.0
blinker==1.4
certifi==2017.11.5
chardet==3.0.4
click==6.7
crcmod==1.7
Faker==0.8.9
Flask==0.12.2
Flask-Script==2.0.6
Flask-SQLAlchemy==2.3.2
Flask-Test==0.1.6
Flask-Testing==0.7.1
Flask-WTF==0.14.2
gevent==1.2.2
gevent-websocket==0.10.1
greenlet==0.4.12
gunicorn==19.9.0
itsdangerous==0.24
Jinja2==2.10
jsonref==0.1
jsonschema==2.6.0
MarkupSafe==1.0
pluggy==0.6.0
py==1.5.2
pycrypto==2.6.1
PyJWT==1.5.3
PyMySQL==0.7.11
pytest==3.3.2
PyYAML==3.12
raven==6.4.0
redis==2.10.6
requests==2.18.4
six==1.11.0
SQLAlchemy==1.1.15
Werkzeug==0.13
WTForms==2.1
Flask-Cors==3.0.7
Flask-SocketIO
```

**Comment by miguelgrinberg** [comment]
Do you have logs? The pictures doesn't really say much.

**Comment by chendongxtu** [comment]
no logs. because the websocket connection step was failed(the request not come to the connect event), so i can not get any logs.

**Comment by miguelgrinberg** [comment]
If the websocket connection fails, the logs may provide clues as to why. Please enable logs  in the server and provide a complete session.

**Comment by chendongxtu** [comment]
thx, follow ur advise, i sepcifed a logger obj to the param engineio_logger.
then i started my proj, and watched the ouput log:
```
2019-11-04 15:52:37,337 INFO [/usr/local/lib/python3.6/site-packages/engineio/server.py:331] - http://127.0.0.1:27439 is not an accepted origin.
2019-11-04 15:52:40,881 INFO [/usr/local/lib/python3.6/site-packages/engineio/server.py:331] - https://auction.test.dos.cheanjia.net is not an accepted origin.
2019-11-04 15:53:02,405 INFO [/usr/local/lib/python3.6/site-packages/engineio/server.py:331] - http://127.0.0.1:27439 is not an accepted origin.
2019-11-04 15:53:06,919 INFO [/usr/local/lib/python3.6/site-packages/engineio/server.py:331] - https://auction.test.dos.cheanjia.net is not an accepted origin.
```
it tells me the origin is not accepted cause of cors. but in my code:
```
    db.init_app(app)
    CORS(app, supports_credentials=True)
    socketio.init_app(
        app=app,
        async_mode=async_mode,
        message_queue=app.config["REDIS_URL"],
        channel="auction_car_info_broadcast",
        ping_timeout=10,
        ping_interval=5,
        logger=app.logger,
        engineio_logger=app.logger,
    )
```
i have allowed it
