### ISSUE TITLE
Error Install on Ubuntu 18

### ISSUE THREAD

**Issue by BeVelasco** [miguelgrinberg/Flask-SocketIO#1096]
Hola a todos,
Estoy tratando de instalar en un servidor Ubuntu 18 con npm

 **sudo npm install socket.io**

and the result is the following error

**343 info postuninstall socket.io@2.3.0
344 error Error: No compatible version found: ms@'^2.1.1'
344 error Valid install targets:
344 error ["0.1.0","0.2.0","0.3.0","0.4.0","0.5.0","0.5.1","0.6.0","0.6.1","0.6.2","0.7.0","0.7.1",$
344 error     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:563:10)
344 error     at /usr/local/lib/node_modules/npm/lib/cache.js:478:10
344 error     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js$
344 error     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:218:7
344 error     at Object.oncomplete (fs.js:297:15)
345 error If you need help, you may report this log at:
345 error     <http://github.com/isaacs/npm/issues>
345 error or email it to:
345 error     <npm-@googlegroups.com>
346 error System Linux 4.4.0-164-generic
347 error command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "socket.io" "--save"
348 error cwd /root
349 error node -v v0.8.15
350 error npm -v 1.1.66
351 verbose exit [ 1, true ]**

I hope you can help me solve this problem.

Regards

**Comment by miguelgrinberg** [comment]
Tu problema es con la version Socket.IO de JavaScript. Este es el repositorio de la version Python, que es completamente independiente.
