### ISSUE TITLE
Flask SocketIO can't connect to React Client

### ISSUE THREAD

**Issue by KristofferTolboll2** [miguelgrinberg/Flask-SocketIO#1097]
![image](https://user-images.githubusercontent.com/43782552/68585757-67632880-0483-11ea-904e-338bccf62454.png)

This issue occurs when i try to connect my flask server with socketio to y React client. 

in run.py
`from backend import app
from backend import socketio

if __name__ == '__main__':
    `app.debug` = True
    socketio.run(app, port=5000, debug=True)`

in __init__.py
`socketio = SocketIO(app, cors_allowed_origin="*")`

in my client 
`import openSocket from 'socket.io-client';
import { stringify } from 'querystring';
const socket = openSocket('http://localhost:5000');
`

i tried to make a simple configuration but i can't seem to connect client and server, why is this issue occuring?

**Comment by miguelgrinberg** [comment]
It's `cors_allowed_origins`, in plural.

**Comment by KristofferTolboll2** [comment]
Thank you! I changed it, and i get a 200 response on serverside, but my react client still gives this error
`Access to XMLHttpRequest at 'http://localhost:5000/socket.io/?EIO=3&transport=polling&t=MvUhUYb' from origin 'http://localhost:3000' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.`

Any idea on to why, this is happening, should i add another parameter in `cors_allowed_origins` ?

**Comment by miguelgrinberg** [comment]
@KristofferTolboll2 can you show me the change that you made to how you create your `SocketIO` object?

**Comment by KristofferTolboll2** [comment]
`socketio = SocketIO(app, cors_allowed_origins='*')

@socketio.on('test')
def test(data):
    print("test")
    print(data)
    emit("response", {'data': 'test'})

@socketio.on('send_message')
def on_send_message(data):
    print("Message received")
    print(f'data received was {data}')

`

My socketIO object with some test methods

**Comment by KristofferTolboll2** [comment]
Client side socket

```
const socket = io('http://localhost:5000');

export const sendMessage = (user, content, attachments) =>{
    const data = {
        sender: user,
        content: content, 
        attachments: attachments,
        timeStamp: Date.now()
    }
    try{
        socket.emit('send_message', data)
        const res = socket.emit('test', data)
        return stringify(res)
    }catch(exception){
        return exception
    }
```

**Comment by miguelgrinberg** [comment]
Instead of allowing all origins, which is insecure, try allowing just the origin that you need:

    socketio = SocketIO(app, cors_allowed_origins='http://localhost:5000')

**Comment by duhaime** [comment]
@miguelgrinberg is there truly no way to allow all origins? What if one doesn't know the request origin a priori?

**Comment by miguelgrinberg** [comment]
@duhaime How would you not know the origin? Is this a publicly available API?

**Comment by duhaime** [comment]
Well in my situation for example, I'm on a host behind a VPN that has some DNS rules that expose a public ip / hostname. Normally one can query for the public ip through some external service like https://www.ipify.org/, but the DNS rules in this case are such that the ip returned is in fact a public ip for my host. 

I can `ifconfig` for the public ip and then allow that origin (the server and client run on the same host), but that seems janky. I'm also happy for this API to be public, so long as there aren't some kind of nefarious loopholes whereby chat users can escalate permissions. 

We will likely move the server to another service like EC2, so it'd be great to simply set the socket to bind to any clients that wish to communicate if that's possible. That said, I'm happy to read any docs that you can recommend that might recommend a different strategy...

**Comment by miguelgrinberg** [comment]
> I'm also happy for this API to be public

This is all that matters. If you don't care who connects, then I see no problem in allowing all origins.

**Comment by duhaime** [comment]
Oh Lord have mercy, `SocketIO(app, cors_allowed_origins='*')` is what I was in search of. Thanks very much!
