### ISSUE TITLE
Client keeps reconnecting with a 101 return

### ISSUE THREAD

**Issue by wleev** [miguelgrinberg/Flask-SocketIO#1099]
I have a Dockerized application hosting a Flask and VueJS app, if I run the container locally I get a working SocketIO connection between front-end and back-end ( a single 101 response ). The moment I deploy the container to the production server with an Nginx running on top of it, I keep getting "successful-looking" connections ( 101 response ), but nothing is functional.

I am pretty sure there is some external factor causing it, but I can't find out what. The Nginx configuration is as recommended. How can I possibly debug this, there are no server-side logs of failed or attempted connections and the front-end doesn't complain either.

Nginx config:
```
upstream socket_nodes {
    # Socket.IO requires sticky sessions
    ip_hash;

    server 127.0.0.1:5000;
    # to scale the app, just add more nodes here!
}

map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    listen 443 ssl;

    location / {
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }

    location /socket.io {
        proxy_pass http://socket_nodes;
        proxy_redirect off;
        proxy_buffering off; # Optional
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
    }
}

```

Socket.IO Client config (Vue-SocketIO)

```
Vue.use(new VueSocketio({
  connection: document.location.origin,
  options: {
    secure: true,
    transports: ['websocket']
  }
}))
```

The Flask app is run with Gunicorn and GeventWebSocketWorker.

No errors in the Nginx logs, no errors in Flask, continously repeating connection with 101 response in the front-end. Where should I be looking for the cause?

**Comment by miguelgrinberg** [comment]
You have not provided the information requested in the issue template. Please get logs to help diagnose this problem.

**Comment by wleev** [comment]
The logs were enough to set me on the right way, thank you. 
Even though both front and back-end are hosted on the same URL, I was getting `x is not an accepted origin.` error. Possibly a side-effect of Dockerization?
Removing the `Origin` header in Nginx cleared the issue up for me.

**Comment by miguelgrinberg** [comment]
@wleev: removing the origin header makes you vulnerable to attacks. Basically any client will be able to connect to your service. Best to use the `cors_allowed_origins` option to configure the list of accepted origins.

**Comment by wleev** [comment]
@miguelgrinberg Will do, thanks for the advice.
