### ISSUE TITLE
Providing proper access to Exceptions in on_error handlers

### ISSUE THREAD

**Issue by patrickjahns** [miguelgrinberg/Flask-SocketIO#110]
Right now, the on_error and on_default_error handlers only allow for accessing the value of the exception. This limits the potential to further interact with the Exception. 

Can we provide a way to either give full access to the Exceptions or provide a way to overwrite the exception behavior ?

**Comment by miguelgrinberg** [comment]
What are you looking for specifically? Can't you get all you need from `sys.exc_info()`?

**Comment by patrickjahns** [comment]
Indeed I can access it - sorry didn`t think of accessing it again with `sys.exec_info()`

Yet it seems kind of strange to me, to have an error handling interface that strips down the error to a string and enforce the user to get it back by calling `sys.exec_info()`. 
In my opinion the error should be passed down as is and then left to the user of the library to decide how to manager it - different thoughts on it?

**Comment by miguelgrinberg** [comment]
Sorry, I understand what you mean now. The `value` argument from `sys.exc_info()` is an exception object, it is not the value inside the exception. Or am I incorrect? At least that is how it should be.

The behavior should be the same as with Flask's `errorhandler` decorator, you get the exception object as an argument.

**Comment by patrickjahns** [comment]
You are correct, I debugged the part of my code again and for some odd reason when specifying a custom Error `isinstance(value, CustomError)` always returned false - when checking the Type in pycharms debuuger it showed me that value is Type String and not the exception class. Though when checking sys.exec_info() for the exception class it would show me that the exception was CustomError. 

I`ve run the tests again with standard python exceptions and now `isinstance(value, IOError)` works flawlessly. 

Sorry for misreading the code at that part
