### ISSUE TITLE
Client not receiving out-of-context messages

### ISSUE THREAD

**Issue by jordaniac89** [miguelgrinberg/Flask-SocketIO#1100]
I'm trying to use Flask-SocketIO and have successfully set it up with event handlers

my events.py:

    from .. import socketio

    @socketio.on('joined', namespace='/sync')
    def joined(message):

        emit('status', 'I has entered the room.')

    @socketio.on('do_work', namespace='/sync')
    def do_work(message):

       print('doing work!')
       sync_tickets.SyncTickets.run_script()

    @socketio.on('text', namespace='/sync')
    def text(message):
        emit('text', message)

    @socketio.on('left', namespace='/sync')
    def left(message):
        """Sent by clients when they leave a room.
        A status message is broadcast to all people in the room."""
        room = session.get('room')
        leave_room(room)
        emit('status', {'msg': 'I has left the room.'})

This all works as expected, sending messages back and forth. However, when I try to send a message out-of-context, i.e. in the SyncTickets.run_script like this:
 
    socketio.emit('text', {'msg': 'here is the message!'}, namespace='/sync')

the client does not receive the message. Here is the client event handler:

     var socket;
     $(document).ready(function(){
        socket = io.connect('http://' + document.domain + ':' + location.port + '/sync');
     socket.on('connect', function() {
        socket.emit('joined', {});
     });
     socket.on('text', function(data) {
         console.log('here! ' + data.msg)
         $('#output').html(data.msg)
     });
     $('#do_work').click(function() {
         socket.emit('do_work', {})
     });
    });

my \__init\__.py and run.py are fairly straightforward. I do the: 

    socketio = SocketIO()
    socketio.init_app(app)

in my __init__.py and:
    socketio.run(app)

in my run.py.

the console shows that the messages are being sent:
    
    INFO:socketio.server:emitting event "text" to all [/sync]

but nothing on the client seems to be happening. None of my console.log statements are printed. Note that I also have a SyncTickets.run_script_in_thread() that will spin up the same process in a separate python thread, but this produces the same results.

**Comment by miguelgrinberg** [comment]
Have you enabled logs in the client? The backend is sending the event, so it would be useful to see what happens when the event arrives in the JS client.

**Comment by jordaniac89** [comment]
I went ahead and added debugging on the client with 

`localStorage.debug = 'socket.io-client:socket';`
<img width="870" alt="Screen Shot 2019-11-12 at 1 05 29 PM" src="https://user-images.githubusercontent.com/8006059/68701893-5a127080-054d-11ea-9b50-8871148612cf.png">

I'm still not seeing much of anything on the client side. I see it polling when the server is shut down, then I see where it opens when I bring up the server:

`socket.io-client:socket transport is open - connecting +0ms`

but there's nothing in between until I shut the server down again:

`socket.io-client:socket close (transport close) +1.1m`

**Comment by miguelgrinberg** [comment]
Did you enable all the client logs? socket.io-client is super noisy, it logs a lot of stuff. Your log does not appear to show everything.

**Comment by jordaniac89** [comment]
Ah, ok. So I went ahead and set debug to "*" and it looks better

<img width="1066" alt="Screen Shot 2019-11-12 at 1 21 56 PM" src="https://user-images.githubusercontent.com/8006059/68703106-88914b00-054f-11ea-93d7-adcc172c1101.png">

It looks like it receives the first message I send it 

`engine.io-client:socket socket receive: type "message", data "2/synctickets,["text",{"msg":"15ce04cc771440329c9095ce191fa67b"}]"`

and that logs to the console

`here! 15ce04cc771440329c9095ce191fa67b`

but then the socket connection closes and can't reopen

`engine.io-client:socket socket error {"type":"TransportError","description":0} +8s`

any ideas?

**Comment by miguelgrinberg** [comment]
@jordaniac89 Look in the network tab, or in the JS console for errors.

**Comment by jordaniac89** [comment]
I don't see anything in the network tab past when the page loads up. 

I only see these messages in the server when I kick off the process. No errors.

`
 INFO:socketio.server:emitting event "text" to all [/synctickets]
 INFO:engineio.server:94cbdc5cffea4add951b0fbf45e18381: Sending packet MESSAGE data 2/synctickets,["text",{"msg":"f29c134e262d42e88fd84ab2dd6ee248"}]
`
Nothing really in the console either other than what I attached above. Is it valid to call the emit in the way I showed above? Am I missing anything when I init the app in my __init__py?

**Comment by jordaniac89** [comment]
So I ended up putting a socketio.sleep(1) after my emit and that seemed to fix it. The client is receiving all messages now.

` socketio.emit('text', {'msg': ticket.external_id}, namespace='/synctickets')
   socketio.sleep(1)
`
So two questions.
1) do you know why that happens?
2) if I have other scripts that also need to emit, will it cause performance issues if I have to sleep after every emit?

**Comment by miguelgrinberg** [comment]
@jordaniac89 call `sleep(0)`, no need to add a delay of 1 second.

Unfortunately you simplified your code too much, enough for me to not see that you had a long running and blocking function. I'm also guessing that you missed to show me server-side logs that read something like "client is gone", which occur when a long running blocking function interferes with the background tasks used by Socket.IO. This would coincide with those socket errors in the client.

**Comment by jordaniac89** [comment]
@miguelgrinberg I had seen the "client is gone" message, but not in my most recent tests, especially when I was running the long blocking function in a separate thread. I also monkey patched eventlet which may have helped. Is there a more preferred way to run a long blocking function like that in a separate thread? I'm currently just spinning up a threading.Thread()

**Comment by miguelgrinberg** [comment]
@jordaniac89 blocking functions are mortal enemies of async servers. The preferred way to deal with them is to offload them to separate processes, either via Celery/RedisQueue, the multiprocessing library or something crafted directly with Popen.
