### ISSUE TITLE
SocketIO emit / redis / external process 

### ISSUE THREAD

**Issue by funoverip** [miguelgrinberg/Flask-SocketIO#1104]
Hello, all I need is a confirmation about a feature (I think).
I start playing with scalability and I have a question about message_queue (redis in my case). 

I understand that it is possible to emit message from an external process until it uses the correct message_queue. Ex:

> socketio = SocketIO(message_queue='redis://')
> socketio.emit('my event', {'data': 'foo'}, namespace='/test')

I confirm using `redis-cli` that the messages are crossing my redis server. However, I can't send a message to a dedicated sid (from an external process) using :

`socketio.emit('my event', {'data': 'foo'}, room=mysid, namespace='/test')`

Is it supposed to work ? No specific errors in my logs so, I wonder if there is a bug on my side or if the library simply don't support the `room` parameter in this config. Or maybe I just didn't understand how it works behind the scene.

PS: I use nginx with stiky config (ip_hash) and two flask workers (no gunicorn or similar)

A big thank you for your hard work !

**Comment by miguelgrinberg** [comment]
Yes, a direct message should also work from an external process. Are you sure the sid is correct?

You should enable logs in your two Flask-SocketIO processes and the external process to see where the message is getting lost.

**Comment by funoverip** [comment]
Thanks for the prompt answer.
Yes I'm pretty sure about my sid . One of the two workers is responsible to emit the messages. When running only one worker it works. 

But I'll rewrite my code to create a more simple and dedicated process to handle these messages. It will then be easier to troubleshoot. At least I confirm that the `room=<sid>` is present in the redis queue.

Thanks for the confirmation. Will be back soon to confirm whether or not the issue remains.

**Comment by funoverip** [comment]
Fixed. It was indeed an issue on my side ;)

I use sqlalchemy to maintain my client sid, and since I run an external process, the fresh DB data was not available to other processes yet (so I was indeed using outdated sid values)  

Works like a charms!
