### ISSUE TITLE
emit message from server to client on a particular time using python-socketio

### ISSUE THREAD

**Issue by harsha2041** [miguelgrinberg/Flask-SocketIO#1107]
I want to emit message on a particular time to a particular client. is that possible ??? is possible to make standard connection between client and server in socket io up to that time???

**Comment by miguelgrinberg** [comment]
The connection needs to be made in advance. When the client starts it makes the connection, and then goes into a wait loop. On the server you can use several mechanisms to detect when it is time to notify a given client. Maybe a background thread that wakes up at regular intervals and checks if it is time to send a notification.

**Comment by ninn55** [comment]
@miguelgrinberg Is there another way to implement this instead of background thread.

**Comment by miguelgrinberg** [comment]
@ninn55 cron job?

**Comment by zerocool95** [comment]
Is there any example I can refer to for background threads or cron jobs ?

**Comment by miguelgrinberg** [comment]
@zerocool95 the example app in this repository uses a background thread.

**Comment by zerocool95** [comment]
@miguelgrinberg Thanks that works perfectly. 
Also I wanted to know if we can implement something like a connection between two processes using python-socketio ? For example lets say we have a processes p1 and p2. both are listening to a websocket and at anytime we can send or receive information in a duplex manner without continuously running background thread or cron jobs?

**Comment by miguelgrinberg** [comment]
That would be up to your application to implement, nothing in this package prevents you from doing something like that.
