### ISSUE TITLE
Socket.io error on IOS 

### ISSUE THREAD

**Issue by SystemDiagnosticss** [miguelgrinberg/Flask-SocketIO#1108]
Hello. On IPhone 10 (IOS 13.3) have socket.io error:
` Websocket network error: the operation couldn't be completed. Socket is not connected`
On Android everything works fine
Any idea?

**Comment by miguelgrinberg** [comment]
This repository is for the Python server, I have no participation on the iOS client so I'm not sure I can help with problems there. Sorry.
