### ISSUE TITLE
Keeping a Socket.io connection on in the background

### ISSUE THREAD

**Issue by ricknichols84** [miguelgrinberg/Flask-SocketIO#1111]
**Your question**
I currently have a Tweepy streaming api connected via flask socketio and everything is working fine (tweets are streaming in without any problems). Question: is it possible to configure socketio in such a manner that when a user lands on the webpage, the latest streamed tweets are already showing? Right now, when a user lands on the page, the flask app "loads", and as a result, the screen is blank (as it is waiting to receive new tweets to stream in). Instead, is it possible to keep the stream alive in the background so when a user visits, the latest tweets are already loaded on the page? Thank You

**Comment by miguelgrinberg** [comment]
Yes, but this is something that you need to implement in your application. When you render that initial page you can include enough of the older tweets to fill the page, and then from that point on new tweets are accepted through the Socket.IO connection.
