### ISSUE TITLE
Socket IO 400 Bad request.

### ISSUE THREAD

**Issue by jkam273** [miguelgrinberg/Flask-SocketIO#1112]
https://github.com/miguelgrinberg/Flask-SocketIO/issues/913
Its the same issue. 

I'm having the response headers as follows 
![image](https://user-images.githubusercontent.com/22021007/69767582-d7cfa200-1131-11ea-86f5-a622b3fcdc50.png)

**Comment by miguelgrinberg** [comment]
Did you set the `cors_allowed_origins` option appropriately? If you are accessing your server from another origin you have to configure CORS, the default is to only accept connections from the same origin.

**Comment by jkam273** [comment]
Yeah, I did. 
cors_allowed_origins = '*' is set as the parameter.

**Comment by miguelgrinberg** [comment]
Okay, then you need to get the logs to see what's going on. See https://github.com/miguelgrinberg/Flask-SocketIO/blob/master/.github/ISSUE_TEMPLATE/question.md for instructions on how to enable logs for the server.

**Comment by pistol-whip** [comment]
Hello, I appear to have a similar problem.

```
014b0e32c53344f8a068f16c4468eb90: Sending packet OPEN data {'sid': '014b0e32c53344f8a068f16c4468eb90', 'upgrades': [], 'pingTimeout': 60000, 'pingInterval': 25000}
2019-12-05 14:52:44,601 | [5588] | [DEBUG] | [WebSocket] New connection from 127.0.0.1
014b0e32c53344f8a068f16c4468eb90: Sending packet MESSAGE data 0
014b0e32c53344f8a068f16c4468eb90: Received request to upgrade to websocket
127.0.0.1 - - [2019-12-05 14:52:44] "GET /socket.io/?EIO=3&transport=websocket HTTP/1.1" 400 215 0.000999
```
This is the log output I receive from my Windows testing machine. On Linux everything works as expected.

What is odd with this one, that everything server side works fine.

**Comment by miguelgrinberg** [comment]
@pistol-whip are you sure you are not missing logs? The 400 error should have generated a log line with more information.

**Comment by pistol-whip** [comment]
@miguelgrinberg Thank you for replying.

There is no stacktrace, no further logs, nothing. When adding `logger = True` to the SocketIO constructor, I see that my background task is pushing messages as expected. 

The entire request goes well until it tries to send the response to the client. I went through the logs of all my testing machines and noticed that this is only happening when running the server on Windows (Tested `W. Server 2012`, `W. Server 2019` and `Windows 10`). 

I'am running the Flask server using `gevent` in a spawned process using `multiprocessing`. Next I will try to create a smaller test case to better isolate this issue, hoping that this is an implementation issue by me rather then a Windows one.

**Comment by miguelgrinberg** [comment]
@pistol-whip yes, if you can create a small example that I can use to reproduce the issue here that will be the best way to get to the bottom of this. Thanks!

**Comment by pistol-whip** [comment]
@miguelgrinberg 

I debugged this a bit further and could isolate the issue to the ssl certificates being used. The original testing was going on in a virtual environment embedded in a `CEFPython` browser, thus those errors were not being reported correctly.

When opening the page in a real browser I now get following error:
```
WebSocket connection to 'wss://127.0.01:49350/socket.io/?EIO=3&transport=websocket' failed: Error in connection establishment: net::ERR_CERT_AUTHORITY_INVALID
r.doOpen @ index.js:83
r.open @ index.js:83
r.open @ index.js:83
r @ index.js:83
r @ index.js:83
r.open.r.connect @ index.js:83
(anonymous) @ index.js:83
```

The certificates are self signed from our internal CA as the client is directly connecting to an API node which is not available outside of our internal network.

I guess this is a "bug" in SocketIO itself. Sorry for wasting your time.

**Comment by jkam273** [comment]
![image](https://user-images.githubusercontent.com/22021007/70671037-9bbb3780-1c2f-11ea-8ba8-30c087ba3fdd.png)

**Comment by jkam273** [comment]
Keep getting logs like these @miguelgrinberg 
No log that shows any sign of some errors happening on server or in the client.

**Comment by miguelgrinberg** [comment]
@jkam273 did you also set `engineio_logger=True`? That adds lower level logs.

**Comment by jkam273** [comment]
This error got resolved. Thanks @miguelgrinberg for letting me know about those logs.

**Comment by jkam273** [comment]
Closing the issue.

**Comment by jkam273** [comment]
Closing Issue !
