### ISSUE TITLE
Disconnect one of two socket connections cause key error exception

### ISSUE THREAD

**Issue by YuqiaoS** [miguelgrinberg/Flask-SocketIO#1113]
**Describe the bug**
On having two browser tabs open with a websocket for each, a request from the frontend to call disconnect() in one connection result in the following exception in the logs..

> INFO:app:DISCONNECTED: b9b4ba36ceb94b3284aedb6f4c9552ab
> INFO:engineio.server:b9b4ba36ceb94b3284aedb6f4c9552ab: Sending packet CLOSE data None
> ::1,127.0.0.1 - - [28/Nov/2019 18:23:47] "GET /socket.io/?EIO=3&transport=websocket&sid=b9b4ba36ceb94b3284aedb6f4c9552ab HTTP/1.1" 200 0 6.270760
> Exception in thread Thread-146:
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.5/threading.py", line 862, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/flask-socketio/venv/lib/python3.5/site-packages/socketio/server.py", line 648, in _handle_event_internal
>     r = server._trigger_event(data[0], namespace, sid, *data[1:])
>   File "/home/flask-socketio/venv/lib/python3.5/site-packages/socketio/server.py", line 677, in _trigger_event
>     return self.handlers[namespace][event](*args)
>   File "/home/flask-socketio/venv/lib/python3.5/site-packages/flask_socketio/__init__.py", line 284, in _handler
>     *args)
>   File "/home/flask-socketio/venv/lib/python3.5/site-packages/flask_socketio/__init__.py", line 698, in _handle_event
>     ret = handler(*args)
>   File "/home/flask-socketio/app/auth/api.py", line 118, in logout
>     disconnect()
>   File "/home/flask-socketio/venv/lib/python3.5/site-packages/flask_socketio/__init__.py", line 922, in disconnect
>     return socketio.server.disconnect(sid, namespace=namespace)
>   File "/home/flask-socketio/venv/lib/python3.5/site-packages/socketio/server.py", line 508, in disconnect
>     self.eio.disconnect(sid)
>   File "/home/flask-socketio/venv/lib/python3.5/site-packages/engineio/server.py", line 283, in disconnect
>     del self.sockets[sid]
> KeyError: 'b9b4ba36ceb94b3284aedb6f4c9552ab'
> 

Additionally:
And this also doesn't logout the user with flask-session extension for the other connection. On refreshing the first disconnected page, I can login again by refreshing. This means the server side session isn't working very well...I feel that I've tested this before and the session gets updated across the different connections correctly before. There may be some updates in some plugins that's causing issues. 

Does anyone else have this issue?

**To Reproduce**
```
eventlet                      0.25.1   
Flask                         1.1.1
Flask-Cors                    3.0.8    
Flask-Login                   0.4.1  
Flask-Session                 0.3.1    
Flask-SocketIO                4.2.1  
python-socketio               4.3.1  
python-engineio               3.9.3    (btw, updating this to 3.9.10 seems to cause connection event not detected on the clientside)
```

1. Open two browser tabs, or simply make two websocket connections.
2. Disconnect one of them from the backend using disconnect() (by sending in a logout request for example)

My code for the logout event handler:
```
    logout_user() // flask-login + flask-session
    disconnect()
```

**Comment by miguelgrinberg** [comment]
There is a fix for the KeyError that you are having in the master branch of python-engineio. I haven't cut an official release with this fix yet, so please try master and let me know if that helps.

**Comment by YuqiaoS** [comment]
I still this this happening. Sometimes it happens on one page too. After a few refreshes and attempt to disconnect, this may go away.

**Comment by YuqiaoS** [comment]
Ok, both the exception and the flask-session / flask-login issue seem to be resolved on the latest master https://github.com/miguelgrinberg/python-engineio/commit/b714f81a0ee27e30070a5ca702a1823236df9981
