### ISSUE TITLE
Flask Socket io does not work 

### ISSUE THREAD

**Issue by Lena-Liwen-Tian** [miguelgrinberg/Flask-SocketIO#1114]
I tried to involve flask-socket io in my application. I tried a lot of methods but it still does not work.

I attached my codes here.
chat.html
![image](https://user-images.githubusercontent.com/49572193/69819462-af44b800-11c4-11ea-93a7-faa5de447674.png)
main.py
![image](https://user-images.githubusercontent.com/49572193/69819593-e31fdd80-11c4-11ea-9f9c-6fc1bb7056f4.png)
events.py
![image](https://user-images.githubusercontent.com/49572193/69819666-0480c980-11c5-11ea-879f-408a76b3f5b9.png)
__init__.py
![image](https://user-images.githubusercontent.com/49572193/69819720-1c584d80-11c5-11ea-8b70-6fa2a0882539.png)
run.py
![image](https://user-images.githubusercontent.com/49572193/69819740-24b08880-11c5-11ea-9077-f7ed389529ee.png)

i cannot detect any changes on the web. 
I get the result as follows:
![image](https://user-images.githubusercontent.com/49572193/69819976-ab656580-11c5-11ea-94b9-04adb88530ea.png)

**Comment by miguelgrinberg** [comment]
Sorry, but I'm not sure how I can help you. The screenshots aren't very useful, I cannot debug your application with screenshots. You also haven't provided the logs that the bug report asks you to provide on the client and server sides.

**Comment by Lena-Liwen-Tian** [comment]
Sorry, I just started learning it. What kind of information will be helpful for you to debug? and what is "the logs that the bug report asks to provide?"
Thank you so much!

**Comment by Lena-Liwen-Tian** [comment]
![image](https://user-images.githubusercontent.com/49572193/69835906-86471600-120a-11ea-8cf8-d3a277b38205.png)
Is this helpful?

**Comment by Lena-Liwen-Tian** [comment]
I just solved this problem.
I would appreciate it if you could give me some explanations.
In my run.py file, I just deleted the line db.create_all(app=create_app()) and then the app works.
Do you know why?
![image](https://user-images.githubusercontent.com/49572193/69836802-f48ed700-1210-11ea-9573-eb51cd8a47d6.png)

**Comment by miguelgrinberg** [comment]
Sorry, but I'm still completely in the dark. You haven't really described the problem outside of "does not work", so I'm not even sure what to look for.

The line that you commented out uses the `create_all()` method, which takes no arguments, but you were sending `app`. Try calling `db.create_all()` instead.
