### ISSUE TITLE
Problem with using flasksocket-io and NLB in AWS

### ISSUE THREAD

**Issue by ecda909** [miguelgrinberg/Flask-SocketIO#1115]
**Issue**

I am having an issue with my Flask app and getting a 400 BAD REQUEST error when running a NLB in front of the app that has SSL in place. The application uses NGINX + GUNICORN and runs perfectly fine when using http without a Load Balancer attached. My gunicorn command for launching is gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 app:app and the the NGINX config is:

server {

    listen [::]:80;
    listen 80;
    server_name www.<domain_name>.com;
    access_log  /var/log/nginx/access.log;
    location / {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_pass http://0.0.0.0:8080;
        include proxy_params;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 300s;
        proxy_connect_timeout 75s;
        proxy_headers_hash_bucket_size 128;
        proxy_headers_hash_max_size 1024;
    }
    location /socket.io {
        include proxy_params;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass http://0.0.0.0:8080/socket.io;
    }
}

The NLB Listener config is setup for TLS on 443 and has a target group behind it which is set to 80 directed at the ec2 instance. I have also tried ALB with the same configuration and received the same error.

**Logs**

Failed to load resource: the server responded with a status of 400 (BAD REQUEST)
socket.io/?EIO=3&transport=polling&t=MwzUGRh&sid=797b34925cad4ebc92d678f458ef1cbd:1 Failed to load resource: the server responded with a status of 400 (BAD REQUEST)
index.js:83 POST https://www.<domain_name>/socket.io/?EIO=3&transport=polling&t=MwzUN4c&sid=fee2b2387d964e7381660a351a8f1604 400 (BAD 
index.js:83 POST https://www.<domain_name>.com/socket.io/?EIO=3&transport=polling&t=MwzUNSC&sid=fee2b2387d964e7381660a351a8f1604 400 (BAD REQUEST)

Any help would be greatly appreciated!

**Comment by miguelgrinberg** [comment]
The logs that you included are just the ones from the web server. If you enable the Socket.IO logs you will see more specific information. But in any case, I suspect the problem is related to having multiple workers under the load balancer. This is only supported when the load balancer uses sticky sessions, which I believe are not used in NLB.

**Comment by ecda909** [comment]
So I switched to an ALB and enabled stickiness for 10 minutes. These are the access logs from nginx:

10.192.11.73 - - [01/Dec/2019:00:22:45 +0000] "GET /socket.io/?EIO=3&transport=websocket&sid=e1624605dd0747918d02a6c91e5135ac HTTP/1.1" 101 2 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
10.192.22.154 - - [01/Dec/2019:00:22:47 +0000] "GET /socket.io/?EIO=3&transport=polling&t=Mw-rRT2&sid=982ef72b310b445c9577d7527c3c91f8 HTTP/1.1" 504 569 "https://www.<domain_name>.com/vote" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
10.192.22.154 - - [01/Dec/2019:00:22:49 +0000] "GET /socket.io/?EIO=3&transport=polling&t=Mw-rS3s&sid=e304f4f30fe1481e89ec8ef90e82e31b HTTP/1.1" 499 0 "https://www.<domain_name>.com/vote" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
10.192.22.154 - - [01/Dec/2019:00:23:05 +0000] "GET / HTTP/1.1" 200 53323 "-" "ELB-HealthChecker/2.0"
10.192.11.73 - - [01/Dec/2019:00:23:06 +0000] "GET / HTTP/1.1" 200 53322 "-" "ELB-HealthChecker/2.0"
10.192.22.154 - - [01/Dec/2019:00:23:11 +0000] "POST /socket.io/?EIO=3&transport=polling&t=Mw-rm0K&sid=e1624605dd0747918d02a6c91e5135ac HTTP/1.1" 400 11 "https://www.<domain_name>.com/vote" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
10.192.22.154 - - [01/Dec/2019:00:23:13 +0000] "POST /socket.io/?EIO=3&transport=polling&t=Mw-rmMp&sid=e1624605dd0747918d02a6c91e5135ac HTTP/1.1" 400 11 "https://www.<domain_name>.com/vote" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
10.192.22.154 - - [01/Dec/2019:00:23:14 +0000] "GET /socket.io/?EIO=3&transport=polling&t=Mw-rmo3 HTTP/1.1" 200 119 "https://www.<domain_name>.com/vote" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
10.192.22.154 - - [01/Dec/2019:00:23:15 +0000] "GET /socket.io/?EIO=3&transport=websocket&sid=496ecbf265f148ddb71d0a1329654b01 HTTP/1.1" 101 2 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
10.192.22.154 - - [01/Dec/2019:00:23:18 +0000] "GET /socket.io/?EIO=3&transport=polling&t=Mw-rYxi&sid=4e12112e1efd4ecea6c684ca897d4186 HTTP/1.1" 499 0 "https://www.<domain_name>.com/vote" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"

and these are the logs from the browser console:

POST https://www.<domain_name>.com/socket.io/?EIO=3&transport=polling&t=Mw-rND7&sid=ae5c05a513e041c295bf4e481b0123d9 400
index.js:83 POST https://www.<domain_name>.com/socket.io/?EIO=3&transport=polling&t=Mw-rNDu&sid=ae5c05a513e041c295bf4e481b0123d9 400

**Comment by ecda909** [comment]
I am also getting the issue when I remove the load balancer and solely run falsk socketio through NGINX's ssl config. NGINX config for that is:
server {
    server_name www.<name>.com;
    access_log  /var/log/nginx/access.log;
    location / {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_pass http://0.0.0.0:8080;
        include proxy_params;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 300s;
        proxy_connect_timeout 75s;
        proxy_headers_hash_bucket_size 128;
        proxy_headers_hash_max_size 1024;
ubuntu@ip-10-192-11-187:/etc/nginx/conf.d$ cat <name>.conf
server {
    server_name www.<name>.com;
    access_log  /var/log/nginx/access.log;
    location / {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_pass http://0.0.0.0:8080;
        include proxy_params;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 300s;
        proxy_connect_timeout 75s;
        proxy_headers_hash_bucket_size 128;
        proxy_headers_hash_max_size 1024;
    }
    location /socket.io {
        include proxy_params;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass http://0.0.0.0:8080/socket.io;
    }

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/www.<name>.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/www.<name>.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = www.<name>.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen [::]:80;
    listen 80;
    server_name www.<name>.com;
    return 404; # managed by Certbot
}

and my flask socket io config (Client side test) is:

 var socket = io();
 socket.on('connect', function () {
            console.log('I am connected')
        });

And error logs are:

index.js:83 POST https://www.<name>.com/socket.io/?EIO=3&transport=polling&t=Mw-tsM5&sid=4acf98cdefe243338b29c6f9f93ef51d 400 (BAD REQUEST)
index.js:83 POST https://www.<name>.com/socket.io/?EIO=3&transport=polling&t=Mw-tsMw&sid=4acf98cdefe243338b29c6f9f93ef51d 400 (BAD REQUEST)

I'm just trying different things, if I can get it to work with or without the load balancer, its fine...

**Comment by miguelgrinberg** [comment]
You are ignoring my request to enable Socket.IO logs, none of the logs you are showing me have the information that I'm asking to see. Review again the issue template that you were presented when you wrote this bug: https://github.com/miguelgrinberg/Flask-SocketIO/blob/master/.github/ISSUE_TEMPLATE/bug_report.md.

**Comment by ecda909** [comment]
My apologies, Im sorry I forgot to include those. These are the logs from Socket.IO:

```
Server initialized for gevent.
3d6a744c62dc491dac03b1303359f588: Sending packet OPEN data {'pingInterval': 25000, 'pingTimeout': 60000, 'upgrades': ['websocket'], 'sid': '3d6a744c62dc491dac03b1303359f588'}
3d6a744c62dc491dac03b1303359f588: Sending packet MESSAGE data 0
https://www.edersdevdomain.com is not an accepted origin.
4c6f8f84b212400a8330f9e15f154d03: Sending packet OPEN data {'pingInterval': 25000, 'pingTimeout': 60000, 'upgrades': ['websocket'], 'sid': '4c6f8f84b212400a8330f9e15f154d03'}
4c6f8f84b212400a8330f9e15f154d03: Sending packet MESSAGE data 0
https://www.edersdevdomain.com is not an accepted origin.
https://www.edersdevdomain.com is not an accepted origin.
https://www.edersdevdomain.com is not an accepted origin.
56bf564503cc4d529b18dd24540c4014: Sending packet OPEN data {'pingInterval': 25000, 'pingTimeout': 60000, 'upgrades': ['websocket'], 'sid': '56bf564503cc4d529b18dd24540c4014'}
56bf564503cc4d529b18dd24540c4014: Sending packet MESSAGE data 0
https://www.edersdevdomain.com is not an accepted origin.
```
Steps to Reproduce:

1. Go to https://www.edersdevdomain.com/vote 
2. Sign-in with this temporary account I've created:
username: troubleuser12
password: Testadd241!
3. You'll, be redirect to a 404 page, just go back to https://www.edersdevdomain.com/vote and you will be signed in. 
4. From here, you can press the up or down arrow on any album.

Expected Outcome:

When pressing the up or down arrows the vote numbers should change depending on what you click on.

**Comment by miguelgrinberg** [comment]
Add `cors_allowed_origins='https://www.edersdevdomain.com'` to your `SocketIO()` constructor to avoid the cross-origin error.

**Comment by ecda909** [comment]
Wow, it works! Thank you so much. Is that in the flask socketio documentation anywhere?

**Comment by miguelgrinberg** [comment]
@ecda909 the CORS options are documented, but for most people the defaults work just fine. In your case, something that you are doing in your reverse proxy or load balancer is preventing the public hostname of your server from reaching the Flask application. For that reason Flask-SocketIO believes the requests are coming from a different origin.

**Comment by ecda909** [comment]
That makes perfect sense. Thank you, for helping me I've been stuck for a while.
