### ISSUE TITLE
Eventlet Production Server

### ISSUE THREAD

**Issue by leveraction** [miguelgrinberg/Flask-SocketIO#1116]
I am very new to trying to host a web page and feel that I may be missing something very basic.  I am trying to use the eventlet embedded server to host (just on my LAN at this point) my Flask application on port 80.  Works fine on 5000, but I get permissions errors for 80.  My understanding is that the OS won't allow a script to be run as root.

In the docs is says:

> The simplest deployment strategy is to have eventlet or gevent installed, and start the web server by calling socketio.run(app) as shown in examples above. This will run the application on the eventlet or gevent web servers, whichever is installed.
> 
> Note that socketio.run(app) runs a production ready server when eventlet or gevent are installed.
> 

Ok, so how do you user eventlet's production ready server on port 80 since we are not using something like Nginx as a proxy in this case?

**Comment by miguelgrinberg** [comment]
If you want to run the eventlet server directly on port 80 you have to run your application as root. It's not a recommended thing to do because the script running as root will have permission to do anything on the system, but regardless of the risk, this is possible, not sure why you thought that is not allowed.

**Comment by leveraction** [comment]
So what is the recommended way to use eventlet as a production web server on port 80 if not running app.py as root?

**Comment by miguelgrinberg** [comment]
The normal thing to do is to run a reverse proxy on port 80 and the application on a high port running as a non-root user. That protects you first against bugs in your app that can damage the system, and second, in case your app is compromised the attacker doesn't get root access.

**Comment by leveraction** [comment]
OK, so with all that it looks like I will have to move this project from EBS to straight EC2 and set it up manually.  Thanks for the help.
