### ISSUE TITLE
socket port stayed open but can't be found in order to be closed

### ISSUE THREAD

**Issue by fonty422** [miguelgrinberg/Flask-SocketIO#1119]
I don't believe it's a bug, probably just bad code on my part, but i was using eventlet, but it had issues with threads sending an emit on 1Hz being sporadic. Tried the direct threading version (while 
in developement) and couldn't remove the logging from client polling, so tried gevent... then things went strange.
Ran wonderfully the first time, crtl+c to stop the server, add a bit of code, start again and got the `Only one usage of each socket address (protocol/network address/port) is normally permitted: ('0.0.0.0', 9000)` response. Couldn't close it down, so figured I can just reboot the computer... but the same issue came up again.
Even more strange is that if it run a `netstat` command (windows 10), there is nothing on port 9000 anywhere. Can't find it, can't close it, can't run the app. I'm not prepared to try a new port just in case that also refuses to close.
Thoughts?

**Comment by fonty422** [comment]
In addition, I attempted to revert to threading and eventlet to see if they could resolve it, but nope.
I then turned the pc off for 10 minutes, then back ok and still it says it's already in use, but i still can't see it using `netstat`

**Comment by fonty422** [comment]
Decided to run a brand new app on the same port - super simple with no functionality and it works fine.
Closed it gracefully, restarted it a few times, just fine.
Tried to run the old version - crash with the same problem. Stripped it way back line-by-line, and it started working. I honestly couldn't anything i what i took out that would have caused it to stop. But it's working again... for now.

**Comment by miguelgrinberg** [comment]
@fonty422 one guess is that you were starting two servers on the same app, so regardless of the port you would always hit this problem on the second instance of the server.

**Comment by fonty422** [comment]
Yeah, i figured that must be the problem, but no where in the code was running the app other than in the __main__ function of one part. Although importing a master defined socketio object might be a the root of the problem? Especially if multiple other scripts need to access that variable?

**Comment by miguelgrinberg** [comment]
@fonty422 I haven't seen your code, I can't really say. If you have the server start statement in the global scope it might run twice.
