### ISSUE TITLE
Greenlet exception after client disconnect

### ISSUE THREAD

**Issue by ktoh** [miguelgrinberg/Flask-SocketIO#112]
First, Miguel I bought your book on [Flask Development](http://www.amazon.com/Flask-Web-Development-Developing-Applications/dp/1449372627), it's great!

I'm running Flask-SocketIO (github master) with gunicorn (18.0), and am encountering the following exception after client disconnects:

```
Client disconnected
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/eventlet/hubs/hub.py", line 346, in fire_timers
    timer()
  File "/usr/local/lib/python2.7/dist-packages/eventlet/hubs/timer.py", line 56, in __call__
    cb(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/eventlet/event.py", line 163, in _do_send
    waiter.switch(result)
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 331, in run
    self._report_result(result)
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 306, in _report_result
    self._notifier = self.parent.loop.run_callback(self._notify_links)
AttributeError: 'greenlet.greenlet' object has no attribute 'loop'
```

As a result the gunicorn worker process terminates.
I don't know where to start debugging this as this is popping up in an inner dependency (Flask-SocketIO -> gevent -> greenlet) in an asynchronous event.  

Has anyone else encountered this problem, or would you have pointers around how I can figure out what is going on here?

As a side issue, I'm not sure why my clients keep disconnecting as I've set the `gunicorn --timeout` parameter to some very large number.

thanks!

**Comment by miguelgrinberg** [comment]
I have never seen this error. Does it also happen on a normal disconnect, for example when a user closes the browser? Does it happen with the example application?

**Comment by ktoh** [comment]
I'm closing this as the error mysteriously (and disturbingly) stopped showing up.  Will report back if it re-occurs.

**Comment by taizo** [comment]
I've also experienced a similar error with the following modules.

```requirements.txt
Flask==0.10.1
gevent==1.0.2
greenlet==0.4.7
gunicorn==19.3.0      # worker_class = 'gevent'
supervisor==3.1.3
```

In a few minutes after the error occurred, my web application didn't answer anymore, so I had to terminate processes manually. It's because the processes couldn't be stopped even if using supervisorctl command.

```python
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/eventlet/hubs/poll.py", line 115, in wait
    listener.cb(fileno)
  File "/usr/local/lib/python2.7/site-packages/gevent/greenlet.py", line 331, in run
    self._report_result(result)
  File "/usr/local/lib/python2.7/site-packages/gevent/greenlet.py", line 306, in _report_result
    self._notifier = self.parent.loop.run_callback(self._notify_links)
AttributeError: 'greenlet.greenlet' object has no attribute 'loop'
Removing descriptor: 18
```

**Comment by gposton** [comment]
We're seeing this as well (using gevent inside celery tasks)

**Comment by ktoh** [comment]
@gposton in my case I tracked it down to a conflict with another coroutine module (in my case,  `eventlet`) which was competing for the same resource loop and ended up doing bad things.

I removed the dependency (by using gevent only) and it went away. HTH.

**Comment by gposton** [comment]
Thanks @ktoh, we had the exact same issue.... but went the other direction and removed gevent to resolve.
