### ISSUE TITLE
greenle.error: cannot switch to another thread

### ISSUE THREAD

**Issue by Puyodead1** [miguelgrinberg/Flask-SocketIO#1120]
Hello,
I'm trying to add flask_socketio to an existing Flask app that is ontop of a discord.py bot.
I can get a client to connect and emit fine from the main file, but when i want to emit from another file, an error is thrown:
```
Traceback (most recent call last):
  File "C:\Users\Puyodead1\AppData\Local\Programs\Python\Python38-32\lib\site-packages\eventlet\queue.py", line 118, in switch
    self.greenlet.switch(value)
greenlet.error: cannot switch to a different thread
```

I've tried attaching the socket instance to builtins (and directly to the bot instance) and using it in another file, the reason is because discord.py has events that i want to trigger an emit on the socket to update a website. If i try using the socket that is attached to the bot instance (which is passed to the file by discord.py), with the engineio_logger set to true, the console shows that a message is being emitted with the data but the client doesn't recieve it at times. The greenlet errors is thrown when I try using the socket that is attached to builtins.

Here are my code snippets:
- Client Code:
```Javascript
<script type="text/javascript" charset="utf-8">
    let socket = io("http://127.0.0.1:5001");
    socket.on('connect', function() {
        console.log("Connected to WebSocket!");
    });
    socket.on("user count", function (data) {
        console.log(data);
        $("#user-count").text(data["users"]);
    });
</script>
```
- Server Code:
```Py
# get asyncio loop
loop = asyncio.get_event_loop()
# i have this as thread=False because otherwise it hangs the entire application
eventlet.monkey_patch(thread=False)

app = Flask(__name__)

# cors is on here because the client dev console is spammed with errors about it not being there
socketio = SocketIO(app, cors_allowed_origins="*",
                    engineio_logger=True)
bot = commands.Bot(...)
bot.socket = socketio

# Ready event
@bot.event
async def on_ready():
    bot.startedAt = time.time()
    getLogger().info(f'Logged in as {bot.user}')

	# create partial for flask server/socketio, this is because without it, the discord bot doesnt get started
    partial_run = partial(socketio.run, app=app, debug=True, host=os.getenv("API_HOST"), port=os.getenv("API_PORT"),
                          use_reloader=False)

	# just a class to start a thread with the partial
    APIServer(partial_run).start()

@socketio.on('connect')
def connected():
    # this part works fine
    socketio.emit("user count", {"users": len(bot.users)})

bot.login(os.getenv("TOKEN"))
```
- Cog (the event file) Code:
```Py
class GuildEventsCog(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
 
    @commands.Cog.listener()
    async def on_member_join(self, member):
        self.bot.socket.emit("user count", {"users": len(self.bot.users)})
```

I hope this is explanitory enough.
I've spent a few hours trying different things, and looking throught other issues but couldn't find a solution yet. Any help would be appricated.

Edit: I don't know if this is relevant, but the client console also shows these errors:
![image](https://user-images.githubusercontent.com/14828766/70397534-10e4fd80-19e1-11ea-8069-013859e309f8.png)

**Comment by miguelgrinberg** [comment]
If you do anything with threads, you typically need to monkey patch threading so that it becomes compatible with eventlet. I suggest you investigate the problem that occurs when you monkey patch.

**Comment by Puyodead1** [comment]
Do you have an idea as to how I could monkey patch threading?

**Comment by miguelgrinberg** [comment]
You explicitly disabled the monkey patching of threads:

    eventlet.monkey_patch(thread=False)

My guess is that this is related to your problem.

**Comment by Puyodead1** [comment]
Ah, I see what you mean now. The reason I had to do that was because it was hanging the application. I'll look into it more. Thank you!
