### ISSUE TITLE
Disabling Flask-SocketIO without removing from environment

### ISSUE THREAD

**Issue by akragan** [miguelgrinberg/Flask-SocketIO#1122]
What is the way to disable Flask-SocketIO extension  (so that it does not take over "flask run") without removing it from the Python environment.
We have a few apps (blueprints) being served from the same flask project but only one of them uses flask-socketio.  Wouldn't want to have to vary python environment between them.
However it seems that once installed in the python environment it takes over "flask run" even if it's not imported into the app's code.

**Comment by akragan** [comment]
Actually it works with FLASK_DEBUG=0
With FLASK_DEBUG=1 it throws (using version 3.1.2 py36)

I just found this thread
https://github.com/miguelgrinberg/Flask-SocketIO/issues/817
which suggests using version 3.2.0
I'll give it a spin

**Comment by akragan** [comment]
3.3.2 seems to work fine with FLASK_DEBUG=1

**Comment by miguelgrinberg** [comment]
Current versions of this package do not override `flask run` anymore.
