### ISSUE TITLE
I can't see any data in my redis,how can know it working?

### ISSUE THREAD

**Issue by huaSoftware** [miguelgrinberg/Flask-SocketIO#1123]
**Your question**
The redis connect is success, program is working.But i can't see any data in my redis. 

**connect code**
```
from gevent import monkey
monkey.patch_all(select=True, socket=True)
async_mode = 'gevent'
socketio = SocketIO(app, message_queue="redis://:{}@{}:{}/{}".format(REDIS_PAS,REDIS_IP,REDIS_PORT,REDIS_DB), async_mode=async_mode, logger=True, engineio_logger=True,cors_allowed_origins="*")
```
**redis picture**

**Comment by huaSoftware** [comment]
I think queue use redis pub / sub from document .But how can see it in redis ?

**Comment by miguelgrinberg** [comment]
What do you need to see in Redis? The system uses redis pub/sub for communication. You can watch the `socketio` channel if you like to see the traffic, but there is nothing you need to do directly on Redis.

**Comment by huaSoftware** [comment]
Okay,I try to watch the socketio channel. Thanks a lot.
