### ISSUE TITLE
worker timeout restarts gunicorn server with react app client

### ISSUE THREAD

**Issue by arendeutsch** [miguelgrinberg/Flask-SocketIO#1124]
Hello,
I hope someone can help me with an issue i've been having.
I have a react app and a flask restful application running on a raspberry pi. when the a component is mount a socket connection is establish and a thread is starting according to the example in the master branch here sending information to the client with a 0.1 delay.

Everything works fine BUT sometimes when the component is mount and a open socket is sent from the client i get  enginio.server Ivalid session which result in critical worker timeout. This causes to the gunicorn server to restart. 

I've tried different different init configurations such as always connect and changing the async mode but nothing seems to help. Once in a while it happens and i cant figure out why

**Comment by miguelgrinberg** [comment]
You haven't provided the details requested in the bug template, in particular this:

**Logs**
Please provide relevant logs from the server and the client. On the server, add the `logger=True` and `engineio_logger=True` arguments to your `SockertIO()` object to get logs dumped on your terminal. The same arguments can be used on the [python-socketio's client](https://github.com/miguelgrinberg/python-socketio). If you are using the JavaScript client, see [here](https://socket.io/docs/logging-and-debugging/) for how to enable logs.

**Comment by arendeutsch** [comment]
Hei Miguel,
Here is how I initiate the socket on the server side.
socketio = SocketIO(logger=True, engineio_logger=True)
socketio.init_app(app, async_mode='threading', cors_allowed_origins='*')
I'm attaching two images that shows the log from the client and the server.

It's worth noting that this happens much more frequently when I use two sockets connections, one foe each page. But it also happened few times when I only used one socket connection (drift) which was started when the component was mounted and disconnected when the component unmounted from the page.
Really hope that helps, please let me know if there is anything else I should try

![client-socket-log](https://user-images.githubusercontent.com/17125449/70892592-c3bce900-1fe9-11ea-8616-ea36add6f58a.png)
![client-server-log](https://user-images.githubusercontent.com/17125449/70892594-c61f4300-1fe9-11ea-99eb-8067f58406b0.png)

**Comment by miguelgrinberg** [comment]
The invalid session error occurs because the client was disconnected, and after that the server received more messages from it. Did your application trigger this disconnect? Note that there was a "leave" event right before this happened.

**Comment by arendeutsch** [comment]
Yes. Thats true, the application triggered a disconnect (leave message to the server) which then stops the thread and disconnect the socket. Is that a faulty way of doing it ? 
Would it be better not to emit a disconnect message (leave) from the client ?

**Comment by miguelgrinberg** [comment]
@arendeutsch the problem is that your client continues to communicate with the server after being disconnected, so I suspect there is a race condition there, where client sends the `leave` event, but continues to emit events to the server. At some point the server executes the disconnect, and later receives some leftover events the client sent out.
