### ISSUE TITLE
socketio emit not working in the loop

### ISSUE THREAD

**Issue by sathishsatzy** [miguelgrinberg/Flask-SocketIO#1125]
Hi miguelgrinberg,
           I am trying to emit a message continuously from python flask-socketio server to client, but i receive only one message from server and i replaced the infinite loop into countable with 10 iterations this scenario also first i got one message atlast of the loop only i got the remaining 9 messages in client not in continuous manner, let me suggest how to do that as possible ?

Server code :
```
from flask import Flask,request
from flask_socketio import SocketIO

app = Flask(__name__)
app.config['SECRET_KEY'] = 'mysecret'
socketio = SocketIO(app)

@socketio.on('server')
def sendmessage():
 while True:
  socketio.emit('client' , 'hi')
  socketio.sleep(2)

@socketio.on('connect')
def connect():
    print('client connected',request.sid)

@socketio.on('disconnect')
def disconnect():
    print('client disconnected',request.sid)

if __name__ == '__main__':
    try:
        socketio.run(app,port=5000)
    except Exception as e:
        print("\n Execption occurs while starting the socketio server",str(e))
```

Client code :
```
<!DOCTYPE html>
<html>
    <head>
        <script src="socket.io.js"></script>
        <script>
            const socket = io('http://localhost:5000');
            socket.on('client',function(data){
                console.log(data);
            })
            socket.on('connect',function(){
                console.log('connected');
                socket.emit('server')
            });
            socket.on('disconnect',function(){
                console.log('disconnected');
            });
        </script>
    </head>
    <body>
    </body>
</html>
```

**Comment by miguelgrinberg** [comment]
When I run your example I see a `hi` in the browser's console every two seconds. Were you expecting a different behavior?

**Comment by sathishsatzy** [comment]
Here i put a `print('looping')` statement for checking the while loop's iteration, in a server side loop is working continuously but i didn't get the messages on client side also the client automatically disconnected once. for your reference i attached the image.

![socketio](https://user-images.githubusercontent.com/35100551/70796386-22a31800-1dc8-11ea-938c-7735be9565bf.png)

**Comment by miguelgrinberg** [comment]
Well, the application does not have an issue, it works fine for me.

Make sure you have the latest versions of all your packages, and also that you have eventlet or gevent installed so that the server works asynchronously.

**Comment by sathishsatzy** [comment]
:) yup, its working fine after upgrading all the packages, Thanks a lot for your quick response.
