### ISSUE TITLE
use example app statrt on local windows ok but on server centos failed error 400

### ISSUE THREAD

**Issue by adorkkk** [miguelgrinberg/Flask-SocketIO#1128]
excuse,  I just started using websocket,
i run example's app locally on windows everything is ok,
but when i run it on my server(centos7+python3.7+super+nginx+gunicorn+eventlet),  
It always tries to connect the service, just connect then disconnect,
details are shown below,
![image](https://user-images.githubusercontent.com/44963900/70874546-8eb29580-1fed-11ea-8e83-8927025023a9.png)
![image](https://user-images.githubusercontent.com/44963900/70874636-f8cb3a80-1fed-11ea-9674-e377623f23fd.png)

**Comment by miguelgrinberg** [comment]
You may want to enable logging on the server to see if that helps identify the issue. Just add `engineio_logger=True` to your `SocketIO()` constructor.

**Comment by adorkkk** [comment]
tks for your reply.
i add `engineio_logger=True` to  SocketIO() constructor, its details are shown below, i dont konw the reason for invalid session
![image](https://user-images.githubusercontent.com/44963900/70973783-4eccda80-20e1-11ea-9b6c-0a0c6b4cf0ee.png)

**Comment by miguelgrinberg** [comment]
This does not appear to be an issue with the Socket.IO server. I assume this is going through nginx? Can you try connecting directly to the gunicorn server to see if that works or not?

**Comment by adorkkk** [comment]
Hi, Miguel,
I try connecting directly to the gunicorn server, (**gunicorn -w 1 -b 127.0.0.1:5000 app:app**,
logs detail:
```

```
![image](https://user-images.githubusercontent.com/44963900/71162558-64c7d000-2286-11ea-9a36-5846ddd72483.png)

its still warning ' Invalid Session', 

then i dont use gunicorn, run it **python3 app:app**,  that's ok,

So I guess the problem is gunicorn, but I don't know how to solve it ~.~

**Comment by adorkkk** [comment]
sorry,
i try uninstall eventlet and install gevent, then use gunicorn directly run it  'gunicorn -w 1 -b 127.0.0.1:5000`, the program runs corrently.

after this, i use nginx+gevent, it also warning 'invalid session'...

**Comment by miguelgrinberg** [comment]
You are not running gunicorn correctly. Try:

    gunicorn -w 1 -k eventlet -b 127.0.0.1:5000

**Comment by adorkkk** [comment]
mygod,
its ok by `gunicorn -w 1 -k eventlet -b 127.0.0.1:5000`

thank you very much,

mua~
