### ISSUE TITLE
Switching from threading to multiprocessing

### ISSUE THREAD

**Issue by egorf** [miguelgrinberg/Flask-SocketIO#113]
Hello!
I tried the example app and it works great.
However, I would like to move the server generated event part from threading to multiprocessing lib.
It doesn't seem to work that way, the messages don't reach the browser. Is there a specific reason behind this?

**Comment by miguelgrinberg** [comment]
Well, you are free to do multiprocessing, but the actual sending of an event must happen in the gevent process, as that is the one that is connected to the client. Your background process needs to signal the server when it wants to send something to a client and let the server do it.

**Comment by egorf** [comment]
Thank you, that makes the situation pretty clear
