### ISSUE TITLE
Socket.io not establishing connection with load balancer : timeout error

### ISSUE THREAD

**Issue by jtopel** [miguelgrinberg/Flask-SocketIO#1131]
**Your question**
Hi Miguel, We are in the process of moving our cloud instance from Linode to Google Cloud Platform. Our entire web app uses socket.io for most frontend behavior. When we hit the domain on the GCP instance we are experiencing extremely slow speeds. In addition we are experiencing a server disconnect every 3-5 seconds. When we looked at the web server logs we saw the following:

**Logs**
A 2019-12-18T22:27:08.305600469Z [2019-12-18 22:27:08,304] ERROR in kombu_manager: Sleeping 32.0s
A 2019-12-18T22:27:08.305685444Z Traceback (most recent call last):
A 2019-12-18T22:27:08.305692804Z   File "/usr/local/lib/python3.5/dist-packages/kombu/utils/functional.py", line 332, in retry_over_time
A 2019-12-18T22:27:08.305698205Z     return fun(*args, **kwargs)
A 2019-12-18T22:27:08.305702737Z   File "/usr/local/lib/python3.5/dist-packages/kombu/connection.py", line 261, in connect
A 2019-12-18T22:27:08.305707322Z     return self.connection
A 2019-12-18T22:27:08.305711636Z   File "/usr/local/lib/python3.5/dist-packages/kombu/connection.py", line 802, in connection 
A 2019-12-18T22:27:08.305716109Z     self._connection = self._establish_connection()
A 2019-12-18T22:27:08.305736993Z   File "/usr/local/lib/python3.5/dist-packages/kombu/connection.py", line 757, in _establish_connection
A 2019-12-18T22:27:08.305741614Z     conn = self.transport.establish_connection() 
A 2019-12-18T22:27:08.305745468Z   File "/usr/local/lib/python3.5/dist-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
A 2019-12-18T22:27:08.305749625Z     conn.connect()
A 2019-12-18T22:27:08.305753414Z   File "/usr/local/lib/python3.5/dist-packages/amqp/connection.py", line 294, in connect
A 2019-12-18T22:27:08.305757408Z     self.transport.connect()
A 2019-12-18T22:27:08.305761307Z   File "/usr/local/lib/python3.5/dist-packages/amqp/transport.py", line 120, in connect
A 2019-12-18T22:27:08.305765180Z     self._connect(self.host, self.port, self.connect_timeout)
A 2019-12-18T22:27:08.305769048Z   File "/usr/local/lib/python3.5/dist-packages/amqp/transport.py", line 161, in _connect
A 2019-12-18T22:27:08.305773031Z     self.sock.connect(sa)
A 2019-12-18T22:27:08.305776680Z   File "/usr/local/lib/python3.5/dist-packages/eventlet/greenio/base.py", line 261, in connect 
A 2019-12-18T22:27:08.305780599Z     self._trampoline(fd, write=True, timeout=timeout, timeout_exc=_timeout_exc)
A 2019-12-18T22:27:08.305784455Z   File "/usr/local/lib/python3.5/dist-packages/eventlet/greenio/base.py", line 208, in _trampoline
A 2019-12-18T22:27:08.305788491Z     mark_as_closed=self._mark_as_closed)
A 2019-12-18T22:27:08.305792209Z   File "/usr/local/lib/python3.5/dist-packages/eventlet/hubs/__init__.py", line 164, in trampoline
A 2019-12-18T22:27:08.305796128Z     return hub.switch() 
A 2019-12-18T22:27:08.305799746Z   File "/usr/local/lib/python3.5/dist-packages/eventlet/hubs/hub.py", line 297, in switch
A 2019-12-18T22:27:08.305803719Z     return self.greenlet.switch()
A 2019-12-18T22:27:08.310863763Z socket.timeout: timed out
 

**GCP architecture**
We are setup using RabbitMQ as the broker and then Redis as in-memory storage. Prior to setting up the load balancer, when we setup a single web server we had no problems and everything worked fine. When we setup the load balancer on top of a single web server, that is when the problems began occuring.

**Comment by miguelgrinberg** [comment]
How do you run your web server?

**Comment by jtopel** [comment]
Flask

**Comment by miguelgrinberg** [comment]
Sorry, but your answer is insufficient. I need all the details. What you have installed in your virtualenv, how you actually run your server (what command do you use to start it?) and so on.
