### ISSUE TITLE
Need some helping deploying Flask-Socketio/Gunicore/Nginx app

### ISSUE THREAD

**Issue by JamesHearts** [miguelgrinberg/Flask-SocketIO#1137]
**Your question**
Hello. I've been at this problem for around 8 hours now. I've got an app where the most complex functionality is polling a mongodb database every 3 seconds and then pushes the updates to an Angular client (which is running ngx-socket-io). I am running Flask-SocketIO (eventlet), flask-pymongo and using gunicore which nginx connects to. 

I am have followed numerous tutorials and believe i'm close to getting things working but right now my events are not getting pushed to the client. In fact it sometimes works and sometimes does not. Sometimes the events will get pushed all the way to the client, sometimes the 3 second timer callback function won't even execute. 

**Logs**
(venv) $ sudo journalctl -u app-fg.service --since "5 minutes ago"
-- Logs begin at Thu 2019-11-14 16:02:55 PST, end at Fri 2019-12-27 22:41:29 PST. --
Dec 27 22:36:32 marketing-vm1 gunicorn3[100361]: 298ce2979e96455481aa34ba77bcf981: Sending packet OPEN data {'sid': '298ce2979e96455481aa34ba77bcf981', 'upgrades': ['websoc
Dec 27 22:36:32 marketing-vm1 gunicorn3[100361]: 298ce2979e96455481aa34ba77bcf981: Sending packet MESSAGE data 0
Dec 27 22:36:33 marketing-vm1 gunicorn3[100361]: b3b67d819a174ca5a3dbd0a49b059139: Sending packet OPEN data {'sid': 'b3b67d819a174ca5a3dbd0a49b059139', 'upgrades': ['websoc
Dec 27 22:36:33 marketing-vm1 gunicorn3[100361]: b3b67d819a174ca5a3dbd0a49b059139: Sending packet MESSAGE data 0
Dec 27 22:36:33 marketing-vm1 gunicorn3[100361]: b3b67d819a174ca5a3dbd0a49b059139: Received packet CLOSE data None
Dec 27 22:36:35 marketing-vm1 gunicorn3[100361]: b851febf406f41b59f4f1ee1ceb9e8a7: Sending packet OPEN data {'sid': 'b851febf406f41b59f4f1ee1ceb9e8a7', 'upgrades': ['websoc
Dec 27 22:36:35 marketing-vm1 gunicorn3[100361]: b851febf406f41b59f4f1ee1ceb9e8a7: Sending packet MESSAGE data 0
Dec 27 22:36:37 marketing-vm1 gunicorn3[100361]: 3407af8281e74d1d966b577ff393e7a6: Sending packet OPEN data {'sid': '3407af8281e74d1d966b577ff393e7a6', 'upgrades': ['websoc
Dec 27 22:36:37 marketing-vm1 gunicorn3[100361]: 3407af8281e74d1d966b577ff393e7a6: Sending packet MESSAGE data 0
Dec 27 22:36:37 marketing-vm1 gunicorn3[100361]: 3407af8281e74d1d966b577ff393e7a6: Received packet CLOSE data None
Dec 27 22:36:38 marketing-vm1 gunicorn3[100361]: d123ba891fa84bf6b529e285291fb1bb: Sending packet OPEN data {'sid': 'd123ba891fa84bf6b529e285291fb1bb', 'upgrades': ['websoc
Dec 27 22:36:38 marketing-vm1 gunicorn3[100361]: d123ba891fa84bf6b529e285291fb1bb: Sending packet MESSAGE data 0
Dec 27 22:36:38 marketing-vm1 gunicorn3[100361]: d123ba891fa84bf6b529e285291fb1bb: Received request to upgrade to websocket
Dec 27 22:36:39 marketing-vm1 gunicorn3[100361]: d123ba891fa84bf6b529e285291fb1bb: Failed websocket upgrade, no PING packet
Dec 27 22:36:50 marketing-vm1 gunicorn3[100361]: 620c004d859044d2a76d36cbbc90221e: Sending packet OPEN data {'sid': '620c004d859044d2a76d36cbbc90221e', 'upgrades': ['websoc
Dec 27 22:36:50 marketing-vm1 gunicorn3[100361]: 620c004d859044d2a76d36cbbc90221e: Sending packet MESSAGE data 0
Dec 27 22:36:50 marketing-vm1 gunicorn3[100361]: 620c004d859044d2a76d36cbbc90221e: Received request to upgrade to websocket
Dec 27 22:36:50 marketing-vm1 gunicorn3[100361]: 620c004d859044d2a76d36cbbc90221e: Upgrade to websocket successful
Dec 27 22:36:52 marketing-vm1 gunicorn3[100361]: 8d85983ddef645699acb1bdd196b03bf: Client is gone, closing socket
Dec 27 22:36:52 marketing-vm1 gunicorn3[100361]: 8d85983ddef645699acb1bdd196b03bf: Client is gone, closing socket
Dec 27 22:37:04 marketing-vm1 gunicorn3[100361]: eae9ed5080ea4b0fac3e4a58e134454c: Client is gone, closing socket
Dec 27 22:37:04 marketing-vm1 gunicorn3[100361]: eae9ed5080ea4b0fac3e4a58e134454c: Client is gone, closing socket
Dec 27 22:37:15 marketing-vm1 gunicorn3[100361]: 620c004d859044d2a76d36cbbc90221e: Received packet PING data None
Dec 27 22:37:15 marketing-vm1 gunicorn3[100361]: 620c004d859044d2a76d36cbbc90221e: Sending packet PONG data None
Dec 27 22:37:40 marketing-vm1 gunicorn3[100361]: 620c004d859044d2a76d36cbbc90221e: Received packet PING data None
Dec 27 22:37:40 marketing-vm1 gunicorn3[100361]: 620c004d859044d2a76d36cbbc90221e: Sending packet PONG data None
Dec 27 22:37:46 marketing-vm1 gunicorn3[100361]: 298ce2979e96455481aa34ba77bcf981: Client is gone, closing socket
Dec 27 22:37:46 marketing-vm1 gunicorn3[100361]: 298ce2979e96455481aa34ba77bcf981: Client is gone, closing socket
Dec 27 22:37:54 marketing-vm1 gunicorn3[100361]: b851febf406f41b59f4f1ee1ceb9e8a7: Client is gone, closing socket
Dec 27 22:37:54 marketing-vm1 gunicorn3[100361]: b851febf406f41b59f4f1ee1ceb9e8a7: Client is gone, closing socket
Dec 27 22:38:02 marketing-vm1 gunicorn3[100361]: d123ba891fa84bf6b529e285291fb1bb: Client is gone, closing socket
Dec 27 22:38:02 marketing-vm1 gunicorn3[100361]: d123ba891fa84bf6b529e285291fb1bb: Client is gone, closing socket
Dec 27 22:38:05 marketing-vm1 gunicorn3[100361]: 620c004d859044d2a76d36cbbc90221e: Received packet PING data None
Dec 27 22:38:05 marketing-vm1 gunicorn3[100361]: 620c004d859044d2a76d36cbbc90221e: Sending packet PONG data None
Dec 27 22:38:31 marketing-vm1 gunicorn3[100361]: 620c004d859044d2a76d36cbbc90221e: Received packet PING data None
Dec 27 22:38:31 marketing-vm1 gunicorn3[100361]: 620c004d859044d2a76d36cbbc90221e: Sending packet PONG data None
Dec 27 22:38:57 marketing-vm1 gunicorn3[100361]: 620c004d859044d2a76d36cbbc90221e: Received packet PING data None
Dec 27 22:38:57 marketing-vm1 gunicorn3[100361]: 620c004d859044d2a76d36cbbc90221e: Sending packet PONG data None
Dec 27 22:39:23 marketing-vm1 gunicorn3[100361]: 620c004d859044d2a76d36cbbc90221e: Received packet PING data None
Dec 27 22:39:23 marketing-vm1 gunicorn3[100361]: 620c004d859044d2a76d36cbbc90221e: Sending packet PONG data None
Dec 27 22:39:49 marketing-vm1 gunicorn3[100361]: 620c004d859044d2a76d36cbbc90221e: Received packet PING data None
Dec 27 22:39:49 marketing-vm1 gunicorn3[100361]: 620c004d859044d2a76d36cbbc90221e: Sending packet PONG data None
Dec 27 22:40:15 marketing-vm1 gunicorn3[100361]: 620c004d859044d2a76d36cbbc90221e: Received packet PING data None
Dec 27 22:40:15 marketing-vm1 gunicorn3[100361]: 620c004d859044d2a76d36cbbc90221e: Sending packet PONG data None
Dec 27 22:40:41 marketing-vm1 gunicorn3[100361]: 620c004d859044d2a76d36cbbc90221e: Received packet PING data None
Dec 27 22:40:41 marketing-vm1 gunicorn3[100361]: 620c004d859044d2a76d36cbbc90221e: Sending packet PONG data None
Dec 27 22:41:07 marketing-vm1 gunicorn3[100361]: 620c004d859044d2a76d36cbbc90221e: Received packet PING data None
Dec 27 22:41:07 marketing-vm1 gunicorn3[100361]: 620c004d859044d2a76d36cbbc90221e: Sending packet PONG data None

I can add more data as needed for anyone that can help me.

**Comment by JamesHearts** [comment]
Extra logs after trying some things.

Dec 27 23:01:00 marketing-vm1 gunicorn3[105885]: 702fa0c5e58f48ab84dde31a24e1aa7c: Sending packet OPEN data {'sid': '702fa0c5e58f48ab84dde31a24e1aa7c', 'upgrades': ['websoc
Dec 27 23:01:00 marketing-vm1 gunicorn3[105885]: 702fa0c5e58f48ab84dde31a24e1aa7c: Sending packet MESSAGE data 0
Dec 27 23:01:25 marketing-vm1 gunicorn3[105885]: 0133c58c7fde4f5a83a65c3b63438a61: Sending packet OPEN data {'sid': '0133c58c7fde4f5a83a65c3b63438a61', 'upgrades': ['websoc
Dec 27 23:01:25 marketing-vm1 gunicorn3[105885]: 0133c58c7fde4f5a83a65c3b63438a61: Sending packet MESSAGE data 0
Dec 27 23:01:25 marketing-vm1 gunicorn3[105885]: 0133c58c7fde4f5a83a65c3b63438a61: Received request to upgrade to websocket
Dec 27 23:01:26 marketing-vm1 gunicorn3[105885]: 0133c58c7fde4f5a83a65c3b63438a61: Failed websocket upgrade, expected UPGRADE packet, received None instead.
Dec 27 23:01:38 marketing-vm1 gunicorn3[105885]: 327fccf34d634d1493d6bea81e7c3fb5: Sending packet OPEN data {'sid': '327fccf34d634d1493d6bea81e7c3fb5', 'upgrades': ['websoc
Dec 27 23:01:38 marketing-vm1 gunicorn3[105885]: 327fccf34d634d1493d6bea81e7c3fb5: Sending packet MESSAGE data 0
Dec 27 23:01:52 marketing-vm1 gunicorn3[105885]: 870276733a4d4eef9a3a13d8750602c5: Sending packet OPEN data {'sid': '870276733a4d4eef9a3a13d8750602c5', 'upgrades': ['websoc
Dec 27 23:01:52 marketing-vm1 gunicorn3[105885]: 870276733a4d4eef9a3a13d8750602c5: Sending packet MESSAGE data 0
Dec 27 23:01:54 marketing-vm1 gunicorn3[105885]: cb2559255ec8421db30aa0bd5c149933: Client is gone, closing socket
Dec 27 23:01:54 marketing-vm1 gunicorn3[105885]: cb2559255ec8421db30aa0bd5c149933: Client is gone, closing socket
Dec 27 23:02:02 marketing-vm1 gunicorn3[105885]: emitting event "results" to all [/]
Dec 27 23:02:02 marketing-vm1 gunicorn3[105885]: 702fa0c5e58f48ab84dde31a24e1aa7c: Client is gone, closing socket
Dec 27 23:02:02 marketing-vm1 gunicorn3[105885]: 702fa0c5e58f48ab84dde31a24e1aa7c: Client is gone, closing socket
Dec 27 23:02:02 marketing-vm1 gunicorn3[105885]: 0133c58c7fde4f5a83a65c3b63438a61: Client is gone, closing socket
Dec 27 23:02:02 marketing-vm1 gunicorn3[105885]: 0133c58c7fde4f5a83a65c3b63438a61: Client is gone, closing socket
Dec 27 23:02:02 marketing-vm1 gunicorn3[105885]: 327fccf34d634d1493d6bea81e7c3fb5: Sending packet MESSAGE data 2["results",{"results":[{"session_id":"42095939173826","throu
Dec 27 23:02:02 marketing-vm1 gunicorn3[105885]: 870276733a4d4eef9a3a13d8750602c5: Sending packet MESSAGE data 2["results",{"results":[{"session_id":"42095939173826","throu
Dec 27 23:02:02 marketing-vm1 gunicorn3[105885]: 870276733a4d4eef9a3a13d8750602c5: Received packet CLOSE data None
Dec 27 23:02:07 marketing-vm1 gunicorn3[105885]: emitting event "results" to all [/]
Dec 27 23:02:07 marketing-vm1 gunicorn3[105885]: 327fccf34d634d1493d6bea81e7c3fb5: Sending packet MESSAGE data 2["results",{"results":[{"session_id":"42095939173826","throu
Dec 27 23:02:08 marketing-vm1 gunicorn3[105885]: 0f5035dbc1cb4ed5998b430630c2861e: Sending packet OPEN data {'sid': '0f5035dbc1cb4ed5998b430630c2861e', 'upgrades': ['websoc
Dec 27 23:02:08 marketing-vm1 gunicorn3[105885]: 0f5035dbc1cb4ed5998b430630c2861e: Sending packet MESSAGE data 0
Dec 27 23:02:08 marketing-vm1 gunicorn3[105885]: 0f5035dbc1cb4ed5998b430630c2861e: Received request to upgrade to websocket
Dec 27 23:02:09 marketing-vm1 gunicorn3[105885]: 0f5035dbc1cb4ed5998b430630c2861e: Upgrade to websocket successful
Dec 27 23:02:12 marketing-vm1 gunicorn3[105885]: emitting event "results" to all [/]
Dec 27 23:02:12 marketing-vm1 gunicorn3[105885]: 327fccf34d634d1493d6bea81e7c3fb5: Client is gone, closing socket
Dec 27 23:02:12 marketing-vm1 gunicorn3[105885]: 327fccf34d634d1493d6bea81e7c3fb5: Client is gone, closing socket
Dec 27 23:02:12 marketing-vm1 gunicorn3[105885]: 0f5035dbc1cb4ed5998b430630c2861e: Sending packet MESSAGE data 2["results",{"results":[{"session_id":"42095939173826","throu
Dec 27 23:02:17 marketing-vm1 gunicorn3[105885]: emitting event "results" to all [/]
Dec 27 23:02:17 marketing-vm1 gunicorn3[105885]: 0f5035dbc1cb4ed5998b430630c2861e: Sending packet MESSAGE data 2["results",{"results":[{"session_id":"42095939173826","throu
Dec 27 23:02:22 marketing-vm1 gunicorn3[105885]: emitting event "results" to all [/]
Dec 27 23:02:22 marketing-vm1 gunicorn3[105885]: 0f5035dbc1cb4ed5998b430630c2861e: Sending packet MESSAGE data 2["results",{"results":[{"session_id":"42095939173826","throu
Dec 27 23:02:27 marketing-vm1 gunicorn3[105885]: emitting event "results" to all [/]
Dec 27 23:02:27 marketing-vm1 gunicorn3[105885]: 0f5035dbc1cb4ed5998b430630c2861e: Sending packet MESSAGE data 2["results",{"results":[{"session_id":"42095939173826","throu
Dec 27 23:02:32 marketing-vm1 gunicorn3[105885]: emitting event "results" to all [/]
Dec 27 23:02:32 marketing-vm1 gunicorn3[105885]: 0f5035dbc1cb4ed5998b430630c2861e: Sending packet MESSAGE data 2["results",{"results":[{"session_id":"42095939173826","throu
Dec 27 23:02:33 marketing-vm1 gunicorn3[105885]: 0f5035dbc1cb4ed5998b430630c2861e: Received packet PING data None
Dec 27 23:02:33 marketing-vm1 gunicorn3[105885]: 0f5035dbc1cb4ed5998b430630c2861e: Sending packet PONG data None
Dec 27 23:02:34 marketing-vm1 gunicorn3[105885]: 2b6aa6c2bf014b3cad7513dde289a946: Sending packet OPEN data {'sid': '2b6aa6c2bf014b3cad7513dde289a946', 'upgrades': ['websoc
Dec 27 23:02:34 marketing-vm1 gunicorn3[105885]: 2b6aa6c2bf014b3cad7513dde289a946: Sending packet MESSAGE data 0
Dec 27 23:02:37 marketing-vm1 gunicorn3[105885]: emitting event "results" to all [/]
Dec 27 23:02:37 marketing-vm1 gunicorn3[105885]: 2b6aa6c2bf014b3cad7513dde289a946: Sending packet MESSAGE data 2["results",{"results":[{"session_id":"42095939173826","throu
Dec 27 23:02:42 marketing-vm1 gunicorn3[105885]: emitting event "results" to all [/]
Dec 27 23:02:42 marketing-vm1 gunicorn3[105885]: 2b6aa6c2bf014b3cad7513dde289a946: Sending packet MESSAGE data 2["results",{"results":[{"session_id":"42095939173826","throu
Dec 27 23:02:47 marketing-vm1 gunicorn3[105885]: emitting event "results" to all [/]
Dec 27 23:02:47 marketing-vm1 gunicorn3[105885]: 2b6aa6c2bf014b3cad7513dde289a946: Sending packet MESSAGE data 2["results",{"results":[{"session_id":"42095939173826","throu
Dec 27 23:02:47 marketing-vm1 gunicorn3[105885]: 2b6aa6c2bf014b3cad7513dde289a946: Received packet CLOSE data None
Dec 27 23:02:52 marketing-vm1 gunicorn3[105885]: emitting event "results" to all [/]
Dec 27 23:02:57 marketing-vm1 gunicorn3[105885]: emitting event "results" to all [/]
Dec 27 23:03:02 marketing-vm1 gunicorn3[105885]: 6ea934afcdf74ac4850606723521216c: Sending packet OPEN data {'sid': '6ea934afcdf74ac4850606723521216c', 'upgrades': ['websoc
Dec 27 23:03:02 marketing-vm1 gunicorn3[105885]: 6ea934afcdf74ac4850606723521216c: Sending packet MESSAGE data 0

**Comment by miguelgrinberg** [comment]
Did you monkey patch the standard library so that it becomes compatible with eventlet?

**Comment by JamesHearts** [comment]
I've been messing with monkey patching in various places. First before all imports. And then in different files. It has helped some but then broke other things. Here is another log from the client if its helps.

![image](https://user-images.githubusercontent.com/16404535/71548424-c9b4b180-297b-11ea-9782-380d4c5dcbc4.png)

**Comment by JamesHearts** [comment]
The CORS error was me removing the CORS(app) line of code to see if that was affecting something.

**Comment by miguelgrinberg** [comment]
Monkey patching isn't tricky at all, you have to do it before anything else from the app is imported. So it goes in the main module at the top, above all imports. If something doesn't work after monkey patching, then that something is likely incompatible with eventlet.

**Comment by JamesHearts** [comment]
Interesting thing is everything works locally even if I reverse proxy through nginx (on WSL running Ubuntu 18.04). On the server the only difference is that they installed two versions of python so I start the server using 'gunicorn3 --worker-class eventlet -w 1 wsgi:app' aftering using pip3 to install gunicorn3 and other packages. I'm not sure if that should cause some errors?

**Comment by JamesHearts** [comment]
I believe I figured out the issue. I changed the port that I was serving the app on which was 8000 to 8020 and it works. Not sure why in the world this would be an issue, but I'm thinking it had something to do with the firewall on the server. Thanks for the help @miguelgrinberg
