### ISSUE TITLE
Strategies and tools for load & stress tests

### ISSUE THREAD

**Issue by hqntrt** [miguelgrinberg/Flask-SocketIO#1138]
I want to test my application against real world usage there are some tools out there like load runner and apache jmeter but they lack support for socketio. I have done those:

1. Created a bare bones testing application, kept sending huge chunks of data to server but this is limited by my upload speed to the internet.
2. Configured application to send huge chunks of data to the client again still limited by connection's speed.

Is there a way to test how many users it can support ?

Note: I am using socketio to send and receive small pictures and sound files up to 65KB, not just text.

**Comment by miguelgrinberg** [comment]
What I have done is run the test from a location that is closer to the server, without the Internet in the middle. The simplest form of this is to run the test in the same machine as the server. If you want to prevent the test itself from affecting the load on your server, then use a separate host that is connected to the server via private network.
