### ISSUE TITLE
Flask SocketIO with Firebase Inconsistent 

### ISSUE THREAD

**Issue by gerbilord** [miguelgrinberg/Flask-SocketIO#1139]
**Having trouble getting sockets working with Firebase**
Using Flask-socketIO I created a multiplayer chess website. I was trying to follow [this tutorial](https://medium.com/firebase-developers/hosting-flask-servers-on-firebase-from-scratch-c97cfb204579) to host my website. However it does not use flask-socketio and I believe that is where my errors stem from.

I am using `flask run` to test my website locally. Everything is works perfectly locally. However when I upload it to google cloud using the commands below I run into issues.
`gcloud builds submit --tag gcr.io/<project-id>/flask-fire`
`gcloud beta run deploy --image gcr.io/<project-id>/flask-fire`

When opening my website with the google cloud link the basics work. However when a socket is created like this:
```
var protocol = window.location.protocol;
var socket = io.connect(protocol + '//' + document.domain + ':' + location.port + '/shrinkChess');
```

I get the error: `flask-fire-rx4exhar6q-uc.a.run.app/:1 Failed to load resource: the server responded with a status of 400 ()`

When accessing the website with projectName.firebaseapps.com
There are no errors and AJAX requests don't work most the time. However sockets will work. The behavior is very inconsistent.

If you could please explain what I am doing wrong that would be greatly appreciated.

**app.py** 
```
app = Flask(__name__)
app.config['SECRET_KEY'] = 'keyPlaceHolder'
socketio = SocketIO(app)
if __name__ == '__main__':
    socketio.run(app, host='0.0.0.0', port=8080)
```

**Docker File**

```
FROM python:3.7

RUN pip install Flask
RUN pip install Flask gunicorn
RUN pip install flask-socketio

COPY src/ /app
WORKDIR /app

ENV PORT 8080

CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 app:app

```
**firebase.json**
```
{
  "hosting": {
    "public": "static",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [{
      "source": "**",
      "run": {
        "serviceId": "flask-fire"
      }
    }]
  }
}

```

**Comment by miguelgrinberg** [comment]
You haven't provided server-side logs.

**Logs**
Please provide relevant logs from the server and the client. On the server, add the `logger=True` and `engineio_logger=True` arguments to your `SockertIO()` object to get logs dumped on your terminal. The same arguments can be used on the [python-socketio's client](https://github.com/miguelgrinberg/python-socketio). If you are using the JavaScript client, see [here](https://socket.io/docs/logging-and-debugging/) for how to enable logs.

**Comment by gerbilord** [comment]
**app.py**
```
if __name__ == '__main__':
    socketio.run(app, host='0.0.0.0', port=8080, logger=True, engineio_logger=True)
```
I added the code as said but two things: 
1. The terminal output seems to be the same.
2. I doubt the terminal output on my local machine would be very helpful since the flask run is working fine.
I assume I need the logs of the google cloud app but do not know how to get those. However I added the logs from running `flask run` and `firebase serve`
No errors: [flaskRun.log](https://github.com/miguelgrinberg/Flask-SocketIO/files/4009202/flaskRun.log)
Websockets don't work: [firebaseServe.log](https://github.com/miguelgrinberg/Flask-SocketIO/files/4009212/firebaseServe.log)

**Comment by miguelgrinberg** [comment]
The logging options go in the `SocketIO()` constructor, not in the `run()` method.

**Comment by gerbilord** [comment]
Thank you. Here are the logs. 

[flaskRun.log](https://github.com/miguelgrinberg/Flask-SocketIO/files/4009239/flaskRun.log)

[firebaseServe.log](https://github.com/miguelgrinberg/Flask-SocketIO/files/4009234/firebaseServe.log)

**Comment by miguelgrinberg** [comment]
I don't see any errors in the log that you provided.

**Comment by gerbilord** [comment]
When using `flask run` and accessing the website locally everything works perfectly. Thus flaskRun.log has no errors. However after uploading to firebase, errors occur. I am not quite sure how to obtain those logs.

**Comment by miguelgrinberg** [comment]
Well, there isn't much I can do without seeing the logs, so you need to figure out how to get those. The 400 errors have a specific cause, this is reported in the logs.

**Comment by gerbilord** [comment]
I found these logs on the gcloud. I'm not sure if they are helpful as they don't seem to be output logs of the terminal.
[gcloud.log](https://github.com/miguelgrinberg/Flask-SocketIO/files/4009310/gcloud.log)

**Comment by miguelgrinberg** [comment]
No, that's not the Socket.IO logs, sorry. You need to configure the logging on this package in a way that you can access it. These logs are going to tell you what's wrong very likely.

**Comment by gerbilord** [comment]
I think I'll try to find a different way to upload/host it then. Thank you for your time.
