### ISSUE TITLE
Delay between client disconnect and server handling of disconnect event

### ISSUE THREAD

**Issue by hexturtle** [miguelgrinberg/Flask-SocketIO#114]
I've noticed there is a significant delay between when the client navigates away from my web app and when the server receives/processes the disconnect event. My guess is this is really an issue with using an older version of the Socket.IO client, 0.9.16. Though, if this is not the case, I would greatly appreciate guidance for how to solve this.

Nevertheless, the documentation says this is the most stable version of the Socket.IO client:
> The 1.x releases of the Socket.IO client-side Javascript libraries are not compatible with project gevent-socketio. At this time the Socket.IO client release 0.9.16 has been found to be the most stable.
https://flask-socketio.readthedocs.org/en/latest/

I tried using the latest version of the Socket.IO client as well, but encountered errors as expected.

With that said, I don't know if the latest version of Socket.IO addresses this issue. But version 0.9.16 does not appear to do so. Therefore, I believe this issue can be attributed to Flask-SocketIO's lack of compatibility with newer versions of the SocketIO client.

If anyone has found a way to fix this, or if I'm totally off base with identifying the cause please let me know.

**Comment by miguelgrinberg** [comment]
The `heartbeat_interval` and `heartbeat_timeout` configuration items control the timings of the heartbeat packages exchanged between client and server. If you need the disconnects to be detected quicker then you need to use short values for these, but then the keep alive traffic will increase so you need to find the right balance.

**Comment by hexturtle** [comment]
Oh cool, I wasn't aware of those. I was able to solve my problem by setting `heartbeat_interval=.5` seconds. Note that it may be a good idea to specify the unit as seconds in the docs.

I'm also curious what the default value for `heartbeat_timeout` is? It says `heartbeat_interval` should be less than `heartbeat_timeout`, therefore I'd like to know that I'm not violating that rule without having to set `heartbeat_timeout` myself.

Finally, are there any known issues with having a low `heartbeat_interval` other than the increased traffic? Since setting the value to .5, I've experienced two different server errors when I rapidly refresh the page in the browser. Is this just an inherent issue with setting such a low interval? If not, I'll open a new issue for it.

**Comment by miguelgrinberg** [comment]
The extension just passes these values to `gevent-socketio`. The defaults set by that project are 60 seconds for the timeout and 25 for the interval. As I said, the only drawback of using short times is that the overhead increases. It may be worthwhile looking at the network stats on a client to see how much in/out traffic your settings generate on an idle connection.

**Comment by tonysun1220** [comment]
Where should I set this heartbeat_interval ?

**Comment by miguelgrinberg** [comment]
@tonysun1220 See `ping_timeout` and `ping_interval` in the [documentation](https://flask-socketio.readthedocs.io/en/latest/#flask_socketio.SocketIO).

**Comment by tonysun1220** [comment]
Thanks. That solved my problem.
