### ISSUE TITLE
Why is backend emitting to every client then it's filtering out on the front end side?

### ISSUE THREAD

**Issue by lazercorn** [miguelgrinberg/Flask-SocketIO#1141]
I have each individual client register a uniqueid on the front end like so, socket.on("unique_id_1"'), Let's say I emit a message like so socket.emit("unique_id_1", {}), it's sending that message to everyone connected to the backend and filtering out on the front end in the sense that only person who owns unique_id_1 gets the message. I want only that person  who owns unique_id_1 sent the message, not via this sending to all/filtering mechanism. Why is it coded to work like this? Isn't this a security risk?

**Comment by miguelgrinberg** [comment]
You are not showing me any code, but my guess is that you are "broadcasting". If you want to send an event to a single client, then add `to=client_sid` in the `emit()` call.

**Comment by lazercorn** [comment]
No need to show more code, it's self explanatory. Each person uniquely registers on their client side socket.on("unique_id_1"') for client 1, socket.on("unique_id_2"') for client 2 and so on, when you do socket.emit("unique_id_1", {}), it's not suppose to send to client 2 only to client 1 because he didn't register "unique_id_1", yet it still does, but because the client side filters it, it doesn't seem like it receives it.

**Comment by miguelgrinberg** [comment]
I just told you what you need to do to get the result that you want above. You are making wrong assumptions about how this library works. The handlers that you set in the client are not known by the server.

**Comment by lazercorn** [comment]
ok, library misunderstanding. Thanks for clarifying.
