### ISSUE TITLE
easy private message

### ISSUE THREAD

**Issue by laticoda** [miguelgrinberg/Flask-SocketIO#1142]
**Is your feature request related to a problem? Please describe.**
Hi !
i am fighting with making game multiplayer, i have to identify connections but each time the player refresh or go to another page, i lost the connection, i can not send him message anymore.
Even if the target player stay on the same page, if i want use a flash message thanks to flask_socketio , i got this:
you can't use request.sid in an HTTP view, because there is no Socket.IO context. That only works in a Socket.IO event handler.

i have also   to avoid cheating by multiconnection.
Also, how can i have a Ajax effect, i mean refresh data displayed with destroying the connection ?
How can i display to every clients which players are connected, today just the very last one knows who is playing.
i have many example and tutorial but i am not able to solve this problem. 

thanks

**Comment by miguelgrinberg** [comment]
On the connection event you have to create a mapping between `request.sid` and your own user identification. On the disconnection event you remove that mapping.

Then on other socket events you can use `request.sid` to look up the user id. On regular HTTP routes you can use your own HTTP based authentication mechanism to determine the user id, and if you need to, you can look up the `sid` with it.

**Comment by laticoda** [comment]
Should i use session or Session ? g ? cookies ?
i try to do like this without node.js
https://hackernoon.com/enforcing-a-single-web-socket-connection-per-user-with-node-js-socket-io-and-redis-65f9eb57f66a

**Comment by miguelgrinberg** [comment]
The article that you are using as a reference uses Redis. Another option would be a dictionary in memory, but only if you plan on having a single server, once you start working with a cluster Redis is probably the best option.

**Comment by laticoda** [comment]
thank you very much Miguel
