### ISSUE TITLE
Event is not getting emitted from inside of a thread.

### ISSUE THREAD

**Issue by shreeramk** [miguelgrinberg/Flask-SocketIO#1143]
**Describe the bug**
Socket connection is done. But events are not getting emitted from inside of a thread.

Command Used to run: `gunicorn --worker-class eventlet -w 1 api:app `
Sample Code:
```
from flask_socketio import SocketIO

import eventlet
eventlet.monkey_patch()
threading = eventlet.patcher.original('threading')

app = Flask(__name__)

app.config['SECRET_KEY'] = '12345#'
socketio = SocketIO(app, cors_allowed_origins="*",  engineio_logger=True, async_mode='eventlet')

@app.route('/pyapi/uploadcsv', methods=['POST','GET'])
def upload_csv():

    file = request.files['files']

    file.save(os.path.join(app.config['UPLOAD_FOLDER'], file.filename))

    def do_work(sid):
        # Some code
        emitSocketEvent(sid, 'csv read')

    thread = threading.Thread(target=do_work, kwargs={'sid': request.args.get('sid')})
    thread.start()

    return jsonify({'status': 200,  'message': 'File Uploaded successfully', 'id': obj_address})
```

Expected Behaviour:
After thread execution is completed. Event should be emitted. But it doesn't

Logs:
Client connected with sid: edc4dfa7eaf6498790ad9dfb17b217e2
edc4dfa7eaf6498790ad9dfb17b217e2: Sending packet MESSAGE data 2["connected",{"status":200,"message":"Websocket connection successful.","sid":"edc4dfa7eaf6498790ad9dfb17b217e2"}]
edc4dfa7eaf6498790ad9dfb17b217e2: Sending packet MESSAGE data 0
edc4dfa7eaf6498790ad9dfb17b217e2: Received request to upgrade to websocket
edc4dfa7eaf6498790ad9dfb17b217e2: Upgrade to websocket successful

edc4dfa7eaf6498790ad9dfb17b217e2: Sending packet MESSAGE data 2["csv read",{"status":200,"message":"Describe Data is ready","sid":"edc4dfa7eaf6498790ad9dfb17b217e2"}]
edc4dfa7eaf6498790ad9dfb17b217e2: Received packet PING data None
edc4dfa7eaf6498790ad9dfb17b217e2: Sending packet PONG data None
f7590a4328364a819dc18b59473d3bc8: Client is gone, closing socket
Client disconnected
f7590a4328364a819dc18b59473d3bc8: Client is gone, closing socket

**Comment by miguelgrinberg** [comment]
Did you monkey patch the standard library for eventlet? See https://eventlet.net/doc/patching.html.

**Comment by shreeramk** [comment]
Is this enough?
```
import eventlet
eventlet.monkey_patch()
```

Or any other configuration needs to be added?

**Comment by miguelgrinberg** [comment]
That should do it. Make sure you add this at the very top of the main script, even above other imports. This is to ensure that those imports are executed after the monkey patching is done.

**Comment by shreeramk** [comment]
I added to top of the main script. Still it doesn't work. Any other suggestions?

**Comment by miguelgrinberg** [comment]
Are you still getting these?

    f7590a4328364a819dc18b59473d3bc8: Client is gone, closing socket
Client disconnected

This means that the client and the server aren't communicating. In most cases this is due to the server being blocked and not being able to listen to the client messages. If you have done the monkey patching, then there must be some other thing you do in your application that blocks eventlet and is not properly fixed by monkey patching.

**Comment by shreeramk** [comment]
Yea.  The api upload_csv is returning response back and running a thread. Under the thread the uploaded csv is being read and on completion of that websocket event is emitted. That's all. No other processing. Do you think there is an issue the way it has been implemented?

**Comment by miguelgrinberg** [comment]
File I/O is blocking under eventlet. If you have a loop inside which you read your CSV rows, try adding a `socketio.sleep(0)` to help keep things moving along.

**Comment by shreeramk** [comment]
I think I have been able to simply the problem. I am just running the code without any api call.

In browser network console, I can see 
Request 1 - Made to initiate the websocket connection and it is sucessful. 
Request 2 - To upgrade the connection.

After this no requests I see in browser network console which is really weird.

I am attaching a sample file. Can you try and see if it is working for you?
Python File: [sample.txt](https://github.com/miguelgrinberg/Flask-SocketIO/files/4025376/sample.txt)
HTML File: [ws_html.txt](https://github.com/miguelgrinberg/Flask-SocketIO/files/4025382/ws_html.txt)

Command used:
gunicorn --worker-class eventlet -w 1 sample:app

**Comment by miguelgrinberg** [comment]
This protocol uses WebSocket, you are not going to see HTTP requests once the connection is established. Is there a problem with the application besides you not seeing what you expect to see in the network console?

**Comment by shreeramk** [comment]
Oh is it? 

If I change
`socketio = SocketIO(app, cors_allowed_origins="*",  engineio_logger=True)`
to
`socketio = SocketIO(app, cors_allowed_origins="*", async_mode='threading', engineio_logger=True)`

I can see those logs in browser network console.

**Comment by shreeramk** [comment]
Also, on using eventlet or gevent....the flask api is processing the threads sequentially, rather than in background.  Any idea what could be the cause?

**Comment by miguelgrinberg** [comment]
I mentioned this above, you seem to be doing blocking operations. In an eventlet or gevent application blocking code prevents concurrency. Follow my advice please, add the sleep statements to force your blocking code to cooperate with other running tasks.

**Comment by shreeramk** [comment]
Ok. But I m not running any loop inside thread. Do you suggest to put sleep statement inside each thread or if I have some 30 lines of code executed by that thread...then after every line do I need to put sleep?

Also, is there a different way to run gunicorn where I don't hv to use eventlet or gevent or any other worker class and flask-SocketIO will work?

**Comment by miguelgrinberg** [comment]
So you have a thread that performs a long operation but it does not have a loop? What does your thread do? Blocking operations are not going to work with eventlet or gevent unfortunately.

Unfortunately gunicorn does not have any other modes of operation, but you can use the `flask run` command which does. Just make sure neither eventlet or gevent are installed when you use `flask run`. That will put the app in "threading" mode, which is a lot more forgiving in terms of blocking operations. This mode does not support WebSocket, so your clients will all be doing long-polling. And of course, the Flask server is not very robust, so definitely not something you will use on production.
