### ISSUE TITLE
the 'on' method can't correctly register the handler

### ISSUE THREAD

**Issue by jiaqidegege** [miguelgrinberg/Flask-SocketIO#1145]
Hei Miguel,  I used socketio.on to register the handler in blueprint, it didn't work, however ,I found the socket link was established from chrome network panel, do you have some idea?
![image](https://user-images.githubusercontent.com/31435549/71780948-d2545a00-3003-11ea-9ce5-4a24106bc3b1.png)

`from flask import render_template, request, json, copy_current_request_context
from flask import current_app
from manage import app
from .dealExcel import *
from . import relation_graph_blueprint
from app.exts import socketio

executor = ThreadPoolExecutor(max_workers=2)

@socketio.on('connect', namespace='/test')
def test_connect():
    print('connect')

@socketio.on('disconnect', namespace='/test')
def test_disconnect():
    print('Client disconnected', request.sid)`

**Comment by miguelgrinberg** [comment]
What is it that does not work? Do you mean that the connect/disconnect handlers do not run? Do they run if you move them somewhere else?

**Comment by jiaqidegege** [comment]
I've tried move it to the place where I instantiate the app and some other place, it doesn't work too

**Comment by miguelgrinberg** [comment]
@jiaqidegege you are still not telling what is it that does not work. I suggest you use the example application in this repository, which does work, as a starting point, and modify it to suit your needs.

**Comment by jiaqidegege** [comment]
@miguelgrinberg I'm sorry haven't made the "not work" clear, I mean that the connect/disconnect handlers do not run. actually，I just begin with the example code, and from the debug mode, the server did register the connect/disconnect handlers. I'm also sure the socket connection has been established

**Comment by miguelgrinberg** [comment]
Are you connecting on the `/test` namespace?

**Comment by jiaqidegege** [comment]
> Are you connecting on the `/test` namespace?

yes, I just use the example client 
![image](https://user-images.githubusercontent.com/31435549/71813078-b3ad9c00-30b3-11ea-8bd1-2ea4cc683266.png)

**Comment by miguelgrinberg** [comment]
Unfortunately I don't really have the context to help you with this. If the example app works for you, and your code does not, then I think you need to debug your application to figure out why those handlers are not invoked. Possible problems I can think of:

- the file that has the event handlers is never imported, so the handlers do not get registered.
- your handlers are registered too late, after starting the server

**Comment by jiaqidegege** [comment]
thanks, miguel
I found that It's due to a wrong import, I've sovled it.
thanks for your help
