### ISSUE TITLE
How to increase debug information

### ISSUE THREAD

**Issue by quiddihub** [miguelgrinberg/Flask-SocketIO#1151]
**Your question**
How do I increase the level of logging from the `emit()` function?

My `SocketIO()` call currently looks like;

```
socketio = flask_socketio.SocketIO(
    app,
    engineio_logger=app.logger,
    async_mode='gevent',
    cors_allowed_origins=caos,
    logger=app.logger,
)
```

**Why?**
Periodically the server generates an `emit()` in response to an authentication request from a new client which doesn't appear to get to the client. The call is being executed but no sign of the data being sent to the client is evident with the current logging levels (`app.logger` level is `DEBUG`).

Any subsequent websocket interaction with the server (clients already connected) after this failure no longer seems to work either but the server continues to function at the Flask/HTTP level without an issue.

**Other information**
Versions
```
Flask==1.1.1
Flask-SocketIO==4.2.1
gevent==1.4.0
gevent-websocket==0.10.1

Python 3.6
```

Command
`gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 -b 0.0.0.0:8000 dashboard:app -D`

**Comment by miguelgrinberg** [comment]
You should add `engineio_logger=True`, that is the most lower level logging:

```python
socketio = flask_socketio.SocketIO(
    app,
    engineio_logger=app.logger,
    async_mode='gevent',
    cors_allowed_origins=caos,
    logger=app.logger,
    engineio_logger=app.logger,
)
```

Then you can control when to log and when not to by changing the level in `app.logger`.

**Comment by quiddihub** [comment]
Hi Miguel,
Thanks for responding so quickly.
Argument 2 of my example sets `engineio_logger` which you appear to have repeated in argument 6, was this intentional?

Also, as `emit()` doesn't return anything, is there a way to check to see if the message has been sent?

**Comment by miguelgrinberg** [comment]
Ah, sorry, I missed that you had it at the top.

The `emit()` function is asynchronous, when it returns back to you the message hasn't been sent yet. All the function does is add the message to the send queue.

**Comment by quiddihub** [comment]
Hello Miguel,
Yes, I understand the async nature of the function. Is there an event I can bind to confirm the send?

Given that once the fault starts, all `emit()`s fail, is it logical to focus on the queue? How does that mechanism work and how do I influence the logging of that component? Do I need to look at the `message_queue` parameter?

**Comment by miguelgrinberg** [comment]
@quiddihub the place were the writes is made is in the python-engineio package. Here is the exact line where WebSocket writes are made: https://github.com/miguelgrinberg/python-engineio/blob/master/engineio/socket.py#L205.

There is no logging for these writes, but you can modify the code and add logging temporarily to debug the issue.

The `message_queue` parameter is completely unrelated, by the way, that's a different queue, not the send queue.

**Comment by quiddihub** [comment]
Miguel,
Thanks for the feedback. I'll have a look at the engineio package as per your suggestion.

Interestingly this issue was not present in the server with it was running under python 2.7.  The code is monkey patched as per the documentation;

**Comment by miguelgrinberg** [comment]
I'm not sure this is a problem related to lack or bad monkey patching, to be honest. The typical indicators are not there. People who have monkey patching problems experience problems right from the start, the fact that your application works well for a while and suddenly it stops working makes me think this is something else.

But if you want a quick and easy experiment, remove the monkey patching and any other references to gevent in your code, change `async_mode='threading'`, and then run the app with `socketio.run(app)`. If that works better, then maybe monkey patching might be part of the problem.

**Comment by quiddihub** [comment]
Miguel,
Thanks again for the prompt response.

If I fail to monkey patch the code then it certainly does fail immediately, so I'm happy that is doing what it should. I will have a look at the option of removing gevent. In this configuration, how would you best advise running the code? I have used gevent because that seemed to work best with gunicorn.

With reference the logging. I can see the call to the `emit()` because I have log lines around it so I know it is being called and I can see the related data. When the emit works I can see the related logging, for example;
```
Jan 10 06:27:28 boatymbf dboard send             :94   60429305 INFO - 62f7a60107c847c0aa90f891653f7fdd: Sending packet MESSAGE data 2["global/resp_connection_control_channel",{"success":false,"logged_out":false}]
```
When this fault appears the above line is not produced, although other lines around it are.

**Comment by miguelgrinberg** [comment]
> In this configuration, how would you best advise running the code? 

As I said above, add `socketio.run(app)` at the bottom of your main script, and run that to start the server.

**Comment by quiddihub** [comment]
Miguel,
Surely that just runs the test server, doesn't it?.. or are you suggesting that as a way of testing/narrowing down what the issue might be?

**Comment by miguelgrinberg** [comment]
Yes, that runs under the Werkzeug server. I suggested just as a way to see if the behavior remains or disappears, not as a permanent solution.

**Comment by quiddihub** [comment]
Hi Miguel,
Yes, I thought as much. Interestingly we have never had the issue running in our test environment under gevent or under the Werkzeug server. 

I'm interested that the issue only ever crops up at the authentication stage and never during any other WS interaction. Is it possible that something is failing and the thread dies? How would I test for that eventuality?

**Comment by miguelgrinberg** [comment]
I would expect that if there is an unexpected failure a stack trace would be logged. Technically it is not impossible that a failure occurs and the crash isn't reported, but I think it would be highly unlikely.

You can add logging in the writer thread I pointed out earlier if you like, to help detect unexpected crashes or the thread suddenly exiting on its own. Something I forgot to ask is if you see the PING/PONG messages every 25 seconds. If you see those in the log, then it means that the server and the client continue to communicate, so all the threads are still running. Of course you should check the SID value for these packets, you should be looking at the log entries for the specific SID that goes into the failure mode.

**Comment by quiddihub** [comment]
Miguel,
Yes, I meant to mention that earlier too. In the example I had this morning, the `emit()` takes place at 10:13 but the ping/pong takes place at 10:31, presumably ~25 from the connection time.

```
Jan 10 10:13:11 boatymbf dboard validate_user       :232  74002409 DEBUG - emitting: 'validated_user', { 'success': True, 'known': True, 'tfa': False } )
Jan 10 10:13:31 boutymbf dboard receive             :52   74022465 INFO - 65c06dea6dce427c82b47366f6148d96: Received packet PING data None
Jan 10 10:13:31 boatymbf dboard send                :94   74022468 INFO - 65c06dea6dce427c82b47366f6148d96: Sending packet PONG data None
```

The `emit()` is at line 233 in `validate_user`.  We have Sentry on the application and can confirm that is certainly not generating any alerts. I will start to add logging to the `python-engineio` package and come back to you when I have something.

Thanks for your help so far, much appreciated.

**Comment by miguelgrinberg** [comment]
@quiddihub was this log example that you just copied for a session that was in the failed state? If it was, the PING proves that the server is receiving, and the PONG proves that the server is still able to send. PONGs and regular events all go though the same path, so if one worked, the one should have worked as well. You should have a `Sending packet MESSAGE data ...` that matches your validated_user event, I would think.

**Comment by quiddihub** [comment]
Miguel,
Yes, that session is in the failed state. I'll confirm the presence of the `Sending packet` log line when I get back online.

**Comment by quiddihub** [comment]
Hi Miguel,
Hope you are well. Further to the above conversation, I have a little more information. Although it initially seems off topic I wondered if there was anything in the SocketIO library that depends on IP address. The reason I ask is I have seen 3 or 4 instances of the below. Although this isn't the same issue as above, it might have a bearing.

I can't include more information on the above as the event has not arisen since the last time I posted.

```
Jan 17 08:01:29 boatymbf dboard send                :94   596855657 INFO - c79ab61f672b403f8f437313932eabea: Sending packet OPEN data {'sid': 'c79ab61f672b403f8f437313932eabea', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
Jan 17 08:01:29 boatymbf dboard connect             :180  596855659 DEBUG - websocket connection from c79ab61f672b403f8f437313932eabea
Jan 17 08:01:29 boatymbf dboard emit                :284  596855659 INFO - emitting event "resp_connection" to c79ab61f672b403f8f437313932eabea [/]
Jan 17 08:01:29 boatymbf dboard send                :94   596855661 INFO - c79ab61f672b403f8f437313932eabea: Sending packet MESSAGE data 2["resp_connection",{"success":true,"id":"c79ab61f672b403f8f437313932eabea"}]
Jan 17 08:01:29 boatymbf dboard send                :94   596855662 INFO - c79ab61f672b403f8f437313932eabea: Sending packet MESSAGE data 0
Jan 17 08:01:29 boatymbf dboard handle_get_request  :104  596855768 INFO - c79ab61f672b403f8f437313932eabea: Received request to upgrade to websocket
Jan 17 08:01:29 localhost haproxy[19715]: X.148.74.154:28045 [17/Jan/2020:08:01:29.123] public~ admin_backend/boatymbf 23/0/1/75/99 200 178 - - --VN 1/1/1/1/0 0/0 {APP.com||https://admin.textmy.com/||Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36|} "GET /socket.io/?EIO=3&transport=polling&t=M-oXNW0&sid=c79ab61f672b403f8f437313932eabea HTTP/1.1"
Jan 17 08:01:59 boatymbf dboard _websocket_handler  :178  596885705 INFO - c79ab61f672b403f8f437313932eabea: Failed websocket upgrade, expected UPGRADE packet, received None instead.
Jan 17 08:01:59 localhost haproxy[19715]: X.112.182.111:25178 [17/Jan/2020:08:01:29.146] public~ admin_backend/boatymbf 42/0/1/1/29983 101 139 - - --VN 2/2/2/1/0 0/0 {APP.com||||Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36|} "GET /socket.io/?EIO=3&transport=websocket&sid=c79ab61f672b403f8f437313932eabea HTTP/1.1"
Jan 17 08:02:01 boatymbf dboard check_ping_timeout  :75   596887810 INFO - c79ab61f672b403f8f437313932eabea: Client is gone, closing socket
Jan 17 08:02:01 boatymbf dboard disconnect          :186  596887811 DEBUG - socket c79ab61f672b403f8f437313932eabea disconnected
Jan 17 08:02:01 boatymbf dboard check_ping_timeout  :75   596887812 INFO - c79ab61f672b403f8f437313932eabea: Client is gone, closing socket
Jan 17 08:02:01 localhost haproxy[19715]: 109.148.74.154:51937 [17/Jan/2020:08:01:29.258] public~ admin_backend/boatymbf 22/0/1/31954/31977 200 169 - - --VN 2/2/2/1/0 0/0 {APP.com||https://admin.textmy.com/||Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36|} "GET /socket.io/?EIO=3&transport=polling&t=M-oXNY7&sid=c79ab61f672b403f8f437313932eabea HTTP/1.1"
```

The above logging is application level logging, socketio, engineio and HAProxy logging. It shows a successful connect and response (this happens before the authentication exchange referred to above) along with an upgrade request. As you can see the upgrade fails, even though the HAProxy logs plainly show the requests taking place. _The HAProxy log output follows the application logging as the events are generated on completion, obviously_.

The only item of interest that differs from a successful attempt is that the client appears to be using a load balancing proxy which appears to spit out HTTP(s) requests on one of a number of public IP addresses. You can also see that the traffic is consistently routed by HAProxy to the correct backend server.

I just thought I would mention it in case it sheds any more light on the situation, although I suspect not as I assume, once the upgrade has happened there is a permanent connection/socket open and the traffic will flow through the same connection... unless there is provision for reconnecting that would suffer from the same problem.

Anyway, as I say, just mentioning in case it helps.

**Comment by quiddihub** [comment]
Hi Miguel,
Spoke too soon posting the comment this morning as the same error occurred almost immediately afterwards.

The comms level logging for a successful transaction is as follows;
```
Jan 17 10:40:22 boatymbf dboard send                :94   1062678  INFO - 5ea604191c574264ae84e1904d72439d: Sending packet OPEN data {'sid': '5ea604191c574264ae84e1904d72439d', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
Jan 17 10:40:22 boatymbf dboard connect             :180  1062679  DEBUG - websocket connection from 5ea604191c574264ae84e1904d72439d
Jan 17 10:40:22 boatymbf dboard emit                :284  1062680  INFO - emitting event "resp_connection" to 5ea604191c574264ae84e1904d72439d [/]
Jan 17 10:40:22 boatymbf dboard send                :94   1062681  INFO - 5ea604191c574264ae84e1904d72439d: Sending packet MESSAGE data 0
Jan 17 10:40:22 boatymbf dboard send                :94   1062683  INFO - 5ea604191c574264ae84e1904d72439d: Sending packet MESSAGE data 2["resp_connection",{"success":true,"id":"5ea604191c574264ae84e1904d72439d"}]
Jan 17 10:40:22 boatymbf dboard handle_get_request  :104  1062758  INFO - 5ea604191c574264ae84e1904d72439d: Received request to upgrade to websocket
Jan 17 10:40:22 localhost haproxy[19715]: 195.88.71.2:62199 [17/Jan/2020:10:40:22.692] public~ admin_backend/boatymbf 11/0/1/2/14 200 257 - - --VN 4/4/2/1/0 0/0 {admin.textmy.com||https://admin.textmy.com/||Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36|} "GET /socket.io/?EIO=3&transport=polling&t=M-p5l1z&sid=5ea604191c574264ae84e1904d72439d HTTP/1.1"
Jan 17 10:40:22 localhost haproxy[19715]: 195.88.71.2:17783 [17/Jan/2020:10:40:22.741] public~ admin_backend/boatymbf 11/0/1/2/14 200 178 - - --VN 4/4/2/1/0 0/0 {admin.textmy.com||https://admin.textmy.com/||Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36|} "GET /socket.io/?EIO=3&transport=polling&t=M-p5l2k&sid=5ea604191c574264ae84e1904d72439d HTTP/1.1"
Jan 17 10:40:22 boatymbf dboard _websocket_handler  :210  1062824  INFO - 5ea604191c574264ae84e1904d72439d: Upgrade to websocket successful
Jan 17 10:40:31 boatymbf dboard receive             :52   1071739  INFO - 5ea604191c574264ae84e1904d72439d: Received packet MESSAGE data 2["cmd_validate_user",{"session":"","user":{"username":"**********","password":"*******************************","code":""},"element":"login"}]
Jan 17 10:40:31 boatymbf dboard _handle_event       :640  1071740  INFO - received event "cmd_validate_user" from 5ea604191c574264ae84e1904d72439d [/]
Jan 17 10:40:31 boatymbf dboard cmd_validate_user   :192  1071741  DEBUG - session id is 5ea604191c574264ae84e1904d72439d
Jan 17 10:40:31 boatymbf dboard emit                :284  1071750  INFO - emitting event "resp_validated_user" to 5ea604191c574264ae84e1904d72439d [/]
Jan 17 10:40:31 boatymbf dboard send                :94   1071751  INFO - 5ea604191c574264ae84e1904d72439d: Sending packet MESSAGE data 2["resp_validated_user",{"success":true,"known":true,"tfa":false,"url":"home","auth":"5da086820efc7ad376524965.3506ab2f-602d-4dd4-8236-6b40da61408f"}]
```
As expect, `emit` generates its logging and `send` generates its... all good.

The failure processing for a few minutes earlier, however;
```
Jan 17 09:55:16 boatymbf dboard send                :94   603682929 INFO - 8f93f473feef4be59fdd305bb851be30: Sending packet OPEN data {'sid': '8f93f473feef4be59fdd305bb851be30', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
Jan 17 09:55:16 boatymbf dboard connect             :180  603682931 DEBUG - websocket connection from 8f93f473feef4be59fdd305bb851be30
Jan 17 09:55:16 boatymbf dboard emit                :284  603682931 INFO - emitting event "resp_connection" to 8f93f473feef4be59fdd305bb851be30 [/]
Jan 17 09:55:16 boatymbf dboard send                :94   603682932 INFO - 8f93f473feef4be59fdd305bb851be30: Sending packet MESSAGE data 0
Jan 17 09:55:16 boatymbf dboard handle_get_request  :104  603683093 INFO - 8f93f473feef4be59fdd305bb851be30: Received request to upgrade to websocket
Jan 17 09:55:16 localhost haproxy[19715]: 195.88.71.2:52553 [17/Jan/2020:09:55:16.488] public~ admin_backend/boatymbf 26/0/0/10/36 200 178 - - --VN 6/6/2/2/0 0/0 {APP.com||https://APP.com/||Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko|} "GET /socket.io/?EIO=3&transport=polling&t=M-oxQLS&sid=8f93f473feef4be59fdd305bb851be30 HTTP/1.1"
Jan 17 09:55:16 boatymbf dboard _websocket_handler  :210  603683113 INFO - 8f93f473feef4be59fdd305bb851be30: Upgrade to websocket successful
Jan 17 09:55:22 boatymbf dboard receive             :52   603689086 INFO - 8f93f473feef4be59fdd305bb851be30: Received packet MESSAGE data 2["cmd_validate_user",{"session":"5da086820efc7ad376524965.88c12484-7df0-49af-a49f-02f774456ced","user":{"username":"**********","password":"*******************************"},"element":"login"}]
Jan 17 09:55:22 boatymbf dboard _handle_event       :640  603689087 INFO - received event "cmd_validate_user" from 8f93f473feef4be59fdd305bb851be30 [/]
Jan 17 09:55:22 boatymbf dboard cmd_validate_user   :192  603689088 DEBUG - session id is 8f93f473feef4be59fdd305bb851be30
Jan 17 09:55:22 boatymbf dboard emit                :284  603689096 INFO - emitting event "resp_validated_user" to 8f93f473feef4be59fdd305bb851be30 [/]
Jan 17 09:55:41 boatymbf dboard receive             :52   603708060 INFO - 8f93f473feef4be59fdd305bb851be30: Received packet PING data None
Jan 17 09:55:41 boatymbf dboard send                :94   603708061 INFO - 8f93f473feef4be59fdd305bb851be30: Sending packet PONG data None
``` 
As you can see, the `emit` generates its logging as per the success case, however, the `send` function does not, even though the `PING` and `PONG` follow successfully.

I am about to enhance the logging of `python-engineio`, as you suggested, and will move my query to that project. I just wanted to give you a progress update and, for completeness, drop this information here in case anyone else has the same issue... and to provide a little more information about your previous assertion that if the PING/PONG is working then everything else is, because the engine plainly receives events and successfully PING/PONGs, but does not `send`.

**Comment by quiddihub** [comment]
Hi Miguel,
It's been a bit of a while but I wanted to update you on this item in case anyone has the same issue. It appears that the problem was related to the `message_queue` parameter and a remote Redis server. It appears that if the Redis server becomes unavailable for any reason the socket server stops sending messages but all the other activities (including `ping` & `pong`) appear to function normally.

Our LB is done using HAProxy so there was no need for the parameter to start with and I have no idea why it was ever added to the production build.

As I say, I hope this helps someone in the future who might have the same issue.

**Comment by miguelgrinberg** [comment]
Thanks for providing the details for your solution!
