### ISSUE TITLE
how many clients are connected? 

### ISSUE THREAD

**Issue by pauapaua** [miguelgrinberg/Flask-SocketIO#1152]
Hey guys,
is there a function to know , how many clients are conncted?
thank you :)

Cheers pau

**Comment by miguelgrinberg** [comment]
You can maintain a counter in your connect and disconnect handlers to know the client count. This package does not provide the count, because in some instances such as when using multiple servers it is expensive to calculate it.

**Comment by pauapaua** [comment]
Thank you.
IT IS possible to proove a Connection? Like
isConnectionStillAlive(clientId/sessionId)

Cheers pau

Miguel Grinberg <notifications@github.com> schrieb am Fr., 10. Jan. 2020,
15:30:

**Comment by miguelgrinberg** [comment]
You will be notified when a connection drops in the disconnect handler, so as long as you have not received a disconnect the connection is still on.
