### ISSUE TITLE
Python Generators with Flask_Socketio

### ISSUE THREAD

**Issue by Rashmi-P** [miguelgrinberg/Flask-SocketIO#1156]
Hi,

I just had a query, we are working with Kubernetes and using Flask-Socketio to establish communication between client and server. 
In Kubernetes, we have 'Watch' module, which gives us a stream of data which can be easily returned through generators and HTTP response,
Can we use generators with emit or send functions?

**Comment by miguelgrinberg** [comment]
I don't see how generators and Flask-SocketIO are related. If you are thinking in something like a Flask streamed response but with Socket.IO the answer is no, there is no streamed emits. But there is no issue if you emit each item returned by a generator, that should work just fine.

**Comment by Rashmi-P** [comment]
Thank you for replying. If my generator is returning stream of data with every change in the status of pod, is there a way to emit it without using sleep or delay continuously.

**Comment by miguelgrinberg** [comment]
You are using an asynchronous server, so you cannot block for long periods of time. If your generator does not allow other concurrent tasks to run, then your only option is to call `sleep(0)`. That's not something related to this package, it's just the way async servers work.

**Comment by Rashmi-P** [comment]
If we use sleep(0), it keeps sending the data even if there is no change in the watch of kubernetes. I have attached my code here. I'm new to this, could you please help me out with this.
In the frontend, they are using the same event names to get data from server.
[get_pods.txt](https://github.com/miguelgrinberg/Flask-SocketIO/files/4075486/get_pods.txt)

**Comment by miguelgrinberg** [comment]
Try something like this:

```python
for data in gen:
    socketio.emit('my_response', data)
    socketio.sleep(0)
```

**Comment by Rashmi-P** [comment]
Hi Miguel, this is working for me, I'm just converting generator object to JSON and sending.
Thank you very much :)

**Comment by Rashmi-P** [comment]
Hi Miguel,
I have multiple Watch methods like mentioned above which will continuously yield stream of data(with different events), do I have to make different connection for every stream(event) of data? Because we are facing some issues with sending multiple objects with multiple events at a time.

**Comment by miguelgrinberg** [comment]
Try adding a lock around the emit, I think that will be sufficient to prevent collisions between the multiple tasks.
