### ISSUE TITLE
10054, "An existing connection was forcibly closed by the remote host"

### ISSUE THREAD

**Issue by Adhders** [miguelgrinberg/Flask-SocketIO#1157]
there are  two tasks in my app , it will  fail with error message "westwell Error while reading from socket: (10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)"  when both tasks run frequntly. 
`app = Flask(__name__)

socketio =SocketIO(app,ping_interval=60,engineio_logger=True,logger=True)

app.config['SECRET_KEY'] = 'secret!'

red = RedisHelper()
conn=red.conn()

@socketio.on('mainpage', namespace='/westwell')
def mainpage():
    thread_1()

@socketio.on('plc_data', namespace='/westwell')
def plc():
    thread_2()

def thread_1():
    while True:
        info_data = red.subscribe("infohandler").parse_response(block=False, timeout=0)#非阻塞监听
        info=None
        if info_data:
            info = str(info_data[2], encoding="utf-8")
        socketio.emit("mainpage", {'value': info}, namespace="/westwell")
        socketio.sleep(0)

def thread_2():
    while True:
        plc_data = red.subscribe("plc_data").parse_response(block=False, timeout=0)
        plc=None
        if plc_data:
            plc = str(plc_data[2], encoding="utf-8")
    
        socketio.emit("plc_data", {"value": plc}, namespace="/westwell")
        socketio.sleep(0)

def main():
    socketio.run(app, host='0.0.0.0', debug=True,port=8080)

if __name__=="__main__":

    # pool.spawn_n(main())
    # pool.spawn_n(mainpage)
    # pool.spawn_n(plc)
    # pool.waitall()
    main()`

542cda9fd0404c7cb2068469d580e90e: Sending packet MESSAGE data 2/westwell,["plc_data",{"value":null}]
ab5eb73b49ee4f9bafbd7ee447fbe3ed: Sending packet MESSAGE data 2/westwell,["plc_data",{"value":null}]
emitting event "mainpage" to all [/westwell]
542cda9fd0404c7cb2068469d580e90e: Sending packet MESSAGE data 2/westwell,["mainpage",{"value":null}]
ab5eb73b49ee4f9bafbd7ee447fbe3ed: Sending packet MESSAGE data 2/westwell,["mainpage",{"value":null}]
emitting event "plc_data" to all [/westwell]
542cda9fd0404c7cb2068469d580e90e: Sending packet MESSAGE data 2/westwell,["plc_data",{"value":null}]
ab5eb73b49ee4f9bafbd7ee447fbe3ed: Sending packet MESSAGE data 2/westwell,["plc_data",{"value":null}]
emitting event "mainpage" to all [/westwell]
542cda9fd0404c7cb2068469d580e90e: Sending packet MESSAGE data 2/westwell,["mainpage",{"value":null}]
ab5eb73b49ee4f9bafbd7ee447fbe3ed: Sending packet MESSAGE data 2/westwell,["mainpage",{"value":null}]
emitting event "plc_data" to all [/westwell]
542cda9fd0404c7cb2068469d580e90e: Sending packet MESSAGE data 2/westwell,["plc_data",{"value":null}]
ab5eb73b49ee4f9bafbd7ee447fbe3ed: Sending packet MESSAGE data 2/westwell,["plc_data",{"value":null}]
emitting event "mainpage" to all [/westwell]
542cda9fd0404c7cb2068469d580e90e: Sending packet MESSAGE data 2/westwell,["mainpage",{"value":null}]
ab5eb73b49ee4f9bafbd7ee447fbe3ed: Sending packet MESSAGE data 2/westwell,["mainpage",{"value":null}]
emitting event "plc_data" to all [/westwell]
542cda9fd0404c7cb2068469d580e90e: Sending packet MESSAGE data 2/westwell,["plc_data",{"value":null}]
ab5eb73b49ee4f9bafbd7ee447fbe3ed: Sending packet MESSAGE data 2/westwell,["plc_data",{"value":null}]
emitting event "mainpage" to all [/westwell]
542cda9fd0404c7cb2068469d580e90e: Sending packet MESSAGE data 2/westwell,["mainpage",{"value":null}]
ab5eb73b49ee4f9bafbd7ee447fbe3ed: Sending packet MESSAGE data 2/westwell,["mainpage",{"value":null}]
emitting event "plc_data" to all [/westwell]
542cda9fd0404c7cb2068469d580e90e: Sending packet MESSAGE data 2/westwell,["plc_data",{"value":null}]
ab5eb73b49ee4f9bafbd7ee447fbe3ed: Sending packet MESSAGE data 2/westwell,["plc_data",{"value":null}]
emitting event "mainpage" to all [/westwell]
542cda9fd0404c7cb2068469d580e90e: Sending packet MESSAGE data 2/westwell,["mainpage",{"value":null}]
ab5eb73b49ee4f9bafbd7ee447fbe3ed: Sending packet MESSAGE data 2/westwell,["mainpage",{"value":null}]
emitting event "plc_data" to all [/westwell]
542cda9fd0404c7cb2068469d580e90e: Sending packet MESSAGE data 2/westwell,["plc_data",{"value":null}]
ab5eb73b49ee4f9bafbd7ee447fbe3ed: Sending packet MESSAGE data 2/westwell,["plc_data",{"value":null}]
emitting event "mainpage" to all [/westwell]
542cda9fd0404c7cb2068469d580e90e: Sending packet MESSAGE data 2/westwell,["mainpage",{"value":null}]
ab5eb73b49ee4f9bafbd7ee447fbe3ed: Sending packet MESSAGE data 2/westwell,["mainpage",{"value":null}]
emitting event "plc_data" to all [/westwell]
542cda9fd0404c7cb2068469d580e90e: Sending packet MESSAGE data 2/westwell,["plc_data",{"value":null}]
ab5eb73b49ee4f9bafbd7ee447fbe3ed: Sending packet MESSAGE data 2/westwell,["plc_data",{"value":null}]
emitting event "mainpage" to all [/westwell]
542cda9fd0404c7cb2068469d580e90e: Sending packet MESSAGE data 2/westwell,["mainpage",{"value":null}]
ab5eb73b49ee4f9bafbd7ee447fbe3ed: Sending packet MESSAGE data 2/westwell,["mainpage",{"value":null}]
emitting event "plc_data" to all [/westwell]
542cda9fd0404c7cb2068469d580e90e: Sending packet MESSAGE data 2/westwell,["plc_data",{"value":null}]
ab5eb73b49ee4f9bafbd7ee447fbe3ed: Sending packet MESSAGE data 2/westwell,["plc_data",{"value":null}]
emitting event "mainpage" to all [/westwell]
542cda9fd0404c7cb2068469d580e90e: Sending packet MESSAGE data 2/westwell,["mainpage",{"value":null}]
ab5eb73b49ee4f9bafbd7ee447fbe3ed: Sending packet MESSAGE data 2/westwell,["mainpage",{"value":null}]
emitting event "plc_data" to all [/westwell]
542cda9fd0404c7cb2068469d580e90e: Sending packet MESSAGE data 2/westwell,["plc_data",{"value":null}]
ab5eb73b49ee4f9bafbd7ee447fbe3ed: Sending packet MESSAGE data 2/westwell,["plc_data",{"value":null}]
emitting event "mainpage" to all [/westwell]
542cda9fd0404c7cb2068469d580e90e: Sending packet MESSAGE data 2/westwell,["mainpage",{"value":null}]
ab5eb73b49ee4f9bafbd7ee447fbe3ed: Sending packet MESSAGE data 2/westwell,["mainpage",{"value":null}]
emitting event "plc_data" to all [/westwell]
542cda9fd0404c7cb2068469d580e90e: Sending packet MESSAGE data 2/westwell,["plc_data",{"value":null}]
ab5eb73b49ee4f9bafbd7ee447fbe3ed: Sending packet MESSAGE data 2/westwell,["plc_data",{"value":null}]
emitting event "mainpage" to all [/westwell]
542cda9fd0404c7cb2068469d580e90e: Sending packet MESSAGE data 2/westwell,["mainpage",{"value":null}]
ab5eb73b49ee4f9bafbd7ee447fbe3ed: Sending packet MESSAGE data 2/westwell,["mainpage",{"value":null}]
ab5eb73b49ee4f9bafbd7ee447fbe3ed: Sending packet MESSAGE data 3/westwell,1[]
westwell Error while reading from socket: (10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)
westwell Error while reading from socket: (10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)
ab5eb73b49ee4f9bafbd7ee447fbe3ed: Sending packet MESSAGE data 3/westwell,0[]
542cda9fd0404c7cb2068469d580e90e: Unexpected error "timed out", closing connection
192.168.105.102 - - [16/Jan/2020 17:47:32] "GET /socket.io/?EIO=3&transport=websocket&sid=542cda9fd0404c7cb2068469d580e90e HTTP/1.1" 200 0 60.025060
b0d20ae811d64725827f4b652fd377c9: Sending packet OPEN data {'sid': 'b0d20ae811d64725827f4b652fd377c9', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 60000}
b0d20ae811d64725827f4b652fd377c9: Sending packet MESSAGE data 0
192.168.105.102 - - [16/Jan/2020 17:47:33] "GET /socket.io/?EIO=3&transport=polling&t=M-jm3nC HTTP/1.1" 200 401 0.002961
b0d20ae811d64725827f4b652fd377c9: Received packet MESSAGE data 0/westwell,
b0d20ae811d64725827f4b652fd377c9: Sending packet MESSAGE data 0/westwell
192.168.105.102 - - [16/Jan/2020 17:47:33] "POST /socket.io/?EIO=3&transport=polling&t=M-jm3nS&sid=b0d20ae811d64725827f4b652fd377c9 HTTP/1.1" 200 219 0.001992
192.168.105.102 - - [16/Jan/2020 17:47:33] "GET /socket.io/?EIO=3&transport=polling&t=M-jm3nU&sid=b0d20ae811d64725827f4b652fd377c9 HTTP/1.1" 200 247 0.001001
(16180) accepted ('192.168.105.102', 49736)
b0d20ae811d64725827f4b652fd377c9: Received request to upgrade to websocket
192.168.105.102 - - [16/Jan/2020 17:47:33] "GET /socket.io/?EIO=3&transport=polling&t=M-jm3ng&sid=b0d20ae811d64725827f4b652fd377c9 HTTP/1.1" 200 235 0.003000
b0d20ae811d64725827f4b652fd377c9: Upgrade to websocket successful
ab5eb73b49ee4f9bafbd7ee447fbe3ed: Received packet PING data None
ab5eb73b49ee4f9bafbd7ee447fbe3ed: Sending packet PONG data None
server=localhost:8080//socket.io/ client=127.0.0.1:62740 socket shutdown error: [WinError 10054] An existing connection was forcibly closed by the remote host127.0.0.1 - - [16/Jan/2020 17:47:45] "GET /socket.io/?EIO=3&transport=websocket&sid=ab5eb73b49ee4f9bafbd7ee447fbe3ed HTTP/1.1" 200 0 65.036599
eb0fa3b08e64444784817ab2831bbb0f: Sending packet OPEN data {'sid': 'eb0fa3b08e64444784817ab2831bbb0f', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 60000}
eb0fa3b08e64444784817ab2831bbb0f: Sending packet MESSAGE data 0
127.0.0.1 - - [16/Jan/2020 17:47:46] "GET /socket.io/?EIO=3&transport=polling&t=M-jm6r- HTTP/1.1" 200 384 0.000998
eb0fa3b08e64444784817ab2831bbb0f: Received packet MESSAGE data 0/westwell
eb0fa3b08e64444784817ab2831bbb0f: Sending packet MESSAGE data 0/westwell
127.0.0.1 - - [16/Jan/2020 17:47:46] "POST /socket.io/?EIO=3&transport=polling&t=M-jm6sC&sid=eb0fa3b08e64444784817ab2831bbb0f HTTP/1.1" 200 202 0.000998
127.0.0.1 - - [16/Jan/2020 17:47:46] "GET /socket.io/?EIO=3&transport=polling&t=M-jm6sJ&sid=eb0fa3b08e64444784817ab2831bbb0f HTTP/1.1" 200 230 0.000000
eb0fa3b08e64444784817ab2831bbb0f: Received packet MESSAGE data 2/westwell,0["mainpage"]
received event "mainpage" from eb0fa3b08e64444784817ab2831bbb0f [/westwell]
emitting event "mainpage" to all [/westwell]
b0d20ae811d64725827f4b652fd377c9: Sending packet MESSAGE data 2/westwell,["mainpage",{"value":null}]
eb0fa3b08e64444784817ab2831bbb0f: Sending packet MESSAGE data 2/westwell,["mainpage",{"value":null}]
127.0.0.1 - - [16/Jan/2020 17:47:46] "GET /socket.io/?EIO=3&transport=polling&t=M-jm6sU&sid=eb0fa3b08e64444784817ab2831bbb0f HTTP/1.1" 200 258 0.000000
127.0.0.1 - - [16/Jan/2020 17:47:46] "POST /socket.io/?EIO=3&transport=polling&t=M-jm6sT&sid=eb0fa3b08e64444784817ab2831bbb0f HTTP/1.1" 200 202 0.014961
emitting event "mainpage" to all [/westwell]
b0d20ae811d64725827f4b652fd377c9: Sending packet MESSAGE data 2/westwell,["mainpage",{"value":null}]
eb0fa3b08e64444784817ab2831bbb0f: Sending packet MESSAGE data 2/westwell,["mainpage",{"value":null}]
emitting event "mainpage" to all [/westwell]
b0d20ae811d64725827f4b652fd377c9: Sending packet MESSAGE data 2/westwell,["mainpage",{"value":null}]
eb0fa3b08e64444784817ab2831bbb0f: Sending packet MESSAGE data 2/westwell,["mainpage",{"value":null}]
eb0fa3b08e64444784817ab2831bbb0f: Received packet MESSAGE data 2/westwell,1["plc_data"]
received event "plc_data" from eb0fa3b08e64444784817ab2831bbb0f [/westwell]
127.0.0.1 - - [16/Jan/2020 17:47:47] "GET /socket.io/?EIO=3&transport=polling&t=M-jm6sq&sid=eb0fa3b08e64444784817ab2831bbb0f HTTP/1.1" 200 301 0.000000
eb0fa3b08e64444784817ab2831bbb0f: Sending packet MESSAGE data 3/westwell,1[]
eb0fa3b08e64444784817ab2831bbb0f: Sending packet MESSAGE data 3/westwell,0[]
127.0.0.1 - - [16/Jan/2020 17:47:47] "GET /socket.io/?EIO=3&transport=polling&t=M-jm6tA&sid=eb0fa3b08e64444784817ab2831bbb0f HTTP/1.1" 200 253 0.000996
127.0.0.1 - - [16/Jan/2020 17:47:47] "POST /socket.io/?EIO=3&transport=polling&t=M-jm6sv&sid=eb0fa3b08e64444784817ab2831bbb0f HTTP/1.1" 200 202 0.019941
westwell Error while reading from socket: (10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)
westwell Error while reading from socket: (10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)

**Comment by miguelgrinberg** [comment]
Are you using eventlet or gevent with your application? If yes, have you monkey patched the standard library?

**Comment by Adhders** [comment]
I don't set the async_mode，so I use the default. And I don't know about the library need patch.
How can I patch the library？thanks



发自我的iPhone


------------------ Original ------------------

**Comment by miguelgrinberg** [comment]
@Adhders okay, start by removing gevent-websocket, you do not need that, since you are using the eventlet async mode by default.

See https://eventlet.net/doc/patching.html with regards to patching the standard library. This is required when you use threads, sockets or other blocking things in an eventlet application.

**Comment by Adhders** [comment]
@miguelgrinberg  very thanks to you ,I make it !
