### ISSUE TITLE
KeyError: 'Session is disconnected'

### ISSUE THREAD

**Issue by Adhders** [miguelgrinberg/Flask-SocketIO#1158]
I have referenced #597,#814,#179, and there is no help   to use “try  ..  except ” to catch the error, 
how can I catch and handle this error? thanks!

932ad25b5ade43bcb2bfde891ce01ed6: Received request to upgrade to websocket
emitting event "mainpage" to all [/westwell]
932ad25b5ade43bcb2bfde891ce01ed6: Sending packet MESSAGE data 2/westwell,["mainpage",{"value":null}]
86a61baff1f94decb31daa45e685b3de: Sending packet MESSAGE data 2/westwell,["mainpage",{"value":null}]
86a61baff1f94decb31daa45e685b3de: Received request to upgrade to websocket
192.168.105.102 - - [16/Jan/2020 18:16:42] "GET /socket.io/?EIO=3&transport=polling&t=M-jsflu&sid=932ad25b5ade43bcb2bfde891ce01ed6 HTTP/1.1" 200 740 10.094744
127.0.0.1 - - [16/Jan/2020 18:16:42] "GET /socket.io/?EIO=3&transport=polling&t=M-jsk1Y&sid=86a61baff1f94decb31daa45e685b3de HTTP/1.1" 200 258 0.000996
86a61baff1f94decb31daa45e685b3de: Received packet MESSAGE data 2/westwell,["message",{"data":"I'm disconnected!"}]
received event "message" from 86a61baff1f94decb31daa45e685b3de [/westwell]
emitting event "mainpage" to all [/westwell]
932ad25b5ade43bcb2bfde891ce01ed6: Sending packet MESSAGE data 2/westwell,["mainpage",{"value":null}]
86a61baff1f94decb31daa45e685b3de: Sending packet MESSAGE data 2/westwell,["mainpage",{"value":null}]
emitting event "plc_data" to all [/westwell]
932ad25b5ade43bcb2bfde891ce01ed6: Sending packet MESSAGE data 2/westwell,["plc_data",{"value":"{\"crane_id\": \"QC106\", \"timestamp\": 3920735936, \"ls_trolley_pos\": \"26.6\", \"ls_trolley_speed\": \"00.0\", \"ls_spreader_size\": \"40\", \"ls_twistlock\": \"0\", \"ls_spreader_height\": \"03.4\", \"ls_spreader_speed\": \"25.6\", \"lane\": \"2\", \"move_type\": \"load\"}"}]
86a61baff1f94decb31daa45e685b3de: Sending packet MESSAGE data 2/westwell,["plc_data",{"value":"{\"crane_id\": \"QC106\", \"timestamp\": 3920735936, \"ls_trolley_pos\": \"26.6\", \"ls_trolley_speed\": \"00.0\", \"ls_spreader_size\": \"40\", \"ls_twistlock\": \"0\", \"ls_spreader_height\": \"03.4\", \"ls_spreader_speed\": \"25.6\", \"lane\": \"2\", \"move_type\": \"load\"}"}]
emitting event "mainpage" to all [/westwell]
932ad25b5ade43bcb2bfde891ce01ed6: Sending packet MESSAGE data 2/westwell,["mainpage",{"value":null}]
86a61baff1f94decb31daa45e685b3de: Sending packet MESSAGE data 2/westwell,["mainpage",{"value":null}]
emitting event "mainpage" to all [/westwell]
932ad25b5ade43bcb2bfde891ce01ed6: Sending packet MESSAGE data 2/westwell,["mainpage",{"value":null}]
86a61baff1f94decb31daa45e685b3de: Sending packet MESSAGE data 2/westwell,["mainpage",{"value":null}]
emitting event "mainpage" to all [/westwell]
932ad25b5ade43bcb2bfde891ce01ed6: Sending packet MESSAGE data 2/westwell,["mainpage",{"value":null}]
86a61baff1f94decb31daa45e685b3de: Sending packet MESSAGE data 2/westwell,["mainpage",{"value":null}]
emitting event "mainpage" to all [/westwell]
932ad25b5ade43bcb2bfde891ce01ed6: Client is gone, closing socket
932ad25b5ade43bcb2bfde891ce01ed6: Client is gone, closing socket
86a61baff1f94decb31daa45e685b3de: Client is gone, closing socket
86a61baff1f94decb31daa45e685b3de: Client is gone, closing socket
Traceback (most recent call last):
  File "D:\Python37\lib\site-packages\eventlet\wsgi.py", line 566, in handle_one_response
    result = self.application(self.environ, start_response)
  File "D:\Python37\lib\site-packages\flask\app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "D:\Python37\lib\site-packages\flask_socketio\__init__.py", line 46, in __call__
    start_response)
  File "D:\Python37\lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "D:\Python37\lib\site-packages\socketio\server.py", line 534, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "D:\Python37\lib\site-packages\engineio\server.py", line 373, in handle_request
    socket = self._get_socket(sid)
  File "D:\Python37\lib\site-packages\engineio\server.py", line 561, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'

**Comment by miguelgrinberg** [comment]
This isn't an error that you can handle. The problem is that your clients and the server don't have a fluid communication. At some point the server thinks two of your clients have left and declares them gone, but then a bit later they show up again when it is too late.

This could be due to badly behaving clients, or also due to a server that is blocked and cannot timely respond to client pings.

**Comment by WeekiCode** [comment]
I get this error from www.google.com/bot.html  .... is there a way to fix it?
