### ISSUE TITLE
multiplayer rooms 

### ISSUE THREAD

**Issue by hghaffar2** [miguelgrinberg/Flask-SocketIO#1162]
**Questions**:

How do I identify the users within a room by just knowing the name of the room?

Was wondering if there is a dynamic way to connect 2 users automatically in a multiplayer game?

How does multiplayer work in mobile games? For example, in some mobile games I press the battle button and the game connects me to an opponent within seconds.

**Log**: Here I generated a room name. However, what follows this? Or, what am I missing....

def generate_room():
    letters = string.ascii_letters
    room = ''.join(random.choice(letters) for i in range(8))
    return room

Thank you in advance, you have already been so helpful.

**Comment by miguelgrinberg** [comment]
You should keep track of which players are connected in your own applications, this package does not provide this information. I think you may be looking for a gaming communication library, which this is not. You can use this package for your needs, but the connections between players need to be handled by your game.
