### ISSUE TITLE
Know All Connected User's

### ISSUE THREAD

**Issue by deounix** [miguelgrinberg/Flask-SocketIO#1163]
As said here [how-to-disconnect-all-sockets-serve-side-using-socket-io](https://stackoverflow.com/questions/30570658/how-to-disconnect-all-sockets-serve-side-using-socket-io#answer-30578695)

In SocketIO JS we can get a list of connected sockets.

Why in python ?

We need some how to know if user is still connected or not cuz what I did is this:

1. I created a two decorators on connect && disconnect users.
2. I saved users session (sid) in redis memory.

The problem is some time my redis server or my python project get fail for some reason and get shutdown so the old staff of users still exists in redis memory.

In my scenario single user can connect and open multi sessions. why ?
Cuz am making something like BOTS so one (bot - username) can connect from multi server (bots are executing heavy functions on servers) it's like a load balancing but on client side

eg: Server check if username have multi sessions then send a custom ping request to all user sessions then the first one who respond to my request he can execute my command cuz he's available .... etc

The problem is sometime gunicorn or redis stopped. So is there any thing I can do to check if user is connected or not to socketio ? something good more than I make a callback or .... etc

**Comment by miguelgrinberg** [comment]
I have answered this questions many times. This package does not keep track of the list of users. Your application can do that using the connect and disconnect handlers.

**Comment by deounix** [comment]
@miguelgrinberg Sorry for bothering you with the same question.

There's a scenario that both of (connect & disconnect) handlers not helping me.
Assuming that I have this architecture :

![tBYmkkAMQWWX](https://user-images.githubusercontent.com/17798647/72785884-e4094480-3c34-11ea-9431-9f44120fc9c4.png)

**Comment by miguelgrinberg** [comment]
If the server dies it is impossible to call the disconnect handlers. It seems you are suggesting the handlers should be invoked on the other server, but that's really not possibly, as the other server(s) have no knowledge of the users that were on the server that went offline.

On redis a good solution is to write your keys with a timeout. Your clients can send a hearbeat at regular intervals that trigger a refresh on their redis registration. If a server dies, then those entries will expire on their own, and the clients will reconnect through a different server.

**Comment by deounix** [comment]
@miguelgrinberg thnx. it's clear now.
