### ISSUE TITLE
Server gets "stuck" and will not take incoming requests

### ISSUE THREAD

**Issue by flabbyThoroughbred** [miguelgrinberg/Flask-SocketIO#1166]
I have a simple server set up that currently does two routes, gathers data from a database and displays it in html and one that submits commands to a terminal via subprocess.

I have the server configured to use gevent, engineio_logger is enabled. Running on python 3.8.

Here's my requirements log
```
certifi==2019.9.11
cffi==1.13.2
chardet==3.0.4
Click==7.0
cssmin==0.2.0
Flask==1.1.1
Flask-Assets==0.12
Flask-SocketIO==4.2.1
gevent==1.4.0
gevent-websocket==0.10.1
greenlet==0.4.15
idna==2.8
itsdangerous==1.1.0
Jinja2==2.10.3
jsmin==2.2.2
MarkupSafe==1.1.1
pycparser==2.19
pymongo==3.9.0
python-engineio==3.10.0
python-socketio==4.3.1
requests==2.22.0
shotgun-api3==3.2.0
six==1.12.0
urllib3==1.25.6
webassets==0.12.1
Werkzeug==0.16.0
```

I use socket-io to communicate between the python code and the javascript when gathering data from the database and displaying it on the web page.

I post data to the other route that then runs a command using subprocess.

This seems to work fine for a while, I can trigger either route and they work as expected. Lately I've noticed that the server gets "stuck" and I cannot send requests to either route.

Most of the time the terminal display is similar to
```
b974731d348b4853bfdf9ae111fbd2e9: Sending packet PONG data None
0e31ea1d94564b5da6ea6dd7a79b6403: Received packet PING data None
0e31ea1d94564b5da6ea6dd7a79b6403: Sending packet PONG data None
b974731d348b4853bfdf9ae111fbd2e9: Received packet PING data None
b974731d348b4853bfdf9ae111fbd2e9: Sending packet PONG data None
0e31ea1d94564b5da6ea6dd7a79b6403: Received packet PING data None
```

If i find that the server is stuck, pressing ctrl+c once sometimes helps it along. This seems to be temporary however and in most cases I'm forced to restart the server.

this is my __init__.py file
```
import gevent.monkey
gevent.monkey.patch_all()
async_mode = 'gevent'

# import eventlet
# from eventlet import monkey_patch as monkey_patch
# monkey_patch(subprocess=True)
# async_mode = 'eventlet'

import os, sys
import logging
import logging.handlers as logHandlers

from flask import Flask
from flask_assets import Bundle, Environment
from app import configs
from flask_socketio import SocketIO, emit

sio = SocketIO()

_Configs = configs.DevelopmentConfig    

# app = Flask(__name__, static_url_path='')
app = Flask(__name__)

app.config.from_object(_Configs)
app.config.update()

sio.init_app(app, async_mode=async_mode, engineio_logger=True)

from app import routes
from app import assets
```

Both the function to gather data for the web page and the subprocess submission are on the same thread. I'm not sure if this is the best way to go about it but it seems like nothing in particular causes the server to seize up.

Here are my routes:

```
@app.route('/event_history', methods=['GET', 'POST'])
def request_event_history():
    data = request.form

    evt_data = build_event_data(data['id'])

    return render_template('event_history.html', 
                           columns=evt_data['fields'], 
                           title='Event History',
                           rows=evt_data['rows'])
```

Here build_event_data is accessing a database. 

```
@app.route('/submit_script', methods=['GET', 'POST'])
def submit_script():
    data = request.form

    success = dl_submit_script(data)

    return json.dumps({'return_code': success[0], 'stdout': repr(success[1]), 'stderr': repr(success[2])})
```
Here dl_submit_script takes the data parcel and parses it into a subprocess command and runs subprocess.Popen

Does anything look out of the ordinary here?

Thanks!

**Comment by miguelgrinberg** [comment]
Does the problem remain if you replace the call to `dl_submit_script()` with a mock version? I'm wondering if something you do in that function is blocking.

**Comment by flabbyThoroughbred** [comment]
I replaced it with a function that just parses and returns the data again. I'll monitor it for a while and see if it gets stuck.

In the meantime I'll try some other methods based on the socketio git examples.

Thanks for your help!

**Comment by flabbyThoroughbred** [comment]
I couldn't reproduce the issue with a function that just passes the data.

I'm currently trying to start a background task with the subprocess submitter passed to it and I still find that it gets hung up.

my submitter code looks like this
```
def clear_dead_threads():
    global threads
    for thr in threads:
        if thr.dead:
            app.logger.info('removing old thread {}'.format(thr))
            threads.remove(thr)


@app.route('/pyscript_submitter', methods=['GET', 'POST'])
def submit_script():
    global threads
    data = request.form
    try:
        clear_dead_threads()
        threads.append(sio.start_background_task(dl_submit_script, data))
        # threads.append(gevent.spawn(dl_submit_script, data)) # I was trying to spawn a gevent thread to see if that would work. same issues arose
        return 'Job Submitted', 200    
    except Exception as e:
        return 'Job Submission Failed: {}'.format(e), 400
```

A couple thoughts:
Something about my data request might be screwing things up. I'm not passing anything
too egregious - mostly strings and some jsonified data. If it would help I can drop that info in a database and send along just an ID with the post. In the flask route I can collect it.

I have a timeout set where I post this data to the waiting flask route. Is this a bad idea? I mostly want to use it as a means to find out if the server itself is having issues receiving it. which leads to my last thought.

Am I implementing my flask route function in such a way that any return status could would be received? I honestly don't think I'm implementing the background threads correctly nor am I dealing with my active/dead threads in the best way. Any advice on implementation would be greatly appreciated.

Thanks!

**Comment by miguelgrinberg** [comment]
What do you do in `dl_submit_script`? That's key to understand the problem. Based on your description my guess is that you are blocking there.

**Comment by flabbyThoroughbred** [comment]
My apologies. I forgot to include that code.
```
def dl_submit_script(script_path='',
                     group='',
                     job_name='',
                     executable=r"C:\Python27\python.exe",
                     script_args=None,
                     dl_postscript='',
                     extra_info=None,
                     dl_pool='low',
                     sec_pool='',
                     email='',
                     priority='50'):

    '''
      Submits python scripts to Deadline via subprocess.
      Returns return code, stdout and stderr as tuple.

      arguments:
          - script_path: <str> full path to python script
          - group: <str> deadline group name
          - job_name: <str> job name
          - python_path: <str> Default python executable location.
            (User can specify another python app so long as it is valid)
          - script_args: <list> optional script arguments. Must match args
            count of calling script.
          - dl_postscript: <str> OPTIONAL post script to run.
          - extra_info: <dict> OPTIONAL key/value pair of whatever relevant
            arguments need to be included. If post script requires arguments,
            pass them here.
          - dl_pool: <str> primary deadline render pool. Defaults to 'low'.
          - sec_pool: <str> OPTIONAL secondary deadline render pool.
          - priority: <int> sets job queue priority. Default is 50.
    '''
    dl_app = 'deadlinecommand.exe'
    dl_path = r"C:\Program Files\Thinkbox\Deadline10\bin"
    str_args = ' '.join(script_args)
    run_script_args = [dl_app,
                       '-SubmitCommandLineJob',
                       '-executable',
                       '{}'.format(executable),
                       '-arguments',
                       '"{}" {}'.format(script_path, str_args),
                       '-pool',
                       dl_pool,
                       '-group',
                       group,
                       '-name',
                       job_name,
                       '-priority',
                       priority
                      ]

    # ######################### ADD EXTRA ARGUMENTS ############################
    # build extra info arguments if applicable
    if extra_info:
        ei_list = []
        count = 0
        for key in extra_info:
           ei_list.append('-prop')
           ei_list.append('ExtraInfoKeyValue{}={}={}'.format(count, key, extra_info[key]))
           count+=1

        run_script_args.extend(ei_list)

    # add postscript if using.
    # <WARNING> if post script requires arguments, pass them in
    # the extra info args dictionary!
    if dl_postscript:
        run_script_args.append('-prop')
        run_script_args.append('PostJobScript={}'.format(dl_postscript))

    # add secondary pool argument if using
    if sec_pool:
        run_script_args.append('-prop')
        run_script_args.append('SecondaryPool={}'.format(sec_pool))
    
    if email:
        run_script_args.append('-prop')
        run_script_args.append('NotificationEmails={}'.format(email))
        run_script_args.append('-prop')
        run_script_args.append('OverrideNotificationMethod=true')
        run_script_args.append('-prop')
        run_script_args.append('EmailNotification=true')

    p = Popen(run_script_args, stdin=PIPE, stdout=PIPE, stderr=PIPE, executable=os.path.join(dl_path, dl_app))
    stdout, stderr = p.communicate()

    LOGGER.info("subprocess return code: {}".format(p.returncode))
    LOGGER.info("subprocess stdout: {}".format(repr(stdout)))
    LOGGER.info("subprocess stderr: {}".format(repr(stderr)))

    return (p.returncode, stdout, stderr)
```

Deadline is a render queue that you can also pass scripts to to run on worker nodes. I'm using this instead of, say, celery to do heavy lifting tasks.

Deadline does have a REST api that I believe I can submit jobs to. I plan on looking into that and see if it helps. But it would be great to know what about this function is causing issues with flask/socketio.

Thanks!

**Comment by miguelgrinberg** [comment]
Are you sure `subprocess.Popen` is monkey patched? It would be useful to verify that, because if it isn't that would definitely block your server.

**Comment by flabbyThoroughbred** [comment]
It just occurred to me that the fact that I'm importing the module that contains that function would not(?) be monkey patched.

Is this a correct assumption? A custom imported module that import subprocess would not have its subprocess monkey-patched?

As a test I moved this function within my flask app to see if there's any change.

**Comment by miguelgrinberg** [comment]
If the monkey patching is done at the very start of the application, all imports of the affected packages should redirect to the alternative version. The problem is if monkey patching is not done first thing after start, then you may end up with weird behavior due to some blocking functions being used.
