### ISSUE TITLE
Mistake in tutorial. Not imported send function in Rooms section

### ISSUE THREAD

**Issue by TiredFingers** [miguelgrinberg/Flask-SocketIO#1167]
Hello, everybody! Is it a mistake in the tutorial https://flask-socketio.readthedocs.io/en/latest/#rooms

here is using a send function without importing it. 

`from flask_socketio import join_room, leave_room

@socketio.on('join')
def on_join(data):
    username = data['username']
    room = data['room']
    join_room(room)
    send(username + ' has entered the room.', room=room)

@socketio.on('leave')
def on_leave(data):
    username = data['username']
    room = data['room']
    leave_room(room)
    send(username + ' has left the room.', room=room)`

**Comment by miguelgrinberg** [comment]
These are code snippets, not complete scripts. Note that only the first time a function is used it is imported, any follow up snippets of code assume the function has been already imported.

**Comment by TiredFingers** [comment]
Ok, thanks
