### ISSUE TITLE
Statistics/Monitoring Solution?

### ISSUE THREAD

**Issue by umityayla** [miguelgrinberg/Flask-SocketIO#1168]
Hello,

I've been using APM Server + Elastic Search + Kibana stack for a while for our Rest API. But, now that we have socket.io in it, I can't properly get enough data from our socket endpoints. I remember reading there's no such thing something like @before_request in Flask. So, I wonder what is the proper way to collect/view data and monitor the socker server?

**Comment by miguelgrinberg** [comment]
One option is to use a class-based namespace, which allows you to override the dispatching method and add any monitoring logic you need there.

**Comment by umityayla** [comment]
Thank you for your reply, love your work.
