### ISSUE TITLE
emit not working in socket with leave_room

### ISSUE THREAD

**Issue by D-E-F-E-A-T** [miguelgrinberg/Flask-SocketIO#1169]
**Describe the bug**
I am working with rooms, when I am using _leave_room_ inside the socket function then _emit_ is not emiting to client side. I have checked for any errors on client side or in function but they all fine, even if I simply replace _leave_room_ with _join_room_ then emit is working fine.

**To Reproduce**
Server side

```
@socketio.on('leave')
def on_leave(data):
    username = data["username"]
    room = data["room"]
    leave_room(room)
    mymessage = 'user {} has joined room {}'.format(username, room)
    emit('room_leave', mymessage, room=room)
```
Client side

```
    socket.on('room_leave', function(msg) {
        alert(msg);
    });
```

[Entire server code](http://bit.ly/2tZQUwh)
[Entire client code](https://www.paste.org/102640)

**Expected behavior**
It should emit to the client side

**Additional context**
I checked the code many number of times if still I am missing something then tell please.

**Comment by miguelgrinberg** [comment]
When you say "it should emit to the client side" which client(s) are you referring to? The client that left the room is not in the room anymore, so it's not going to receive anything. Other clients that are already in the room should receive the message.
