### ISSUE TITLE
Question: Emitting to a room from a background thread?

### ISSUE THREAD

**Issue by ktoh** [miguelgrinberg/Flask-SocketIO#117]
The [example app](https://github.com/miguelgrinberg/Flask-SocketIO/blob/master/example/app.py#L17) has a nice implementation of a singleton background thread can perform periodic tasks:

    def background_thread():
        """Example of how to send server generated events to clients."""
        count = 0
        while True:
            time.sleep(10)
            count += 1
            socketio.emit('my response',
                          {'data': 'Server generated event', 'count': count},
                          namespace='/test')

A problem arises when the thread needs to emit messages to a particular room, say `my_room`:

* The thread isn't a participant in `my_room` by default, so it would need to join the room before attempting the `emit()`.
* But when I try to use `join_room()` or the `_join_room(...)` method to accomplish this, I realize the `join...` methods depend on a request context.  

Since the background thread is a singleton that runs outside of any particular request context, the code fails.

Is there a way to emit a server-generated event to a particular room using the example app's background thread?

**Comment by miguelgrinberg** [comment]
The thread does not own a participant, so it does not need to join rooms to send messages to them. Just add `room='room_name'` as an argument to the `emit()` call.

**Comment by ktoh** [comment]
I've done some further investigation on this.

I think what is happening is:

1. When chat rooms are created, they are added to the room's namespace, and also to the `socketio` singleton's `.rooms`.  From [__init__.py](https://github.com/miguelgrinberg/Flask-SocketIO/blob/master/flask_socketio/__init__.py#L74):
>```
>def join_room(self, room):
>    if self.socketio._join_room(self, room):
>        self.rooms.add(room)
>```

2. When the background thread performs an emit to a room ( `socketio.emit(event, data, room="myroom")`), it attempts to find the room on the `socketio` singleton. From [__init__.py](https://github.com/miguelgrinberg/Flask-SocketIO/blob/master/flask_socketio/__init__.py#L74):
>```
>if room is not None:
>    for client in self.rooms.get(ns_name, {}).get(room, set()):
>        client.base_emit(event, *args, **kwargs)
>```

**However** what is happening is, the background thread's `socketio` singleton is not getting synced properly with the main thread's `socketio`:

**Main thread:**
```
print socketio
   <flask_socketio.SocketIO object at 0x22b6a10>
print socketio.rooms
   { '/mynamespace': {'mychat': set([<flask_socketio.GenericNamespace object at 0x5cb6450>]) } }
```

**Background thread:**
```
print socketio
   <flask_socketio.SocketIO object at 0x22b6a10>
print socketio.rooms
   {}
```

...the `socketio` instances appear to be the same, but somehow their `.rooms` attributes have gotten unsynced between the main thread and the background thread.

Any idea why this is happening?

**Comment by miguelgrinberg** [comment]
Do you have your application somewhere I can see it?

**Comment by ktoh** [comment]
Not up live, but here's the very simple code:

```
import logging
import time
from threading import Thread

from flask.ext.security import current_user
from application.web_app import socketio, db, app
from flask.ext.socketio import emit, join_room

logger = logging.getLogger(__name__)
CHAT_NAMESPACE = '/chat'


@socketio.on('send-reply', namespace=CHAT_NAMESPACE)
def chat_reply(payload):

    reply_content = payload.get('content', u'').strip()
    logger.info("Creating chat reply for {}".format(current_user))

    # Do some processing here to create a reply

    emit('chat-response', reply_content, room='myroom')

@socketio.on('connect', namespace=CHAT_NAMESPACE)
def chat_connect():
    # Join the user to chat rooms so she can get updates.
    join_room('myroom')

    logger.info(u"[ ] Client {} connected".format(current_user.full_name))
    logger.info(u'    SocketIO: {}'.format(hex(id(socketio))))
    logger.info(u'    SocketIO rooms: {}'.format(socketio.rooms))

def background_thread():
    """
    Based on Flask-SocketIO exapmle app at:
    https://github.com/miguelgrinberg/Flask-SocketIO/blob/master/example/app.py
    """
    global socketio, db, app

    # Do a periodic background emit from the server
    while True:
        time.sleep(5)

        logger.info(u'-----------------------------------------')
        logger.info(u'[ ] Doing background task')
        logger.info(u'    SocketIO: {}'.format(hex(id(socketio))))
        logger.info(u'    SocketIO rooms: {}'.format(socketio.rooms))

        logger.info(u'-----------------------------------------')
        socketio.emit('chat-response', 'server says hello!',
                room='myroom', namespace=CHAT_NAMESPACE)


logger.info('[ ] Starting background thread...')
thread = Thread(target=background_thread)
thread.start()
```

The background thread starts when the module is loaded, and when a client connects, that client is joined to a chatroom.  In the main thread, `socketio.rooms` reports the room correctly.  

But in the background thread, `socketio.rooms` remains empty (`{}`), so it appears that the instance variable in the background thread has gotten unsynced from the main thread.

**Comment by miguelgrinberg** [comment]
Not sure if this is going to help or not, but I noticed you haven't monkey patched the `threading` module with gevent. Can you try that?

**Comment by ktoh** [comment]
@miguelgrinberg that fixed it!

Thanks for your help here. 

For posterity if others find this question:

The flask-socketio [sample app](https://github.com/miguelgrinberg/Flask-SocketIO/blob/master/example/app.py) includes a good illustration of a background thread initiated via a request to an `index()` Flask route.

If for some reason you need to start a background thread earlier (or for security reasons you don't want to execute the background thread inside a user's `request` context), then it's also possible to just run the background thread outside of the request context and use `socketio.emit()` to send messages to namespaces and rooms.

You will need to monkey patch the threading module as per the example app, but this works fine.

**Comment by dan-passaro** [comment]
Don't know if this is related but I was also having trouble getting `socketio.emit()` to broadcast messages from a room.  It seemed to be that this is because I spawned the background thread in a standard HTTP request instead of in a socketio handler.

**Comment by ffleandro** [comment]
I also experienced this problem and took me a while to find this thread. Maybe document a little bit better?

**Comment by miguelgrinberg** [comment]
@ffleandro what specifically are you suggesting needs better docs?

I think the main problem I see users having is that they are not familiar with how asynchronous frameworks work, and in particular the fact that they are not compatible with a somewhat important portion of the Python standard library (threads, locks, sockets, etc). I'm honestly not sure how to improve my documentation to help with that, but if you have ideas I'm open to hear them.

**Comment by dan-passaro** [comment]
That some of these calls will only work when run from certain handlers or triggered in a certain way is definitely surprising.  There's nothing in the `socketio.emit()` signature that indicates it shouldn't work from any place in code.  As you indicate I'm not aware of the implementation challenges of this type of library, but if there's some context or variable set somewhere that `socketio.emit()` relies on, that's not available during e.g. a normal HTTP request, perhaps it would be more explicit if this was a required argument of `socketio.emit()`?  Otherwise, documenting which sequence of events needs to happen for socketio functions to work as intended would be helpful. Also, raising an error when an `emit()` is made but can't possibly work would be nice, although I can't tell if that failure condition is easy to determine.

**Comment by miguelgrinberg** [comment]
> There's nothing in the socketio.emit() signature that indicates it shouldn't work from any place in code.

There are two ways to emit. The `socketio.emit()` method actually does work from any place in the code. It is the other one, the `emit()` global function that has some restrictions, and these are documented already. 

From the [global function docs](https://flask-socketio.readthedocs.io/en/latest/#flask_socketio.emit):

> This function emits a SocketIO event to one or more connected clients. A JSON blob can be attached to the event as payload. This is a function that can only be called from a SocketIO event handler, as it obtains some information from the current client context.

And the [method](https://flask-socketio.readthedocs.io/en/latest/#flask_socketio.SocketIO.emit):

> This function emits a SocketIO event to one or more connected clients. A JSON blob can be attached to the event as payload. This function can be used outside of a SocketIO event context, so it is appropriate to use when the server is the originator of an event, outside of any client context, such as in a regular HTTP request handler or a background task.

So after seeing this, do you still think there is anything that's missing here?

**Comment by ffleandro** [comment]
@miguelgrinberg you're right on the spot regarding "not familiar with how asynchronous frameworks work, and in particular the fact that they are not compatible with a somewhat important portion of the Python standard library".

My suggestion is just a comment remembering users that if they are using `eventlet` or `gevent` to not forget to monkey patch the library before starting the application. I just think the `emitting in a background thread` section had little information if you're not using the standard `threading` library.

Regarding the `socketio.emit` function or the `emit` global function, I think they are well documented and there wasn't any problem for me.

**Comment by miguelgrinberg** [comment]
> My suggestion is just a comment remembering users that if they are using eventlet or gevent to not forget to monkey patch the library before starting the application

Monkey patching is not required. If you start your thread using the `start_background_task()` function things are going to work just fine. You only need to monkey patch if you use one of the modules in the standard library that are blocking, but this is difficult to document. There are already several references to monkey patching in the docs, where I thought it was appropriate, but I disagree with the idea of recommending monkey patching across the board.

The idea of monkey patching is that you can still code against those blocking functions you know, and transparently those calls are redirected to the green thread friendly versions. If you code everything against the eventlet or gevent frameworks you do not need to monkey patch.

So while I agree with you that it would be nice if there was a way to improve the docs to avoid people tripping over this, I haven't found exactly what I need to change to achieve that goal.

**Comment by ffleandro** [comment]
Ok, I understand better now.
In my case I can't use the `start_background_task` function, since I have no control over the creation of the thread. My specific case is a `Button` handler from the `gpiozero` library, that triggers a socketio event when a button state change is detected.

Thanks for the detailed explanation and for the awesome contributions to several projects. Ever since I've started working with `Python` and `Flask` that I have been reading your blog tutorials and using your `Flask` extensions. Well done, sir!
