### ISSUE TITLE
Don't see how a useful implementation with gunicorn, eventlet, and nginx is possible

### ISSUE THREAD

**Issue by mmirandah** [miguelgrinberg/Flask-SocketIO#1170]
I'd like to implement Flask-SocketIO but I'm having trouble trying to figure out how to make it work with gunicorn, eventlet, and nginx while still preserving intended functionality.

So the documentation says to use several gunicorns all with one worker. Then have nginx use ip_hash to send each client to the same worker. But doesn't this mean that each client would be stuck with *only* one worker which may easily get hung up on a heavy request?

And how can a message get broadcasted to all clients in this paradigm? How does one gunicorn process know about the other gunicorn processes handling the other clients?

I feel like these two requirements (that each client can have more than one gunicorn, and that one client can broadcast a message to all other clients) are incompatible in this implementation. Is there an implementation that allows for both these requirements?

For reference, I'm running `gunicorn -c ./gunicorn.conf.py --worker-class eventlet -w 1 application:app` with `socketio = SocketIO(app, engineio_logger=True)`

**Comment by miguelgrinberg** [comment]
This is well documented.

You are using eventlet, so you cannot use what you call "heavy requests". There is no such thing in an asynchronous application.

Also with eventlet one worker can handle thousands of concurrent jobs. You have the thinking of a synchronous worker, but this is eventlet, so it's different dynamics.

Finally, each gunicon communicates with the other gunicorns via a message queue, which is required when you use more than one server.

**Comment by mmirandah** [comment]
Thanks for the quick response! I got everything working the way I needed.

For anybody else reading I added a message queue with `socketio = SocketIO(app, message_queue='redis://')` and put `import eventlet` and `eventlet.monkey_patch()` at the top of my module/application.py file.

I also updated my gunicorn from 19.9.0 to 20.0.4 which seems to have solved a BlockingIOError errno 35 I was getting.
