### ISSUE TITLE
How to do something on PING/PONG

### ISSUE THREAD

**Issue by umityayla** [miguelgrinberg/Flask-SocketIO#1171]
Hello,

I would like to write some metrics through the PING/PONG transmission. But when I try to add stuff like
`@socketio.on("pong")` or`@socketio.on("ping")`, nothing happens, it doesn't happen anything even if I emit manually, so I believe it's done to prevent people from breaking it. Is there any way to add an extra method/code to PINGs/PONGs

And I would like to execute some code after endpoint return command, is there a command in Flask-SocketIO like there's in Flask "after_request"?

**Comment by Vezir-313** [comment]
Hello, I also would like to use **before_request** and **after_request**  on Flask-SocketIO.

**Comment by miguelgrinberg** [comment]
The example application in this repository implements ping/pong. See https://github.com/miguelgrinberg/Flask-SocketIO/blob/master/example/app.py#L101.

There is no equivalent to before/after request for Socket.IO at this time. You can implement it yourself using a class-based namespace, by overriding the `trigger_event()` method.

**Comment by umityayla** [comment]
I was wondering if I can modify existing ping/pong process, but I guess it's not possible. But anyway, thank you for your help.

**Comment by miguelgrinberg** [comment]
@umityayla only if you subclass the `Server` and/or `Client` classes.
