### ISSUE TITLE
Implementation with React-Native 0.61.5 

### ISSUE THREAD

**Issue by dulangaheshan** [miguelgrinberg/Flask-SocketIO#1172]
**Can't establish connection with React-Native**
I tried ti implement socket connection between react native and flask,for client side i use socket.io-client npm package 
##### client code

   
  
     
```
    import io from 'socket.io-client/dist/socket.io'; 
     class App extends Component {
     constructor(props){
     super(props);
     this.socket = io("http://10.0.2.2:5000")     
     this.socket.on("retrieve_active_users", () => {

            this.socket.emit("activate_user", { username: "test_user" })

      })

      this.socket.on('user_activated', (data) => {    
        console.log(data)
      })
    }
```
###### server side 

```
from flask_socketio import  SocketIO, join_room, leave_room, emit
app = Flask(__name__)
Debug(app)
cors = CORS(app,resources={r"/api/*":{"origins":"*"}})
socketio = SocketIO(app,engineio_logger=True,logger=True)

@socketio.on('connect')
def connect():
  print('listening to connect')
  retrieve_active_users()


def retrieve_active_users():
  print("trigger")
  emit('retrieve_active_users')


@socketio.on('activate_user')
def on_active_user(data):
    user = data.get('username')
    emit('user_activated', {'user': user}, broadcast=True)

if __name__ == '__main__':
    socketio.run(app, debug=True, host='127.0.0.1')
```

**output**
######these lines are not execute in client side

```
this.socket.on('user_activated', (data) => {    
    console.log(data)
})
```

######server side
`listening to connect  // print statements that i have added`
`trigger // print statements that i have added`
`"GET /socket.io/?EIO=3&transport=polling&t=N04fglI HTTP/1.1" 200`
`Invalid session None`
`"POST /socket.io/?EIO=3&transport=polling&t=N0C2eN_ HTTP/1.1" 400`

######and some times
`b05af575be8045928c73c97c1c79e123: Client is gone, closing socket`

**Comment by miguelgrinberg** [comment]
Your client is sending requests that do not include the session. Note the `Invalid session None` message.

**Comment by dulangaheshan** [comment]
Thanks for your quick reply, as it mentioned i changed `this.socket = io(`http://10.0.2.2:5000`, { transports: ['websocket']});`  
now my output shows as below
![issue](https://user-images.githubusercontent.com/33221629/73723700-af76ac00-474f-11ea-8a37-f0995b114742.PNG)

still i'm getting 400 error

so i add below lines in my client side 
`		  this.socket.on('connect_error', (error) => {
			console.log(error)
		  });`

it shows 
![issue2](https://user-images.githubusercontent.com/33221629/73724633-c74f2f80-4751-11ea-9416-9252461d4729.PNG)

please guide me to fix this and if this issue is not related to #####Flask-SocketIO  close the issue
