### ISSUE TITLE
How to join a static room to a every client when connects

### ISSUE THREAD

**Issue by mukhlis7** [miguelgrinberg/Flask-SocketIO#1173]
I am developing a chat app with flask-socketIO server and Android SocketIO Client. I have developed a registration system with unique username and i want to automatically join every registered user to a separate room and i want name of that room to be its username name so i can send private messages easily. I don't want each client to be in rooms with name of random session id.

**Comment by miguelgrinberg** [comment]
What is the problem that you have? You can create as many rooms as you want and put users in them as required by your application.
