### ISSUE TITLE
How to disconnect SIDs from Celery worker

### ISSUE THREAD

**Issue by tropicoo** [miguelgrinberg/Flask-SocketIO#1174]
Hey,
Basically I have set up SocketIO (gunicorn + eventlet) + Flask + Celery with Redis as message queue. Emitting from Celery worker  works, but how to disconnect people from Celery? 

After successful websocket connection and passing JWT authorization token as query param I cache SID to the Redis with JWT access expiration time. I want to disconnect people when expiration time is over, but it seems that Celery worker doesn't have any relationship with Flask/SocketIO server through the Redis (`disconnect` function). 

In Celery task I retrieve SIDs from Redis that should be disconnected.
Is there any workaround for `disconnect` function?

```python
# Celery worker
expired = self._cache.get_expired_sids()
for sid in expired:
    disconnect(sid, namespace='/n')
    self._cache.delete_sid(sid)
```
This code should handle case when websocket connection is still alive even when the user auth is expired.
Thanks.

**Comment by miguelgrinberg** [comment]
There is currently no support for disconnecting users from a third party script. Could be added, I'll leave this open as a feature request for that.

**Comment by miguelgrinberg** [comment]
@tropicoo  the master branch on the python-socketio repo has this implemented. Could I ask you to install that from the github repo and give it a quick test? The addition is that the client manager object now has a `disconnect()` method.
