### ISSUE TITLE
Question: Not able to create simultaneous multiple Socket Connections

### ISSUE THREAD

**Issue by utkarshdbodake** [miguelgrinberg/Flask-SocketIO#118]
We are trying to create multiple socket connections simultaneously and then join the user to a room on that specific socket connection. But we are unable to achieve this, as Socket connection is achieved only once, and we are not able to have another simultaneous socket connection until the first one disconnects. The other socket connections are just Queueing up. So, is this the expected behaviour ? 
    So can we get the multiple socket connections simultaneously by changing some parameters? As we need such kind of behaviour for our business.

**Comment by miguelgrinberg** [comment]
Do you need multiple socket connections from the same client or from different clients?

For same client, you can use namespaces to multiplex multiple connections over the same socket. For multiple clients, this is obviously supported, there is nothing that you need to do to get this. Try connecting with multiple clients to the example application in this repository to see if that works.

**Comment by utkarshdbodake** [comment]
We have our Socket client code on Node Server. The multiple clients are connected to Node Server which establishes Socket connection with our flask-socketio server.

In this setup we are able to see that multiple connections are not being made through our Node client. So, all the connections coming from the same Node are being treated as a single client and hence this behaviour ? . So is it possible to open multiple socket connections through this Node.
Please check out the attached diagram.

![socket connection dg1](https://cloud.githubusercontent.com/assets/11180230/8080552/25161cd6-0f8b-11e5-9723-be3d3ef63a32.png)

**Comment by utkarshdbodake** [comment]
Hi, the issue is resolved. It was a Node issue.
