### ISSUE TITLE
Sending image to client without receiving the image from client.

### ISSUE THREAD

**Issue by iszzul** [miguelgrinberg/Flask-SocketIO#1180]
Hi Sir,

I develop system which able to capture the image of detected object. The image will be store in one folder in flask server. So right now I want to display the capture image in flask-web as it's will update as real time. Real time here means the web will display  the latest image in flask-web if new object is detected. Based on this scenario is't possible to use flask-socket.io to push the image to display in flask-web? Since the image is capture by the algorithm and do not receiving form client. Hope you can explain on this issue.

**Comment by miguelgrinberg** [comment]
If this is a standard image, isn't it easier to serve it as a regular image file through the HTTP web server? Why do you need Socket.IO for this? You can send a notification to the client that there is a new image if you like, but the image itself could still go through HTTP.

**Comment by iszzul** [comment]
> If this is a standard image, isn't it easier to serve it as a regular image file through the HTTP web server? Why do you need Socket.IO for this? You can send a notification to the client that there is a new image if you like, but the image itself could still go through HTTP.

Hi sir, thank you for reply. Do you mean i need to create api with combination of jquery and ajax?

**Comment by miguelgrinberg** [comment]
You can call it an API if you like, but it is no different than any other endpoint that returns an image, such as those that return static files. Then from the client side you can generate an `<img>` tag that pulls this image into your page.

**Comment by iszzul** [comment]
Hi sir, last question if i want to make the images update real time. without refreshing  the we. what i mean here when the image it capture it will automatically display in web.what approach should i do? You can just throw the idea i will try the best the solution. please help🙏🙏🙏

**Comment by miguelgrinberg** [comment]
Use JavaScript to update the `src` attribute of your `<img>` tag.

**Comment by iszzul** [comment]
Hi Sir, I know this issue already close but i want to ask a question, I have decide to use flask-socketio to solve my issue. Basically, I have two file app.py and camera.py. In camera.py i capture the image of object detected by using openv and try emit it. I believe if i able to emit it. I will able to call the data using javascript in my html page. I try to send image in file but fail and i also try to convert and put as json format but i also fail. Hope you can give me and idea or solution. Here I attach my code

**App.py**
`from flask import Flask, render_template, Response,jsonify
from camera import VideoCamera
import numpy as np
import os
import time
import detect as dt
from PIL import Image
import cv2
import base64
import json
from flask_socketio import SocketIO, emit


app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app)


def success_handle(output, status=200, mimetype='application/json'):
    return Response(output, status=status, mimetype=mimetype)

@app.route("/images", methods=['GET'])
def get_images():
    directory = os.listdir('C:/Users/HP/Miniconda3/envs/count_vechicle/coding/images')
    os.chdir('C:/Users/HP/Miniconda3/envs/count_vechicle/coding/images')

    flist = list()
    for file in directory:
        data = dict()
        base = os.path.basename(file)
        data["label"] = base
        open_file = open(file,'rb')
        image_read = open_file.read()
        image_64_encode = base64.encodebytes(image_read)
        data["data"] = image_64_encode.decode('ascii')
        flist.append(data)
    final_data = {'files':flist}
    emit('my-image-event', final_data)
    return 'message sent via websocket'
    

@app.route('/')
def index():
    return render_template('index.html')

def gen(camera):
    frame_id = 0
    while True:
        frame = camera.get_frame()
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')

@app.route('/video_feed')
def video_feed():
    return Response(gen(VideoCamera()),
                    mimetype='multipart/x-mixed-replace; boundary=frame')

if __name__ == '__main__':
    socketio.run(app)`

**camera.py**
`import cv2
import time
import os
import numpy as np



font = cv2.FONT_HERSHEY_PLAIN
starting_time= time.time()
frame_id = 0
count = 0
d = 0

labelsPath = os.path.sep.join(["yolo-coco", "coco.names"])
weightsPath = os.path.sep.join(["yolo-coco", "yolov3.weights"])
configPath = os.path.sep.join(["yolo-coco", "yolov3.cfg"])
#imagesPath = 'C:/Users/HP/Miniconda3/envs/count_vechicle/coding/images/file_%d.jpg"%d'
labelsPath = os.path.sep.join(["yolo-coco", "coco.names"])
VideoPath = os.path.sep.join(["videos", "highway.mp4"])
LABELS = open(labelsPath).read().strip().split("\n")


net = cv2.dnn.readNet(configPath, weightsPath)

layer_names = net.getLayerNames()
outputlayers = [layer_names[i[0] - 1] for i in net.getUnconnectedOutLayers()]


colors= np.random.uniform(0,255,size=(len(LABELS),3))

class VideoCamera(object):
    def __init__(self):
        # Using OpenCV to capture from device 0. If you have trouble capturing
        # from a webcam, comment the line below out and use a video file
        # instead.
        self.video = cv2.VideoCapture(0)
        self.frame_id = 0
        self.d = 0
        # If you decide to use video.mp4, you must have this file in the folder
        # as the main.py.
        # self.video = cv2.VideoCapture('video.mp4')
    
    def __del__(self):
        self.video.release()


    def get_frame(self):
        success, image = self.video.read()
        # We are using Motion JPEG, but OpenCV defaults to capture raw images,
        # so we must encode it into JPEG in order to correctly display the
        # video stream.
        self.frame_id+=1
        #print(frame_id)
    
        height,width,channels = image.shape
        #print (frame.shape)
        #detecting objects
        blob = cv2.dnn.blobFromImage(image,0.00392,(320,320),(0,0,0),True,crop=False) #reduce 416 to 320    
        
            
        net.setInput(blob)
        outs = net.forward(outputlayers)
        #print(outs)
        print(outs[1])

        #Showing info on screen/ get confidence score of algorithm in detecting an object in blob
        class_ids=[]
        confidences=[]
        boxes=[]

        for out in outs:
            #print(out)
            for detection in out:
                scores = detection[5:]
                class_id = np.argmax(scores)
                confidence = scores[class_id]
                print(confidence)
                if confidence > 0.8:
                    #object detected
                    center_x= int(detection[0]*width)
                    center_y= int(detection[1]*height)
                    w = int(detection[2]*width)
                    h = int(detection[3]*height)

                    #cv2.circle(img,(center_x,center_y),10,(0,255,0),2)
                    #rectangle co-ordinaters
                    x=int(center_x - w/2)
                    y=int(center_y - h/2)
                    #cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),2)

                    boxes.append([x,y,w,h]) #put all rectangle areas
                    confidences.append(float(confidence)) #how confidence was that object detected and show that percentage
                    class_ids.append(class_id) #name of the object tha was detected

        indexes = cv2.dnn.NMSBoxes(boxes,confidences,0.4,0.6)
        # result = open('C:/Users/HP/Miniconda3/envs/count_vechicle/coding/images/frame%04d.txt'%(count), 'w')
        flist = list()
        for i in range(len(boxes)):
            if i in indexes:
                x,y,w,h = boxes[i]
                label = str(LABELS[class_ids[i]])
                # cv2.imwrite(label, crop_img)
                confidence= confidences[i]
                color = colors[class_ids[i]]
                crop_img = image[y:y + h, x:x + w]
                # imagesPath = "images/file_%d.jpg"%self.d
                open_file = open(crop_img,'rb')
                image_read = open_file.read()
                image_64_encode = base64.encodebytes(image_read)
                data["data"] = image_64_encode.decode('ascii')
                flist.append(data)
                # cv2.imwrite(imagesPath, crop_img)
                # self.d+=1
                cv2.rectangle(image,(x,y),(x+w,y+h),color,2)
                cv2.putText(image,label+" "+str(round(confidence,2)),(x,y+30),font,1,(255,255,255),2)
            final_data = {'files':flist}
            emit('json', final_data)

                

        elapsed_time = time.time() - starting_time
        fps=frame_id/elapsed_time
        cv2.putText(image,"FPS:"+str(round(fps,2)),(10,50),font,2,(0,0,0),1)
        
        # cv2.imshow("Image",image)
        # key = cv2.waitKey(1) #wait 1ms the loop will start again and we will process the next frame

        # if key == 27: #esc key stops the process
        #     break;
        ret, jpeg = cv2.imencode('.jpg', image)
        return jpeg.tobytes()`

**Comment by miguelgrinberg** [comment]
You can send images in binary form, just include a bytes string, ie `data['data'] = image_read`. No need to convert to a base64 string, binary blobs are supported. If you get an error, please show the error, without that I cannot tell you what's wrong.

**Comment by iszzul** [comment]
Hi Sir, Thank you very much for your response. I will try this one and update to you back. But I have another problem with my webcam now. When i use flask-socket-io in my app.py the webcam don't display in my index.html. my webcam open but don't display in my index.html. When i remove it and using flask i works well.

**Comment by miguelgrinberg** [comment]
@iszzul sorry, I don't really know how to help you with your webcam issue.

**Comment by iszzul** [comment]
Hir Sir, I will try to find the solution first and will let's you know

**Comment by def-fun** [comment]
> camera.py
Your code has some mistakes, for example, `base64.encodebytes(image_read)` before import `base64`.
Maybe [my rtm2](https://github.com/def-fun/rtm2)  can help you.
I send frame to client without encode it using socketIO **only when motion detected with openCV**.
I use flask, too.
