### ISSUE TITLE
Nginx SSL - Not working

### ISSUE THREAD

**Issue by toomuchio** [miguelgrinberg/Flask-SocketIO#1181]
Not sure what the issue is my configuration is below, now the weird thing is it works fine when browsing over http. But as soon as you browse over https the websocket can't connect. Nginx gives a 400 error, timeout waiting for the upstream.

My relevant python stuff is
socketio = SocketIO(app, async_mode="eventlet")
socketio.run(app, debug=False)

And I'm just running it in a screen via it's own virtual environment at the moment while I debug but have it in systemd normally.
python app.py

Also the docs have an error appending '/socket.io' to the proxy_pass setting of the socket.io portion makes the whole thing not work.

```upstream xxx_app {
	server 127.0.0.1:5000;
}

server {
	listen 80;
	listen 443 ssl;
    server_name xxx;

	ssl_certificate /etc/letsencrypt/live/xxx.xxx.com.au/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/xxx.xxx.com.au/privkey.pem;
	ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
	
	ssl_prefer_server_ciphers on;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;

	resolver 1.1.1.1 1.0.0.1;
	ssl_stapling on;
	ssl_stapling_verify on;
	ssl_trusted_certificate /etc/letsencrypt/live/xxx.xxx.com.au/chain.pem;

	add_header X-Frame-Options SAMEORIGIN;
	add_header X-Content-Type-Options nosniff;
	add_header X-XSS-Protection "1; mode=block";

    location / {
        include proxy_params;
        proxy_pass http://xxx_app;
    }

	location /socket.io {
        include proxy_params;

		proxy_pass http://xxx_app;
        proxy_buffering off;
		proxy_redirect off;

		proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
```

**Comment by miguelgrinberg** [comment]
The docs are correct, the `/socket.io` path needs to be added to the proxy_pass statement.

I find it odd that you are getting a 400 error as a timeout, since 400 is not the correct code for timeouts, it should have been a 5xx code if it was really a timeout.

Try adding logging to the Socket.IO server to see if there are any useful messages there.

**Comment by toomuchio** [comment]
The /socket.io path does nothing it functions without it, to be honest you can just globally enable websockets and not even need that section.

I was wrong it's not a timeout it's 400, bad request, but it only happens over ssl. I can't understand why.
```
(17347) accepted ('127.0.0.1', 50636)
...,127.0.0.1 - - [10/Feb/2020 03:00:46] "GET / HTTP/1.0" 200 5741 0.001403
(17347) accepted ('127.0.0.1', 50638)
...,127.0.0.1 - - [10/Feb/2020 03:00:47] "POST /socket.io/?EIO=3&transport=polling&t=N0kmZqi&sid=e78e09af726e471e8e8737dccbebe283 HTTP/1.1" 400 122 0.000282
(17347) accepted ('127.0.0.1', 50640)
Client connected 549f122747864e8e8445c4a8414b5f6f
...,127.0.0.1 - - [10/Feb/2020 03:00:47] "GET /socket.io/?EIO=3&transport=polling&t=N0kma2a HTTP/1.1" 200 325 0.000868
(17347) accepted ('127.0.0.1', 50642)
(17347) accepted ('127.0.0.1', 50644)
...,127.0.0.1 - - [10/Feb/2020 03:00:48] "GET /socket.io/?EIO=3&transport=websocket&sid=549f122747864e8e8445c4a8414b5f6f HTTP/1.1" 400 122 0.000238```

**Comment by toomuchio** [comment]
Nginx error logs just have some, connect() failed (111: Connection refused) while connecting to upstream messages as well.

**Comment by toomuchio** [comment]
Ok I figured it out, CORS error. Same as described here.
I think a note needs to be added to the deployment doc recommending the ProxyFix module be used or cors be set because that error isn't clear at all. Closing off.

https://github.com/miguelgrinberg/Flask-SocketIO/issues/1047
