### ISSUE TITLE
Does flask-socketio multiple server only support 2 servers?

### ISSUE THREAD

**Issue by sbqsbqsbq** [miguelgrinberg/Flask-SocketIO#1182]
**Your question**
Hi, I'm developing a chatbot application with your library. Recently, I've read that there's a method that can start multiple flask-socketio server by adding `socketio = SocketIO(app, async_mode="gevent", message_queue="redis://")`. Actually, I've succeeded in creating multiple servers by adding the above code. However, there are only working 2 servers, when I launched my flask socketio app. Is there any method to increase the number of servers? That's my question. 

Thank you for creating a great library.

**Comment by miguelgrinberg** [comment]
You can run as many servers as you need, there is no limit set to 2. Did you try running a 3rd server?

**Comment by sbqsbqsbq** [comment]
My instance's core is 4, but I don't know how to run another server. How can I run more servers?

**Comment by miguelgrinberg** [comment]
Sorry, I don't understand what you are asking. Each server is an independent process. If you want to run two servers, then you run the application two times. To run a third server you run one more instance of the application. Each will be running on a different port, and you will use a reverse proxy such as nginx to load balance requests. See the docs if you need more information about this.

**Comment by sbqsbqsbq** [comment]
Thank you for answering! I need to check my nginx configuration.
