### ISSUE TITLE
How i save and show existing progress status using flask socketio if browser is closed(session)

### ISSUE THREAD

**Issue by Set4now** [miguelgrinberg/Flask-SocketIO#1183]
Hello miguel!!

Am asking this since i need some guidance in how to achieve this?

Requirement :-

As you know am using flask socketIo ...and i have almost completed the project.
Now i want to implement something which is very common on web development.

Right now i can show the status of background tasks in the UI, and events are getting send to specfic (request.sid ). Now if the user accidentally  close his browser and and returns to the same page, for obvious reason he won't see anything ( which was happening in the existing session).
How can achieve that ?

**Comment by miguelgrinberg** [comment]
Do your clients authenticate? If they do, then when the client reopens the page you should be able to find if there are any pending tasks for that user.

**Comment by Set4now** [comment]
I am not using flask authentication. It's a in-House authentication thing. When i close and reopen the page, it's showing the refreshed page, not the one status since that got rendered in a diff session. Is there any way we can save the existing session ( html page) to something and create a dynamic url link which i can show in the homepage. So that the user know that something is runnijng and once click , get to the old running page.

**Comment by Set4now** [comment]
Am trying to achieve something exactly like any cloud based solutions For example if i create an Ec2 instance from console and close it. Upon reopening it will still show the existing operations with current status ( running,pending ) etc..

**Comment by miguelgrinberg** [comment]
@Set4now all cloud based solutions require that you authenticate with them before you can see your dashboard. They associate the state of your account with your identity. Authentication does not need to be based in Flask, as long as you know who the user is you can store the current state in your database and recall it when the user reconnects.
