### ISSUE TITLE
Flask stream_with_context blocking after changing to SocketIO

### ISSUE THREAD

**Issue by welabbar1** [miguelgrinberg/Flask-SocketIO#1184]
Hello Miguel,

First of all i would like to say thank you for all of your hard work! I absolutely love this module! 

I am wondering if you can help me, i have finally converted my Flask app to use SocketIO in order to emit a large amount of data and it is working perfectly along with the rest of the app. I am running in a container using Eventlet alongside a separate Nginx container for HTTPS reverse proxy and it is working fine after i add monkey_patch().

My issue is i was making use of a Flask response(stream_with_context) function that yields a generator to the browser which was is working fine with Flask only behind nginx using app.run(). But as soon as i use socketio.run(app) with Eventlet, the response no longer streams out, it just blocks and returns a response after the function is complete. The rest of the app works fine.

My question is: Can i still use Flask response alongside SocketIO? Is there something i need to change or enable to get it to stream as it should?

Thanks!

**Comment by welabbar1** [comment]
Update: When i run SocketIO with threading enabled (socketio = SocketIO(async_mode='threading') the function works properly.

**Comment by miguelgrinberg** [comment]
Something that you are doing in your generator is blocking eventlet. Monkey patching is likely to help. If that does not work, you should share more details on the work that you do in that streaming response. Maybe you will need to redesign it so that it is friendly to eventlet.

**Comment by welabbar1** [comment]
I use Azure modules that install and uninstall specific VM extensions and i was using yield and time.sleep to send out status messages to the browser as well as using the Azure Msrest Poller function to hold the response until the operation on the extension was concluded. 

I took a hard look at the function and redesigned it to use SocketIO emits instead of yielding and it worked perfectly! Rather than opening up a new tab and yielding html tags, i now emit on another namespace and append the messages to the same html of the VM list as a child row. Works so much better and presents a lot of opportunities. 

I would close this issue. Thanks for your advice chief!
