### ISSUE TITLE
Not working as WebSocket on Windows 7 Ultimate

### ISSUE THREAD

**Issue by fred913** [miguelgrinberg/Flask-SocketIO#1185]
**Your question**
I'm trying to start a Websocket server with Flask and flask-socketio. It's working as ajax polling mode (Not WebSocket Mode). But It didn't work when I installed the eventlet module (for WebSocket Support). 

**Logs**
Server initialized for eventlet.
Then nothing:`(

**Comment by miguelgrinberg** [comment]
First of all, even if it was true that this package does not work under Windows 7, it is such an old release that I would not consider it important to support it.

But I believe you must be incorrect. Say that the logs show nothing is strange. If you connect to your webserver it should say something, even if it is an error. This is more likely user error on your part, but you need to provide more details about how you are connecting to help me pinpoint what you are doing wrong.

**Comment by fred913** [comment]
I'm sorry about that...
I rebooted my computer and the log never output anything again.
But Web services are effective.
Thank you for your reply!
