### ISSUE TITLE
Ambiguities with the use of socketio.run(app) with uWSGI.

### ISSUE THREAD

**Issue by wfehrnstrom** [miguelgrinberg/Flask-SocketIO#1186]
**Your question**
I'm a little confused as to the actual canonical way that uWSGI should hook in with flask-socketio. In your documentation you specify that socketio.run(app) is the recommended way to start the gevent web server. It's also said that uWSGI has built in websocket support, and that having gevent on your system with uWSGI will enable full websocket support with flask-socketio. But my confusion is centered around two things: 1: why is the callable that uwsgi uses the callable exposed by vanilla flask (in my case `app`), and not the wrapper `socketio` created through `socketio = SocketIO(app)`. 2: in your documentation socketio.run(app) is only run when the script is run directly. Does socketio.run(app) spin up a web server through flask, and that's why we don't want to use it when uWSGI is hooking into a flask callable? Do I need to somehow run socketio.run(app) when I'm interfacing with uWSGI? And if so, how should I do this canonically (in your view)? Further, I don't really understand the init_app style you mention briefly. I apologize if any of these questions are elementary: I wanted to enhance my understanding as much as possible. Thank you for providing this excellent software and good documentation as well. 

My stack is nginx, uWSGI, flask-socketio and socketio on the client side, for extra information, but I'm primarily concerned with flask-socketio, flask and uWSGI here. Thanks for your help!

**Comment by miguelgrinberg** [comment]
> 1: why is the callable that uwsgi uses the callable exposed by vanilla flask (in my case app), and not the wrapper socketio created through socketio = SocketIO(app)

The `app` variable holds a WSGI callable, while `socketio` is just a Flask extension that enhances the Flask app. Like most/all extensions, it does not replace your app, just adds new tricks to it.

> 2: in your documentation socketio.run(app) is only run when the script is run directly. Does socketio.run(app) spin up a web server through flask, and that's why we don't want to use it when uWSGI is hooking into a flask callable?

The `socketio.run(app)` method of running the server is implemented for the gevent, eventlet and Flask web servers. It is not implemented for uWSGI, in the same way it isn't implemented for gunicorn. When you use uWSGI or gunicorn you have to start the server as you always do, but there are some restrictions on the options that you use (i.e. you have to enable gevent and websocket, and run a single worker, see the docs for an example).

> Do I need to somehow run socketio.run(app) when I'm interfacing with uWSGI?

No, the `run()` method isn't used with uWSGI, at least not at this time.

> Further, I don't really understand the init_app style you mention briefly. 

`init_app` is a standard way to initialize Flask extensions that works well with the app factory pattern. See https://flask.palletsprojects.com/en/1.1.x/extensiondev/#the-extension-code.

**Comment by wfehrnstrom** [comment]
Thank you for your clarifications!
