### ISSUE TITLE
Invalid session error in cpanel socket app / 400 error code in browser

### ISSUE THREAD

**Issue by Aarlangdi** [miguelgrinberg/Flask-SocketIO#1188]
Can you please help?
It connects ok but throws 400 error when I send message.
Server log says - Invalid session.

Here are my codes:
Server code ( in Cpanel ):

from flask import Flask 
from flask_socketio import SocketIO, send
import eventlet

app = Flask(__name__)
app.config['SECRET_KEY'] = 'mysecret'

socketio = SocketIO(app)

@socketio.on('message')
def handleMessage(msg):
	print('Message: ' + msg)
	send(msg, broadcast=True)

if __name__ == '__main__':
	socketio.run(app)

Client side code:
<html>
<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Chat Room</title>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.3.0/socket.io.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
</head>
<body>
<script type="text/javascript">
$(document).ready(function() {

	var socket = io.connect('https://domainname.com',{
	    path: '/socket.io/',
	    transports: ['polling'],
	    cookie: false,
	    autoConnect: false,
	    forceNode: true,
	     reconnection: true, 
	     forceNew: false,
	      upgrade: false
	});
	
	socket.once('connect', function() {
		socket.send('User has connected!');
		
		socket.on('message', function(msg) {
    		$("#messages").append('<li>'+msg+'</li>');
    		console.log('Received message');
    	});
	}); 
	
	socket.once('connection', function() {
		socket.send('User has connection....!');
	});

    $("#connectToSocket").on("click", function(){
       socket.connect();
    });

	

	$('#sendbutton').on('click', function() {
		socket.send($('#myMessage').val());
		$('#myMessage').val('');
	});

});
</script>
<ul id="messages"></ul>
<input type="text" id="myMessage">
<button id="sendbutton">Send</button>
<button id="connectToSocket">Connect</button>
</body>
</html>

Errors:
Browser(Chrome):
POST/GET https://domainname.com/socket.io/?EIO=3&transport=polling&t=N12BS3j&sid=56bdaa1138ef49749f040599fb2869af 400

SERVER (Cpanel):
App 2819199 output: [ pid=2819199, time=2020-02-14 11:35:54,408 ]: Invalid session ff0f9d832af04d50900e000890003a03

**Comment by miguelgrinberg** [comment]
Did you notice that the bug template includes information on how to capture mode detailed logs? Without that it is hard for me to figure out what went wrong.

**Comment by Aarlangdi** [comment]
Hi Miguel,
Thanks for reply.
The error for this specific app in Cpanel does not have that info. This is what I get when I ran the app.
App 3904950 output: [ pid=3904950, time=2020-02-15 10:57:26,955 ]: Invalid session 629524efde1c4a8d912c9fdafa9bc7e5
App 3904950 output: [ pid=3904950, time=2020-02-15 10:57:27,045 ]: Invalid session 629524efde1c4a8d912c9fdafa9bc7e5

Cpanel error section gives me this-
Checking whether to disconnect long-running connections for process 3894886, application /directory (production)

Where else can I look up for errors? 

I don't know how but When I double click the button send in client side. I get message back occasionally:
$('#sendbutton').on('click', function() {
	socket.send($('#myMessage').val());
	//$('#myMessage').val('');
});

**Comment by Aarlangdi** [comment]
One more thing, Javascript file is not in template folder of Python app. It is outside.
E.g.
JS in www.domainname.com/foldername/index.html
where python app is at
www.domainname/pythonAppDir

I had that index.html inside template folder of python app before and got same error 400 in browser and invalid session error in server.

Thanks

**Comment by miguelgrinberg** [comment]
As I said, when you wrote your issue here you had the information on how to generate additional logs. Here is that info again for your convenience:

**Logs**
Please provide relevant logs from the server and the client. On the server, add the `logger=True` and `engineio_logger=True` arguments to your `SockertIO()` object to get logs dumped on your terminal. The same arguments can be used on the [python-socketio's client](https://github.com/miguelgrinberg/python-socketio). If you are using the JavaScript client, see [here](https://socket.io/docs/logging-and-debugging/) for how to enable logs.

**Comment by Aarlangdi** [comment]
Hi Miguel,
Error in the server is still same: 
App 621686 output: [ pid=621686, time=2020-02-16 08:22:05,267 ]: Invalid session 16529ea35b8844b6a1f25813c67daf15

But I got these errors in client side(JS):

socket.io-client:url parse https://domainname.com +0ms
index.js:83 socket.io-client new io instance for https://domainname.com +0ms
index.js:83 socket.io-client:manager readyState closed +0ms
index.js:83 socket.io-client:manager opening https://domainname.com +2ms
index.js:83 engine.io-client:socket creating transport "polling" +0ms
index.js:83 engine.io-client:polling polling +0ms
index.js:83 engine.io-client:polling-xhr xhr poll +0ms
index.js:83 engine.io-client:polling-xhr xhr open GET: https://domainname.com/socket.io/?EIO=3&transport=polling&t=N1AyPL8 +2ms
index.js:83 engine.io-client:polling-xhr xhr data null +2ms
index.js:83 engine.io-client:socket setting transport polling +9ms
index.js:83 socket.io-client:manager connect attempt will timeout after 20000 +13ms
index.js:83 engine.io-client:polling polling got data ArrayBuffer(119) +331ms
index.js:83 engine.io-client:socket socket receive: type "open", data "{"sid":"9be4c30d3be948bd92f03956f6e9c222","upgrades":["websocket"],"pingTimeout":60000,"pingInterval":25000}" +328ms
index.js:83 engine.io-client:socket socket open +1ms
index.js:83 socket.io-client:manager open +328ms
index.js:83 socket.io-client:manager cleanup +1ms
index.js:83 socket.io-client:socket transport is open - connecting +0ms
index.js:83 engine.io-client:socket socket receive: type "message", data "0" +6ms
index.js:83 socket.io-parser decoded 0 as {"type":0,"nsp":"/"} +0ms
index.js:83 engine.io-client:polling polling +16ms
index.js:83 engine.io-client:polling-xhr xhr poll +342ms
index.js:83 engine.io-client:polling-xhr xhr open GET: https://domainname.com/socket.io/?EIO=3&transport=polling&t=N1AyPQY&sid=9be4c30d3be948bd92f03956f6e9c222 +1ms
index.js:83 engine.io-client:polling-xhr xhr data null +1ms
index.js:83 socket.io-client:manager writing packet {"type":2,"data":["message","sdfsdfsdfsdfdsf"],"options":{"compress":true},"nsp":"/"} +5s
index.js:83 socket.io-parser encoding packet {"type":2,"data":["message","sdfsdfsdfsdfdsf"],"options":{"compress":true},"nsp":"/"} +5s
index.js:83 socket.io-parser encoded {"type":2,"data":["message","sdfsdfsdfsdfdsf"],"options":{"compress":true},"nsp":"/"} as 2["message","sdfsdfsdfsdfdsf"] +1ms
index.js:83 engine.io-client:socket flushing 1 packets in socket +5s
index.js:83 engine.io-client:polling-xhr xhr open POST: https://domainname.com/socket.io/?EIO=3&transport=polling&t=N1AyQcx&sid=9be4c30d3be948bd92f03956f6e9c222 +5s
index.js:83 engine.io-client:polling-xhr xhr data 31:42["message","sdfsdfsdfsdfdsf"] +1ms
index.js:83 POST https://domainname.com/socket.io/?EIO=3&transport=polling&t=N1AyQcx&sid=9be4c30d3be948bd92f03956f6e9c222 400
i.create @ index.js:83
i @ index.js:83
o.request @ index.js:83
o.doWrite @ index.js:83
(anonymous) @ index.js:83
(anonymous) @ index.js:83
o @ index.js:83
(anonymous) @ index.js:83
(anonymous) @ index.js:83
e.encodePacket @ index.js:83
i @ index.js:83
i @ index.js:83
c @ index.js:83
e.encodePayload @ index.js:83
r.write @ index.js:83
r.send @ index.js:83
r.flush @ index.js:83
r.sendPacket @ index.js:83
r.write.r.send @ index.js:83
(anonymous) @ index.js:83
r.encode @ index.js:83
r.packet @ index.js:83
r.packet @ index.js:83
r.emit @ index.js:83
r.send @ index.js:83
(anonymous) @ record_4.php:43
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3
index.js:83 engine.io-client:socket socket error {"type":"TransportError","description":400} +2s
index.js:83 socket.io-client:manager error +2s Error: xhr post error
    at o.r.onError (index.js:83)
    at i.<anonymous> (index.js:83)
    at i.r.emit (index.js:83)
    at i.onError (index.js:83)
    at index.js:83
index.js:83 engine.io-client:socket socket close with reason: "transport error" +3ms
index.js:83 engine.io-client:polling transport open - closing +6s
index.js:83 engine.io-client:polling writing close packet +1ms
index.js:83 engine.io-client:polling-xhr xhr open POST: https://domainname.com/socket.io/?EIO=3&transport=polling&t=N1AyQ-s&sid=9be4c30d3be948bd92f03956f6e9c222 +2s
index.js:83 engine.io-client:polling-xhr xhr data 1:1 +1ms
index.js:83 socket.io-client:manager onclose +9ms
index.js:83 socket.io-client:manager cleanup +3ms
index.js:83 socket.io-client:socket close (transport error) +6s
index.js:83 socket.io-client:manager will wait 767ms before reconnect attempt +3ms
index.js:83 POST https://domainname.com/socket.io/?EIO=3&transport=polling&t=N1AyQ-s&sid=9be4c30d3be948bd92f03956f6e9c222 400
i.create @ index.js:83
i @ index.js:83
o.request @ index.js:83
o.doWrite @ index.js:83
(anonymous) @ index.js:83
(anonymous) @ index.js:83
o @ index.js:83
(anonymous) @ index.js:83
(anonymous) @ index.js:83
e.encodePacket @ index.js:83
i @ index.js:83
i @ index.js:83
c @ index.js:83
e.encodePayload @ index.js:83
r.write @ index.js:83
t @ index.js:83
r.doClose @ index.js:83
r.close @ index.js:83
r.onClose @ index.js:83
r.onError @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onError @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
i.onError @ index.js:83
(anonymous) @ index.js:83
setTimeout (async)
hasXDR.e.onreadystatechange @ index.js:83
XMLHttpRequest.send (async)
i.create @ index.js:83
i @ index.js:83
o.request @ index.js:83
o.doWrite @ index.js:83
(anonymous) @ index.js:83
(anonymous) @ index.js:83
o @ index.js:83
(anonymous) @ index.js:83
(anonymous) @ index.js:83
e.encodePacket @ index.js:83
i @ index.js:83
i @ index.js:83
c @ index.js:83
e.encodePayload @ index.js:83
r.write @ index.js:83
r.send @ index.js:83
r.flush @ index.js:83
r.sendPacket @ index.js:83
r.write.r.send @ index.js:83
(anonymous) @ index.js:83
r.encode @ index.js:83
r.packet @ index.js:83
r.packet @ index.js:83
r.emit @ index.js:83
r.send @ index.js:83
(anonymous) @ record_4.php:43
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3
index.js:83 socket.io-client:manager attempting reconnect +769ms
index.js:83 socket.io-client:manager readyState closed +1ms
index.js:83 socket.io-client:manager opening https://domainname.com +0ms
index.js:83 engine.io-client:socket creating transport "polling" +784ms
index.js:83 engine.io-client:polling polling +783ms
index.js:83 engine.io-client:polling-xhr xhr poll +781ms
index.js:83 engine.io-client:polling-xhr xhr open GET: https://domainname.com/socket.io/?EIO=3&transport=polling&t=N1AyRB5 +1ms
index.js:83 engine.io-client:polling-xhr xhr data null +2ms
index.js:83 engine.io-client:socket setting transport polling +6ms
index.js:83 socket.io-client:manager connect attempt will timeout after 20000 +10ms
index.js:83 engine.io-client:polling polling got data ArrayBuffer(119) +235ms
index.js:83 engine.io-client:socket socket receive: type "open", data "{"sid":"16529ea35b8844b6a1f25813c67daf15","upgrades":["websocket"],"pingTimeout":60000,"pingInterval":25000}" +232ms
index.js:83 engine.io-client:socket socket open +1ms
index.js:83 socket.io-client:manager open +231ms
index.js:83 socket.io-client:manager cleanup +0ms
index.js:83 socket.io-client:socket transport is open - connecting +1s
index.js:83 socket.io-client:manager reconnect success +2ms
index.js:83 engine.io-client:socket socket receive: type "message", data "0" +5ms
index.js:83 socket.io-parser decoded 0 as {"type":0,"nsp":"/"} +3s
index.js:83 engine.io-client:polling polling +10ms
index.js:83 engine.io-client:polling-xhr xhr poll +242ms
index.js:83 engine.io-client:polling-xhr xhr open GET: https://domainname.com/socket.io/?EIO=3&transport=polling&t=N1AyREw&sid=16529ea35b8844b6a1f25813c67daf15 +1ms
index.js:83 engine.io-client:polling-xhr xhr data null +1ms
index.js:83 socket.io-client:socket performing disconnect (/) +2s
index.js:83 socket.io-client:manager writing packet {"type":1,"nsp":"/"} +2s
index.js:83 socket.io-parser encoding packet {"type":1,"nsp":"/"} +2s
index.js:83 socket.io-parser encoded {"type":1,"nsp":"/"} as 1 +1ms
index.js:83 engine.io-client:socket flushing 1 packets in socket +2s
index.js:83 engine.io-client:polling-xhr xhr open POST: https://domainname.com/socket.io/?EIO=3&transport=polling&t=N1AyRfH&sid=16529ea35b8844b6a1f25813c67daf15 +2s
index.js:83 engine.io-client:polling-xhr xhr data 2:41 +1ms
index.js:83 socket.io-client:manager disconnect +6ms
index.js:83 socket.io-client:socket close (io client disconnect) +9ms
index.js:83 POST https://domainname.com/socket.io/?EIO=3&transport=polling&t=N1AyRfH&sid=16529ea35b8844b6a1f25813c67daf15 400
i.create @ index.js:83
i @ index.js:83
o.request @ index.js:83
o.doWrite @ index.js:83
(anonymous) @ index.js:83
(anonymous) @ index.js:83
o @ index.js:83
(anonymous) @ index.js:83
(anonymous) @ index.js:83
e.encodePacket @ index.js:83
i @ index.js:83
i @ index.js:83
c @ index.js:83
e.encodePayload @ index.js:83
r.write @ index.js:83
r.send @ index.js:83
r.flush @ index.js:83
r.sendPacket @ index.js:83
r.write.r.send @ index.js:83
(anonymous) @ index.js:83
r.encode @ index.js:83
r.packet @ index.js:83
r.packet @ index.js:83
r.close.r.disconnect @ index.js:83
(anonymous) @ record_4.php:34
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3
index.js:83 engine.io-client:socket socket error {"type":"TransportError","description":400} +2s
index.js:83 socket.io-client:manager error +2s Error: xhr post error
    at o.r.onError (index.js:83)
    at i.<anonymous> (index.js:83)
    at i.r.emit (index.js:83)
    at i.onError (index.js:83)
    at index.js:83
index.js:83 engine.io-client:socket socket close with reason: "transport error" +2ms
index.js:83 engine.io-client:polling transport open - closing +3s
index.js:83 engine.io-client:polling writing close packet +0ms
index.js:83 engine.io-client:polling-xhr xhr open POST: https://domainname.com/socket.io/?EIO=3&transport=polling&t=N1AyS1u&sid=16529ea35b8844b6a1f25813c67daf15 +2s
index.js:83 engine.io-client:polling-xhr xhr data 1:1 +1ms
index.js:83 socket.io-client:manager onclose +6ms
index.js:83 socket.io-client:manager cleanup +3ms
index.js:83 POST https://domainname.com/socket.io/?EIO=3&transport=polling&t=N1AyS1u&sid=16529ea35b8844b6a1f25813c67daf15 400
i.create @ index.js:83
i @ index.js:83
o.request @ index.js:83
o.doWrite @ index.js:83
(anonymous) @ index.js:83
(anonymous) @ index.js:83
o @ index.js:83
(anonymous) @ index.js:83
(anonymous) @ index.js:83
e.encodePacket @ index.js:83
i @ index.js:83
i @ index.js:83
c @ index.js:83
e.encodePayload @ index.js:83
r.write @ index.js:83
t @ index.js:83
r.doClose @ index.js:83
r.close @ index.js:83
r.onClose @ index.js:83
r.onError @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onError @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
i.onError @ index.js:83
(anonymous) @ index.js:83
setTimeout (async)
hasXDR.e.onreadystatechange @ index.js:83
XMLHttpRequest.send (async)
i.create @ index.js:83
i @ index.js:83
o.request @ index.js:83
o.doWrite @ index.js:83
(anonymous) @ index.js:83
(anonymous) @ index.js:83
o @ index.js:83
(anonymous) @ index.js:83
(anonymous) @ index.js:83
e.encodePacket @ index.js:83
i @ index.js:83
i @ index.js:83
c @ index.js:83
e.encodePayload @ index.js:83
r.write @ index.js:83
r.send @ index.js:83
r.flush @ index.js:83
r.sendPacket @ index.js:83
r.write.r.send @ index.js:83
(anonymous) @ index.js:83
r.encode @ index.js:83
r.packet @ index.js:83
r.packet @ index.js:83
r.close.r.disconnect @ index.js:83
(anonymous) @ record_4.php:34
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3
index.js:83 engine.io-client:polling polling got data ArrayBuffer(0) +49s
index.js:83 engine.io-client:polling polling got data ArrayBuffer(0) +7s

**Comment by miguelgrinberg** [comment]
Instead of selecting the line that you think is significant from the server logs, please show me the entire content. You are missing important content there, I think.

**Comment by Aarlangdi** [comment]
Hi Miguel,
I wish there are info in server log file. 

I spoke to server guys about this and they don't know what is going on. Only time I got different error in console is when I add host name with http or https e.g. socket.run(app, host='https://domainname.com) ---- address not found.

If this helps - It sends and receives message ok when I use ping or pong as emit event.

When I use firefox it gives back CORS error even though I added allow all origin or ignore cross origin.
Server is started on http and I don't know how change that to https.

Thanks

**Comment by miguelgrinberg** [comment]
I need to see your logs, please.

**Comment by Aarlangdi** [comment]
Current log -
App 3420304 output: stdin: is not a tty
App 3420304 output: wsgi-loader.py:26: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
App 3420304 output:   import sys, os, io, re, imp, threading, signal, traceback, socket, select, struct, logging, errno
App 3420459 output: stdin: is not a tty
App 3420459 output: wsgi-loader.py:26: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
App 3420459 output:   import sys, os, io, re, imp, threading, signal, traceback, socket, select, struct, logging, errno
App 3420816 output: stdin: is not a tty
App 3420816 output: wsgi-loader.py:26: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
App 3420816 output:   import sys, os, io, re, imp, threading, signal, traceback, socket, select, struct, logging, errno

**Comment by miguelgrinberg** [comment]
I do not know what logs you are giving me. I asked for Socket.IO logs. You had the instructions to get these logs in the issue template. I copied them again for you in this thread. Here they are a third time:

**Logs**
Please provide relevant logs from the server and the client. On the server, add the `logger=True` and `engineio_logger=True` arguments to your `SockertIO()` object to get logs dumped on your terminal. The same arguments can be used on the [python-socketio's client](https://github.com/miguelgrinberg/python-socketio). If you are using the JavaScript client, see [here](https://socket.io/docs/logging-and-debugging/) for how to enable logs.

**Comment by Aarlangdi** [comment]
I added these parameters to socketio but I did get anything other than I posted.
3 different places, I can get these errors in cpanel are -
- App passenger log
- cpanel terminal 
- error section of cpanel 
There are no other errors than that.
Other than that I don't know where to find logs in cpanel.

Thanks

**Comment by miguelgrinberg** [comment]
Well, I don't know how you configure your app logs. This is the application, so you must know where you app logs go to. Maybe to standard output, which is the default. Clearly you are not looking in the correct place. I do not use cpanel, so I cannot assist you with specifics to that platform.

**Comment by Aarlangdi** [comment]
Would you be able to simulate the same situation in your cpanel app with my code?

Thanks

**Comment by miguelgrinberg** [comment]
I have zero knowledge of cpanel, so no, I cannot help much with that.

**Comment by Aarlangdi** [comment]
Cpanel is really annoying, I know. There are not any other sections to look for errors - not that I know. I will try again tonight and let you know if I get different errors.

Where do I run my app for production if not cpanel? I can't host my own server.

**Comment by miguelgrinberg** [comment]
I think you are making this more complicated that it needs to be. As I said, the Socket.IO server logs a lot of useful information. By default this log goes to stdout. Make it go to a file for example, or an email if you don't have access to the file system. The logging package in Python is powerful, you can do a lot of things with it.

**Comment by Aarlangdi** [comment]
Hi Miguel,
Thanks for everything. Problem is solved now. Cpanel didn't have WS support before and now it is added by server company and it is working now.
