### ISSUE TITLE
Where have I to store sqlalchemy object

### ISSUE THREAD

**Issue by ivan-fr** [miguelgrinberg/Flask-SocketIO#1189]
Hello,

I want to create a chat application using sqlalchemy (without the flask-sqlachemy extension).
So in my code, i want to store an object for the time of a  websocket session and destroy it when the user disconnect. Because i don't want to reload the object from database each times.

If i understand i have to set manage_session to true and use the flask session normally, haven't i ?

like (in socket.py) :

import flask
flask.session["current_thread"] = thread_object

another thing, i have to create a session and close it manualy each time i use sqlachemy, haven't i ?

sorry for my english cause i'm not english lol

**Comment by miguelgrinberg** [comment]
You can store data in the session without changing the `manage_session` setting. Note that Flask expects anything you write in the user session to be serializable to JSON, so you may run into trouble writing a SQLAlchemy model.

**Comment by ivan-fr** [comment]
ok thanks :)
