### ISSUE TITLE
Question: GZIP compression for websocket data

### ISSUE THREAD

**Issue by jaredmcqueen** [miguelgrinberg/Flask-SocketIO#119]
Is there a way to compress websocket data before sending it to the browser?  Some google searching shows me that other solutions exist that do this.

In my particular application, I regularly send large JSON chunks to the browser.  It'd be awesome if I could compress these chunks to save bandwidth and speed things up.

Just wondering if I can do it with Flask-SocketIO.  thanks!

**Comment by miguelgrinberg** [comment]
Unfortunately gevent-websocket does not support compression, so no, this isn't currently possible. Sorry.

**Comment by fake-name** [comment]
Why does this require gevent support?

If compression only worked with eventlet, that'd be fine.

**Comment by miguelgrinberg** [comment]
This is an old ticket, back when I replied gevent was the only supported WebSocket implementation. For the current version, this would ideally be handled by each WebSocket implementation (gevent and eventlet), since compression is done at the protocol level.

**Comment by markmnl** [comment]
Is there support for Websocket GZIP using Flask Socket IO today?

Otherwise I'll just manually do it I guess.

**Comment by miguelgrinberg** [comment]
@markmnl it depends on which implementation of WebSocket you are using. Over the years I have added a few of them: eventlet, gevent-websocket, uwsgi, aiohttp, the websockets package, Tornado. I honestly haven't documented which do and which don't, so you will need to find out if the one you are using has this support.

**Comment by markmnl** [comment]
I'm not even sure, I have `import eventlet` but uWSGI is running my flask `Flask-SocketIO==3.0.2` application (proxied from NGINX).

I followed the docs at the time setting uWSGI up, but am not sure looking now "which implementation of WebSocket I am using".

How do I tell?

I can see messages are not being gizipped, there seem to be no args to the SocketIO application to tell it to gzip - I get you are saying this is up to the WebSocket but surely the application must control it somehow?

**Comment by miguelgrinberg** [comment]
@markmnl you seem to have an incorrect mix of two supported configurations.

If you are using uwsgi, then you WebSockets come from uwsgi itself. You can't use eventlet at the same time, not sure how that even works. You may want to remove the eventlet monkey patching.

**Comment by markmnl** [comment]
My mistake using eventlet for socketio app proxied directly from nginx (using uWSGI for another flask app which led to the confusion)

So WebSocket is being used by eventlet, but seems no way to get it gzip the messages. SocketIO docs says it should by default..
