### ISSUE TITLE
Packet loss? Emitting problem (getting slow over time)

### ISSUE THREAD

**Issue by BlasterL** [miguelgrinberg/Flask-SocketIO#1190]
Hi, guys. I am working on machine learning with Flask-SocketIO.

Firstly, introduce my setting.

I have a single server and 100 clients. The entire process like below

1. server selects some clients and requests selected clients to run training step.
2. If a client receives training request, then it sends a message of confirming request. 
3. When training in a client is done, the client sends learned parameters to central server.
4. server aggregates these learned parameters and repeats 1.

My experiment setting is on google cloud platform. My clients and server communicate internally in google cloud platform. And not using any gevent, eventlet like web-socket.

My problem is that procedure 1 is getting slow over time. Firstly, I guess some packets from server to clients dropped so I fixed my code: my server re-emits training request to the specific clients that doesn't send a message of request-confirm for every 60sec. 
```python
for sid in self.selected_clients:
        self.socketio.emit('request-train', req, room=sid) # to the specific client
        time.sleep(0.5)
is_transmit=True
t_start1=time.time()
t_start2=time.time()
while is_transmit:
        elapsed1 = time.time()-t_start1
        elapsed2 = time.time()-t_start2
        if elapsed1 >= 5:
                t_start1 = time.time()
                with self.lock_train:
                        if len(self.selected_clients) <= 0:
                                is_transmit=False
                                break
        if elapsed2 >= 60:
                t_start2 = time.time()
                with self.lock_train:
                        if len(self.selected_clients) <=0:
                                is_transmit=False
                                break
                        syslog(self.server_id, "Re-transmission : (%s)"%(self.get_clients(self.selected_clients)))
                        for sid in self.selected_clients:
                                self.socketio.emit('request-train', req, room=sid) # to the specific client
                                time.sleep(0.5)
        time.sleep(5)
```

This code is in server. time.sleep(0.5) sometimes makes bad request error[400] but time.sleep(1) is not making bad request error.

Additionally, when I sets the number of selected clients=5, the server works well. But problem is occur when the number of selected clients is above 10. 

Did you have any guess for this issue?

**Comment by miguelgrinberg** [comment]
Did you notice the bug template when you wrote your issue? It is important that you provide the information requested. Without logs I cannot do much analysis of your problem.
