### ISSUE TITLE
How to ban a client in  flask and socketio

### ISSUE THREAD

**Issue by janmejayniit** [miguelgrinberg/Flask-SocketIO#1191]
I have a issue with ban user in chat application in flask and socket io . This chat application is one to many connection. I have used socket.disconnect(socket.id) but its not working and also try many tricks but they failed to perform task. What i want when super user ban that client during the chat then client could not able to send the message to group chat. 
I have created  a function to perform this task is 
function ban_user_from_room(id){
                socket.disconnect(id);
                socket.emit('disconnect',{'user_id':id});
            }

**Comment by miguelgrinberg** [comment]
Did you notice the bug template, where you are asked to provide logs? Please follow the instructions and do that, I cannot quickly diagnose an issue without seeing logs.

**Comment by janmejayniit** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/29685541/74967091-580a5880-543e-11ea-9492-50f4944ed886.png)




Server side code.
@socketio.on('disconnect',namespace='/chat')
def disconnect_users(message):
    disconnect(message['user_id'])
    emit('message',{'msg':'User is disconnected.'})


Client side code.
<html>
    <head>
        <title>Flask-SocketIO-Chat: {{ room }}</title>
        
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js"></script>
        <script type="text/javascript" charset="utf-8">
            var socket;
            var clients = [];
            $(document).ready(function(){
                
                socket = io.connect('http://' + document.domain + ':' + location.port + '/chat');
                socket.on('connect', function() {
                    clients.push(socket.id); 
                    socket.emit('joined', {});
                    //ban_user_from_room()   
                });
                socket.on('status', function(data) {
                    $('#chat').val($('#chat').val() + '<' + data.msg + '>\n');
                    $('#chat').scrollTop($('#chat')[0].scrollHeight);
                    $("#user_list").append('<a href="javascript:;" class="ban-user-id" data-id="'+socket.id+'">'+data.user+'</a><br/>');
                });
                socket.on('message', function(data) {
                    $('#chat').val($('#chat').val() + data.msg + '\n');
                    $('#chat').scrollTop($('#chat')[0].scrollHeight);
                });
                $('#text').keypress(function(e) {
                    var code = e.keyCode || e.which;
                    if (code == 13) {
                        text = $('#text').val();
                        $('#text').val('');
                        socket.emit('text', {msg: text});
                    }
                });

                $(document).on('click','.ban-user-id',function(){
                     
                    var id =$(this).data('id');
                    ban_user_from_room(id);
                });

            });
            function leave_room() {
                socket.emit('left', {}, function() {
                    socket.disconnect();

                    // go back to the login page
                    window.location.href = "{{ url_for('main.index') }}";
                });
            }

            function ban_user_from_room(id){
                socket.disconnect(id);
                socket.emit('disconnect',{'user_id':id});
            }

             
        </script>
    </head>
    <body>
        <h1>Flask-SocketIO-Chat: {{ room }}</h1>
        <textarea id="chat" cols="80" rows="20"></textarea><br><br>
        <input id="text" size="80" placeholder="Enter your message here"><br><br>
        <a href="#" onclick="leave_room();">Leave this room</a>
        <div id="user_list">

        </div>
    </body>
</html>

**Comment by miguelgrinberg** [comment]
I need to see your logs.

**Logs**
Please provide relevant logs from the server and the client. On the server, add the `logger=True` and `engineio_logger=True` arguments to your `SockertIO()` object to get logs dumped on your terminal. The same arguments can be used on the [python-socketio's client](https://github.com/miguelgrinberg/python-socketio). If you are using the JavaScript client, see [here](https://socket.io/docs/logging-and-debugging/) for how to enable logs.

**Comment by janmejayniit** [comment]
Thanks a lot for your suggestion sir. I have find a solution with the help of socket log. Thank you very much sir.
