### ISSUE TITLE
Does flask socketIO works with paramiko in multithreading env

### ISSUE THREAD

**Issue by Set4now** [miguelgrinberg/Flask-SocketIO#1192]
My last hurdle ..

in my backend code i need to use paramiko in threaded env to run remote commands.
look like paramiko doesn't support gevent async. Does that mean i can't use flask socketio for real time updates?

**Comment by miguelgrinberg** [comment]
If paramiko does not work with gevent or with eventlet then you will have to move it to a separate process to be able to use one of these frameworks for your Socket.IO server.
