### ISSUE TITLE
Why doesn't websocketio use async keyword of python ?

### ISSUE THREAD

**Issue by ivan-fr** [miguelgrinberg/Flask-SocketIO#1193]
Hello, 

Why doesn't websocketio use "async" keyword of python ? Like django-channels does for example.

Also why don't we need to call a "sync_to_async" function when we call the database with sqlalchemy which, i think, is a synchrone function ? (also like django-channels)

**Comment by miguelgrinberg** [comment]
This library works with several async frameworks. When using along with Flask it uses gevent or eventlet. The async keyword is not used.

You can use asyncio as well, but Flask does not support it, so you have to drop Flask for that. The https://github.com/miguelgrinberg/python-socketio repo has the general version of the Socket.IO server that can be used with asyncio.
