### ISSUE TITLE
Conflict with runConsoleEventLoop?

### ISSUE THREAD

**Issue by fengerzh** [miguelgrinberg/Flask-SocketIO#1194]
Code as below:

```python
    class AppNotify(AppKit.NSObject):
        def getAppName_(self, song):
            aaa = song.userInfo().objectForKey_('NSWorkspaceApplicationKey')
            print(aaa.localizedName())
```

In namespace init function:

```python
        if system == 'Darwin':
            nc = AppKit.NSWorkspace.sharedWorkspace().notificationCenter()
            app_notify = AppNotify.new()
            nc.addObserver_selector_name_object_(
                app_notify, 'getAppName:', 'NSWorkspaceDidActivateApplicationNotification', None)

            AppHelper.runConsoleEventLoop()
```

I would like to print out the application name when user switch between apps, but once add `AppHelper.runConsoleEventLoop()`, socketio won't work, seems this function block the whole process. I've also tried to put the code in `socketio.start_background_task` but no avail. I think AppHelper block socketio.

I am not very familiar with multi thread coding, any suggesiton? Thanks!

**Comment by miguelgrinberg** [comment]
Are you using eventlet or gevent in your application?

If you are, then you are not using multithreading, you are using async tasks, which are likely being blocked by the `runConsoleEventLoop()` function.

**Comment by fengerzh** [comment]
Yes, I am using eventlet. I thought I have to use eventlet as I need to use pyinstaller to package it. Is that possible to still use multithreading and without eventlet while using pyinstaller to make package? My package will be only used on client computer and only serve one client, I think I do not need eventlet kind of tech, but don't know how to make it.

**Comment by fengerzh** [comment]
I read document again, and found below sentence:

> If neither eventlet nor gevent are installed, then the Flask development server is used.

Is that means when I use pyinstaller to package it, I should firstly do `pip uninstall eventlet` and `pip uninstall gevent`, so that the package won't use eventlet any more, and then I can use multi-threading? I am really confused, thanks for you support.

**Comment by fengerzh** [comment]
> async_mode – The asynchronous model to use. See the Deployment section in the documentation for a description of the available options. Valid async modes are threading, eventlet, gevent and gevent_uwsgi. If this argument is not given, eventlet is tried first, then gevent_uwsgi, then gevent, and finally threading. The first async mode that has all its dependencies installed is then one that is chosen.

So maybe set `asnyc_mode` to `threading` will make it work?

**Comment by miguelgrinberg** [comment]
Sure, you can uninstall eventlet and gevent, and then the server will automatically run in threading mode, as that will be the only available mode.

Keep in mind that WebSocket isn't supported when using threading.

**Comment by miguelgrinberg** [comment]
Sure, you can uninstall eventlet and gevent, and then the server will automatically run in threading mode, as that will be the only available mode.

Keep in mind that WebSocket isn't supported when using threading.

**Comment by fengerzh** [comment]
Thank you! Finally I got the `threading` mode work! Just specify `async_mode` to `threading` when create socketio, and `from engineio.async_drivers import threading` will make `pyinstaller` to package it, and the server will run in a polling mode, which works perfect for my situation. This is really interesting, now I totally understand how socketio works. Thanks for your timely help again!
