### ISSUE TITLE
Websocket stuck at 101 status (Switching Protocols)

### ISSUE THREAD

**Issue by BassThatHertz** [miguelgrinberg/Flask-SocketIO#1197]
**Describe the bug**
I am trying to use websockets to show the contents of a text file in realtime to my website. The text file has the current encoding progress of an audio file and I want this to be shown on my website during the "File uploaded. Converting..." stage This works when running my flask app on my local computer, however I also run my flask app on an Amazon AWS ubuntu server (because I want my website to be up 24/7) and for some reason it's stuck on 101 status when I look at the network tab of Chrome. 

Here is what I see in the network tab when running it on my local computer (and everything works as it should): https://i.imgur.com/ZFZI5DZ.png

Here is what I see in the network tab when I access the same flask app (i.e. my website) that is running on the ubuntu server: https://i.imgur.com/09gP3N4.png. You can access my website via https://freeaudioconverter.net if it will help you to diagnose the issue.

**To Reproduce**
Simply go to my website using Chrome, right click on the webpage, select "Inspect", click on the "Network" tab and you will see what I mean.

**Expected behavior**
After selecting an audio file and clicking on "Convert", during the "File uploaded. Converting..." stage, you are supposed to be able to see the converting progress at the bottom of my webpage. This works when running this on my local computer, so I'm guessing the issue is related to Nginx or Gunicorn. I'm also using eventlet as you can see in the myproject.service file below.

**Additional context**
To configure gunicorn, I created a myproject.service file as suggested in [this tutorial](https://www.digitalocean.com/community/tutorials/how-to-serve-flask-applications-with-gunicorn-and-nginx-on-ubuntu-18-04). Here is the contents of my "myproject.service" file:

```
[Unit]
Description=Gunicorn instance to serve myproject
After=network.target

[Service]
User=ubuntu
Group=www-data
WorkingDirectory=/home/ubuntu/myproject
ExecStart=/home/ubuntu/.local/bin/gunicorn --timeout=9999 --worker-class eventlet -w 1 myproject:app --bind 127.0.0.1:5000

[Install]
WantedBy=multi-user.target
```
And here is my Nginx configuration file:
```
server {
    listen 80;
    server_name freeaudioconverter.net;

    location / {
        include proxy_params;
        proxy_pass http://127.0.0.1:5000;
    }

    location /socket.io {
        include proxy_params;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass http://127.0.0.1:5000/socket.io;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/freeaudioconverter.net-0001/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/freeaudioconverter.net-0001/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot



}
```

**Comment by BassThatHertz** [comment]
If it helps, you can see all of the Flask/Python/HTML/JavaScript code here: https://github.com/BassThatHertz/freeaudioconverter.net
The files to pay attention to are **main.py** and **progress.js** in /static/js

**Comment by miguelgrinberg** [comment]
I'm confused about what you expect to happen with that 101. That's perfectly normal. Looking at that websocket connection on your site I see that ping and pong packets are being sent at the 25 second rate as normal. So I fail to see the problem with this connection. It seems to work.

**Comment by BassThatHertz** [comment]
> I'm confused about what you expect to happen with that 101. That's perfectly normal. Looking at that websocket connection on your site I see that ping and pong packets are being sent at the 25 second rate as normal. So I fail to see the problem with this connection. It seems to work.
When the user selects an audio file and clicks on the convert button at the bottom, the file starts uploading. When it has uploaded, it starts converting and an unclickable button (File uploaded. Converting..." appears. When this button appears, underneath it it is supposed to be showing the conversion progress in realtime. But it doesn't. Maybe the 101 thing is not the issue, this is my first time using websockets and Flask-SocketIO so I just mentioned the 101 thing being stuck on pending as I was assuming that was the issue, but the issue might be something else. When running the flask app locally on my Windows 10 machine using the flask development server, the realtime conversion progress shows as it should. I've also noticed that the "?EIO" websocket thing repeatedaly shows up in the network log, whereas on my website running on the Ubuntu server with Nginx/Gunicorn, looking at the network tab there's is only two "?EIO" websocket thiings and then a 3rd pending 101 one.

I've recorded a video for you to show what is supposed to happen. Please have a look when you're free and if you have any questions or would me to show you something in particular, let me know :)

Here is the video: https://www.youtube.com/watch?v=MYreOeVoDx8

**Comment by BassThatHertz** [comment]
> I'm confused about what you expect to happen with that 101. That's perfectly normal. Looking at that websocket connection on your site I see that ping and pong packets are being sent at the 25 second rate as normal. So I fail to see the problem with this connection. It seems to work.

I decided to use console.log to see whether the text from the file is being retrieved: https://i.imgur.com/sBnDgj5.png

I noticed something interesting. When I load the page, it is continually getting the text from the file once every second which is good as this is what I'm telling to it do. However, when an audio file starts converting and the old text file starts being overwritten, at this stage I no longer see anything with the console.log statement I added. This is why the user cannot see the conversion progress. Maybe on Ubuntu you cannot read a file while it's being overwritten or something? This is the code I'm using to read the file:
```
with open('2.txt', 'r') as f:
            lines = f.readlines()
            last_line = lines[-5:]
            last_line = last_line[0]
            last_line = last_line[:-8]
            last_line = last_line[9:]
            formatted_output = last_line + " [HH:MM:SS]" + " of the file has been converted so far..."
            print(formatted_output)
            # Trigger a new event called "show progress" 
            socketio.emit('show progress', {'number': formatted_output})
            socketio.sleep(1)
```

**Comment by miguelgrinberg** [comment]
Are you using gevent or eventlet? If yes, have you monkey patched the standard library? It is possible that when you run ffmpeg you are completely blocking the web server if you did not fix the standard library to be compatible with gevent/eventlet.

**Comment by BassThatHertz** [comment]
> Are you using gevent or eventlet? If yes, have you monkey patched the standard library? It is possible that when you run ffmpeg you are completely blocking the web server if you did not fix the standard library to be compatible with gevent/eventlet.
> 
How do I do this? This is the first time I've come across the term "monkey patch", I only started learning programming last year so I'm not expert at Python either. Here is my main.py code: https://github.com/BassThatHertz/freeaudioconverter.net/blob/master/main.py

What do I need to change?

**Comment by BassThatHertz** [comment]
And I'm using eventlet

**Comment by BassThatHertz** [comment]
Do I simply add:
```
import eventlet
eventlet.monkey_patch()
```
in main.py and that's it?

**Comment by miguelgrinberg** [comment]
@BassThatHertz in general yes, you run the monkey patching at the top of your main script and that is it. Unfortunately this isn't a beginner friendly thing, maybe you try this and it works and you got lucky, but be aware that it may take additional work to get everything to work nicely under eventlet depending on the functions that you use in your application.

**Comment by BassThatHertz** [comment]
> @BassThatHertz in general yes, you run the monkey patching at the top of your main script and that is it. Unfortunately this isn't a beginner friendly thing, maybe you try this and it works and you got lucky, but be aware that it may take additional work to get everything to work nicely under eventlet depending on the functions that you use in your application.

Maybe I can use something else instead of eventlet? I tried adding the monkey patch thing and it didn't work. It seems like I need to use eventlet or gevent because I'm using Gunicorn. If Gevent doesn't work either, do you know what method of deploying my flask app is most likely to allow this to work? I'm even willing to change the WSGI that I'm using etc, maybe uSWGI with gevent will work? 

I just want this to work.

**Comment by miguelgrinberg** [comment]
Yeah, sorry that this is so difficult, that is why I indicated that you should be prepared for potential troubles.

Unfortunately there isn't a simple solution that I can give you. Basically you have two approaches:

- Keep doing what you are doing and do not use eventlet/gevent. Your ffmpeg solution will work well, but you won't have WebSocket.
- Use eventlet or gevent to have WebSocket. Figure out what is it that you are doing in your application that is incompatible with these frameworks and do it in a different way that works. This is in general hard, sadly, as some things just don't work when you use an asynchronous server.

**Comment by BassThatHertz** [comment]
So the issue is because of eventlet, not Nginx or Gunicorn?
> * Keep doing what you are doing and do not use eventlet/gevent. Your ffmpeg solution will work well, but you won't have WebSocket.

According to the Flask-SocketIO documentation, it seems like I need to use eventlet/gevent if using Gunicorn or uWSGI. So I'll have a look at what other WSGIs there are that don't require eventlet/gevent when you want to use Flask-SocketIO (any suggestions?). The only reason I'm using Gunicorn is because it's not recommended to use Flask's built-in development server.

**Comment by miguelgrinberg** [comment]
Once again, I apologize this is so complex and confusing. Let me try to clarify.

- The Flask dev server is, as you already know, not recommended for a production site. This server, however, works really well with Flask-SocketIO, as you also have experienced.
- Normally Gunicorn and uWSGI are not used with threads. They both support threads though. If you run a single Gunicorn process and enable lots of threads on it, and do not use eventlet/gevent, then Flask-SocketIO should work (though I haven't personally tested nor documented this option). You will not have WebSocket if you do this. The approximate number of concurrent clients you will be able to support is half the number of threads that you run. So for example, if you configure 20 web threads you will be able to handle about 10 connected clients. Of course these threads are separate from the threads that you create in your app.

So there isn't a great solution here, unfortunately, but if you don't care about WebSocket you may be able to make this work.

**Comment by BassThatHertz** [comment]
@miguelgrinberg 
I'm probably being annoying but I just tried switching to gevent as the documentation says it supports WebSocket ("When using gunicorn with the gevent worker and the WebSocket support provided by gevent-websocket, the command that starts the server must be changed to select a custom gevent web server that supports the WebSocket protocol. "). I installed gevent-websockets and I'm using the following Gunicorn command: 

`gunicorn --threads 2 -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 myproject:app`
I've also used `--threads` as you can see.
And in main.py I have:
`from flask_socketio import SocketIO`
 `socketio = SocketIO(app, async_mode='gevent')`
and at the bottom:
```
if __name__ == "__main__":
    socketio.run(app)
```
Shouldn't this work?

**Comment by miguelgrinberg** [comment]
The `--threads` option should not be used with gevent or eventlet. If it works or not really depends on the functions that you use and whether they are compatible with gevent, so the easiest way to know is to try it.

**Comment by BassThatHertz** [comment]
I didn't need to use eventlet/gevent when using gunicorn.... I decided to try using Gunicorn without either of those and and the encoding progress now shows on my website. The documentation implies that you need to use eventlet or gevent when using Gunicorn:
`An alternative to socketio.run(app) is to use gunicorn as web server, using the eventlet or gevent workers. For this option, eventlet or gevent need to be installed, in addition to gunicorn. 
`
Why does the documentation state eventlet or gevent need to be installed?

**Comment by miguelgrinberg** [comment]
@BassThatHertz Unfortunately you are somewhat incorrect in your assessment. Gunicorn without eventlet or gevent is a really bad deployment solution for most people. I get that it works for you, but it is not something I would recommend. Problems:

- No WebSocket.
- The maximum number of clients you can have reliably is limited to half the number of threads you allocate.

**Comment by BassThatHertz** [comment]
I have a question related to SocketIO. Is there a difference between `socketio.start_background_task` and starting a thread using Python's threading module? Does `socketio.start_background_task` basically start a thread?

In other words, is this:
`socketio.start_background_task(GetOutput)`
equivalent to:
```
import threading
my_thread = threading.Thread(target=GetOutput)
my_thread.start()
```

If there is a difference between the two, what is the difference? I'm currently using start_background_task and I'm wondering if I should use the threading module instead.

**Comment by miguelgrinberg** [comment]
@BassThatHertz the difference is that `start_background_task()` can start the task using several methods. If you are using the eventlet or gevent web servers it uses methods that are appropriate to those frameworks. If you are using the threading mode then it just starts the thread using the threading package, so only in that case the two methods are the same.

**Comment by BassThatHertz** [comment]
@miguelgrinberg Thank you. I have another question regarding whether to use multiple workers or multiple threads. I've realised that using multiple workers also works. So Both `gunicorn --workers 3` and `gunicorn --threads 3` work and show the live encoding progress on my website via socket.io. 

I'm not sure which approach I should use. I'm using a free Amazon EC2 Ubuntu server which only has 1 vCPU, so I believe I shouldn't go above 3 workers as gunicorn recommends (number of CPUs x 2) + 1. Any idea whether using workers or threads is better for my application and server hardware?

**Comment by miguelgrinberg** [comment]
Threads is your only option, you are again incorrect regarding multiprocessing web servers. Not sure what you are testing exactly, but that's a road to trouble, it just does not work.

As I said above, using gunicorn w/o eventlet/gevent with the `--threads` option works, but it is a bad deployment option. What you need to think about is how many clients you want to have connected at the same time. Take that number, multiply it by 2, and that's the least number of threads you need to maintain the Socket.IO connections. For example, if you need to host 20 clients concurrently you need at least 40 threads. You need to add more threads for HTTP traffic not related to Socket.IO on top of that.

**Comment by BassThatHertz** [comment]
> As I said above, using gunicorn w/o eventlet/gevent with the `--threads` option works, but it is a bad deployment option. What you need to think about is how many clients you want to have connected at the same time. Take that number, multiply it by 2, and that's the least number of threads you need to maintain the Socket.IO connections. For example, if you need to host 20 clients concurrently you need at least 40 threads. You need to add more threads for HTTP traffic not related to Socket.IO on top of that.

Isn't there a limit to the amount of threads I can have considering I'm running my Flask app on a single core machine? Gunicorn recommends that the number of workers should be (number of CPUs x 2) + 1, and I decided to use this same formula for the number of threads because I'm not sure how many threads I can have. What is the limit? Surely there has to a limit otherwise everyone can just set a high number of threads to be safe.

**Comment by miguelgrinberg** [comment]
Usually the limit is memory. You can have as many threads as you like as long as you don't run out of memory.

The Socket.IO server is heavily I/O bound, which means that most threads are going to be idle most of the time. The traditional formulas of (#CPUs x 2) or (#CPU x 2 + 1) are okay to use I guess, as long as you realize that you have a maximum limit in number of concurrent connections, and if you pass that some clients are going to timeout and drop.

Going back to my (#clients x 2) formula, I wanted to note that if your traffic is moderate to low, you may get away with less threads, so you may want to test (#clients x 1.5) for example and see how responsive the system is. The formula I gave you originally is for a worst-case very busy server.

**Comment by BassThatHertz** [comment]
> Going back to my (#clients x 2) formula, I wanted to note that if your traffic is moderate to low, you may get away with less threads, so you may want to test (#clients x 1.5) for example and see how responsive the system is. The formula I gave you originally is for a worst-case very busy server.

I think setting number of threads to (#clients x 2) is pretty much necessary. That's because two threads are required for the conversion to happen AND the progress file to be read at the same time (to show the user the encoding progress). Right now, I'm assuming 2 clients can't see their conversion progress at the same time as I've set the number of threads to 3. The server has 1GiB of memory, I wonder how many threads I can have. Just ran the `free -h` command in the terminal and [it seems like I have 114MB memory available](https://i.imgur.com/LeTkCy0.png), any idea roughly how many threads I can have?

I appreciate the help you've given :)

**Comment by miguelgrinberg** [comment]
You can look at `top` or `ps` to see how much memory the server uses. Try running different number of threads and looking at memory usage (during normal use, a recently started server that is idle would not give you a good measure).
