### ISSUE TITLE
Data received at client side is found distorted

### ISSUE THREAD

**Issue by dadhichmohit** [miguelgrinberg/Flask-SocketIO#1199]
I am emitting data to client from server with  different code locations:

**_For Event Id : 'remove_grains'_**
`socket_server.emit("remove_grains", {'message': "3D Image Acquisition Completed, Now You can Remove Grains"})`
`socket_server.sleep(0.1)`

**_For Event Id : 'prediction_initiated'_**
`socket_server.emit('prediction_initiated', {'message': "Classification Processing...Now You Can Remove Grains"})`
`socket_server.sleep(0.1)`

**Flask Side Declaration:**
`socket_server = SocketIO(matt, engineio_logger=True)`

**Client Side Declaration:**
`var socket_client = io.connect('http://' + document.domain + ':' + location.port);`

### **Now Server Logs are:**
**_For Event Id : 'remove_grains'_**
`c237667168a34c38bf02132863c9cf5d: Sending packet MESSAGE data 2["remove_grains",{"message":"3D Image Acquisition Completed, Now You can Remove Grains"}]`

**_For Event Id : 'prediction_initiated'_**
`c237667168a34c38bf02132863c9cf5d: Sending packet MESSAGE data 2["prediction_initiated",{"message":"Classification Processing...Now You Can Remove Grains"}]`

### **Console log at client side:**

**_For Event Id : 'remove_grains'  Received event data is 'sremove_grains'_** 

`engine.io-client:socket socket receive: type "ping", data "["sremove_grains,{"message":"P3D Imge" Acquisiion SCople.ed ,Now. You an Reqmove Grains,}]"`

**_For Event Id : 'prediction_initiated' Received event data is 'proedicion_initiated' _**

`engine.io-client:socket socket receive: type "ping", data "["proedicion_initiated",{"sessage":"PClasinfiction Srocessing .."ow. You Cn Reqmove Grains,}]"`

As client is receiving distorted event names/ids  and message data, further client side events are not functioning. Please guide how tackle this issue, Is there any basic mistake i am making while emitting message from server.

Thanks a Ton.
Regards
Mohit

**Comment by miguelgrinberg** [comment]
I can't really suggest anything from the software side, I have never seen something like this. Messages go out through TCP, so there is error correction in place to prevent this. Is your network set up non-standard?

**Comment by dadhichmohit** [comment]
Dear Miguel, 

Thanks for a quick response. My program runs on a standalone LocalHost machine,Client is using chrome browser on the same machine. There is sometime 'Client Gone. Closing Socket Connection' has been observed. Sometime it also disconnects stating : 'Received a broken close frame containing invalid UTF-8'. But this distorted data is bothering me a lot and it is pretty strange too me as well. 
 
I am using gunicorn  and eventlet and running the program with following parameters:

`~/.virtualenvs/m3/bin/gunicorn --worker-class eventlet -w 1 run:matt -b 0.0.0.0:$port -t 500 --preload --access-logfile $ACCESS_FILE --error-logfile $ERROR_FILE --log-level=debug  --capture-output &
`
My virtual Environment Consist of:

Flask==1.1.1
Flask-SocketIO==4.2.1
gunicorn==19.9.0
eventlet==0.25.1
python-engineio==3.9.3
python-socketio==4.3.1

On Client End Javascript SocketIO is 1.3.6. 

I am happy to deliver further details. Please let me know if you need any.

Regards
Mohit

**Comment by miguelgrinberg** [comment]
Can you reproduce this on a second computer? If the problem exists on multiple computers I'll need you to create a small self-contained version of it that I can test here.

**Comment by dadhichmohit** [comment]
I will let you know the proceedings. 

Thanks
