### ISSUE TITLE
extra_files in run_with_reloader?

### ISSUE THREAD

**Issue by bjamil** [miguelgrinberg/Flask-SocketIO#120]
Hi, 

It looks like run_with_reloader originally supports an 'extra_files' parameter, but this is gobbled up with the monkey patching done in SocketIO.run(...) in this project. That field is a pretty nice way to restart the app when config files change. Can we get that parameter back? 

Am happy to submit a PR for it, if needed.

**Comment by miguelgrinberg** [comment]
I don't have a problem with adding `extra_files`, happy to take it as a contribution if you want to do it. Thanks!

**Comment by bjamil** [comment]
Great! [PR submitted](https://github.com/miguelgrinberg/Flask-SocketIO/pull/121). 

Thanks!

**Comment by miguelgrinberg** [comment]
Merged. Thanks again.
