### ISSUE TITLE
How can I check if client is still connected?

### ISSUE THREAD

**Issue by hqntrt** [miguelgrinberg/Flask-SocketIO#1202]
Issue is if a client refreshes the chat page fast enough, the client side of socketio does not fire disconnect event when the page is refreshed but the new chat page fires a connect event therefore server can match the same user with himself with different two ids. Is there a way to check if the client is still there before matching them? Do I have to implement a ping pong kind of mechanism or does this library already provide such features?

**Comment by miguelgrinberg** [comment]
You will get the disconnect a little bit later, in about a minute.

The problem is that if you refresh the page before the client was upgraded to websocket then the disconnection takes longer to detect.

**Comment by hqntrt** [comment]
Thank you for answer, does that mean should I leave it as it is or invest time in such feature?

**Comment by miguelgrinberg** [comment]
The disconnects are supported, they just take longer when the client is connected with HTTP. You can't immediately determine if an HTTP client is gone, you just have to wait for some time and if you don't get any polling messages for a while you just have to assume the client went away.

**Comment by hqntrt** [comment]
Just to be clear you are referring to the default disconnect behavior by saying " if you don't get any polling messages for a while you just have to assume the client went away" , right? I don't get to access those polling messages on the server (without a hacky way at least )?

**Comment by miguelgrinberg** [comment]
I'm just explaining how the disconnect logic works. There is nothing to do on your part, it's all being done in this library.

**Comment by hqntrt** [comment]
Thank you for your great work and help.

**Comment by ilirosmanaj** [comment]
@miguelgrinberg is there a way to catch this event? I would want to run some custom code in case the client disconnects

**Comment by miguelgrinberg** [comment]
Yes. Link to docs: https://flask-socketio.readthedocs.io/en/latest/getting_started.html#connection-events

**Comment by Curiouspaul1** [comment]
Hi is it possble to check before sending an event to a client, that the client is still connected?.

**Comment by Curiouspaul1** [comment]
I was thinking of using a store using request.sid, so anytime a client connects i store their sid in redis using the on.connect() event and when it disconnects I remove it from the cache. So to confirm i believe i could check the redis store to see if the sid is still in there. What do you think of this.?

**Comment by miguelgrinberg** [comment]
@Curiouspaul1 That should be okay, but keep in mind that some disconnections take a bit of time to be detected, usually up to a minute or so, so you may still find that when you try to send an event to a user that is in your redis store the user is already gone and has not been detected yet.

**Comment by Curiouspaul1** [comment]
Hmm okay thanks will find a way around that. Have a great day

**Comment by sidhant1608** [comment]
How are you handling this ? I was thinking of deleting all my keys on server shutdown / restart so my redis store gets built by scratch when server comes up as all clients would fire on connect again anyways. @Curiouspaul1
