### ISSUE TITLE
gevent.spawn_later not working as expected

### ISSUE THREAD

**Issue by jugges** [miguelgrinberg/Flask-SocketIO#1203]
I'm using flask-socketio with gevent after I ran into issues that made working with eventlet a nightmare (mainly it's co-operation with the mpv-python library). And what I need to do is spawn a function after a certain time gap defined by seconds.

With eventlet it was achievable by calling `eventlet.spawn_after`,
With gevent it seems achievable by calling `gevent.spawn_later`,
but it seems not to work when called after `socketio.run`:

**Code Example**
```Python
def delayed_thing(msg):
    print(msg)


if __name__ == '__main__':
    gevent.spawn_later(2, delayed_thing, 'hello world')
    with open('videos.json', encoding="utf8") as json_file:
        videos = json.load(json_file)
    gevent.spawn_later(5, delayed_thing, '5 seconds')
    socketio.run(app, host='0.0.0.0', port=5000, debug=True)
    gevent.spawn_later(1, delayed_thing, 'SHOW ME!')
    player['osd-duration'] = 5000
```

**Output**
```
Server initialized for gevent.
 * Restarting with stat
Server initialized for gevent.
 * Debugger is active!
 * Debugger PIN: 157-451-657
hello world
5 seconds
```

It may also be important to list that I didn't monkey patch the standard library as it makes the application freeze upon starting and I suspect it to conflict with that python-mpv library after some debugging.

In what way should I schedule a function to start after a certain amount of seconds?

**Comment by quiddihub** [comment]
`socketio.run` does not return, so any statement after that will not be executed... as far as I understand it. Also, I was under the impression that monkey patching was required under Python 3 - is this not always the case?

**Comment by jugges** [comment]
@quiddihub
`player['osd-duration'] = 5000` is being executed despite being placed after 
`socketio.run`, I also tried having that 
`gevent.spawn_later` execute on a certain function call decorated by a socketio event and faced the same issue.

**Comment by miguelgrinberg** [comment]
@jugges you are mistaken, socketio.run does not return, so nothing that you put after will ever run. This is true for eventlet and gevent. Move your spawn above socketio.run please.

I expect you will also have issues with mpv-python when using gevent. For both eventlet and gevent you may get things to work better if you monkey patch the standard library.

**Comment by jugges** [comment]
@miguelgrinberg Thank you for taking time to answer this question Miguel,
Yes I was mistaken about `socketio.run`, but what about doing something like this:
```
def startVoting():
    global status, isVoting, userVoteList
    userVoteList = {}
    isVoting = True
    status = 2
    gevent.spawn_later(voteTime, delayed_thing)
    socketio.emit('status', getStatus())
    app.logger.info('vote started!')
```
This function is being called from an mpv event listener and yet `gevent.spawn_later` is not working... I've implemented sort of a workaround by having one of the clients that's considered a "master" to the server do the count down for the server and then emit when it's done, but am still curious if there's a working way to implement calling a function after a certain time count.

**Comment by miguelgrinberg** [comment]
@jugges re-read my previous message, the part about monkey patching. Try that. If that does not help, then you'll probably have to assume that mpv-python is incompatible with gevent and eventlet.

**Comment by jugges** [comment]
> @jugges re-read my previous message, the part about monkey patching. Try that. If that does not help, then you'll probably have to assume that mpv-python is incompatible with gevent and eventlet.

Monkey patching freezes my application:
```python
from gevent import monkey
monkey.patch_all()

import json
from random import randrange
from flask_socketio import SocketIO, send, emit, ConnectionRefusedError
from forms import LoginForm
from flask import Flask, abort, session, render_template, url_for, flash, redirect, request
import socket
import mpv
from collections import Counter
```
Guess I'll just stick to my workaround!
Thanks anyway (:
