### ISSUE TITLE
Both flask live stream  and flask-socketIo can not be done concurrently

### ISSUE THREAD

**Issue by yanxiaoyan2020** [miguelgrinberg/Flask-SocketIO#1206]
@miguelgrinberg
Hello Flask_socketIO team
I want to send messages to client continuously from server when live stream  are playing.But they can not be done cocurrently.How can I resolve it?Is this design feasible?

**Comment by miguelgrinberg** [comment]
Please provide information about your problem, the title is not sufficient.

**Comment by yanxiaoyan2020** [comment]
@miguelgrinberg 
my code main.py and index.html as following.
 I try to create thread to send video stream many times ,then failed.How can I video streaming and control by user on browser,for example stop and start live video stream.
main.py 
from flask import Flask, render_template, Response
from flask_socketio import SocketIO, emit
from camera import Camera
from threading import Lock

app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app, async_mode=async_mode)
thread = None
thread_lock = Lock()


@app.route('/')
def index():
    return render_template('index.html')

def gen(camera):
    while True:
        frame = camera.get_frame()
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')

@app.route('/video_feed')
def video_feed():
    return Response(gen(Camera()),
                    mimetype='multipart/x-mixed-replace; boundary=frame')
                    
def background_thread():
    """Example of how to send server generated events to clients."""
    count = 0
    while True:
        socketio.sleep(10)
        count += 1
        socketio.emit('my_response',
                      {'data': 'Server generated event', 'count': count},
                      namespace='/test')
@socketio.on('connect', namespace='/test')
def test_connect():
    global thread
    with thread_lock:
        if thread is None:
            thread = socketio.start_background_task(background_thread)
    emit('my_response', {'data': 'Connected', 'count': 0})


@socketio.on('my_event', namespace='/test')
def test_message(message):
    session['receive_count'] = session.get('receive_count', 0) + 1
    emit('my_response',
         {'data': message['data'], 'count': session['receive_count']})

if __name__ == '__main__':
    socketio.run(app)
index.html
<html>
 <head>
    <title>Flask-SocketIO Test</title>
    <script src="//code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.js" integrity="sha256-yr4fRk/GU1ehYJPAs8P4JlTgu0Hdsp4ZKrx8bDEDC3I=" crossorigin="anonymous"></script>
    <script type="text/javascript" charset="utf-8">
        $(document).ready(function() {
            // Use a "/test" namespace.
            // An application can open a connection on multiple namespaces, and
            // Socket.IO will multiplex all those connections on a single
            // physical channel. If you don't care about multiple channels, you
            // can set the namespace to an empty string.
            namespace = '/test';

            // Connect to the Socket.IO server.
            // The connection URL has the following format, relative to the current page:
            //     http[s]://<domain>:<port>[/<namespace>]
            var socket = io(namespace);

            // Event handler for new connections.
            // The callback function is invoked when a connection with the
            // server is established.
            socket.on('connect', function() {
                socket.emit('my_event', {data: 'I\'m connected!'});
            });

            // Event handler for server sent data.
            // The callback function is invoked whenever the server emits data
            // to the client. The data is then displayed in the "Received"
            // section of the page.
            socket.on('my_response', function(msg, cb) {
                $('#log').html('Received #' + msg.count + ': ' + msg.data));
                if (cb)
                    cb();
            });
       });
    </script>
</head>
  <body>
    <h1>Video Streaming and control Demonstration</h1>
     <h2>Receive:</h2>
    <p id="log">   </p>
    <img src="{{ url_for('video_feed') }}">
  </body>
</html>

I am confused whether this design is feasible or not. 
I am looking forward to your response 
best regards   yan

**Comment by miguelgrinberg** [comment]
As long as your web server is multithreaded this should work. If it doesn't work on a multithreaded web server then you need to debug it, look for clues or errors in the client and the server.

**Comment by yanxiaoyan2020** [comment]
@miguelgrinberg 
      Thanks for your taking time to answer this question.  
       My web server is multithreaded. Maybe I didn't  describe this issue clearly.
       When I run main.py as above,client can emit 'connected 'to server  ,and also can emit 'my event' to server by click commit on browser .Then, when web server start to send video stream   to browser(client) ,both servery and client cannot communicate by click commit on browser using socketIO.
      best regards  yan

**Comment by miguelgrinberg** [comment]
If your server is multithreaded it should be able to maintain a Socket.IO connection while at the same time respond to HTTP events, so I don't see why that would not work. Check the log for your web server for errors, and also the browser's console.

If your server is running on a slow system (Raspberry Pi or similar) then maybe the work of generating the stream makes all other tasks in the system very slow. In that case try slowing down your stream by adding a `socketio.sleep(0.1)` statement or similar in the generator function.

If nothing seems to work, I have to say that I'm doubting you are using a multithreaded web server.

**Comment by yanxiaoyan2020** [comment]
@miguelgrinberg  
        My server is running on a slow system (Raspberry Pi 4B) .
         I have doubt that  my raspberry 4b can not support 25 fps  video stream and socketIO concurrently.    But I am not sure whether the work of generating the stream makes all other tasks in the system very slow.   When  generator video stream starts,I setup three Processes( from multiprocessing) to preprocess image.  I have already slowed down my stream by adding a socketio.sleep(5) statement.But it doesn't work.   I will try to slow down  video stream  in the generator function by adding a time.sleep.
       It's nice of you to answer this question.
        Best regards ,yan

**Comment by miguelgrinberg** [comment]
Are you using eventlet or gevent? Try using the "threading" async mode instead as a test, to see if that makes any difference.

**Comment by yanxiaoyan2020** [comment]
@miguelgrinberg 
     It's nice to answer this question.
     I have slowed down my video stream  in the yield function  by adding a time.sleep(0.1) .  It works. That' great, It's helpful for me. It proved my doubt although video stream  is not up to 25 fps. It's nice of you to help me to resolved this question.
    I will using eventlet or gevent to see whether that make other difference.For example, improving performance about fps.
    I bought your book "Flask Web development" in 2014 ISBN:978-7-115-37399-1. That's good book. Would you please recommend appropriate book. I developed project using flask two monthes ago. thank  you again.
     Best regards     yan

**Comment by miguelgrinberg** [comment]
@yanxiaoyan2020 If you've added a `sleep(0.1)` that means that the most efficient frame rate you would be able to get is never going to be faster than 10 fps, since your 0.1 seconds of sleep prevent it. Now that you have the system working you can try to fine tune it by reducing the 0.1. Maybe if you use `sleep(0.05)` you get more fps, while still having a responsive system.

Using eventlet or gevent is not going to make your server faster, in fact when working with specialized hardware such as cameras in general these frameworks do not work well, that is why I asked you if you were using them already.

**Comment by yanxiaoyan2020** [comment]
@miguelgrinberg
       I've added a sleep(0.001)  and sleep(0.1) in yield function ,the former is 10 fps,the later is 8 fps in win OS, and when video steam is playing ,browser and server can communicate in these cases. And I have observed that video stream picture pause with eyes.
        I will try to test them in raspberry 4 B.,then the test result let you know.   Your analysis is very accurate.  that's awesome. 
       Best regards     yan

**Comment by yanxiaoyan2020** [comment]
@miguelgrinberg 
        I have tested fps by adding a time.sleep(0.001  1ms)   in raspberry 4 B.Frame per second in this case is 25.The performance is nice.That is great.  Thanks for your suggestion and analysis. It's nice of you.
       Best regards     yan
