### ISSUE TITLE
SocketIO Peer to Peer

### ISSUE THREAD

**Issue by nxtexe** [miguelgrinberg/Flask-SocketIO#1214]
Is there any socketiop2p functionality coming soon? As you know WebRTC is becoming more reliable, socketiop2p is possible through nodejs as their examples demonstrate here https://github.com/socketio/socket.io-p2p. I'm not sure if flask_socketio has any implementation of this that I'm unaware of. If so could you explain?

**Comment by miguelgrinberg** [comment]
To my knowledge this hasn't been implemented for the Python Socket.IO server.

**Comment by nxtexe** [comment]
Ok thanks for the quick response.

**Comment by nxtexe** [comment]
I'll close the issue if that's ok
