### ISSUE TITLE
Poor scaling of app based on Flask-Socketio

### ISSUE THREAD

**Issue by mischkadb** [miguelgrinberg/Flask-SocketIO#1215]
I cannot tell if Flask-Socketio is even the problem, but my app scales rather poorly in production. There is currently a user influx due to increased free time of players. A digitalocean droplet with 200 users online uses >50% of the CPU. With ~40 users online it uses ~10%. The 5 gunicorn workers consume by far most of it. 

The stack is Flask-Socketio + gevent + gunicorn + nginx. You can see the socketio initialization here: https://github.com/mischkadb/lidarts/blob/master/lidarts/__init__.py

I think there must be some mistake on my side because there is no way I could scale this app properly. If you need certain logs let me know. Help would be much appreciated.

The relevant parts of the nginx config:

```
upstream socketio_nodes {
    ip_hash;

    # flask-socketio+gevent+gunicorn can only handle one worker, nginx has to load balance
    # basic # of workers: # of (v)CPUs * 2 + 1
    server 127.0.0.1:5001;
    server 127.0.0.1:5002;
    server 127.0.0.1:5003;
    server 127.0.0.1:5004;
    server 127.0.0.1:5005;
}

[..]

server {
    server_name lidarts.org;

    location / {
        include proxy_params;
        proxy_pass http://socketio_nodes;
    }

[..]

    location /socket.io {
        include proxy_params;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_redirect off;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header X-NginX-Proxy true;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass http://socketio_nodes/socket.io;

        proxy_read_timeout 3600;
        proxy_send_timeout 3600;

        proxy_headers_hash_max_size 2048;
        proxy_headers_hash_bucket_size 256;
    }

[..]

```

The systemd service config (x5):

```
[Unit]
Description=Gunicorn instance to serve lidarts1
After=network.target

[Service]
User=lidarts
Group=www-data
WorkingDirectory=/home/lidarts/lidarts
Environment="PATH=/home/lidarts/lidarts/venv/bin"
ExecStart=/home/lidarts/lidarts/venv/bin/gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 "lidarts:create_app()" -b 127.0.0.1:5001 --error-logfile /home/lidarts/logs/gunicorn_error.log
ExecReload=/bin/kill -s HUP $MAINPID

[Install]
WantedBy=multi-user.target
```

**Comment by miguelgrinberg** [comment]
I can't really say. The problem is likely that the CPU usage in your app grows exponentially as more users join. You should add a profiler to help you determine where the CPU is used. With a profiler report you'll be able to tell if the problem is in your application or somewhere else.

**Comment by mischkadb** [comment]
I have a dashboard which monitors endpoint reponse time. Their profiling does not work properly at the moment, but none of the endpoints that gets called "often" (>1k calls in a few hours) have response times over 100ms. The most requested ones much less - simple API calls with <5ms response time.

So I guess the socket connections cause the load problem. They are not profiled, only entrypoints are. Do you know whether the built-in werkzeug profiler you used in your mega tutorial will work? At first glance it also reports entrypoints only. Or is there another way to profile the socketio requests?

**Comment by miguelgrinberg** [comment]
The Werkzeug profiler will only profile each Flask endpoint individually, and it will not account for other things that occur in your server such as Socket.IO stuff, background threads, etc. Maybe you should try a standard Python profiling session for your entire server process. It will be based on the same Python profile used by Werkzeug, but it will be looking at the entire process for a period of time. See https://docs.python.org/3/library/profile.html.

**Comment by mischkadb** [comment]
I'll try that, thanks.

A short question about flask_socketio.emit(). I basically use emit('response', {data}, room=roomid, broadcast=False) and have multiple clients in the room. The behaviour that I expect is that only the client that invoked the call should receive that message, however it is broadcasted to all clients in the room. Is my understanding wrong?

**Comment by miguelgrinberg** [comment]
Yeah, I think you are mistaken in your understanding. You can broadcast or you can emit to a room, those are the only two options. If you broadcast everybody gets the message. If you emit to a room, all the people in the room get the message. If you want to send to a single client, then use the sid of that client as room name.

The `emit()` function has some context-based defaults that probably add to the confusion. If you are in a Socket.IO handler for an event, then the default if you don't specify broadcasting or a room name is to emit to the client that triggered the current event. If you specify the broadcast flag or a room name, then the default goes away and everything works as described in the above paragraph.

The `socketio.emit()` method is not subject to defaults, only the `emit()` function is.

**Comment by mischkadb** [comment]
I see. Thank you for clarification.

**Comment by mischkadb** [comment]
A quick follow up: I did not manage to profile the gunicorn workers globally, but I used a sampling profiler (py-spy). As you can see in the log below, the most CPU time is consumed by flask_socketio and socketio event handlers. Can I assume that the amount of socket connections and messages sent is the current bottleneck by this? 

I know it depends on the computations in the application, but I have ~30% CPU consumption with  around 400 socket connections on a 4 dedicated CPU droplet on DigitalOcean and it does certainly not scale linear at all. The amount of messages per second per user is not high, certainly well below 1. That droplet will not be able to handle 1000 concurrent connections. Are my scaling expectations too high?

~~~
   %Own   %Total  OwnTime  TotalTime  Function (filename:line)
  0.00%   5.00%   0.000s     9.83s   _trigger_event (socketio/server.py:708)
  0.00%   5.00%   0.010s     9.83s   _handler (flask_socketio/__init__.py:284)
  0.00%   5.00%   0.000s     9.32s   _handle_event_internal (socketio/server.py:679)
  0.00%   5.00%   0.020s     8.79s   _handle_event (flask_socketio/__init__.py:698)
  1.00%   1.00%    7.56s     7.56s   run (gevent/hub.py:582)
  0.00%   2.00%   0.000s     3.84s   __iter__ (sqlalchemy/orm/query.py:3403)
  0.00%   2.00%   0.010s     3.31s   _execute_on_connection (sqlalchemy/sql/elements.py:293)
  0.00%   2.00%   0.000s     3.31s   execute (sqlalchemy/engine/base.py:984)
  0.00%   1.00%   0.010s     3.27s   <lambda> (<string>:1)
  0.00%   2.00%   0.020s     3.17s   first (sqlalchemy/orm/query.py:3298)
  0.00%   1.00%   0.050s     3.14s   __getitem__ (sqlalchemy/orm/query.py:3076)
  0.00%   2.00%   0.010s     3.04s   _execute_and_instances (sqlalchemy/orm/query.py:3428)
  0.00%   2.00%   0.010s     2.72s   __getattr__ (werkzeug/local.py:347)
[...]
~~~

**Comment by miguelgrinberg** [comment]
The only entry that is taking significant time in your profiler summary is:

```
  1.00%   1.00%    7.56s     7.56s   run (gevent/hub.py:582)
```

I'm not sure you are interpreting this correctly. The "OwnTime" column shows how much time was spent on each function. The "TotalTime" shows the time spent on that function and any children functions that were invoked from it.

The gevent function that is slow is the main function, actually, the one that runs the event loop, which is odd, I don't understand why that happens, other than because the profile is confused by gevent's cooperative multitasking. Googling "gevent profiler" it appears there are a bunch of them out there, maybe you should try those instead.
