### ISSUE TITLE
CPU pinned at 100% after reconnect using message queues?!

### ISSUE THREAD

**Issue by collinkreutzer** [miguelgrinberg/Flask-SocketIO#1216]
Hello,
I've been trying to use flask-socketio's `message_queue` option recently in order to emit from different processes on a raspberry pi running some data acquisition and calculations in the background.
Everything seems to run perfectly fine on first connection to the server but after reloading the webpage (reconnecting a client), the server pins the cpu at 100% usage. I've narrowed down the problem to just passing the `message_queue` parameter (tried redis and rabbitMQ, no difference here). Omitting the parameter instantly resolves this problem (CPU usage ~0-1% after reconnect) but prevents me from emitting in other processes.
Ive attached a simple script to replicate this behavior and the corresponding log output.
The output of the logger just keeps spamming "pubsub message: disconnect" after i reconnect (reloading the javascript webapp) to the server.  Omitting the `message_queue='redis://'` resolves this problem.

Thanks in advance!

```
import eventlet
eventlet.monkey_patch()

from flask import Flask
from flask_socketio import SocketIO, emit

app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret'
socket = SocketIO(app, message_queue='redis://', logger=True, engineio_logger=True)

@socket.on('connect')
def client_connect():
    print("Connect")

@socket.on('disconnect')
def client_disconnect():
    print("Disconnect")

if __name__ == '__main__':
    socket.run(app)
```

Server initialized for eventlet.
202195e7a2914d9684325164374f0888: Sending packet OPEN data {'sid': '202195e7a2914d9684325164374f0888', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
redis backend initialized.
Connect
202195e7a2914d9684325164374f0888: Sending packet MESSAGE data 0
202195e7a2914d9684325164374f0888: Received request to upgrade to websocket
202195e7a2914d9684325164374f0888: Received packet MESSAGE data 2["stats"]
received event "stats" from 202195e7a2914d9684325164374f0888 [/]
Disconnect
pubsub message: disconnect
Disconnecting 202195e7a2914d9684325164374f0888 [/]
202195e7a2914d9684325164374f0888: Sending packet MESSAGE data 1
Disconnect
pubsub message: disconnect
pubsub message: disconnect
pubsub message: disconnect
pubsub message: disconnect
3c45e7820c1a497f8e3218f1344cf82d: Received packet MESSAGE data 2["stats"]
received event "stats" from 3c45e7820c1a497f8e3218f1344cf82d [/]
pubsub message: disconnect
3c45e7820c1a497f8e3218f1344cf82d: Received request to upgrade to websocket
pubsub message: disconnect
pubsub message: disconnect
pubsub message: disconnect
pubsub message: disconnect
pubsub message: disconnect
pubsub message: disconnect
pubsub message: disconnect
pubsub message: disconnect
pubsub message: disconnect
3c45e7820c1a497f8e3218f1344cf82d: Upgrade to websocket successful

**Comment by miguelgrinberg** [comment]
Please upgrade python-socketio. This was an unfortunate mistake I've made in release 4.5.0.
