### ISSUE TITLE
reject all connection with no namespace="/chat"

### ISSUE THREAD

**Issue by aktoak** [miguelgrinberg/Flask-SocketIO#1217]
I'm trying to allow a client only to connect to specific (dynamic) namespaces and reject the connection to other namespaces. 
for example allow all clients to connect to namespace="/chat"

```
@socketio.on('connect', namespace='/chat '
def connect_chat():  
      //authentication
       return True
```

but deny all other connections:
```
@socketio.on("connect")
def connect():
    raise ConnectionRefusedError('unauthorized!')
```

but it doesn't seem to work, and all connections fail even to the  /chat namespace.
any suggestions on how i can achieve that?

**Comment by miguelgrinberg** [comment]
There is no support for dynamic namespaces.

And all connections start by connecting on the default namespace, even if they intend to use another namespace, so that is why all connections fail for you.
