### ISSUE TITLE
Client connects to server - disconnected when emitting event

### ISSUE THREAD

**Issue by Tokusei** [miguelgrinberg/Flask-SocketIO#1218]
I am running the example server/client project. It is working fine

However, Running another client, Such as Firecamp, Unreal Engine etc to test socket connections results in unexpected behavior. I can connect to the server, and it responds to ping requests if listening, However if I send any other event such as 'message'  , 'my_event' it will close the connection with XHR Post error

![image](https://user-images.githubusercontent.com/4631534/77525237-ab4f4b00-6ec3-11ea-979a-0ca63396d5d2.png)

**Comment by miguelgrinberg** [comment]
You need to look at the server project to see what's the issue.

**Comment by Tokusei** [comment]
@miguelgrinberg where exactly do I look? I am running the socketio example project, which has a generic server setup and a html based client which loads the socketio client library remotely.

I am guessing the client needs some kind of handshake before it can emit events other than connect/ping, because it gets disconnected when it tries to emit any other kind of event, but I cant find any documentation about that, The HTML client works fine, But Firecamp and the UE SocketIO plugin both fail to connect

![image](https://user-images.githubusercontent.com/4631534/77605183-480afa80-6f4f-11ea-9bc7-c5149f0c9489.png)

**Comment by miguelgrinberg** [comment]
Your requests are all being responded with a 400 error.  You can enable logs on the server to have more information. Add `engineio_logger=True` and `logger=True` to your `SocketIO()` class to enable the additional logs.

**Comment by GilZm** [comment]
I went trough such issue few days ago... 2 things to pay attention on :
- ensure you've setup CORS accordingly (cors_allowed_origins)
- make sure to have the Flask+socketIO initialisation at the very beginig of your project.
I hope this would help.

**Comment by Tokusei** [comment]
Thanks for the replies. However,I enabled the logger and set CORS to accept all inbound connections, But it is still returning error 400 with limited debug information:

`Server initialized for eventlet.
5af6293818a84cd690d117ebb4555ede: Sending packet OPEN data {'sid': '5af6293818a84cd690d117ebb4555ede', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
5af6293818a84cd690d117ebb4555ede: Sending packet MESSAGE data 0
5af6293818a84cd690d117ebb4555ede: Received request to upgrade to websocket
5af6293818a84cd690d117ebb4555ede: Upgrade to websocket successful
127.0.0.1 - - [01/Apr/2020 11:51:01] code 400, message Bad request version ('ÚÚ\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x01\x93ÊÊ\x00\x00\x00\x17\x00\x00ÿ\x01\x00\x01\x00\x00')
127.0.0.1 - - [01/Apr/2020 11:51:01] "  ü|]f&n¾ñõÂ©Ê¼a¶ëRO]¡ÈÒ÷ü û­Ø%ÓOö.àïJ!IOöêGM3:+* 0,
»ø  ÚÚÀ+À/À,À0Ì©Ì¨ÀÀ  ÊÊ     ÿ   " 400 -
127.0.0.1 - - [01/Apr/2020 11:51:01] code 400, message Bad request version ('ág]\x9d|Îvu-\x16\x8c\x96\x00"ºº\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x00')
127.0.0.1 - - [01/Apr/2020 11:51:01] "  ü£ôuöÞpI3¨03ÎÉpÕFù²ÒüFL2]Þtf )§AÊÐ1ìì³]Éþ'Y ág] "ººÀ+À/À,À0Ì©Ì¨ÀÀ  
127.0.0.1 - - [01/Apr/2020 11:51:02] code 400, message Bad request version ('ºº\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x01\x93ÊÊ\x00\x00\x00\x17\x00\x00ÿ\x01\x00\x01\x00\x00')
127.0.0.1 - - [01/Apr/2020 11:51:02] "  ü3(ßå6K©Zh+}eS~Máåð!0áJ] \?ºÄF<ÏêÀ=n9¼^#uÙ"º»yf  ººÀ+À/À,À0Ì©Ì¨ÀÀ  ÊÊ     ÿ   " 400 -
127.0.0.1 - - [01/Apr/2020 11:51:02] code 400, message Bad request version ('iõD\x00"ÊÊ\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x00')
iõD "ÊÊÀ+À/À,À0Ì©Ì¨ÀÀ  ÁBø\æÊàÌvÙ»Vµý  øª<±|E1Å÷:±$;Öeeï
127.0.0.1 - - [01/Apr/2020 11:51:04] code 400, message Bad request version ('\x9a\x9a\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x01\x93êê\x00\x00\x00\x17\x00\x00ÿ\x01\x00\x01\x00\x00')
127.0.0.1 - - [01/Apr/2020 11:51:04] "  üÎàW´¨íw
                                                c
ÿ\}½Ú,1ß¬ HTst¦ ß$âÊrF}àêîáöÊ1fzj
                                 U¹o  À+À/À,À0Ì©Ì¨ÀÀ  êê     ÿ   " 400 -
127.0.0.1 - - [01/Apr/2020 11:51:04] code 400, message Bad request version ('/iÜ»ÁúRí$\x89Ç')
127.0.0.1 - - [01/Apr/2020 11:51:04] "  üìtü2¸Ó£æ¢h?~ÐþýÁ{L-6m\¥À L ÷ï×9/iÜ»ÁúRí$Ç" 400 -
127.0.0.1 - - [01/Apr/2020 11:51:07] code 400, message Bad request version ('zz\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x01\x93ÚÚ\x00\x00\x00\x17\x00\x00ÿ\x01\x00\x01\x00\x00')
127.0.0.1 - - [01/Apr/2020 11:51:07] "  ü°òaé­±e¹Ä~HñêãUº}'bAw²Õð"F §SO%Ü Ø$³x9Õp×sZæ=zõ:INêuF7  zzÀ+À/À,À0Ì©Ì¨ÀÀ  ÚÚ     ÿ   " 400 -
127.0.0.1 - - [01/Apr/2020 11:51:07] code 400, message Bad request version ('nXÕ/;\x95è\x15\xady)\x01ìü¾\x00"jj\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x00')
127.0.0.1 - - [01/Apr/2020 11:51:07] "  ü­á<ùq&Î*ö!÷¢°¹Ì 7IÔ-Ö)Q4ð ä¦´ØÛø§
                                                                          F÷Ó!ÉÔ¦      nXÕ/;è­y)ìü¾ "jjÀ+À/À,À0Ì©Ì¨ÀÀ  
5af6293818a84cd690d117ebb4555ede: Received packet PING data None
5af6293818a84cd690d117ebb4555ede: Sending packet PONG data None`

**Comment by GilZm** [comment]
the dump above make me think of a encryption issue... alike accessing non-TLS server with an https enabled client. Try ws:// instead of wss:// or use a reverse proxy to handle TLS (recommended).

**Comment by miguelgrinberg** [comment]
Who is printing the log lines that start with `code 400, message Bad request version`? That is not Flask-SocketIO.

**Comment by Tokusei** [comment]
@miguelgrinberg looks like the Dash application was printing to the log, I tried removing the Dash application and now it can successfully connect to the server and send/receive custom socket events. Turns out the problem wasnt with Flask-SocketIO but with Dash. 

If anyone knows how to correctly configure dash to be hosted on a flask server and send/receive socket events, I would appreciate it . I am using sample code from a forum post which integrates socket callbacks into dash, but the code may possibly be outdated, as it's refusing to connect now

**Comment by Tokusei** [comment]
Ok, I have no idea what is going on. I thought it was the flask app which was printing all the http errors into the log, But now I have completely removed it from the code, and it's still printing it. The code looks like this:

![image](https://user-images.githubusercontent.com/4631534/78336648-4d58ec80-75c2-11ea-903b-0a5e4e4b69a5.png)

it was working earlier, sockets could connect. Now errors again.
