### ISSUE TITLE
Detect which room a client disconnects from 

### ISSUE THREAD

**Issue by Ethiarpus** [miguelgrinberg/Flask-SocketIO#1219]
**Your question**
I am building an application in which a user can have multiple rooms connected at once, in different tabs but in the same namespace. I am using flask_login to manage the users.  
If a client closes a tab with a room in it, I want their name to disappear from the list of connected users.  
However, there is no way of telling which room a tab is in when it disconnects (as far as I'm aware).  
For example, if a user causes this server code to run in one tab:
`join_room('tab_1')`
and this code in another: 
`join_room('tab_2')`
Then when I listen to `socketio.on('disconnect', namespace='/test')`, I want to find out whether they closed tab 1 or 2, and inform the other members of that room.  
Is there any way to replicate the desired functionality (other than just polling the user)?

**Logs**
*N/A*

**Comment by miguelgrinberg** [comment]
You are assuming that this package knows that the same user has two or more tabs open. That is actually incorrect, from this package point of view each tab is a different client.

With that in mind, a client that disconnects is removed from any rooms it was added. Isn't this exactly what you want?

**Comment by Ethiarpus** [comment]
Well then, it appears that my error was in tying multiple clients to one `User` model, and using `current_user` in socketio functions.

I want to send a socketio message to clients in the room that tells them that the person has disconnected.
If I just do 
```python
@socketio.on('disconnect')
def disconnect_handler():
    emit('user_disconnected', {'id':current_user.id,'name':user.username}, namespace="/test")
```
then the user will disappear from all rooms.
Can you think of any functionality of socketio that would allow me to pop them user out of just one room upon disconnect? Or am I still not understanding?

**Comment by Ethiarpus** [comment]
Ok; I solved the problem by storing the `request.sid` as part of a `Connection` model which acts as an association object between `User` and `Room` models.

This way, we can say:
```python
@socketio.on('disconnect')
def disconnect_handler():
    con = Connection.query.get(request.sid)
    if not con:
        return
    room = con.room
    emit('user_disconnected', {'id':con.user.id,'name':con.user.username},room=con.room.id,namespace='/test')
    db.session.delete(con)
    db.session.commit()
```
Which disconnects them from the room and notifies others.
Thanks for your help!

**Comment by miguelgrinberg** [comment]
Glad you figured it out!
