### ISSUE TITLE
When will flask-socketio support quart?

### ISSUE THREAD

**Issue by pansila** [miguelgrinberg/Flask-SocketIO#1220]
I'm migrating from Flask to Quart which is an asyncio based web framework application after Flask's APIs, it's frustating that many familiar flask extentions are not working with Quart.

Since python-socketio supports async server mode, it should be easy to support it for Quart.

I found a similar request [here](https://github.com/miguelgrinberg/Flask-SocketIO/issues/532), probably to consider it again? Thanks a lot.

**Comment by miguelgrinberg** [comment]
I don't expect Flask-SocketIO will be ported to Quart because it is very difficult to maintain a code base that works both with and without asyncio. This is, after all, the reason why Quart was created as a complete rewrite of Flask.

You can use the python-socketio package with Quart.
