### ISSUE TITLE
Separating Flask-SocketIO and Flask routes to avoid wasting resources

### ISSUE THREAD

**Issue by TaaviE** [miguelgrinberg/Flask-SocketIO#1223]
I am wondering, what's the intended method/archidecture of separating Flask-SocketIO and Flask routes?

For example I have a medium-sized web application with a lot of code being run like this,
`python3 -m gunicorn.app.wsgiapp --bind 127.0.0.1:5000 --workers=3 wsgi:app`, it initializes all the routes and required code to serve the entire application. 

Let's assume now I want to add Flask-SocketIO to the project, how would one go and avoid initializing the entire rest of the web application (e.g. db connections, caches and so on) when one wants to create a Flask-SocketIO worker? 

Should I basically create a new project without any "cruft" to deal with websockets (and just share code between the two projects) or is there a nice architecture I'm missing here?

**Comment by miguelgrinberg** [comment]
If you want to run the Flask and Socket.IO projects separately, then just do that. Keep running Flask the same way, and then use the python-socketio package, which is framework, agnostic to create your Socket.IO service.

On the other side, if you prefer to have everything together, then add the Socket.IO to your current project, and run everything as one server.

Both approaches are valid, it depends on your preference.

**Comment by TaaviE** [comment]
Thanks for the reply, I think I'll go with a separate project for cleanliness.
