### ISSUE TITLE
Making calls to external API with only 1 gunicorn worker

### ISSUE THREAD

**Issue by jamesbaker1** [miguelgrinberg/Flask-SocketIO#1224]
When I run `gunicorn --worker-class eventlet -w 1 app:app`, there is only one worker so I can't make calls to external APIs? I am trying to save my chat to a Firebase database and whenever I try to do so my gunicorn has a WORKER TIMEOUT.

**Comment by jamesbaker1** [comment]
When I run `python app.py` with `socketio.run(app, debug=True)`, everything (including the firebase updates) work perfectly fine.

**Comment by miguelgrinberg** [comment]
Closing as a duplicate, this is the third reference I see from you on this issue.
