### ISSUE TITLE
Sending ArrayBuffer through Heroku - 503 (Service Unavailable)

### ISSUE THREAD

**Issue by luisArandas** [miguelgrinberg/Flask-SocketIO#1230]
Hello and good day, I am currently building some interaction between clients on a Flask instance with sockets (using this library) and I am now sending 2 events, one with an arrayBuffer of an audio file loaded from the system and the other one just with information about the buffer. I'm hosting this at heroku and locally everything works when I upload I get : 

GET <link>/socket.io/?EIO=3&transport=polling&t=N4xrr8y&sid=64a4e613942244058de4fc32a6e324b3 503 (Service Unavailable). 

I also tried running the app 

socketio.run(app, cors_allowed_origins="*") but doesn't work actually some gevent bugs (still working locally I don't think it's this) if needed can post the logs here also

Any help on this?
Thanks very much
Luis

**Comment by miguelgrinberg** [comment]
503 is not an error that is returned by the application, it is probably Heroku itself doing it when it finds that your app is not responding.

**Comment by luisArandas** [comment]
Thank you for the quick reply @miguelgrinberg 
It actually works when I use the first domaind <app>.herokuapp.com with https:// 
I think it's a CORS problem.
