### ISSUE TITLE
How to handle default namespace authentication in class based namespace Socketio?

### ISSUE THREAD

**Issue by raheel4839** [miguelgrinberg/Flask-SocketIO#1231]
Hi,
I am implementing class based namespace Connections in socketio.
i am initializing the server as :
 `socketio = SocketIO(app, async_mode=async_mode, message_queue='redis')`

i have implemented MyNamespace class and defined event handlers as follows:
```
class MyNamespace(Namespace):
	def on_my_event(self, message):
            # do somethnig
       def on_connect(self, message):
            # do somethnig

```
i was unable to invoke these handlers for default namespace. So, i run this line of code: `socketio.on_namespace(MyNamespace('/'))` to initialize default` namespace at the start of application.

I have two problems with this approach:

1. when on_connect is invoked for default namespace connection, i am unable to refuse unauthorized connections by `return False` or calling `disconnect()`.
2. when i am handling connect event of some custom namespace `on_connect` is invoked twice for both default and custom namespace.

Looking forward to your response.

Thanks

**Comment by miguelgrinberg** [comment]
For 1, can you provide a complete server example that shows the problem? The correct way to reject a client is by returning `False`. The `disconnect()` call cannot be used in the on_connect handler.

For 2, this is expected. The default namespace is always connected. If you use a custom namespace, then you will get the connect handler for the default namespace first, then the one for the custom namespace.

**Comment by raheel4839** [comment]
```
from flask_socketio import SocketIO, Namespace, emit, disconnect,ConnectionRefusedError
from flask import Flask, render_template, request, jsonify, send_file, flash, redirect, session, abort, g, url_for , Markup , make_response,current_app

app = Flask(__name__)
socketio = SocketIO(app,always_connect=False)
login=False
@app.route("/")
def index():
    global login
    login=False
    socketio.on_namespace(MyNamespace("/"))
    return "index"
@app.route("/home")
def home():
    global login
    login=True
    socketio.on_namespace(MyNamespace("/home"))
    return render_template("index.html")
class MyNamespace(Namespace):
    def on_my_event(self,message):
        print("\n my event \n")
        print(message['data'])

    def on_connect(self):
        print(self.namespace)
        print("\n my connect \n ")
        global login
        print(login)
        if login==False:
            raise ConnectionRefusedError("unauthorized")
        else:
            emit('heading', {'data': 'SOCKET'})
    def on_disconnect(self):
        print('Client disconnected', request.sid)
    def on_disconnect_request(self):
        print("disconnect request from ",request.sid)
        disconnect()
    
@socketio.on_error_default  # handles all namespaces without an explicit error handler
def default_error_handler(e):
    print(str(e))
    return False

if __name__ == '__main__':
    while(True):   
        try:
            print("running")
            socketio.run(app, host='0.0.0.0', port='4000',debug=True)
        except Exception as err:
            print(str(err))
            pass
```

here is the server side script.... this is the test app that i made to reproduce the problem i am facing...

For 1, i have tried returning the `False` and in the above raising `ConnectionRefusedError` but i think still it doesnt work for me.... how am i testing that?  answer is i manually send a call to `http://localhost:4000/socket.io/` which should be a connection request for default namespace and it still returns me the file with `sid` and other information instead of unauthorized error.

For 2, wouldn't this be wrong to allow connection to two namespaces(default and custom) when a request is for a custom namespace connection ? 

what i actually want to achieve is that i want to reject connection for default namespace... maybe there is a different approach to achieve this?

**Comment by miguelgrinberg** [comment]
> how am i testing that? answer is i manually send a call to http://localhost:4000/socket.io/

You should use a Socket.IO client, sending a plain HTTP request isn't really proving anything. The connection will be dropped by the server once it realizes that the client isn't speaking the proper Socket.IO protocol.

> For 2, wouldn't this be wrong to allow connection to two namespaces(default and custom) when a request is for a custom namespace connection ?

Why would it be wrong? The default namespace is special, it is not just another namespace. It represents the physical communication channel. Custom namespaces are multiplexed on the default namespace. You can't refuse a connection on default and allow it on a custom one, that makes no sense. In any case, I think you are giving namespaces too much importance, most applications don't need to care about that and just use the default namespace.

> what i actually want to achieve is that i want to reject connection for default namespace... maybe there is a different approach to achieve this?

Why do you want this? It goes against the design of the Socket.IO protocol.

**Comment by raheel4839** [comment]
> Why do you want this? It goes against the design of the Socket.IO protocol.
this is because we are running appscan on our application and it raises this issue of getting files from `https://localhost:4000/socket.io/` server endpoint...

**Comment by miguelgrinberg** [comment]
There is a single endpoint for Socket.IO regardless of what namespace you use, so shutting down this endpoint will render the whole Socket.IO server unusable.

This server does not offer any files for download. Your appscan might be confusing the connection response with a file.

**Comment by raheel4839** [comment]
> There is a single endpoint for Socket.IO regardless of what namespace you use, so shutting down this endpoint will render the whole Socket.IO server unusable.
> 
> This server does not offer any files for download. Your appscan might be confusing the connection response with a file.


yeah we dont want to shut down socketio endpoint.... 
i think so too that is the connection response... but when you send an http request to socketio endpoint it is downloaded as a file with the following information.
`ˇ0{"sid":"00f4ebd809d4458cbf841365a7fcb250","upgrades":["websocket"],"pingTimeout":60000,"pingInterval":25000}ˇ44`

Also appscan reports download of other files by the following url:
`https://localhost:port/socket.io/[filename]`
where `filename` is `socket.io.tar.gz , socket.io.arc ,socket.io.arj,socket.io.tar,socket.io.lzh,socket.io.rar` and a few more.

So, is there anything that we need to do or is this all normal?

**Comment by miguelgrinberg** [comment]
All your appscan is doing is creating an invalid connection that will be disposed shortly after. It thinks it's getting a file download, but it is just getting the Socket.IO connection response. So there is no actual problem, just that you are pointing a tool that knows nothing about Socket.IO at the Socket.IO endpoint.

Now that I finally understand why were you asking all these questions about namespaces I can think about ways to detect invalid clients and automatically reject them, but this is not going to change anything for you, it's just about being more efficient and kicking out invalid clients right away instead of assuming they might be valid and failing them a little later.

**Comment by raheel4839** [comment]
> All your appscan is doing is creating an invalid connection that will be disposed shortly after. It thinks it's getting a file download, but it is just getting the Socket.IO connection response. So there is no actual problem, just that you are pointing a tool that knows nothing about Socket.IO at the Socket.IO endpoint.
> 
> Now that I finally understand why were you asking all these questions about namespaces I can think about ways to detect invalid clients and automatically reject them, but this is not going to change anything for you, it's just about being more efficient and kicking out invalid clients right away instead of assuming they might be valid and failing them a little later.

Thanks Miguel for all the clarification... and yes that would be great if you can think of a way to make this process more efficient.

This thing i mentioned will be nullified if you can find a way to reject clients not coming through the right channel like HTTP request from browser.

**Comment by miguelgrinberg** [comment]
Current releases of python-engineio reject clients that do not indicate a specific version of the Socket.IO protocol to use.
