### ISSUE TITLE
Flask-socketIO audio streaming not emiting the signals

### ISSUE THREAD

**Issue by sherwin7** [miguelgrinberg/Flask-SocketIO#1232]
**Flask-socketIO with gunicorn workers**
I have created a streaming application where the MEAN stack based web-application will be sending a continuous audio stream to the API written in flask-socketIO.

if I use gunicorn for deployment with one worker (only master) it is working fine where the flask-socketIO API is perfectly emitting back to the web-application.

if i use gunicorn with more number of worker the audio stream is continuously getting shifted to different worker and if a child or slave worker processes or worker emits the signal it is not going to the web-application since it is looking at the master process port in (my case 3010)

**Expected behavior**
audio stream from web-app -> flask api port (master - 3010) -> free worker process -> flask api port (master - 3010) -> web-app 

**Current behavior**
audio stream from web-app -> flask api port (master - 3010) -> free worker process -> goes some where...

**Comment by miguelgrinberg** [comment]
You cannot use more than one worker with Gunicorn. You can run multiple Gunicorn instances, each with one worker and a load balancer on front. See the documentation to learn about the supported deployment configurations.

**Comment by sherwin7** [comment]
You can run multiple Gunicorn instances, each with one worker and a load balancer on front

this is what i exactly want one gunicorn instance for one user my doubt is how will be ports get assigned to the worked and how signals gets emits through which port?

**Comment by miguelgrinberg** [comment]
@sherwin7 the load balancer that you use does this, for example nginx. Have you read the documentation as I suggested?

**Comment by sherwin7** [comment]
Ya i got it so with nginx which has a load balancer will solver the problem thanks @miguelgrinberg for the tip it helped a lot
