### ISSUE TITLE
Flask-SocketIO emit() from a function enqued in rq

### ISSUE THREAD

**Issue by kirilgeorgiev82** [miguelgrinberg/Flask-SocketIO#1234]
Dear Miguel,

First, thank you for all the great articles and the fantastic book on Flask web development you have written. Could I please ask about Flask-SocketIO and more specifically - about emit()-ing from a function which is enqueued as a background task? The situation is:

@some_bp.route('/some-route', methods=[...]):
def some_route():
      .......
      current_user.launch_task('my_function_to_enqueue', *args)
      ........

It seems that when I am trying to emit() from within my_function_to_enqueue(), the message does not reach the client. I read a similar question about celery where you say background tasks run in a different process so such communication is not possible. Is this also true for rq (I did my fair share of reading but I was not able to find enough info about what happens under the hood in rq, and subsequently - whether I am using Flask-SocketIO incorrectly, or this is just not possible). 

Generally, what I am trying to do is enqueue a large number of repetitive tasks (e.g. OCR processing of documents) to multiple workers and get live feedback when some of those background jobs are done.

Thank you very much in advance! Stay safe and keep being so great :)

Kind regards,
Kiril

**Comment by miguelgrinberg** [comment]
Emitting from a separate process can be done, but it requires additional set up. See [the documentation](https://flask-socketio.readthedocs.io/en/latest/#emitting-from-an-external-process).

**Comment by kirilgeorgiev82** [comment]
Thank you very much, Miguel!
