### ISSUE TITLE
Invalid or unexpected token in web browser

### ISSUE THREAD

**Issue by tanhuynhhoang** [miguelgrinberg/Flask-SocketIO#1236]
Thanks for your app its help me so much. i have problem that when i use "<script src="//cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.js" integrity="sha256-yr4fRk/GU1ehYJPAs8P4JlTgu0Hdsp4ZKrx8bDEDC3I="crossorigin="anonymous"></script>"
my chrome run socketio, but i changed to <script src="/socket.io/socket.io.js"> </script>
it's caused error that "Uncaught SyntaxError: Invalid or unexpected token"
I google it, and some answer that it maybe wrong path, so please give me advice how to configure
i change src because my web can run on PC, android but not in iphone saphari, and some one said i must configure use local socketio not from cdns.xxx.xxx
Please help me, thanks

**Comment by miguelgrinberg** [comment]
Not sure this is an issue with an invalid path, but in any case, is that path that you are using correct?

The browser console will give you a location for the error, it may be somewhere else in the page, not on this line.

**Comment by tanhuynhhoang** [comment]
thanks miguelgrinberg !
i found solution. it maybe old socketio version. i change newest version and it work.
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.3.0/socket.io.js" crossorigin="anonymous"></script>
that link fixed error in safari.
Thanks
