### ISSUE TITLE
engineio.packet.Packet object is not a byte

### ISSUE THREAD

**Issue by umityayla** [miguelgrinberg/Flask-SocketIO#1238]
I've started receiving errors like these over my Flask-SocketIO server. Any idea how can I fix them?

```
TypeError: <engineio.packet.Packet object at 0x7f65cf2c5e20> is not a byte,
[2020-04-07 14:03:07 +0000] [12] [ERROR] Error handling request,
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base_async.py", line 114, in handle_request,
    resp.write(item),
  File "/usr/local/lib/python3.8/site-packages/gunicorn/http/wsgi.py", line 328, in write,
    raise TypeError('%r is not a byte' % arg),
TypeError: <engineio.packet.Packet object at 0x7f65cecce0d0> is not a byte
```

**Comment by miguelgrinberg** [comment]
How do I reproduce this? Please provide example code, requirements.txt, and anything else I need to see this error.

**Comment by umityayla** [comment]
The clients are Unity based mobile game applications. From android/iOS. I'm not sure but I probably haven't received this error through PC. The problem is I can't see this over at the test environment. I'm not sure how much I can provide but here are stuff I can provide;

`Flask==1.1.1
Flask-Cors==3.0.8
Flask-PyMongo==2.2.0
pymongo==3.10.0
Flask-SocketIO==4.2.1
redis==3.3.8
eventlet==0.25.1
gunicorn==20.0.2
PyJWT==1.7.1`

Because I can't reproduce the issue either, I don't know what can I provide else.

**Comment by miguelgrinberg** [comment]
I was afraid this was going to be your answer. Do you recall upgrade any of your requirements or other part of your deployment recently?

**Comment by umityayla** [comment]
There were problems with socket connections on the client side it wasn't very stable (I'm not sure if it was poor implementation or old library). So the client side's library changed to [this](https://assetstore.unity.com/packages/tools/network/best-http-2-155981) plugin. (By the way when the old plugin was in use, there were error logs like #179 issue over here) But other than that on the server side, I believe nothing major/nothing under the hood has changed.

**Comment by umityayla** [comment]
Is there anything I can do to reproduce this? @miguelgrinberg

**Comment by miguelgrinberg** [comment]
Unfortunately I do not know how to reproduce, the error is very terse. This has been reported once before (https://github.com/miguelgrinberg/python-engineio/issues/72) but that person also was unable to provide information sufficient for me to figure out what was going on.

**Comment by umityayla** [comment]
Updates on the bug; I started to hardcode the bug, I believe it occurs on "connection" phase, will post further if I manage to find out more.

**Comment by umityayla** [comment]
It seems like I can encode it successfully if the payload from engine.io hasn't been encoded yet on the wsgi.py. I'm not sure what causes the encoding problem, but would it be a big mistake to do something like this;

```
(...)
if arg not byte:
    arg = arg.encode(arg)
(...)
``` @miguelgrinberg

**Comment by miguelgrinberg** [comment]
What you are asking is to change gunicorn to do this, which is wrong. As I said before, I just need to know how to reproduce this issue and then it is likely easy to fix. But inspecting the code I could not find any instance in which a `Packet` object is returned.

**Comment by umityayla** [comment]
Well, you are right, It's a bad practice to change gunicorn. But as you know this is a **terse** error. And we have no idea how can we reproduce this issue. But obviously, we have a problem here and I'm asking if changing that for gunicorn would be a huge problem. I'm not proposing to change it to gunicorn or anything, I'm asking would I have big problems if I were to change the gunicorn to encode `Packet` to `bytes`?

**Comment by miguelgrinberg** [comment]
It's impossible for me know. Is the information in that `Packet` object correct? How can I know that?

**Comment by umityayla** [comment]
I believe problem happens on connection/upgrade stage.  When I look into it like I wrote earlier; the packet seems to be an upgrade packet. `{'sid': '5422ee88adf040d789525b1c4b10cf4c', 'upgrades': [], 'pingTimeout': 60000, 'pingInterval': 5000}` And this seems correct to me. Isn't it?

**Comment by miguelgrinberg** [comment]
As I said, I do not know. You claim that this is an upgrade packet, then you show me a connection packet. I get that it seems correct to you. I have no way to know if this packet is the correct packet for that client at that time.

I can't tell you that your proposed solution is good. It is actually quite bad as I mentioned before. The only way to convince yourself that it works is by testing it.
