### ISSUE TITLE
Google live streaming transcribe doesn't work when monkey patching eventlet. 

### ISSUE THREAD

**Issue by moinuddinNascenia** [miguelgrinberg/Flask-SocketIO#1239]
**Two scenario and a question, hope you can guide me on the right way**
Normal socket functionality works, Like receive text from browser and emit to the browser. But when trying to implement Google STT using Flask-SocketIO facing problems. 

1. Google StreamingRecognizeRequest api (to convert voice into text) works when eventlet monkey_patch is **not applied**. But emitting from another thread doesn't work. 
`socketio.emit('transcript', data)` 
Browser don't receive anything. No error log on server side. 

2. When monkey patching is applied at the top of the file, then **StreamingRecognizeRequest** doesn't work. it don't provides any error, its just stuck. Don't listen any further event.  I'm doing this recognition in another thread. 

```
import eventlet
eventlet.monkey_patch()

from flask import Flask
from flask_socketio import SocketIO
from flask_socketio import send, emit
import threading

from google.cloud import speech
from google.cloud.speech import enums
from google.cloud.speech import types
```
```
app = Flask(__name__)
app.config['SECRET_KEY'] = 'topSecretKey'
socketio = SocketIO(app, cors_allowed_origins='http://localhost:63342', async_mode='eventlet')
```
```
def start():
        """Start up streaming speech call"""
        threading.Thread(name='recognizeThread', target=process).start()
```
```
@socketio.on('connect')
def connect():
    print('Server Connection created: ')
    return 'socket connected'

@socketio.on('start_recognition')
def recognitionStart():
    print('start recognition process')
    start()
    .....

@socketio.on('stop_recognition')
def recognitionStop():
    print('stop recognition process')
    ....

@socketio.on('audio_stream')
def handleStream(stream):
    print('receiving voice data')
    ....
```
In the process function google transcribe streaming speech implemented. In the browser, after few seconds **stop_recognition** emit fired. But server side didn't received it. The cursor keeps blinking. 

```
if __name__ == '__main__':
    socketio.run(app, host=HOST, port=PORT, debug=True)
```
3. Can socket-io listen and emit at the same time? Like socket will continuously receive voice data, and in the mean time emit the converted text. 

**Logs when monkey patch is applied**
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 103-802-482
(2159) wsgi starting up on http://127.0.0.1:5001
(2159) accepted ('127.0.0.1', 55816)
Server Connection created: 
127.0.0.1 - - [08/Apr/2020 17:00:22] "GET /socket.io/?EIO=3&transport=polling&t=N5PShON HTTP/1.1" 200 402 0.001812
(2159) accepted ('127.0.0.1', 55817)
127.0.0.1 - - [08/Apr/2020 17:00:22] "GET /socket.io/?EIO=3&transport=polling&t=N5PShP0&sid=a4a503fe273546f882894433d783acb5 HTTP/1.1" 200 236 0.005951
start recognition process
receiving voice data
**Blinking cursor, nothing happens**

**Comment by miguelgrinberg** [comment]
Python packages for Google APIs are sadly incompatible with eventlet and gevent. It has been requested that they add support for greenlet based frameworks, but so far they have not shown interest in doing so. Sadly using these packages in an eventlet or gevent application is not possible at this time.

**Comment by Meshi28** [comment]
Saw this issue was closed and without a potential resolution. I've come across the same issue and found that many others have too so I wanted to add this to help others. Sorry if this isn't the place for it

Using the library `httplib2shim` I am able to continue to use eventlet and contact googleapis.com. https://pypi.org/project/httplib2shim/

As in their example, just before creating the credentials, import the library and run `patch()`

`import httplib2shim`
`httplib2shim.patch()`

`credentials = GoogleCredentials.get_application_default()`

`service = build('compute', 'v1', credentials=credentials)`

**Comment by dragon18456** [comment]
Um, know that this has been a while, but could you elaborate about how import httplib2shim solves the problem?

I have been trying this several different ways:
1. `socketio = SocketIO(app, cors_allowed_origins="*", async_handlers=True, async_mode='eventlet')
     yourThread = threading.Thread(target=recognize, args=[stream]).start()
     socketio.emit("results", transcript)`
    With this current form, the Google ASR works perfectly fine. However, the final emit of the results in the translation 
    loop never actually reach the client. I suspected that this was a threading vs eventlet thing.
2. Replacing the thread with `socketio.start_background_task(target=lambda: recognize(stream))`
    The issue here is that the google api doesn't work with eventlet, and the patching didn't work in this case. The flask 
    backend just hangs for a really long time
    I even tried eventlet itself with `eventlet.spawn(lambda: recognize(stream))` and it still has the same hanging  
    behavior.
I tried all of this with the httplib2shim patching code from their pypi examples, but none of them work. Also, do any of the commits from here: https://github.com/Akrog/grpc/commit/3023219df9ef575e77cd190c2223f38eb301c974 have anything to do with this issue?

**Comment by SevaSk** [comment]
You can still use Google APIs with gevent if you use the experimental GRPC gevent support.
I got mine to with adding these lines 

import grpc.experimental.gevent
grpc.experimental.gevent.init_gevent()

after gevent monkey patching.

https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/experimental/gevent.py
