### ISSUE TITLE
Freeze when using debug options

### ISSUE THREAD

**Issue by gabrielelanaro** [miguelgrinberg/Flask-SocketIO#124]
I'm pip-installed flask-socketio and I've been running the file example/app.py.
If debug is enabled, the app won't start and the page is loading indefinitely. It happens only when debug is enabled. Is it possible to solve this problem?

Versions: 
Flask 0.10.1
gevent 1.0.1
gevent-socketio 0.3.6

It looks like it hangs reading events. An hanging python process is also left (blocking the 5000 port).

/site-packages/watchdog/observers/inotify_buffer.py", line 59, in run
    inotify_events = self._inotify.read_events()

**Comment by miguelgrinberg** [comment]
You seem to be using gunicorn, correct?. Are you starting it as shown in the documentation?

**Comment by ktoh** [comment]
Gabriel, does it work without watchdog? 

Without a traceback it's hard to guess what's happening.

**Comment by gabrielelanaro** [comment]
I used the requirements.txt file in the example directory and that solved the bug. Now I'm trying to reproduce it again but I'm not able to.

Weirdly enough, I wasn't using gevent to run the app which brings the question: which library was using it? 

I guess we can close the issue I'll reopen if I find out the weirdness.
