### ISSUE TITLE
Doubt about workers on nginx and gunicorn as limited by flask-socketio.

### ISSUE THREAD

**Issue by Roberto09** [miguelgrinberg/Flask-SocketIO#1241]
**Question:**
Hi @miguelgrinberg! I've been recently looking at the work you've done with Python and its impressive. Also, I’m new to doing backend with Python and I had a doubt about using this library in production.

I was looking at how gunicorn combined with eventlet (as used in the examples in the documentation) will allow a **single server instance** to dispatch various (io-bound) requests simultaneously at an entry point from socketio in our program. However in the documentation you mentioned that:

 “Due to the limited load balancing algorithm used by gunicorn, it is not possible to use more than one worker process when using this web server. “

Also in the documentation, in the “Using Multiple Workers” part you mention that:

“Flask-SocketIO supports multiple workers behind a load balancer starting with release 2.0. Deploying multiple workers gives applications that use Flask-SocketIO the ability to spread the client connections among multiple processes and hosts, and in this way scale to support very large numbers of concurrent clients.”

**So my question is**, is the only way, that's mentioned in the documentation, of supporting multiple workers with flask-socketio is to use nginx with multiple server instances at different ports **that will act as such workers**?

    “upstream socketio_nodes {
        ip_hash;

        server 127.0.0.1:5000;
        server 127.0.0.1:5001;
        server 127.0.0.1:5002;
        # to scale the app, just add more nodes here!
    }”

If so, are this multiple server instances in nginx sort of equivalent to synchronous workers in gunicorn or what would be the closest equivalent in gunicorn terms?

Thanks in advance.

**Comment by miguelgrinberg** [comment]
Each worker is a gunicorn process with 1 eventlet worker. The same gunicorn configuration that you are using for a single instance. You have to start a bunch of those, each on its own port, and add nginx in front to do the load balancing.

**Comment by Roberto09** [comment]
Ohh okay, and such approach that yo mention to handle multiple workers (that works properly with flask-socketio) is the closest we can get to the approach of having a single server instance with multiple workers in gunicorn (which is not possible in this case as mentioned in the documentation)?

**Comment by miguelgrinberg** [comment]
Yes. Gunicorn is unlikely to ever support load balancing options such as sticky sessions, so I don't expect you'll be able to use it with multiple workers any time soon. This is the closest thing that works.

**Comment by Roberto09** [comment]
okay, thanks!
