### ISSUE TITLE
example doesn't work

### ISSUE THREAD

**Issue by mhechthz** [miguelgrinberg/Flask-SocketIO#1242]
Hi,

I know that this is a quite unspecific problem, but I try to run the example on an ubuntu system and all I get is 'cannot connect to server'. I run the app:
```
#!/usr/bin/env python3
from threading import Lock
from flask import Flask, render_template, session, request, \
    copy_current_request_context
from flask_socketio import SocketIO, emit, join_room, leave_room, \
    close_room, rooms, disconnect

# Set this variable to "threading", "eventlet" or "gevent" to test the
# different async modes, or leave it set to None for the application to choose
# the best option based on installed packages.
async_mode = None

app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app, async_mode=async_mode)
thread = None
thread_lock = Lock()


def background_thread():
    """Example of how to send server generated events to clients."""
    count = 0
    while True:
        socketio.sleep(10)
        count += 1
        socketio.emit('my_response',
                      {'data': 'Server generated event', 'count': count},
                      namespace='/test')


@app.route('/')
def index():
    return render_template('index.html', async_mode=socketio.async_mode)
...

if __name__ == '__main__':
    print("start server ...")
    socketio.run(app, port=10001, host='myhost',debug=True)
```
The index.html is in directory templates. I modified it slightly because I'm behind a proxy:
```
<!DOCTYPE HTML>
<html>
<head>
    <title>Flask-SocketIO Test</title>
    <script src="http://myhost:8081/oi/javascript/jquery-1.12.4.js""></script>
    <script src="http://myhost:8081/oi/javascript/socket.io-2.2.0.js"></script>
    <script type="text/javascript" charset="utf-8">
        $(document).ready(function() {
            // Use a "/test" namespace.
...
```
The js files are definitely reachable. The port is definitely open and hostname is ok. I tested it with a flask application. After starting the app.py there is a port open at 10001 - I checked this with `nc -zvw3 myhost 10001`.

connecting in browser to `http://myhost:10001` results in 'cannot connect to server'. There is no output from the running program. 

I don't know how to activate additional logging. But it is the basic example. What is my problem?

**Comment by miguelgrinberg** [comment]
You seem to be using two ports, 8081 and 1001. Why is that?

**Comment by mhechthz** [comment]
The files are served via nginx server. But nginx shouldn't confluct with socker.io.

**Comment by miguelgrinberg** [comment]
It's really difficult for me to help. I'm pretty sure some part of your set up is wrong, but the only way to find out where is the problem is to debug this, and you are the only one who have access to the system and can actually do this.

For example, how was "myhost" defined? Normally you put an IP address in Flask's host argument, not a hostname. Use `0.0.0.0` instead of `myhost` and see if that helps.

**Comment by mhechthz** [comment]
Ok, w are a step further. Both approaches show the index.html at least: `0.0.0.0` and my IP.

Unfortunately now I get with any button (e.g.` echo`):
```
Method Not Allowed
The method is not allowed for the requested URL.
```
Furthermore, index.html shows:
```
Async mode is: gevent
Average ping/pong latency: ms
```
i.e. no value for latency.
The app in debug mode doesn't show any helpful message on the terminal.

**Comment by miguelgrinberg** [comment]
You are having the most basic types of Flask errors here. This is definitely your application.

> Method Not Allowed

What URL is giving you this? Once you know that, review how you defined your view function for this URL, and fix it to use the HTTP method that you expect.

**Comment by mhechthz** [comment]
Hmmm ... it's YOUR example from github in the example subdirectory `app.py`.

**Comment by miguelgrinberg** [comment]
Please show me the output from the Flask application.

**Comment by mhechthz** [comment]
... I  am unworthy ... so after solving the IP address problem (which is in my opinion really a problem since I don't want to stock to fixed IP addresses)  you lead me to the  only position I changed the code. There was a typo in the jquery inclusion which lead to the strange error.

So finally your exampe works (which is obviously no surprise for you). Maybe the IP address vs. hostname issue can be _optimized_ in a future version.

Thank you for your help.

**Comment by miguelgrinberg** [comment]
Great. Side note, '0.0.0.0' is not a fixed IP address. It's an alias for "all" your IP addresses. It actually allows you to not have to specify an IP address, which is what you want.
