### ISSUE TITLE
Unit Testing Flask Socket IO disconnection issue

### ISSUE THREAD

**Issue by RobustProgram** [miguelgrinberg/Flask-SocketIO#1243]
Hey miguel, in my current project I have pytest test cases set up to test my server. The tests are set up so certain test cases will have two connections to mimic two people performing actions. However, I encountered something interesting when attempting to disconnect the clients.

At the start of my test, I will create two test clients using the following code,
```python
create_client = SocketIOTestClient(app, socketio, flask_test_client=FLASK_TEST_CLIENT)
join_client = SocketIOTestClient(app, socketio, flask_test_client=FLASK_TEST_CLIENT)
```

This works great as both clients have different `request.sid`. However, when I attempt to manually disconnect one of the client it will cause the second client to also disconnect.
```python
create_client.disconnect()
join_client.disconnect()
```
and as such, I will receive the following error `RuntimeError: not connected` for `join_client`.

I just want to know if this is the intended behaviour and if so, how do I correctly simulate a client disconnecting in my test cases.

Thank you.

**Comment by miguelgrinberg** [comment]
Hmm. Not sure what the problem is. I just improved one of my unit tests to start two test clients, and that seems to work just fine.

https://github.com/miguelgrinberg/Flask-SocketIO/blob/master/test_socketio.py#L260-L275

Any chance there is something else going on on your tests that causes this?

**Comment by RobustProgram** [comment]
I went through my code again and realised that I was already testing disconnect using `join_client`. That was completely my bad, I apologise for the inconvenience.
