### ISSUE TITLE
App stucked at switching protocols (101)

### ISSUE THREAD

**Issue by sidbelbase** [miguelgrinberg/Flask-SocketIO#1244]
Hey Miguel,

So, I see my app getting stuck at `Status Code: 101` finally after deploying on Ubuntu 18.04 server on Amazon EC2 Instance. I have used `gevent / gevent-websocket` and running through the latest version of `gunicorn` as shown below:
 `gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 app:app`

 **Locally,** everything works fine when running with the same configuration.

 For deploying this same app into server I configured nginx like you have shown in _readthedocs for flask-socketio_ and my nginx configuration looks like this:

```
upstream local {
    ip_hash;
    server 127.0.0.1:8000;
}

server {
    listen 80;
    server_name example.com;
    return 301 https://example.com$request_uri;
}

server {
    listen 443 ssl http2;
    ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    server_name example.com;

    location /socket.io {
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass http://local/socket.io;
    }

    location / {
        proxy_pass http://local;
        include /etc/nginx/proxy_params;
        proxy_redirect off;
    }
}
```
And the main `chat.js` socket controller variable looks like this( thought this might need here ):
```javascript
let socket = io.connect( location.protocol +'//' + document.domain + ':' + location.port + '/chatwith', {transports:["websocket"]});
``` 
##### What I have also tried:
```python
from gevent import monkey
monkey.patch_all()
```
Once again, this all worked in my machine locally and there were no 101 status and no ws output in `ws` column inside Networks tab when running locally and  socket chat was working perfectly fine.

But, after deploying this same app on aws I see network tab getting `GET 101 SWITCHING PROTOCOLS` on `ws` area & no chat feature doesn't work at all. It's been 2 days and I was trying to fix with old relevant issues. But thought posting here might make me feel less miserable. What I'm missing? What did I do wrong? 

Here is the error I was talking about:

![image](https://user-images.githubusercontent.com/23023761/79052487-5f700600-7c26-11ea-8f02-7c7547ed60bf.png)

Let me know if you need more resources to look into. Thanks!

**Comment by miguelgrinberg** [comment]
The 101 status code is actually indicating that the HTTP connection was successfully upgraded to websocket, that's expected. You need to look for errors either in the client or server sides. Note that both sides have additional logging that you can enable to see more information about the Socket.IO connection (you ignored the instructions in the bug template and did not do any of that, which is actually necessary to troubleshoot pretty much any issue).

**Comment by sidbelbase** [comment]
> Note that both sides have additional logging that you can enable to see more information about the Socket.IO connection (you ignored the instructions in the bug template and did not do any of that, which is actually necessary to troubleshoot pretty much any issue).

So, I enabled logging both from the client and server-side using:

**Client Side:**
`localStorage = "*"`

**Server Side**
`socketio = SocketIO(logger=True, engineio_logger=True)`

Client-side didn't have better bugs to address so I went to server-side and have this one problem:
`https://example.com is not an accepted origin`

Searched for the similar issues inside 'Flask-SocketIO' and luckily came under one
`socketio = SocketIO(cors_allowed_origins='https://example.com')`

Applying this solution helped me to less worry about coming future bugs, till that date see you, Miguel.
You can close this issue now. Stay safe though.
