### ISSUE TITLE
webapp , socket lost the connection after seconds. "Client is gone, closing socket"

### ISSUE THREAD

**Issue by YkRic** [miguelgrinberg/Flask-SocketIO#1246]
**Your question**
Hello, 
I am a ready webapp with flask,  and try integrate with flaskwebsocket . The socket only emit the messge after the client is logged. After someone seconds emit a follow message:  Client is gone, closing socket. 
The code is call  from a views inside the folder  app , atached in the image . 

**Logs**
emitting event "newnumber" to all [/test]
2ed331a9e625493ba2be0f07cc690ab7: Sending packet MESSAGE data 2/test,["newnumber",{"number":0,"recording":-1,"time":0,"countingStart":false,"countingStop":false}]
emitting event "newnumber" to all [/test]
2ed331a9e625493ba2be0f07cc690ab7: Sending packet MESSAGE data 2/test,["newnumber",{"number":0,"recording":-1,"time":0,"countingStart":false,"countingStop":false}]
emitting event "newnumber" to all [/test]
2ed331a9e625493ba2be0f07cc690ab7: Sending packet MESSAGE data 2/test,["newnumber",{"number":0,"recording":-1,"time":0,"countingStart":false,"countingStop":false}]
emitting event "newnumber" to all [/test]
2ed331a9e625493ba2be0f07cc690ab7: Sending packet MESSAGE data 2/test,["newnumber",{"number":0,"recording":-1,"time":0,"countingStart":false,"countingStop":false}]
emitting event "newnumber" to all [/test]
2ed331a9e625493ba2be0f07cc690ab7: Client is gone, closing socket

**My code is:** 
```python
def capture():
with tf.Session() as sess:
        model_cfg, model_outputs = posenet.model.load_model(model, sess)
        output_stride = model_cfg['output_stride']

        if file is not None:
            cap = cv2.VideoCapture(file)
        else:
            cap = cv2.VideoCapture(0)
        
        cap.set(3, cam_width)
        cap.set(4, cam_height)     
        
        while True:
                        
            input_image, display_image, output_scale = posenet.utils.read_cap(
                cap, scale_factor=scale_factor, output_stride=output_stride)

            heatmaps_result, offsets_result, displacement_fwd_result, displacement_bwd_result = sess.run(
                model_outputs,
                feed_dict={'image:0': input_image}
            )

            pose_scores, keypoint_scores, keypoint_coords = posenet.decode_multi.decode_multiple_poses(
                heatmaps_result.squeeze(axis=0),
                offsets_result.squeeze(axis=0),
                displacement_fwd_result.squeeze(axis=0),
                displacement_bwd_result.squeeze(axis=0),
                output_stride=output_stride,
                max_pose_detections=10,
                min_pose_score=0.15)

            keypoint_coords *= output_scale

                
            overlay_image = posenet.utils.draw_skel_and_kp(
                display_image, pose_scores, keypoint_scores, keypoint_coords,
                min_pose_score=0.15, min_part_score=0.1)

                
            socketio.emit('newnumber', {'number': number, 'recording': init_recoder,'time': t , 'countingStart' : countingTimeStart, 'countingStop': countingTimeStop}, namespace='/test')
          
            socketio.sleep(0)
```

My project: 
![project](https://user-images.githubusercontent.com/24683549/79079556-4038ad80-7ce6-11ea-8f22-b693f80dffd1.png)

![createapp](https://user-images.githubusercontent.com/24683549/79079664-ade4d980-7ce6-11ea-84e3-10b284b360e5.png)

Thanks in advance!

**Comment by miguelgrinberg** [comment]
Are you using eventlet or gevent with this server? The functions that you are using to get data from your camera are blocking, very likely are incompatible with these frameworks.

**Comment by YkRic** [comment]
Hello Miguel thanks for your answer.
No , I am'not using eventlet or gevent. 
I tested the websocket and the camera with a small application stored in a single script file, before   of refactoring my project,  the camera and websocket work perfectly.

**Comment by miguelgrinberg** [comment]
Sorry, but how do you get websocket to work? That's inconsistent with your previous reply. Only eventlet and gevent provide websocket.
