### ISSUE TITLE
ping_timeout units

### ISSUE THREAD

**Issue by lelandpaul** [miguelgrinberg/Flask-SocketIO#1247]
The current Flask-SocketIO docs state:

> **ping_timeout** — The time _in seconds_ that the client waits for the server to respond before disconnecting. The default is 60 seconds.

The current [SocketIO server docs](https://socket.io/docs/server-api/#new-Server-httpServer-options) state:

> **pingTimeout** — how many _ms_ without a pong packet to consider the connection closed

Is it true that Flask-SocketIO expects the time in seconds? With `ping_timeout = 18000` (in my Flask-SocketIO configuration) my project seemed to be timing out on the order of 18 seconds (rather than 5 hours), so I suspect not, but perhaps my timeout is caused by a different issue.

**Comment by miguelgrinberg** [comment]
@lelandpaul you are looking at two completely independent projects. The Python server and client both take the timeouts in seconds. The JS server and client use milliseconds.

**Comment by lelandpaul** [comment]
Ok — thanks for the clarification!
