### ISSUE TITLE
Issue with emit when moving from internal to external message queue

### ISSUE THREAD

**Issue by webbpinner** [miguelgrinberg/Flask-SocketIO#1249]
I'm trying to get the external messaging queue working so I can eventually use Celery to send messages to clients via flask-socketio.  At this point I can send messages to the client via websockets using the internal queue but so far I've been unable to get the same functionality work via an external messaging queue (rabbitmq).

The flask-socketIO logging shows the emit being reached in the code in both cases but the client never receives the data when the external message queue is in use.

I have confirmed that RabbitMQ is running and I can see the messages entering the queue so I think that part is atleast working.

I assume I'm missing something pretty fundamental with this.  Thank in advance for your assistance and for your great tutorials and YT videos.

```
# ./app.py
...
from server import create_app, socketio
...
app = create_app()
if __name__ == "__main__":
    socketio.run(app, port=5000, debug=True)
```

```
# ./server/__init__.py
import eventlet
eventlet.monkey_patch()

from flask import Flask
from flask_socketio import SocketIO
from .config import Config
from .resources import blueprint as api
...

socketio = SocketIO(cors_allowed_origins='*', message_queue='amqp://', channel='rt_updates', async_mode='eventlet', logger=True)  # <-- not working
# socketio = SocketIO(cors_allowed_origins='*', logger=True) # <-- works

def create_app(test_config=None, debug=False, *args, **kwargs):
    """Create an application."""
    app = Flask(__name__, instance_relative_config=True)

    if test_config is None:
        app.config.from_object(Config)
    else:
        app.config.from_mapping(test_config)

    socketio.init_app(app)

    with app.app_context():
        app.register_blueprint(api)
        return app
```

```
# ./server/resources/deployment.py
from flask_restx import Resource, reqparse, Namespace, fields
from flask_socketio import emit
from ..models.deployment import DeploymentModel
import json
from .. import socketio
...
api = Namespace('deployments', description='Deployments', path='/api/v1')

...
_deployment_put_payload = reqparse.RequestParser()
_deployment_put_payload.add_argument('name',
                            type=str,
                            help="A shortname for the deployment."
                            )
...

@socketio.on('connect', namespace="/deployments")
def connect():
    print('client connected to deployments namespace')

@socketio.on('disconnect', namespace="/deployments")
def disconnect():
    print('client disconnected from deployments namespace')

@socketio.on('new_deployment')
def handle_new_deployment(deployment):
    """if deployment model is created or updated broadcast the serialized object to all clients connected to the deployments namespace """
    emit('new_deployment', deployment.json(), broadcast=True, namespace='/deployments')

@api.route('/deployment/<deployment_id>')
@api.param('deployment_id', 'The deployment identifier')
class Deployment(Resource):
...

    @classmethod
    @api.expect(_deployment_put_payload)
    @api.response(204, 'Resource Updated')
    def put(cls, deployment_id: int):
        """
        Update an deployment definition based on the definition's id.
        """
        data = _deployment_put_payload.parse_args()

        deployment = DeploymentModel.find_by_id(deployment_id)
        ...
        try:
            deployment.save_to_db()
            handle_new_deployment(deployment)
        except Exception as error:
            raise InternalServerError("An error occurred saving to database.")

        return None, 204
    ...
```

```
// client.js
import React, { Component, useState, setOpen } from 'react';
import io from 'socket.io-client';
import { WS_ROOT_URL } from '../client_config';
...

class Topbar extends Component {
 
  constructor (props) {
    super(props);

    this.deployments_client = null;
  }

  componentDidMount() {
    try {
      this.deployments_client = io(WS_ROOT_URL + '/deployments');
      this.deployments_client.on('new_deployment', (data) => {this.newDeployment(data)});
    } catch(error) {
      console.log(error);
      throw(error);
    }

  newDeployment(deployment) {
    console.log("new deployment")
  }
...
}
```

**Comment by miguelgrinberg** [comment]
You have ignored the request for logs in the issue template. Please provide logs to help me diagnose the problem.

**Comment by webbpinner** [comment]
My mistake...  added below.  As you will see there's no difference with the exception that the external message queue never sees the socketio.on(connect,...) event.

Thank you for your very prompt response.

Logs from using internal queue:
```
kombu backend initialized.
client connected to deployments namespace
received new expedition {"id": 1, "name": "qwerty", "start_ts": "2020-04-12T00:00:00", "stop_ts": "2020-04-16T00:00:00", "platform_id": 1, "disabled": false, "status": "active"}
emitting event "new_expedition" to all [/expeditions]
received new deployment {"id": 1, "name": "ytrewq", "start_ts": "2020-04-02T00:00:00", "stop_ts": "2020-04-17T00:00:00", "platform_id": 2, "disabled": false}
emitting event "new_deployment" to all [/deployments]
received new deployment {"id": 1, "name": "qwerty2", "start_ts": "2020-04-01T00:00:00", "stop_ts": "2020-04-13T00:00:00", "platform_id": 2, "disabled": false}
emitting event "new_deployment" to all [/deployments]
```
Logs from using RabbitMQ:
```
kombu backend initialized.
received new deployment {"id": 1, "name": "qwerty", "start_ts": "2020-04-14T00:00:00", "stop_ts": "2020-04-17T00:00:00", "platform_id": 2, "disabled": false}
emitting event "new_deployment" to all [/deployments]
received new deployment {"id": 1, "name": "qwerty2", "start_ts": "2020-04-01T00:00:00", "stop_ts": "2020-04-15T00:00:00", "platform_id": 2, "disabled": false}
emitting event "new_deployment" to all [/deployments]
received new deployment {"id": 1, "name": "qwerty3", "start_ts": "2020-04-06T00:00:00", "stop_ts": "2020-04-11T00:00:00", "platform_id": 2, "disabled": false}
emitting event "new_deployment" to all [/deployments]
```

**Comment by miguelgrinberg** [comment]
you need to clarify what you mean by "internal queue". Both examples are using Kombu. What's the difference?

**Comment by webbpinner** [comment]
Sorry for the confusion...
What I meant by internal queue
```
socketio = SocketIO(cors_allowed_origins='*', logger=True) # <-- works
```
vs using an external message queue, RabbitMQ in my case:
```
socketio = SocketIO(cors_allowed_origins='*', message_queue='amqp://', channel='rt_updates', async_mode='eventlet', logger=True)  # <-- not working
```
This is the ONLY difference in the code.

**Comment by miguelgrinberg** [comment]
I don't see how the message queue can affect client connections. Do you want to create a simple client and server that I can run here to reproduce this problem and understand it better?

**Comment by webbpinner** [comment]
Thank you for taking the time to respond.  I will build a minimal example of my project and post to GitHub for review.

**Comment by webbpinner** [comment]
Here is the link to a stripped down version of my project on GitHub:
https://github.com/webbpinner/flask-socketio-test-server

The readme hopefully explains how to correctly install the client(react) and server(flask/flask-restx/flask-socketio).  The readme also includes where I'm having an issue (lines 13-14 ./server/__init__.py) using rabbitmq for the flask-socketio message queue vs the default message queue.  Debug mode and flask-socketio logging are both set to True.

**Comment by webbpinner** [comment]
I spent a few hours continuing to troubleshoot.  One problem I think I was having was I didn't bind the rabbitmq exchange to a queue so I believe rabbitmq didn't know how to handle the incoming messages.  I believe I have that sorted as I'm no seeing messges being collected by a queue.

I'm now wondering if I have a fundamental misunderstanding of how the message_queue functionality works.  Do I need to write a function that consumes the messages in the rabbitmq queue and if so how would that function emit messages to the clients?

**Comment by miguelgrinberg** [comment]
You do not need to do anything with the queue, just configure it. I'll look at your example when I have a moment in the next couple of days.

**Comment by webbpinner** [comment]
Thank you for making time to look at this.

I spent more time reading up on RabbitMQ and poured over a lot of online examples.  I figured out (I think) that I needed to create a RabbitMQ queue and bind the 'flask-socketio' exchange to it.  I now see messages added to the queue whenever an emit is called.

I've also further stripped down my test project and in doing so I did find a poorly place indentation.  The server now acknowledges connect/disconnect events from clients when message_queue='amqp://'.  So that's at least a little progress.

**Comment by webbpinner** [comment]
Ok... figured it out.  It was how I was initializing socketio.

Original Code:
```
# ./server/__init__.py
...
from flask_socketio import SocketIO
...
socketio = SocketIO(cors_allowed_origins='*', message_queue='amqp://', logger=True)

def create_app(test_config=None):
    app = Flask(__name__, instance_relative_config=False)

    ...
    socketio.init_app(app)
    ...

    return app
```

Working version:
```
# ./server/__init__.py
...
from flask_socketio import SocketIO
...
socketio = SocketIO()  # <--- CHANGED

def create_app(test_config=None):
    app = Flask(__name__, instance_relative_config=False)

    ...
    socketio.init_app(app, cors_allowed_origins='*', message_queue='amqp://', logger=True)   # <--- CHANGED
    ...

    return app
```

I figured this out by reading issue #324 and then looking at the `__init__.py` in the Flack repo.  The fact that the flask-socketio exchange was being created but not the associated queue should have tipped me off it was an initialization issue.

Thanks again for your patience.
