### ISSUE TITLE
Example unable to run with multiprocess module 

### ISSUE THREAD

**Issue by abhi94** [miguelgrinberg/Flask-SocketIO#125]
The example is not running when I change ,
thread = Thread(target=background_thread)
to 
thread = Process(target=background_thread)

**Comment by miguelgrinberg** [comment]
Yes, this is expected. The gevent-socketio context is held in memory, so a different process cannot directly emit events.

If you need a separate process to talk to clients over the socket connection you have to create a way for this process to pass the messages to the socketio server process.

**Comment by abhi94** [comment]
Thank you for your replay,
My background task is very long and blocking(it is calling a library wich internally calls c using ctypes), I am using a callback function in regular intervals of time.
 As this gevent serialise the threads if i run this task as a thread it will stop all incoming requests(i tried gevent.sleep() not much effective)

when passing 'threading=False' when monkey patching works fine. But I don't know it is a proper way of doing things.
I am running on an embedded device so piping between two process will be hard

**Comment by miguelgrinberg** [comment]
@abhi94 mixing green and regular threads is not something I would recommend. Instead, I suggest you look at Celery, which will enable you to run your long task in a separate process and then pass the results back to the main process.

**Comment by abhi94** [comment]
@miguelgrinberg  thank you for showing a right direction. I will look at celery.
