### ISSUE TITLE
How to avoid the automatic disconnection of Flask-SocketIO server to the Client and How to invoke an event

### ISSUE THREAD

**Issue by sathishsatzy** [miguelgrinberg/Flask-SocketIO#1251]
Hi Team,
1. While running a Flask-socketIO server and client, I invoke an event which simply plays audio that audio stream takes 25 seconds to finish, once it finished that connection between server and client gets disconnected automatically how to avoid this disconnection?
2. At the time of executing the 'play audio' event, I can't invoke another event('get number' event) in the server, How to achieve this properly? 

Server :
```
from flask import Flask, request
from flask_socketio import SocketIO
from playsound import playsound

app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app, cors_allowed_origins ="*")

@socketio.on('connect')
def connect():
	print("Client connected ",request.sid)

@socketio.on('disconnect')
def disconnect():
	print("Client disconnected")
	# socketio.stop()

@socketio.on('get number')
def getnum():
	print("in get number event")
	socketio.emit('Response',23)

@socketio.on('play audio')
def playAudio():
	print("playing audio")
	playsound('ringtone.mp3')
	socketio.emit('Response',"playback finished")
	
if __name__ == '__main__':
	try:
		socketio.run(app)
	except Exception as e:
		print("! Exception occured :(  \n",e)
```

Client :
```
<!DOCTYPE html>
<html>
	<head>
		<title>Client</title>
	</head>
	<body>
		<button onclick="audio()">play audio</button>
		<button onclick="number()">get number</button>

		<script type="text/javascript" src="assets/socketio.js"></script>
		<script type="text/javascript">
			const socket = io('http://localhost:5000');

			socket.on('connect',()=>{
				console.log("connected with server",socket.id)
			})
			socket.on('disconnect',()=>{
				console.log("disconnected with server",socket.id)
			})
			socket.on('Response',(resp)=>{
				console.log("%cserver : ",'color: blue',resp)
			})
			function audio()
			{
				socket.emit('play audio')
			}
			function number() {
				socket.emit('get number')
			}

		</script>
	</body>
</html> 

```
<img width="960" alt="issue" src="https://user-images.githubusercontent.com/35100551/79327579-55a21780-7f32-11ea-8c80-9469081aef64.png">

**Comment by miguelgrinberg** [comment]
Your audio playing is blocking the server and preventing it from maintaining the Socket.IO connections, or actually from doing anything. I assume you are using eventlet or gevent in this server? Sadly you cannot do anything that blocks for a long time. So you have to either find an audio playing function that is compatible with eventlet and/or gevent, or stop playing audio files on the server, or stop using eventlet/gevent.

**Comment by sathishsatzy** [comment]
Thanks for your reply, 
1. Please let me know how can we find the package or function which is compatible with eventlet or gevent?
2. If I stopped using eventlet/gevent for this socketIO server, is that server work as a socketIO server? and Can I invoke the events parallelly without interrupting the server-client connection?

**Comment by miguelgrinberg** [comment]
1. That is super tricky. I don't really know if there are any non-blocking audio playback libraries. Maybe there isn't any. It is highly unusual to play audio in a server process.
2. Without eventlet and gevent you will have a Socket.IO server that works only with the polling mechanism. The server relies on one of those frameworks to have access to WebSocket.

**Comment by sathishsatzy** [comment]
Ohh okay, Thanks for your support.
