### ISSUE TITLE
it works on locally, but doesnt work on ubuntu server 18.04 

### ISSUE THREAD

**Issue by Pang654** [miguelgrinberg/Flask-SocketIO#1252]
I have develop it in mac locally with socketio.run, it works perfectly.

when I move it on to the ubuntu server, it doesn't listen and response. Does anyone know why? Thanks
`from gevent import monkey
monkey.patch_all()

from flask import Flask , jsonify
from flask_socketio import SocketIO, emit, join_room, leave_room, send, ConnectionRefusedError

app = Flask(__name__)
app.config['SECRET_KEY'] = "ABC"
app_plain_text = "ABC"

socketio = SocketIO(app, cors_allowed_origins="*")

app.config['DEBUG'] = True

def ack():
  print('message was received!')

@app.route("/test", methods=["POST"])
def test():
  return jsonify({"result": "successful"})

@socketio.on('connect')
def test_connect():
  print('Client connected')

@socketio.on('disconnect')
def test_disconnect():
  print('Client disconnected')

if __name__ == "__main__":
  socketio.run(app, host='0.0.0.0', port=5000)`

**Comment by miguelgrinberg** [comment]
You have ignored the request to show your logs. Without see the Socket.IO logs from your server I cannot know what's happening. Please enable Socket.IO logs and provide a log capture.

**Comment by Pang654** [comment]
Here is the log for mac

`* Restarting with stat
 * Debugger is active!
 * Debugger PIN: 230-847-422
(22206) wsgi starting up on http://0.0.0.0:5000
(22206) accepted ('127.0.0.1', 63940)
127.0.0.1 - - [16/Apr/2020 18:26:37] "POST /test HTTP/1.1" 200 137 0.005040
(22206) accepted ('127.0.0.1', 63954)
Client connected
Client disconnected
127.0.0.1 - - [16/Apr/2020 18:27:27] "GET /socket.io/?EIO=3&transport=websocket HTTP/1.1" 200 0 2.648456`

Here is the log for the ubuntu server
` * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 281-591-133
61.93.48.188 - - [2020-04-16 18:27:04] "POST /test HTTP/1.1" 200 137 0.008003`

Here is the network connections for ubuntu server
`Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
        tcp        0      0 0.0.0.0:5000            0.0.0.0:*               LISTEN      26827/python3    `


HTTP POST request pass through for both of mac and ubuntu server, but when it come to WebSocket, it works only for mac in locally. It is a connection time out for server when I send the request. 
I am using this socket testing tool. https://amritb.github.io/socketio-client-tool/

**Comment by miguelgrinberg** [comment]
You haven't enabled Socket.IO logs.

**Logs**
Please provide relevant logs from the server and the client. On the server, add the `logger=True` and `engineio_logger=True` arguments to your `SocketIO()` object to get logs dumped on your terminal. The same arguments can be used on the [python-socketio's client](https://github.com/miguelgrinberg/python-socketio). If you are using the JavaScript client, see [here](https://socket.io/docs/logging-and-debugging/) for how to enable logs.

**Comment by Pang654** [comment]
Here is the log for Mac
Server side:
`Server initialized for eventlet.
 * Restarting with stat
Server initialized for eventlet.
 * Debugger is active!
 * Debugger PIN: 230-847-422
(23172) wsgi starting up on http://0.0.0.0:5000
(23172) accepted ('127.0.0.1', 65033)
9869395674b44f7aa30c7770e6643d17: Sending packet OPEN data {'sid': '9869395674b44f7aa30c7770e6643d17', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
Client connected
9869395674b44f7aa30c7770e6643d17: Sending packet MESSAGE data 0
127.0.0.1 - - [16/Apr/2020 19:25:32] "GET /socket.io/?transport=polling&EIO=3&t=1587036332.7581592 HTTP/1.1" 200 349 0.009128
(23172) accepted ('127.0.0.1', 65035)
9869395674b44f7aa30c7770e6643d17: Received request to upgrade to websocket
9869395674b44f7aa30c7770e6643d17: Upgrade to websocket successful
9869395674b44f7aa30c7770e6643d17: Received packet PING data None
9869395674b44f7aa30c7770e6643d17: Sending packet PONG data None
9869395674b44f7aa30c7770e6643d17: Received packet PING data None
9869395674b44f7aa30c7770e6643d17: Sending packet PONG data None
9869395674b44f7aa30c7770e6643d17: Received packet CLOSE data None
Client disconnected
127.0.0.1 - - [16/Apr/2020 19:26:06] "GET /socket.io/?transport=websocket&EIO=3&sid=9869395674b44f7aa30c7770e6643d17&t=1587036332.785702 HTTP/1.1" 200 0 33.442875`

Client side:
`Attempting polling connection to http://localhost:5000/socket.io/?transport=polling&EIO=3
Polling connection accepted with {'sid': '9869395674b44f7aa30c7770e6643d17', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
Engine.IO connection established
Received packet MESSAGE data 0
Namespace / is connected
Attempting WebSocket upgrade to ws://localhost:5000/socket.io/?transport=websocket&EIO=3
I'm connected!
WebSocket upgrade was successful
Sending packet PING data None
Received packet NOOP data None
Received packet PONG data None`

Here is the log for Ubuntu server
Server side
`Server initialized for eventlet.
 * Restarting with stat
Server initialized for eventlet.
 * Debugger is active!
 * Debugger PIN: 281-591-133
(27707) wsgi starting up on http://0.0.0.0:5000
(27707) accepted (, 65183)
999b2bc03d714ed3b413e10f58ec91f5: Sending packet OPEN data {'sid': '999b2bc03d714ed3b413e10f58ec91f5', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
Client connected
999b2bc03d714ed3b413e10f58ec91f5: Sending packet MESSAGE data 0
 - - [16/Apr/2020 19:29:43] "GET /socket.io/?transport=polling&EIO=3&t=1587036583.63452 HTTP/1.1" 200 349 0.007606
(27707) accepted ('61.93.48.188', 65184)
999b2bc03d714ed3b413e10f58ec91f5: Received request to upgrade to websocket
999b2bc03d714ed3b413e10f58ec91f5: Upgrade to websocket successful
999b2bc03d714ed3b413e10f58ec91f5: Received packet PING data None
999b2bc03d714ed3b413e10f58ec91f5: Sending packet PONG data None
999b2bc03d714ed3b413e10f58ec91f5: Received packet CLOSE data None
Client disconnected
 - - [16/Apr/2020 19:29:51] "GET /socket.io/?transport=websocket&EIO=3&sid=999b2bc03d714ed3b413e10f58ec91f5&t=1587036583.6811142 HTTP/1.1" 200 0 7.971796`

Client side
`Attempting polling connection to http://servername:5000/socket.io/?transport=polling&EIO=3
Polling connection accepted with {
Engine.IO connection established
Received packet MESSAGE data 0
Namespace / is connected
Attempting WebSocket upgrade to transport=websocket&EIO=3
I'm connected!
WebSocket upgrade was successful
Sending packet PING data None
Received packet NOOP data None
Received packet PONG data None
I'm disconnected!
Sending packet CLOSE data None
Engine.IO connection dropped
Exiting write loop task
Received packet NOOP data None`

It works now after I change from using gevent to eventlet. I am not sure is it because of gevent. Anyways thanks alot
