### ISSUE TITLE
Using Flask-SocketIO and -Login simultaneously

### ISSUE THREAD

**Issue by JanezBr** [miguelgrinberg/Flask-SocketIO#1253]
I am using the Flask-SocketIO and Flask-Login extensions simultaneously and am experiencing issues. I want to use the flask_login.current_user object inside the socketio event handlers, but the object seems to be reset or unavailable there (the User object turns into an AnonymousUser object, which has no id attribute). I have tried using the example code from [this blog post](https://blog.miguelgrinberg.com/post/unit-testing-applications-that-use-flask-login-and-flask-socketio) (with some modification) but still seem to be getting the AttributeError. I have also set manage_session=False as per [this blog post](https://blog.miguelgrinberg.com/post/flask-socketio-and-the-user-session).

**The code is:**
```
from flask import Flask, request, abort, redirect, render_template
from flask_login import LoginManager, login_user, current_user, UserMixin
from flask_socketio import SocketIO, emit

allowed_users = {'foo': 'bar', 'python': 'is-great!'}

app = Flask(__name__)
app.config['SECRET_KEY'] = 'top secret!'

login = LoginManager(app)
socketio = SocketIO(app, cors_allowed_origins='*', manage_session=False, engineio_logger=True, logger=True)

@login.user_loader
def user_loader(id):
    return User(id)

class User(UserMixin):
    def __init__(self, username):
        self.id = username

@app.route('/login', methods=['POST', 'GET'])
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        if username not in allowed_users or allowed_users[username] != password:
            abort(401)
        else:
            login_user(User(username))
            print('Logged in', current_user.id)
            return render_template('connect.html')
    else:
        return render_template('testlogin.html')

@socketio.on('connect')
def on_connect():
    print('Connected to', current_user.id)
    if current_user.is_anonymous:
        return False
    emit('welcome', {'username': current_user.id})

if __name__ == '__main__':
    socketio.run(app, debug=True)
```

The _testlogin.html_ is a simple form and _connect.html_ only attempts to connect to the server with:
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.3.0/socket.io.js"></script>
<script type="text/javascript">const socket = io.connect("http://127.0.0.1:5000");</script>
```

In case this is relevant: I also noticed in chrome developer tools that the session token is stored in the Cooke, while the session storage is empty. Is that alright? I read that cookies could not be sent through web socket connections.

**Logs**:
This is the logs I get when I first visit the login page and am then redirected to the connect page. Withing the login route the current_user works as I am able to print the username after login. 
```
Server initialized for eventlet.
 * Debugger is active!
 * Debugger PIN: something
(11276) wsgi starting up on http://127.0.0.1:5000
(11276) accepted ('127.0.0.1', 65070)
127.0.0.1 - - [16/Apr/2020 11:55:55] "GET / HTTP/1.1" 404 365 0.000987
(11276) accepted ('127.0.0.1', 65071)
127.0.0.1 - - [16/Apr/2020 11:55:58] "GET /login HTTP/1.1" 200 456 0.001995

Logged in foo

127.0.0.1 - - [16/Apr/2020 11:56:03] "POST /login HTTP/1.1" 200 699 0.004967
(11276) accepted ('127.0.0.1', 65072)
e83132c322fe419bb35424c0e23c6456: Sending packet OPEN data {'sid': 'e83132c322fe419bb35424c0e23c6456', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
connect handler error
Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\lib\site-packages\engineio\server.py", line 546, in _trigger_event
    return self.handlers[event](*args)
  File "C:\Users\user\Anaconda3\lib\site-packages\socketio\server.py", line 721, in _handle_eio_connect
    return self._handle_connect(sid, '/')
  File "C:\Users\user\Anaconda3\lib\site-packages\socketio\server.py", line 626, in _handle_connect
    self.environ[sid])
  File "C:\Users\user\Anaconda3\lib\site-packages\socketio\server.py", line 708, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "C:\Users\user\Anaconda3\lib\site-packages\flask_socketio\__init__.py", line 284, in _handler
    *args)
  File "C:\Users\user\Anaconda3\lib\site-packages\flask_socketio\__init__.py", line 696, in _handle_event
    ret = handler()
  File "C:\Users\user\OneDrive\something\FlaskSite\test.py", line 43, in on_connect
    print('Connected to', current_user.id)
  File "C:\Users\user\Anaconda3\lib\site-packages\werkzeug\local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'AnonymousUserMixin' object has no attribute 'id'
Application rejected connection
```
**Versions:**
eventlet==0.25.2
Flask==1.1.1
Flask-Login==0.5.0
Flask-Session==0.3.1
Flask-SocketIO==4.2.1

**Aside**: I have had a similar issue when using the Flask-Session extension, where entries to the session dictionary could not be accessed in the event handlers resulting in a KeyError.

**Comment by miguelgrinberg** [comment]
Why did you turn off the managed session setting? Did you see in that blog post that this setting was meant to be used with server-side sessions? For your case manage_session should be the default of `True`.

**Comment by JanezBr** [comment]
I incorrectly thought Flask-Login used server-side sessions. However, the issue persists even with the default setting with the logs unchanged.

**Comment by miguelgrinberg** [comment]
Since I don't have the complete code I cannot debug it here. You need to look at the Flask session cookie, if it is being set or not, and then if it is sent in the Socket.IO requests.
