### ISSUE TITLE
Sending data to not connected instances through library import

### ISSUE THREAD

**Issue by luisArandas** [miguelgrinberg/Flask-SocketIO#1255]
Hello and good day.

I am working with this library in a heroku server, and I'd like to know if it is possible to send sockets to machines that are not objectively connected through the website. I imagine this say for instance some javascript import from cdns in a p5js editor or codepen from a library that I can create to make an interface with this. Is there any project or solution you found for this? This is a way to extend the way people connect. I brought a small code sample to exemplify this idea.

`#import lib_from_cloud_that_interfaces_with_server`
`var new_connection;`
`async setup(v) {`
`    new_connection = new ServerInterface('socketid1');`
`}`
`async do(v) {`
`    if (new_connection.sockettrigger()) {`
`        //code goes here`
`    }`
`}`

Thanks in advance
Luis

**Comment by miguelgrinberg** [comment]
You need a Socket.IO client to connect to this server.

**Comment by luisArandas** [comment]
Ok maybe I will integrate a code editor in the front end and solve this the other way around. Thanks @miguelgrinberg
