### ISSUE TITLE
Client getting disconnected with "transport close" reason when running with gunicorn

### ISSUE THREAD

**Issue by ericjam3** [miguelgrinberg/Flask-SocketIO#1258]
I have been working on a Flask-SocketIO app that runs great when I just run "$ python main.py" in the terminal on my Digital Ocean server. However, when I close my laptop and thus exit the terminal, I have wanted to keep the app running. So I used to documentation and tried virtually every method in there, plus spent a couple of days just googling everything I can think of, to no avail. Currently, I am having some success running the following command:

gunicorn --bind 104.xxx.x.xx:xxxx --worker-class eventlet -w 1 main:app &

I have x'ed out the address, but the point is, it is the address to the server, it is not just localhost. So when I run this command, I get about 1 step further than just running "$ python main.py" and closing the terminal (which just shuts down the app altogether). When I instead run the gunicorn command, the app also runs fine in this case until the terminal is closed. At this point, I can tell the app is still running, because I can still get to the page and the main page still renders just fine. However, the server does not seem to be responding to any requests. I added a socket.on("disconnect") event to the js to see the disconnect reason, and found it to be "Transport close". I have found that everytime I emit something to the server I get this message, NOT when I exit the terminal. At this point, even when I refresh the browser or open a new tab and navigate to the page, whenever I try to emit something to the server I get this disconnect message.

For more reference, this is my code for running the app within main.py:

if __name__ == '__main__':
    socketio.run(app, host='104.xxx.x.xx', port=xxxx, debug=False)

I am assuming that I am missing something obvious, but as I said, I have been Googling for days and at this point I am pretty lost on what is going on. Any help would be greatly appreciated!!

**Comment by miguelgrinberg** [comment]
First of all, use `0.0.0.0` as IP address, no need to use the actual number.

Second, what you want to do is run your Flask application as a service. I wrote a [tutorial](https://blog.miguelgrinberg.com/post/running-a-flask-application-as-a-service-with-systemd) about this.

**Comment by ericjam3** [comment]
Awesome, that worked, thanks a bunch!
