### ISSUE TITLE
Maximum room support

### ISSUE THREAD

**Issue by ikoonman** [miguelgrinberg/Flask-SocketIO#1259]
I want to implement Flask SocketIO on one of my projects, which provides a dashboard to customers upon login. From what I see, Flask SocketIO would work well in pushing frequent data from the server to the clients for this purpose.

I've also noticed that some people suggest you maintain an internal array and add new clients to this array when they register/connect to the websocket. You can then iterate through this array and send data to each client's dashboard according to predefined criteria (which would typically be some JSON object). 

Can I use rooms for this purpose? I think the solution might be similar to using the `request.sid` as mentioned as the solution in [https://stackoverflow.com/questions/39423646/flask-socketio-emit-to-specific-user](url). Essentially, I'll be using each room as a messaging mechanism to push data from the server to the client, where each room (client) is isolated from the rest.

Also, is there a limit to the amount of rooms I can utilise, assuming that one client will use one room?

Hope my question is clear. Any advice would be appreciated.

**Comment by miguelgrinberg** [comment]
Sure, you can use rooms. There is no limit, and in fact, each client gets a room of its own by default when they connect. The room name is the same as `request.sid`.
