### ISSUE TITLE
Flak-SocketIO with nginx and gunicorn

### ISSUE THREAD

**Issue by JEGolding** [miguelgrinberg/Flask-SocketIO#1261]
Hi Miguel,
I'm trying to get a project working with Flask, SocketIO, gunicorn and Nginx. I've been following your microblog tutorial and have found it very helpful (thanks). I have everything working locally, but when I try to deploy the project to a linux server I get errors on all pages involving sockets.
I'm getting the following error on the client side in the javascript terminal:
[blocked] The page at {webpage} was not allowed to display insecure content from http://{my server's ip}/socket.io/?game_id=3452&page=game_display&EIO=3&transport=polling&t=1587450665323-0.

This is followed by:
Not allowed to request resource

And
XMLHttpRequest cannot load http://{my server's ip}/socket.io/?game_id=3452&page=game_display&EIO=3&transport=polling&t=1587450665323-0 due to access control checks.

When I check my "var/log/project_error.log" file I see the following:
2020/04/21 05:56:25 [error] 30367#30367: *165 connect() failed (111: Connection refused) while connecting to upstream, client: {client's ip}, server: _, request: "GET {webpage extension} HTTP/1.1", upstream: "{webpage}", host: "{server's ip}"

I've tried to follow this up and have set up gevent through gunicorn and added a location/socketio section to the nginx config file, but the problem is persisting. Any help would be much appreciated.

My /etc/supervisor/conf.d/project.conf file is as follows:

```
[program:project]
command=/home/ubuntu/project/venv/bin/gunicorn -b 127.0.0.1:8000 -k gevent -w 1 prroject:app
directory=/home/ubuntu/project
user=ubuntu
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
```

And my /etc/nginx/sites-enabled/project file is:

```
server {
    # listen on port 80 (http)
    listen 80;
    server_name _;
    location / {
        # redirect any requests to the same URL but on https
        return 301 https://$host$request_uri;
    }
}
server {
    # listen on port 443 (https)
    listen 443 ssl;
    server_name _;

    # location of the self-signed SSL certificate
    ssl_certificate /home/ubuntu/project/certs/cert.pem;
    ssl_certificate_key /home/ubuntu/project/certs/key.pem;

    # write access and error logs to /var/log
    access_log /var/log/project_access.log;
    error_log /var/log/project_error.log;

    location / {
        # forward application requests to the gunicorn server
        proxy_pass http://127.0.0.1:8000;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /static {
        # handle static files directly, without forwarding to the application
        alias /home/ubuntu/project/app/static;
        expires 30d;
    }

    location /socket.io {
        proxy_pass http://localhost:8000/socket.io;
        proxy_redirect off;
        proxy_buffering off;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";

    }
}
```

**Comment by miguelgrinberg** [comment]
I believe you should be using the domain name when you access the application, not the IP address.

**Comment by JEGolding** [comment]
I haven't set up a domain name yet, and am trying to test just using the IP as you suggest in your tutorial. Is there any way to test that/should I change any settings before doing so?

I changed the localhost:8000 to 127.0.0.1:8000 in an effort to debug the problem, but obviously missed one, thanks for pointing it out.

**Comment by miguelgrinberg** [comment]
Okay, so you are using a self-signed certificate then? Make sure you make every access to your server over https://, not http://

**Comment by JEGolding** [comment]
Hi Miguel,
I'm now having some other issues with the same project. I'm getting multiple 502 bad gateway errors, and when I check the error log I see "1109 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number)" and a bunch of "peer closed connection in SSL handshake while SSL handshaking to upstream" errors. I've found some suggestions that this is to do with my self-signed certificates, and have tried adding an upstream section to my nginx /sites-enabled/project file, but haven't found anything that works so far. Any help would be much appreciated.

**Comment by JEGolding** [comment]
After some more digging I've reached a different error. I was incorrectly changing the http:// to https:// in the location / and location /socket.io sections of the sites-enabled/project file. With that now fixed my sockets connect initially, but then after a pause of about a minute I get a few 400 (BAD REQUEST) errors in the javascript console, followed by a string of "Failed to load resource: the server responded with a status of 401 (UNAUTHORIZED)".
Checking my server-side error logs I see "upstream timed out (110: Connection timed out) while reading response header from upstream, client:".
I have tried fixing this issue using suggestions I've found such as adding 
`proxy_set_header Connection ""; ` and `proxy_read_timeout 3600;` to the nginx configuration file, but this hasn't helped solve my problem. The configuration file is now as follows:
```
server {
    # listen on port 80 (http)
    listen 127.0.0.1:80;
    server_name _;
    location / {
        # redirect any requests to the same URL but on https
        return 301 https://$host$request_uri;
    }
}

server {
    # listen on port 443 (https)
    listen 127.0.0.1:443 ssl;
    server_name _;

    # location of the self-signed SSL certificate
    ssl_certificate /home/ubuntu/project/certs/cert.pem;
    ssl_certificate_key /home/ubuntu/project/certs/key.pem;

    # write access and error logs to /var/log
    access_log /var/log/project_access.log;
    error_log /var/log/project_error.log;

    location / {
        # forward application requests to the gunicorn server
        proxy_pass http://127.0.0.1:8000;
        proxy_ssl_server_name on;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 3600;
        proxy_set_header Connection "";
    }

    location /static {
        # handle static files directly, without forwarding to the application
        alias /home/ubuntu/project/app/static;
        expires 30d;
    }

    location /socket.io {
        include proxy_params;
        proxy_pass http://127.0.0.1:8000/socket.io;
        proxy_redirect off;
        proxy_buffering off;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";

    }
}
```

**Comment by miguelgrinberg** [comment]
Can't really know whats going on without seeing the Socket.IO logs.

**Comment by JEGolding** [comment]
How do I access the logs when the app is deployed to a server? I've initialised sockets with:
SocketIO = SocketIO(app, logger=True, engineio_logger=True)
but can't find the logs anywhere.

**Comment by miguelgrinberg** [comment]
@JEGolding this really depends on how you set up your deployment. The logs go to stdout by default. Usually that is captured and put on a logfile, but as I said, it largely depends on the tools that you are using.

**Comment by JEGolding** [comment]
I was able to solve everything by following the instructions in this thread:
https://github.com/miguelgrinberg/Flask-SocketIO/issues/1047
Thanks for your patience and help Miguel, love your work.
