### ISSUE TITLE
No http requests logged ?

### ISSUE THREAD

**Issue by johaven** [miguelgrinberg/Flask-SocketIO#1262]
**Your question**
I understand that it is no longer Werkzeug which processes the requests but I am surprised that in debug mode I do not see any http request logged.
I can see the app.logger.debug of my application however.

**Version**
Python 3.7
Flask-SocketIO     4.3.0 
python-socketio    4.5.1  
gevent             20.4.0 
gevent-websocket   0.10.1 
greenlet           0.4.15 

**Logs**
```
[2020-04-24 10:08:48,122] INFO (server.py:150): Server initialized for gevent.
 * Restarting with stat
[2020-04-24 10:08:48,735] INFO (server.py:150): Server initialized for gevent.
 * Debugger is active!
 * Debugger PIN: 273-473-532
[2020-04-24 10:08:52,242] DEBUG (browsers.py:96): added: []
[2020-04-24 10:08:52,242] DEBUG (browsers.py:97): changed: []
[2020-04-24 10:08:52,242] DEBUG (browsers.py:98): removed: []
```
**Code**
```python
# init
app = Flask(__name__)
app.config.from_object(environnment)
app.template_folder = app.config['STATIC_PATH']
app.static_folder = app.config['STATIC_PATH']
app.logger.setLevel(app.config['LOGGER_LEVEL'])
# managing database
db = SQLAlchemy(app, session_options={'expire_on_commit': False})
# socket io
socketio = SocketIO(app, logger=True, engineio_logger=app.logger, debug=True)
```

```python
# run
from webapp import app, socketio

if __name__ == '__main__':
    socketio.run(app, host='127.0.0.1', port=5000, log_output=True, debug=True, use_reloader=True)
```

**Comment by johaven** [comment]
In developpement mode i think i have to use _app.run_ maybe the answer :)

**Comment by miguelgrinberg** [comment]
Yes, I agree it is strange. I don't believe this was like this in the past. But I've verified that I'm passing `log='default'` to the gevent wsgi server, which would make all logs go out to stderr.

**Comment by jamesharding** [comment]
I am seeing the same issue while using gevent and gevent-ws.

**Comment by miguelgrinberg** [comment]
Closing, since I do not believe this to be an issue with this package.
