### ISSUE TITLE
/socket-io/?EIO=3 & transport=websocket failed with 500 

### ISSUE THREAD

**Issue by laventy** [miguelgrinberg/Flask-SocketIO#1263]
**Your question**
Hey all, I use the Nginx/uwsgi/Flask-socketio for the flask application.

In my prod environment, the uwsgi outputs the 500 error below:

[pid: 25|app: 0|req: 62/62] 172.18.0.34 () {58 vars in 1233 bytes} [Sat Apr 25 13:06:33 2020] GET /notification/socket-io/?EIO=3&transport=websocket => generated 0 bytes in 0 msecs (HTTP/1.1 500) 0 headers in 0 bytes (4 switches on core 999)

uwsgi run statement:

uwsgi --http :80 --gevent 1000 --http-websockets --master --wsgi-file run.py --callable app -b 32768

However, there is no traceback to see what happens to the 500 error.

Therefore, is there any way to see the cause of this 500 error? any input will be helpful.

**Comment by miguelgrinberg** [comment]
@laventy I would check the uwsgi log more carefully, there's got to be something there, either from uwsgi or the Flask app indicating what was the problem.

**Comment by laventy** [comment]
@miguelgrinberg hey thanks for it. However, I cant see any traceback or any other thing for the problem. any idea?

**Comment by miguelgrinberg** [comment]
@laventy I can't really debug this, so no, I cannot offer any additional theories. As I said, a 500 is an unexpected server error, either uwsgi or the Flask app generated it. If you can't tell which from the logs first make sure your logs are working. If you are positive errors are being logged, then maybe replace uwsgi with gunicorn and see if that changes anything. Or comment out parts of your application that you suspect.

**Comment by laventy** [comment]
@miguelgrinberg thanks so much for your help. I have tried to use gunicorn instead. However, in this case, the frontend received the error below for the handshake request:

**Error during WebSocket handshake: Unexpected response code: 200**

**Nginx Log:**

2020/04/26 12:03:30 [error] 14#14: *129 upstream sent no valid HTTP/1.0 header while reading response header from upstream, client: 10.5.7.49, server: , request: "GET /notification/socket-io/?EIO=3&transport=websocket HTTP/1.1"

**Nginx Setting:**

location /notification {
    proxy_http_version 1.1;                    
    set $upstream "notification:80";
    proxy_pass http://$upstream; 
}  

**Questions:**

I think the HTTP code 101 should be the expected one. However, what is the reason for the flask app to return 200 instead?

**Comment by miguelgrinberg** [comment]
You don't seem to be following the instructions for the nginx socket.io configuration. Why is that? I suggest you use the logs that have been tested to work, and only once you have everything working start customizing the configuration to fit your needs.

**Comment by krishmoodbidri** [comment]
@miguelgrinberg do you see any difference between using uwsgi and gunicorn?
We switched to gunicorn as we had polling issue with uwsgi, and gunicorn seemed to use the web socket functionality of socketio

**Comment by miguelgrinberg** [comment]
@krishmoodbidri You've got it backwards. uWSGI has native support for WebSocket, gunicorn does not. When you use gunicorn the WS functionality comes from eventlet or gevent-websocket.

**Comment by krishmoodbidri** [comment]
> @krishmoodbidri You've got it backwards. uWSGI has native support for WebSocket, gunicorn does not. When you use gunicorn the WS functionality comes from eventlet or gevent-websocket.

@miguelgrinberg thank you for your reply, I'm having trouble accessing REMOTE_USER information using gunicorn and flask with apache. I have an apache authentication that takes it to my flask app (via gunicron), and I want to prepopulate my form with the authentication info. This relatively simple task has taken weeks since I dont see the REMOTE_USER info in either the header or the request env 

Thoughts?

**Comment by miguelgrinberg** [comment]
@krishmoodbidri this is a Flask question, how is Socket.IO related to this? If Flask does not see a remote user in your incoming requests, then this extension is going to also not have this information.
