### ISSUE TITLE
Monkey patching Thread with Flask-SocketIO and eventlet hangs in Python 3.8

### ISSUE THREAD

**Issue by spmsh** [miguelgrinberg/Flask-SocketIO#1264]
Hi Miguel,

I guess this is rather a question than a real issue to fix (at least not on ur end), but I am wondering the usage and impact of eventlet monkey_patch() on socketio engine.

I'm using Flask-SocketIO for a while in one of my app, using python 3.6.6, fully monkey patched with eventlet (the patching is done at the very beginning of my app).

`eventlet.monkey_patch()`
`socketio.init_app(app, async_mode='eventlet')`

I've recently upgraded to python 3.8, and now is facing an unexpected behavior that had me scratching my head for some time until I found out the problem.

Basically, using the same full eventlet.monkey_patch() will cause the server to hang after some idle time. Server doesn't accept any new request and only way to revive it is to restart the app. I have never experienced this behavior on v3.6.6, only with v3.7.6 and v3.8.2.

I found out if I disable Thread in monkey patch

`eventlet.monkey_patch(thread=False)`

then the server does not hang up anymore as explained above. 

I haven't fully retested all my app yet with this way of monkey patching, but I'd like to know what you think would be the impact of not having Thread=False with your socketio ? Does it have to be with green-threading ? I'm using a lot of socketio.start_background_task(...) in the app.

Thanks.

PS: I am having the same behavior with python 3.7.6

Flask-SocketIO==4.3.0
eventlet==0.25.2

**Comment by miguelgrinberg** [comment]
Flask-SocketIO does not require monkey patching. As long as you use the `start_background_task()` function you will be using green threads regardless of monkey patching.

The problem is with your dependencies. If any of those use threads then your code may end up blocking due to those packages running on regular threads, and that is bad.

**Comment by spmsh** [comment]
Thanks Miguel, I was under the impression that monkey patching was necessary when using socketio with eventlet, but after re-reading your documentation, it is actually most likely needed except if we use a message queue (which I don't at the moment, but may in the future if my app needs to scale...), so for now I think I can remove the monkey patch.

Just curious was this issue was not happening on version 3.6.x., anyway my app only make use of `start_background_task()` and not the standard python threads. I will double all my dependencies (using APScheduler a lot as well), but I think it should be okay.

Thanks again for the great lib.

**Comment by miguelgrinberg** [comment]
Yes, message queues need monkey patching. I don't recall if they need `threading` and `socket` or just `socket` though. Other dependencies that you use might require it as well. APScheduler might be okay to run on real threads as long as it runs on its own and you never wait on anything coming from this package, because the moment you wait you'll block the async loop.

**Comment by gharidev** [comment]
Hi Miguel,

I am using python 3.8.5. I am building a **scalable** application which uses Flask-SocketIO with eventlet. I am also using pdfkit for generating pdf's which uses threading. Using `eventlet.monkey_patch()` hangs up my application when the pdf redner is called and changing it to `eventlet.monkey_patch(socket=True)` or `eventlet.monkey_patch(threading=False)` does the job.

Is it required to set threading monkey_patch'ed?

**Comment by miguelgrinberg** [comment]
@gharidev not specifically familiar with pdfkit, but in general if threads are used you need to monkey patch threading.

**Comment by gharidev** [comment]
@miguelgrinberg Yes. pdfkit calls subprocess for rendering pdf's. So are you suggesting to use `eventlet.monkey_patch()`? But leaving it like that hangs the server on pdf rendering. Any other solutions?

**Comment by miguelgrinberg** [comment]
I'm not familiar with pdfkit as I said, so I'm not sure it is compatible with eventlet.

Note that threads is not the same as subprocesses. As an alternative solution you may consider not using pdfkit in the same process as eventlet. Maybe use a job queue such as Celery or RQ to run your PDF jobs.

**Comment by codeffe** [comment]
@miguelgrinberg I am using async_mode = gevent with Flask-SocketIO and a celery task. How do I monkey_patch my imports? Should I patch celery import or  not?

**Comment by miguelgrinberg** [comment]
@codeffe There is no correct or incorrect way here. Monkey patching should be done in the process that uses gevent concurrency. It should not be done in any processes that use other forms of concurrency such as threads or multiprocessing.
