### ISSUE TITLE
Flask-socketIO clients Arduino

### ISSUE THREAD

**Issue by andreapas79** [miguelgrinberg/Flask-SocketIO#1265]
Goodmorning everyone
I have a web server with flask and socketIO on raspberry. Is it possible to connect esp8266 (Arduino c++) with a socket for direct communication? Which library can I use with Arduino? I have tried several but without success, is it possible or should I change my approach?
I would also need a simple clue or example to continue, I have been getting 5 days
With this library, with which I am getting the best result, it gives me this answer. (<WebSocketClient.h>)
```
192.168.1.201 - - [29 / Apr / 2020 12:08:28] "GET /socket.io/?EIO=3&transport=polling&t=N74H4Tr&sid=403cc87bcbf84bc96a485165b281dc8f HTTP / 1.1" 400 -
```
If you want I can post the whole code.
Thank you and good day

**Comment by miguelgrinberg** [comment]
You seem to be using a websocket client on the Arduino. If that's the case, then you have to use a WebSocket server on your Pi. This is a Socket.IO server, it's not WebSocket.

**Comment by andreapas79** [comment]
For now, I'm using, socketIO on Flask...while in Arduino I'm trying to using websocketclient, but I also tried socketIO. Which is the best way to connect multiple clients in Arduino for a webstream on the raspberry webserver? am I completely wrong approach?

```
from flask import Flask, render_template
from flask_socketio import SocketIO, send
import os


app = Flask(__name__)
app.config['SECRET-KEY'] = os.urandom(24).hex()
socketio = SocketIO(app)

@app.route('/')
def index():
	return render_template('index.html')

@socketio.on('message')
def handle_maessage(msg):
	send(msg, broadcast=True)

if __name__ == '__main__':
	socketio.run(app, host='192.168.1.113', port=5000)
```

**Comment by miguelgrinberg** [comment]
It's what I just said, you seem to be using mismatched servers and clients. With a Socket.IO server you have to use a Socket.IO client. If you want to use a WebSocket client on your Arduino, then you have to use a WebSocket server. You can't mix and match.

I do not know of any working implementations of Socket.IO for microcontrollers. I recall at some point someone showed me one that was actually an incomplete implementation of the protocol and did not work. At some point I'm probably going to port my own Socket.IO client to MicroPython, but I assume you want C++, not MicroPython anyway.

**Comment by andreapas79** [comment]
and I am studying it with passion and pleasure, but I would like to create a platform that can also be used by implementations in C ++. I would like a solution that always goes well, adaptable to both micropython and c ++ ... so you advise me to migrate to a websocket server

**Comment by miguelgrinberg** [comment]
I can't really give you the best advice because I haven't really done C++ on Arduino or other microcontrollers in a long time. The Socket.IO protocol is higher level and overall a better choice in my opinion, but if you haven't found any C++ Socket.IO clients that work in your hardware it does not seem viable.

I assume you have tried this one? https://github.com/socketio/socket.io-client-cpp.

**Comment by andreapas79** [comment]
Yes, this one, and also this:
https://github.com/timum-viw/socket.io-client
I will try a few more days to see if I can solve something. If I succeed I will post my results here. Thanks very much for your reply.

**Comment by miguelgrinberg** [comment]
I should note that the one I linked does work when used on a desktop platform, at least I know some people have used it successfully with this server.
