### ISSUE TITLE
How to unit test the application without a create_app function due to known bug with socketio

### ISSUE THREAD

**Issue by Ash4669** [miguelgrinberg/Flask-SocketIO#1266]
Hello, I'm struggling to unit test my application because I don't have a create_app() function which I think I need for the unit tests. I heard it was a known bug with socketio that you can't use a create_app() function and then use flask run. How do you unit test an application otherwise? Or is the bug fixed perchance?

My app code is as follows:

```
#!/usr/bin/python3
# maybe delete above line
# app.py

from flask import Flask, session
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
import configparser
from flask_socketio import SocketIO, emit, send, join_room, leave_room


config = configparser.ConfigParser()
config.read("../settings.conf")

app = Flask(__name__)

# Ignores slashes on the end of URLs.
app.url_map.strict_slashes = False

app.config['SECRET_KEY'] = config.get('SQLALCHEMY','secret_key')
app.config['SQLALCHEMY_DATABASE_URI'] = config.get('SQLALCHEMY','sqlalchemy_database_uri')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

# init SQLAlchemy so we can use it later
db = SQLAlchemy(app)

socketio = SocketIO()

socketio.init_app(app)


login_manager = LoginManager()
login_manager.login_view = 'auth.login'
login_manager.init_app(app)

import models

@login_manager.user_loader
def load_user(user_id):
    return models.User.query.get(int(user_id))



# blueprint for auth routes in our app
from controllers.auth import auth as auth_blueprint
app.register_blueprint(auth_blueprint)

# blueprint for non-auth parts of app
from controllers.main import main as main_blueprint
app.register_blueprint(main_blueprint)

# blueprint for chase_the_ace parts of app
from controllers.games.chase_the_ace import chase_the_ace as chase_the_ace_blueprint
app.register_blueprint(chase_the_ace_blueprint)

# blueprint for shed parts of app
from controllers.games.shed import shed as shed_blueprint
app.register_blueprint(shed_blueprint)

# Game sockets import game mechanics and socketio listeners.
from controllers.games import chase_the_ace_gameplay


@socketio.on('connect')
def handle_my_connect_event():
    print('connected')

@socketio.on('disconnect')
def handle_my_disconnect_event():
    print('disconnected')

# If running app.py, then run app itself.
if __name__ == '__main__':
    socketio.run(app)
```

Models:
```# models.py

from flask_login import UserMixin
from app import db

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key = True)
    email = db.Column(db.String(100), unique = True)
    username = db.Column(db.String(50), unique = True)
    password = db.Column(db.String(50))
    firstName = db.Column(db.String(50))
    lastName = db.Column(db.String(50))
    chaseTheAceWins = db.Column(db.Integer)

class Player(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    userId = db.Column(db.Integer)
    roomId = db.Column(db.Integer)
    generatedPlayerId = db.Column(db.String(100), unique = True)
    name = db.Column(db.String(100))
    card = db.Column(db.String(10))
    lives = db.Column(db.Integer)
    outOfGame = db.Column(db.Boolean)

class Room(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    roomId = db.Column(db.Integer, unique = True)
    gameType = db.Column(db.String(20))
    hostPlayerId = db.Column(db.String(100))
    currentPlayerId = db.Column(db.String(100))
    dealerPlayerId = db.Column(db.String(100))
    locked = db.Column(db.Boolean)
```

Is there anything in my app that I'm doing wrong?

**Comment by miguelgrinberg** [comment]
I don't know which known bug you refer. Do you have a link to it?

Also, can you explain what the problem is with your unit tests? I don't see that mentioned in your report.

**Comment by Ash4669** [comment]
Thanks for the help.

I may have worded it a bit wrong so I'll give some more context. Because we run the application with socketio.run(app) and don't return app, I can't run a create_app() function and then use FLASK_APP='location' and use Flask run in the terminal. Most tutorials for unit tests all revolve around running a mock version of the application which requires a create_app() function (I think) and so I'm struggling to unit test my app. Just to get the importing to work for my test folder, I've had to put empty __init__.py files in each of the folders to make them packages and I don't fully understand that either.
How do you go about unit testing your applications? Do you use a create_app() method to run an instance of the application while testing? What's your method for creating an instance of the app to test?

Thank you.

Ashley

**Comment by miguelgrinberg** [comment]
@Ash4669 none of what you are saying has to do with Flask-SocketIO, the  complications with testing Flask apps that you describe exist without Flask-SocketIO as well.

Also, you can't rely on `flask run` for anything other than running your app during development. If you don't have a way to run your app that does not involve `flask run` then you have a problem. How are you going to run the app for production use?

Finally, there is nothing to prevent you from using an app factory function with Flask-SocketIO. This works:

```python
app = create_app()
socketio.run(app)
```

**Comment by Ash4669** [comment]
Sorry, I didn't realise. I only know from what I've managed to glean from random online tutorials.

I don't use ```flask run``` anymore, I just run the file as ```python app.py```. Also, I haven't a clue about production. I'll try and face that hurdle when I get to it with hopefully help from work platformer friends.

I'll try that to get the unit testing to work with that, thank you.
