### ISSUE TITLE
Flask hot reload with gevent monkey patching?

### ISSUE THREAD

**Issue by alsyia** [miguelgrinberg/Flask-SocketIO#1267]
Hi!

I've been trying to make Flask-SocketIO work with a message queue in Python 3.8. Since `eventlet` is broken in Python 3.7 and 3.8 (see https://github.com/eventlet/eventlet/issues/526, installing pyOpenSSL only solve the issue on some of my servers, not all of them), I decided to go with `gevent`.

My code looks like this:

```
from gevent import monkey
monkey.patch_all()

from my_app import create_app

if __name__ == "__main__":

    app = create_app()
    socketio.run(app, host="0.0.0.0", port=80, use_reloader=False)
```

It works well as long as `use_reloader` is set to False, but if I try to enable it, the server hangs, presumably because I only call `patch_all` in the parent process. What can I do to fix this? Is there a way to patch _after_ the reload but _before_ all the db and messaging libs are loaded? The reload worked with `eventlet` with Python 3.7 but sadly that's not an option... (your doc still recommend `eventlet` though, maybe I missed a fix somewhere?).

Thank you very much :)

**Comment by miguelgrinberg** [comment]
The reloader does not get along well with gevent, it never had. I suggest you use an external reloading tool such as [watchgod](https://pypi.org/project/watchgod/).

**Comment by alsyia** [comment]
Erf... that's sad. But I expected that. Thanks for the answer!
