### ISSUE TITLE
App timesout when deployed

### ISSUE THREAD

**Issue by pgulley** [miguelgrinberg/Flask-SocketIO#1268]
When deploying a flask-socketio app (tested against several different deployment methods) the server crashes before the app can start.

The app runs correctly on a local environment when run directly via `socketio.run(app)`
However, when deployed using gunicorn (with gevent or eventlet and with the default worker), I get an error like this:

```
[2020-05-01 18:52:07 -0400] [40920] [CRITICAL] WORKER TIMEOUT (pid:40924)
[2020-05-01 18:52:07 -0400] [40924] [INFO] Worker exiting (pid: 40924)
[2020-05-01 18:52:07 -0400] [40925] [INFO] Booting worker with pid: 40925
```

When deployed on a heroku environment without gunicorn, the app continuously crashes silently before ever going "up" in approximately the same time-frame as the verbose failure from above, so I assume it's the same issue. 

I have tried stripping all of the application logic out of the server file- leaving only [this](https://pastebin.com/8pT866Fd) and the error still occurs under the above conditions. 

It's possible this isn't an issue with flask-socketio but it seems the most likely candidate out of all the static pieces.

**Comment by pgulley** [comment]
I feel as a dingus does. 
The issue went away when I removed the `socket.run(app)` call at the bottom of the server file. I guess that was redundant, and thus causing issues. Glad it was simple- sorry to spam!

**Comment by sanren99999** [comment]
I meet the same problem.So i modify my nginx config and other, the problem has gone. like this:
	location /socket.io
	{   
            include proxy_params;
            proxy_http_version 1.1;
            proxy_buffering off;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_pass http://127.0.0.1:5000/socket.io;
        }
and use the eventlet as worker:
/usr/local/bin/gunicorn --worker-class eventlet -w 1  -b 127.0.0.1:5000 your-project:app
