### ISSUE TITLE
start_background_task not working with Gunicorn nginx

### ISSUE THREAD

**Issue by rupak78** [miguelgrinberg/Flask-SocketIO#1269]
**Your question**
start_background_task function works when using 
socketio.run(app) with eventlet. But, doesn't seem to work when the script is been run using Gunicorn.
I am using Nginx as reverse proxy.

The Gunicorn is quite simple as per documentation.

gunicorn --worker-class eventlet -w 1 module:app

When Gunicorn is not been used and the application is been run by eventlet server with Nginx as reverse proxy everything is working fine.
Any help is much appreciated.

I am using Gunicorn 20.0 in centos 7.

**Comment by miguelgrinberg** [comment]
I'm pretty certain the bug is in your own code. Can you show how you are doing this?

**Comment by rupak78** [comment]
Thanks for helping.

Here is my code.

```
if __name__=='__main__':   
    try:
      MongoConnect()
      ThresholdValue()
      socketData = socketio.start_background_task(sendData)
      socketio.run(application, host='192.168.1.214')
    except KeyboardInterrupt:
        socketData.join()
```

```
def sendData():
    
    while True:
        #Other Codes
		socketio.emit('alarm', data=(row[2], key, record['event'][key]['double'],
								 record['event']['dataTime']['string'], 'upper', upper_threshold,
								 uniqi), room='alert')

		socketio.emit('message', data=(
		record['event'], row[2], '123'), room=row[2])
		socketio.emit('heartbeat', data=(
		row[2], record['event']['dataTime']['string']), room='alive')
```



**Nginx configuration :** 
**This portion works**

` location /api { 
           proxy_pass http://192.168.1.214:5000/;
           proxy_set_header Host $host;
           proxy_set_header X-Real-IP $remote_addr;
           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;     
           # Define the maximum file size on file uploads
           client_max_body_size 50M;
        }
`

**Portion that doesn't work :**
`location /socket.io { 
            include proxy_params; 
            proxy_http_version 1.1; 
            proxy_buffering off;
            proxy_set_header Upgrade $http_upgrade; 
            proxy_set_header Connection "Upgrade"; 
            proxy_pass http://192.168.1.214:5000/socket.io;
        }`

**Gunicorn command :**

`gunicorn --worker-class eventlet -w 1  --bind 0.0.0.0:5000 mongoclient:application`

So, socket.io function doesn't work when running the code via Gunicorn.

**Comment by miguelgrinberg** [comment]
The code that you put inside `if __name__ == '__main__':` only runs when the module is directly executed by Python. None of those calls that you are making there run when you start the application under Gunicorn.

The `socketio.run()` call does not need to run under Gunicorn because it would compete with it (i.e. both start a web server), but the other three need to be moved outside of the conditional if you need them to run under Gunicorn.

```python
MongoConnect()
ThresholdValue()
socketData = socketio.start_background_task(sendData)

if __name__=='__main__':   
    try:
      socketio.run(application, host='192.168.1.214')
    except KeyboardInterrupt:
        socketData.join()
```

Depending on your particular situation you may prefer to put these three calls inside a `@before_first_request` Flask handler, which would delay their start until the first request is received.

**Comment by rupak78** [comment]
Thanks man.

That is really helpful. It solved the issue.
