### ISSUE TITLE
Emit socket to array of clients

### ISSUE THREAD

**Issue by luisArandas** [miguelgrinberg/Flask-SocketIO#1270]
Hello and good day!

I'd like to ask if it is possible with this lib to specify inside the socket.emit function multiple specific clients. Doing it like this works perfectly 

socket.emit('this-message', "hello", data[0]); 

Where data is an array of clients and sending to the first one to join. Is it possible to send to multiple like this?

I used the solution posted in https://stackoverflow.com/questions/39423646/flask-socketio-emit-to-specific-user

Thanks in advance!
Luis

**Comment by miguelgrinberg** [comment]
Not sure if I understand what you are asking, but I think what you want to do is this:

```python
for client in data:
    socket.emit('this-message', "hello", room=client)
```

Alternatively, if your clients were all previously added to a room, you can then do:

```python
socket.emit('this-message', "data", room=the_room_you_want)
```

**Comment by luisArandas** [comment]
Hello @miguelgrinberg thanks for the quick answer. The thing is I am not stacking them in the room object neither in different pages. I am making a matrix of interaction and want to "filter it". I get _data_ from the socketio function where it is just an array of ids ["id1baba", "id2baba"]. 

I can always do a loop and emit every iteration, 
I would say for word in data: socket.emit('this-message', 'hello', word[i])
Do you think it is a good solution?

**Comment by miguelgrinberg** [comment]
I don't understand what `word[i]` represents in your example, but the idea of using a for-loop to emit to many clients is perfectly fine. That's how this package does it internally.

**Comment by luisArandas** [comment]
Ok thanks!
