### ISSUE TITLE
Intercept outgoing messages

### ISSUE THREAD

**Issue by mlmarius** [miguelgrinberg/Flask-SocketIO#1271]
Is there a way to intercept outgoing messages that are in transit from the server to the client before they leave the server ?

For example somewhere in my application I broadcast something that is supposed to reach my client but before the message is actually dispatched to this subscribed client I need to perform some additional filtering and decide if the client should actually receive it or not.

For example the client subscribes to logging messages and only wants to receive some particular log levels and only for some particular modules. This is too dynamic to represent as an event but I could filter it before putting it on the wire. Can this be done ?

P.S. My application uses the Redis backend so I guess I need to intervene somewhere between the redis listen yields and the point where the message gets dispatched to the client's socket but haven't been able to pinpoint that or figure out some way to do what I want.

**Comment by miguelgrinberg** [comment]
You can probably use rooms for this filtering, but if that does not work, subclass your `Server` or `AsyncServer` class and override `emit()` with your logic.
