### ISSUE TITLE
How can I disable long-polling?

### ISSUE THREAD

**Issue by mortoray** [miguelgrinberg/Flask-SocketIO#1275]
How can I prevent a client from staying connected in long-polling mode. The performance characteristics of long-polling will not be sufficient for the application I'm building*.

I'm using eventlet.

(*Even in a local server setup it can take 2-5s before messages arrive at the long-polling client. It also appears to lose some messages -- or has simply taken so long I failed to wait.)

**Comment by miguelgrinberg** [comment]
The client can specify websocket as its only desired transport. How you do this depends on your client. This is specified in the arguments of the connection call, usually.

**Comment by mortoray** [comment]
Okay, I'll test further with the socket.io client. I'm having difficulties with it, that's why I wondered if I could just turn it off on the server.

Is there are way on the server to detect that the client is using long-polling?

**Comment by miguelgrinberg** [comment]
Yes, but note that this isn't a publicly available option so it can change at any time. Given a `sid` for a client, the currently used transport can be obtained as follows:

    transport = socketio.server.transport(sid)

Note that the transport can change when upgrades are enabled, so make sure you wait a few seconds after a connection to get the final transport.
