### ISSUE TITLE
HTTP Authentication failed; no valid credentials available

### ISSUE THREAD

**Issue by quuu** [miguelgrinberg/Flask-SocketIO#1276]
Occasionally (reproduced 6/10 times hitting the server), the first request to the server gets reutnred with 
`2.bde4c2d8.chunk.js:2 WebSocket connection to 'wss://127.0.0.1:5000/socket.io/?EIO=3&transport=websocket' failed: HTTP Authentication failed; no valid credentials available`

Simply by invoking `socketio.run()` and then having a client connect and emit a signal to it a few times will result in hitting this error popping up in chrome developer console.

**Settings**
secure transport only
websocket transport only
using gevent

**Comment by miguelgrinberg** [comment]
Have you looked at server-side logs as requested in the issue template? Without the server logs it's really impossible for me to know what happened.

**Comment by i524304** [comment]
Hi @miguelgrinberg 

While using cognitive servcices speech options for web chat using this sample (https://github.com/microsoft/BotFramework-Samples/blob/master/docs-samples/web-chat-speech/index.html) i am getting this web sockect connection error

Error : WebSocket connection to 'wss://speech.platform.bing.com/speech/recognition/interactive/cognitiveservices/v1?format=simple&language=en-US&Ocp-Apim-Subscription-Key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-ConnectionId=2607EB6D18B74798BD56FAA15AE367A0' failed: HTTP Authentication failed; no valid credentials available

Hope you can help and hoping to hear from you soon

Kind regards

**Comment by miguelgrinberg** [comment]
@i524304 you error has nothing to do with this package. You are just sending a request to a 3rd party API without authentication or with invalid credentials.
