### ISSUE TITLE
Websocket is closed before connection is established.

### ISSUE THREAD

**Issue by utalmighty** [miguelgrinberg/Flask-SocketIO#1277]
**Problem**
When I try to use 'https' protocol, I get error 'WebSocket is closed before connection is established' while using 'http' or localhost all seems to work fine as expected. 
I am working with Media Devices so I need 'https' protocol,
I am using ngrok to tunnel my localhost. 

Please follow the [link here](https://stackoverflow.com/questions/61755886/flask-socketio-not-working-with-https-protocol) for problem in detail:
Thanks.

**Comment by miguelgrinberg** [comment]
This is a problem between the browser and your web server, not with Flask-SocketIO. I suggest you look at client and server side logs to see if there are any indication of what the problem might be.

**Comment by utalmighty** [comment]
Hey, @miguelgrinberg after tinkering with flask, flask-socketio versions. I have reached the conclusion that 'python-engineio' was the package where the problem lies, it works fine with 'python-engineio==3.8.2.post1' but upgrading beyond that the 'https' problem continues. 
Installing 'flask-socketio' automatically updates 'python-engineio' to latest version.

**Comment by miguelgrinberg** [comment]
@utalmighty did you enable Socket.IO logs as I suggested? The problem could be as simple as a cross origin issue. Somewhere around that release some security related changes were made to python-engineio. As I said, the logs show clearly messages for all conditions, no need to look elsewhere.

**Comment by utalmighty** [comment]
Well thanks, @miguelgrinberg I didn't enable logs but instead thought to work around the versions. But now I can see enabling logs could have helped me.
