### ISSUE TITLE
Unable to establish a socket connection while using Flask-SocketIO on the server side and socket.io on the client side (ReactJS) in production mode

### ISSUE THREAD

**Issue by palakkapoor** [miguelgrinberg/Flask-SocketIO#1281]
I am unable to establish a socket connection while using Flask-SocketIO on the server side and socket.io on the client side (ReactJS) in production mode. 

On the client side, I am providing the complete ip address:port of the server

const socket = io(http://107.105.221.67:5000, {
transports: ['websocket']
};)

The above code works fine in development environment (localhost) but not in production mode i.e. after building the UI code and copying the buiild contents to public folder of the server. Please help.

**Comment by miguelgrinberg** [comment]
Did you configure CORS access?

**Comment by palakkapoor** [comment]
Hi, Thanks for the quick response.

Here is the complete code:

//Server Side

import eventlet

eventlet.monkey_patch()

from flask import Flask

from flask_socketio import SocketIO

socketIo = SocketIO(app, cors_allowed_origins="*",async_mode='eventlet')

@socketIo.on("connect", namespace='/create')

def handlecon():

   print("server is connected")




if __name__ == '__main__':

socketIo.run(app, host='0.0.0.0', debug=False, use_reloader=False, port=5010)










//Client Side

const io=require('socket.io-client')

//const SocketEndPoint = "http://107.109.113.24:5010/create";

const SocketEndPoint = '/create'

const socket= io(SocketEndPoint, {

  transports: ['websocket']

});




  componentDidMount() {

    socket.on('connect', ()=> {

      console.log("connected")

    })

  }

**Comment by miguelgrinberg** [comment]
You will need to look at the logs from your client and your server to see what's going on. There's nothing immediately obvious from looking at the source code.

**Comment by palakkapoor** [comment]
The browser data was cached. That's what caused the problem. Thanks
