### ISSUE TITLE
Switching from threading to eventlet prevents out-of-context broadcast websocket traffic

### ISSUE THREAD

**Issue by robshep** [miguelgrinberg/Flask-SocketIO#1282]
I have my application working great - just using 'threading' by default as I didn't install eventlet or gevent during initial development. 
I'm moving to test this in a staging environment, using gunicorn with eventlet behind nginx.

As soon as I install eventlet (pip install eventlet) some parts of the websocket traffic cease to be transmits.  Here are more details. 

I send a ws reply when the client connects, to bring an up-to-date state object.

```
// client.js
var socket = io.connect('ws://' + document.domain + ':' + location.port);
socket.on('connect', function() {
    socket.emit('client_connected');
    Vue.set(vm, 'message', 'Connected')
});

socket.on('update', function (data) {
    Vue.set(vm, 'state', data);
});

# flask.py
@socketio.on('client_connected')
def handle_client_connect_event():
    socketio.emit('update', logic.get_state('client_connect'), json=True, broadcast=False)
    log.info("Client Connect")
```
This works fine, both 'threading' and 'eventlet'

I also have some other events that arise from timers, network events, other bits of hardware etc.
When that happens, I do this:

```
# flask.py
def broadcast_bus(arg=None):
    with app.app_context():
        socketio.emit('update', arg, broadcast=True, namespace="/")
```
With async_mode='threading' this works and the client gets the update. 
With async_mode='eventlet' this one above does not work and the clients do not get the update.

I've tried a few different browsers.

In the service side, I see the event being emitted:

```
# python log
2020-05-19 21:12:43,938 INFO socketio.server - emitting event "update" to all [/] - [/dev/.venv/lib/python3.7/site-packages/socketio/server.py/emit:293]
2020-05-19 21:12:43,939 INFO engineio.server - c7a6a847d6b247aaa8b6d7e766144513: Sending packet MESSAGE data 2["update",{...}] - [/dev/.venv/lib/python3.7/site-packages/engineio/socket.py/send:96]
2020-05-19 21:12:43,940 INFO engineio.server - 179aa0f36725484ab615acd5bac3b5cc: Sending packet MESSAGE data 2["update",{...}] - [/dev/.venv/lib/python3.7/site-packages/engineio/socket.py/send:96]
```
And on the client side, using `localStorage.debug = 'socket.io-client:socket'` I don't see any traffic when these update messages are aparently being sent.

I fire it up like.....
```
socketio = SocketIO(async_mode='threading', logger=True)
socketio.init_app(app)
if __name__ == "__main__":
    socketio.run(app,host='0.0.0.0', port=8081, debug=False)
```

Now, I can also provoke something strange.....
On the client, I have a button which does a `js: socket.emit(...)` these are always received fine, get tossed around in the backend, and ultimately call that `broadcast_bus` function shown above. 
'threading' is always fine remember, but in 'eventlet', when I click these buttons on connected clients it all works as it should and updates are flowing freely. 
But, when I trigger something outside of a request context (a network event, or a hardware event) then the websocket server->client broadcasts stop - now the web-buttons don't work for any client, or rather the client->server messages go, the logic runs but the broadcasts stop.  If I reload a client page then _only _its_ broadcasts resume, and the buttons on other 'broken' clients are still going, until I trigger a hardware event. 

Likely there is something wrong with my Thread setup, but i can't work out how to resolve it.
I've read about this `eventlet.monkey_patching()` thing and if I try that my regular Threads don't work as expected. (I.e. a call to `my_thread.start()` blocks) 
I've tried to shift all my background threads to eventlet.patcher.original("threading") - and they work fine, but requests to load regular flask pages hang.

I'm stumped, and it looks like I'll have to stick with 'threading' and a UWSGI thread based server for the time being.

Thanks for reading thus far: my question is.... should it be possible to mix blocking Threads and eventlet coroutines in the same Flask application - as I've described - or am I trying to achieve something that is likely an unsupported/able scenario?

Thanks again. R

**Comment by robshep** [comment]
A better question might be: _Is there an example in the wild of running this scenario?_

**Comment by miguelgrinberg** [comment]
Eventlet isn't compatible with standard threading, timers and networking. Have you accounted for that? This framework provides a monkey patching option that sometimes help transform all these operations into compatible ones, if you haven't done that it should be the first thing to try. https://eventlet.net/doc/patching.html

**Comment by robshep** [comment]
Thank you. 
I have spent many hours reading documentation and source code, and trying various permutations  so I think I have now got a reasonable appreciation of it.
Yes, I've tried the monkey_patch function, but this doesn't tolerate threads that block (I have some char-device I/O that is currently with a blocking file.read() operation  )
I've wrapped these in `eventlet.spawn(eventlet.tpool.execute, func, arg ... ))` 
and I've similarly tried pushing them back to `eventlet.patcher.original("threading")`
and whilst all the background stuff then happens fine, Flask just won't respond with a page request.

I may have to stick with `gthread` workers in Gunicorn.

**Comment by miguelgrinberg** [comment]
Unfortunately eventlet is pretty strict in terms of not calling blocking functions. If your code cannot be adapted to be non-blocking then you either have to move it to another process or stop using eventlet.

**Comment by robshep** [comment]
Thanks again for your comments. And of course thank you for these libraries.

I was hoping to include the two domains - the legacy code (a few blocking threads), and the webapp (websockets, eventlet etc) but I cannot find a configuration that works. 
I don't actually need anything related to ws&eventlet to call any of the background threads, they don't need to be managed by the web-application, they just push events to a Queue or an embedded event bus. They all get initialised in main.py with some common data structures. 

It seems that the monkey_patching affects, or had side affects, that prevent such side-by-side existence.

worth a try.  gevent and long-polling it is. 

Thanks again, R
