### ISSUE TITLE
Handle namespaces which don't start with slash

### ISSUE THREAD

**Issue by johaven** [miguelgrinberg/Flask-SocketIO#1284]
**Enhancement proposal**

If namespaces don't start with a slash : show a warning or prefix it by a slash.

Functions emit/send, routes decorator, namespace class based should be considered.

**Comment by miguelgrinberg** [comment]
Namespaces have to start with a slash, as that is part of the Socket.IO protocol. While I could prepend the slash if it is missing, that would add a lot of code all over the place. Given that the vast majority of people know that namespaces start with a slash I don't think this change is that important.
