### ISSUE TITLE
uwsgi-nginx return 400 when sending message

### ISSUE THREAD

**Issue by andostini** [miguelgrinberg/Flask-SocketIO#1286]
Hey there,

I have set up a flask app with an socketio chat behind nginx-uwsgi. I can log in to the chat and it also emits the "XX has joined the room" message. But on sending messages I get timeout errors in the backend. 
Note If I try 20 times to send a message, one or two message will actually go through.
The same app is running just fine on my local Werkzeug server.

[log.txt](https://github.com/miguelgrinberg/Flask-SocketIO/files/4676933/log.txt)
This log is from docker container server until manual shutdown

**Logs**
;uWSGI instance configuration
[uwsgi]
cheaper = 2
processes = 16
ini = /app/uwsgi.ini
module = main
callable = app
http-websockets = 
ini = /etc/uwsgi/uwsgi.ini
socket = /tmp/uwsgi.sock
chown-socket = nginx:nginx
chmod-socket = 664
hook-master-start = unix_signal:15 gracefully_kill_them_all
need-app = true
die-on-term = true
show-config = true
;end of configuration

user  nginx;
worker_processes 1;
error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;
events {
    worker_connections 1024;
}
http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
    access_log  /var/log/nginx/access.log  main;
    sendfile        on;
    uwsgi_read_timeout 300s;
    keepalive_timeout  65;
    include /etc/nginx/conf.d/*.conf;
}
daemon off;

**Comment by miguelgrinberg** [comment]
Use a single worker process in your uwsgi set up. Check the docs if you need help learning how to configure your server for Socket.IO.
