### ISSUE TITLE
SocketIOTestClient emit/send to room

### ISSUE THREAD

**Issue by altusgerona** [miguelgrinberg/Flask-SocketIO#1290]
**Your question**
Looking through the test suite and documentation I saw that `SocketIOTestClient`'s `send` and `emit` cannot send to a room unlike the normal `SocketIO` class. Thus the test suite only checks whether events sent back from the server through the specified room is received and not whether a message sent by the test itself is received by all members in the room.

Is this intentional? Is there another way to test this?

**Comment by miguelgrinberg** [comment]
The send and emit functions in the test client replace said functions in a client, not in the server. From the side of the client there is no way to address a room, the only recipient for events sent from the client is the server.

**Comment by altusgerona** [comment]
Yup that makes sense. I've also repurposed my unit test to that end. Thanks for the clarification.

**Comment by simanacci** [comment]
@miguelgrinberg For `socket.emit('notif-count')` after a specific function like allocating permission to user x, is it advisable to create a room for each user then `emit()` versus adding a unique identifier to `notif-count` like user's id i.e `notif-count- + str(user.id)` then on the client `socket.on('notif-count-1)`?

**Comment by miguelgrinberg** [comment]
@simanacci Clients are assigned a room automatically when they connect. The name of the room is the value of `request.sid`.

**Comment by simanacci** [comment]
@miguelgrinberg So if I `socketio.emit('notification-message', {'count': user.notification_count()})` in Production it will only update that particular user based on the request.sid even though all users have `socket.on('notification-message', function(msg)` on the client side? I'm trying to test locally running via gunicorn with one user in a private browser window but it updates both windows.

**Comment by miguelgrinberg** [comment]
Your `socket.emit()` call does not have the `room` argument, so it will go out to everybody.

**Comment by simanacci** [comment]
@miguelgrinberg where should the background task function be located? It seems to be having a context problem. https://gist.github.com/simanacci/b74717921a3ad239238ebd44da6b9717 I had tried to emit from my flask route but got an `AttributeError` because of `room=request.sid`.

**Comment by miguelgrinberg** [comment]
You can't use `current_user` in a background thread, since the thread is not associated with a client or a request context.
