### ISSUE TITLE
Non-blocking emit from a subroutine

### ISSUE THREAD

**Issue by mukz545** [miguelgrinberg/Flask-SocketIO#1291]
Hey there,

I am struggling to emit events with socketIO from a subroutine started (and managed) in the standard background_task and would be happy if you can point me in the right direction.

**TDLR:**  `sio.emit('result', {'data': "result slave_task"})` is beeing blocked in `slave_task`

On the connect event a background task is started that loops over a queue of events.
For specific events a new subroutine is started from the background task.
In this subroutine I want to be able to emit an event via socketIO, but it seems that the ongoing execution of the subroutine is blocking the emit. (see abstract code at bottom)

**How can I implement a non-blocking subroutine so that an event emit is possible ?**
  
  
You can think of the background task as a master routine and the subroutine as a slave task.
To clearify the requirements for the slave task:  

- I want to be able to kill and restart the slave routine from the standard background task loop
- I want to be able to emit results via socketIO from the slave task
- As I need only one active slave routine, multiple slaves are not necessary

Struggling to find the right way of implementing this non-blocking subroutine behavior 
**I tried following approaches**:

- classic python thread that can be killed with manually raising exceptions
see:  [First Example @ different-ways-to-kill-a-thread](https://www.geeksforgeeks.org/python-different-ways-to-kill-a-thread/)
&rarr; Problem: slave-task is blocking and does not emit result

- eventlet greenthreads with example code seen below
see: [eventlet docs greenthread](https://eventlet.net/doc/modules/greenthread.html)
&rarr; Problem: slave-task is blocking and does not emit result
- even with **monkey_patching**  it is still blocking
- python processes from the multiprocessing module
see: [multiprocessing docs process](https://docs.python.org/2/library/multiprocessing.html#multiprocessing.Process)
&rarr; Problem:   
`NotImplementedError: set_nonblocking() on a file object with no setblocking() method (Windows pipes don't support non-blocking I/O)`

**What am I missing and are there better approaches to achieve a non blocking subroutine?**
I am happy over any input. Thanks!
  
Due complexity I tried to abstract the code as simple as possible:
```
import eventlet
from flask import Flask
from flask_socketio import SocketIO
from Queue import LifoQueue
from threading import Lock


app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app, async_mode="eventlet")

background_thread = None
slave_thread = None
thread_lock = Lock()
queue = LifoQueue()


def background_task():
    while True:

        global queue
        if queue.qsize() > 0:

            thread_lock.acquire()

            next_event_data = queue.get()
            # do some calc
            other_arg = "intermediate result"

            thread_lock.release()

            # start, kill, restart slave-task
            global slave_thread
            if slave_thread is None:
                slave_thread = eventlet.greenthread.spawn(slave_task, socketio, other_arg)
            else:
                slave_thread.kill()
                slave_thread = eventlet.greenthread.spawn(slave_task, socketio, other_arg)

        socketio.sleep(0)


def slave_task(sio, other_arg):
    # do some calc with otherArg
    sio.emit('result', {'data': "result slave_task"})
    while True:
        # this is probably blocking the emit
        abstract_loop = "more calc, maybe more emit"


@socketio.on('connect', namespace='/test')
def connect():
    global background_thread
    with thread_lock:
        if background_thread is None:
            background_thread = socketio.start_background_task(background_task)
        else:
            print "..background thread is already running"


@socketio.on('new_event', namespace='/test')
def new_event(msg):
    new_event_data = msg["data"]
    global queue
    queue.put(new_event_data)


if __name__ == '__main__':
    socketio.run(app, debug=False, port="5000")
```

Background task with processes

```
def background_task():
    while True:

        global queue
        if queue.qsize() > 0:

            thread_lock.acquire()

            next_event_data = queue.get()
            # do some calc
            other_arg = "intermediate result"

            thread_lock.release()

            # start, kill, restart slave-task
            global slave_process
            if slave_process is None:
                slave_process = Process(slave_task, socketio, other_arg)
                slave_process.start()
            else:
                slave_process.terminate()
                slave_process = Process(slave_task, socketio, other_arg)
                slave_process.start()
```

**Comment by mukz545** [comment]
After more investigation I think I am facing two different problems.

With adding  **`eventlet.sleep(0)`** in the `slave_task` I managed two to make the slav-task **non-blocking**:

```
def slave_task(sio, other_arg):
    # do some calc with otherArg
    sio.emit('result', {'data': "result slave_task"})
    while True:
        # this is not blocking the emit
        abstract_loop = "more calc, maybe more emit"
        eventlet.sleep(0)
```
**Therefore the greenthread is now non-blocking because of the manually swap-call.**
**However the emitted event is not recieved at the client side.**
  
  
My feeling is that the proper context is missing, since the context is now the new greenthread.
Adding namespace-param `namespace='/test'` to the emit event and extending the function parameter with the app context seems not enough:





@ Background-Task:
`slave_thread = eventlet.greenthread.spawn(slave_task, socketio, other_arg, app.app_context())`
```
def slave_task(sio, other_arg, context):
    # do some calc with otherArg
    with context:
        sio.emit('result', {'data': "result slave_task"}, namespace='/test')
    while True:
        # this is not blocking the emit
        abstract_loop = "more calc, maybe more emit"
        eventlet.sleep(0)
```

**Comment by miguelgrinberg** [comment]
Is your background task doing long or heavy CPU work? That is a problem because you are using eventlet, which is asynchronous. You may get an improvement if you sprinkle `socketio.sleep(0)` calls often enough during your calculation.

**Comment by mukz545** [comment]
The background task is pretty lightweight. It is mostly just checking the queue and start/kill/restart the slave-task. This is the place for cpu heavy calculations.

> You can't when using eventlet or any other asynchronous server

Seems like there is no way around manual `socketio.sleep(0)` calls & usage of greenthreads.
But this will still block on specific parts on the slave-task.

As starting the slave-task in a new process is not possible due multiprocessing incompatibility other forms of non-blocking subroutines are not existing?

**Comment by miguelgrinberg** [comment]
@mukz545 have you tried Celery?

**Comment by mukz545** [comment]
Didn't heared of it yet as I am pretty new to this topic. 
Will read into it - thanks!
