### ISSUE TITLE
Unable to run app using SSL

### ISSUE THREAD

**Issue by rejogc** [miguelgrinberg/Flask-SocketIO#1294]
At bottom is a small program that demonstrates my problem. In it I have two lines (one commented out) that set up flask-socketio:

    sio = SocketIO(app,async_mode="eventlet")
    # sio = SocketIO(app,certfile="cert.pem",keyfile="key.pem",async_mode="eventlet")

My problem is that both ways work with an http request and fail with an https request from my browser. It doesn't look like specifying the certfile and keyfile will cause the app to accept https requests. I would really like https to work as I'm writing a PWA and SSL is required. Here's some relevant details:

- python 3.8.0
- Flask 1.1.2
- Flask-SocketIO 4.3.0
- eventlet 0.25.2

I have another, much simpler, version of this program without Flask-SocketIO and eventlet. It works fine using 'ssl_context' in the regular app.run command. So I know the cert.pem and key.pem files work.

Below is my complete test program:
```
#!/usr/bin/env python

from flask import Flask, Response
from flask_socketio import SocketIO, emit

app = Flask(__name__)
app.config['SECRET_KEY'] = "It's very very secret"
sio = SocketIO(app,async_mode="eventlet")
# sio = SocketIO(app,certfile="cert.pem",keyfile="key.pem",async_mode="eventlet")

page = """<html>
<head>
  <title>Test</title>
</head>
<script src="static/socket.io.js" type="text/javascript"></script>
<script>
document.addEventListener('DOMContentLoaded', (ev) => {
    skt = io();
    document.querySelector("#btn").onclick = (ev) => skt.emit("test");
    skt.on("test", (ev) => console.log("test"));
})
</script>
<body>
  <h1>Test Flask socket.io over SSL</h1>
  <button id="btn">Button</button>
</body>
</html>"""

@app.route('/')
def index():
    return Response(page)

@sio.on("test")
def on_test():
    print("test")
    sio.emit("test")

if __name__ == '__main__':
    sio.run(app,host='0.0.0.0')
```

**Comment by miguelgrinberg** [comment]
Try this:

    sio.run(app,host='0.0.0.0', certfile="cert.pem", keyfile="key.pem")

**Comment by rejogc** [comment]
Yes! That Worked!
 
It would be nice if somewhere in the documentation that certfile and keyfile (and also ssl_context) be mentioned. I believe I dug through the Issues to find any mention of these keywords. Perhaps in the Deployment section?

Anyway, thank you very much. Great tool and great support.

**Comment by miguelgrinberg** [comment]
@rejogc the SSL options are really passed through to the web server that you use, and they are different for each one.

**Comment by rejogc** [comment]
@miguelgrinberg yes, the SSL options are passed through to the web server but by default Flask-SocketIO looks for eventlet and flask uses werkzeug. In the 'Embedded Server' section you call out eventlet as having a 'production ready server'. To run a PWA, SSL is required so 'production ready' really means being able to configure SSL in the embedded server, no? As it is now, one has to sift through the guts of the eventlet documentation and the Flask-SocketIO issues log to get a clue as to how this is done.

**Comment by miguelgrinberg** [comment]
@rejogc While in essence I agree that it would be nice if these options were more clear, a number of things that you said I disagree with.

> but by default Flask-SocketIO looks for eventlet

This is incorrect. Flask-SocketIO uses Werkzeug by default. If you install eventlet, gevent or uwsgi, then it switches to them.

> having a 'production ready server'

This means this is a robust web server for production loads, opposite to Werkzeug which is not.

> To run a PWA, SSL is required

Yes, but SSL is not required to be hosted on the same web server. What a much more common pattern is to host SSL in your reverse proxy (Apache, nginx), not on the Python process.

> As it is now, one has to sift through the guts of the eventlet documentation and the Flask-SocketIO issues log to get a clue as to how this is done.

This part I agree, but as indicated below, eventlet isn't special, if I document it I also need to document gevent, uwsgi and werkzeug.

**Comment by MichaelOdumosu57** [comment]
if anyone is looking this is the code to do it now 
```py
class SocketIOManager():
  init= False
  ssl_cert = None
  ssl_key = None
  server = None
  def __init__(self,ssl_cert,ssl_key,CONFIGS):
    if(self.init):
      raise SingletonException
    else:
      self.init = True
      self.ssl_cert = ssl_cert
      self.ssl_key = ssl_key
      self.CONFIGS = CONFIGS
      self.server = SocketIO(logger=False)


  def init_app(self,app):
    self.server.init_app(
      app,
      cors_allowed_origins=self.CONFIGS.app['access_control_allow_origin'],
      ssl_cert = self.ssl_cert,
      ssl_key = self.ssl_key
    )

  def run_via_eventlet(self,app):
    self._add_listeners()
    self.server.run(
      app=app,
      host ="127.0.0.1",
      certfile=self.ssl_cert, keyfile=self.ssl_key,
      use_reloader=True,
      debug=True,
      port=self.CONFIGS.app["backend_port"]
    )
```
