### ISSUE TITLE
According to the official website's documentation, my application can't work

### ISSUE THREAD

**Issue by VEADoc** [miguelgrinberg/Flask-SocketIO#1295]
![Jietu20200606-020011](https://user-images.githubusercontent.com/22616515/83908975-87996280-a79a-11ea-9a7f-84ebd10d930f.jpg)
![891591380090_ pic_hd](https://user-images.githubusercontent.com/22616515/83908984-8a945300-a79a-11ea-8b52-23d9660f1274.jpg)

**Comment by VEADoc** [comment]
there is no print when client connected

**Comment by miguelgrinberg** [comment]
You are doing a plain socket connection. Your server is a Socket.IO server, you need to use a Socket.IO client to connect.

**Comment by VEADoc** [comment]
oh I see, it means can't combine plain socket server with websocket server, right ?

**Comment by miguelgrinberg** [comment]
No, these are all different protocols, you have to use matching server and
client.
