### ISSUE TITLE
SocketIO + SSL for video app

### ISSUE THREAD

**Issue by a35026** [miguelgrinberg/Flask-SocketIO#1297]
#### Documentation update request

I am trying to build a simple app with following components:

- Dockerized React front-end on GAE
- Flask back-end + ffmpeg + static IP on GCE

Being new to Websockets I decided to use SocketIO for sending progress of a ffmpeg task (conversion and basic manipulation) back to a client. I chose GCP over AWS ELB, since I read somewhere that the latter is not recommended for Websockets stuff.

For testing purposes I run Flask simply by python app.py but plan to use gunicorn (with eventlet).

SocketIO + React pair works really great for my purposes and I get realtime server response when React is on localhost, but when deployed React is on SSL it fails for various reasons: starting from Mixed content in the beginning, now mostly for net::ERR_SSL_PROTOCOL_ERROR, net::ERR_CERTIFICATE_INVALID and net::ERR_CONNECTION_CLOSED.

It was expected but I got no experience with SSL other than getting managed certs from GCP and AWS, so please bear with me here:

- What certificates do I need for Flask? React ones or separate?
Currently I have .pem files for React app only (obtained from CloudFlare)
If I need them separate, does it mean that I should obtain a domain name for server, since I have only static IP (looks like CloudFlare and Let's Encrypt don't provide certs for bare IPs)? What's the newb-friendly way to obtain them? If I have to buy it, what's the best option now?

- Should I serve certs to `gunicorn -k eventlet -w 1 --key --cert` or it should go to `sio.run(app, host="0.0.0.0", port=8443, certfile="cert.pem", keyfile="key.pem")` or elsewhere?

- How to correctly deploy SocketIO and be sure it will run after I close my terminal?
This part is really confusing, since there are lots of deployment options and gunicorn seems the one I need, but there is no mentions whether I should comment out `sio()` if I use gunicorn or not? I just need the app to run as a daemon on GCE instance and restart itself automatically if ffmpeg fails for some reason.

This is not really a SocketIO issue, in all other aspects my dev experience with SocketIO was quite intuitive and I do want to learn more about it, thanks to amazing features it provides. But those very last steps suffer from missing of clear explanations which is critical for newbies when it comes to the intersection of several different things (SocketIO, SSL, gunicorn, eventlet, etc.)

Would be really great if the documentation could briefly describe the steps one should take for SSL.

**Comment by miguelgrinberg** [comment]
Most of what you asking applies to web applications in general, not to Socket.IO specifically.

> What certificates do I need for Flask? React ones or separate?

Your certificates are associated with domains, not with applications. You need certificates for all the domains that you use. Do you use the same domain to serve the react app and to answer Flask requests? Then you need one certificate for that domain. Do you use different domains? Then you need certificates for both.

> Should I serve certs to gunicorn -k eventlet -w 1 --key --cert or it should go to sio.run(app, host="0.0.0.0", port=8443, certfile="cert.pem", keyfile="key.pem") or elsewhere?

The `run()` function is not used with gunicorn. The `run()` call is normally inside a `if __name__ == '__main__':` conditional, so it will only run when it is called directly by Python, but not when invoked through Gunicorn or other web server.

If you are using Gunicorn as your main server, then the certificate should be configured there. If you have a reverse proxy in front of Gunicorn (nginx, Apache, etc), then that's where the certificate should be configured. It goes in the Internet facing service, the one clients connect to directly.

> How to correctly deploy SocketIO and be sure it will run after I close my terminal?

The `run()` call should be guarded with the conditional as mentioned above, no need to comment it out, as that will ensure it does not run. To run your gunicorn process as a service you can use any options available to your OS to daemonize processes. You can use systemd if you have that (I wrote a [tutorial](https://blog.miguelgrinberg.com/post/running-a-flask-application-as-a-service-with-systemd)), or supervisord (also wrote a [tutorial](https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xvii-deployment-on-linux)).
