### ISSUE TITLE
socketio.run (app) vs  app.run ()

### ISSUE THREAD

**Issue by hichabh** [miguelgrinberg/Flask-SocketIO#1299]
Hello,
I am trying to create an application that can detect objects in an image.

When I launch with socketio.run (app) it only works the 1st time, when I upload another image and I click the 2nd time I have the following error message:

W tensorflow / core / framework / op_kernel.cc: 1622] OP_REQUIRES failed at save_restore_v2_ops.cc:184: Not found: Key yolo_v3_model_1 / batch_normalization_100 / beta not found in checkpoint Exception in thread Thread-7

When I use app.run (), it works every time.

**Comment by hichabh** [comment]
Yes and When I use gevent I have the following message:
<Thread at 0x1aef5b20158: <bound method Server._handle_event_internal of <socketio.server.Server object at 0x000001AEF04ACF88 >> (<socketio.server.Server object at 0x000001AEF04ACF, '444fab7086d841d3983145309e4ec3a8' : / Users / me / De, '/', None)> failed with NotFoundError

**Comment by miguelgrinberg** [comment]
Not much that can be done, sadly. You can't use those CPU intensive frameworks alongside gevent/eventlet. Use a separate process for your server, that's really the painless way.
