### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by rupak78** [miguelgrinberg/Flask-SocketIO#1300]
Does Flask-socketio have any extension to read .xlsx/.xls file.

I was using Flask-Excel, but, it doesn't seem to work with Flask-socketio.

Any suggestions would be much appreciated.

**Comment by miguelgrinberg** [comment]
Flask-SocketIO has really nothing to do with Excel, so no, there is nothing for that. You should research the problem that you have with Flask-Excel, I can't think of any issue that could exist between these two packages.
