### ISSUE TITLE
Gunicorn Workers

### ISSUE THREAD

**Issue by seanieb** [miguelgrinberg/Flask-SocketIO#1301]
**Your question**
In the docs under ["Deployment"](https://flask-socketio.readthedocs.io/en/latest/#deployment) it says:

> "Due to the limited load balancing algorithm used by gunicorn, it is not possible to use more than one worker process when using this web server. For that reason, all the examples above include the -w 1 option."

Is this referring to when using gunicorn with the gevent workers only? Does this impact gunicorn with eventlet?

And generally does having only one worker severely impact the performance of the server, for both WS's and HTML routes?

**Comment by miguelgrinberg** [comment]
This limitation applies to Gunicorn in general.

A single eventlet or gevent worker can handle hundreds/thousands of concurrent clients. If you need more, then you can run multiple single-worker gunicorns and put nginx in front as a load balancer.

**Comment by seanieb** [comment]
Thanks Miguel!
