### ISSUE TITLE
Memory leakage when running neural network

### ISSUE THREAD

**Issue by chamecall** [miguelgrinberg/Flask-SocketIO#1302]
I’m trying to run my model with Flask but I bumped into high memory consumption and eventually shutting down of server.

I started to profile my app to find a place with huge memory allocation and found it in model inference (if I comment my network inference then there’s no problems with a memory).
First inference:

```
Line #    Mem usage    Increment   Line Contents
================================================
    49    261.6 MiB    261.6 MiB       @profile
    50                                 def predict(self, img):
    51    261.6 MiB      0.0 MiB           with torch.no_grad():
    52    269.3 MiB      7.7 MiB               data = self.test_image_transforms(img)
    53    269.3 MiB      0.0 MiB               data = torch.unsqueeze(data, dim=0)
    54    269.3 MiB      0.0 MiB               data = data.to(self.device)
    55    442.1 MiB    172.8 MiB               logit = self.net(data)
    56    442.1 MiB      0.0 MiB               pred = torch.sigmoid(logit.cpu())[0][0].data.numpy()
    57    442.1 MiB      0.0 MiB               mask = pred >= 0.5
    58
    59
    60    442.1 MiB      0.0 MiB           return mask
```

It can be seen that there’s huge memory allocation on line 55 (127 MB) while total memory usage is 261.6 MB (before allocation).

Second inference (after 10 sec):
```
Line #    Mem usage    Increment   Line Contents
================================================
    49    374.4 MiB    374.4 MiB       @profile
    50                                 def predict(self, img):
    51    374.4 MiB      0.0 MiB           with torch.no_grad():
    52    380.6 MiB      6.2 MiB               data = self.test_image_transforms(img)
    53    380.6 MiB      0.0 MiB               data = torch.unsqueeze(data, dim=0)
    54    380.6 MiB      0.0 MiB               data = data.to(self.device)
    55    548.5 MiB    167.9 MiB               logit = self.net(data)
    56    548.5 MiB      0.0 MiB               pred = torch.sigmoid(logit.cpu())[0][0].data.numpy()
    57    548.5 MiB      0.0 MiB               mask = pred >= 0.5
    58
    59
    60    548.5 MiB      0.0 MiB           return mask
```

There’s already total 375 MB allocated and so on every next inference.

I'm not sure completely that the problem is from the flask side but I tried to run the network in a cycle even with a thread for every run and the memory consumption was on the same level.

**Comment by miguelgrinberg** [comment]
None of this refers to Socket.IO code, correct? Or am I misinterpreting your findings?

**Comment by chamecall** [comment]
> None of this refers to Socket.IO code, correct? Or am I misinterpreting your findings?

The thing is that this doesn't happen when I run the code outside of Flask in a cycle (with and without threads).

**Comment by miguelgrinberg** [comment]
This is an issue board for Flask-SocketIO, not for Flask. As I said, I do not see how Flask-SocketIO can influence memory usage by pytorch. There isn't even an indication that you are using Flask-SocketIO at all in your report.

**Comment by chamecall** [comment]
my flask app creation:

```
app = Flask(__name__)

print(flask.__file__)
socketio = SocketIO(async_handlers=False)
socketio.init_app(app, async_handlers=False)

import namespaces


def get_namespaces(namespaces):
	namespaces_list = []
	for module_name in dir(namespaces):
		required_module = namespaces.__dict__.get(module_name)
		if isinstance(namespaces.__dict__.get(module_name), type(sys)):
			for resource_name in dir(required_module):
				resource = required_module.__dict__.get(resource_name)
				if "_namespace" in dir(resource):
					namespaces_list.append({
						"namespace_instance": resource,
						"namespace_name": resource.__dict__.get("_namespace"),
					})
	return namespaces_list


@app.route('/')
def index():
	return "Server is working"


if __name__ == "__main__":
	for current_namespace in get_namespaces(namespaces):
		socketio.on_namespace(current_namespace["namespace_instance"](current_namespace["namespace_name"]))
	socketio.run(app, host="0.0.0.0", debug=False)
```

part of Namespace:

#global 
similar_color_finder = SimilarColorFinder()

class MyNamespace(Namespace):
    _namespace = "/my_namespace"
    session_log_files = {}
    session_expiration_timeout = 900
    
    def __init__(self, *args, **kwargs):
        super(MyNamespace, self).__init__(*args, **kwargs)
        self.history = History.get_instance()
        self.session = None

    #handler which receive img and then pass it to the network
    def on_send_face_frame(self, message):
        img = self.form_image(message)
        if img is not None:
            #passing to the network
            self.extract_hair_color(img)

**Comment by miguelgrinberg** [comment]
I don't see anything in this code that could cause your leak, sorry.
