### ISSUE TITLE
Will broadcast messages reach clients in the same order?

### ISSUE THREAD

**Issue by mortoray** [miguelgrinberg/Flask-SocketIO#1303]
When I call emit/send, with broadcast, multiple times, are clients guaranteed to receive the messages in the same order?

That is, I have I clients A & B. Then I do:
emit('channel', msg1, broadcast=True, room=room, namespace=ns)
emit('channel', msg2, broadcast=True, room=room, namespace=ns)

Are both A & B expected to see the messages in the order: msg1, msg2 ?

I'm assuming yes, but would like to know for sure.

More interesting that the above is when multiple web requests from different clients each call  emit.  Let's assume this happens at about the "same time" for as much as an eventlet server on Python can do concurrency. For example:

Request from Client A:
   emit('channel', msg1, broadcast=True)

Request from Client B:
   emit('channel', msg2, broadcast=True)

Is it guaranteed that both clients get either `msg1, msg2` or `msg2, msg1`?

What about if I use a Redis queue to connect multiple instances? Is it still guaranteed?

**Comment by miguelgrinberg** [comment]
Assuming no client disconnections happening during this experiment, the events should be received in the order they are sent. But keep in mind that the client may allow running of event handlers in parallel, so your `msg1` and `msg2` events may be running concurrently, even if `msg1` was launched a moment before `msg2`.

The second example is a bit trickier to think about. If you have a single web server process, and it is asynchronous (i.e. gevent or eventlet, but not threading async mode), then your assumption is correct, the events will arrive in the same order. If you use the threading async mode, or you use multiple server processes, then the broadcasts from these two client requests might happen concurrently, so then there is really no way to tell what the order will be. In these situations I would think the order can be different for different clients.

**Comment by mortoray** [comment]
Thank you.   I assume the default for geventl is not to do threading?

Assuming I wanted to fix the second problem, what method do I have to feeding messages into a variety of processes and emitting them into the room? 

I would take the approach that all my incoming messages would be pushed to a Redis queue, and then each server instance would read those messages and dispatch them.

Or there perhaps already a flag that would force the messages to be pushed via the existing Redis queue system?

**Comment by miguelgrinberg** [comment]
Gevent uses its own concurrency mechansim based on greenlets. Eventlet also uses greenlets. The threading async mode is based on standard threads.

If you are using a single server process and greenlets, then it should be fine, as I mentioned earlier. If you are using multiple server processes, then the concurrency between servers is managed by the hardware and operating system, so the only way to serialize your broadcasts is to use some sort of cross-process synchronization. You will need to find a locking mechanism that is compatible with greenlet based concurrency for this, I believe the standard multiprocess locks in Python will block under gevent/eventlet.
