### ISSUE TITLE
Transport error/close along with CORS and 502 errors

### ISSUE THREAD

**Issue by a35026** [miguelgrinberg/Flask-SocketIO#1304]
I have a React app with socket.io on HTTPS and Flask SocketIO with eventlet on a different server. Flask app is deployed on Google Compute Engine GPU VM instance on Debian and served through Google-managed certificates.

I've managed to make Flask on HTTPS work having almost no experience with DevOps things like nginx, certbot or gunicorn, thanks to Miguel's tutorials and his detailed answers here. Thanks again!

However, after successfully establishing a connection and getting first data (I mirror ffmpeg stdout to React frontend in realtime) I see a bunch of errors in this exact order:

```
transport close
Access to XMLHttpRequest at 'https://website.ml/socket.io/?EIO=3&transport=polling&t=NAvBCCW' from origin 'https://www.reactapp.tk' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
GET https://website.ml/socket.io/?EIO=3&transport=polling&t=NAvBCCW net::ERR_FAILED
```
Sometimes this series ends with `transport error`. But after a few seconds I see this:
```
WebSocket connection to 'wss://website.ml/socket.io/?EIO=3&transport=websocket&sid=f674125663fa4839ae8b77de11961e9c' failed: Error during WebSocket handshake: Unexpected response code: 502
```
Looks like it's running circles, reestablish a connection, send some data during 5-10 sec, then lost the connection and start over again.  

I mean it works in general and I can really quickly send big chunks of string data back and forth but I'm not sure if it's stable enough to consider it working.

## Expected behavior
With plain HTTP connection React localhost <=> IP, it can keep connection literally for hours.  
With React HTTPS <=> IP I get mixed content error which is expected.
With HTTPS <=> HTTPS I get this weird behavior.

## Logs
Usually it's something like this:
```
(1618) accepted ('35.191.4.204', 49257)
78.129.1.65,34.120.2.38,35.191.2.204 - - [15/Jun/2020 20:04:12] "POST /socket.io/?EIO=3&transport=polling&t=NAvbGLh&sid=ee46e8e0cf3949458ba6efdfb32ef0a0 HTTP/1.1" 200 218 0.000233
78.129.1.65,34.120.2.38,35.191.4.201 - - [15/Jun/2020 20:04:12] "POST /socket.io/?EIO=3&transport=polling&t=NAvbGLk&sid=ee46e8e0cf3949458ba6efdfb32ef0a0 HTTP/1.1" 200 218 0.000186
78.129.1.65,34.120.2.38,35.191.4.204 - - [15/Jun/2020 20:04:12] "GET /socket.io/?EIO=3&transport=polling&t=NAvb1WS&sid=ee46e8e0cf3949458ba6efdfb32ef0a0 HTTP/1.1" 200 234 60.747491
78.129.1.65,34.120.2.38,35.191.4.204 - - [15/Jun/2020 20:04:12] "GET /socket.io/?EIO=3&transport=polling&t=NAvb1WS&sid=ee46e8e0cf3949458ba6efdfb32ef0a0 HTTP/1.1" 200 230 30.745739
78.129.1.65,34.120.2.38,35.191.4.198 - - [15/Jun/2020 20:04:14] "GET /socket.io/?EIO=3&transport=polling&t=NAvbGew&sid=88d005faab6f49f1a49ec26277bf7dfe HTTP/1.1" 200 234 0.427862
78.129.1.65,34.120.2.38,130.211.2.39 - - [15/Jun/2020 20:04:17] "GET /socket.io/?EIO=3&transport=websocket&sid=88d005faab6f49f1a49ec26277bf7dfe HTTP/1.1" 200 0 3.245074
```
## Context
**React client**
```javascript
this.socket = io('https://website.ml', { transport: ['websocket', 'polling']});
```
**Flask**
```python
socketio = SocketIO(
    application,
    cors_allowed_origins='*',
    async_mode='eventlet',
    always_connect=True,
    ping_timeout=300,
    ping_interval=60)

def _build_cors_preflight_response():
    response = make_response()
    response.headers.add("Access-Control-Allow-Origin", "*")
    response.headers.add('Access-Control-Allow-Headers', "*")
    response.headers.add('Access-Control-Allow-Methods', "*")
    return response

def _corsify_actual_response(response):
    response.headers.add("Access-Control-Allow-Origin", "*")
    return response

@socketio.on('connect')
def connect():
    socketio.emit('after connect',  {'data':'New client connected.'})
    return None

@application.route('/', methods=['GET', 'POST', 'OPTIONS'])
def establish_connection():
    if request.method == "OPTIONS":
        return _build_cors_preflight_response()
    else:
        return _corsify_actual_response(jsonify(status='All succeeded!'))


if __name__ == '__main__':
    socketio.run(application, host='0.0.0.0', port=8080, debug=True)
```

**Comment by miguelgrinberg** [comment]
You haven't included Socket.IO logs in your report. Can you enable logs and run the system until you get another failure?

**Comment by a35026** [comment]
Yep, thanks, enabled logging with `engineio_logger=True`, this is what I see:
```
(1432) accepted ('35.191.3.13', 61147)
64025d3187d1447caf32c4b946fb6151: Sending packet OPEN data {'sid': '64025d3187d1447caf32c4b946fb6151', 'upgrades': ['websocket'], 'pingTimeout': 300000, 'pingInterval': 60000}
64025d3187d1447caf32c4b946fb6151: Sending packet MESSAGE data 0
64025d3187d1447caf32c4b946fb6151: Sending packet MESSAGE data 2["after connect",{"data":"New client connected."}]
78.129.1.65,34.120.2.38,35.191.3.13 - - [15/Jun/2020 22:57:34] "GET /socket.io/?EIO=3&transport=polling&t=NAwCwd- HTTP/1.1" 200 457 0.002038
...
(1432) accepted ('130.211.2.48', 32770)
78.129.1.65,34.120.2.38,130.211.2.170 - - [15/Jun/2020 22:58:44] "GET /socket.io/?EIO=3&transport=websocket&sid=d5b8dc85965d4f1ab52e2b4ef6e72f63 HTTP/1.1" 200 0 30.002995
3fc5a3ea38ea445ea8424f4b278a8201: Sending packet OPEN data {'sid': '3fc5a3ea38ea445ea8424f4b278a8201', 'upgrades': ['websocket'], 'pingTimeout': 300000, 'pingInterval': 60000}
3fc5a3ea38ea445ea8424f4b278a8201: Sending packet MESSAGE data 0
3fc5a3ea38ea445ea8424f4b278a8201: Sending packet MESSAGE data 2["after connect",{"data":"New client connected."}]
78.129.1.65,34.120.2.38,35.191.3.1 - - [15/Jun/2020 22:58:46] "GET /socket.io/?EIO=3&transport=polling&t=NAwDDIP HTTP/1.1" 200 457 0.001163
...
(1432) accepted ('35.191.2.192', 64224)
3fc5a3ea38ea445ea8424f4b278a8201: Received request to upgrade to websocket
78.129.1.65,34.120.2.38,35.191.3.10 - - [15/Jun/2020 22:58:46] "GET /socket.io/?EIO=3&transport=polling&t=NAwDDLz&sid=3fc5a3ea38ea445ea8424f4b278a8201 HTTP/1.1" 200 234 0.365044
3fc5a3ea38ea445ea8424f4b278a8201: Upgrade to websocket successful
```
Last chunk `Received request to upgrade to websocket` matches the last error in sequence:  
**Error during WebSocket handshake: Unexpected response code: 502**  

After 30 seconds it starts the full cycle again.
![image](https://user-images.githubusercontent.com/66538710/84714414-08204600-af87-11ea-876b-8b80c21ccfd7.png)

**Comment by miguelgrinberg** [comment]
502 means that the server is not responding. Normally this happens when the server is offline or blocked. Any chance you are doing something that blocks the server? Maybe you can craft a small test application that I can use to reproduce the problem here?

**Comment by a35026** [comment]
Got it, Miguel, thank you for the offer, will try to arrange it and get back to you in this thread
Just FYI: the VM instance is behind the GCE Load Balancer which provides SSL, maybe it interferes somehow in-between IP chain and drops/omits some requests.

Also I see lots of random requests from unknown hosts/crawlers (20-30 per each error cycle). Not sure if it's connected or could cause sort of an overflow, but I believe in rare cases when there are no bot requests it does seem like nothing drops.

Are there any limits for concurrent polling connections or something similar to it?

**Comment by miguelgrinberg** [comment]
> Are there any limits for concurrent polling connections or something similar to it?

Not from this package. The web server and your load balancer might impose some limits.

**Comment by a35026** [comment]
Resolved using @miguelgrinberg hints
