### ISSUE TITLE
Unable to deploy flask-socketio on Ubuntu ec2 using Nginx and Gunicorn

### ISSUE THREAD

**Issue by iamarunchauhan** [miguelgrinberg/Flask-SocketIO#1306]
@miguelgrinberg I'm not able to deploy my flask-socketio application on ubuntu ec2 server. For deployment I'm using nginx server and gunicorn service. My whole application along with socket-io is working good without any problem on my local system.

Even the application working on cloud but **socket-io not working** & the functionality of socket-io gets remain **unimplemented**. 

Can you please guide me how to resolve this problem & how can I proceed further. This would be a big help to me. Thanks

**Flaskapp**  in `/etc/nginx/sites-enabled`

![image](https://user-images.githubusercontent.com/37152406/85104113-974a8980-b225-11ea-9d89-436634cbec8d.png)
 

**_Pip Freeze_**
![image](https://user-images.githubusercontent.com/37152406/85103763-eba13980-b224-11ea-9f4b-71d1ffb7bdd6.png)

_**Error in Console -**_

![image](https://user-images.githubusercontent.com/37152406/85103346-1ccd3a00-b224-11ea-9136-85f89ff19d13.png)

**Comment by miguelgrinberg** [comment]
Have you looked at the logs, as the issue filing instructions suggest? Most likely this is a CORS related issue, but the logs will tell.

**Comment by iamarunchauhan** [comment]
@miguelgrinberg I'm totally strucked here & not able to deploy flask-socketio on ec2 ubuntu. Also I'm unable to find logs in my nginx server. 

Now what I'm thinking is to deploy this from scratch now with either Nginx & Gunicorn or Apache & uWSGI. But don't know how deployment works with flask-socketio & which configuration files need to be changed. 

If you have something different approach to deploy flask-socketio application on ec2 or already deployed application like these. Then please guide me or share any reference material where can I get complete idea of this work-flow.

Thanks in advance

**Comment by miguelgrinberg** [comment]
There is nothing special about an EC2 server, it is a Linux machine. It does not require any additional care or instructions.

Have you enabled Socket.IO logs? When you created this issue you had an issue template with instructions on how to do this. Have you followed that?

Once you have enabled Socket.IO logs, you will get them on standard output. What method did you use to deploy your application? Normally output to standard output is collected to a log file. If you haven't done that, then this is very important and something you need to have implemented not only for this but for any other conditions that are logged, such as Flask 500 errors. If you want to learn how to do this, one possible way is systemd, which I wrote about here: https://blog.miguelgrinberg.com/post/running-a-flask-application-as-a-service-with-systemd.
