### ISSUE TITLE
Running a SocketIO instance does not display anything

### ISSUE THREAD

**Issue by Vayel** [miguelgrinberg/Flask-SocketIO#131]
I have this simple code:

```python
from flask import Flask, render_template
from flask_socketio import SocketIO, emit


app = Flask(__name__)
app.debug = True
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app)

@app.route('/')
def index():
    return render_template('index.html')


if __name__ == '__main__':
    socketio.run(app)
```

Running it does not display any message in the console whereas `app.run()` does:

```
(rampe) [vincent@vincent rampe]$ python httpserver.py 
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
```

I'm under the v1.0.

Thanks.

**Comment by Matzeee** [comment]
Same for me since the last pull.

With `app.debug = False` and  ` socketio.run(app)` I get
```
(640) wsgi starting up on http://0.0.0.0:5000/
(640) accepted ('127.0.0.1', 48159)
```
but the socket does only connect with `app.debug = True` independent of a reverse proxy.

**Comment by miguelgrinberg** [comment]
Logging in debug mode should work like in regular Flask apps now. Please update packages python-engineio and python-socketio to install the fix.
