### ISSUE TITLE
Implement clear cache function

### ISSUE THREAD

**Issue by RobustProgram** [miguelgrinberg/Flask-SocketIO#1318]
**Is your feature request related to a problem? Please describe.**
When implementing tests, sometimes my test clients will have a backlog of packets that I would like to flush out

**Describe the solution you'd like**
Would like to see the SocketIOTestClient have a simple function to clear the queue like,
```
def clear_cache(self):
    self.queue[self.sid] = []
```

**Describe alternatives you've considered**
I know I could just clear the queue myself in the tests but I thought this might be a nice addition to have to make tests more readable.

Would love to hear your opinion on this 😃

**Comment by miguelgrinberg** [comment]
Are you using the same SocketIO object for multiple tests? I'm trying to understand why do you have this problem.

**Comment by RobustProgram** [comment]
Hi Miguel,

So for my current project, I am creating rooms to allow for others to join. Anytime a person joins, the server will emit to the clients the new list of users who are in the room. So every time I create a new room and make test clients join the room, there will be a backlog of events relating to this.

Since I already have a test to make sure the server is sending the correct data when a new user is joining, I feel it may be redundant to keep checking in different test cases. As such, I would just flush out the backlog by calling `get_received()`, however, I felt adding `clear_cache()` would make it more readable.

I have linked a file in a project as an example of this [Project Link](https://gitlab.com/avalon-game/avalon-backend/-/blob/master/tests/test_avalon_backend.py), starting from line 260.

Thanks

**Comment by miguelgrinberg** [comment]
Given that there is already a way to do this with the `get_received()` function I really don't see a need to add an alias to it.

I honestly would not even worry about clearing the receive queue. This test:

```python
    c_1.get_received()

    # ...

    # All the clients should be notified as well
    received = c_1.get_received()
    assert received[0]['name'] == constants.ROOM_LISTENER
```

Is equivalent to:

```python
    # All the clients should be notified as well
    received = c_1.get_received()
    assert received[-1]['name'] == constants.ROOM_LISTENER
```

**Comment by RobustProgram** [comment]
That is fair assertion. Thanks for the response!
