### ISSUE TITLE
Websocket cors errors since upgrade to 4.X

### ISSUE THREAD

**Issue by Kruptein** [miguelgrinberg/Flask-SocketIO#1319]
**Describe the bug**
I recently upgraded my server from python-socketio 3.1.1 to 4.5.1 (also happens on 4.6.0)

This server is behind an nginx reverse proxy and uses aiohttp as its main server that all works fine.  my main application however communicates over a websocket and that suddenly did no longer work.  I have it working on my local computer without nginx with the latest version, so I suspect it has something to do with that combination although I didn't change anything in the nginx config

I enabled engineio logging and I noticed I get a "https://A.B.dev" is not an accepted origin, so I went ahead and added a cors_allowed_origin='*' and then it magically worked again.  However It does not work if I set cors_allowed_origin to any of the following: `'A.B.dev'`, `'B.dev'`, `['A.B.dev']`, `['B.dev']` or `['A.B.dev', 'B.dev']`.  It always comes back with the 'is not an accepted origin' error.

Any ideas how I can make it work without having to set my cors to *?

**Comment by miguelgrinberg** [comment]
What origin does the "is not an accepted origin" error shows you? That is the origin that should be added to your allowed origins list.

**Comment by Kruptein** [comment]
`https://A.B.dev is not an accepted origin` is the exact message, with A and B redacted.

**Comment by miguelgrinberg** [comment]
Okay, then you should use `cors_allowed_origins='https://A.B.dev'`.

**Comment by Kruptein** [comment]
I see I was under the impression from the examples that the protocol should not be included there, my bad and I was convinced I tried it, but I can confirm it works. Sorry for the stupid question
