### ISSUE TITLE
Running With Gunicorn won't request 3rd party APIs? running with flask run gives results okay

### ISSUE THREAD

**Issue by Ahzam-Lathiya** [miguelgrinberg/Flask-SocketIO#1320]
Hello Miguel,
My requirement. I'm building an app for a chatbot. The flask app will receive messages from the front-end via javascript socket-io and query that message to a remote NLP model through API. When I'm running the app with flask run command the api works correctly but when I run it with **gunicorn --worker-class eventlet -w 1 module:app** the API doesn't work. Since my server isn't showing any errors. Neither it is crashing it just returns the default message which I have written to print if the API isn't run.

**Comment by miguelgrinberg** [comment]
> the API doesn't work

What does this mean exactly (i.e. in terms of the HTTP exchange)?

**Comment by Ahzam-Lathiya** [comment]
My event calls a 3rd party API, The same event when run with flask run gives the API response and when run with gunicorn command the API is not being called. Now, Im not sure is this because of gunicorn or some other issue . The app doesn't show any issues.

**Comment by miguelgrinberg** [comment]
How can it not be called? This is what I need more details on? If you add a print statement right before the requests call, do you see it? If the call is attempted, then there must be something you can print for debugging purposes on the response that you receive.

**Comment by Ahzam-Lathiya** [comment]
I added a print statement right before the request as well as after the request, but the API is not called, I cannot get the API results. If I do the same with running flask run then everything works as expected. That's what I'm worried about that maybe the server is causing this issue.

**Comment by miguelgrinberg** [comment]
> I added a print statement right before the request as well as after the request, but the API is not called

You are providing vague descriptions of what is happening. What happened with the prints? I need actual details. Show me the code and the logs that you obtained if you prefer.

**Comment by Ahzam-Lathiya** [comment]
This is my event which is supposed to request a 3rd party API to recognize the message that is received by the server. In the exception(if the user doesn't provide the appropriate message) section the alternative message is returned. But i am giving the appropriate message but still the API call doesn't work.

`
@socketio.on('send_event')
def handle_send_event(json, methods=['GET', 'POST']):
    print('received my event: ' + str(json))

    utterance = json["query"]

    try:
        
        # YOUR-APP-ID: The App ID GUID found on the www.luis.ai Application Settings page.
        appId = '504c234a-bd45-4375-9abb-4f18e5444cfe'

        # YOUR-PREDICTION-KEY: Your LUIS authoring key, 32 character value.
        prediction_key = 'b36b154e90d54597b54590c405c6ac40'

        # YOUR-PREDICTION-ENDPOINT: Replace with your authoring key endpoint.
        # For example, "https://westus.api.cognitive.microsoft.com/"
        prediction_endpoint = 'https://westus.api.cognitive.microsoft.com/'

        # The headers to use in this REST call.
        headers = {
        }

        # The URL parameters to use in this REST call.
        params ={
            'query': utterance,
            'timezoneOffset': '0',
            'verbose': 'true',
            'show-all-intents': 'true',
            'spellCheck': 'false',
            'staging': 'false',
            'subscription-key': prediction_key
        }


        # Make the REST call.
        print("Requesting Bot")
        **luis_response = requests.get(f'{prediction_endpoint}luis/prediction/v3.0/apps/{appId}/slots/production/predict', headers=headers, params=params)**

        print("Response Received")
        # Display the results on the console.
        #print(response.json())

        intent = luis_response.json()['prediction']['topIntent']

        city = luis_response.json()['prediction']['entities']['geographyV2'][0]['value']

        weather_response = requests.get("http://api.openweathermap.org/data/2.5/weather?appid=149c9522d9216ca927a52354d76ec8e7&q={}".format(city) )

        desc = weather_response.json()['weather'][0]['description']

        temp = weather_response.json()['main']['temp']
        temp = temp - 273

        humid = weather_response.json()['main']['humidity']

        json["query"] = "The weather is {} with a temperature of {}°C and humidity at {}%".format(desc, round(temp,3), humid)

        
        #json["query"] = "Hello back udpsodop okopkokopkd hjhhqhuih 6979213-90"
        socketio.emit('my response', json, callback=messageReceived)

    # The exception to be run if there is no required data passed in the API request
    except Exception as e:
        json["query"] = "Please enter a correct location."
        socketio.emit('my response', json, callback=messageReceived)

if __name__ == '__main__':
    socketio.run(app, debug=True)`

**Comment by Ahzam-Lathiya** [comment]
This is the log from my terminal
`[2020-07-02 20:14:46 +0500] [11220] [INFO] Starting gunicorn 20.0.4
[2020-07-02 20:14:46 +0500] [11220] [INFO] Listening at: http://127.0.0.1:8000 (11220)
[2020-07-02 20:14:46 +0500] [11220] [INFO] Using worker: eventlet
[2020-07-02 20:14:46 +0500] [11223] [INFO] Booting worker with pid: 11223
received my event: {'data': 'User Connected'}
received my event: {'query': 'what is the weather in london'}
Request is made`

After the 'received my event:' the server is supposed to run the API call

**Comment by miguelgrinberg** [comment]
@Ahzam-Lathiya sorry, but the log that you are showing me does not match the code. Where is "Request is made" printed?

**Comment by Ahzam-Lathiya** [comment]
print("Requesting Bot")
and "request is made" is the same, sorry I changed the print statement when I ran the same code with **flask run** command.
Now what I'm asking is that why is this happening as you can see in # Make the REST call section the api is not being called when I run **gunicorn --worker-class eventlet -w 1 module:app** command.
All I need to know what can I do to fix this, as I think that it has something to do with gunicorn server. Thank you

**Comment by miguelgrinberg** [comment]
Please show me the output of "pip freeze" in your working configuration with flask run, and also the one in your gunicorn configurationt that hangs.

**Comment by Ahzam-Lathiya** [comment]
I'm running the **flask run** or *gunicorn* in the same environment. So the requirements are the same.

This is the output for pip freeze.

`pip freeze
adal==1.2.1
aiohttp==3.6.2
aiounittest==1.3.0
arrow==0.15.6
async-timeout==3.0.1
asyncio==3.4.3
attrs==19.3.0
azure-cognitiveservices-language-luis==0.2.0
azure-common==1.1.25
Babel==2.7.0
binaryornot==0.4.4
botbuilder-ai==4.9.1
botbuilder-core==4.9.1
botbuilder-dialogs==4.9.1
botbuilder-integration-aiohttp==4.9.1
botbuilder-schema==4.9.1
botframework-connector==4.9.1
certifi==2020.4.5.2
cffi==1.14.0
chardet==3.0.4
click==7.1.2
cookiecutter==1.7.2
cryptography==2.8
datatypes-date-time==1.0.0a2
datedelta==1.3
dnspython==1.16.0
emoji==0.5.4
eventlet==0.25.2
Flask==1.1.2
Flask-Cors==3.0.8
Flask-SocketIO==4.3.0
geojson==2.5.0
grapheme==0.6.0
greenlet==0.4.16
gunicorn==20.0.4
idna==2.8
isodate==0.6.0
itsdangerous==1.1.0
Jinja2==2.11.2
jinja2-time==0.2.0
jsonpickle==1.2
MarkupSafe==1.1.1
monotonic==1.5
msal==1.2.0
msrest==0.6.10
msrestazure==0.6.3
multidict==4.7.6
multipledispatch==0.6.0
oauthlib==3.1.0
pkg-resources==0.0.0
poyo==0.5.0
pycparser==2.20
PyJWT==1.5.3
pyowm==3.0.0
PySocks==1.7.1
python-dateutil==2.8.1
python-engineio==3.13.0
python-slugify==4.0.0
python-socketio==4.6.0
pytz==2020.1
recognizers-text==1.0.2a2
recognizers-text-choice==1.0.2a2
recognizers-text-date-time==1.0.2a2
recognizers-text-number==1.0.2a2
recognizers-text-number-with-unit==1.0.2a2
regex==2019.8.19
requests==2.22.0
requests-oauthlib==1.3.0
six==1.15.0
text-unidecode==1.3
urllib3==1.25.9
Werkzeug==1.0.1
wrapt==1.12.1
yarl==1.4.2`

**Comment by miguelgrinberg** [comment]
Are you monkey patching the standard library for eventlet compatibility?

**Comment by Ahzam-Lathiya** [comment]
No I haven't used monkey patching. Can you show me a way to use monkey patching for my scenario or any scenario at all? Thanks.

**Comment by miguelgrinberg** [comment]
See the eventlet documentation: https://eventlet.net/doc/patching.html.

**Comment by Ahzam-Lathiya** [comment]
@miguelgrinberg  I was going through the issues posted in this repo and I found this one https://github.com/miguelgrinberg/Flask-SocketIO/issues/696
This problem is the same one as mine. This guy is using sockets to receive messages and then making an HTTP request to dialogflow. I am doing the same exact for the dialogflow part I am using LUIS api. So I Monkey patch the code but still it doesn't work with the gunicorn server.
I've put this at the top even before my imports.
`import eventlet
eventlet.monkey_patch()`

In the link I mentioned I've learned that if the HTTP request is blocking code then it won't run with eventlet monkey patch. I still don't understand how do I make this work??

**Comment by miguelgrinberg** [comment]
Unfortunately most Google API clients for Python are incompatible with eventlet and gevent at this time due to the grpc package that they use, which blocks under these frameworks. See https://github.com/grpc/grpc/issues/15923.

**Comment by Ahzam-Lathiya** [comment]
okay @miguelgrinberg Using Eventlet Monkey Patch And running the app on **gunicorn --worker-class eventlet -w 1 application:app** The app works as expected only if I don't call any 3rd party API  in my event. If I call a 3rd party API then it gives **wrap_socket() got an unexpected keyword argument '_context'** error .

My Code:
`import eventlet
eventlet.monkey_patch()


from flask import Flask, render_template, request, session
from flask_socketio import SocketIO, join_room
from flask_cors import CORS
import requests

app = Flask(__name__)
app.config['SECRET_KEY'] = 'vnkdjnfjknfl1232#'
CORS(app)
socketio = SocketIO(app)

@app.route('/')
def sessions():
    return render_template('textbox.html')


def messageReceived(methods=['GET', 'POST']):
    print('message was received!!!')

@socketio.on('connect_event')
def handle_connect_event(json, methods=['GET', 'POST']):
    print( 'received my event: ' + str(json) )


@socketio.on('send_event')
def handle_send_event(json, methods=['GET', 'POST']):
    print('received my event: ' + str(json))

    utterance = json["query"]
    client = []

    try:

        #store the client on basis of session id
        client.append(request.sid)
  
        #create a room on basis of session and join
        room = session.get('room')
        join_room(room)
        
        # YOUR-APP-ID: The App ID GUID found on the www.luis.ai Application Settings page.
        appId = '504c234a-bd45-4375-9abb-4f18e5444cfe'

        # YOUR-PREDICTION-KEY: Your LUIS authoring key, 32 character value.
        prediction_key = 'b36b154e90d54597b54590c405c6ac40'

        # YOUR-PREDICTION-ENDPOINT: Replace with your authoring key endpoint.
        # For example, "https://westus.api.cognitive.microsoft.com/"
        prediction_endpoint = 'https://westus.api.cognitive.microsoft.com/'

        # The headers to use in this REST call.
        headers = {
        }

        # The URL parameters to use in this REST call.
        params ={
            'query': utterance,
            'timezoneOffset': '0',
            'verbose': 'true',
            'show-all-intents': 'true',
            'spellCheck': 'false',
            'staging': 'false',
            'subscription-key': prediction_key
        }

        # Make the REST call.
        luis_response = requests.get(f'{prediction_endpoint}luis/prediction/v3.0/apps/{appId}/slots/production/predict', headers=headers, params=params)
        print(luis_response)

        intent = luis_response.json()['prediction']['topIntent']

        city = luis_response.json()['prediction']['entities']['geographyV2'][0]['value']

        weather_response = requests.get("http://api.openweathermap.org/data/2.5/weather?appid=149c9522d9216ca927a52354d76ec8e7&q={}".format(city) )

        desc = weather_response.json()['weather'][0]['description']

        temp = weather_response.json()['main']['temp']
        temp = temp - 273

        humid = weather_response.json()['main']['humidity']

        json["query"] = "The weather in {} is {} with a temperature of {}°C and humidity at {}%".format(city,desc, round(temp,3), humid)


        socketio.emit('my response', json, callback=messageReceived, room=client[0])

    except Exception as e:
        print(e)
        json["query"] = "Please enter a correct location."

        socketio.emit('my response', json, callback=messageReceived)`

**Comment by miguelgrinberg** [comment]
@Ahzam-Lathiya that's a bug in eventlet's ssl support that occurs with certain combinations of Python versions and eventlet versions. Try older eventlet releases, you may find one that works until this issue is fixed. See https://github.com/eventlet/eventlet/issues/526.

**Comment by Ahzam-Lathiya** [comment]
hey @miguelgrinberg  Just wanted to tell you that it works fine now. The API is being called in the event while running on gunicorn server. I was using python 3.7 but now I completely wiped out python 3.7 from my system and made a new virtualenv with **python 3.6.9** and all dependencies work fine.
Here's my requirements.txt file python 3.6.9:
`certifi==2020.6.20
chardet==3.0.4
click==7.1.2
dnspython==1.16.0
eventlet==0.25.2
Flask==1.1.2
Flask-Cors==3.0.8
Flask-SocketIO==4.3.1
greenlet==0.4.16
gunicorn==20.0.4
idna==2.10
itsdangerous==1.1.0
Jinja2==2.11.2
MarkupSafe==1.1.1
monotonic==1.5
pkg-resources==0.0.0
python-engineio==3.13.1
python-socketio==4.6.0
requests==2.24.0
six==1.15.0
urllib3==1.25.9
Werkzeug==1.0.1`
Thanks alot,
PS I am going to deploy this on a VM I will tell you about it how it works.

**Comment by Ahzam-Lathiya** [comment]
Hey @miguelgrinberg  I ran the same app with nginx configured as a reverse proxy and a gunicorn WSGI on my localhost. It works fine on localhost. But when I deploy it to a VM and I run it , it doesn't give me issues when I check the status but the the app can't be accessed when I try to open in the browser. 
Here are my configurations for both Nginx and gunicorn service.
my file in /etc/systemd/system/myapp.service
`[Unit]
Description=Gunicorn instance to serve exampleapp
After=network.target

[Service]
User=root
Group=www-data
WorkingDirectory=/root/myvenv/mydir
Environment="PATH=/root/myvenv/bin"
ExecStart=/root/myvenv/bin/gunicorn --worker-class eventlet -w 1 wsgi:app

[Install]
WantedBy=multi-user.target`

my file in /etc/nginx/sites-available/myapp

`server {
    listen 80;
    server_name my_server_ip www.my_server_ip;
    
    location / {
        include proxy_params;
        proxy_pass http://my_server_ip:5000;
    }
   
    location /socket.io {
        include proxy_params;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass http://my_server_ip:5000/socket.io;
    }
}`

And when I check the logs
sudo journalctl -u myapp
`Jul 10 21:26:51 chatbot systemd[1]: Started Gunicorn instance to serve acianobot.
Jul 10 21:26:52 chatbot gunicorn[86733]: [2020-07-10 21:26:52 +0000] [86733] [INFO] Starting gunicorn 20.0.4
Jul 10 21:26:52 chatbot gunicorn[86733]: [2020-07-10 21:26:52 +0000] [86733] [INFO] Listening at: http://127.0.0.1:80
Jul 10 21:26:52 chatbot gunicorn[86733]: [2020-07-10 21:26:52 +0000] [86733] [INFO] Using worker: eventlet
Jul 10 21:26:52 chatbot gunicorn[86733]: [2020-07-10 21:26:52 +0000] [86752] [INFO] Booting worker with pid: 86752`

sudo journalctl -u nginx
`Jul 10 21:44:11 chatbot systemd[1]: Stopping A high performance web server and a reverse proxy server...
Jul 10 21:44:11 chatbot systemd[1]: Stopped A high performance web server and a reverse proxy server.
Jul 10 21:44:11 chatbot systemd[1]: Starting A high performance web server and a reverse proxy server...
Jul 10 21:44:11 chatbot systemd[1]: Started A high performance web server and a reverse proxy server.`

After I check both gunicorn service and nginx with **sudo systemctl status** and they don't show any error.

In the localhost version of mine in the nginx config file I have put **127.0.0.1** instead of **my_server_ip**. And it works perfectly fine.
Thanks.

**Comment by miguelgrinberg** [comment]
You have gunicorn listening on port 80:

    Listening at: http://127.0.0.1:80

Shouldn't that be 5000?

**Comment by Ahzam-Lathiya** [comment]
Even if I configure gunicorn to listen at **server_address:8000** and nginx at **server_address:5000** it still won't work. Although in my local machine I use **127.0.0.1:8000** for gunicorn and **127.0.0.1:5000** for nginx.

**Comment by Ahzam-Lathiya** [comment]
Hey @miguelgrinberg it works now. Since my gunicorn server is running at **127.0.0.1:8000** and I want my site to be accessible by the **server_address** only, not by adding any port number.
So the Nginx configuration is:
my file in /etc/nginx/sites-available/myapp

`server {
    listen 80;
    server_name **my_server_ip** **www.my_server_ip**;
    
    location / {
        include proxy_params;
        proxy_pass http://127.0.0.1:8000;
    }
   
    location /socket.io {
        include proxy_params;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass http://127.0.0.1:8000/socket.io;
    }
}`

**Comment by Ahzam-Lathiya** [comment]
Hey @miguelgrinberg turns out I'm not using nginx for caching my static files. Can you help me out a little bit? I've included the static path in the **/etc/nginx/sites-available/myapp** configuration file just like in the documentation, the css works even some other javascript functions work but the client fails to connect to the server via websocket.
In my javascript code:
`var socket = io.connect('ws://my_server_ip');`
and the console shows status (failed) for xhr requests.
I've searched and I've found that I should put the static files in /var/www/html ??
Though I'm still confused about how should I put my static files in the folder.
By the way my app directory has separate files for html, css and js like templates for html and static for css and js.

Thanks

**Comment by miguelgrinberg** [comment]
@Ahzam-Lathiya you need to show me what you did. I don't see how a static file configuration can affect your websocket connections.

**Comment by Ahzam-Lathiya** [comment]
@miguelgrinberg The static file problem is solved. Works like a charm now. I got a new problem now. All this time I had been running gunicorn with 1 worker with **gunicorn --worker-class eventlet -w 1 wsgi:app** . Now I'm running with 9 workers since my computer's got 4 cores and **(2*CPU) + 1** gives me 9. But with 9 workers my client can't connect to the server. Perhaps it can't figure out which one to connect. 
Here are the logs from my server starting. 
`gunicorn --worker-class eventlet -w 9 wsgi:app
[2020-07-16 18:01:08 +0500] [7444] [INFO] Starting gunicorn 20.0.4
[2020-07-16 18:01:08 +0500] [7444] [INFO] Listening at: http://127.0.0.1:8000 (7444)
[2020-07-16 18:01:08 +0500] [7444] [INFO] Using worker: eventlet
[2020-07-16 18:01:08 +0500] [7447] [INFO] Booting worker with pid: 7447
[2020-07-16 18:01:08 +0500] [7448] [INFO] Booting worker with pid: 7448
[2020-07-16 18:01:09 +0500] [7450] [INFO] Booting worker with pid: 7450
[2020-07-16 18:01:09 +0500] [7452] [INFO] Booting worker with pid: 7452
[2020-07-16 18:01:09 +0500] [7453] [INFO] Booting worker with pid: 7453
[2020-07-16 18:01:09 +0500] [7454] [INFO] Booting worker with pid: 7454
[2020-07-16 18:01:09 +0500] [7456] [INFO] Booting worker with pid: 7456
[2020-07-16 18:01:09 +0500] [7457] [INFO] Booting worker with pid: 7457
[2020-07-16 18:01:09 +0500] [7458] [INFO] Booting worker with pid: 7458`

And when I open **127.0.0.1:8000** and inspect, none of the websockets connection shows status 101. Although some polling connections show 200 while some show 400 even 500

Usually, with 1 worker there is 1 sometimes 2 polling requests and after being successful there is a websocket connection which shows 101 connection.

Thanks.

**Comment by miguelgrinberg** [comment]
You can't use multiple workers:

> Due to the limited load balancing algorithm used by gunicorn, it is not possible to use more than one worker process when using this web server. For that reason, all the examples above include the -w 1 option.

Docs here: https://flask-socketio.readthedocs.io/en/latest/#gunicorn-web-server

**Comment by miguelgrinberg** [comment]
I don't understand the question. What do you mean by "efficiently" here? Nginx is a pretty robust load balancer, and performs really well. What is your concern?

**Comment by jmoheywood** [comment]
Hi folks running into a very similar problem; using Eventlet with external API (sendgrid in my case) not working. Running Python 3.8.2 - should I really revert back to 3.6.9 to fix this or is there another solution?

**Comment by miguelgrinberg** [comment]
@jmoheywood this isn't related to this issue. There is an eventlet bug that causes your problem, so you may need to go back to Python 3.6 to avoid it.

**Comment by Ahzam-Lathiya** [comment]
hey @miguelgrinberg  can you tell me about some tools or techniques for testing the performance of my socketio app. Like how the app responds to 10000 concurrent requests. Some type of benchmark that gives me all the time spent and memory consumed.

Thanks

**Comment by miguelgrinberg** [comment]
@Ahzam-Lathiya I don't know any testing tool for Socket.IO well enough to recommend it. You can use the python-socketio client to build your own.

**Comment by Ahzam-Lathiya** [comment]
Hey @miguelgrinberg is there any way to store some info in a global variable throughout a single session?
I've used simply global variables outside functions but they end up being used across different sessions. I need it to store some info throughout the session for a single user.

**Comment by miguelgrinberg** [comment]
Sure, use the `session` variable from Flask.

**Comment by Ahzam-Lathiya** [comment]
Yeah I used the Session variable from **Flask_session**. It can store global variable in a list within same session. Now values from different sessions don't get mixed up.

**Comment by Ahzam-Lathiya** [comment]
Hello @miguelgrinberg. I want to ask how can I shift my application from this one to a complete backend as a service. Since currently this is rendering the html page on the same address I haven't made it such that the web page is hosted completely elsewhere and can communicate with the server.

I've tried to run a flask app that renders the HTML template and a socketio app with gunicorn which listens for the events. But I am not getting anywhere as the html display shows that the connection hasn't been made with the server.

Even my javascript is pointing to ws://127.0.0.1:8000 and my html rendering app runs on http://127.0.0.1:5000

**Comment by miguelgrinberg** [comment]
I'm not sure I understand. If your HTML backend is on port 5000 and your Socket.IO backend is on 8000, then you have to a) implement CORS, since you will be doing cross-origin requests, and b) define the correct connection URL that points to the Socket.IO backend and not the HTML backend.

**Comment by Ahzam-Lathiya** [comment]
`import eventlet
eventlet.monkey_patch()

from flask import Flask, render_template, request, session
from flask_socketio import SocketIO, join_room
from flask_cors import CORS
import requests

app = Flask(name)
app.config['SECRET_KEY'] = 'vnkdjnfjknfl1232#'
CORS(app)
socketio = SocketIO(app)

@app.route('/')
def sessions():
return render_template('textbox.html')

def messageReceived(methods=['GET', 'POST']):
print('message was received!!!')

@socketio.on('connect_event')
def handle_connect_event(json, methods=['GET', 'POST']):
print( 'received my event: ' + str(json) )

@socketio.on('send_event')
def handle_send_event(json, methods=['GET', 'POST']):
print('received my event: ' + str(json))

utterance = json["query"]
client = []

try:

    #store the client on basis of session id
    client.append(request.sid)

    #create a room on basis of session and join
    room = session.get('room')
    join_room(room)
    
    # YOUR-APP-ID: The App ID GUID found on the www.luis.ai Application Settings page.
    appId = '504c234a-bd45-4375-9abb-4f18e5444cfe'

    # YOUR-PREDICTION-KEY: Your LUIS authoring key, 32 character value.
    prediction_key = 'b36b154e90d54597b54590c405c6ac40'

    # YOUR-PREDICTION-ENDPOINT: Replace with your authoring key endpoint.
    # For example, "https://westus.api.cognitive.microsoft.com/"
    prediction_endpoint = 'https://westus.api.cognitive.microsoft.com/'

    # The headers to use in this REST call.
    headers = {
    }

    # The URL parameters to use in this REST call.
    params ={
        'query': utterance,
        'timezoneOffset': '0',
        'verbose': 'true',
        'show-all-intents': 'true',
        'spellCheck': 'false',
        'staging': 'false',
        'subscription-key': prediction_key
    }

    # Make the REST call.
    luis_response = requests.get(f'{prediction_endpoint}luis/prediction/v3.0/apps/{appId}/slots/production/predict', headers=headers, params=params)
    print(luis_response)

    intent = luis_response.json()['prediction']['topIntent']

    city = luis_response.json()['prediction']['entities']['geographyV2'][0]['value']

    weather_response = requests.get("http://api.openweathermap.org/data/2.5/weather?appid=149c9522d9216ca927a52354d76ec8e7&q={}".format(city) )

    desc = weather_response.json()['weather'][0]['description']

    temp = weather_response.json()['main']['temp']
    temp = temp - 273

    humid = weather_response.json()['main']['humidity']

    json["query"] = "The weather in {} is {} with a temperature of {}°C and humidity at {}%".format(city,desc, round(temp,3), humid)


    socketio.emit('my response', json, callback=messageReceived, room=client[0])

except Exception as e:
    print(e)
    json["query"] = "Please enter a correct location."

    socketio.emit('my response', json, callback=messageReceived)``

The code that I have mentioned works like a website that serves a rendered HTML page. Now i want to go one step further to make my websocket server available as an API which won't serve HTML pages itself but be accessible by any client as long as they are pointing to the same server and are authenticated.

I have configured CORS.  My issue is not of CORS but I want to make this like a service. Can I use flask_restful to make this a service.

**Comment by miguelgrinberg** [comment]
> I have configured CORS

For Flask only. You haven't for Socket.IO.

> My issue is not of CORS but I want to make this like a service

I don't understand what you expect to be different "like a service". You just return JSON instead of HTML. Have you seen any of the tutorials (some mine) on writing APIs?

**Comment by Ahzam-Lathiya** [comment]
You know what miguel configuring socketio for CORS makes it work. Now I can access the server without my server serving file, instead it now works like a backend service. A simple html UI without a server communicates to the service (making sure the javascript socket is pointed to the server)
I've written it like this:

`cors = CORS(app, resources={r"/*": {"origins": "*"}})

socketio = SocketIO(app, cors_allowed_origins="*")
`
Thanks alot.

**Comment by Ahzam-Lathiya** [comment]
Hey @miguelgrinberg Can you tell how to send cookies from the socketio to the client? I am sending it from flask make_response.send_cookie() method. The problem is that I have sent all the data through socketio.emit() and within that emit function I specify my json in which is the message to be sent. 
I want to make a mechanism that when the client connects, the server sends the response as well as the cookies.
This is the error I am getting:
`TypeError: Object of type 'Response' is not JSON serializable`

And this is the code for my connect event:
`@socketio.on('connect_event')
def handle_connect_event(json, methods=['GET', 'POST']):
    print( 'received my event: ' + str(json) )

    #record the client on basis of session id
    client = request.sid

    #create a room on basis of session and join
    room = session.get('room')
    join_room(room)

    session['dialogues'] = []
    print(json["cookie"])

    response = make_response('')

    """cookie_data = {'key'     :'crossite',
                   'value'   :'allow',
                   'samesite':'Lax',
                   'httponly':'False',
                   'secure'  :'False'
                  }
    """
    response.set_cookie('crossite',
                         value='allow',
                         samesite='Lax',
                         httponly='False',
                         secure='False')
    
    #print(type(response))
    print(request.args)

    json["cookie"] = response
    socketio.emit('receive_cookie', json, callback=messageReceived, room=client)
`
Thank you

**Comment by miguelgrinberg** [comment]
You can't send cookies via Socket.IO, it's not supported. WebSocket does not support cookies.

**Comment by Ahzam-Lathiya** [comment]
I just watched a video of yours the one in which you tell about how socketio can't access flask sessions and by turning manage_sessions=False in the socketio class , both the flask and socketio can share sessions.
So according to that I should send cookies before the websocket connection is made??

**Comment by miguelgrinberg** [comment]
Right. If you need to set a session cookie, that needs to be done through HTTP before the Socket.IO connection is made.

**Comment by Ahzam-Lathiya** [comment]
My goal is to make my app like a 3rd party service. In my app I have some flask routes and some socketio routes. I've checked that if I set all the send cookies functionality through the make_response and set_cookie method in a flask route and hit that endpoint I still don't get any cookies even I haven't triggered any socketio events.

`
@app.route('/', methods=['POST', 'GET'])
def sendcookie():
    response = make_response('')
    response.set_cookie('crossite',
                         value='bar',
                         httponly='',
                         samesite='',
                         secure=''
                       )
    print('Sending Cookie...')
    return response
`
I am hitting 127.0.0.1:8000 via curl this is what I get
`
curl: (6) Could not resolve host: POST
HTTP/1.1 200 OK
Server: gunicorn/20.0.4
Date: Wed, 02 Sep 2020 15:20:30 GMT
Connection: keep-alive
Content-Type: text/html; charset=utf-8
Content-Length: 0
Set-Cookie: crossite=bar; HttpOnly; Path=/; SameSite=Lax
Access-Control-Allow-Origin: *
Set-Cookie: session=df64cdc7-b69b-4c1d-a1b1-94e496496922; Expires=Sat, 03-Oct-2020 15:20:29 GMT; HttpOnly; Path=/
`

**Comment by miguelgrinberg** [comment]
I don't really have control over this, as it is your browser or client that decides whether a cookie needs to be sent or not. I suggest you debug this by looking at the requests in the network tab of your browser's console.

I'm also confused because the cookie that you are setting appears in your curl output, so it does appear to work.

**Comment by Ahzam-Lathiya** [comment]
It appears in the curl but when I try to access the cookie from the server via Javascript and try to console.log() it. I don't get anything even if I check application > cookies but still nothing is there. My chrome version is 84 something. Also chrome above 80 requires the 3rd party cookies to be set to **samesite=None and secure=True**. I guess this is upsetting the browser somehow.

**Comment by Ahzam-Lathiya** [comment]
Hey @miguelgrinberg Can you give me some advice or point me to some resources which implement **Redis** as a cache for this socketio server. I am looking to use redis to store session info as well as other info(user name, email, etc) which I will later store to a database.

**Comment by miguelgrinberg** [comment]
@Ahzam-Lathiya did you try the Flask-Session extension?

**Comment by Ahzam-Lathiya** [comment]
@miguelgrinberg Thanks for that. I am using the flask-session with the **app.config['SESSION_TYPE'] = 'filesystem'**. All the sessions are stored inside a folder in binaries. I am looking for implementing redis which is faster and can be a better option.
Thanks

**Comment by miguelgrinberg** [comment]
@Ahzam-Lathiya Flask-Session supports redis as well.

**Comment by Ahzam-Lathiya** [comment]
Hey @miguelgrinberg Can you point out how can I access the session variables across flask and socketio endpoints. I have initialized the socketio instance with manage_session = False and I have initialized some variables in the flask endpoint. They are accessed in the socketio endpoints but the data is not passed along. If I print them along with their type I get **<class 'NoneType'>!!None**. If I do this with manage_session=True then if I initialize a variable in one socketio endpoint then it is accessible to the other endpoint. But in this case I am not getting anything. I want to share session vars across flask and socketio endpoints.

Below are some of my flask and socketio endpoints:
`
@app.route('/get-cookies/', methods=["GET", "POST"] )
def setcookies():

    # sending the browser fingerprint
    fingerprint = request.get_json(force=True)
    print( fingerprint.keys() )
    response = make_response('')

    try:
        session['browserid'] = fingerprint['browserID']
        session['dialogues'] = []
        
        #this prints okay
        print(session['browserid'])

        response.set_cookie(key='id',
                            value= '3db4adj3d',
                            httponly=False,
                            samesite='Lax',
                            secure=False)

            

        
    except KeyError:
        print(f"KeyError: {fingerprint['browserID']}")
        
    finally:
        return response

@socketio.on('send_event')
def handle_send_event(json, methods=['GET', 'POST']):

    browserid = session.get('browserid')
    #this gets printed None
    print(browserid)

    dialogues = session.get('dialogues')
    # These both get printed None
    print( f"{type(dialogues)}!!{dialogues}" )
`
Thanks in advance

**Comment by miguelgrinberg** [comment]
@Ahzam-Lathiya there is an example in this repository that shows how to do this. I don't really see anything wrong in your code, you may want to test the example in this repo and adapt it to your needs.

**Comment by Ahzam-Lathiya** [comment]
@miguelgrinberg Can you point it out? I looked in the repo but I can't find anything that will solve my problem. I hope you understand my problem. I want to access session VARS from my flask endpoints throughout the socketio endpoints and vice versa. I've read your blogs and stuff. I know it's possible. Can you please be a little specific? Point out what my problem is.
Thanks

**Comment by miguelgrinberg** [comment]
https://github.com/miguelgrinberg/Flask-SocketIO/blob/master/example/sessions.py

**Comment by Ahzam-Lathiya** [comment]
Hello @miguelgrinberg . I am looking for a way to reconnect with the server using the same session id such that if someone refreshes the page the session terminates but again it is established using the same session id. Is there a possibility in socket.io or is this impossible?

Thank you

**Comment by miguelgrinberg** [comment]
@Ahzam-Lathiya no, session ids are randomly generated, they cannot be reused.

**Comment by gupta-shrinath-ril** [comment]
Thank you so much because of this issue I able to fix a weird issue of http requests failing by using gevent instead of eventlet 
`HTTPSConnectionPool(host='', port=123): Max retries exceeded with url: /user/login (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff9f40a750>: Failed to resolve '' ([Errno -3] Lookup timed out)"))`
