### ISSUE TITLE
Can't run flask socketio app

### ISSUE THREAD

**Issue by eleswarapu** [miguelgrinberg/Flask-SocketIO#1321]
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\gevent\_ffi\loop.py", line 269, in python_check_callback
    def python_check_callback(self, watcher_ptr): # pylint:disable=unused-argument
KeyboardInterrupt

Whenever I try to run, it stuck at "def python_check_callback(self, watcher_ptr): # pylint:disable=unused-argument". 

Code:
```python
from flask import Flask
from flask_socketio import SocketIO, send

app = Flask(__name__)
app.config ['SECRET_KEY'] = 'secret'
socketio =  SocketIO(app)

@socketio.on('message')
def handleMessage(msg):
    print('Message: ' + msg)
    send(msg, broadcast = True)


if __name__ == '__main__':
    socketio.run(app,debug=True)
```
Could you help get through this?

**Comment by miguelgrinberg** [comment]
I can run your code and it does  not hang for me. Are you doing anything specific from your client to cause it to hang?

**Comment by eleswarapu** [comment]
That code is in main.py and I can run normal flask apps using python main.py but when it comes to socketio app, it loads till Debugger PIN and then never responds.

**Comment by eleswarapu** [comment]
I just uninstalled gevent and then it ran. But its showing "WebSocket transport not available. Install eventlet or gevent and gevent-websocket for improved performance." Can I ignore it?

**Comment by miguelgrinberg** [comment]
Gevent is incompatible with the Flask reloader. Add gevent back, and then run with `debug=False`.

**Comment by Soontosh** [comment]
I know this is two years late but has anybody gotten a fix?

**Comment by Magnarks** [comment]
Sorry for reviving this old post, but now the same error happens to me, I was working fine, but from one moment to the next, I started getting this error
