### ISSUE TITLE
deploying flask-socketio app on heroku

### ISSUE THREAD

**Issue by riverscuomo** [miguelgrinberg/Flask-SocketIO#1322]
Hi Miguel,

I made a chat app with flask-socketio for my CS50 Web Programming class. It worked fine when I ran it locally and I received full credit for my assignment. But now I'd like to deploy the app on heroku. I haven't been able to figure out how to get it to run. Any help you could give me would be much appreciated.

If it's helpful, you can see my repository [here](https://github.com/riverscuomo/riverchat).

I'm using the latest flask socketio ( 4.3 ) and python 3.6, eventlet==0.25.2.

Server: 
  gunicorn/18.0

These two lines are at the top of my application file:
` import eventlet
eventlet.monkey_patch()`

I start the server like this:
`if __name__ == "__main__":
      socketio.run(app)`

Procfile:
 `web:gunicorn --worker-class eventlet -w 1 application:app`

When I load this old version of socket.io (as per my assignment)  `<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js"></script>`  and run the app locally, it works great.

But when I deploy the app to Heroku, after most of the page loads and I try to interact with it I get this response:
  
`Request Method: POST
  Status Code: 400 BAD REQUEST
  Host: murmuring-ridge-73542.herokuapp.com
  Origin: https://murmuring-ridge-73542.herokuapp.com
  Sec-Fetch-Dest: empty
  Sec-Fetch-Mode: cors
  EIO: 3
  transport: polling`

Moreover, when I load the latest socket.io (as per your example app)  `<script src="//cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.js" integrity="sha256-yr4fRk/GU1ehYJPAs8P4JlTgu0Hdsp4ZKrx8bDEDC3I=" crossorigin="anonymous"></script>`  my command terminal gets stuck in a loop of mostly:
 ` "GET /socket.io/?EIO=3&transport=polling&t=NCRpeWN&sid=74e55595d38a4cceb9f0f53d9c90281b HTTP/1.1" 200 -
It appears to be connecting over and over.`

If I include the server logger outputs, I see:

`c83ba63c162e4084b5c22cfef65e69b8: Sending packet MESSAGE data 2["connect"]
c83ba63c162e4084b5c22cfef65e69b8: Sending packet MESSAGE data 0
127.0.0.1 - - [04/Jul/2020 15:04:16] "GET /socket.io/?EIO=3&transport=polling&t=NCRr8tn HTTP/1.1" 200 -
0eecf42f2f37436abcecffb26ea22873: Sending packet OPEN data {'sid': '0eecf42f2f37436abcecffb26ea22873', 'upgrades': [], 'pingTimeout': 60000, 'pingInterval': 25000}
emitting event "connect" to all [/]
ae0aa34c957a4144b89a93aac90d2edd: Sending packet MESSAGE data 2["connect"]`

[This conversation regarding eventlet](https://github.com/eventlet/eventlet/issues/371) is over my head but I thought it might be relevant.

Sorry, I'm pretty lost and I'm not giving you much to go with. Please tell me if you have any ideas or if there's any other information I can give you.

Thank you so much.

**Comment by miguelgrinberg** [comment]
Any warnings in the log regarding the `https://murmuring-ridge-73542.herokuapp.com` origin not being allowed? You may need to explicitly allow this origin by passing it on the `cors_allowed_origins` option.

**Comment by abhipaiangle** [comment]
Hey Miguel, 
I am facing the same problem when I deploy it on heroku.
This is my Procfile:
web: gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 application:app

This is requirements.txt:
asgiref==3.2.10
certifi==2020.6.20
cffi==1.14.0
chardet==3.0.4
click==7.1.2
Flask==1.1.2
Flask-SocketIO==4.3.1
gevent==20.6.2
gevent-websocket==0.10.1
greenlet==0.4.16
gunicorn==20.0.4
idna==2.10
itsdangerous==1.1.0
Jinja2==2.11.2
MarkupSafe==1.1.1
numpy==1.18.5
pycparser==2.20
python-engineio==3.13.1
python-socketio==4.6.0
pytz==2020.1
redis==3.5.3
requests==2.24.0
six==1.15.0
sqlparse==0.3.1
urllib3==1.25.9
Werkzeug==1.0.1
zope.event==4.4
zope.interface==5.1.0


This is the javascript code I used to connect to WebSocket:

	if(window.location.protocol == "https:") {
		var ws_scheme = "wss://";
	} else {
		var ws_scheme = "ws://"
	};
	var socket = io.connect(ws_scheme + location.host + "/login");

"/login" route is my chat room in flask application.py

I am getting bad request(400) again and again.
It would be great if you can solve this issue.
Thanks

**Comment by abhipaiangle** [comment]
socket.io.js:4163 WebSocket connection to 'wss://app-pichat.herokuapp.com/socket.io/?EIO=3&transport=websocket&sid=ca7e885f85d2485bad2ea34e010cbf55' failed: WebSocket is closed before the connection is established.

socket.io.js:3511 POST https://app-pichat.herokuapp.com/socket.io/?EIO=3&transport=polling&t=NCUsMsm&sid=ca7e885f85d2485bad2ea34e010cbf55 400 (BAD REQUEST)

These are the errors that I am getting in the console.

**Comment by miguelgrinberg** [comment]
@abhipaiangle my comment above in this thread applies to you as well.

**Comment by riverscuomo** [comment]
Thank you for the response.

I happened to open your message on my phone and click the link to my app. I was shocked to find the app runs perfectly from there.  Then I tried a different computer. It runs perfectly there too. Let me investigate a little more and get back to you.

**Comment by abhipaiangle** [comment]
@riverscuomo Can you please share the code snippet of your procfile, main function in flask application, and the js code you used to connect to websocket if possible? Would be of great help. Thank you.

**Comment by riverscuomo** [comment]
Well, I'll be a monkey's uncle. It seems to be working now. The only remaining issue is that I have to use `socket.io/1.3.6/socket.io.min.js` instead of  `socket.io/2.2.0/socket.io.js`. Let me know if you have any thoughts about that.  Otherwise, as far as I'm concerned, you can close this issue. Thanks for everything.

@abhipaiangle , the 3 code snippets you requested are at the top of this thread, in my first post. In any case, here they are again:

I start the server like this:
`if __name__ == "__main__": `
`socketio.run(app)`

Procfile:
`web:gunicorn --worker-class eventlet -w 1 application:app`

I load this old version of socket.io 
`<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js"></script>`

Let me know if you  have any other questions.

**Comment by abhipaiangle** [comment]
Thanks for the snippets. The client is able to connect to socket. It can emit events and the events are recieved at the server too but either the server is not able to send event or the client is not able to recieve events. 

This is my heroku log


2020-07-05T18:04:09.850270+00:00 app[web.1]: 91667a3ce77740bdbe222cfead777793: Upgrade to websocket successful
2020-07-05T18:04:13.354008+00:00 app[web.1]: 91667a3ce77740bdbe222cfead777793: Received packet MESSAGE data 2/login,["send msg",{"user":"Abhishek","msg":"Hello","channel":"General"}]
2020-07-05T18:04:13.354172+00:00 app[web.1]: received event "send msg" from 91667a3ce77740bdbe222cfead777793 [/login]
2020-07-05T18:04:34.230812+00:00 app[web.1]: 91667a3ce77740bdbe222cfead777793: Received packet PING data None
2020-07-05T18:04:34.231278+00:00 app[web.1]: 91667a3ce77740bdbe222cfead777793: Sending packet PONG data None
2020-07-05T18:05:00.295580+00:00 app[web.1]: 91667a3ce77740bdbe222cfead777793: Received packet PING data None
2020-07-05T18:05:00.295735+00:00 app[web.1]: 91667a3ce77740bdbe222cfead777793: Sending packet PONG data None
2020-07-05T18:05:26.007983+00:00 app[web.1]: 91667a3ce77740bdbe222cfead777793: Received packet PING data None
2020-07-05T18:05:26.008135+00:00 app[web.1]: 91667a3ce77740bdbe222cfead777793: Sending packet PONG data None
2020-07-05T18:05:52.312034+00:00 app[web.1]: 91667a3ce77740bdbe222cfead777793: Received packet PING data None
2020-07-05T18:05:52.312203+00:00 app[web.1]: 91667a3ce77740bdbe222cfead777793: Sending packet PONG data None
2020-07-05T18:06:17.975105+00:00 app[web.1]: 91667a3ce77740bdbe222cfead777793: Received packet PING data None
2020-07-05T18:06:17.975219+00:00 app[web.1]: 91667a3ce77740bdbe222cfead777793: Sending packet PONG data None
2020-07-05T18:06:43.934948+00:00 app[web.1]: 91667a3ce77740bdbe222cfead777793: Received packet PING data None
2020-07-05T18:06:43.935153+00:00 app[web.1]: 91667a3ce77740bdbe222cfead777793: Sending packet PONG data None
2020-07-05T18:07:09.937774+00:00 app[web.1]: 91667a3ce77740bdbe222cfead777793: Received packet PING data None
2020-07-05T18:07:09.937943+00:00 app[web.1]: 91667a3ce77740bdbe222cfead777793: Sending packet PONG data None
2020-07-05T18:07:35.947814+00:00 app[web.1]: 91667a3ce77740bdbe222cfead777793: Received packet PING data None
2020-07-05T18:07:35.947973+00:00 app[web.1]: 91667a3ce77740bdbe222cfead777793: Sending packet PONG data None
2020-07-05T18:08:01.938639+00:00 app[web.1]: 91667a3ce77740bdbe222cfead777793: Received packet PING data None
2020-07-05T18:08:01.938956+00:00 app[web.1]: 91667a3ce77740bdbe222cfead777793: Sending packet PONG data None
2020-07-05T18:08:27.937981+00:00 app[web.1]: 91667a3ce77740bdbe222cfead777793: Received packet PING data None
2020-07-05T18:08:27.938249+00:00 app[web.1]: 91667a3ce77740bdbe222cfead777793: Sending packet PONG data None

**Comment by miguelgrinberg** [comment]
@abhipaiangle your log does not show your server application sending anything out to clients. Any chance this is a logic bug in your code?

**Comment by abhipaiangle** [comment]
```
import eventlet
import requests
import time
from flask import Flask , render_template, session, request, jsonify
from flask_socketio import SocketIO, send, emit
eventlet.monkey_patch()
app = Flask(__name__)
app.config['SECRET_KEY'] = 'mysecret'
socketio = SocketIO(app, logger=True, engineio_logger=True, always_connect=True)
channels=[{"ch":"General","key":""}]
dname=""
msgs=[]
channel="General"
users=[]
@app.route("/")
def index():
    return render_template('index.html')

@app.route("/login",methods=["GET","POST"])
def login():
    dname=request.form.get('dname')
    password=request.form.get('password')
    found = 0
    for i in range(len(users)):
        if users[i]["dname"] == dname:
            found = 1
            if users[i]["password"] == password:                
                channel= users[i]["channel"]
                return render_template('login.html', dname= dname ,channels=channels,channel=channel)
            else:
                return render_template('index.html',message="Looks like the Display Name has been already taken or you have entered incorrect password")

    if found == 0:
        if dname == "" or password == "":
            return render_template('index.html',message="Display Name or Password cannot be empty")
        else:
            users.append({'dname': dname, 'password':password, 'channel': "General"})
            return render_template('login.html', dname= dname ,channels=channels,channel="General")

@socketio.on('send msg')
def handleMessage(data):
        print(data)
        newdata={'user': data["user"],'msg':data["msg"],'time':time.strftime('%b %d %H:%M:%S',time.localtime()),'channel':data["channel"]}
        if len([msgs[i] for i in range(len(msgs)) if msgs[i]["channel"]== data["channel"] ])>100:
            for i in range(len(msgs)):
                if msgs[i]["channel"] == data["channel"]:
                    msgs.pop(i)
                    break
        msgs.append(newdata)
        emit('recieved msg',newdata, broadcast = True )
        

@socketio.on('channel created')
def addChannel(channel):
    if channel not in channels:
        channels.append({"ch":channel["ch"],"key":channel["key"]})   
        emit('channel recieved',{"channels":channels} , brodcast = True)
        

@socketio.on('join')
def join(_data):
    if _data["channel"] in channels or _data["channel"]["key"] == "yvh8273vrhtd^&":
        print(_data["user"] ,"has joined channel", _data["channel"]["ch"])
        data={"data":_data,"msgs":[msgs[i] for i in range(len(msgs)) if msgs[i]["channel"]==_data["channel"]["ch"]]}
        emit('joined',data, brodcast = True)
        

@socketio.on('logout_reload')
def user_append(user):
    for i in range(len(users)):
        if users[i]["dname"]==user["dname"]:
            password=users[i]["password"]
            users.pop(i)
            user={"dname":user["dname"],"password":password ,"channel":user["channel"]}
            users.append(user)

if __name__ == '__main__':
	socketio.run(app)

```

I did not find any problem with this.

**Comment by abhipaiangle** [comment]
Hey, the app started working. I removed the monkey patch, changed the js filename to socketio.js( I don't know how relevant is this), and ran it locally once. It worked. Thanks.
