### ISSUE TITLE
Passing a variable between two socket instances through the session

### ISSUE THREAD

**Issue by Ash4669** [miguelgrinberg/Flask-SocketIO#1323]
Hello Miguel,

I'm currently creating an online card game where players can set up their own game rooms and set a password to lock the room down. It's the password that I'm struggling to pass through the backend. On the main page, they will enter an optional password which will be sent via socket back to the server side and redirect the user to the new page. Through the emit, I store the value in the session  in the server side and when on the next page, I try to pull it out of the session within another socket on server side again. The trace is down below to help explain my point and sorry if I haven't been clear.

I saw your video on using flask_session to use the original session and not the forked socket session and set my code up as you specified in the video but it isn't working.

Do you know why my code may not be persisting the value? I tried putting in a wait just in case it took time to store it, but this didn't fix it.

If it is not possible to do this, I may use the database to persist the password and just keep overwriting it, but I hope not to need to.

Thank you for your help.

__\_\_init\_\_.py__
```
...
sess = Session()
...
sess.init_app(app)
...
if __name__ == '__main__':
    socketio.run(app, manage_session=False)
...
```

// Clients on client side emit this after clicking 'Host Game' and entering a password.
__HostPage.js__
```
...
let password = document.getElementById("password-input").value;
socket.emit('host game send', password);
...
```

__chase_the_ace_redirects.py__
```
...
@socketio.on('host game send')
def generateAndHostRedirect(password, lives):
session['ChaseTheAcePassword'] = password
...
# Emit the redirect for the client to redirect with javascript.
emit('redirect', {'url': url_for('chase_the_ace.chase_the_ace_instance', roomId=roomId)})
```

__chase_the_ace.py__
```
...
@chase_the_ace.route('/play/chase_the_ace/<roomId>')
def chase_the_ace_instance(roomId):

# Saving the game id into the session.
session['roomId'] = roomId
return render_template('games/chase_the_ace/game.html', roomId = roomId)
...
```

__GamePage.js__
```
...
// Triggering server response to someone joining the game.
socket.on('connect', function()
{
    socket.emit('join chase the ace');
});
...
```

__chase_the_ace_gameplay.py__
```
...
# Managing players joining the game.
@socketio.on('join chase the ace')
def onJoin():

# Generating a player id for the player.
session['playerId'] = generatePlayerId()
...
```

**Comment by miguelgrinberg** [comment]
If I understand this correctly, the problem is that you change the page in between setting up the room and entering the room. When you change the page the client disconnects, so when it makes a connection on the second page the server sees it as a different client with a brand new session.

One option that you have is to use a single page app, which would preserve the socket connection. Another is to store your user data in a database under the username.

**Comment by Ash4669** [comment]
Thank you for responding so quickly. 

I thought so but weren't entirely sure because I was hoping I could store it in the socket session that is using the same session as the html and then when the new instance is created, it copies that same session or uses it without a continuity issue.

I'll look at the single page application method possibly, bit I weren't sure what the standard was with these kinds of sites.

The db option also seems quite easy to implement so I'll debate the two. What would you recommend? Is having multiple socket sessions on a site bad practice?

Thanks, 

Ashley

**Comment by miguelgrinberg** [comment]
There is actually a third option, more in line with what you are asking. If you use server-side sessions (via the Flask-Session) extension, then changes you made in Socket.IO routes will be saved immediately to the server, and shared on HTTP routes, even if you change the page. This is in that video that I have on YouTube, so check it out again if you need a refresher.

**Comment by Ash4669** [comment]
I've fixed the issue. It works fine now. I wasn't even running the line of code
```
if __name__ == '__main__':
    socketio.run(app, manage_session=False)
```
Because I wasn running from using a create_app() method. I instead changed the
```
socketio.init_app(app)
```
to
```
socketio.init_app(app, manage_session=False)
```
and put Session(app) above the line instead of below it. It now all runs on the same session and the passwords are working as well.

Thank you for your help!

Ashley
