### ISSUE TITLE
changing username in the server side

### ISSUE THREAD

**Issue by fdq09eca** [miguelgrinberg/Flask-SocketIO#1326]
Hi,

I have a question of changing `username` in the backend when `username` could be the same, the following is some background.

1. Everyone enters the chatroom will be assigned a default name `untitled user` _if they did not change their name previously_
2. As soon as they enter, the socket will be connected and emit their default name to the backend
3. The backend will generate a `user` instance with respect to their `username` i.e. `user = USER(username)` and append them to a `list`

I want to allow them to change their name in the frontend but **I am stuck at targeting the respective `user` in the `list` as some of them share the same name e.g. `untitled user`.** 

I tried the following
- Using `request.sid` to identify the respective user
  - It won't be appropriate since the `sid` will be different if they re-enter the room 
- Storing an ID, such as counter, in the client-side `localStorage` like the `username`.
  - It kind of works, but It won't be appropriate as the client may able to edit and accidentally change others' `username`.

Any better suggestion? Thank you.

**Comment by miguelgrinberg** [comment]
If the users don't authenticate you will not have a foolproof way of identifying users.

You can use a cookie with a uniquely generated id, that in my opinion is better than local storage, but still, the user can clear their cookies whenever they want.

**Comment by fdq09eca** [comment]
> If the users don't authenticate you will not have a foolproof way of identifying users.
> 
> You can use a cookie with a uniquely generated id, that in my opinion is better than local storage, but still, the user can clear their cookies whenever they want.

So if I would like to go with the cookie way, should I just use the following code when I see a new connection?
```python
seesion['sid'] = some_unique_id
```

Sorry I m very new to web programming

**Comment by miguelgrinberg** [comment]
No, you cannot change the `sid`. What a user connects for the first time the server can generate an id for them and send it in an event. The client can then add a cookie with this id to remember it.

When the client connects again the cookie will be sent along with the connection request, so the server will recognize that this is a previous user.

**Comment by fdq09eca** [comment]
> No, you cannot change the `sid`. What a user connects for the first time the server can generate an id for them and send it in an event. The client can then add a cookie with this id to remember it.
> 
> When the client connects again the cookie will be sent along with the connection request, so the server will recognize that this is a previous user.

so how may I practically give them a cookie without using session?

```python
import os
from flask import Flask, render_template, request, redirect, url_for, session, jsonify
from flask_socketio import SocketIO, emit

app = Flask(__name__)
app.config["SECRET_KEY"] = os.getenv("SECRET_KEY")
socketio = SocketIO(app)


class USER:
    def __init__(self, username, channel=None):
        self.username = username
        self.channel = channel
        self.sid = request.sid
        print(self)

    def rename(self, new_username):
        self.username = new_username

    def __str__(self):
        return f'{self.username}, {self.sid}'


class userManager:
    users = []

    def add(user):
        userManager.users.append(user)

    def rename(self, new_username, sid):
        print([u.username for u in userManager.users])


@app.route("/")
def index():
    return render_template('index.html')


@socketio.on('user-arrived-lobby')
def welcome_bdc(data):
    username = data['default-username']
    user = USER(username)
    userManager.add(user)
    emit('welcome-bdc', {'user': user.username, 'sid': user.sid}, broadcast=True)
    print(f'emit-welcome-bdc for {username}')
```

for example, the above code block I sent back the frontend a sid for them to store in the client's local storage, but I do not consider it is a cookie?

**Comment by miguelgrinberg** [comment]
> so how may I practically give them a cookie without using session?

You can't send a cookie from the server. Using the user session only works if you have server-side sessions.

What I was actually thinking is that the server will send this unique id in an event, and then the client adds the cookie on their own.

**Comment by fdq09eca** [comment]
I had another workaround after a bit of thinking. I stored the username in the client in local storage, give them a request.sid whenever they check-in the site. the sid will be set to the client local storage every time when they re-enter/open another browser. so the workflow becomes the following:

1. If the client changes their name, the frontend will emit previous username, new-username, and the sid to the backend 
2. The backend will use the sid to address the client user instance 
3. update their username. 

It kind of work as expected. But I do not understand what good is using cookie instead of local storage on this occasion?
## frontend-html
```html
{% extends "layout.html" %} {% block title %}index{% endblock %} {% block
content %}
<div>
  <div>
    <input
      type="text"
      name="username"
      id="username-input"
      placeholder="what is your name"
    />
    <button id="btn-sumbit-username">Submit</button>
  </div>
  <div>
    <h1 id="username"></h1>
  </div>
</div>
<div>
  <ul id="sys-msg"></ul>
</div>
{% endblock %} {% block js %}
<script
  type="text/javascript"
  src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js"
></script>
<script src="{{ url_for('static', filename = 'js/username.js') }}"></script>
{% endblock %}
```

## frontend-js
```js
function get_username() {
  /* default username to Untitled User */
  if (!localStorage.getItem("username")) {
    localStorage.setItem("username", "Untitled User");
  }
  // const username = localStorage.getItem("username");
  return localStorage.getItem("username");
}

function set_fields() {
  document.querySelector("#username-input").value = "";
  document.querySelector("#username").innerHTML = `Hi, ${get_username()}`;
}

function main() {
  var socket = io.connect(
    location.protocol + "//" + document.domain + ":" + location.port
  );

  socket.on("connect", () => {
    console.log("socket connect!");
    socket.emit("user-arrived-lobby", { "default-username": get_username() });
  });
  set_fields();
  document.querySelector("#btn-sumbit-username").onclick = () => {
    const new_username = document.querySelector("#username-input").value;
    previous_username = get_username();
    localStorage.setItem("username", new_username);

    set_fields();
    socket.emit("user-rename", {
      "new-username": new_username,
      "previous-username": previous_username,
      "user-id": localStorage.getItem("user-id"),
    });
  };

  socket.on("welcome-bdc", (data) => {
    localStorage.setItem("user-id", data["sid"]);
    const li = document.createElement("li");
    li.innerHTML = `${
      data["user"]
    } just entered the lobby, ${localStorage.getItem("user-id")}, backend id: ${
      data["sid"]
    }`;
    document.querySelector("#sys-msg").append(li);
  });

  socket.on("user-rename-bdc", (data) => {
    const li = document.createElement("li");
    li.innerHTML = `${data["previous_username"]} changed their username to ${data["new_username"]}`;
    document.querySelector("#sys-msg").append(li);
  });
}

main();

```
## backend-flask
```python
import os
from flask import Flask, render_template, request, redirect, url_for, session, jsonify
from flask_socketio import SocketIO, emit

app = Flask(__name__)
app.config["SECRET_KEY"] = os.getenv("SECRET_KEY")
socketio = SocketIO(app)


class USER:
    def __init__(self, username, channel=None):
        self.username = username
        self.channel = channel
        self.id = request.sid
        print(self)

    def rename(self, new_username):
        self.username = new_username

    def __str__(self):
        return f'{self.username}, {self.id}'


class userManager:
    users = []

    def add(user):
        userManager.users.append(user)

    def rename(new_username, user_id):
        for u in userManager.users:
            if u.id == user_id:
                u.username = new_username
                # u.rename(new_username)
        print(f'current users : {[u.username for u in userManager.users]}')


@app.route("/")
def index():
    return render_template('index.html')


@socketio.on('user-arrived-lobby')
def welcome_bdc(data):
    username = data['default-username']
    user = USER(username)
    userManager.add(user)
    emit('welcome-bdc', {'user': username, 'sid': user.id}, broadcast=True)
    print(f'emit-welcome-bdc for {username}')


@socketio.on('user-rename')
def rename_bdc(data):
    previous_username = data['previous-username']
    new_username = data['new-username']
    user_id = data['user-id']
    userManager.rename(new_username, user_id)
    payload = {
        'previous_username': previous_username,
        'new_username': new_username
    }

    emit('user-rename-bdc', payload, broadcast=True)
    print(
        f'emit-rename-bdc for {new_username} (previously: {previous_username})')
```

**Comment by miguelgrinberg** [comment]
First of all, there is no need to store and send the `sid`, since this is included in all packets. The server can always find out what is the `sid` of the client with `request.sid`.

Second, how does your solution work when the client is disconnected and reconnects, like for example by refreshing the page? I thought that was the main thing you wanted to handle. That is the only reason I suggested you generate an id and put it in a cookie. If you don't care about that, then just pass the old and new names and that's it.

**Comment by fdq09eca** [comment]
> First of all, there is no need to store and send the `sid`, since this is included in all packets. The server can always find out what is the `sid` of the client with `request.sid`.

The purpose of `request.sid` is an identifier. coz whenever a user will be appended to a list in the backend whenever they check-in. Since they are allowed to share the same name, I can only change their name rely on their assigned. which is the reason for the `userManager.rename()`
```python
class userManager:
    users = []

    def add(user):
        userManager.users.append(user)

    def rename(new_username, user_id):
        for u in userManager.users:
            if u.id == user_id:
                u.username = new_username
                # u.rename(new_username)
        print(f'current users : {[u.username for u in userManager.users]}')
```

> Second, how does your solution work when the client is disconnected and reconnects, like for example by refreshing the page? 

If the refresh the page they will be considered logout and login again. Sorry, I still did not write the handler for poping the respective user in the list.

>I thought that was the main thing you wanted to handle. That is the only reason I suggested you generate an id and put it in a cookie. If you don't care about that, then just pass the old and new names and that's it.

passing the old and new name without an `id`-liked index will not be possible for me to locate the user in the list.. that is the main thing I wanted to solve.

**Comment by miguelgrinberg** [comment]
If your solution works, then great. No need to listen to me anymore. You said (and I'm copying you here) "emit previous username, new-username, and the sid". All I'm saying is that the `sid` does not need to be sent, because all packets carry the sid. Now you switch to say "user_id", so maybe this was just a mistake when you described your solution. In any case, you seem to have things under control, so great.
