### ISSUE TITLE
Flask-socketIO keeps polling instead of communicating with websockets.

### ISSUE THREAD

**Issue by aaronchoi5** [miguelgrinberg/Flask-SocketIO#1327]
I've read the documentation and set it up according to the instructions but it keeps polling instead of using websockets. Is there something I'm doing wrong? I've installed eventlet too since Flask doesn't natively support websockets. Below is python backend code
```
app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app)
socketio.init_app(app, cors_allowed_origins="*")

app.config['MONGODB_HOST'] = 'mongodb://localhost:27017/examples'

db.init_app(app)
CORS(app, support_credentials=True)

@socketio.on('connect')
def test_connect():
	print("blah")
	emit('after connect',  {'data':'Lets dance'})

if __name__ == '__main__':
    socketio.run(app)
```
Below is js code used in a vue component. 
import io from 'socket.io-client';` 

...
          
            console.log("yooo");
            this.connection = io.connect('http://127.0.0.1:5000');

            this.connection.on('connect', () => {
              console.log('Successfully connected!');
            });

            this.connection.onmessage = function(event) {
                console.log(event);
            }`

logs from server side:
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Server initialized for threading.
Server initialized for threading.
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
8b33fde3d0134ea5a0fc1ac649981a79: Sending packet OPEN data {'sid': '8b33fde3d0134ea5a0fc1ac649981a79', 'upgrades': [], 'pingTimeout': 60000, 'pingInterval': 25000}
blah
emitting event "message" to 8b33fde3d0134ea5a0fc1ac649981a79 [/]
8b33fde3d0134ea5a0fc1ac649981a79: Sending packet MESSAGE data 2["message","after connect"]
after
8b33fde3d0134ea5a0fc1ac649981a79: Sending packet MESSAGE data 0
127.0.0.1 - - [14/Jul/2020 09:14:21] "[37mGET /socket.io/?EIO=3&transport=polling&t=NDDTZw0 HTTP/1.1[0m" 200 -
39f2641435ef4e2f9670343460d1ba52: Sending packet OPEN data {'sid': '39f2641435ef4e2f9670343460d1ba52', 'upgrades': [], 'pingTimeout': 60000, 'pingInterval': 25000}
blah
emitting event "message" to 39f2641435ef4e2f9670343460d1ba52 [/]
39f2641435ef4e2f9670343460d1ba52: Sending packet MESSAGE data 2["message","after connect"]
after
39f2641435ef4e2f9670343460d1ba52: Sending packet MESSAGE data 0
127.0.0.1 - - [14/Jul/2020 09:14:31] "[37mGET /socket.io/?EIO=3&transport=polling&t=NDDTcHV HTTP/1.1[0m" 200 -
39f2641435ef4e2f9670343460d1ba52: Received packet PING data None
39f2641435ef4e2f9670343460d1ba52: Sending packet PONG data None
127.0.0.1 - - [14/Jul/2020 09:14:56] "[37mGET /socket.io/?EIO=3&transport=polling&t=NDDTcK1&sid=39f2641435ef4e2f9670343460d1ba52 HTTP/1.1[0m" 200 -
127.0.0.1 - - [14/Jul/2020 09:14:56] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NDDTiQe&sid=39f2641435ef4e2f9670343460d1ba52 HTTP/1.1[0m" 200 -
39f2641435ef4e2f9670343460d1ba52: Received packet PING data None
39f2641435ef4e2f9670343460d1ba52: Sending packet PONG data None
127.0.0.1 - - [14/Jul/2020 09:15:21] "[37mGET /socket.io/?EIO=3&transport=polling&t=NDDTiQr&sid=39f2641435ef4e2f9670343460d1ba52 HTTP/1.1[0m" 200 -
127.0.0.1 - - [14/Jul/2020 09:15:21] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NDDToXU&sid=39f2641435ef4e2f9670343460d1ba52 HTTP/1.1[0m" 200 -
8b33fde3d0134ea5a0fc1ac649981a79: Client is gone, closing socket
8b33fde3d0134ea5a0fc1ac649981a79: Client is gone, closing socket
127.0.0.1 - - [14/Jul/2020 09:15:21] "[37mGET /socket.io/?EIO=3&transport=polling&t=NDDTZwE&sid=8b33fde3d0134ea5a0fc1ac649981a79 HTTP/1.1[0m" 200 -
39f2641435ef4e2f9670343460d1ba52: Received packet PING data None
39f2641435ef4e2f9670343460d1ba52: Sending packet PONG data None
127.0.0.1 - - [14/Jul/2020 09:15:46] "[37mGET /socket.io/?EIO=3&transport=polling&t=NDDToXm&sid=39f2641435ef4e2f9670343460d1ba52 HTTP/1.1[0m" 200 -
127.0.0.1 - - [14/Jul/2020 09:15:46] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NDDTueQ&sid=39f2641435ef4e2f9670343460d1ba52 HTTP/1.1[0m" 200 -
39f2641435ef4e2f9670343460d1ba52: Received packet PING data None
39f2641435ef4e2f9670343460d1ba52: Sending packet PONG data None
127.0.0.1 - - [14/Jul/2020 09:16:11] "[37mGET /socket.io/?EIO=3&transport=polling&t=NDDTuec&sid=39f2641435ef4e2f9670343460d1ba52 HTTP/1.1[0m" 200 -
127.0.0.1 - - [14/Jul/2020 09:16:11] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NDDT-lF&sid=39f2641435ef4e2f9670343460d1ba52 HTTP/1.1[0m" 200 -

**Comment by miguelgrinberg** [comment]
Which websocket server did you install?

**Comment by miguelgrinberg** [comment]
The issue template asked for logs and you haven't provided them. Without the logs it is impossible for me to say what's going on.

**Comment by aaronchoi5** [comment]
Sorry! I added my logs from the server side. Client doesn't really have anything I can see.

**Comment by miguelgrinberg** [comment]
This is the problem:

    Server initialized for threading.

Your server is not initializing for eventlet. You said you have the eventlet package installed? Can you double check?

**Comment by aaronchoi5** [comment]
Yes the eventlet package is installed. I did use a virtual environment if that makes a difference.

**Comment by miguelgrinberg** [comment]
@aaronchoi5 Well, your logs say otherwise. Are you passing the `async_mode` argument when you create your server? If you pass it, it needs to be set to `eventlet`.

**Comment by aaronchoi5** [comment]
Thanks for the quick responses! I added the async_mode to eventlet and got an exception: 
raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
so then i read through old issues and imported eventlet and eventlet.wsgi. I then addedthis "eventlet.wsgi.server(eventlet.listen(('', 8026)), app)"

I get the following logs
```
(venv) C:\Users\aaron\Documents\Code\Platoon>flask run
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Server initialized for eventlet.
(7928) wsgi starting up on http://0.0.0.0:8026
```

The server just hangs there without doing anything now. Sorry for my ignorance but is there something I missed in deploying it?

**Comment by miguelgrinberg** [comment]
Yes, okay, now I see. You are using the Flask development web server. See the docs on how to start the Socket.IO server: https://flask-socketio.readthedocs.io/en/latest/#initialization.

**Comment by aaronchoi5** [comment]
Oh I see so I had to use python -filename instead of flask run. I think it could be very helpful to add a little example on how to start the Socket.IO server. Thanks for helping me sort the issue out!
