### ISSUE TITLE
CPU-intensive tasks and socketio.sleep(0)

### ISSUE THREAD

**Issue by a35026** [miguelgrinberg/Flask-SocketIO#1328]
@miguelgrinberg [Connection over SSL](https://github.com/miguelgrinberg/Flask-SocketIO/issues/1304) works as expected, thank you so much for the hints!

This is NOT directly related to Flask-SocketIO but unfortunately IS affecting its workflow.
I get the following output after several minutes of CPU-intensive task (ffmpeg conversion):
```
Tail of FFmpeg output.....
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=  240 fps=0.0 q=-1.0 Lsize=     130kB time=00:00:09.62 bitrate= 110.8kbits/s speed=3.38e+03x
video:42kB audio:80kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 6.949782%
0c2542e219d04034a0cc5a342aa3ec8a: Client is gone, closing socket
0c2542e219d04034a0cc5a342aa3ec8a: Received packet PING data None
Receive error -- socket is closed
```
After that I can see the process of establishing a new connection as socketio normally does.
I guess this is caused by busy CPU skipping polling requests during ffmpeg operations.

I suppose that `socketio.sleep(0.1)` might help me in this case but don't understand how to apply it.
Would be great if you could recommend how to call it in such cases
I call ffmpeg like this:
```
p = subprocess.Popen(
    ['/usr/bin/ffmpeg',
        '-ss', values.get('delay'),
        '-i', f'/home/user/video/{values.get("filename")}',
        '-vf', 'crop=in_h',
        f'/home/user/video/p{values.get("created")}.{values.get("ext")}'
    ])
p.wait()
```
It also relates to any other processes where you can't directly control the flow.
Maybe I should change `ping_timeout, ping_interval` but the problem here is that I can't be sure how much time it would take ffmpeg to encode videos, since I can't really control input data sizes.

**Comment by miguelgrinberg** [comment]
Did you monkey patch the standard library? Anything related to subprocesses is blocking. Eventlet provides non-blocking alternatives that in many cases work well. You can either use the eventlet versions directly, or else tell eventlet to monkey-patch the standard library so that all these blocking things are redirected to eventlet.

**Comment by a35026** [comment]
Frankly speaking, I haven't used it so far, this is how I import it:
```
from flask import Flask
from flask_socketio import SocketIO, emit
from google.cloud import firestore, storage
import eventlet
from skimage import img_as_ubyte
import imageio
import numpy as np
```
I guess you might have already done something of similar nature in one of your many applications. Meaning that I would be obliged if you could just point me to any similar cases utilizing eventlet non-blocking alternatives.

Side note: I plan to build kind of a queue system, so I believe multi-threading with non-blocking behavior and sending data to different clients/channels is what I want to learn next. Thank you

**Comment by miguelgrinberg** [comment]
I don't have any examples to share, unfortunately, because I try not to mix CPU intensive tasks with web applications. You can read about monkey patching here: https://eventlet.net/doc/patching.html.

Bit of a warning, from looking at your dependencies I suspect it isn't going to be easy for you to integrate with eventlet.

**Comment by a35026** [comment]
Thank you for hints! I have utilized `asyncio.create_subprocess_shell()` as it suits my mere needs.
