### ISSUE TITLE
How can background tasks be assigned to a client?

### ISSUE THREAD

**Issue by ShawnChen-dev** [miguelgrinberg/Flask-SocketIO#1330]
What I need now is:
The front end sends a message to the server through an event, and the server parses the message, and then continuously pushes the required data to the client.

The current practice is to push data to the front end through background tasks, but all clients listening to this event will receive this message.

How to get each client connection and send the message to the designated client？

event:
```
@socketio.on('my_event', namespace='/test')
def mtest_message(message):
    global thread
    with thread_lock:
        if thread is None:
            thread = socketio.start_background_task(background_thread)
    emit('my_response',
         {'data': message['data'], 'count': session['receive_count']}, broadcast=True)
```

background_thread
```
def background_thread():
    """Example of how to send server generated events to clients."""
    count = 0

    while True:
        global socket_data
        socketio.sleep(5)
        count += 1
        socketio.emit('my_response',
                 {'data': str(socket_data), 'count': count},
                 namespace='/test')
```

**Comment by miguelgrinberg** [comment]
Pass `request.sid` to your background thread when you start it. Then add `room=sid` to the emits in the thread.

**Comment by ShawnChen-dev** [comment]
> `request.sid`启动时传递给您的后台线程。然后添加`room=sid`到线程中的发射。

Thank you very much for your advice
But how can I end this background task or stop sending messages to this room? How can I control this background task

**Comment by miguelgrinberg** [comment]
@ShawnChen-dev how you manage your background task has no relation to this package. You can use any standard techniques to manage and terminate your thread.
