### ISSUE TITLE
How to block all scanners requests except for /socket.io/

### ISSUE THREAD

**Issue by a35026** [miguelgrinberg/Flask-SocketIO#1332]
In logs I can see a lot of flying by requests from botnet scanners and alike:
```
43.226.152.131,127.0.0.1 - - [20/Jul/2020 14:41:20] "GET /wp-content/plugins/portable-phpmyadmin/wp-pma-mod/index.php HTTP/1.1" 404 356 0.000558
(1805) accepted ('127.0.0.1', 34590)
43.226.152.131,127.0.0.1 - - [20/Jul/2020 14:41:22] "GET /sqladmin/index.php HTTP/1.1" 404 356 0.000541
(1805) accepted ('127.0.0.1', 34592)
43.226.152.131,127.0.0.1 - - [20/Jul/2020 14:41:22] "GET /sql/index.php HTTP/1.1" 404 356 0.000506
(1805) accepted ('127.0.0.1', 34594)
43.226.152.131,127.0.0.1 - - [20/Jul/2020 14:41:23] "GET /SQL/index.php HTTP/1.1" 404 356 0.000543
(1805) accepted ('127.0.0.1', 34596)
43.226.152.131,127.0.0.1 - - [20/Jul/2020 14:41:23] "GET /websql/index.php HTTP/1.1" 404 356 0.000570
(1805) accepted ('127.0.0.1', 34598)
43.226.152.131,127.0.0.1 - - [20/Jul/2020 14:41:23] "GET /MySQLAdmin/index.php HTTP/1.1" 404 356 0.000566
(1805) accepted ('127.0.0.1', 34600)
43.226.152.131,127.0.0.1 - - [20/Jul/2020 14:41:24] "GET /manager/html HTTP/1.1" 404 356 0.000642
(1805) accepted ('127.0.0.1', 34602)
43.226.152.131,127.0.0.1 - - [20/Jul/2020 14:41:24] "POST /axis2/axis2-admin/login HTTP/1.1" 404 356 0.000606
(1805) accepted ('127.0.0.1', 34610)
128.14.134.134,127.0.0.1 - - [20/Jul/2020 14:43:12] "GET / HTTP/1.1" 404 356 0.000507
```
I communicate with my Flask app through React frontend using messages only, not routes.
Recently I also added `cors_allowed_origins=['https://website', 'http://localhost:8080']` in order to expose Flask app (which is btw behind NGINX proxy) to my website and for development purposes.  

What's the best practice to cut absolutely everything except my own requests?  
For obviously hostile requests like pinging SQL or WP admin pages - as early as possible?
Even before SocketIO will have to deal with it using CORS, etc.?

**Comment by miguelgrinberg** [comment]
Do you have a reverse proxy in your setup? You may want to add nginx, which would return these 404s directly before they reach the Python server. That's really the best you can do, you can't prevent random requests from arriving.

**Comment by a35026** [comment]
This is really out of SocketIO scope, but was worth to ask you!
Yes, I do have a reverse proxy like this:
```nginx
upstream flaskapp {
  server 127.0.0.1:5000 fail_timeout=0;
}

server {
  listen 80;
  server_name _;
  location / {
    add_header "Access-Control-Allow-Origin" "http://localhost, https://website";
    try_files $uri @proxy_to_app;
  }

  location @proxy_to_app {
    proxy_pass http://flaskapp;
    proxy_http_version 1.1;
    proxy_buffering off;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $http_host;
    proxy_redirect off;
  }
} 

server {
  listen 443;

  ssl on;
  ssl_certificate      /etc/letsencrypt/live/server/fullchain.pem;
  ssl_certificate_key  /etc/letsencrypt/live/server/privkey.pem;
  ssl_session_timeout 5m;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
  ssl_prefer_server_ciphers on;
  
  location / {
    add_header "Access-Control-Allow-Origin" "http://localhost, https://website";
    try_files $uri @proxy_to_app;
  }

  location @proxy_to_app {
    proxy_pass http://flaskapp;
    proxy_http_version 1.1;
    proxy_buffering off;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $http_host;
    proxy_redirect off;
  }
}
```
Read somewhere that I could return 444 instead of 404, so scanners won't act upon actual responses.
I have tried this construction but not sure if it's not blocking something useful:
```nginx
location @proxy_to_app {
  location ~ ^/(?!socket\.io) {
    deny all;
  }
  location = /socket.io/ {
    limit_except GET {
      deny all;
    }
  }
  ... # upgrade http to websockets
}
```
Would be obliged if you could share some templates for production configs you consider decent. Thank you!

**Comment by miguelgrinberg** [comment]
I don't understand what your concern is. Some random client is asking for a URL that does not exist in your server, and nginx is responding with a 404. Things are working as designed. You can't prevent clients to connect to your server except by blocking their IP addresses with a firewall. I assume you do not want to go that far?

**Comment by a35026** [comment]
I thought that responding to them gives them a clue that they could proceed scanning further.
Possibly giving them timeouts or 444 Connection Closed Without Response.

As I understand they only know my server's IP, not the exact domain, so it might worth filtering those who don't provide correct headers in requests. Also they use HTTP, not HTTPS as I do.
If my understanding of it is correct, then I could block them on this logic, which I guess is too complex for firewall, so possibly it's better to implement it in Nginx.

@miguelgrinberg there is no security section in the documentation, although my question is not really a Flask-SocketIO issue, but I guess newbies are facing this everyday, so might worth sharing your thoughts on where to start tackling this side of app development.

**Comment by miguelgrinberg** [comment]
> I thought that responding to them gives them a clue that they could proceed scanning further.

I think you are confusing different issues here. When people talk about "scanning", they mean "port scanning". This is a technique in which the attacker tries to connect to your server at different ports to detect which services are running. Your server should have a firewall installed, which makes sure that only your chosen ports are open.

But obviously, you have to have ports 80 and 443 open to accept legitimate connections, so the only way to "not respond" on these ports is to implement filtering based on the IP address of the client. Any HTTP respond that you provide is going to tell the attacker that an HTTP server is running on the system, be it 404 or 444 or anything else.

> As I understand they only know my server's IP, not the exact domain, so it might worth filtering those who don't provide correct headers in requests. Also they use HTTP, not HTTPS as I do.

There are a lot of things you can do by filtering based on the contents of the request. None of these equal to "not responding", because you have to accept the connection to read the incoming request, and that would tell the other side that your server is listening to them.

> there is no security section in the documentation

The Linux deployment chapter of my Mega-Tutorial covers the use of a firewall and other security practices.

**Comment by a35026** [comment]
Thank you for a thorough explanation, I indeed was confusing different notions about scanners.
According to your hints, I will use firewall to close all ports except 80, 443 and 22.
Then I will use NGINX for filtering malicious requests as I know what should be provided in a legit request.
Also will check the Mega Tutorial (initially I was referring to the documentation on Readthedocs.io)

@miguelgrinberg thank you for your work
