### ISSUE TITLE
How to catch exceptions or errors thrown from a flask-socketio server using gevent

### ISSUE THREAD

**Issue by harshamadank88** [miguelgrinberg/Flask-SocketIO#1333]
**Your question**
I have CPU intensive server side code to some real time data from an application and i send the same to client using flask-socketio server. When the flask-socketio server is not listening on the mentioned port after starting the sever , Is it possible to determine the reason for the same by catching the exception or error arising from gevent server ?

Since i have a CPU intensive code which gets executed before the UI is loaded , I am unable find the error on the console . I want log the error or exception. I have enabled file configuration logger and set the same for logger and engineio_logger. I can see the logs being written in the file but my server is still not listening on the port specified and it is unable to send data to ui.

I have simulated one such issue where the specified port is not free and when tried to access the port gevent webserver it throws the error but I am unable to capture the error in the logger. I am attaching the traceback error for the same.

I could not find any solution from previous issues. If it is already addressed ,please provide me some pointers .

**Logs**
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\Acer\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Acer\Anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\flak_cer_nobb\venv\lib\site-packages\flask_socketio\__init__.py", line 613, in run_server
    self.wsgi_server.serve_forever()
  File "D:\flak_cer_nobb\venv\lib\site-packages\gevent\baseserver.py", line 398, in serve_forever
    self.start()
  File "D:\flak_cer_nobb\venv\lib\site-packages\gevent\baseserver.py", line 336, in start
    self.init_socket()
  File "D:\flak_cer_nobb\venv\lib\site-packages\gevent\pywsgi.py", line 1500, in init_socket
    StreamServer.init_socket(self)
  File "D:\flak_cer_nobb\venv\lib\site-packages\gevent\server.py", line 180, in init_socket
    self.socket = self.get_listener(self.address, self.backlog, self.family)
  File "D:\flak_cer_nobb\venv\lib\site-packages\gevent\server.py", line 192, in get_listener
    return _tcp_listener(address, backlog=backlog, reuse_addr=cls.reuse_addr, family=family)
  File "D:\flak_cer_nobb\venv\lib\site-packages\gevent\server.py", line 288, in _tcp_listener
    sock.bind(address)
OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted: ('0.0.0.0', 5040)

Any help or suggestions is highly appreciated. Thank you

**Comment by harshamadank88** [comment]
I am running the application on windows 10 machine

**Comment by miguelgrinberg** [comment]
How are you starting this application? Are you putting the server in a background thread?

**Comment by harshamadank88** [comment]
I am starting the server using the socketio.run command as shown below  

if __name__ == '__main__':
        socketio.run(app, host='0.0.0.0', port=5040, debug=True)

I get the real time data feed from the other application by calling a thread . This task is done by using @app.before_first_request(main) decorator on the function so that I keep getting the data feed even though I have'nt accessed the UI using the url.

Please let me know If you need any further information.

Thanks a lot for quick reply Miguel.

**Comment by harshamadank88** [comment]
> I am starting the server using the socketio.run command as shown below
> 
> if **name** == '**main**':
> socketio.run(app, host='0.0.0.0', port=5040, debug=True)
> 
> I get the real time data feed from the other application by calling a thread . This task is done by using @app.before_first_request(main) decorator on the function so that I keep getting the data feed even though I have'nt accessed the UI using the url.
> 
> Please let me know If you need any further information.
> 
> Thanks a lot for quick reply Miguel.

**Comment by miguelgrinberg** [comment]
Try without debug mode, that is definitely going to make things more complicated because it creates an additional subprocess.

If the exception cannot be caught by wrapping `socketio.run()` with a try/except block after you turn off debug mode then this is really a limitation of the gevent web server, unfortunately I don't think I can provide a solution.

**Comment by harshamadank88** [comment]
Ok Miguel .. I will try without debug mode and update here accordingly.

**Comment by harshamadank88** [comment]
Hi Miguel ... Thanks a lot for the response ..  Without the debug mode I was able to capture the port unavailability issue  using the try/ Except block.

I would like to know your suggestion on the other aspect of posting this issue.  I am getting the real time data by running a thread using @app.before_first_request(main) decorator and it is CPU intensive which does not allow the server to be listening on the specified free port what is ideal of way of dealing this issue ?

I had seen the socketio.sleep(0)  was mentioned as a suggestion in some issue . If so, how should i use it ?

**Comment by miguelgrinberg** [comment]
> what is ideal of way of dealing this issue ?

CPU intensive work is almost always a bad idea in a gevent or eventlet server. There is really no way to deal with this, other than relocating the CPU work to another process.

You can try adding sleep(0) and that sometimes help, depending on how frequently you are able to sleep during the CPU work.

**Comment by harshamadank88** [comment]
Ok Miguel..  socktio.sleep(0) is also not helping... server is not listening on the port when i am constantly getting updates at real time from other application and I process the data before passing to ui using websocket.

**Comment by miguelgrinberg** [comment]
Right, that was what I expected. Move this work to a separate process and you will be fine.
