### ISSUE TITLE
Socket-io emit doesn't write to frontend when there is another flask call

### ISSUE THREAD

**Issue by kkissmart** [miguelgrinberg/Flask-SocketIO#1334]
I am trying to write an audio - streaming, transcript and return text to frontend.
It looks very silly though. I have a speech to text program running in the background outside flask.

WIthout click recording. I am able to see the socketio.start_background_task(_qread) writing to frontend. but when record start, socketio.emit doesn't work.

Also I was wondering how to stop this record function by click another button "stop".

Any help is appreciate!

```
eventlet.monkey_patch()

app = Flask(__name__)
socketio = SocketIO()

@app.route('/')
def index():
    return render_template('index.html', async_mode=socketIO.async_mode)

@app.route('/record')
def record():
    app.config['recording'] = True
    a = Recorder('/Users/kkissmart/Desktop/')
    a.listen()
    gevent.sleep()
    return Response(a.listen())

@app.route('/stop_record')
def stop_record():
    app.config['recording'] = False
    print("stopped")
    return ("stopped")

@socketio.on('message')
def connect(msg):
    print("Message:" + msg)

def _qread():
    current = 1
    while True:
        filename = os.path.join('/Users/kkissmart/Desktop/writeout', '{}.txt'.format(current))
        if os.path.exists(filename):
            with open(filename, "rb") as f:
                for line in f:
                    if line.strip():
                        print(line.strip(), file=sys.stderr)
                        socketio.emit('transcript', line.strip().decode('utf-8'))
                f.close()
            current += 1
        else:
            socketio.sleep(0.5)
```

**Comment by miguelgrinberg** [comment]
Your recording task is incompatible with gevent/eventlet and is blocking it. You may need to move your recording to a separate process to prevent the blocking.

Also, you have a mix of gevent and eventlet calls in your code. Pick one and drop the other, they are not supposed to be used together.

**Comment by kkissmart** [comment]
@miguelgrinberg Thank you so much!

Any suggestion on how to design this recording function? I need to start it when a button is clicked and stop it when another button is clicked.

Thanks!!!!

**Comment by miguelgrinberg** [comment]
@kkissmart one option is to build a little audio web server that has `/start` and `/stop` to start/stop the recording. Your main web server using Socket.IO and eventlet will send requests to the audio web server as needed. The audio web server can emit the audio chunks to the client as an external script, or it can send them to the main web server through any inter-process communication method that you like.

**Comment by kkissmart** [comment]
@miguelgrinberg 
one thing I am thinking about is to use subprocesses in the recording function to run a python recording script. do you think that will work?

**Comment by miguelgrinberg** [comment]
@kkissmart hard to tell. If you use an eventlet compatible method of starting your subprocesses then it should work.

**Comment by kkissmart** [comment]
subprocess works!!!!!!! just leave it run in the background without "communication" 

Thanks a lot!
BTW, flask- Socket is so great!!! Thanks!
