### ISSUE TITLE
Is there any way to use flask_limiter in flask-socketio? 

### ISSUE THREAD

**Issue by TheBubblePopped** [miguelgrinberg/Flask-SocketIO#1339]
I want to set a rate limit for my websocket endpoint, but i can't find how. 

With flask_restful the only thing i had to do is place

decorators = [limiter.limit('100/minute;1000/hour', methods=['POST'])]

in the class of my Resource, but how would i approach the problem if i use flask-socketio?

**Comment by miguelgrinberg** [comment]
Flask-Limiter is for HTTP requests. The Socket.IO connection is WebSocket and is permanent, so it is a completely different thing. Past the initial connection requests there is no request/response cycle. You can probably build some sort of custom solution that prevents the client from sending too many events, I guess, but if you are really trying to limit WebSocket I wonder if HTTP wouldn't be a better fit for your use case.

**Comment by TheBubblePopped** [comment]
Hi miguel,

first of all thank you for the very quick response. Second, i think i'll have to go with the custom solution. My problem was that a user could trigger a function that consumes a lot of backend ressources (ML) but the websocket statefull functionality is still wanted.
