### ISSUE TITLE
Can't pass a header when connecting

### ISSUE THREAD

**Issue by SnoozeFreddo** [miguelgrinberg/Flask-SocketIO#1340]
I serve a simple route where a user receives 
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Connect To Socket</title>
</head>
<body>
<script src="//cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.js" integrity="sha256-yr4fRk/GU1ehYJPAs8P4JlTgu0Hdsp4ZKrx8bDEDC3I=" crossorigin="anonymous"></script>
<script type="text/javascript" charset="utf-8">
    var socket = io.connect('localhost:5000', headers={'boom':'bla'});
</script>
</body>
</html>
```

I also tried

`var socket = io("http://localhost", {
  extraHeaders: {
    Authorization: "Bearer authorization_token_here"
  }
});`

however my request object doesn't contain my desired header. What am i doing wrong? 
(I also tried the query method and everything in [here](https://readthedocs.org/projects/python-socketio/downloads/pdf/latest/))

**Comment by miguelgrinberg** [comment]
I'm guessing you are seeing the limitations of sending custom headers in the browser, not a problem with the server. See https://github.com/socketio/engine.io-client#nodejs-with-extraheaders for the discussion on what works and what doesn't in the Socket.IO JS client. You probably want the 3rd browser example in this page.

**Comment by SnoozeFreddo** [comment]
Hello miguel,

you are right. Thank you for pointing this out. 
Have a lovely day
