### ISSUE TITLE
Working with worker server as well as normal server

### ISSUE THREAD

**Issue by jmoheywood** [miguelgrinberg/Flask-SocketIO#1341]
I have an an app that is working great with SocketIO normally :) 

However I have a very long running function that I have had to queue with Redis and rq, and would like to send something to the user when it has completed running (in the last item of the queued functions).

However it doesn't seem to be working; no errors thrown, but likely to be something to do with it being called from the worker server...

Is there a way to be able to run sockets from both these servers?

**Comment by miguelgrinberg** [comment]
Did you see how to emit from an external process in the docs? https://flask-socketio.readthedocs.io/en/latest/#emitting-from-an-external-process

**Comment by jmoheywood** [comment]
Thanks for the speedy reply :) I have tried this, and perhaps I am setting it up wrong...

In my app.py (main server) I have `socketio = SocketIO(app)` and all works great

Within another .py file I have a function being called from within redis queue (with a redis_url)
- Within this I am trying to instantiate a new `socketio_worker = SocketIO(???)` that I can then use to send in a similar way to in app.py with `socketio_worker.emit('increment_notification', room= user.sid)`

**Comment by miguelgrinberg** [comment]
You have to point both processes to the message queue so that they can communicate.

In the Flask server use `socketio = SocketIO(app, message_queue='redis://')`. In the worker, use `socketio = SocketIO(message_queue='redis://')`.

**Comment by jmoheywood** [comment]
> You have to point both processes to the message queue so that they can communicate.
> 
> In the Flask server use `socketio = SocketIO(app, message_queue='redis://')`. In the worker, use `socketio = SocketIO(message_queue='redis://')`.

Thank you - and this `'redis://' `would be = my `redis_url` for my queueing of other functions?

**Comment by miguelgrinberg** [comment]
@jmoheywood oh sorry, yes, that is your Redis URL. This is a completely separate usage of Redis, by the way, nothing to do with your other uses. When you have multiple Socket.IO processes a message queue is required for coordination.

**Comment by jmoheywood** [comment]
Sorted, thank you @miguelgrinberg !
