### ISSUE TITLE
GraphQL Subscription With SocketIO

### ISSUE THREAD

**Issue by AaronWatson2975** [miguelgrinberg/Flask-SocketIO#1342]
**Your question**
I have a <a href="https://github.com/graphql-python/graphql-ws/tree/master/examples/flask_gevent">simple Flask GraphQL subscription example app</a> up and running using flask sockets and everything is working perfect. 

I'm trying to get it to work using flask-socketio without any luck. I did a good amount of searching and couldn't find anything to help me on this, I'm guessing the solution is related to socket.route vs socket_io.on, but I'm not sure.

Here is the original flask example(I left out the rest of the file since it's identical to the example) with the flask sockets commented out.

    #sockets = Sockets(app)
    socket_io = SocketIO(app)
    
    # @sockets.route('/subscriptions')
    # def echo_socket(ws):
    #     subscription_server.handle(ws)
    #     return []

    @socket_io.on('subscriptions', namespace='/subscriptions')
    def echo_socket(ws):
        subscription_server.handle(ws)
        return []

There was no errors, but also nothing returned in GraphiQL when I tested the subscription.

**Logs**
Log output isn't showing anything except 
    Server initialized for gevent.

Thanks for taking the time to read this, any help at all would be greatly appreciated!  [ :

**Comment by miguelgrinberg** [comment]
I assume you are aware that this isn't a WebSocket server? What did you change in the client to use Socket.IO?

**Comment by AaronWatson2975** [comment]
Ahhh that makes sense, in that case I don’t think this is going to work and I’ll have to use Flask Sockets.  I thought I could use SocketIO as a drop in replacement for Flask Sockets but it looks like that’s not the case since the client would need to change.

That would also explain why I wasn’t able to find any information on people using SocketIO for GraphQL subscriptions.

Thank you for the quick reply!
