### ISSUE TITLE
SameSite attribute in Flask-SocketIO

### ISSUE THREAD

**Issue by vonsky104** [miguelgrinberg/Flask-SocketIO#1344]
After recent Chrome update in Issues bar I can see a warning about SameSite attribute. Two warnings actually:

- Indicate whether to send a cookie in a cross-site request by specifying its SameSite attribute
- Indicate whether a cookie is intended to be set in cross-site context by specifying its SameSite attribute

I don't know how the 'SameSite=None' and 'Secure' should be set in configuration line. If I set 'cookie' to None, I get rid off second warning, but the first still persists. Can you help with that? Cheers in advance ;)

**Comment by miguelgrinberg** [comment]
What cookie is this about? Can you show me the exact error message?

**Comment by vonsky104** [comment]
Error message 1
![image](https://user-images.githubusercontent.com/31688110/88935427-07ffaf80-d282-11ea-8054-e0fc5d2052ab.png)

Error message 2
![image](https://user-images.githubusercontent.com/31688110/88935699-4eeda500-d282-11ea-9d75-b30ff34cc194.png)


Request header
![image](https://user-images.githubusercontent.com/31688110/88935495-1a79e900-d282-11ea-87a8-9579e57770ab.png)

**Comment by miguelgrinberg** [comment]
Okay, I think I understand now. This is just a warning, and the default action the browser implements is actually the one that is the most secure. I will update the cookie to define the cross-origin options explicitly.

**Comment by vonsky104** [comment]
Great, thanks for the response 👍

**Comment by ZanderBrown** [comment]
> Cookie “io” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To learn more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

Also in firefox
