### ISSUE TITLE
Problem emitting from one namespace to another

### ISSUE THREAD

**Issue by dian-workz** [miguelgrinberg/Flask-SocketIO#1345]
Hi,

I have 2 clients connecting to a server using web sockets. The one client connects to the server from a Python script to the namespace "edge", the other client connects from a ReactJS frontend to the "ui" namespace. For good measure, each also joins their on respective room. 

```python
@socketio.on('connect', namespace='/ui')
def client_connect():
    join_room("ui")
    print("UI connecting")
    emit('ui', {'message': 'Server connected 2'}, namespace='/ui')

@socketio.on('connect', namespace='/edge')
def edge_connect():
    print("EDGE connecting")
    if current_user.is_authenticated:
        print("EDGE authenticated")
        join_room("edge")
```

When the client connects via the UI namespace, the message the code emits is received by the ReactJS ui, and the same with the EDGE code. The problem I am having is emitting a message from the 'edge' namespace to the 'ui' namespace, as illustrated in the code (emit is the last line):

```python
@socketio.on('client_data', namespace='/edge')
# @authenticated_only
def client_message(message):
    print("EDGE Received.. : " + request.sid + " " + message['quid'])
    emit('ui', {'message': 'edge data received'}, namespace='/ui')
```

It would appear that server can emit to both connected clients respectively, but the problem is sending between the namespaces - the UI client does not receive the message from the EDGE namespace.

Worst case scenario I could consider 2 separate servers each dealing with their respective namespace clients, and then exchanging messages between them using something like RabbitMQ/Kafka, but for my POCO that seems a bit OTT.

Any suggestions would be appreciated

**Comment by miguelgrinberg** [comment]
The `emit()` function has two defaults that you need to override: the namespace and the recipient. You put an override for the namespace, but not for the recipient. The default is to emit to the client that sent the originating event. Your originating event came from the client connected on `/edge`, and this client is not connected on `/ui`, so your emit is not going to reach anyone.

Add the `room` argument to override the recipient as well:

    emit('ui', {'message': 'edge data received'}, room='ui', namespace='/ui')

Given that you are putting your edge and ui clients in their own rooms, I wonder if you really need to use namespaces for this. I think you can connect everyone on a single namespace and simplify things a bit.

**Comment by dian-workz** [comment]
Thank you. Solved.
