### ISSUE TITLE
400 bad request when gunicorn worker class type is set to "gthread"

### ISSUE THREAD

**Issue by shadylpstan** [miguelgrinberg/Flask-SocketIO#1347]
I am creating an ML app.  I'm using gunicorn with no NGINX. 
The worker class is set to gthread, since there are a lot of CPU bound tasks. 
When I am using flask socketio with the worker type "gevent", it is working fine irrelevant of the number of workers(1,2,4).
But when I change it to "gthread", it gives 400 bad request error.

**Gunicorn configuration :** 
`
# import multiprocessing

bind = "0.0.0.0:8081"
workers = 1
#threads = 10
timeout = 10000000
keepalive = 24 * 60 * 60  # 1 day
#keyfile = "staPrivateKey.key"
#certfile = "staCertificate.crt"
worker_class = "gthread"
`

Any help on this, please.

**Comment by miguelgrinberg** [comment]
You can't use gthread, the only supported worker types are gevent and eventlet. Put your CPU intensive work in a separate process instead.

**Comment by shadylpstan** [comment]
Thanks @miguelgrinberg  for the clarification. 
Also, is there any dependency on the number of workers? If number of workers is increased, I can see some problems.

**Comment by miguelgrinberg** [comment]
You have to use one worker. See the docs for how to run multiple workers in a compatible way.

**Comment by shadylpstan** [comment]
Thanks for the help and for clarifying my doubts.
