### ISSUE TITLE
Getting 502 bad gateway and 400 bad request with flask_socketio + flask + gunicorn + nginx

### ISSUE THREAD

**Issue by juno-day** [miguelgrinberg/Flask-SocketIO#1349]
**Your question**
So I have been setting up a website with flask + flask_socketio + eventlet + gunicorn + nginx. I have looked at the documentation for flask_socketio for this configuration and it is supported. Though after using the website I noticed that while flask would work perfectly, flask_socketio would not work at all. Here are the relevant configuration and error codes. I would like to note that some flask_socketio bits post requests would go through with a 200 OK. 
This is on ubuntu 18.04 
There are more logs here
https://stackoverflow.com/questions/63321877/getting-502-bad-gateway-and-400-bad-request-with-flask-socketio-flask-gunico

**Comment by miguelgrinberg** [comment]
Answered on SO, so I'm closing this issue.
