### ISSUE TITLE
Cannot publish to redis... 

### ISSUE THREAD

**Issue by jmoheywood** [miguelgrinberg/Flask-SocketIO#1350]
All working fine on local, however when live on Heroku (have had it working previously...) I get the following error.

`Cannot publish to redis... retrying`
`Cannot publish to redis... giving up`

No errors being thrown other than above.

Initiating with 

`socketio = SocketIO(app, message_queue='redis://')`
running with 
`socketio.run(app)`

I also have rq running redis. 

What could be going wrong?

**Comment by miguelgrinberg** [comment]
What URL did you use to connect RQ to redis?

**Comment by jmoheywood** [comment]
I have just used as above 'redis://' and works fine locally

**Comment by miguelgrinberg** [comment]
Hmm. What do you clarify that RQ worked "locally"? Is your Socket.IO server not running locally as well?

**Comment by jmoheywood** [comment]
Locally; I can set up a connection (from front end to back end), and I can emit to a user and handle it with JS (everything works)

Live on Heroku; I can set up a connection, however on emitting I receive the error above

**Comment by miguelgrinberg** [comment]
Well, okay, but on Heroku you would not be running Redis on `redis://`, right? RQ would not work either if you don't use the correct Redis URL.

**Comment by jmoheywood** [comment]
Understood, thank you. Potentially silly question; how do I get the redis url to use live? (would it be the same one I use for RQ?)

**Comment by jmoheywood** [comment]
it is indeed the same redis_url after just testing. Thank you!
