### ISSUE TITLE
diff bwteen socketio.emit and emit

### ISSUE THREAD

**Issue by RunFeifei** [miguelgrinberg/Flask-SocketIO#1353]
this is how i define

> @celery.task()
def async_emit_01(event, *args, **kwargs):
    from config.socket import socketio
    socketio.emit(event, *args, **kwargs)
    

> @celery.task()
def async_emit_02(event, *args, **kwargs):
    emit(event, *args, **kwargs)

this is how i use

> async_emit.delay('disconnect_broadcast', message.to_json(), broadcast=True)

there is 2 clients connected
but async_emit_01--> only 1 client received msg
async_emit_02-->2 clients received msg

can anyone help me?thanks!!

**Comment by miguelgrinberg** [comment]
The `emit()` function is context-aware, which means that it takes some defaults from the request context. The `socketio.emit()` is not context-aware. So basically, your `async_emit_02()` task might be working differently because of the request context that you have pushed on your Celery worker.

**Comment by RunFeifei** [comment]
> The `emit()` function is context-aware, which means that it takes some defaults from the request context. The `socketio.emit()` is not context-aware. So basically, your `async_emit_02()` task might be working differently because of the request context that you have pushed on your Celery worker.

thanks！！！
