### ISSUE TITLE
upstream prematurely closed connection while reading response header from upstream

### ISSUE THREAD

**Issue by Leedokyung6439** [miguelgrinberg/Flask-SocketIO#1354]
flask-socketio + nginx + uwsgi

app.py

    import os
    from application import app, socketio
    from flask_cors import CORS, cross_origin

    def main():
        port = int(os.environ.get('PORT', 5001))
        app.debug = True
        app.secret_key = 'secret_key'
 
        socketio.run(app, debug=True, host = '0.0.0.0', port=port, use_reloader=False)

    if __name__ == '__main__':
	    main()

__init__.py

    from flask import Flask
    from flask_socketio import SocketIO, send

    app = Flask(__name__)
    socketio = SocketIO(app, logger=True, engineio_logger=True, cors_allowed_origins="*")

    import application.controllers

controllers.py

    @socketio.on('connect')
    def test_connect():
        emit('my_response', {'data': 'Connected'})

html

    var socket = io.connect("ws://www.mydomain.com");
    console.log(socket);

    socket.on('connect', function() {

    });

     socket.on('my_response', function(msg, cb) {

         console.log(msg);

    });

ini
[uwsgi]
module = wsgi:app
master = true
processes = 1
http-websockets = true
socket = umclass.sock
chmod-socket = 666
uid = www-data
gid = www-data
vacuum = true
die-on-term = true

/etc/nginx/sites-available/umclass

    location / {
        include uwsgi_params;
        uwsgi_pass unix:/ubuntu/umclass/umclass.sock;

    }
    location /socket.io/ {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass http://unix:/ubuntu/umclass/umclass.sock;
    }

pip list
appdirs             1.4.4
configparser        4.0.2
contextlib2         0.6.0.post1
distlib             0.3.1
dnspython           1.16.0
eventlet            0.26.1
filelock            3.0.12
greenlet            0.4.16
importlib-metadata  1.7.0
importlib-resources 3.0.0
monotonic           1.5
pathlib2            2.3.5
pip                 20.2.1
pycurl              7.43.0
pyliblzma           0.5.3
pysqlite            1.0.1
rpm-python          4.12.0.1
scandir             1.10.0
setuptools          20.7.0
simplejson          3.17.0
singledispatch      3.4.0.3
six                 1.15.0
typing              3.7.4.3
urlgrabber          3.9.1
virtualenv          20.0.30
wheel               0.29.0
yum-metadata-parser 1.1.4
zipp                1.2.0
zope.event          4.4
zope.interface      5.1.0
error.log

2020/08/19 17:50:34 [error] 2726#2726: *744 upstream prematurely closed connection while reading response header from upstream, client: 220.92.20.129, server: umclass.com, request: "GET /socket.io/?EIO=3&transport=polling&t=NG5wQqV HTTP/1.1", upstream: "http://unix:/ubuntu/umclass/umclass.sock:/socket.io/?EIO=3&transport=polling&t=NG5wQqV", host: "www.mydomain.com", referrer: "http://www.mydomain.com/chat"

 http://www.mydomain.com/socket.io/?EIO=3&transport=polling&t=NG5wphV 502 (Bad Gateway)
 http://www.mydomain.com/socket.io/?EIO=3&transport=polling&t=NG5wphV 502 (Bad Gateway)
 http://www.mydomain.com/socket.io/?EIO=3&transport=polling&t=NG5wphV 502 (Bad Gateway)

**Comment by miguelgrinberg** [comment]
Look in the uwsgi log for errors.

**Comment by Leedokyung6439** [comment]
Aug 19 17:49:31 ip-172-31-21-253 uwsgi[2841]: invalid request block size: 21573 (max 4096)...skip
Aug 19 17:49:39 ip-172-31-21-253 uwsgi[2841]: invalid request block size: 21573 (max 4096)...skip
Aug 19 17:50:27 ip-172-31-21-253 uwsgi[2841]: message repeated 7 times: [ invalid request block size: 21573 (max 4096)...skip]
Aug 19 17:50:34 ip-172-31-21-253 uwsgi[2841]: invalid request block size: 21573 (max 4096)...skip
Aug 19 17:52:12 ip-172-31-21-253 uwsgi[2841]: message repeated 14 times: [ invalid request block size: 21573 (max 4096)...skip]

**Comment by Leedokyung6439** [comment]
> uwsgi 로그에서 오류를 찾습니다.

Aug 19 17:49:31 ip-172-31-21-253 uwsgi[2841]: invalid request block size: 21573 (max 4096)...skip
Aug 19 17:49:39 ip-172-31-21-253 uwsgi[2841]: invalid request block size: 21573 (max 4096)...skip
Aug 19 17:50:27 ip-172-31-21-253 uwsgi[2841]: message repeated 7 times: [ invalid request block size: 21573 (max 4096)...skip]
Aug 19 17:50:34 ip-172-31-21-253 uwsgi[2841]: invalid request block size: 21573 (max 4096)...skip
Aug 19 17:52:12 ip-172-31-21-253 uwsgi[2841]: message repeated 14 times: [ invalid request block size: 21573 (max 4096)...skip]

**Comment by miguelgrinberg** [comment]
@Leedokyung6439 I was trying to give you advice on how you can troubleshoot this problem yourself, not ask you to give me more information to solve this problem for you. You have a misconfiguration problem, nothing to do with this package. Google the error and go from there.
