### ISSUE TITLE
socketio keep using polling instead using wetsockets

### ISSUE THREAD

**Issue by OriAmir** [miguelgrinberg/Flask-SocketIO#1356]
Hi, I create some really basic flask server and try to implement live notification using flask-socketIo  ... the problem is that it looks like it's using only poling instead using web socket:

![image](https://user-images.githubusercontent.com/17565646/90990410-de4c5680-e5a9-11ea-9692-51f11ea4ddc2.png)

My flask app code:

**run.py**

```
from app import create_app, socketio
app = create_app()

if __name__ == "__main__":
    # app.run()
    socketio.run(app, port=5000)
```

**app.py**
```
from flask_socketio import SocketIO

socketio = SocketIO()

def create_app():
    # init flask app instance
    app = Flask(__name__)
    # setup with the configuration provided by the environment
    app.config.from_object(app_config[os.environ['ENV']])


    # setup all our dependencies
    database.init_app(app)
    commands.init_app(app)

    socketio.init_app(app)
    CORS(app)
    from api import blueprint as blueprint1
    app.register_blueprint(blueprint1)

    return app
```

**js(React) side:**

```
import io from "socket.io-client";

const socket = io('')

const App = () => {
  const { register, handleSubmit, errors } = useForm(); // initialise the hook
    socket.on("message", (data) => {
      console.log(data.message);
    });
  };
.....
}

```

What I'm doing wrong?

- I try to install `eventlet` library but it does not help (or maybe I don't understand how to use that).

- I try to change client configuration to enforce websocket :

```
var socket = io("/", {
  transports: ["websocket"] })
```
but then I got error of:  _websocket is closed before the connection is established_ 

- I try many other configurations but nothings help.

- I try to read here /StackOverflow some discussions but nothing help me.

What could be the issue?
Thanks !!

**Comment by miguelgrinberg** [comment]
You need to install a websocket server that is supported. Just installing eventlet should have added the websocket transport to your server.

**Comment by OriAmir** [comment]
@miguelgrinberg thanks for the answer, I install the `eventlet` already but it's not change anything, Did I need to change something after I install this package ( in the server or in the client) ?

I also try to install `gevent` but nothing changes also

**Comment by miguelgrinberg** [comment]
I can't answer bind. Please enable logs in your server and show them to me so that I see what's going on. To enable logs, add `logger=True` and `engineio_logger=True` when you create your `SocketIO` object.

**Comment by OriAmir** [comment]
@miguelgrinberg 
```
Server initialized for eventlet.
62a6d068d2f54c5ab7ffd29d5980205f: Sending packet OPEN data {'sid': '62a6d068d2f54c5ab7ffd29d5980205f', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
62a6d068d2f54c5ab7ffd29d5980205f: Sending packet MESSAGE data 0
8cf4d1c4cef54b4a8b7a479ca08b37a7: Sending packet OPEN data {'sid': '8cf4d1c4cef54b4a8b7a479ca08b37a7', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
8cf4d1c4cef54b4a8b7a479ca08b37a7: Sending packet MESSAGE data 0
emitting event "message" to all [/]
62a6d068d2f54c5ab7ffd29d5980205f: Client is gone, closing socket
62a6d068d2f54c5ab7ffd29d5980205f: Client is gone, closing socket
8cf4d1c4cef54b4a8b7a479ca08b37a7: Sending packet MESSAGE data 2["message",{"data":"got it!"}]
8cf4d1c4cef54b4a8b7a479ca08b37a7: Received packet PING data None
8cf4d1c4cef54b4a8b7a479ca08b37a7: Sending packet PONG data None
```


it keeps sending HTTP requests every 25 sec

Thanks for the help!

**Comment by miguelgrinberg** [comment]
The client should initiate an upgrade to websocket, you can see that the server is now reporting that it can do it:

   62a6d068d2f54c5ab7ffd29d5980205f: Sending packet OPEN data {'sid': '62a6d068d2f54c5ab7ffd29d5980205f', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}

So it is up to the client to do request an upgrade, or even connect over WebSocket from the start.

**Comment by OriAmir** [comment]
@miguelgrinberg 
I try to force the client using only websocket:
`var socket = io('/', {transports: ['websocket']});
`
but then I get this error on the network:
![image](https://user-images.githubusercontent.com/17565646/91084269-65560900-e654-11ea-8b2e-74aa1d1dc763.png)

this is my logs in the server:
```
Server initialized for eventlet.
emitting event "message" to all [/]
emitting event "message" to all [/]
```


I don't really understand when I'm doing wrong, I just "emit" in one of my api's and listen on the client side...

**Comment by miguelgrinberg** [comment]
Is that all the logs? Where is the connection attempt?

**Comment by OriAmir** [comment]
so this is the point:
when I change my client to` var socket = io('/', {transports: ['websocket']});` I'm not get any logs(only the server initialized..) and then when I create some HTTP request where I emit there I get only `emitting event "message" to all [/]` so I think something not really work...

**Comment by OriAmir** [comment]
@miguelgrinberg maybe its something with my CRA configuration? right now I only have in my package.json the proxy:
`  "proxy": "http://localhost:5000"
`

**Comment by miguelgrinberg** [comment]
Okay, so you didn't mention this before. Does the proxy option support WebSocket at all? The fact that the connection does not even appear in the log suggests this is a problem that occurs before the request reaches the server, so there is nothing that can be done from this side.

**Comment by OriAmir** [comment]
I read their doc: https://create-react-app.dev/docs/proxying-api-requests-in-development/

And they wrote: 


The proxy option supports HTTP, HTTPS and WebSocket connections.

**Comment by miguelgrinberg** [comment]
Still, the fact remains that these WS requests are not reaching the server, so you need to debug the earlier parts. I'm not sure how I can help.

**Comment by OriAmir** [comment]
@miguelgrinberg 

So I have been update my client project and add proxy configuration:

```
const { createProxyMiddleware } = require('http-proxy-middleware');

module.exports = function(app) {
  // proxy api calls
  app.use(createProxyMiddleware('/api', {
    target: 'http://localhost:5000',
    changeOrigin: true,
  }));

  // proxy websocket
  app.use(createProxyMiddleware('/socket.io', {
    target: 'http://localhost:5000',
    changeOrigin: true,
    ws: true,
  }));
};
```

Now I got different error on the logs:
```
Server initialized for eventlet.
8a35dd3ca50a400faa9430d7149c81e5: Sending packet OPEN data {'sid': '8a35dd3ca50a400faa9430d7149c81e5', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
8a35dd3ca50a400faa9430d7149c81e5: Sending packet MESSAGE data 0
http://localhost:3000 is not an accepted origin.
8a35dd3ca50a400faa9430d7149c81e5: Client is gone, closing socket
8a35dd3ca50a400faa9430d7149c81e5: Client is gone, closing socket
```


I read this issue :https://github.com/miguelgrinberg/python-socketio/issues/329 but it's looks like it's resolved , so how did i face this issue?

thanks!!

**Comment by OriAmir** [comment]
OK, finally it works.
I added this line in my flask server:
`    socketio.init_app(app, cors_allowed_origins="*")
`

So, to concluse:
1.I instaleld `eventlet` library.
2. Add proxy in client configuration:
```
const { createProxyMiddleware } = require('http-proxy-middleware');
module.exports = function(app) {
  // proxy api calls
  app.use(createProxyMiddleware('/api', {
    target: 'http://localhost:5000',
    changeOrigin: true,
  }));

  // proxy websocket
  app.use(createProxyMiddleware('/socket.io', {
    target: 'http://localhost:5000',
    changeOrigin: true,
    ws: true,
  }));
};
```
3. Add origin config to the socketio:
`socketio.init_app(app, cors_allowed_origins="*")
`

Now, it really works as expected:

```
Server initialized for eventlet.
410c9d15c75643aeaa4db0dd66185c00: Sending packet OPEN data {'sid': '410c9d15c75643aeaa4db0dd66185c00', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
410c9d15c75643aeaa4db0dd66185c00: Sending packet MESSAGE data 0
410c9d15c75643aeaa4db0dd66185c00: Received request to upgrade to websocket
410c9d15c75643aeaa4db0dd66185c00: Upgrade to websocket successful
71de14e4e8414c96a22aee8609590dd1: Sending packet OPEN data {'sid': '71de14e4e8414c96a22aee8609590dd1', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
71de14e4e8414c96a22aee8609590dd1: Sending packet MESSAGE data 0
71de14e4e8414c96a22aee8609590dd1: Received request to upgrade to websocket
71de14e4e8414c96a22aee8609590dd1: Upgrade to websocket successful
emitting event "message" to all [/]
71de14e4e8414c96a22aee8609590dd1: Sending packet MESSAGE data 2["message",{"data":"got it!"}]
71de14e4e8414c96a22aee8609590dd1: Received packet PING data None
71de14e4e8414c96a22aee8609590dd1: Sending packet PONG data None
71de14e4e8414c96a22aee8609590dd1: Received packet PING data None
```

when I look at the network browser tab I don't see any HTTP requests.

@miguelgrinberg really thanks for quick help, I really appreciate that.

**Comment by miguelgrinberg** [comment]
Regarding this line:

    socketio.init_app(app, cors_allowed_origins="*")

It's okay to use for development, but insecure for production. It would be best if you do this:

    socketio.init_app(app, cors_allowed_origins=["http://localhost:3000", "https://your-production-domain.com"])
