### ISSUE TITLE
why the example app.py can run properly in Chrome,but can't run properly in Edge and IE11

### ISSUE THREAD

**Issue by myahuang** [miguelgrinberg/Flask-SocketIO#1357]
Hi!
I'm a freshman. I have runned  the app.py, then  opened the link in explorer, but the Edge and IE11 can't work well the code. It display as follwing:
 

<img width="334" alt="image" src="https://user-images.githubusercontent.com/57703532/91188318-be40a280-e723-11ea-8041-697511b11ab4.png">

**Comment by myahuang** [comment]
when I delete the integrity and crossorigin propertys of script, the Edge and IE11 can work well.
why?

**Comment by miguelgrinberg** [comment]
Because these aren't supported on those browsers. See https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity.

**Comment by myahuang** [comment]
Thanks for your help!
