### ISSUE TITLE
cors_allowed_origin typo throwing 400 instead of Error

### ISSUE THREAD

**Issue by yang94pro** [miguelgrinberg/Flask-SocketIO#1358]
When typo such as `cors_allowed_origin` was used. The flask_socketio will not throwing any error, instead it giving 400 bad request or 502 response.  Making difficult for user debugging.

the correct call should be `cors_allowed_origins`

**To Reproduce**
change `socketio = SocketIO(app,cors_allowed_origins="*") ` to `socketio = SocketIO(app,cors_allowed_origin="*") `

**Expected behavior**
ERROR should be throwing for the typo

**Comment by miguelgrinberg** [comment]
The problem is that this function takes optional arguments that are passed to the next layer down.

**Comment by yang94pro** [comment]
suggest to use **kwargs.pop() and assert len(kwargs) == 0 to raise error

**Comment by miguelgrinberg** [comment]
@yang94pro I don't understand what you mean. This is something that every dependency that I use that receives kwargs should do. It's not something I can do myself from this side.
