### ISSUE TITLE
Question about example sessions.py

### ISSUE THREAD

**Issue by myahuang** [miguelgrinberg/Flask-SocketIO#1360]
Hi
I'm learning the great library Flask_SocketIO, and I have a question about example sessions.py:

The sessions.py use sessions.html as its template , when I visited the Flask_socketIO server by explorer ,then click the 'connect' button, the current session and current user of Socket.IO group are updated same to HTTP group, but I have browsed the sessions.html to find out that '#socketio-session' and '#socketio-user' only refresh when the 'connect' is clicked. The browser is only emit "get-session" message per second, why the current session and current user of Socket.IO group can continuously refresh or update?

**Comment by myahuang** [comment]
When I delete cookie, then the current session and current user of Socket.IO group are updated differently to HTTP group, and the two groups are independent each other! Why?

**Comment by miguelgrinberg** [comment]
Have you seen the video in which I explain the session.py example in detail? https://www.youtube.com/watch?v=OZ1yQTbtf5E

**Comment by myahuang** [comment]
Thanks for your reply!  I should find a way to get over the wall to visit Youtube...

**Comment by miguelgrinberg** [comment]
@myahuang I have also written a blog post with the same content as the video: https://blog.miguelgrinberg.com/post/flask-socketio-and-the-user-session.

**Comment by myahuang** [comment]
Great! I have a deeper understanding of Flask-SocketIO sessions and socket.io.js library through your example! Thanks again!
I think there are many  Flask-SocketIO users  from China, but the paypal is not support CNY, so if you have a Alipay account payment link , users from china can easily donate for this project.
