### ISSUE TITLE
Socketio not emitting data even with socketio.sleep

### ISSUE THREAD

**Issue by minhhnguyen** [miguelgrinberg/Flask-SocketIO#1362]
**Your question**
I am creating an app, in which a route takes data from an object created to gather live trades data for an asset via a websocket server. I want to slightly process this data and feed it to clients via Flask-SocketIO and I have almost been successfull, with the exception that the loops (either for or while) seem to muddle up the emission of trade data. With a for loop, the emission of ALL the messages and emits happen on the browser, but after the completion of the loop and for a while loop it does not happen at all. I can see the updates happening in my terminal while the loops are going. I have tried the socketio.sleep function wedged in between each loop as suggested in several posts on this issue but it still does not work. Would you mind pointing out where I am doing this wrong? Help would be much appreciated

**Logs**
```
def emit_latest_data():
    
    global api
    response = api.data_points
    print(len(response))

    if len(response) == 0:
        response = 'No data.'
    
    else:
        response = str(response[-1])
        
    socketio.emit('new_data', 
        {'data' : response}, 
        namespace = '/admin/stream_data', 
        broadcast = True)

def start_stream_api(ticker):
    
    from potfolio.DATA import FinnhubAPI
    
    global api
    
    api = FinnhubAPI()
    api.run(ticker)

thread = None

    
    
@socketio.on('connect', namespace = '/admin/stream_data')
def handle_connect():
    
    eventlet.monkey_patch()
    
    msg = f'{current_user.username} has connected'
    
    print('Message: ' + msg)
    
    global thread
    
    if thread is None:
        
        thread = socketio.start_background_task(start_stream_api, 'BINANCE:BTCUSDT')
        
    socketio.send('API is active: ' + str(api.active), 
         namespace = '/admin/stream_data', 
         broadcast = True)  
    
    socketio.sleep(0)   
    
    for i in range(5):
        
        emit_latest_data()
        socketio.sleep(0.5)
        
    api.stop()
```

This is my __init__.py
```
async_mode = None

db = SQLAlchemy(app)
admin = Admin(app)
socketio = SocketIO(app,cors_allowed_origins="*")
```

 This is the JS on the client side.

```
    <script type="text/javascript">
        $(document).ready(function() {
        
            var socket_stream = io('http://' + document.domain + ':' + location.port + '/admin/stream_data');
            
            socket_stream.on('message', function(msg) {
                $('#messages').append('<p>'+msg+'</p>');
            });
            
            $('#streambutton').on('click', function() {
            
                socket_stream.emit('stream');
                console.log('emitted');
                
            });
            
            socket_stream.on('new_data', function(msg){
                console.log('New data')
                $('#data').html('<p>'+msg.data+'</p>'); 
            });
            
        });
        </script>
```

**Comment by miguelgrinberg** [comment]
Your connection isn't going to be fully established until you return from the connect handler. Move your logic to another event, or to a background task that is started from the connect handler. You need to return from the handler for the connection with the client to be established.

**Comment by minhhnguyen** [comment]
Cheers Miguel. I've finally got it to work with a rather ad hoc approach using Flask-Executor. I'm still confused as to why when I use socketio.start_background_task in place for executor.submit in this code the thread refuses to run the code after. I would have thought both the functions serve the tasks on new threads?

@socketio.on('stream', namespace = '/admin/stream_data')
def handle_stream(data):
    
    ticker = data['ticker']
    
    socketio.send(f"Received stream request for {ticker}.", 
         namespace = '/admin/stream_data', 
         broadcast = True)  
    
    global thread
    global api
    
    socketio.send("Starting new thread.", 
                     namespace = '/admin/stream_data', 
                     broadcast = True)  
    
    thread = executor.submit(start_stream_api, ticker)
    
    if not api.active:
        api.active = True
        
    socketio.send('API is active: ' + str(api.active), 
     namespace = '/admin/stream_data', 
     broadcast = True)  
    
    while api.active:
        
        emit_latest_data()
        socketio.sleep(0)




from flask_socketio import SocketIO
from flask_executor import Executor
executor = Executor(app)

**Comment by miguelgrinberg** [comment]
Your `start_stream_api()` function does not return, so it blocks the server when started via `start_background_task`. The executor puts it in a separate thread, so with this you avoid the blocking.

**Comment by minhhnguyen** [comment]
That makes sense. Thanks so much!
