### ISSUE TITLE
Inherited Namespace Class cannot emit message

### ISSUE THREAD

**Issue by KosukeShimizu** [miguelgrinberg/Flask-SocketIO#1363]
Flask application is currently hosted at GCP App Engine Flexible environment and SocketIO instance message queue is addressed to Redis server as 'redis://{{REDIS_HOST}}:{{REDIS_PORT}}'.

```
app = Flask(__name__)
socketio_first = SocketIO(
    app,
    path='/websocket/first',
    message_queue='redis://{}:{}'.format(os.environ.get('REDIS_HOST_FIRST'), int(os.environ.get('REDIS_PORT_FIRST'))),
    cors_allowed_origins="*",
    engineio_logger=True
)
socketio_first.on_namespace(InheritedNamespace('/namespace_first'))
```

SocketIO worked fine when I was only hosting single SocketIO instance, however Inherited Namespace Class cannot emit message to client when I was trying to host two SocketIO instances which addressed to different Redis servers although SocketIo connection can be established.

```
app = Flask(__name__)
socketio_first = SocketIO(
    app,
    path='/websocket/first',
    message_queue='redis://{}:{}'.format(os.environ.get('REDIS_HOST_FIRST'), int(os.environ.get('REDIS_PORT_FIRST'))),
    cors_allowed_origins="*",
    engineio_logger=True
)
socketio_first.on_namespace(InheritedNamespace('/namespace_first'))

socketio_second = SocketIO(
    app,
    path='/websocket/second',
    message_queue='redis://{}:{}'.format(os.environ.get('REDIS_HOST_SECOND'), int(os.environ.get('REDIS_PORT_SECOND'))),
    cors_allowed_origins="*",
    engineio_logger=True
)
socketio_second.on_namespace(InheritedNamespace('/namespace_second'))
```

Inherited Namespace looks like following
```
class InheritedNamespace(Namespace):
    def on_connect(self):
        pass

    def on_join(self, data):
       room = int(data['room'])
       join_room(room)

    def on_message(self, data):
        room = int(data['room'])
        if room in rooms():
            logging.info('[InheritedNamespace] ' + str(data['message']))  # <a>
            emit('message', data['message'], room=room)
```

I have seeing message output at `<a>` when I am hosting two SocketIO instances, so the issue seems only with `emit()` function located under the Inherited Namespace function.

Can the multiple SocketIO instance coexist as the code above? or is there another way to use multiple Redis Server as message_queue of single SocketIO instance?

**Comment by miguelgrinberg** [comment]
No, this extension does not support attaching two `SocketIO()` objects to the same Flask app instance.

**Comment by KosukeShimizu** [comment]
Thank you for your quick reply!
