### ISSUE TITLE
Sticky sessions still required if forced websocket transport?

### ISSUE THREAD

**Issue by grgghrn** [miguelgrinberg/Flask-SocketIO#1365]
With regard to distributing socket-io over multiple workers using a message queue backer, I'm trying to understand why sticky sessions are required, since it complicates our architecture substantially.

Are sticky sessions only required to support the connection upgrade from long-polling to websocket?  I mean if I setup the client to only allow websocket connections, would sticky sessions still be a requirement?  On a quick local test it seems like this will force the socket connection into websocket immediately without the normal handshaking, but I haven't tried it distributed yet:

```
const socketIo = io({transports: ['websocket']});
let socket = socketIo.connect(window.location.protocol + '//' + window.location.host + '/');
```

Currently uwsgi is managing numerous workers and I'd rather avoid manually managing a bunch of single-worker instances of uwsgi then fronting those with NGINX (plus we have another ALB in front of those NGINX servers).  If we can get away without the sticky sessions it would simplify things greatly for us.

The followup question would then become, "what cases would websockets not work and we'd end up losing our long polling clients".  We have a pretty controllable internal environment and limited user base, so hopefully we can avoid those situations if they are known.

**Comment by miguelgrinberg** [comment]
I don't really have a lot of experience setting up solutions without sticky sessions, but yes, as long as you only accept WS connections sticky sessions should not be necessary. You do need a message queue, though.

> what cases would websockets not work and we'd end up losing our long polling clients

Only for clients that don't have websocket support. For browsers this isn't a problem, all relatively modern browsers have WS support.

**Comment by grgghrn** [comment]
This does seem to work just fine forcing websocket connections except for one issue.  I wanted to add some error handling just in case we do run into a client who doesn't support websockets.  

So I add a 'connect' handler to the server and have was testing returning 'False' or raising ConnectionRefusedError.  When I do this with standard transports, the polling request is first and it triggers the 'connect_error' on the client.  When I limit it to websocket transports, however, the client just times out - it never sees the explicit failure/error.

Is this just an inherent limitation of how the the websocket only transport works, or do I just have it setup wrong?

**Comment by miguelgrinberg** [comment]
@grgghrn This isn't part of the standard Socket.IO protocol, which starts from long-polling. It is not possible to return an error once the WebSocket connection is established, the only thing that you can do is end the connection, which only indicates an error indirectly. Contrast this against the long-polling interface, which allows you to return a well-defined HTTP status code such as 401.

The behavior in a direct WebSocket connection isn't defined in the protocol, so not sure how to handle this in a way that all clients will like. I suggest you follow the rules and use long-polling as an initial connection mechanism.
