### ISSUE TITLE
JS to python socket server not connected

### ISSUE THREAD

**Issue by kirankumarind** [miguelgrinberg/Flask-SocketIO#1367]
**Describe the bug**
i have a python socket io server running in ngnix , i able to connect through socket io client but i can't able to connect through js from front end side
This is i get from server side 
Sending packet MESSAGE data 0
 Received request to upgrade to websocket
127.0.0.1 - - [10/Sep/2020 16:48:18] "GET /socket.io/?EIO=3&transport=websocket HTTP/1.1" 400 -
 and in front end side

websocket.js:124 WebSocket connection to 'wss:/url/socket.io/?EIO=3&transport=websocket' failed: Error during WebSocket handshake: Unexpected response code: 400

**Comment by miguelgrinberg** [comment]
The most likely issue is that you haven't configured CORS correct to allow for cross-origin access to your server.

**Comment by kirankumarind** [comment]
Can you please help me out how to configure.

**Comment by kirankumarind** [comment]
import json
import os
from flask import Flask, render_template, request,session
from flask_socketio import SocketIO, send, emit
from datetime import timedelta,datetime
from flask_cors import CORS

app = Flask(__name__)
app.config['SECRET_KEY'] = 'secretkey'
app.config['DEBUG'] = True
app.config['CORS_HEADERS'] = 'Content-Type'
cors = CORS(app, resources={r"/*": {"origins": "*"}})
socketio = SocketIO(app, cors_allowed_origins='*',engineio_logger=True)

users = {}

@app.before_request
def make_session_permanent():
    session.permanent = True
    app.permanent_session_lifetime = timedelta(minutes=1)

@app.route('/')
#@cross_origin(origin='*',headers=['Content- Type','Authorization'])
def index():
    return render_template('index.html')

@socketio.on('connect')
def connect():

    print("connected");


@socketio.on('agent-to-user')
def recievedData(data):
    emit('from-agent-to-user',data,broadcast=True)
    socketio.sleep(0)
if __name__ == '__main__':
    socketio.run(app,host='0.0.0.0',port=5000)


my server side code

**Comment by miguelgrinberg** [comment]
Did you look at the logs? There should be a reason for your 400 errors there. I can't really help you if you don't provide the information requested.
