### ISSUE TITLE
Engine.io or websocket instead of socket.io

### ISSUE THREAD

**Issue by AndiLeni** [miguelgrinberg/Flask-SocketIO#1368]
Hello,

I wanted to ask wether I can use engine.io instead of socket.io (for Javascript support). 
As far as the issues stated in the repo for the socket.io javascript library, it is no longer acively maintained and the users should just use websockets or engine.io. 

Kind regards
Andreas

**Comment by miguelgrinberg** [comment]
Where did you get the idea that Socket.IO is no longer maintained?

Engine.IO is a part of the Socket.IO protocol. The JS version is maintained by the same people as Socket.IO. So I'm pretty sure if one of the goes under the other will too.

**Comment by AndiLeni** [comment]
I read that in the issues. Last commit was also a year ago :(
https://github.com/socketio/socket.io-client/issues/1360

**Comment by miguelgrinberg** [comment]
The maintainer said this:

> There is currently ongoing work on engine.io / engine.io-client, which will eventually be merged in Socket.IO, but that... takes quite some time.

If you prefer using native WS that's totally fine, though. Depending on your project you may need to reimplement a bunch of functionality, so be aware it could be more work.

**Comment by AndiLeni** [comment]
Okay, thanks. But flask-socketio only supports socketio, right? So for using plain websockets I would have to change the library.
May I ask another question, is it possible to send data to clients when a url gets a post request?
I want to push new data to clients when the application receives new data from a get/post request.
```
@app.route('/send')
def sendTestMessage():
    emit('testmessage', {'data': 'TESTMESSAGE'})
```

**Comment by miguelgrinberg** [comment]
> Okay, thanks. But flask-socketio only supports socketio, right?

Correct.

> is it possible to send data to clients when a url gets a post request?

Yes. Your example will broadcast the message to all your Socket.IO clients. From an HTTP handler it is a bit tricky to know how to only address that same client that sent the HTTP request through a parallel Socket.IO connection.

**Comment by AndiLeni** [comment]
I still have some problems getting the data to the client.
On the server side I emit the data with:
```
@app.route('/send', methods=['POST'])
def sendTestMessage():
    emit('testmessage', namespace='/', args={'data': request.json}, broadcast=True)
```

But on the client side
```
socket.on('testmessage', function (data) {
            console.log(data)
        });
```
logs undefinded for data.

**Comment by miguelgrinberg** [comment]
Try this:

```python
@app.route('/send', methods=['POST'])
def sendTestMessage():
    emit('testmessage', {'data': request.json}, namespace='/', broadcast=True)
```

**Comment by AndiLeni** [comment]
That worked, thanks.
Flask gives a `TypeError: The view function did not return a valid response.` for this method. Is this error flask related, or does emit() return something I have to check?

**Comment by miguelgrinberg** [comment]
The error is from Flask. You need to return a response.
