### ISSUE TITLE
Correctly set cors header

### ISSUE THREAD

**Issue by AndiLeni** [miguelgrinberg/Flask-SocketIO#1369]
Hello,

I wanted to ask, how exactly the cors header must be set to allow an incomming connection.
Chrome gives me a `net::ERR_CONNECTION_TIMED_OUT` error while Firefox says the CORS request did not succeed.
Setting socketio = SocketIO(app, cors_allowed_origins="*") did not help.
Is this actually a cors error, or is the websocket maybe not reachable?

**Comment by miguelgrinberg** [comment]
Doesn't look like a CORS issue. Enable Socket.IO and Engine.IO logs to have more details about this error.

**Comment by AndiLeni** [comment]
Thats what the client says:

```
socket.io-client:manager attempting reconnect +5s socket.io.js:6:3801
socket.io-client:manager readyState closed +1ms socket.io.js:6:3801
socket.io-client:manager opening https://www.mydomain.eu:5000/liveticker +0ms socket.io.js:6:3801
engine.io-client:socket creating transport "polling" +5s socket.io.js:6:3801
engine.io-client:polling polling +5s socket.io.js:6:3801
engine.io-client:polling-xhr xhr poll +25s socket.io.js:6:3801
engine.io-client:polling-xhr xhr open GET: https://www.mydomain.eu:5000/socket.io/?EIO=3&transport=polling&t=NI1Vere +0ms socket.io.js:6:3801
engine.io-client:polling-xhr xhr data null +2ms socket.io.js:6:3801
engine.io-client:socket setting transport polling +3ms socket.io.js:6:3801
socket.io-client:manager connect attempt will timeout after 20000 +4ms socket.io.js:6:3801
XHRGEThttps://www.mydomain.eu:5000/socket.io/?EIO=3&transport=polling&t=NI1Vere
socket.io-client:manager connect attempt timed out after 20000 +20s socket.io.js:6:3801
engine.io-client:socket socket close with reason: "forced close" +20s socket.io.js:6:3801
engine.io-client:polling transport not open - deferring close +20s socket.io.js:6:3801
engine.io-client:socket socket closing - telling transport to close +3ms socket.io.js:6:3801
socket.io-client:manager connect_error +4ms socket.io.js:6:3801
socket.io-client:manager cleanup +1ms socket.io.js:6:3801
socket.io-client:manager reconnect attempt error +1ms socket.io.js:6:3801
socket.io-client:manager will wait 5000ms before reconnect attempt +0ms
```

**Comment by miguelgrinberg** [comment]
I meant the server, not the client, sorry for not being clear. Add `engineio_logger=True` and `logger=True` to your `SocketIO()` class.

**Comment by AndiLeni** [comment]
There is no other output than 
```
Server initialized for eventlet.
 * Debugger is active!
 * Debugger PIN: 322-747-724
(26339) wsgi starting up on http://0.0.0.0:5000
(26339) accepted ('100.65.75.1', 45798)
2003:de:af10:1d88:7d2d:99b6:2474:484d,100.65.75.1 - - [12/Sep/2020 11:24:16] "GET /liveticker/ HTTP/1.1" 200 4330 0.020994
```
in the console.
No signs of an connection attempt.

**Comment by miguelgrinberg** [comment]
Then the problem is elsewhere, your connection requests aren't reaching the server.

**Comment by AndiLeni** [comment]
Okay,
I figured out, that the path was not set correctly.
Setting `var socket = io('https://www.domain.de/liveticker/', {path: "/liveticker/"});` fixed the issue with the connection problem.

Unfortunately, there seems to be another issue on the backend side, since the polling request is rejected from the flask app with a 405.

```
2003:de:af10:1d60:45f:28fc:2b81:a97a,100.65.75.1 - - [16/Sep/2020 15:54:18] "GET /liveticker/?EIO=3&transport=polling&t=NINCSwF HTTP/1.1" 200 4350 0.001780
(15737) accepted ('100.65.75.1', 40904)
2003:de:af10:1d60:45f:28fc:2b81:a97a,100.65.75.1 - - [16/Sep/2020 15:54:19] "POST /liveticker/?EIO=3&transport=polling&t=NINCSws HTTP/1.1" 405 357 0.001219
```

**Comment by miguelgrinberg** [comment]
How did you set the `/liveticker` endpoint in the server?

**Comment by AndiLeni** [comment]
This is done with a tool from my hosting provider (uberspace).

**Comment by miguelgrinberg** [comment]
I'm not familiar with this service, so I can't really tell you. The logs clearly show that the endpoint does not speak Socket.IO, it just accepts `GET` requests. Not sure if this is because you configured a WebSocket endpoint instead of a Socket.IO, but that could be one problem.
