### ISSUE TITLE
How to scroll up and down to prevent loss of messages?

### ISSUE THREAD

**Issue by scheung38** [miguelgrinberg/Flask-SocketIO#137]
and delete individual messages? Thanks. 

and the purpose of 
```
Server generated event
```
?

**Comment by miguelgrinberg** [comment]
I don't understand your first question.

What application are you asking about? Flask-SocketIO does not know anything about the browser or scrolling, that is an application specific thing.

The server generated events are useful in some situations. The idea is that the server initiates an exchange by contacting a client. For example, you may want to display a popup in the browser when the user gets a message from another user. The server can do that by sending the notification to the client. This is not possible with HTTP, if you were using HTTP you would need all clients to constantly poll the server for notifications.

**Comment by scheung38** [comment]
Sorry, I meant having an infinite listview or frame where messages appear so that user don't have to scroll all the way back to top to type in messages as more appear

**Comment by miguelgrinberg** [comment]
You can certainly implement your application that way. There are many ways to implement scrolling of a portion of a page, but this is a client-side topic that has nothing to do with the socket server. For example, you can make any `<div>` element scrollable using CSS.
