### ISSUE TITLE
Missing app_context when working with background threads

### ISSUE THREAD

**Issue by NamanJain2050** [miguelgrinberg/Flask-SocketIO#1370]
**Your question**
Consider the following use-case:
```
@socketio.on('leave')
def leave_handler(room_id):
  ...
  ...
  leave_room(room_id)
  ...
  ...

@socketio.on('test_event')
def test_event_handler():
  ...
  ...
  # trying to spawn a thread that'll run after 30 secs
  threading.Timer(30, foo, [room_id])
  ...
  ...

def foo(room_id):
  leave_handler(room_id)
```

When such a scenario occurs, where I have to call a event handler from a backend thread I get the error: **app_context** missing. I also tried

```
with app.app_context():
  threading.Timer(30, foo, [room_id])
```

but still doesn't solves the purpose. What's the correct approach to trigger an event from within the server backend threads or call to event handler function with right context?

**Comment by miguelgrinberg** [comment]
The correct way to do this is as follows:

- Start the timer as in your first example:

        threading.Timer(30, foo, [room_id])

- Create an app context when your `foo` function starts:

        def foo(room_id):
            with app.app_context():
                leave_handler(room_id)

**Comment by NamanJain2050** [comment]
Following is the leave_room() function from flask__socketio > __init__.py

```
def leave_room(room, sid=None, namespace=None):
    socketio = flask.current_app.extensions['socketio']
    sid = sid or flask.request.sid
    namespace = namespace or flask.request.namespace
    socketio.server.leave_room(sid, room, namespace=namespace)
```
(I've removed the comments)

When I was not providing the proper app_context I got error in line 
`socketio = flask.current_app.extensions['socketio']`

Now that I provide the app_context as you mentioned in the above comment, I got an error in line:
`namespace = namespace or flask.request.namespace`
saying 
`RuntimeError: Working outside of request context.`

I also tried using:
```
def foo(room_id):
      with app.test_request_context('/'):
          leave_handler(room_id)
```
but got the error in the same line
`namespace = namespace or flask.request.namespace`
saying
`AttributeError: 'Request' object has no attribute 'namespace'`

**Comment by miguelgrinberg** [comment]
Creating a test request context doesn't help, a test context does not have information about the client.

What you need to do is pass all the arguments into the function, so that there is no need to fill in the gaps with information from the context. So in addition to the room name, pass the `sid` of the user in question and the namespace. For the `sid` you may need to pass it as an argument into your thread function.

So your function would be something like the following:

```python
def foo(room_id, sid):
      with app.app_context():
          leave_handler(room_id, sid=sid, namespace='/')
```
