### ISSUE TITLE
Adding authorization

### ISSUE THREAD

**Issue by kirankumarind** [miguelgrinberg/Flask-SocketIO#1373]
Hi i need to add authorization for socket to avoid others to  access to our socket. How colud i add this feature. can some one help me out.

**Comment by miguelgrinberg** [comment]
Did you read the documentation?

**Comment by kirankumarind** [comment]
yes but i could no able to understand that

**Comment by bluthen** [comment]
You are not giving us much to go on. What have you tried so far?

Mainly the idea is to use a session or cookie and check them in the socketio handler.

**Comment by kirankumarind** [comment]
Actually I tried simple python server and node client for my application. I
need to allow only authorised people to connect and go further processing

**Comment by kirankumarind** [comment]
can we add jwt auth in python server is it possible?

**Comment by miguelgrinberg** [comment]
@kirankumarind of course, everything is possible, it's just software. You are not asking any specific questions, so I'm really confused about why you wrote an issue here.

**Comment by kirankumarind** [comment]
sorry for this confusion, you can remove this issue
Thanks
