### ISSUE TITLE
socketio.emit manually triggered from another python file

### ISSUE THREAD

**Issue by joeskt** [miguelgrinberg/Flask-SocketIO#1374]
Thank you for your detailed documentation and example code in app.py. 
It works very well.

With regards to trigerring and sending server generated events, you provided the example of 
socketio.emit('my response',{'data': 'Server generated event', 'count' : count}, namespace='/test')
triggered within app.py.

My question is: whilst app.py is running (after launching the command line: python app.py), is it possible to separately do a socketio.emit from another python file ?

For example: within the same directory as app.py, I created this file:

**manualtrigger.py**
from app import socketio
socketio.emit('my response',{'data': 'Server manual trigger', 'count' : 1}, namespace='/test')

But when I separately run the above file (whilst app.py is already running), no data from socketio.emit reaches the clients. 

I need to separately launch manualtrigger.py, not trigerred by app.py, but triggered as a separate process. Could you kindly provide a sample code that could work for this particular need. Your guidance is much appreciated. Thank you.

**Comment by miguelgrinberg** [comment]
Yes, you can read about that in the docs: https://flask-socketio.readthedocs.io/en/latest/#emitting-from-an-external-process
