### ISSUE TITLE
Disconnect 

### ISSUE THREAD

**Issue by kirankumarind** [miguelgrinberg/Flask-SocketIO#1376]
How to force disconnect the client form server side in python?

**Comment by bluthen** [comment]
flask_socketio.disconnect()

https://flask-socketio.readthedocs.io/en/latest/#flask_socketio.disconnect

**Comment by kirankumarind** [comment]
I have this error
AttributeError: 'SocketIO' object has no attribute 'disconnect'

**Comment by bluthen** [comment]
I don't know I just tried it and worked great. Maybe it is how you are doing it. You didn't give very much information.

# test.py
```python
from flask import Flask, render_template
from flask_socketio import SocketIO, disconnect, emit
import json

app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app)

@socketio.on('message')
def handle_message(message):
    print('got'+json.dumps(message))

@socketio.on('make_me_disconnect')
def do_disconnect():
    disconnect()

@socketio.on('connect')
def test_connect():
    print('Client connected')
    emit('my response', {'data': 'Connected'})

@socketio.on('disconnect')
def test_disconnect():
    print('Client disconnected')

if __name__ == '__main__':
    socketio.run(app)

```

# test.html
```html
<html>
<body>
<script src="//cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.js" integrity="sha256-yr4fRk/GU1ehYJPAs8P4JlTgu0Hdsp4ZKrx8bDEDC3I=" crossorigin="anonymous"></script>
<script type="text/javascript" charset="utf-8">
    var socket = io('http://localhost:5000');
    socket.on('connect', function() {
        socket.emit('message', {data: 'I\'m connected!'});
    });
        setTimeout(function() {
            socket.emit('make_me_disconnect');
        }, 5000);
</script>
</body>
```

**Comment by kirankumarind** [comment]
Hi ,
Thanks its working fine for me, with python client but i need to barere
token as parameter while coneection in js client

my Python client

auth_token = "Bearer " + "afadfdf"
headers = {"Authorization" : auth_token}
sio.connect(url='https://link',headers=headers)

I need like this for js client

**Comment by miguelgrinberg** [comment]
@kirankumarind that is not the concern of this project. Have a look at the [extraHeaders](https://socket.io/docs/client-api/#With-extraHeaders) option for the js client, maybe that is what you need.
