### ISSUE TITLE
Create Pipe between two socketio applications

### ISSUE THREAD

**Issue by Sh3lldor** [miguelgrinberg/Flask-SocketIO#1377]
Hello everyone !
Tried everything on the internet but nothing worked.
I Have two flask applications that both running on SocketIO:
App 1 running on port 5000.
App 2 running on port 5001 that creates thread on port 6002

Our Goal in to send data from first app to the second app.

When App 1 sends data to App 2 that what happens:
1) Creates a new pipe to App2

def create_pipe(data):
    address = ('localhost', 6002)
    try:
        conn = Client(address, authkey=b'abc')
        conn.send(data)
        conn.close()
    except Exception as e:
        print(e)
        return
************************************************

2) App 2 is listening on port 6002 and should receive the data with those functions:

@socketio.on('connect')
def start_chats_thread():
    """
    Creates new background task that starts a thread to listen for incoming data
    """
    global thread
    with thread_lock:
        if thread is None:
            thread = socketio.start_background_task(new_messages_job)

def new_messages_job():
   """"
   Should Get Data from App 1 and call to send_message() that send data to users
   """"
    address = ('localhost', 6002)
    listener = Listener(address, authkey=b'abc')
    while True:
        conn = listener.accept()
        msg = conn.recv()
        send_message(msg[0], users_ids=msg[1])
    listener.close()

************************************************
App 2 doesn't get data from App 1 with the following error:

[WinError 10035] A non-blocking socket operation could not be completed immediately
And after that error the thread shuts down.

We think that there's a problem in listener.accept().

Help will be much appreciated.

**Comment by miguelgrinberg** [comment]
I'm not sure what you mean by "pipe" in this context. You are not showing all your code, but it seems you are just connecting the two processes with a low-level TCP connection? I'm guessing, because I don't know what your `Client` and `Listener` classes do.

Are you using eventlet or gevent in these applications? If yes, did you monkey patch the standard library so that socket operations become non-blocking?

**Comment by Sh3lldor** [comment]
By pipe I mean open a socket that waits to get connection from the other process, and then use the data.
I added monkey_patch at the start of my imports. 
But still no real connection could be made between the two Applications.
The flow is like that: 
1) user do some action and the data needs to be transferred to the second app (That listens on port 6002)
2) App 1 tries to connect to socket of App 2 (port 6002) with above error

If I don't use monkey_patch the process get stuck at startup.

If you have better idea to move data between two socketio processes I would like to know (maybe I just doing it all wrong).

**Comment by miguelgrinberg** [comment]
Well, you seem to have a problem with some low-level networking code, not with this package, right? Why is this package part of the problem?

As for other ways to communicate, two that come to mind are sending HTTP requests, and using a Socket.IO client.

**Comment by Sh3lldor** [comment]
Is it possible to emit to another socketio process ?

**Comment by miguelgrinberg** [comment]
Yes, there are actually two ways. One is with the "external process" technique (docs: https://flask-socketio.readthedocs.io/en/latest/#emitting-from-an-external-process). The other way is by using a Socket.IO client and connecting like the browser would do (docs: https://python-socketio.readthedocs.io/en/latest/client.html)

**Comment by Sh3lldor** [comment]
You helped a lot 🙏, Thank you very much !

**Comment by danielgrayson2012** [comment]
Hi,

I have External Process that I want to : 

1)  **emit** from it  - **works** fine following this instructions 
     https://flask-socketio.readthedocs.io/en/latest/#emitting-from-an-external-process

2) **But, this is what I'm looking for** in the documentation or here, 
   **How the External process** can **listen to events** ? 
     
i'm doing this:
      from flask_socketio import SocketIO, Namespace, emit, join_room, leave_room, close_room, rooms, disconnect

     socketio = SocketIO(message_queue='redis://:pass@192.122.1.12:6379/0')

this works for emit:
       socketio.emit('my_response', my_data, namespace='/test')


But how do i listen to event? 
in the MAIN SERVER (were the Flask app is running just fine with flask_socketio)
I have custom namespace  "test" exactly as in the example code ..

**do I need** to do in my _EXTERNAL PROCESS_ the same, like this : 
**socketio.on_namespace(MyNamespace('/test'))**

somehow it doesn't work for me.

also i see this answer:
--
there are actually two ways. One is with the "external process" technique (docs: https://flask-socketio.readthedocs.io/en/latest/#emitting-from-an-external-process). The other way is by using a Socket.IO client and connecting like the browser would do (docs: https://python-socketio.readthedocs.io/en/latest/client.html)
---
is that mean that if I want that my External Process _not just_ "**emit**" messages
**but also "listen"** to events from the server
I need to setup the external process as a client like any other client (for example the javascript client..)
? 
 (the main flask app can send messages to the external process, for example to do some work on a request) 

I know there is Celery, etc.. to do bg work..
I just want that this configuration/example will work.

Thanks
