### ISSUE TITLE
Firebase-admin with flask-socketio

### ISSUE THREAD

**Issue by yura2000** [miguelgrinberg/Flask-SocketIO#1379]
I'm trying to get documents from the firestore collection, but it's just stuck. No responses, no errors. 
Everything works locally, but when I deploy in the google app engine it doesn’t work.
 
`
io = SocketIO(app, logger=True, engineio_logger=True)
`
When I call '...collection.get()' just stuck. Same when I try to add new documents

**Comment by miguelgrinberg** [comment]
Firebase (and most other Google APIs for Python) are incompatible with eventlet and gevent. Not a problem with this project, so there isn't much I can do. And Google isn't very interested in addressing the problem either. Search the issues here and on python-socketio and python-engineio, some people came up with workarounds. The best solution would be to not mix these two in the same process.

**Comment by yura2000** [comment]
Thanks

**Comment by Shkunn** [comment]
I'm having the same problem as many people, I hope I'll find some answers here. 

I'm looking for a solution to use firebase and eventlet with python-socketio... I saw a lot of topics saying that they are incompatible but some maybe someone has now found a workaround or maybe @miguelgrinberg, you have a new solution.

I can give you all the details you want to know to help me out on this. I need to run firestore and socketio in my app.
