### ISSUE TITLE
Thread not defined into class

### ISSUE THREAD

**Issue by scheung38** [miguelgrinberg/Flask-SocketIO#138]
Not moving the method that starts the chat into a class, I get 
```
NameError: global name 'thread' is not defined
```
Are there ways around it? Because I am calling this class later on when a navigation tab is selected and rendered, as opposed to an initial starting index page.
```
class MyView(BaseView):
    
    @expose('/method3/<string:param1>')
    @has_access
    def method3(self, param1):
        global thread
        if thread is None:
            thread = Thread(target=background_thread)
            thread.start()
        return render_template('chat.html')
```

**Comment by miguelgrinberg** [comment]
Do you have a global variable called `thread` defined in your script?
