### ISSUE TITLE
Eventlet and boto3 incompatibility

### ISSUE THREAD

**Issue by DanielMS93** [miguelgrinberg/Flask-SocketIO#1380]
SSL Context Error thrown when using boto3 (to connect to s3 bucket) and eventlet 

![image](https://user-images.githubusercontent.com/44974943/94677908-92619f80-0315-11eb-898d-2d224a7e5979.png)

Python 3.6.9
Eventlet 0.25.1

**Comment by miguelgrinberg** [comment]
Is this project part of the problem in any way? It seems this is the known SSL issues in eventlet.

**Comment by DanielMS93** [comment]
> Is this project part of the problem in any way? It seems this is the known SSL issues in eventlet.

So far, I have only seen a fix for the SSL issue for python 3.5. are you aware per chance of any fix in python 3.6?

**Comment by miguelgrinberg** [comment]
It's really hard to keep track because the SSL bugs have existed for a long time and with different versions of Python. Some eventlet versions work well with specific versions of Python, but I don't know of anyone who has done a thorough testing and reported what combinations work.
