### ISSUE TITLE
Cant see website logs after using socketio.run(app)

### ISSUE THREAD

**Issue by NarayanAdithya** [miguelgrinberg/Flask-SocketIO#1381]
I  have tried referring a lot of the issues but couldn't find a solution to this one yet.

I was following Miguel Grindbergs structure of the flask app where we did use flask run. But then i needed the use of flask socketio so i changed my code such that when i use `python app.py` the server starts. 

The issue is that i am not getting the logs from the site. The only Logs i can see are these

```
(flaskenv) C:\Users\HP\Desktop\celis_test>python celis_app.py
C:\Users\HP\Desktop\celis_test
App got stuck here
Server initialized for gevent.
 * Restarting with stat
C:\Users\HP\Desktop\celis_test
App got stuck here
Server initialized for gevent.
 * Debugger is active!
 * Debugger PIN: 994-179-599
Active

```
This is my app.py

```
from app import app,db,socketio
from app.models import User,thread,post


@app.shell_context_processor
def make_shell_context():
    return {'db':db,'User':User,'thread':thread,'post':post}

if __name__ == '__main__':
    socketio.run(app,debug=True)

```

My '__init__.py'  is
```
from flask import Flask
from config import config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from flask_socketio import SocketIO,send
#general configs
app=Flask(__name__)
app.config.from_object(config)

#DB Configs
db=SQLAlchemy(app)
migrate=Migrate(app,db)
#Login Configs
login=LoginManager(app)
login.login_view='login'
login.message='Please Login To Access The Page'
login.login_message_category='info'

from app import routes,models
print("App got stuck here")
from flask_socketio import SocketIO,send
socketio=SocketIO(app,engineio_logger=True,logger=True,cors_allowed_origins="*")
```

What did i miss due to which i cant see the site access logs.

**Comment by miguelgrinberg** [comment]
This is not an issue, you are using a different web server, the one from gevent, which has different logging rules. See https://github.com/miguelgrinberg/Flask-SocketIO/issues/1000.

**Comment by NarayanAdithya** [comment]
I changed 

```
if __name__ == '__main__':
    socketio.run(app,debug=True)

```
to

```
if __name__ == '__main__':
    socketio.run(app,debug=True,log_output=True)
```

is didnt work i even tried adding the `log_output = True` to 

`socketio=SocketIO(app,engineio_logger=True,logger=True,cors_allowed_origins="*")`

Even that didnt get me the logs.

**Comment by miguelgrinberg** [comment]
As I said, this is an issue with the gevent wsgi server, not this package. I'm passing `log='default'` to the gevent server, which should be sending logs to stderr.

I cannot comment on the print problem, since you are not showing your code.
