### ISSUE TITLE
socketio.sleep(0), monkey patching, and python threads

### ISSUE THREAD

**Issue by cbasavaraj** [miguelgrinberg/Flask-SocketIO#1382]
Hi, I've been using flask-socketio for a few months and everything works great. I was always aware though that the emitted events were not received by my browser client in *real-time*. So after looking at other issues on GitHub, I learnt to do socketio.sleep(0) after emits or sends, and also monkey patching with either eventlet or gevent.

Now, events are indeed received by the browser immediately. But my app invokes a multi-threaded computer vision pipeline. This pipeline normally works in real-time (5 frames per second), but after monkey-patching, the throughput has dropped significantly, to 2.2 fps. I can't do without threading.Thread for the vision pipeline. Any idea how I can make it work at the original fps? Thanks

**Comment by miguelgrinberg** [comment]
This is not an issue with this package, but with eventlet and/or gevent. These are async frameworks, so you cannot have CPU intensive work as that blocks the whole application. I suggest you look for a solution that applies to your problem in a forum specific to the framework that you are using. As for generic advice, what I can tell you is that the way to make this work is to move all CPU intensive work to a separate process.

**Comment by cbasavaraj** [comment]
Thanks for the quick reply. I'm ready to try multi-processing but haven't used it ever. My pipeline is for object detection using deep learning. It's the threads in the pipeline which emit / send the socketio events to show what objects have been detected. Do you think I can import socketio from the app into a separate process? And also, won't there be the same issue with eventlet / gevent?

**Comment by miguelgrinberg** [comment]
As I said, you can't mix eventlet/gevent with CPU intensive tasks. Your CPU intensive process has to use standard threads, not eventlet/gevent. The documentation shows how to emit from an auxiliary process that is not the server if that's what you want to do.

**Comment by cbasavaraj** [comment]
Ah right. I'd read that part of the documentation but it wasn't so relevant for me, till now. Thanks, will try sometime.
