### ISSUE TITLE
Using SSL terminated at reverse proxy

### ISSUE THREAD

**Issue by boredomdenied** [miguelgrinberg/Flask-SocketIO#1383]
**Describe the bug**
I'm trying to run a client app in a production environment with SSL being terminated at Nginx reverse proxy. This seems to work fine for requests to the `/` and `/static` location blocks. The location block for `socket.io` is returning "mixed-content" errors and is using HTTP protocol. I can't seem to solve this. Is there any issue with using polling/websockets with HTTP and then serving https from the proxy? This has worked fine with projects in the past. I'm not sure what the issue is.

I've tried to use `ProxyFix` which it seemed like this would fake an https signature. Is this a correct approach?! That resulted in a recursive loop that I could not resolve. I did find a `io.connect` line in the client's file that was pointing to HTTP. If I change to HTTPS it shows up 404. I'm guessing this would require the cert be on the actual machine at that point. I'd rather terminate at the proxy so as not to have to keep all worker machines in sync with cert rotation on the proxy. 

Is my approach sane to terminate SSL for the socket.io endpoint at the load balancer? Is there anything this would cause conflict with? If this is not doable then is my only remedy to install the cert on the machine, set the io.connect to HTTPS?

I managed to get the ProxyFix to work without throwing the recursive error. I just can't get this to work out. I've tried so many different headers and combinations and nothing is working. I don't even know where to probe at this point.

**Comment by miguelgrinberg** [comment]
Have you looked at the requests that have mixed content to see what is the http:// content? That would be a good first step to diagnose this problem.

Terminating SSL at the reverse proxy is perfectly fine. That's actually how I host my own projects.

**Comment by boredomdenied** [comment]
It's the endpoint for `socket.io` that comes back as HTTP. I have no idea why. 

I have:
`socket = io.connect('http://' + document.domain + ':' + location.port);
Is this how you have it setup in your app? Are you using nginx? I would like to compare my config to yours if your don't mind.

```
#limit max upload file size
client_max_body_size 50M;

upstream flask_app {
    #for sticky sessions
#    ip_hash;

#    server 172.16.0.79:5000;
    server 172.31.16.205:5000;
}

server {
    server_name example.com;

    ssl_session_cache shared:SSL:50m;
    ssl_stapling on;
    ssl_stapling_verify on;
    add_header Strict-Transport-Security max-age=15768000;

    location = /robots.txt {
        add_header  Content-Type  text/plain;
        return 200 "User-agent: *\nDisallow: /\n";
    }

        location / {
                proxy_pass              http://flask_app/app;
                proxy_next_upstream     error timeout invalid_header http_500 http_502 http_503 http_504;
                proxy_redirect          off;
                proxy_buffering         off;
                proxy_set_header HTTPS on;
                proxy_set_header X-Forwarded-Ssl on;
                proxy_set_header        Host                    $host;
                proxy_set_header        X-Real-IP               $remote_addr;
                proxy_set_header        X-Forwarded-For         $proxy_add_x_forwarded_for;
                proxy_set_header        X-Forwarded-Proto       https;
        }

        location /socket.io/ {
                proxy_pass              http://flask_app/socket.io;
                proxy_http_version 1.1;
#        proxy_redirect off;
#        proxy_buffering off;

                proxy_set_header        Host                    $host;
                proxy_set_header        X-Forwarded-For         $proxy_add_x_forwarded_for;
                proxy_set_header        X-Forwarded-Proto       https;
                proxy_set_header        X-Forwarded-Port        443;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_redirect http://$host/ https://$host/;
    }

    # let's encrypt host validation
    location ~ /.well-known {
        allow all;
    }
        location /errorpages/ {
                alias /var/www/errorpages/;
       }


    location /static {
        include /etc/nginx/proxy_params;
        proxy_pass http://flask_app;
        expires 30d;
    }


    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}



server {
#    if ($host = example.com) {
        return 301 https://$server_name$request_uri;
#    } # managed by Certbot


    listen 80;
    server_name example.com;
    return 404; # managed by Certbot


}

```
Does anything there look out of order? I've tried so many variations at this point. Not sure what else to be doing.

Here is the error I see in console:
```
socket.io.min.js:1 Mixed Content: The page at 'https://example.com/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://example.com/socket.io/?EIO=3&transport=polling&t=1602001555731-0'. This request has been blocked; the content must be served over HTTPS.
i.create @ socket.io.min.js:1
```

**Comment by boredomdenied** [comment]
I have just tried adding this to the HTML in the <HEAD> section:
`<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">`
This gives the same result as when I change the protocol in the io.connect to HTTPS. I get 404s. I don't think this is the correct approach and it wants my certs installed on the box. I want to terminate SSL at the proxy. Why on earth is only this endpoint coming back with mixed-content? This is just a polling endpoint. I don't even see the websocket request coming through anymore when trying SSL. I had no issues with HTTP before applying the cert. Any ideas?

**Comment by boredomdenied** [comment]
I resolved this. It was a missing trailing "/" in the proxy pass for the `socket-io` location block. Now I have to figure out how much of this extra gunk can be removed without breaking all the things...
