### ISSUE TITLE
How to resolve this problem (multiprocessing, queues, gevent) leading to RecursionError?

### ISSUE THREAD

**Issue by Tiemichael** [miguelgrinberg/Flask-SocketIO#1388]
I am working on a program which writes a python-program and runs it on another machine.
The whole program is controlled via   web-browser using FLASK.
The main-process writes a python-program which is started as a 'multiprocessing Process'. This client-process communicates to the main process via multiprocessing Queues and Events.
The client-process communicates with an other machine either via web-sockets or via USB (adb).
Results from this other machine, are send  via a queue (appr once per second) back to the main-process which displays these results automatically on a browser via flask-socketio.emit.
Everything runs fine if the client-process communicates to the other machine via web-sockets, but not if this communication is via USB.
I see the queue is 'loaded' in the client-process and received by the main-process. but  socketio disconnects.
```
Traceback (most recent call last):
File "src\\gevent\\greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
File "C:\Users\Michael\.virtualenvs\CE-SCPI_V2\lib\site-packages\engineio\async_drivers\gevent.py", line 22, in _run
    return self.run()
RecursionError: maximum recursion depth exceeded while calling a Python object
2020-10-13T08:29:02Z <Thread at 0x24abc649948: _run> failed with RecursionError
```

Socketio uses  monkey-patched gevent. The first lines in my main program are:
```
import gevent.monkey
gevent.monkey.patch_socket()
gevent.monkey.patch_all()
```
I understand that the combination 'flask-socketio', 'gevent' and 'multiprocessing' is tricky, and I am using a 'multiprocessing Process' because I need to be able to terminate the slave process via the browser (main-process)

Any idea how to resolve this issue, or which other approach I could take.
Thanks!

**Comment by Tiemichael** [comment]
Even if I start in debug-mode
 ```
socketio = SocketIO(app,  async_mode='gevent', logger=True, engineio_logger=True)
socketio.run(app, host='0.0.0.0', port=5000, debug=True)
```
all I get is this
 ```
60a0832d564c4fe19affbd21c8a746a1: Sending packet OPEN data {'sid': '60a0832d564c4fe19affbd21c8a746a1', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
60a0832d564c4fe19affbd21c8a746a1: Sending packet MESSAGE data 0
60a0832d564c4fe19affbd21c8a746a1: Received packet MESSAGE data 0/scpi_cons
SocketIO Client connected: 2020-10-14 09:40:12.510825
60a0832d564c4fe19affbd21c8a746a1: Sending packet MESSAGE data 0/scpi_cons
60a0832d564c4fe19affbd21c8a746a1: Received request to upgrade to websocket
60a0832d564c4fe19affbd21c8a746a1: Upgrade to websocket successful

Traceback (most recent call last):
  File "src\\gevent\\greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
  File "C:\Users\Michael\.virtualenvs\CE-SCPI_V2-b4nhZvkm\lib\site-packages\engineio\async_drivers\gevent.py", line 22, in _run
    return self.run()
RecursionError: maximum recursion depth exceeded while calling a Python object
2020-10-14T01:40:13Z <Thread at 0x2c60b93a3a8: _run> failed with RecursionError
```
I have no idea what causes this error ...

**Comment by miguelgrinberg** [comment]
Did you monkey patch?

**Comment by Tiemichael** [comment]
Yes, I am monkey-patching gevent. The first lines in my main program are:
```
import gevent.monkey
gevent.monkey.patch_socket()
gevent.monkey.patch_all()
```

**Comment by miguelgrinberg** [comment]
That was my only theory. If you are monkey patching then I don't know. You may want to try eventlet, or older gevent releases. Sorry I can't help more.

**Comment by Tiemichael** [comment]
I tried eventlet before - the result was the same
Anyway, thanks for your help!
