### ISSUE TITLE
Update query string without closing connection

### ISSUE THREAD

**Issue by TheKruspe** [miguelgrinberg/Flask-SocketIO#1389]
**Describe the bug**
Updates made to the query string are ignored until the connection closes and opens again. This is probably related to this bug: https://github.com/socketio/socket.io/issues/1677

**To Reproduce**

Client-side:

    socket = io('http://localhost/custom', {
        query: {
            'token': '123',
        },
        transports: ['polling'],
    });

    function changeQuery() {
        //socket.close();
        socket.io.opts.query.token = 'abc';
        socket.query.token = 'abc';
        //socket.io.custom.transport.query.token='abc';
        socket.connect();
    }
    changeQuery();
    socket.emit('showMeMyToken');

Server-side:

    @socketio.on('showMeMyToken', namespace='/custom')
    def showMeMyToken():
        token = request.args.get('token')
        print(token)

**Expected behavior**
I would expect that `abc` gets logged in the server console. But instead I get `123`.

**Additional context**
Since WebSockets are disabled, I can see what query string is used to emit the `showMeMyToken` function. The `token`-param still holds `123`. However, if I uncomment the line `socket.io.custom.transport.query.token='abc';`, the token used for the request (in the URL) does actually change to `abc`, but the server still prints `123`. If I uncomment the line `socket.close();`, the query string does change and the server prints `abc`, but a disconnect gets triggered. As far as I understood from the referenced SocketIO bug, this behavior results out of a server-side cached query param, but I was unable to locate the problem in `Flask-SocketIO` or `Python-SocketIO`.

**Comment by miguelgrinberg** [comment]
The information that the server exposes about a client is what is sent during the connection call. If you are using long-polling, data included in the requests that do the polling is not used, and this is by design, because there is no equivalent method to make such updates in a WebSocket connection.
