### ISSUE TITLE
Invalid Session and Cannot Send to sid in cpanel

### ISSUE THREAD

**Issue by DivyanshByte** [miguelgrinberg/Flask-SocketIO#1391]
I have a app which when I run it on cpanel, Gives me a `400` bad request error in Client side.
and It gives me a `Invalid Session` and `Cannot Send to sid` error in Logs.
First It gives only `Invalid Session` Error but After Some time, It gives both `Invalid Session` and  `Cannot Send to sid` Error
It also Gave These Errors when I tried it on Google Cloud Platform
But when I run it locally on my own mac, It works without any error.
and also it do not gave errors on Heroku

### Client Side:
![image](https://user-images.githubusercontent.com/57246976/96086228-9d086100-0edf-11eb-8020-d6f7386e3f2b.png)
![image](https://user-images.githubusercontent.com/57246976/96086324-cb863c00-0edf-11eb-996e-371c47538cc7.png)
### Server Side:
![image](https://user-images.githubusercontent.com/57246976/96086453-fff9f800-0edf-11eb-8405-4143ee00add0.png)

Can You Please Help Me?

**Comment by miguelgrinberg** [comment]
Unfortunately I know nothing about cpanel. I suggest you check the documentation on deployment and figure out how to adapt the requirements to what cpanel provides.

**Comment by DivyanshByte** [comment]
@miguelgrinberg According to Cpanel Docs, I have used the way to run my app. I also Tried it using `ngrok` in cpanel. There it worked with no errors. But it again don't work when I use Cpanel to run.

**Comment by miguelgrinberg** [comment]
When I said you should check the documentation, I meant the Flask-SocketIO documentation, no Cpanel's.

**Comment by DivyanshByte** [comment]
Oh Sorry, I thought Checking cpanel docs But there's Nothing about deploying on cpanel in the docs.

**Comment by miguelgrinberg** [comment]
That's exactly my point, Cpanel is not a supported option. You can learn about the options that do work in the docs and find how to adapt them to your environment.
