### ISSUE TITLE
Correct method for making CORS work

### ISSUE THREAD

**Issue by alethiophile** [miguelgrinberg/Flask-SocketIO#1394]
I recently tried to deploy Flask-SocketIO behind an nginx reverse proxy for the first time, and initially ran into the same CORS issue that some others have, getting the `(proxy_address) is not an accepted origin` error message. Wrapping the Flask app in Werkzeug's ProxyFix didn't change anything, but adding the correct proxy_address to cors_allowed_origins fixed it.

Is this the correct intended method of fixing the CORS issue? All my code is same-origin, and I feel like there should be some way similar to ProxyFix of deducing the running origin from the proxy rather than having to hard-code a deployment origin. This solution works fine in practice, but I wonder if it could cause loss of flexibility.

**Comment by miguelgrinberg** [comment]
I would think the ProxyFix middleware should have worked in your case. The correct middleware chain should be:

ProxyFix --> Flask-SocketIO --> Flask

Instead of:

Flask-SocketIO --> ProxyFix --> Flask

I believe initializing Flask-SocketIO before adding `ProxyFix` should give you the right sequence.

**Comment by alethiophile** [comment]
So I should create the `SocketIO` object, which takes `app` as an argument, and then do the 
```
app.wsgi_app = ProxyFix(app.wsgi_app, ...)
```
thing?

Or is it a different object I need to wrap in ProxyFix?

**Comment by miguelgrinberg** [comment]
@alethiophile yes, I think that should do it. Please report back if this does it.

**Comment by alethiophile** [comment]
Okay, I just tried that and it worked.

Thanks much.
