### ISSUE TITLE
Concurrent socket connections handling.

### ISSUE THREAD

**Issue by mike-bionic** [miguelgrinberg/Flask-SocketIO#1398]
**Increasing the performance of sockets and the connections**
Good day! I develop an API using Python Flask framework and I've got to move a part of code for socket.io usage. But my issue is the quantity of connections on single worker, because I need a >1000 users to be connected. Is it possible to increase the qty of possible connections with configuring async sockets or will it require a server with better performance (RAM, CPU)?

Developers recommend to use **NodeJS** with the same **SocketIO** library, saying that Node can run thousands async sockets on a single worker, and eventually create NodeJS socket server, so the Flask app will work as a  client. I feel that this is a bad idea, but I need to know that Python's implementation of SocketIO server will give the same good performance.
If yes, what has to be done for it?

Thanks in advance.

**Comment by miguelgrinberg** [comment]
This library does not have limitations on number of active clients per worker. These limits are imposed by web servers, so you need to configure your web server to handle as many connections as you need, assuming your system has enough resources to handle it.

**Comment by mike-bionic** [comment]
Then, it means that no matter if I use NodeJS or Python, I will get the same performance. It depends only on server config.
Mr. Miguel, on one of your PyCon presentations few years before there were a question about getting a lot more socket connections, than quantity of the workers server can handle. I didn't get it clearly, but you said a word about celery. I use background tasks for tasks like db Insert of a bigger data like BLOBs or some server operations, but I have no idea of using it in sockets, because messages should be inserted and later delivered.
Could you help me somehow in configuring, give some clue or link for useful references?

**Comment by miguelgrinberg** [comment]
> on one of your PyCon presentations few years before there were a question

I can't possibly remember. Which talk was this?

**Comment by mike-bionic** [comment]
https://www.youtube.com/watch?v=Jwux1TPZUwg&t=9m42s
> at 36:02

there was a word about celery intensive processes and async websockets.. What should be configured on the Web Server to handle them?
Best regards.

**Comment by miguelgrinberg** [comment]
I believe the question was about CPU intensive work, not about large number of client connections.

**Comment by mike-bionic** [comment]
I found a solution by using asyncio, but didn't check it on high load yet. I will give it a try.
