### ISSUE TITLE
Production server

### ISSUE THREAD

**Issue by XxSamixX123** [miguelgrinberg/Flask-SocketIO#1399]
Good evening.
First of all I would like to apologize for my English.
I have created a simple application that servers pages to the client, and then communicates with 
them using the socketIO library.

I have thought about deploying my application, and wanted to do it on a windows machine.
I have read in the documentation that using the Embedded server is good for production, and was somehow confused since I know that using the flask built-in server (without socketIO) which is called "werkzeug" if I'm not mistaken, is good only for testing and not for production.

Is the built-in socketIO server good for production as opposed to "werkzeug".
And if yes, the documentation says that the server will use either eventlet or gevent, whichever is installed. 
Is it enough that I have installed them with pip, or do I have to import them or something like that before writing "Socketio.run(app)"

I know this question is already really long, but I wanted to mention that if the built-in server isn't good, I have been looking at the "waitress" server, that is supposed to resemble Gunicorn. As far as I have researched "waitress" doesn't support the socketIO library. Is there something that I'm missing?.

Thanks in advance for all the answers!

**Comment by miguelgrinberg** [comment]
Both eventlet and gevent have production quality servers. You do not need to import them, the `socketio.run()` function does it for you.

**Comment by XxSamixX123** [comment]
Thank you for the answer. Will the server be good enough to serve the static content that comes with the pages?

**Comment by miguelgrinberg** [comment]
Sure, but normally you'd want to use a dedicated web server to serve your static content and also act as a reverse proxy to your Python server. Nginx is a good choice.

**Comment by XxSamixX123** [comment]
Okay. Thank you for the answer.
