### ISSUE TITLE
Flask MQTT on_connect is never called when used with SocketIO

### ISSUE THREAD

**Issue by ramanraja** [miguelgrinberg/Flask-SocketIO#1400]
I am trying to implement an MQTT to Web Socket bridge on the lines of  the  example
https://flask-mqtt.readthedocs.io/en/latest/usage.html#interact-with-socketio

In the above example, subscribing to the MQTT topic is triggered by the socket client. But I want my MQTT channel to keep communicating even if there is no socket client.   

So I tried to subscribe in the @mqtt.on_connect() event. But that callback is never invoked. But once subscription is initiated using a socket, MQTT messages start flowing in all right. Does SocketIO in some way interfere with MQTT life cycle events ?

I have posted the sample code here:
https://stackoverflow.com/questions/64592277/flask-mqtt-on-connect-is-never-called-when-used-with-socketio

**Comment by miguelgrinberg** [comment]
The example is from the Flask-MQTT documentation, I do not know anything about it. Maybe you intended to file a bug with that project instead?

**Comment by ramanraja** [comment]
Sure, thanks. (The plain Flask-MQTT example works fine. The callback fails when Socket support is added to it. So my thought process was to examine how async_mode and socketio.run() interact with the MQTT life cycle.). If I get any more leads I will it update here.
