### ISSUE TITLE
redis://:my_passoword@redis_server_ip:6379/0 not working

### ISSUE THREAD

**Issue by danielgrayson2012** [miguelgrinberg/Flask-SocketIO#1403]
Hi,

i have an issue with adding redis message_queue='redis://:my_passoword@redis_server_ip:6379/0'
to the Flask-SocketIO

my current redis url is
redis://:my_passoword@redis_server_ip:6379/0

but this is NOT WORKING - *
Flask IO not connecting anymore
However, this:
-----------------------------------
import redis 

r = redis.Redis(host='redis_server_ip',port=6379, password='my_passoword') 
             # or this:
r = redis.Redis.from_url('redis://:my_passoword@redis_server_ip:6379/0')

my_key_value = r.get('key123')
---------------------------------------------
Works fine.

so the problem is in the Flask-SocketIO, is the url accept password ? my redis server has the authentication (requiredpassword)

**socketio = SocketIO(app, logger=True, engineio_logger=True, debug=True, cors_allowed_origins = None, message_queue='redis://:my_passoword@redis_server_ip:6379/0')**

my_passoword, redis_server_ip its just placeholders, its the real password and ip ... in the code :)

the websocket itself is also SSL
client connected to wss://
(first connected to https://mydomain.com/socket-io/ and than its upgraded to websockets wss://) 

Thanks

**Comment by miguelgrinberg** [comment]
The issue template that you completely ignored asks you to collect logs. Why haven't you done that?

**Comment by danielgrayson2012** [comment]
you are right, sorry...

its something related to : 
RuntimeError: Redis requires a monkey patched socket library to work with gevent_uwsgi

from your docs:
"Flask-SocketIO does not apply monkey patching when eventlet or gevent are used. But when working with a message queue, it is very likely that the Python package that talks to the message queue service will hang if the Python standard library is not monkey patched."

Ok we got the error and the problem, now i guess i need to figure what i need to do... 
and let me guess, you want me to find this by my own...



Log:
================================================================
c237af2e8feb4cb883f7c1bd10d41cda: Sending packet OPEN data {'sid': 'c237af2e8feb4cb883f7c1bd10d41cda', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
redis backend initialized.
connect handler error
Traceback (most recent call last):
  File "/home/berry/projects/python/kjBerry1/kjBerry1Venv/lib/python3.8/site-packages/engineio/server.py", line 549, in _trigger_event
    return self.handlers[event](*args)
  File "/home/berry/projects/python/kjBerry1/kjBerry1Venv/lib/python3.8/site-packages/socketio/server.py", line 722, in _handle_eio_connect
    self.manager.initialize()
  File "/home/berry/projects/python/kjBerry1/kjBerry1Venv/lib/python3.8/site-packages/socketio/redis_manager.py", line 65, in initialize
    raise RuntimeError(
RuntimeError: Redis requires a monkey patched socket library to work with gevent_uwsgi
Application rejected connection

**Comment by danielgrayson2012** [comment]
from gevent import monkey
monkey.patch_all() 

THANKS !
