### ISSUE TITLE
Nginx + eventlet + https

### ISSUE THREAD

**Issue by atomtm** [miguelgrinberg/Flask-SocketIO#1406]
Following the official guide: https://flask-socketio.readthedocs.io/en/latest/ I am trying to serve my app using nginx and https:
This is my configuration so far: 
```
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name myserver.com;

    ssl_certificate /etc/letsencrypt/live/myserver.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/myserver.com/privkey.pem;    

    access_log /var/log/nginx/myserver.com.access.log;
    error_log /var/log/nginx/myserver.com.error.log;

    location / {
        include proxy_params;
        proxy_pass http://127.0.0.1:5000;
    }

    location /static {
        alias /home/src/static;
        expires 30d;
    }

    location /socket.io {
        include proxy_params;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass http://127.0.0.1:5000/socket.io;
    }
}
```
However , when trying to connect the flask server reports:
```
Server initialized for eventlet.
79a87f9d10764559b2f166a8269e394a: Sending packet OPEN data {'sid': '79a87f9d10764559b2f166a8269e394a', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
79a87f9d10764559b2f166a8269e394a: Sending packet MESSAGE data 0
https://myserver.com is not an accepted origin.
```
Nginx reports:
```
*1422 connect() failed (111: Connection refused) while connecting to upstream, client: my.ip, server: myserver.com, request: "GET /socket.io/?EIO=3&transport=polling&t=NMut1JN HTTP/2.0", upstream: "http://127.0.0.1:5000/socket.io/?EIO=3&transport=polling&t=NMut1JN", host: "myserver.com", referrer: "https://myserver.com/master"
```
The clients give me: 
```
WebSocket connection to '<URL>' failed: WebSocket is closed before the connection is established.
```
Using http instead of https, the app works as intended.

Any help would me much appreciated !

**Comment by atomtm** [comment]
Well setting `cors_allowed_origins='https://mysite.com'` made the app accept the request, however I am curious on how to make this work without setting CORS.

**Comment by miguelgrinberg** [comment]
Why do you want to avoid CORS?

The allowed origins setting is used both to set CORS headers and to configure the origin verification server-side. There is currently no way to configure the server-side verification without also configuring CORS headers at the same time.

**Comment by atomtm** [comment]
> Why do you want to avoid CORS?
> 
> The allowed origins setting is used both to set CORS headers and to configure the origin verification server-side. There is currently no way to configure the server-side verification without also configuring CORS headers at the same time.

Well http works without CORS, and following the official documentation, CORS is not mandatory. If otherwise then please let me know. Please forgive my ignorance I am trying to learn :)

**Comment by miguelgrinberg** [comment]
As I said, there's two things, one is CORS (which is a check done by the browser and only applies to HTTP), and the other is server-side origin verification which is done by this package. Your error is about server-side origin verification, and it fails because the server does not know what the correct origin is unless you configure it.

**Comment by atomtm** [comment]
Thank you very much Miguel! Really appreciate
