### ISSUE TITLE
External process - emit works - i see the docs - but how to listen to event from external process - do i need to use socket.io client for that ? 

### ISSUE THREAD

**Issue by danielgrayson2012** [miguelgrinberg/Flask-SocketIO#1407]
this is posted in 
https://github.com/miguelgrinberg/Flask-SocketIO/issues/1377
but i cant see this in the open questions so nobody see this..
sorry if duplicated..

Hi,

I have External Process that I want to : 

1)  **emit** from it  - **works** fine following this instructions 
     https://flask-socketio.readthedocs.io/en/latest/#emitting-from-an-external-process

2) **But, this is what I'm looking for** in the documentation or here, 
   **How the External process** can **listen to events** ? 
     
i'm doing this:
      from flask_socketio import SocketIO, Namespace, emit, join_room, leave_room, close_room, rooms, disconnect

     socketio = SocketIO(message_queue='redis://:pass@192.122.1.12:6379/0')

this works for emit:
       socketio.emit('my_response', my_data, namespace='/test')

But how do i listen to event? 
in the MAIN SERVER (were the Flask app is running just fine with flask_socketio)
I have custom namespace  "test" exactly as in the example code ..

**do I need** to do in my _EXTERNAL PROCESS_ the same, like this : 
**socketio.on_namespace(MyNamespace('/test'))**

somehow it doesn't work for me.

also i see this answer:
--
there are actually two ways. One is with the "external process" technique (docs: https://flask-socketio.readthedocs.io/en/latest/#emitting-from-an-external-process). The other way is by using a Socket.IO client and connecting like the browser would do (docs: https://python-socketio.readthedocs.io/en/latest/client.html)
---
is that mean that if I want that my External Process _not just_ "**emit**" messages
**but also "listen"** to events from the server
I need to setup the external process as a client like any other client (for example the javascript client..)
? 
 (the main flask app can send messages to the external process, for example to do some work on a request) 

I know there is Celery, etc.. to do bg work..
I just want that this configuration/example will work.

Thanks

**Comment by miguelgrinberg** [comment]
External processes can only emit, there is no support for listening.

**Comment by danielgrayson2012** [comment]
Thanks for the quick response !

I'll use Socket.IO client.
