### ISSUE TITLE
Socket.io on prod 400 BAD REQUEST

### ISSUE THREAD

**Issue by Sh3lldor** [miguelgrinberg/Flask-SocketIO#1408]
Hey miguel !
I am setting my socket.io app to prod but when I moved it to my ubuntu server and run it with gunicorn I get the following error in console:

GET https://192.168.211.130/socket.io/?EIO=3&transport=polling&t=NN2Wf6C&sid=... 400 (BAD REQUEST)

gunicorn command:
authbind gunicorn -w 4 -b 0.0.0.0:443 --certfile=ssl/host.cert --keyfile=ssl/host.key myapp:app
("authbind" letting me bind 443 port with low permissions user)

Server is running but all socket.io functions are not.
I tried to add response.headers.add("Access-Control-Allow-Origin", "*") to my header with no different results.

Would be happy to know if you have any idea how to fix my problem.

**Comment by miguelgrinberg** [comment]
You haven't provided the logs that the issue template requires. Why is that?
