### ISSUE TITLE
can sid across from different worker? 

### ISSUE THREAD

**Issue by dingwf** [miguelgrinberg/Flask-SocketIO#1409]
Hello, I use flask-socketio for my project. I only use with one worker,  now, I want deploy in k8s for multi workers,  

when a user connect my socketio server, I assign "uid" for this user (sid), I store uid and sid key pairs  in my memory, when some thing happen, I will notify this user, I find out he's uid, and I found sid, then emit he with sid.

but when I use with multi worker with manage-queue(eg. Redis), I don't know which server he is connecting. when I want to notify this user, how I found he ? 

I think I store all uid-sid in Redis? then I access Redis, I get sid by uid, then i emit with sid without know which connect server he is connect?

thanks a lot!

**Comment by miguelgrinberg** [comment]
You can emit to any user from any server, that is all handled internally via messaging through the queue.

**Comment by dingwf** [comment]
Thanks, 
It means, if I get user's sid, I can emit he  from every server? 
sid is unique and global across many server?

**Comment by miguelgrinberg** [comment]
Yes to both questions.

**Comment by dingwf** [comment]
Thank you very much!
