### ISSUE TITLE
all events come through to server at once

### ISSUE THREAD

**Issue by jeffthemaximum** [miguelgrinberg/Flask-SocketIO#141]
I'm hitting a similar issue as this: https://github.com/miguelgrinberg/Flask-SocketIO/issues/106

Basically have a flask app where user plays against a chess AI that's launched as a subprocess.

I want to output think AI's thinking via flask-socketio.

When I put my emit call inside a while loop, it buffers, then outputs all the emits at once, when the loop exits.

When I put time.sleep or gevent.sleep within the loop, the emit calls stream to the client as I want, but the AI crashes.

relevant code:

    @main.route('/getpythondata')
    def get_python_data():
        # gets current proc by finding user's most recent game...
        current_game = get_current_game(current_user)
        current_proc = get_current_proc(current_game)
        print "hello from AI"

        # receive output from gnuchess and print to console
        line = current_proc.stdout.readline().rstrip()

        # for gnu chess
        if current_game.ai == "GNU chess":
            while ("My move is" not in line):
                socketio.emit('echo', {'echo': line})
                # time.sleep(.01)
                gevent.sleep(.01)
                print "AI thinking: " + line
                line = current_proc.stdout.readline().rstrip()

Seems like others have solved this problem with gevent.sleep. Any other way to flush the emit buffer situation?

**Comment by miguelgrinberg** [comment]
@jeffthemaximum why does your application crash when you issue the sleeps? That is really the only way to make this work when you use gevent, threading is cooperative so you have to release the CPU so that other tasks associated with the server get a chance to run and flush the messages. Any chance you haven't monkey patched the standard library?

PS: your project sounds interesting, would love you see it when it's done :)

**Comment by jeffthemaximum** [comment]
@miguelgrinberg thanks for getting back to me! I think it's really cool you get on here and helps people like me trouble shoot issues. 

I got it working late last night with a little help from this: http://blog.pythonisito.com/2012/07/gevent-and-greenlets.html

Basically, I just replaced **gevent.sleep(.01)** with **gevent.sleep(0)**

It's my understanding that this flushes the messages, but avoids whatever issue was crashing my AI.

Also, on closer inspection, I don't think it was the AI that was crashing. I was getting a line **[CRITICAL] WORKER TIMEOUT**, so I think the socketio.sgunicorn.GeventSocketIOWorker was timing out? 

The AI sometimes takes >2 seconds to print a new line of thinking, so perhaps this was beyond the timeout limit of the socketio worker? 

Regardless, it's working now!

The app I'm working on is hosted on AWS here: http://ec2-52-20-212-59.compute-1.amazonaws.com/
And the source code is here: https://github.com/jeffthemaximum/crispy-hippopotamus

The aws site isn't too front-end fancy yet, it's still has some bugs, and the socket functionality isn't on AWS yet... But you can checkout some of what I've made :)

Anyway, thanks for your help! I'll send another message along once the site is a little more functional. My basic plan was to use flask to make a web app where users could play chess against some of the best open-source chess AI's that exist.

**Comment by jingxa** [comment]
Hi,thank you for your information! i feel i am dying if i don't see this topic;
i want to emit new immediately , but when i run "emit" in loop, it always flush all data once! that's terrible!
thank u!

**Comment by xuhuigithub** [comment]
牛逼！！！！！

**Comment by xuhuigithub** [comment]
Thanks for your help @jeffthemaximum .Good job!!!!
