### ISSUE TITLE
Flask-Login not staying authenticated with Flask-SocketIO

### ISSUE THREAD

**Issue by lmcdaniel1998** [miguelgrinberg/Flask-SocketIO#1410]
Hello All,

I am working on using Flask login with Flask Socket-IO. I am currently having issues authenticating my client when it connects to the server. My client connects with JavaScript that is on my index page. Here is the code that my client uses to connect to the server. When this code runs the current user’s username is displayed on the page, so I know the user is authenticated on the index web page.

index.html

```
{% if current_user.is_authenticated %}
Hi {{ current_user.username }}!
{% endif %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.7.3/socket.io.min.js"></script>

<script type="text/javascript">


// socket connection is a string: ‘http://localhost:5000/namespace’ using my custom namespace

var socket = io.connect(socket_connection);

</script>
```

My server code that handles incoming connections can be seen below in a namespace object. When I print out the current user it is a flask_login.mixins.AnonymousUserMixin object. When the client connects, the current user is not authenticated I know this is because my current user is anonymous. My question is why is my user anonymous on the server while authenticated on my client web page and how can I fix this?

routes.py

```
class MyNamespace(Namespace):
def on_connect(self):
	print(current_user)
            	if current_user.is_authenticated:
            		if request.args.get('fail'):
                			return False
            		print('authenticated sid: ' + request.sid)
```

**Comment by miguelgrinberg** [comment]
Can you provide a complete and runnable example that I can use to reproduce this problem?

**Comment by lmcdaniel1998** [comment]
Miguel,

First off I want to thank you for all of your amazing tutorials and the work you've done with Flask. I would have never have gotten as far as I have in this project without you.
All of the code for my project is on my github at: [https://github.com/lmcdaniel1998/FlaskWithWebsockets](https://github.com/lmcdaniel1998/FlaskWithWebsockets)
My flask server has the same database structure as the database in your flask mega-tutorial.
The issue is only present when in the on_connect function of my Namespace class in routes.py lines 112-130.
The web client code is all contained in the index.html file located in templates.

**Comment by miguelgrinberg** [comment]
This is the output of the code in lines 112-130:

```
<User miguel>
authenticated sid: fe61c4c31f6f4b67a97ee8f3562848f3
```

So it seems to be working for me.

**Comment by lmcdaniel1998** [comment]
Huh for some reason on my machine it outputs:
`<flask_login.mixins.AnonymousUserMixin object at 0x0000023D78E1CBC8>`

Do you know why the server would not recognize the user even if the page index.html where the websocket is trying to connect from can authenticate the user?

**Comment by miguelgrinberg** [comment]
@lmcdaniel1998 cookies disabled on your browser maybe?

**Comment by lmcdaniel1998** [comment]
I've enabled cookies and I have tried with Google Chrome and Firefox. I also tried a much simpler example and it is not working. Is there another way to authenticate the user? Or another place I could put my flask-socketio routines so that the server recognizes the user?

**Comment by miguelgrinberg** [comment]
Without cookies you will have to manually pass your authentication token when you make a connection request.
