### ISSUE TITLE
Cannot import emit or socketio from flask

### ISSUE THREAD

**Issue by gjfrick** [miguelgrinberg/Flask-SocketIO#1411]
**Your question**
I am unable to import emit or SocketIO into worker app.  I get the following error:

 from flask import Flask, url_for, render_template, redirect, SocketIO, emit
ImportError: cannot import name 'SocketIO' from 'flask' (C:\Users\gfrick\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\__init__.py)

I've tried:
 from flask_module import ....
 from flash import SocketIO, emit 
 from flask.ext.socketio... (deprecated)

The appropriate packages are installed to the best of my knowledge:
Package         Version
--------------- ---------
bcrypt          3.2.0
beautifulsoup4  4.9.3
branca          0.4.1
certifi         2020.6.20
cffi            1.14.3
chardet         3.0.4
click           7.1.2
colorama        0.4.4
configparser    5.0.1
cryptography    3.2.1
distro          1.5.0
ebaysdk         2.2.0
elasticsearch   7.9.1
emit            0.4.0
Flask           1.1.2
Flask-WTF       0.14.3
flist           0.602
folium          0.11.0
geographiclib   1.50
geopy           2.0.0
gevent          20.9.0
greenlet        0.4.17
idna            2.10
itsdangerous    1.1.0
Jinja2          2.11.2
lxml            4.6.1
MarkupSafe      1.1.1
module          0.0.4
netifaces       0.10.6
ntlm-auth       1.5.0
numpy           1.19.2
panda           0.3.1
pandas          1.1.3
paramiko        2.7.2
pip             20.2.4
pycparser       2.20
pyinfra         1.2.1
PyNaCl          1.4.0
python-dateutil 2.8.1
pytz            2020.1
pywinrm         0.4.1
requests        2.24.0
requests-ntlm   1.1.0
setuptools      50.3.2
six             1.15.0
socketio        0.2.1
.
.
.
**Logs**
I have no 'socketio' logs for obvious reasons

**Comment by miguelgrinberg** [comment]
You are importing `SocketIO` from Flask, which is incorrect. Flask does not have support for Socket.IO, this comes from the Flask-SocketIO extension. You have to install this extension and then import from `flask_socketio`:

    from flask_socketio import SocketIO

**Comment by gjfrick** [comment]
Thank you for the correction.  The documentation that I found was incorrect.

________________________________

**Comment by miguelgrinberg** [comment]
Let me know where in the documentation you found this error and I'll fix it.

**Comment by gjfrick** [comment]
Sorry, not your documentation.  Someone else's.  I apologize for insinuating that it was your documenation.

________________________________
