### ISSUE TITLE
Best way to keep track of users on room

### ISSUE THREAD

**Issue by sinedie** [miguelgrinberg/Flask-SocketIO#1412]
I need to keep track of users connected on a room -just like google docs- and i'm wondering what is the best way of doing it.

At the moment I see two options:

1. When a user joins a room, save his nickname to the database where the room_id and all others users on the room are stored. Then send his nickname to all clients on room.
2. When a user joins a room send a request to all clients on the room asking for their nickname and then storing it on client side -avoiding duplicates and all that stuff-

I haven't thought on room leave or server disconnection. I think the database could solve that, but idk.

Also, I've notice that if a user is on room A -has joined room A- and sends a message to another room -say room B-, even if he is not in that room, the message shows up on room B. I think it works like it is supossed to, but there must be a way to avoid this, no?. Like I have a chat room and someone -outside the room- can sends a message to the room is weird to me.

Pd: Sorry for my english.

**Comment by miguelgrinberg** [comment]
I would go with option 1, I don't really understand option 2.

I also don't understand what you are saying regarding room communication. A user cannot send a message to a room. All a user can do is send a message to the server, which then can opt to relay that message to a given room. The server has control on wether messages are forwarded to rooms or not.

**Comment by sinedie** [comment]
Maybe I didn't explain option two well

Option two is about keeping track of all room's users on client side -all browser have a list of users on the room-. This is possible if when a user enters the room save his own nick name in localstorage or something and then sends a request to the server that broadcast to all users on room and ask for their own nick name. That's a lot of request but only happen when someone joins the room. Then, cause all users has sent his nickname, each client has to check if user is connected or not and stored in the list.

I implemented this option before asking so I have a working code right now... Here is my bad code.

**Javascript - client side**
(roomInterceptor and userInterceptor insert current room and user nickname to the request)
```
function joinRoom(room_id) {    // Enters the room
    emit_data('join', {room: room_id}, undefined)
}


socket.on('joined', (response) => {
    sessionStorage.setItem("current_user_id", response.user_id)
    sessionStorage.setItem("current_user", response.user)
    sessionStorage.setItem("room", response.room)
    emit_data('get_connected_users', {}, [roomInterceptor])     // Request for all users on room
});


socket.on('get_user_info', () => {
    emit_data('user_info', {}, [userInterceptor, roomInterceptor])
});


socket.on('user_connected', (user_info) => {
    if (!sameUserOfRequest(user_info)) {
        const connected_users = get(connectedUsers)
        const user = connected_users.find(user => user.id == user_info.user_id)

        if (user == undefined) {
            connectedUsers.addUser({
                user_id: user_info.user_id,
                user: user_info.user,
            })
        }
    }
});

function emit_data(endpoint, data, interceptors) {
    if (interceptors != undefined) {
        interceptors.forEach(interceptor => {
            interceptor(data)
        });
    }

    socket.emit(endpoint, data);
}

function roomInterceptor(request) {
    request.room = sessionStorage.getItem("room")
}


function userInterceptor(request) {
    request.user_id = sessionStorage.getItem("current_user_id")
    request.user = sessionStorage.getItem("current_user")
}


function sameUserOfRequest(request) {
    return request.user_id == sessionStorage.getItem("current_user_id")
}
```


**Python - server side**
```
@socketio.on('join')
@authenticated_only
def on_join(data):
    project_id = data['room']

    project = Project.query.filter_by(id=project_id).first()

    if project is not None and current_user.id in project.shared_with: 
        join_room(project_id)
        emit("joined", {
            "room": project_id,
            "user_id": request.sid,
            "user": current_user.name
        })
        return

    emit("not_found")


@socketio.on('get_connected_users')
@authenticated_only
def get_connected_users(data):
    emit("get_user_info", room=data['room'])


@socketio.on('user_info')
@authenticated_only
def user_info(data):
    emit("user_connected", data, room=data['room'])
```


And about the second question... that was my stupid brain, I understand now. Thank you.

**Comment by miguelgrinberg** [comment]
Okay, I understand now. You want this so that you can show a list of participants or something like that?

**Comment by sinedie** [comment]
yeah, I have a 3d view where you can select boxes. Each user can select a different box and it becomes of another color, so i need to show which user has selected which box. As u say, a list of participants and their selection

**Comment by sinedie** [comment]
Well, i'm closing this. I just wanted to know what would be better. I think the database solution is better to avoid sending a lot of request but for the moment I'm going to use the second cause it's already implemented. Thinking in migrate this to database in the future.

Thank u for the reply.  Keep going with this, a great work. This library made this a lot easier for me -I'm not really a web developer-.
