### ISSUE TITLE
use eventlet in flask_socketio ,can't send socket message and kafka message at the same time.

### ISSUE THREAD

**Issue by daizzhisheng** [miguelgrinberg/Flask-SocketIO#1414]
I use use eventlet in flask_socketio,  but the server can't send socket message and kafka message at the same time.
the key code like this:

from flask import Flask, request, render_template, Response
from flask_cors import *
from flask_socketio import SocketIO, emit

server = Flask(__name__, static_url_path='')
CORS(server, supports_credentials=True, resources=r'/*')

import eventlet
eventlet.monkey_patch()
server.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(server, async_mode='eventlet', cors_allowed_origins='*')

if __name__ == "__main__":
    socketio.run(server, host='0.0.0.0', port=9999, debug=False)

I want to send the same message through socket and kafka at the same time, but the socket client can receive socket mesage, however the server can't send msg by kafka,  it bring the error "module 'select' has no attribute 'epoll'".

![image](https://user-images.githubusercontent.com/21993936/99629467-ff222c00-2a72-11eb-9b16-4a103ec3d21a.png)

this question just appear in linux systerm,  and it's normal on windows.

thanks for your help!

**Comment by miguelgrinberg** [comment]
This should be asked to someone that is familiar with Kafka. My guess is that there is an incompatibility between eventlet and the Kafka client, but I don't really have much experience.
