### ISSUE TITLE
Flask-SocketIo

### ISSUE THREAD

**Issue by jj009** [miguelgrinberg/Flask-SocketIO#1419]
When application run about 12 hours,it will be no response .After time out about 60 seconds,all http request  will return 504 httpcode.

Nginx conf:
  pstream socketio_nodes {
    ip_hash;

    server 127.0.0.1:5000;
    server 127.0.0.1:5001;
    server 127.0.0.1:5002;
    # to scale the app, just add more nodes here!
}
server {
    listen 443 ssl;
    server_name xxx.com;
    ssl_certificate /root/Documents/Project/wwwroot/ssl_server/1t1f.com.crt;
    ssl_certificate_key /root/Documents/Project/wwwroot/ssl_server/1t1f.com.key;
    ssl_session_timeout 5m;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers ALL:!ADH:!EXPORT56:RC4+RSA:+HIGH:+MEDIUM:+LOW:+SSLv2:+EXP;
    ssl_prefer_server_ciphers on;
    client_max_body_size 2048M;
    location / {
        proxy_pass http://127.0.0.1:5000;
        proxy_redirect off;
        proxy_set_header Host               $http_host;
        proxy_set_header X-Real-IP          $remote_addr;
        proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto  $scheme;
    }
    location /static {
        alias /root/Documents/Project/wwwroot/static;
        expires 3d;
    }

    location /socket.io {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass http://socketio_nodes/socket.io;
    }
}

eventlet mode to run flask-socketio three process ,and port  is 5000 \5001\5002

**Comment by miguelgrinberg** [comment]
Did you notice that the issue template requests that you include logs with your bug report? Any reason why you decided to ignore that request?
