### ISSUE TITLE
on_error should get the exception

### ISSUE THREAD

**Issue by richburdon** [miguelgrinberg/Flask-SocketIO#142]
Feature request: 

on_error just displays a short string.

A lot of code happens in request handling and it would be useful if the exception object were passed to this handler.

**Comment by miguelgrinberg** [comment]
Not sure I understand. The argument to the error handler is actually the exception object. See https://github.com/miguelgrinberg/Flask-SocketIO/blob/v1.0/flask_socketio/__init__.py#L128-L129, this is where your handler is invoked.

**Comment by richburdon** [comment]
Sorry my mistake.
