### ISSUE TITLE
400 bad request using official socketio client

### ISSUE THREAD

**Issue by noomly** [miguelgrinberg/Flask-SocketIO#1421]
Hello,

I am facing a frustrating bug and I can't figure out why things aren't working.

My setup is as follow:

- Flask server located on a docker container, which I now want to include a WebSocket server using Flask-SocketIO,
- the client is a (firefox) WebExtension, which should be able to communicate via a WebSocket to the server, via a background script using the official SocketIO client (https://github.com/socketio/socket.io-client).

I am using the latest versions available for both Flask-SocketIO and the javascript SocketIO client.

Here is my main python code that runs the server:

```python
import os
from flask import Flask, jsonify
from flask_cors import CORS
from flask_login import LoginManager

from flask_socketio import SocketIO, send, emit

app = Flask(__name__)
app.secret_key = os.environ.get("SECRET_KEY") or os.urandom(24)

socketio = SocketIO(app, cors_allowed_origins="*")

CORS(app)

login_manager = LoginManager()
login_manager.init_app(app)

@app.route("/", methods=["GET"])
def hello_world():
    return jsonify("Hello FutStock")

@socketio.on("message")
def handle_message(message):
    print("received message: " + message)


if __name__ == "__main__":
    socketio.run(app, debug=True, host="0.0.0.0")
```

And here is the javascript code on the client side:

```javascript
let socket = io("http://localhost:5000");

console.log("SOCKET", socket);

socket.on('connect', () => {
    console.log("CONNECTED", socket.connected); // true
});
```

The bug manifests on the client side and on the server side as lots of `GET http://localhost:5000/socket.io/?EIO=4&transport=polling&t=NOWaKHw` that get 400 as a response. The payload of the response being `The client is using an unsupported version of the Socket.IO or Engine.IO protocols`.

As I have read in various locations while in search for a solution that it could be because of CORS, I have used the advised `cors_allowed_origins="*"` parameter to no avail. I am also using `CORS(app)` from flask_cors which to my understanding should also have solved the problem.

I should also mention that I am effectively running the script using `python <script>` and not `flask run`.

I have run out of ideas as to where this could come from and would very much appreciate a bit of help.

**Comment by bluthen** [comment]
I think the newer protocol hasn't been implemented yet. It came out just recently. You can try with an older client.

https://github.com/miguelgrinberg/python-socketio/issues/560

**Comment by noomly** [comment]
Exactly, I just tried with the 2.3.1 client and it works. I shouldn't have assumed the latest version would be the one supported. Maybe it should be made clear in the documentation what current client version is Flask-SocketIO supporting?

Anyway, thank you very much.
