### ISSUE TITLE
Messages Stalling after Page Refresh

### ISSUE THREAD

**Issue by grantregen** [miguelgrinberg/Flask-SocketIO#1422]
Hi! 

I'm newer to deployment and am trying to make a python backend, react frontend app with nginx. The deployment was going well until I found out that refreshing the page lead to the following error where the websocket would reconnect and instead of pinging, would get hung on "Received request to upgrade to websocket" and constantly disconnect after waiting and try again without luck. 

Here's the flask server's output on a successful first run: 
`Debugger is active!
 Debugger PIN: 120-458-680
(199499) wsgi starting up on http://127.0.0.1:5000
(199499) accepted ('127.0.0.1', 33080)
[2020-12-02 19:58:34,409] INFO in socket: 5a610a394a9d48a1acdffa0e493ca6b0: Sending packet OPEN data {'sid': '5a610a394a9d48a1acdffa0e493ca6b0', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
[2020-12-02 19:58:34,410] INFO in socket: 5a610a394a9d48a1acdffa0e493ca6b0: Sending packet MESSAGE data 0
76.21.113.81,127.0.0.1 - - [02/Dec/2020 19:58:34] "GET /socket.io/?EIO=3&transport=polling&t=NOb2FkL HTTP/1.1" 200 347 0.002021
(199499) accepted ('127.0.0.1', 33082)
(199499) accepted ('127.0.0.1', 33084)
[2020-12-02 19:58:34,577] INFO in socket: 5a610a394a9d48a1acdffa0e493ca6b0: Received request to upgrade to websocket
76.21.113.81,127.0.0.1 - - [02/Dec/2020 19:58:34] "GET /socket.io/?EIO=3&transport=polling&t=NOb2Flq&sid=5a610a394a9d48a1acdffa0e493ca6b0 HTTP/1.1" 200 159 0.155060
[2020-12-02 19:58:34,725] INFO in socket: 5a610a394a9d48a1acdffa0e493ca6b0: Upgrade to websocket successful
[2020-12-02 19:58:59,519] INFO in socket: 5a610a394a9d48a1acdffa0e493ca6b0: Received packet PING data None
[2020-12-02 19:58:59,519] INFO in socket: 5a610a394a9d48a1acdffa0e493ca6b0: Sending packet PONG data None`

And then here its is after a refresh:
`[2020-12-02 18:14:57,160] INFO in socket: 06cd74ed8d1e480d88feac6ed2ed2401: Sending packet OPEN data {'sid': '06cd74ed8d1e480d88feac6ed2ed2401', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
[2020-12-02 18:14:57,161] INFO in socket: 06cd74ed8d1e480d88feac6ed2ed2401: Sending packet MESSAGE data 0
76.21.113.81,127.0.0.1 - - [02/Dec/2020 18:14:57] "GET /socket.io/?EIO=3&transport=polling&t=NOagY5o HTTP/1.1" 200 347 0.000735
(198390) accepted ('127.0.0.1', 32912)
(198390) accepted ('127.0.0.1', 32914)
[2020-12-02 18:14:57,327] INFO in socket: 06cd74ed8d1e480d88feac6ed2ed2401: Received request to upgrade to websocket
76.21.113.81,127.0.0.1 - - [02/Dec/2020 18:14:57] "GET /socket.io/?EIO=3&transport=polling&t=NOagY7B&sid=06cd74ed8d1e480d88feac6ed2ed2401 HTTP/1.1" 200 159 0.103889
`
On error the console shows this: 
`socket.io-client:socket transport is open - connecting +0ms
App.js:13 Connected to Backend w/ ID: 
App.js:14 2224b5769c3045b99034af7580fd4241
polling-xhr.js:268 GET http://calc-dev.mmnt.us/socket.io/?EIO=3&transport=polling&t=NOb39A2&sid=2224b5769c3045b99034af7580fd4241 504 (Gateway Time-out)
browser.js:133 socket.io-client:socket close (transport error) +1m
App.js:18 Disconnected from backend w/ ID: 
App.js:19 undefined
browser.js:133 socket.io-client:socket transport is open - connecting +1s
App.js:13 Connected to Backend w/ ID: 
App.js:14 b1d83a8da0494d40b85215fb4f5030ae
websocket.js:124 WebSocket connection to 'ws://calc-dev.mmnt.us/socket.io/?EIO=3&transport=websocket&sid=b1d83a8da0494d40b85215fb4f5030ae' failed: Error during WebSocket handshake: Unexpected response code: 504
browser.js:133 socket.io-client:socket close (transport error) +1m
App.js:18 Disconnected from backend w/ ID: 
App.js:19 undefined
browser.js:133 socket.io-client:socket transport is open - connecting +1s
App.js:13 Connected to Backend w/ ID: 
App.js:14 099b2bb7443240f9a5e7ff3d45aee9fd`

Here's my app.py server (condensed): 
`import eventlet
eventlet.monkey_patch()
from flask import *
from flask_socketio import SocketIO, send, emit`
....
`app = Flask(__name__)
app.config['SECRET_KEY'] = 'XXXXXX'
app.debug = True
app.host = 'http://172.31.18.98'
app.port = '5000'
socketIo = SocketIO(app, cors_allowed_origins="*",
                    logger=app.logger, engineio_logger=app.logger)`
...
`@app.route('/api')
def root():
    return "Hello I have changed";
@socketIo.on("message")
def handleMessage(msg):
    socketIo.sleep(0)
    emit("clear", "clearing results...")`
...
`if __name__ == '__main__':
    socketIo.run(app, port=5000)`

Here's my app.js client (condensed):
`
...
const endPoint = "http://websiteName.com";
const socket = io(endPoint);
var clients = {}
socket.on('connect',function(client) {
    console.log('Connected to Backend w/ ID: ');
    console.log(socket.id);
    clients[socket.id] = socket;
});
socket.on('disconnect', function() {
    console.log('Disconnected from backend w/ ID: ');
    console.log(socket.id);
    delete clients[socket.id];
});
...
`

And here's my Nginx config file: 
`server {
    listen 80;
    root /home/ubuntu/RideCalc3/Internal_UI/build;
    index index.html;
    location / {
        try_files $uri $uri/ =404;
    }
    location /api {
        include proxy_params;
        proxy_pass http://127.0.0.1:5000;
    }
    location /socket.io {
          include proxy_params;
          proxy_http_version 1.1;
          proxy_buffering off;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "Upgrade";
          proxy_pass http://127.0.0.1:5000/socket.io;
      }
}`

Any help on why reloading it causes this stall would be extremely helpful thanks!

**Comment by miguelgrinberg** [comment]
Does this happen when you don't run the Flask debugger? I'm not sure if it would work well under eventlet, it wasn't designed with greenlets in mind.

**Comment by grantregen** [comment]
Just turned off the debugger and same issue occurred, but the flask-socket.io logging also disabled for some reason when I set app.debug = False. Any suggestion on how to turn back on the logging with debug off? And if that doesn't show the issue do you recommend switching to gevent instead of eventlet? Thanks for the help btw, I've been trouble shooting for days now.

**Comment by miguelgrinberg** [comment]
Logging is turned on with the `logger=True` and `engineio_logger=True` options.

**Comment by grantregen** [comment]
Strange both of those are still on but it won't throw logging with debug off. Either way, though I isolated the bug by rebooting my server and re-disabling ubuntu's systemd which I had previously tried to automate reloads with. Thanks so much for the help, and I'll close out the question here.
