### ISSUE TITLE
Flask not designed for large applications or for large applications or asynchronous servers?

### ISSUE THREAD

**Issue by scheung38** [miguelgrinberg/Flask-SocketIO#143]
From doc:

http://flask.pocoo.org/docs/0.10/design/

(section in Thread Locals)

"However Flask is just not designed for large applications or asynchronous servers. Flask wants to make it quick and easy to write a traditional web application."

http://flask.pocoo.org/docs/0.10/becomingbig/#becomingbig

section in Scale like a pro

So can it scale?

**Comment by ktoh** [comment]
This really isn't a flask-socketio issue. You may want to ask this on stackoverflow, but there are lots of articles out there in the scalability of flask.
