### ISSUE TITLE
Decorated methods do not fire

### ISSUE THREAD

**Issue by brettrichards** [miguelgrinberg/Flask-SocketIO#1430]
I've been struggling to get a simple example working.   After hours of searching, I'm unable to get decorated methods to fire on the flask side. Originally I thought it was an issue with how I was using init_app(), so I setup a separate simple app to test.

The flask app is receiving the messages from the client as shown in the logs below, however, nothing ever is printed out in the debug terminal/log from the flask side.

**Example**:

```python
from flask import Flask
from flask_socketio import SocketIO
    
app = Flask(__name__)
socketio = SocketIO(app, cors_allowed_origins="*", engineio_logger=True)

print("--------started this thing-------------")

@app.route("/")
def test():
    return {"status":"success"}
    
@socketio.on('connect')
def test_connect():
    print("client connected")

@socketio.on("my event")
def handle_my_event():
    print("my event received")

@socketio.on('disconnect')
def test_disconnect():
    print('Client disconnected')

if __name__ == '__main__':
    socketio.run(app, host="127.0.0.1", port="50000", debug=True)
```

**Client**

```typescript
        this.socket = io("http://localhost:50000", {transports: ['websocket']});

        this.socket.on("connect", (s:any) => {
            console.log("I'm connected");
            this.socket.emit("my event", "hi from client");
        });
```

The Chrome console shows: 
`I'm connected`

**Log output**
(I hit the root flask endpoint once to ensure it was working properly):

```
 * Restarting with stat
Server initialized for eventlet.
--------started this thing-------------
 * Debugger is active!
 * Debugger PIN: 211-366-074
(23220) wsgi starting up on http://127.0.0.1:50000
(23220) accepted ('127.0.0.1', 51665)
127.0.0.1 - - [10/Dec/2020 10:08:58] "GET / HTTP/1.1" 200 158 0.001025
(23220) accepted ('127.0.0.1', 51666)
(23220) accepted ('127.0.0.1', 51695)
seMQWqIBE5HpGVpeAAAA: Sending packet OPEN data {'sid': 'seMQWqIBE5HpGVpeAAAA', 'upgrades': [], 'pingTimeout': 5000, 'pingInterval': 25000}
seMQWqIBE5HpGVpeAAAA: Received request to upgrade to websocket
seMQWqIBE5HpGVpeAAAA: Upgrade to websocket successful
seMQWqIBE5HpGVpeAAAA: Received packet MESSAGE data 0
seMQWqIBE5HpGVpeAAAA: Sending packet MESSAGE data 0{"sid":"vr8DGa1DK0tQHBgxAAAB"}
seMQWqIBE5HpGVpeAAAA: Received packet MESSAGE data 2["my event","hi from client"]
```

**conda environment**

According to the table on the Python-SocketIO repo, If I'm using version 3 of the Javascript library, I need to be using version 4 of python-engineio and version 5 of python-socketio.

```
dependencies:
  - bidict=0.21.2=py_0
  - ca-certificates=2020.12.5=h5b45459_0
  - certifi=2020.12.5=py38haa244fe_0
  - cffi=1.14.4=py38hd8c33c5_1
  - click=7.1.2=pyh9f0ad1d_0
  - cryptography=3.3.1=py38hd8c33c5_0
  - dnspython=1.16.0=py_1
  - ecdsa=0.16.1=pyhd8ed1ab_0
  - eventlet=0.29.1=py_0
  - flask=1.1.2=pyh9f0ad1d_0
  - flask-socketio=4.3.2=pyhd3eb1b0_0
  - greenlet=0.4.17=py38h1e8a9f7_1
  - idna=2.10=pyh9f0ad1d_0
  - itsdangerous=1.1.0=py_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - markupsafe=1.1.1=py38hab1e662_2
  - monotonic=1.5=py_0
  - openssl=1.1.1h=he774522_0
  - pip=20.3.1=pyhd8ed1ab_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pycryptodome=3.9.9=py38h294d835_0
  - pyopenssl=20.0.0=pyhd8ed1ab_0
  - python=3.8.6=h7840368_1_cpython
  - python-engineio=4.0.0=pyhd3eb1b0_0
  - python-socketio=5.0.1=pyhd3eb1b0_0
  - python_abi=3.8=1_cp38
  - setuptools=49.6.0=py38h9bdc248_2
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.34.0=h8ffe710_0
  - vc=14.1=h869be7e_1
  - vs2015_runtime=14.16.27012=h30e32a0_2
  - werkzeug=1.0.1=pyh9f0ad1d_0
  - wheel=0.36.1=pyhd3deb0d_0
  - wincertstore=0.2=py38h32f6830_1005
```

**Additional Information**
This is on Windows 10 machine running a properly activated virtual environment using the werkzeug server for now in development.

Am I too far into to coding rabbit hole that I don't see the obvious issue right in front of my face?

**Comment by miguelgrinberg** [comment]
Your installation is incorrect, you have incompatible dependencies installed. Uninstall `flask-socketio`, `python-socketio` and `python-engineio` and then reinstall `flask-socketio` so that it pulls the correct versions of the other two dependencies.

**Comment by brettrichards** [comment]
Thanks @miguelgrinberg 

I'm now at 
```
  - flask-socketio=4.3.2=pyhd8ed1ab_0
  - python-engineio=3.11.2=py_0
  - python-socketio=4.5.1=pyh9f0ad1d_0
```
[this table](https://github.com/miguelgrinberg/python-socketio#python-socketio) shows the JS version should be 2.X for those dependencies, or does this situation not apply to flask-socketio at all?

I ask because the version I have from NPM was 3.0.2.  I'm wondering if I need to downgrade that as well.

**Comment by miguelgrinberg** [comment]
Yes, the table is correct. Use 2.x.

**Comment by brettrichards** [comment]
Thank you!  After re-installing with the correct dependencies, and downgrading my NPM to 2.3.1, I'm able to connect from the client with flask acknowlegding via a print statement.
