### ISSUE TITLE
Session Stickiness in Docker Swarm

### ISSUE THREAD

**Issue by anandtripathi5** [miguelgrinberg/Flask-SocketIO#1431]
I'm implementing the WebSocket application using docker swarm.
My Nginx and backend application is in docker swarm and Nginx is forwarding the request to backend service using reverse proxy.

I have 2 replicas of the backend application and used the service name in the reverse proxy of Nginx. But the WebSocket requests are failing cause the request are handled by any of the two replicas. I want to have a sticky session based on ip_hash so that on the basis of the request will go to one replica only.

I checked on the web and it seems there is only one solution that is using Traefik as a loadbalancer. But I cannot do that cause we are using AWS load balancer for it and we cannot replace AWS load balancer with Traefik.

Have you have any idea how I can implement websocket with backend in docker swarm and having replicas more than one. Cause I'm planning to use this in production and on production the replicas are more in numbers generally.

@miguelgrinberg Thanks in Advance

**Comment by miguelgrinberg** [comment]
Websocket does not require sticky sessions, long-polling does. If you force all clients to connect via WebSocket then you do not need to have sticky sessions in your server.

**Comment by anandtripathi5** [comment]
How I can do that??

**Comment by miguelgrinberg** [comment]
Those are options that your Socket.IO client must provide. Check the documentation for the client that you are using to see how this is done.

**Comment by anandtripathi5** [comment]
Cool, let me check. Thanks for the response

**Comment by anandtripathi5** [comment]
Hi @miguelgrinberg, I disabled the long polling using the below command, and it's working fine now. Thanks

`const socket = io(<url>, {transports:['websocket']})`
