### ISSUE TITLE
The client is using an unsupported version of the Socket.IO or Engine.IO protocols (further occurrences of this error will be logged with level INFO)

### ISSUE THREAD

**Issue by shreshtha-stack** [miguelgrinberg/Flask-SocketIO#1432]
I am running this repo, but it is showing the above error.  I have install ( pip install flask-socketio) using python3. 

and this also, 

127.0.0.1 - - [14/Dec/2020 17:31:32] "GET /socket.io/?EIO=3&transport=polling&t=1607947292766-270 HTTP/1.1" 400 -
The client is using an unsupported version of the Socket.IO or Engine.IO protocols

**Comment by fuglede** [comment]
Just ran into the same issue; I managed to get around it by downgrading pinning some of its dependencies to `python-engineio==3.13.2` and `python-socketio==4.6.0`.

**Comment by miguelgrinberg** [comment]
See [version compatibility](https://flask-socketio.readthedocs.io/en/latest/#version-compatibility) in the documentation.

**Comment by fuglede** [comment]
@miguelgrinberg Since yesterday (or perhaps a few days ago?) the issue appears simply by installing the older version of Flask-SocketIO; from a user perspective, it would feel more natural if the constraints on `python-engineio` and `python-socketio` were baked into the constraints for `flask-socketio`; that is, so that `conda install flask-socketio=x.y.z` does not resolve to a combination of packages that will cause runtime issues.

**Comment by miguelgrinberg** [comment]
@fuglede I cannot revise an existing version. I can only publish a new version with the constraints once they are known, which I did. If you install the latest of the 4.x versions you'll get the correct dependencies.

On the other side, you can easily avoid this problem by pinning your dependencies with `pip freeze`. You should always do this, it's the only way to avoid problems like this.

**Comment by fuglede** [comment]
@miguelgrinberg Right, makes sense, ensuring that the latest 4.x has the proper dependencies does indeed sound as good as it gets. However, with conda, that's not actually what it looks like right now; `conda install flask-socketio` in a blank environment gives the incompatible combination

```
  flask-socketio     pkgs/main/noarch::flask-socketio-4.3.2-pyhd3eb1b0_0
  python             pkgs/main/win-64::python-3.9.1-h6244533_2
  python-engineio    pkgs/main/noarch::python-engineio-4.0.0-pyhd3eb1b0_0
  python-socketio    pkgs/main/noarch::python-socketio-5.0.1-pyhd3eb1b0_0
```

**Comment by miguelgrinberg** [comment]
@fuglede That seems to be a conda problem. The latest published version of Flask-SocketIO is 5.0.0, and you are still getting 4.3.2. And the 4.3.2 release does have the upper bound version on python-socketio set, as you confirm yourself here: https://github.com/miguelgrinberg/Flask-SocketIO/blob/0bd5eea91477054ba42a9841915c38aa244a843d/setup.py.

**Comment by fuglede** [comment]
Yep, the `run` subsection of the `requirements` section of the [4.3.2 conda package](https://anaconda.org/anaconda/flask-socketio/4.3.2/download/noarch/flask-socketio-4.3.2-pyhd3eb1b0_0.tar.bz2)'s `info/recipe/meta.yaml` only has

```
    run:
        - flask >=0.9
        - python
        - python-socketio >=4.3.0
```

**Comment by shreshtha-stack** [comment]
Actually I got the solution of this in my case updating the Flask-SocketIO==4.3.2 resolves this issue. You no need to pull lower version of python-engineio.

**Comment by BlkPingu** [comment]
> Actually I got the solution of this in my case updating the Flask-SocketIO==4.3.2 resolves this issue. You no need to pull lower version of python-engineio.

this fixed it for me. I just uninstalled everything in the venv and let flask_socketio==4.3.2 pull the flask version it needed and it worked.

**Comment by thunder1234x** [comment]
RUN THESE TWO COMMANDS That May BE SOLVE  This Problem

1st:
pip install python-socketio==3.1.2 

2nd:
pip install flask-socketio==4.3.2

and then restart the server and  my probloem was solved

**Comment by miguelgrinberg** [comment]
@thunder1234x the versions that you are using are super old, in particular your Socket.IO client version 1.4.5 was released in January 2016! Why would you recommend such an old release? Use version 2.3.0 instead, which is fully compatible with the 4.3.2 release of Flask-SocketIO.

**Comment by thunder1234x** [comment]
ya .i have checked with 2.3.0 it is working Fine . Both of it working
fine.Thanks for your Tips

**Comment by littlethumb123** [comment]
Downgrade the flask-socketio 5.0.1 to 4.3.2 which also brings python-engineio-3.14.2 python-socketio-4.6.1 solved problem.

**Comment by codexponent** [comment]
@littlethumb123 solution:

> Downgrade the flask-socketio 5.0.1 to 4.3.2 which also brings python-engineio-3.14.2 python-socketio-4.6.1 solved problem.

fixed it for me. Thank you.

**Comment by Helveg** [comment]
This seems to be a frequently recurring issue; If there is a blocking version check like this, please specify it in `setup.py` and not inside of the codebase. This is exactly why version restrictions exist in pip.

**Comment by miguelgrinberg** [comment]
@Helveg the problem is that I would need a time machine to go back and fix versions that were released before this new incompatible version was known.

**Comment by Helveg** [comment]
Oh, I thought there was some hard coded version checking going on since it reported an error about versions. And if your upstream dependencies behave nicely then you can restrict to the current major version and use something like `dependabot` to propose automatic PRs for you. Then it's nothing more than verifying that that PR passes CI and you can release a new patch version yourself with the new major version of your dependency

**Comment by miguelgrinberg** [comment]
The reported error is done at runtime, when the client indicates what version of the Socket.IO protocol they speak. It's not a dependency check between Python packages.

**Comment by neuronflow** [comment]
Hmm I have these versions running on server side:
```
Flask-SocketIO==5.0.1
python-engineio==4.0.0
python-socketio==5.0.4
```

client side:
```
python-engineio==4.0.0
python-socketio==5.0.4
```

Server says:
```
The client is using an unsupported version of the Socket.IO or Engine.IO protocols (further occurrences of this error will be logged with level INFO)
```

Client crashes when calling: `self.sio.connect('http://localhost:5000')`:
```
Traceback (most recent call last):
  File "/home/florian/anaconda3/envs/btk_test/lib/python3.8/site-packages/socketio/client.py", line 276, in connect
    self.eio.connect(url, headers=headers, transports=transports,
  File "/home/florian/anaconda3/envs/btk_test/lib/python3.8/site-packages/engineio/client.py", line 189, in connect
    return getattr(self, '_connect_' + self.transports[0])(
  File "/home/florian/anaconda3/envs/btk_test/lib/python3.8/site-packages/engineio/client.py", line 299, in _connect_polling
    raise exceptions.ConnectionError(
engineio.exceptions.ConnectionError: ('Unexpected status code 400 in server response', 'The client is using an unsupported version of the Socket.IO or Engine.IO protocols')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/florian/flow/btk_test/BraTS-Toolkit/0_preprocessing_single.py", line 17, in <module>
    prep.single_preprocess(t1File=t1File, t1cFile=t1cFile, t2File=t2File, flaFile=flaFile,
  File "/home/florian/flow/btk_test/BraTS-Toolkit/src/brats-toolkit/brats_toolkit/preprocessor.py", line 106, in single_preprocess
    self.batch_preprocess(exam_import_folder=dockerFolder, exam_export_folder=dockerOutputFolder, mode=mode,
  File "/home/florian/flow/btk_test/BraTS-Toolkit/src/brats-toolkit/brats_toolkit/preprocessor.py", line 127, in batch_preprocess
    self.connect_client()
  File "/home/florian/flow/btk_test/BraTS-Toolkit/src/brats-toolkit/brats_toolkit/preprocessor.py", line 131, in connect_client
    self.sio.connect('http://localhost:5000')
  File "/home/florian/anaconda3/envs/btk_test/lib/python3.8/site-packages/socketio/client.py", line 279, in connect
    self._trigger_event(
  File "/home/florian/anaconda3/envs/btk_test/lib/python3.8/site-packages/socketio/client.py", line 550, in _trigger_event
    return self.handlers[namespace][event](*args)
TypeError: connect_error() takes 0 positional arguments but 1 was given
```

Any suggestions what I am doing wrong?

**Comment by Torxed** [comment]
I'm hesitant to open a new ticket for this @miguelgrinberg, but your [documentation on the website](https://flask-socketio.readthedocs.io/en/latest/#Initialization) feels all off if I understand this thread correctly. 
```javascript
<script src="//cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.js" integrity="sha256-yr4fRk/GU1ehYJPAs8P4JlTgu0Hdsp4ZKrx8bDEDC3I=" crossorigin="anonymous"></script>
<script type="text/javascript" charset="utf-8">
    var socket = io();
    socket.on('connect', function() {
        socket.emit('my event', {data: 'I\'m connected!'});
    });
</script>
```
Causes this issue, which is the example-code you're giving on your main documentation.
If this isn't supported, then I strongly recommend you to change it.

Starting out with this library is a bit of a PITA when the "getting started" documentation presents a copy-paste test code, that doesn't actually work. And the debugger isn't turned on by default in the flask example so finding out why you're getting `http://127.0.0.1:5000/socket.io/?EIO=3&transport=polling&t=XXXXX 400 (BAD REQUEST)` errors is a bit of a PITA for someone that just started out.

**Comment by miguelgrinberg** [comment]
@Torxed I missed updating the version in the docs example, sorry about that. Clearly very few people read the documentation, most go to the examples, which I did update and tested. In any case, I have updated it now.

**Comment by Torxed** [comment]
> @Torxed I missed updating the version in the docs example, sorry about that. Clearly very few people read the documentation, most go to the examples, which I did update and tested. In any case, I have updated it now.

Cool, thanks for the quick update. Also I might have sounded a bit harsh - was a bit tired and frustrated at the time. I for one have far worse documentation for my projects and shouldn't be one to judge :)

**Comment by bneumann** [comment]
This is a quite interesting bug. I updated my packages now to the latest version and now I am getting this error as well. The interesting part is, that I am using the ```app.test_client()``` to connect inside my unit tests.
My versions are:
```
Flask==2.0.2
Flask-Cors==3.0.10
Flask-SocketIO==5.1.1
python-engineio==4.3.1
python-socketio==5.5.1
```

My server setup:
```python
app = Flask(__name__, instance_relative_config=True)
app.config.update(
    SECRET_KEY=environ.get("SECRET_KEY", "dev"),
    SOCKET_URL=environ.get("SOCKET_URL", "/")
)
print("Starting with config:")
print(app.config)
CORS(app)
app.config["CORS_HEADER"] = "Content-Type"
socketio = SocketIO(app, cors_allowed_origins="*", logger=True, path=app.config["SOCKET_URL"])
self.socket = socketio
```

I am setting up my client in a fixture:
```python
@pytest.fixture
def client(app: Flask) -> FlaskClient:
    client = app.test_client()

    yield client
```

My tests calls:

```python
# bla bla setup bla
response = client.get("/list")
assert response.status_code == 200 # this fails because it returns the version error
```

Could it be that I somehow need to explicitly set the test client version?

I tried downgrading to the mentioned versions which caused everything to stop working (I can't get a connection at all and there is no logging whatsoever.) The funny thing is that this here mentioned version works in production but not in the API unit tests. ¯\_(ツ)_/¯

**Comment by Oakento** [comment]
same error with
```
Flask==2.3.2
flask-socketio==5.3.4
python-engineio==4.4.1
python-socketio==5.8.0
```
😥

**Comment by miguelgrinberg** [comment]
@Oakento I have explained this several times above. The problem is between your Socket.IO client and the Socket.IO server, it is not a problem with your Python packages, you have to look at the version compatibility table in the docs and ensure that your client and your server are on compatible versions.

**Comment by PrinceSendai** [comment]
Giving me this error and I can't fix it. My versions are:

Flask-SocketIO==5.3.6
python-engineio==4.8.0
python-socketio==5.10.0

**Comment by miguelgrinberg** [comment]
@PrinceSendai read the comment I made immediately above yours. The issue is between server and client, not between the packages you have on the server.

**Comment by oc8** [comment]
⚠️ for me it was a CORS error, try to add `cors_allowed_origins="*"`
