### ISSUE TITLE
Maintain app state of connected clients

### ISSUE THREAD

**Issue by dternyak** [miguelgrinberg/Flask-SocketIO#1436]
How would you best suggest implementing an in-app (really, in redis) state of connected clients?

So far, our main issue appears to be relying on `disconnect` events being fired. For example, in instances of the backend going offline, those `disconnects` would not be fired, even if the socket really did get disconnected. This would cause us to maintain in our list of active clients, a request.sid that is really not active anymore, since we would have never cleaned it up.

Right now, our best idea is to basically re-implement the ping/pongs you have in the internal code in our own background task, but to make them stateful at the shared redis level, and maintain a list of "live" request.sids that way. We would get our redis list of request.sids that were added at the `connect` event, and then drop whichever ones out of our list if we perceived that they were not active anymore through our own ping/pong.

Would love to get your thoughts on the best way to approach this. I imagine this is a common need, so I'm curious if there's somewhere you can point me where others have done this as well.

**Comment by dternyak** [comment]
On a similar note, is it possible to "listen in" to ping/pongs? It might be neater for us to determine ourselves, outside of the `disconnect` event, if a request.sid is still active or should be removed from the active client list in redis.

**Comment by dternyak** [comment]
In cases of downtime on our app, it would certainly be nice to cleanup redis without relying on capturing `disconnect` events. Let me know if you have a good idea for a pattern on how to determine whether a socket is active, given a request.sid.

**Comment by dternyak** [comment]
To update, the approach I ended up going with was to trigger `ping/pongs` as needed, and then kick-off a celery task after 5 seconds to see if a redis entry with a timestamp within 5 seconds exists for the request.sid that I just pinged. If not, purge the request.sid from redis.

Seems to work well enough, but still curious about your thoughts.

**Comment by miguelgrinberg** [comment]
There is currently no way to attach to the ping/pong events. These are internal and part of the Socket.IO protocol, and in fact there has been a major change in how these work in the most recent update of the protocol, so I'm  not planning to expose these as application events.

What I have done for this type of problem is to implement custom pings from the client. For example, let's say the client sends a ping every 2 minutes. When the ping is received, the server writes a key to Redis with an expiration of 2.5 minutes. As long as the client continues to send pings, Redis will keep the client's state. If the client drops, the key will expire and dissappear.

**Comment by dternyak** [comment]
Ah, this is an interesting approach. I wasn't aware that you could write expirable keys to redis. Thank you!
