### ISSUE TITLE
Disconnecting sockets outside event handler context

### ISSUE THREAD

**Issue by jjedele** [miguelgrinberg/Flask-SocketIO#1437]
Hi,
I found several related issues, but I didn't find a satisfactory answer in them.

I want to have an internal (HTTP) API which disconnects all web sockets connected to the current server instance (temporary solution because we have a test client which doesn't clean up its connections properly and messes up some of our application metrics).

Currently I'm doing the following:
```python
sio = SocketIO(async_mode="threading", logger=logging.getLogger("socketio"))
...
def disconnect():
    sids = sio.server.manager.get_participants(namespace="/", room=None)
    for sid in sids:
        sio.server.disconnect(sid, namespace="/")
```

The first part (getting the SIDs) seems to work fine, but the first call to `disconnect()` blocks and never returns.

So two questions:
1. Is this supported?
2. Any idea why it doesn't work?

**Comment by jjedele** [comment]
It seems the socket actually disconnects, but after that it hangs and doesn't return.

**Comment by miguelgrinberg** [comment]
Couple of things.

First of all, you are logging Socket.IO, so sid you look at the logs?
Second, you are using internal methods that are not part of the public API of this package. Be aware that these can change at any time, and in fact, the `get_participants()` call has changed in a breaking way in the latest release.

**Comment by jjedele** [comment]
Hey @miguelgrinberg , thx for answering so quickly. Let's quickly clarify which of the things we are doing are not officially part of the API:
1. `get_participants()` - OK, fully aware of this. I guess the "official" way of this would be implementing our own registry using the connect and disconnect event handlers? But this part seems to work fine right now.
2. `sio.server.disconnect()` - Let's just say I'm using `flask_socketio.disconnect` instead then. Behaves exactly the same way.

The logs look OK to me:
```
INFO:socketio:5ab1bad47ac5452097e066a0d5eed5a3 is entering room u::3 [/]
INFO:socketio:5ab1bad47ac5452097e066a0d5eed5a3 is entering room o::1 [/]
DEBUG:MA:Socket connected for session=None.
INFO:CommunicationRouter:Starting server-side disconnect of 1 websockets.
INFO:CommunicationRouter:Server-side disconnect for websocket 5ab1bad47ac5452097e066a0d5eed5a3.
INFO:socketio:Disconnecting 5ab1bad47ac5452097e066a0d5eed5a3 [/]
DEBUG:MA:Socket disconnected for session=None.
```

The `CommunicationRouter` logs are when I call my method. It actually looks like the socket is disconnected as I would expect, but the call to `disconnect()` never returns. When I cancel the request and trigger it again, it continues to the next socket or finishes.

**Comment by miguelgrinberg** [comment]
> I guess the "official" way of this would be implementing our own registry using the connect and disconnect event handlers?

Yes, that is the correct way to do this. As I said above, when you upgrade Flask-SocketIO to the latest release this code will break.

> Let's just say I'm using flask_socketio.disconnect instead then

That would be better. Note that this was just advice I was giving you, I did not intend to imply the issue was related to the use of these internal calls.

What is your `disconnect()` function that does all of this? Is it a Flask route? A Socket.IO handler?

**Comment by jjedele** [comment]
Thx for the advice regarding both points! I think I even started out with `flask_socketio.disconnect`, but then tried some other APIs because I ran into this problem. I changed it back now. For the `get_participants` I'll add a TODO, but I want to see first if we need this method long enough to make it worth implementing a more mature solution for this.

> What is your disconnect() function that does all of this? Is it a Flask route? A Socket.IO handler?

It's a function which in turn is called from a Flask route. Not a Socket.IO handler.

Maybe also of interest: The local setup I'm currently testing this with is using the non-upgraded polling transport. Might this somehow block the socket from closing?

**Comment by miguelgrinberg** [comment]
I'm not able to reproduce this here, and I tried both with WebSocket and with long-polling. Will you be able to create a small and complete example I can use to see this hang?

**Comment by jjedele** [comment]
Hey. Yes, I'm able to reproduce it with a minimal example: 
[socketio-1437.zip](https://github.com/miguelgrinberg/Flask-SocketIO/files/5714855/socketio-1437.zip)

1. Start server by running `app.py`
2. Connect a socket by running `client.py`
3. Call disconnect method: `curl localhost:5000/disconnect`

On 3. I see that the connection is actually terminated (both in the server logs and because the client quits). But the curl call never returns.

**Comment by miguelgrinberg** [comment]
I can reproduce this with older versions, and only when long-polling is used (WebSocket is fine). With the latest version I cannot reproduce the problem, but of course, as I mentioned before, your code needs to be adapted to work with it. 

In the server, the disconnect loop needs to use `sid[0]` instead of just `sid`:

```python
    for sid in sids:
        disconnect(sid[0], namespace="/")
```

In the client, the `connect_error` event takes one argument:

```python
@sio.event
def connect_error(e):
    print("The connection failed!")
```

**Comment by jjedele** [comment]
Ok, thank you very much for your help! Then updating is probably a good idea.
