### ISSUE TITLE
Docker is buggy, but it is ok not to use Docker

### ISSUE THREAD

**Issue by dayhappy2012** [miguelgrinberg/Flask-SocketIO#1438]
![image](https://user-images.githubusercontent.com/47685606/102518326-1c770400-40cc-11eb-89b2-dadb32b12337.png)

The client is using an unsupported version of the Socket.IO or Engine.IO protocols

**Comment by dayhappy2012** [comment]
@miguelgrinberg

**Comment by miguelgrinberg** [comment]
@dayhappy2012 the error message is correct, you are using incompatible Socket.IO client and servers.

**Comment by umityayla** [comment]
You may want to check #1432 @dayhappy2012 . Upgrading to `Flask-SocketIO==4.3.2`solved my issue like described.

**Comment by dayhappy2012** [comment]
@umityayla You can't use Flask-SocketIO==4.3.2 before, you can't use Flask-SocketIO==5.0.0 now

**Comment by dayhappy2012** [comment]
Is docker port forwarding a problem

**Comment by umityayla** [comment]
I don't really think so, are you sure that your client's version is correct? Also, can you provide your requirements.txt file?

**Comment by dayhappy2012** [comment]
Flask==1.1.2
Flask-Cors==3.0.8
flask-peewee==3.0.3
flask-redis==0.4.0
Flask-Session==0.3.1
Flask-SocketIO==4.3.0
Flask-SQLAlchemy==2.4.1

@umityayla

**Comment by umityayla** [comment]
Yeah, when I tested it. I got the same response too but by changing `Flask-SocketIO==4.3.0` to `Flask-SocketIO==4.3.2` fixed my problem. 

But, when I installed Flask-SocketIO==5.0.0 problem occured again. @miguelgrinberg

**Comment by dayhappy2012** [comment]
@umityayla thanks, I try it again

**Comment by miguelgrinberg** [comment]
Sorry guys, but you seem to be just blindly trying different things until something works, while this problem has been documented. Look in the documentation for the version compatibility table and pick all your dependencies so that they all belong to the same row in the table. It's not rocket science, just use compatible packages for the client, Flask-SocketIO, python-socketio and python-engineio.
