### ISSUE TITLE
How to handle unexpected disconnections?

### ISSUE THREAD

**Issue by YalinThin** [miguelgrinberg/Flask-SocketIO#1440]
Hi miguelgrinberg,

I am developing a simple customer service chat system using flasksocketio. I have a scenario like this. Server side will reply frontend by calling an external api after receiving messages from frontend. It may take a few secondes to get api returned result. If frontend clients disconnect unexpectedly before server side get api returned result, server emit should be failed. I think frontend client will not receive this message when it re connects again. So my question is, do we have any best practices to deal with such cases, if server emit failed, what can we do to make sure frontend doesn't miss any messages when it re connect again. Hope you can share some ideas, thanks for your time!

**Comment by miguelgrinberg** [comment]
@YalinThin You need to keep some state in your application, so that this notifications can be requested by the client when it reconnects.

**Comment by YalinThin** [comment]
@miguelgrinberg, thanks for your immediate answer.  I'm trying to understand, when you say "state", do you mean client cocket connection state? So I think database may be a option to keep the state, right?  In my code, I need to update the connection state in database when connect or disconnect event is fired. And before I can emit message to client, I need to use a while loop or something else to check the connection state. Please correct me if my understanding is wrong.

**Comment by miguelgrinberg** [comment]
By "keeping some state" I mean storing these notifications in a database or other storage until you are sure that the client has received them. When a client reconnects it can ask the server to receive any pending notifications, that you will read from the database.

**Comment by YalinThin** [comment]
Thanks miguelgrinberg, I think I understand your approach now. I have another question, does flasksocketio provide a function which return socket connection status?

**Comment by miguelgrinberg** [comment]
I don't know what you mean. Flask-SocketIO manages a connection per client. It does not manage clients that aren't connected.

**Comment by YalinThin** [comment]
@miguelgrinberg , I created a socketio instance in frontend page with a dynamic namespace, the server side connection listener can response, but I cannot get the right namespace. When I click connect button in frontend page, the server side get global namespace "/", but I want to get the namespace which I defined in frontend. Could you teach me how to get the namespace I want?

server code:
@socket.on('connect')
def connect():
    print('##############', request.namespace)
    print('client connected.')

client code:
var namespace = '/' + $('#username').attr('value');
  $("#connect").click(function(){
      window.socket = io.connect('http://' + document.domain + ':' + location.port+namespace); 
  }); 

server side printed information:

127.0.0.1 - - [29/Dec/2020 12:05:52] "GET /index/client_101/f0005 HTTP/1.1" 200 4802 0.001994
############## /
client connected.
127.0.0.1 - - [29/Dec/2020 12:05:59] "GET /socket.io/?EIO=3&transport=polling&t=1609214759326-0 HTTP/1.1" 200 371 0.002990
127.0.0.1 - - [29/Dec/2020 12:05:59] "POST /socket.io/?EIO=3&transport=polling&t=1609214759336-1&sid=4cb645d41d934f78b9aab7b262a2b036 HTTP/1.1" 200 219 0.000998
(30384) accepted ('127.0.0.1', 49706)
127.0.0.1 - - [29/Dec/2020 12:05:59] "GET /socket.io/?EIO=3&transport=polling&t=1609214759349-2&sid=4cb645d41d934f78b9aab7b262a2b036 HTTP/1.1" 200 183 0.000982

**Comment by miguelgrinberg** [comment]
This package does not support dynamic namespaces.

**Comment by YalinThin** [comment]
I use different namespaces for each client socket creation. In background thread, I emit message to specific user client  when I get data from some api. To make sure background data can be emitted successfully, I want to add some codes before emit action to check if the specific user client is still in connecting. My idea is maintaining connection status by username in background, but I cannot get the mapping relationship of usernames and socket instances. Could you help me what features I can use from your package to slove my problems?

client code:
var namespace = '/' + $('#username').attr('value');
$("#connect").click(function(){
window.socket = io.connect('http://' + document.domain + ':' + location.port+namespace);
});
window.socket.on('chat', function(data){
      console.log(data)
});

background code:
from flask_socketio import emit
data = call_some_api()
username = data.get('username')
emit('chat', data, broadcast=True, namespace='/{}'.format(username))

**Comment by miguelgrinberg** [comment]
You can't use dynamic namespaces, as I explained that is not supported by the Python server. You will need to change your client to use the same namespace for all your clients.

To know if a client is connected or disconnected you can create `connect` and `disconnect` event handlers, which are invoked as clients come and go.

**Comment by YalinThin** [comment]
Thanks miguelgrinberg, I think I can get some inspiration from this thread 
https://stackoverflow.com/questions/39423646/flask-socketio-emit-to-specific-user .  
I'm trying to understand, when a socket client is connected to server, an unique sid value is generated. I can let the user which  represents each socket client join a room named by username, therefor I can build a mapping relationship between sid value and username, when disconnect event is fired, I could know which sid or which username is disconnected from server, right? Pleaase correct me if my understanding is wrong. 

server code:
user_mapping = dict()
@socket.on('connect')
def connect():
    print('client connected.')

@socket.on('disconnect')
def disconnect():
    username = user_mapping.pop(request.sid)
    print('{} has discconnected.'.format(username))

@socket.on('join')
def on_join(data):
    username = data['username']
    user_mapping[request.sid] = username
    join_room(username)
    print("{} has joined the room {}".format(username, username))

**Comment by miguelgrinberg** [comment]
@YalinThin Yes, you reasoning seems correct.

**Comment by YalinThin** [comment]
@miguelgrinberg  Thanks for your great help. Wish you have a nice day.
