### ISSUE TITLE
not broadcasting in room in example

### ISSUE THREAD

**Issue by lerefor** [miguelgrinberg/Flask-SocketIO#1441]
Fix a little bug in app.py

@socketio.event
def my_room_event(message):
    session['receive_count'] = session.get('receive_count', 0) + 1
    emit('my_response', {'data': message['data'], 'count': session['receive_count']}, to=message['room'])

should be

@socketio.event
def my_room_event(message):
    session['receive_count'] = session.get('receive_count', 0) + 1
    emit('my_response', {'data': message['data'], 'count': session['receive_count']}, to=message['room']**, broadcast=True**)

in order to broadcast the msg to all room users

**Comment by miguelgrinberg** [comment]
The fix was a bit more involved than what you suggested, but it should be working ow. Thanks!
