### ISSUE TITLE
Amazon SQS?

### ISSUE THREAD

**Issue by sinedie** [miguelgrinberg/Flask-SocketIO#1442]
Hey there, I've been experimenting with redis as broker and it works good.

Was wondering if this library can use Amazon SQS like message broker? and if so, is used like celery+sqs or need something else?

Ty for your time

**Comment by miguelgrinberg** [comment]
There is currently no support for SQS. This would require adding the support in the python-socketio package, which has a extensible framework to add different message queues. I think this would have to be a combination of SNS/SQS, not just SQS.

**Comment by sinedie** [comment]
Mmm, I see... Well, sounds like I have to use Redis in production too... Ty for the quick reply. Closing this issue.

**Comment by stephendwolff** [comment]
i've just switched Celery from using redis, to use SQS instead as a test, then i've realised that python/flask socketio doesn't (yet) support it. The celery change takes advantage of support in Kombu, so i was wondering how tricky you think this might be to add? I may well get a chance to have a go so any tips would be very welcome!

**Comment by miguelgrinberg** [comment]
I haven't tested this, but there is a driver for Kombu in python-socketio, so I think it should work exactly as it does for Celery.

**Comment by stephendwolff** [comment]
I've used the same SQS queue url, and while it appears to work (ie no errors), the behaviour of socketio has changed, i don't seem to be getting the events emitted to multiple clients as before. Do i need a separate url, or is there a pub-sub use of redis with socketio that would require SNS (which you mention briefly above in this thread)?

**Comment by miguelgrinberg** [comment]
I'm not really sure, because I'm not familiar with the way Kombu implements SQS support. My comment was about how I thought an implementation of pub/sub on AWS would work. A quick review of the docs do not appear to indicate the SQS implementation is lacking with respect to RabbitMQ and Redis, but maybe it is.

**Comment by stephendwolff** [comment]
Ok thanks. I’ll dig deeper

**Comment by stephendwolff** [comment]
Also SQS has two message queue types, one which guarantees the message is delivered at least once, and a fifo queue where it is only once and order matters. I think I need to try the fifo queue
