### ISSUE TITLE
How to  show users online or offline in real time using flask and socket io even user close the browser without logout?

### ISSUE THREAD

**Issue by janmejayniit** [miguelgrinberg/Flask-SocketIO#1443]

**Comment by miguelgrinberg** [comment]
You can keep track of what users are online or offline by adding connect and disconnect handlers.

**Comment by janmejayniit** [comment]
Thank you. Could you please share some code for that.

**Comment by miguelgrinberg** [comment]
@janmejayniit I don't have any examples to show you. It does not need to be very sophisticated, you have a global variable set to an empty list. In the connect handler you add the user to the list, and in the disconnect handler you remove it. Then all the users that are on the list are online, while everyone else is offline.

**Comment by janmejayniit** [comment]
Thank You for your valuable response ..
 After successful login i can Login status is changed to live (green mark) but after closing the browser i am not able to disconnect the users from the socket io.
I am sharing my code Please help me to find out the issue. 

--------------------------------------------
Server side code
---------------------------------------------
@socketio.on('connect', namespace='/test' )
def connect_handler():
    if current_user.is_authenticated :
        if current_user.id not in online_users_list:
            data={'id':current_user.id}
            online_users_list.append(data)
    emit('connect_res', {'id':current_user.id,'name':current_user.full_name,'loginTime':'','status':'online','onlineUsers':online_users_list}, broadcast=True)

@socketio.on('disconnect')
def test_disconnect():
    online_users_list.remove(current_user.id)
    emit({'logout_status':'logged out.'+ current_user.id }, broadcast=True)

-----------------------------------------------
client side code 
-----------------------------------------------

socket.on('connect_res',function(data){
	     	var onineUsers = data.onlineUsers;
	     	$("#__sublt li").each(function(index,item){
	     		var subs_id = $(this).data('follower_id'); 
				for(i=0; i<onineUsers.length; i++){
					if(onineUsers[i]['id']==subs_id){
						  $(this).find('.contact-status').attr('class','contact-status online');
					}
				}
	     	});
	    });

         window.addEventListener('beforeunload', (event) => {
            event.preventDefault();
             socket.disconnect();
            event.returnValue = '';
        });


---------------------------------------------------------------------------------------------------------------------------------------------

**Comment by miguelgrinberg** [comment]
Have you debugged your application? I can't really do it just by looking at the code. I suggest you make sure your list of online users is updated correctly when a user disconnects. From looking at the code it seems you are not doing it correctly, but as I said, you are in the best place to debug this and figure it out.

**Comment by janmejayniit** [comment]
Thank You sir i will try

**Comment by malay9418** [comment]
> Thank You sir i will try



> Thank You for your valuable response .. After successful login i can Login status is changed to live (green mark) but after closing the browser i am not able to disconnect the users from the socket io. I am sharing my code Please help me to find out the issue.
> 
> ## Server side code
> ```
> @socketio.on('connect', namespace='/test' )
> def connect_handler():
>     if current_user.is_authenticated :
>         if current_user.id not in online_users_list:
>             data={'id':current_user.id}
>             online_users_list.append(data)
>     emit('connect_res', {'id':current_user.id,'name':current_user.full_name,'loginTime':'','status':'online','onlineUsers':online_users_list}, broadcast=True)
> 
> @socketio.on('disconnect')
> def test_disconnect():
>     online_users_list.remove(current_user.id)
>     emit({'logout_status':'logged out.'+ current_user.id }, broadcast=True)
> ```
> 
> ## client side code
> ```
> socket.on('connect_res',function(data){
> 	     	var onineUsers = data.onlineUsers;
> 	     	$("#__sublt li").each(function(index,item){
> 	     		var subs_id = $(this).data('follower_id'); 
> 				for(i=0; i<onineUsers.length; i++){
> 					if(onineUsers[i]['id']==subs_id){
> 						  $(this).find('.contact-status').attr('class','contact-status online');
> 					}
> 				}
> 	     	});
> 	    });
> 
>          window.addEventListener('beforeunload', (event) => {
>             event.preventDefault();
>              socket.disconnect();
>             event.returnValue = '';
 >         });
> ```

***Problem***:-
okey, so the problem here is, when any client gets disconnected by just pressing back and exit or refreshes the page, then the server side ```socket.on('disconnect')``` will gonna be invoked. But in case the client just close the window directly then the server side disconnection method will not gonna invoked. Idk why is it like that. 

***Solution***:-
Just make a type of heart beat function on the client side, which will continuously give update as they are online, by any chance the beating get stucked then identify that the client is offline.

***Advantages***:-
1) No matter how the client's getting disconnected everytime this will work.
2) By receiving some data like current time you can show last seen time of a client.

Happy coding : )
