### ISSUE TITLE
Update CORS domains on the fly

### ISSUE THREAD

**Issue by dternyak** [miguelgrinberg/Flask-SocketIO#1444]
**Is your feature request related to a problem? Please describe.**
Currently, `cors_allowed_origins` looks like it's only able to be configured on instiation, or with `.init_app`. Our use case requires us to be able to dynamically update allowed origins based on user provided data that is stored in our database.

**Describe the solution you'd like**
It would be great to be able to provide a list of domains that are allowed when each request comes in, potentially in the `socket.on` decorator? We would make a db call to retrieve the list, and then provide that to `flask-socketio`.  Or we could provide a reference to a function to retrieve valid cors domains at instantiation.

**Comment by miguelgrinberg** [comment]
This is a very unusual use case. Why can't you just check the origin in the connect handler?

**Comment by dternyak** [comment]
We could, and that's what we do now. We have `"*"` as `cors_allowed_origins` initially, and then we have our own decorator that does a check. 

We're trying to make sure that our approach is very scalable, and I imagine that our current approach is a leaving on the table in terms of performance.

I definitely agree with you that this is not a typical case.

**Comment by miguelgrinberg** [comment]
I don't think a decorator is necessary for this task, because you have to check only once, in the connect handler. But either way, the origin check that this package performs is also done in Python, so in terms of performance it should e equivalent to your application based check.

**Comment by dternyak** [comment]
I see. We wanted to make sure that other handlers wouldn't be hit, but you're right, they would never make it past the single check in connect.

Thanks!
