### ISSUE TITLE
Location of init_app Causing Strangeness

### ISSUE THREAD

**Issue by robb17** [miguelgrinberg/Flask-SocketIO#1448]
I have a very niche question that may either be a result of a bug or an issue in my understanding of the function init_app().

When run locally, the following patterns in app/__init__.py both work as expected, where running is invoked by calling db.create_all(app=create_app(...)). The former method also works under gunicorn (with port specified after message_queue), whereas the latter results in strange behavior: the client is able to establish a websocket connection, but it seems that none of the event handlers declared in app/main.py are registered.

I'd like to use the latter, as I need to spin up multiple instances of the app, and I'd like to do so as cleanly as possible.

```
socketio = SocketIO(app, async_mode="eventlet", manage_session=False, message_queue="redis://")
socketio.init_app(app)

def create_app(supplied_port = 5000):
    app.config['SECRET_KEY'] = 'secret!'
    ...

```

```
socketio = SocketIO(app)

def create_app(supplied_port=5000, backend_id=1, path=None, queue_port=6379, local=False):
    global socketio
    global app
    if not local:
        socketio.init_app(app, message_queue="redis://localhost:" + str(queue_port), async_mode="eventlet", manage_session=False, path="/" + path + "/socket.io")
    else:
        socketio.init_app(app, message_queue="redis://localhost:" + str(queue_port), async_mode="eventlet", manage_session=False)

    app.config['SECRET_KEY'] = 'secret!'
```

main.py imports:

```
import eventlet
eventlet.monkey_patch()
from functools import wraps
import urllib.parse
from flask import Flask, Blueprint, render_template, request, session, redirect, url_for, flash, abort
from werkzeug.security import generate_password_hash, check_password_hash
from flask_socketio import SocketIO, join_room, leave_room
from . import db
import os, sys
from . import socketio
import random
import string
from itertools import combinations
from copy import deepcopy
from collections import deque
import re
from . import app
import requests
from threading import Thread, Lock, Event
import time
import datetime
import math
from flask_login import current_user, logout_user
import redis
import re
import rsa
import base64
```

Thanks!

**Comment by miguelgrinberg** [comment]
If you are going to use `init_app()`, then create the `SocketIO` object without any arguments. All the arguments must be passed in the call to `init_app()`. You can't pass some arguments in the constructor and some others in `init_app()`, that confuses things.

**Comment by robb17** [comment]
I'm not sure if that's what the issue is. I've spent quite a while testing out different series of calls with different parameters, and, at least for my app, I was able to achieve a working setup __in production__ only with the following:

```
socketio = SocketIO(app, async_mode="eventlet", manage_session=False, message_queue="redis://", path="<path>")
socketio.init_app(app)

def create_app(supplied_port = 5000):
    app.config['SECRET_KEY'] = 'secret!'
    ...
```
Omitting socketio.init_app(app) resulted in 404 errors: requests could not be forwarded to the appropriate backend.

The following series of calls also produced 404 errors:
```
socketio = SocketIO()
socketio.init_app(app, async_mode="eventlet", manage_session=False, message_queue="redis://", path="<path>")

def create_app(supplied_port=5000):
    app.config['SECRET_KEY'] = 'secret!'
    ...
```
I've attached part of my nginx config to give you a better idea of what my setup is:
```
    ...
    location / {
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 300;
        proxy_pass http://frontend_nodes;
    }

    location /p5000/socket.io {
        include proxy_params;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass http://127.0.0.1:6000/socket.io/;
    }
    location /p5001/socket.io {
        include proxy_params;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass http://127.0.0.1:6001/socket.io;
    }
    ...
```

**Comment by miguelgrinberg** [comment]
What URL was giving you 404 errors?

What you are doing is really weird. If you are using a `create_app()` function you should create your application inside the function, not outside.

And I stand by my suggestion. You have to pass all the arguments in the `SocketIO()` constructor and not call `init_app()`, or else you have to pass no arguments in `SocketIO()` and then pass all your arguments in `init_app()`. Those are the only two supported workflows. If you do something different you are sort of on your own, things may or may not work because you are using the extension in a way it wasn't designed to be used.

**Comment by robb17** [comment]
From the console: wss://example.com/p5002/socket.io/?EIO=3&transport=websocket' failed: Error during WebSocket handshake: Unexpected response code: 404

Is there a way to create the application inside the function while also being to access the application's context from, for example, auth.py? I've tried restructuring the layout of my codebase, but it seems as though I can't do so without losing the ability to, for example, spawn new threads that can do things within the application's context.

**Comment by miguelgrinberg** [comment]
> Is there a way to create the application inside the function while also being to access the application's context from, for example, auth.py?

I suggest you review how this tutorial structures the application, or actually any other tutorial or the official Flask documentation. The application does not need to be a global variable.

**Comment by robb17** [comment]
Once again, your documentation has proven superior to the third-party guides I sometimes reference. It looks like this sentence in your mega tutorial was exactly what I was looking for:

> Replacing `app` with Flask's `current_app` variable eliminates the need of importing the application instance as a global variable.

I will close this question shortly if all goes well. Thank you for your help.
