### ISSUE TITLE
[1.0b] Collistion in handling of SocketIO.run(...) arguments

### ISSUE THREAD

**Issue by ktoh** [miguelgrinberg/Flask-SocketIO#145]
The [`run(...)`](https://github.com/miguelgrinberg/Flask-SocketIO/blob/v1.0/flask_socketio/__init__.py#L260) method does the following with named arguments (i.e. `kwargs`):

* Converts them into `server_options` for configuring the bound `socketio.Server`
* When used with eventlets, [passes `kwargs` on to the `eventlet.wsgi.server`](https://github.com/miguelgrinberg/Flask-SocketIO/blob/v1.0/flask_socketio/__init__.py#L329), which is a sensible thing to do.

This propagated use of `kwargs` causes a few issues:

1. If an eventlet server argument is specified, it will get picked up in `server_options` and forwarded to the `socketio.Server(...)` constructor.  That may be fine, except the engineio server [only permits defined arguments](https://github.com/miguelgrinberg/python-engineio/blob/master/engineio/server.py#L54), so the initialization will fail.  For example:

   ```socketio.run(app, port=80, log_format="%(client_ip)s %(status_code)s")```

  * Suggested fix:  Add `**kwargs` to the [`engineio` constructor](https://github.com/miguelgrinberg/python-engineio/blob/master/engineio/server.py#L54), to promote better composability when it's bound to other objects. If that's not possible, then [filter `server_options`](https://github.com/miguelgrinberg/Flask-SocketIO/blob/v1.0/flask_socketio/__init__.py#L301) so that only valid parameters are passed into `socketio.Server(...)`.

2. Specifically, if `log_output='...'` is specified as an argument to `run(...)`, then there will be collision because it is [explicitly passed into `eventlet.wsgi.server(..., log_output=log_output, **kwargs)`](https://github.com/miguelgrinberg/Flask-SocketIO/blob/v1.0/flask_socketio/__init__.py#L330) alongside `kwargs`.  But `kwargs` also contains `log_output`!  So there is a collision.
   * Suggested fix: add `log_output` as a named argument in the `run(..., log_output=debug)` method.  This avoids the need to pass it into the eventlet server explicitly.

**Comment by diresi** [comment]
I don't want to hijack this issue, but also related to run() arguments:

If neiter `app` nor `port` is specified, `run()` trips over line 282 where `app` is accessed before `self.app` is assigned to it.

**Comment by miguelgrinberg** [comment]
The argument problems are now fixed:

1. I added `kwargs` to python-engineio's `Server` constructor, as suggested by @ktoh.
2. I removed any potentially conflicting arguments from `kwargs` before combining it with `self.server_options`.
3. Due to a previous fix, `app` is a required argument of `run()`, so this problem does not apply anymore.
