### ISSUE TITLE
How to send a Blob to a socket handler?

### ISSUE THREAD

**Issue by lnogueir** [miguelgrinberg/Flask-SocketIO#1450]
I am trying to generate subtitles in real-time for a conference room application. 
So on the client-side, I use the [start](https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder/start) method from a [MediaRecorder](https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder) with a timeslice to stream chunks of audio to the flask-socket.io backend to then use google streaming recognition API.

So the start method mentioned above gives me a Blob of type audio/ogg; codecs=opus for every timeslice milliseconds elapsed. Currently, on the client-side, I emit these Blobs as they become available. The problem is on the server-side, when I am receiving the data, socketio internally is not decoding it correctly.

Below is an image with the error logs:

![image](https://user-images.githubusercontent.com/48890798/103505548-7f84cc80-4e28-11eb-80dd-7009e1708848.png)

Here we see that it's calling this decode function inside packet.py and it's trying to figure out the packet type looking at the first character of the packet. But since I'm sending an audio/ogg, the packets starts like this:

![image](https://user-images.githubusercontent.com/48890798/103505868-531d8000-4e29-11eb-8807-8aa30e109bc9.png)

Since it starts with 'Ogg', on image 1 we can see why it is complaining about ValueError: invalid literal for int() with base 10: b'O'.

I've tried to modify this packet.py to try to handle this ValueError, but then I get other errors.

Can anyone help me get rid of this issue? I think I am not supposed to emit the Blob directly, but what should I do instead?

For reference:
 - Windows Pro
 - Python 3.9.1
 - python-socketio==5.0.4
 - Flask==1.1.2
 - Flask-SocketIO==5.0.1

Thanks

**Comment by miguelgrinberg** [comment]
Can I see your client-side emit code?

**Comment by lnogueir** [comment]
Definitely!

![image](https://user-images.githubusercontent.com/48890798/103559399-116df300-4e84-11eb-9c20-5f94f6ccffd2.png)

It's a simple prototype. On the HTML page, there's just a button tag to start and stop sending chunks.
Line 31 is the event listener for the available chunks and e.data is the blob.

Thank you

**Comment by miguelgrinberg** [comment]
What Socket.IO client version are you using?

**Comment by lnogueir** [comment]
> 
> 
> What Socket.IO client version are you using?

Here's the CDN: https://cdnjs.cloudflare.com/ajax/libs/socket.io/3.0.4/socket.io.min.js

**Comment by miguelgrinberg** [comment]
The versions are correct, so it's not that. It appears that somehow the packets get mixed up, but I'm not sure if it happens in the client or the server. Do you get the failure in every binary blog that you sent, or only on some?

**Comment by lnogueir** [comment]
> 
> 
> The versions are correct, so it's not that. It appears that somehow the packets get mixed up, but I'm not sure if it happens in the client or the server. Do you get the failure in every binary blob that you sent, or only on some?

From my testing, it appears to happen only on some.

**Comment by miguelgrinberg** [comment]
Okay, I'll see if I can write a simple test to reproduce this. How big are your audio payloads, do you know?

**Comment by lnogueir** [comment]
> 
> 
> Okay, I'll see if I can write a simple test to reproduce this. How big are your audio payloads, do you know?

According to my testing, a single chunk may vary in size, but so far they've ranged from 0 to 5kb.

But in terms of the entire audio payload, the goal is to allow one to speak continually for up to 5 minutes, as that's the google API limit. My idea is to not send any microphone data to the backend if I see that the audio amplitude from this user is below some constant threshold.

**Comment by lnogueir** [comment]
I've noticed that when I increase my timeslice a little bit, in order words, I send chunks less frequently, this problem does not occur ever.
Bumping from 100ms to 250ms I already stop getting these errors.

**Comment by miguelgrinberg** [comment]
Okay, this is interesting. I assume you are using either eventlet or gevent in your server, or in other words, that all this traffic goes through WebSocket and not HTTP?

It would be useful if you can take a look at the WebSocket traffic in the Chrome dev tools to see if the packets are sent in order. I believe in your case there should be a Socket.IO packet, followed by a binary packet with data, and then this should repeat every time the client emits.

**Comment by lnogueir** [comment]
> 
> 
> Okay, this is interesting. I assume you are using either eventlet or gevent in your server, or in other words, that all this traffic goes through WebSocket and not HTTP?
> 
> It would be useful if you can take a look at the WebSocket traffic in the Chrome dev tools to see if the packets are sent in order. I believe in your case there should be a Socket.IO packet, followed by a binary packet with data, and then this should repeat every time the client emits.

Yes, I am using gevent.

I think the packets were just getting messed up in the frontend due to the speed with which I was requesting chunks. I had no more problems with that once I bumped the timeslice a little bit.

But I actually found out another way to do what I was trying to do using the [Web Speech API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API). Although it is not supported by all browsers right now, it serves my purpose really well.

Feel free to close this issue and thanks for the support 👍

**Comment by bluthen** [comment]
I've had to do similar also using gevent, after resampling. I converted to base64 before send to flask, and didn't have an issue. It is always hard for me to trust javascript to correctly send binary data. We used bigger buffers than what you would get with 100ms also though.
