### ISSUE TITLE
SocketIO Chat Web app showing wierd errors

### ISSUE THREAD

**Issue by AayushDhande** [miguelgrinberg/Flask-SocketIO#1451]
Hi All,

I Am Getting some wierd error when i am running a flask-socketio chat web app on a development server. Refer Below.

`127.0.0.1 - - [04/Jan/2021 19:23:18] code 400, message Bad request version ('úú\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x01\x93\x8a\x8a\x00\x00\x00\x17\x00\x00ÿ\x01\x00\x01\x00\x00')
C;D0Ñ^☻Vcdè^ñÛèmÀçI)­WQÄ☺é¶7 vYÇq¦¯OÅn↓Õæ?§yßAnr×Ó¡åx? úú‼☺‼☻‼♥À+À/À,À0Ì©Ì¨À‼À¶↨ÿ☺☺" 400 -
127.0.0.1 - - [04/Jan/2021 19:23:18] code 400, message Bad request version ('B\x94\x91ú¨\x19\x11Yè\x06\x11\x05ÛRÉ\x97\x15\x7fÜ\x00"ZZ\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x00')
127.0.0.1 - - [04/Jan/2021 19:23:18] "▬♥☺☻☺☺ü♥♥i¾9→PÀÕÿ@@^,∟Q*♣ö]àÖÒ
                                                                    e::0Fï#z©?↑¸°²¡                                                 B
ú¨↓◄Yè♠◄♣ÛRÉ§⌂Ü"ZZ‼☺‼☻‼♥À+À/À,À0Ì©Ì¨À‼À¶
                                        9NË↔PÌÌ¿À1"jj‼☺‼☻‼♥À+À/À,À0Ì©Ì¨À‼À¶¡2_à♣¨7²Îþ♂ÆûfØ+ËXÁ_u0G¤¤u ×·y¥ç1âw¥♣/9[►ÙÌ►
127.0.0.1 - - [04/Jan/2021 19:23:30] code 400, message Bad request version ('ªª\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x01\x93\x9a\x9a\x00\x00\x00\x17\x00\x00ÿ\x01\x00\x01\x00\x00')
127.0.0.1 - - [04/Jan/2021 19:23:30] "▬♥☺☻☺☺ü♥♥LÐñ$ØÃ~eeÓ↓ÄÔA<û»↓Àxdü¾¹ÿa(Ì#3c=u=§@1> ªª‼☺‼☻‼♥À+À/À,À0Ì©Ì¨À‼À¶
↨ÿ☺☺" 400 -
127.0.0.1 - - [04/Jan/2021 19:23:30] code 400, message Bad request version ('·wu+\x9a2íâ\x00"ÊÊ\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x00')
K©ÿ¿Ä'ã ëÅ¿!C¬5yn/20 ·wu+2íâ"ÊÊ‼☺‼☻‼♥À+À/À,À0Ì©Ì¨À‼À¶
                                                     ↓¶fµÂëoì!*Ôfz| ªª‼☺‼☻‼♥À+À/À,À0Ì©Ì¨À‼À¶zz↨ÿ☺☺" 400 -0-mb¡0¥ºä◄¶E¯TZ HÒD?Å`\A
127.0.0.1 - - [04/Jan/2021 19:23:36] code 400, message Bad request version ('@À*9âG\x00\x00"ªª\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x00')
127.0.0.1 - - [04/Jan/2021 19:23:36] "▬♥☺☻☺☺ü♥♥Þ4;yçb↑,ÈÓ%u$?ßÏËW$♦-  U¶FãyÒ
vxù↕Q¥8F♣*                                        &
=U ∟@À*9âG"ªª‼☺‼☻‼♥À+À/À,À0Ì©Ì¨À‼À¶`

Any Ideas Why?

**Comment by miguelgrinberg** [comment]
The most likely reason is that your client is sending garbage, or at least something that is not Socket.IO packets.

**Comment by AayushDhande** [comment]
But When I look all of the dependacies and all things are working properly.

**Comment by miguelgrinberg** [comment]
There is nothing more than I can tell you with the little information you provided, sorry.

**Comment by robb17** [comment]
Recently triggered a similar error because I was routing to a page using https instead of http.
Hope this helps.
