### ISSUE TITLE
Connecting a python-socketio client to a flask-socketio server

### ISSUE THREAD

**Issue by LCD12345** [miguelgrinberg/Flask-SocketIO#1453]
I am trying to learn how to use Flask-socketio with Python-socketio as a client but I am struggling. I would like to write a basic application where a client sends JSON to a server and maintains a constant connection, where the server sends continuous messages back to the client.

The documentation was helpful, and I managed to get a basic prototype running but I would like to improve on it. Here is my code, which runs when I open 2 command lines with `python server.py` in one and `python client.py` in the other.

Server:

    from flask import Flask
    from flask_socketio import SocketIO, send
    import time
    
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'secret'
    app.config['DEBUG'] = True
    socketio = SocketIO(app)
    
    @socketio.on('connect')
    def on_connect():
        print('Server received connection')
    
    @socketio.on('message')
    def on_message(msg):
        print(msg)
        endtime = time.time() + 5 # loop for 5 secs
        while time.time() < endtime:
            socketio.emit("custom event", f"The time is: {time.strftime('%H:%M:%S')}")
            socketio.sleep(1)
    
    if __name__=="__main__":
        socketio.run(app)

Client:

    import socketio
    
    sio = socketio.Client()
    
    @sio.on('connect')
    def on_connect():
        sio.send(f"\nClient {sio.sid} connected...\n")
    
    @sio.on('custom event')
    def receive_custom(msg):
        print(msg)
    
    sio.connect('http://localhost:5000')
    # sio.wait() # cannot keyboard interrupt this
    sio.sleep(10)
    sio.disconnect()

Ideally, I’d like to be able to connect to the server with authentication and then manually send a message, and then receive continuous responses, so I think I might need to use an asynchronous client but I haven’t been able to make this work.

Most of the examples I have seen use JavaScript SocketIO clients. Are there any resources or tutorials where I can see an example of how to properly design this? I did recently see that you uploaded some youtube tutorials demonstrating what I might do, but this was using purely Python-socketio without flask-socketio, and I was unable to follow along as one of the requirements is not supported on Windows. After watching, I am unclear whether to use Flask-socketio or Python-socketio for the server side, or what the benefits would be of using one over the other. 

I would appreciate some assistance, feedback, or pointers on where to look for example implementations.

**Comment by miguelgrinberg** [comment]
Have you seen the few client examples in the python-socketio repo?

**Comment by LCD12345** [comment]
Thank you! I hadn't seen this.
