### ISSUE TITLE
Emitting from background task exhibits odd behavior and disconnections

### ISSUE THREAD

**Issue by aptsurfer** [miguelgrinberg/Flask-SocketIO#1456]
**Describe the bug**
When emitting from a background task with apscheduler.schedulers.background.BackgroundScheduler (using flask_socketio.emit, which should work [according to the docs](https://flask-socketio.readthedocs.io/en/latest/#flask_socketio.SocketIO.emit)), clients do not seem to be receiving responses and generally exhibit erratic behaviour, including disconnections.

**To Reproduce**
1. Save the [public gist I made](https://gist.github.com/aptsurfer/7aaa0680155ad777650f4eecb3a93677) that reproduces the issue.
2. Run as `./flask_socketio_bkg_threads.py`. Open several browsers to `localhost:5000` and observe the program behaviour. Try refreshing the page; see that other clients are updated immediately. Everything works.
3. Run as `./flask_socketio_bkg_threads.py --bgtask`. This will start a background task that emits every 10 seconds. Open several browsers to `localhost:5000`. Try refreshing the page. You will notice erratic behaviour and disconnections.

**Expected behavior**
Clients should see the message being broadcasted every 10 seconds and not be disconnected when the script is run with `--bgtask`.

**Logs**

Note: These logs were created by the following:
* Opening one tab to `localhost:5000`
* Opening two more tabs to the page
* Closing the two extra tabs so that there is only 1 left
* Opening another tab (so there are 2 now)
* Refreshing the second tab
* Closing the second tab (only the original one left)
* Closing the server.

Client logs and output come from the original tab, which stays open the whole time.

Without `--bgtask` (works):
* Program output (displayed on page): [log_output.txt](https://github.com/miguelgrinberg/Flask-SocketIO/files/5791709/log_output.txt)
* JS client socket.io output: [log_jsclient.txt](https://github.com/miguelgrinberg/Flask-SocketIO/files/5791710/log_jsclient.txt)
* Server output: [log_server.txt](https://github.com/miguelgrinberg/Flask-SocketIO/files/5791711/log_server.txt)

With the background task using `--bgtask` (does not work):
* Program output (displayed on page): [bkg_output.txt](https://github.com/miguelgrinberg/Flask-SocketIO/files/5791715/bkg_output.txt)
* JS client socket.io logs: [bkg_log_jsclient.txt](https://github.com/miguelgrinberg/Flask-SocketIO/files/5791719/bkg_log_jsclient.txt)
* Server output: [bkg_log_server.txt](https://github.com/miguelgrinberg/Flask-SocketIO/files/5791720/bkg_log_server.txt)

**Comment by miguelgrinberg** [comment]
You are using eventlet which is incompatible with threads in combination with APScheduler's threaded background task. That is not going to work.

I'm not sure if the eventlet monkey patching will help in this case as I'm not familiar with how APScheduler implements its background worker, but that helps sometimes.

**Comment by aptsurfer** [comment]
Thank you. After uninstalling eventlet, gevent seems to work well with APScheduler's threaded background task.

**Comment by miguelgrinberg** [comment]
> gevent seems to work well with APScheduler

Only if you use the monkey patching option. Eventlet and gevent are very much alike.

**Comment by aptsurfer** [comment]
Ah, is this due to concurrency issues?

**Comment by miguelgrinberg** [comment]
Sort of. Event and gevent implement concurrency through greenlets. Thread concurrency under these frameworks is blocking, so it prevents greenlet concurrency to happen. When you use these frameworks you want to move all your tasks to greenlets. The monkey patching option that the frameworks provide is an easy way to make the `threading` module from Python to use greenlets instead of threads.
