### ISSUE TITLE
copying flask session to socketio session

### ISSUE THREAD

**Issue by hem4nt** [miguelgrinberg/Flask-SocketIO#1458]
Hi Miguel, Thank you so much for the libraries and tutorials,

I can't figure out how flask session variables are being copied to socketio session on my 
1) https://doman.com >> nginx with ssl>> gunicorn >> flask + flask_socketio
but not on 
2) http://localhost:3000 >> guinicorn >> flask  + flask_socketio

Can you please help?

## config for 1) is:
```
from flask_session import Session

from flask_cors import CORS
from .functions import hash_password
from datetime import datetime, timedelta
import os
from flask_socketio import SocketIO
from flask import Flask
app = Flask(__name__, static_folder='../../front_end/build',
            static_url_path='/')
socketio = SocketIO(cors_allowed_origins=[],
                    manage_sessions=False,
                    logger=False,
                    engineio_logger=False,
                    allow_upgrades=True,
                    )
app.config['PERMANENT_SESSION_LIFETIME'] = timedelta(days=30)
app.config['SESSION_TYPE'] = 'filesystem'
app.config['SECRET_KEY'] = hash_password(os.urandom(500), 'secret')
app.config['DEBUG'] = True
app.config['SESSION_COOKIE_SECURE'] = True
app.config['REMEMBER_COOKIE_SECURE'] = True
app.session_cookie_name = 'api_session'
CORS(app, supports_credentials=True, resources={
    r'*': {'origins': []}})
Session(app)
socketio.init_app(app)
```
## config for 2) is :
```
from flask_session import Session
from flask_cors import CORS
from .functions import hash_password
from datetime import datetime, timedelta
import os
from flask_socketio import SocketIO
from flask import Flask
app = Flask(__name__, static_folder='../../front_end/build',
            static_url_path='/')

socketio = SocketIO(cors_allowed_origins=[
    'http://localhost:3000',
    'https://localhost:3000',
    'http://192.168.2.100:3000'
    'https://192.168.2.100:3000'

],
    manage_sessions=False,
    logger=True,
    engineio_logger=True,
    allow_upgrades=True,
)
app.config['PERMANENT_SESSION_LIFETIME'] = timedelta(days=30)
app.config['SESSION_TYPE'] = 'filesystem'
app.config['SECRET_KEY'] = hash_password(os.urandom(500), 'secret')
app.config['DEBUG'] = True
app.config['SESSION_COOKIE_SECURE'] = False
app.config['REMEMBER_COOKIE_SECURE'] = False
app.session_cookie_name = 'api_session'
CORS(app, supports_credentials=True, resources={
    r'*': {'origins': [
        'http://localhost:3000',
        'https://localhost:3000',
        'http://192.168.2.100:3000'
        'https://192.168.2.100:3000'
 ]}})
Session(app)
socketio.init_app(app)

```
## I see nothing strange in log for 2) 

Server initialized for eventlet.
Server initialized for eventlet.
rROWrXEonFyNlb2UAAAA: Sending packet OPEN data {'sid': 'rROWrXEonFyNlb2UAAAA', 'upgrades': ['websocket'], 'pingTimeout': 5000, 'pingInterval': 25000}
rROWrXEonFyNlb2UAAAA: Received packet MESSAGE data 0
emitting event "hmessage" to hBafVXABboStgcDNAAAB [/]
rROWrXEonFyNlb2UAAAA: Sending packet MESSAGE data 2["hmessage","Server says connected!"]
rROWrXEonFyNlb2UAAAA: Sending packet MESSAGE data 0{"sid":"hBafVXABboStgcDNAAAB"}
rROWrXEonFyNlb2UAAAA: Received request to upgrade to websocket
rROWrXEonFyNlb2UAAAA: Upgrade to websocket successful
rROWrXEonFyNlb2UAAAA: Sending packet PING data None
rROWrXEonFyNlb2UAAAA: Received packet PONG data

**Comment by miguelgrinberg** [comment]
You forgot to indicate what's not working. Please describe the problem clearly.

**Comment by hem4nt** [comment]
I created a website using flask backend and reactjs front end and hosted on my pc with the configurations **1)** production-like,  and **2)** for development as described above. 
Now the website hosted using configurations **1)** is working fine and as expected, `flask` session is getting **forked** into `flask_socketio` session. 
However in the development set-up with configurations **2)**, `flask_socketio` session always has only this value:`{'_permanent': True}` and **nothing is getting forked** from flask http session.
Some additional info: 
I'm using the following command to start the server.
`export FLASK_ENV=development && gunicorn --bind 127.0.0.1:3001 run:app_dev -k eventlet --workers 1`
front-end is being served on 127.0.0.1:3000 using `npm start` command

**Comment by miguelgrinberg** [comment]
With your 2) configuration there is no need to fork anything, the session is stored in the server and can be accessed as modified any time. For that set up you have to pass `manage_session=False`. For your 1) set up you have to pass `manage_session=True` because in that configuration the session is not easily accessible in the server so it needs to be copied during the Socket.IO connection.

You are using a `manage_sessions` argument. Note that you have a typo there, the name is `manage_session`. Documentation: https://flask-socketio.readthedocs.io/en/latest/#module-flask_socketio.

**Comment by hem4nt** [comment]
Hi Miguel,
Thank you and I found a solution. The issue was on the client side. I had to add  `{ withCredentials: true, }` on the client side explicitly may be because that would be a CORS request on setup 2) unlike setup 1).
`socket = io.connect(WS_BASE, { withCredentials: true, }) 
`
