### ISSUE TITLE
Cannot associate a SocketIO instance with more than one application

### ISSUE THREAD

**Issue by ericremoreynolds** [miguelgrinberg/Flask-SocketIO#146]
Hi Miguel,

While you work on the other issue I posted here is another question for you.

Are you planning on keeping this limitation or will v1 support multiple apps in future?

In our case this is creating a problem because our tests are failing since each one instantiates a new app.

Kind regards,

Eric

**Comment by miguelgrinberg** [comment]
Hmm. Let me think about this, it's tricky. Normally, extensions get the app from the app context, but with sockets there is no HTTP request, so no context either. Storing the app is a simple (and lazy, why not admit it) solution that works well, but creates this limitation.

**Comment by ericremoreynolds** [comment]
Sure I imagine it's not straightforward.

But it's hard to work around because the SocketIO instance serves two purposes - (a) to provide the declarative syntax to define handlers (common to all app instances) and (b) to actually do the work (specific to a single app instance).

I am obviously not super-acquainted with your code but I guess the two things could be somehow separated, e.g. the SocketIO instance takes care of (a) then init_app creates some internal object to do  (b) behind the scenes.

**Comment by miguelgrinberg** [comment]
@ericremoreynolds could you please try release 1.0b2? I think you will be able to work with multiple app instances with this version. Thanks!

**Comment by ericremoreynolds** [comment]
Looks good! Works with our code. Thanks.
