### ISSUE TITLE
Handler as a method

### ISSUE THREAD

**Issue by vladpaul10** [miguelgrinberg/Flask-SocketIO#1460]
**Your question**
Hello! I want to know if it's possible to add a custom variable to event handler call like this:

```
Sio.on('customEvent', customhandler(data, customVar))
```

Because I don't want to use global variables inside handler, I want my handlers to be present on another script dedicated for event handlers...

**Comment by miguelgrinberg** [comment]
I don't understand what you are trying to do. There is no problem with putting event handlers in a separate file. What are `data` and `customVar` in your example? Where do they come from?

**Comment by vladpaul10** [comment]
The data is the object emmited, by the client, to the server and on the server event method I want to pass an extra local variable to the call, if is possible...

**Comment by miguelgrinberg** [comment]
Where does `customVar` come from? You say it is a local variable, but local in which context? The handler is not called by you, it is called as a result of an action taken by the client, so how is that connected with some local context in your server application?

**Comment by vladpaul10** [comment]
I wanted to do something like this
sio.on('event', handler, extra_args)

And extra_args can be global variables( a logger or something else) which belong to the main file of the server. 

It would be easier for me to pass a variable as an argument and not to import all variables to event handler file.

But I think I can't do this...

**Comment by miguelgrinberg** [comment]
You can use the `partial()` function from the `functools` package to add your own arguments to your function.

**Comment by vladpaul10** [comment]
I will try with partial()

Thank you! 😃
