### ISSUE TITLE
404 Errors During Websocket Handshake 

### ISSUE THREAD

**Issue by robb17** [miguelgrinberg/Flask-SocketIO#1461]
I've been experiencing issues when trying to initialize SocketIO in the supported way, and I was hoping you might be able to help me pinpoint where the issue is. I've created a minimal example [here](https://github.com/robb17/socketio-do-nothing), which also includes the NGINX configuration.

Of interest is the startup_production script, which spawns multiple gunicorn processes. The only ones that matter for the present example, though, are those listening on ports 5008/5009 (depending on your IP) and 5000. You can see a live version of the toy app [here](example.donkhouse.com). When accessing the index, the process to which you've been IP-hashed should forward websocket requests to the process listening on 5000. Unfortunately, however, these requests are 404ed.

The log file for the process listening on port 5000 consists of many entries of the following:

```
[2021-01-13 22:20:30 +0000] [16466] [DEBUG] GET /socket.io//
[2021-01-13 22:20:30 +0000] [16466] [DEBUG] Closing connection.
[2021-01-13 22:20:38 +0000] [16466] [DEBUG] GET /socket.io//
[2021-01-13 22:20:38 +0000] [16466] [DEBUG] Closing connection.
[2021-01-13 22:20:46 +0000] [16466] [DEBUG] GET /socket.io//
[2021-01-13 22:20:46 +0000] [16466] [DEBUG] Closing connection.
[2021-01-13 22:20:54 +0000] [16466] [DEBUG] GET /socket.io//
[2021-01-13 22:20:54 +0000] [16466] [DEBUG] Closing connection.
```
Thanks, and let me know if I can provide any more information!

(Also, yes, init_socket.py and app/static/js/socketinit.js are EXTREMELY janky—do you have any recommendations on how I might better specify connection protocols dynamically?)

**Comment by miguelgrinberg** [comment]
Your nginx config is removing the `/p500x` prefix from the Socket.IO URL, so the Python processes should listen on `/socket.io`, not on `/p500x/socket.io`.

Also, you have an extra slash in the proxy_pass statement, so the redirection ends up going to `/socket.io//`.

Those are the two errors I could spot. Not sure if there are more, but in any case, this is fairly easy to debug when you see what URLs are getting to the Python process (shown in the log that you pasted above).

**Comment by robb17** [comment]
Beautiful! Thank you so much!
