### ISSUE TITLE
Bad namespace error with 5.0.1 upgrade

### ISSUE THREAD

**Issue by Nanda-Nandan** [miguelgrinberg/Flask-SocketIO#1462]
**Client.py**
```
sio = socketio.Client()
data = {"a":1,"b":2}
@sio.on('progressStatus', namespace='/reg')
def response_sock(data):
    #print(data)
    if data.get('stage_no'):
        print("response from stage "+str(data['stage_no'])+" stage progress "+str(data['message']))
    else:
        print(data)

sio.connect('http://0.0.0.0:8001',socketio_path='/progress', namespaces='/reg')
sio.emit('test', data, namespace='/reg')
```

**Server.py**
```
from flask import Flask, session, copy_current_request_context
from flask_socketio import SocketIO, emit, disconnect

app = Flask(__name__)
socket_ = SocketIO(app, path='/progress', async_mode="eventlet")


@socket_.on('connect',  namespace='/reg')
def test_connect():
    print("connected")
    emit('progressStatus', {'data': 'Connected'})



@socket_.on('test', namespace='/reg')
def register_skt(data):
    for x in range(7):
        data = "registration for user 1 stage "+str(x+1)+" completed"
        emit('progressStatus',data)
        socket_.sleep(5)


if __name__ == "__main__":
    socket_.run(app, host='0.0.0.0', port=8001, debug=False)
```

**Problem**
I was using same code for version 4.* but it is not working in 5.* version
The error is Badnamespaceerro: '/reg'  is not a connected namespace.

I have checked client.py file of flask-socketio package and i have observed self.namespaces = None and self.connectednamespaces = ['/reg'] and while emit event executes then it searches in self.namespaces instead of self.connectednamespaces

**emit event**
![image](https://user-images.githubusercontent.com/26704166/104638031-9ef2e380-56cb-11eb-9b2a-b6c77d3e8f4c.png)
**connect**
![image](https://user-images.githubusercontent.com/26704166/104638178-d792bd00-56cb-11eb-919c-97ce28c3992c.png)

**Comment by miguelgrinberg** [comment]
You are not waiting for the connect handler to be invoked to issue your emit. You get this error because the emit happens before the namespace connection is established. Move your emit to the connect handler and you will be fine.

**Comment by Nanda-Nandan** [comment]
I have added below lines in client.py
```
@sio.on('connect_custom', namespace='/reg')
def on_connect(data):
    print(data)
    sio.emit('registrationData', data, namespace='/reg')
sio.connect('http://0.0.0.0:7789', socketio_path='/progress', namespaces='/reg')
```
and in server.py
@socket_.on('connect',  namespace='/reg')
```
def test_connect():
    print("connected")
    emit('connect_custom', {'data': 'Connected'})
```

but this time i am getting connectionrefused error
![image](https://user-images.githubusercontent.com/26704166/104689309-4d2c7680-5728-11eb-9265-0868d884c82e.png)
howerver my ip,port,path and namespace everything same

Important note is the former code segments without changing inside connect event working for version 4.3.2

**Comment by miguelgrinberg** [comment]
@Nanda-Nandan versions 4 and 5 have breaking differences, the Socket.IO protocol changed in some significant ways. Code that worked in version 4 does not necessarily work with version 5, it may need to be adapted.

In this case your server appears to be rejecting the connection, so I would look at the server to see how the connection looks from that side.
