### ISSUE TITLE
Response not getting received when using gunicorn or uwsgi

### ISSUE THREAD

**Issue by Nanda-Nandan** [miguelgrinberg/Flask-SocketIO#1463]
**Describe the bug**
emit response is not getting received properly to client while using gunicorn

**Client1.py**

```
sio = socketio.Client()
data = {"something":"test1"}
@sio.on('test', namespace='/reg')
def response_sock(data):
    #print(data)
    if data.get('stage_no'):
        print("response from stage "+str(data['stage_no'])+" stage progress "+str(data['message']))
    else:
        print(data)

sio.connect('http://0.0.0.0:7789',socketio_path='/progress', namespaces='/reg')
sio.emit('proceed', data, namespace='/reg')
```
**client2.py**
```
sio = socketio.Client()
data = {"something":"test2"}
@sio.on('test', namespace='/reg')
def response_sock(data):
    #print(data)
    if data.get('stage_no'):
        print("response from stage "+str(data['stage_no'])+" stage progress "+str(data['message']))
    else:
        print(data)

sio.connect('http://0.0.0.0:7789',socketio_path='/progress', namespaces='/reg')  #1462   
#mentioned issue is not repro in this version of socketio
sio.emit('proceed', data, namespace='/reg')
```
**server.py**
```
import eventlet
eventlet.monkey_patch()
# from gevent import monkey
# monkey.patch_all()
from threading import Lock
from flask import Flask, session, copy_current_request_context
from flask_socketio import SocketIO, emit, disconnect
async_mode = None
app = Flask(__name__)
# app.config['SECRET_KEY'] = 'secret!'
socket_ = SocketIO(app, path='/progress') #have tried with explicitly mentioning async_mode = eventlet,gevent based on the #parameters passed from gunicorn or uwsgi command

interface_lock = Lock()
@socket_.on('connect',  namespace='/reg') 
def test_connect():
    print("connected")
    emit('test', {'data': 'Connected'})

@socket_.on('proceed', namespace='/reg')
def proceed_skt(data):
    global interface_lock
    a = A()
    a.some_method(data)
    # for x in range(7):
    #     data = "registration for user 1 stage "+str(x+1)+" completed"
    #     emit('test',data)
    #     socket_.sleep(5)
   )
```
**A.py**
```
def some_method(self, data):
     #45 second processing
      data = {"data":"dummy response"}
     emit('test',data)

```

- in server inside proceed_skt event it calls to another method from A.py file which does some processing for 45 sec and emits response.
- when i am setting async_mode="threading" its running properly and if i am sending request from client1.py i am getting response
- when iam setting asyncmode ="eventlet" or "gevent" and running it using gunicorn command gunicorn --worker-class eventlet 
       -w 1 wsgi:app --bind 0.0.0.0:7789 --timeout 1200 or gunicorn -k gevent -w 1 wsgi:app --bind 0.0.0.0:7789 -t 1200 where i have wsgi.py file and i have just imported callable app inside it i am not able to get response inside client1.py
- what is the reason behind it
- when i am hitting 2 requests at a time from client1 and client2 to gunicorn server 1 request is running and other is showing connection refused error,Have tried to inrease the worker but no effect,what is the issue?
- is it possible to get 2 requests running at same time using gunicorn on flask socket io?

**Comment by miguelgrinberg** [comment]
I'm sorry but I don't understand what you mean. When you say "I'm sending a request", where is that in the code? I see nothing that sends requests in this code. Maybe you should work on fixing #1462 first, then see if this is still a problem.
