### ISSUE TITLE
gunicorn eventlet flask-socketio  -w 10 or more?

### ISSUE THREAD

**Issue by dayhappy2012** [miguelgrinberg/Flask-SocketIO#1464]
I would like to use the Gunicorn Eventlet pattern -w 10, how to do this, or how to achieve the multi-process service

**Comment by dayhappy2012** [comment]
server 127.0.0.1:5000;
server 127.0.0.1:5001;
server 127.0.0.1:5002;

Is that right? How do I open multiple ports

**Comment by miguelgrinberg** [comment]
Did you try the documentation? https://flask-socketio.readthedocs.io/en/latest/#using-multiple-workers

**Comment by dayhappy2012** [comment]
Using Multiple Workers

1. Start multiple Socketio projects?

2. Gunicorn does not work as a web server?

**Comment by dayhappy2012** [comment]
One more question

Which versions of Docker Socketio supports

**Comment by miguelgrinberg** [comment]
@dayhappy2012 Please read the documentation to learn about multiple workers. The version of Docker is irrelevant, this project does not use Docker APIs at all.
