### ISSUE TITLE
Production Deployment Clarifications

### ISSUE THREAD

**Issue by jjedele** [miguelgrinberg/Flask-SocketIO#1466]
Hey,
this is kind of covered in the documentation already, but I want to clarify since I'm not 100% sure.

1. Do I understand correctly that `socketio.run(app, debug=False)` with eventlet/gevent installed is the suggested approach for production deployments, also for apps that are not only web socket servers but also have normal HTTP routes. No need to put gunicorn in front?
2. > eventlet is the best performant option, with support for long-polling and WebSocket transports.

Out of interest, where is this coming from? Can I find benchmarks anywhere?

Thx!

**Comment by miguelgrinberg** [comment]
1. There isn't a "suggested" approach, there are just a number of deployment options. The eventlet and gevent WSGI servers (which are used when you call `socketio.run()`) are both production quality. Gunicorn with the eventlet or gevent workers is also production quality. All these options work well.
2. There are no benchmarks, this is based on the fact that for a very long time gevent-websocket did not work under Python 3, so the only reliable option to get WebSocket was through eventlet. Without WebSocket you do not get good performance, so eventlet was the best choice. The gevent-websocket package has been ported to Py3 now, so maybe this statement is now outdated.

**Comment by jjedele** [comment]
@miguelgrinberg Thx for answer!
