### ISSUE TITLE
Optimal configuration for 10K+ concurrent websocket connections running on Heroku?

### ISSUE THREAD

**Issue by dternyak** [miguelgrinberg/Flask-SocketIO#1470]
**Your question**

Our application will maintain large numbers of concurrent socket connections with very low data transfer for each connection. We are starting off with a goal of supporting 10K concurrent connections, with a likelihood of growing to 1M or more over the next year. Each socket connection is basically transmitting no data however. 

Based on the conversation here https://github.com/miguelgrinberg/Flask-SocketIO/issues/859#issuecomment-449622654, it appears flask-socketio with an eventlet configuration supports 1024 simultaneous connections per server by default. Our socket connections are very light, and I believe that 1024 number is an arbitrary cap meant to provide a reasonable upper limit on hardware utilization, however I'm not sure what we could safely bump this up to given our case of very low transfer per socket.

Simply horizontally scaling to 10 dynos should enable us support 10k concurrent connections, however, I've realized that heroku may not "realize" that a particular dyno is saturated to whatever the max_size value is and intelligently direct new connections to other servers instances / scale up additional dynos. It might be smart enough to pick this up based on resource utilization though, which is somewhat of a proxy, but I'm not certain. Advice here would be appreciated. 

Another approach instead of scaling dynos is to purchase very beefy vertically scaled instances, and then increase that 1024 number to something much larger (maybe 10-50x?).  We could get away with running perhaps 1-2 of these to satisfy our initial scaling goals.

<img width="324" alt="Screen Shot 2021-01-22 at 1 51 46 PM" src="https://user-images.githubusercontent.com/7861465/105538479-0ce56f00-5cb9-11eb-9bfb-81b0f5af4081.png">

I'm a bit more bearish on this second scaling approach. It doesn't feel as robust.

My understanding is that we can only run 1 gunicorn worker on each server, so I don't believe we could eak out any performance there either.

`web: cd backend && gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 application.app:create_app\(\) -b 0.0.0.0:$PORT -w 1 --log-level=debug`

There may be something we could try related to ping intervals as well.

Finally, we've already setup flask-socketio to only allow websocket transport, which I believe is the most optimal/light transport, so I don't believe we can improve that further.

**Comment by miguelgrinberg** [comment]
I'm not really sure what is the question you expect me to answer, but I feel I need to correct you on the following statement.

> it appears flask-socketio with an eventlet configuration supports 1024 simultaneous connections per server by default

Flask-SocketIO does not have a limit on concurrent connections. Web servers usually put a cap on active connections, which is configurable. Eventlet's WSGI server has 1024 connections by default. Gunicorn's Eventlet web server starts with 1000 by default if I remember correctly. Both can be increased or decreased as needed.

The only way to find a good configuration is to test for it. Each application is different.

**Comment by dternyak** [comment]
Got it, thanks @miguelgrinberg.

To be very specific with the question, I was curious if you had any specific gotchas/advice on configuration that would provide the best approach given our needs.

It sounds like there wasn't anything off the top of your head, and it seems we just need to do some load testing.

**Comment by miguelgrinberg** [comment]
> For example, one that we figured out ourselves was enforcing only websocket transport.

Not sure why you concluded this. Clients will never choose to use long-polling if given the option to also use WebSocket, so there is really no point in "enforcing" WebSocket. In fact, WebSocket connections have limitations, such as not allowing custom headers, which complicate authentication. The default flow for a connection, where the client initiates the connection via HTTP long polling and then upgrades to WebSocket is there for a reason.

> My guess is that you've seen this question asked before, and might have a resource of some low hanging fruit where we could start.

Yeah, I don't really understand what you are after. There is nothing special about Socket.IO. Your application will be using the most resources, so you have to measure how many clients you can handle, and if that is not satisfactory then you have to optimize.

**Comment by dternyak** [comment]
> Not sure why you concluded this

To be more specific, we concluded that not supporting long-polling at all would be more performant than supporting it for the browsers that can't handle websockets. Good point r/e headers - I'll have to think about that more.

> Yeah, I don't really understand what you are after. There is nothing special about Socket.IO. Your application will be using the most resources, so you have to measure how many clients you can handle, and if that is not satisfactory then you have to optimize.

Ok thanks for confirming there's no obvious gotchas / tips.

**Comment by miguelgrinberg** [comment]
> than supporting it for the browsers that can't handle websockets

There are no current browser lacking support for WebSocket. All browsers desktop and mobile can do this.

**Comment by Mister-Gee** [comment]
@miguelgrinberg I have a flask socket-io app running on heroku and I'm trying to scale horizontally to 3 dynos but anytime I increase the dyno above 1, I get invalid session error. Pls help. Thanks
