### ISSUE TITLE
Clarification for nginx configuration to use multiple single-worker gunicorn processes

### ISSUE THREAD

**Issue by mgd722** [miguelgrinberg/Flask-SocketIO#1471]
I have read through many many of your comments on issues and the docs, but am still a little fuzzy on this. Much like some other tickets have said, my app is currently running using gunicorn with multiple workers. I am trying to replicate this as much as possible given that I need to now shift load-balancing to nginx.

In your [simplified config example in the docs](https://flask-socketio.readthedocs.io/en/latest/#using-nginx-as-a-websocket-reverse-proxy), you have the following:
```
location / {
    include proxy_params;
    proxy_pass http://127.0.0.1:5000;
}
```
Does this mean that the regular http part of the app is serviced by only one worker, while the websockets part gets serviced by three workers (as seen in the rest of the config)? I understand your example is not a complete production config, but I want to make sure I am interpreting things correctly.

In ticket #1035, you said:
>[If a client sends multiple requests at the same time under an ip_hash configuration, then all of those requests will run concurrently on the same worker. But nginx is pretty powerful, you can configure the socket.io endpoint under ip_hash, and any other endpoints with the normal routing. This is really up to you.](https://github.com/miguelgrinberg/Flask-SocketIO/issues/1035#issuecomment-522171964)

Does this mean I could configure nginx to serve regular http requests to my app using the same multi-worker gunicorn process I currently use, and route ONLY the socket.io traffic to be serviced by an arbitrary number of single-worker gunicorn eventlet servers?

In essence, here is an abbreviated version of my current config:
```
location / {
    # ...other config things

    # this points to a process that runs gunicorn with 3 different workers. NO eventlet. command:
    # gunicorn --workers 3 --bind unix:app.sock api.wsgi:app
    proxy_pass http://unix:/path/to/my/app.sock;
}
```
If I'm understanding what you said in #1035 correctly, I could continue to use my current configuration and just add the following to accomodate for sockets with multiple workers:
```
upstream socketio_nodes {
    ip_hash;

    # each of these is ran using gunicorn/eventlet and one worker like so (YES eventlet):
    # gunicorn --workers 1 --bind localhost:<port> --worker-class eventlet api.wsgi:app
    server 127.0.0.1:5000;
    server 127.0.0.1:5001;
    server 127.0.0.1:5002;
}

location /socket.io {
    include proxy_params;
    proxy_http_version 1.1;
    proxy_buffering off;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_pass http://socketio_nodes/socket.io;
}
```
Thus, all my regular http traffic can continue to be served by 3 gunicorn workers and my socket.io traffic can be served by 3 different workers. Therefore, if on pageload my app makes 6 requests to `/generic/app/endpoint` and 1 socket.io connection, the 6 requests would be distributed among the 3 non-eventlet gunicorn workers and the socket connection would be handled by 1 of the eventlet workers?

**Comment by miguelgrinberg** [comment]
Nginx allows you to build any sort of structure for your load balancing, so basically yes, you can build what you describe, where your HTTP traffic goes to a single multi-worker gunicorn, and your Socket.IO traffic goes to 3 single worker gunicorns with eventlet.

The thought that crosses my mind when you I see what you are trying to do is that given that you are going through so much effort to keep HTTP and Socket.IO traffic separate, if it wouldn't make more sense to build two separate applications. Because if I understand you correctly, you have a single app, right? So all the Socket.IO code is going to be loaded but inactive in your HTTP workers, and likewise your HTTP code is going to be loaded and inactive in your Socket.IO workers, which does not make a lot of sense to me.

**Comment by mgd722** [comment]
That is correct, I have a single app. I am trying to separate http traffic from socket.io traffic because I want the http traffic to be able to leverage as many available workers as possible while also servicing socket.io traffic with more than one worker. Perhaps there's a better way to do this than the config I included in my initial post?

Alternatives I've considered, assuming on pageload my app makes 6 http requests and 1 socket.io connection:

1. Your example config in the docs. Again understanding that this is a limited config, it seems like http requests get serviced by only one worker and socket.io gets spread among three workers. The 6 http requests would be handled concurrently by one worker (not ideal) and another worker would handle my socket.io connection (always the same worker based on my IP).
2. I send my http requests to the same upstream pool as websockets (seen in another dev's config from #1215):
```
upstream socketio_nodes {
    ip_hash;

    # each of these is ran using gunicorn/eventlet and one worker like so (YES eventlet):
    # gunicorn --workers 1 --bind localhost:<port> --worker-class eventlet api.wsgi:app
    server 127.0.0.1:5000;
    server 127.0.0.1:5001;
    server 127.0.0.1:5002;
}

location / {
    # this points to the same socketio workers
    proxy_pass http://socketio_nodes;
}

location /socket.io {
    # ... regular socket.io config
}
```
The downside here is that ALL my traffic would get handled concurrently by the same worker.

**Comment by mgd722** [comment]
This could be split into two apps, but both the http portion of my app and the socket.io portion share much of the same code (mostly models) and they're related enough that it doesn't make sense for me to split them up. Given what you've said:
> ...all the Socket.IO code is going to be loaded but inactive in your HTTP workers, and likewise your HTTP code is going to be loaded and inactive in your Socket.IO workers, which does not make a lot of sense to me.

perhaps it makes the most sense to use the same workers to service either http or socket.io traffic, but allow http traffic to be handled by multiple workers and socket.io traffic to always be handled by the same worker?
```
# this always services requests from the same IP by the same worker.
upstream socketio_nodes {
    ip_hash;

    # each of these is ran using gunicorn/eventlet and one worker like so (YES eventlet):
    # gunicorn --workers 1 --bind localhost:<port> --worker-class eventlet api.wsgi:app
    server 127.0.0.1:5000;
    server 127.0.0.1:5001;
    server 127.0.0.1:5002;
}

# send any socket.io request to always be serviced by the same process.
location /socket.io {
    include proxy_params;
    proxy_http_version 1.1;
    proxy_buffering off;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_pass http://socketio_nodes/socket.io;
}

# this services http requests using whatever processes are available.
upstream http_nodes {
    least_conn;  # a request is sent to the server with the least number of active connections

    # same workers from above, but serving http traffic too.
    server 127.0.0.1:5000;
    server 127.0.0.1:5001;
    server 127.0.0.1:5002;
}

location / {
    # this points to the same socketio workers, but can service many requests at once.
    proxy_pass http://http_nodes;
}
```
Under this configuration, the 6 http requests can be handled concurrently by all available workers and the one socket.io request will always be serviced by the same worker? If this makes sense, this would seem to be the closest socket.io-enabled analog to the multi-worker gunicorn deployment that many of us are coming from.

**Comment by miguelgrinberg** [comment]
@mgd722 You are giving the example in the docs too much weight. It is just an example. The fact that the nodes serving HTTP and Socket.IO are different was not done on purpose, and it would be unlikely that I would ever configure a project with mismatched workers for HTTP and Socket.IO. So don't assume that the example has some secret benefit in that mismatched configuration.

I'm going to mention something that you probably know, but that maybe you are not considering:

- An eventlet Gunicorn worker can handle thousands of concurrent client connections, which can be HTTP, WebSocket or a combination of both.
- A standard Gunicorn worker can handle no more than 1 concurrent connection.

Keeping this in mind, why do you want to have HTTP on standard Gunicorn workers?

**Comment by mgd722** [comment]
I was too hung up on separating them, and you're right-- especially in hindsight it seems useless. I did some testing this week and using the same upstream for everything makes the most sense. Thank you for your insight and direction!
