### ISSUE TITLE
vue-socketio request error 500，The flask-socketio server error message is as follows:

### ISSUE THREAD

**Issue by rsqai** [miguelgrinberg/Flask-SocketIO#1472]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gevent/pywsgi.py", line 970, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python3.6/site-packages/geventwebsocket/handler.py", line 87, in run_application
    return super(WebSocketHandler, self).run_application()
  File "/usr/local/lib/python3.6/site-packages/gevent/pywsgi.py", line 917, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/flask_socketio/__init__.py", line 46, in __call__
    start_response)
  File "/usr/local/lib/python3.6/site-packages/engineio/middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/socketio/server.py", line 563, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/engineio/server.py", line 413, in handle_request
    self._log_error_once('Invalid session ' + sid, 'bad-sid')
TypeError: must be str, not NoneType
2021-01-27T01:19:10Z {'REMOTE_ADDR': '172.16.194.0', 'REMOTE_PORT': '54416', 'HTTP_HOST': 'ws.jundax.com', (hidden keys: 37)} failed with TypeError

**Comment by miguelgrinberg** [comment]
Yeah, there is a problem in how I'm logging an error message for an unexpected condition.

The real problem, however, is that your client is sending a POST request without the Socket.IO session id, which is not valid according to the Socket.IO protocol.

I can fix the crash, but this isn't going to solve the problem, your connection will end as a result of this because your client does not appear to be compliant.

**Comment by rsqai** [comment]
Thanks so much for your response. It is strange that: the same vue-socketio client code works well locally(flask-socketio always working on the kubernetes cluster), as soon as vue-socketio client was deployed on the same kubernetes cluster, it went wrong the information I mentioned above.

**Comment by rsqai** [comment]
> Yeah, there is a problem in how I'm logging an error message for an unexpected condition.
> 
> The real problem, however, is that your client is sending a POST request without the Socket.IO session id, which is not valid according to the Socket.IO protocol.
> 
> I can fix the crash, but this isn't going to solve the problem, your connection will end as a result of this because your client does not appear to be compliant.

Thank you very much for your reply. It is strange that: the same vue-socketio works well locally(flask-socketio always working in a kubernetes cluster), above error occurs as soon as the vue-socketio client is deployed to the same kubernetes cluster.

**Comment by miguelgrinberg** [comment]
@rsqai Your Vue client runs in a web browser, correct? When you say that you deployed the vue client to your kubernetes cluster, do you mean the actual client with the browser and everything, or do you mean that you deployed the web server that serves the client-side files to the browser?

In any case, if you use the master branch of the python-engineio package the crash will not occur and instead your client is going to receive a 400 error. You can take a look at the request in your browser to debug this further. The request should have a `sid` argument in the query string of the URL. The error you are getting suggests that this argument is missing.

**Comment by rsqai** [comment]
I'm sorry I didn't make myself clear, When i say i deployed the vue client to my kubernetes cluster i mean that the web server serves the client-side files such as vue-socketio code 、css and html file to the browser. This appears to be a configuration issue of my vue-socketio server deployment. Now I want to fix flask-socketio 500 bugs, do I just need to reinstall Flask-SocketIO? Or i still need to reinstall the python-engineio? My flask-socketio version is 4.3.2. 

> @rsqai Your Vue client runs in a web browser, correct? When you say that you deployed the vue client to your kubernetes cluster, do you mean the actual client with the browser and everything, or do you mean that you deployed the web server that serves the client-side files to the browser?
> 
> In any case, if you use the master branch of the python-engineio package the crash will not occur and instead your client is going to receive a 400 error. You can take a look at the request in your browser to debug this further. The request should have a `sid` argument in the query string of the URL. The error you are getting suggests that this argument is missing.

I'm sorry I didn't make myself clear, When i say i deployed the vue client to my kubernetes cluster i mean that the web server serves the client-side files such as vue-socketio code 、css and html file to the browser. This appears to be a configuration issue of my vue-socketio server deployment. Now I want to fix flask-socketio 500 bugs, do I just need to reinstall Flask-SocketIO? Or i still need to reinstall the python-engineio? My flask-socketio version is 4.3.2.

**Comment by rsqai** [comment]
> @rsqai Your Vue client runs in a web browser, correct? When you say that you deployed the vue client to your kubernetes cluster, do you mean the actual client with the browser and everything, or do you mean that you deployed the web server that serves the client-side files to the browser?
> 
> In any case, if you use the master branch of the python-engineio package the crash will not occur and instead your client is going to receive a 400 error. You can take a look at the request in your browser to debug this further. The request should have a `sid` argument in the query string of the URL. The error you are getting suggests that this argument is missing.

I'm sorry I didn't make myself clear, My vue client runs in a web browser and when i say i deployed the vue client to my kubernetes cluster i mean that the web server serves the client-side files such as vue-socketio code 、css and html file to the browser. This appears to be a configuration issue of my vue-socketio server deployment. Now I want to fix flask-socketio 500 bugs, do I just need to reinstall Flask-SocketIO? Or i still need to reinstall the python-engineio? My flask-socketio version is 4.3.2.

**Comment by miguelgrinberg** [comment]
The fix for this 500 error is not in an official version yet. I mentioned this above, you have to install the python-engineio package from the master branch to get this fix.

**Comment by rsqai** [comment]
ok, thanks.
