### ISSUE TITLE
Streaming data processing error

### ISSUE THREAD

**Issue by henry8th** [miguelgrinberg/Flask-SocketIO#1473]
**Your question**
Hello,
First off thanks for the fantastic package.
I have an issue, perhaps you could provide some guidance.
My project streams audio saving every 5 seconds, each 5 second block the client sends a break signal causing the file to be closed and saved and a new file to be opened.

The First file is then sent to be processed as a future. However, multiple empty files audio  are being created. my thinking is perhaps this is due to client requests being handled asynchronously?
Do you have any idea as to what may be the problem and how to fix it?
Thank you

```python
@socketio.on('start-recording')
def start_recording(options):
    """Start recording audio from the client."""
    print("Recording started")
    session['active'] = False
    session['wavChannels'] = options.get('numChannels', 1)
    session['sampleWidth'] = options.get('bps', 16) // 8
    session['frameRate'] = options.get('fps', 22050)
    if session['active'] == False : create_wav()  # To prevent a wav being created if one is already open (not workink?)

def create_wav():
    session['active'] = True
    session['wavename'] = uuid.uuid4().hex + '.wav'
    wf = wave.open(session['wavename'], 'wb')
    wf.setnchannels(session['wavChannels'])
    wf.setsampwidth(session['sampleWidth'])
    wf.setframerate(session['frameRate'])
    session['wavefile'] = wf

@socketio.on('write-audio')
def write_audio(data):
    """Write a chunk of audio from the client."""
    session['wavefile'].writeframes(bytes(data))

@socketio.on('new-chunk')
def new_chunk():
    session['wavefile'].close()
    session['active'] = False
    session['wav_queue'].append(global_vars['wavename'])
    create_wav()
    if session['processor busy'] or (len(session['wav_queue']) < 1):
        pass
    else:
        session['model_busy'] = True
        future = pool.submit(wav_processing, session['wav_queue'])
        session['wav_queue'].clear()
```

**Comment by miguelgrinberg** [comment]
The issue template requested that you include logs with your questions, but you have ignored that request. Without logs it is difficult for me to answer.

**Comment by henry8th** [comment]
Thanks! I enabled logs and was able to debug the error myself.
One other question I had was if I have a cpu intensive task what is the best way to execute in the background, while continuing to receive client data.
Would you recommend the multiprocessing package?
Thank you

**Comment by miguelgrinberg** [comment]
CPU intensive work in an async web server is very tricky. Depending on which async framework you use (eventlet, gevent) and which version of it, and exactly how you do, working with the multiprocessing package may or may not work, so if I had to do this myself I would not use multiprocessing or any other method that relies on having child processes.

My choice would be to use a separate process to do the CPU intensive work. There are many ways for the server to send jobs to this other process. You can opt to use a queue solution such as Celery or RQ, or you can also define a simple HTTP server in this second process with Flask and then the main server can trigger jobs by sending HTTP requests.

**Comment by henry8th** [comment]
Awesome! Thanks for the suggestions they are very helpful.
Thanks again for the cool package.
