### ISSUE TITLE
Best practice for asynchrounous requests whilst data streaming

### ISSUE THREAD

**Issue by henry8th** [miguelgrinberg/Flask-SocketIO#1474]
Hi again,
I took your advice and went with a dual server setup, one to handle client requests and the second to perform processing.
As the title states, is there a best practice for performing code blocking functions with socketio. 
To elaborate, I initially tried making a post request with the data that needed processing to the rest api endpoint and then wait for a post request back from the server to finally send back to the client, this however caused the socket to stop streaming data.
Is threading or async calls in combination with get requests better?
Thank you

**Comment by miguelgrinberg** [comment]
I assume you are using eventlet or gevent in your Flask server? Did you monkey patch the standard library so that socket calls become non-blocking?

**Comment by henry8th** [comment]
Thanks! adding the monkey patch sorted the problem.
