### ISSUE TITLE
Using RQ not connecting

### ISSUE THREAD

**Issue by jmoheywood** [miguelgrinberg/Flask-SocketIO#1479]
Connection to the localhost redis server is working fine. Issue only when sending a function to the queue with:
```
q = Queue(connection=redis.from_url('redis://localhost:6379'))
item = q.enqueue(
                        my_func,
                        job_id=f"{random.getrandbits(128)}",
                        job_timeout=600,
                        result_ttl=1800,
                    )
```

 Currently using monkey_patch(). Any ideas please?

![image](https://user-images.githubusercontent.com/15943683/107711668-eb781180-6cbf-11eb-8454-9ac1183eccca.png)

**Comment by miguelgrinberg** [comment]
I do not know. This seems to be an issue with eventlet and not with this package, so I suggest you ask on that project or on StackOverflow.

**Comment by jmoheywood** [comment]
Yeah I think you're right. Seems very weird. Pushed to production (at a risk) - no problem there...
