### ISSUE TITLE
Emit doesn't work sometimes

### ISSUE THREAD

**Issue by blackfly19** [miguelgrinberg/Flask-SocketIO#1481]
**Your question**
I have written a backend for my react native app. I have used flask socketio,celery,redis and rabbitmq in it. It's deployed on heroku. The problem is whenever I restart the dynos the emit function is working normally. Everything is emitting. But if the server is idle for a few minutes and then we try to connect it doesn't emit. I have a hobby dyno so the server doesn't sleep.

**Logs**
These are the logs from engineio_logger. This is after restarting
![IMG_20210215_142201.jpg](https://user-images.githubusercontent.com/43345480/107937482-fc6ba000-6fa9-11eb-833b-90b8853756e7.jpg)

This is after a few minutes
![IMG_20210215_161509.jpg](https://user-images.githubusercontent.com/43345480/107937552-19a06e80-6faa-11eb-941b-2df479051dec.jpg)

**Comment by miguelgrinberg** [comment]
I don't see any errors in your log. Your client isn't emitting the same thing in these two cases though. In the first one, your client sent `authorize` to the server. It didn't send that in the second one. Why is that?

**Comment by blackfly19** [comment]
In the first case the server is emitting on the  ```authorize```  event.  The client sends  ```syncTime```  in both cases but in the second case the server isn't emitting back on  ```syncTime``` .

**Comment by miguelgrinberg** [comment]
Why isn't the client sending `authorize` in the second case?

**Comment by blackfly19** [comment]
I have added the emitting on ```authorize``` in the connect function. So whenever a connection is formed by the client to the server, the server emits on the ```authorize``` event.

**Comment by miguelgrinberg** [comment]
It seems you are looking at this from the server side. I'm asking about why your client behaves differently in these two cases.

The second log shows that the connection was just established, and the first event that the server received from this client was `syncTime`. Why is this client not authorizing first, like the one in the first log?

**Comment by blackfly19** [comment]
This is how it is working.
- First the client forms a connection with the server. When the connection is established, the server emits on the ```authentication``` event asking for user_id.
- The client then sends the user_id to the ```mapHashId``` event as visible in the first log.
- Simultaneously the client emits on ```syncTIme``` asking for current server time to synchronise timers across various devices.

The client is not responsible for authentication. It is the server.

The client sends the user_id only when the server emits on the ```authorize``` event. Since the emit is not working in the second case the server doesn't receive the user_id.
The client emits on ```syncTime``` in both the logs.

**Comment by miguelgrinberg** [comment]
Okay, I think I'm understand how this is supposed to work better. Let me ask my question one more time, hopefully with more accuracy now: Why did the server in the second case did not send `authorize` to the client as soon as it connected? What is different in that case?

**Comment by blackfly19** [comment]
That is exactly my question. The emit to ```authorize``` event in the second case is not working.

`@socketio.on('connect')
def connect():
    sid = request.sid
    print("Connected: ",sid)
    emit('authorize',1,room=sid)

@socketio.on('disconnect')
def disconnect():
    print("Disconnected: ",request.sid)
    if redis_client.exists(request.sid):
        user_hash = redis_client.get(request.sid)
        redis_client.delete(request.sid)
        redis_client.delete(user_hash)
`
This is a part of my code. There is no difference in code in both the cases. The second case occurs when the server is left idle for a few minutes.

**Comment by miguelgrinberg** [comment]
I can't answer a question that refers to code that I have not seen. I believe this is a bug in your application. If you were calling `emit()` then the log would show it. The logging occurs when the function is called, not when the event is delivered to the client. Since it is not in the log, my only explanation is that your application isn't calling emit(). If you are convinced this is a bug in this package, then please create a small example that reproduces the problem, because with the information that I have I cannot really find a problem.

Alternatively, you need to show me actual code, not a simplification of it.

**Comment by blackfly19** [comment]
I found the solution to my problem. The application was not emitting because of my redis hosting on azure vm. The connections become disconnected after the connection has been idle for 4 minutes.
So is there any way I can send keep alives for the message_queue connection to redis?

**Comment by miguelgrinberg** [comment]
@blackfly19 Are you using a more or less recent version of the python-socketio package? The redis connection is retried if it disconnects.

**Comment by blackfly19** [comment]
I am using the latest version of python-socketio. It doesn't reconnect to the redis-server. There is also no error on the logs when the message queue connection disconnects. So is there any way I can access the message queue connection?

**Comment by miguelgrinberg** [comment]
The work to reconnect redis was done three years ago. How is it possible that you don't see this? Here is the commit with the changes, you can see that there are log statements when the redis connection breaks. If you are doing things correctly you should see these messages in the log and the connection should be retried.

**Comment by blackfly19** [comment]
I realised the reconnection is working but due to silent disconnection by azure vm it was not triggering an error. But I solved it by setting the tcp-keepalive variable to less than 4 minutes which keeps the connection alive.
Thanks for you time and help!
