### ISSUE TITLE
Know a client's room

### ISSUE THREAD

**Issue by MathiasDrapier** [miguelgrinberg/Flask-SocketIO#1482]
Hello, 
When a client connects, I put it in a room according to a token that he provides as headers. That works well.
Then, I would like, when a client sends a message, that it is sent to all the other client of his room.

So I would like to know if there is a solution to know the part of a customer when he sends a message?

In the client's message there will just be data, he must not know in which room he is, it is only the server that must manage this.

Thank :)

**Comment by miguelgrinberg** [comment]
Have you seen the [rooms()](https://flask-socketio.readthedocs.io/en/latest/#flask_socketio.rooms) function?

**Comment by MathiasDrapier** [comment]
Thanks, that's exactly what I was looking for.
