### ISSUE TITLE
Emit message just after client log in

### ISSUE THREAD

**Issue by MathiasDrapier** [miguelgrinberg/Flask-SocketIO#1484]
Hello, 
I need to send some message just after a client is connected, so I implemented this in a handle_connect method attached to the @ socketio.on ("connect") event.
But the client receives the messages before the "connected" event.

My function on the server side:

`@socketio.on("connect")`
`def handle_connect():`
     `emit("foo")`
     `emit("bar")`

And my logs in client side : 

22.02.2021 12:43:43 `42["message","foo"]`
22.02.2021 12:43:44 `42["message","bar"]`
22.02.2021 12:43:46 `["connected"]`

I want receive foo, bar after connected event.

**Comment by miguelgrinberg** [comment]
@MathiasDrapier the connect event handler in the server is supposed to be used for authenticating the client, before the connection is accepted.

You can pass `always_connect=True` when you create the `SocketIO()` and then the connection will be automatically accepted before the connect handler is invoked. See https://flask-socketio.readthedocs.io/en/latest/#flask_socketio.SocketIO for additional details.

**Comment by MathiasDrapier** [comment]
I don't want the connection to be automatically accepted, in my handle_connect method I also have client verification logic. That I did not make public in my question.
So I want to: check my client. If he has permission he connects, then immediately I have to send messages to him and other client to notify of this connection.

**Comment by miguelgrinberg** [comment]
Did you read the documentation of the option I recommended? It might still work.

**Comment by MathiasDrapier** [comment]
I will watch, thank you very much
