### ISSUE TITLE
socketio.exceptions.BadNamespaceError: / is not a connected namespace.

### ISSUE THREAD

**Issue by mishkat-ucr** [miguelgrinberg/Flask-SocketIO#1485]
I am trying out one use case here, which is: send over some data in batches to the client. I will initiate an event from the client, in which server will respond with another event which will send the next batch. In a nutshell, I'm trying to achieve some sort of synchronicity in an asynchronous event based mechanism.

Here is the gist of my client code:
```
@socketio_client.on('continue train')
def continue_train():
        socketio_client.emit('train', 'hello world', callback=ack_train)


@socketio_client.on('continue test')
def continue_test():
        socketio_client.emit('test', 'hello world', callback=ack_test)

socketio_client.emit('train', 'hello world', callback=ack_train)

socketio_client.emit('train', 'hello world', callback=ack_train)
``` 

Here is the gist of my server code:
```
@socketio.on('train')
def handle_train(data):
    print(data)
    emit('continue train')


@socketio.on('test')
def handle_test(data):
    print(data)
    emit('continue test')
```

However, I am getting a `socketio.exceptions.BadNamespaceError: / is not a connected namespace.` error. Any idea why?

**Comment by miguelgrinberg** [comment]
Yes, this issue is known and is explained here: https://github.com/miguelgrinberg/python-socketio/issues/634.

The master branch of python-socketio has a fix, but it hasn't been released yet. Feel free to install from git if you want to try out the fix, or else you can also change your application as suggested in the issue linked.

**Comment by mishkat-ucr** [comment]
Great, @miguelgrinberg ! Thank you for the reply.

**Comment by mishkat-ucr** [comment]
Hi @miguelgrinberg , I am using the 5.0.2.dev0 version now. But, the problem still persists. I am using a sio.sleep(1) after the connect as well. Any insights after this?

**Comment by miguelgrinberg** [comment]
@mishkat-ucr the fix is not in this repo, it's in python-socketio. That's the one you need to install from git.
