### ISSUE TITLE
A question about async_mode and block

### ISSUE THREAD

**Issue by north-horse** [miguelgrinberg/Flask-SocketIO#1486]
I am trying to complete a python backend server so that it could send messages to the front webpage when I receive data from Kafka. I found that when I set the async_mode as 'eventlet',  the backend could not use socketio.emit to send the message to the front webpage. It looks like the communication is blocked. However, when I set the async_mode as ''threading" the program works fine. 
Here is how I set async_mode:
`socketio = SocketIO(app, async_mode='threading', cors_allowed_origins='*')`
Here is how I use socketio.emit:

```
consumer = KafkaConsumer("test", bootstrap_servers=["192.168.142.139:9092"])
def background_thread():
    count = 0
    global consumer
    for msg in consumer:
        count += 1
        socketio.sleep(0)
        data_json = msg.value.decode('utf8')
        socketio.emit('my_response', {'data': data_json, 'count': count})
```
Therefore, I want to ask why this happen? What is the difference between that two async_mode? Is the 'threading' async_mode would cause any problem If I want to deploy the server?

**Comment by miguelgrinberg** [comment]
Are you familiar with eventlet? My guess is that you haven't monkey patched the standard library.

**Comment by north-horse** [comment]
> Are you familiar with eventlet? My guess is that you haven't monkey patched the standard library.

Hi, It is true that I am not familiar with eventlet, after I use `eventlet.monkey_patch()`, I found that my problem is solved, thanks!
