### ISSUE TITLE
Just a WebSocket server?

### ISSUE THREAD

**Issue by ShubhamJain7** [miguelgrinberg/Flask-SocketIO#1488]
Is it possible to use this library to host a WebSocket server that can be accessed through a `ws://` or `wss://` URL?
I wish to serve only data/media, similar to a REST API, but using the WebSocket protocol instead of `HTTP` or `HTTPS`.

**Comment by miguelgrinberg** [comment]
No, this is Socket.IO, not WebSocket.

**Comment by ShubhamJain7** [comment]
Ah, my bad, I got confused between the two. Did a little more research and discovered I could use your `python-socketio` library to create a client that can communicate with a server created using this library, through a `HTTP` or `HTTPS` URL! Thanks!
