### ISSUE TITLE
Flask-SocketIO with APScheduler when using uWSGI problem

### ISSUE THREAD

**Issue by denisvitez** [miguelgrinberg/Flask-SocketIO#1489]
**Your question**
I have used `uWSGI` to host my Flask API which is using `Flask-SocketIO`. There were some problems on the way, but they were resolved:

- Monkey patch
- Using `processes = 1` otherwise strange things began to happen.

I am also using the `Flask-APScheduler` to run a recurring job, that sometimes also need to send Socket.IO messages. The setup is working without any problem when debugging, but it doesn't seem to work when hosting.

Is there anything else that I need to be careful of with this kind of setup so the messages will get sent from that Scheduler job.

**Comment by miguelgrinberg** [comment]
Can you define "it doesn't seem to work" in more precise terms?

**Comment by denisvitez** [comment]
Well the messages that would be sent from the APScheduler code, doesn't get to the clients. So my guess here is that they are not sent. The messages that are sent from normal API calls are received normally.

**Comment by miguelgrinberg** [comment]
Have you enabled logs for Socket.IO explicitly? The logs are not printed by default.

**Comment by denisvitez** [comment]
Yes, I enabled the `logger=True` and `engineio_logger=True`. I managed to solve it, the problem was actually with `APScheduler`. I was mistaken in thinking it was running, but it wasn't... It's working now :)
