### ISSUE TITLE
Is it possible to emit event from a custom flask command?

### ISSUE THREAD

**Issue by mikalatte** [miguelgrinberg/Flask-SocketIO#1490]
I am using flask_socketio with eventlet. I have a scheduled flask custom command where some data is updated and I need to send this data with socketio. When I set logger=True, I see that the event is emitted but it doesn't reach the client and there is no logs in engineio logs. I'm using eventlet.spawn to call the method where the event is emitted? Is there smth I'm doing wrong or I'm trying to perform some impossible action?

**Comment by miguelgrinberg** [comment]
Are you following the "Emitting from an external process" instructions from the documentation? The `flask` command is an external process, so you have to do the corresponding set up.

**Comment by mikalatte** [comment]
I tried to but I had this error: 

_File "/var/www/backend/venv/lib/python3.8/site-packages/flask_socketio/__init__.py", line 416, in emit
    self.server.emit(event, *args, namespace=namespace, room=room,
AttributeError: 'NoneType' object has no attribute 'emit'

Is it necessary to use a message queue to emit from an external process?

**Comment by miguelgrinberg** [comment]
> Is it necessary to use a message queue to emit from an external process?

Yes. That is exactly what I was asking if you configured.

**Comment by mikalatte** [comment]
I haven't, but will do now. Thank you for your help!
