### ISSUE TITLE
Different “sid” in the Flask application and in the client js

### ISSUE THREAD

**Issue by Yasha261998** [miguelgrinberg/Flask-SocketIO#1493]
**Your question**
I am writing a website for Flask, I use Socketio. I'm trying to send a private message to a specific user, but the room sid are different. 
When the client connects to the server, I write its sid to the database:
`@socketio.on('connect')
def _handle_on_connect(self):
    user = Users.query.get(current_user.get_id())
    user.sid = request.sid
    db.session.add(user)
    db.session.commit()`

Then I use to send with:
`socketio.emit('mqtt_message', data=dict_dev["dict_type_element"], room=self.user.sid)`

Socketio js client profile.js:
`var socket = io.connect('http://' + document.domain + ':' + location.port);`
`socket.on('mqtt_message', function(data){
   console.log(msg);
});`

What could be the problem?

**Logs**
 For example: sid in Flask app `d2ypkS66fvEvn7oQAAAH`, but on the js client side `doUhD3ovQq0SWN37AAAC`.

**Comment by miguelgrinberg** [comment]
Are you using a recent version of Flask-SocketIO?

**Comment by Yasha261998** [comment]
Yes, `5.0.1`

**Comment by miguelgrinberg** [comment]
I'm not sure what the problem can be then. Make sure your python-socketio and python-engineio are also the most recent. If that doesn't fix the problem, then can I ask you to create a small example that shows the problem?

**Comment by Yasha261998** [comment]
python-socketio and python-engineio are also the most recent

**Comment by Yasha261998** [comment]
app.py:

```
from flask_socketio import SocketIO
from flask_login import current_user

app = Flask(__name__)
app.config.from_object(ProductionConfig)
socketio = SocketIO(app, async_mode='gevent')

@app.route('/profile')
def index():
    return render_template('profile.html')

@socketio.on('connect') 
def _handle_on_connect(): 
        print(request.sid)
        socketio.emit('mqtt_message', data='data', room=request.sid)

if __name__ == '__main__':
        socketio.run(app, host='127.0.0.1', port=5000, use_reloader=False, debug=True, log_output=True)
```

profile.js:

```
$(document).ready(function() {
    var socket = io.connect('http://' + document.domain + ':' + location.port);

    socket.on('mqtt_message', function(data) {
         console.log(data);
    });
});
```

**Comment by Yasha261998** [comment]
?

**Comment by bluthen** [comment]
Your example wasn't that complete. I had to spend some time to get a working example, but it looks like it works for me. The client gets the event.

**Comment by Yasha261998** [comment]
Are the sid on the server and on the client the same?

**Comment by bluthen** [comment]
Yep Download attached zip:
```
unzip flask_socketio_issue_1493.zip
cd flask_socketio_issue_1493
pipenv --python `which python3`
pipenv sync
pipenv shll
python app.py
```
open-browser http://localhost:5000/profile
Open console -> reload page
Notice same sid is printed in js console as by app.py
[flask_socketio_issue_1493.zip](https://github.com/miguelgrinberg/Flask-SocketIO/files/6120137/flask_socketio_issue_1493.zip)
