### ISSUE TITLE
Docs state Werkzeug lacks WebSocket support

### ISSUE THREAD

**Issue by ysangkok** [miguelgrinberg/Flask-SocketIO#1498]
I noticed that docs/index.rst states that "the Flask-SocketIO server is not recommended due to lack of WebSocket support". This sentence was added [in Jan 2019](https://github.com/miguelgrinberg/Flask-SocketIO/commit/9bde4beda523d539e2113151e8c4d3f88765a5ea). But is this still true after [PR #1709](https://github.com/pallets/werkzeug/pull/1709) was added to Werkzeug in Jan 2020? It would be nice if the docs stated which version of Werkzeug it is applicable to.

**Comment by miguelgrinberg** [comment]
Yes, this is still true. Werkzeug does not have a websocket implementation, it just has the support to route websocket requests.

**Comment by ysangkok** [comment]
Aaah, all right, I didn't realize there was more to it. Thanks for the swift response :)
