### ISSUE TITLE
Threading server selected over eventlet server (v1.0b)

### ISSUE THREAD

**Issue by PTaylour** [miguelgrinberg/Flask-SocketIO#150]
Hi all,

I'm having trouble starting flask_socketio with the eventlet server.

I only have eventlet installed, nothing that resembles gevent:
```
pip freeze | grep event
eventlet==0.17.4

pip freeze | grep gevent
# nothing to see here
```

Yet, the following (with or without the explicit async_mode='eventlet')
```
from flask_socketio import SocketIO
socketio = SocketIO()

[...]

socketio.init_app(app, engineio_logger=True, async_mode='eventlet')
```

prints out this:
`Server initialized for threading.`

on starting the app.
Am I doing something obviously wrong?

**Comment by miguelgrinberg** [comment]
This is very odd. Are you using the example app? If not, can you check with that application?

Also, can you try without passing the `async_mode` argument? The extension should select eventlet by default, since that is preferred over threading when it is found to be installed.

**Comment by PTaylour** [comment]
Strange indeed. Just tried the example app, worked fine (`Server initialized for eventlet`), and tried the example app using the same virtualenv as my project--again that also worked fine. 

This is a project worked with Flask-SocketIO versions <1.0.

So looks like it's something to do with my project but not the install. I can't see much that could be going wrong. Any tips on how to track this down? 

The project is based on [flaskage](https://github.com/fgimian/flaskage) so I'm calling `socketio.init_app` in `configure_extensions` in an app `__init__.py` that looks a lot like https://github.com/fgimian/flaskage/blob/master/flaskage/templates/project/app/__init__.py.jinja

**Comment by ktoh** [comment]
I ran I to something similar with a 0.60 project migrating to 1.0b.
In my case, uninstalling packages (in particular gevent and gevent-socketio) fixed the problem.

**Comment by PTaylour** [comment]
@ktoh I thought it could be something like that initially, but tried with completely fresh installs of my requirements and still found the same behaviour.

However--update--I just found that the problem is definitely caused by my app configuration.

If I remove my `app.config.from_object` then everything works as expected.

Now looking into what could conflict in my config.

**Comment by PTaylour** [comment]
Ah, it is really nothing exciting. 

I hadn't realised that..
```
        if app.debug:
            self.server_options['async_mode'] = 'threading'
```
and you'd never guess what was in the config.  (yes..`DEBUG = True`)

Problem solved!

**Comment by miguelgrinberg** [comment]
Oh, I see. The 1.0b1 release forces threading when in debug mode, but I have removed that limitation, you can see the commit that changed that in the history. The next release will not require threading when running debug mode.

**Comment by PTaylour** [comment]
Good stuff. Apologies for dragging this out, but I have (what I now know to be) an unrelated setup issue. 

When running with gunicorn
```
gunicorn --log-file=- --worker-class eventlet -w 1 wsgi:app
```
My client looks to be trying and failing to poll `GET http://localhost:8000/socket.io/?EIO=3&transport=polling&t=1444692088909-12 404 (NOT FOUND)`. 

This is using `"socket.io-client": "~1.3.7"`.

**Comment by miguelgrinberg** [comment]
@PTaylour how is `app` defined in wsgi.py?

**Comment by PTaylour** [comment]
my wsgi.py is 
```
from app import create_app
app = create_app('production')
```

and create_app is 

```
def create_app(config):
    instance_path = os.path.abspath(
        os.path.join(
            os.path.dirname(os.path.dirname(__file__)), 'config', 'instance'
        )
    )
    app = Flask(
        __name__, instance_path=instance_path, instance_relative_config=True
    )
    configure_app(app, config)
    configure_extensions(app, db)
    configure_logging(app)
    configure_hooks(app)
    configure_template_filters(app)
    configure_template_globals(app)
    configure_error_handlers(app)
    configure_blueprints(app)
    return app
```

**Comment by miguelgrinberg** [comment]
Yeah, I see what the problem is. I do not create the SocketIO middleware, this needs to be added.

As a workaround until I get this fixed, add the following line right before `return app`:

    app.wsgi_app = socketio.Middleware(socketio.server, app.wsgi_app)

where `socketio` is your `SocketIO` instance.

This is done for you inside `socketio.run`, clearly I have to move it outside, so that it is also done when not using the embedded web server.

**Comment by PTaylour** [comment]
I'm getting `AttributeError: 'SocketIO' object has no attribute 'Middleware'` when I try with my `SocketIO` instance.

I tried `app.wsgi_app = Middleware(Server(**socketio.server_options), app.wsgi_app)`, importing `Middleware` and `Server` from the `socketio` module, after which the client did connect after this error

```
WebSocket connection to 'ws://localhost:8000/socket.io/?EIO=3&transport=websocket&sid=fea549b8737348269d5c25a8af5ce6a2' failed: Error during WebSocket handshake: Unexpected response code: 500
```

which has the trace 
```
Traceback (most recent call last):
  File "/Users/petertaylour/.virtualenv/qpl-web-app/lib/python2.7/site-packages/gunicorn/workers/async.py", line 45, in handle
    self.handle_request(listener, req, client, addr)
  File "/Users/petertaylour/.virtualenv/qpl-web-app/lib/python2.7/site-packages/gunicorn/workers/async.py", line 93, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/Users/petertaylour/.virtualenv/qpl-web-app/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/petertaylour/.virtualenv/qpl-web-app/lib/python2.7/site-packages/engineio/middleware.py", line 32, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/Users/petertaylour/.virtualenv/qpl-web-app/lib/python2.7/site-packages/socketio/server.py", line 301, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/Users/petertaylour/.virtualenv/qpl-web-app/lib/python2.7/site-packages/engineio/server.py", line 224, in handle_request
    environ, start_response)
  File "/Users/petertaylour/.virtualenv/qpl-web-app/lib/python2.7/site-packages/engineio/socket.py", line 75, in handle_get_request
    start_response)
  File "/Users/petertaylour/.virtualenv/qpl-web-app/lib/python2.7/site-packages/engineio/socket.py", line 110, in _upgrade_websocket
    return ws(environ, start_response)
  File "/Users/petertaylour/.virtualenv/qpl-web-app/lib/python2.7/site-packages/eventlet/websocket.py", line 113, in __call__
    ws = self._handle_hybi_request(environ)
  File "/Users/petertaylour/.virtualenv/qpl-web-app/lib/python2.7/site-packages/eventlet/websocket.py", line 195, in _handle_hybi_request
    sock = environ['eventlet.input'].get_socket()
KeyError: 'eventlet.input'
```

**Comment by miguelgrinberg** [comment]
Sorry, my bad. You need to import `Middleware` as follows:

    from socketio import Middleware

or else, just do

    import socketio

and then reference the class as `socketio.Middleware`. If you go with this last option, you may have a collision between the `socketio` package and the socketio instance, so you will need to rename your instance.

**Comment by PTaylour** [comment]
hmm I'm now getting `AttributeError: 'NoneType' object has no attribute 'handle_request'`

My `socketio.server` is `None`. Am I right in saying `self.server` is only set in `SocketIO.run`?

**Comment by miguelgrinberg** [comment]
@PTaylour yes, you are correct. This is an embarrassing omission on my part. I have now restructured the extension to create the server and set up the middleware in `init_app`, which I should have done from the start.

Could you please give it a try and confirm this works for you?

Side note, while testing this code with gunicorn I have found a new issue #153 that you may run into if you use gunicorn and eventlet together. That fix is coming soon as well.

**Comment by PTaylour** [comment]
@miguelgrinberg yep, it now works for me.

And yes, also recreating issue #153 when using eventlet with gunicorn.

Thanks for you help Miguel. Glad I could help in covering some issues.
