### ISSUE TITLE
Emitting, not broadcasting, to a single client in an external process

### ISSUE THREAD

**Issue by tsoernes** [miguelgrinberg/Flask-SocketIO#1502]
Is this possible to emit to a single client in an external process? I assume that SocketIO needs to run on Redis. How do I communicate which client that the external process should emit to?

**Comment by miguelgrinberg** [comment]
You can emit to a single client by passing the `sid` of that client as the room name.

**Comment by tsoernes** [comment]
Do I need to create that room first?

**Comment by miguelgrinberg** [comment]
No. A room with the `sid` name is created automatically for each user upon connection.
