### ISSUE TITLE
AssertionError: wrong app context with emit unit testing

### ISSUE THREAD

**Issue by SirRunner** [miguelgrinberg/Flask-SocketIO#1504]
Hey miguel, I'm working on writing pytest unit tests for one of my projects, and I'm running into an issue with emitting from my test clients. My own digging into the issue has identified that the emit line is causing the error, and that the issue is probably with the test, but I am having an issue figuring out what I have done wrong. 

```
def test_client_connect(client_2):
    socketio_client = socketio.test_client(app, namespace="/combat", flask_test_client=client_2)

    row_id = "1"
    app_context = client_2.get(f"/room/{row_id}")
    open_room_test = client_2.post("/generate_room", data={"room_id":f"{row_id}", "csrf_token":client_2.csrf_token}, follow_redirects=True)

    assert socketio_client.is_connected("/combat")
    assert not socketio_client.is_connected("/")

    room_id = "12345678"
    # Throws an 'AssertionError: Popped wrong app context.'
    socketio_client.emit("on_join", {'room_id': room_id}, namespace="/combat")
```

The "on_join" event has a client join the specified socketio room.

**Comment by miguelgrinberg** [comment]
Are you doing anything with application contexts, either in your application or in your pytest fixtures? That's where the problem is, likely.

**Comment by SirRunner** [comment]
I don't think so. I honestly did not know that one could even touch application contexts until this error started occurring. Here's the client_2 definition. I removed the database specifics since this is a public forum.

```
@pytest.fixture
def client_2(mocker):
    app.config['TESTING'] = True
    app.test_client_class = FlaskClient
    with app.test_client() as client_2:
        create_dbs()
        mocker.patch("flask_login.utils._get_user", return_value = UserObject)
        AddUserInfoToDB
        yield client_2
    
    RemoveUserInfoFromDB
```

**Comment by miguelgrinberg** [comment]
@SirRunner See if the answers to this question help: https://stackoverflow.com/questions/26647032/py-test-to-test-flask-register-assertionerror-popped-wrong-request-context.

**Comment by SirRunner** [comment]
I had already looked at that. I went through it again and tried the suggestion (and followed the link to the flask-testing issue. Setting `FLASK_DEBUG=0` and `PRESERVE_CONTEXT_ON_EXCEPTION=False` did not work. All of the pytest fixtures already are scoped to "function".

**Comment by miguelgrinberg** [comment]
@SirRunner Okay, but did you look at the explanation? Any chance something is failing in the `tearDown` method of your test case?

**Comment by SirRunner** [comment]
It looks like it was failing. Somehow it was grabbing the wrong app context. I was able to fix it by wrapping all of the socketio testing in a `with app.app_context():`.
