### ISSUE TITLE
Adding to Deployment Documentation

### ISSUE THREAD

**Issue by nipunarora** [miguelgrinberg/Flask-SocketIO#151]
Thanks for an excellent and well written project.

The gunicorn required for deployment is version 18.0
pip install gunicorn==18.0

As well as the module to be run it seems is the flask module? (I assume)
~/flask-socketio-celery-example/flask-socketio/bin/gunicorn --worker-class socketio.sgunicorn.GeventSocketIOWorker app:app -w 2 -b 0.0.0.0:3400

With gunicorn using virtual environment one also needs to be careful and use the complete path, as gunicorn will otherwise use the system python :P - A mistake I made

Maybe this can be added to the documentation.

**Comment by miguelgrinberg** [comment]
Documentation has been updated in release 1.0.
