### ISSUE TITLE
about start_background_task

### ISSUE THREAD

**Issue by cocxtrash** [miguelgrinberg/Flask-SocketIO#1517]
**How many start_background_task can run at same time?**
I am a noob when it comes to server config and running things parallelly.

This is my server config running in heroku.

_Procfile_
`web: uwsgi uwsgi.ini`

_Uwsgi_
```
http-socket = :$(PORT)
master = true
processes = 4
die-on-term = true
wsgi-file = run.py
callable = app
memory-report = false
gevent-monkey-patch = true
gevent-early-monkey-patch = true
gevent = 1000
http-websockets = true

```
I need to return response in 30sec. So this is how i am running long task. then manually sending necessary data to api from backgroud task.
```
@app.route('/api')
def hello():
    socketio.start_background_task(about_five_minute_task) 
    return f'demand response in 30 second'
```

**Everything works**.  I just want to know how many _background_task_ can i keep running or start at same time? Also will they keep running or will wait for other background_task to finish? 

**I am thinking of increasing the usage of start_background_task. So i'm afraid, is there any limit that i will hit?**

**Comment by miguelgrinberg** [comment]
The `start_background_task()` function creates a thread, or the closest thing to a thread that is available within the async_mode that you are using. In general there is no limit to the number of tasks you can have running at a time, though threads and the resources they use are not unlimited and you will eventually run out.

**Comment by cocxtrash** [comment]
Understood. Thank You :)
