### ISSUE TITLE
Server restarts when running background task

### ISSUE THREAD

**Issue by BenAAndrew** [miguelgrinberg/Flask-SocketIO#1520]
**Describe the bug**
After initializing a background task with `socketio.start_background_task(background_task, **kwargs)` the background task runs halfway through, before abruptly restarting the entire socketio application (`Server initialized for threading.` appears alongside other setup messages)

**To Reproduce**
1. Launch application
2. Trigger background task
3. Wait for 30 seconds

**Expected behavior**
App should not restart and either run background task to completion or raise an Exception.

**Logs**
```
INFO:socketio.server:emitting event "logs" to all [/voice]
0cOxmJ7_lcn6AXqdAAAA: Sending packet MESSAGE data 2/voice,["logs",{"text":"Loaded data"}]
INFO:werkzeug:127.0.0.1 - - [12/Apr/2021 11:34:57] "GET /socket.io/?EIO=4&transport=polling&t=NZ5fU0W&sid=0cOxmJ7_lcn6AXqdAAAA HTTP/1.1" 200 -
INFO:engineio.server:0cOxmJ7_lcn6AXqdAAAA: Sending packet MESSAGE data 2/voice,["logs",{"text":"Loaded data"}]
INFO:voice:Loaded data
emitting event "logs" to all [/voice]
INFO:socketio.server:emitting event "logs" to all [/voice]
0cOxmJ7_lcn6AXqdAAAA: Sending packet MESSAGE data 2/voice,["logs",{"text":"Loaded checkpoint 'data\\models\\Dave\\checkpoint_510000' from iteration 510001"}]
INFO:werkzeug:127.0.0.1 - - [12/Apr/2021 11:34:59] "GET /socket.io/?EIO=4&transport=polling&t=NZ5fWyM&sid=0cOxmJ7_lcn6AXqdAAAA HTTP/1.1" 200 -
INFO:engineio.server:0cOxmJ7_lcn6AXqdAAAA: Sending packet MESSAGE data 2/voice,["logs",{"text":"Loaded checkpoint 'data\\models\\Dave\\checkpoint_510000' from iteration 510001"}]
INFO:voice:Loaded checkpoint 'data\models\Dave\checkpoint_510000' from iteration 510001
Epoch: 157
emitting event "progress" to all [/voice]
INFO:socketio.server:emitting event "progress" to all [/voice]
0cOxmJ7_lcn6AXqdAAAA: Sending packet MESSAGE data 2/voice,["progress",{"number":" 157","total":"1000"}]
INFO:engineio.server:0cOxmJ7_lcn6AXqdAAAA: Sending packet MESSAGE data 2/voice,["progress",{"number":" 157","total":"1000"}]
INFO:voice:Progress - 157/1000
INFO:werkzeug:127.0.0.1 - - [12/Apr/2021 11:34:59] "GET /socket.io/?EIO=4&transport=polling&t=NZ5fXL-&sid=0cOxmJ7_lcn6AXqdAAAA HTTP/1.1" 200 -
Server initialized for threading.
Server initialized for threading.
```

**Additional context**
The source code can be found here: https://github.com/BenAAndrew/Voice-Cloning-App with the background task code in https://github.com/BenAAndrew/Voice-Cloning-App/blob/main/application/utils.py and function running as the background task: https://github.com/BenAAndrew/Voice-Cloning-App/blob/main/training/train.py.

This was working only about a week ago so I suspect I've done something to cause this, but it's very odd behavior which is making it difficult to debug.

Commenting out a section of code prevents the issue which suggests that it may cause an Exception, but previously this exception would be raised, whereas now the app is restarting.

**Comment by miguelgrinberg** [comment]
The server does not have any logic to restart itself. How are you running this server? I assume it is as a Docker container? Have you confirmed the container ID remains the same after one of this occurrences? I believe what you are seeing is that your container is dying for some reason and you have it configured to auto-restart.

**Comment by BenAAndrew** [comment]
Hi @miguelgrinberg, This is been run locally as a python process (i.e. `python main.py` which is the script that executes `socketio.run(app)`) so no docker related stuff here

**Comment by miguelgrinberg** [comment]
@BenAAndrew Are you running Flask in debug mode, by any chance? Could it be the Flask reloader acting up?

**Comment by BenAAndrew** [comment]
@miguelgrinberg I've tried turning off debugging and reloader but no luck

**Comment by miguelgrinberg** [comment]
@BenAAndrew the only other suggestion that I have is that you back track your git commits until the issue is resolved. Once you have this behavior mapped to the commit that introduced it we can hopefully do a better analysis.

**Comment by BenAAndrew** [comment]
@miguelgrinberg No worries, I will spend today and tomorrow investigating.

**Comment by BenAAndrew** [comment]
The issue appears to have been that the background task function was creating other threads and causing it to crash. This is an issue with the python threading library rather than this project
