### ISSUE TITLE
Confuse with start_background_task

### ISSUE THREAD

**Issue by alexcc4** [miguelgrinberg/Flask-SocketIO#1521]
**question**
I just started celery and flask for long run task . Using SocketIO for monitoring celery task log（one log per task). However, I started two client, only the first client showed log. The log of second client just appended to first client terminal.

**code**

client.py
```
import sys

import socketio


client = socketio.Client(reconnection=False)


@client.on('log', namespace='/cdc')
def on_log(args):
    print(args['data'])


def send(log_path):
    try:
        client.connect('http://127.0.0.1:5000', namespaces='/cdc')
        client.emit('log', {'log_path': log_path}, namespace='/cdc')
    except KeyboardInterrupt:
        try:
            sys.exit(0)
        except SystemExit:
            sys.exit(1)
``` 

server.py

```
is_connected = False
thread = None
thread_lock = threading.Lock()


@sio.on('log', namespace='/cdc')
def log(data):
    global thread
    with thread_lock:
        if thread is None:
            thread = sio.start_background_task(scan_log, data['log_path'], flask.request.sid)


def scan_log(log_path, client_id=None):
    global is_connected
    counter = 0
    with open(log_path, 'r') as f:
        while is_connected:
            line = f.readline()
            if not line:
                sio.sleep(0.1)
                continue
            counter += 1
            sio.emit('log', {'data': line.strip()}, namespace='/cdc', to=client_id)
```

**Logs**
![image](https://user-images.githubusercontent.com/5210569/114522430-f5919e80-9c75-11eb-83ea-9f2e9f34a10d.png)
![image](https://user-images.githubusercontent.com/5210569/114522504-0510e780-9c76-11eb-8914-228c71722220.png)

**Comment by miguelgrinberg** [comment]
You are starting a single background thread. Where is the thread for the 2nd client?

**Comment by alexcc4** [comment]
@miguelgrinberg I just run `flask run` for service.
Is there an example for this case?

**Comment by cis1124** [comment]
I just encountered the same problem. I want each new socket connection has a thread to accept request.But it cant work.
Seems only new connection work.

**Comment by miguelgrinberg** [comment]
@alexcc4 I don't know what "this case" means. You have logic in your application to start a single background thread (i.e you have a single `thread` global variable). You haven't done anything to start additional threads.

**Comment by alexcc4** [comment]
> @alexcc4 I don't know what "this case" means. You have logic in your application to start a single background thread (i.e you have a single `thread` global variable). You haven't done anything to start additional threads.
Thx, I will try starting additional threads.
By the way, any great example?

**Comment by alexcc4** [comment]
@miguelgrinberg Thx, I will try starting additional threads.
By the way, any great example?

**Comment by alexcc4** [comment]
> @alexcc4 I don't know what "this case" means. You have logic in your application to start a single background thread (i.e you have a single `thread` global variable). You haven't done anything to start additional threads.

I remove `thread` global variable.

```
@sio.on('log', namespace='/cdc')
def log(data):
    # global thread
    # with thread_lock:
    #     if thread is None:
    thread = sio.start_background_task(scan_log, data['log_path'], None, flask.request.sid)
```

I started one client, the log showed normally.
Then, the second, the log in its window seem normal.
Otherwise, log of second client append to the first.
![image](https://user-images.githubusercontent.com/5210569/114534519-ab161f00-9c81-11eb-869c-72040efb7805.png)

After I stop the first client, all log seem normal, no matter how many client I start.

![image](https://user-images.githubusercontent.com/5210569/114534946-19f37800-9c82-11eb-9612-6ef509bb6231.png)

**Comment by miguelgrinberg** [comment]
I'm sorry but the screenshots that you are showing me don't have any meaning to me. Is each client dumping a different log file? If the clients are all looking at the same log file they're all going to report the same logs.

**Comment by alexcc4** [comment]
Yep, each client(task) dumping a different log file

**Comment by alexcc4** [comment]
I started server with `gunicorn + eventlet `, using `gunicorn --worker-class eventlet -w 2 "app:create_app()"` , instead of `flask run`. Then, it seems all right(every client log normally).
Is that concerned with the way service start up?

**Comment by miguelgrinberg** [comment]
The `-w 2` is not supported, you would normally use `-w 1` when using eventlet or gevent. Also `flask run` is not supported if you intend to use eventlet, that only works for the standard development server, which lacks support for WebSocket.

**Comment by alexcc4** [comment]
Thx for quick reply.
