### ISSUE TITLE
sid and background task in eventlet

### ISSUE THREAD

**Issue by FerusAndBeyond** [miguelgrinberg/Flask-SocketIO#1523]
I have two questions. Firstly, if I log `sid` when someone connects to the client and then log it again when the same user disconnects they're different. Isn't `sid` unique for each user for each session? Secondly, if I start a background task with `start_background_task` and eventlet the main thread is blocked. Also when using emit in this thread it doesn't seem to send anything back to the client. Only if I add `eventlet.sleep(0.1)` every loop does it work. Is there another solution to this?

Essentially it looks like this:

```
def thread_work(route):
    while not finished:
        ... do some work ...
        route.emit()

start_background_task(thread_work, route)
```

Also if I want to stop this thread in case the user disconnects, is the most appropriate way to listen for `on("disconnect")` and save all disconnects or is there an easier way?

**Comment by miguelgrinberg** [comment]
> Firstly, if I log sid when someone connects to the client and then log it again when the same user disconnects they're different.

Can you show me the code that you are using for this? The sids should be the same.

> if I start a background task with start_background_task and eventlet the main thread is blocked.

Eventlet does not uses threads, it uses greenlets, which are a special kind of coroutines. Everything runs in the main thread. To prevent a greenlet from blocking you have to release the CPU often. You may want to read up on asynchronous development if you are not familiar with the async model. The documentation for eventlet is a good place to start.

> Also when using emit in this thread it doesn't seem to send anything back to the client. Only if I add eventlet.sleep(0.1) every loop does it work.

Emits are asynchronous. If your task performs blocking tasks after it calls emit then you are not giving a chance to the background work that gets the emitted data out to do its thing. The way to not block is to call the sleep function as often as you can. You can pass a 0 as an argument, doesn't need to be a positive number. Once again, this is common async development. Seems weird if you are not familiar with it, but that's how things work.

**Comment by FerusAndBeyond** [comment]
> Can you show me the code that you are using for this? The sids should be the same.

I narrowed it down to namespaces vs global. Sids in namespaces are different than those in global for the same user, but sids in connect/disconnect is the same if they are in the same namespace.

> Eventlet does not uses threads, it uses greenlets, which are a special kind of coroutines. Everything runs in the main thread. To prevent a greenlet from blocking you have to release the CPU often. You may want to read up on asynchronous development if you are not familiar with the async model. The documentation for eventlet is a good place to start.

Okay, I was not sure what coroutine would have the focus after calling emit in the greenlet, but I guess it makes sense that if the process is looping synchronously that it will keep blocking.

Also given that a thread is running and passing emit, is there any way to know if the emit didn't reach the client (because it is disconnected) or is the only way to know this to monitor the disconnects? Appreciate the help.

**Comment by miguelgrinberg** [comment]
> is there any way to know if the emit didn't reach the client

The reverse is possible. You can emit to a client and ask for a callback, which confirms the message was received.

**Comment by FerusAndBeyond** [comment]
Okay, thanks!
