### ISSUE TITLE
get_received() returns empty in unittests

### ISSUE THREAD

**Issue by dariuscosden** [miguelgrinberg/Flask-SocketIO#1528]
I followed the documentation and am not able to get events emitted with `get_received()`. No matter what I try, it always returns an empty list.

Here is my setup

This is my BaseTestCase which tests inherit from.

```
# imports

socketio = SocketIO()

class BaseTestCase(unittest.TestCase):
    def setUp(self):
        self.app = create_app()
        self.test_client = self.app.test_client()

        self.socket = socketio
```

This is an individual test class

```
# imports

class TestSocket(BaseTestCase):
    def setUp(self):
        super().setUp()

        self.namespace = "/socket/v1/user"
        self.socket_test_client = self.socket.test_client(
            self.app,
            namespace=self.namespace,
            flask_test_client=self.test_client,
        )

    def tearDown(self):
        self.socket_test_client.disconnect(namespace=self.namespace)

    def test_1(self):
            self.socket_test_client.emit(
                "test_event", namespace=self.namespace
            )
            r = self.socket_test_client.get_received(namespace=self.namespace)
            print(r)  # Always empty...  why?
```

And here is the main socket

```
# imports

class UserSocket(Namespace):

    def on_test_event(self):
        emit(
                "received_event",
                json.dumps({"test": true}),
            )

socketio.on_namespace(UserSocket("/socket/v1/user"))
```

I've seen others post about this issue but none of them were able to solve my issue. What am I doing wrong?

**Comment by miguelgrinberg** [comment]
Is the event handler running at all? That would be the first thing I would check. The code that you are showing for the event handler appears broken, not sure if this is a result of bad copy/paste or if it is really broken and that is what prevents the emit from working.

**Comment by dariuscosden** [comment]
The code I showed is heavily simplified to make it easy to read here. I might have made some copy paste mistakes. Could you tell me what is broken in the above? I'm not able to see it.

When I run the tests, as well as when I run the app and call these events through the client, it all works and emits the appropriate events. It is specifically the test that is not returning any received events from the socket test client.

**Comment by miguelgrinberg** [comment]
@dariuscosden you have a `true` constant, which should be `True`. That's a silly error, I get that, but it tells me that I'm likely not seeing all the details about your implementation, since you are editing and removing stuff.

The fact is that this package itself relies heavily on the `get_received()` method for its own unit tests, so there's got to be something in particular that makes it fail for you. If you can create a simple example of a server and a unit test that show this, something that is runnable by me that would be the most useful.

**Comment by dariuscosden** [comment]
Found out my error. In my simplified code above, I removed the rooms I joined and emitted to. In reality, in my code I am sending events to specific rooms each time and  I wasn't joining the appropriate room in my test cases and therefore I wasn't receiving the events emitted by the socket client.

So allow me to add some details here for anyone else that may run into something similar.

The updated main socket

```
# imports

class UserSocket(Namespace):

    def on_join(self, data):
        join_room(data["user_id"])

    def on_test_event(self):
        emit(
                "received_event",
                json.dumps({"test": "worked"}), # Thanks Miguel for pointing this silly mistake
                room="1" # I was emitting to a room
            )

socketio.on_namespace(UserSocket("/socket/v1/user"))
```

In my tests, I had to make this change

```
# imports

class TestSocket(BaseTestCase):
    def setUp(self):
        super().setUp()

        self.namespace = "/socket/v1/user"
        self.socket_test_client = self.socket.test_client(
            self.app,
            namespace=self.namespace,
            flask_test_client=self.test_client,
        )

        # Update: need to join room to receive events!
        self.socket_test_client.emit("join", {"user_id": "1"}, namespace=self.namespace)

    def tearDown(self):
        self.socket_test_client.disconnect(namespace=self.namespace)

    def test_1(self):
            self.socket_test_client.emit(
                "test_event", namespace=self.namespace
            )
            r = self.socket_test_client.get_received(namespace=self.namespace)
            print(r)  # No longer empty, returns proper values
```
