### ISSUE TITLE
Background Thread emits messages, but does not send Packets when started from a Class-Based Namespace

### ISSUE THREAD

**Issue by jaikun12** [miguelgrinberg/Flask-SocketIO#1538]
Hi, I'm not sure if there is something wrong with my implementation. Whenever I run a background thread in my class-based namespace, the background thread seems to work (able to emit) but does not send packets to the client. Please see the logs below:

![image](https://user-images.githubusercontent.com/15951100/116646748-71e0ed00-a9ab-11eb-99da-89f1aed9f61e.png)

Here's my current code:
### __init__.py
https://github.com/jaikun12/SocketIO-test/blob/main/app/__init__.py

### namespaces.py
https://github.com/jaikun12/SocketIO-test/blob/main/app/mod_notifications/namespaces.py

**Comment by miguelgrinberg** [comment]
I can't reproduce from here, your code works fine for me.

```
emitting event "response" to P-iakqp2z4yN3gohAAAC [/notification]
Tfw2metBW9XsEY2-AAAA: Sending packet MESSAGE data 2/notification,["response",{"data":"Server generated event"}]
emitting event "response" to P-iakqp2z4yN3gohAAAC [/notification]
Tfw2metBW9XsEY2-AAAA: Sending packet MESSAGE data 2/notification,["response",{"data":"Server generated event"}]
emitting event "response" to P-iakqp2z4yN3gohAAAC [/notification]
Tfw2metBW9XsEY2-AAAA: Sending packet MESSAGE data 2/notification,["response",{"data":"Server generated event"}]
```

**Comment by jaikun12** [comment]
Hi @miguelgrinberg thanks for looking into this, I'm closing this for now and check if the issue is caused by something else.
