### ISSUE TITLE
Disconnect unauthenticated users when using Flask-Login with v1.0

### ISSUE THREAD

**Issue by meismyles** [miguelgrinberg/Flask-SocketIO#154]
In the documentation for Flask-SocketIO v0.x, when using Flask-Login we could disconnect unauthenticated users using `request.namespace.disconnect()`.

Since `request.namespace` now returns the name of the namespace being handled rather than the connection in v1.0, how would we do this?

I'm using v1.0b1 with eventlet.

**Comment by miguelgrinberg** [comment]
The examples in the 0.x documentation use an outdated form of the disconnect. You can achieve the same thing with the following, which works in both 0.x and 1.x releases:

    from flask_socketio import disconnect
    ...
    @socketio.on('event')
    def my_event():
        disconnect()
