### ISSUE TITLE
'Request' object has no attribute 'namespace'

### ISSUE THREAD

**Issue by viktorstrand** [miguelgrinberg/Flask-SocketIO#1540]
Do you know what is causing the error?
![Screenshot (10)](https://user-images.githubusercontent.com/46597051/117182956-43ae4380-add7-11eb-8bd9-bcbdcc40560b.png)

**Comment by miguelgrinberg** [comment]
Yes. The `request.namespace` attribute is only available in the context of a Socket.IO event handler. You seem to be using it in a standard request instead.

**Comment by viktorstrand** [comment]
I am a bit confused as to what namespaces are. In my example, is 'dealer_hit' the namespace?

**Comment by miguelgrinberg** [comment]
Just add `namespace='/'` to your `emit()` call, that's all you need to do. When this function is called from a Socket.IO handler, the namespace is available in the request context. When you use it somewhere else, the request context does not have the namespace, so you have to provide it.

**Comment by viktorstrand** [comment]
Thank you so much!
