### ISSUE TITLE
Cannot access session[] from function with @socketio.on decorator. 

### ISSUE THREAD

**Issue by viktorstrand** [miguelgrinberg/Flask-SocketIO#1542]
I am trying to access session['user_id'] which i have defined in a function bypass() with @app.route decorator. When I call a different function that utilizes session['user_id'] from the function bypass(), everything works fine. But when attempt to call it from a function new_player_joined() with @socketio.on decorator, it gives me an error. 
Note, the code is strange for testing purposes. I just want t know how to access the session from the new_player_joined() function.
<img width="188" alt="Skärmbild 2021-05-06 175507" src="https://user-images.githubusercontent.com/46597051/117328908-62264480-ae94-11eb-9ad6-c24365cc23ba.png">
<img width="229" alt="Skärmbild 2021-05-06 175526" src="https://user-images.githubusercontent.com/46597051/117328914-62bedb00-ae94-11eb-9051-15114307aaba.png">
<img width="173" alt="Skärmbild 2021-05-06 175600" src="https://user-images.githubusercontent.com/46597051/117328917-62bedb00-ae94-11eb-9dc2-8bd08c54905a.png">

**Comment by miguelgrinberg** [comment]
Have you read the limitations regarding the use of the user session in the documentation? https://flask-socketio.readthedocs.io/en/latest/#access-to-flask-s-context-globals
