### ISSUE TITLE
App doesn't start until I press Ctrl + C

### ISSUE THREAD

**Issue by pmorim** [miguelgrinberg/Flask-SocketIO#1550]
## My app does not start receiving/sending messages until I press Ctrl+C in the terminal.

server.py:
```python
# Flask
from flask import Flask
from flask_socketio import SocketIO, emit
from flask_cors import CORS

# Eventlet server
import eventlet
eventlet.monkey_patch()

# .env
import os
from dotenv import load_dotenv, find_dotenv
load_dotenv(find_dotenv())

# Server initialization
app = Flask(__name__)
app.config['CORS_HEADERS'] = 'Content-Type'
app.config['SECRET_KEY'] = os.environ.get('SECRET')
socketio = SocketIO(app, cors_allowed_origins='*')
CORS(app)


@socketio.event
def connect():
  emit('server_client', 'test message')


@socketio.event
def client_server(json_obj):
  print(json_obj)


if __name__ == '__main__':
  app.run(host='localhost', port=os.environ.get('PORT'))
  socketio.run(app)
```

Terminal output:
>  * Serving Flask app 'server' (lazy loading)
> * Environment: production
>   WARNING: This is a development server. Do not use it in a production deployment.
>   Use a production WSGI server instead.
> * Debug mode: off
> * Running on http://localhost:5000/ (Press CTRL+C to quit)

After I press Ctrl+C:
>**^C**127.0.0.1 - - [16/May/2021 15:25:25] "GET /socket.io/?EIO=4&transport=polling&t=NbraI4r HTTP/1.1" 200 -
>127.0.0.1 - - [16/May/2021 15:25:25] "POST /socket.io/?EIO=4&transport=polling&t=NbraKSo&sid=W3o8EvTlMk1UVF6pAAAA HTTP/1.1" 200 -

**Comment by miguelgrinberg** [comment]
Remove the `app.run()` call. The only thing you should have at the bottom is `socketio.run(app)`.

**Comment by pmorim** [comment]
How would I choose the port of the app then?
