### ISSUE TITLE
Why it is needed to specify app in SocketIO constructor and also in SocketIO run method?

### ISSUE THREAD

**Issue by busslina** [miguelgrinberg/Flask-SocketIO#1552]
If specified in constructor and try to run the "run" method without specify the "app" parameter it will crash.
If not specified in constructor but specified in "run" method as parameter it works fine apparently.

Thanks

**Comment by miguelgrinberg** [comment]
Is there a problem with having to specify it twice? Flask extensions normally do not keep a copy of the app, this is why the app needs to be provided in every call that it is needed.

**Comment by busslina** [comment]
Thank for clarifying me this. It seemed weird to me but now it make sense.
