### ISSUE TITLE
ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA]

### ISSUE THREAD

**Issue by busslina** [miguelgrinberg/Flask-SocketIO#1554]
Today I have move from flask default development server (Werkzeug) to a production one. I installed evenlet and run it. Apparently everything runs fine. My https site runs okay. Even better, because with Werkzeug server, the app was randomly crashing due to "headers already sent" bug and it  was breaking my head. 
**But it appears constantly a SSL error that is not causing my server crash.** But I want to know why occurs. Every browser that I tested with it process successfully the SSL certificate (LetsEncrypt).

> Traceback (most recent call last):
>   File "/root/.local/share/virtualenvs/https-server-S4Igx79L/lib/python3.7/site-packages/eventlet/hubs/poll.py", line 111, in wait
>     listener.cb(fileno)
>   File "/root/.local/share/virtualenvs/https-server-S4Igx79L/lib/python3.7/site-packages/eventlet/greenthread.py", line 221, in main
>     result = function(*args, **kwargs)
>   File "/root/.local/share/virtualenvs/https-server-S4Igx79L/lib/python3.7/site-packages/eventlet/wsgi.py", line 815, in process_request
>     proto.__init__(conn_state, self)
>   File "/root/.local/share/virtualenvs/https-server-S4Igx79L/lib/python3.7/site-packages/eventlet/wsgi.py", line 346, in __init__
>     self.handle()
>   File "/root/.local/share/virtualenvs/https-server-S4Igx79L/lib/python3.7/site-packages/eventlet/wsgi.py", line 379, in handle
>     self.handle_one_request()
>   File "/root/.local/share/virtualenvs/https-server-S4Igx79L/lib/python3.7/site-packages/eventlet/wsgi.py", line 408, in handle_one_request
>     self.raw_requestline = self._read_request_line()
>   File "/root/.local/share/virtualenvs/https-server-S4Igx79L/lib/python3.7/site-packages/eventlet/wsgi.py", line 391, in _read_request_line
>     return self.rfile.readline(self.server.url_length_limit)
>   File "/usr/lib/python3.7/socket.py", line 589, in readinto
>     return self._sock.recv_into(b)
>   File "/root/.local/share/virtualenvs/https-server-S4Igx79L/lib/python3.7/site-packages/eventlet/green/ssl.py", line 252, in recv_into
>     return self._base_recv(nbytes, flags, into=True, buffer_=buffer)
>   File "/root/.local/share/virtualenvs/https-server-S4Igx79L/lib/python3.7/site-packages/eventlet/green/ssl.py", line 267, in _base_recv
>     read = self.read(nbytes, buffer_)
>   File "/root/.local/share/virtualenvs/https-server-S4Igx79L/lib/python3.7/site-packages/eventlet/green/ssl.py", line 187, in read
>     super(GreenSSLSocket, self).read, *args, **kwargs)
>   File "/root/.local/share/virtualenvs/https-server-S4Igx79L/lib/python3.7/site-packages/eventlet/green/ssl.py", line 161, in _call_trampolining
>     return func(*a, **kw)
>   File "/usr/lib/python3.7/ssl.py", line 911, in read
>     return self._sslobj.read(len, buffer)
> ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:2488)
> Removing descriptor: 9
> 
>

**Comment by miguelgrinberg** [comment]
Have you asked in an eventlet forum? This error has nothing to do with this package, it comes from the SSL implementation in eventlet.

**Comment by busslina** [comment]
My fault. Thank you
