### ISSUE TITLE
How to access connection `auth` parameters

### ISSUE THREAD

**Issue by madjaqk** [miguelgrinberg/Flask-SocketIO#1555]
The traditional way to include additional parameters with a Socket.IO connection is with the `query` option, something like 
```js
const socket = io({
  query: {
    token: "abc"
  }
});
```
This attaches the items as query parameters on the connection URL, so they can be read with flask_socketio by looking at `request.args`.

However, query parameters can cause unexpected behavior with multiplexed connections (because the connection is recycled, the connection URL, and thus the query parameters, aren't updated).  To address this, Socket.io 3.x added an `auth` option for the connection function:
```js
const socket = io({
  auth: {
    token: "abc"
  }
});
```
Per the Socket.IO docs, `auth` values are sent in the `CONNECT` packet as opposed to the query parameters.  

Is there a way to read these `auth` values with flask_socketio?  My apologies if this is documented somewhere, but I haven't been able to find it.  Thank you!

[Socket.IO notes on the `auth` parameter](https://socket.io/docs/v3/migrating-from-2-x-to-3-0/#Add-a-clear-distinction-between-the-Manager-query-option-and-the-Socket-query-option)

**Comment by miguelgrinberg** [comment]
This change was implemented in the python-socketio package, which receives the `auth` argument in the connect handler function. But this change has not been implemented in Flask-SocketIO yet. I'll keep this issue open as a reminder to add it.
