### ISSUE TITLE
Server does not accept requests in dev mode using werkzeug/flask 1.1

### ISSUE THREAD

**Issue by diurnalist** [miguelgrinberg/Flask-SocketIO#1557]
**Describe the bug**
When using FLASK_ENV of development, which sets many debug flags in various other modules, Flask-SocketIO 5.0.2 and onwards do not accept requests. The server is reachable but the request just seems to hang without ever getting a response. No meaningful logs are outputted.

**To Reproduce**
1. Install flask 1.x, werkzeug 1.x, Flask-SocketIO 5.0.2, latest eventlet.
2. Run the [repro script](https://gist.github.com/diurnalist/51a585a1178b4c3675ba2c04e00f25ed) and try to navigate to the index page. It will never load.
3. Upgrading to flask 2.x, werkzeug 2.x fixes the issue.

**Expected behavior**
The server should serve requests when dev mode is enabled when using flask 1.x and werkzeug 1.x, as the package claims to support it in the metadata.

**Logs**
Not much to see here, even with engineio_logging on:

```
Server initialized for eventlet.
 * Restarting with stat
Server initialized for eventlet.
 * Debugger is active!
 * Debugger PIN: 448-077-307
(14885) wsgi starting up on http://127.0.0.1:5000
```

**Additional context**
The issue seems to be https://github.com/miguelgrinberg/Flask-SocketIO/commit/6563634e4c7836479ff5d38d20f4339e6bcf92ab, which is not compatible with werkzeug 1.x. It seems the _reloader implementation doesn't work well in werkzeug 1.x. Perhaps there can be some detection of which werkzeug version is in play, or this package just needs a stricter package dependency.

**Comment by miguelgrinberg** [comment]
@diurnalist I must be missing something, because the example app in this repo works just fine with the reloader enabled and eventlet, both with Flask/Werkzeug 1.x and 2.x. Do you want to share your code?

**Comment by diurnalist** [comment]
Hmm, I included a link to a gist I was using to test. I ran it as an
executable.

**Comment by miguelgrinberg** [comment]
Sorry, missed the link. You can't monkey patch in the middle of the script, that needs to be done at the very top, before all other imports. Moving the monkey patch line makes your script work for me.

**Comment by diurnalist** [comment]
Ah! Thank you. I did not experience the issue in the older version,
probably some luck with imports.
