### ISSUE TITLE
Emit to room from scheduled func

### ISSUE THREAD

**Issue by Donkere-vader** [miguelgrinberg/Flask-SocketIO#1558]
**Question**
In my program I have some devices that connect to the websocket. And I periodicly want to ping those devices, to see if they are online.

But when running ``socketio.emit("ping", room="device-room-name")`` in a scheduled function (using ``apscheduler``) the ping never reaches the device.

However if i run the same line in the main socket events file:

```py
@socketio.on("test")
@roomrequired
def on_test(data={}, room=None):
    socketio.emit("ping", room="device-room-name")
```

It does work.

TL;DR: how to emit to room from within function scheduled with ``apscheduler``

I hope I'm being clear. Any help would be appreciated :)

**Comment by miguelgrinberg** [comment]
Are you using eventlet or gevent? These frameworks are likely incompatible with the threads spawned by apscheduler.

**Comment by Donkere-vader** [comment]
Ah yes, I am. I alreadt thought it was probably threading that caused the issues.

A possible solution could be to do a GET request on for example the route ``/scheduled/1``

And have the setup like this:

scheduled function:
```py
def im_scheduled(minute_interval):
    requests.get(f"http://localhost:/scheduled/{minute_interval}")
```

Route
```py
@app.route("/scheduled/<minute_interval>")
def scheduled(minute_interval):
    ping_devices()
    return jsonify(succes=True)
```

That way the websocket stuff should happen in the "main" thread. 

However this feels kinda cheap/ not-clean. Do you might know a better solution? If not that's okay too than I'll just do it this way.

P.S. Thanks for responding to all the issues on here (from other people and this one) it helps a lot :)

**Comment by miguelgrinberg** [comment]
@Donkere-vader Well, the easiest solution is to not use eventlet/gevent. If that works for you, then it would require no changes to your code.

**Comment by Donkere-vader** [comment]
That fixed the issue! Thank u so much!
