### ISSUE TITLE
Various errors running cloned project

### ISSUE THREAD

**Issue by ibrido90** [miguelgrinberg/Flask-SocketIO#156]
Under Windows development, cloned your repo, created virtualenv with python 3.4 and run 
```
pip install -r requirements.txt
```
After that i run 
```
python app.py
```
and i got this errors
![errror_log_miguel](https://cloud.githubusercontent.com/assets/2493217/10539412/acc0874c-73ff-11e5-9874-f4c847c6af21.png)

**Comment by miguelgrinberg** [comment]
The current version of the extension is not compatible with Python 3, there is at least one dependency that hasn't been ported.

Release 1.0 of this extension will use a new set of dependencies and will be compatible with Python 3.4. If you want to try my current beta version, run `pip install flask-socketio==1.0b2".

**Comment by ibrido90** [comment]
Many thanks. Anyway I think it would be nice if you write a simple python client to connect to the server

**Comment by miguelgrinberg** [comment]
You will find a couple of Socket.IO clients implemented in Python, look them up on pypi. But there isn't really a good use case for that. A Python client can use a regular socket connection, no need to complicate things with WebSocket and Socket.IO.
