### ISSUE TITLE
simple-websocket not work

### ISSUE THREAD

**Issue by skysea04** [miguelgrinberg/Flask-SocketIO#1560]
### Here is my full app code
```
from flask import Flask, render_template, request, session, redirect, url_for
from flask_socketio import SocketIO, join_room, send


app = Flask(__name__)
app.config['SECRET_KEY'] = 'secretjsidfjsidfjsdifjsdifj!'
socketio = SocketIO(app)


@app.route('/')
def index():
    return render_template('index.html')

@socketio.on('message')
def handle_message(msg):
    print('get message:'+ msg)
    send(msg, broadcast=True)


if __name__ == "__main__":
    socketio.run(app)
```
When I run the server, it shows 
```
skysea@qiuyuxuandeAir flask-test % python3 app.py
WebSocket transport not available. Install simple-websocket for improved performance.
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
http://localhost:5000 is not an accepted origin. (further occurrences of this error will be logged with level INFO)
127.0.0.1 - - [28/May/2021 12:42:45] "GET /socket.io/?EIO=4&transport=polling&t=NcnI2J7 HTTP/1.1" 400 -
```

But I have installed simple-websocket

Here is my Flask-SocketIO information
```
skysea@qiuyuxuandeAir flask-test % pip3 show flask_socketio 
Name: Flask-SocketIO
Version: 5.0.3
Summary: Socket.IO integration for Flask applications
Home-page: http://github.com/miguelgrinberg/Flask-SocketIO/
Author: Miguel Grinberg
Author-email: miguelgrinberg50@gmail.com
License: MIT
Location: /opt/homebrew/lib/python3.9/site-packages
Requires: python-socketio, Flask
Required-by: 
```

Here is my simple-websocket information
```
skysea@qiuyuxuandeAir flask-test % pip3 show simple-websocket
Name: simple-websocket
Version: 0.2.0
Summary: Simple WebSocket server and client for Python
Home-page: https://github.com/miguelgrinberg/simple-websocket
Author: Miguel Grinberg
Author-email: miguel.grinberg@gmail.com
License: UNKNOWN
Location: /opt/homebrew/lib/python3.9/site-packages
Requires: wsproto
Required-by: 
```

I use Mac M1, how can I fix this problem?

**Comment by miguelgrinberg** [comment]
This is the problem, it is unrelated:

> http://localhost:5000 is not an accepted origin.

This is because the connection URL that you are using for Socket.IO does not match the URL of the page from where the connection is made. Maybe you are using `http://127.0.0.1:5000` on the page and `http://localhost:5000` on the Socket.IO connection? Use the same URL for both.

**Comment by skysea04** [comment]
thank you for helping

but now I get a new message
```
WebSocket transport not available. Install simple-websocket for improved performance.
 * Debugger is active!
 * Debugger PIN: 252-557-861
The WebSocket transport is not available, you must install a WebSocket server that is compatible with your async mode to enable it. See the documentation for details. (further occurrences of this error will be logged with level INFO)
```

I tried to install guicorn  ,eventlet and gevent , and try to change the commands write in https://flask-socketio.readthedocs.io/en/latest/deployment.html but the message still there, I want to ask how can I install a WebSocket server? and the simple-websocket still not work too.

**Comment by miguelgrinberg** [comment]
@skysea04 Please upgrade Flask-SocketIO to eliminate the message.

**Comment by skysea04** [comment]
Oh but I have installed the lastest version 5.0.3

**Comment by skysea04** [comment]
Sorry my mistake ,
But when I update to 5.1.0
message still the same

**Comment by miguelgrinberg** [comment]
At this point I really don't know what you are running and what message you refer to, since you have copied two of them above. You also mentioned several things that are mutually exclusive, including simple-websocket, gevent and eventlet.

So which websocket library do you want to use? Simple-websocket, eventlet or gevent? What error message do you get? What packages have you installed in your virtualenv?

**Comment by skysea04** [comment]
Finally I create a new virtualenv and use simple-websocket, it works!! no any warning message.
Maybe I have another package and interfere the simple-websocket library, thanks for your help!!
