### ISSUE TITLE
How to catch all messages sent to unregistered event handlers?

### ISSUE THREAD

**Issue by lazercorn** [miguelgrinberg/Flask-SocketIO#1564]
How may I catch all messages sent to unregistered event handlers? If a client sends an event to an unregistered event handler, I want that message to go to a default event handler that then handles the message. Is this possible?

**Comment by miguelgrinberg** [comment]
The only way is to use a class-based namespace, where you can override the `trigger_event()` method and handle unknown events.

**Comment by lazercorn** [comment]
Thanks, got it. 

Below is code to help out others. Example is catching all unknown events for '/' namespace.

```
class MyCustomNamespace(Namespace):
	def on_unknown_event(self, sid, data):
		#handle unknown event
		pass
	def trigger_event(self, event, *args):
		self.on_unknown_event(*args)
socketio.on_namespace(MyCustomNamespace('/'))
```
