### ISSUE TITLE
Can I get parameters from namespaces URL?

### ISSUE THREAD

**Issue by piderking** [miguelgrinberg/Flask-SocketIO#1567]
In flask you can do
```python 
@app.route(“/<param>“)
def parram(param):
   # do something

```
And I was wondering if you do something like
```python

@sio.on(“chat”, namespace=“/<chatname>“)
def chat(chatname):
   print(chatname)

```

**Comment by miguelgrinberg** [comment]
Not at this time. The namespace looks like a URL path, but it really isn't implemented that way, so it does not go through the Flask routing algorithm. It would be an interesting addition to do this, but right now it isn't possible.

**Comment by piderking** [comment]
Ok thanks for the response so fast!
