### ISSUE TITLE
does not working real time with kafka python

### ISSUE THREAD

**Issue by mainulquraishi** [miguelgrinberg/Flask-SocketIO#1569]
I am building a real-time app with flask-socketio and Kafka.  But the problem I am facing, the rate I am getting data from Kafka topic and the rate I am getting data at the front end are not equal. The front end is always lagging 4-5 seconds. For a realtime time scenario, this is not acceptable (at least in my use case).
Here is what I am doing: 

I have a nginx server as proxy webserver and a gunicorn server as app server. 

I am running the gunicorn like what suggested at the tutorial:
`gunicorn --worker-class eventlet -w 1 wsgi:app  `

The wsgi.py file:

```
from eventlet import monkey_patch;
monkey_patch()
from application import init_app
app,socketio = init_app()

```
In the application folder there is  a __init__.py file:

```
import eventlet
eventlet.monkey_patch(os=False, thread=False)
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from kafka import KafkaConsumer
from kafka import TopicPartition
from flask_socketio import SocketIO,emit,send
from eventlet import sleep
import os
from joblib import dump, load
import numpy as np
import json
from random import random

app = Flask(__name__)
socketio = SocketIO(app)


def init_app():
    applicationDir=os.path.abspath(os.path.join(os.path.dirname(__file__),".."))
    minmaxscaler = load(applicationDir+'/application/models/minmaxscaler.joblib')

    with app.app_context():
        from . import routes

    @socketio.on('connect', namespace='/test')
    def test_connect(auth):
        print('connected')
        send( {'data':"connected"})

    @socketio.on('my_event', namespace='/test')
    def test_message(message):
        Y=list()
        Y1=list()
        Y2=list()
        Y3=list()
        consumer = KafkaConsumer(
        bootstrap_servers=["kafka-server"],
        auto_offset_reset='latest',
        enable_auto_commit=True,
        api_version=(2, 0, 2),
        group_id='group9',
        fetch_max_wait_ms=5)
        tp0 = TopicPartition("xdk1", 0)
        tp1 = TopicPartition("xdk1", 1)
        consumer.assign([tp0, tp1])
        consumer.seek_to_end(tp0)
        consumer.seek_to_end(tp1)

        for m in consumer:
            message=m.value
            l=message.decode("utf-8").split('\n')
            l.pop()

            for i in l:
                temp = i.split(',')
                Y.append(float(temp[4]))
                Y1.append(int(temp[1]))
                Y2.append(int(temp[2]))
                Y3.append(int(temp[3]))
                y1,y2,y3,y=minmaxscaler.transform(np.array([Y1,Y2,Y3,Y]).T).T
                obj=json.dumps({"data":[y.tolist(),y1.tolist(),y2.tolist(),y3.tolist()]})
                emit('my_response', obj)
                print(obj)
    return app,socketio

```
For testing, at the front end, I am writing console.log() just after receiving the data.
 ```
socket.on('my_response', function(msg, cb) {
                        console.log(msg)
```
 now, When data streaming starts, I look at both the server console and browser console. I noticed that, when I turn off the data streams (from Kafka), the server console stops printing right away. but in the browser, still receiving data for another 5 - 6 seconds. 
The weird thing is even if I stop the sever in-between this 5-6 seconds, the browser shows that data is still receiving. 

To understand, I commented off the Kafka code and just sending some random fake stream. (but sending the same amount of data)

```
obj=json.dumps({"data":[ [random() for i in range(23)], [random() for i in range(23)], [random() for i in range(23)], [random() for i in range(23)]]})

for i in range(100) :   
    emit('my_response', obj)
    print(obj)
    sleep(.1)
```

This time, it is completely real-time. 

So, loading data from Kafka might not be a problem, because, the server already has the data (which is why it is printing and the print statement is under emit()). The server-side printing is real-time. Because it stops when I stop right away the data stream from kafka.

What might be the problem ?

**Comment by miguelgrinberg** [comment]
I'm really not very familiar with Kafka. The problem that you have is more an integration between Kafka and eventlet, and not so much about Flask-SocketIO. I suggest you try remove eventlet and see if that solves the problem. At least that will be confirmation that this is a problem between those two components.

**Comment by mainulquraishi** [comment]
I remove the following lines from both file (wsgi.py and __init__.py)
```
import eventlet
eventlet.monkey_patch()
```

resulted same behavior.

**Comment by miguelgrinberg** [comment]
Uninstall eventlet as well.

**Comment by mainulquraishi** [comment]
I uninstalled eventlet. now since there is no eventlet, I can not run by `gunicorn --worker-class eventlet -w 1 wsgi:app`. So i ran the code by `python` command with the development server. 

Now, the back end and the front end are in sync. Not behaving like above mentioned. This is understandable because, without eventlet this is running in sync mode. But as a side effect, if the data stream is fast (high rate frequency data coming into kafka-> kafka consumer sends it to front end via websocket), the kafka consumer is lagging behind. 

This is also strange, because,  data is coming to kafka at 5 Hz. frequency, so to **NOT** to lag behind, the emit() needs to send data to front end in <=200 millisecond and sending fake data sending at 10Hz just working fine (code mentioned above). 

**I am very confused about one thing: in the above code, i wrote print(obj) after emit(), then why, it is printing data but the same data is not reached to front end yet? and What it is to do with eventlet? **

**Comment by miguelgrinberg** [comment]
I asked you to uninstall eventlet as a test to determine if Kafka was having issues with it. I believe we have confirmed that this is the case? Then you can't use eventlet with Kafka, or you can ask in a Kafka or Eventlet place if someone knows how to make these two packages work together.

You can try gevent as an alternative to eventlet. You can also use Gunicorn without eventlet/gevent, as shown in the documentation, with the simple-websocket package to get WebSocket support.

**Comment by mainulquraishi** [comment]
Hi, So I solved the problem by optimizing the backend code. specifically after in the consumer loop, after getting data from Kafka. Since this is taking less time, it removes the lag. 

This is working even with eventlet. 
So, I guess no problem with eventlet with Kafka-python. 

Thanks

**Comment by miguelgrinberg** [comment]
Sounds, good. Thanks for the update!
