### ISSUE TITLE
Flask SocketIO horizontal scaling on heroku

### ISSUE THREAD

**Issue by Mister-Gee** [miguelgrinberg/Flask-SocketIO#1570]
@miguelgrinberg I have a flask socket-io app running on heroku and I'm trying to scale horizontally to 3 dynos but anytime I increase the dyno above 1, I get invalid session error but when I scale down, it starts to work again. Pls help. Thanks in advance

**Comment by bluthen** [comment]
I think you need sticky sessions or a method to communicate between dyno's to share sessions.
https://devcenter.heroku.com/articles/session-affinity

**Comment by Mister-Gee** [comment]
Thanks but i have tried but still got the same error

**Comment by miguelgrinberg** [comment]
@Mister-Gee what @bluthen said is correct. If you followed that advice and you still get the same error then you aren't doing it correctly. Since you are not providing any information regarding what you are trying exactly I don't think there is any more advice I can provide.

**Comment by Mister-Gee** [comment]
Ok, What im trying to build is a system that uses python selenium to scrape data from several website and return streams of data using base on the intial data sent by the client and this can be memory intensive so im trying to scale the program horizontally.
Heres part of my code:

`import eventlet
eventlet.monkey_patch()

import os
import sys
import time
from datetime import datetime
from flask import Flask, request
from selenium import webdriver
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait as wait
from selenium.common.exceptions import TimeoutException
from flask_socketio import SocketIO, disconnect, emit
from pymongo import MongoClient
import gc

app = Flask(__name__)
app.config['SECRET_KEY'] = "secret"
socketio = SocketIO(app,  logger=True, engineio_logger=True, ping_timeout=1200, ping_interval=5000, message_queue=os.environ.get(
        "REDISTOGO_URL"))

`
so the problem i have is anytime i increase my dyno, i get invalid session error, but when i scale it down it works perfectly so i did some research and found out i needed flask socketio needs sticky session to run multiple dynos, so i added affinity session but the problem still persist.

**Comment by bluthen** [comment]
Do the clients need to communicate with each other, or is it like client giving server payloads and server does its thing isolated? If the later maybe having the socketio clients use websocket only could solve your problem if the session affinity doesn't seem to be doing it. You also wouldn't need the message queue.

I don't have any experience with Heroku and don't know how it's load balancer works exactly.

**Comment by Mister-Gee** [comment]
The clients dont communicate with each other, the client just sends payload to the server.

**Comment by bluthen** [comment]
Ahh then easy, no need for message queue and you can set the client to only use websockets and not need to worry about session affinity then.

**Comment by miguelgrinberg** [comment]
Just to be clear about this, not using a message queue with multiple instances is not a supported deployment option. You are basically on your own if you do that. A number of things break when you drop the message queue so make sure you understand what you are losing if you decide to take that path.

**Comment by Mister-Gee** [comment]
Ok @miguelgrinberg what do you think the solution or what best way do you think i can tackle this problem?

**Comment by miguelgrinberg** [comment]
@Mister-Gee I'm not convinced that you are following the instructions for multiple workers correctly. If you want to generate logs for your dynos I can give you a more detailed opinion, but with the information that I have my guess is that this is an error on your part.

**Comment by Mister-Gee** [comment]
I have figured out the problem after going through the code again, i discovered that i went about the architecture in a wrong way, instead of having one web dyno that communicate with the other worker dyno, i had 3 web dynos trying to commicate with each other and from the docs, we can only have 1 instance of the the gunicorn web dyno.

Thanks @miguelgrinberg and @bluthen for your time.
