### ISSUE TITLE
Cannot get the examples to work JS Socket.IO 3.x

### ISSUE THREAD

**Issue by seandepagnier** [miguelgrinberg/Flask-SocketIO#1571]
only working  js socket.IO 2.x   I was hoping to get socket.IO 3.x to work.

Trying to run app_namespace.py example, nothing special.   using latest git of Flask-SocketIO as well as tried latest version of pip as well as git for python-socketio and python-engineio.   The site does not load or does not work correctly depending on the versions used.   With latest versions of everything it simply does not display anything on the site such as ping time or other messages, but they do appear in the logging output.

I cannot get the examples to work correctly until I roll back before:
"Move to python-socketio 4.x and JS Socket.IO 3.x"

As well I must install as:
sudo python3 -m pip install python-socketio==4.3.0
sudo python3 -m pip install python-engineio==3.13.2

**Comment by miguelgrinberg** [comment]
Did you notice in the issue template that you are required to post logs when you have a problem? Why didn't you do this?

**Comment by seandepagnier** [comment]
Hi, and sorry.   I thought it was very easy to reproduce.   I made the logs:
Flask==1.0.2
Flask-Babel==2.0.0
Flask-Login==0.4.1
Flask-Session==0.3.1
Flask-SocketIO==4.3.0
gevent==1.4.0
gevent-websocket==0.10.1
python-engineio==4.2.0
python-socketio==5.3.0
websocket-client==0.53.0
websockets==8.1


[flask_socketio_app_namespace_client.log](https://github.com/miguelgrinberg/Flask-SocketIO/files/6644126/flask_socketio_app_namespace_client.log)
[flask_socketio_app_namespace_server.log](https://github.com/miguelgrinberg/Flask-SocketIO/files/6644127/flask_socketio_app_namespace_server.log)

**Comment by miguelgrinberg** [comment]
Okay. The problem is that gevent has issues with the Flask reloader. I think removing `debug=True` in the last line will fix the problem. Alternatively, you can add the following two lines at the top of the script (above all other imports):

```python
from gevent import monkey
monkey.patch_all()
```

**Comment by seandepagnier** [comment]
I removed debug=True and the result is the same.

I then added the lines:
from gevent import monkey
monkey.patch_all()

to the top of app_namespace.py

The result is the same: it still does not work, no ping times etc.

**Comment by miguelgrinberg** [comment]
That is not what I see here. Would you care to generate a fresh set of logs?

**Comment by seandepagnier** [comment]
Sorry for the delay

These are the log without debug=True, and with the monkey patch.   I attached the app_namespace.py to avoid any ambiguity
It does not report ping times, or any other data to the javascript client.   I tried with firefox and chrome, x86_64 as well as armhf on raspberry pi, all with the same results.

[flask_socketio_app_namespace_client_2.log](https://github.com/miguelgrinberg/Flask-SocketIO/files/6664300/flask_socketio_app_namespace_client_2.log)
[flask_socketio_app_namespace_server_2.log](https://github.com/miguelgrinberg/Flask-SocketIO/files/6664302/flask_socketio_app_namespace_server_2.log)
[app_namespace.py.txt](https://github.com/miguelgrinberg/Flask-SocketIO/files/6664308/app_namespace.py.txt)

**Comment by miguelgrinberg** [comment]
@seandepagnier to have the complete picture I also need to see your index.html file.

**Comment by seandepagnier** [comment]
[index.html.txt](https://github.com/miguelgrinberg/Flask-SocketIO/files/6665479/index.html.txt)

When trying to execute app, I get:
~/Flask-SocketIO/example$ python3 app.py 
Traceback (most recent call last):
  File "app.py", line 34, in <module>
    @socketio.event
AttributeError: 'SocketIO' object has no attribute 'event'

I have python-socketio==5.3.0

**Comment by miguelgrinberg** [comment]
What version of Flask-SocketIO do you have? It's probably old.

**Comment by seandepagnier** [comment]
As far as I know it is the latest git commit.


sean@swift1:~/Flask-SocketIO$ git log | head -n 5
commit f9e1651a5328cf886f83ac3db20ece66dd2ab640
Author: Miguel Grinberg <miguel.grinberg@gmail.com>
Date:   Tue Jun 8 12:52:56 2021 +0100

    Fix documentation typo #nolog
sean@swift1:~/Flask-SocketIO$ git branch
* main

**Comment by miguelgrinberg** [comment]
The symbol that you get as undefined is defined [here](https://github.com/miguelgrinberg/Flask-SocketIO/blob/main/src/flask_socketio/__init__.py#L357). You can verify it yourself. I think you need to debug your environment because things aren't working as expected for you for some reason.

**Comment by seandepagnier** [comment]
Sorry for all the trouble.   There was a conflicting version and now all seems well.
