### ISSUE TITLE
The WebSocket transport is not available, you must install a WebSocket server

### ISSUE THREAD

**Issue by vikvikst** [miguelgrinberg/Flask-SocketIO#1573]
Hello!
I have a mistake: 

"The WebSocket transport is not available, you must install a WebSocket server that is compatible with your async mode to enable it. See the documentation for details. (further occurrences of this error will be logged with level INFO)"

Тhe messages(socket.on, socket.emit) work but the presence of the error saddens me. Please help me.

Environment:
1)The Flask development server based on Werkzeug
2) Package version:
    Flask-SocketIO==5.1.0
    python-engineio==4.2.0
    python-socketio==5.3.0
3)web  client socket.io.min.js(Socket.IO v4.1.2)
4)>>> flask.__version__ =     '1.1.2'

all package in virtual env(from pip freeze):
alembic==1.5.8
bidict==0.21.2
click==7.1.2
decorator==5.0.7
Flask==1.1.2
Flask-Login==0.5.0
Flask-Migrate==2.7.0
Flask-SocketIO==5.1.0
Flask-SQLAlchemy==2.5.1
Flask-WTF==0.14.3
greenlet==1.0.0
itsdangerous==1.1.0
Jinja2==2.11.3
lxml==4.6.3
Mako==1.1.4
MarkupSafe==1.1.1
python-dateutil==2.8.1
python-editor==1.0.4
python-engineio==4.2.0
python-socketio==5.3.0
self==2020.12.3
six==1.15.0
SQLAlchemy==1.4.4
Werkzeug==1.0.1
WTForms==2.3.3

console log:
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
The WebSocket transport is not available, you must install a WebSocket server that is compatible with your async mode to enable it. See the documentation for details. (further occurrences of this error will be logged with level INFO)
127.0.0.1 - - [18/Jun/2021 15:38:50] "GET /socket.io/?EIO=4&transport=polling&t=NeUHTIR HTTP/1.1" 200 -
127.0.0.1 - - [18/Jun/2021 15:38:50] "POST /socket.io/?EIO=4&transport=polling&t=NeUHTId&sid=jKL0xufN95-VbnJKAAAA HTTP/1.1" 200 -
127.0.0.1 - - [18/Jun/2021 15:38:50] "GET /socket.io/?EIO=4&transport=polling&t=NeUHTIe&sid=jKL0xufN95-VbnJKAAAA HTTP/1.1" 200 -
127.0.0.1 - - [18/Jun/2021 15:38:50] "POST /socket.io/?EIO=4&transport=polling&t=NeUHTIz&sid=jKL0xufN95-VbnJKAAAA HTTP/1.1" 200 -
127.0.0.1 - - [18/Jun/2021 15:38:50] "GET /socket.io/?EIO=4&transport=polling&t=NeUHTIz.0&sid=jKL0xufN95-VbnJKAAAA HTTP/1.1" 200 -

This is all good except for the first line.

**Comment by miguelgrinberg** [comment]
The error is correct. You must install a websocket server. This package does not provide one, you have to install it and then this package will use it. This is all in the documentation, but if you want the short version, try installing `simple-websocket`.

**Comment by vikvikst** [comment]
Thank you!

**Comment by yeungsk** [comment]
Hi, I have installed the `eventlet` according to the document, but I still got the same error.
```
The WebSocket transport is not available, you must install a WebSocket server that is compatible with your async mode to enable it. See the documentation for details. (further occurrences of this error will be logged with level INFO)
```

My environment:
* Flask              1.1.2
* python-socketio    5.5.0
* Flask-SocketIO     5.1.1
* eventlet           0.33.0
* js Socket.IO            4.4.0

**Comment by miguelgrinberg** [comment]
@yeungsk did you see the part that reads *that is compatible with your async mode*? Any chance eventlet is not the async mode you are using?

**Comment by n1lby73** [comment]
> but if you want the short version, try installing `simple-websocket`.

do i need to install this when i have flask_socketio installed already

**Comment by miguelgrinberg** [comment]
@n1lby73 the order of installation does not matter

**Comment by n1lby73** [comment]
> @yeungsk did you see the part that reads _"that is compatible with your async mode"_? Any chance eventlet is not the async mode you are using?

how do i know if eventlet is not the async mode i'm using
