### ISSUE TITLE
Using a callback from a background process

### ISSUE THREAD

**Issue by theahura** [miguelgrinberg/Flask-SocketIO#1576]
**Your question**
Hey Miguel, thanks for this great library.

I'm using flask SocketIO with eventlet. I have a socket handler that runs a long computation (training some models from scikit learn, for e.g.). I'd like to be able to get/respond to other Flask calls and other Flask SocketIO calls while the long computation is running. I can't easily call socketio.sleep(0) in the middle of this long computation, because afaik scikit does not allow you to add hooks like that.

After digging around on StackOverflow ([eg](https://stackoverflow.com/questions/39528730/flask-socketio-misses-events-while-copying-file-in-background-thread)) it looks like the right way to handle this is to spin off another thread or subprocess. However, I would like to still 'return' once the computation is done in such a way that the frontend can utilize acknowledgement callbacks.

I'm a bit confused exactly how to do this.

1) How does all of this interact with socketio.start_background_task()? Should I be running the long computation with that function as a wrapper? Do I need to use eventlet.monkey_patch() if I use start_background_task()?

2) What is the right way to actually utilize the callback from inside a background process (or subprocess or thread)? I don't mean 'start the background process and immediately return', nor do I mean 'return a different event that the client can listen for'; rather, I mean 'return the results of the long computation to the client through the acknowledgement callback'.

3) It seems like the long running computation blocks requests made to normal Flask endpoints (those that don't use the socket). However, this seems odd to me -- I think of traditional HTTP requests and WS as two different pipes. Am I misunderstanding something about how these two pieces interact?

Thanks again!

**Logs**
NA

**Comment by miguelgrinberg** [comment]
Answers to your questions:

1. When using eventlet, `start_background_task` starts a greenlet, not a thread. So this is not going to solve your problem. Even if you manage to start a real thread, I'm not sure it is going to be enough because of the global interpreter lock. The best option that you have is to offload the CPU work to a sub-process.

2. The acknowledgement callbacks are intended to be used to signal that an event handler completed. If you need to send signals to the front end that are not related to the completion of an event handler, then use an `emit` call.

3. The CPU task cannot be in the same process as the eventlet server. If you move that to another process then your Eventlet server is not going to block.

**Comment by theahura** [comment]
Following up on number 2, is there a way to signal that the event handler has completed from a subprocess?

Or perhaps a way to wait for a subprocess to return a value to the event handler so that the event handler can use 'return' semantics?

**Comment by miguelgrinberg** [comment]
> Following up on number 2, is there a way to signal that the event handler has completed from a subprocess?

This isn't really a question that makes sense. The callback triggers when the event handler ends. You can't manually trigger the callback to run. And wether you use sub-processes is unrelated. All you need to do to send a callback, is return from your event handler function.

> Or perhaps a way to wait for a subprocess to return a value to the event handler so that the event handler can use 'return' semantics?

You can do whatever you want in the event handler. If you want to start a child process and block until it returns I guess you can. Seems like a strange way to use callbacks, but there are no rules against it.

**Comment by theahura** [comment]
Thanks for the really fast followup! I'll close this out.
