### ISSUE TITLE
How to create a database connection for each thread

### ISSUE THREAD

**Issue by MathiasDrapier** [miguelgrinberg/Flask-SocketIO#1577]
Hello,
I am using flaskSocketIo for my api backend.
 Each of my endpoint calls several postgresql database request, I have a permanently open connection with my database.
 Each time a request is called, the program waits until the connection is available to carry out its transaction.
When I call 1000 simultaneous endpoint I get very long response times.
I think each enventlet thread would have to create its own connection to the database but I don't know how to do that.
I tried to create a new connection for each endpoint call but this also created very long response times

**Comment by miguelgrinberg** [comment]
This extension knows nothing of your database and how connections are created. This depends on the database library that you use.

**Comment by MathiasDrapier** [comment]
Thanks for your answer, I use psycopg2

**Comment by miguelgrinberg** [comment]
I can't still answer your question. As I said, this library is not concerned with databases. If you are using eventlet or gevent make sure your postgres library is patched so that it becomes non-blocking. Other than that I have no advice to give you, you have to manage your database connections directly from your application. Flask-SocketIO is not going to interfere with that.

**Comment by MathiasDrapier** [comment]
I have an executeRequest method which is called whenever I want to query the database.
I would like to be able to have an open connection for each greenlet and in this method I could choose the right connection depending on the greenlet that calls this method.
I don't know if this is possible, I use eventlet

**Comment by miguelgrinberg** [comment]
I do not use psycopg2 so I can't answer your question. As I said before, this library does not prevent you from doing that.

**Comment by MathiasDrapier** [comment]
Ok thank you for your reply.
