### ISSUE TITLE
Questions about the process

### ISSUE THREAD

**Issue by dayhappy2012** [miguelgrinberg/Flask-SocketIO#1578]
The present environment:

docker + nginx (ip_hash) + gunicorn -w 1 + eventlet

Now can I use the following two methods?

1. from multiprocessing import Process
2. from threading import Thread

**Comment by dayhappy2012** [comment]
One more question, how do I count the online numbers? How to count the number of rooms?

**Comment by miguelgrinberg** [comment]
Questions 1 and 2 apply to eventlet, not to this package. I'm not sure if multiprocessing works under eventlet, probably not. The threading module works only if you monkey patch the standard library (which I believe gunicorn does by default).

To count number of users add a counter in your connect and disconnect handlers. If you have multiple workers, then the counter needs to be across instances, so you may need to use something like Redis for it.

To count the number of rooms your application needs to keep track of them. This package does not manage a global list of rooms.

**Comment by dayhappy2012** [comment]
thanks, I close the Questions
