### ISSUE TITLE
simple-websocket need 'werkzeug.socket' in environ

### ISSUE THREAD

**Issue by Leonard-sc** [miguelgrinberg/Flask-SocketIO#1579]
**question**
im using the simple-websocket package. This package require 'werkzeug.socket' in environ when using the Flask dev server
But in my environment, the Flask dev server does not have 'werkzeug.socket' in environ,So it throws:
```
File "/Users/user/venv/lib/python3.7/site-packages/simple_websocket/ws.py", line 138, in __init__
    raise RuntimeError('Cannot obtain socket from WSGI environment.')
RuntimeError: Cannot obtain socket from WSGI environment.
```
How to solve this problem?

**Comment by Leonard-sc** [comment]
After I upgraded Flask to version 2+（werkzug to version 2+ too）, everything was fine

**Comment by miguelgrinberg** [comment]
That's correct. Flask 2 and Werkzeug 2 are required to use simple-websocket.
