### ISSUE TITLE
sqlalchemy.orm.exc.DetachedInstanceError in unit test with socketio.test_client

### ISSUE THREAD

**Issue by LostInDarkMath** [miguelgrinberg/Flask-SocketIO#1582]
**Describe the bug**
I just included `Flask-SocketIO` in my project which is based on `Flask-SQLAlchemy` and wrote some tests. But I in a simple test I get the following error:
```
sqlalchemy.orm.exc.DetachedInstanceError: Instance <User at 0x2812f970> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: http://sqlalche.me/e/14/bhk3)
```
The error causing test can be reduced to the following:
```python
def test_receive_notifications_on_new_message_via_websockets(self) -> None:
    socketio_client = self.socketio.test_client(app=self.app, flask_test_client=self.client, headers=self.header())
    self._send_message(sender=self.dummy2, receiver=self.dummy)  # it fails here
```
If I comment out the the first line that creates the socketio test client, the errors does not appear. This is quite strange because I have no idea why the creation of socketio test client can lead to detached instances.
Do you have any idea whats going on here?

The dummy users `self.dummy` and `self.dummy2` are Wrappers for an ORM user class. The instances are created inside the `setup()` of the parent test class. I use them in almost any of my 300+ tests and I never had any problems before.

I hope you can help me here.
 
**Additional context**
I do not think that I use `Flask-SocketIO` wrong because if I start the server and my client everything works perfectly fine. Additionally, my other simple socketio tests also work perfectly:
```python
    def test_establish_websocket_connection_without_credentials(self) -> None:
        socketio_client = self.socketio.test_client(app=self.app, flask_test_client=self.client)
        self.assertFalse(socketio_client.is_connected())

    def test_establish_websocket_connection_successful_and_receive_initial_data(self) -> None:
        socketio_client = self.socketio.test_client(app=self.app, flask_test_client=self.client, headers=self.header())
        self.assertTrue(socketio_client.is_connected())
        res_list = socketio_client.get_received()
        self.assertEqual(1, len(res_list))
        # more assertions here
```

**Comment by miguelgrinberg** [comment]
Two important things are missing:

1. the complete stack trace of the error
2. the code that fails, which I assume is the `_send_message()` method of your unit test class?
