### ISSUE TITLE
SocketIO Import Error

### ISSUE THREAD

**Issue by schwaby** [miguelgrinberg/Flask-SocketIO#161]
I just upgraded from version 0.6 to 1.0b4 and I can't seem to figure out why I am getting this error:
>
...
lib/python2.7/site-packages/Flask_SocketIO-1.0b4-py2.7.egg/flask_socketio/__init__.py", line 11, in <module>
    class _SocketIOMiddleware(socketio.Middleware):
AttributeError: 'module' object has no attribute 'Middleware'

I am importing SocketIO like this:
```python
from flask_socketio import SocketIO
```

I am running Python 2.7.3 in a virtualenv with the following packages installed:
Flask (0.10.1)
Flask-SocketIO (1.0b4)
gevent (1.1b6)
gevent-socketio (0.3.6)
gevent-websocket (0.9.5)
greenlet (0.4.9)
itsdangerous (0.24)
Jinja2 (2.8)
MarkupSafe (0.23)
ModestMaps (1.4.6)
Pillow (3.0.0)
pip (6.1.1)
setuptools (15.0)
simplejson (3.8.0)
six (1.10.0)
Werkzeug (0.10.4)

Any help would be appreciated.
Thanks

**Comment by miguelgrinberg** [comment]
Run `pip uninstall gevent-socketio`, then try again. Let me know if you still get the error.

**Comment by schwaby** [comment]
It looks like my project had a requirement to pull in gevent-socketio and that was causing a conflict - thanks for the information.
