### ISSUE TITLE
Unable to connect to flask-socketio server on Heroku

### ISSUE THREAD

**Issue by thebowenfeng** [miguelgrinberg/Flask-SocketIO#1626]
**Description**
I have a website hosted on heroku, which utilizes flask-socketio. I have a frontend website attempting to connect to the backend socketio using javascript. Code as follows:

`var socket = io.connect(window.location.protocol + '//' + document.domain + ':' + location.port + '/web', {
      transports: ['websocket']
    });

    socket.on('connect', () => {
      console.log('Connected');
      socket.emit('join', "{{username}}")
    });

    socket.on('disconnect', () => {
      console.log('Disconnected');
      socket.emit('leave', "{{username}}")
    });

    socket.on('connect_error', (error) => {
      console.log('Connect error! ' + error);
    });

    socket.on('connect_timeout', (error) => {
      console.log('Connect timeout! ' + error);
    });

    socket.on('error', (error) => {
      console.log('Error! ' + error);
    });`

My socketIO app is fairly standard.

However, my frontend refuses to connect for some reason, even though it works fine when locally hosted. The error I get is "connection timed out". 

The log on heroku is:` 2021-07-07T06:14:10.380908+00:00 heroku[router]: at=info method=GET path="/socket.io/?EIO=3&transport=websocket" host=livestreaming-server.herokuapp.com request_id=8b70bda0-b47a-493c-9df2-a4418ea71ab3 fwd="101.100.129.133" dyno=web.1 connect=1ms service=2ms status=101 bytes=129 protocol=https`

and

`https://livestreaming-server.herokuapp.com is not an accepted origin.`

**Comment by miguelgrinberg** [comment]
The log is telling exactly what the problem is:

> https://livestreaming-server.herokuapp.com is not an accepted origin.

Have you configured this origin as allowed in your server? If you don't know what this is, please read the cross-origin section of the documentation: https://flask-socketio.readthedocs.io/en/latest/deployment.html#cross-origin-controls.
