### ISSUE TITLE
socket.io polling result is 404 not found

### ISSUE THREAD

**Issue by dragonchoi** [miguelgrinberg/Flask-SocketIO#166]
i'm developing notification server with Flask-Socket.io and gunicorn, nginx.

but when i deploy my server, polling result is 404 not found in client like below.

GET http://myserver.cloudapp.net/socket.io/?EIO=3&transport=polling&t=1446389818036-416 404 (NOT FOUND)

i was trying to resolve this issue during two days...
i feel like this is not hard issue.. but i couldn't resolve because i'm beginner in flask + gunicorn + nginx
so could i ask some your help?

my nginx configuration is

server {
    listen 80;
    server_name localhost;  #or myserver.cloudapp.net
    access_log /var/log/nginx/my-server-app.log;

    location /socket.io {
        proxy_pass http://127.0.0.1:8000/socket.io;
        proxy_redirect off;
        proxy_buffering off;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_redirect off;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

and execute gunicorn via upstart like below
(/etc/init/myproject.conf)

start on startup
chdir /home/dragonchoi/webserver_test
exec gunicorn --worker-class eventlet runserver:app

OS : Ubuntu 14.04.2 LTS

thanks

**Comment by miguelgrinberg** [comment]
First of all, check that you have a version of ngnix that is 1.4 or newer. Older versions of nginx do not support websocket.

Next you need to determine if the 404 is generated by nginx of by gunicorn. You may want to add a gunicorn logfile, so that you can check if the requests for socket.io are getting there.

You may also want to test gunicorn without nginx, to confirm that the socket.io protocol is working.

**Comment by dragonchoi** [comment]
i'm using MS azure(cloud) linux vm.

when i just run my module like below, it works
python runserver.py

but it doesn't work in nginx + gunicorn + upstart
this is nginx access log ( 404 not found was occured )
nginx version is 1.8

110.11.34.9 - - [09/Nov/2015:15:53:46 +0000] "GET /socket.io/?EIO=3&transport=polling&t=1447084428022-128 HTTP/1.1" 404 233 "http://server.cloudapp.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36"

this is python log. 
maybe reverse proxy configuration is correct.

[2015-11-09 15:52:49 +0000] [15684] [INFO] Starting gunicorn 19.3.0
[2015-11-09 15:52:49 +0000] [15684] [INFO] Listening at: http://127.0.0.1:8000 (15684)
[2015-11-09 15:52:49 +0000] [15684] [INFO] Using worker: eventlet
[2015-11-09 15:52:49 +0000] [15690] [INFO] Booting worker with pid: 15690
============Request Header===============
Referer: http://server.cloudapp.net/^M
X-Real-Ip: 110.11.34.9^M
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36^M
Connection: Upgrade^M
Cookie: io=cab88ef9f89b49a7883b2204fcd3ff2e; fbsr_1669537499999309=byZxbwBJTTC1CWRGe3FCoskDCVQqHBNTl9cVLcOCk1A.eyJhbGdvcml0aG0iOiJITUFDLVNIQTI1NiIsImNvZGUiOiJBUUJiNHNxZWdHZHBvVEtLUllNU1AzdlpBQ0xuUzFNcG00bEc4ZGlTZjd5YXRfUFdzQTlEd04zVjJsYkxOYWhRZWFvOWJLNkV3bXY5VFdNOE1qOURLMTRuV3FlcmJQMzVFVUJlODFRRnRMWHJNTUliME9NVDR1dFFSNWZnamZXdzBtbk9oSlZBV2stcW9EQzNLM19QbDhTdktQUkdhY3VvWDl0aE5rVWJ0emhac3BUbnBxR2FiMEVQWHRhV2JUWnNMNnJOalZOcGhJZ0xkclZiclR1RHBxcGRyRWZhU3pXQXZrOW1jMnJ1SnpmZ3lVOWkySnRlWUlrQkxzTHZhQWc0NzVJXy1MUFh3SU5WVTQzcG96Y1I2X3puZ0YtZzJad0Vrck1aaHZ0NWlzXzA1M2VkUW9hTlFNZTZxMnVoUXdkX2xieVE5cF9xRENLazJucG9kZDAzalhJeCIsImlzc3VlZF9hdCI6MTQ0NzA4MzU1MiwidXNlcl9pZCI6Ijc3NTg4NzU1NTg1MzI4MCJ9; session=eyJfaWQiOnsiIGIiOiJZVEJoTnpaa1kyVmlOMkV6TURsalpEWXdZV1psTkdOaU5qTmxNbUl5WmpJPSJ9LCJwb3N0X29hdXRoX2xvZ2luX3VybCI6eyIgYiI6Ikx3PT0ifX0.CSJTAg.KfuZRp4YfvOePi0iEydkCHkIbDc^M
Host: server.cloudapp.net^M
Accept: */*^M
Accept-Language: ko-KR,ko;q=0.8,en-US;q=0.6,en;q=0.4^M
X-Forwarded-For: 110.11.34.9^M
Accept-Encoding: gzip, deflate, sdch^M

============  Request URL ===============
http://server.cloudapp.net/socket.io/?EIO=3&transport=polling&t=1447084428022-128


my last nginx configuration

server {
    listen 80;
    server_name server.cloudapp.net;
    access_log /var/log/nginx/server-app.log;

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_redirect off;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /socket.io {
        proxy_pass http://127.0.0.1:8000/socket.io;
        proxy_redirect off;
        proxy_buffering off;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }
}

i still can't find this cause of the problem...

**Comment by miguelgrinberg** [comment]
Please remove gevent, gevent-websocket and gevent-socketio and try again. You are using eventlet, so you don't need those, and gevent-socketio in particular might be causing an unintended collision with package python-socketio.

**Comment by dhhagan** [comment]
I also receive nearly the same error once I try going to production from local dev...thus I assume it is something with the config file? I am trying to use Gunicorn with eventlet and nginx (v1.9). It works great on the production server if I launch from the terminal using:

    >>> gunicorn --worker-class eventlet --bind 0.0.0.0:8000 wsgi:app

However, with the following config file...I receive nothing but 400 Bad Request errors..it is also trying to fall back on polling?

Config:

    exec gunicorn --workers 3 --worker-class eventlet --bind 0.0.0.0:8000 wsgi:app


/sites-available/sockets 

    server {
        listen 80;
        server_name 'server-name';
        access_log /var/log/nginx/example.log;

        location / {
            proxy_pass http://127.0.0.1:8000;
            proxy_redirect off;
            proxy_read_timeout 600;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /socket.io {
            proxy_pass http://127.0.0.1:8000/socket.io;
            proxy_redirect off;
            proxy_buffering off;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }

What can I look for that would be causing the issue only when I move to production and running through nginx?

**Comment by miguelgrinberg** [comment]
Probably not the main issue, but note that you can't use multiple gunicorn workers for serving socket.io, so remove the `--workers 3`. Also you do not need to listen on `0.0.0.0`, doing `127.0.0.1` is enough when nginx is in front.

Regarding the 400 errors, I think it would be useful if you can identify who is putting those out. Is it nginx responding with 400, or are the requests getting through to the application? If you enable logging on nginx and your application you should be able to figure out which layer is the one producing the errors.

**Comment by dhhagan** [comment]
It appears that that removing the additional workers fixed the issue. I didn't realize that would break it!

**Comment by miguelgrinberg** [comment]
On second thought, the load balancer in gunicorn is not very flexible, so requests from a client could randomly get assigned to different workers, and this is likely what broke the Socket.IO polling protocol.

**Comment by sivasivacsc** [comment]
@miguelgrinberg I just Clone this repo in my aws ec2 instance after that i run a example file app.py using python3 
**This is My Nginx Configuration** 
`	location /api/{

		proxy_pass         http://127.0.0.1:5000/;
		proxy_redirect     off;
		proxy_set_header   Host             $host;
		proxy_set_header   X-Real-IP        $remote_addr;
		proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
	}
	location /socket.io/{
		proxy_pass	http://127.0.0.1:5000/socket.io;
		proxy_http_version 1.1;
                proxy_redirect     off;
                proxy_set_header   Host             $host;
                proxy_set_header   X-Real-IP        $remote_addr;
                proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
        }`
**Error Log**
`sivaravi@ip-172-31-20-216:/tmp/Flask-socketio/example$ python3 app.py 
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 316-398-610
(23773) wsgi starting up on http://127.0.0.1:5000
(23773) accepted ('127.0.0.1', 52700)
45.251.33.11,127.0.0.1 - - [14/Mar/2017 11:51:47] "GET / HTTP/1.0" 200 6023 0.006306
(23773) accepted ('127.0.0.1', 52701)
45.251.33.11,127.0.0.1 - - [14/Mar/2017 11:51:48] "GET /socket.io?EIO=3&transport=polling&t=1489492304904-0 HTTP/1.1" 404 342 0.000959
(23773) accepted ('127.0.0.1', 52702)
45.251.33.11,127.0.0.1 - - [14/Mar/2017 11:51:49] "GET /socket.io?EIO=3&transport=polling&t=1489492306103-1 HTTP/1.1" 404 342 0.000935
(23773) accepted ('127.0.0.1', 52703)
45.251.33.11,127.0.0.1 - - [14/Mar/2017 11:51:50] "GET /socket.io?EIO=3&transport=polling&t=1489492307297-2 HTTP/1.1" 404 342 0.000977
(23773) accepted ('127.0.0.1', 52704)
45.251.33.11,127.0.0.1 - - [14/Mar/2017 11:51:54] "GET /socket.io?EIO=3&transport=polling&t=1489492311245-3 HTTP/1.1" 404 342 0.002287
(23773) accepted ('127.0.0.1', 52705)
45.251.33.11,127.0.0.1 - - [14/Mar/2017 11:51:59] "GET /socket.io?EIO=3&transport=polling&t=1489492315870-4 HTTP/1.1" 404 342 0.000919
(23773) accepted ('127.0.0.1', 52706)
45.251.33.11,127.0.0.1 - - [14/Mar/2017 11:52:04] "GET /socket.io?EIO=3&transport=polling&t=1489492320905-5 HTTP/1.1" 404 342 0.000912
(23773) accepted ('127.0.0.1', 52707)
45.251.33.11,127.0.0.1 - - [14/Mar/2017 11:52:09] "GET /socket.io?EIO=3&transport=polling&t=1489492326030-6 HTTP/1.1" 404 342 0.001018
(23773) accepted ('127.0.0.1', 52708)
45.251.33.11,127.0.0.1 - - [14/Mar/2017 11:52:14] "GET /socket.io?EIO=3&transport=polling&t=1489492331066-7 HTTP/1.1" 404 342 0.000964
`
**Pip freeze**
`ChatterBot==0.5.3
CouchDB==1.1
Flask==0.12
Flask-Cors==3.0.2
Flask-CouchDB==0.2.1
Flask-Login==0.3.2
Flask-Mail==0.9.1
Flask-OAuthlib==0.9.3
Flask-SocketIO==2.8.4
Jinja2==2.9.5
MarkupSafe==0.23
Werkzeug==0.11.15
appdirs==1.4.0
blinker==1.4
chardet==2.2.1
click==6.7
colorama==0.2.5
command-not-found==0.3
enum-compat==0.0.2
enum34==1.1.6
eventlet==0.20.1
future==0.16.0
gevent==1.2.1
greenlet==0.4.12
gunicorn==19.7.0
html5lib==0.999
itsdangerous==0.24
jsondatabase==0.1.7
language-selector==0.1
nltk==3.2.2
numpy==1.12.0
oauthlib==2.0.1
packaging==16.8
pandas==0.19.2
pycurl==7.19.3
pygobject==3.12.0
pymongo==3.4.0
pyparsing==2.1.10
python-apt==0.9.3.5ubuntu2
python-dateutil==2.6.0
python-engineio==1.3.0
python-socketio==1.7.2
python-twitter==3.2.1
pytz==2016.10
rauth==0.7.3
requests==2.2.1
requests-oauthlib==0.8.0
six==1.10.0
ufw==0.34-rc-0ubuntu2
unattended-upgrades==0.1
urllib3==1.7.1
validate-email==1.3
wheel==0.24.0
xmltodict==0.10.2
`
in App.py File i just edited the **async_mode = "gevent"** after that just run `gunicorn -k gevent -w 1 app:app`

**Comment by iChigozirim** [comment]
7 years later and I'm facing the exact problem @dragonchoi shared above.
Please help! I've been on this for over a week now.

**Comment by kaijaz123** [comment]
@cgzirim hey do you manage to solve this?

**Comment by cgzirim** [comment]
@kaijaz123, unfortunately, no.
I gave up trying and directly connected the client to the server using the IP address and the port socket.io was running on.

**Comment by cgzirim** [comment]
@kaijaz123, unfortunately, no.
I gave up trying and directly connected the client to the server using the IP address and the port socket.io was running on.

**Comment by kaijaz123** [comment]
@cgzirim Hi there, I finally figured out where the problem was. This might be only specific to my case, but hopefully it will give you some insight.

The nginx web server is on my ec2 which the ec2 instance is behind the CloudFront service. So the 404 not found is due to the behavior configuration under the ec2 path routing. I didn't have the path pattern configured for` /socket.io/*` for my ec2, hence it can't be found and throw the 404 not found error.

Solution is just simply add the `/socket.io/*` to the path pattern and thats it.

**Comment by cgzirim** [comment]
@kaijaz123 thank you for sharing 🫶.
