### ISSUE TITLE
Add blueprint support for websockets

### ISSUE THREAD

**Issue by adamlwgriffiths** [miguelgrinberg/Flask-SocketIO#1674]
**Is your feature request related to a problem? Please describe.**
Blueprints allow the routing/view to be decoupled from the application creation.
This makes code more modular.

[flask-sockets](https://github.com/heroku-python/flask-sockets) has blueprint support (see the example in the README), it should be possible to add blueprints to this.

**Describe the solution you'd like**

Flask-sockets blueprints work just like flask ones (using the example as a base)
```

from flask import Blueprint
from flask_socketio import SocketIO

app = Flask(__name__)
socketio = SocketIO(app, async_mode=None)

ws = Blueprint('ws', __name__)

# there may be a better functions or more options that are usable here
@ws.route('my_event')
def my_event(message):
    print(f'my_event({message})')
    session['receive_count'] = session.get('receive_count', 0) + 1
    emit('my_response',
         {'data': message['data'], 'count': session['receive_count']})

socketio.register_blueprint(ws)
```

**Additional context**

I've knocked up a quick-and-dirty implementation using flask-sockets as a base:
```
class SocketIO_BP(SocketIO):
    def __init__(self, *args, **kwargs):
        self.blueprints = {}
        self._blueprint_order = []
        super(SocketIO_BP, self).__init__(*args, **kwargs)

    def add_url_rule(self, rule, _, f, **options):
        self.on(rule, options.get('namespace'))(f)

    def register_blueprint(self, blueprint, **options):
        assert blueprint.name not in self.blueprints, f'A blueprint with the name {blueprint.name} is already registered'
        self.blueprints[blueprint.name] = blueprint
        self._blueprint_order.append(blueprint)

        blueprint.register(self, options)
```

```
app = Flask(__name__)
socketio = SocketIO_BP(app, async_mode=async_mode)

ws = Blueprint('ws', __name__)

#@socketio.event
@ws.route('my_event')
def my_event(message):
    print(f'my_event({message})')
    session['receive_count'] = session.get('receive_count', 0) + 1
    emit('my_response',
         {'data': message['data'], 'count': session['receive_count']})

socketio.register_blueprint(ws)
```

Using this, the existing demo still works and I can see the "my_event(message)" print out when called by the client.

**Comment by miguelgrinberg** [comment]
Sorry, but I don't understand what is the benefit of doing this. Flask-Sockets is a WebSocket extension, Flask-SocketIO is not. If you want to put some Socket.IO events in a blueprint, just put them there. Nothing prevents you from organizing your Socket.IO events however you like.

**Comment by adamlwgriffiths** [comment]
> Sorry, but I don't understand what is the benefit of doing this. 

The concept is exactly the same as flask's blueprints, Ie. [decoupling view from the application instance](https://exploreflask.com/en/latest/blueprints.html#why-would-you-use-blueprints).

Having code constantly reach back into an 'app.py' file to access some global instance is an anti-pattern, and global variables doubly so.

With the existing method, the flask app / socketio instance are created, then the views are imported, which then have to reach _back_ to the app instance to register themselves. It's not only cyclical but creates unnecessary coupling.

Blueprints are self-contained, only existing within the module they are defined in.
The app creation then registers any blueprints its interested in, and can mount them to an endpoint of its choosing.
The coupling between the app instance and view is reduced.

> Flask-Sockets is a WebSocket extension, Flask-SocketIO is not. If you want to put some Socket.IO events in a blueprint, just put them there. Nothing prevents you from organizing your Socket.IO events however you like.

I'm not quite sure what you mean by this, I still need to write glue code for this to work.
The concept of blueprints is _exactly_ so I can organise my events however I like.

> In case this isn't clear, you do not need to have an `app` instance to create Socket.IO events, so your `socketio` instance works exactly like a blueprint, in that it allows you create handlers in an application that uses the create_app factory pattern.

I would say that works exactly the opposite of a blueprint and exactly like the Flask 'app' instance.
They're still global instances which the views have to reach back to register themselves.

A blueprint is defined in the module the views are defined in. The view then doesn't have to reach back to the central app instance.
The views then become modular / self-contained.

**Comment by miguelgrinberg** [comment]
> The concept is exactly the same as flask's blueprints, Ie. decoupling view from the application instance.

That's exactly why I don't understand. To create a Socket.IO endpoint you do not need to have an application instance.

> With the existing method, the flask app / socketio instance are created, then the views are imported, which then have to reach back to the app instance to register themselves. It's not only cyclical but creates unnecessary coupling.

You can create the `SocketIO` instance in the place you define your event handlers (without passing any arguments to it), and then from inside your create_app function you import this instance and call `init_app` on it to attach it to the app.

What I'm saying is that the `SocketIO` object can be used exactly like blueprints are used if that's what you like.

**Comment by adamlwgriffiths** [comment]
Ok I'm starting to see what you mean.
So it sounds like the following is valid?

view1.py / view2.py
```
socketio = flask_socketio.SocketIO()

@socketio.on('joined', namespace='/chat')
def joined(message):
    ...
```

app.py
```
import view1, view2
app = Flask(__name__)
view1.socketio.init_app(app)
view2.socketio.init_app(app)
```

**Comment by miguelgrinberg** [comment]
Yes, but with the exception that you can use only one `SocketIO` object, not many.

**Comment by adamlwgriffiths** [comment]
Yep, so it comes back to the original problem, without blueprints you need god instances.

**Comment by adamlwgriffiths** [comment]
Ok, thanks for explaining the alternatives.
I'll look into making a separate repo for it, as I'm sure someone will find it handy.
