### ISSUE TITLE
sometimes, it takes really very long time to connect on heroku

### ISSUE THREAD

**Issue by small-yellow-rice** [miguelgrinberg/Flask-SocketIO#171]
After I deploy  example in Flask-SocketIO to heroku(http://flasksocketio2.herokuapp.com/)
https://github.com/miguelgrinberg/Flask-SocketIO/tree/master/example

my Procfile
web: gunicorn --worker-class eventlet app:app

## It usually takes sevral tries to connect.
It seems that after several times retrying, It can connect.
But sometimes it will take really very long time.

The output will be like this:
Received #0: Connected
Received #0: Connected
Received #0: Connected
Received #0: Connected
Received #0: Connected
Received #1: I'm connected!
Received #96: Server generated event
Received #97: Server generated event
Received #98: Server generated event
Received #99: Server generated event
Received #100: Server generated event
Received #101: Server generated event
Received #102: Server generated event
Received #103: Server generated event

## Also the following errors happen every time.
Should I ignore the error?
The second error is just fine, 
but the first error sometimes happened too many times. I have to wait long time to be connect.
#### error1
Firefox can't establish a connection to the server at ws://flasksocketio2.herokuapp.com/socket.io/?EIO=3&transport=websocket&sid=92cd00f57ded4da9863a9bb2178b5b4d.
#### error2
The connection to ws://flasksocketio2.herokuapp.com/socket.io/?EIO=3&transport=websocket&sid=e68d81ce5f9c4659aee891fbbb2ccf08 was interrupted while the page was loading.

**Comment by miguelgrinberg** [comment]
I assume you added eventlet to the requirements file you uploaded to Heroku?

**Comment by small-yellow-rice** [comment]
Yes, I deployed to heroku again and also put the same source code to github.
#### New heroku url:
http://flasksocketiofork.herokuapp.com/
#### New github source code fork
https://github.com/small-yellow-rice/Flask-SocketIO/tree/master/example
#### New app output:
Received #0: Connected
Received #0: Connected
Received #0: Connected
Received #0: Connected
Received #0: Connected
Received #0: Connected
Received #0: Connected
Received #0: Connected
Received #1: I'm connected!
Received #0: Connected
Received #9: Server generated event
Received #0: Connected
Received #1: I'm connected!
Received #0: Connected
Received #1: I'm connected!
Received #0: Connected
Received #0: Connected
Received #1: I'm connected!
Received #9: Server generated event
Received #10: Server generated event
Received #11: Server generated event
Received #12: Server generated event
Received #13: Server generated event
Received #14: Server generated event
Received #15: Server generated event
Received #16: Server generated event
Received #17: Server generated event
Received #18: Server generated event
Received #19: Server generated event
Received #20: Server generated event
Received #21: Server generated event

#### The following is my deploy log from heroku:
remote:        Successfully installed Flask-0.10.1 Flask-SocketIO-1.0 Jinja2-2.7.3 MarkupSafe-0.23 W
erkzeug-0.10.4 eventlet-0.17.4 greenlet-0.4.9 gunicorn-19.3.0 itsdangerous-0.24 python-engineio-0.7.
0 python-socketio-0.6.0 six-1.9.0

**Comment by miguelgrinberg** [comment]
Thanks. I can reproduce the problem here too. I'm investigating.

**Comment by miguelgrinberg** [comment]
Can I ask you to perform a simple test? Please change the gunicorn release from 19.3 to 18.0. Let me know if that makes it work for you.

With that change I'm getting the example to run on Heroku. The odd thing is that gunicorn 19.3 works fine locally.

**Comment by small-yellow-rice** [comment]
Work like amazing after switching gunicorn  to 18.0!!
Thank you!
Should I close this question? Or I should create pull request to memo the version stuff on somewhere?

**Comment by miguelgrinberg** [comment]
Awesome!

Leave it open for now, I need to figure out if this is a gunicorn problem or something I can address on my side.

**Comment by small-yellow-rice** [comment]
OK. Flask-SocketIO have everything I need for my personal website.
I search whole internet, can't find anything like this.
You are awesome!

**Comment by miguelgrinberg** [comment]
Filed [a bug](https://github.com/benoitc/gunicorn/issues/1147) with Gunicorn.
Also added a recommendation for release 18.0 in the gunicorn section of the documentation.
