### ISSUE TITLE
Request within request hangs since switching to eventlet

### ISSUE THREAD

**Issue by patrick-bark** [miguelgrinberg/Flask-SocketIO#172]
Hey, I recently picked up using Flask-SocketIO for my project and have been very happy with it, except that I am running into a strange error. I have a route within my project that hits an API and then returns the data from that api to the front end. This all was working fine, till I switched the server to eventlet, now that API call takes several minutes to finish, when it used to take a couple seconds. I have tried changing the route to a socket, and have tested the API to make sure there aren't any issues. Do you have any idea what could be causing this to hang? The server is running on Ubuntu 12.04, Anaconda3-2.3.0. Thanks

**Comment by miguelgrinberg** [comment]
@patrick-bark Did you monkey patch the Python libraries? This is required to transform the blocking socket functions in the standard library into non-blocking functions that play nice with eventlet.

**Comment by patrick-bark** [comment]
ok, I did do that, but I did not do it before the imports. I will give that a try. Thanks

**Comment by patrick-bark** [comment]
That did not seem to effect it, it seems to mostly happen with SSL, however it is also happening when rendering certain pages. What is usually your process for debugging the server? I can't find any info on how to do that. Thanks

**Comment by miguelgrinberg** [comment]
@patrick-bark as a first attempt, what I would do is interrupt the server while it is in the hung state. Hopefully you get a stack trace that shows exactly where the hang is occurring inside your API request. Feel free to add the stack trace if you want me to take a look.

Do you have this application somewhere I can see it?

**Comment by miguelgrinberg** [comment]
Please reopen the issue when you can provide the requested information.
