### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by edenroseFR** [miguelgrinberg/Flask-SocketIO#1725]
After cloning the repository, I created a virtual environment and installed `flask` and `flask-socketio` before running the main.py . It does run on 127.0.0.1:5000 , but when I tried it on my Google Chrome, it says `404 Not Found`
![Capture](https://user-images.githubusercontent.com/65489091/141381848-26e2c625-1db0-46ce-ada7-dfbc6bf915c4.PNG)

**Comment by miguelgrinberg** [comment]
You filed an issue on the Flask-SocketIO repository, but the problem that you have is with a particular application that you are trying to use. Talk to the author or maintainer of the application to get help, I really don't know how to help you.

**Comment by edenroseFR** [comment]
My apologies. I got confused. Anyway, thanks for taking the time to reply.
