### ISSUE TITLE
How do you pass SSL info to the gevent wsgi server?  

### ISSUE THREAD

**Issue by incognick** [miguelgrinberg/Flask-SocketIO#173]
I want to pass the keyfile and certfile to the gevent.wsgi server.  Is this supported?  

The following seems to work inside SocketIO.run()
```
self.wsgi_server = pywsgi.WSGIServer(
                    (host, port), app, handler_class=WebSocketHandler,
                    log=log,
                    **kwargs)
```

**Comment by miguelgrinberg** [comment]
This is an oversight on my part. I prefer to have the SSL terminated by nginx in front of the SocketIO server, so for my own usage this was never necessary.

This is a valid issue, those ssl arguments need to be passed on to the wsgi server.

**Comment by miguelgrinberg** [comment]
This has been addressed in recent releases. Closing.
