### ISSUE TITLE
socketio emit from another thread not working

### ISSUE THREAD

**Issue by alexroat** [miguelgrinberg/Flask-SocketIO#1744]
**IMPORTANT**: If you have a question, or you are not sure if you have found a bug in this package, then you are in the wrong place. Hit back in your web browser, and then open a GitHub Discussion instead. Likewise, if you are unable to provide the information requested below, open a discussion to troubleshoot your issue.

**Describe the bug**
It seems that when you do an emit from another thread of the server the message is not sent to client (or clients if you are broad casting). It seems that there is a clash of internal threading with the standard python threading. Essentially the issue is the lack of the request context when emitting outside the flas-socketio stack. Various turnaround are offered but non of them seems to be clean and effective and especially transparent respect the choosen mode to run flask-socketio (gevents, greenlet, ...).
A server should have the possibility to emit a message even outside from connect and event hooks. Lets say for example if I'm monitoring an external source, and I want to emit a message when this event happen.
I've tried to solve using a loop inside the conenct but it stucks the socketio loop.
What is needed is an emit version that runs in agnostic way (not depending on the sync/async mode and neither on gevent, greenlet) and that is thread_safe.

**To Reproduce**
1) setup a flask server with flask-socketio endpoint and that serve a socketio client dumping the incoming message in the console
2) create a threading.Timer that trigger after 10 seconds
3) open the page with socketio client
4) you will see that you never receive the message

**Expected behavior**
I expect to receive the message even if I emit outside from a decorated hook (@socketio.on("connect") or @socketio.on("message") ) 
If something goes wrong an exception should be emitted, not a silent drop of the sent message.

**Logs**

**Additional context**

**Comment by miguelgrinberg** [comment]
The example code in this repo shows how to emit from a background thread. Also, please read the instructions before filing a bug, in particular the part about "If you have a question, or you are not sure if you have found a bug in this package, then you are in the wrong place.".

**Comment by alexroat** [comment]
@miguelgrinberg 

Maybe I could express well the issue.
I've already seen the example in the docs.
What I was saying is that if you have an external thread loop like the one in example below is not possible to emit a message.
If you trigger the thread an d use the specific socketio sleep you actually can do a background job but when I've a loop implemented in standard threading python module (for example) it is not possible to emit a message from it.
At the moment, and the example in the docs confirm that, it is mandatory to start the background job in a connect or in a receive.

If you do something like this it does not work:
```
import threading

def my_background_generic_thread():
    def send_something():
        print("you can see me, but the emit below wont send anything!")
        socketio.emit('server_message',{'data': 'Server generated but outside from the connect/receive hook and it does not work!'})
    while True:
        print("loop")
        threading.Event().wait(1000)
        socketio.start_background_task(send_something)
t=threading.Thread(target=my_background_generic_thread)
t.start()
```

Not all the libs are using gevents and greenslet or manage threading so it would be better IMHO to add a global emit method that can be called even from outside of the context using a queue.
Moreover, it would be better that if you attempt to call the emit from outside of a context an exception should be raised

**Comment by alexroat** [comment]
@miguelgrinberg 
Maybe this can help to understand better the issue:

```
import threading

def my_background_generic_thread():
    def send_msg():
        txt="I'm trying to emit a message from another generic thread but I get: greenlet.error: cannot switch to a different thread, if you are lucky you can see just one message on client but you should see a message every seconds, that's not the case. Not all the libraries are using greenlet or gevent."
        print(txt)
        socketio.emit('server_message',{'data': txt})
    while True:
       threading.Event().wait(1)
       socketio.start_background_task(send_msg)
t=threading.Thread(target=my_background_generic_thread)
t.start()
```

index.html is like:
```
<!DOCTYPE html>
<html>
<head>
<title>Page Title</title>
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js" integrity="sha512-q/dWJ3kcmjBLU4Qc47E4A9kTB4m3wuTY7vkFJDTZKjTs8jhyGQnaUrxa0Ytd0ssMZhbNua9hE+E7Qv1j+DyZwA==" crossorigin="anonymous"></script>
<script type="text/javascript" charset="utf-8">
    var socket = io();
    socket.on('connect', function() {
        socket.emit('client_message', {data: 'I\'m connected!'});
    });
    socket.on('server_message', function(m) {
        console.log("message from server",m);
    });
</script>
</head>
<body>

<h1>This is a Heading</h1>
<p>This is a paragraph.</p>

</body>
</html>
```
as you can see it does not work.
IMHO there should be a "thread safe" and "agnostic" way to emit and broadcast a message without depending the socket.io backgrounds. 
That is, using socketio.sleep is working and using and Event().wait(...) is not working? It is simply not thread safe and it should be documented or suggested a way to trigger an emit even if I'm not in a "socketio backgorund_task" that is only using socketio.sleep and should be launched only from "connect" or "message" hook otherwise you don't have the context.

**Comment by miguelgrinberg** [comment]
Two things:

- If you want help in troubleshooting your application, then this is the wrong place. I already said that. Write a discussion topic, provide complete code, and I'll be happy to help you.

- You can have an opinion on how this package should work, but that does not constitute an issue. You have to consider that it could be that you do not fully understand the way to work with this package, or just that I see things in a different way and we just disagree on how this package should work, which means you will have to adapt or find another package that does thing the way you like. Either way, I welcome a discussion topic, but I do not want bugs filed on the project for non-bugs. Thank you.
