### ISSUE TITLE
gunicorn + gthread，cannot use thread pool

### ISSUE THREAD

**Issue by door7474** [miguelgrinberg/Flask-SocketIO#1755]
1、async_mode = threading
2、gunicorn command : gunicorn -w 1 --threads 5 -b 0.0.0.0:8899 app:app
3、socketio func :

@socketio.on('run', namespace="/test")
def test_func(data):
    print(threading.currentThread().name)

The result is 【Thread-2】 instead of 【ThreadPoolExecutor-0_2】

**Comment by miguelgrinberg** [comment]
I'm sorry but I don't understand. Can you explain what the issue is please?

**Comment by door7474** [comment]
Using the deployment of (Flask-SocketIO + simple_websocket + gunicorn + gthread), when an event is triggered, a new thread will be created to process the event, instead of obtaining a thread from the thread pool of gunicorn to process the event

**Comment by miguelgrinberg** [comment]
The thread pool from gunicorn is used to handle HTTP and websocket requests. Socket.IO events are handled separately from that.
