### ISSUE TITLE
Flask Socketio not emitting data to client after running "with app.app_context()" on login process

### ISSUE THREAD

**Issue by zaingithub** [miguelgrinberg/Flask-SocketIO#1795]
**Describe the bug**

Hello, I'm developing a desktop application using flask.

Where in this application users can login using their email and password.

While using flask-soscketio, I encountered problems logging in.

When the user logs in, the application will authenticate the email and password, if it is successful then my application will call a function to run the scheduler using flask-apscheduler (https://github.com/viniciuschiele/flask-apscheduler) to check the license periodically.

The code is roughly like this:

`def task_license_scheduler() :
	with app.app_context(), app.test_request_context() :
		scheduler.add_job(code_here)`

`@auth.route('/login', methods=['GET', 'POST'])
def login():
	if request.method == 'POST':
		is user_valid :
			login_user(user_valid)
			### run scheduler
			task_license_scheduler()`

When the user has successfully logged in, they will be directed to the "homepage", the server should have emitted data to the client.

But when the application calls the **task_license_scheduler()** function, the server emits any data to the client.

But when I restart the flask application, the socket runs normally and emits data to the client as expected.

This happens only when inside the **task_license_scheduler()** function involves **with app.app_context(), app.test_request_context()**.

Please give the best solution for this problem. thank you very much.

**To Reproduce**

**Expected behavior**
Flask Socketio emitting data to client

**Comment by miguelgrinberg** [comment]
Please do not write issues on this package when you need help to make your own application to work. Especially if you also posted the same question in the discussions board.
