### ISSUE TITLE
ImportError: cannot import name 'run_with_reloader' from 'werkzeug.serving'

### ISSUE THREAD

**Issue by ericvanbuhler** [miguelgrinberg/Flask-SocketIO#1809]
**Describe the bug**
I am seeing the following issue upon importing `flask_socketio` into my app:
```
File "/home/.../venv/lib/python3.7/site-packages/flask_socketio/__init__.py", line 24, in <module>
    from werkzeug.serving import run_with_reloader
ImportError: cannot import name 'run_with_reloader' from 'werkzeug.serving' (/home/.../venv/lib/python3.7/site-packages/werkzeug/serving.py)
```

**To Reproduce**
Steps to reproduce the behavior on Linux:
1. Create a clean virtualenv to test the scenario
2. Install `Flask-SocketIO==4.3.2` in the virtualenv: `pip install Flask-SocketIO==4.3.2`
3. Ensure that Werkzeug is the latest version (2.1.0): `pip freeze | grep Werkzeug`
4. Import `flask_socketio` and observe the error: `python -c "import flask_socketio"`

**Expected behavior**
The import should complete cleanly

**Additional context**
I've observed this issue on Python 3.7.X on Ubuntu 18.04, Mac, and Windows.

**Comment by miguelgrinberg** [comment]
This is not going to be fixed. Upgrade Flask-SocketIO to latest, or pin Werkzeug to an old release that is compatible with the old release of Flask-SocketIO that you are using.
