### ISSUE TITLE
Attaching SocketIO to your app changes the logger configuration.

### ISSUE THREAD

**Issue by fake-name** [miguelgrinberg/Flask-SocketIO#183]
Basically, if you have a plain flask app, each get request is logged to the console:

`192.168.1.106 - - [16/Dec/2015 11:32:09] "GET / HTTP/1.1" 200 -`

However, once you attach and start the app with SocketIO connected:
```
socketio = SocketIO(app)
- - -
socketio.run(app)
```

The console logging behaviour is fairly dramatically changed:
```
(28658) accepted ('192.168.1.106', 2497)
(28658) accepted ('192.168.1.106', 2498)
(28658) accepted ('192.168.1.106', 2499)
(28658) accepted ('192.168.1.106', 2500)
(28658) accepted ('192.168.1.106', 2501)
```

I'm not sure if this is a function of now depending on `wsgi`, but it would be nice if attaching the socketio layer didn't basically break the console logging. It makes debugging much more annoying.

**Comment by fake-name** [comment]
Investigating further, passing `log_output=True` to `socketio.run()` restores the original behaviour. However, it should probably default to `True` in all cases, as that better follows the behaviour of what it replaces.

**Comment by miguelgrinberg** [comment]
Let me explain what's going on.

When you run a normal Flask app on the development web server, you are using Werkzeug as a server, which outputs the logs you are used to see.

When you run Flask-SocketIO with eventlet, the web server that is used is eventlet's, which provides the support for WebSocket, in addition to also running the regular WSGI app. With this set up, the Werkzeug server, which writes the logs you are used to, is not used. The logs that you get are what eventlet's web server writes.

What you can do if you want to get the logs you are familiar with, is to force Flask-SocketIO to work in the "threading" async mode. This mode runs on Werkzeug. You will not have support for WebSocket in this mode, so it only makes sense during development, but when you do this you will have the same server running the application.

Hope this clarifies everything.

**Comment by fake-name** [comment]
That doesn't seem to match with the fact that simply passing `log_output=True` replicates the normal behaviour.

**Comment by miguelgrinberg** [comment]
The `log_output` option is used in the eventlet web server. I'm setting it to `True` in debug mode, and `False` in non-debug mode. Are you running in debug or non-debug mode? Have you tried both?

**Comment by miguelgrinberg** [comment]
Just tried it here. It appears that when logging is disabled, eventlet prints the "accepted" lines only. When log_output=True (or also when debug=True in the Flask app) it prints those lines plus the standard request lines.

**Comment by fake-name** [comment]
Yes, I tried both. With `debug` passed on the command-line, you get the expected logging like non-debug mode without SocketIO. Without `debug`, you only get the "accepted" output.

Basically, normal Werkzeug logging output is not sensitive to whether you've passed `debug` on the command line, so it SocketIO being sensitive to the debug parameter differs from the existing behaviour, and is what wound up prompting this bug report.

**Comment by miguelgrinberg** [comment]
While I understand your point of view, this extension has been doing
logging this way for many releases. I support three different web servers,
and it is impossible to make all three behave the same way, so given that
logging can be controlled still, I'm going to leave it this way. My opinion
is that if you want Werkzeug behavior there is nothing better than using
Werkzeug, which you can.

**Comment by fake-name** [comment]
Well, I can see that perspective.
