### ISSUE TITLE
Problems with Firefox

### ISSUE THREAD

**Issue by jextrevor** [miguelgrinberg/Flask-SocketIO#186]
I have made a program with Flask-SocketIO, When I use the "threading" async mode, everything works fine. However, when I try to use eventlet or gevent, Chrome works with my program but Firefox does not.

Both connect to the websocket, but Firefox is unable to send messages. Sometimes the messages will send correctly, but only after a message is received from the server.

What can I do to fix this issue with using eventlet/gevent?

**Comment by jextrevor** [comment]
More experimentation shows that this issue is spotty - sometimes I have it, sometimes I don't.

**Comment by jextrevor** [comment]
Further investigation shows that the Firefox websocket will function correctly after it receives a broadcast message from the server, but not before. Why this happens, I do not know.

**Comment by miguelgrinberg** [comment]
What version of Firefox, and also, are there any errors in the browser's console?

**Comment by jextrevor** [comment]
I'm using Firefox 43.0. No errors appear in the console.

**Comment by miguelgrinberg** [comment]
Could you try the example application in this repository and check if you see the same problem with it? I have Firefox 43.0.2 and using eventlet on the server the websocket connection works well.

**Comment by PierrePaul** [comment]
Works fine for me too, eventlet 0.17.4 and firefox 43.0.4. Ubuntu client and server.

**Comment by ecerulm** [comment]
I'm not sure it's the same issue. Using Firefox 43.0.4 in Linux to connect to the the flask-socketio running on the same machine works unreliablily. Seems to work if I keep emitting (several times per seconds) but as soon if it's idle for  a bit then it's stalled (nothing is received at the flask-socketio side). 

The same flask-socketio app works ok if accessed from a remote windows machine running the same Firefox version. 

Also using Chrome 48.0.2 in the same machine as the flask_socketio works fine. It's only Firefox in the same host. 

Using socket.io 1.3.5 in the browser side and flask-socketio==2.0

**Comment by jextrevor** [comment]
After using the latest version of Flask-SocketIO, I don't see the bug anymore.

**Comment by jextrevor** [comment]
Never mind. Issue is still present.

**Comment by jpoeppel** [comment]
I have a very similar issue with firefox, but I suspect it has to do with localhost (which unfortunately is also present when run on a webserver behind nginx as the socket is forwarded to localhost). @jextrevor would your server also get the requests from localhost (either directly during development, or through a webserver)? 

Unfortunately, I am currently still trying to track it down. All I can say from the websocket extension of mozillas development tools, is that the client sents the 2probe, gets the 3probe as return, but fails to send another information, which seems to be required for quite some time. Until this package (a json with value 5?) was send the client does not want to emit/send messages to the server. 

What is strange that the message will be send eventually (can however take several minutes) and sometimes is send immediately just as in other browsers... If I find anything else, I'll let you know.

**Comment by mwent-cray** [comment]
Same issue here - probably will set up a blank message to setup proper connections everywhere... But that is a sub-optimal solution.
Same as others mentioned - sending messages in ff will work after it receieves one

**Comment by mwent-cray** [comment]
It seems as if emits run in:
@socketio.on('connect')
Are not properly emitted to FF.
And FF tries to ping the server with 0B response. After a couple of tries it disconnects & reconnects
![screen shot 2017-05-02 at 12 49 40 pm](https://cloud.githubusercontent.com/assets/26014391/25636334/f72af1b2-2f35-11e7-87dd-33f2711f2c6d.png)

**Comment by miguelgrinberg** [comment]
@mwent-cray what operating system is this? Linux as stated above or something else?

**Comment by mwent-cray** [comment]
@miguelgrinberg Currently running on Mac OS X El Capitan

**Comment by szhjia** [comment]
Same issue... Safari and Chrome work fine. Firefox (52.0.2 ) some times will not send data to server but whenever receive a broadcast it will be back...

**Comment by miguelgrinberg** [comment]
I think I'm going to need some help in reproducing this.

I'm using Firefox 53.0 on OS X. I took the example app in this repository and commented out the emit that the server sends in the connect event ([this line](https://github.com/miguelgrinberg/Flask-SocketIO/blob/master/example/app.py#L101)), so that upon connection the server does not send anything. But the application works just fine, I can emit and broadcast from the browser without a problem.

What else can I do to see this problem?

**Comment by mwent-cray** [comment]
@miguelgrinberg Hmm weird, I just tested again (53.0) and didn't have any problems anymore. Please keep it open just in case. But it is very odd.

I didn't have async_mode set
I don't have namespace set

After testing first with and then without async_mode set to "eventlet" FF seems to be behaving.
But no conclusive fix. I will try tomorrow at different computers.

**Comment by jpoeppel** [comment]
@miguelgrinberg I have just gotten around to creating a minimal example, which shows the problem for me:
https://github.com/jpoeppel/Flask-SocketIO-FirefoxBug

I am using Ubuntu Xenial and running Firefox 54.0 using the latest flask-socketIO from pypi (2.8.6) and the socketio.js version 2.0.1.

It would be great if you can let me know if you can reproduce the bug with this example, so that I can make sure it is not something different on my system.

For completeness: 
The expected behaviour is, that you can click the "Test"-Button right after loading the page, and you should see "got it!: {'data': 'Testdata'}" in a div above the Test-Button, every time you reload the page. For me this only works every few reloads, as in the other cases the websocket-upgrade does not seem to complete. I hope this helps in finding the source of this strange bug.

**Comment by miguelgrinberg** [comment]
@jpoeppel Sorry, but still can't reproduce. I'm using FF 57 like you, with your code example, and in my case I do get the connection upgraded to WebSocket. Does it fail always or intermittently for you?

**Comment by jpoeppel** [comment]
@miguelgrinberg Thanks for still checking this. If I force websocket it always fails, with the 400 bad Request on the client side (oddly enough the server still receives the connect event). The console spawns an error message: "Firefox can’t establish a connection to the server at ws://localhost:5000/socket.io/?EIO=3&transport=websocket."
If I do not force websockets I do not get the automatic update ever, it does not even look like it is trying an upgrade.

I will try a different machine (this was on Linux) over the weekend to see if it behaves the same there for me as well. 

Currently I can live with the long-polling at least always working, which is an improvement to the upgrade getting stuck before, but I would still like to finally figure out what is going on here.

**Comment by jp-bennett** [comment]
I too have observed this issue with a Firefox client. For now I'm working around it using {transports: ['websocket'], upgrade: false}

It seems that something about Firefox's method of upgrading from long polling to a websocket is broken, but forcing it to just make a websocket connection seems to work.

**Comment by miguelgrinberg** [comment]
I'm closing, since I haven't heard of any more issues with Firefox in almost 3 years.
