### ISSUE TITLE
Does the socket io android package work for flask-socketio as well?

### ISSUE THREAD

**Issue by emcenrue** [miguelgrinberg/Flask-SocketIO#190]
As seen on their main blog: http://socket.io/blog/native-socket-io-and-android/

**Comment by miguelgrinberg** [comment]
Yes, you can use the Java Socket.IO client on your Android device and talk to a Flask-SocketIO server.

**Comment by emcenrue** [comment]
thank you! Also thanks for the amazing book, "Flask Web Development"! I learned so much!

**Comment by Nixellion** [comment]
I'm getting 400 Bad request error trying to connect to my https flask socketio server, what are the usual suspects?

**Comment by miguelgrinberg** [comment]
@Nixellion did you enable the server logs to see what's going on?

**Comment by Nixellion** [comment]
@miguelgrinberg I was not sure if you or anyone gets notifications from closed issues, so I posted a new one here: #550 

I posted logs there
