### ISSUE TITLE
Underlying socket#conn events + heartbeat ping/pong event access

### ISSUE THREAD

**Issue by AFlowOfCode** [miguelgrinberg/Flask-SocketIO#1905]
**Is your feature request related to a problem? Please describe.**
Yes. The main problem is the server is unable to easily tell who is connected and for how long due to hiding the internal heartbeat / ping / pong / packet reception events. The ability to access some other internal events would be useful as well for increased flexibility.

**Describe the solution you'd like**
An implementation of the events specified at https://socket.io/docs/v4/server-socket-instance/#socketconn. At minimum I'd like to see a `packet` event interface.

**Describe alternatives you've considered**
Patching `python-engineio` (eg `server.py` & `socket.py`), `python-socketio`, and/or `flask-socketio` & running a modified version which always reports back "to the surface" aka flask event/endpoint code on these events. If there are other, simpler alternatives I'm missing I would like to know!

**Additional context**
Over the years, to one implementation of Socket.IO or another, countless people have expressed the desire to have access to internally handled events, such as the ping/pong [heartbeat](https://github.com/miguelgrinberg/Flask-SocketIO/issues/530) or basic packet reception triggers. To any readers, please see the linked issue, its linked issue, and the various responses for additional context. The below is partially a response to that ticket as well as the general sentiment surrounding access to such "internals". I try to explain the context of why such requests are valid even though they have been ignored or casually dismissed for many years by implementers, for reasons I do not fully comprehend.

The primary reason people want access to things like this is because you do not always have control over the client. That you cannot control (aka trust) the client is one of the key principals of web development & a necessary perspective when developing backend server code. Yes, of course I can tell *my* client to send a custom heartbeat for example, but that doesn't stop *other* clients from being set up to try and eat all my sockets (threads, workers) with as long of a connection they can get away with (especially if people are encouraged to use the default `/socket.io` path - I recommend changing this). And I will anticipate another dismissive argument and state that no, requiring auth on connection is not always a legitimate solution to the issue at hand.

There are solid use cases for wanting access to this information. As a developer, nothing is more misguided than casually making assumptions about what use cases exist or do not exist around certain types of features, especially ones that people consistently ask for. It is a lack of imagination that cannot conceptualize and thus casually dismisses such use cases with some off-handed comment or tells people they should not want them or trivializes it. If it isn't specified in Socket.IO's actual protocol description then it really should be.

People have had workarounds in other implementations for a good amount of time (eg "heartbeat" event). I believe if there is no official support for this there should be at minimum a workaround in this implementation besides running patched versions of the dependencies. Other than that this is a great implementation (not only `flask-socketio` but also the above-mentioned associated libraries, and I'm particularly fond of the test client - thank you!) & not having access to some of the internals is the biggest frustration. I am not trying to pick a fight or complain, simply requesting a feature and using that allotted space to add my perspective to the historical record in support of easy access to internal events in Socket.IO implementations in general, and this implementation in particular. Many thanks to the contributors for their work and their time!

**Comment by miguelgrinberg** [comment]
> The main problem is the server is unable to easily tell who is connected and for how long due to hiding the internal heartbeat

The application is informed as clients come and go with the `connect` and `disconnect` events. After you receive `'connect`, you can safely assume that the client remains connected until you receive the `disconnect`. Note that unlike the internal ping/pong mechanism, connect/disconnect are tracked per namespace. Even if you were able to tap into the ping/pong mechanism you would not be able to know which namespace(s) are connected or disconnected, since this is all at the Engine.IO level where namespaces do not exist.

I don't understand why you say you are unable to know who's connected and who isn't. If you think the connect/disconnect events are broken, then please provide all the details and I'll fix any use cases in which they aren't worked as designed.

Likewise, if you can provide a solution that provides access to low-level events **that does not affect performance in any way** for the vast majority of apps that do not care, I would be open to consider merging it.

**Comment by AFlowOfCode** [comment]
Yes, sorry perhaps I wasn't as specific as I should have been. I realize that once someone is connected they are assumed to be connected until `disconnect` is received. The issue is more about connection time, such as when a client is emitting no events so nothing except the `connect` event has or possibly ever will be triggered until maybe `disconnect` at some unknown point in the future. These are essentially silent connections except for low-level heartbeat packets.

For example what if I want to track how long each client is connected based on time passed since `connect`? Of course socket details can (and should be) be saved in the database along with `connected_at` timestamps, and it is possible to schedule tasks based on some other timer to go through existing connections that haven't triggered `disconnect` yet. To follow the actual connection & have up to date information, such a task could take `ping_interval` and `ping_timeout` into consideration. But since there is an existing mechanism already operating under the hood, the most natural way to do this in my opinion would be to have any sort of pure connection-time logic attached to the ping/pong packets received by the server from each connection. 

Even just being able to compare the `last_ping` property of the socket to a `connected_at` timestamp on such an event would be of great use. The simplest way to do this is plug into the socket level packet events for each connection. Namespace doesn't matter in the case where you only care about connection time or socket-level details, which is reasonable. Sometimes you do not care about namespaces, while other times you do. This is one example of something that would be made simpler and cleaner with access to a packet receive event.

**Comment by miguelgrinberg** [comment]
> For example what if I want to track how long each client is connected based on time passed since connect?

Connection time for any client, silent or not, long-polling or WebSocket, can be calculated as `time.time() - client.connected_at`. All you need to calculate connection time is to store the timestamp the `connect` event was called for each client. The time of the last ping/pong is not part of this formula.

What I understand between the lines of what you are saying is that you also don't care about ping/pong interactions, what you care about is to be reminded of every connected client at regular intervals. Now you already indicated that you are open to saving a `connected_at` for each client in a database, so you already have an easy way to obtain the list of connected clients by querying the database, without any added network traffic or added background tasks, except maybe a single background task that walks the client list in your database.

> Namespace doesn't matter in the case where you only care about connection time or socket-level details

Namespaces do matter. First of all, the low-level Engine.IO events are going to use Engine.IO SIDs, which are not the SIDs that you receive for your Socket.IO connections. The SIDs that you manage at the Socket.IO layer are all generated under a namespace, so you are using namespaces in spite of not caring about them. The Engine.IO SID is going to be different than the Socket.IO SID that you obtain for each namespace the client connected to.

Also, given the separation between the two layers, it is possible (yet unusual) to have a healthy Engine.IO connection with working ping/pongs that for whatever reason lost all the Socket.IO namespace connections. So technically you can be 100% disconnected at the Socket.IO level, but the transport remains connected. Again, this is technically possible but highly unusual, I mention it just to make a point that focusing on the Engine.IO layer will bring about more issues than solutions.

> Adding background tasks to check all existing connections has a performance effect as well

No. You need a single background task that walks your database stored client list. This can actually be quite efficient.

Dispatching events that are unlikely to be implemented in most apps also has a cost, especially when you are operating at large scale. Preserving performance is more important, in my opinion. But I stand by my offer above, if you can come up with a way to do this that does not sacrifice any performance for the apps that do not care about internal Engine.IO events, I would consider it.

**Comment by AFlowOfCode** [comment]
Thanks for your thoughts. 

I do agree that performance is important. The simplest way that initially comes to mind would be to make internal events optional via a setting passed in during initialization. For example a parameter `emit_internal_events=False`. Checking a boolean before emitting an event would cost very little, but if apps do want these (and the accompanying burden) they can set it to `True`.

Another example of the utility of access to internal events is regarding an internal `close` event. Even though the server *should* always receive the `disconnect` event, this is not necessarily the case. For instance it is possible to modify the socket.io javascript client library to remove the `beforeunload` handler which handles a sudden disconnection on the client side (eg closing the page). No `disconnect` event will be sent to the server if this listener has been removed. Engineio will realize "Client is gone" due to no ping response, but the `disconnect` event is never triggered in this case. 

Of course "normal" users will not do this, but it's not hard & this could be a way to manipulate applications that solely depend on `disconnect` events to determine if sockets are still connected, such as only deleting some `Socket` record on this event (following the basic assumption that users are connected until this event is received).

While there are other solutions to the examples I am providing, they are only examples of how internal events can be useful. It's not an exhaustive list of how to make use of them nor do I mean to say it's the only way of doing anything, just that there are real uses for them.

**Comment by miguelgrinberg** [comment]
I feel you are ignoring the complications I mentioned above. The low level events will have a different SID on them. Your application will have to handle a one-to-many mapping from one Engine.IO SID to potentially many Socket.IO SIDs.

> For instance it is possible to modify the socket.io javascript client library to remove the beforeunload handler which handles a sudden disconnection on the client side (eg closing the page). 

First of all, why would anyone do that? And second, the `disconnect` event will still be invoked in the server. The "client is gone" mechanism, which is used mainly to detect disconnects in long-polling connections is also going to kick in for these silent disconnections from WebSocket clients. What would you want a weird `close` event that doesn't mean anything when you can get a proper `disconnect`?

**Comment by AFlowOfCode** [comment]
> why would anyone do that?

To answer this first of all, if an application has enough traffic it is fact at some point someone will try to break it. This has nothing to do with the limits of anyone's imagination when considering "plausible" or "reasonable" client behavior. I take it you are not accustomed to thinking from an "attacker" perspective about application security. As I stated, "you can't trust the client". I confirmed that you can manipulate the client so the server doesn't receive `disconnect` and instead I get the "client is gone" log. I recommend trying it yourself if that doesn't seem possible to you.

What I am asking for is exactly what I stated in the "solution I'd like" section - https://socket.io/docs/v4/server-socket-instance/#socketconn. However it was just an idea mostly to get your perspective on it. As I also stated I wanted to put my thoughts on this topic here for the record, which I have now done sufficiently.

At the end of the day, I can't imagine there being any way you would authentically consider it despite what you've stated granted that you think checking a conditional before sending an event potentially has too much of a performance impact. How could it be possible to implement anything at all if that in itself is too much?

In any case I'll close the ticket, I think it has served its purpose. Thanks for your work and your comments!

**Comment by miguelgrinberg** [comment]
> at some point someone will try to break it

As I explained above, removing the unload event in the client would just cause a small delay in the server detecting the disconnection. The `disconnect` event would still be sent, just a few seconds layer than it would have been normally.

> How could it be possible to implement anything at all if that in itself is too much?

With a subclass.
