### ISSUE TITLE
make the SocketIOTestClient more conform to python-socketio for seemless substitution

### ISSUE THREAD

**Issue by duquesnay** [miguelgrinberg/Flask-SocketIO#1906]
**Is your feature request related to a problem? Please describe.**
I'm developing a little game server based on an underlying flask-socketio and the client relies on a python-socketio client

During unit testing, I want to provide my game client with a SocketIOTestClient instead of a socketio.Client thanks to socketio.test_client(...)
Problem: the interface and life cycle is not exactly the same as python-socketio client, so I have to do many twists to get it compatible, namely on 3 points:
- connect(...) doesn't take a url parameter
- the mocked client is provided already connected, and subsequent calls to connect(...) are ignored, so I can't directly test my connection process
- the mocked client doesn't have an sid provided, so can't use this as a reference in the upper layers (the fame client)

**Describe the solution you'd like**
1. add an 'url' parameter to SocketIOTestClient.connect(...) to mimic the signature from python-socketio Client.connect(...). The url can be ignored. 
2. test_client() returns a test client that claims to be not already connected, and the connection simulation happens only when connect(...) is called. 
2bis. the connection simulation adds an sid attribute and set it during SocketIOTestClient.connect

to avoid breaking compatibility with existing use of test_client(), we could even have an alternative test_unconnected_client()

**Describe alternatives you've considered**
- running a server the regular way -> since shutting it seem to be very complicated, not going there
- create another SocketIOTestClient variant and use it on my side. Not fun

any clarification needed? thoughts?

**Comment by duquesnay** [comment]
after a quick test, it's working straightforwardly. I created another class, copy pasted of SocketIOTestClient. noted difference
- removed the call to connect(...) at the end of __init__(), and cleaned now useless __init__() parameters, so you're left with the Flask app, SocketIO object, and optional flask_test_client
- init self.sid = None at __init__
- during connect(), once the sid is calculated it's retained in self.sid
- for convenience, I've created another builder function reproducing test_client() (with less parameters, then)

As for retro-compatibility, maybe we can make the connect() call optional during __init__(), adding an optional parameter no_connect=False. That would give a bit of a polymorphic signature, not sure if that's pythonic

**Comment by miguelgrinberg** [comment]
I don't really understand what you are trying to do. The Socket.IO test client is not a real client and it's not intended to be one. You will never be able to replace a real client with a test client. The test client does not handle incoming events at all, for example. The fact that the connection logic is different to that of the real client is a minor difference compared to all the other ways in which the test client lacks compared to the real one. Lots of people use a real client for testing, why is that a problem for you?

**Comment by miguelgrinberg** [comment]
> I understand it's still quite tricky for shutting down the servers

This is completely unrelated to Flask-SocketIO, as it depends on the web server that you use. If you can stop the server with Ctrl-C then you can get the same result sending a SIGINT signal programmatically.
