### ISSUE TITLE
line 470, in handle_one_response

### ISSUE THREAD

**Issue by x4dr** [miguelgrinberg/Flask-SocketIO#191]
Honestly this is probably my stupidity and spaghetti code, but i get 

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/eventlet/wsgi.py", line 470, in handle_one_response
    for data in result:
TypeError: 'NoneType' object is not iterable
```

In random intervals, sometimes i get one of them while testing all of my functions sometimes i get 5 of them  within one tabbing back and forth from browser to IDE ... I dont really know where to look or what is causing it, except it stops happening if i disable the SocketIO parts of my Flask app

Does anyone know how i can find out what is causing this?
I could just disable everything in turn and use the site for like 10 minutes each but that would take a long time especially if people would have an idea what is causing this. (my code can be viewed here on Github, the things that are going wrong are probably in NossiNet/NossiSite/chat.py which is halfway in transition from example to what i want to do with it^^

**Comment by x4dr** [comment]
also where do i put my code for handling The 104 and stuff when someone closes the page, i like my Exceptions handled ^^

**Comment by miguelgrinberg** [comment]
This has been addressed a while ago. Closing.
