### ISSUE TITLE
Flask socketio test_client method to test received ConnectionRefusedError messages

### ISSUE THREAD

**Issue by Seluj78** [miguelgrinberg/Flask-SocketIO#1963]
Hi !

I'm writing unit tests to test my socketio auth and I'd like to test if the correct message is returned by `ConnectionRefusedError` based on my auth send.

Sadly, this isn't doable right now. The only method available for the `test_client` is `get_received` which checks if the client is connected before getting the messages, but the client isn't connected when a `ConnectionRefusedError` is raised during the `on("connect")` method.

I would like to be able to do

```py
    def test_no_token(self):
        socketio_client = socketio.test_client(application)

		self.assertEqual("JWT access token required in query parameters.", socketio_client.get_received()[0]["args"])
```

Or something along those lines.

But currently, all I can do is:

```py
    def test_no_token(self):
        socketio_client = socketio.test_client(application)
        with self.assertRaises(RuntimeError):
            socketio_client.get_received()

    def test_invalid_token(self):
        socketio_client = socketio.test_client(application)(
            query_params="?token=yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
            ".eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY3OTk"
        )
        with self.assertRaises(RuntimeError):
            socketio_client.get_received()
```

Thank you very much !

**Comment by Seluj78** [comment]
Do you need any more details on this @miguelgrinberg ? :)

**Comment by miguelgrinberg** [comment]
No, I don't need anything else. The test client wasn't designed to work like a real client and for that reason some things cannot be done. I will see if a connection failure can be simulated, but if you really want to do serious testing I recommend that you run a real client against a real server.

**Comment by Seluj78** [comment]
The idea was to run unit tests directly from `unittest` without having a huge setup elsewhere. Having a real client against a real server is a completely different type of testing and not one we're ready to work on on this projet :)

**Comment by Seluj78** [comment]
Fair enough ! I will make it work without it for now, and figure out a solution if needed later ! Thank you !
