### ISSUE TITLE
Flask-SocketIO Admin UI

### ISSUE THREAD

**Issue by Seluj78** [miguelgrinberg/Flask-SocketIO#1964]
This one might be a big feature request, but I might be able to try and work on it if I am given a nudge :D

I've just come across the fact that the `socketIO` standard has an admin UI for clients using it on their backend with nodeJS: https://socket.io/docs/v4/admin-ui/

I was wondering how hard it would be, if even possible, to reproduce something similar or compatible for Flask SocketIO ?

Cheers !

**Comment by miguelgrinberg** [comment]
I was able to hook up to the Socket.IO Admin UI, so this is definitely possible. It will take me a few more days to polish this up enough to be committed, but work is in progress.

**Comment by Seluj78** [comment]
Oh wow amazing! I was about to ask you if you could point me in the right direction so I could try and do this myself :)

You rock !

**Comment by miguelgrinberg** [comment]
Closing this issue, as I'm tracking this work on https://github.com/miguelgrinberg/python-socketio/pull/1164
