### ISSUE TITLE
Support for once to listen for an event only 1 time (Like official socket.io server has)

### ISSUE THREAD

**Issue by kingdevnl** [miguelgrinberg/Flask-SocketIO#1997]
**Is your feature request related to a problem? Please describe.**
For example to request user input from a socket and to only handle the output once.

**Describe the solution you'd like**
Sending a event to the client requestInput -> {"title": "Enter name of file"}
then in the client ask for input, then send the the respsonse to the server
In the server write the data to for example redis.

**Additional context**
[Add any other context or screenshots about the feature request here.
](https://socket.io/docs/v4/listening-to-events/#socketonceeventname-listener)

**Comment by miguelgrinberg** [comment]
Unlike the JavaScript libraries, these use a more Pythonic approach and do not allow adding and removing event handlers while the application is running. You set up your handlers before the server start, and then those handlers remain active. With this in mind, I think it isn't really clear how to implement what you are asking.
