### ISSUE TITLE
Option to redirect http to https instead of raising errors

### ISSUE THREAD

**Issue by Ashenguard** [miguelgrinberg/Flask-SocketIO#2002]
**Is your feature request related to a problem? Please describe.**
Every time I check my server logs for potential issues... I find SSL errors spamming it.

**Describe the solution you'd like**
I would like to remove them from logging...
If I can redirect users to https too it would be great!

**Describe alternatives you've considered**
In my searches, I found Flask-SSLify, which works fine with Flask. But unfortunately, there is no support for Flask-SocketIO

**Comment by miguelgrinberg** [comment]
I'm not sure I understand. This package is not a web server and has nothing to do with SSL. The errors that you get are coming from your web server I think, so that is where your request should be directed.
