### ISSUE TITLE
get_received(namespace=None) does not returns the messages

### ISSUE THREAD

**Issue by pravesh-sharma** [miguelgrinberg/Flask-SocketIO#2006]
**Describe the bug**
After recent update in python-socketio, Flask-SocketIO's `get_received(namespace=None)` function is not returning the messages received from server it just returns an empty list. However, with older version of python-socketio everything works.

**Additional context**
We are using this function to write API test case for our socket implementation.

**Comment by miguelgrinberg** [comment]
Can you test the main branch and report back if the problem is addressed? I'll issue a new release once you confirm that the fix works well for you.

**Comment by pravesh-sharma** [comment]
@miguelgrinberg Tested on main branch and it is working. You can issue new release.

**Comment by miguelgrinberg** [comment]
Thanks. Release 5.3.6 is out with this fix!

**Comment by shivansh-vishwakarma** [comment]
Hi @miguelgrinberg 
I feel like the issue still persist, can you please check and update. I am on version 5.3.6. 
After emitting event to SocketIOTestClient the `get_received(namespace=None)` still gives `[]`.

**Comment by miguelgrinberg** [comment]
@shivansh-vishwakarma If you provide a complete and runnable example test that shows the problem and I'll investigate.

**Comment by shivansh-vishwakarma** [comment]
Moving the conversation to https://github.com/miguelgrinberg/Flask-SocketIO/issues/2063
