### ISSUE TITLE
python-engineio and python-socketio version matching with Flask-SocketIO >= 5.3.0

### ISSUE THREAD

**Issue by 876720687** [miguelgrinberg/Flask-SocketIO#2029]
I've come across a project that requires Flask-SocketIO >= 5.3.0, but I've never been able to find a matching combination when matching the corresponding python-engineio and python-socketio, and keep getting errors:

ERROR:engineio.server:The client is using an unsupported version of the Socket.IO or Engine.IO protocols (further occurrences of this error will be IO protocols (further occurrences of this error will be logged with level INFO)

Has anyone tried anything like this?

**Comment by miguelgrinberg** [comment]
The error message tells you what's wrong. The **client** is using an unsupported version of the Socket.IO or Engine.IO protocol. This means that the client that you are using is not compatible with the version of the server. Either change the client to a compatible version, or change the server to match the version of the client that you have. The documentation has a version compatibility table that you can use for help with this.
