### ISSUE TITLE
Messages delayed/dropped depending on framework

### ISSUE THREAD

**Issue by lukeyeager** [miguelgrinberg/Flask-SocketIO#203]
I'm testing out all the framework options (because of #199) and am seeing different results depending on which framework I use when trying to do `socketio.emit()` on the server and receive it with `socket.on()` on the browser.

1. Using `gevent` (with or without `gevent-websocket`) leads to 10-20 second delays. Could I simply not be activating websockets? Surely the default polling time is less than 10 seconds?

2. Using `eventlet` leads to the messages being missed entirely. They don't show up on the browser-side at all.

3. Oddly, I can receive the messages just fine when using neither of the above frameworks

Library | Delay
------------ | -------------
neither (werkzeug) | *none*
`gevent` | 10-20 seconds
`gevent` and `gevent-websocket` | 10-20 seconds
`eventlet` | Infinite (message never received)

**Comment by lukeyeager** [comment]
[Relevant code](https://github.com/lukeyeager/flask-sqlalchemy-socketio-demo/tree/46e9cc6342):
```python
# Server
# https://github.com/lukeyeager/flask-sqlalchemy-socketio-demo/blob/46e9cc6342/main.py#L81-L83
        with app.app_context():
            print 'Sending to SocketIO ...'
            socketio.emit('new_update', item['data'])
```
```js
// Client
// https://github.com/lukeyeager/flask-sqlalchemy-socketio-demo/blob/46e9cc6342/templates/index.html#L21-L23
    socket.on('new_update', function(data) {
        console.log(data);
    });
```
Full matrix of delay/shutdown issues by framework: https://github.com/lukeyeager/flask-sqlalchemy-socketio-demo/issues/3

**Comment by lukeyeager** [comment]
I tried rolling back to `Flask-SocketIO==1.2` (since I see that v2.0 just got released) and saw the same thing from each framework listed above.

**Comment by miguelgrinberg** [comment]
@lukeyeager my first guess is that the problems are related to not monkey patching the Python std lib. You are using threads, which require that you either patch the libraries, or else use the gevent or eventlet thread specific calls instead of Python standard ones.

**Comment by lukeyeager** [comment]
Good call. I had to monkey patch the std libs and implement threading using whichever framework was installed. Now messages can be sent with any framework. Thanks!

https://github.com/lukeyeager/flask-sqlalchemy-socketio-demo/commit/9a61509da0497a120eb8f01827af8e0f58a1dca1
