### ISSUE TITLE
Server fails while serving a file to quicktime player  -- Flask Server while using flask-serverio

### ISSUE THREAD

**Issue by jackmullen2** [miguelgrinberg/Flask-SocketIO#206]
Hello Miguel : 

I have been working on a application using Flask-socketIO (version 1) that among other things allows the uploading of files and provides links for download.  I have created a route for playback that uses the following method - for purposes of requiring a download and not a stream ..  The method works for straight link related calls by a browser -- the browser will just download instead of trying to play -- 

@app.route('/static/uploads/<directory>/<filename>')
def download_file_uploads(directory,filename):
    return send_from_directory('static/uploads/'+directory,
                               filename, as_attachment=True)

Of course this def is not a socket-io route -- but, the app has other socket-io routes some of which may be in use during server operation.  I wanted to see if you had seen this kind of error when using flask and eventlet as a server for static content.  I continue to get this error when my iphone's quicktime player attempts to play a file -- and the server restarts and then quicktime starts over..  I am wondering if this is anything you have seen before or had a suggestion for how to prevent this error.  It is quite repeatable. Perhaps using an Nginx server as the static content server may be the answer ? 

Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 192, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 183, in execute
    write(data)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 164, in write
    self.wfile.write(data)
IOError: [Errno 32] Broken pipe

**Comment by miguelgrinberg** [comment]
You are using Werkzeug as web server, which is a development web server. Switch to eventlet or gevent and see if those work better.

**Comment by jackmullen2** [comment]
Thank you for helping me .. I installed eventlet .. and from the Flash-SockeIO documentation  "The simplest deployment strategy is to have eventlet or gevent installed, and start the web server by calling socketio.run(app) as shown in examples above. This will run the application on the eventlet or gevent web servers, whichever is installed. " Is there something further I should do to use the eventlet server .. ?

**Comment by jackmullen2** [comment]
Ok .. I just say your comments here : 

When you run app.run(debug=True) you are explicitly telling Flask to run your application on the development web server, which is based on Werkzeug. It does not matter that you have loaded eventlet.

If you want to run your application on the eventlet web server, you have to start an eventlet web server, which according to the documentation is started as follows:

wsgi.server(eventlet.listen(('', 8000)), your_app)

This is more or less what socketio.run() does in my Flask-SocketIO extension, with a little bit more complexity to optionally handle SSL. The lines of code that do this are: https://github.com/miguelgrinberg/Flask-SocketIO/blob/539cd158f49ce085151911cb63edbacd0fa37173/flask_socketio/init.py#L391-L408. If you look around those lines, you will see that there are three different start up chunks of code, one for werkzeug, one for eventlet and one for gevent. They are all different.

Again .. thanks for helping me ..

**Comment by jackmullen2** [comment]
OK .. I removed "debug=True" -- Unfortunately the same thing happens ..  the new exception is : 

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/eventlet/wsgi.py", line 477, in handle_one_response
    write(b''.join(towrite))
  File "/usr/local/lib/python2.7/dist-packages/eventlet/wsgi.py", line 426, in write
    _writelines(towrite)
  File "/usr/lib/python2.7/socket.py", line 334, in writelines
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
  File "/usr/local/lib/python2.7/dist-packages/eventlet/greenio/base.py", line 376, in sendall
    tail = self.send(data, flags)
  File "/usr/local/lib/python2.7/dist-packages/eventlet/greenio/base.py", line 359, in send
    total_sent += fd.send(data[total_sent:], flags)
error: [Errno 32] Broken pipe

**Comment by miguelgrinberg** [comment]
Well, broken pipe means that the client closed the connection, so my first guess is that there is some sort of problem with your client or with the network between the client and the server.

**Comment by jackmullen2** [comment]
I thought that also .. but I have been using a cell phone with 4 bars and LTE -- perhaps mobile clients are not reliable in terms of maintaining a a stream .. However I set the same test up using a apache server to server the data and it works without a glitch .. very frustrating this problem :) .. Thanks again ..

**Comment by jackmullen2** [comment]
Again, thanks for you help, I believe the issue is with the iTunes player on the iphone .. as it is unable to restart the stream at the last point of data after a loss of the stream data and apparently before that it quickly closes the connection.  I installed the VLC player for iphone and it works without an issue.  You can even set a buffer time delay that would likely be useful for periods of signal loss while driving.  I have experience with the iPhone player in version 7 of the IOS and I could open a file set for download and the player would download the entire file as it played it -- most of the time the bitrate encoding was low enough that the player could consume most of the stream before just a few minutes played .. this enabled listening to the file during prolonged periods of no signal -- which is one of my objectives ..  Jack
