### ISSUE TITLE
Cassandra Requests Hang in Flask-SocketIO Development Mode

### ISSUE THREAD

**Issue by rodrigo1t** [miguelgrinberg/Flask-SocketIO#2084]
**Describe the bug**
When using Flask-SocketIO in development mode (FLASK_DEBUG=1), requests to Cassandra hang (do not return). This issue does not occur in production mode (FLASK_DEBUG=0). This behavior suggests that the Flask debug mode conflicts with the protocol or asynchronous handling required for Cassandra.

**To Reproduce**

1. Set up a Flask application with Flask-SocketIO and Cassandra.
2. Enable Flask debug mode by setting FLASK_DEBUG=1.
3. Make a request to Cassandra within the Flask application.
4. Observe that the request hangs and does not return.
5. Disable Flask debug mode by setting FLASK_DEBUG=0.
6. Make the same request to Cassandra.
7. Observe that the request completes successfully.

**Expected behavior**
Requests to Cassandra should complete successfully regardless of whether Flask debug mode is enabled or disabled. Additionally, it should be possible to maintain the development environment with Flask reload and debug mode enabled (FLASK_DEBUG=1) without causing requests to Cassandra to hang.

**Environment**
Flask-SocketIO version: 5.3.6
Flask version: 2.3.3
Python version: 3.12.3
Cassandra-driver version: 3.29.1
gevent: 24.2.1

**Here is the code used to set up the Flask application**
```
import os
from flask import Flask
from flask_socketio import SocketIO
from cassandra.auth import PlainTextAuthProvider
from cassandra.cluster import Cluster


def get_cassandra_connection(keyspace=None):
    auth_provider = PlainTextAuthProvider(
        username='your_username',
        password='your_password',
    )
    cluster = Cluster(
        ['127.0.0.1'],
        port=9042,
        auth_provider=auth_provider,
    )
    connection = cluster.connect()

    if keyspace:
        connection.set_keyspace(keyspace)

    return connection

ENVIRONMENT = os.environ.get('ENVIRONMENT')
is_production = ENVIRONMENT == 'production'
os.environ['FLASK_DEBUG'] = '0' if is_production else '1'

app = Flask(__name__)
socketio = SocketIO(app, engineio_logger=is_production)
app.config['SocketIO'] = socketio
app.config['cassandraConnection'] = get_cassandra_connection()


@app.route('/')
def index():
    # Simulate a request to Cassandra
    print('Before')
    app.config['cassandraConnection'].execute(f'SELECT * FROM test_table')
    print('After request')  # <<<  Print is not displayed and does not return anything, hang occurs
    return 'Success'

if __name__ == '__main__':
    app.config['SocketIO'].run(
        app,
        port=int(5001),
        host='0.0.0.0',
    )
```

**Comment by miguelgrinberg** [comment]
You are using gevent, which is likely to have incompatibility issues with the Flask reloader.

I suggest you try to disable the automatic code reloader to see if that resolves the issue. If that does not do it or if you need to use the code reloader, then you can drop gevent and switch to the `threading` async mode which is not going to have any incompatiblities.

**Comment by rodrigo1t** [comment]
> You are using gevent, which is likely to have incompatibility issues with the Flask reloader.
> 
> I suggest you try to disable the automatic code reloader to see if that resolves the issue. If that does not do it or if you need to use the code reloader, then you can drop gevent and switch to the `threading` async mode which is not going to have any incompatiblities.

Yes, I am using gevent. If I disable the reloader (use_reloader=False), the request to Cassandra works. However, my goal is to keep the reloader active since I am in a development environment.

When I change the async_mode to threading, the request to Cassandra works, the reloader and debug mode also work, but I cannot establish WebSocket connections. Here is the code and the output I am getting:

`socketio = SocketIO(app, engineio_logger=is_production, async_mode='threading')`
Output:
```
* Serving Flask app 'TestAPI'
* Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
* Running on all addresses (0.0.0.0)
* Running on http://127.0.0.1:5001
* Running on http://192.168.1.100:5001
```

My goal is to have the reloader and debug mode active in the development environment while ensuring that both Cassandra requests and WebSocket connections work properly.

Could you please guide me on how to achieve this?

**Comment by miguelgrinberg** [comment]
What version of python-socketio, python-engineio and simple-websocket do you have installed?

**Comment by rodrigo1t** [comment]
> What version of python-socketio, python-engineio and simple-websocket do you have installed?

python-socketio = 5.11.3
python-engineio = 4.9.1
simple-websocket = 1.0.0

**Comment by miguelgrinberg** [comment]
I think you should have websocket support with those dependencies. What happens when the client tries to upgrade to WebSocket?

**Comment by rodrigo1t** [comment]
> **Describe the bug** When using Flask-SocketIO in development mode (FLASK_DEBUG=1), requests to Cassandra hang (do not return). This issue does not occur in production mode (FLASK_DEBUG=0). This behavior suggests that the Flask debug mode conflicts with the protocol or asynchronous handling required for Cassandra.
> 
> **To Reproduce**
> 
> 1. Set up a Flask application with Flask-SocketIO and Cassandra.
> 2. Enable Flask debug mode by setting FLASK_DEBUG=1.
> 3. Make a request to Cassandra within the Flask application.
> 4. Observe that the request hangs and does not return.
> 5. Disable Flask debug mode by setting FLASK_DEBUG=0.
> 6. Make the same request to Cassandra.
> 7. Observe that the request completes successfully.
> 
> **Expected behavior** Requests to Cassandra should complete successfully regardless of whether Flask debug mode is enabled or disabled. Additionally, it should be possible to maintain the development environment with Flask reload and debug mode enabled (FLASK_DEBUG=1) without causing requests to Cassandra to hang.
> 
> **Environment** Flask-SocketIO version: 5.3.6 Flask version: 2.3.3 Python version: 3.12.3 Cassandra-driver version: 3.29.1 gevent: 24.2.1
> 
> **Here is the code used to set up the Flask application**
> 
> ```
> import os
> from flask import Flask
> from flask_socketio import SocketIO
> from cassandra.auth import PlainTextAuthProvider
> from cassandra.cluster import Cluster
> 
> 
> def get_cassandra_connection(keyspace=None):
>     auth_provider = PlainTextAuthProvider(
>         username='your_username',
>         password='your_password',
>     )
>     cluster = Cluster(
>         ['127.0.0.1'],
>         port=9042,
>         auth_provider=auth_provider,
>     )
>     connection = cluster.connect()
> 
>     if keyspace:
>         connection.set_keyspace(keyspace)
> 
>     return connection
> 
> ENVIRONMENT = os.environ.get('ENVIRONMENT')
> is_production = ENVIRONMENT == 'production'
> os.environ['FLASK_DEBUG'] = '0' if is_production else '1'
> 
> app = Flask(__name__)
> socketio = SocketIO(app, engineio_logger=is_production)
> app.config['SocketIO'] = socketio
> app.config['cassandraConnection'] = get_cassandra_connection()
> 
> 
> @app.route('/')
> def index():
>     # Simulate a request to Cassandra
>     print('Before')
>     app.config['cassandraConnection'].execute(f'SELECT * FROM test_table')
>     print('After request')  # <<<  Print is not displayed and does not return anything, hang occurs
>     return 'Success'
> 
> if __name__ == '__main__':
>     app.config['SocketIO'].run(
>         app,
>         port=int(5001),
>         host='0.0.0.0',
>     )
> ```

I would like to add additional information that a warning appears when running my tests:
I don't know if this helps with debugging.

```
Warning: 
DeprecationWarning: The asyncore module is deprecated and will be removed in Python 3.12. The recommended replacement is asyncio
  import asyncore

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```
![image](https://github.com/user-attachments/assets/a4234902-383b-477c-bcbc-0e3bede25624)

**Comment by rodrigo1t** [comment]
> I think you should have websocket support with those dependencies. What happens when the client tries to upgrade to WebSocket?
When I use async_mode='threading', as you suggested, I am unable to establish WebSocket connections. The request to Cassandra works, as do the reloader and debug mode, but the WebSocket connections fail.

When I attempt to establish a connection, I receive the following error:

```
127.0.0.1 - - [07/Aug/2024 17:10:12] "GET /socket.io/?EIO=4&transport=websocket HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/Users/developer/my_project/venv/lib/python3.12/site-packages/werkzeug/serving.py", line 363, in run_wsgi
    execute(self.server.app)
  File "/Users/developer/my_project/venv/lib/python3.12/site-packages/werkzeug/serving.py", line 329, in execute
    write(b"")
  File "/Users/developer/my_project/venv/lib/python3.12/site-packages/werkzeug/serving.py", line 254, in write
    assert status_set is not None, "write() before start_response"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: write() before start_response
```

My goal is to have the reloader, debug mode, Cassandra requests, and WebSocket connections all working together in the development environment.

What do you think might be causing this, and how can I resolve this issue while keeping everything functioning as expected?

**Comment by miguelgrinberg** [comment]
@rodrigo1t Try upgrading your Werkzeug to the latest 2.3.x.

**Comment by rodrigo1t** [comment]
> @rodrigo1t Try upgrading your Werkzeug to the latest 2.3.x.

I was using version 3.0.3 and downgraded to version 2.3.8, but the error persisted when connecting to the websocket.
```
assert status_set is not None, "write() before start_response"
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: write() before start_response

```

**Comment by miguelgrinberg** [comment]
You need to review your dependecies. You said you were using Flask 2.3.3 and Werkzeug 3.0.3, which are known to be incompatible.

What I suggest is that you take the app.py example in this repository, and modify it in a way that reproduces the issue that you are having. Then send me the modified code, templates, and requirements.txt that you used.

**Comment by miguelgrinberg** [comment]
Thanks. I've added the template from the app.py example to your application and was able to make a websocket connection just fine in threading mode:

![image](https://github.com/user-attachments/assets/750f2ef5-48b0-4247-8296-8c2c205066f3)

**Comment by rodrigo1t** [comment]
> Thanks. I've added the template from the app.py example to your application and was able to make a websocket connection just fine in threading mode:
> 
> ![image](https://private-user-images.githubusercontent.com/2715854/356805954-750f2ef5-48b0-4247-8296-8c2c205066f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyODY2NTgsIm5iZiI6MTcyMzI4NjM1OCwicGF0aCI6Ii8yNzE1ODU0LzM1NjgwNTk1NC03NTBmMmVmNS00OGIwLTQyNDctODI5Ni04YzJjMjA1MDY2ZjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTBUMTAzOTE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWIzMjFlMDZlM2M4ZmUzNjc3OTY2ZGJjNDRjMGVmYzEzYTE5MTc5MjhlYzEwNDNiZWYyYmY5OGEzYzMzZGIyNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9YG41oEavkQPFZTp_Gt6PJxKDY5TQaGTBwwWPEEmdxo)
> 
> Package versions:
> 
> ```
> Flask==3.0.3
> Werkzeug==3.0.3
> Flask-SocketIO==5.3.6
> python-socketio==5.11.3
> python-engineio==4.9.1
> simple-websocket==1.0.0
> ```

@miguelgrinberg, thank you very much for your time and assistance. I wanted to let you know that I found a solution that works for my situation. By using eventlet version 0.36.1, I was able to enable debug=True and the auto-reloader, while also making requests to Cassandra and establishing WebSocket connections successfully.

Thanks again for your help!

**Comment by miguelgrinberg** [comment]
@rodrigo1t I wouldn't rely on eventlet for anything that is production code. See https://eventlet.readthedocs.io/en/latest/.

**Comment by rodrigo1t** [comment]
> @rodrigo1t I wouldn't rely on eventlet for anything that is production code. See https://eventlet.readthedocs.io/en/latest/.

Thanks for letting me know, I went back to using gevent for production, and when using the versions indicated above, the web-socket connection and requests to cassandra worked with async_mode='threading'.
