### ISSUE TITLE
Not possible to emit with multiple arguments

### ISSUE THREAD

**Issue by miguelgrinberg** [miguelgrinberg/Flask-SocketIO#209]
In the Socket.IO client, it is possible to emit an event with multiple arguments:

    socket.emit('my event', 'foo', 'bar', 123);

The server-side code that receives this event needs to be coded as follows:

    @socketio.on('my event')
    def (a, b, c):
        # a is 'foo'
        # b is 'bar'
        # c is 123

This is currently impossible to do when the server is the emitter, because the `emit` and `send` functions take the `data` argument and send it as a single argument. These functions can be extended so that when the `data` argument is a tuple, the elements in the tuple are sent as separate arguments.

**Comment by miguelgrinberg** [comment]
This has been fixed in python-socketio. To send multiple arguments, a tuple must be used:

    emit('my event', data=('foo', 'bar', 123))

**Comment by yamass** [comment]
It would be super nice if somebody could add this to the documentation at https://python-socketio.readthedocs.io/en/latest/api.html#client-class
