### ISSUE TITLE
Man

### ISSUE THREAD

**Issue by SOK122** [miguelgrinberg/Flask-SocketIO#2093]
from flask import Flask, render_template, redirect, url_for, request
from flask_socketio import SocketIO, send
from flask_login import LoginManager, UserMixin, login_user, login_required, logout_user, current_user

app = Flask(__name__)
app.config['SECRET_KEY'] = 'your_secret_key'

# SocketIO для работы с реальным временем
socketio = SocketIO(app)

# Flask-Login для аутентификации пользователей
login_manager = LoginManager()
login_manager.init_app(app)

# Временная база данных пользователей
users = {'user1': 'password1', 'user2': 'password2'}  # Простая база данных для демонстрации

# Класс пользователя
class User(UserMixin):
    def __init__(self, id):
        self.id = id

@login_manager.user_loader
def load_user(user_id):
    return User(user_id)

# Главная страница
@app.route('/')
def index():
    return render_template('index.html')

# Страница входа
@app.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        if username in users and users[username] == password:
            user = User(username)
            login_user(user)
            return redirect(url_for('chat'))
    return render_template('login.html')

# Страница чата (доступна только авторизованным пользователям)
@app.route('/chat')
@login_required
def chat():
    return render_template('chat.html', username=current_user.id)

# Выход из аккаунта
@app.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('login'))

# Обработка сообщений через WebSocket
@socketio.on('message')
def handle_message(msg):
    if current_user.is_authenticated:
        print(f"Сообщение от {current_user.id}: {msg}")
        send(f"{current_user.id}: {msg}", broadcast=True)

if __name__ == '__main__':
    socketio.run(app, debug=True)

**Comment by miguelgrinberg** [comment]
If you have a question, please use the discussions forums.
