### ISSUE TITLE
Add support for wildcard events

### ISSUE THREAD

**Issue by Dubidu1212** [miguelgrinberg/Flask-SocketIO#2095]
I would like to listen to generic events to be able to handle them myself. Wildcard events are supported by the underlying python socketio library since version  5.4.1 

I would love it if we could have "*" events which would trigger every time no other event handler was registered for the event.
```
socketio.on("*")
def catchall(event):
    print(event)
```
When emiting an event from the client that the server hasn't registered elswhere we would see something like:
`Client> emit("unregistered_event")`
`Server> "unregistered_event"`

I have considered directly interfacing with the underlying library, but it seems to break some higher level functionalities.

**Comment by miguelgrinberg** [comment]
@Dubidu1212 Could you give the main branch of this repository a quick try for catch all events?

**Comment by Dubidu1212** [comment]
@miguelgrinberg Thanks a lot! Works exactly like I imagined!
