### ISSUE TITLE
Support for Phusion Passenger

### ISSUE THREAD

**Issue by HGStyle** [miguelgrinberg/Flask-SocketIO#2099]
**Is your feature request related to a problem? Please describe.**
Yes, but not a problem with Flask-SocketIO, rather more a problem with my hosting provider. They let me host Python apps though the use of Phusion Passenger, and there is no configuration setup for that software.

**Describe the solution you'd like**
Help on making it work inside documentation, if it's possible to get it working.

**Describe alternatives you've considered**
I tried using the Flask application object in Phusion Passenger instead of using the Socket object.

**Logs**
Is that needed for a feature request? If needed, I'll add some here, tell me.

**Comment by miguelgrinberg** [comment]
Flask-SocketIO supports WSGI, which is used widely in Python. I'm not sure how Phusion Passenger supports Python web apps, but if they don't support WSGI then I think the most logical solution would be for them to add support for it.

**Comment by HGStyle** [comment]
Okay, will ask on their repo. Thanks for the information.
