### ISSUE TITLE
Watchdog installed breaks development server

### ISSUE THREAD

**Issue by rstcruzo** [miguelgrinberg/Flask-SocketIO#2102]
**Describe the bug**
When I start the socketio server in development mode (config["DEBUG"] = True) and watchdog is installed, no client can't connect to it. I don't see any errors on server side but every client reports Connection Refused.

**To Reproduce**
1. Use the example/app.py file in this repo
2. Set config["DEBUG"] = True
3. Install watchdog and other dependencies
4. Start the server with python app.py
5. Try to connect with any client

**Expected behavior**
The client can connect successfully

**Logs**
No error logs on server side.
On client side:
```
Traceback (most recent call last):
  File "/Users/rsantacruz/Code/client-example.py", line 4, in <module>
    sio.connect("ws://localhost:5000")
  File "/Users/rsantacruz/Code/.venv/lib/python3.9/site-packages/socketio/simple_client.py", line 82, in connect
    self.client.connect(url, headers=headers, auth=auth,
  File "/Users/rsantacruz/Code/.venv/lib/python3.9/site-packages/socketio/client.py", line 159, in connect
    raise exceptions.ConnectionError(exc.args[0]) from None
socketio.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /socket.io/?transport=polling&EIO=4&t=1729524516.573758 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x105cf6580>: Failed to establish a new connection: [Errno 61] Connection refused'))
```

**Additional context**
I can't just uninstall watchdog because I'm also using dramatiq which uses it for autoreloading the code.

**Comment by miguelgrinberg** [comment]
This package does not provide a web server. This is an inconpatibility between watchdog and your chosen web server. If you are using the Flask development web server, not that it also has a code reloading feature, the issue might by these two reloading features interfering with each other. I suggest you try running your application with debug mode disabled if you are using watchdog for code reloads. Maybe that solves your problem.

**Comment by rstcruzo** [comment]
Maybe I wasn't clear. The server I'm running is the one provided by this package:
```
socketio.run(app)
```
The docs of that function states `Run the SocketIO web server.`.

The Flask development server works fine. Flask automatically uses watchdog if it's installed. The issue lies in the incompatibility between the SocketIO web server and watchdog.

**Comment by rstcruzo** [comment]
Oh, I see. So all this package does is add the /socket.io route to the flask application. Thank you for the explanation! I thought this was meant to be run as a separate server.

I wonder why my Flask development server, which I run with `flask run`, works, but when I run `socketio.run()`, no connections can be established. I guess it's something in my setup.

Thank you again, I'll try to dig more.

**Comment by miguelgrinberg** [comment]
Do you have gevent or eventlet installed? If you are, then you are not using the flask web server.

**Comment by rstcruzo** [comment]
I do have gevent installed. Does that mean the incompatibility is between gevent and watchdog?

**Comment by miguelgrinberg** [comment]
@rstcruzo the fact that [watchdog-gevent](https://pypi.org/project/watchdog-gevent/) exists is a pretty good indication that these two packages do not like each other when used on their own.

Note that if you are using gevent, then you are not using the Flask development web server, you are using the gevent web server. Maybe you did not realize this, but this could be part of the confusion.

Any reason you need gevent in your project? You can try not using it. Flask-SocketIO works well with threads, and this would eliminate any incompatibilities with watchdog.

**Comment by rstcruzo** [comment]
Now that I'm using `flask run` to start the server I see the regular Werkzeug log `WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.`.

I want to use gevent because it is said to be more efficient; greenlets are lighter than threads.

To my understanding, If I use Werkerzug in development mode and gevent in production, I should be fine, as watchdog isn't used in production. Or am I missing something?

**Comment by miguelgrinberg** [comment]
I suppose you can, assuming nothing else conflicts with gevent.

**Comment by rstcruzo** [comment]
@miguelgrinberg Quick question: is gevent-websocket needed anymore? I see you removed it from python-socketio [here](https://github.com/miguelgrinberg/python-socketio/commit/0aa8683a3b13f5175fea70e52f889297d605b2bc#diff-2e8b3bd0cd400f73069709441b7f7f5499adb1c247b191088ec7e89ee3a2cbacL887), but I still see a warning "WebSocket transport not available. Install gevent-websocket for improved performance." when it's not installed. The warning seems to be coming from [here](https://github.com/miguelgrinberg/Flask-SocketIO/blob/e72896597503d6e9bc4c213f123bee8545dab614/src/flask_socketio/__init__.py#L703)

**Comment by miguelgrinberg** [comment]
No, gevent-websocket is not needed because in recent versions the simple-websocket package provides the same functionality. The warning in this package is outdated, I will remove it.

**Comment by miguelgrinberg** [comment]
Documentation has been updated to reflect this.
