### ISSUE TITLE
Tutorial not working with latest socket.io-client npm when using long polling

### ISSUE THREAD

**Issue by chuckus** [miguelgrinberg/Flask-SocketIO#219]
I cannot use the `socket.io-client` v1.4.5 from npm to connect to the example chat server described in the tutorial. I am running the code from the tutorial repo with Python 2.7.10, and running the following with Node v5.5.0.

```
$ DEBUG=* node
> var socket = require('socket.io-client')('http://localhost:5000/chat')
  socket.io-client:url parse http://localhost:5000/chat +9s
  socket.io-client new io instance for http://localhost:5000/chat +0ms
  socket.io-client:manager readyState closed +1ms
  socket.io-client:manager opening http://localhost:5000/chat +0ms
  engine.io-client:socket creating transport "polling" +0ms
  engine.io-client:polling polling +0ms
  engine.io-client:polling-xhr xhr poll +0ms
  engine.io-client:polling-xhr xhr open GET: http://localhost:5000/socket.io/?EIO=3&transport=polling&t=LARMs1x&b64=1 +0ms
  engine.io-client:polling-xhr xhr data null +1ms
  engine.io-client:socket setting transport polling +1ms
  socket.io-client:manager connect attempt will timeout after 20000 +0ms
  socket.io-client:manager readyState opening +1ms
```

Server logs with `basicConfig(level=logging.DEBUG)`

```
$ python chat.py
INFO:engineio:Server initialized for eventlet.
INFO:werkzeug: * Restarting with stat
INFO:engineio:Server initialized for eventlet.
(47534) wsgi starting up on http://127.0.0.1:5000/
(47534) accepted ('127.0.0.1', 64837)
INFO:engineio:94ed18a91f51492384f291a8880478ed: Sending packet OPEN with {'pingInterval': 25000, 'pingTimeout': 60000, 'upgrades': ['websocket'], 'sid': '94ed18a91f51492384f291a8880478ed'}
INFO:engineio:94ed18a91f51492384f291a8880478ed: Sending packet MESSAGE with 0
127.0.0.1 - - [01/Feb/2016 18:52:55] "GET /socket.io/?EIO=3&transport=polling&t=LARP1rV&b64=1 HTTP/1.1" 200 392 0.002962
(47534) accepted ('127.0.0.1', 64839)
```

It just remains in the `opening` readyState. The server logs show a 200 response for the connect and each reconnect, but that's it. I've updated the `flask-socketio` dependency to 2.0 and still get the same behaviour. I'm currently looking to see if this is a firewall issue (hopefully is).

Using the web interface served from Flask works fine, and using the client with the official socket.io chat NodeJS example works properly as well. Is anyone else seeing the same behaviour.

**Comment by miguelgrinberg** [comment]
I have only tested versions 1.3.5 through 1.3.7 of the Javascript client, and only from the browser. Can you please try these versions and see if you see any difference?

You can also switch the Flask html template to use the 1.4.5 client, and see if that works from the browser. Maybe the 1.4.x releases changed something, let me know what the results of these tests are and we'll go from there.

**Comment by chuckus** [comment]
Before I continue, thanks for everything @miguelgrinberg, super impressed not by just everything you've made, but your attentiveness to the issues raised.

Test results:
* Switching to 1.4.5 client in the html template had the same correct behaviour, so I can make a pull request for that if you'd like.
* Downgrading `socket.io-client` npm client to both 1.3.5 and 1.3.7 and trying to connect does not work, and appears to exhibit the same behaviour (null data returned from server).

To ensure it wasn't my environment, I spun up an Ubuntu 14.04 VM in the could and was able to recreate the same behaviour with the npm client. Let me know what else I can do to help out.

**Comment by chuckus** [comment]
I forced `socket.io-client` to use websocket as its default transport:
```
var socket = require('socket.io-client')('http://localhost:5000/test', { transports: ['websocket'] })
```
and managed to connect to the server, and emit and receive messages!

**Comment by miguelgrinberg** [comment]
Okay, so connecting directly via WebSocket works, but not if you want to do it the standard way, which involves connecting via HTTP long-polling first.

I can actually reproduce the problem here, so I'll try to figure this thing out.

> Switching to 1.4.5 client in the html template had the same correct behaviour, so I can make a pull request for that if you'd like.

Yes, happy to do this. Thanks!

**Comment by christopher-abastar** [comment]
+1 on this.

thanks!

**Comment by christopher-abastar** [comment]
Hi Miguel,

After investigating this problem, i found out that the response data being sent in the response during polling is has multiple packets in it in the during in the upgrade response.

In the screenshot below, message "40" should have not been appended here in the response, it should have been sent in the next GET request of the client.  I'm guessing that some client implementation of socket.io doesn't understand this type message during polling and ignore this message causing it to be stuck in an open state?

![screen shot 2016-03-29 at 7 38 34 pm](https://cloud.githubusercontent.com/assets/12439198/14106729/d8df8554-f5e5-11e5-8db6-51b7894c711e.png)

**Comment by miguelgrinberg** [comment]
I believe this was caused by a bug in the XHR module used by the Socket.IO client when running under node.js. I submitted a fix, which was accepted (see https://github.com/socketio/engine.io-client/pull/483).
