### ISSUE TITLE
Working Behind an (NginX) Proxy?

### ISSUE THREAD

**Issue by benjamid** [miguelgrinberg/Flask-SocketIO#22]
First, this has been a great library to use: very convenient and helpful.  However, I've had a ton of trouble setting up an NginX (v1.4) reverse proxy, which is needed to handle SSL and other useful functions.  Are there any examples of NginX config files that work with this library?  I feel like I've tried and modified every socketio .conf variant on the internet at this point, but still can't get the handshake to work.  For production use, being able to get this properly proxied is very important.

**Comment by nikitph** [comment]
can someone elaborate on these lines:

_location /socket.io {
        proxy_pass http://127.0.0.1:5000/socket.io;_
does this mean it points to the route /socket.io in the flask app? essentially how does this map to the flask app? is it transparent? meaning i dont have to make any changes in the actual app?

**Comment by miguelgrinberg** [comment]
@nikitph the `/socket.io` endpoint is handled by Flask-SocketIO. When you create a `SocketIO` instance and pass your Flask app to it, the extension inserts its endpoint into the app. You do not need to make any changes to the application, as any requests that are not going to `/socket.io` are passed through to the application.

**Comment by nikitph** [comment]
@miguelgrinberg thanks a lot miguel. big fan of your work. 

interesting. so do i need to supply this on the client? locally everything works very smoothly. i am above version 1.4 for nginx too. 

my client looks like this

var socket = io.connect('http://' + document.domain + ':' + location.port + namespace);
            socket.on('connect', function () {
                socket.emit('join', {room: 1});
            });

this is my local server setting 

manage.py -->
def server():
    app.debug = True
    # WSGIServer(('127.0.0.1', 5000), app).serve_forever()
    eventlet.wsgi.server(eventlet.listen(('127.0.0.1', 5000)), app)

now this is my deploy script on digital ocean

exec gunicorn  --timeout=300 -b 127.0.0.1:{{port}} manage:app -w $NUM_WORKERS \
    --user=$USER --group=$GROUP --log-level=debug \
    --log-file=$LOGFILE 2>>$LOGFILE --worker-class=eventlet --worker-connections 1001

and this is the nginx config -->

server {
    listen       80;
    server_name  {{server_hostname}} ;
    return       301 http://www.{{server_hostname}}$request_uri;
}


server {

    listen 80;
    server_name {{ ansible_eth0.ipv4.address }} www.{{server_hostname}};

    root /home/{{user_name}}/{{server_hostname}};

    location  /static {
            alias /home/{{user_name}}/{{server_hostname}}/static;
            autoindex on;
            expires max;
        }

    #deny access to git and dot files
    location ~ /\.  { 
    deny all;
    return 404;
    }

    #deny direct access to script and sensitive files 
    location ~* \.(pl|cgi|py|sh|lua|log|md5)$ {
        return 444;
        }

    location / {
        proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_pass http://127.0.0.1:{{enferno_port}};
        
    }
    
    location /socket.io {
        proxy_pass http://127.0.0.1:{{enferno_port}}/socket.io;
        proxy_redirect off;
        proxy_buffering off;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }
}

but i get a bunch of JS errors on the client and this on the backend

2016-04-30 17:48:30 [20877] [DEBUG] GET /socket.io/
2016-04-30 17:48:30 [20877] [DEBUG] Closing connection. 
2016-04-30 17:48:30 [20879] [DEBUG] POST /socket.io/
2016-04-30 17:48:30 [20879] [DEBUG] Closing connection. 
2016-04-30 17:48:30 [20879] [DEBUG] GET /socket.io/
2016-04-30 17:48:30 [20879] [DEBUG] Closing connection. 
2016-04-30 17:48:30 [20880] [DEBUG] POST /socket.io/
2016-04-30 17:48:30 [20880] [DEBUG] Closing connection. 

appreciate the help.

**Comment by nikitph** [comment]
i just saw i m loading on a closed bug. LMK if you want a new one opened.
