### ISSUE TITLE
How to handle a long time job?

### ISSUE THREAD

**Issue by wzwcn** [miguelgrinberg/Flask-SocketIO#220]
My server-side test code is as follows：
`
@socketio.on('query', namespace='/test')
def query(data):

    for i in range(100):
        emit('query_result',{'is_success':True,'result':{'v':str(i)}})
        print(i)
        time.sleep(0.5)
`
Clients typically receive more than 40 times, then not receive anymore，any suggestions？

**Comment by miguelgrinberg** [comment]
Is there any problem when you use the handler as you coded it? Looks decent to me, as long as `time.sleep` is monkey patched.

**Comment by wzwcn** [comment]
Thanks for your answer.
yes,`time.sleep` is monkey patched,and i solves it  by following code:
`@socketio.on('query', namespace='/test')
def query(data):

    @copy_current_request_context
    def test():
        for i in range(100):
        emit('query_result',{'is_success':True,'result':{'v':str(i)}})
        time.sleep(0.5)
    thread=Thread(target=test)
    thread.daemon=True
    thread.start()`

**Comment by miguelgrinberg** [comment]
Was the original code blocking other handlers from firing? I shouldn't have, it should have only blocked the client that owned the connection.
