### ISSUE TITLE
SocketIO server with Apache in front stalls at 86880 bytes

### ISSUE THREAD

**Issue by bodgit** [miguelgrinberg/Flask-SocketIO#221]
Hello,

I have my Flask-SocketIO application working and so to be able to handle SSL/TLS I have put an Apache instance in front of it that performs the SSL/TLS termination and just speaks HTTP to the application behind it. For dealing with the websockets side I have the `proxy_wstunnel` Apache module loaded and the configuration looks like this:

```apache
RewriteEngine On

RewriteCond %{QUERY_STRING} transport=polling
RewriteRule /(.*)$ http://flask:8080/$1 [P]

ProxyPreserveHost On
ProxyRequests Off

ProxyPass /socket.io/ ws://flask:8080/socket.io/
ProxyPassReverse /socket.io/ ws://flask:8080/socket.io/

ProxyPass / http://flask:8080/
ProxyPassReverse / http://flask:8080/
```

This should in theory handle both websockets and the fallback of long-polling HTTP requests. It all works except in the case where the Flask application returns a regular HTTP response that is large, something around 100 KB or bigger. The problem I have is I only receive the first 86880 bytes of the response and then the connection stalls until the relevant timeout kicks in and closes the connection. It's always 86880 bytes too.

I've reproduced the problem down to this very small (well, small apart from the test data) test case that doesn't even deal with any websockets:

```python
from flask import Flask
from flask.ext.socketio import SocketIO

app = Flask(__name__)
socketio = SocketIO(app)

lorem = """
<~100 KB of Lorem Ipsum ...>
"""

@app.route("/lorem")
def lorem():
    return lorem

if __name__ == "__main__":
    #app.run(debug=True, host='0.0.0.0', port=8080)
    socketio.run(app, debug=True, host='0.0.0.0', port=8080)
```

Provided the response is larger than 86880 bytes (hence 100 KB of test data) it will reliably stall through Apache _only_ if I start the application with `socketio.run(...)` (which is using eventlet as the chosen webserver). Toggling debug between True and False makes no difference either which means it's using Werkzeug for the debug-enabled case. If I instead start the application with `app.run(...)` then it works no problem (with no websocket support obviously) so it leads me to believe it's something in the SocketIO path even though I'm not doing anything specifically with websockets here.

If I access the Flask application directly using curl, etc. then it also works without any problem which is odd as I can't work out what Apache is doing differently, at this point it's just normal HTTP proxying.

**Comment by bodgit** [comment]
I've managed to reproduce this using just your python-engineio module and its example server:

```python
import engineio
import eventlet
from flask import Flask

eio = engineio.Server()
app = Flask(__name__)

response = """
<~ 100 KB of Lorem Ipsum ...>
"""

@app.route("/lorem")
def lorem():
    return response

if __name__ == "__main__":
    app = engineio.Middleware(eio, app)
    eventlet.wsgi.server(eventlet.listen(('', 8080)), app)
```

So it looks more like it's more likely a problem in that module rather than this one.

**Comment by miguelgrinberg** [comment]
I think this is likely a problem in evenlet's WSGI server, but I'll run some more tests to confirm before I submit a bug to them. Thanks.

**Comment by Wendong-Wu** [comment]
This also happens when I just use Eventlet + Flask without a Apache/Nginx at the front. Eventlet 0.18 will get stuck when serving static files larger than around 60KB. 

The solution is to downgrade Eventlet to 0.17.

**Comment by miguelgrinberg** [comment]
Good to know. Eventlet 0.18 came out about a week ago, and it was followed by a 0.18.1 the day after. Probably not a good idea to jump to that release until it gets a bit of mileage. The 0.17.4 release has been pretty stable for me, though I don't think I have ever managed large files with it.

**Comment by bodgit** [comment]
Thanks for the tip on Eventlet, I was using 0.18.1 it seems and now by pinning back to 0.17.4 it looks much happier.

I think eventlet/eventlet/issues/295 is possibly the cause of this problem, the behaviour smelt of something related to a partial write somewhere in the stack which might explain why Apache triggers it if maybe it's using a different size of receive buffer compared to when I went direct with curl.
