### ISSUE TITLE
Are you able to run the server separately to the client?

### ISSUE THREAD

**Issue by fergvick** [miguelgrinberg/Flask-SocketIO#227]
Is it possible to run the Flask-SocketIO server within a docker container and then access it from another Flask app ?

**Comment by miguelgrinberg** [comment]
Yes, that should work just fine. In reality, it won't be the Flask app accessing, it will be the clients that will connect to the Flask app to get the HTML/CSS/JS, and to the Flask-SocketIO server for the socket connection.
