### ISSUE TITLE
Session ID missing?

### ISSUE THREAD

**Issue by fishgills** [miguelgrinberg/Flask-SocketIO#228]
Here's an error I'm receiving. I'm not sure what I'm doing wrong. I was recently using Flask SocketIO 0.9 with no issues and I'm working on upgrading to Flask SocketIO 2.1 and Socketio client library 1.4.5.

> mauie_1 | Traceback (most recent call last):
> mauie_1 |   File "/usr/local/lib/python2.7/dist-packages/eventlet/wsgi.py", line 470, in handle_one_response
> mauie_1 |     result = self.application(self.environ, start_response)
> mauie_1 |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
> mauie_1 |     return self.wsgi_app(environ, start_response)
> mauie_1 |   File "/usr/local/lib/python2.7/dist-packages/flask_socketio/__init__.py", line 37, in __call__
> mauie_1 |     start_response)
> mauie_1 |   File "/usr/local/lib/python2.7/dist-packages/engineio/middleware.py", line 47, in __call__
> mauie_1 |     return self.engineio_app.handle_request(environ, start_response)
> mauie_1 |   File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 303, in handle_request
> mauie_1 |     return self.eio.handle_request(environ, start_response)
> mauie_1 |   File "/usr/local/lib/python2.7/dist-packages/engineio/server.py", line 226, in handle_request
> mauie_1 |     environ, start_response)
> mauie_1 |   File "/usr/local/lib/python2.7/dist-packages/engineio/socket.py", line 75, in handle_get_request
> mauie_1 |     start_response)
> mauie_1 |   File "/usr/local/lib/python2.7/dist-packages/engineio/socket.py", line 114, in _upgrade_websocket
> mauie_1 |     return ws(environ, start_response)
> mauie_1 |   File "/usr/local/lib/python2.7/dist-packages/engineio/async_eventlet.py", line 13, in __call__
> mauie_1 |     return super(WebSocketWSGI, self).__call__(environ, start_response)
> mauie_1 |   File "/usr/local/lib/python2.7/dist-packages/eventlet/websocket.py", line 127, in __call__
> mauie_1 |     self.handler(ws)
> mauie_1 |   File "/usr/local/lib/python2.7/dist-packages/engineio/socket.py", line 176, in _websocket_handler
> mauie_1 |     self.receive(pkt)
> mauie_1 |   File "/usr/local/lib/python2.7/dist-packages/engineio/socket.py", line 45, in receive
> mauie_1 |     self.server._trigger_event('message', self.sid, pkt.data)
> mauie_1 |   File "/usr/local/lib/python2.7/dist-packages/engineio/server.py", line 327, in _trigger_event
> mauie_1 |     return self.handlers[event](*args)
> mauie_1 |   File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 429, in _handle_eio_message
> mauie_1 |     self._handle_event(sid, pkt.namespace, pkt.id, pkt.data)
> mauie_1 |   File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 371, in _handle_event
> mauie_1 |     r = self._trigger_event(data[0], namespace, sid, *data[1:])
> mauie_1 |   File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 397, in _trigger_event
> mauie_1 |     return self.handlers[namespace][event](*args)
> mauie_1 |   File "/usr/local/lib/python2.7/dist-packages/flask_socketio/__init__.py", line 177, in _handler
> mauie_1 |     app = self.server.environ[sid]['flask.app']
> mauie_1 | KeyError: '34835e1cf8124a2ebd83e877692c2710'

SocketIO falls back to polling after this and even then, it seems to fail after about 5 polls or so.

Anyone know anything about this?

**Comment by miguelgrinberg** [comment]
Do you get the same error if you run the example application in this repository, or just with your code?

**Comment by fishgills** [comment]
:( Just my own code...

I'll dig around some more. Was crossing my fingers that there was something already about this. Example works.

**Comment by miguelgrinberg** [comment]
If you want to share your code I'm happy to review it and maybe I'll save you some time.
