### ISSUE TITLE
WebSocketBadStatusException: Handshake status 200

### ISSUE THREAD

**Issue by joyzhang15** [miguelgrinberg/Flask-SocketIO#229]
The example works fine when I access it from browser. However, when I trying to connect websocket by using python script, it always raise websocket._exceptions.WebSocketBadStatusException: Handshake status 200.
The code of python script is as following:
`from websocket import create_connection`
`ws = create_connection('ws://127.0.0.1:5000/')`

It there any problem with my python script?

**Comment by miguelgrinberg** [comment]
Flask-SocketIO is not a websocket server, it follows the Socket.IO protocol. You need to use a Socket.IO client. If you need one in Python, try [this one](https://pypi.python.org/pypi/socketIO-client).

**Comment by joyzhang15** [comment]
Thanks so much!

**Comment by matrixback** [comment]
The docs of flask-socketio said "eventlet is the best performant option, with support for long-polling and WebSocket transports", I installed eventlet and it works, but use websocket's create_connect to connect, still raise " WebSocketBadStatusException: Handshake status 200 ".of course, socketIO_client can connect.

**Comment by miguelgrinberg** [comment]
@matrixback Socket.IO is built on top of WebSocket. The Socket.IO connection will use WebSocket as transport protocol if available. Only when WebSocket is not available it will use long polling.

**Comment by matrixback** [comment]
@miguelgrinberg  Thanks so much. I didn't really understand the difference between Socket.IO and WebSocket. Socket.IO will use Websocket technology
technology if available, but the two protocols are difference on initial handshake. Socket.IO use Websocket but is not a Websocket server.Thanks again.
