### ISSUE TITLE
ValueError: Invalid async_mode specified

### ISSUE THREAD

**Issue by halcyonjuly7** [miguelgrinberg/Flask-SocketIO#233]
Im using the flask app_factory method to initialize the app like this

```python
socketio.init_app(app, async_mode="eventlet")
```

and it gives me the error above. this has never happened before. whats going on?

Did something change specifiying an async_mode that I am not aware of?

**Comment by miguelgrinberg** [comment]
Maybe you don't have eventlet installed?

**Comment by halcyonjuly7** [comment]
I was coming from windows and pip froze my modules to a requirements.txt file and transferred it to linux thinking it would be smooth sailing.

upon installing the modlues in the requirements.txt file to Linux there where compilation errors which led to a installing half of the modules in the requirements.txt successfully and the either half not.

and whats was odd because in my virtualenv eventlet was installed because I opened up an interpreter and it imported eventlet w/out errors

but the problem is Linux based and not a flask-socketio issue.

**Comment by RajaSureshAditya** [comment]
hi I am using the SocketIo in the following way and tried to package in exe using pyinstaller
from flask_socketio import SocketIO, emit, disconnect
async_mode = None
socketio = SocketIO(app, async_mode='eventlet')
but I was getting the below error even I have installed evenlet 
error is 
Traceback (most recent call last):
  File "run.py", line 51, in <module>
    socketio = SocketIO(app, async_mode='eventlet')
  File "site-packages\flask_socketio\__init__.py", line 162, in __init__
  File "site-packages\flask_socketio\__init__.py", line 213, in init_app
  File "site-packages\socketio\server.py", line 89, in __init__
  File "site-packages\engineio\server.py", line 122, in __init__
ValueError: Invalid async_mode specified
[1536] Failed to execute script run

**Comment by miguelgrinberg** [comment]
@RajaSureshAditya did you add eventlet to your installation?

**Comment by miguelgrinberg** [comment]
@RajaSureshAditya I have never used pyinstaller myself, but [this issue](https://github.com/miguelgrinberg/python-socketio/issues/35) has a discussion among people who had. Hopefully that will give you some pointers.

**Comment by RajaSureshAditya** [comment]
ok  @miguelgrinberg  ThanQ for the quick response I will follow them

**Comment by RajaSureshAditya** [comment]
Hi @miguelgrinberg I trying to run the exe but it throwing error saying 
jinja2.exceptions.TemplateNotFound
jinja2.exceptions.TemplateNotFound: swagger-ui.html

I think i was not able to package the Jinja2 package into the pyinstaller can you please see the code 
I am trying to package the application using these packages in requirements.txt
aniso8601==2.0.1
bcrypt==3.1.3
cffi==1.10.0
click==6.7
python-docx==0.8.6
Flask==0.12.1
Flask-Bcrypt==0.7.1
flask-restplus==0.9.2
Flask-SocketIO==2.9.6
ipaddr==2.2.0
itsdangerous==0.24
Jinja2==2.9.6
jsonschema==2.6.0
MarkupSafe==1.0
pycparser==2.17
PyJWT==1.4.2
python-engineio==2.0.4
python-socketio==1.9.0
pytz==2018.3
requests==2.13.0
six==1.10.0
SQLAlchemy==1.1.9
Werkzeug==0.12.1
flask-cors==3.0.3

**Comment by miguelgrinberg** [comment]
Well, that is unrelated to Socket.IO, so I don't know. Sounds like one of your dependencies needs this file to be in the package. Maybe `python-docx`?

**Comment by yingshaoxo** [comment]
Maybe it's just as simple as importing that module like this: `from engineio.async_drivers import gevent`

https://stackoverflow.com/a/55642042/8667243
