### ISSUE TITLE
Close server gracefully

### ISSUE THREAD

**Issue by christopher-abastar** [miguelgrinberg/Flask-SocketIO#237]
Hi, 

I'm using eventlet and did a monkey patch. Now after doing that, I tried to run all my unit tests via nosetests. It seems to be working fine but the test doesn't exit. I have to do a CTRL+C for it to terminate and receive the a keyboard interrupt. 

I tried to do a socketio.stop() upon the on tearDown of testcases, but i'm getting an error of "raise SystemExit" error. Is there a way to stop socketio threads successfully during testing?

Regards,

**Comment by miguelgrinberg** [comment]
I guess it depends on how you wrote your unit tests. Are you using the test client or running a real server?

**Comment by christopher-abastar** [comment]
I haven't used the test client, also i haven't implemented any test yet for the socketio module. I just included the following in the my app:

```python
socketio = SocketIO(app, async_mode='eventlet', message_queue=redis_url, channel="websocket")
```
And immediately started the my old test cases to see if it was affected by any eventlet monkey patch.

Thanks for the quick reply.

**Comment by miguelgrinberg** [comment]
I'll leave this issue open and consider exposing and documenting a way to gracefully exit the socketio server.

**Comment by PierrePaul** [comment]
I get the same issue when providing the ```message_queue``` parameter. It becomes troublesome when automating deployment. It's not limited to UnitTests. In my case, it's when running Flask-migrate (via flask-script).

**Comment by PierrePaul** [comment]
Adding ```daemon=True``` to the thread initialization seems to be fixing my issue, but I have no idea if it's a good idea...

```python
def start_background_task(self, target, *args, **kwargs):
        th = getattr(self.async['threading'],
                     self.async['thread_class'])(target=target, args=args,
                                                 kwargs=kwargs, daemon=True)
```

https://github.com/miguelgrinberg/python-engineio/blob/master/engineio/server.py#L267

**Comment by miguelgrinberg** [comment]
The `stop()` method referenced in the original post needs to be called from a handler. The way to stop the server is to create a request handler and call stop from there. After that you can join the thread that runs the server to wait for it to exit gracefully.
