### ISSUE TITLE
client connecting only on async_mode='threading'

### ISSUE THREAD

**Issue by oldmonkABA** [miguelgrinberg/Flask-SocketIO#242]
I am new to flask and trying to learn the flask-socketio.I downloaded the example app.py and the template/index.html  

when i run app.py, by default it chooses 'async_mode is eventlet'
After running app.py, if i point my browser to http://localhost:5000 it does not connect to the server.
It eventually times out
The server also does not receive any connect requests.

However, if i force the async_mode= 'threading', then the whole example works fine.

pip freeze returns 

eventlet==0.18.4
Flask==0.10.1
Flask-SocketIO==2.2
gevent==1.1.0
gevent-websocket==0.9.5
greenlet==0.4.9
itsdangerous==0.24
Jinja2==2.8
MarkupSafe==0.23
python-engineio==0.9.0
python-socketio==1.1
six==1.10.0
Werkzeug==0.11.4

**Comment by christopher-abastar** [comment]
Not sure if it helps but you might wanna try removing gevent stuff from the packages and use eventlet.

**Comment by miguelgrinberg** [comment]
@oldmonkABA let me know what browser are you using, and also include the output of the command `pip freeze`.

**Comment by oldmonkABA** [comment]
@miguelgrinberg I am using Chrome Version 46.0.2490.86 running on kubuntu . I had attached partial output of pip freeze .. here i am attaching the whole output

alabaster==0.7.6                                                                                                                                                                                           
appnope==0.1.0                                                                                                                                                                                             
apt-xapian-index==0.46                                                                                                                                                                                     
argh==0.26.1                                                                                                                                                                                               
astroid==1.2.1                                                                                                                                                                                             
Babel==2.0                                                                                                                                                                                                 
backports.ssl-match-hostname==3.4.0.2                                                                                                                                                                      
beautifulsoup4==4.3.2                                                                                                                                                                                      
bicyclerepair==0.9                                                                                                                                                                                         
boto==2.39.0                                                                                                                                                                                               
brewer2mpl==1.4.1
bz2file==0.98
certifi==2015.4.28
characteristic==0.1.0
chardet==2.3.0
colorama==0.3.3
configobj==5.0.6
cvxopt==1.1.6
cvxpy==0.1
Cython==0.21.1
decorator==4.0.2
dirspec==13.10
dnspython==1.12.0
docopt==0.6.2
docutils==0.12
EasyProcess==0.1.6
ecdsa==0.11
ecos==1.0.1
eventlet==0.18.4
evernote==1.25.1
Flask==0.10.1
Flask-SocketIO==2.2
funcsigs==0.4
functools32==3.2.3.post2
fuse-python==0.2.1
future==0.14.3
gensim==0.12.4
gevent==1.1.0
gevent-websocket==0.9.5
ggplot==0.6.8
GnuPGInterface==0.3.2
gnureadline==6.3.3
greenlet==0.4.9
gyp==0.1
html5lib==0.999
httplib2==0.9
httpretty==0.8.10
importlib==1.0.3
ipykernel==4.0.3
ipyparallel==4.0.2
ipython==4.0.0
ipython-genutils==0.1.0
itsdangerous==0.24
Jinja2==2.8
joblib==0.8.3
jsonschema==2.5.1
jupyter-client==4.0.0
jupyter-core==4.0.4
keyring==4.0
launchpadlib==1.10.3
lazr.restfulclient==0.13.4
lazr.uri==1.0.3
logilab-common==0.62.0
lxml==3.4.2
MarkupSafe==0.23
matplotlib==1.4.2
mercurial==3.1.2
mistune==0.7
mock==1.3.0
mpltools==0.2.dev0
mysql-connector-python==1.2.3
MySQL-python==1.2.3
mysql-utilities==1.3.5
nbconvert==4.0.0
nbformat==4.0.0
ndg-httpsclient==0.4.0
networkx==1.9.1
nltk==3.0.0
nose==1.3.7
notebook==4.0.2
numexpr==2.4
numpy==1.9.2
numpydoc==0.5
oauth==1.0.1
oauth2==1.9.0.post1
oauthlib==0.6.1
openpyxl==1.7.0
PAM==0.4.2
pandas===0.15.1-228-g0a5e6c9
paramiko==1.15.1
path.py==7.6.1
pathtools==0.1.2
patsy==0.3.0
pbr==1.5.0
pdfminer==20110515
pdftables==0.0.3
pep8==1.5.7
pexpect==3.3
pickleshare==0.5
Pillow==2.7.0
praw==3.2.1
psutil==2.1.1
PyAlgoTrade==0.15
pyasn1==0.1.8
pyasn1-modules==0.0.5
pycrypto==2.6.1
pycups==1.9.72
pycurl==7.19.5
pydot==1.0.32
pyflakes==0.8.1
Pygments==1.6
pygobject==3.14.0
pyinotify==0.9.4
pylint==1.3.1
pymc==2.3.4
pyodbc==3.0.10
PyOpenGL==3.1.0
pyOpenSSL==0.15.1
pyparsing==2.0.3
PyPDF2==1.25.1
pypdfocr==0.8.2
pyreadline==2.0
pyserial==2.6
pysmbc==1.0.15.3
pysqlite==2.6.3
python-apt===0.9.3.11build1
python-dateutil==2.2
python-debian==0.1.22
python-engineio==0.9.0
python-socketio==1.1
pytz==2014.9
pyudev==0.16.1
PyVirtualDisplay==0.1.5
pyxdg==0.25
PyYAML==3.11
pyzmq==14.7.0
qtconsole==4.0.1
redis==2.10.5
reportlab==3.2.0
requests==2.8.1
roman==2.0.0
rope==0.10.2
scikit-learn==0.16.1
scipy==0.14.1
SecretStorage==2.1.1
selenium==2.48.0
service-identity==1.0.0
simplegeneric==0.8.1
simplejson==3.8.0
six==1.10.0
smart-open==1.3.2
snowballstemmer==1.2.0
Sphinx==1.3.1
sphinx-rtd-theme==0.1.8
spyder==2.3.2
SQLAlchemy==1.0.8
statsmodels==0.5.0
stop-words==2015.2.23.1
tables==3.1.1
termcolor==1.1.0
terminado==0.5
testpath==0.2
tornado==4.2.1
traceback2==1.4.0
traitlets==4.0.0
Twisted-Core==14.0.2
Twisted-Web==14.0.2
UnbalancedDataset==0.1
unittest2==1.1.0
update-checker==0.11
urllib3==1.9.1
virtualenv==13.1.2
wadllib==1.3.2
watchdog==0.8.3
Werkzeug==0.11.4
Whoosh==2.7.0
wikipediafs==0.0.0
wxPython==2.8.12.1
wxPython-common==2.8.12.1
xkit==0.0.0
xlrd==0.9.2
xlwt==0.7.5
zope.interface==4.1.1

**Comment by miguelgrinberg** [comment]
Okay, nothing out of the ordinary in your virtualenv. Can you please run the server with logging enabled? Add `engineio_logger=True` to the `SocketIO` constructor.

**Comment by oldmonkABA** [comment]
I modified the constructor.It now looks as

socketio = SocketIO(app, async_mode=async_mode,engineio_logger=True)

My shell shows

async_mode is eventlet
Server initialized for eventlet.
 * Restarting with inotify reloader
async_mode is eventlet
Server initialized for eventlet.
 * Debugger is active!
 * Debugger pin code: 146-939-421
(10726) wsgi starting up on http://127.0.0.1:5000

After that nothing..

In the browser i type http://127.0.0.1:5000
It does not connect.

**Comment by miguelgrinberg** [comment]
Can you get a simple flask application to run and let you connect? Try the
seven line example from the flask documentation.

**Comment by oldmonkABA** [comment]
Yup. Since yesterday I have been trying different examples.
I can get the basic flask application to run. 
I can get basic flask-socketio  websocket application also running.

The problem crops up when i try to get the async application running, which is what the example app.py is trying to do. The reply is sent from a thread.This is where things dont work.

My observations are as follows

* if in the example I make async_mode='threading' the whole application works as expected.

* if in the example, I make async_mode='eventlet', the browser does not connect.

* if in the example, I make async_mode= 'eventlet' and comment the eventlet.monkey_patch() line,
then the browser connects. However, the messages that are generated at the server no longer reach the browser.

I found the following question in stackoverflow:
http://stackoverflow.com/questions/34581255/python-flask-socketio-send-message-from-thread-not-always-working

However, the solution refers back to your flask-socketio example.

thank you so much for taking time to respond back

**Comment by christopher-abastar** [comment]
Hello,

could you trying patching eventlet at the start of your app?

This is from their docs.

> 
It is important to call monkey_patch() as early in the lifetime of the application as possible. Try to do it as one of the first lines in the main module. The reason for this is that sometimes there is a class that inherits from a class that needs to be greened – e.g. a class that inherits from socket.socket – and inheritance is done at import time, so therefore the monkeypatching should happen before the derived class is defined. It’s safe to call monkey_patch multiple times.

**Comment by oldmonkABA** [comment]
@christopher-abastar 
I am running the exact same code as given in this repo.

It already has eventlet.monkey_patch().

My observation is that if i dont comment the monkey_patch() then there is no communication between the browser and the server

However if i comment out that line then browser can communicate to server, however the reply from server does not reach the browser.

**Comment by oldmonkABA** [comment]
i created a fresh virtual env and reinstall flask , flask-socketio and eventlet. Things are working fine .
I guess some package in the old virtual env was conflicting

**Comment by miguelgrinberg** [comment]
@oldmonkABA okay, good to know.
