### ISSUE TITLE
error 400 when using accent in client side.

### ISSUE THREAD

**Issue by gamugamu** [miguelgrinberg/Flask-SocketIO#246]
I'm encountering problems when I'm sending  message with accents from client side to the server side. Everytime I send accents to the server, I've got a 400 error code.

I have tested with the js server side / js client and it worked fine. But when I switch to flaskSocketio, I've got a 400 error code from the client side, but no error output from  flaskSocketio, so I can't debug it.
Here what I got from the js console when I emit "é": 

`https://10.0.0.2:5001/socket.io/?EIO=3&transport=polling&t=LEOipev&sid=9b1fde2fc3324fec9e8bd8e099ab14a2 400 (BAD REQUEST)Request.create @ socket.io.js:1456Request @ socket.io.js:1369XHR.request @ socket.io.js:1297XHR.doWrite @ socket.io.js:1310(anonymous function) @ socket.io.js:1829(anonymous function) @ socket.io.js:3291proxy @ socket.io.js:2223(anonymous function) @ socket.io.js:3306(anonymous function) @ socket.io.js:3286exports.encodePacket @ socket.io.js:3085encodeOne @ socket.io.js:3285eachWithIndex @ socket.io.js:3304map @ socket.io.js:3311exports.encodePayload @ socket.io.js:3290Polling.write @ socket.io.js:1828Transport.send @ socket.io.js:857Socket.flush @ socket.io.js:568Socket.sendPacket @ socket.io.js:628Socket.write.Socket.send @ socket.io.js:588(anonymous function) @ socket.io.js:4745Encoder.encode @ socket.io.js:6044Manager.packet @ socket.io.js:4743Socket.packet @ socket.io.js:5092Socket.emit @ socket.io.js:5073$scope.chatClientPressed @ chat:40(anonymous function) @ angular.js:10288(anonymous function) @ angular.js:18086Scope.$eval @ angular.js:12045Scope.$apply @ angular.js:12145(anonymous function) @ angular.js:18085(anonymous function) @ angular.js:2626forEach @ angular.js:311eventHandler @ angular.js:2625
`

I'm using python 2.7, and my script is encoded as # coding: utf8
flask-socketIO 2.1 and socket-io-client 1.4.5

**Comment by miguelgrinberg** [comment]
Confirmed. Only happens when using polling, though. If I wait until the transport is upgraded to websocket, then I can send "é" back and forth. Can you confirm this is true for you as well?

To delay the emit, I have changed it to this:

    window.setTimeout(function() { socket.emit('my event', {data: 'é'}) }, 5000);

**Comment by gamugamu** [comment]
Unfortunatly, I can't test it for the moment. I'm using https connection and switching to gevent or eventlet cause for some reason SSL handshake error (seems like I must switch to python > 2.7). So now I'm still using werkzeug for the moment and it seems it is not switching to websocket, even with a 10 seconds delay.

**Comment by miguelgrinberg** [comment]
Sorry it took me so long to figure this one out. It runs out there is a bug in the JavaScript engine.io client that makes it send text payloads incorrectly encoded. Instead of sending them as utf-8, it applies a second utf-8 encoding to them, so the server receives an invalid packet. See https://github.com/socketio/engine.io/issues/315 for details.

I have added a workaround for this bug in version 1.0.3 of package python-engineio. The server now tries to detect if the packet came with a double utf-8 encoding applied and in that case applies a double decode to fix it.
