### ISSUE TITLE
Document proper way to disconnect gracefully when the user leaves or closes the page

### ISSUE THREAD

**Issue by miguelgrinberg** [miguelgrinberg/Flask-SocketIO#249]
I need to investigate if the `unload` event is an appropriate place to put a disconnect call, or if there is a better alternative.

**Comment by kingdion** [comment]
I understand this is an old topic and disregard this if a better alternative has been found, but would onbeforeunload be a better place to put a disconnection call? (called before unload), as it would allow you to send any final payloads before the final closing of the browser?

**Comment by miguelgrinberg** [comment]
The disconnect event is triggered without you having to do anything, so this is not needed. If you need to do something other than just disconnecting, then yes, the before unload event is a good place to do it.

**Comment by miguelgrinberg** [comment]
No need to document anything, the disconnect just happens when the user leaves.
