### ISSUE TITLE
emit after join spawned thread causing websocket session to close

### ISSUE THREAD

**Issue by MaxBear** [miguelgrinberg/Flask-SocketIO#250]
I'm running into a strange scenario, i have been debugging for a while to pin point the cause to the following, however, I cannot tell why this is happening and how to fix it, hopefully someone can point me to the right direction. 

Attached is server handler for client request for event "stop session". When server receive this emitted request from client, it will try to join spawned thread started by another "start session" handler. After this finishes, it will emit a response message to browser (client), browser will then print it out on webpage. The emit after thread join is causing websocket session released, when message is sent to client, this will trigger an exception. But if I comment the emit out as the following, the session will not get disconnected, everything runs fine. 

Anyone knows why ? 

    @socketio.on('stop session', namespace='/test')
    def stop_record():
        session['receive_count'] = session.get('receive_count', 0) + 1 
        global thread
        if thread is not None: 
            thread.join()
            thread = None
            #emit('my response',
            #     {'data': 'Current session stopped', 'count': session['receive_count']})
        else:
            emit('my response',
                 {'data': 'No active session found', 'count': session['receive_count']})

**Comment by miguelgrinberg** [comment]
How long does it take for the `join` call to return? If that is blocking for too long that could be preventing other communications to continue. Normally if you want to stop a background thread you send some sort of signal to the thread to indicate it needs to exit. I don't see that in your code.

**Comment by MaxBear** [comment]
Here is thread implementation, I am confused as why when emit uncommented, the session is disconnected from time from time, otherwise, it will not... is this a client issue ? not convinced....

class Agent(threading.Thread):
    def __init__(self, name='agent'):
        self._stopevent = threading.Event()
        threading.Thread.__init__(self, name=name)
        self.daemon = True

    def run(self):
        c = SSEClient(...)
        for msg in c:
            socketio.emit('my response',
...
                          namespace='/test')
            if self._stopevent.isSet( ):
                break
        c.disconnect()

    def join(self, timeout=None):
            """ Stop the thread and wait for it to end. """
            self._stopevent.set( )
            threading.Thread.join(self, timeout)

**Comment by MaxBear** [comment]
Better formatted version of the code snippet: 

class Agent(threading.Thread):

    def __init__(self, name='agent'):
        self._stopevent = threading.Event()
        threading.Thread.__init__(self, name=name)
        self.daemon = True

    def run(self):
        c = SSEClient(..)
        for msg in c:
            socketio.emit('my response',
                          {'data': msg.data},
                          namespace='/test')
            if self._stopevent.isSet( ):
                break
        # destroy token, stop session
        c.disconnect()

    def join(self, timeout=None):
            """ Stop the thread and wait for it to end. """
            self._stopevent.set( )
            threading.Thread.join(self, timeout)

**Comment by miguelgrinberg** [comment]
Can you show me the exception that you get when you call emit after join?

**Comment by MaxBear** [comment]
93.93.96.102 - - [25/Mar/2016 18:53:12] "GET /socket.io/?EIO=3&transport=polling&t=1458928392146-84&sid=d718daa456a24b2bafe64900f2a954d5 HTTP/1.1" 200 -
d718daa456a24b2bafe64900f2a954d5: Received packet MESSAGE data 2/test,["stop session"]

[2016-03-25 18:53:19.586153] Get request to stop session <= my debug message

8188e249bd0041eb89f62d2ec4779b95: Received packet PING data None
8188e249bd0041eb89f62d2ec4779b95: Sending packet PONG data None

93.93.96.102 - - [25/Mar/2016 18:53:30] "POST /socket.io/?EIO=3&transport=polling&t=1458928410488-197&sid=8188e249bd0041eb89f62d2ec4779b95 HTTP/1.1" 200 -
93.93.96.102 - - [25/Mar/2016 18:53:30] "GET /socket.io/?EIO=3&transport=polling&t=1458928392248-196&sid=8188e249bd0041eb89f62d2ec4779b95 HTTP/1.1" 200 -

d718daa456a24b2bafe64900f2a954d5: Client is gone, closing socket
('Client disconnected', 'd718daa456a24b2bafe64900f2a954d5')
<= session is closed at this point
[2016-03-25 18:53:41.518582] Client disconnected d718daa456a24b2bafe64900f2a954d5

<= SSEclient emit a heatbeat message
8188e249bd0041eb89f62d2ec4779b95: Sending packet MESSAGE data 2/test,["my response",{"time_stamp":1458928421.517663,"data":"","event":"message","type":"..."}]

93.93.96.102 - - [25/Mar/2016 18:53:41] "GET /socket.io/?EIO=3&transport=polling&t=1458928410852-198&sid=8188e249bd0041eb89f62d2ec4779b95 HTTP/1.1" 200 -

<= thread join executed
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:789: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
[2016-03-25 18:53:48.814034] Closing EventSource connection...
[2016-03-25 18:53:48.814106] EventSource connection is closed
[2016-03-25 18:53:48.814388] About to emit.... <= printed out before emit causing exception


... EXCEPTIONS...
93.93.96.102 - - [25/Mar/2016 18:53:48] "POST /socket.io/?EIO=3&transport=polling&t=1458928399331-86&sid=d718daa456a24b2bafe64900f2a954d5 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1978, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/Flask_SocketIO-2.2-py2.7.egg/flask_socketio/__init__.py", line 37, in __call__
    start_response)
  File "/usr/local/lib/python2.7/dist-packages/engineio/middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 303, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/engineio/server.py", line 244, in handle_request
    socket.handle_post_request(environ)
  File "/usr/local/lib/python2.7/dist-packages/engineio/socket.py", line 96, in handle_post_request
    self.receive(pkt)
  File "/usr/local/lib/python2.7/dist-packages/engineio/socket.py", line 48, in receive
    self.server._trigger_event('message', self.sid, pkt.data)
  File "/usr/local/lib/python2.7/dist-packages/engineio/server.py", line 330, in _trigger_event
    return self.handlers[event](*args)
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 429, in _handle_eio_message
    self._handle_event(sid, pkt.namespace, pkt.id, pkt.data)
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 371, in _handle_event
    r = self._trigger_event(data[0], namespace, sid, *data[1:])
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 397, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/usr/local/lib/python2.7/dist-packages/Flask_SocketIO-2.2-py2.7.egg/flask_socketio/__init__.py", line 199, in _handler
    self.server.environ[sid]['saved_session'] = {}
KeyError: 'd718daa456a24b2bafe64900f2a954d5'
93.93.96.102 - - [25/Mar/2016 18:53:49] "POST /socket.io/?EIO=3&transport=polling&t=1458928428941-87&sid=d718daa456a24b2bafe64900f2a954d5 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1978, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/Flask_SocketIO-2.2-py2.7.egg/flask_socketio/__init__.py", line 37, in __call__
    start_response)
  File "/usr/local/lib/python2.7/dist-packages/engineio/middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 303, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/engineio/server.py", line 242, in handle_request
    socket = self._get_socket(sid)
  File "/usr/local/lib/python2.7/dist-packages/engineio/server.py", line 340, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'

**Comment by miguelgrinberg** [comment]
The problem is, I think, that your `join` call is blocking and preventing the constant exchange of messages from happening.

Instead of using `join`, I recommend that in your `stop session` handler you just signal the thread to stop and return right away. Then in the thread you can send the `current session stopped` when you exit the loop. Would that work?

**Comment by MaxBear** [comment]
Yes, that fixed it. Thanks a lot, Miguel.
