### ISSUE TITLE
Hyphenated event names aren't registered

### ISSUE THREAD

**Issue by LaurencePutterman** [miguelgrinberg/Flask-SocketIO#252]
I had an event on the server called 'send-message' that refused to register when my clients emitted to it. As soon as I changed the event name to 'sendpm', it worked as I expected.

Interestingly, the javascript client supports listening on hyphenated messages.

**Comment by miguelgrinberg** [comment]
I can't reproduced here. I changed the `"my event"` event in the example app to `"my-event"` and everything works as expected.

**Comment by LaurencePutterman** [comment]
Hmm. I'm not sure. Admittedly, this is my first project with SocketIO so I may be doing some things wrong.  
Here's my requirements.txt 

```
eventlet==0.18.4
Flask==0.10.1
Flask-SocketIO==2.2
greenlet==0.4.9
gunicorn==19.4.5
itsdangerous==0.24
Jinja2==2.8
MarkupSafe==0.23
python-engineio==0.9.0
python-socketio==1.2
redis==2.10.5
six==1.10.0
Werkzeug==0.11.5

```


Here's the relevant serverside code

```
from flask import Flask, render_template, request
import eventlet
from flask.ext.socketio import SocketIO, emit, join_room, leave_room
import json
app = Flask(__name__)
socketio = SocketIO(app)

usersOnline = {}
registered = []

@socketio.on('sendpm')
def handle_send_message(data):
	print usersOnline
	sender = data['sender']
	recipient = data['recipient']
	message = data['message']
	sid = getSIDFromUsername(usersOnline,recipient)
	toSend = sender+": "+message
	print 'Send message from %s to %s with body %s' %(sender,recipient,message)
	print sid
	print request.sid
	emit('receive-message',{'chatWith':sender,'message':toSend},room=sid)
	emit('receive-message',{'chatWith':recipient,'message':toSend},room=request.sid)


if __name__ == '__main__':
   	socketio.run(app)

```
and here's the clientside code that sends the event

`app.socket.emit('sendpm',{sender:this.get('username'), recipient:recipient, message:message});`


Aside from this, I'm not sure what to say. When the event was called 'send-message', the server didn't respond to it. As soon as I changed it to 'sendpm', it started working.

**Comment by miguelgrinberg** [comment]
Do you want to put the complete project, including client side files on a repo that I can checkout and test here?
