### ISSUE TITLE
Does not work with socket.io-client 1.4.5 from npm

### ISSUE THREAD

**Issue by ripitrust** [miguelgrinberg/Flask-SocketIO#253]
Hi @miguelgrinberg 

Thanks for your awesome library
It seems that I can't get it to work with npm installed socket.io-client 1.4.5
The server side simply can't receive any event emitted from the client

 and according to https://github.com/miguelgrinberg/Flask-SocketIO/issues/219 and  https://github.com/miguelgrinberg/Flask-SocketIO/issues/247. You mentioned there is currently no solution that work with both flask and npm socket.io-client right?

**Comment by miguelgrinberg** [comment]
I'm still investigating this issue, but the workaround is to use WebSocket instead of starting with long-polling and later upgrade to WS. See https://github.com/miguelgrinberg/Flask-SocketIO/issues/219#issuecomment-177882354.

**Comment by ripitrust** [comment]
@miguelgrinberg  I have already using websocket and still can't get response 
Could it be my problem

**Comment by miguelgrinberg** [comment]
@ripitrust it's not about using websocket, it's about initiating the connection with websocket from the start. The normal way a socket.io connection is established is starting with long-polling, then upgrading to websocket. The comment I referenced shows how to tell the socket.io-client to initiate with websocket.

**Comment by ripitrust** [comment]
@miguelgrinberg     Thanks for your reply 
I have done exactly that as mentioned in https://github.com/miguelgrinberg/Flask-SocketIO/issues/219#issuecomment-177882354

However I am not around my working computer,  I will post my code when I get back

**Comment by ripitrust** [comment]
@miguelgrinberg  Here is my code:

In the client side, I use it together with react, I put the following code in one of a button component onClick event

Client Side:
`import io from 'socket.io-client';`
`var socket = io.connect('http://' + document.domain + ':' + location.port + '/status',{ transports: ['websocket']});`
`socket.emit('message', { data: 'hello world' });`

in the server side, I followed the flask_socketio tutorial:

`@socketio.on('message')`
`def handle_message(message):`
    `print('received message: ' + message)`


But when I click on the button, the server side does not receive any event:
Chrome console:
> socket.io-client:socket transport is open - connecting +688ms

Python console:
> (1011) accepted ('127.0.0.1', 49829)

No event is received and print out from the console

Does this issue comes with the socket.io-client library?

**Comment by miguelgrinberg** [comment]
You need to enable logging to see what's going on. On the server, add `engineio_logger=True` to the `SocketIO` constructor. On the client, type `localStorage.debug = '*';` on your browser's console.

**Comment by ripitrust** [comment]
@miguelgrinberg  Thanks for your reply
I now get something like this:
Server:

> (811) accepted ('127.0.0.1', 50416)
> a2cf80fcef9943108f2798989ccdb9b8: Sending packet OPEN data {'pingInterval': 25000, 'pingTimeout': 60000, 'upgrades': [], 'sid': 'a2cf80fcef9943108f2798989ccdb9b8'}
> a2cf80fcef9943108f2798989ccdb9b8: Sending packet MESSAGE data 0
> a2cf80fcef9943108f2798989ccdb9b8: Received request to upgrade to websocket
> a2cf80fcef9943108f2798989ccdb9b8: Upgrade to websocket successful
> a2cf80fcef9943108f2798989ccdb9b8: Received packet MESSAGE data 0/status
> a2cf80fcef9943108f2798989ccdb9b8: Sending packet MESSAGE data 0/status
> a2cf80fcef9943108f2798989ccdb9b8: Received packet MESSAGE data 2/status,["message",{"my":"data"}]
> 4f928dfde6614d21ba0d8f7274a21bd4: Received packet PING data None
> 4f928dfde6614d21ba0d8f7274a21bd4: Sending packet PONG data None

Client:

> engine.io-client:socket socket receive: type "open", data "{"pingInterval":25000,"pingTimeout":60000,"upgrades":[],"sid":"a2cf80fcef9943108f2798989ccdb9b8"}" +7ms
> main.bundle.js:43341 engine.io-client:socket socket open +0ms
> main.bundle.js:43341 socket.io-client:manager open +1ms
> main.bundle.js:43341 socket.io-client:manager cleanup +0ms
> main.bundle.js:43341 socket.io-client:socket transport is open - connecting +0ms
> main.bundle.js:43341 socket.io-client:manager writing packet {"type":0,"nsp":"/status"} +0ms
> main.bundle.js:43341 socket.io-parser encoding packet {"type":0,"nsp":"/status"} +1ms
> main.bundle.js:43341 socket.io-parser encoded {"type":0,"nsp":"/status"} as 0/status +0ms
> main.bundle.js:43341 engine.io-client:socket flushing 1 packets in socket +1ms
> main.bundle.js:43341 engine.io-client:socket socket receive: type "message", data "0" +0ms
> main.bundle.js:43341 socket.io-parser decoded 0 as {"type":0,"nsp":"/"} +1ms
> main.bundle.js:43341 engine.io-client:socket socket receive: type "message", data "0/status" +5ms
> main.bundle.js:43341 socket.io-parser decoded 0/status as {"type":0,"nsp":"/status"} +1ms
> main.bundle.js:43341 socket.io-client:manager writing packet {"type":2,"data":["message",{"my":"data"}],"options":{"compress":true},"nsp":"/status"} +2ms
> main.bundle.js:43341 socket.io-parser encoding packet {"type":2,"data":["message",{"my":"data"}],"options":{"compress":true},"nsp":"/status"} +1ms
> main.bundle.js:43341 socket.io-parser encoded {"type":2,"data":["message",{"my":"data"}],"options":{"compress":true},"nsp":"/status"} as 2/status,["message",{"my":"data"}] +0ms
> main.bundle.js:43341 engine.io-client:socket flushing 1 packets in socket +1ms
> main.bundle.js:43341 engine.io-client:socket writing ping packet - expecting pong within 60000ms +23s
> main.bundle.js:43341 engine.io-client:socket flushing 1 packets in socket +0ms
> main.bundle.js:43341 engine.io-client:socket socket receive: type "pong", data "undefined" +2ms


It seems that the connection is already open, but what is the reason that server side did not print out the message?

besides, if I emit some event `emit('hello', 'world')` from server side, and listen to it from the client side, it still did not show up.

**Comment by miguelgrinberg** [comment]
I don't see anything wrong in these logs. Messages are being exchanged just fine.

Connection (client -> server):

    main.bundle.js:43341 socket.io-parser encoded {"type":0,"nsp":"/status"} as 0/status +0ms
    a2cf80fcef9943108f2798989ccdb9b8: Received packet MESSAGE data 0/status

Reply: (server -> client):

    a2cf80fcef9943108f2798989ccdb9b8: Sending packet MESSAGE data 0/status
    main.bundle.js:43341 engine.io-client:socket socket receive: type "message", data "0/status" +5ms

application data (client -> server):

    main.bundle.js:43341 socket.io-parser encoded {"type":2,"data":["message",{"my":"data"}],"options":{"compress":true},"nsp":"/status"} as 2/status,["message",{"my":"data"}] +0ms
    a2cf80fcef9943108f2798989ccdb9b8: Received packet MESSAGE data 2/status,["message",{"my":"data"}]

So where is the problem?

**Comment by ripitrust** [comment]
@miguelgrinberg 
Yes it looks like it is working fine
But In my server side handler,  the `handle_message` function do not get called at all. It does not print out the message as coded.
In fact, what ever I put into this function is not executed at all

Am I missing something ?

**Comment by miguelgrinberg** [comment]
Try using a different name other than `'message'` for your event. That is a reserved name, socket.io uses it for string payloads.

**Comment by ripitrust** [comment]
I tried but it is the same 

server:
```
@socketio.on('noconflict', namespace='/status')
def handle_message(message):
    print('received message: ' + message)
    print('reveiced')
    emit('hello', 'world')
```

client:
 ```
var socket = io.connect('http://' + document.domain + ':' + location.port + '/status',{ transports: ['websocket']});
    
    socket.emit('noconflict', { my: 'data' });

    socket.on('hello',(data) =>{
        
        console.log(data);
        
    });
```

Nothing gets printed out, nothing gets emitted and client side receive nothing:

> 375ee7bbb2b0408495a412a5f8b45b82: Sending packet OPEN data {'pingInterval': 25000, 'pingTimeout': 60000, 'upgrades': [], 'sid': '375ee7bbb2b0408495a412a5f8b45b82'}
> 375ee7bbb2b0408495a412a5f8b45b82: Sending packet MESSAGE data 0
> 375ee7bbb2b0408495a412a5f8b45b82: Received request to upgrade to websocket
> 375ee7bbb2b0408495a412a5f8b45b82: Upgrade to websocket successful
> 375ee7bbb2b0408495a412a5f8b45b82: Received packet MESSAGE data 0/status
> 375ee7bbb2b0408495a412a5f8b45b82: Sending packet MESSAGE data 0/status
> 375ee7bbb2b0408495a412a5f8b45b82: Received packet MESSAGE data 2/status,["noconflict",{"my":"data"}]
>


> engine.io-client:socket socket receive: type "message", data "0" +2ms
> main.bundle.js:43341 socket.io-parser decoded 0 as {"type":0,"nsp":"/"} +2ms
> main.bundle.js:43341 engine.io-client:socket socket receive: type "message", data "0/status" +2ms
> main.bundle.js:43341 socket.io-parser decoded 0/status as {"type":0,"nsp":"/status"} +1ms
> main.bundle.js:43341 socket.io-client:manager writing packet {"type":2,"data":["noconflict",{"my":"data"}],"options":{"compress":true},"nsp":"/status"} +1ms
> main.bundle.js:43341 socket.io-parser encoding packet {"type":2,"data":["noconflict",{"my":"data"}],"options":{"compress":true},"nsp":"/status"} +0ms
> main.bundle.js:43341 socket.io-parser encoded {"type":2,"data":["noconflict",{"my":"data"}],"options":{"compress":true},"nsp":"/status"} as 2/status,["noconflict",{"my":"data"}] +1ms

**Comment by miguelgrinberg** [comment]
Can you share the complete application, so that I can try it here?

**Comment by ripitrust** [comment]
Please take a look at it here : https://github.com/ripitrust/socketio-debug

I followed the application structure in the flask-socketio-chat example, and put the events.py in  `app/main` directory. and start the application from the outer most `ultron.py`  This makes the socket.io not responsible.

However if I put everything in one python file ( in `app/ultron.py`), it works perfectly.

**Comment by ripitrust** [comment]
@miguelgrinberg 

After a long and painful debugging session, I find out that if I pass `engineio_logger=True` to the `SocketIO()` : `socketio = SocketIO(engineio_logger=True)`,  the handler function will not be executed.

After remove it , it works fine. 

this may be caused by the `engineio.logger`,  not sure if it is intended to be so

**Comment by calbertts** [comment]
I'm having this issue!.. 
I'm just trying to create a simple unit test, but socket.io-client never starts the connection with the server, when I try to do it from another browser tab loading the socket.io script it works, but from NodeJS by using NPM it doesn't work.

Any idea?

**Comment by miguelgrinberg** [comment]
I have finally spent some time debugging this issue. The bug is in the Socket.IO client package, or more specifically in one of its dependencies. My investigation does not point to a bug or incompatibility in this package.

The issue appears to be with the [xmlhttprequest-ssl](https://www.npmjs.com/package/xmlhttprequest-ssl) package, which emulates the browser's XmlHttpRequest object in charge of sending HTTP requests. I'm not sure why, but requests sent with the current version of this package never invoke the response callback. The xmlhttprequest-ssl package is a fork of another package called xmlhttprequest. I have been successful in connecting the socket.io client when replacing the fork with the original package (I needed to fix a couple of things in the socket.io client code to make it work with the original).

Based on what I have found, the fork of this package adds some additional ssl options that the original does not have. I have not found exactly what is the problem in the forked package yet.

**Comment by ripitrust** [comment]
@miguelgrinberg Thank you so much for the work

**Comment by miguelgrinberg** [comment]
Pull request to project engine.io-client with the fix: https://github.com/socketio/engine.io-client/pull/483

**Comment by amckinley** [comment]
I spent some time tcpdump'ing the handshake between the node.js client and various servers. Here's an example of the first response the node.js server sends to the client. After this, the connection proceeds as normal.
```
..F...F.HTTP/1.1 200 OK
Set-Cookie: io=6dRuwN_rdzICjK0PAAAA
Content-Type: text/plain; charset=UTF-8
Content-Length: 100
Access-Control-Allow-Origin: *

Date: Fri, 02 Sep 2016 20:24:06 GMT
Connection: close

97:0{"sid":"6dRuwN_rdzICjK0PAAAA","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":60000}
```
And here's the first response sent by flask-socketio. After this, the client and the server get into a loop and don't proceed with the connection.
```
..yg..yfHTTP/1.1 200 OK
Set-Cookie: io=1c58f1832d064a60b11e270ae778f25b
Content-Type: application/octet-stream
Content-Length: 117
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true

Date: Fri, 02 Sep 2016 20:27:36 GMT
Connection: close

109:0{"sid":"1c58f1832d064a60b11e270ae778f25b","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":60000}2:40
```



As @miguelgrinberg suspected, setting `Content-Type: application/octet-stream` in the response from flask-socketio is causing the node.js client to never finish connecting because it ignores the response body.

**Comment by miguelgrinberg** [comment]
Closing this issue, since my PR to engine.io-client has been merged.
