### ISSUE TITLE
App works fine in Chrome on a desktop, but constant disconnects in Chrome on Android

### ISSUE THREAD

**Issue by justinhopper** [miguelgrinberg/Flask-SocketIO#254]
Hello,

I searched the documented issues and I found others that discussed issues with the server raising KeyError('Session is disconnected'), but I didn't find anybody else that is running into this issue only on mobile devices.  Here's what I have going on.

flask_socketio running on a Raspberry Pi, backend written in Python, serving to a local network.  The app fires various emits and takes various commands from a simple HTML page via emits on the client side.

When I access the app from my desktop (running Chrome on Ubuntu), I see my browser connect to the backend and then the session pretty much holds consistently from then on, never disconnects, even for a week at a time (I left the page up on my desktop for a week and was still receiving emits and able to communicate with the backend).  Here's what I see:

```
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 319-830-029
(13044) wsgi starting up on http://0.0.0.0:5000
(13044) accepted ('192.168.1.5', 42953)
192.168.1.5 - - [13/Apr/2016 01:19:37] "GET / HTTP/1.1" 200 3709 0.046275
192.168.1.5 - - [13/Apr/2016 01:19:37] "GET /socket.io/?EIO=3&transport=polling&t=1460510366286-0 HTTP/1.1" 200 381 0.002740
Starting background thread
192.168.1.5 - - [13/Apr/2016 01:19:37] "POST /socket.io/?EIO=3&transport=polling&t=1460510366307-1&sid=03f510aede124c38900322619c5927ff HTTP/1.1" 200 222 0.005111
(13044) accepted ('192.168.1.5', 42954)
(13044) accepted ('192.168.1.5', 42955)
192.168.1.5 - - [13/Apr/2016 01:19:37] "GET /socket.io/?EIO=3&transport=polling&t=1460510366312-2&sid=03f510aede124c38900322619c5927ff HTTP/1.1" 200 285 0.001369
```

When I connect to the same app via my phone (android) or via my tablet (also android), I get an initial connection and emits from the backend, then no more emits from the backend and the commands from the frontend may or may not work.  I also see GETs from the client constantly, like every second for the polling transport:

```
(13044) accepted ('192.168.1.9', 52656)
(13044) accepted ('192.168.1.9', 52657)
192.168.1.9 - - [15/Apr/2016 19:41:09] "GET / HTTP/1.1" 200 3709 0.006327
192.168.1.9 - - [15/Apr/2016 19:41:10] "GET /socket.io/?EIO=3&transport=polling&t=1460749272573-0 HTTP/1.1" 200 381 0.002661
Starting background thread
192.168.1.9 - - [15/Apr/2016 19:41:10] "POST /socket.io/?EIO=3&transport=polling&t=1460749272693-1&sid=ed3ade4d69cf4f569a6edf166efcfa4b HTTP/1.1" 200 222 0.004582
192.168.1.9 - - [15/Apr/2016 19:41:11] "GET /favicon.ico HTTP/1.1" 404 366 0.004653
192.168.1.9 - - [15/Apr/2016 19:41:11] "GET /socket.io/?EIO=3&transport=polling&t=1460749272731-2&sid=ed3ade4d69cf4f569a6edf166efcfa4b HTTP/1.1" 200 285 0.001459
(13044) accepted ('192.168.1.9', 52663)
192.168.1.9 - - [15/Apr/2016 19:41:11] "GET /socket.io/?EIO=3&transport=polling&t=1460749273196-3&sid=ed3ade4d69cf4f569a6edf166efcfa4b HTTP/1.1" 200 346 0.001313
192.168.1.9 - - [15/Apr/2016 19:41:12] "GET /socket.io/?EIO=3&transport=polling&t=1460749273874-4&sid=ed3ade4d69cf4f569a6edf166efcfa4b HTTP/1.1" 200 332 0.001318
192.168.1.9 - - [15/Apr/2016 19:41:13] "GET /socket.io/?EIO=3&transport=polling&t=1460749274500-5&sid=ed3ade4d69cf4f569a6edf166efcfa4b HTTP/1.1" 200 331 0.001266
192.168.1.9 - - [15/Apr/2016 19:41:13] "GET /socket.io/?EIO=3&transport=polling&t=1460749275110-6&sid=ed3ade4d69cf4f569a6edf166efcfa4b HTTP/1.1" 200 350 0.001481
```

And then eventually I see the session disconnects:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/eventlet/wsgi.py", line 481, in handle_one_response
    result = self.application(self.environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask_socketio/__init__.py", line 37, in __call__
    start_response)
  File "/usr/local/lib/python2.7/dist-packages/engineio/middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 303, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/engineio/server.py", line 223, in handle_request
    socket = self._get_socket(sid)
  File "/usr/local/lib/python2.7/dist-packages/engineio/server.py", line 340, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'
```

So, I'm a little mystified why the app works great in Chrome on a desktop but terrible on a mobile device.  The desktop has a wired connection to the local network, the mobile devices are connected via wifi.  The Raspberry Pi is also connected via wifi.

Thanks for any help, let me know if there's any other information I can give.

**Comment by miguelgrinberg** [comment]
I haven't tested the Android browser much, but for a mobile device that frequently goes to sleep I can see that it is likely that connections get interrupted. Have you taken measures to keep the phone awake, and still see disconnections?

**Comment by justinhopper** [comment]
Thanks for getting back to me.  So the tests I've done on the Android devices, it's not an issue with the device going to sleep, because I get a disconnect within 60 seconds or so of using the frontend with the client.  Actually, looking more at the timestamps of activity now, I see the disconnect comes almost exactly every 60 seconds.  Then a new connection (and new session ID) is established, then 60 seconds later another disconnect happens.

The customer that I'm building this system for is going to be using Apple devices, have you tested much with Apple devices, is this problem specific to Android devices?

It seems that there is definitely some sort of disconnect between the frontend and backend, the server seems to only be seeing the initial session setup, then for some reason isn't seeing all these "polling" GET requests happening every second from the client.  And then on the client end it sees only the initial emit from the backend, then nothing more.

How can I help you debug what's happening here?  I probably need to capture the ping traffic from the client to see if there are pings happening to the backend, and then see if the backend is receiving them?

**Comment by miguelgrinberg** [comment]
There is a significance to 60 seconds. If the server does not receive a PING packet in that time, it decides the client is gone and closes the connection. If the connection always lives for 60 seconds, then that means that the Android browser isn't sending PING packets.

> then for some reason isn't seeing all these "polling" GET requests happening every second from the client

If you are using WebSocket, then after a few exchanges of HTTP requests you will not see any more requests flying through, as the WebSocket connection is a permanent channel. If you are not using WebSocket in your server, then yes, you should see a constant stream of GET and POST requests.

**Comment by miguelgrinberg** [comment]
I just tested a connection from an Android phone, and I see no problems. I'm using the example application in this repository, only adapted to listen on `0.0.0.0` instead of localhost. The connection remains active even when the phone's screen goes to sleep. So I'm really at a loss, I'm guessing there must be a problem on your end that makes the connection unreliable?

**Comment by justinhopper** [comment]
I went through and stripped my app down to the bare minimum framework, and encountered no problems on the Android devices.  My app has a background thread running through eventlet, and it emits status updates every half second.  This results in a fair amount of data constantly streaming to the frontend.  I optimized this to only send updates when there is a reading change, and this cut the volume of data down quite a bit and seems to have resolved the problem.  When I was emitting data every half second, I would see errors like these after a couple minutes of use:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/eventlet/wsgi.py", line 481, in handle_one_response
    result = self.application(self.environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask_socketio/__init__.py", line 37, in __call__
    start_response)
  File "/usr/local/lib/python2.7/dist-packages/engineio/middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 303, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/engineio/server.py", line 223, in handle_request
    socket = self._get_socket(sid)
  File "/usr/local/lib/python2.7/dist-packages/engineio/server.py", line 340, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'

192.168.1.16 - - [17/Apr/2016 18:09:49] "GET /socket.io/?EIO=3&transport=polling&t=1460916586013-57&sid=cff7ff8d75644d9ba59c8c4cc23db67d HTTP/1.1" 500 1212 0.007482
Invalid session cff7ff8d75644d9ba59c8c4cc23db67d
192.168.1.16 - - [17/Apr/2016 18:09:51] "POST /socket.io/?EIO=3&transport=polling&t=1460916587780-58&sid=cff7ff8d75644d9ba59c8c4cc23db67d HTTP/1.1" 400 241 0.001749
(17614) accepted ('192.168.1.16', 50487)
f858c3d6baf841348240fcb459ba6c35: Sending packet OPEN data {'pingInterval': 25000, 'pingTimeout': 60000, 'upgrades': ['websocket'], 'sid': 'f858c3d6baf841348240fcb459ba6c35'}
```

I assume those numbers third from the end of the GET and POST request are HTTP Response Codes, and the first is a 500, so Internal Server Error when the front end tried to communicate again, and then a 400 error on the next POST.  Then it re-establishes a new connection, but never seems to be able to fully communicate with the front end.

Now that I've quieted down the emits from the background thread, it seems there are still disconnects after a while (around 5 minutes of inactivity on the Android device), there seems to be no more 400 errors when re-establishing the connection:

```
  File "/usr/local/lib/python2.7/dist-packages/flask_socketio/__init__.py", line 177, in _handler
    app = self.server.environ[sid]['flask.app']
KeyError: '5eff044c5027467e89d1dd525c70ab0b'

192.168.1.16 - - [17/Apr/2016 19:51:39] "GET /socket.io/?EIO=3&transport=websocket&sid=5eff044c5027467e89d1dd525c70ab0b HTTP/1.1" 500 2637 79.916614
a599e845f8464bd7bba3f81e75ffdccd: Sending packet OPEN data {'pingInterval': 25000, 'pingTimeout': 60000, 'upgrades': ['websocket'], 'sid': 'a599e845f8464bd7bba3f81e75ffdccd'}
a599e845f8464bd7bba3f81e75ffdccd: Sending packet MESSAGE data 0
192.168.1.16 - - [17/Apr/2016 19:51:40] "GET /socket.io/?EIO=3&transport=polling&t=1460922698387-17 HTTP/1.1" 200 381 0.004741
a599e845f8464bd7bba3f81e75ffdccd: Received packet MESSAGE data 0/cm
Starting background thread
a599e845f8464bd7bba3f81e75ffdccd: Sending packet MESSAGE data 0/cm
192.168.1.16 - - [17/Apr/2016 19:51:42] "POST /socket.io/?EIO=3&transport=polling&t=1460922698855-18&sid=a599e845f8464bd7bba3f81e75ffdccd HTTP/1.1" 200 222 0.007844
(17704) accepted ('192.168.1.16', 51294)
192.168.1.16 - - [17/Apr/2016 19:51:42] "GET /socket.io/?EIO=3&transport=polling&t=1460922698860-19&sid=a599e845f8464bd7bba3f81e75ffdccd HTTP/1.1" 200 219 0.001330
a599e845f8464bd7bba3f81e75ffdccd: Sending packet MESSAGE data 2/cm,["cm_response",{"data":"closing_limit_hit","type":"door_status"}]
```

I'm not sure if the error I was having is something you want to continue to investigate (where a background thread is sending a near-constant stream of data to the frontend and what happens when there's a disconnect), but for my purposes I think I have everything working as needed.  I greatly appreciate your help.

**Comment by Basit-qc** [comment]
Any update on this?

**Comment by miguelgrinberg** [comment]
@Basit-qc I don't have any updates, and the OP solved their problem. I'm going to close this issue as it is more than 4 years old. If you have an issue to report, please open a new and and provide all the requested information.
