### ISSUE TITLE
RuntimeError: working outside of application context

### ISSUE THREAD

**Issue by yagman** [miguelgrinberg/Flask-SocketIO#256]
The documentation says 

"In all the examples shown until this point the server responds to an event sent by the client. But for some applications, the server needs to be the originator of a message. This can be useful to send notifications to clients of events that originated in the server, for example in a background thread. The socketio.send() and socketio.emit() methods can be used to broadcast to all connected clients:

```
def some_function():
    socketio.emit('some event', {'data': 42})
```

Note that socketio.send() and socketio.emit() are not the same functions as the context-aware send() and emit(). Also note that in the above usage there is no client context, so broadcast=True is assumed and does not need to be specified."

This is not really working; my client only receives events if socketio.emit used in context otherwise the client wouldn't listen. Moreover, when I used the emit(), send(), and even the disconnect() functions, I get 'working outside of application context' error. All I am trying to do is to shutdown the server and its clients using a regular function outside of context. Any idea on how I could do that? Thanks!

**Comment by miguelgrinberg** [comment]
I don't understand what the problem is, sorry. Can you show the code that is failing and the complete stack trace, please?

**Comment by PierrePaul** [comment]
>  All I am trying to do is to shutdown the server and its clients using a regular function outside of context. 

Do you have the ```message_queue``` parameter set on your initialization?

ie : ```socket = SocketIO(app, message_queue="redis://localhost:6379/0")```
Flask-SocketIO can send message outside of context, but it needs be on the same thread/process if you don't specify your message queue (so no background thread or outside service).

Don't hesitate to correct me @miguelgrinberg if I'm wrong.

**Comment by gtatyous93** [comment]
`def Foo ():
   app = Flask(__name__)
   io = SocketIO(app) # engineio_logger=True)

   def die():
     io.emit('Hi', {})
   
  class Bar:
    def __init__(self, *args, **kwargs):
      self.app = app
      self.io = io
 
    @io.on('connect')
     def connect():
       print('connection established')
         io.emit('downlink', {'connection': 'good'})
    
    @io.on('disconnect')
     def disconnecting():
       disconnect() #emits disconnect message to all clients
       print('all clients are disconnected!')
       io.stop() #raise SystemExit which halts the server
       print('flask app disconnected successfully!') 

    def close(self):
      io.emit('kill me', {}) #client will emit disconnect event to the server
      #disconnect()        #this generates RuntimeError: working outside of application context

  return Bar

**Comment by gtatyous93** [comment]
`def Foo ():
   app = Flask(__name__)
   io = SocketIO(app) # engineio_logger=True)

   def die():
     io.emit('Hi', {})
   
  class Bar:
    def __init__(self, *args, **kwargs):
      self.app = app
      self.io = io
 
    @io.on('connect')
     def connect():
       print('connection established')
         io.emit('downlink', {'connection': 'good'})
    
    @io.on('disconnect')
     def disconnecting():
       disconnect() #emits disconnect message to all clients
       print('all clients are disconnected!')
       io.stop() #raise SystemExit which halts the server
       print('flask app disconnected successfully!') 

    def close(self):
      io.emit('kill me', {}) #client will emit disconnect event to the server
      #disconnect()        #this generates RuntimeError: working outside of application context

  return Bar`

**Comment by PierrePaul** [comment]
Can you also paste the ```disconnect``` function as well?

**Comment by gtatyous93** [comment]
@PierrePaul the disconnect function is imported from Flask_socketio

**Comment by PierrePaul** [comment]
The [disconnect function](https://github.com/miguelgrinberg/Flask-SocketIO/blob/master/flask_socketio/__init__.py#L650) remove a single client (sid) from all the rooms inside a single namespace. If you don't have the application context (the request object), there is no way to know the user sid (socket-id) you want to disconnect.

By reading your comment though ```#emits disconnect message to all clients```, I'm guessing what you want to do is : 
```python
io.emit('user-disconnected', {sid: flask.request.sid})
```

Unless you wanted to disconnect all clients when a single client disconnect?

**Comment by gtatyous93** [comment]
I only have one client connected right now. I cannot shutdown my server because io.stop() won't work until this client shutdown. 

io.emit('user-disconnected', {sid: flask.request.sid}) does not work. it says flask has no attribute 'request'

**Comment by gtatyous93** [comment]
I must say that I am running the client and io.run using two different threads. This might have been causing the issue with the application context and I am not sure how to fix it!

**Comment by miguelgrinberg** [comment]
@gtatyous93 the code that you showed includes a `close` function, but you are not showing the code that calls it.

**Comment by gtatyous93** [comment]
I am not sure how would that effect it but eventually I want to be able to shutdown the server using object.close(). Currently, I am testing using the following code:

` if __name__ == '__main__':
   with USBDetectorFactory()() as usb:
     time.sleep(2);`

and the __exit__(self) function calls self.close()

**Comment by miguelgrinberg** [comment]
Shutdown the server? The `disconnect` function disconnects a user, it has nothing to do with the server.

**Comment by duahimanshu100** [comment]
@PierrePaul 
 I had a same problem 
`socket = SocketIO(app, message_queue="redis://localhost:6379/0")`
This worked for me :)
