### ISSUE TITLE
How to pack flask-socketio app with pyinstaller

### ISSUE THREAD

**Issue by novice79** [miguelgrinberg/Flask-SocketIO#259]
I tried simple test code:
#test.py
from flask import Flask, jsonify, request, render_template
from flask_socketio import SocketIO

class REST():
    def __init__(self):
        self.app = Flask(__name__)
        self.app.config['SECRET_KEY'] = 'freego!'
        # , async_mode="eventlet"
        self.socketio = SocketIO(self.app)

    def run(self):
        #self.init_routes()
        self.socketio.run(self.app, host='0.0.0.0', port=4444)
REST().run()

run it without problem, but pack it with: pyinstaller --onefile test.py
and run test.exe, I got :
Traceback (most recent call last):
  File "<string>", line 59, in <module>
  File "<string>", line 12, in __init__
  File "site-packages\flask_socketio\__init__.py", line 119, in __init__
  File "site-packages\flask_socketio\__init__.py", line 144, in init_app
  File "site-packages\socketio\server.py", line 72, in __init__
  File "site-packages\engineio\server.py", line 100, in __init__
ValueError: Invalid async_mode specified
test returned -1
I tried with or without eventlet installed, or without --onefile, or pyinstaller --onefile --hidden-import=eventlet -F test.py 
it's no differrent.
any suggestion?

**Comment by miguelgrinberg** [comment]
Closing this, as it has been addressed here: https://github.com/miguelgrinberg/python-socketio/issues/35.

**Comment by bluszcz** [comment]
What is the real solution? It still does not work for me.

**Comment by patarapolw** [comment]
> What is the real solution? It still does not work for me.

https://github.com/miguelgrinberg/python-socketio/issues/35#issuecomment-482350874
