### ISSUE TITLE
Getting all of rooms is not available

### ISSUE THREAD

**Issue by bdh1011** [miguelgrinberg/Flask-SocketIO#260]
I tried `socketio.rooms[namespace].keys()` to get all list of rooms by referring issue #96 .
However, it returns `AttributeError: 'SocketIO' object has no attribute 'rooms'`.
How about we implement a function that returns all rooms regardless of sid?
I don't think this is bothersome work.

**Comment by miguelgrinberg** [comment]
Obtaining the list of rooms is not a trivial operation when there are multiple servers each handling a subset of the connected clients. For that reason, my opinion is that the application should keep track of what rooms are active by storing them in a database, file, etc.

**Comment by bdh1011** [comment]
Opps, I asked pool question. 
Thank you @miguelgrinberg.
