### ISSUE TITLE
High performance website with socketIO possible?

### ISSUE THREAD

**Issue by kramer65** [miguelgrinberg/Flask-SocketIO#267]
I've recently deployed a flask website for a customer with Flask-socketIO. I first wanted to deloy with uWSGI, but since it [doesn't work well](http://flask-socketio.readthedocs.io/en/latest/#uwsgi-web-server) with Flask-SocketIO the site is now running on Gunicorn. According to the docs Gunicorn should [not be used with more than one worker](http://flask-socketio.readthedocs.io/en/latest/#gunicorn-web-server), but that is not a problem, since this is a website with a low load.

We are now looking into a new project, which consists of a backend system and a website (with websockets) which will likely run under quite a high load. Since uWSGI can't be used and Gunicorn is limited to one worker, is Flask-SocketIO prepared for high-volume websites at all? 

I didn't run any benchmarks, but I'm just wondering about this before we make a decision which kills us at a later stage.

**Comment by miguelgrinberg** [comment]
Gunicorn is limited to one worker because its load balancer does not provide sticky sessions, a requirement of the Socket.IO server. But nothing prevents you from running several gunicorn instances, each with one worker, with nginx as load balancer.

Side note, be aware that Socket.IO is a stateful protocol. To use more than one worker it is required that you also run a message queue, which the workers use to communicate and coordinate.

**Comment by kramer65** [comment]
Thanks for the quick reply. Good to know that running several gunicorn instances is an option. I don't have experience with running a message queue, but I guess I can use something like Redis.

I searched around and read the introduction of the [django-websocket-redis docs](https://django-websocket-redis.readthedocs.io/en/latest/introduction.html), which explains some of the relevant concepts. I don't even know if we're going to run into trouble (testing will tell us), but at least it's good to know that there are options. 

If you know of any tutorials or examples explaining how to run a message queue with Gunicorn and Flask-SocketIO they're more than welcome. If not I'll try to mess around with it later once this becomes a relevant topic for us.

Thanks anyway!

**Comment by miguelgrinberg** [comment]
@kramer65 Well, speaking of coincidences, I will be giving a tutorial on Flask scalability at PyCon on the 28th. Guess what I'll cover? Even if you are not coming to PyCon, the classes are later published on youtube for the community to enjoy.

As far as Redis goes, this is really not something you need to be concerned, as Redis is one of the easiest and problem-free services that exist. If you install it via a package manager (apt, yum, etc) chances are it's all taken care for you and after the install is done you have the service up and running. If you prefer, you can install it and run it by hand, which is almost as easy. See [this script of mine](https://github.com/miguelgrinberg/flasky-with-celery/blob/master/run-redis.sh), which downloads, builds and runs redis.

**Comment by kramer65** [comment]
Awesome! I won't be at PyCon, but I'll be waiting for your classes to come online!

Btw. You said uwsgi can't correctly handle websockets, but I just found [this](https://github.com/zeekay/flask-uwsgi-websocket). I didn't really go through it in depth, but couldn't that help to get flask-socketio run with uWSGI?

**Comment by miguelgrinberg** [comment]
Yes, it definitely could help. The uWSGI situation is odd, because it comes with its own implementation of websocket, and while it supports gevent, it does not support gevent's own websocket implementation. I intend to write a driver for uWSGI's websockets, just have not found the time yet.

**Comment by abshkd** [comment]
Please can I request for a redis based example of running Flask-socketio. I could not get it to work simply by adding redis to Socketio call as suggested here https://flask-socketio.readthedocs.io/en/latest/

The flask server process hangs (using eventlet and gunicorn) 
Flask-Socketio 2.6.1 
I am still learning the ropes on ws and your extension is quite helpful for someone only familiar with flask.

**Comment by miguelgrinberg** [comment]
@abshkd the hang is probably caused by not having the Python standard library monkey patched. Did you do the monkey patching?

**Comment by abshkd** [comment]
@miguelgrinberg I have not monkey patched anything for sure. I am sure I am missing something, hence my ask. What exactly do I need to monkey path?

**Comment by miguelgrinberg** [comment]
The problem is that many of the functions in the Python standard library are not compatible with eventlet. Eventlet provides equivalent functions, but for code that was not written specifically for eventlet, you have to monkey patch the Python library so that the eventlet functions are called.

In your main script, at the top, before you do any imports, run the following:

    import eventlet
    eventlet.monkey_path()

That should take care of it. If you want more details, see http://eventlet.net/doc/patching.html.

**Comment by abshkd** [comment]
@miguelgrinberg Thank you so much. I know I came back late but it was exactly what was needed.
