### ISSUE TITLE
I have a question on the begin of open web page

### ISSUE THREAD

**Issue by huangfupeng** [miguelgrinberg/Flask-SocketIO#271]
sometimes socket.io content will time-out, so i can not send broadcast, Firefox always appearance

**Comment by miguelgrinberg** [comment]
Not sure I understand what you mean by "sometimes socket.io content will time-out". Can you provide an example please?

**Comment by huangfupeng** [comment]
I use nginx  for agent, sometimes Flask-socket.io  have one more request,  the request will time-out,  you can use my application， http://123.206.58.192/， account:   kNmJmbDz@163.com 
password:  111111   [http://intio.org/uploads/files/1466657592963-test.png](url)

**Comment by miguelgrinberg** [comment]
Looks like you replaced your application with the example app. I still don't understand what the problem is, sorry.

**Comment by huangfupeng** [comment]
sorry, it is ok now

**Comment by huangfupeng** [comment]
you can test in my web  http://123.206.58.192 account: kNmJmbDz@163.com 
password: 111111

**Comment by huangfupeng** [comment]
just now, I use you example  in nginx config  two port , port : 8000 and  port 8001, the problem not work

**Comment by miguelgrinberg** [comment]
It looks like the server isn't responding to the ping package that the client sends. Are you doing anything CPU heavy on the server side?

**Comment by huangfupeng** [comment]
I use your example start two services port 8000 and port 8001 , I use nginx for agent, port 8000service the client request port 8001service  server-side. use firefox always return 504 time-out.I think my nginx configuration have a problem

**Comment by huangfupeng** [comment]
I server-side use tornado , socket.io use flask-socket.io . I search nginx configuration try agant, but alway return 504

**Comment by miguelgrinberg** [comment]
A 504 code means that nginx sent a request to one of your servers, and the server took too long to respond. You may want to look at nginx and server logs to see what requests are timing out. You may also want to remove nginx and see if that resolves the timeouts, suggesting the nginx configuration may have a problem.

**Comment by huangfupeng** [comment]
server {
    listen 80;
    server_name localhost;
    access_log /var/log/nginx/example.log;

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_redirect off;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /socket.io {
        proxy_pass http://127.0.0.1:8001/socket.io;
        proxy_redirect off;
        proxy_buffering off;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }
}

**Comment by huangfupeng** [comment]
I use the nginx configuration like your documentation，Just  change with two port

**Comment by huangfupeng** [comment]
Nginx and server logs no return error， just like this nginx configuration,I also should pay attention to what？

**Comment by miguelgrinberg** [comment]
Well, I'm not really sure. If nginx response with 504, that means that some requests are timing out. Do you know which requests are these? Are they on the app side, or the socket.io side? If on the socket.io side, is it a HTTP request or the WebSocket request? I really can't help you with the information that I have, you need to debug the problem and try the things I suggested above.

**Comment by huangfupeng** [comment]
Thank you for taking the time to help me with my question
