### ISSUE TITLE
Streaming Binary Data to Flask Server

### ISSUE THREAD

**Issue by habdulkafi** [miguelgrinberg/Flask-SocketIO#273]
To start out: I'm pretty much a noob when it comes to javascript in general.  My goal is to stream binary data (audio) from the client to the server.  I got it working using [flask-sockets](https://henri.io/posts/streaming-microphone-input-with-flask.html), but I need to access the `session` object during the handling of the websocket, so I decided to move to this implementation.  However, I'm having a bit of trouble.  The relevant client-side code is:
```javascript
socket = io.connect('http://' + document.domain + ':' + location.port);
function recorderProcess(e) {
    if (recording){
      var left = e.inputBuffer.getChannelData(0);
      socket.emit('audio', left);
    }
  }
```
Here, `left` is the left channel of the audio represented by the amplitude of in the form of a `Float32Array` object.  
On the server side (simplified):
```python
socketio = SocketIO(app, binary=True)

## flask views go here ##

@socketio.on('connect')
def connect():
    session['audio'] = []

@socketio.on('audio')
def handle_my_custom_event(audio):
    session['audio'] += audio.values()

@socketio.on('disconnect')
def disconnect():
    scipy.io.wavfile.write('out.wav', 44100, numpy.array(session['audio']))

if __name__ == '__main__':
    socketio.run(app)

```

Basically, my problem is that even though the client-side object is a `Float32Array`, the `audio` object in the handler is a dictionary where the keys are unicode (?) numbers and the values are floats.  As an example, here are a few key/value pairs of the `audio` object:
```
{u'1362': 0.00024930821382440627, u'1363': 0.00033425656147301197, u'1360': 0.0001966044947039336, u'1361': 0.00029520277166739106, u'3728': 0.00016393758414778858, u'478': -0.0006958675221540034, u'479': -0.0006966364453546703, u'2916': -0.00010853035928448662, u'3699': -7.229528273455799e-05, u'1368': 0.0004023140936624259, u'1369': 0.0003377062384970486}
```
I'm almost certain there is some sort of data "loss" when converting between the `Float32Array` and the dictionary because the general structure of the output audio is intact, but the output sounds nothing like the input.
Questions: Am I sending the `left` object correctly from the client side?  Am I receiving the `audio` object correctly on the server side?  Is there something I should be doing on either side to handle arbitrary binary data properly?

**Comment by miguelgrinberg** [comment]
Do you know what those `u'1362', etc. numbers mean?

**Comment by habdulkafi** [comment]
Thanks for pointing that out!!!  That was what I wasn't understanding: Those keys are the indices of the `left` array, so just doing `audio.keys()` makes no sense!  In case anyone was wondering, this would  fix the problem:
```python
from collections import OrderedDict
@socketio.on('audio')
def handle_my_custom_event(audio):
    session['audio'] += OrderedDict(sorted(audio.items(), key=lambda t:int(t[0]))).values()
```
Thanks a lot for your help!

**Comment by miguelgrinberg** [comment]
It may be more efficient to force the client to send an array. I think if you do something like `socket.emit('audio', {samples: left});` on the JS side this will force the array to be sent as an array inside the top-level dictionary. This should at least save some bandwidth, since those indices are not really needed on the server.

**Comment by habdulkafi** [comment]
Hmm, yea that would make sense from an efficiency perspective.  However, doing `socket.emit('audio', {"samples": left});` on the client side just makes the server side get a nested dictionary with the same `audio` dictionary embedded inside of it.

**Comment by miguelgrinberg** [comment]
Okay. If you want to generate a plan JS array I'm pretty sure that will be serialized as a regular list. But that is going to be less efficient on the client side, so depending on your needs it may or may not make sense.

**Comment by jaijujacob** [comment]
Hi Abdul,

I am trying to do the same thing.. I am a new bie.. I am able to recieve the wave data in server using the above method.
but @socketio.on('disconnect') event doesn't happen in my case.. Can you please suggest what need to be done?

**Comment by miguelgrinberg** [comment]
@jaijujacob Are you sure the disconnect event does not happen? You may need to wait some time, depending on how the connection was established and disconnected, it may take up to a minute for the system to declare the client gone for good and invoke the disconnect event.

**Comment by jaijujacob** [comment]
Thanks Miguel! It works now.. Yes there was some delay. 
I am recording a wave file using the above method. Wave file is getting saved but there are some noice and disturbance (Not a problem with SocketIO anyway). Do you have any idea?

**Comment by miguelgrinberg** [comment]
@jaijujacob you may want to print the first few and last few bytes of each audio buffer on the browser, and then again on the server, to see if they match. Hard to tell what the problem is, you need to figure out if the corruption is introduced on the client or server sides.

**Comment by jaijujacob** [comment]
Let me try. Thank you !

**Comment by nicgirault** [comment]
Thanks @habdulkafi to spot this issue. I have the same issue and this thread helped me to solve the issue. I chose to fix my code on the front side as @miguelgrinberg proposed. Here is the snippet:

```javascript
socket.emit('audio', Array.from(event.inputBuffer.getChannelData(0)))
```
