### ISSUE TITLE
Lots of BAD REQUESTS(400). Messages come from time to time at random

### ISSUE THREAD

**Issue by cyberthrone3** [miguelgrinberg/Flask-SocketIO#276]
@miguelgrinberg 
Hi! I have some problems using flask-socketio. I'd like to mention that my issue is similar to https://github.com/miguelgrinberg/Flask-SocketIO/issues/176. But that solution did not help me. 
My version of gunicorn == 18.0.0
I have support of eventlet as well.
command=/home/developer/.virtualenvs/xxx.yyyy.net/bin/gunicorn -k eventlet --workers=5 --timeout=180 --bind=unix:///tmp/xxx.yyyy.net.sock main:app --log-level=debug
But it doesn't solve the issue :(

So, I have a lot of 400 error before a connection happen.
But the most interesting thing is that some messages can't be sent to their destination.
For example, I send the first message. Nothing happens. Then I send the second message - it comes to its destinations. Then I send the next 20 messages. Nothing happens. And then I send some message again - and it comes to its destination.
Why does it happen? Why can't I receive all messages I've sent?

It'd be great if you could help me :)

**Comment by miguelgrinberg** [comment]
You have to use one worker with gunicorn. Change the `-w 5

**Comment by cyberthrone3** [comment]
Thanks a lot! My fault!

**Comment by cyberthrone3** [comment]
@miguelgrinberg 
Hello again! As I've mentioned in this issue https://github.com/miguelgrinberg/Flask-SocketIO/issu.. I have multiple workers. So I decided to divide it into two different processes (main_app 127.0.0.1:5000 and socket_app 127.0.0.1:5001).
The first one is the old one with a bunch of workers and the second one is for sockets only.
According to the documentation https://flask-socketio.readthedocs.io/en/latest/#emit.. it is possible to emit events from external processes using REDIS.
But, when I try to call emit from the main_app nothing happens =( 
I think I defined socketios incorrectly. But how to define them in the right way? There is no full info anywhere :(
Here is an example of my divided apps.

**main_app.py**
```
from flask import Flask
from flask_socketio import SocketIO, send, emit

app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(
message_queue='redis://127.0.0.1:6379/0',
channel='the_best_channel_in_the_world'
)

@app.route('/')
def hello_world():
socketio.emit('my_event', 'some_string_goes_here')
return "Hello, world!"

if __name__ == '__main__':
app.run()
```

**socket_app.py**
```
from flask import Flask, session
from flask_socketio import SocketIO

app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(
app=app,
message_queue='redis://127.0.0.1:6379/0',
channel='the_best_channel_in_the_world'
)

@socketio.on('connect')
def on_connect():
join_room(session['user_id'])

if __name__ == '__main__':
socketio.run(app, host='127.0.0.1', port=5001)
```
Thank you!

**Comment by miguelgrinberg** [comment]
Can your socket app emit? That would confirm that the connection is established.

**Comment by cyberthrone3** [comment]
@miguelgrinberg 
Everything is fine with socket_app.py when I remove string with "message_queue='redis//',".
I can emit and send messages from my server(5001), the client side can intercept server messages as well.

But when I try to create a socketio with "message_queue='redis//'," the server can intercept signals from the client. Server prints show that the client connects and sends messages. BUT when the server tries to emit or send messages to the client nothing happens! The client cannot intercept server signals! :(  By the way, there is no item in the browser "WS" tab as well.
Also, a redis-browser shows that redis has no keys at all.

Is this a common issue or there is something weird with my configs?

**Comment by miguelgrinberg** [comment]
Ah, the monkey patching. I wish there was a way for eventlet/gevent to detect when a blocking function is called. Glad it is working!
