### ISSUE TITLE
Integrating Flask-SocketIO with Flask-Script

### ISSUE THREAD

**Issue by egorf** [miguelgrinberg/Flask-SocketIO#279]
Hi!

I've had some trouble integrating Flask-SocketIO with the Flask-Script Manager. Following the app factory pattern, described in your book(brilliant, btw), I had something like this:

```
from flask import Flask, render_template
from flask_socketio import SocketIO
from config import configs

socketio = SocketIO()

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(configs[config_name])
    configs[config_name].init_app(app)

    socketio.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return socketio, app


```

Then, `manage.py` used as the main script:

```
import os
from app import create_app

from flask_script import Manager, Server

app = create_app(os.getenv("FLASK_CONFIG") or "default")
manager = Manager(app)
manager.add_command("runserver", Server(host="0.0.0.0", port=3000))

if __name__ == "__main__":
    manager.run()
```

However, this setup gave some trouble:

* The server requests would sometimes hang and take up to 45 seconds.
* The socket.io disconnect event would fire now and then
* [pace.js](http://github.hubspot.com/pace/) script would not show the web page is fully loaded
* server would sometimes raise exceptions about not using eventlet, even though it was installed

At the moment, the solution I found was to get rid of the **Manager**, and make the factory return both **app** and **socketio** instances, which is quite ugly. This is the working manage.py:

```
import os
from app import create_app

socketio, app = create_app(os.getenv("FLASK_CONFIG") or "default")

if __name__ == "__main__":
    socketio.run(app, host="0.0.0.0", port=3000)

```

Is there a way to get around this? It seems like I must to run the server exactly this way, with the **socketio** instance.

**Comment by miguelgrinberg** [comment]
The problem is that Flask-Script's `runserver` task cannot be used with Flask-SocketIO, which has its own way to start the server. Take a look at this example for a new runserver task that is compatible with socket.io: https://github.com/miguelgrinberg/flack/blob/master/manage.py

**Comment by egorf** [comment]
So, basically, there is no way I can leave SocketIO initialization inside the **create_app** factory?

**Comment by miguelgrinberg** [comment]
SocketIO is more than a Flask extension, it requires a different web server, one that can handle long-polling and websockets. You can initialize SocketIO as a regular Flask extension, in fact you are probably doing that. What you can't do is use SocketIO with the Flask development server, at least not in its default configuration.

The `socketio.run()` call encapsulates the support for the three supported web server configurations. That needs to be used in place of `app.run()` when working with SocketIO.

**Comment by egorf** [comment]
Thanks for the thorough explanation. I think this information should be in the docs(correct me if I'm wrong).

**Comment by miguelgrinberg** [comment]
I believe it is, actually. Nothing specifically calling out the use of Flask-Script, but the use of custom servers is well explained, I think. If you have any specific fixes you want to make feel free to suggest them or send a pull request.
