### ISSUE TITLE
xamarin.ios socket.io client connection error "parser error"

### ISSUE THREAD

**Issue by KirillVolkov** [miguelgrinberg/Flask-SocketIO#280]
how fix?

**Comment by cyberthrone3** [comment]
@miguelgrinberg 
I'll add some info here :)
We'd like to find out if there is some incompatibility with ios applications and flask-socketio?
The server side seems to be working correct. At least, js client connects to a socket and works with it perfectly.
But in case with ios application there is a 'parser error' appears when the app tries to connect to the socket.
Logs show that there are a lot of attempts of connecting to it.
For example:
```
@socketio.on('connect')
def on_connect():
      print('Connection has been established')
```
The server console displays about a hundred of print('Connection has been established').
Is there any way of fixing it?

Thank you!

**Comment by miguelgrinberg** [comment]
Can you provider more information about this "parser error"? Is it client or server side? Do you have a stack trace? 

Also, do you know what version of the Socket.IO protocol your client implements? There is an old version of Socket.IO that is incompatible with the current code, you may need an old release of Flask-SocketIO if you need to use the 0.9 or older protocol. The current code works for 1.0 and up.

**Comment by KirillVolkov** [comment]
@miguelgrinberg  maybe you know how appears this error?

**Comment by cyberthrone3** [comment]
@miguelgrinberg 
The client side shows "Server error: parser error". And there is no stacktrace at all. The version of the protocol the client implements is 1.1
