### ISSUE TITLE
resource is called path in socket.io 1.0

### ISSUE THREAD

**Issue by MaxNoe** [miguelgrinberg/Flask-SocketIO#281]
I just stumbled on this. Was very confusing.

**Comment by miguelgrinberg** [comment]
Are you suggesting any changes? If I change resource to path in this extension, then all existing applications will break.

**Comment by MaxNoe** [comment]
Yeah, I know. 

Maybe provide both options resulting in the same?

At least document, that this property is called differently in the JavaScript library now.

**Comment by miguelgrinberg** [comment]
Okay. I can support both path and resource, that's doable.

**Comment by miguelgrinberg** [comment]
Fixed in commit aa34521f35cedce2c9ff5e57a6dec82c7a9b1c81.
