### ISSUE TITLE
Not able to get the list of rooms the client is currently in on disconnect event

### ISSUE THREAD

**Issue by vtjeng** [miguelgrinberg/Flask-SocketIO#282]
An [issue in the repo for socket.io](https://github.com/socketio/socket.io/issues/1814) summarizes why it would be useful to get the list of rooms a client is in when they disconnect (I think this is frequently needed functionality), and outlines several possible hacky fixes. What is the appropriate approach in Flask-SocketIO?

**Comment by miguelgrinberg** [comment]
This was actually raised as an issue on the python-socketio repo a few days ago. See https://github.com/miguelgrinberg/python-socketio/pull/33.

I have merged the solution that was proposed, which basically kept the disconnected user in all the rooms until after the disconnect event handler is invoked. So it is now perfectly fine to query the user for the rooms, and then possibly broadcast something to those rooms to let others know the user left.
