### ISSUE TITLE
Random Timeout

### ISSUE THREAD

**Issue by elbaro** [miguelgrinberg/Flask-SocketIO#284]
After a few minutes my script runs, the program randomly times out.

I am running a socketio server in a separate thread:

```
th = threading.Thread(target=socketio.run, args=(app, '0.0.0.0', 5000))
th.name ='socketio-thread'
th.daemon = True
th.start()
```

All python threads call `socketio.sleep(0)` whenever they can.

The version of flask-socketio is 2.5, installed with pip.

Here is the error:

```
(11350) wsgi exited, is_accepting=True
Exception in thread socketio-thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_socketio/__init__.py", line 436, in run
    run_server()
  File "/usr/local/lib/python2.7/dist-packages/flask_socketio/__init__.py", line 431, in run_server
    log_output=log_output, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/eventlet/wsgi.py", line 865, in server
    client_socket = sock.accept()
  File "/usr/local/lib/python2.7/dist-packages/eventlet/greenio/base.py", line 220, in accept
    timeout_exc=socket.timeout("timed out"))
  File "/usr/local/lib/python2.7/dist-packages/eventlet/greenio/base.py", line 203, in _trampoline
    mark_as_closed=self._mark_as_closed)
  File "/usr/local/lib/python2.7/dist-packages/eventlet/hubs/__init__.py", line 162, in trampoline
    return hub.switch()
  File "/usr/local/lib/python2.7/dist-packages/eventlet/hubs/hub.py", line 294, in switch
    return self.greenlet.switch()
timeout: timed out
```

**Comment by miguelgrinberg** [comment]
Did you monkey patch the python standard library?

**Comment by elbaro** [comment]
```
import eventlet
eventlet.monkey_patch()
```
The code has the above two lines in the top. Can you explain when this happenes?

**Comment by miguelgrinberg** [comment]
@elbaro at the top of which file? Monkey patching needs to be done for the entire application. The problem that you have sounds like a mix of greenlet and regular threading code, which is almost never a good idea.

**Comment by elbaro** [comment]
It's a single script, so all code run after the monkey patching.

I am closing this because I don't have time to debug and couldn't find the same issue. Someone trying to utilize multi-threading with eventlet might find the below helpful. Please correct any wrong statement.

-------
Reading the docs for Greenlet, my understanding is that it's okay to mix the built-in threading module with greenlet.

The ideal usage would be 

python-thread1 (main)
python-thread2 (flask-socketio): greenlet thread1, greenlet thread2, ..
python-thread3 (executor1)
..

where each python-thread is preemptive, while green threads are non-preemptive and need to switch between them with explicit eventlet.sleep() calls. Greenlet switching is only valid within each python thread, so I shouldn't call eventlet.sleep() from main thread.

If you do broadcasting from a normal python-thread, that will use a greenlet version of socket, and I am not sure what would happen. The safe way would be adding the task to the queue, and let a greenlet thread pop and process it.

Or, one could monkey patch and think every thread as a greenlet thread.

Still, I tried all combinations and it didn't work.
1. no money-patch + python-threads + no eventlet.sleep() from main: the script hangs
2. no money-patch + python-threads + eventlet.sleep() from main: no hang, random timeout
3. money-patch + all greenlets + no sleep() from main: the script hangs
4. money-patch + all greenlets + sleep() from main: no hang, random timeout

**Comment by Karthik777** [comment]
I have the same random timeout issues. 
I have monkey patched at the start of the application. (eventlet)
and all threads I create are through the socketio.start_background_tasks with a thread lock because I access shared variables.
Any advice would be highly appreciated

**Comment by jarryxy** [comment]
> I've had the same problem. Every time you connect to a sockettio client, the program stops after 60 seconds with an error. When I pip uninstall eventlet, using other tools seems to be fine.

this is my error：

![image](https://github.com/miguelgrinberg/Flask-SocketIO/assets/56039867/459fa5fb-68bb-4c5a-8e8f-adf7c7182722)
