### ISSUE TITLE
Non-decorator way to register callbacks

### ISSUE THREAD

**Issue by sotte** [miguelgrinberg/Flask-SocketIO#286]
I wish there was a non-decorator way to register callbacks for methods of a class. I.e., I want to be able to do something like this:

``` python
class A:
    def __init__(self, gui_controller):
        self._gui = gui_controller
        self._gui._socketio.on(msg="dummy", callback=self.f, namespace=self._gui.ns)

    def f(self, json):
        print("Dummy")
```

I don't have a global socketio instance and I need to register the callbacks using some parameters from the instance (in the example it's the namespace).

Is there a way to do this?

**Comment by miguelgrinberg** [comment]
The syntax is a bit awkward, but you can do it as follows:

    self._gui._socketio.on('dummy', namespace=self._gui.ns)(self.f)

**Comment by sotte** [comment]
Thanks for the quick respond! Works like a charm.
