### ISSUE TITLE
Authentication with flask_httpauth

### ISSUE THREAD

**Issue by Silvercast** [miguelgrinberg/Flask-SocketIO#293]
Hi,
I'm quite new to Flask. The documentation says authentication can be done with Flask-Login but my app is pure REST APIs and it's using flask_httpauth for verification. Is there any way I can use this awesome package with flask_httpauth instead of flask-login? Thanks

**Comment by miguelgrinberg** [comment]
flask-httpauth helps with authentication for HTTP APIs, so it is not the right thing to use for Socket.IO. If you already have a way to validate tokens for your API, then you can have the client send the token over the Socket.IO connection, and you can validate it on the server by calling the same validation code you use with flask-httpauth.

**Comment by Silvercast** [comment]
I wonder if I can do the validation on `@socketio.on('connect')` as it takes no parameter i.e. no way to validate token on `connect` event. Otherwise server has to let client connect, then disconnect on bad tokens.

**Comment by Silvercast** [comment]
super quick response btw 👍

**Comment by miguelgrinberg** [comment]
Yeah, it is unfortunate but the connect event does not accept parameters (nothing I can do, that's how the Socket.IO protocol was designed).

One way to trick the system and get a token sent is to have the client put it in a cookie before connecting. The cookie will be included in the connection request, and should be available to you via the Flask `request` object.

**Comment by Silvercast** [comment]
I will try, thanks for clarification. Close issue for now.
