### ISSUE TITLE
Can't put Gunicorn in front of Flask-SocketIO server

### ISSUE THREAD

**Issue by ocervell** [miguelgrinberg/Flask-SocketIO#294]
Tried to put a gunicorn server in front of my Flask-SocketIO app: 

`gunicorn --worker-class socketio.sgunicorn.GeventSocketIOWorker ui:app`

Get following exception:

```
class uri 'socketio.sgunicorn.GeventSocketIOWorker' invalid or not found:

[Traceback (most recent call last):
  File "/Users/ocervell/.virtualenvs/flask/lib/python2.7/site-packages/gunicorn/util.py", line 142, in load_class
    mod = import_module('.'.join(components))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named socketio.sgunicorn
]
```

App works fine without gunicorn but I'd like to put an nginx server and multiple gunicorn instances to serve multiple clients.

Thanks !

**Comment by miguelgrinberg** [comment]
I think you are reading the wrong documentation. The command you are using is for gevent-socket. This is flask-socketio. The gunicorn deployment docs are here: https://flask-socketio.readthedocs.io/en/latest/#gunicorn-web-server

**Comment by ocervell** [comment]
I'm asking here because of your response to http://stackoverflow.com/questions/30936567/correct-configuration-for-flask-socketio , where you recommended to use this worker with Flask-SocketIO.

**Comment by miguelgrinberg** [comment]
Right, sorry for the confusion. In the past, in pre-1.0 releases of Flask-SocketIO, the gevent-socketio project was used as a dependency. Back in those days, that gunicorn command line, which came from the gevent-socketio documentation, would have been appropriate for flask-socketio as well.

Since version 1.0, Flask-SocketIO uses a different set of dependencies. The documentation link I pointed you at will get you running with gunicorn.

**Comment by ocervell** [comment]
Thanks for the documentation, I see a little bit more clear now. 

So if I want to scale up my Flask-SocketIO app, it seems I have to use the following worker: `geventwebsocket.gunicorn.workers.GeventWebSocketWorker` along with `nginx` as reverse HTTP proxy to dispatch incoming requests.

I am now having problems running this worker:
```
$ gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 -b 127.0.0.1:5000 ui:app
[2016-07-29 14:30:52 -0500] [91177] [INFO] Starting gunicorn 19.6.0
[2016-07-29 14:30:52 -0500] [91177] [INFO] Listening at: http://127.0.0.1:5000 (91177)
[2016-07-29 14:30:52 -0500] [91177] [INFO] Using worker: geventwebsocket.gunicorn.workers.GeventWebSocketWorker
[2016-07-29 14:30:52 -0500] [91180] [INFO] Booting worker with pid: 91180
Traceback (most recent call last):
  File "/Users/ocervell/.virtualenvs/flask-v2/lib/python2.7/site-packages/gevent/pywsgi.py", line 884, in handle_one_response
    self.run_application()
  File "/Users/ocervell/.virtualenvs/flask-v2/lib/python2.7/site-packages/geventwebsocket/handler.py", line 76, in run_application
    self.run_websocket()
  File "/Users/ocervell/.virtualenvs/flask-v2/lib/python2.7/site-packages/geventwebsocket/handler.py", line 52, in run_websocket
    self.application(self.environ, lambda s, h, e=None: [])
  File "/Users/ocervell/.virtualenvs/flask-v2/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/ocervell/.virtualenvs/flask-v2/lib/python2.7/site-packages/flask_socketio/__init__.py", line 37, in __call__
    start_response)
  File "/Users/ocervell/.virtualenvs/flask-v2/lib/python2.7/site-packages/engineio/middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/Users/ocervell/.virtualenvs/flask-v2/lib/python2.7/site-packages/socketio/server.py", line 308, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/Users/ocervell/.virtualenvs/flask-v2/lib/python2.7/site-packages/engineio/server.py", line 231, in handle_request
    environ, start_response)
  File "/Users/ocervell/.virtualenvs/flask-v2/lib/python2.7/site-packages/engineio/socket.py", line 80, in handle_get_request
    start_response)
  File "/Users/ocervell/.virtualenvs/flask-v2/lib/python2.7/site-packages/engineio/socket.py", line 119, in _upgrade_websocket
    return ws(environ, start_response)
  File "/Users/ocervell/.virtualenvs/flask-v2/lib/python2.7/site-packages/engineio/async_eventlet.py", line 11, in __call__
    raise RuntimeError('You need to use the eventlet server. '
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.
{'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, sdch',
 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.8',
 'HTTP_AUTHORIZATION': 'Basic b2NlcnZlbGw6TW9uZGF5MTI=',
 'HTTP_CACHE_CONTROL': 'no-cache',
 'HTTP_CONNECTION': 'Upgrade',
 'HTTP_COOKIE': 'io=8e27c0ada45e4310bdce815c1aa283d0; session=.eJwlzksLgkAABOC_EnuW2LQkhA6VKaupSD7Ki6y26vosH5iF_72NjjMMw_cBfVOQGkiATFoWqTG1qIbcN1qZFHWo8tbxEYmGY_OWk06Gw_pppNhXIMqblynfNpaMRjN3hcResotHwOaWbPwi1FScdeGW5MoB5soZV1qr-x29Ol7aFJdefya-IJ54EuwB93eE96HFPW0YSISQA0NH2hpXBEgfsIiYMuLNMq6DMlLHHZjnL7PUPvI.Cn1AcQ.X6gg8fBgf6rEoR3agk3zNowkKE8',
 'HTTP_HOST': '127.0.0.1:5000',
 'HTTP_ORIGIN': 'http://127.0.0.1:5000',
 'HTTP_PRAGMA': 'no-cache',
 'HTTP_SEC_WEBSOCKET_EXTENSIONS': 'permessage-deflate; client_max_window_bits',
 'HTTP_SEC_WEBSOCKET_KEY': 'noGn0DRFyvxM/zkA6eSYeQ==',
 'HTTP_SEC_WEBSOCKET_VERSION': '13',
 'HTTP_UPGRADE': 'websocket',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36',
 'PATH_INFO': '/socket.io/',
 'QUERY_STRING': 'EIO=3&transport=websocket&sid=8e27c0ada45e4310bdce815c1aa283d0',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_PORT': '55635',
 'REQUEST_METHOD': 'GET',
 'SCRIPT_NAME': '',
 'SERVER_NAME': '1.0.0.127.in-addr.arpa',
 'SERVER_PORT': '5000',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'gevent/1.1.2 gunicorn/19.6.0',
 'flask.app': <Flask 'ui'>,
 'wsgi.errors': <gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x10e7d3d90>,
 'wsgi.file_wrapper': <class 'gunicorn.http.wsgi.FileWrapper'>,
 'wsgi.input': <gevent.pywsgi.Input object at 0x10f081530>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0),
 'wsgi.websocket': None,
 'wsgi.websocket_version': '13'} failed with RuntimeError
```

**Three questions:**

1) In order to allow emit calls to be non-blocking I had to put the following lines at the top of my file:
```
import eventlet
evenlet.monkey_patch()
```
I suspect this is the reason why the former worker doesn't run and asks me to use `eventlet` worker ?
I tried running with the eventlet worker: `gunicorn -k eventlet -w 1 -b 127.0.0.1:5000 ui:app` and it seems to be working.

2) If I'm bound to choose the `eventlet` worker, will it support scaling with `nginx` the same way as `geventwebsocket.gunicorn.workers.GeventWebSocketWorker` ?

3) In the `Using Multiple Workers` section you seem to be inferring that if I want to scale up my app I need to install some queuing service like `redis`. 
Is that still required if I don't need clients to share anything between them (completely independent versions of the app per client) ?

Thanks for your response and for your overall work around Flask (watched / read all your tutorials !).

**Comment by ocervell** [comment]
Fixed my problem with `eventlet` by running `pip uninstall eventlet` and replacing the following lines:
```
import eventlet
eventlet.monkey_patch()
```

by:
```
from gevent import monkey
monkey.patch_all()
```

My questions 1) is thus solved, I'd still like to know about 2) and 3) though.

Thanks.

**Comment by miguelgrinberg** [comment]
1) you seem to be wanting to use gevent. Is this correct? Flask-SocketIO by default will look at what's installed to decide which web server to use. Eventlet is given first choice, gevent is second. If you have both eventlet and gevent installed and want to use gevent, then you have to explicitly select it by adding `async_mode='gevent'` to the `SocketIO` constructor.

2) gevent-websocket uses a more complicated set up that requires a custom gunicorn worker. Eventlet is implemented in a simpler way, the default gunicorn worker for eventlet works fine with it.

3) I honestly never tested multiple workers w/o a communication channel between them. The messaging queue is used to coordinate actions that require addressing groups of users, which will be all randomly assigned to different servers. If your communications are always between the server and a single user you may be able to get by without the queue. Untested, and likely never supported officially though, you'll have to test this yourself.
