### ISSUE TITLE
Flask Yield don't work on Chrome

### ISSUE THREAD

**Issue by rafaelcapucho** [miguelgrinberg/Flask-SocketIO#296]
Hello,

Could Flask-SocketIO be related with this problem:
http://stackoverflow.com/questions/38668967/flask-yield-dont-work-on-chrome

Thank you.

**Comment by miguelgrinberg** [comment]
I doubt it. But did you try removing Socket.IO to see if the issue goes away?

If would be useful to write a simple app that only does the streaming.

**Comment by rafaelcapucho** [comment]
Hi @miguelgrinberg 

You're right, even a simple snippet (without SocketIO) is hanging on Chromium:
http://pastebin.com/raw/YtJLVmU8

**Comment by rafaelcapucho** [comment]
Feel free to close the issue if you don't know the reason of the bug, thank you.

**Comment by miguelgrinberg** [comment]
Could this be relevant?
https://bugs.chromium.org/p/chromium/issues/detail?can=2&start=0&num=100&q=chunked&colspec=ID%20Pri%20M%20Iteration%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=&id=156023

Try changing the content type to something else.

**Comment by rafaelcapucho** [comment]
@miguelgrinberg 
Yeah! It works!! thank you so much ;)
