### ISSUE TITLE
Release with git tag and ChangeLog

### ISSUE THREAD

**Issue by mckelvin** [miguelgrinberg/Flask-SocketIO#299]
Hi @miguelgrinberg , Thanks for developing and maintaining `Flask-SocketIO` and the corresponding software family.

I'm using pip-tools to maintain the pip-dependency of my software. And every time when I'm going to upgrade the 3rd-party dependency, I need to check the changelog between every release (read the changeset or RTFC).

So everytime a new version is upload to PyPI, would you please add some changelog messages in the bump-version commit? like [what gevent do](https://github.com/gevent/gevent/releases/tag/v1.1.2)

```
Release 2.6

ChangeLog

- bla bla
- ...
```

And tag the commit with `v2.6` Then I'll be able to check it in https://github.com/miguelgrinberg/Flask-SocketIO/releases/tag/v2.6 and also https://github.com/miguelgrinberg/Flask-SocketIO/compare/v2.5...v2.6 .

Thanks a lot.

**Comment by miguelgrinberg** [comment]
You can look at the commits between the "Release..." commits to find the changes that went into a release.
