### ISSUE TITLE
flask-socketio + gunicorn, client seems to connect but no answer from the server

### ISSUE THREAD

**Issue by tendresse** [miguelgrinberg/Flask-SocketIO#300]
Hello Miguel, first of all a big big big thank you for your work ! We really appreciate it !
We converted our app to use websocket using flask-socketio.
We're using gunicorn 19.6.0, flask-socketio 2.6.1 and eventlet 0.19.0.
I'm launching the server via : 
`gunicorn --worker-class eventlet -w 1 app.wsgi:app`
and the server starts normaly : 
`[2016-08-03 23:17:23 +0200] [7923] [INFO] Starting gunicorn 19.6.0
[2016-08-03 23:17:23 +0200] [7923] [DEBUG] Arbiter booted
[2016-08-03 23:17:23 +0200] [7923] [INFO] Listening at: http://127.0.0.1:8000 (7923)
[2016-08-03 23:17:23 +0200] [7923] [INFO] Using worker: eventlet
[2016-08-03 23:17:23 +0200] [7926] [INFO] Booting worker with pid: 7926
[2016-08-03 23:17:23 +0200] [7923] [DEBUG] 1 workers
`
We have an ionic app, with socket.io on it, that we want to connect to the app.
`var connect = function(token){
    myIoSocket = io.connect('http://127.0.0.1:8000/api/v1');
    myIoSocket.on('connect', function (data) {
      console.log("connected + "+data);
      myIoSocket.emit('auth', { token: token });
    });
    myIoSocket.on('auth', function (data) {
      console.log("authentificated");
    });
    mySocket = socketFactory({
      ioSocket: myIoSocket
    });
  }
`

The problem is that when the app tries to connect to the server, those lines appears : 
`[2016-08-03 23:17:24 +0200] [7926] [DEBUG] POST /socket.io/
[2016-08-03 23:17:24 +0200] [7926] [DEBUG] GET /socket.io/
127.0.0.1 - - [03/Aug/2016:23:17:24 +0200] "GET /socket.io/?EIO=3&transport=polling&t=LPIHA85&sid=ac67dffc647545189f9ac3115b63d426 HTTP/1.1" 200 12 "http://localhost:8100/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36"
[2016-08-03 23:17:24 +0200] [7926] [DEBUG] GET /socket.io/
127.0.0.1 - - [03/Aug/2016:23:17:24 +0200] "POST /socket.io/?EIO=3&transport=polling&t=LPIHA7-&sid=ac67dffc647545189f9ac3115b63d426 HTTP/1.1" 200 2 "http://localhost:8100/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36"
[2016-08-03 23:17:24 +0200] [7926] [DEBUG] GET /socket.io/
127.0.0.1 - - [03/Aug/2016:23:17:24 +0200] "GET /socket.io/?EIO=3&transport=polling&t=LPIHA8b&sid=ac67dffc647545189f9ac3115b63d426 HTTP/1.1" 200 4 "http://localhost:8100/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36"
[2016-08-03 23:17:24 +0200] [7926] [DEBUG] POST /socket.io/
[2016-08-03 23:17:24 +0200] [7926] [DEBUG] GET /socket.io/
127.0.0.1 - - [03/Aug/2016:23:17:24 +0200] "POST /socket.io/?EIO=3&transport=polling&t=LPIHA8l&sid=ac67dffc647545189f9ac3115b63d426 HTTP/1.1" 200 2 "http://localhost:8100/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36"
[2016-08-03 23:17:33 +0200] [7926] [ERROR] Error handling request /socket.io/?EIO=3&transport=websocket&sid=ac67dffc647545189f9ac3115b63d426
Traceback (most recent call last):
  File "/home/greygz/dev/tendresse_api/venv/lib/python3.5/site-packages/gunicorn/workers/async.py", line 52, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/home/greygz/dev/tendresse_api/venv/lib/python3.5/site-packages/gunicorn/workers/async.py", line 112, in handle_request
    resp.close()
  File "/home/greygz/dev/tendresse_api/venv/lib/python3.5/site-packages/gunicorn/http/wsgi.py", line 418, in close
    self.send_headers()
  File "/home/greygz/dev/tendresse_api/venv/lib/python3.5/site-packages/gunicorn/http/wsgi.py", line 334, in send_headers
    tosend = self.default_headers()
  File "/home/greygz/dev/tendresse_api/venv/lib/python3.5/site-packages/gunicorn/http/wsgi.py", line 315, in default_headers
    elif self.should_close():
  File "/home/greygz/dev/tendresse_api/venv/lib/python3.5/site-packages/gunicorn/http/wsgi.py", line 238, in should_close
    if self.status_code < 200 or self.status_code in (204, 304):
AttributeError: 'Response' object has no attribute 'status_code'
127.0.0.1 - - [03/Aug/2016:23:17:33 +0200] "GET /socket.io/?EIO=3&transport=websocket&sid=ac67dffc647545189f9ac3115b63d426 HTTP/1.1" 500 - "-" "-"
[2016-08-03 23:17:33 +0200] [7926] [DEBUG] Failed to send error message.
`
and in the web console from the app, the result of my console.log is : 
`connected + undefined`

and the console.log("authentificated") is never triggered.

Do you have an idea about what I could have done wrong ? 
I put [here](https://github.com/tendresse/tendresse_api/tree/socket) a link towards the project if you need more code or context.
Also, no " print " from the server is outputted into the terminal, besides having debug=True.
It seems like the events are not linked to the project or gunicorn isn't forwarding the requests.

Thank you so much for your help !

**Comment by miguelgrinberg** [comment]
Why do you have `/api/v1` in `io.connect('http://127.0.0.1:8000/api/v1');`?

**Comment by tendresse** [comment]
Thank you for your answer ! I added /api/V1 because the blueprint has a prefix url which is "/api/v1".

**Comment by miguelgrinberg** [comment]
Flask-SocketIO does not work with HTTP or blueprints. The syntax for the Socket.IO connection URL is `http://host:port/namespace`, or just `http://host:port/` if you don't use a namespace.

**Comment by tendresse** [comment]
Oh ok :) , I'll give it a try but I think I already tried to connect with/without the "/api/v1" withtout success !

**Comment by tendresse** [comment]
I tried without the "/api/v1", and again, no print is outputted in the terminal from the flask server.
I don't know how to test more things to see where the bug is.
When I login on my app, and HTTP PUT request is sent in order to get a token, then the websocket is opened and the token is sent via the "auth" event, but the client is supposed to listen for an "auth" event back, but the server doesn't send anything ...
`[2016-08-04 09:15:07 +0200] [1490] [DEBUG] OPTIONS /api/v1/users
127.0.0.1 - - [04/Aug/2016:09:15:07 +0200] "OPTIONS /api/v1/users HTTP/1.1" 200 - "http://localhost:8100/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36"
[2016-08-04 09:15:07 +0200] [1490] [DEBUG] PUT /api/v1/users
127.0.0.1 - - [04/Aug/2016:09:15:07 +0200] "PUT /api/v1/users HTTP/1.1" 200 165 "http://localhost:8100/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36"
[2016-08-04 09:15:07 +0200] [1490] [DEBUG] GET /socket.io/
127.0.0.1 - - [04/Aug/2016:09:15:07 +0200] "GET /socket.io/?EIO=3&transport=polling&t=LPKPzbY HTTP/1.1" 200 119 "http://localhost:8100/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36"
[2016-08-04 09:15:07 +0200] [1490] [DEBUG] GET /socket.io/
[2016-08-04 09:15:07 +0200] [1490] [DEBUG] POST /socket.io/
127.0.0.1 - - [04/Aug/2016:09:15:07 +0200] "POST /socket.io/?EIO=3&transport=polling&t=LPKPzgT&sid=b7698cd9947d423b9971272b25ba7680 HTTP/1.1" 200 2 "http://localhost:8100/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36"
[2016-08-04 09:15:07 +0200] [1490] [DEBUG] GET /socket.io/
127.0.0.1 - - [04/Aug/2016:09:15:07 +0200] "GET /socket.io/?EIO=3&transport=polling&t=LPKPzgZ&sid=b7698cd9947d423b9971272b25ba7680 HTTP/1.1" 200 4 "http://localhost:8100/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36"
`
The funny part is that the auth event sent to the server returns a 200 : 
`Request URL:http://127.0.0.1:8000/socket.io/?EIO=3&transport=polling&t=LPKPzgT&sid=b7698cd9947d423b9971272b25ba7680
Request Method:POST
Status Code:200 OK
Remote Address:127.0.0.1:8000
`

It really looks like flask is not listening for any event.

**Comment by tendresse** [comment]
Here's what the webconsole looks like : [imgur](http://imgur.com/a/WQRny)

**Comment by miguelgrinberg** [comment]
The screenshot that you sent does not show any errors, that looks like a successful run from the point of view of the Socket.IO connection.

I think the next step is for you to enable Socket.IO logging on your browser and on the server to figure out what events are being sent or not.

**Comment by tendresse** [comment]
Thank you for your answer ! I enabled the debug option on the client side and I have this : 

`engine.io-client:socket writing ping packet - expecting pong within 60000ms +25s
socket.io.js:3511 GET http://127.0.0.1:8000/socket.io/?EIO=3&transport=polling&t=LPWDurc&sid=39e827bfb08647c58fc25b9175a4af61 400 (BAD REQUEST)Request.create @ socket.io.js:3511Request @ socket.io.js:3424XHR.request @ socket.io.js:3352XHR.doPoll @ socket.io.js:3382Polling.poll @ socket.io.js:3795Polling.onData @ socket.io.js:3834(anonymous function) @ socket.io.js:3385Emitter.emit @ socket.io.js:4389Request.onData @ socket.io.js:3546Request.onLoad @ socket.io.js:3627xhr.onreadystatechange @ socket.io.js:3499
socket.io.js:1799 engine.io-client:socket socket error {"type":"TransportError","description":400} +35s
socket.io.js:1799 socket.io-client:manager error +2ms Error: xhr poll error(…)
socket.io.js:1799 engine.io-client:socket socket close with reason: "transport error" +12ms
socket.io.js:1799 socket.io-client:manager onclose +4ms
socket.io.js:1799 socket.io-client:manager cleanup +4ms
socket.io.js:1799 socket.io-client:socket close (transport error) +3ms
socket.io.js:1799 socket.io-client:manager will wait 765ms before reconnect attempt +3ms
socket.io.js:1799 engine.io-client:socket probe transport "websocket" failed because of error: socket closed +2ms
`

I will enable the debug on the server side too, but maybe you already have a clue about the problem. Thank you !

**Comment by tendresse** [comment]
Well the ping-pong requests are working I'm gonna investigate on why other events dont work.

**Comment by tendresse** [comment]
Here's the errors I get : 
`127.0.0.1 - - [07/Aug/2016:00:12:48 +0200] "GET /socket.io/?EIO=3&transport=websocket&sid=b16f1cf1ebce4a8ca2de554a820a0239 HTTP/1.1" 500 - "-" "-"
[2016-08-07 00:12:48 +0200] [9352] [DEBUG] Failed to send error message.
`

And I try desperately to output some errors without luck : I tried with print, logger but no messages are printed.
For example this print is never outputted.

`@socketio.on('connect')
def test_connect():
    print('\n\n\n CONNECTION \n\n\n')
`
I don't know how to debug my app. I don't know why no events are triggered.

**Comment by miguelgrinberg** [comment]
You need to run your Flask application in debug mode, so that 500 errors like the one you show above display a stack trace to the console.
