### ISSUE TITLE
Event Handler Callback not passing all python-socketio event arguments

### ISSUE THREAD

**Issue by mklein0** [miguelgrinberg/Flask-SocketIO#305]
It appears the Flask-SocketIO library does not communicate all the handler arguments python-socketio is passing such as SID. 
  * https://github.com/miguelgrinberg/Flask-SocketIO/blob/v2.6.2/flask_socketio/__init__.py#L214-L217

Depending on the event, the event handler wrapper is dropping the Socket ID and potential environment arguments in the case of a connect event.

**Comment by miguelgrinberg** [comment]
The connection event does not have arguments. Use `request.sid` inside the handler to get the session id. This works in all event handlers, not only connect.

**Comment by mklein0** [comment]
Ah.

I am not use to the Flask usage model of the thread local globals yet. Thanks.
