### ISSUE TITLE
Emit is not sending data to the connected clients

### ISSUE THREAD

**Issue by Manuel83** [miguelgrinberg/Flask-SocketIO#308]
I updated Flask-SocketIO from Version 0.0.6 to the current 2.6.2.
I developed a home brewing controller based on Flask using WebSocket to Update the UI.
Currently about 200 home brewers are using the software. https://github.com/Manuel83/craftbeerpi

With version 0.0.6 everything was working fine. 

In my server I'm starting a background thread. This background thread is emitting data.
Unfortunately I don't get the data in the brewer.

How can I debug if Flask-Socket Io is sending the data or if its a case of the JavaScript Implementation.

How can I figure out if long polling or websocket is used for communication?

![image](https://cloud.githubusercontent.com/assets/5859486/17715056/cd39ea88-6402-11e6-8313-adc7a7befef1.png)

**Comment by miguelgrinberg** [comment]
Hey, your project looks super cool 👍 

I took a quick look, I think the main problem you have is that you upgraded Flask-SocketIO but left your Javascript client at the old 0.9.x release. Unfortunately the current Socket.IO protocol is incompatible with those old client versions. If you bring your socket.io client to something like a 1.3.x or 1.4.x I think things will work better.

I'd say try that, and if that is not enough post any errors you get and we'll go from there.

**Comment by Manuel83** [comment]
Thanks a lot. I will check the combination today evening.

Yesterday evening I found out that I have to use 
`socketio.sleep()` in a background task and not`time.sleep()`

**Comment by miguelgrinberg** [comment]
`socketio.sleep()` is a wrapper that abstracts your application from the different async frameworks, same as `socketio.start_background_task()`. If you call these wrapper functions you don't have to worry about using the proper functions for eventlet or gevent.

**Comment by Manuel83** [comment]
Its working! Thanks a lot. I updated the socketio client to 1.4.x
