### ISSUE TITLE
Message Queue example 

### ISSUE THREAD

**Issue by NickolasBoyer** [miguelgrinberg/Flask-SocketIO#310]
Hey Miguel first of all thanks for all your hard work! I have been using Flask-socketIO for a while now with great pleasure, it rocks! I have a quick question, is there, or is there ever going to be a example using message queues so that emitting from external events is possible, I have not succeeded yet in emitting from celery and I want too use RethinkDB's changefeeds to directly emit changes to clients. I have tried RabbitMQ as well as reddis but have not had any success despite numerous attempts.  If there is a basic example using the message queues avaliable anywhere I would be delighted to hear about it.
Thanks!

**Comment by miguelgrinberg** [comment]
Yes, I showed how to build an app that emits from celery in my PyCon 2016 class Flask at Scale. The code is here: https://github.com/miguelgrinberg/flack. The entire 3 hour long class is also on youtube: https://www.youtube.com/watch?v=tdIIJuPh3SI.

**Comment by NickolasBoyer** [comment]
Thank you so much! I'm sorry I was not be able to find it on my own.
