### ISSUE TITLE
Memory not decreasing when clients disconnecting

### ISSUE THREAD

**Issue by jonwhitee** [miguelgrinberg/Flask-SocketIO#311]
Hi Miguel,

Memory not decreasing when clients disconnecting, maybe you don't delete data from all lists?
for example, i putted a break point in the disconnect function in engineio and i found that on disconnecting this function wasn't called..

Another question, the queue in enginio (async['queue']) why there is no maxsize on the queue?
on a high frequency messeging the memory of the process will explode.

Thank you (:

**Comment by miguelgrinberg** [comment]
@jonwhitee there are some memory structures that are allocated on first use, so I expect some amount of memory to not be returned when clients disconnect. The disconnect event not called is strange, if you have an example that reproduces that problem I'd like to see it.

Regarding capping the size of the queue, I have never seen that queue growing too large, but if you feel having a max size is necessary I think having an optional configuration option for it is a good idea. Would you be interested in writing a PR for that?
