### ISSUE TITLE
flask_socketio.__version__

### ISSUE THREAD

**Issue by lukeyeager** [miguelgrinberg/Flask-SocketIO#314]
Many Python modules follow [PEP 396](https://www.python.org/dev/peps/pep-0396/) and provide `module.__version__`:
```py
>>> import flask
>>> flask.__version__
'0.10.1'
```
But this project doesn't:
```py
>>> import flask_socketio
>>> flask_socketio.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute '__version__'
```

Neither do [python-engineio](https://github.com/miguelgrinberg/python-engineio/blob/v1.0.0/engineio/__init__.py) or [python-socketio](https://github.com/miguelgrinberg/python-socketio/blob/master/socketio/__init__.py).

1. Why not?
2. Do you provide another way to query the version somehow?

**Comment by miguelgrinberg** [comment]
No reason, I just didn't think of it, and nobody asked until now.

**Comment by miguelgrinberg** [comment]
I've now added `__version__` to engineio, socketio and this package. Even though I think it is a good idea, note that PEP 396 is not an accepted PEP, it's been deferred due to lack of interest.

**Comment by lukeyeager** [comment]
* https://github.com/miguelgrinberg/python-engineio/commit/8e1f4e0b3cbfda8d1ac1dcae7102e9f1b3046c88
* https://github.com/miguelgrinberg/python-socketio/commit/b436d60a9ffe787a25e284046d32f5d9f8c18f58
* https://github.com/miguelgrinberg/Flask-SocketIO/commit/200424160e1f28b40e82daa5e427d8953614d612

Great stuff, thanks!

> note that PEP 396 is not an accepted PEP, it's been deferred due to lack of interest

Thanks for pointing that out - I didn't realize that.
