### ISSUE TITLE
Default mode set to gevent_uwsgi

### ISSUE THREAD

**Issue by mekanix** [miguelgrinberg/Flask-SocketIO#316]
Version 1.0.0 of enginetio adds gevent_uwsgi async mode in [engineio/server.py](https://github.com/miguelgrinberg/python-engineio/blob/master/engineio/server.py#L94) which is tried before gevent. Flask-SocketIO doesn't even handle gevent_uwsgi as async_mode in [flask_socketio/__init__py](https://github.com/miguelgrinberg/Flask-SocketIO/blob/master/flask_socketio/__init__.py#L88)

**Comment by miguelgrinberg** [comment]
Yes, the support for gevent_uwsgi is almost done, the rest of the changes will be available soon.

**Comment by miguelgrinberg** [comment]
This should be okay now, but make sure you upgrade Flask-SocketIO, python-socketio and python-engineio to the latest releases. Please reopen if you still have problems with this.
