### ISSUE TITLE
Simple Example

### ISSUE THREAD

**Issue by adityosnrost** [miguelgrinberg/Flask-SocketIO#317]
Hi, i'm trying to learn websocket using Python as server-side and JavaScript as my client-side. I have this setup on my server side:

![python server](https://cloud.githubusercontent.com/assets/8223156/18166525/dde814de-7075-11e6-89af-79f4122a2395.PNG)

and this is my simple client side:

![javascript clien](https://cloud.githubusercontent.com/assets/8223156/18166531/ee78723a-7075-11e6-8af2-bc63deea1646.PNG)

I've managed to get connected. But, whenever I tried to click and trigger an event of getevent, it does not work. Is my code is right ? I've followed a couple of example of client and server codes. But, none of them are worked.

Is there any thing that should I do to run websocket ?

Thank You

**Comment by miguelgrinberg** [comment]
You did not include your entire source code, but looking at the first two screenshots, you have two separate `socketio` objects, one in each file. There should be only one of these that should be used application wide.

You may want to look at my examples. A single file example: https://github.com/miguelgrinberg/Flask-SocketIO/blob/master/example/app.py. A more complex example: https://github.com/miguelgrinberg/Flask-SocketIO-Chat

**Comment by adityosnrost** [comment]
Hi, thanks for your reply. That's all the code that I have touched, I am using simple flask project structure that generated by visual studio python flask template. 

I'm using views.py as my routing or basis code. runserver.py is the running python file. Where I should init SocketIO ? 

Thank You

**Comment by miguelgrinberg** [comment]
It does not matter where you initialize it. What matters is that you have one instance, not two.

I recommend that you try the examples I linked above, and maybe use one of those as a starting point for your project.

**Comment by adityosnrost** [comment]
Thanks for reply. I'll try it. They looks the same as my planning structures.
