### ISSUE TITLE
Delayed/Accumulated messages with APScheduler. time.sleep(0) solves it

### ISSUE THREAD

**Issue by olingerc** [miguelgrinberg/Flask-SocketIO#318]
I've been using your library for years, so many thanks.

Recently I started using APScheduler. I use flask-socketio to send progress to clients. My first line of code is:
```python
import eventlet
eventlet.monkey_patch()
```
Everything was peachy until I realized that messages get accumulated and are sent out in one big burst after some time. I was able to solve the problem by adding
```python
time.sleep(0)
```
after every emit. This is the basic BackgroundScheduler which uses threading together with an executor which runs the actual jobs in a concurrent.futures process pool. There also is a gevent executor. Do you think that would solve it? Or should I write an eventlet executor?

**Comment by miguelgrinberg** [comment]
The behavior that you observed is actually expected. When you call emit, the message is not immediately sent. Instead it is put in a queue, to be processed by another thread. Only when that other thread gets to run the message will be sent.

You have to consider that eventlet implements a cooperative multitasking environment. If you have a function that runs for a long time, then the only way other threads in the system get to run is when you do I/O (at which point eventlet implicitly gives the chance to other threads to run while your thread waits) or via explicit release of the CPU by calling the `sleep` function. So calling sleep in this situation should not be seen as a hack, you are allowing other threads to run concurrently with yours. Typically, if your function does some work in a loop, it is pretty standard to sleep once per loop iteration, to keep all the other threads in the system happy.

Switching to gevent will not eliminate the need to explicitly release the CPU, on this aspect eventlet and gevent work in the same way.

**Comment by olingerc** [comment]
Great explanation! I'll make sure to 'sleep' more often in that case. I can consider myself lucky that I used time.sleep as a test case during development or I would never have spotted this.
Can be closed from my side.
