### ISSUE TITLE
init_app() is not working with message_queue

### ISSUE THREAD

**Issue by DurandA** [miguelgrinberg/Flask-SocketIO#321]
When I instantiate SocketIO using (consecutive)
```
socketio = SocketIO(None, async_mode='eventlet', message_queue='redis://')
socketio.init_app(app)
```
the server does not receive/dispatch requests from the queue while using `socketio = SocketIO(None, async_mode='eventlet', message_queue='redis://')` is perfectly fine.

Do I miss something or is this an issue?

**Comment by miguelgrinberg** [comment]
This is an issue. The code that implements the `init_app` way of initializing the extension expects all extra arguments to be given to `init_app`, the args that you pass to the constructor are not saved. This will work just fine:

    socketio = SocketIO()
    socketio.init_app(app, async_mode='eventlet', message_queue='redis://')
