### ISSUE TITLE
Emit to specific client

### ISSUE THREAD

**Issue by VincentRichard555** [miguelgrinberg/Flask-SocketIO#322]
I am trying to emit to a specific client. I've seen this issue here but I would like to see working code for this. Here is some example code, say I want to message the first client every person joins, how do I do this?

I opened a stackoverflow question about this with code attached, maybe just answer it there? Here is the link: 

http://stackoverflow.com/questions/39423646/flask-socketio-emit-to-specific-user

If you would like this code here please ask. 

Thanks!

**Comment by miguelgrinberg** [comment]
(below is a copy of the accepted SO answer)

I'm not sure I understand the logic behind emitting to the first client, but anyway, this is how to do it:

    clients = []
    
    @socketio.on('joined', namespace='/chat')
    def joined(message):
        """Sent by clients when they enter a room.
        A status message is broadcast to all people in the room."""
        # Add client to client list
        clients.append(request.sid)

        room = session.get('room')
        join_room(room)

        # emit to the first client that joined the room
        emit('status', {'msg': session.get('name') + ' has entered the room.'}, room=clients[0])

As you can see, each client has a room for itself. The name of that room is the Socket.IO session id, which you can get as `request.sid` when you are handling an event from that client. So all you need to do is store this `sid` value for all your clients, and then use the desired one as room name in the `emit` call.
