### ISSUE TITLE
JSON decode errors not raised inside event handlers

### ISSUE THREAD

**Issue by zezic** [miguelgrinberg/Flask-SocketIO#323]
@socketio.on('connect', namespace='/test')
    def test_connect():
        json.loads("wrong JSON string")
        emit('my response', {'data': 'Connected'})

What expected:
JSONDecodeError raise.

What really happened:
JSONDecodeError **not** raised.

**Comment by miguelgrinberg** [comment]
Do you have an error handler set up? Any exceptions raised during the handling of an event will cause the error handler to be invoked.

**Comment by zezic** [comment]
Really, I don't set up error handler. Sorry for false report. Problem solved.
