### ISSUE TITLE
Gunicorn Server suddenly stops accepting new connections

### ISSUE THREAD

**Issue by christopher-abastar** [miguelgrinberg/Flask-SocketIO#328]
Hello Miguel,

Currently, i'm using the gunicorn server(1 worker) as in the docs specified. Recently, I have around 300+ active clients and recently reached 400+ marked. But suddenly I encountered an error in freebsd 10.3 saying:

```sh
sonewconn: pcb 0xfffff800c222b620: Listen queue overflow: 3073 already in queue awaiting acceptance (7033 occurrences)
```

So I went in and checked the backlog of the queues via netstat -Lan
```
Current listen queue sizes (qlen/incqlen/maxqlen)
Proto Listen Local Address
tcp4 3073/0/2048 127.0.0.1.5001
tcp4 0/0/4096 *.8888
tcp4 0/0/4096 *.80
```

Also the time wait state of the connections was very high.
```sh
netstat -a | grep TIME_WAIT | wc -l 
2919
```
I already posted some questions on reddit/r/freebsd to confirmed that it isn't some driver bug

https://www.reddit.com/r/freebsd/comments/53nmae/help_on_listen_queue_overflow/

The CPU wasn't high that high 5-10% as I'm running a c4.large and utilizing only 1 CPU & 1 process (for debugging process).

The only problem is when this occurred, it stopped accepting new connections (no gunicorn error or whatever) it just stopped. I just saw the number of clients dropping and activity is still going on.

I reverted back to standalone eventlet run.py for now. (hoping it won't occur as I just recently migrated to gunicorn setup)

Here's the command i use for the gunicorn

```sh
command= /home/xx/env/bin/gunicorn wsgi:app --bind 127.0.0.1:5001 --pid /tmp/gunicorn-chat1.pid --workers 1 --worker-class eventlet --error-logfile /var/log/gunicorn/gunicorn-chat.err
```

Hoping for your insights.

**Comment by miguelgrinberg** [comment]
Have you increased the value of `somaxconn`? If I remember correctly the default in FreeBSD is unrealistically slow.

The problem must be happening when you get a sudden batch of connections, all at the same time. You need to make sure the size of the listening queue is large enough to allow the system to ride through the spike.

Also you may want to ask in the gunicorn project. Maybe they have seen this and have other ideas.

**Comment by christopher-abastar** [comment]
yes @miguelgrinberg somaxconn has been increased. Also the netstat above i posted has a maxqlen of 2048.

I did check AWS elb connection charts, the increase was just gradual and not a burst connection.   When this occured,  the backlog of the queue greatly was increased from 0 -> 3073 connections and it seems it wasn't accepting new connections. I did try to kill the TIME_WAIT state connections by reducing the time but still it wasn't responding.. So had to restart it in the end.

**Comment by miguelgrinberg** [comment]
Unfortunately I have not seen this problem myself, but I don't use FreeBSD much these days (I used to in the past, my blog is actually hosted on FreeBSD still). I think your best bet is to report the problem to the gunicorn project.

**Comment by christopher-abastar** [comment]
ok thanks miguel.

**Comment by christopher-abastar** [comment]
hi @miguelgrinberg ,

So i'm still running eventlet for now and I haven't reach the 400+  to anticipate the error. I checked my netstat listen queue for the run.py and it's only set to 50, probably the default of eventlet

```sh
$ netstat -Lan                                                                                                                                                                                              130 ↵
Current listen queue sizes (qlen/incqlen/maxqlen)
Proto Listen         Local Address
tcp4  0/0/50         *.5001
tcp4  0/0/4096       *.8888
tcp4  0/0/4096       *.80
```

Is there a way or me to increase the backlog similar  to the docs in eventlet? 
Just in case I need to increase it.

```ascii
eventlet.listen(addr, family=<AddressFamily.AF_INET: 2>, backlog=50)

```
source:  http://eventlet.net/doc/basic_usage.html

**Comment by miguelgrinberg** [comment]
The `backlog` setting is currently not exposed. The server started by `socketio.run()` is a not supposed to be fully featured, you can run your own server if you need more customization. For example, this starts an eventlet server that sets a backlog option:

```python
import eventlet
import eventlet.wsgi
eventlet.wsgi.server(eventlet.listen(('', 5000), backlog=1024), app)
```

**Comment by christopher-abastar** [comment]
Thanks @miguelgrinberg 

I think i finally found the one causing it, When I run it I attached the new relic agent to the gunicorn process or eventlet process. that probably caused a stall of the process eventually causing the process to stop accepting connections.

```sh
command=/home/xx/env/bin/newrelic-admin run-program  /home/xx/env/bin/gunicorn wsgi:app --bind 127.0.0.1:5001 --pid /tmp/gunicorn-chat1.pid --workers 1 --worker-class eventlet --error-logfile /var/log/g
```

I already reached more than 400+ 450+ concurrent connections and it's stabilizing.

**Comment by christopher-abastar** [comment]
HI @miguelgrinberg 

I posted more on the eventlet group on this. It seems the previous post i thought was the solution but it wasn't, it just prolonged the server but still stalls in the  #process

https://github.com/eventlet/eventlet/issues/350 #

**Comment by christopher-abastar** [comment]
Hi @miguelgrinberg ,

Anyway just to share some tweaks I did just to stabilize the load of the server. I tweaked the how the wsgi server runs using greenpool. I think by default it only allows 1024 connections.

Here's the example diff:

```diff
-                eventlet.wsgi.server(eventlet_socket, app,
-                                     log_output=log_output, **kwargs)
-
+                pool = eventlet.GreenPool(10000)
+                eventlet.wsgi.server(eventlet_socket, app, custom_pool=pool,
+                                              debug=True,
+                                              log_output=log_output, **kwargs)
```

Also, Since I was using HaProxy, I had to enable the server tcp keepalive.

```sh
option srvtcpka
```

So far, it's stable it has been running for weeks now without restart.

tyvm
