### ISSUE TITLE
Session Affinity on Heroku

### ISSUE THREAD

**Issue by arthurtyukayev** [miguelgrinberg/Flask-SocketIO#333]
Reading the Multiple Workers deployment guide, it says that you must use Sticky Sessions with nginx's ip_hash. I was wondering if deploying on Heroku you can use Session Affinity? Is it the same thing?

https://devcenter.heroku.com/articles/session-affinity

If I enable Session Affinity, can I have a MQ to sync things up. Can I scale with multiple Heroku dynos?

**Comment by miguelgrinberg** [comment]
Never tried it myself, but based on their docs I think their session affinity should work just fine. You have to use eventlet or gevent for your workers though, as that will allow each worker to handle multiple requests concurrently (another requirement to get multiple workers going).

**Comment by arthurtyukayev** [comment]
I assume that using Gunicorn's eventlet or gevent workers will also work fine as long as I use the `-w 1` tag in the Procfile?

**Comment by miguelgrinberg** [comment]
Yes, gunicorn's workers for eventlet and gevent are both compatible when using a single worker.

**Comment by arthurtyukayev** [comment]
Thank you.
