### ISSUE TITLE
NGINX with SSL

### ISSUE THREAD

**Issue by stefaang** [miguelgrinberg/Flask-SocketIO#334]
I'd like to share my NGINX config file as it is even simpler than in the documentation.. and it has basic SSL support. Just let me know if you rather want me to post this in the wiki.
The official documentation removes redirection for some unknown reason (I suspect copy pasta).
Anyway, this is a good starting point for wss:// support.

```
server {
   listen 80;
   server_name "insertsitename.com";
   return 301 https://$server_name$request_uri;
}

server {
   listen 443;
   server_name "insertsitename.com";

   add_header Strict-Transport-Security "max-age=31536000";

   ssl on;
   ssl_certificate     /etc/nginx/certificates/insertsitename.com.crt;
   ssl_certificate_key /etc/nginx/certificates/insertsitename.com.key;

   location / {
      include proxy_params;
      proxy_pass http://127.0.0.1:5000;
   }

   location /socket.io {
      proxy_pass http://127.0.0.1:5000/socket.io;
      proxy_http_version 1.1;
      proxy_buffering off;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
      proxy_read_timeout 86400;
   }
}
```

**Comment by miguelgrinberg** [comment]
Thanks!

I will combine some of your improvements/simplifications with the example that I have in the documentation.

**Comment by miguelgrinberg** [comment]
I did not include SSL in the examples, since that is unrelated to Socket.IO, but I did take some of the other improvements you are suggesting here. Thanks!
