### ISSUE TITLE
Cannot get it to work with Openshift

### ISSUE THREAD

**Issue by dneyirp** [miguelgrinberg/Flask-SocketIO#339]
Hi Miguel

Many thanks for the excellent software.

I am having trouble trying to get Flask-SocketIO working with RedHat's Openshift ([http://www.openshift.com]) server.

Your example ([https://blog.miguelgrinberg.com/post/easy-websockets-with-flask-and-gevent]) works perfectly on my local machine. However when I upload it to the Openshift server it does not work. This is due to Openshift  using port 80 for the normal HTTP traffic but a different port (8000) for websocket traffic.

I have tried all sorts of methods I could find from the net but cannot get it to work.
Can you help with the appropriate setup to get your example above to work on Openshift?

Many thanks

**Comment by miguelgrinberg** [comment]
I'm not familiar with OpenShift, but based on the port restrictions you mention it seems to me you have to pick a single transport to use. If you connect your socket.io client to port 80 you will have only long-polling available. If you connect to port 8000, then you have to tell the client to connect directly using WebSocket, as the default is to connect on long-polling first, then upgrade. See https://coderwall.com/p/pgk00a/socket-io-and-openshift-websockets for an example of how to use the WebSocket transport with Socket.IO.

**Comment by dneyirp** [comment]
Okay thanks, appreciate the feedback.
