### ISSUE TITLE
how to work with meinheld gunicorn?

### ISSUE THREAD

**Issue by tkisme** [miguelgrinberg/Flask-SocketIO#340]
how to work with meinheld with gunicorn

**Comment by miguelgrinberg** [comment]
Meinheld is currently not officially supported. The platforms that are supported and tested are:

- eventlet
- gevent + gevent-websocket
- gunicorn + eventlet
- gunicorn + gevent + gevent-websocket
- uWSGI + gevent

These are all covered in the documentation.

**Comment by qwexvf** [comment]
@miguelgrinberg what are the best deployment platforms for now ? cause any of these i got errors.

**Comment by miguelgrinberg** [comment]
These are all working. What errors do you get?

**Comment by tkisme** [comment]
@miguelgrinberg thank you for explain
@qwexvf please open a new issue
