### ISSUE TITLE
socketio emit in separate process involving zmq

### ISSUE THREAD

**Issue by etseidler** [miguelgrinberg/Flask-SocketIO#342]
Hi. I'm working on a relatively simple flask-socketio app. The part of the app that I'm working on now is using a socketio emit in a separate non-server process*. I've looked at #113 and #125 and started skimming #204 and #158 to get some background info.  [Emitting from an external process](https://flask-socketio.readthedocs.io/en/latest/#emitting-from-an-external-process) is also helpful. Looks like it's intentional that socketio emits don't work in a separate process. and it seems to make sense, to some degree, to utilize a message queue to enable separate-process emits, although i'm still a little fuzzy on the details with that.

one factor that i haven't yet mentioned, and which is confusing me, is that for the separate process in my app, all it's doing is receiving zmq messages on a zmq socket (that part works fine in a separate process), performing a slight conversion on the data received, then emitting that data to the client via socketio (this is the part that breaks down in a separate process).

so before i try to incorporate a(nother) message queue simply for the purpose of enabling separate non-server process socketio emits, i have to ask, is there some simple way of doing this translating of received zmq events to socketio emits that i'm missing? or do i really need a separate message queue if i want to do a socketio emit on a separate process? i also looked at kombu briefly and it looks like there may be some support for zmq, but i'm having trouble keeping all the components and their purposes straight.

do you have any suggestions/advice?

\* = by the way, i have no trouble using a thread with a sleep to do the socket emit. i'd just really like to use a separate process, if at all possible.

**Comment by miguelgrinberg** [comment]
This is fairly complex stuff to think about. If you already have an integration with zeromq, I think what makes more sense is to also use zeromq for the communication between your auxiliary process and the SocketIO server. I have not tried kombu with zmq, but there is support, so that part looks promising.

If you want to do a quick test, I recommend you get the code from [flack](https://github.com/miguelgrinberg/flack), get it to run with Redis or RabbitMQ first, as those two I know for a fact that work well, and once you know you can run it, switch the queue for zmq to confirm everything still works.

**Comment by etseidler** [comment]
Thanks for the quick reply. I'll give that a shot.

**Comment by etseidler** [comment]
i was able to get redis to work for non-server process emits on both the flack sample app as well as my app. i was not able to get zmq to work for either app. either i'm not doing something right to initialize the message queue with the zmq transport, or the zmq transport implementation is faulty. apparently the zmq transport was removed entirely in the latest major version of kombu, and if i'm reading things right, it was only experimental when it was a kombu transport. there are a few other transports like file system, in memory, pyro, etc that i might look at to see if they work and to compare to the zmq transport implementation.

since this seems to be an issue not with flack-socketIO, but with the message queue transport, i can close this issue if you like. thanks again for your help.

**Comment by etseidler** [comment]
ok, one more question. say i were to directly use zmq in the flask-socketIO app to facilitate IPC. it's trivial to _send_ a message from another process. but how could i set up a zmq listener in the same process as the web server such that the socketIO emit would work as it does when using threads instead of multiprocessing?

does that approach even make sense, or is the message_queue option in the socketIO app init still my best bet?

**Comment by miguelgrinberg** [comment]
Sure, you can simply disregard the message queue functionality in Flask-SocketIO and instead implement your own solution that does the same thing over zmq. Just put a zmq listener in a background thread on the server process, and emit from there.

**Comment by etseidler** [comment]
i was able to do that just now using a thread spawned from the main server process. going back to the message_queue option, when redis is used, there needs to be a redis server running on the default port. is there some sort of equivalent zmq broker that would have to be running for the message_queue option to work with the zmq transport?

**Comment by miguelgrinberg** [comment]
In Flask-SocketIO use of zmq is through the [kombu](http://docs.celeryproject.org/projects/kombu/en/latest/) package, which is part of Celery. Unfortunately documentation and examples of kombu or Celery usages with zeromq is nonexistent, so it isn't really clear what the requirements are.

**Comment by etseidler** [comment]
Gotcha. Thank you again for your responses.

-- sent from my phone
