### ISSUE TITLE
ssl(https) error 

### ISSUE THREAD

**Issue by DoHyeong** [miguelgrinberg/Flask-SocketIO#343]
context = SSL.Context(SSL.SSLv3_METHOD)## SSL.Context(SSL.SSLv23_METHOD)
    cert = 'server.crt'
    pkey = 'server.key'
    context.use_privatekey_file(pkey)
    context.use_certificate_file(cert)
    socketio.run(app,'0.0.0.0',446,ssl_context=(cert, pkey),threaded=True)

---

returns 
<gevent._socket3.socket object, fd=53, family=2, type=1, proto=0>: Invalid HTTP method:
error
how can I resolve it?
thank you

**Comment by miguelgrinberg** [comment]
What webserver are you using?

**Comment by garfieldnate** [comment]
I am getting this error as well. I am running my server like so:
     socketio.run(app, debug=True, host='0.0.0.0', port=9001, ssl_context='adhoc')

I am running the file directly with Python 3.6, without using nginx or other external servers.
