### ISSUE TITLE
how to change attribute of emitted instance?

### ISSUE THREAD

**Issue by Popkultur** [miguelgrinberg/Flask-SocketIO#346]
If I emit some server instances by the client, and this instances keep running in the background because they have a (endless) while-loop inside, how can I change an attribute of the running instance to change the state? for example, I have attributes like instance.close or instance.resize, and if they change the instance changes within the loop.

I'm running monkey patched eventlet.
Thank you!

**Comment by miguelgrinberg** [comment]
What do you mean in this context by an "instance"? Is this a background thread? Can you provide a more specific example?

**Comment by Popkultur** [comment]
This is what I mean:

`
def on_connect(vsnum):
    socketio.emit('sendpic', {'vsnum': vsnum, 'buffer': bi, 'status': 0})  
    c = IpCamera(0);
    while c.status == 0:
        buffer = c.get_frame()
        socketio.emit('sendpic', { 'vsnum': 1, 'buffer': buffer, 'status': 0 })
        @socketio.on('camrecstart')
        def camrecstart():
            c.camrec = True
        @socketio.on('camrecstop')
        def camrecstop():
            c.camrec = False
    return 'ok'
`

It looks like I managed it to solve the problem. Thank you!

**Comment by Popkultur** [comment]
However, I realized that this code will not work properly. It will choose randomly eventlet-Threads and jump into them.

**Comment by miguelgrinberg** [comment]
I still don't understand, sorry. Is the indentation on your example what you intended? It looks wrong, normally the socketio decorated functions should appear at the outer level.

**Comment by Popkultur** [comment]
```
c = {}
def showcambackground(vsnum):
    global c
    c[vsnum] = IpCamera(source);
    while c[vsnum].status == 0 and c[vsnum].camclose == False:
        buffer = c[vsnum].get_frame()
        socketio.emit('sendpic', { 'vsnum': vsnum, 'buffer': buffer, 'status': 0 })
    return 'ok'

thread = {}
def on_connect(vsnum):
    global thread
    if not vsnum in thread:
        thread[vsnum] = Thread(target=showcambackground, name='thread-'+vsnum, args=(vsnum, ))
        thread[vsnum].start()
    return 'ok'

@socketio.on('camrecstart')
def camrecstart(data):
    global c
    c[data['vsnum']].camrec = True
```

This is what I intended to do, and it seems to work now. Sorry that I could not make it clearer.
