### ISSUE TITLE
doing long operations inside the event handler

### ISSUE THREAD

**Issue by jmrbcu** [miguelgrinberg/Flask-SocketIO#348]
How to do long operations inside an event handler with Flas-SocketIO, for instance, I notice the following code does not work in every situation. Also, in some cases, messages don't get received on the client side if the handler emitting it does not finish.
```
@socketio.on('test_event')
def on_test_event():
    c = 0
    while True:
        print 'On the server: {0}'.format(c)
        c += 1
        socketio.sleep(1)
```

Also, why do you recommend eventlet over gevent right now?

**Comment by miguelgrinberg** [comment]
Not sure I understand your example. You say that messages don't make it to the client, but this code isn't sending anything to the client.

If you want to use long event handlers I recommend that you add `async_handlers=True` to your `SocketIO` constructor. That will run event handlers asynchronously.

> Also, why do you recommend eventlet over gevent right now?

Mainly two reasons: First, my observations regarding performance of WebSocket is that eventlet's implementation is slightly faster. Second, eventlet has been running on Python 3 for much longer than gevent. Package gevent-websocket isn't even ported to Python 3 yet.

**Comment by jmrbcu** [comment]
Sorry, I forgot to add the emitting part, here is the complete example:

```
@socketio.on('test_event')
def on_test_event():
    c = 0
    while True:
        print 'On the server: {0}'.format(c)
        emit('counter', c)
        c += 1
        socketio.sleep(1)
```

So, if I understand correctly, adding: `async_handlers=True` to SocketIO constructor will yield on every socketio.sleep(1) giving chance to some other `on_test_event` handler from another client to run?

Thanks Miguel, this is an awesome package!

**Comment by miguelgrinberg** [comment]
@jmrbcu the `async_handlers=True` option will invoke your handlers (like your `on_test_event()` function) in a background thread, separate from the threads where Flask-SocketIO processes events. This prevents your long running function from ever blocking tasks that are internal. Give that a try and let me know if it helps.

**Comment by jmrbcu** [comment]
Well, it is not working for me, here is the code in my `events.py`, `count` events are flushed at the end when the server handler finish. My method of testing is as follow:

1- Open up the main page using one browser (opera): `http://localhost:5000`
2- Open up the main page using one browser (safari): `http://localhost:5000` 
3- Open up the main page using one browser (chrome): `http://localhost:5000`

Here is where I create the app at `project_root/app/__init__.py`:
```python
from eventlet import monkey_patch
monkey_patch()

from flask import Flask
from flask_redis import FlaskRedis
from flask_socketio import SocketIO
from config import config

socketio = SocketIO(async_handlers=True)
redis_client = FlaskRedis()


def create_app(config_name):
    """Create an application."""
    app = Flask(__name__)
    app.config.from_object(config[config_name])

    # initialize objects depending on the app
    socketio.init_app(app, async_mode='eventlet')
    redis_client.init_app(app)

    from .transcriber import transcriber
    app.register_blueprint(transcriber)

    return app
```

Here a snippet of my app `events.py`:
```python
@socketio.on('start', namespace='/transcriber')
def on_start(cid):
    counter = 20
    while counter:
        msg = 'Thread: {0}, count: {1}'.format(eventlet.getcurrent(), counter)
        print msg
        emit('count', counter)
        counter -= 1
        socketio.sleep(1)
```

here is the client code:
```javascript
$(document).ready(function() {
    socket = io(url);
    socket.on("connect", function () {
        console.log('Connected, trying to get live transcription for call with id: ' + cid);
        socket.emit('start', cid);
    });

    socket.on("count", function (count) {
        $("#timeline").html(count)
    })
});
```

**Comment by miguelgrinberg** [comment]
Can you describe exactly what you mean by "it does not work"? Do you get any errors on the clients or on the server? Have you enabled client and server logging specifically for Socket.IO to see if there are any clues there?

**Comment by jmrbcu** [comment]
Sorry, I just found the problem and the solution. It's basically the way I was initializing the SocketIO instance, before it was like:

```python
from eventlet import monkey_patch
monkey_patch()

from flask import Flask
from flask_redis import FlaskRedis
from flask_socketio import SocketIO
from config import config

socketio = SocketIO(async_handlers=True)
redis_client = FlaskRedis()


def create_app(config_name):
    """Create an application."""
    app = Flask(__name__)
    app.config.from_object(config[config_name])

    # initialize objects depending on the app
    socketio.init_app(app, async_mode='eventlet')
    redis_client.init_app(app)

    from .transcriber import transcriber
    app.register_blueprint(transcriber)

    return app
```

But this way, `async_handlers=True` was being overwritten when later I call `create_app` and line:
`socketio.init_app(app, async_mode='eventlet') `
executed, so, `async_handlers` is set to `False`, which is the default.

now I have it like this:

```python
from eventlet import monkey_patch
monkey_patch()

from flask import Flask
from flask_redis import FlaskRedis
from flask_socketio import SocketIO
from config import config

socketio = SocketIO()
redis_client = FlaskRedis()


def create_app(config_name):
    """Create an application."""
    app = Flask(__name__)
    app.config.from_object(config[config_name])

    # initialize objects depending on the app
    socketio.init_app(app, async_mode='eventlet', async_handlers=True)
    redis_client.init_app(app)

    from .transcriber import transcriber
    app.register_blueprint(transcriber)

    return app
```

and the problem is solved!
One more, thing, is there any advice against using long handlers like this one? 
Is it a bad practice?

**Comment by miguelgrinberg** [comment]
Oh, actually the `async_handlers` option should have worked in both places, that's a bug, I'll fix it.

> One more, thing, is there any advice against using long handlers like this one? 
> Is it a bad practice?

I wouldn't call it a bad practice, but it does go against the idea of event based programming. Normally when you work with async frameworks you have short event handlers that are invoked to respond to events. I added the `async_handlers` option specifically for this type of situation, I have found that a lot of people write long functions, so I make them play nice with the rest of the async system by putting them in background threads.

**Comment by miguelgrinberg** [comment]
@jmrbcu I finally tested this, and it seems `async_handlers` can be given either in the `SocketIO` constructor or in `init_app`, it works in both cases. Is it possible that you were using a release older than 2.7.2 when you tested this? That's the release in which that bug was fixed, see #321 for more details.

**Comment by jmrbcu** [comment]
Thanks for letting me know Miguel, you were right, the version of Flask-SocketIO I was using was: 2.7.1.

**Comment by miguelgrinberg** [comment]
Great. Then I'll go ahead and close this issue. Thanks!
