### ISSUE TITLE
Proper way to monkey patch?

### ISSUE THREAD

**Issue by jmrbcu** [miguelgrinberg/Flask-SocketIO#349]
Hi Miguel, another probably silly question. What is the proper way to monkey patch with Flask-SocketIO if in advance I won't know what async mode SocketIO is gonna use?. Base on the precedence (eventlet --> gevent --> threading) I have something like this in my `flask_project_root/app/__init__.py` but, is this the right way or can I patch based on the selected `async_mode` after this is selected by SocketIO?

```
try:
    from eventlet import monkey_patch as monkey_patch
    monkey_patch()
except ImportError:
    try:
        from gevent.monkey import patch_all
        patch_all()
    except ImportError:
        pass

from flask import Flask
from flask_redis import FlaskRedis
from flask_socketio import SocketIO
from config import config

socketio = SocketIO(async_handlers=True)
redis_client = FlaskRedis()


def create_app(config_name):
    """Create an application."""
    app = Flask(__name__)
    app.config.from_object(config[config_name])

    # initialize objects depending on the app
    socketio.init_app(app, async_mode=None)
    redis_client.init_app(app)

    from .transcriber import transcriber
    app.register_blueprint(transcriber)

    return app

```

**Comment by miguelgrinberg** [comment]
What you came up with should work, but it is really not a great idea to assume that the selection of an async mode will always be the same as it is today.

How come you don't know which async mode is being used? Are you building a generic library for others to use? Because if you are building an application I see no reason for you to try to support all async modes. Just pick one and go just with that one.

**Comment by jmrbcu** [comment]
Well, yes, in the case of building just an app, you are right!

**Comment by miguelgrinberg** [comment]
Actually the other alternative, which is the one I take, is to not rely on monkey patching. Just use the functionality that you need directly from the eventlet and/or gevent frameworks, At run time you can ask Flask-SocketIO which of the async modes is being used, and with that you can choose the right framework to use.

**Comment by jmrbcu** [comment]
Yeap, you are right but, let's suppose I need to use Redis Pub/Sub mechanism, which is blocking, in this case I need to know in advance which method is being used because, correct me if I am wrong, monkey patching needs to be applied at the very beginning of the app, before any function of the blocking library is called.

**Comment by miguelgrinberg** [comment]
Yes. If you are using third party libraries that don't have native support for eventlet/gevent then you have no way around monkey patching.

But as I mentioned above, you are making assumptions about how Flask-SocketIO is going to make a selection of an async framework, and this process may change in the future (It did change once already, when I introduced support for uwsgi).

With all the constraints that you have, I think the only sensible solution is for you to take ownership of the async mode selection and completely override Flask-SocketIO's. This means you will need to select which method to use based on installed packages, or maybe via configuration, and then you will set the `async_mode` argument to `SocketIO` to disable the automatic selection.

**Comment by jmrbcu** [comment]
That is exactly what I am doing right now, I selected eventlet mode. Now, that being said, I think is a very common case to be using some blocking library like Redis (Pub/Sub, Queue handling with BLPOP, etc) in conjunction with SocketIO code, so, in these cases, the only option to explicitly select the async_mode ourselves.

**Comment by miguelgrinberg** [comment]
@jmrbcu in the code you posted above, you pass `async_mode=None`. That needs to be set to the mode that you selected, if not Flask-SocketIO will use its own selection algorithm, which may end up pick a different framework than yours.
