### ISSUE TITLE
example app.py errors

### ISSUE THREAD

**Issue by denis77** [miguelgrinberg/Flask-SocketIO#350]
hello,
I am trying the **example app.py **(chat).
With eventlet, I got in console an error when I click on the Disconnect button.
Here is the output :
127.0.0.1 - - [06/Nov/2016 16:57:21] "GET /socket.io/?EIO=3&transport=polling&t=14784478417
c36576788d7b49e19d055d8e220f96d4 HTTP/1.1" 200 215 0.017001
Client disconnected c36576788d7b49e19d055d8e220f96d4
127.0.0.1 - - [06/Nov/2016 16:58:49] "GET /socket.io/?EIO=3&transport=websocket&sid=c365767
9d055d8e220f96d4 HTTP/1.1" 200 0 87.752019
Traceback (most recent call last):
  File "C:\Users\ad.min\Envs\test_sockets\Flask-SocketIO-master\example\venv\lib\site-pa
entlet\greenpool.py", line 82, in _spawn_n_impl
    func(*args, **kwargs)
  File "C:\Users\ad.min\Envs\test_sockets\Flask-SocketIO-master\example\venv\lib\site-pa
entlet\wsgi.py", line 719, in process_request
    proto.__init__(sock, address, self)
  File "c:\users\ad.min\appdata\local\programs\python\python35-32\Lib\socketserver.py",
 in __init__
    self.finish()
  File "C:\Users\ad.min\Envs\test_sockets\Flask-SocketIO-master\example\venv\lib\site-pa
entlet\wsgi.py", line 636, in finish
    greenio.shutdown_safe(self.connection)
  File "C:\Users\ad.min\Envs\test_sockets\Flask-SocketIO-master\example\venv\lib\site-pa
entlet\greenio\base.py", line 474, in shutdown_safe
    return sock.shutdown(socket.SHUT_RDWR)
OSError: [WinError 10038] Une opération a été tentée sur autre chose qu\u2019un socket
(translation : one operation was tried on something other than a socket.

As I am curious, I uninstalled evenlet and  installed  gevent . (async_mode = "gevent" in app.py and app_namespace.py )
With gevent , the app is sending get and post messages continuously.

127.0.0.1 - - [2016-11-06 17:11:16] "GET /socket.io/?EIO=3&transport=polling&t=147844867586
b741010435fc45d3b1433b17f345f29f HTTP/1.1" 200 216 0.960055
127.0.0.1 - - [2016-11-06 17:11:17] "POST /socket.io/?EIO=3&transport=polling&t=14784486778
=b741010435fc45d3b1433b17f345f29f HTTP/1.1" 200 195 0.002000
127.0.0.1 - - [2016-11-06 17:11:17] "GET /socket.io/?EIO=3&transport=polling&t=147844867686
b741010435fc45d3b1433b17f345f29f HTTP/1.1" 200 216 0.989057
127.0.0.1 - - [2016-11-06 17:11:18] "POST /socket.io/?EIO=3&transport=polling&t=14784486788
=b741010435fc45d3b1433b17f345f29f HTTP/1.1" 200 195 0.002000
127.0.0.1 - - [2016-11-06 17:11:18] "GET /socket.io/?EIO=3&transport=polling&t=147844867786
b741010435fc45d3b1433b17f345f29f HTTP/1.1" 200 216 0.990057
127.0.0.1 - - [2016-11-06 17:11:19] "POST /socket.io/?EIO=3&transport=polling&t=14784486798
=b741010435fc45d3b1433b17f345f29f HTTP/1.1" 200 195 0.002000
127.0.0.1 - - [2016-11-06 17:11:19] "GET /socket.io/?EIO=3&transport=polling&t=147844867888
b741010435fc45d3b1433b17f345f29f HTTP/1.1" 200 216 0.985056
127.0.0.1 - - [2016-11-06 17:11:20] "POST /socket.io/?EIO=3&transport=polling&t=14784486808
=b741010435fc45d3b1433b17f345f29f HTTP/1.1" 200 195 0.003000
127.0.0.1 - - [2016-11-06 17:11:20] "GET /socket.io/?EIO=3&transport=polling&t=147844867989
b741010435fc45d3b1433b17f345f29f HTTP/1.1" 200 216 0.973056
127.0.0.1 - - [2016-11-06 17:11:21] "POST /socket.io/?EIO=3&transport=polling&t=14784486818
=b741010435fc45d3b1433b17f345f29f HTTP/1.1" 200 195 0.003000
127.0.0.1 - - [2016-11-06 17:11:21] "GET /socket.io/?EIO=3&transport=polling&t=147844868087
b741010435fc45d3b1433b17f345f29f HTTP/1.1" 200 216 0.973056
KeyboardInterrupt

But I didn't an error in the console  when I click on the Disconnect button.

Regards.

**Comment by miguelgrinberg** [comment]
Are you using the latest releases of Flask-SocketIO, python-socketio and python-engineio? I do not get any errors here when I click disconnect. Please show me the output of `pip freeze`.

**Comment by denis77** [comment]
Hello, here is the output of pip freeze:

eventlet==0.19.0
Flask==0.10.1
Flask-SocketIO==2.7.2
gevent==1.1.2
greenlet==0.4.10
itsdangerous==0.24
Jinja2==2.7.3
MarkupSafe==0.23
python-engineio==1.0.3
python-socketio==1.6.0
six==1.9.0
speedtest-cli==0.3.4
Werkzeug==0.10.4

regards

----- Mail original -----
De: "Miguel Grinberg" <notifications@github.com>
À: "miguelgrinberg/Flask-SocketIO" <Flask-SocketIO@noreply.github.com>
Cc: "denis77" <denis.gay@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Dimanche 6 Novembre 2016 17:27:33
Objet: Re: [miguelgrinberg/Flask-SocketIO] example app.py errors (#350)



Are you using the latest releases of Flask-SocketIO, python-socketio and python-engineio? I do not get any errors here when I click disconnect. Please show me the output of pip freeze .

**Comment by miguelgrinberg** [comment]
Can you open your browser console before you click the disconnect button? Let me know if any errors appear there when you disconnect. Also, what version of the Socket.IO client are you using?

**Comment by denis77** [comment]
No error in the console log when I disconnect.
I think the version of the socket client io is  here : ajax/libs/socket.io/1.3.5
I'm going to run the example on a mac today.
Regards
