### ISSUE TITLE
Initialize loggers in a normal way

### ISSUE THREAD

**Issue by mckelvin** [miguelgrinberg/Flask-SocketIO#352]
Thanks for maintaining the SocketIO family. As mentioned in https://docs.python.org/2/howto/logging.html :

> A good convention to use when naming loggers is to use a module-level logger, in each module which uses logging, named as follows:
>> logger = logging.getLogger(__name__)

But in **SocketIO** family (`Flask-SocketIO`, `python-engineio`, `python-socketio`), loggers are initialized in a lazy way (i.e.: inside `__init__` methods). This behaviour brings some headache problems for me.

I would like to control the log level and format of all loggers inside my app (which is proudly using Flask-SocketIO), so [the setup_logging](https://gist.github.com/mckelvin/c0781fdb8b419bbd1f7c0ded1abd4466#file-setup_logging-py-L31) function is called at the beginning of my (`main()`) function. But this doesn't work for SocketIO familiy, since loggers inside which are not created when the main is called yet. But There're still some workaround I can do, So I create loggers first and then pass into the SocketIO object:

```python
from flask_socketio import SocketIO
sio = SocketIO(
    logger=logging.getLogger("socketio"),
    engineio_logger=logging.getLogger("engineio"),
)
```

But sadly I find the logger in `engineio.server` is still leaking. I read the code and then I have to change to:

```python
from flask_socketio import SocketIO
sio = SocketIO()

sio.init_app(
    app,
    logger=logging.getLogger("socketio"),
    engineio_logger=logging.getLogger("engineio"),
)
```

Now everything looks good to me **BUT**, the `flask_socketio.SocketIO` and the `engienio.Server` are sharing the same logger (the logger named socketio). That's nasty though it's not a big deal to me.

I'd appreciate if all loggers could be changed to module level loggers:

> logger = logging.getLogger(__name__)

**Comment by miguelgrinberg** [comment]
Made logger static, as you suggested. See miguelgrinberg/python-socketio@749f8663c48cf100440ba51724542577e46c1b58 and miguelgrinberg/python-engineio@e6b3a6d8bce3d7f53fde7b56037fd9e9f7cbe492.
