### ISSUE TITLE
OSError: raw readinto() when exiting IE11

### ISSUE THREAD

**Issue by sebastianstigler** [miguelgrinberg/Flask-SocketIO#355]
I get a reproduceable traceback, when I close the IE 11 (not just the tab but the whole programm) after opening the following app (see [Stackoverflow](http://stackoverflow.com/questions/35394616/oserror-raw-readinto-returned-invalid-length-when-use-websockets) ). If I use Firefox or Chrome I don't get the traceback.

It is the same traceback as in #241 but I use socket.io on the client side and not websockets like in that issue!

**main.html**

    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Chat</title>
        <script type="text/javascript" src="{{ url_for('static', filename='jquery-2.2.0.js') }}"></script>
        <script type="text/javascript" src="{{ url_for('static', filename='socket.io.min.js') }}"></script>
    </head>
    <body>

    <script type="text/javascript" charset="utf-8">
    
         $(document).ready(function() {
    
             var socket = io.connect('http://' + document.domain + ':' + location.port);
    
             socket.emit('connect', {data: 'U connected'});
    
             socket.on('apply', function (e) {
                console.log('it works');
                     $('#log').append('<br>' + e.data + '<br>')
    
            });
    
         });
    
    </script>
    
    <h1 id="log"></h1>
    </body>
    </html>

**app.py**

    from flask_socketio import SocketIO, emit
    from flask import Flask, render_template
    
    
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'secret!'
    socket_io = SocketIO(app)
    
    
    @app.route('/')
    def index():
        return render_template('main.html')
    
    
    @socket_io.on('connect')
    def connect():
        emit('apply', {'data': "Connect"})
    
    if __name__ == '__main__':
        socket_io.run(app, debug=True)

**Traceback**

    Traceback (most recent call last):
      File "/home/sebastian/.virtualenvs/cuebung/lib/python3.4/site-packages/eventlet/greenpool.py", line 82, in _spawn_n_impl
        func(*args, **kwargs)
      File "/home/sebastian/.virtualenvs/cuebung/lib/python3.4/site-packages/eventlet/wsgi.py", line 719, in process_request
        proto.__init__(sock, address, self)
      File "/usr/lib/python3.4/socketserver.py", line 673, in __init__
        self.handle()
      File "/usr/lib/python3.4/http/server.py", line 401, in handle
        self.handle_one_request()
      File "/home/sebastian/.virtualenvs/cuebung/lib/python3.4/site-packages/eventlet/wsgi.py", line 330, in handle_one_request
        self.raw_requestline = self.rfile.readline(self.server.url_length_limit)
    OSError: raw readinto() returned invalid length -1 (should have been between 0 and 8192)

**pip freeze**
```alembic==0.8.8
amqp==1.4.9
anyjson==0.3.3
billiard==3.3.0.23
bleach==1.4.3
celery==3.1.23
click==6.6
docutils==0.12
dominate==2.2.1
eventlet==0.19.0
Flask==0.11.1
Flask-Bootstrap==3.3.7.0
Flask-HTTPAuth==3.2.1
Flask-Migrate==2.0.0
Flask-Script==2.0.5
Flask-SocketIO==2.7.1
Flask-SQLAlchemy==2.1
greenlet==0.4.10
html5lib==0.9999999
itsdangerous==0.24
Jinja2==2.8
kombu==3.0.35
Mako==1.0.4
Markdown==2.6.6
MarkupSafe==0.23
plantweb==1.0.0
psutil==4.3.1
python-editor==1.0.1
python-engineio==1.0.3
python-markdown-math==0.2
python-pam==1.8.2
python-socketio==1.5.1
pytz==2016.6.1
redis==2.10.5
redislite==3.0.296
requests==2.11.1
sadisplay==0.4.6
six==1.10.0
SQLAlchemy==1.0.15
visitor==0.1.3
Werkzeug==0.11.11
```

In Wireshark Version 2.2.1 I can see a difference in the ip packages after closing the websocket between IE and Firefox:

[Wireshark_traces.zip](https://github.com/miguelgrinberg/Flask-SocketIO/files/583145/Wireshark_traces.zip)

**Comment by miguelgrinberg** [comment]
IE has an approx market share of 2% these days, so I'm not going to pursue this issue.
