### ISSUE TITLE
How to share session between background threads

### ISSUE THREAD

**Issue by jmrbcu** [miguelgrinberg/Flask-SocketIO#356]
Hello again Miguel, sometimes I need to share values stored in the session with my background threads, but for some reason, when I try to read those values from the session in the background threads the only thing I see is the session object empty. Here is an example:

```py
@socketio.on('connect', namespace='/transcriber')
def on_start():
    @copy_current_request_context
    def transcriber():
        while not session.get(request.sid):
            print session
            socketio.sleep(1)

    session['key'] = 'testing value'
    session[request.sid] = False
    socketio.start_background_task(transcriber)


@socketio.on('disconnect', namespace='/transcriber')
def on_disconnect():
    session[request.sid] = True
```

In this case, the thread will never end because `session.get(request.sid)` will be always None, which means that changes to the session object at the beginning of the handler are not seen by the thread. Is this the intended behavior?

**Comment by miguelgrinberg** [comment]
There are some differences in how Flask and Flask-SocketIO implement the request context and the context globals, that is probably why Flask's `copy_current_request_context` does not work inside Flask-SocketIO events. I will look into it.

But if all you need is pass some values into your thread, no need to use the session for that, just pass the values directly as arguments, or the pass the session dictionary as an argument with `session._get_current_object()`. That will remove the need to use the copy request decorator.

**Comment by jmrbcu** [comment]
Sorry for the late response, basically, what you mean is instead of doing this:

```py
@socketio.on('test_event')
def on_test_event():
    @copy_current_request_context
    def long_handler():
        while True:
            print session['key']
            emit('response')
            socketio.sleep(1)

    session['key'] = 'testing value'
    socketio.start_background_task(long_handler)
```

I should be doing either this:

```py
@copy_current_request_context
def long_handler():
    while True:
        print session['key']
        emit('response')
        socketio.sleep(1)

@socketio.on('test_event')
def on_test_event():
    session['key'] = 'testing value'
    socketio.start_background_task(long_handler)
```

or better, this:

```py
def long_handler(session):
    while True:
        print session['key']
        emit('response')
        socketio.sleep(1)

@socketio.on('test_event')
def on_test_event():
    session['key'] = 'testing value'
    socketio.start_background_task(long_handler, session._get_current_object())
```

Am I right?

**Comment by miguelgrinberg** [comment]
The last of your examples definitely works, because you are sending the session dictionary directly.

The example in your first post does work in the way it is intended, so this issue is really not a bug, that's how Flask works. The `copy_current_request_context` decorator makes a copy of the request context, and gives that to the background thread. Any changes that you make to the session right below the thread function will happen after the decorator made the request context copy, so those will not be in the copy. The request context copy is not linked to the original, so changes will not be moved to the thread.
