### ISSUE TITLE
Flask-Login and jsessionid

### ISSUE THREAD

**Issue by charyorde** [miguelgrinberg/Flask-SocketIO#360]
When a user is authenticated (stored in user session), does flask-socketio identifies with jsessionid within the current_user context? I mean, do I need to perform any further handling of this process?

**Comment by miguelgrinberg** [comment]
Flask's `session` context variable is available in your Flask-SocketIO event handlers, so any authentication information you have stored in the session is accessible.

**Comment by charyorde** [comment]
Cool. However, Does `flask-socketio` implement all the loaders? That is, `request_loader`
Which of the loaders are implemented by `flask-socketio`? I'm using user_loader and header_loader in my app and wondering what `flask-socketio` is expecting. 

I debugged `current_user` and found only `request_loader`. Are other loaders supported?

`('current_user ', ('request_loader...', <Request 'http://192.168.56.1:5000/socket.io/?EIO=3&transport=polling&t=LXjHJcs' [GET]>)`

**Comment by miguelgrinberg** [comment]
@charyorde Socket.IO does not implement anything that is specific to Flask-Login. All it does is set up a request context before invoking your handlers. This request context has the data that was sent by the client in the Socket.IO connection call, including headers, cookies, etc.

**Comment by charyorde** [comment]
Ok. I've been able to hook it all together. I configured `flask-socketio` to use `jsessionid` like so:
`sio = SocketIO(app, client_manager=mgr, cookie='jsessionid')`
But I'm getting multiple jsessionid from the console:
```
Cookie:io=dfcc2c6de4244b31b00e68ea289d9ec3; jsessionid=022b37864f5142f4a168c2be01e442a5; jsessionid="a2F5b2RlLm9kZXllbWlAZ3JlZW53b29kLm5nOjE0NzkzOTk2MTcuODk6MzA="; session=.eJwdj01rg0AYhP9K2XMOZpMtROhBWCOG7LtE1O2-lxAbi-5HD6Zi3dD_3qWHgWFgHmae5Po59Y-BpN_T3G_IdbyT9EleOpISMNWAvlnQiB2oZpXcMqztXvBsRZ4HHZyHIBhQEcCDxaLyskCP_Oihvnuh9BaMG7W5BOQ60SpPoqfaNKtWrY-cHyjKVRYlixlFYxdByxVNvo38PRSXmLUODIwy9sGfLHI3Rg3IW6vDYARvFlD5G_ndkPnRT__7yY0eWUcrd_YHi-_OdcpluDs5VGzX0YM9e_YlTZ5AsEHWlor6Y47vXkXIIukPohVbdQ.Cw9qQg._IXrqSBADPuavI_UfA8M1OIJXHY
```
This is mine `jsessionid="a2F5b2RlLm9kZXllbWlAZ3JlZW53b29kLm5nOjE0NzkzOTk2MTcuODk6MzA="; `. Not sure how to restrict it to just this. Do you know whether `Flask` or `Flask-Login` happen to set own jsessionid or is it coming from `Flask-SocketIO`?

**Comment by miguelgrinberg** [comment]
I don't know anything about a jsessionid cookie. And I don't think you want to change the `cookie` argument in `SocketIO`, that's best left alone, unless you have a very specific need.

**Comment by charyorde** [comment]
I guess what I'm asking is that is this: `jsessionid=022b37864f5142f4a168c2be01e442a5;` generated as a result of this config: `sio = SocketIO(app, client_manager=mgr, cookie='jsessionid')` ?

I disabled my custom `jsessionid`, then after a while a new jsessionid is generated. I know it's not mine because of the pattern.

From the `flask-socketio` docs, `cookie – Name of the HTTP cookie that contains the client session id. If set to None, a cookie is not sent to the client.`. How does that behave?

**Comment by miguelgrinberg** [comment]
@charyorde You are getting carried away with this `cookie` feature of Socket.IO. It has nothing to do with your authentication problem, and 99.9% of the time be ignored. The `jsessionid` cookie is being added because you are passing that name in the `SocketIO` constructor. Any name you pass there will cause the server to set a cookie with that name. But this does not help your problem at all.

**Comment by charyorde** [comment]
Capitalized `JSESSIONID` seems to be what I needed on login. Thank you.
