### ISSUE TITLE
eventlet.monkey_patch() causing celery to never connect to redis

### ISSUE THREAD

**Issue by jdlovins** [miguelgrinberg/Flask-SocketIO#361]
Much like the issue #61 it seems when i add that line it breaks celery.

I'm trying to use flask, flask-socketio, and celery for frontend updates.

I can get socket communication working when im not trying to use celery but when i try to implement it i cant run the worker since it doesnt ever connect to redis. Am i missing something obvious? I'm using http://celeodor.com/flask-flask-socketio-celery-and-redis-background-task-processing/ as an example.

Thanks!

`app = Flask(__name__)
app.config.update(
    CELERY_BROKER_URL='redis://localhost:6379/0',
    CELERY_RESULT_BACKEND='redis://localhost:6379/0',
    SOCKETIO_REDIS_URL='redis://localhost:6379/0',
    SQLALCHEMY_DATABASE_URI='removed',
    SQLALCHEMY_TRACK_MODIFICATIONS=True,
    SECRET_KEY='adadhaoiwh12131',
    DEBUG=True
)

db = SQLAlchemy(app)

celery = Celery(app.name, broker=app.config['CELERY_BROKER_URL'])
celery.conf.update(app.config)

socketio = SocketIO(app, async_mode='eventlet', message_queue=app.config['SOCKETIO_REDIS_URL'])
eventlet.monkey_patch()

login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'login'

@celery.task(name="upload.handler", bind=True)
def upload_task(self, servers, files, redis):

    print(self.request.id)
    local_socketio = SocketIO(message_queue=redis)
    socketio.sleep(3)

    local_socketio.emit('test', {'data': 'background task starting ...'}, namespace='/mything')

`

**Comment by jdlovins** [comment]
Nevermind. I managed to find the repo and how he started the celery worker.

celery worker -A main.celery -P eventlet --loglevel=info

the -P eventlet was the missing thing!

**Comment by miguelgrinberg** [comment]
@jdlovins yes, one option is what you did, use Celery's eventlet support. But note that in most cases Celery does not need to run on eventlet, you only need eventlet on the Flask server. That is how I configured my [Flack](https://github.com/miguelgrinberg/flack) example app.

**Comment by jdlovins** [comment]
@miguelgrinberg I'm pretty newish to python so I'm not seeing where you are only setting flask with eventlet and not celery. Is it because all of my stuff is declared in one python file?

**Comment by miguelgrinberg** [comment]
Take a look at the [create_app](https://github.com/miguelgrinberg/flack/blob/master/flack/__init__.py#L29) function. It takes a `main` argument that configures for the Flask server (main=True) or auxiliary processes (main=False).

**Comment by jdlovins** [comment]
Hmm i changed my code around so it uses init_app like

**Comment by jdlovins** [comment]
@miguelgrinberg so I copied the structure of your project since it was way better than mine. It did fix the eventlet issue i was having but now im running into another issue. I import my celery tasks in the __init__.py file like you have but in my task I query the database using a model and i get 

"RuntimeError: application not registered on db instance and no application bound to current context"

How do I get/pass the context to the events module?

**Comment by miguelgrinberg** [comment]
Here is one of my tasks, which also requires an app context: https://github.com/miguelgrinberg/flack/blob/master/flack/events.py#L27.

**Comment by jdlovins** [comment]
Ah i did that but with the non aux thing and it did not like that. That worked for me, thank you so much @miguelgrinberg
