### ISSUE TITLE
This is a question on using flask-socketio inside an existing flask application

### ISSUE THREAD

**Issue by neela77777** [miguelgrinberg/Flask-SocketIO#362]
Hi Miguel, 

I have an existing flask application that does a bunch of stuff. I am trying to add a flask-socketio piece in order to stream realtime market data onto a webpage that I receiver from an external source. I am finding it hard to integrate flask-socketio into the existing application. I would appreciate any help. Here are snippets of what I have so far:
A piece of __init__.py

```python
import eventlet
from flask_socketio import SocketIO
import json
def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    mail.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    pagedown.init_app(app)
    eventlet.monkey_patch()
    socketio = SocketIO(app, async_mode='eventlet')
```

I have this in my manage.py ...

```python
if __name__ == '__main__':
    socketio.run(app)
```
clearly, this is a problem, because *socketio* is not recognized in manage.py
Because I have instantiated socketio in __init__.py, and it is not available in manage.py

Also, I don't know where to place the server side code that is in your example:

```python
@socketio.on('message')
def handle_message(message):
    print('received message: ' + message)
```

i am thinking this needs to go into the views.py of a typical Flask application.

I am not sure I am articulating my problem correctly.
I am trying to add flask-socketio functionality to an existing flask application.
A lot of this technology is new to me. I am taking your example trying to fashion it to my needs.
Please help.

Thanks in advance.
Neela.

**Comment by miguelgrinberg** [comment]
You can import `socketio` in your manage.py module, so that then you can start the server with `socketio.run(app)`.

If you want some ideas regarding project structure, you may want to take a look at my [flack](https://github.com/miguelgrinberg/flack) project.

**Comment by neela77777** [comment]
Thank you very much Miguel. Do I need Celery? Your Flack app seems to be integrated with Celery.   I currently use Flask with gunicorn and nginx. Haven't used Celery.

**Comment by miguelgrinberg** [comment]
Celery is not required for Flask-SocketIO. Flack uses it to run asynchronous tasks, if you don't need that, then ignore that part of the application.

**Comment by neela77777** [comment]
Thank you.

**Comment by neela77777** [comment]
I have a couple of follow up questions .. In order to keep things simple, I tried a standalone approach where I keep the "non socketio Flask" and "socketio Flask" applications separate. 
If I launch the socketio Flask application as "python application.py", it runs fine.  
The application is setup in the following manner:

import eventlet
from flask_socketio import SocketIO, emit
...
app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
app.config['DEBUG'] = True
socketio = SocketIO(app)
...
if __name__ == '__main__':
    socketio.run(app)


If I run the above application in the following manner instead:
gunicorn -b 127.0.0.1:5000 --timeout=1200 application:app 
It throws the following error:
Traceback (most recent call last):
  File "/home/server/projects/async_flask/async_flask/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/server/projects/async_flask/async_flask/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/server/projects/async_flask/async_flask/local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/server/projects/async_flask/async_flask/local/lib/python2.7/site-packages/flask_socketio/__init__.py", line 27, in __call__
    raise RuntimeError('You need to use a gevent-socketio server.')
RuntimeError: You need to use a gevent-socketio server.




The second question I have is that I have an nginx sites-available file setup as follows to cover the two flask applications:
server {
    listen 80;

    access_log /home/server/projects/flasky/logs/nginx/access.log;
    error_log /home/server/projects/flasky/logs/nginx/error.log;

    location / {
        proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        if (!-f $request_filename) {
            proxy_pass http://127.0.0.1:8000;
            break;
        }
    }

    location /static {
        alias  /home/server/projects/flasky/app/static/;
        autoindex on;
    }
}

server {
    listen 80;
    server_name _;

    access_log /home/server/projects/async_flask/logs/nginx/access.log;
    error_log /home/server/projects/async_flask/logs/nginx/error.log;


    location / {
        include proxy_params;
        proxy_pass http://127.0.0.1:5000;
    }

    location /socket.io {
        include proxy_params;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass http://127.0.0.1:5000/socket.io;
}
}

I can see both applications under 127.0.0.1:8000 and 127.0.0.1:5000 on the local host.
From outside the machine though, I can only see the 127.0.0.1:8000 application.
Would appreciate any help with these two questions.

Thank you.

**Comment by miguelgrinberg** [comment]
@neela77777 The documentation explains all the supported options for deploying a Flask-SocketIO application. In particular, gunicorn is only supported when you use it alongside eventlet or gevent, not standalone like you are. See the docs for information and examples.

Also, this message:

    RuntimeError: You need to use a gevent-socketio server.

suggests you are using a very old version of Flask-SocketIO. Please upgrade.

Regarding the nginx config, you have two problems. First, you again haven't read the docs on how to deploy Socket.IO with nginx, and second, you seem to have the two applications listening on the same server port, with no specific hostname, so how does the client select which application it wants to send a request to?

**Comment by neela77777** [comment]
My apologies if I came across as not having read the documentation. It is more a case of not understanding the documentation after reading it a few times. But thank you.

**Comment by alfredzhou1902** [comment]
Hi, I suppose I could put my question here:
I want to use flask-socketio to handle one or two page in my website, other pages are normal flask project(using HTTP protocol). 

 I thought it will be weird, In a normal flask project to use `socketio.run(app)` to run my application.

Is there any good practice I can use as reference?
Please forgive my obsession. ; )

**Comment by miguelgrinberg** [comment]
@alfredzhou1902 I don't understand your question. If you don't want to use `socketio.run(app)`, then use `flask run`, which also works.

**Comment by alfredzhou1902** [comment]
@miguelgrinberg 
Nice,I got it.Thanks for your patient. :+1:

**Comment by nitin-sharma5** [comment]
I had the same question,
I want to use flask-socketio to handle only one page in my website, other pages are normal flask project(using HTTP protocol).
So, while starting the application, should I run socketio.run(app) or normal app.run(), because doing the later results in "RuntimeError('You need to use the gevent-websocket server"

**Comment by miguelgrinberg** [comment]
@nitin-sharma5 If you need Socket.IO in your server, then you need to use `socketio.run(app)`. That provides the Socket.IO server, and also includes the support to serve all your HTTP routes.

**Comment by nitin-sharma5** [comment]
@miguelgrinberg I just need socketIO in my server for 1 webpage out of the 6 webpages that my application renders. And using socketio.run(app) does not seem to support HTTP routes( maybe it is still trigeering the flask development server, as my other web pages are normal flask project).

also, regarding your app.py example, it gives a runtime error when i replace socketio.run(app) with a normal app.run() ? although the application works fine.
File "/local/openagent/NETCONF-GUI/netconf-gui-5300/venv/lib/python2.7/site-packages/engineio/async_gevent.py", line 34, in __call__
    raise RuntimeError('You need to use the gevent-websocket server. '
RuntimeError: You need to use the gevent-websocket server. See the Deployment section of the documentation for more information.

**Comment by miguelgrinberg** [comment]
It does not matter how many pages use HTTP vs. Socket.IO. If you want Socket.IO to work, you need to start the server via the Socket.IO extension. If none of the actively viewed pages connect over Socket.IO, then no Socket.IO resources will be used.

The HTTP routes should work. If they don't, then make sure the HTTP route functions are imported, because if they are not, they will not be registered with the application.

**Comment by cacods** [comment]
Hi Miguel, my question is similar to the @neela77777 post.

I'm new to Flask and followed the official Flask docs to make an authentication system.

Reading the posts of this thread I see that I can run a socketio app and have access to http requests. So I thought that was simple as return socketio instead of app, from `create_app`.

So I have the `__init__.py` with:

```
def create_app(test_config=None):
    # create and configure the app
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_mapping(
        SECRET_KEY='dev',
        DATABASE=os.path.join(app.instance_path, 'flaskr.sqlite'),
    )
    # ...

    socketio = SocketIO(app)

    return socketio
```
But I get an error:

`Error: Failed to find Flask application or factory in module 'flaskr'. Use 'FLASK_APP=flaskr:name' to specify one.`

What is the right way to return the `socketio` wrapper to have the app running for both SocketIO and normal http requests?

**Comment by miguelgrinberg** [comment]
@cacods The SocketIO object is not a Flask application and it is not intended to replace it. Have you read the documentation?

**Comment by cacods** [comment]
I'm reading the documentation but as I'm new to both Flask and sockets I'm a little confused.

I just read the [api reference](https://flask-socketio.readthedocs.io/en/latest/api.html) about initializing SocketIO with `init_app`. So I changed the `create_app` to:

```
def create_app(test_config=None):
    # create and configure the app
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_mapping(
        SECRET_KEY='dev',
        DATABASE=os.path.join(app.instance_path, 'flaskr.sqlite'),
    )
    # ...

    socketio = SocketIO(app)
    socketio.init_app(app, debug=True)

    return app
```
If this is correct, how to access socketio inside another script? I want to handle socket operations from inside `chat.py`:
```
@socketio.on('my event')
def handle_my_custom_event(json, methods=['GET', 'POST']):
    print('received my event: ' + str(json))
    socketio.emit('my response', json, callback=messageReceived)
```

Sorry if I didn't reach the docs about this scenario. I'm reading a lot about sockets with flask but didn't find anything related to my problem yet.

**Comment by miguelgrinberg** [comment]
Try this:

```python
socketio = SocketIO()

def create_app(test_config=None):
    # create and configure the app
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_mapping(
        SECRET_KEY='dev',
        DATABASE=os.path.join(app.instance_path, 'flaskr.sqlite'),
    )
    # ...

    socketio.init_app(app, debug=True)

    return app
```

Now you have a global `socketio` object that you can import and use anywhere you need it.

**Comment by cacods** [comment]
That was nice, and clean. It works like a charm. Thank you very much Miguel.

**Comment by cacods** [comment]
Now I'm trying to adapt testing socket messages from your [blog](https://blog.miguelgrinberg.com/post/unit-testing-applications-that-use-flask-login-and-flask-socketio). to work with my Flask app configured to use a message queue.

I'm passing `message_queue` argument with the URI for the broker. So the difference from [you suggestion](https://github.com/miguelgrinberg/Flask-SocketIO/issues/362#issuecomment-879910494) is adding that to `init_app`.

```
socketio = SocketIO()

def create_app(test_config=None):
    # create and configure the app
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_mapping(
        SECRET_KEY='dev',
        DATABASE=os.path.join(app.instance_path, 'flaskr.sqlite'),
    )
    # ...

    socketio.init_app(app, message_queue=app.config['CELERY_BROKER_URL'])

    return app
```
I created `tests/test_socketio.py` with the initial code from your blog, to test if all goes right:

from flaskr import socketio

```
def test_socketio(app):
    flask_test_client = app.test_client()

    socketio_test_client = socketio.test_client(
        app, flask_test_client=flask_test_client)
```
When I run the pytest tests I get the error:

`RuntimeError: Test client cannot be used with a message queue. Disable the queue on your test configuration.`

The `conftest.py` is as in official Flask tutorial:
```
# ...
pytest.fixture
def app():
    db_fd, db_path = tempfile.mkstemp()

    app = create_app({
        'TESTING': True,
        'DATABASE': db_path,
    })

    with app.app_context():
        init_db()
        get_db().executescript(_data_sql)

    yield app

    os.close(db_fd)
    os.unlink(db_path)


@pytest.fixture
def client(app):
    return app.test_client()
#...
```
I don't devise in what place I can change the `socketio.init_app` call to call without `message_queue` attribute.

**Comment by miguelgrinberg** [comment]
```python
if app.config['TESTING']:
    socketio.init_app(app)
else
    socketio.init_app(app, message_queue=app.config['CELERY_BROKER_URL'])
```

**Comment by cacods** [comment]
Sorry for the delay. I tried that but, for some reason, when running the socketio test it runs `__init__` once and sets up first `app.config['TESTING']` to `False`, and run the `__init__` again with `app.config['TESTING'] == True`. So the same error occurs.

But anyway, thanks again @miguelgrinberg.
