### ISSUE TITLE
socket.request.headers.cookie

### ISSUE THREAD

**Issue by charyorde** [miguelgrinberg/Flask-SocketIO#363]
`http://socket.io/docs/server-api/#namespace#use(fn:function):namespace`.

Can we squeeze headers somewhere [here](https://github.com/miguelgrinberg/Flask-SocketIO/blob/master/flask_socketio/__init__.py#L567)

**Comment by miguelgrinberg** [comment]
I don't understand what you are saying. What headers?

**Comment by charyorde** [comment]
Access to the socket request headers. NodeJS socketio server already implemented such. Wondering whether you plan to add the same here?

**Comment by miguelgrinberg** [comment]
Your socket event handler functions run inside a request context, `request.headers` is how you access the headers from the socket request, Flask does this for you.
