### ISSUE TITLE
Is there a way to broadcast to all clients except sender?

### ISSUE THREAD

**Issue by AzRu** [miguelgrinberg/Flask-SocketIO#365]
From the [socket.io reference](http://socket.io/docs/#broadcasting-messages), their broadcast functionality does just this. Is there an easy way to do this in Flask-SocketIO?

**Comment by AzRu** [comment]
Found it! I think. 

```
include_self – True to include the sender when broadcasting or addressing a room, or False to send to everyone but the sender.
```

**Comment by miguelgrinberg** [comment]
Yes, that's the way.

**Comment by AzRu** [comment]
Thanks Miguel!

**Comment by AzRu** [comment]
I ran into an issue using include_self within a regular route. I'm trying to do 
```
socketio.emit('project', data, include_self=False)
```
But run into this error
```
AttributeError: 'Request' object has no attribute 'sid'
```
If I try to emit it without the include_self parameter, it works.

**Comment by miguelgrinberg** [comment]
I assume by "regular" you mean an HTTP route. In that case, there is no concept of "self". There is no link between a client sending HTTP requests and the same client connected to Socket.IO.

Who is "self" is stored in `request.sid`, which only exists during the handling of Socket.IO events. If you want the `include_self` option to work outside of a Socket.IO event handler, you can probably fool the system into doing what you want if you add `request.sid = "<the sid of the client you want to ignore>"`. But it would be up to your application to figure out what `sid` to use. You can, for example, get the sid from the `io` cookie which Socket.IO normally sets during the connection process.

**Comment by AzRu** [comment]
That makes sense. Perhaps the docs need to be updated to make it clear that include_self is not meant to be used outside of the SocketIO event context. The descriptions for for send and emit state that they can be used outside of it which is why I was expecting include_self to also work. 

Thanks again!

**Comment by miguelgrinberg** [comment]
Fair point. I will update the docs to make this clear.

**Comment by skortchmark9** [comment]
> You can, for example, get the sid from the io cookie which Socket.IO normally sets during the connection process.

I can't seem to get this anywhere. I'm printing ```request.cookies``` and all I see is my session
