### ISSUE TITLE
Socket server cannot catch emitted message from client

### ISSUE THREAD

**Issue by renodesper** [miguelgrinberg/Flask-SocketIO#367]
I have this flask-angular2 project which use socketio to send message every 5 second from the server after the client send some coordinate to the server. But when the client emit the message, the server can't catch that message. I use custom namespace, but it also happens when I use default namespace (/).

This is how I open the connection to the default namespace:
![20161127004647](https://cloud.githubusercontent.com/assets/807413/20642214/8cfa7c9c-b43b-11e6-862e-405d32e3bbd1.png)

This is the function to send the message:
![20161127004411](https://cloud.githubusercontent.com/assets/807413/20642220/bef10b3a-b43b-11e6-8644-57ac343627df.png)

My function simply emit the message to the server. I also try to print the message with console.log and it appears successfully:
![20161127004434](https://cloud.githubusercontent.com/assets/807413/20642228/ec7b93fe-b43b-11e6-89ee-2869fbe5af20.png)

Now, in the server I have this handler to catch that message:
![20161127004330](https://cloud.githubusercontent.com/assets/807413/20642234/066f4b70-b43c-11e6-9426-dc7b146fabe7.png)

But the log doesn't print the message nor the string even though flask-socketio received the message:
![20161127004233](https://cloud.githubusercontent.com/assets/807413/20642239/2395ad84-b43c-11e6-9f64-583c7fe20d62.png)

These are all the packages that I use:
```
backports.shutil-get-terminal-size==1.0.0
click==6.6
decorator==4.0.10
enum34==1.1.6
eventlet==0.19.0
fake-factory==0.7.2
Flask==0.11.1
Flask-Cors==3.0.2
Flask-JWT==0.3.2
Flask-SocketIO==2.7.1
Flask-SQLAlchemy==2.1
Flask-WTF==0.13.1
gevent==1.1.2
greenlet==0.4.10
gunicorn==19.6.0
ipaddress==1.0.17
ipython==5.1.0
ipython-genutils==0.1.0
itsdangerous==0.24
Jinja2==2.8
MarkupSafe==0.23
marshmallow==2.10.3
MySQL-python==1.2.5
pathlib2==2.1.0
pexpect==4.2.1
pickleshare==0.7.4
prompt-toolkit==1.0.8
psutil==4.4.2
ptyprocess==0.5.1
Pygments==2.1.3
PyJWT==1.4.2
python-dateutil==2.6.0
python-engineio==1.0.3
python-socketio==1.6.0
requests==2.11.1
simplegeneric==0.8.1
six==1.10.0
SQLAlchemy==1.1.2
sqlalchemy-datatables==0.4.0
traitlets==4.3.1
wcwidth==0.1.7
Werkzeug==0.11.11
wheel==0.24.0
WTForms==2.1
```

I also can't catch the "client_connected" message or any other message.
Can you tell me where I'm doing wrong?
I really appreciate your response, thank you very much.

**Comment by miguelgrinberg** [comment]
How is your server side project structure? Are you sure the module that has your `bounding_box` event handler is imported when the application starts?

**Comment by renodesper** [comment]
This is my project structure:
![20161127012609](https://cloud.githubusercontent.com/assets/807413/20642416/f12aadf4-b440-11e6-8529-265a54cfaefe.png)

events.py is the only file which has socketio decorator and I already import that file in create_app function. These are some code in my events.py file:
![20161127012817](https://cloud.githubusercontent.com/assets/807413/20642435/331f4bd4-b441-11e6-9635-fa9d5a43035e.png)

on_bounding_box function also located in events.py.

**Comment by miguelgrinberg** [comment]
With the information you provided I can't really see what the problem is. Sorry.

Can you make a complete example that I can try here that demonstrates the problem? There is obviously something wrong, but it is probably a small detail.

**Comment by renodesper** [comment]
Hi @miguelgrinberg, [this](https://drive.google.com/open?id=0B4mPgfAVYRN9enFCSGJ6Qkl4aDg) is a minimal example for you to test.

**Comment by miguelgrinberg** [comment]
This ended up being a bug on my side. It was caused by having Socket.IO options passed in the constructor, and later calling init_app with more options.

**Comment by miguelgrinberg** [comment]
@renodesper give version 2.8.1 a try please.

**Comment by renodesper** [comment]
Awesome, it works as expected now.
Thank you very much for your fast response @miguelgrinberg

**Comment by renodesper** [comment]
@miguelgrinberg server works in catching message in version 2.8.1, but now when I try to send message to client, the client cannot catch that message. I test it with emit in loop. I attach the [code](https://drive.google.com/open?id=0B4mPgfAVYRN9ZVI4eV9HaTE4Szg), it also has the client  in client folder.
