### ISSUE TITLE
problem with port 80 behind proxy

### ISSUE THREAD

**Issue by sldvhshlhkd** [miguelgrinberg/Flask-SocketIO#368]
hi
I am using socket.io & flask for chat server and when place my code behind of proxy (Nginx) and use port 80 for server I get this error:
Firefox can't establish a connection to the server at ws://mydomain.com/socket.io/?EIO=3&transport=websocket.
The connection to ws://mydomain.com/socket.io/?EIO=3&transport=websocket was interrupted while the page was loading.

and when type this url in browser I get this error:

http://mydomain.com/socket.io/?EIO=3&transport=websocket

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/eventlet/wsgi.py", line 489, in handle_one_response
    'Content-Length' not in [h for h, _v in headers_set[1]]:
IndexError: list index out of range

but when using another port socket.io work without problem.

**Comment by miguelgrinberg** [comment]
Why are you entering an internal Socket.IO URL in the browser's address bar? Not sure what that will do, I recommend that you test using the Socket.IO JavaScript client. See the example in this repository.

**Comment by sldvhshlhkd** [comment]
Thank you.
I get this error on flask server, too.
I use JavaScript client in my project:
`
       io({transports: ['websocket',]});
       var socket = io.connect('http://mydomain.com:80/admin_socket');
       socket.on('new_chat', function(data) {
            .....
       });
`

and this config for NginX:
`
server {
   listen 80;
   server_name MyDomainAddress;
   access_log /var/log/nginx/example.log;

    location / {
       proxy_pass http://127.0.0.1:8080;
       proxy_redirect off;

       proxy_set_header Host $host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
   }

   location /socket.io {
       proxy_pass http://127.0.0.1:8080/socket.io;
       proxy_redirect off;
       proxy_buffering off;

       proxy_set_header Host $host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

       proxy_http_version 1.1;
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection "Upgrade";
   }
}
`

**Comment by miguelgrinberg** [comment]
Do you get the same error with other browsers besides Firefox?

**Comment by sldvhshlhkd** [comment]
yes, I get same error:
FireFox:
"NetworkError: 500 Internal Server Error - http://mydomain/socket.io/?EIO=3&transport=websocket"
Firefox can't establish a connection to the server at ws://mydomain/socket.io/?EIO=3&transport=websocket.

Chrome:
socket.io.min.js:1 WebSocket connection to 'ws://mydomain/socket.io/?EIO=3&transport=websocket' failed: Error during WebSocket handshake: Unexpected response code: 500

**Comment by miguelgrinberg** [comment]
Two questions:

1. What version of the Socket.IO client are you using?
2. Do you see the 500 error on the server side logs? Do you have a stack trace for it?

**Comment by sldvhshlhkd** [comment]
1. latest version of Socket.IO, 1.4.5
2. yes, I see. I have not a stack trace now :(

**Comment by miguelgrinberg** [comment]
Well, you need to get that stack trace. Run your app in debug mode, that should write a stack trace to the console or log.

**Comment by sldvhshlhkd** [comment]
Thank you. My server is not accessible now. As soon as possible I will get that stack trace.

**Comment by sldvhshlhkd** [comment]
App's stack trace:

45.44.61.23,127.0.0.1 - - [29/Nov/2016 15:02:22] "GET /socket.io/?EIO=3&transport=websocket HTTP/1.1" 500 372 0.003070
(15513) accepted ('127.0.0.1', 56400)
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/eventlet/wsgi.py", line 489, in handle_one_response
    'Content-Length' not in [h for h, _v in headers_set[1]]:
IndexError: list index out of range

**Comment by miguelgrinberg** [comment]
@sldvhshlhkd is there any reason why your client is connecting directly via websocket? Normally the connection starts with HTTP, and is upgraded to websocket as a second step.

The error appears to be a bug in eventlet, it has been reported, but it does not look like there was any activity on it: https://github.com/eventlet/eventlet/issues/288.

**Comment by sldvhshlhkd** [comment]
> Normally the connection starts with HTTP, and is upgraded to websocket as a second step.

Browsers create websocket automatically. How can I do this manually?

**Comment by miguelgrinberg** [comment]
> Browsers create websocket automatically

No, they don't. You have a client application that connects to the Socket.IO server, right? Are you asking for a direct websocket connection, maybe? Try making a connection in the default way, maybe that'll help. I don't think you are doing anything wrong requesting a websocket connection from the start, but I think there is a possibility that that is triggering the bug in eventlet.

**Comment by sldvhshlhkd** [comment]
> Try making a connection in the default way.
How can I make a connection in the default way?
what do I change in code?

> main.py
app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app)

@socketio.on('connect', namespace='/test_socket')
def test_connect():
    print('Connected')
    emit('my response', {'data': 'Connected'})

if __name__ == '__main__':
    socketio.run(app, host='0.0.0.0', port=8080, debug=True)

> layout.html
<html>
<head>
	<script src="https://cdn.socket.io/socket.io-1.4.5.js"></script>
</head>
	<body>
	...
	<script>
	$(document).ready(function(){
		io({transports: ['websocket',]});
		var socket = io.connect('http://mydomain.com:80/test_socket');
		socket.on('my response', function(data) {
			.....
		});
	}
	</script>
	</body>
</html>

**Comment by miguelgrinberg** [comment]
Remove the `transports: ['websocket']` option from your connection call.

**Comment by sldvhshlhkd** [comment]
By removing this line, It works but it goes to polling mode. I need websocket because my flask server become very slow in polling mode.
My code works on any ports except port 80.

**Comment by miguelgrinberg** [comment]
@sldvhshlhkd That is incorrect. Without the line I ask you to remove, Socket.IO behaves in the normal way, which is to start the connection in long-polling, then upgrade it to websocket for the clients that support it.
