### ISSUE TITLE
how to use global variables?

### ISSUE THREAD

**Issue by MUYOUHUIYAO** [miguelgrinberg/Flask-SocketIO#372]
I am a newer to flask and flask-socketIO, when I am using flask-socketIO to save global variables with flask.g, it seems I cannot get the variable out of the request. Then I look up the document and found that I should push the application context. But it seems still didn't work. I an puzzled about that and don't know what is wrong? Here is how I push the application context.
```
ctx=app.app_context()
ctx.push()
g._var=var
ctx.pop()
```

**Comment by miguelgrinberg** [comment]
The variables you store in `app.g` are not global variables, they are tied to the app context. Each new app context that you push has its own `g`. If you need global variables that live beyond a single request, then use a proper Python global variable.

**Comment by MUYOUHUIYAO** [comment]
yes, use python global variable really work. But I chose to use flask.g based on the document of flask 0.11, so it means the the flask-socketIO has something different from the newest flask?

**Comment by miguelgrinberg** [comment]
No, this has nothing to do with Flask-SocketIO. The `g` variable does not extend past the life of a request. Each request starts with an empty `g`. I think you are not interpreting the Flask documentation on g correctly.

**Comment by MUYOUHUIYAO** [comment]
When I was looking for the information about the flask.g, I did see the issue that g was a request variable, but I did see the document in flask 0.11 and it said that g is an application context through flask 0.10 and I also found an example in flask 0.11 in which a global variable is stored in g. Here is the example:
```
import sqlite3
from flask import g

def get_db():
    db = getattr(g, '_database', None)
    if db is None:
        db = g._database = connect_to_database()
    return db

@app.teardown_appcontext
def teardown_db(exception):
    db = getattr(g, '_database', None)
    if db is not None:
        db.close()
``` 
```
from werkzeug.local import LocalProxy
db = LocalProxy(get_db)
```
  I suddenly find I did't save the global variable like this way which call the LocalProxy to save the db, so this is my error in using g?

**Comment by miguelgrinberg** [comment]
flask.g can be used to share variables between all the functions that are invoked as part of a single request. Any variables you set in a before_request handler, for example, will be available in your route function and in the after_request and teardown_appcontext handlers. But they cannot be accessed across requests. It works the same way for Flask-SocketIO.

**Comment by MUYOUHUIYAO** [comment]
I remember I had seen some one said that a request is a child of the LocalProxy, so if the way flask use is to push the localproxy in the current request so the db variable can be reached in any request?

**Comment by miguelgrinberg** [comment]
If you are not sure how the app context and g work, I recommend that you create a small application and test it.

I don't understand your last comment, if you have a reference to this thing you heard I'm happy to take a look and comment on it. I'll leave you a couple of quotes from the official documentation at http://flask.pocoo.org/docs/0.11/appcontext/#purpose-of-the-application-context:

> The application context is created and destroyed as necessary. It never moves between threads and it will not be shared between requests. As such it is the perfect place to store database connection information and other things.

and http://flask.pocoo.org/docs/0.11/appcontext/#context-usage:

> The context is typically used to cache resources that need to be created on a per-request or usage case. For instance, database connections are destined to go there.

**Comment by MUYOUHUIYAO** [comment]
Ok, I will test g after later, thank you for your help

**Comment by bill8260** [comment]
These links don't seem to work any longer:

http://flask.pocoo.org/docs/0.11/appcontext/#context-usage:
I get - Chapter 404: The Lost Page

**Comment by miguelgrinberg** [comment]
The 0.11 version of Flask is very old. Change 0.11 with 0.12 or 1.0 for the same documentation on more recent releases.
