### ISSUE TITLE
OSError: raw readinto() returned invalid length -1

### ISSUE THREAD

**Issue by peterel** [miguelgrinberg/Flask-SocketIO#374]
Hello,
Firstly, thanks for a great project/product/lib! Used an older version for another app which was great but Im having some issues now as Ive updated all packages. I believe all is up to date now but I keep getting following error: 

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/eventlet/greenpool.py", line 82, in _spawn_n_impl
    func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/eventlet/wsgi.py", line 719, in process_request
    proto.__init__(sock, address, self)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/server.py", line 424, in handle
    self.handle_one_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/eventlet/wsgi.py", line 330, in handle_one_request
    self.raw_requestline = self.rfile.readline(self.server.url_length_limit)
OSError: raw readinto() returned invalid length -1 (should have been between 0 and 8192)
```

Seems there is something in eventlet that causes this but Im not sure. I assume its related to https://github.com/miguelgrinberg/Flask-SocketIO/issues/355 but this is happening to me on Chrome rather than IE.

Any tips or ideas would be welcome.

Best,

Peter

**Comment by miguelgrinberg** [comment]
Does your app work if you don't use eventlet? This error typically means that the server is expecting an HTTP request, but the sender is sending something else. I've seen it for example when a plain WebSocket client (not a Socket.IO client) connects to the Socket.IO server.

**Comment by peterel** [comment]
Thanks @miguelgrinberg! This was indeed the case. Uninstalling eventlet did the trick. But, now when I start my app I get.
`
WebSocket transport not available. Install eventlet or gevent and gevent-websocket for improved performance.`

So, my app now uses Socket IO but not websockets?

Thanks.

Best,

Peter

**Comment by miguelgrinberg** [comment]
Well, my suggestion was not to drop eventlet altogether, just to confirm a baseline Socket.IO server works.

As the warning you are getting says, your options to get WebSocket working within Socket.IO are either eventlet, or gevent combined with gevent-websocket. This last combination unfortunately only works on Python 2, gevent-websocket has not been ported to 3 yet. If you don't use either of these, then your server will work just fine, but it will not use the WebSocket transport.

So I think your next step is to try the gevent option to see if that works any better. It is odd that eventlet does not work for you with Chrome, as that is my main testing platform and that has been very reliable for me. I think another thing you can try is to use my example application from this repository and see if that works well under eventlet/chrome. If that works, then I guess you'll need to figure out how your application is different.

**Comment by peterel** [comment]
Thanks for the help and tips! If I do neither of the options but keep SocketIO, am I correct in assuming that this would then be the equivalents of long polling?

Hmm, could it have anything to do with the version of eventlet? I assume Im installning the latest, 0.19.0. Which are you using?

**Comment by miguelgrinberg** [comment]
It would not be the "equivalent" of long polling. It would be exactly that. So it is not a great solution.

I have been using eventlet through all their recent releases. I've tested a lot on the 0.17.4 release, but have used 0.19.0 as well. Try my example application from this repo to see if you get better results. That would indicate something in your application is different.

**Comment by peterel** [comment]
Alright, Ill try out the sample app.

Peter

**Comment by peterel** [comment]
Same error with the sample app:

`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/eventlet/greenpool.py", line 82, in _spawn_n_impl
    func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/eventlet/wsgi.py", line 719, in process_request
    proto.__init__(sock, address, self)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/server.py", line 424, in handle
    self.handle_one_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/eventlet/wsgi.py", line 330, in handle_one_request
    self.raw_requestline = self.rfile.readline(self.server.url_length_limit)
OSError: raw readinto() returned invalid length -1 (should have been between 0 and 8192)`

Thanks for your help with this @miguelgrinberg. There must be some issue with my setup I guess which is tricky for you to help debug of course. I dig around a bit more to see if there is anything I can come up with. Feel free to close this question.

**Comment by miguelgrinberg** [comment]
Are you running client and server on the same machine, or different ones? Maybe some sort of issue related to firewall?

You may want to try gevent + gevent-websocket instead of eventlet to see how the outcome changes.

**Comment by peterel** [comment]
Both running locally on the same machine.

Im using python 3.5.2. Isnt gevent + gevent-websockets only for python 2.7?

**Comment by peterel** [comment]
For future potential issues. This was solved by connecting with:

`var socket = io.connect(url, { transports: ["websocket"] });`

instead of

var socket = io.connect(url);

No idea why though. @miguelgrinberg Maybe you make some sense of this?

**Comment by miguelgrinberg** [comment]
With this change you are bypassing the initial long polling connection and going straight to WebSocket. This will only work for clients that support WebSocket, which these days is not a concern anymore since most browsers do support it.

**Comment by peterel** [comment]
Alright, thanks for the info and your help @miguelgrinberg . Closing this issue now.
