### ISSUE TITLE
Emit from Pika consumer callback

### ISSUE THREAD

**Issue by aminalaee** [miguelgrinberg/Flask-SocketIO#375]
I'm trying to use SocketIO with Pika, I've tried both blocking and non-blocking consumers and also tried green threads but I can't emit messages from the Pika callback.
This is my example of the blocking connection:

```
def on_message(channel, method_frame, header_frame, body):
    print(body)
    socketio.emit('notification', 'testing')
    channel.basic_ack(delivery_tag=method_frame.delivery_tag)

def pika_client():
    connection = pika.BlockingConnection()
    channel = connection.channel()
    channel.basic_consume(on_message, 'queue')
    channel.start_consuming()

@socketio.on('connect')
def on_connect():
    from eventlet.green import threading
    thread = threading.Thread(target=pika_client)
    thread.start()
   # this too didn't work
   #socketio.start_background_task(target=pika_client)

```

I've also tried using non-blocking consumer from pika but that doesn't help. In my on_message I can print the messages but can't emit them to the browser. And sometimes loading the page sends it into an infinite loop.

P.S.: using the example from the repo and calling start_background_task with a while True works, but I need to emit on pika callbacks.

Thanks

**Comment by miguelgrinberg** [comment]
Turn on logging on the server and the client, so that we can figure out where is the message being dropped.

**Comment by zhengqz** [comment]
i use start_background_task to start a kafka comsumer background
when i leave room(kafka topic), how can i stop the background task

**Comment by m8man** [comment]
Miguel what do you mean with monkey patching the std library?
I have an issue that when channel.start_consuming() is running in a background thread I cant make a new connection to the website (or send any other data with flask socketio) until channel.start_consuming() is getting a message in the queue (and the callback function is called. When the callback function is called, it seems that all the socketio requests I made all happens at once.) 

As an side note, If it takes time before a message is comming to the queue, then I get a [CRITICAL] WORKER TIMEOUT after little more than 30 seconds.

I guess the issue would be solved if I understood your comment above. I already have this in app.py:
```
import eventlet
eventlet.monkey_patch()
```

are you talking about something else?
