### ISSUE TITLE
About the gevent-websocket package on Python3

### ISSUE THREAD

**Issue by wwqgtxx** [miguelgrinberg/Flask-SocketIO#380]
In your document,you said that 
> The gevent-websocket package adds WebSocket support to gevent, but unfortunately this package is current only available for Python 2. 

I do a search in PyPi,then I found a fork library [karellen-geventws](https://pypi.python.org/pypi/karellen-geventws) which can support Python 3.

So I want to know that can Flask-SocketIO work well with karellen-geventws in Python3 and if it works will,would you add this library to the document to help more people use gevent and Flask-SocketIO in Python3 without uwsgi.

**Comment by miguelgrinberg** [comment]
I am not familiar with this fork, so I don't know if it will work or not. If they preserved all the APIs of the original project, then I think there is a good chance it will.

As far as recommending it in the documentation, I'm not sure. Projects on GitHub come and go all the time, and this project is just 7 days old, so I think it is way too soon to be thinking about it being a replacement for the gevent-websocket package.
