### ISSUE TITLE
Flask-SocketIO triggering unwarranted disconnect event? 

### ISSUE THREAD

**Issue by AzRu** [miguelgrinberg/Flask-SocketIO#382]
Maybe the title is a bit off, I'm trying to understand what's happening. 

Context: 
- I have an auth handler in my app adds a 'current_user' to the RequestContext based on their token (current_user['sub'] is their ID), done for both socket events and REST routes
- My socket event handler does a join_room with current_user['sub'] (to emit notifications, etc just to them)
- I also have a socket disconnect event handler, that does a leave_room with current_user['sub'] (the client app sends this event in some cases)
- I have a REST route, POST /project, that adds a project to the DB, then emits an event that the project was added so the client's page can be updated in real time.
- This route worked fine up until about a week ago. It's now failing. 

Here's the stack trace from the logs. To me, it looks like the emit event triggered a disconnect from python-socketio, and my app tried to remove the current_user, but it wasn't set as no token was sent over. Maybe my disconnect handler is now overriding some other disconnect handler. I can rename the event if so, and I should probably try that (it's just occurring to me now that this might be why).

```
Dec 08 10:43:23 beta gunicorn[5752]: [2016-12-08 10:43:23,429] ERROR in app: Exception on /project [POST]
Dec 08 10:43:23 beta gunicorn[5752]: Traceback (most recent call last):
Dec 08 10:43:23 beta gunicorn[5752]: File "/root/auth0/env/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
Dec 08 10:43:23 beta gunicorn[5752]: response = self.full_dispatch_request()
Dec 08 10:43:23 beta gunicorn[5752]: File "/root/auth0/env/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
Dec 08 10:43:23 beta gunicorn[5752]: rv = self.handle_user_exception(e)
Dec 08 10:43:23 beta gunicorn[5752]: File "/root/auth0/env/local/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
Dec 08 10:43:23 beta gunicorn[5752]: return cors_after_request(app.make_response(f(*args, **kwargs)))
Dec 08 10:43:23 beta gunicorn[5752]: File "/root/auth0/env/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
Dec 08 10:43:23 beta gunicorn[5752]: reraise(exc_type, exc_value, tb)
Dec 08 10:43:23 beta gunicorn[5752]: File "/root/auth0/env/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
Dec 08 10:43:23 beta gunicorn[5752]: rv = self.dispatch_request()
Dec 08 10:43:23 beta gunicorn[5752]: File "/root/auth0/env/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
Dec 08 10:43:23 beta gunicorn[5752]: return self.view_functions[rule.endpoint](**req.view_args)
Dec 08 10:43:23 beta gunicorn[5752]: File "/root/auth0/env/local/lib/python2.7/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
Dec 08 10:43:23 beta gunicorn[5752]: resp = make_response(f(*args, **kwargs))
Dec 08 10:43:23 beta gunicorn[5752]: File "/root/auth0/app/__init__.py", line 197, in newfn
Dec 08 10:43:23 beta gunicorn[5752]: return fn(*args, **kwargs)
Dec 08 10:43:23 beta gunicorn[5752]: File "/root/auth0/app/mod_project/controllers.py", line 112, in get
Dec 08 10:43:23 beta gunicorn[5752]: 'event': 'singleProject'
Dec 08 10:43:23 beta gunicorn[5752]: File "/root/auth0/env/local/lib/python2.7/site-packages/flask_socketio/__init__.py", line 343, in emit
Dec 08 10:43:23 beta gunicorn[5752]: skip_sid=skip_sid, callback=callback, **kwargs)
Dec 08 10:43:23 beta gunicorn[5752]: File "/root/auth0/env/local/lib/python2.7/site-packages/socketio/server.py", line 217, in emit
Dec 08 10:43:23 beta gunicorn[5752]: **kwargs)
Dec 08 10:43:23 beta gunicorn[5752]: File "/root/auth0/env/local/lib/python2.7/site-packages/socketio/base_manager.py", line 127, in emit
Dec 08 10:43:23 beta gunicorn[5752]: self.server._emit_internal(sid, event, data, namespace, id)
Dec 08 10:43:23 beta gunicorn[5752]: File "/root/auth0/env/local/lib/python2.7/site-packages/socketio/server.py", line 395, in _emit_internal
Dec 08 10:43:23 beta gunicorn[5752]: binary=binary))
Dec 08 10:43:23 beta gunicorn[5752]: File "/root/auth0/env/local/lib/python2.7/site-packages/socketio/server.py", line 406, in _send_packet
Dec 08 10:43:23 beta gunicorn[5752]: self.eio.send(sid, encoded_packet, binary=False)
Dec 08 10:43:23 beta gunicorn[5752]: File "/root/auth0/env/local/lib/python2.7/site-packages/engineio/server.py", line 173, in send
Dec 08 10:43:23 beta gunicorn[5752]: socket.send(packet.Packet(packet.MESSAGE, data=data, binary=binary))
Dec 08 10:43:23 beta gunicorn[5752]: File "/root/auth0/env/local/lib/python2.7/site-packages/engineio/socket.py", line 63, in send
Dec 08 10:43:23 beta gunicorn[5752]: self.close(wait=False, abort=True)
Dec 08 10:43:23 beta gunicorn[5752]: File "/root/auth0/env/local/lib/python2.7/site-packages/engineio/socket.py", line 104, in close
Dec 08 10:43:23 beta gunicorn[5752]: self.server._trigger_event('disconnect', self.sid, async=False)
Dec 08 10:43:23 beta gunicorn[5752]: File "/root/auth0/env/local/lib/python2.7/site-packages/engineio/server.py", line 359, in _trigger_event
Dec 08 10:43:23 beta gunicorn[5752]: return self.handlers[event](*args)
Dec 08 10:43:23 beta gunicorn[5752]: File "/root/auth0/env/local/lib/python2.7/site-packages/socketio/server.py", line 522, in _handle_eio_disconnect
Dec 08 10:43:23 beta gunicorn[5752]: self._handle_disconnect(sid, '/')
Dec 08 10:43:23 beta gunicorn[5752]: File "/root/auth0/env/local/lib/python2.7/site-packages/socketio/server.py", line 434, in _handle_disconnect
Dec 08 10:43:23 beta gunicorn[5752]: self._trigger_event('disconnect', '/', sid)
Dec 08 10:43:23 beta gunicorn[5752]: File "/root/auth0/env/local/lib/python2.7/site-packages/socketio/server.py", line 480, in _trigger_event
Dec 08 10:43:23 beta gunicorn[5752]: return self.handlers[namespace][event](*args)
Dec 08 10:43:23 beta gunicorn[5752]: File "/root/auth0/env/local/lib/python2.7/site-packages/flask_socketio/__init__.py", line 221, in _handler
Dec 08 10:43:23 beta gunicorn[5752]: *args)
Dec 08 10:43:23 beta gunicorn[5752]: File "/root/auth0/env/local/lib/python2.7/site-packages/flask_socketio/__init__.py", line 588, in _handle_event
Dec 08 10:43:23 beta gunicorn[5752]: ret = handler(*args)
Dec 08 10:43:23 beta gunicorn[5752]: File "/root/auth0/app/mod_user/controllers.py", line 40, in disconnect
Dec 08 10:43:23 beta gunicorn[5752]: leave_room(str(current_user['sub']))
Dec 08 10:43:23 beta gunicorn[5752]: File "/root/auth0/env/local/lib/python2.7/site-packages/werkzeug/local.py", line 373, in <lambda>
Dec 08 10:43:23 beta gunicorn[5752]: __getitem__ = lambda x, i: x._get_current_object()[i]
Dec 08 10:43:23 beta gunicorn[5752]: File "/root/auth0/env/local/lib/python2.7/site-packages/werkzeug/local.py", line 302, in _get_current_object
Dec 08 10:43:23 beta gunicorn[5752]: return self.__local()
Dec 08 10:43:23 beta gunicorn[5752]: File "/root/auth0/app/__init__.py", line 69, in <lambda>
Dec 08 10:43:23 beta gunicorn[5752]: current_user = LocalProxy(lambda: _request_ctx_stack.top.current_user)
Dec 08 10:43:23 beta gunicorn[5752]: AttributeError: 'RequestContext' object has no attribute 'current_user'
```

**Comment by miguelgrinberg** [comment]
You do not explain how exactly you inject this `current_user` attribute into the request, but whatever method you use, it seems it isn't triggering on a disconnect event.

The actual problem is that while broadcasting a message to some (or all) your clients, one of them was detected as gone. So during your emit, the disconnect event from this now gone client is invoked.

The request object that is given to the application handlers is not the same every time, it is recreated for each call, so the `current_user` attribute is missing on the request object passed to this disconnect handler. But the user session is preserved across invocations, so I think you can fix your problem if you move `request.current_user` to `session['current_user']`.

**Comment by AzRu** [comment]
> You do not explain how exactly you inject this current_user attribute into the request, but whatever method you use, it seems it isn't triggering on a disconnect event.

I use JWT based auth, so a token is sent on each request by my client apps. I have a decorator that decodes the payload when a request comes in, and if it's a valid token it will add the user info to the _request_ctx_stack. My code assumes that a token will be sent.

So I guess the invoked disconnect doesn't send a token like my clients do.

I was able to get rid of the error by renaming the disconnect event though.. my disconnect event was essentially a 'leave_room' event. 

Another question: should I be explicitly doing a flask_socketio.disconnect ? From the docs, it appears that it sends a disconnect event on the client. I don't have a disconnect handler on the client side.

**Comment by miguelgrinberg** [comment]
> I have a decorator that decodes the payload when a request comes in

This is the misconception that you have, I think. Socket.IO doesn't work on top of regular requests, like the normal Flask routes. Depending on the method the client uses to connect, you can have events that do not have a corresponding HTTP request, so Flask-SocketIO makes one up for you, only so that the session data can be accessible in a Flask friendly way. I stand by my recommendation above to use `session` to store your user. Maybe you found a case where the request object works for you, but it isn't a reliable place to store data.

> So I guess the invoked disconnect doesn't send a token like my clients do.

Disconnects are not always requested by clients, sometimes they are determined by the server when a client silently stops communicating. Even if the client requests the disconnection, sometimes this isn't done with a request.

> should I be explicitly doing a flask_socketio.disconnect ?

Only if you want to kick out a client. Typically Socket.IO connections remain until the client leaves or disconnects explicitly.
