### ISSUE TITLE
SocketIO + Eventlet doesn't accept external requests

### ISSUE THREAD

**Issue by iiDatKat** [miguelgrinberg/Flask-SocketIO#386]
I'm running Flask + Socket.IO on the Eventlet library that I got via pip.
Here's my code:

    from flask import Flask, request, render_template
    from flask_socketio import SocketIO
    from flask_cors import CORS, cross_origin
    app = Flask(__name__)
    app.config['SECRET_KEY']='secret!'
    socketio = SocketIO(app)

    import eventlet
    eventlet.monkey_patch()

    @app.route("/")
    def index():
        return "<html><body><h1>Hellooooooooooo</h1></body></html>"

    if __name__ == '__main__':
        CORS(app)
        socketio.run(app, host='0.0.0.0', debug = False, use_reloader=False)

The last line of code (`socketio.run(app, host='0.0.0.0', debug = False, use_reloader=False)`), according to the socket.io documentation, should run the Eventlet server, and it does. I specify the host to be `0.0.0.0`, so theoretically it should accept requests from outside, e.g. from local IP (192.168.1.xxx) and from localhost. 

When I run it, it does say that it's running on 0.0.0.0:5000 (default port on Flask), but when I try to access it via web browser (`192.168.1.xxx:5000`) it gets stuck and doesn't load the webpage. Same result with `localhost:5000`. 

However, if I uninstall eventlet, it runs on the default Flask web server. I commented out the eventlet part of the code and ran it again. Sure enough, visiting `localhost:5000` works but `192.168.1.xxx:5000` doesn't work.

Is this an error with eventlet or socket.io?

**Comment by miguelgrinberg** [comment]
Have you checked if you have a firewall on your machine that might be rejecting outside connections? I think that could explain the access from other machines.

For the local access problem with eventlet, try 127.0.0.1 instead of localhost and let me know if that works.

**Comment by iiDatKat** [comment]
@miguelgrinberg Issue resolved. My IP changed unexpectedly, so accessing the server via the old IP didn't work.
