### ISSUE TITLE
Support websocket via the ws4py project

### ISSUE THREAD

**Issue by miguelgrinberg** [miguelgrinberg/Flask-SocketIO#387]
This would be a nice alternative to gevent-websocket, which does not run on Python 3.

https://pypi.python.org/pypi/ws4py

**Comment by PawelTroka** [comment]
@miguelgrinberg Any updates on this? Is it a lot of work? It just so happens that we desperately need it in the project :)

**Comment by miguelgrinberg** [comment]
gevent-websocket has been ported to Python 3, so I'm not currently planning on adding yet another websocket package.

**Comment by PawelTroka** [comment]
Would you accept PR on the matter then?

**Comment by miguelgrinberg** [comment]
I would consider it, assuming the changes do not affect the support that I have in place for the eventlet, gevent and uwsgi websocket providers.

**Comment by miguelgrinberg** [comment]
Not planning to do this, so I'm closing.

**Comment by ecamaj** [comment]
This would be beautiful to be done, since nowdays very popular CherryPy python server only supports sockets through ws4py.
I managed to use python-socketio with "threading" but it is only using polling, unfortunately.
Any ideas? Thanks <3
