### ISSUE TITLE
Improve documentation for flask-socketio + click

### ISSUE THREAD

**Issue by imaia** [miguelgrinberg/Flask-SocketIO#390]
In docs https://flask-socketio.readthedocs.io/en/latest/ it is written that you only needs to set FLASK_APP environment variable to have socketio working with flask. Also, shouldn't there be a line break before `flask run`?

**Comment by miguelgrinberg** [comment]
> it is written that you only needs to set FLASK_APP environment variable to have socketio working with flask

What else do you think should be included in this section?

> Also, shouldn't there be a line break before flask run?

No. That is just an example using bash, and it is correct as it is. For a complete reference on how to set FLASK_APP, you can consult the official Flask documentation: http://flask.pocoo.org/docs/0.12/quickstart/#a-minimal-application.

**Comment by italomaia** [comment]
Well, it was not crystal to me how the code should be for running with "flask run".
Docs state socket.io provides a new "flask run" version. Does that mean my code should look like this?

```
from flask import Flask, render_template
from flask_socketio import SocketIO

app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app)
```

or like this:

```
from flask import Flask, render_template

app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
```

If my extension is initialized somewhere else, and the code should look like the first example, should I use my project instance or create a new one (or doesn't matter)?

**Comment by miguelgrinberg** [comment]
> Docs state socket.io provides a new "flask run" version

What that means is that when you use Flask-SocketIO, the `flask run` command is enhanced to work appropriately for Socket.IO. But this is done transparently, it does not change the way you start the project, which is always `flask run`.

> If my extension is initialized somewhere else, and the code should look like the first example, should I use my project instance or create a new one (or doesn't matter)?

This is a question that applies to Flask, more than Flask-SocketIO, and can be asked of any extension.

Regardless of where your extension is initialized, you have to use the same application instance. You can't use a different one.

**Comment by imaia** [comment]
`This is a question that applies to Flask, more than Flask-SocketIO, and can be asked of any extension.`

Ok, made sense. flask run will use the io extension that is available in my Flask instance.
