### ISSUE TITLE
app not handling public requests

### ISSUE THREAD

**Issue by funb0x** [miguelgrinberg/Flask-SocketIO#395]
Hi Miguel,

I running a simple application:

from flask import Flask, render_template, Response
from flask_socketio import SocketIO
import picamera
import io
import time

app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app, async_mode='threading')

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/video_feed')
def video_feed():
    time.sleep(2)
    return Response(gen(), mimetype='multipart/x-mixed-replace; boundary=frame')

def gen():
    camera = picamera.PiCamera(resolution = (640, 480))
    camera.framerate = 30
    stream = io.BytesIO()
    while True:
        camera.capture(stream, format = 'jpeg', use_video_port = True, splitter_port = 1)
        #camera.capture(stream, format = 'jpeg')
        stream.truncate()
        stream.seek(0)
        frame = stream.read()    
        stream.seek(0)
        stream.truncate()
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')

@socketio.on('connect', namespace='/ws')
def connect():
    print('_' * 10, 'new connection: ')

@socketio.on('disconnect', namespace='/ws')
def disconnect():
    print('Client disconnected')

@socketio.on_error('/ws') 
def error_handler_chat(e):
    print('_' * 10, 'Error', e)

@socketio.on('move', namespace='/ws')
def handle_message(message):
    print('_' * 10, 'received message: ', message)

if __name__ == '__main__':
    socketio.run(app, debug = True)
`

And I am only able to see the homepage only from raspberry pi browser.
Could you please help me to find out the reason why app is not reachable from public ip addresses?

**Comment by miguelgrinberg** [comment]
Have you tried setting your host to `0.0.0.0` in `socketio.run()`?
