### ISSUE TITLE
Sockets getting stuck in CLOSED state

### ISSUE THREAD

**Issue by audrummer15** [miguelgrinberg/Flask-SocketIO#396]
I'm having issues with file descriptors hanging around in a closed state as shown below

```
Python  19189 Adam.Brown    5u    IPv4 0xade16c4796252cff       0t0      TCP *:commplex-main (LISTEN)
Python  19189 Adam.Brown    7u    IPv4 0xade16c479d7517e7       0t0      TCP localhost:commplex-main->localhost:65135 (ESTABLISHED)
Python  19189 Adam.Brown    8u    IPv4 0xade16c47970c07e7       0t0      TCP localhost:commplex-main->localhost:63315 (CLOSED)
Python  19189 Adam.Brown    9u    IPv4 0xade16c479d750eef       0t0      TCP localhost:commplex-main->localhost:65136 (ESTABLISHED)
Python  19189 Adam.Brown   10u    IPv4 0xade16c479d74fcff       0t0      TCP localhost:commplex-main->localhost:65137 (ESTABLISHED)
Python  19189 Adam.Brown   13u    IPv4 0xade16c479613eb0f       0t0      TCP localhost:commplex-main->localhost:63323 (CLOSED)
Python  19189 Adam.Brown   16u    IPv4 0xade16c47972847e7       0t0      TCP localhost:commplex-main->localhost:65151 (ESTABLISHED)
Python  19189 Adam.Brown   17u    IPv4 0xade16c47968ec407       0t0      TCP localhost:commplex-main->localhost:65154 (ESTABLISHED)
Python  19189 Adam.Brown   18u    IPv4 0xade16c4796252407       0t0      TCP localhost:commplex-main->localhost:65155 (ESTABLISHED)
Python  19189 Adam.Brown   19u    IPv4 0xade16c47976c25f7       0t0      TCP localhost:commplex-main->localhost:63335 (CLOSED)
Python  19189 Adam.Brown   22u    IPv4 0xade16c4797943cff       0t0      TCP localhost:commplex-main->localhost:63341 (CLOSED)
Python  19189 Adam.Brown   27u    IPv4 0xade16c479620a5f7       0t0      TCP localhost:commplex-main->localhost:63400 (CLOSED)
Python  19189 Adam.Brown   28u    IPv4 0xade16c47962535f7       0t0      TCP localhost:commplex-main->localhost:63402 (CLOSED)
Python  19189 Adam.Brown   29u    IPv4 0xade16c479620b7e7       0t0      TCP localhost:commplex-main->localhost:63405 (CLOSED)
Python  19189 Adam.Brown   30u    IPv4 0xade16c4796571217       0t0      TCP localhost:commplex-main->localhost:63407 (CLOSED)
```

Is this a known issue?

**Comment by miguelgrinberg** [comment]
Not sure what this means.

I have a deployed application that has been up for a long time, and I don't see any closed sockets still lingering there. Are you sure this isn't temporary? Maybe the OS takes a bit of time to recycle those file handles?

**Comment by audrummer15** [comment]
Hmm, well it's good to know it's not the extension. It's possible that it's the way we're serving it. We are simply using 
```python
socketio.run(app)
```

Using with gunicorn may take care of our issue. I will investigate and respond with the results.

P.S. You're a champ managing this extension. Always very responsive. Many thanks to you sir!

**Comment by miguelgrinberg** [comment]
Ah, okay, so you are checking socket usage during development then. It is possible that Werkzeug (the web server engine used by Flask in debug mode) has a socket leak problem. But since Werkzeug is supposed to be used only for development, it would not be a show stopper. Still worth investigating, but I would not put it high on the panic scale. And Flask-SocketIO configures Werkzeug to work in multithreaded mode, which is not a mode that is widely used, so one more reason to suggest there could be a bug hiding there.

I recommend that you repeat your test with your production configuration, a socket leak on gunicorn, uWSGI, etc. would be a serious problem.

**Comment by audrummer15** [comment]
I'm marking this as closed. I've tested in production and do not see these issues. It must be a problem with Werkzeug. Thanks @miguelgrinberg
