### ISSUE TITLE
(Question) Can server celery task be initiated by emitting a socket from client?

### ISSUE THREAD

**Issue by microdou** [miguelgrinberg/Flask-SocketIO#397]
I have a working Client (`react.js`) ~ Server (`flask (blueprint) & celery & flask-socket.io`) setup.
Client can post via url `/start_a_task` to initiate a celery task within `routes`, just as the following example.
```
# Server Routes
@frontend.route('/start_a_task', methods=['POST'])
def start_a_task():
    test_task.delay(current_app.config['SOCKETIO_REDIS_URL'])
    return 'Started test task'
```

My question is, is it possible to initiate the celery task within `socket events` instead?
```
# Server Events
@socketio.on('action')
def client_submitted_an_action(action_data):
    test_task.delay(current_app.config['SOCKETIO_REDIS_URL'], action_data)
```
In this way, client will be able to **emit a socket to initiate the server celery task**, and the unnecessary route `/start_a_task` can be removed. I've tried this idea but it did not work...

Thanks!

**Comment by Zarinia** [comment]
Hi,
yes, you can run celery task from socket but you can't emit socket from celery
because celery run in different thread.

**Comment by miguelgrinberg** [comment]
Yes, there should be no problem starting the Celery task from the socket event.

**Comment by microdou** [comment]
@Zarinia @miguelgrinberg 
Good to know that it can work.
The problem might be due to a wrong order of importing events and tasks in my setup. It now works after I moved task import step into the socket function. I have both blueprint and celery, so the import order is tricky...
Now everything seems working flawlessly: client can emit a socket to a server socket event;  server then initiate a celery task, which can keep on emitting sockets to the client during the task.

Previous:
```
# events.py

from .tasks import test_task

@socketio.on('action')
def client_submitted_an_action(action_data):
    test_task.delay(current_app.config['SOCKETIO_REDIS_URL'], action_data)
```
Now:
```
# events.py

@socketio.on('action')
def client_submitted_an_action(action_data):
    from .tasks import test_task
    test_task.delay(current_app.config['SOCKETIO_REDIS_URL'], action_data)
```
