### ISSUE TITLE
Can't disconnect a client in the `on_error` handler when also overriding `trigger_event`

### ISSUE THREAD

**Issue by amckinley** [miguelgrinberg/Flask-SocketIO#398]
I'm subclassing `Namespace`, and I implement an `on_error` handler and I override `trigger_event` to get logging of all incoming events. The combination appears to be causing crashes due to exceeding Python's maximum call stack depth. Not sure if this combination is supported or if there's another way I should be attempting this, but it surprised me. 

Example snippet of stack trace: https://gist.github.com/theloniouspunk/e20451fae6b6e175f75d0e77cc689452

Relevant code from my `application.py`:
```
class FlashPokerNamespace(Namespace):
    def on_error(self, e):
        self.logger.exception("Error from client %s", request.sid)
        disconnect()

    def trigger_event(self, event, *args):
        self.logger.debug("Received event '%s'", event)
        return super(FlashPokerNamespace, self).trigger_event(event, *args)
```

**Comment by miguelgrinberg** [comment]
Well, what I think is happening is that your disconnect call in your error handler is triggering an error, which in turn causes the handler to be invoked recursively.

What error are you getting in your log?

**Comment by amckinley** [comment]
I think you're right. I managed to reproduce the issue by crafting a request that triggers a database transaction error, which invokes my `on_error` handler, which invokes `disconnect`, which invokes my `on_disconnect` handler, which performs some DB cleanup that re-throws the transaction error because the session is still in a broken state, which leads to calling `on_error` recursively.

I can just wrap my `disconnect` call in a try/catch block to handle this issue. I'm pretty sure you can close this, unless you think it makes sense to add a try/catch inside the `disconnect` method (or around `_trigger_event('disconnect', *args)`).

**Comment by miguelgrinberg** [comment]
Great. I'm going to leave this open, as a reminder to investigate if I can catch the second error and prevent the recursion.
