### ISSUE TITLE
disconnect() wont disconnect all namespace when the client visit multiple namespace

### ISSUE THREAD

**Issue by bigzt** [miguelgrinberg/Flask-SocketIO#403]
hi Miguel, i found that the disconnect() function won't disconnect all the namespace,  when the client visits multiple namespace. So that's means, the connection is still in there.

```
192.168.1.133 - - [10/Feb/2017 09:45:51] "POST /socket.io/?EIO=3&transport=polling&t=1486691151979-1&sid=dc1ab75ce4cb401f9fc0ff09fe4732bf HTTP/1.1" 200 219 0.002667
192.168.1.133 - - [10/Feb/2017 09:45:51] "GET /socket.io/?EIO=3&transport=polling&t=1486691151982-2&sid=dc1ab75ce4cb401f9fc0ff09fe4732bf HTTP/1.1" 200 272 0.007114
dc1ab75ce4cb401f9fc0ff09fe4732bf: Sending packet NOOP data None
dc1ab75ce4cb401f9fc0ff09fe4732bf: Received packet MESSAGE data 2/time,["time",{"anything":""}]
received event "time" from dc1ab75ce4cb401f9fc0ff09fe4732bf [/time]
emitting event "t" to dc1ab75ce4cb401f9fc0ff09fe4732bf [/time]
dc1ab75ce4cb401f9fc0ff09fe4732bf: Sending packet MESSAGE data 2/time,["t","1486691151"]
192.168.1.133 - - [10/Feb/2017 09:45:51] "POST /socket.io/?EIO=3&transport=polling&t=1486691152006-3&sid=dc1ab75ce4cb401f9fc0ff09fe4732bf HTTP/1.1" 200 219 0.002874
192.168.1.133 - - [10/Feb/2017 09:45:51] "GET /socket.io/?EIO=3&transport=polling&t=1486691152006-4&sid=dc1ab75ce4cb401f9fc0ff09fe4732bf HTTP/1.1" 200 266 0.000391
dc1ab75ce4cb401f9fc0ff09fe4732bf: Upgrade to websocket successful
dc1ab75ce4cb401f9fc0ff09fe4732bf: Received packet PING data None
dc1ab75ce4cb401f9fc0ff09fe4732bf: Sending packet PONG data None
dc1ab75ce4cb401f9fc0ff09fe4732bf: Received packet PING data None
dc1ab75ce4cb401f9fc0ff09fe4732bf: Sending packet PONG data None
**dc1ab75ce4cb401f9fc0ff09fe4732bf: Received packet MESSAGE data 0/login
dc1ab75ce4cb401f9fc0ff09fe4732bf: Sending packet MESSAGE data 0/login**
dc1ab75ce4cb401f9fc0ff09fe4732bf: Received packet MESSAGE data 2/login,["login",{"serial":"","pat_id":"","dev_mac":"","dev_type":"","gain":"","v_ref":"","ad_bit":"","freq":"","electrod":"","signal":""}]
received event "login" from dc1ab75ce4cb401f9fc0ff09fe4732bf [/login]
emitting event "f" to dc1ab75ce4cb401f9fc0ff09fe4732bf [/login]
dc1ab75ce4cb401f9fc0ff09fe4732bf: Sending packet MESSAGE data 2/login,["f",{"msg":"login authentication failed."}]
**Disconnecting dc1ab75ce4cb401f9fc0ff09fe4732bf [/login]**
dc1ab75ce4cb401f9fc0ff09fe4732bf: Sending packet MESSAGE data 1/login
dc1ab75ce4cb401f9fc0ff09fe4732bf: Received packet PING data None
dc1ab75ce4cb401f9fc0ff09fe4732bf: Sending packet PONG data None
dc1ab75ce4cb401f9fc0ff09fe4732bf: Received packet PING data None
```

but when the client visits only one namespace, disconnect() works well.

```
b269a8db547e4416a06fcae6c0b8a782: Sending packet OPEN data {'pingTimeout': 50000, 'upgrades': ['websocket'], 'sid': 'b269a8db547e4416a06fcae6c0b8a782', 'pingInterval': 2000}
b269a8db547e4416a06fcae6c0b8a782: Sending packet MESSAGE data 0
192.168.1.133 - - [10/Feb/2017 09:49:10] "GET /socket.io/?EIO=3&transport=polling&t=1486691350150-0 HTTP/1.1" 200 351 0.002858
(1881) accepted ('192.168.1.133', 53448)
b269a8db547e4416a06fcae6c0b8a782: Received request to upgrade to websocket
b269a8db547e4416a06fcae6c0b8a782: Received packet MESSAGE data 0/login
b269a8db547e4416a06fcae6c0b8a782: Sending packet MESSAGE data 0/login
192.168.1.133 - - [10/Feb/2017 09:49:10] "POST /socket.io/?EIO=3&transport=polling&t=1486691350173-1&sid=b269a8db547e4416a06fcae6c0b8a782 HTTP/1.1" 200 219 0.002930
b269a8db547e4416a06fcae6c0b8a782: Sending packet NOOP data None
192.168.1.133 - - [10/Feb/2017 09:49:10] "GET /socket.io/?EIO=3&transport=polling&t=1486691350175-2&sid=b269a8db547e4416a06fcae6c0b8a782 HTTP/1.1" 200 247 0.000341
b269a8db547e4416a06fcae6c0b8a782: Upgrade to websocket successful
b269a8db547e4416a06fcae6c0b8a782: Received packet PING data None
b269a8db547e4416a06fcae6c0b8a782: Sending packet PONG data None
b269a8db547e4416a06fcae6c0b8a782: Received packet PING data None
b269a8db547e4416a06fcae6c0b8a782: Sending packet PONG data None
b269a8db547e4416a06fcae6c0b8a782: Received packet PING data None
b269a8db547e4416a06fcae6c0b8a782: Sending packet PONG data None
b269a8db547e4416a06fcae6c0b8a782: Received packet PING data None
b269a8db547e4416a06fcae6c0b8a782: Sending packet PONG data None
b269a8db547e4416a06fcae6c0b8a782: Received packet MESSAGE data 2/login,["login",{"serial":"","pat_id":"","dev_mac":"","dev_type":"","gain":"","v_ref":"","ad_bit":"","freq":"","electrod":"","signal":""}]
received event "login" from b269a8db547e4416a06fcae6c0b8a782 [/login]
emitting event "f" to b269a8db547e4416a06fcae6c0b8a782 [/login]
b269a8db547e4416a06fcae6c0b8a782: Sending packet MESSAGE data 2/login,["f",{"msg":"login authentication failed."}]
Disconnecting b269a8db547e4416a06fcae6c0b8a782 [/login]
b269a8db547e4416a06fcae6c0b8a782: Sending packet MESSAGE data 1/login
192.168.1.133 - - [10/Feb/2017 09:49:18] "GET /socket.io/?EIO=3&transport=websocket&sid=b269a8db547e4416a06fcae6c0b8a782 HTTP/1.1" 200 0 8.794847
```

**Comment by bigzt** [comment]
hi Miguel, i found that the disconnect() function won't disconnect all the namespace, when the client when the client visits multiple namespace. So that's means, the connection still in there.

`
192.168.1.133 - - [10/Feb/2017 09:45:51] "POST /socket.io/?EIO=3&transport=polling&t=1486691151979-1&sid=dc1ab75ce4cb401f9fc0ff09fe4732bf HTTP/1.1" 200 219 0.002667
192.168.1.133 - - [10/Feb/2017 09:45:51] "GET /socket.io/?EIO=3&transport=polling&t=1486691151982-2&sid=dc1ab75ce4cb401f9fc0ff09fe4732bf HTTP/1.1" 200 272 0.007114
dc1ab75ce4cb401f9fc0ff09fe4732bf: Sending packet NOOP data None
dc1ab75ce4cb401f9fc0ff09fe4732bf: Received packet MESSAGE data 2/time,["time",{"anything":""}]
received event "time" from dc1ab75ce4cb401f9fc0ff09fe4732bf [/time]
emitting event "t" to dc1ab75ce4cb401f9fc0ff09fe4732bf [/time]
dc1ab75ce4cb401f9fc0ff09fe4732bf: Sending packet MESSAGE data 2/time,["t","1486691151"]
192.168.1.133 - - [10/Feb/2017 09:45:51] "POST /socket.io/?EIO=3&transport=polling&t=1486691152006-3&sid=dc1ab75ce4cb401f9fc0ff09fe4732bf HTTP/1.1" 200 219 0.002874
192.168.1.133 - - [10/Feb/2017 09:45:51] "GET /socket.io/?EIO=3&transport=polling&t=1486691152006-4&sid=dc1ab75ce4cb401f9fc0ff09fe4732bf HTTP/1.1" 200 266 0.000391
dc1ab75ce4cb401f9fc0ff09fe4732bf: Upgrade to websocket successful
dc1ab75ce4cb401f9fc0ff09fe4732bf: Received packet PING data None
dc1ab75ce4cb401f9fc0ff09fe4732bf: Sending packet PONG data None
dc1ab75ce4cb401f9fc0ff09fe4732bf: Received packet PING data None
dc1ab75ce4cb401f9fc0ff09fe4732bf: Sending packet PONG data None
dc1ab75ce4cb401f9fc0ff09fe4732bf: Received packet MESSAGE data 0/login
dc1ab75ce4cb401f9fc0ff09fe4732bf: Sending packet MESSAGE data 0/login
dc1ab75ce4cb401f9fc0ff09fe4732bf: Received packet MESSAGE data 2/login,["login",{"serial":"","pat_id":"","dev_mac":"","dev_type":"","gain":"","v_ref":"","ad_bit":"","freq":"","electrod":"","signal":""}]
received event "login" from dc1ab75ce4cb401f9fc0ff09fe4732bf [/login]
emitting event "f" to dc1ab75ce4cb401f9fc0ff09fe4732bf [/login]
dc1ab75ce4cb401f9fc0ff09fe4732bf: Sending packet MESSAGE data 2/login,["f",{"msg":"login authentication failed."}]
Disconnecting dc1ab75ce4cb401f9fc0ff09fe4732bf [/login]
dc1ab75ce4cb401f9fc0ff09fe4732bf: Sending packet MESSAGE data 1/login
dc1ab75ce4cb401f9fc0ff09fe4732bf: Received packet PING data None
dc1ab75ce4cb401f9fc0ff09fe4732bf: Sending packet PONG data None
dc1ab75ce4cb401f9fc0ff09fe4732bf: Received packet PING data None
`

but when the client visits only one namespace, disconnect() works well.
`

b269a8db547e4416a06fcae6c0b8a782: Sending packet OPEN data {'pingTimeout': 50000, 'upgrades': ['websocket'], 'sid': 'b269a8db547e4416a06fcae6c0b8a782', 'pingInterval': 2000}
b269a8db547e4416a06fcae6c0b8a782: Sending packet MESSAGE data 0
192.168.1.133 - - [10/Feb/2017 09:49:10] "GET /socket.io/?EIO=3&transport=polling&t=1486691350150-0 HTTP/1.1" 200 351 0.002858
(1881) accepted ('192.168.1.133', 53448)
b269a8db547e4416a06fcae6c0b8a782: Received request to upgrade to websocket
b269a8db547e4416a06fcae6c0b8a782: Received packet MESSAGE data 0/login
b269a8db547e4416a06fcae6c0b8a782: Sending packet MESSAGE data 0/login
192.168.1.133 - - [10/Feb/2017 09:49:10] "POST /socket.io/?EIO=3&transport=polling&t=1486691350173-1&sid=b269a8db547e4416a06fcae6c0b8a782 HTTP/1.1" 200 219 0.002930
b269a8db547e4416a06fcae6c0b8a782: Sending packet NOOP data None
192.168.1.133 - - [10/Feb/2017 09:49:10] "GET /socket.io/?EIO=3&transport=polling&t=1486691350175-2&sid=b269a8db547e4416a06fcae6c0b8a782 HTTP/1.1" 200 247 0.000341
b269a8db547e4416a06fcae6c0b8a782: Upgrade to websocket successful
b269a8db547e4416a06fcae6c0b8a782: Received packet PING data None
b269a8db547e4416a06fcae6c0b8a782: Sending packet PONG data None
b269a8db547e4416a06fcae6c0b8a782: Received packet PING data None
b269a8db547e4416a06fcae6c0b8a782: Sending packet PONG data None
b269a8db547e4416a06fcae6c0b8a782: Received packet PING data None
b269a8db547e4416a06fcae6c0b8a782: Sending packet PONG data None
b269a8db547e4416a06fcae6c0b8a782: Received packet PING data None
b269a8db547e4416a06fcae6c0b8a782: Sending packet PONG data None
b269a8db547e4416a06fcae6c0b8a782: Received packet MESSAGE data 2/login,["login",{"serial":"","pat_id":"","dev_mac":"","dev_type":"","gain":"","v_ref":"","ad_bit":"","freq":"","electrod":"","signal":""}]
received event "login" from b269a8db547e4416a06fcae6c0b8a782 [/login]
emitting event "f" to b269a8db547e4416a06fcae6c0b8a782 [/login]
b269a8db547e4416a06fcae6c0b8a782: Sending packet MESSAGE data 2/login,["f",{"msg":"login authentication failed."}]
Disconnecting b269a8db547e4416a06fcae6c0b8a782 [/login]
b269a8db547e4416a06fcae6c0b8a782: Sending packet MESSAGE data 1/login
192.168.1.133 - - [10/Feb/2017 09:49:18] "GET /socket.io/?EIO=3&transport=websocket&sid=b269a8db547e4416a06fcae6c0b8a782 HTTP/1.1" 200 0 8.794847
`

**Comment by miguelgrinberg** [comment]
The namespaces are completely independent of each other. The `disconnect()` call affects only the current namespace.

This is in line with the Socket.IO design, which defines namespaces as independent logical connections, multiplexed on a single physical connection.

**Comment by bigzt** [comment]
Is there have a way that i can disconnect the connection in server side ?

**Comment by miguelgrinberg** [comment]
It seems to me you are not using namespaces for the intended use. If the multiple namespaces that you are using are somehow related, then I recommend that you use a single namespace, and add some data inside the payloads that allows you to know what type of information each payload has. If you do that, then a disconnect should take care of your problem.

Disconnecting all namespaces at the same time is currently not possible, unfortunately.

**Comment by bigzt** [comment]
Thank you very much.
According to python-socketio code, I write a disconnect_conn() function. Could you please review these code?
Thank you again.

```
def disconnect_conn():
    ‘’‘
    close the connection
    ‘’’
    socketio = flask.current_app.extensions['socketio']

    namespace_list = list(socketio.server.manager.get_namespaces())
    for n in namespace_list:
        socketio.server.disconnect(flask.request.sid, namespace=n)

```

**Comment by miguelgrinberg** [comment]
The problem is that you are using private classes and methods of python-socketio. I make no warranties about those, they can change at any time.
