### ISSUE TITLE
test_connect stopped working due to positional argument error

### ISSUE THREAD

**Issue by cs01** [miguelgrinberg/Flask-SocketIO#405]
My unit tests calling `test_client` have been working fine, but all of a sudden I started getting an error. It looks like a dependency or version changed somewhere, but I can't find where. 

```
Traceback (most recent call last):
  File "tests/test_app.py", line 35, in test_connect
    client = socketio.test_client(backend.app)
  File "/home/.virtualenvs/p3/lib/python3.5/site-packages/flask_socketio/__init__.py", line 570, in test_client
    return SocketIOTestClient(app, self, namespace)
  File "/home/.virtualenvs/p3/lib/python3.5/site-packages/flask_socketio/test_client.py", line 51, in __init__
    socketio.server.manager.initialize(socketio.server)
TypeError: initialize() takes 1 positional argument but 2 were given
```

But when I do not pass an argument to test_client, I get

```
Traceback (most recent call last):
  File "tests/test_app.py", line 35, in test_connect
    client = socketio.test_client()
TypeError: test_client() missing 1 required positional argument: 'app'
```

my requirements.txt file:
Flask==0.12
Flask-SocketIO==2.8.2
eventlet==0.20.1

**Comment by miguelgrinberg** [comment]
@cs01 Yeah, sorry about that. I just made a pretty major update to one of the dependencies, and missed this small interface change. If you upgrade to 2.8.3 I think you will be fine.

**Comment by cs01** [comment]
Thanks so much for the quick fix, and thanks for making this library too. I tested with 2.8.3 and it fixed it.
