### ISSUE TITLE
Incompatible with python-socketio==1.7.0

### ISSUE THREAD

**Issue by langep** [miguelgrinberg/Flask-SocketIO#406]
Hi,
I am running into following problem. When I try to deploy my application, I don't receive emits from the server on the client side. I do receive callbacks.

The first request produces following error message:
```
[2017-02-14 01:36:48 +0000] [9] [ERROR] Error handling request /socket.io/?EIO=3&transport=polling&t=1487036208612-0
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 52, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 103, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/flask_socketio/__init__.py", line 42, in __call__
    start_response)
  File "/usr/local/lib/python2.7/site-packages/engineio/middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/socketio/server.py", line 353, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/engineio/server.py", line 251, in handle_request
    transport, b64)
  File "/usr/local/lib/python2.7/site-packages/engineio/server.py", line 349, in _handle_connect
    if self._trigger_event('connect', sid, environ, async=False) is False:
  File "/usr/local/lib/python2.7/site-packages/engineio/server.py", line 378, in _trigger_event
    return self.handlers[event](*args)
  File "/usr/local/lib/python2.7/site-packages/socketio/server.py", line 492, in _handle_eio_connect
    self.manager.initialize()
TypeError: initialize() takes exactly 2 arguments (1 given)
```

**This went away after fixing python-socketio to 1.6.0.**

**Comment by miguelgrinberg** [comment]
Yes, some internal changes went into packages python-engineio and python-socketio in recent days. Thanks for alerting me of it, I need to fix the dependencies to ensure bad combinations of packages are not allowed.

**Comment by bdh1011** [comment]
I had same problem 2days ago and confused during few hours. Downgrading python-socketio to 1.6.0 fixed it.

**Comment by miguelgrinberg** [comment]
@langep @bdh1011 I don't really see a problem, actually. How did you upgrade to python-socketio 1.7.0? That should have also upgraded python-engineio to 1.2.1, which is the correct version. The error that you are having suggests that you are using python-socketio 1.7.0 with a python-engineio version older than 1.2.0, but the dependencies are set up correctly to not allow that combination.

**Comment by langep** [comment]
@miguelgrinberg I was installing it inside a docker container based on 'python:2.7-slim'. My requirements.txt file does not contain any version numbers:

`Flask
flask-socketio
flask-redis
gunicorn
eventlet
celery`

I started building this image before python-socketio and python engineio updated. If it would be helpful, I can try to install things with the above mentioned requirements.txt instead of adding python-socketio==1.6.0 and create a printout of the actual installed versions of everything.

**Comment by miguelgrinberg** [comment]
@langep Yes, if you can still reproduce the problem, I would like know what version of python-engineio is landing on your image.

**Comment by samwwwblack** [comment]
python-socketio's `PubSubManager.initialize` had the `server` argument removed in 1.7.0, but both `KombuManager.initialize` and `RedisManager.initialize` still expect it.

Removing the argument and replacing `server` with `self.server` fixes the issue.

**Comment by miguelgrinberg** [comment]
@samwwwblack Ah, okay, that's what I missed. I'll fixed it.

**Comment by miguelgrinberg** [comment]
Please try the latest python-socketio package. I think that addresses this problem. Sorry about the mistake. I've recently added support for asyncio (not for the flask extension, just for python-socketio), and that required a number of internal changes. I thought I kept everything working, but something always slips.

**Comment by samwwwblack** [comment]
Working here.

**Comment by miguelgrinberg** [comment]
Great. I'm going to assume this is fully addressed and close. Please reopen if there are any more problems.
