### ISSUE TITLE
Background thread how to use socketio push real time database info to client?

### ISSUE THREAD

**Issue by buweilv** [miguelgrinberg/Flask-SocketIO#410]
This is my views file snippet:
```
thread = None


def background_thread(app=None):
    """
   send host status information to client
    """
    with app.app_context():
        while True:
            # update host info interval
            socketio.sleep(app.config['HOST_UPDATE_INTERVAL'])
            # socketio.sleep(5)
            all_hosts = dict([(host.id, host.status) for host in Host.query.all()])
            socketio.emit('update_host', all_hosts, namespace='/hostinfo')


@main.route('/', methods=['GET', 'POST'])
def index():
    all_hosts = Host.query.all()
    return render_template('dashboard.html', hosts=all_hosts, async_mode=socketio.async_mode)

@socketio.on('connect', namespace='/hostinfo')
def on_connect():
    global thread
    if thread is None:
        app = current_app._get_current_object()
        thread = socketio.start_background_task(target=background_thread, app=app)
    emit('my_response', {'data': 'conncted'})

@socketio.on('disconnect', namespace='/hostinfo')
def on_disconnect():
    print 'Client disconnected...', request.sid


@socketio.on('my_ping', namespace="/hostinfo")
def ping_pong():
    emit('my_pong')
```

I want to push real-time database Host table information to the client using a background thread which uses flask-socketio send the information.
However, background thread uses current_app context, so this context is just a "snapshot", so the database information is also just a "snapshot", however, I want to get the real time database information just like in the app context. So how background thread use socketio push real time database info to client?

**Comment by miguelgrinberg** [comment]
The app context in your background thread should be enough for you to get updated queries from the database. But you need to pass the app differently to the thread:

    thread = socketio.start_background_task(target=background_thread, app=app._get_current_object())

Try that, and report back if you get any other errors.

**Comment by buweilv** [comment]
@miguelgrinberg, after I try pass the app differently to thread, I got error:

```
Traceback (most recent call last):
  File "/home/buwei/Flask-Dev/local/lib/python2.7/site-packages/eventlet/wsgi.py", line 490, in handle_one_response
    result = self.application(self.environ, start_response)
  File "/home/buwei/Flask-Dev/local/lib/python2.7/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/buwei/Flask-Dev/local/lib/python2.7/site-packages/flask_socketio/__init__.py", line 42, in __call__
    start_response)
  File "/home/buwei/Flask-Dev/local/lib/python2.7/site-packages/engineio/middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/home/buwei/Flask-Dev/local/lib/python2.7/site-packages/socketio/server.py", line 352, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/home/buwei/Flask-Dev/local/lib/python2.7/site-packages/engineio/server.py", line 259, in handle_request
    socket.handle_post_request(environ)
  File "/home/buwei/Flask-Dev/local/lib/python2.7/site-packages/engineio/socket.py", line 98, in handle_post_request
    self.receive(pkt)
  File "/home/buwei/Flask-Dev/local/lib/python2.7/site-packages/engineio/socket.py", line 50, in receive
    async=self.server.async_handlers)
  File "/home/buwei/Flask-Dev/local/lib/python2.7/site-packages/engineio/server.py", line 359, in _trigger_event
    return self.handlers[event](*args)
  File "/home/buwei/Flask-Dev/local/lib/python2.7/site-packages/socketio/server.py", line 505, in _handle_eio_message
    self._handle_connect(sid, pkt.namespace)
  File "/home/buwei/Flask-Dev/local/lib/python2.7/site-packages/socketio/server.py", line 413, in _handle_connect
    self.environ[sid]) is False:
  File "/home/buwei/Flask-Dev/local/lib/python2.7/site-packages/socketio/server.py", line 480, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/home/buwei/Flask-Dev/local/lib/python2.7/site-packages/flask_socketio/__init__.py", line 222, in _handler
    *args)
  File "/home/buwei/Flask-Dev/local/lib/python2.7/site-packages/flask_socketio/__init__.py", line 587, in _handle_event
    ret = handler()
  File "/home/buwei/Mario/app/main/views.py", line 139, in on_connect
    thread = socketio.start_background_task(target=background_thread, app=app._get_current_object())
AttributeError: 'Flask' object has no attribute '_get_current_objec
```

So, Why do I need to `_get_current_object()` twice, `app` is the first time ` app = current_app._get_current_object()`.

**Comment by miguelgrinberg** [comment]
Ah, right, sorry, I missed you were already doing that one line above. Your original code is correct, then, at least with respect to passing the app instance to the thread.

Next step would be to enable logging on the server and client, to see if the messages are going out and being received by the browser.

**Comment by buweilv** [comment]
@miguelgrinberg
The app context in my background thread is indeed enough for me to get updated queries from the database. Because I add or delete rows from the Host table, then, thread will query Host table with these rows deleted or added. However, when I update the row, thread still get old row information, this is confusing.

**Comment by buweilv** [comment]
@miguelgrinberg
Yes, I have logged on the client and server side, they both get same information. But when I update my rows, I can not get the newest row info, however, I can get newest info from `python mange.py shell` or directly inquiry from sqlite database.

**Comment by miguelgrinberg** [comment]
@buweilv so the only problem is that you can't get updated values from the database? Then try to clear the session, as that will eliminate all cached objects and force the next query to go to the database. Use `db.session.remove()`.

**Comment by buweilv** [comment]
@miguelgrinberg , Yes, the only problem is that you can't get updated values from the database. And I am sorry to ask, where I should use `db.session.remove()`. In your book, I just see  `db.session.remove()` used in a unit test.

**Comment by miguelgrinberg** [comment]
Put it as the last thing in you while loop, so that each iteration starts with a clean session.

**Comment by buweilv** [comment]
Thanks a lot @miguelgrinberg , you're a great person, problem solved. So, the reason is that my background thread just use a stable cached session, so this is why the unit test use `db.session.remove()` to get the newest session?

**Comment by miguelgrinberg** [comment]
Right. In a normal web application, Flask-SQLAlchemy takes care of recycling sessions, so each request gets a clean one. In your thread you were using the same session over and over, with the `remove()` call you are emulating the way sessions work for regular requests.

**Comment by buweilv** [comment]
@miguelgrinberg Got it, antoher question not concerned about this issue, I hope you may help me.
The situation is like this: My flask app is a performance app, the app distribute test info(test IP, test type) to remote servers(the distribution method is realized by redis (pub/sub way) ). **Now in flask app side I want to have a background thread to get result info by subscribing redis channel and store these info to database. So the background thread should start with the flask app, how can I achieve it?**

**Comment by miguelgrinberg** [comment]
Not sure what part you are asking about? You already know how to start a background thread, so if you just need to get a redis client and subscribe to the channel in question. What do you need help with?

**Comment by buweilv** [comment]
I just need a thread start with the flask app under the application context. Yes, the websocket way is feasible, but I think it's triggered by client connection.

**Comment by buweilv** [comment]
For example, I want to start the redis-server with the flask app start, after flask app turn off, the redis server is turned off too. So does the background start with the flask app and destroied with the flask app, the lifecycle of the background thread and redis-server is same as the Flask app.

**Comment by miguelgrinberg** [comment]
Redis is a separate process, you don't have to attach it to the Flask server, just start it separately, or configure it so that it is always running in the background in your OS.

**Comment by buweilv** [comment]
Ok , it's not neccessary to add trouble to flask app, thanks :)
