### ISSUE TITLE
Sending Message by POST

### ISSUE THREAD

**Issue by adityosnrost** [miguelgrinberg/Flask-SocketIO#411]
Hi.

I would like to know if it is possible to have a callback function that return emit to all user ? here is the example:

```
from datetime import datetime
from flask import render_template, jsonify, abort, make_response, request, Flask, redirect, url_for, g
from flask_cors import CORS
from myapp import app

from flask_socketio import emit, join_room, leave_room
from . import socketio

CORS(app)

@app.route('/')
def index():
    return "OKE"

@app.route('/httpcallback/ms', methods=['POST'])
def home():
    emit('my response', {'data': 'POST METHOD Return'}, broadcast=True)

@socketio.on('my event', namespace='/test')
def test_message(message):
    emit('my response', {'data': message['data']})

@socketio.on('connect', namespace='/test')
def test_connect():
    print("connected")
    emit('my response', {'data': 'Connected'})

@socketio.on('disconnect', namespace='/test')
def test_disconnect():
    print('Client disconnected')
```

**Comment by miguelgrinberg** [comment]
Try this:

    @app.route('/httpcallback/ms', methods=['POST'])
    def home():
        socketio.emit('my response', {'data': 'POST METHOD Return'})

**Comment by adityosnrost** [comment]
Hi,

Thanks for your reply. I have tried it, but I have my example client using javascript didn't get the 'POST METHOD Return' both using emit and send. Do I need to create room first ?

**Comment by miguelgrinberg** [comment]
Sorry, missed the namespace:

    @app.route('/httpcallback/ms', methods=['POST'])
    def home():
        socketio.emit('my response', {'data': 'POST METHOD Return'}, namespace='/test')

Since you don't have a context in this function, the namespace is not automatically discovered.

**Comment by adityosnrost** [comment]
Hi,

Thank you very much for your help, it's working great
