### ISSUE TITLE
Need some help, please urgent (Check if user is in custom room)

### ISSUE THREAD

**Issue by mexekanez** [miguelgrinberg/Flask-SocketIO#412]
Hi!
I'm trying to create notification for user if user is not in room.
So in general idea is to create private chat with **two persons**, and if one is offline - send email with message from second user...

Is some way to check current room with len. or by sid or somehow? 

Regards, Ivan!

**Comment by miguelgrinberg** [comment]
You can get the list of rooms a specific user is in using the `rooms()` method of the underlying socket.io server:

    rooms = socketio.server.rooms(sid)

**Comment by mexekanez** [comment]
yep that is correct, but question is how can I know if second user is in the same room and he is not disconnected?

**Comment by mexekanez** [comment]
@miguelgrinberg so let's simplify ... we have 10 instances and one redis server for messages queue (to predict confusing with rooms and sid's).. So I can say that all rooms will be in one place..
next: I joined 2 users into one room.. user 1 sends messages to user2.. but user 2 went offline.. how can I catch this situation and send email with message?

**Comment by miguelgrinberg** [comment]
For starters, if the communication is between two users, then why use a room? Give each user the `sid` of the other and they can communicate.

To detect offline users, you can use a callback. When user1 sends a message to user2, it requests a callback. If the callback does not come in certain amount of time, then you can assume user2 is offline and you can send a notification.

**Comment by mexekanez** [comment]
@miguelgrinberg I need room because service provides multiple users to chat with one.
it's like a dating site.. if users like each other I creating room for them..

**Comment by miguelgrinberg** [comment]
> if users like each other I creating room for them

Right. It's fine to use a room for many people, but when two people want to chat privately, you just have these two users communicate by sending direct messages, using their session ids. And you send these direct messages with a callback request, and that is how you detect if a user went offline.
