### ISSUE TITLE
Support for connecting to WebSockets directly

### ISSUE THREAD

**Issue by willdeuschle** [miguelgrinberg/Flask-SocketIO#416]
Is it possible to support connecting to a WebSocket endpoint directly instead of needing to upgrade upon connection over http? 

My use case is that there are js packages out there which use the WebSocket API and thus expect a url of the form `ws://...` to connect, and that is unfortunately not compatible with this package. 

Happy to contribute to making this happen if possible.

**Comment by miguelgrinberg** [comment]
Sure, that is something that the client needs to request. With the JavaScript client, you do it like this:

    io.connect('https://...', {
        upgrade: false,
        transports: ['websocket']
    })

**Comment by willdeuschle** [comment]
Ok thanks. 

Then am I correct in understanding that it isn't possible to directly use the WebSocket API, with something like `socket = new WebSocket('wss://localhost:5000')`? 

I still connect just fine with the code you've provided above, but the methods exposed by the WebSocket API (with handlers like `onmessage` and `onopen`) are not identical to the methods exposed when connecting with socket.io, which has caused me some problems when using 3rd party libraries that are tied to the WebSocket client-side implementation. I was hoping there might be a workaround for that inconsistency.

**Comment by miguelgrinberg** [comment]
No. If you need a websocket server, then this project is not what you want.
Socket.IO is a different protocol, built on top of websocket.

**Comment by willdeuschle** [comment]
Got it, thank you!
