### ISSUE TITLE
gevent with uwsgi requires ping/pong

### ISSUE THREAD

**Issue by MattWycklendt** [miguelgrinberg/Flask-SocketIO#417]
I am having an issue where the client does not receive emits from the server unless it sends a message.  To recreate the issue run the example app in the Flask-SocketIO library and comment out the ping/pong functions in the client library (currently lines 38 to 57).  Run the server with uwsgi and gevent using the command listed in the docs.  If I send an ECHO message to the server the client doesn't get any response back until sending another ECHO message.

**Comment by miguelgrinberg** [comment]
When you say

> If I send an ECHO message to the server the client 

Do you mean typing `ECHO` in the first text box from the example in this repository, so is it something else? If you are using your own code, messages that are sent do not receive a response, unless you request a callback.

**Comment by MattWycklendt** [comment]
@miguelgrinberg Sorry, I probably wasn't clear in my description.  I am not using my own code, only the example code provided in the repo with a couple lines commented out.  Below are more detailed steps:
 1. I cloned the Flask-SocketIO library.
 2. I installed gevent and uwsgi in my virtual environment.
 3. In `/examples/templates/index.html` I commented out the interval timer to emit a `my_ping` message, and listen to `my_pong` message.  This is equivalent to commenting out lines 38 to f7.
 4. Run the app with uwsgi in the example directory using the command `uwsgi --http :5000 --gevent 1000 --http-websockets --master --wsgi-file app.py --callable app`
 5. In the browser start sending messages in the first echo text box.  If I type `msg1` I expected to see that echoed back but nothing happened. If I enter `msg2` in the text box I see `msg1` come back.  If I then enter `msg3` in the text box I see `msg2` come back... Basically I was only recieving echo messages from the server after entering another echo message.

**Comment by miguelgrinberg** [comment]
Sorry for the misunderstanding. I have now reproduced the issue.

It appears I inadvertently introduced this bug in https://github.com/miguelgrinberg/python-engineio/commit/d15842383b1cd0fbaa741c5125b5ef26d1915a7a, by changing the method to read the websocket file handle.

Please upgrade python-engineio to version 1.2.4. I think with that upgrade uwsgi will behave.

**Comment by MattWycklendt** [comment]
Working.  Thanks!
