### ISSUE TITLE
client could not receive emits from the server.

### ISSUE THREAD

**Issue by Missingbrain** [miguelgrinberg/Flask-SocketIO#418]
i am learning flask now and i have a big problem.
i use flask and flask-scoketio.  my client could not receive emits from the server. i dont know why.
the websocket is Upgrade 
```
(10728) accepted ('127.0.0.1', 52781)
(10728) accepted ('127.0.0.1', 52782)
127.0.0.1 - - [01/Mar/2017 16:14:38] "GET / HTTP/1.1" 200 5263 0.010000
127.0.0.1 - - [01/Mar/2017 16:14:38] "GET /static/web.css HTTP/1.1" 200 6780 0.219000
111c03a0438947ecae776c4103091c37: Sending packet OPEN data {'pingInterval': 25000, 'pingTimeout': 60000, 'upgrades': ['websocket'], 'sid': '111c03a0438947ecae776c4103091c37'}
111c03a0438947ecae776c4103091c37: Sending packet MESSAGE data 0
127.0.0.1 - - [01/Mar/2017 16:14:38] "GET /socket.io/?EIO=3&transport=polling&t=Lg8xtLu HTTP/1.1" 200 381 0.001000
(10728) accepted ('127.0.0.1', 52784)
111c03a0438947ecae776c4103091c37: Received request to upgrade to websocket
111c03a0438947ecae776c4103091c37: Sending packet NOOP data None
111c03a0438947ecae776c4103091c37: Received packet MESSAGE data 2["message",{"data":"hello"}]
111c03a0438947ecae776c4103091c37: Sending packet MESSAGE data 2["server_response",{"data":"welcome"}]
127.0.0.1 - - [01/Mar/2017 16:14:38] "POST /socket.io/?EIO=3&transport=polling&t=Lg8xtM9&sid=111c03a0438947ecae776c4103091c37 HTTP/1.1" 200 219 0.002000
127.0.0.1 - - [01/Mar/2017 16:14:38] "GET /socket.io/?EIO=3&transport=polling&t=Lg8xtMA&sid=111c03a0438947ecae776c4103091c37 HTTP/1.1" 200 260 0.000000
(10728) accepted ('127.0.0.1', 52785)
127.0.0.1 - - [01/Mar/2017 16:14:38] "GET /favicon.ico HTTP/1.1" 404 366 0.000000
111c03a0438947ecae776c4103091c37: Upgrade to websocket successful
```

when i click in client,the emits is empty
`111c03a0438947ecae776c4103091c37: Received packet MESSAGE data 2["message",{"data":"one"}]
111c03a0438947ecae776c4103091c37: Sending packet MESSAGE data 2["server_response",{"data":""}]
111c03a0438947ecae776c4103091c37: Received packet MESSAGE data 2["message",{"data":"two"}]
111c03a0438947ecae776c4103091c37: Sending packet MESSAGE data 2["server_response",{"data":""}]
111c03a0438947ecae776c4103091c37: Received packet MESSAGE data 2["message",{"data":"three"}]
111c03a0438947ecae776c4103091c37: Sending packet MESSAGE data 2["server_response",{"data":""}]
111c03a0438947ecae776c4103091c37: Received packet MESSAGE data 2["message",{"data":"four"}]
111c03a0438947ecae776c4103091c37: Sending packet MESSAGE data 2["server_response",{"data":""}]
111c03a0438947ecae776c4103091c37: Received packet MESSAGE data 2["message",{"data":"five"}]
111c03a0438947ecae776c4103091c37: Sending packet MESSAGE data 2["server_response",{"data":""}]
111c03a0438947ecae776c4103091c37: Received packet MESSAGE data 2["message",{"data":"six"}]
111c03a0438947ecae776c4103091c37: Sending packet MESSAGE data 2["server_response",{"data":""}] `

here is the code

server:
```
@socketio.on('message')
def connectevent(job_name):
    if job_name['data'] == 'hello':
        emit('server_response', {'data': 'welcome'})
    else:
        log_command = ['ping','-t','192.168.4.1']
        log_out = subprocess.Popen(log_command, stdout=subprocess.PIPE)
        while log_out:
            out = log_out.stdout.readline().strip()
            emit('server_response', {'data':out})
```

the out could not print fully and  the emits could not send,it only print 
```
111c03a0438947ecae776c4103091c37: Received packet PING data None
111c03a0438947ecae776c4103091c37: Sending packet PONG data None
111c03a0438947ecae776c4103091c37: Received packet PING data None
111c03a0438947ecae776c4103091c37: Sending packet PONG data None
111c03a0438947ecae776c4103091c37: Received packet PING data None
111c03a0438947ecae776c4103091c37: Sending packet PONG data None
111c03a0438947ecae776c4103091c37: Received packet PING data None
111c03a0438947ecae776c4103091c37: Sending packet PONG data None
```
if i replace **while** with **if** , it works,but it only send one line to client.

client 
```
var socket = io.connect('http://' + document.domain + ':' + location.port);
var name = 'hello'

function jobname(name){
    socket.emit('message',{'data':name});
    return false;
};

socket.on('connect', function() {
    socket.emit('message',{'data':name});
})

socket.on('server_response', function(msgg) {
    console.log(msgg)
    $('#loog').append('<br>' + $('<div/>').text(msgg.data).html());
});
```

thanks everyone

**Comment by miguelgrinberg** [comment]
Are you using eventlet or gevent? If you are, add a `socketio.sleep(0)` after the `emit` in your loop. That will release the CPU and let other tasks do their work.

**Comment by Missingbrain** [comment]
it works,thank you

**Comment by Missingbrain** [comment]
it works on linux,thank you!

**Comment by kyouko-taiga** [comment]
Hello,

I have a similar issue in a very similar setup, but unfortunately adding `socketio.sleep(0)` didn't help in my case. I'm trying to bridge a ssh shell to a web client through socketio. One thread listens to the shell's socket while an event handler sends data to it.

Here are the relevant lines of my code (the whole source is available here: [ssh.py](https://github.com/kyouko-taiga/swift-webui/blob/python-server/webenvy/apps/api/stream/ssh.py)):

```python
@socketio.on('stdin')
def handle_stdin(payload):
    emit('echo', { 'data': payload.get('data', '') })
    socketio.sleep(0)
    channel.send(payload.get('data', ''))

def forward_outbound(channel):
    while True:
        select([channel], [], [])
        data = channel.recv(1024)
        if not data:
            break
        print(data)
        socketio.emit('stdout', { 'data': data.decode() })
        socketio.sleep(0)

thread = threading.Thread(target=forward_outbound, args=[channel])
thread.start()
```

Without eventlet, everything works as expected (the client receives `stdout` events for each read of the shell's output). However with eventlet, nothing but sometimes a single event is emitted (including the `echo` event from the `handle_stdin` function).

**Comment by miguelgrinberg** [comment]
@kyouko-taiga you can't use regular networking and threading functions when you use eventlet, because those are blocking. Your best shot is to see if monkey patching resolves the problem. Just add the following as the first lines of your script:

    import eventlet
    eventlet.monkey_patch()

**Comment by kyouko-taiga** [comment]
Unfortunately that won't do neither. I'll find a workaround.
Thanks for the explanation and the suggestion!

**Comment by miguelgrinberg** [comment]
> Unfortunately that won't do neither.

Care to share why?

**Comment by kyouko-taiga** [comment]
I guess monkey-patching isn't enough to solve the issue of blocking threads.

I tired to monkey patch the standard library, as well as [paramiko](http://www.paramiko.org) (the library I use to open my ssh shell) but the same problem occurs.

I should investigate further into paramiko I think. I'll be sure to keep you posted if I can solve my issue.

**Comment by miguelgrinberg** [comment]
Hmm. Monkey patching should address all your issues with blocking threads. I do not know for sure if that will make Paramiko work, but some people appear to have made it work, both with eventlet and gevent: https://github.com/paramiko/paramiko/issues/389.

**Comment by aswinckr** [comment]
I think my problem is the same as this. I tried the socketio.sleep(0) command as well but the logs still show no data being passed from emit. `Sending packet MESSAGE data 0/chat`

**Comment by nguyendohuuduc** [comment]
I have the same problem. When I added socketio.sleep(0), it works on mac but doesn't work on windows machine and I cant figure out why. Any help is appreciated.
