### ISSUE TITLE
Connecting stored user list in a room?

### ISSUE THREAD

**Issue by rakibtg** [miguelgrinberg/Flask-SocketIO#419]
In my flask app i have a route where it should take a list of user id and add them to a room from a post request, here is my code:
```
@app.route( '/serve/room/add', methods=[ 'POST' ] )
def addToRoom():
  # Get a list of users from the provided string of user ID's
  userIdList = [x.strip() for x in request.form[ 'users' ].split(',')]
  # Add each user in the group
  try:
    for userid in userIdList:
      join_room( { 'userid' : userid, 'room' : request.form[ 'room' ] } )
      print( userid )
    return dictToJson( { 'status' : 1 } )
  except Exception as e:
    return dictToJson( { 'status' : 0, 'error' : str(e) } )
```

I sent the request like this:
![image](https://cloud.githubusercontent.com/assets/5412730/23469412/af496128-fecd-11e6-9b49-63fb3ab6d559.png)

But its returning this error:

> 'Request' object has no attribute 'sid'

What is missing here?

**Comment by miguelgrinberg** [comment]
The `join_room` function takes a single argument, the room to join. The user that's joining the room is assumed to be the originator of the event, which means this function cannot be invoked from a regular HTTP request, as the needed context only exists in a Socket.IO event handler.

There is currently no support for doing what you want in this extension, but you can do it by invoking a method in the Socket.IO server directly:

    socketio.server.enter_room(sid, room, namespace='/your-namespace-here')

The `sid` is the session id that was assigned to the client you want to put in the room.
