### ISSUE TITLE
error: no handlers could be found for logger 'socketio.virtsocket'

### ISSUE THREAD

**Issue by boots-shirts** [miguelgrinberg/Flask-SocketIO#42]
Hi Miguel,
This probably isn't a new issue, but I'm just keeping getting this error:"no handlers could be found for logger 'socketio.virtsocket'" and have no idea what went wrong. 

P.S I have added javascript code in the html file. And the sytax and order of my imports seem fine.

Jquery is local, and the source of socket.io is: 

<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/0.9.16/socket.io.min.js"></script>

Could you give me any suggestions?

Thanks!

**Comment by yamauk** [comment]
"socketio.virtsocket"  is trying to report some error. But you've not set a logger for your program.
For example, you can avoid the error by adding this code.
```python
import logging
logging.basicConfig()
```
