### ISSUE TITLE
Graceful shutdown

### ISSUE THREAD

**Issue by xarg** [miguelgrinberg/Flask-SocketIO#421]
Currently when I want to reload the server with a new version of the code I just kill it with SIGTERM. Is this the correct way to do it? 

The behavior that I'm looking for is to tell flask-socketio server (eventlet in my case) not to accept any connections anymore, wait until all the existing events have been executed and the connections are closed and then shutdown.

Thank you!

**Comment by miguelgrinberg** [comment]
This is the correct behavior in theory. In practice, however, this is apparently harder to implement than one may think, because this doesn't always work well. Try it on your environment to make sure this works before you commit to this solution.

**Comment by xarg** [comment]
Thanks @miguelgrinberg I'll post my findings here. I was wondering if at least it's possible to tell flask-socketio not to accept more new connections. Do you know if it's possible to do currently?

**Comment by miguelgrinberg** [comment]
That's something that needs to be done with the server. Flask-SocketIO does not accept connections, the server does. I don't recall eventlet having that as an option, though I believe it is supposed to let current requests end before exiting, which is the behavior that you want.
