### ISSUE TITLE
update session in a background thread

### ISSUE THREAD

**Issue by jwkvam** [miguelgrinberg/Flask-SocketIO#422]
I want to store some data in a cookie or session. The data I want to store is coming from a background task and I really want to update the session or cookie in the background thread. I don't want to do it in the foreground because I don't know how to do it without blocking. I'm not sure if this is possible and if I'm wasting time. I'm also not a Flask expert so I may be missing something. I'm trying to do the following for example

```
@socket.io('event')
def foo():
    def bar():
        eventlet.sleep(10)
        return dict('key'='value')
    bar = copy_current_request_context(bar)
    thread = eventlet.spawn(bar)

    ret = thread.wait()
    if isinstance(ret, dict):
        session.update(ret)
```

The above works, but I don't like it because `thread.wait()` blocks. I tried to think of some clever solution with eventlet but nothing comes to mind. The following doesn't block, but I also don't update the original session object.

```
@socket.io('event')
def foo():
    evt = eventlet.event.Event()
    def bar():
        eventlet.sleep(10)
        evt.send(dict('key'='value'))
    bar = copy_current_request_context(bar)
    thread = eventlet.spawn(bar)

    def waiter(session):
        ret = evt.wait()
        if isinstance(ret, dict):
            session.update(ret)

    waiter = copy_current_request_context(waiter)
    eventlet.spawn(waiter, session)
```

I'd appreciate any advice, even if it's just to say that this isn't possible.

**Comment by miguelgrinberg** [comment]
It doesn't seem to me that the session is the proper place to store this information. For starters, the Flask session is stored in a cookie, so the only way to make a change is to set the cookie again, and this is not possible when using WebSocket because there are no HTTP responses. When you set the session, you are only setting it locally, the changes are not going out to the client, so they are not going to be visible on HTTP routes that rely on a cookie to restore the session.

Why don't you instead set up some server-side storage that you have full access? Maybe something like Redis or memcache is what I'm thinking.

**Comment by jwkvam** [comment]
That makes sense, I would use Redis to store this data normally. Maybe some backstory might explain why I'm thinking about doing this.

I'm building a [tool](https://github.com/jwkvam/bowtie) for data scientists to quickly generate dashboards. If it takes a while to compute something for a plot, then if possible, it might be nice to shove it in a cookie? If they can get this feature without provisioning a database, I think it would enable developing faster responding dashboards and deploying them quicker.

I was hoping to use sessions as a quick and dirty key-value store to hold expensive computations that don't generate much data. Sorry, I'm a little inexperienced so I don't quite understand what it means to set a session locally but it doesn't go out to the client. I'm basically trying to pick things up as I go along.

Hmm, I just had an idea, that maybe I could store some data in a dummy React component.

I don't know if there's any more you can say, but regardless thanks for helping 👍

**Comment by miguelgrinberg** [comment]
Using cookies to store data is totally fine, but you need to keep in mind you are using WebSocket, so there is no vehicle for the server to send cookies to the client, like there is for HTTP. So using the user session for this becomes complicated, unless you switch to server-side sessions, in which case the rules change. If you wanted to use cookies for this, what you can do do instead, is to send the data to the client over the Socket.IO transport, and then have the client set a cookie by itself.

**Comment by jwkvam** [comment]
The last suggestion of yours sounds good. I'll give it a shot. Thanks again for your insight. I think I'll mark this closed now.
