### ISSUE TITLE
Problems with flask socketio behind nginx/uwsgi.

### ISSUE THREAD

**Issue by georgikoyrushki95** [miguelgrinberg/Flask-SocketIO#429]
Hi there,

We are having problems with flask socketio when it switches to using websockets in production. What happens is that emit() events from a client don't always reach the server. We have tried some debugging and established that this happens even if there is a socket connection. Is it something to do with the way flask socketio is configured in our app? This is the way the server is setup:

`
#!venv/bin/python

from webapp import create_app, socketio
app = create_app('dev')

socketio.run(app, host='0.0.0.0')`

My team and I have not written this. It was from a previous team on the project we are working on. If this is a normal behaviour, are we supposed to handle this ourselves (emit() not reaching server even if a connection is established). Final question, is there a way to set flask socket io to use only long-polling when the server is set up?

Thank you very much for your help in advance.

**Comment by dengxuesong** [comment]
use uwsgi?many processes?

**Comment by miguelgrinberg** [comment]
@georgikoyrushki95 You need to provide me with more information.

- Are you using uwsgi with gevent or without?
- Does your application work when you remove nginx from the picture?
- Can you show me how you start your uwsgi server?
- Can you show me your nginx configuration file?

**Comment by georgikoyrushki95** [comment]
@miguelgrinberg , thank you for responding. Below are answers to your questions.

Are you using uwsgi with gevent or without?
A: It's uwsgi 2.0.14 + gevent 1.2.1

Does your application work when you remove nginx from the picture?
A: only on the localhost yeah - on the server it's served by nginx

Can you show me how you start your uwsgi server?
A: 
```
sudo service uwsgi start

.wsgi file:
from webapp import create_app

application = create_app('prod')

if __name__ == "__main__":
    application.run()

uwsgi.conf:
	
description "uwsgi server"
start on runlevel [2345]
stop on runlevel [06]

respawn

chdir {{ project_root }}
env APP_CONFIG_FILE={{ project_root }}/prod.cfg
export APP_CONFIG_FILE
exec uwsgi --emperor /etc/uwsgi/vassals --uid www-data --gid www-data

app_uwsgi.ini:
[uwsgi]
http            = :{{ app_port }}
gevent          = 1000
http-websockets = true
master          = true
{% if is_dev is defined %}
wsgi-file       = {{ project_root }}/example_dev.wsgi
{% else %}
wsgi-file       = {{ project_root }}/example.wsgi
{% endif %}
chdir           = {{ project_root }}
venv            = venv
callable        = application	
```	
Can you show me your nginx configuration file?
A: Sure!
```
# listen on opinew.com:80 (HTTP-WWW) - redirect to www.the_app.com:443 (HTTPS+WWW)
server {
        listen 80;
        server_name example.com;
        return 301 https://www.example.com$request_uri;
}

# listen on opinew.com:443 (HTTPS-WWW) - redirect to www.opinew.com:443 (HTTPS+WWW)
server {
        listen 443 ssl;
        server_name example.com;

        ssl_certificate     /etc/letsencrypt/live/www.example.com/fullchain.pem;
        ssl_certificate_key     /etc/letsencrypt/live/www.example.com/privkey.pem;
        return 301 https://www.example.com$request_uri;
}

# listen on www.opinew.com:443 (HTTPS+WWW)
server {
        listen 443 ssl;
        server_name www.example.com;

        server_tokens off;
        charset utf-8;

        # SSL
        ssl_certificate     /etc/letsencrypt/live/www.example.com/fullchain.pem;
        ssl_certificate_key     /etc/letsencrypt/live/www.example.com/privkey.pem;

        # Enables all versions of TLS, but not SSLv2 or 3 which are weak and now deprecated.
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

        # Intermediate cypersuite as recommended by Mozilla
        ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
        ssl_prefer_server_ciphers on;

        # Add HSTS (HTTPStrictTransportSecurity)
        add_header Strict-Transport-Security "max-age=31536000";

        client_max_body_size 5M;

        access_log  /var/log/nginx/access.log;
        error_log  /var/log/nginx/error.log;

        # This is for letsencrypt
        location ~ /.well-known {
                allow all;
        }

        location /socket.io {
            proxy_pass http://127.0.0.1:{{ app_port }}/socket.io;
            proxy_redirect off;
            proxy_buffering off;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
        }

        location / {
            proxy_pass http://127.0.0.1:{{ app_port }};
            proxy_redirect off;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_buffer_size   128k;
            proxy_buffers   4 256k;
            proxy_busy_buffers_size   256k;
        }
}
```

**Comment by miguelgrinberg** [comment]
> > Does your application work when you remove nginx from the picture?
> A: only on the localhost yeah - on the server it's served by nginx

What I mean here, is if the app works when connecting to the uwsgi port, using the same configuration that you use on production. Can you test that? That will tell us if this is a nginx or uwsgi problem. I can't really spot anything wrong in your configuration.

**Comment by georgikoyrushki95** [comment]
Hi, 
We tried this. The app is working. A very strange observation I made is that neither in testing nor when I tried what you asked me to, was socketio using websockets. This was exactly what we had in production until about two weeks ago. For some reason (I think it might be because we updated gevent and flask socketio), socketio switched to using web sockets, and this is when we started noticing this behaviour - emits() not reaching the server. Just yesterday before I first contacted you, we tried to force long-polling, and everything seemed to work just fine.
I am not sure how helpful this is, but for now it's all the information I have.

**Comment by miguelgrinberg** [comment]
Are there any errors on the client or the server when these emits fail? Both the client and the server can enable logging, that may be useful in debugging this problem.

**Comment by georgikoyrushki95** [comment]
![screenshot from 2017-03-18 18-01-26](https://cloud.githubusercontent.com/assets/15527263/24075024/f2730ae4-0c0b-11e7-88bd-c7eb8c4a8f9a.png)
This is the network log when the problem occurs on the client side.

**Comment by miguelgrinberg** [comment]
I meant to say that you should enable socket.io logging on both ends, to see what the errors actually.
