### ISSUE TITLE
Alternative Front-end JavaScript library 

### ISSUE THREAD

**Issue by Rexwell** [miguelgrinberg/Flask-SocketIO#430]
Hi,

I would like to understand Flask Socket IO better. What I want to try is to swap the front-end JavaScript library (socket.io.min.js)  with alternatives. I wonder if your Flask Socket IO will accept communication message send from the front-end with other JavaScript library that implements Socket IO protocol. The alternative JavaScript library I am looking into is Sails.js and Atmopshere JS.  What type of modification do I need to make in order to integrate it together. How much work does it involve ?

**Comment by miguelgrinberg** [comment]
The server will connect with any compliant Socket.IO client, so really as long as your library speaks Socket.IO you should be fine without making any changes on the server side.
