### ISSUE TITLE
how to get the client status

### ISSUE THREAD

**Issue by dengxuesong** [miguelgrinberg/Flask-SocketIO#431]
i want to get the client‘s status，such as online，offline，socketio can？

**Comment by dengxuesong** [comment]
i use many servers，and has redis as message_queue

**Comment by dengxuesong** [comment]
@miguelgrinberg can u give some advisor

**Comment by miguelgrinberg** [comment]
See my Flack application: https://github.com/miguelgrinberg/flack.

**Comment by dengxuesong** [comment]
@miguelgrinberg  ok thanks now i save it in redis when connect,but sometimes it cause not exact
