### ISSUE TITLE
How would you recommend initializing a Flask extension which depends on Flask-SocketIO?

### ISSUE THREAD

**Issue by jwg4** [miguelgrinberg/Flask-SocketIO#437]
I am writing a Flask extension which will have a hard dependency on Flask-SocketIO. Briefly using this extension with a Flask app will add some routes to the app, which also emit messages over SocketIO. I just wanted to ask advice over the right way to set the app and the extension up.

Basically, one way could require the user to do this:
```
from flask import Flask
from flask_socketio import SocketIO
from flask_foo import Foo

app = Flask()
socketio = SocketIO(app)
foo = Foo(app, socketio)
```
along with various variations if `init_app` is used. The advantages of this method is that 
1. One then has a socketio object, so that one can do socketio.run()
2. If socketio is used elsewhere in the app, again the socketio object is accessible.

On the other hand, the initialization could look like this,
```
app = Flask()
foo = Foo(app)
```
provided that one creates and initializes socketio in Flask-Foo itself:
```
from flask_socketio import SocketIO

class Foo(object)
    ...
    def init_app(self, app):
        self.app = app
        self.socketio = SocketIO(self.app)

    def run(self):
         self.socketio.run()
```

The big advantage of this method is that if someone using Flask-Foo doesn't know about Flask-SocketIO, they don't have to find out. Indeed, one point of the extension is to allow someone to use an app architecture which sends messages to the client without directly dealing with the mechanics of socketIO. However, if they do want to use socketIO elsewhere in the app, it's kind of clumsy, and I'm not sure if they should initialize their own instance of FlaskSocketIO, or somehow obtain the one initialized by FlaskFoo.

So I would like to know: is there are reasonable way to do the second way, without this drawback? Is there some other way of doing it, which combines the pluses of the two methods? Are there any reasons either of these is a non-starter? Is there any extension which provides a good example of how to do this?

I appreciate this isn't strictly a support question, but I appreciate your advice if possible. Thanks in advance.

**Comment by miguelgrinberg** [comment]
I'm going to throw a third option at you.

To initialize it works like your second option:

```python
app = Flask()
foo = Foo(app)

# ...

foo.run()
```

But internally, this is what you can do:

```python
from flask_socketio import SocketIO

class Foo(SocketIO):
    # add your extension specific methods here
```

With this method, your users will just need to install your extension and you don't have to rewrite anything, since all the Socket.IO functionality is inherited. And if your users want to do Socket.IO specific stuff that does not apply to your extension, you can document that your `Foo` instance is fully compatible with my `SocketIO` instance.

**Comment by jwg4** [comment]
Thanks very much, this seems like a nice clean design. I will try it out.
