### ISSUE TITLE
Debian Packaging and Project Changelogs

### ISSUE THREAD

**Issue by diraol** [miguelgrinberg/Flask-SocketIO#438]
Hi @miguelgrinberg ,

I am from Kytos Project (https://github.com/kytos/kytos / https://kytos.io) and we are using `Flask-SocketIO` on our project (**Big thanks for that!!!**).

Currently we are working on building debian packages for our project.

But unfortunatelly `Flask-SocketIO` do not have a debian package and is not on the debian repositories (the same applies for `python-engineio` project, which is a dependency for  `Flask-SocektIO`!).

So, we are willing to package `Flask-SocketIO` and `python-engineio` for Debian, and would be very nice to have the project CHANGELOG file on this projects in order to to make their packages more complete. ;)

Is it possible for you to address some efforts on this issue?
I've seen that there is a PR (#202) with an automated Changelog proposed. May be we can start with an updated version of that Changelog and use the same tool on `python-engineio`. What do you think about that?

**Comment by miguelgrinberg** [comment]
I meant to get change logs going, but I never got around to do it. I'll see if I can get it done in the near future.

**Comment by miguelgrinberg** [comment]
Unfortunately I do not have the bandwidth to maintain a meaningful change log that covers this and the other two packages. These three projects are fairly active, so maintaining change logs outside of the git commit logs would complicate things for me. I'll revisit in the future if I find a good solution for this.
