### ISSUE TITLE
Question: Reading from a stream

### ISSUE THREAD

**Issue by jason-feng** [miguelgrinberg/Flask-SocketIO#440]
Couldn't find much in the docs, and I am also new to sockets, but I currently have a node client streaming an audio file to flask. would i just try to handle this as a message as well?

**Comment by miguelgrinberg** [comment]
Streaming would be handled as a sequence of emits, each with a segment of the stream. I guess you get your audio in chunks, correct? You can use the chunk size from your audio source and send these chunks as you receive them.
