### ISSUE TITLE
Rooms seemingly not included in SocketIO import

### ISSUE THREAD

**Issue by benjaminturley** [miguelgrinberg/Flask-SocketIO#446]
I'm running an app with the classic __ init __.py creating an instance of socketio with SocketIO(app) in the style of your lovely mega-tutorial. I am importing socketio into a file called sockets.py where everything seems to be working except rooms. Right now the only thing sockets.py consists of is this: 

```
from app import app, socketio

@socketio.on("userfy")
def userfy(data):
    socketio.send("test")
    socketio.join_room("test")
    return
```

The decorator works just fine, as does the send command. However, I get this error on the second to last line:

`AttributeError: 'SocketIO' object has no attribute 'join_room'`

This is the case with every variation of rooms, including 'leave_room', 'close_room', and 'rooms'. I have even tried importing SocketIO raw with `from flask_socketio import SocketIO, join_room, rooms`... ect. Same error. I am totally at a loss as to why the code is behaving this way, `socketio.send("message", room="test")` works like a charm. I've tried everything from moving files around to uninstalling and reinstalling flask-socketio. I'm sure I'm doing something stupid but I can't for the life of me figure out what it is.

**Comment by miguelgrinberg** [comment]
There is no `socketio.join_room`, as the error indicates. Instead, you should do this:

```python
from flask_socketio import send, join_room
from app import app, socketio

@socketio.on("userfy")
def userfy(data):
    send("test")
    join_room("test")
    return
```

The `send()` standalone function will use information from the request context to send the `test` response only to the client that emitted the `userfy` event. Your code above broadcasts the response event to all clients. The `join_room()` standalone function will also use request data to know which client is joining the room.

**Comment by benjaminturley** [comment]
Wow, it's almost like you wrote the package or something. Thanks for doing what you do!
