### ISSUE TITLE
Is the message queue implementation compatible with the official socket.io emitter?

### ISSUE THREAD

**Issue by ZacharyJia** [miguelgrinberg/Flask-SocketIO#448]
I found that there is an official socket.io emitter using redis for sending message from other processes or even other languages.

I wonder if flask-socketIO with redis can work with other emitter implementation(like go or java)?

Thanks!

**Comment by miguelgrinberg** [comment]
No, the official socket.io emitter does not work with this server. You can, however, emit via Redis from other processes, but the implementation is not the same. See https://flask-socketio.readthedocs.io/en/latest/#emitting-from-an-external-process for the details of how it is done.
