### ISSUE TITLE
failed: Error during WebSocket handshake: Unexpected response code: 200

### ISSUE THREAD

**Issue by szhjia** [miguelgrinberg/Flask-SocketIO#455]
When I click the button to send message, the browser will get the failed. But the second time it works fine. It only happens under prod env which I use gunicorn. The gunicorn.conf is 

```
workers = 1
bind = 'unix:/~/projects/web_shop/web_shop.sock'
worker_class='eventlet'
threads=1
timeout=60
```
When I running python app.py -h 0.0.0.0 the failed never happened.

Get no idea about this error, would some one help, thanks.

**Comment by miguelgrinberg** [comment]
Did you try using a tcp port instead of a unix socket? I don't think using a unix socket is wrong, but I'm wondering if gunicorn supports that.

**Comment by szhjia** [comment]
I tried to change to a tcp port, but still the same error.

**Comment by szhjia** [comment]
Looks like the app can't work with websocket, so it will try polling. But how can I enable websocket? Where am i wrong?

**Comment by szhjia** [comment]
Hi Miguel,
I found that my nginx conf can not return 101 when websocekt connecting. My nginx conf is as follow:
```
upstream web_shop {
        server 127.0.0.1:5000;
}

server {
    listen 80;
    server_name 0.0.0.0;
    access_log /home/kimi/logs/web_shop/access.log;
    error_log /home/kimi/logs/web_shop/error.log;

    location / {
        proxy_pass http://web_shop;

        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /socketio {
        proxy_pass http://web_shop/socketio;
        proxy_http_version 1.1;
        proxy_redirect off;
        proxy_buffering off;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }

} 
```
Do you have any idea that where am i wrong ? Thanks.

**Comment by miguelgrinberg** [comment]
The location for the socketio endpoint should be `/socket.io` (unless you are using a custom endpoint). Here is an example nginx config file that I'm currently using (the SSL stuff makes it a bit more complex than yours, you can ignore that if you don't care about encryption): https://github.com/miguelgrinberg/flack/blob/master/webserver/nginx/flack.conf.

**Comment by szhjia** [comment]
What a stupid mistake I made!!! Thanks Miguel, finally it is solved under your instruction. It is socket.io but not socketio. Now, the connection is websocket. 
I am extremely grateful for your incredible work. thank you.
