### ISSUE TITLE
"best performant option"

### ISSUE THREAD

**Issue by skortchmark9** [miguelgrinberg/Flask-SocketIO#456]
Hey Miguel, how's it going!

I'm starting a new project and I'm trying to decide more intelligently between gevent and eventlet. This particular project has to be windows-friendly.

In the docs, you state that 
> eventlet is the best performant option

But this [stackoverflow post](http://stackoverflow.com/questions/12669971/what-does-make-significant-difference-of-performance-between-eventlet-and-gevent) seems to indicate that gevent is more performant in general.

I would obviously prefer whichever is most performant, assuming it works on windows. Eventlet is also appealing since it only requires the one library and has websocket support built in.

**Comment by miguelgrinberg** [comment]
You can try the "latency.py" project from [here](https://github.com/miguelgrinberg/python-socketio/tree/master/examples/wsgi) and compare gevent vs eventlet.

Also, note that if you are using Python 3, there is no official websocket support for gevent. There is an unofficial port of gevent-websocket though. But overall gevent-websocket does not seem to be maintained anymore.

**Comment by skortchmark9** [comment]
I did the comparison and didn't see any difference. (They both averaged around 1ms latency)

**Comment by miguelgrinberg** [comment]
I'm guessing you are running client and server on your own computer? If you want a realistic production-like test, you should deploy the server to some host (i.e. ec2, digital ocean, etc.) and measure that way.

You can also try modifying that app to send batches of messages, and measure the total time. That will help magnify smaller differences.

I don't remember exact numbers, but I used to see a slight edge on my eventlet tests when I did this a while ago.
