### ISSUE TITLE
uWebsockets

### ISSUE THREAD

**Issue by hsvlz** [miguelgrinberg/Flask-SocketIO#461]
Hi Miguel,

really awesome project.

Are you planning to integrate a [uWebsockets](https://github.com/uWebSockets/uWebSockets) compatibility? 

It seems like a popular ws replacement on the node.js socket.io server implementation and does not require any change to the higher level abstraction of socket.io.

Keep up the good work!

**Comment by miguelgrinberg** [comment]
uWebsockets is great, but at this point I believe there are no Python bindings. Also, I'm not really sure how much of that performance gain you will be able to take advantage of when you have your own application written in Python, which is several orders of magnitude slower.
