### ISSUE TITLE
Flask-SocketIO server also a client

### ISSUE THREAD

**Issue by lhercot** [miguelgrinberg/Flask-SocketIO#463]
I have a Flask App/Server (Flask-SocketIO, Flask-restful, eventlet) with browser clients.
This works fine.

I am looking now to have this App to also be a SocketIO client from another App that will manage the first server.
I would like to have a socketIO connection with the Flask-SocketIO app as a client to this other SocketIO App (also build with Flask-SocketIO).

I have tried with SocketIO_client but I don't seems to be able to have both working together.
Did you ever build something like this? Is there a functionality in the Flask-SocketIO to make it also a client?

**Comment by jwg4** [comment]
What breaks when you have socketIO_client code in your Flask app which also uses Flask-SocketIO?

**Comment by miguelgrinberg** [comment]
Flask-SocketIO cannot act as a client. You should be able to use SocketIO_Client alongside Flask-SocketIO, so you should add more details on the problems you had integrating the two. But as a side note, I wonder what's the use case to have a public facing Socket.IO server talk to another, non-public facing Socket.IO service. There are more direct and efficient ways to get to server processes to talk than Socket.IO.
