### ISSUE TITLE
Please help, 400 bad request syntax

### ISSUE THREAD

**Issue by aliwo** [miguelgrinberg/Flask-SocketIO#466]
Hello , I learned flask through the 'flask documentation' and your 'microblog post'.
Thanks to you, I became really into elegance and readable approach the flask takes.

I'm trying to connect arduino websocket client to Flask Websocket server.
But when arduino try to handshake, it always fails with same error message.
The header from arduino and the error messages are below.

Content-Type: text/plain
Upgrade: websocket
Connection: Upgrade
Host: 10.1.1.61
Sec-Websocket-Key: 9eYtRDJj/SJ1MDMFsbT22w==
Sec-Websocket-Protocol: 
Sec-Websocket-Version: 13

10.1.1.84 - - [19/May/2017 16:14:26] code 400, message Bad request syntax ('\x87\x00')
10.1.1.84 - - [19/May/2017 16:14:26] " " 400 -

Strange thing is, there is no code sending anything like  '\x87\x00' in client side.

I tried commenting out below part of header, but problem still remains same.
Sec-Websocket-Protocol: 
Sec-Websocket-Version: 13

So when the header looks like this, same error message occurs.
Content-Type: text/plain
Upgrade: websocket
Connection: Upgrade
Host: 10.1.1.61
Sec-Websocket-Key: 9eYtRDJj/SJ1MDMFsbT22w==

I ran out of idea, and my eyes are burning. Could you please help me resolve the problem?

**Comment by miguelgrinberg** [comment]
Flask-SocketIO is not a WebSocket server. It is a Socket.IO server. Socket.IO is a protocol that is built on top of WebSocket, to connect to it you need a Socket.IO client. There is one for C++ that may probably work from Arduino: https://github.com/socketio/socket.io-client-cpp.

**Comment by aliwo** [comment]
OMG... I didn't know that. Many thanks, Mr.miguel!
