### ISSUE TITLE
Deploy problem of flask-socketio server

### ISSUE THREAD

**Issue by AZLisme** [miguelgrinberg/Flask-SocketIO#468]
I need to deploy my application and facing a problem.

My server needs to serve around 10k clients, and according to my benchmark, a single application server can server around 400 clients at most (is this normal? My test server hardware is: I7-4970K, 8 core 16 threads and 16Gb Ram)

I have done some research and I know there are ways to scale up the capacity: 
1. upgrade my server hardware, faster cpu, more ram
1. running more application instance and using a load balancer in front of them

I planned to use nginx as my load balancer, it has ip_hash algorithm that implements sticky session.
**But the problem is** , the ip_hash uses first 3 parts of ip address, eg. 192.168.1, and most of my clients shares the first 3 parts of ip address (from same company or university), and they are all routed to some of the server nodes, it's not balance at all and soon achieve client capacity.

I'm looking for solution to this problem, here is what I think might be helpful:
1. optimize the server code,  improve client capacity. But I'm not sure how much I can improve.
2. change a load balancer that could customize load balance algorithm, and code a new ip_hash
3. client side load balance, eg, client get server list from an api, and choose one using some algorithm, then save it in cookies or local storage, using that server consistently from then on.

Do you have any good suggestion? Thank you verify much.

**Comment by jwg4** [comment]
Nginx has a directive `hash` which allows you to hash some arbitrary other variable(s) to decide which load balanced server to go to. This includes hashing `$remote_addr`, which stores the IP address of the client.

See this section of the docs on load balancing: https://www.nginx.com/resources/admin-guide/load-balancer/#method the docs for this option: http://nginx.org/en/docs/http/ngx_http_upstream_module.html?&_ga=2.52689832.1851518520.1495443645-1594896997.1495443645#hash or this answer: http://stackoverflow.com/a/32519498/1737957

**Comment by miguelgrinberg** [comment]
@AZLisme I have recently been playing with HAProxy, another open source load balancer. It supports several models for sticky sessions. One that I thought was nice is that it assigns a random server to a client when it sends the first request, then adds a cookie with the selected server. That could work well for you, if you are open to use another load balancer.

Regarding the 400 client max, how did you arrive to that number?
