### ISSUE TITLE
What is the default value of max_http_buffer_size?

### ISSUE THREAD

**Issue by renodesper** [miguelgrinberg/Flask-SocketIO#469]
I have a problem when the server is receiving message from client. The console log shows me this kind of message:
`Failed to load resource: the server responded with status 413 (Request Entity Too Large)`

I thought that "maybe" I can increase the size with max_http_buffer_size (CMIIW), but I cannot find any default value to show me how to do it, is it byte or anything.

**Comment by jwg4** [comment]
In the python-engineio source you can see the default value: https://github.com/miguelgrinberg/python-engineio/blob/master/engineio/server.py#L66 (it is also in the docs for python-engineio).

I am not sure that this is your problem though. If it is, are you doing the right thing by sending SocketIO messages of over 100MB from client to server? Perhaps it would be better to use HTTP or another protocol to send these large messages.

**Comment by renodesper** [comment]
My leader thought that this problem maybe related with flask-socketio, I never thought that the value is defined in python-engineio. Anyway, after a few test we found that problem is not related with socketio/flask/python, but with nginx. The devops team has confirmed this.

Thank you for the information @jwg4, I appreciate it.
