### ISSUE TITLE
SocketIO emit not working from celery task

### ISSUE THREAD

**Issue by bigal337** [miguelgrinberg/Flask-SocketIO#472]
Hi,  I have the following function in my main flask app:
```@celery.task
def update_clients(self, *args, **kwargs):
       print(args)
       socketio.emit('statusmsg', 'message')
```
And I can see in the celery debug log that the task is getting called and run successfully, but no emission happens. When I emit with the following function:
```
@app.route('/listener', methods=['POST'])
def listen():
      print(request.data)
      socketio.emit('statusmsg',request.data.decode())
      return redirect(url_for('hello_world'))
```
The emission works fine.
I am starting the flask server with `$ FLASK_APP=hello.py flask run` and the celery worker with `celery worker -A hello.celery --loglevel=DEBUG`

I just need to receive amqp messages from rabbit and emit via socketIO and it is proving really difficult.

**Comment by miguelgrinberg** [comment]
How do you initialize your `SocketIO` class in the Celery worker?

**Comment by bigal337** [comment]
This is all in the same flask python file.
It is initialised in the top of the file like this: 
```
app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
app.config['CELERY_BROKER_URL'] = 'amqp://......'

app.config['CELERY_RESULT_BACKEND'] = 'rpc://'

socketio = SocketIO(app)
celery = Celery(app.name, broker=app.config['CELERY_BROKER_URL'])

if __name__ == '__main__':
    socketio.run(app)
```

**Comment by miguelgrinberg** [comment]
@bigal337 no, that is how you start the Flask server. I'm asking specifically about the Celery worker.

**Comment by bigal337** [comment]
perhaps I do not understand what is going on properly. At the top of the file, I instantiate `socketio` and `celery` objects.

The only celery task I have is at the bottom of the file 
```
@celery.task
def update_clients(self, *args, **kwargs):
       print(args)
       socketio.emit('statusmsg', 'message')
```
Then I start celery from a separate terminal with the `celery worker -A hello.celery --loglevel=DEBUG` command.

Are you suggesting that the celery function does not see the socketio object from the top of the file?

**Comment by miguelgrinberg** [comment]
First of all, when you work with multiple processes you need to use a message queue, which allows the Flask server and the Celery workers to communicate. Second, the `SocketIO` object needs to be instantiated differently on the Celery worker processes. The docs I linked include the details.

**Comment by bigal337** [comment]
Thank you for helping me.
I'm really struggling to figure out the best of doing this. I have a hack working where celery and flask just talk using the python requests module. Are you saying that the proper was to do this would be to pass celery messages to redis (or something else) and have flask receive them from redis?.

**Comment by miguelgrinberg** [comment]
No, no, you got it wrong.

Flask-SocketIO supports Celery workers emitting directly to clients, but to use that feature, you need to configure a message queue, which could be Redis, RabbitMQ, etc. You do not have to do anything with the queue, just have the service running and configured on the Flask and Celery worker sides. If you configure your `SocketIO` object as shown in the docs (different arguments for the Flask and Celery worker processes), then you can just call `socketio.emit()` from the Celery worker and it will just work.

> as a follow-up, is there a way for socketio to receive amqp messages directly without the need for a celery middleman

I don't understand this question. Flask-SocketIO fully manages a channel in your message queue. You do not write or read from this channel directly. All you need to do is have a queue running.

**Comment by bigal337** [comment]
Sorry I guess my followup question was not clear.
I currently have messages from other services going to a rabbit instance. I need to consume these messages and send them out via socketio. So what I meant, is there a way to receive these messages without celery, just using flask-socketIO.

**Comment by miguelgrinberg** [comment]
Ah, okay. The easiest way would be to just receive those messages yourself in the Flask process, and then call `emit()` with the data that you receive in the event.

You can also reverse engineer the contents of the events posted by the Celery worker and post the same thing from other processes. Obviously this is only possible if you have control over the format of these events posted to Rabbit.

**Comment by bigal337** [comment]
I have not found any way to receive amqp messages from flask. Do you have any documentation that you can point me to. (That is why I went down the celery road)

**Comment by miguelgrinberg** [comment]
Flask has nothing to do with receiving messages from a queue. You have to use a Rabbit client for that. Something like https://pypi.python.org/pypi/amqp or https://pypi.python.org/pypi/librabbitmq. Or if you prefer, you can use a higher level library such as Kombu, which is what Flask-SocketIO does: https://pypi.python.org/pypi/kombu.

**Comment by bigal337** [comment]
what I meant by flask, was my flask-socketIO process. Can flask-socketio receive messages from rabbitmq, and emit them to clients with only one process.

The flask-socketio docs pointed me to [this,](http://docs.celeryproject.org/projects/kombu/en/latest/userguide/connections.html?highlight=urls#urls) before but I did not know how to configure it to listen to specific queues. 

I know I can pass in a url as kwarg at the socketio object, but where do I tell it to listen to a certain queue, and where do I put code that handles the incoming message.
```
if __name__ == '__main__':
    socketio.run(app,
                 message_queue='amqp://............')
```
I imagine it would be something like receiving messages from socketIO js clients?:

```
@socketio.on('message')
def handle_message(message):
    print('received message: ' + message)
```

**Comment by miguelgrinberg** [comment]
> what I meant by flask, was my flask-socketIO process. Can flask-socketio receive messages from rabbitmq, and emit them to clients with only one process.

As I said above, you have to receive the message in the Flask-SocketIO process, then call the `socketio.emit()` function with the data that you receive, and that you format according to your needs.

> but I did not know how to configure it to listen to specific queues.

You can't listen to specific queues, that is not the purpose of the message queue support in Flask-SocketIO. As I also said above, Flask-SocketIO manages its own queue.

> I imagine it would be something like receiving messages from socketIO js clients?

I guess someone could build a library that uses a similar syntax to receive messages from a queue, but that is not what Flask-SocketIO was built for. Messages from clients and messages from rabbit queues are completely different, they have nothing in common. Take a look at those packages I recommended, those do what you want, though likely not in a simplified syntax.

**Comment by bigal337** [comment]
@miguelgrinberg, thank you for all of the help. This sort of basic higher level information was fairly difficult for me to understand, Im more of a hardware guy, but its a lot clearer now.

I should be able to get everything working from here on in.

**Comment by miguelgrinberg** [comment]
@chidioguejiofor Try https://github.com/miguelgrinberg/flack.
