### ISSUE TITLE
Is there a way to get the IP address of each client?

### ISSUE THREAD

**Issue by Benguin** [miguelgrinberg/Flask-SocketIO#473]
I'd like a way to be able to grab the IP addresses of clients as they connect or when they send a command, and so far I haven't found a way online; is there a way?

**Comment by miguelgrinberg** [comment]
You can do this in the usual Flask way, using the `request` object. The `request.remote_addr` attribute contains the IP address of the client. But if you are using a reverse proxy, then `remote_addr` is always going to be the address of your proxy. In this case, the [ProxyFix](http://werkzeug.pocoo.org/docs/0.12/contrib/fixers/#werkzeug.contrib.fixers.ProxyFix) middleware may be of help.

**Comment by Benguin** [comment]
Ahh I see. The proxy issue must by why it didn't work when I tried..

Cheers.
