### ISSUE TITLE
Flask-socketIO and SSL, "Invalid HTTP method"

### ISSUE THREAD

**Issue by crennui** [miguelgrinberg/Flask-SocketIO#476]
when I am trying to run my flask app on "https://" I get all the requests like this ... 
this is how I run the server, is there something I am doing wrong ?  
`if __name__ == "__main__":`
    `cer = os.path.dirname(os.path.realpath(__file__))+"/cert.pem"`
    `key = os.path.dirname(os.path.realpath(__file__))+"/key.pem"`
    `socket.run(app, host="0.0.0.0", debug=True, logger=True, keyfile=key, certfile=cer)`

console (example of request):
<socket fileno=776 sock=127.0.0.1:5000 peer=127.0.0.1:64837>: Invalid HTTP method: '\x16\x03\x01\x00\xae\x01\x00\x00\xaa\x03\x03b6^IP?\x0e\xad\x03\x19\xaa~I0\x04`\xf9F\xe7\xdf\x11\xd6M\xbbvH\x90\xe7h\x1c%\xcb\x00\x00\x1cjj\xc0+\xc0/\xc0,\xc00\xcc\xa9\xcc\xa8\xc0\x13\xc0\x14\x00\x9c\x00\x9d\x00/\x005\x00\n'
127.0.0.1 - - [2017-06-02 01:13:55] "

this is how I created the cert and key files: 
"openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365"

but when I am running the server with "http://" it's all ok but not encrypted... :( what should I do ?

**Comment by miguelgrinberg** [comment]
Which async mode are you using? Are you using eventlet or gevent at least?

**Comment by crennui** [comment]
I am using gevent. now I tried to use eventlet with `log_output=True` and all I get are those accept log
example: 
(10856) accepted ('127.0.0.1', 49162)
(10856) accepted ('127.0.0.1', 49163)
but on the web browser I get : 
"This site can’t be reached
127.0.0.1 took too long to respond."
I checked if the key and cer files are good so I tested them with basic `app.run(ssl_context=context)`  (context has the cer and key files) and it worked.

**Comment by miguelgrinberg** [comment]
Not sure what can be the problem, everything works well here.  Here are the steps I followed:

1. created a self-signed cert

        openssl req -x509 -newkey rsa:4096 -nodes -keyout key.pem -out cert.pem -days 365

2. change the `app.run` line in the example in this repo to:

        socketio.run(app, host='0.0.0.0', debug=True, keyfile='key.pem', certfile='cert.pem')

3. run the example with eventlet

I get a valid, obviously unverified connection, and everything seems to work

**Comment by crennui** [comment]
Ohh Thank you. I tried to make a small basic sockeio app only with ssl and it worked (like you did^). 
Than I understood I used a gevent function that ruined something (I dont know what or why).
now it is working... :)

**Comment by Rakin061** [comment]
@miguelgrinberg  
As per your last comment

> 2. change the app.run line in the example in this repo to:
>           socketio.run(app, host='0.0.0.0', debug=True, keyfile='key.pem', certfile='cert.pem')
> 3. run the example with eventlet

Can I do exactly the same thing while using gevent ?

**Comment by miguelgrinberg** [comment]
@Rakin061 No. Read the documentation for instructions on how to run uwsgi + gevent.

**Comment by Rakin061** [comment]
@miguelgrinberg  

My uwsgi+gevent configuration is fine. But I am struggling to add ssl support while running gevent+uwsgi. 
I found some instructions for eventlent. But no help for ssl support while uwsgi+gevent

**Comment by miguelgrinberg** [comment]
I have never tested SSL with uwsgi so I can't guarantee you that it works well, but the documentation does say how to do it: http://uwsgi-docs.readthedocs.io/en/latest/HTTPS.html.
