### ISSUE TITLE
Client for binary data

### ISSUE THREAD

**Issue by jzalger** [miguelgrinberg/Flask-SocketIO#478]
This is a question more than an issue, if there is a better place for it, let me know.
I need to send compressed pickled objects over a websocket and I am looking at using Flask-SocketIO as the server. Are there any recommended SocketIO clients for python that support binary data transfers?

Will there be any issues on the server side?

**Comment by miguelgrinberg** [comment]
The only client I know is https://github.com/invisibleroads/socketIO-client. I believe it supports binary.
