### ISSUE TITLE
Socket IO & Flask Session Keepalive?

### ISSUE THREAD

**Issue by cjnolet** [miguelgrinberg/Flask-SocketIO#479]
I'm somewhat new to flask and to the socket-io flask library so I very well may be doing something wrong. I'm using flask-sessions to keep sessions alive for a period of time like so:

```
@app.before_request
def make_session_permanent():
    print("TEST")
    session.permanent = True
    app.permanent_session_lifetime = timedelta(minutes=30)
```

What I notice is that the socket.io flask library isn't calling "@app.before_request" in the socket url mappings. What ends up happening is that while a user is not making other http requests but there's a live socket going, the user ends up losing their authenticated session and the app is basically rendered useless. 

How do I get around this so that their socket.io session is keeping their normal http cookie session alive?

**Comment by miguelgrinberg** [comment]
The Socket.IO side cannot work with a session cookie, because the WebSocket protocol does not provide a mechanism to set or change cookies. I suggest you implement some sort of background request in JavaScript that runs at regular intervals to keep your session active.
