### ISSUE TITLE
Emit to spesific rooms at celery worker

### ISSUE THREAD

**Issue by fatihsucu** [miguelgrinberg/Flask-SocketIO#483]
Hello everyone, firstly this a question not a bug report.

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/gMXHc.png

I am trying to scale socketio server for optimize cpu usages and io operations. I have wsgi server, socket server, celery workers, redis, rabbitmq at different machines. 

When i use socketio with message_queue option and without any room spesification it works as expected. But when i use the room parameter in emit, client doesn't receive socket events.

Initiated SocketIO instance at celery machine

```
socket = SocketIO(message_queue="redis://***.**.**.**", async_mode='threading')
```

And also flask_socketio `join_room` method can't be use in celery machine cause of it needs flask app. Instead of `join_room` I use 

```
socket.server.enter_room(sid, room, namespace=namespace)
```

for use in celery's socket instance ( like enter_room ) i passed the `sid` variable at every tasks because thought of socket should known which `sid` is making an request.

What am i doing wrong any ideas? I'll appreciate any help.

**Comment by miguelgrinberg** [comment]
The `join_room` function can be used with our without a request context. If you are using it outside of a context, you have to pass the `sid` and `namespace` arguments in addition to the room name. See the documentation for details.

Not sure about the problem with the emits to rooms. It's odd that you are using the `threading` mode, which means you do not get WebSocket support. Have you tried one of the other async modes? Also, you may want to look at my [Flack](https://github.com/miguelgrinberg/flack) application repository, as this is an app that also uses a wsgi server plus celery workers.

**Comment by fatihsucu** [comment]
```
def join_room(room, sid=None, namespace=None):
    """Join a room.
    This function puts the user in a room, under the current namespace. The
    user and the namespace are obtained from the event context. This is a
    function that can only be called from a SocketIO event handler. Example::
        @socketio.on('join')
        def on_join(data):
            username = session['username']
            room = data['room']
            join_room(room)
            send(username + ' has entered the room.', room=room)
    :param room: The name of the room to join.
    :param sid: The session id of the client. If not provided, the client is
                obtained from the request context.
    :param namespace: The namespace for the room. If not provided, the
                      namespace is obtained from the request context.
    """
    socketio = flask.current_app.extensions['socketio']
    sid = sid or flask.request.sid
    namespace = namespace or flask.request.namespace
    socketio.server.enter_room(sid, room, namespace=namespace)
```

This line needs flask app for join room. Otherwise it raises KeyError as expected.  
```
socketio = flask.current_app.extensions['socketio']
```

> Have you tried one of the other async modes? 

Yes i did. I used eventlet too but nothing changed. 

> Also, you may want to look at my Flack application repository, as this is an app that also uses a wsgi server plus celery workers.

Yes. I watched that tutorial too. Flask at Scale. Great Work! BTW. I use celery at wsgi server. It works like a charm.

My problem must related to rooms. When i use it with broadcast it works but when i pass room variable at emit it stops.

**Comment by miguelgrinberg** [comment]
> This line needs flask app for join room. Otherwise it raises KeyError as expected.

Sure, but that's an app context, not a request context. Just do:

    with app.app_context():
        join_room(...)

> but when i pass room variable at emit it stops.

What do you mean by "it stops"? Do you get any errors?

**Comment by fatihsucu** [comment]
So i understand that even if i use SocketIO just for external emit i need flask app context. I thought i can just use like without any flask application.

```
socketio = SocketIO(message_queue='redis://')
socketio.emit('my event', {'data': 'foo'}, namespace='/test')
```

> What do you mean by "it stops"? Do you get any errors?

No. It doesn't raise any exception or errors. Just client doesn't receive events. I think i am missing some critical point communication between nodes.

**Comment by miguelgrinberg** [comment]
The `SocketIO` is a Flask extension. I never intended for it to work without a Flask app instance. If you don't want to use Flask, then use the python-socketio package directly, and then there is no association with Flask.

Regarding the room emits, did you generate logging from the server and client sides, to see where is the disconnect happening?

**Comment by fatihsucu** [comment]
> The SocketIO is a Flask extension. I never intended for it to work without a Flask app instance. If you don't want to use Flask, then use the python-socketio package directly, and then there is no association with Flask.

I get it. I use flask app and flask_socketio server side. Just tried SocketIO instance in celery machine without flask app instance because actually celery has nothing to do with flask app instance. 

When disconnect received i get this error. 
```
Unexpected error "[Errno 107] Transport endpoint is not connected", closing connection
```

**Comment by daniel329paul** [comment]
even im having same issue...when i broadcast the message it works. But when i mention room and emit, the client which is joined from serverside by passing sid and namespace explicitly is not getting those messages.

**Comment by mayuresh82** [comment]
how do you get the sid when outside of a request context  ?

**Comment by daniel329paul** [comment]
> how do you get the sid when outside of a request context ?

took sid from frontend (<socket_variable_name>.id) and passed to backend flask

**Comment by teojunjie** [comment]
Hi I am facing the same problem as well! Looking for any solutions if possible! Has the keyword argument "room" been changed to "to"

**Comment by miguelgrinberg** [comment]
> Has the keyword argument "room" been changed to "to"

Yes, but `room` is still supported.
