### ISSUE TITLE
No python error if calling invalid function in an event callback

### ISSUE THREAD

**Issue by mrechte** [miguelgrinberg/Flask-SocketIO#484]
Hi. Should one call an invalid function from a event callback, no Python error is caught in the server log.

`@socketio.on('my_event', namespace='/hid')`
`def handle_my_custom_event(json):`
` \t  abcefgh()`

**Comment by miguelgrinberg** [comment]
Yes, I am aware that exceptions are sometimes not reported correctly, and I'm working on a fix. Thanks!

**Comment by miguelgrinberg** [comment]
@mrechte if you can, please install python-engine directly from git, so that you get the current version of the fix that I addresses this. Use `pip install https://github.com/miguelgrinberg/python-engineio/archive/master.zip

**Comment by mrechte** [comment]
Thanks for your prompt reaction.
