### ISSUE TITLE
Generic error

### ISSUE THREAD

**Issue by italomaia** [miguelgrinberg/Flask-SocketIO#485]
If there is an error with the application, flask run will show a generic error saying it could not find the application. I believe this error should appear only if the application instance is not there. Not if there is an error of other sort.

**Comment by italomaia** [comment]
By generic error, I mean: Could not locate Flask application

**Comment by miguelgrinberg** [comment]
Sorry, but I don't understand exactly what you mean. Are you getting an error?

**Comment by italomaia** [comment]
I had an error in my application while creating my app instance. The thing is, when running "flask run", the error I was getting was that socketio could not find the app instance. This was actually happening, but the real error, that made it impossible to find the app instance was being clouded. The issue here is that "flask run" should only state "Could not locate Flask application" if there was no error but the missing app instance.

**Comment by miguelgrinberg** [comment]
Okay, I think I understand, but would be helpful to see an actual example, to help me see where the problem is.
