### ISSUE TITLE
message delay

### ISSUE THREAD

**Issue by javaxiu** [miguelgrinberg/Flask-SocketIO#491]
i got some msg sending delay
flask side:
```
def notify_update():
    while True:
        socketio.emit(update_000010000027, str(time.time()), namespace='/notifychannel')
        time.sleep(2)


start_new_thread(notify_update, ())
```
frontend:
```
const socket = io('http://localhost:8081/notifychan')
  socket.on('update_000010000027', function () {
    console.log(arguments)
  })
```
it was supposed to log every 2 seconds in front-end, right? but i got every 20+ seconds  log 10 lines

buf if i use javascript back-end,  the same html/js code show different behaviors which i wanted: 2 seconds log 1 line
```
const app = require('express')();
const http = require('http').Server(app);
const io = require('socket.io')(http);

http.listen(8081);

setInterval(function () {
    io.emit('update_000010000027', +new Date)
}, 2000)
```

**Comment by miguelgrinberg** [comment]
You can't use `time.sleep()` in an asynchronous server. If you are using eventlet, you may want to switch to `eventlet.sleep()`. Likewise, if you are using gevent, use `gevent.sleep()`.

**Comment by javaxiu** [comment]
understood ,thks
