### ISSUE TITLE
functions with @socketio.on decorators aren't being triggered

### ISSUE THREAD

**Issue by shorstman** [miguelgrinberg/Flask-SocketIO#495]
I'm trying to build a webapp which uses socketIO with flask. Right now I'm just trying to get the connect event to work before I move on to more complex events, but it would seem that the function associated with the socketio.on('connect') decorator isn't being triggered for some reason. Here is (I think) the relevant code. I haven't worked with socketIO before so let me know if there's any more necessary information.

**run.py**

    from app import app
    from flask_socketio import SocketIO, emit
    
    socketio = SocketIO(app)
    socketio.run(app, debug=True)

**views.py**

    from app import app
    from flask import render_template, request, session, redirect, url_for
    from flask_socketio import SocketIO, emit
    
    socketio = SocketIO(app, engineio_logger=True)
    
    #Some view functions with route decorators
    
    @socketio.on('connect', namespace='/admin')
    def test_connect():
        print("connected")
        emit('my_response')

**Relevant JavaScript**

    var namespace = "/admin";
    var socket = io.connect(location.protocol + '//' + document.domain + ':' + location.port + namespace);
    
      socket.on('my_response', function(msg) {
          console.log("Response received");
      });

**Flask console output when a user opens the page containing the javascript**

    127.0.0.1 - - [04/Jul/2017 16:14:50] "GET /admin HTTP/1.1" 200 -
    ee299cde413b438caa7b61b53e85d8ad: Sending packet OPEN data {'sid': 'ee299cde413b438caa7b61b53e85d8ad', 'upgrades': [], 'pingTimeout': 60000, 'pingInterval': 25000}
    ee299cde413b438caa7b61b53e85d8ad: Sending packet MESSAGE data 0
    127.0.0.1 - - [04/Jul/2017 16:14:50] "GET /socket.io/?EIO=3&transport=polling&t=1499199290373-0 HTTP/1.1" 200 -
    ee299cde413b438caa7b61b53e85d8ad: Received packet MESSAGE data 0/admin
    ee299cde413b438caa7b61b53e85d8ad: Sending packet MESSAGE data 0/admin
    127.0.0.1 - - [04/Jul/2017 16:14:50] "POST /socket.io/?EIO=3&transport=polling&t=1499199290430-1&sid=ee299cde413b438caa7b61b53e85d8ad HTTP/1.1" 200 -
    127.0.0.1 - - [04/Jul/2017 16:14:50] "GET /socket.io/?EIO=3&transport=polling&t=1499199290430-2&sid=ee299cde413b438caa7b61b53e85d8ad HTTP/1.1" 200 -

The javascript console is empty when I open the page. I'm not sure why the event isn't being triggered. Any help is appreciated.

**Comment by miguelgrinberg** [comment]
I think the problem is that `views.py` does not get imported, so the connect event handler does not get registered. can you import views in `run.py` and see if that addresses it?

**Comment by shorstman** [comment]
What would be the syntax for importing views.py? My file structure is the same as in your flask megatutorial.

**Comment by miguelgrinberg** [comment]
Try `from app import views`.

**Comment by shorstman** [comment]
As far as I can tell that didn't change anything.

**Comment by miguelgrinberg** [comment]
Well, I can't really help you without seeing the code that you are using. Can you share the whole project?

**Comment by shorstman** [comment]
I would rather not post the full code publicly. Could I send it to you directly somehow? I appreciate the help.

**Comment by miguelgrinberg** [comment]
Sure. Not sure how big is the project, would email work? Use first.last @ gmail.

**Comment by shorstman** [comment]
Did you receive my email? I sent it last Friday. There is no rush but I want to make sure it was sent to the correct email address

**Comment by miguelgrinberg** [comment]
No, sorry, I don't think I have it. What email address did you send it from? Maybe it went to spam.

**Comment by shorstman** [comment]
It should have come from horstman.s@husky.neu.edu

**Comment by miguelgrinberg** [comment]
No, I don't seem to have it. Did you send it to `miguel.grinberg@gmail.com`?

**Comment by shorstman** [comment]
I did, it came up with your google plus account as well. I have just re-forwarded the email to you again. Let me know if you recei
ve it.

**Comment by miguelgrinberg** [comment]
I did get it this time, thanks.

I honestly can't see anything wrong at first sight. What else do I need to be able to run the project?

**Comment by shorstman** [comment]
I thought you had everything actually but it appears I didn't send a few files I needed to. I am about to send them.

**Comment by shorstman** [comment]
Miguel helped me find the issue, I was accidentally creating two separate socketio objects. I changed my run.py to look like this:

```
from app import app

app.config.from_object("config")

from app import views
from flask_socketio import SocketIO, emit

views.socketio.run(app, debug=True)
```
The last line is the important change, I am now using the socketio object from the views file rather than creating two separate ones.

**Comment by volt-l18** [comment]
same issue i am haveing

**Comment by volt-l18** [comment]
i am facing the same issue i tried to make just one object of socketio and importing it everywhere i use socketio but that didn't seem to fix the issue either :(

**Comment by miguelgrinberg** [comment]
@volt-l18 I think you are not initializing the SocketIO extension, you just created the object. See the `init_app()` function in the documentation. This is standard for most Flask extensions.

**Comment by volt-l18** [comment]
thank you very much i wasted like 2 hrs searching thought issues now it work like a charm thank you!!!

**Comment by volt-l18** [comment]
thank you very much i wasted like 2 hrs searching thought issues now it work like a charm thank you!!! also their is this somekind of bug where when ever i start the server and input details its says method not allowed but works fine after a restart nothing changed in code ... or dunno maybe its only on my system
