### ISSUE TITLE
how to manage client  on server

### ISSUE THREAD

**Issue by includedhj** [miguelgrinberg/Flask-SocketIO#496]
i want manage all client on server ,such as disconnect client from server,send msg to one client.
i don't know how to do it ,thanks

**Comment by miguelgrinberg** [comment]
Did you study the example application in this repository? It does what you say.

**Comment by qwIvan** [comment]
Same question, for example, how to send "Hi" to specify user per hour?

**Comment by miguelgrinberg** [comment]
Here is the part of the example app that sends messages on a schedule: https://github.com/miguelgrinberg/Flask-SocketIO/blob/master/example/app.py#L17-L25

**Comment by qwIvan** [comment]
Another example, how to send message to all female user per hour at the same time.

**Comment by qwIvan** [comment]
Where can I find the users list?

**Comment by includedhj** [comment]
i have read this example,but can't resolve my problem.
 like this:  in backgroud thread ,server send  message to every user one by one.
  how to get user list or user socket handle?thx for your help

**Comment by miguelgrinberg** [comment]
The list of users is not available, because Flask-SocketIO is a distributed server, where each server holds only a partial state. You have to maintain a user list on your own application.
