### ISSUE TITLE
test_client method connecto hangs during test.

### ISSUE THREAD

**Issue by Draqun** [miguelgrinberg/Flask-SocketIO#497]
I have some problem in test with socketio. Test client method connect hangs and it stops my tests.

Module with app
```
app = Flask(__name__)
socketio = SocketIO(app, async_mode='eventlet')
Bootstrap(app)
```

My test
```
        mq = posix_ipc.MessageQueue("/AT_QUEUE", flags=posix_ipc.O_CREAT)
        (...)
        tc = socketio.test_client(app)
        tc.connect(namespace) # Place where app hangs
        posix_ipc_signals.send_messages()
        received_json = tc.get_received(namespace)
        tc.disconnect(namespace)
```

There is some reason why it hangs?

Where namespace is not equal with used in app there app ("/at") then test is ok, but when namespace is equal "/at" than it hangs. Any ideas?

**Comment by Draqun** [comment]
OK I saw comment

```
"""Note that it is usually not necessary to explicitly call this method,
        since a connection is automatically established when an instance of
        this class is created. An example where it this method would be useful
        is when the application accepts multiple namespace connections."""
```

I removed line with connect but method get_received does return empty list so I think problem is somewhere else.

**Comment by miguelgrinberg** [comment]
Do you know exactly where it hangs? Do you have a connect handler in your application? Could it be hanging somewhere in there?

**Comment by Draqun** [comment]
It always hangs on connect method. I don't know where exactly in this method.

**Comment by miguelgrinberg** [comment]
Can you add print statements, for example, so that you can pin point where it is hanging?

**Comment by Draqun** [comment]
```
(demo-app-venv) draqun@draqun-ubuntu-mate-machine:~/PycharmProjects/demo-app$ python -m unittest
..It hangs here! :)
> /home/draqun/PycharmProjects/demo-app/tests/demo_app_tests/posix_ipc_signals.py(38)test_for_send_messages()
-> tc.connect(namespace)
(Pdb) l
 33  	
 34  	        mq.send(message)
 35  	        tc = socketio.test_client(app)
 36  	        print("It hangs here! :)")
 37  	        import pdb; pdb.set_trace()
 38  ->	        tc.connect(namespace)
 39  	        posix_ipc_signals.send_messages(namespace)
 40  	        received_json = tc.get_received(namespace)
 41  	        tc.disconnect(namespace)
 42  	
 43  	        self.assertIsNotNone(received_json)
(Pdb) n

```

It is really weird, because when I run only this test not all scope there all is fine.

**Comment by miguelgrinberg** [comment]
Do you have an `@on('connect')` handler? Can you check if that gets invoked? What we really need to find out is what happens in the `connect()` function, how far along things progress until the hang.

**Comment by Draqun** [comment]
I have something like this
```
class AtNamespase(Namespace):
    def on_connect(self):
        try:
            rq.send("ATI 1")
            rq.send("ATI 176")
            rq.send("AT+CEER")
        except SignalError:
            pass

socketio.on_namespace(AtNamespase("/at"))
```

**Comment by miguelgrinberg** [comment]
Does your `on_connect` function get called? Did you try adding print statements there to see if the first `rq.send()` call is hanging?

**Comment by Draqun** [comment]
You have right. rq.send hanging my app.

Thanks a lot.

**Comment by Draqun** [comment]
I moved try except body to function and mock them in test.

Thank you for help!
Best Regards.
Draqun
