### ISSUE TITLE
Add timeout capabilities to emit and send

### ISSUE THREAD

**Issue by jadielam** [miguelgrinberg/Flask-SocketIO#498]
Ability to call emit or send with a timeout parameter and a callback function that generates the data to be sent at the timeout resolution time.

**Comment by miguelgrinberg** [comment]
Do you mean to have a function called at fixed intervals? What would be the benefit versus implementing this in straight Python? Maybe I need to see some pseudo-code to understand better what you are trying to achieve.

**Comment by jadielam** [comment]
Thanks for the quick answer. For example, right now when I want to emit a message, I do the following:

`emit('event name', 'message')`

Something like this might could be useful:

`emit('event name', n, callback)`

where `n` is the number of seconds to wait before emitting the event, and callback is a function that is called at emission time to generate the data to emit.

**Comment by jadielam** [comment]
By the way, would you recommend using Celery for something like that?

**Comment by miguelgrinberg** [comment]
This is easy to implement directly in Python, so I'm closing this.
