### ISSUE TITLE
Don't get information about broken connection

### ISSUE THREAD

**Issue by trojek** [miguelgrinberg/Flask-SocketIO#499]
I have code as follows:
```
app = Flask(__name__)
socketio = SocketIO(app, heartbeat_interval=4, heartbeat_timeout=10, engineio_logger=True)
.....
@socketio.on('connect')
def on_connect():
    print("Client connected")

@socketio.on('disconnect')
def on_disconnect():
    print("Client disconnected")
```

When a client(JS) connects to my server I get the information "Client connected". When I lost connection (due to problems with a network) I don't get information: "Client disconnected".
How can I handle the situation when the client disconnects? I try to set heartbeats interval and timeout, but even if I wait for 10 minutes I don't get information that client disconnects.

**Comment by miguelgrinberg** [comment]
Are you using long-polling or websocket? For long-polling, client disconnections take some time to be detected, so you'll need to wait some time and eventually you will get the disconnect callback. For websocket clients the disconnection is detected immediately.

**Comment by trojek** [comment]
I changed the service to eventlet and now it works. I set the timeout to 10 seconds, but it takes about 50 seconds, what is strange for me.
On the client side, I use https://socket.io/. I don't know if is uses long polling or WebSockets but I suppose that WS.
I have also another problem and maybe there are connected. When I set ip and port (e.g. `socketio.run(app, host='0.0.0.0', port=5040)`) i starts on 127.0.0.1, maybe it "dont see" parameters from SocketIO constructor.

**Comment by trojek** [comment]
Miguel, do you know why "SocketIO" don't take into account heartbeat_interval=4, heartbeat_timeout=10 parameters? It takes 60 seconds to display information that client is disconnected.

**Comment by miguelgrinberg** [comment]
The options are called `ping_interval` and `ping_timeout`. It's not a good idea to change those to lower values, as that increases the ping traffic. Your server is going to be busy just from managing pings.

If you want your client disconnects to be detected immediately, then make sure they connect over WebSocket instead of long-polling.

**Comment by trojek** [comment]
I try to set ping_interval and ping_timeout. It works as I expected. 

How can I switch the connection from long-polling to WebSocket?

**Comment by miguelgrinberg** [comment]
Use eventlet, make sure the server is configured to allow transport upgrades (the default), and also make sure your clients support WebSocket and do not prevent transport upgrades either.

**Comment by trojek** [comment]
I use eventlet==0.21.0. I don't change anything in the server configuration. As I client I use JS socket.io so it should support WebSocket. How can I prevent transport upgrades?

**Comment by miguelgrinberg** [comment]
You can check if clients connect through WebSocket if you add server logging (add `engineio_logger=True` to your `SocketIO()` constructor. Somewhere in the logs you should see `upgrade to WebSocket successful` if the client was able to connect through WebSocket. If you don't see that, and instead see `upgrade to WebSocket failed` then we need to investigate why the upgrade does not work for your client.

Maybe I should ask what is it that you are testing. How is the connection broken? Typically if the client disconnects by closing the browser window or tab, the server immediately detects that on a WebSocket connection. Is your network problem of a different kind?

**Comment by trojek** [comment]
I checked in logs and I get: `d584fc4a68f4464889741c7ebe1b48db: Upgrade to websocket successful`
When I close the browser I instantly get information about the disconnect, but when I turn off the WiFi (server is connected to a router, and the client is also connected to the same router) I get information that client was disconnected after time set in `ping_timeout`.

**Comment by miguelgrinberg** [comment]
Ah, I see. A network disconnection is immediately reported to the other side, but when you disable wi-fi that does not translate into a disconnection. If the code is reading from a socket at that time, that read is not interrupted if the wi-fi goes away. For that reason the timeouts are the only way to detect those problems and break the connection.

So yes, I don't really have a solution for this specific case of losing the wi-fi.

**Comment by trojek** [comment]
Thank you for an explanation. Can you estimate how many ping pers seconds could cause problems with the connection (server stability)?

**Comment by miguelgrinberg** [comment]
No, I can't. It depends on a lot of variables. How many clients you have, the CPU/RAM of your server, how many server process you run, how much traffic your Socket.IO events generate, etc.

**Comment by TheJKFever** [comment]
> So yes, I don't really have a solution for this specific case of losing the wi-fi.

@miguelgrinberg, If you force using WebSocket and don't allow long-polling, do you know if losing wi-fi will immediately be detected?

**Comment by miguelgrinberg** [comment]
@TheJKFever That did not make a different back when I tested this.
