### ISSUE TITLE
dynamic namespacing

### ISSUE THREAD

**Issue by matdrapeau** [miguelgrinberg/Flask-SocketIO#5]
Is it possible to have dynamic namespacing on the client side and catch some part of it as a variable on the backend?

Client declares the namespace `/job/1` and the server has something like `/job/{id}` where the `id` is a variable?

**Comment by oskarsari** [comment]
Apologize commenting on such an old issue, but since dynamic namespaces side[are now supported in Socket.IO](https://socket.io/docs/v3/namespaces/index.html#Dynamic-namespaces), are there plans to support them on python as well?
