### ISSUE TITLE
"Type Error: Non UTF-8" whenever I enable debug

### ISSUE THREAD

**Issue by k33k00** [miguelgrinberg/Flask-SocketIO#502]
Find the offending code below. I feel like its a virtual env issue but honestly no idea. It works totally fine when I remove the debug option

```
from flask import Flask
from flask_socketio import SocketIO

def main():
    pass

app = Flask(__name__)
socketio = SocketIO(app)



if __name__ == "__main__" or __name__ == 'app.run':
    socketio.run(app, debug=True)
```

and the full error message reads

```
  File "C:\Users\K33K00\.virtualenvs\app\Scripts\app.exe", line 1
SyntaxError: Non-UTF-8 code starting with '\x90' in file C:\Users\K33K00\.virtualenvs\app\Scripts\app.exe on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

>python 3.6
>windows 10 64bit

Stuff I've tried
---------------

- consoles
   - Cmder/cmd
   - git bash
   - powershell

activating Active code page: 65001 ( ` chcp 65001  `)

okay so it seems to work if i run like this `python app/run.py` so now I don't know who's problem it is...

**Comment by miguelgrinberg** [comment]
What is `app.exe`? Is that an entry point defined by your application?

**Comment by k33k00** [comment]
yep, my entry points look like this,
```
    entry_points={
        'console_scripts': [
            'app=app.run:main'
        ]
    },
```

when I pip install my own script it generates the exe inside the environment. I think it's just the way windows does its pip/console_scripts magic.

To be honest I've reverted back to calling it via `python app/run.py` and it all is good in the world
