### ISSUE TITLE
Issue with creating a self-signed certificate.

### ISSUE THREAD

**Issue by akinlabiceo** [miguelgrinberg/Flask-SocketIO#503]
Am trying to use GoogleMaps API and I need a secure server (SSL) to enable it work. I have followed your tutorial [here](https://blog.miguelgrinberg.com/post/running-your-flask-application-over-https) and I keep getting this error

`TypeError: server() got an unexpected keyword argument 'ssl_context'`

`from flask import Flask, render_template, url_for, request, redirect, session
from flask_socketio import SocketIO, emit

app = Flask(__name__)

socketio = SocketIO(app, async_mode='eventlet')
thread = None

port = os.getenv('PORT', '5000')
if __name__ == "__main__":
	#app.run(host='0.0.0.0', port=int(port), debug=True)
	socketio.run(app, host='0.0.0.0', port=int(port), ssl_context=('cert.pem', 'key.pem'), debug=True)`

I am using a Mac OS for development, please help!

**Comment by miguelgrinberg** [comment]
@akinlabiceo you are using eventlet. The `ssl_context` option applies to the Flask development server only, not to eventlet or gevent. For eventlet you have to pass the `keyfile` and `certfile` options.

**Comment by akinlabiceo** [comment]
Thank you so much for the answer.

However I have followed your instruction and am getting this error

`SSLError: [SSL] PEM lib (_ssl.c:2718)`

the full terminal output looks like this
`Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/akinlabiajelabi/Documents/2017/projects/casba/venv/lib/python2.7/site-packages/flask_socketio/__init__.py", line 503, in run_server
    **ssl_params)
  File "/Users/akinlabiajelabi/Documents/2017/projects/casba/venv/lib/python2.7/site-packages/eventlet/convenience.py", line 126, in wrap_ssl
    return wrap_ssl_impl(sock, *a, **kw)
  File "/Users/akinlabiajelabi/Documents/2017/projects/casba/venv/lib/python2.7/site-packages/eventlet/green/ssl.py", line 379, in wrap_socket
    return GreenSSLSocket(sock, *a, **kw)
  File "/Users/akinlabiajelabi/Documents/2017/projects/casba/venv/lib/python2.7/site-packages/eventlet/green/ssl.py", line 68, in __init__
    ca_certs, do_handshake_on_connect and six.PY2, *args, **kw)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 554, in __init__
    self._context.load_cert_chain(certfile, keyfile)`

I have tried to apply the patch

`import eventlet
eventlet.monkey_patch()`


Please help me once again 😓

**Comment by miguelgrinberg** [comment]
I think this is either an expired cert, or else, the key does not match the cert. See https://stackoverflow.com/questions/30109449/what-does-sslerror-ssl-pem-lib-ssl-c2532-mean-using-the-python-ssl-libr.

**Comment by akinlabiceo** [comment]
I do not think the key is expired as I self-signed it on my computer... 

I was able to get past the error by wrapping the socket.io server like this

`eventlet.wrap_ssl(socketio.run(app, host='0.0.0.0', port=int(port), debug=True), certfile="server.cer", keyfile="server.key")`

But the app is still served through http

`(venv) Akinlabis-MacBook-Pro-2:3 akinlabiajelabi$ python app.py
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 235-126-940
(9262) wsgi starting up on http://0.0.0.0:5000/`

**Comment by miguelgrinberg** [comment]
@akinlabiceo the call to `eventlet.wrap_ssl` happens inside the `socketio.run()` function. You may want to add prints [here](https://github.com/miguelgrinberg/Flask-SocketIO/blob/master/flask_socketio/__init__.py#L502-L503) to ensure the correct arguments for SSL are being passed.

**Comment by miguelgrinberg** [comment]
Please reopen if you still need my help with this issue.
