### ISSUE TITLE
'emit' emits over message_queue though targeting only current sid

### ISSUE THREAD

**Issue by hsvlz** [miguelgrinberg/Flask-SocketIO#504]
Hi Miguel,

When emit does not receive arguments related to broadcast or room, the emit is solely directed to a user connected to the current server. For instance:
```
@socketio.on('my_ping', namespace='/test')
def ping_pong():
    emit('my_pong')
```

Therefore, in this specific case of emit, why is the event sent to the message_queue?

`1) "message"
2) "flask-socketio"
3) "(dp0\nS'skip_sid'\np1\nNsS'room'\np2\nS'654df1379a534fd7abdb45d8526415b1'\np3\nsS'namespace'\np4\nS'/test'\np5\nsS'event'\np6\nS'my_pong'\np7\nsS'callback'\np8\nNsS'data'\np9\nNsS'method'\np10\nS'emit'\np11\ns."`

as the sid is guaranteed to be located from the current server?

Thanks,

**Comment by miguelgrinberg** [comment]
Yes, I agree. The python-socketio dependency does not currently have the concept of sending to one user, it just knows to send to a room or to all users. This was already reported in https://github.com/miguelgrinberg/python-socketio/issues/82 and I have it in my list of improvements for the near future.

**Comment by hsvlz** [comment]
Could you please have a look at [PR 505](https://github.com/miguelgrinberg/Flask-SocketIO/pull/505) that would expose ignore_queue argument to the user, so one can chose to skip the backend when needed?
This could be augmented in the future with more subtle behaviors (i.e no room and no broadcast means ignore_queue=True).

Thanks!

**Comment by miguelgrinberg** [comment]
Yes, this is a good interim solution before I get to address this in a better way. Thanks!
