### ISSUE TITLE
Question: Setting a customized sid

### ISSUE THREAD

**Issue by Maytrovato** [miguelgrinberg/Flask-SocketIO#506]
Hi everyone and community of flask_socketio ! random coder here. 

I have this question, can I set a customized sid from the client? or is it possible to change it from the server?

`var socket = io.connect('http://localhost:5010/mynamespace?sid=idfromuser');`

btw I love your work with flask_socketio ((:

**Comment by miguelgrinberg** [comment]
No, the session id is generated by the server. Consider the case of a user that is holding two independent sessions with the server, those need to be different. Using the user id for this does not work.

**Comment by Maytrovato** [comment]
Alright, thanks for the answer, Miguel. I'm closing the issue.
