### ISSUE TITLE
Autoreload not working with threads

### ISSUE THREAD

**Issue by taseppa** [miguelgrinberg/Flask-SocketIO#509]
I have a flask application with a long running background thread. I'm running the app in debug mode with autoreload and whenever i make a change I get this error:

```
 * Detected change in '/home/murokki/Tinderify/backend/server.py', reloading
Exception in thread Thread-2 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/local/lib/python2.7/dist-packages/watchdog/observers/api.py", line 200, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'
```

If i comment out the thread creation the problem disappears. Though I tried to create a test application with a thread that only prints "hello" in a loop and I couldn't reproduce the problem. So maybe what happens in the thread is relevant but based on the error message I'm quite clueless.

**Comment by miguelgrinberg** [comment]
Are you using eventlet or gevent in your application? Not sure if watchdog is compatible with those, try uninstalling that package so that Flask uses a polling mechanism to detect file changes.

**Comment by taseppa** [comment]
That solved the problem, thanks!
