### ISSUE TITLE
test_client.get_received() always empty

### ISSUE THREAD

**Issue by egorf** [miguelgrinberg/Flask-SocketIO#510]
Hello,

I've been trying to set up unit tests for my app using pytest. Below is a sample of my first draft. The problem is, whatever I do, the `test_client.get_received()` always returns an empty list. 

`create_app` adds a load of events to both app and socketio. However, they don't seem to be executed. create_app returns a reference to the app and the socketio object used for setting event handlers. The app works :) Could you tell me what is wrong with my setup?

```
import os
import pytest

from .context import my_app
from my_app.app import create_app

@pytest.fixture
def app(request):
    # create the app in test mode
    os.environ["FLASK_CONFIG"] = "testing"
    app, socketio = create_app()

    with app.app_context():
        yield app, socketio


@pytest.fixture
def client(request, app):
    app, _ = app
    client = app.test_client()

    def teardown():
        print("Teardown!")

    request.addfinalizer(teardown)
    return client


@pytest.fixture
def socketio_client(request, app):
    app, socketio = app
    client = socketio.test_client(app)

    def teardown():
        print("SocketIO teardown")

    request.addfinalizer(teardown)
    return client


def test_index(client, app):
    index = client.get('/')
    assert index


def test_event(socketio_client):
    socketio_client.emit("my event")
    assert socketio_client.get_received()
```

**Comment by egorf** [comment]
Ok, never mind, I've figured it out. 

For those that run into the same problem:

You need to stop pytest from recreating fixtures, that can be fixed by initializing the fixture with a different scope:

`@pytest.fixture(scope='session')`

However, the root cause of this is probably in the blueprints. When running `create_app` for the second time in the same process environment, not all imports are coming through and `socketio` does not get its handlers the second time. You can use `reload` if you must rerun `create_app`, for parametrizing app creation.

**Comment by julianYaman** [comment]
Hello, do you have a link or any page where I could see the code from your main app application?

I would like to see how I can make pytests with my application (when you want to know what I´m talking about, please check out my repository where I´m creating a python application to show the bitcoin price)
