### ISSUE TITLE
Question: Issue with socket connections being closed and emitting to a user's channel

### ISSUE THREAD

**Issue by ulmentflam** [miguelgrinberg/Flask-SocketIO#512]
Quick rundown on my use case: 
   I am using Flask-SocketIO as the backing for a messaging client that connects using socket io libraries on iOS and Android. I allow multiple devices to connect to the socket server and receive messages emitted on the channel for that particular user. My server api also emits messages to the socket server via api request. The socket servers are deployed in containers in docker-cloud and are individually run using `uwsgi --http :5000 --gevent 1000 --gevent-monkey-patch --http-websockets --master --wsgi-file subscriber/app.py --callable app`
app being my socket application that has connect functions for two namespaces. The namespace that I am mainly having an issue with is `/messages`. Which is initialized as follows, 
``` Python
from flask import Flask, render_template, session, request
from flask_socketio import (SocketIO, emit, join_room, leave_room, close_room, rooms, disconnect)
from flask_sqlalchemy import SQLAlchemy
async_mode = None

app = Flask(__name__)
app.config['SECRET_KEY'] = ***
app.config['SQLALCHEMY_DATABASE_URI'] = ***
db = SQLAlchemy(app)

socketio = SocketIO(app, message_queue=RABBITMQ_URL async_mode=async_mode)
thread = None

@socketio.on('connect', namespace='/messages')
def connect_handler():
    emit('my_response', {'data': 'Connected', 'count': 0})
    try:
        # Authentication 
        if not authenticated:
            disconnect()
        # Load user
        join_room(unique_user_id)
       # Load Users previous messages.
        for message in messages:
            emit('message', json.dumps(message_metadata), namespace='/messages', room=unique_user_id)
    except (TypeError, ValueError) as e:
        disconnect()
``` 

I also emit to the socket server from my api as follows:
```Python
from flask_socketio import SocketIO
socket_client = SocketIO(message_queue=RABBITMQ_URL)

from package import socket_client

@api_function_deceroator()
def post_function():
            # Database writes within post function
            socket_client.emit('message', json.dumps(message_metadata), namespace='/messages', room=unique_user_id)

```

The issue I am running into is as follows:
   On run the clients are able to connect to the sockets without any issues initially. However over time the logs fill with this error:
```
[subscribe-1]2017-07-26T15:37:16.285601334Z Wed Jul 26 15:37:16 2017 - uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 419] during GET /socket.io/?transport=websocket&token=*** (***)
[subscribe-1]2017-07-26T15:37:16.285789465Z [2017-07-26 15:37:16,285]	[socket:_websocket_handler:200]INFO	: 61cc91e67239491bbca5640173396e04: Unexpected error "unable to send websocket message", closing connection
[subscribe-1]2017-07-26T15:37:16.286279703Z [pid: 13|app: 0|req: 1719/1707] *** () {38 vars in 758 bytes} [Wed Jul 26 15:36:49 2017] GET /socket.io/?transport=websocket&token==***> generated 206 bytes in 27094 msecs (HTTP/1.1 101) 4 headers in 190 bytes (2 switches on core 980)
[subscribe-1]2017-07-26T15:37:16.286796803Z Traceback (most recent call last):
[subscribe-1]2017-07-26T15:37:16.286874586Z   File "/usr/local/lib/python3.6/site-packages/gevent/greenlet.py", line 536, in run
[subscribe-1]2017-07-26T15:37:16.286885636Z     result = self._run(*self.args, **self.kwargs)
[subscribe-1]2017-07-26T15:37:16.287038040Z   File "/usr/local/lib/python3.6/site-packages/engineio/async_gevent_uwsgi.py", line 55, in select_greenlet_runner
[subscribe-1]2017-07-26T15:37:16.287048222Z     select([fd], [], [])[0]
[subscribe-1]2017-07-26T15:37:16.287184241Z   File "/usr/local/lib/python3.6/site-packages/gevent/select.py", line 141, in select
[subscribe-1]2017-07-26T15:37:16.287207478Z     sel_results = _original_select(rlist, wlist, xlist, 0)
[subscribe-1]2017-07-26T15:37:16.287338077Z OSError: [Errno 9] Bad file descriptor
[subscribe-1]2017-07-26T15:37:16.287476005Z Wed Jul 26 15:37:16 2017 <Greenlet at 0x7f3de8b3e2a8: select_greenlet_runner(29, <gevent.event.Event object at 0x7f3de8cdb320>)> failed with OSError
```
Simultaneously with these issues I see when I emit to the socket via api the following errors occur:

```
 Tue Jul 25 20:59:56 2017 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /api/v1/message (ip ***) !!!
[app-1]2017-07-25T20:59:56.342453824Z [2017-07-25 20:59:56,342]	[messaging:post_message:47]ERROR	: [Errno 32] Broken pipe
```

When these errors occur it seems that both the iOS and Android socket clients become disconnected from the socket and can no longer send or receive messages via the socket. I have no idea what is causing the clients to lose connection or the socket to close. Any ideas on what is causing this issue and is causing the iOS, Android, and Server emission clients to lose connection to their socket creating these SIGPIPE/Broken pipe errors and creating these deadly client issues on our production socket server would be greatly appreciated.

**Comment by ulmentflam** [comment]
So another perplexing thing about my issue, when I restart the socket server it resolves the issues with the clients not connecting to the socket server. When I ran into this issue on my development instance the message emit occurred but [socket:send] was not in the logs for each of the emit events. This leads me to believe it may be an issue with the emit and join_channel call to socket and somehow the sockets are being lost. I am monkey patching before the app is run using uwsgi's built in monkey patching

**Comment by ulmentflam** [comment]
Quick update on possible causes of my issue. I finally was able to force my development server into this state and I have concluded it could possibly be a memory issue on both my dev and production platforms. The reason I say this is because the socket server shows the following errors and with larger than average nginx requests I get an out of disk space error. This being said I am curious on how socket connections are saved to memory before they get transported and I am wondering if my other containers running on the instance or my log files are exhausting the file descriptors available for the socket server.
```
bscribe_1      | Traceback (most recent call last):
subscribe_1      |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
subscribe_1      |     return self.wsgi_app(environ, start_response)
subscribe_1      |   File "/usr/local/lib/python3.6/site-packages/flask_socketio/__init__.py", line 42, in __call__
subscribe_1      |     start_response)
subscribe_1      |   File "/usr/local/lib/python3.6/site-packages/engineio/middleware.py", line 47, in __call__
subscribe_1      |     return self.engineio_app.handle_request(environ, start_response)
subscribe_1      |   File "/usr/local/lib/python3.6/site-packages/socketio/server.py", line 353, in handle_request
subscribe_1      |     return self.eio.handle_request(environ, start_response)
subscribe_1      |   File "/usr/local/lib/python3.6/site-packages/engineio/server.py", line 252, in handle_request
subscribe_1      |     transport, b64)
subscribe_1      |   File "/usr/local/lib/python3.6/site-packages/engineio/server.py", line 374, in _handle_connect
subscribe_1      |     ret = s.handle_get_request(environ, start_response)
subscribe_1      |   File "/usr/local/lib/python3.6/site-packages/engineio/socket.py", line 89, in handle_get_request
subscribe_1      |     start_response)
subscribe_1      |   File "/usr/local/lib/python3.6/site-packages/engineio/socket.py", line 136, in _upgrade_websocket
subscribe_1      |     return ws(environ, start_response)
subscribe_1      |   File "/usr/local/lib/python3.6/site-packages/engineio/async_gevent_uwsgi.py", line 61, in __call__
subscribe_1      |     self.app(self)
subscribe_1      |   File "/usr/local/lib/python3.6/site-packages/engineio/socket.py", line 218, in _websocket_handler
subscribe_1      |     raise reraise_exc
subscribe_1      |   File "/usr/local/lib/python3.6/site-packages/engineio/socket.py", line 204, in _websocket_handler
subscribe_1      |     self.receive(pkt)
subscribe_1      |   File "/usr/local/lib/python3.6/site-packages/engineio/socket.py", line 56, in receive
subscribe_1      |     async=self.server.async_handlers)
subscribe_1      |   File "/usr/local/lib/python3.6/site-packages/engineio/server.py", line 401, in _trigger_event
subscribe_1      |     return self.handlers[event](*args)
subscribe_1      |   File "/usr/local/lib/python3.6/site-packages/socketio/server.py", line 509, in _handle_eio_message
subscribe_1      |     self._handle_connect(sid, pkt.namespace)
subscribe_1      |   File "/usr/local/lib/python3.6/site-packages/socketio/server.py", line 414, in _handle_connect
subscribe_1      |     self.environ[sid]) is False:
subscribe_1      |   File "/usr/local/lib/python3.6/site-packages/socketio/server.py", line 481, in _trigger_event
subscribe_1      |     return self.handlers[namespace][event](*args)
subscribe_1      |   File "/usr/local/lib/python3.6/site-packages/flask_socketio/__init__.py", line 224, in _handler
subscribe_1      |     *args)
subscribe_1      |   File "/usr/local/lib/python3.6/site-packages/flask_socketio/__init__.py", line 589, in _handle_event
subscribe_1      |     ret = handler()
subscribe_1      |   File "subscriber/app.py", line 38, in connect_handler
subscribe_1      |     emit('my_response', {'data': 'Connected', 'count': 0})
subscribe_1      |   File "/usr/local/lib/python3.6/site-packages/flask_socketio/__init__.py", line 652, in emit
subscribe_1      |     include_self=include_self, callback=callback)
subscribe_1      |   File "/usr/local/lib/python3.6/site-packages/flask_socketio/__init__.py", line 346, in emit
subscribe_1      |     skip_sid=skip_sid, callback=callback, **kwargs)
subscribe_1      |   File "/usr/local/lib/python3.6/site-packages/socketio/server.py", line 221, in emit
subscribe_1      |     **kwargs)
subscribe_1      |   File "/usr/local/lib/python3.6/site-packages/socketio/pubsub_manager.py", line 66, in emit
subscribe_1      |     'skip_sid': skip_sid, 'callback': callback})
subscribe_1      |   File "/usr/local/lib/python3.6/site-packages/socketio/kombu_manager.py", line 80, in _publish
subscribe_1      |     self.producer.publish(pickle.dumps(data))
subscribe_1      |   File "/usr/local/lib/python3.6/site-packages/kombu/messaging.py", line 181, in publish
subscribe_1      |     exchange_name, declare,
subscribe_1      |   File "/usr/local/lib/python3.6/site-packages/kombu/messaging.py", line 203, in _publish
subscribe_1      |     mandatory=mandatory, immediate=immediate,
subscribe_1      |   File "/usr/local/lib/python3.6/site-packages/amqp/channel.py", line 1748, in _basic_publish
subscribe_1      |     (0, exchange, routing_key, mandatory, immediate), msg
subscribe_1      |   File "/usr/local/lib/python3.6/site-packages/amqp/abstract_channel.py", line 64, in send_method
subscribe_1      |     conn.frame_writer(1, self.channel_id, sig, args, content)
subscribe_1      |   File "/usr/local/lib/python3.6/site-packages/amqp/method_framing.py", line 174, in write_frame
subscribe_1      |     write(view[:offset])
subscribe_1      |   File "/usr/local/lib/python3.6/site-packages/amqp/transport.py", line 269, in write
subscribe_1      |     self._write(s)
subscribe_1      |   File "/usr/local/lib/python3.6/site-packages/amqp/transport.py", line 345, in _write
subscribe_1      |     n = write(s)
subscribe_1      |   File "/usr/local/lib/python3.6/site-packages/gevent/_ssl3.py", line 320, in write
subscribe_1      |     return self._sslobj.write(data)
subscribe_1      | BrokenPipeError: [Errno 32] Broken pipe
subscribe_1      | [pid: 13|app: 0|req: 163/163] 172.18.0.12 () {38 vars in 787 bytes} [Thu Jul 27 16:32:04 2017] GET /socket.io/?transport=websocket&token=f3be71d66017f6fdb834837137b3c48495b37ebbedcaffbcc47057fc15147ca8f8f62faae97fae0a90f6abb0628ec3f4 => generated 109 bytes in 109 msecs (HTTP/1.1 101) 4 headers in 202 bytes (1 switches on core 999)
subscribe_1      | Traceback (most recent call last):
subscribe_1      |   File "/usr/local/lib/python3.6/site-packages/gevent/greenlet.py", line 536, in run
subscribe_1      |     result = self._run(*self.args, **self.kwargs)
subscribe_1      |   File "/usr/local/lib/python3.6/site-packages/engineio/async_gevent_uwsgi.py", line 53, in select_greenlet_runner
subscribe_1      |     select([fd], [], [])[0]
subscribe_1      |   File "/usr/local/lib/python3.6/site-packages/gevent/select.py", line 141, in select
subscribe_1      |     sel_results = _original_select(rlist, wlist, xlist, 0)
subscribe_1      | OSError: [Errno 9] Bad file descriptor
subscribe_1      | Thu Jul 27 16:32:04 2017 <Greenlet at 0x7fa120eb6340: select_greenlet_runner(7, <gevent.event.Event object at 0x7fa120e82da0>)> failed with OSError
```

**Comment by miguelgrinberg** [comment]
This last stack trace appears to indicate a disconnection problem from your RabbitMQ queue. Just a day ago a user contributed some changes that make the connection to the queue more robust, including reconnecting if the connection is dropped, so try upgrading the python-socketio package to see if it helps.

Honestly it does not look like that is the main issue. Why did you conclude you have a memory issue? Also how is the out of disk space problem related to this?

**Comment by ulmentflam** [comment]
The reason I thought it may be a memory issue is the nginx container I have running in the same stack was running into `failed (28: No space left on device)` and the issues with socket were occurring simultaneously with these errors at the time. After observing this behavior I came to the conclusion that these two issues may be related. I have had issues in the past with my docker cloud deployment and one container consuming all of the resources of a cluster and thought that this may be the issue. I even shared the above stack trace with another python dev friend of mine and he thought that could be same problem with a docker cloud container utilizing too many of my resources was contributing of my issue. However I was able to push nginx back into the state where it errors with `failed (28: No space left on device)` and websockets have been running fine with nginx in this state. I thought that maybe both nginx and socket were using some of the same memory resources and when nginx filled the memory sockets were unable to write to disk if they needed to, however since they are functional after I got nginx into the same state as before I pretty much ruled out that theory. Again, in most cases after I restart the socket service my issues cease for a time and I am unable to replicate them on my own, however I cannot rely on this restart in my production environment. Any thoughts?

**Comment by miguelgrinberg** [comment]
Have you checked what device is out of space? That is normally a disk, not memory. I would check how is your disk space in the nginx container and/or on your host.

**Comment by ulmentflam** [comment]
Right, it is the `/dev/xvda1` disk that is running out of space on the host and when I navigate down the contents it is a variety of docker containers that use 75% of that space. Does python-socketio do any disk writes? or are the majority of the operations in memory?

**Comment by miguelgrinberg** [comment]
python-socketio does not write to disk, it's all memory. Sounds like you need to find out where is that disk space going. Not sure it is related to your other problem, but still, something that you need to address.

**Comment by ulmentflam** [comment]
That's what I thought but I was not certain. That does eliminate any correlation with my socket issue and my disk space problem. At this point I am 95% confident that my disk space issue is an issue with the log files not being cleared by docker periodically. However, barring the disk space issue, It still leaves me with this looming socket issue that I am unable to easily replicate.

**Comment by miguelgrinberg** [comment]
Is this still an issue? Please reopen if you need my help.
