### ISSUE TITLE
List of all rooms - is this the right way?

### ISSUE THREAD

**Issue by CreaRo** [miguelgrinberg/Flask-SocketIO#515]
I know this has been raised a couple times before, but I can't seem to find the right way to do it. I understand I cannot/shouldnot use the socketio.server.manager.room as it is a part of the lib internals.

Is this okay, given I am not on a distributed server?

    global _sid_room_pair

    @app.route('/is_connected/<device_id>', methods=['GET'])
	def is_connected(device_id):
	    global _sid_room_pair
	    if device_id in _sid_room_pair:
	        return "connected"
	    else:
	        return "not connected"

	@socketio.on('join_room', namespace=nsp_camera_controls)
	def on_join(data):
	    global _sid_room_pair
	    device_id = data['device_id']
	    join_room(room=device_id, sid=request.sid, namespace=nsp_camera_controls)
	    _sid_room_pair[device_id] = request.sid
	    print('%s now connect, joined room' % device_id)

	@socketio.on('connect', namespace=nsp_camera_controls)
	def on_connect():
	    print('Client Connected', request.sid)

	@socketio.on('disconnect', namespace=nsp_camera_controls)
	def on_disconnect():
	    global _sid_room_pair
	    _sid_room_pair = {key: val for key, val in _sid_room_pair.items() if val != request.sid}
	    print('Client disconnected', request.sid)

What would be a better way to maintain a list of rooms? My use-case is as follows : There are multiple cameras that connect to the flask server. Each communicates through room under their `device_id` name. At any given time I want to know which cameras are active.

**Comment by miguelgrinberg** [comment]
I honestly don't understand why you want to do this by looking at rooms. If you want to know which cameras are active, shouldn't you be connecting to the camera to see if it responds? The existance of a room does not mean that the camera is running, it means that at least one client is in that room.

But aside from that, the idea of using a global variable to keep track of the state of your server is okay, as long as you use a single server. You may need to move to a database service if you ever need to run multiple servers.

**Comment by CreaRo** [comment]
Right! I understand it makes no sense to check for rooms instead of pinging the camera - but my reasoning was each camera gets its own room as soon as it connects and requests to join_room, passing device_id as data argument. But yes I'm using rooms where they aren't needed.

Instead I'll store the session-id along with device_id. For this I'd maintain a similar global list. Do let me know if this is a better/right approach. Also, thanks, I'll move to a database service next!

    @app.route('/is_connected/<device_id>', methods=['GET'])
	def is_connected(device_id):
	    # check if device_id exists in our global list and return

	@socketio.on('on_post_connect', namespace=nsp_camera_controls)
	def on_post_connect(data):
		# Update the _camera_list adding sid and device_id and any other meta properties
	    global _camera_list
	    _camera_list.append({'device_id':data['device_id'], 'sid':request.sid, 'meta':data['meta_properties']})


	@socketio.on('connect', namespace=nsp_camera_controls)
	def on_connect():
		# Do nothing here, on_post_connect should update the global list with new connection information
	    pass


	@socketio.on('disconnect', namespace=nsp_camera_controls)
	def on_disconnect():
	    # remove from global list with matching request.sid

**Comment by miguelgrinberg** [comment]
As I said above, it's not a good implementation. First of all, the camera does not need to join a room, only the receivers of the camera streams have to be in that room. Second, if a camera dies, or loses the network, the room will continue to exist, because you have the subscribers that are receiving the feed in that room as well.

**Comment by CreaRo** [comment]
This isn't exactly what I'm doing. In the updated implementation, I've removed rooms. The camera does not request to join an extra room, nor do the subscribers/viewers join a room. No other rooms exist apart from the default sid one (used for server<->camera communication). My exact use case is as follows - 

1. The user enters into the browser url/start/<device_id>. Flask checks if the device_id mentioned is online, requests the camera to start streaming through a websocket, and returns an RTSP link where the 
 camera stream is available.
2. When a new user requests the same url/start/<device_id>, the same process occurs, except this time we already know the RTSP link and can be sent back directly.
3. There are no camera settings (like brightness, contrast) that need to be reflected back to each of the browsers - all the worry about is getting the RTSP link. Hence none of the viewers need to be clubbed into a room -- it is only later when we have these settings we'd like to reflect to each of the users that rooms will make sense.

So, to check if the camera is alive, I'm storing it's session id along with device_id in a list after the initial camera connect. When it disconnects, the corresponding session_id tuple is deleted from the list.

Thanks a lot for your suggestions and time!
