### ISSUE TITLE
how to close or shutdown a connection?

### ISSUE THREAD

**Issue by includedhj** [miguelgrinberg/Flask-SocketIO#519]
hi 
    when i test my program ,i met some interesting question.
    Android   client connect to server. when  kill client, tcp connect state change ESTABLISHED to CLOSE_WAIT..
    Client send FIN to server  when client abort, server call disconnect() to send ACK to client,but client has gone away ,so server keep  CLOSE_WAIT status.
    i guess i must close connestion by call close(fd) or shutdown in on_disconnect .
    but what should i do ? thx

**Comment by miguelgrinberg** [comment]
This isn't something you need to do on your own, the websocket framework is supposed to do that. So basically you found a case where a socket is not properly closed when the client is killed?

Can you give me more details about your setup? What async framework are you using on the server?

**Comment by includedhj** [comment]
thx ,tomorrow i will give u some more information ,good night

**Comment by includedhj** [comment]
sorry,that's my mistake.
   i used evenlet . when  client abort, then server receive  disconnect event  in on_disconnect, but i continue emit msg to  client , tcp state change to CLOSE_WAIT .
    so ,i give up emit msg to client ,so program run corretly.
     thx
