### ISSUE TITLE
How to send message from server to one particular client?

### ISSUE THREAD

**Issue by KCastiglione** [miguelgrinberg/Flask-SocketIO#52]
Is it possible to send a message to one particular client from the server? For example when a client receives a new mail I want to send a 'push notification' from server to client.

**Comment by miguelgrinberg** [comment]
In release 1.0, users can be addressed using their "session ID" as the room name. You can get the session ID for a user as `request.sid`.

**Comment by includedhj** [comment]
if one client not join any room, is server can send msg to this client ?

**Comment by miguelgrinberg** [comment]
Yes. You can use the sid value assigned to the client as room name.
