### ISSUE TITLE
I am confuse using asynchronous socketio

### ISSUE THREAD

**Issue by FahmiAyil** [miguelgrinberg/Flask-SocketIO#522]
I have a complex calculation in my program, iam using socket io to display the results to webpage, the results are continously until the condition is done.
How can i do that?

Maybe if i give some example is i have infinity loop to generate number, how can i display the results continously on webpage?
Thanks

**Comment by mrwillis** [comment]
A common way to do this is as per [here](https://github.com/miguelgrinberg/Flask-SocketIO/blob/master/example/app.py) in a background thread if you look at this these lines:

``` python
app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app, async_mode=async_mode)
thread = None
thread_lock = Lock()

def background_thread():
    """Example of how to send server generated events to clients."""
    count = 0
    while True:
        socketio.sleep(10)
        count += 1
        socketio.emit('my_response',
                      {'data': 'Server generated event', 'count': count},
                      namespace='/test')
```

With this style, when you create the thread in the below method, it's important to use a lock so that multiple threads are not created:

```python
@utils.authenticated_only
@socketio.on('connect')
def emit_market_data():
    global thread
    with thread_lock:
        if thread is None:
            thread = socketio.start_background_task(target=background_thread)
```

You can also choose to use a message_queue as in the docs and instead emit from an external process. Hope this helps.

**Comment by felixhao28** [comment]
How does this work when multiple connections are active?

Will all active clients receive the results from the background task started by the first client?

Or will the clients other than the first simply receive nothing?

Or (what I actually want) every client gets a background thread to do its work and receive results separately.

Instead of a single global thread lock, is there a built-in thread pool to avoid too many jobs to be running at the same time?

**Comment by miguelgrinberg** [comment]
> Will all active clients receive the results from the background task started by the first client?

It depends on how you implement your thread. If you make it broadcast then yes, if you make it address a specific client, then no.

> Or (what I actually want) every client gets a background thread to do its work and receive results separately.

This is different. For this you need one task per client, not one for the whole server.

> Instead of a single global thread lock, is there a built-in thread pool to avoid too many jobs running at the same time?

You need to use the facilities of the asynchronous framework that you are using for that. Both eventlet and gevent have thread pools. Check out their documentation.

**Comment by miguelgrinberg** [comment]
To address a specific client you need to add a `room` argument set to the `sid` of the addressee.

**Comment by miguelgrinberg** [comment]
The `sleep()` call is the standard way in which you release the CPU in Python asynchronous programs. You may be used to traditional multi-tasking, in which the OS does all the hard work. When using async, the CPU is no managed by the OS, each task needs to explicitly release it to give other tasks a chance to run.

What does the `do_heavy_job()` function do? How long does a background task run for? Not completely sure you need it, your original version could probably work as well, if you add the `sleep()` call.

**Comment by felixhao28** [comment]
Yes you are right. I don't need the background job. A `sleep()` is all I need. `do_heavy_job()` calls from the python hook of tensorflow into some native code. It is a synchronized call.

Then what does `start_background_task` really do?

**Comment by miguelgrinberg** [comment]
it runs the function as a separate task, but as long as you sleep often that may not be necessary. Depends on the situation.

**Comment by zw1988** [comment]
Hi. I am trying to use flask to create a game with many rooms. I have a separated  program to simulate  robots in rooms. So  I run  a background task called "get_room_events" to get room events from the program. The strange thing is that when I changed debug to True, flask is hanging when I visit localhost:5000/hello. But debug = False works fine. How can I solve this? Thank you.

socketio.start_background_task(target=get_room_events)
socketio.run(app, host="0.0.0.0",  debug=False)
@app.rount('/hello')
def hello():
    return 'hello'

**Comment by naveenreddysg** [comment]
Iam trying to implement socketio chat app, whichi is better practice to save chat history in database
