### ISSUE TITLE
@socketio.on hooks in external process

### ISSUE THREAD

**Issue by mrwillis** [miguelgrinberg/Flask-SocketIO#523]
Hi Miguel,

I have a question about applying the `@socket.io.on` decorators in a non-Flask application process, such as an external process that would emit data. I am assuming this is not possible because the session context is not there, but perhaps the message queue communicates this?

Something like this, in some external process:

```python
external_sio = SocketIO(json=flask.json, message_queue='redis://', channel='socketio',
                        async_mode='threading')

@external_sio.on('join')
def join(data):
    print(data)

```

Even if this is possible, in your opinion, is it recommended? I am trying to share some user specific session/metadata available in my Flask app with my external process. Thanks!

**Comment by miguelgrinberg** [comment]
No, that is currently not possible. The only thing an external process can do is emit, the receive side has to be implemented on the main server.
