### ISSUE TITLE
when i run the demo, websocket did't work

### ISSUE THREAD

**Issue by torykit** [miguelgrinberg/Flask-SocketIO#524]
![1](https://user-images.githubusercontent.com/15373053/29081821-3a23577c-7c96-11e7-8bad-1d072d54ea62.png)
![2](https://user-images.githubusercontent.com/15373053/29081861-5f2e448c-7c96-11e7-8f05-b2fa3ccfd150.png)
![3](https://user-images.githubusercontent.com/15373053/29081863-5f490f42-7c96-11e7-915e-acd742dd718a.png)
![4](https://user-images.githubusercontent.com/15373053/29081864-5f70a14c-7c96-11e7-92af-335b1e41bf17.png)
that shoud by one request, why so many?
please help, tks!

**Comment by miguelgrinberg** [comment]
Looks like this client did not upgrade the connection to WebSocket, or tried to upgrade and that failed. You can add logging on the server to see if that indicates what the problem is:

    socketio = Socket(app, engineio_logger=True)

**Comment by torykit** [comment]
![5](https://user-images.githubusercontent.com/15373053/29100730-2f3994a8-7ce0-11e7-86ef-e0fb5cb9721c.png)
@miguelgrinberg

**Comment by torykit** [comment]
@miguelgrinberg I fix it.  when I use async_mode='eventlet' and pip install eventlet .
tks!

**Comment by miguelgrinberg** [comment]
Ah, yes. Without eventlet or gevent there is no WebSocket support. Glad you figured it out!
