### ISSUE TITLE
read json file 

### ISSUE THREAD

**Issue by mervecan** [miguelgrinberg/Flask-SocketIO#525]
I don't know it is a silly question or not. I created dummy json file using Faker and I want to read json file using SocketIO. Is this possible?

**Comment by miguelgrinberg** [comment]
If all you want is to read a json file stored on disk, you don't need SocketIO. All you need is the `json` package from the standard library:

    import json
    data = json.loads(open('myfile.json').read())

**Comment by canmerve** [comment]
I want to read using SocketIO, because later on, my json data source wil not stored disk.

**Comment by miguelgrinberg** [comment]
A SocketIO server will only let you send and receive data from one or more connected clients. There are no functions to read data from disk. Not sure I understand what you are trying to do, can you provide more details?

**Comment by canmerve** [comment]
I need to create dummy json data source, and read this source using flask SocketIO. After that, I need to write on local sql server, periodically. I don't know so much about websockets and python. That is why I cannot explain myself clearly.

**Comment by miguelgrinberg** [comment]
I think you can go about this in a couple of ways. What I would do is forget about SocketIO in the beginning, and write the part of your application that receives the data and writes it to the SQL server. You can use a data file on disk as a data source, and read it using the `json` package as I showed you above.

After you have that part figured out, you can add the SocketIO server, and then replace the part that reads a JSON file from disk with receiving data over SocketIO from a client. You will need to write a SocketIO client that sends the data for this part, so you'll need to find a client package that you like out of the many available (this project is only a server).
