### ISSUE TITLE
Problems wit Flask-SocketIO

### ISSUE THREAD

**Issue by zappfinger** [miguelgrinberg/Flask-SocketIO#527]
I'm having some problems with Flask-SocketIO, on different platforms, with regular Python and Anaconda Python. Most of the times it does not work.  
1) I am using socket.emit from a thread in Python, could this be  a problem?
2) When I use the following n JS:
         b1.click(function(){
         socket.emit('channel', {channel:'control', data:'Start'});
         console.log('start pressed');
      });
and in python:
@socketio.on('channel', namespace='/test')
def test_message(message):
      localtime = time.asctime(time.localtime(time.time()))
      print localtime, message['channel'], message['data']
      if message['channel'] == 'control':
          if message['data'] == 'Start':
              client1.start()
          elif message['data'] == 'Stop':
              client1.stop()
          elif message['data'] == 'Reset':
              client1.reset()

now, nothing comes in. Yesterday it sort of worked, but although I  was only sending the 'Start' command, all 3 of them where triggered (Start, Stop and Reset)
3) Many times I have the following error:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\gevent\pywsgi.py", line 935, in handle_one_response
    self.run_application()
  File "C:\Python27\lib\site-packages\gevent\pywsgi.py", line 909, in run_application
    self.process_result()
  File "C:\Python27\lib\site-packages\gevent\pywsgi.py", line 895, in process_result
    self.write(data)
  File "C:\Python27\lib\site-packages\gevent\pywsgi.py", line 741, in write
    self._write_with_headers(data)
  File "C:\Python27\lib\site-packages\gevent\pywsgi.py", line 763, in _write_with_headers
    self._write(data)
  File "C:\Python27\lib\site-packages\gevent\pywsgi.py", line 726, in _write
    self._sendall(data)
  File "C:\Python27\lib\site-packages\gevent\pywsgi.py", line 701, in _sendall
    self.socket.sendall(data)
  File "C:\Python27\lib\site-packages\gevent\_socket2.py", line 419, in sendall
    timeleft = self.__send_chunk(chunk, flags, timeleft, end)
  File "C:\Python27\lib\site-packages\gevent\_socket2.py", line 355, in __send_chunk
    data_sent += self.send(chunk, flags)
  File "C:\Python27\lib\site-packages\gevent\_socket2.py", line 323, in send
    return sock.send(data, flags)
error: [Errno 10053] De software op uw hostcomputer heeft een verbinding verbroken
Tue Aug 15 10:20:22 2017 {'REMOTE_PORT': '51312', 'HTTP_HOST': '127.0.0.1:5000', 'REMOTE_ADDR': '127.0.0.1', (hidden keys: 23)} failed with error

Do you have any idea?
Richard

**Comment by zappfinger** [comment]
Could someone at least say if the versions I have are compatible? Here's the output of pip list:
attrs (17.2.0)
Automat (0.6.0)
click (6.7)
constantly (15.1.0)
flask (0.12.2)
Flask-SocketIO (2.9.2)
gevent (1.2.2)
greenlet (0.4.12)
incremental (17.5.0)
itsdangerous (0.24)
jinja2 (2.9.6)
markupsafe (1.0)
modbus-tk (0.5.4)
numpy (1.11.3+mkl)
pip (9.0.1)
pymodbus (1.3.0rc1)
pyserial (2.7)
python-engineio (1.7.0)
python-socketio (1.8.0)
setuptools (28.8.0)
six (1.10.0)
Twisted (17.1.0)
werkzeug (0.12.2)
wheel (0.29.0)
zope.interface (4.4.1)

regards,
Richard

**Comment by miguelgrinberg** [comment]
Does the example application in this repository show the same problem if you run it with the same dependencies? That app also issues emits from a background thread.

Also, when something like this happens it is a good idea to enable logging on both sides and see if there are any clues there.

**Comment by zappfinger** [comment]
Yes, that seems to work. I guess I will go from there. Thanks.
