### ISSUE TITLE
Can Flask-SocketIO work with Apscheduler?

### ISSUE THREAD

**Issue by anningwang** [miguelgrinberg/Flask-SocketIO#529]
First of all, thanks for your great work!
I have a trouble when using Flask-SocketIO. When I call socketio.emit() in a job of Apscheduler(v 3.3.1). It doesn't work, and this call maybe breaks down the connection of WebSocket.
Can you help me?

periodic job (apscheduler) -->call socketio.emit() ---- can't work
background_thread---------->call socketio.emit() ----  works well

Thanks.
anning

**Comment by miguelgrinberg** [comment]
I haven't tried this myself, but I haven't heard from anyone being successful at combining appscheduler and Flask-SocketIO. From the docs, it seems appscheduler can run on top of gevent. Flask-SocketIO also supports gevent, so that is probably your best (only) bet to make it work.

**Comment by dmichel76** [comment]
I just encountered the same issue... @anningwang, any luck?

**Comment by nkyordy** [comment]
A little late to the party, but here is how I implemented this. Any event listener you attach to your scheduler will generate events in a different thread than your flask-socketio app. However, you can have your scheduler make a request to localhost and trigger the global emit from the main thread. It's a little hacky, but if you make sure CORs is set up correctly, it should be fairly safe.

`@app.route('/trigger', methods=['GET'])`
`def trigger_event():`
&nbsp;&nbsp;&nbsp;&nbsp;`socketio.emit('event', 'A job event occurred', namespace='/jobs')`
&nbsp;&nbsp;&nbsp;&nbsp;`return "event triggered"`

`def notify():`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`requests.get('http://127.0.0.1:5000/trigger')`
