### ISSUE TITLE
How would I get the heartbeat event?

### ISSUE THREAD

**Issue by EndenDragon** [miguelgrinberg/Flask-SocketIO#530]
In node.js, one would use a heartbeat event inside a connection event, like so https://github.com/socketio/socket.io/issues/1185#issuecomment-46426515

However, I am not sure how to detect the heartbeat events serverside for FlaskSocketIO.  I have attempted implementing it in the following way.

```python
class Gateway(Namespace):
    def on_heartbeat(self):
        print("HEART")
```

**Comment by miguelgrinberg** [comment]
To my knowledge, this `heartbeat` event is not an officially event, just something that someone figured out by looking at the JS implementation. There is no such thing on this server, the heartbeats are handled internally, as specified in the Socket.IO protocol. Nothing prevents you from sending your own custom event and use it as a heartbeat for your application. This is just a 3-4 lines of code of JS to create a scheduled event to be sent at a specific interval.
