### ISSUE TITLE
[bug-report] Unable to connect to redis on docker

### ISSUE THREAD

**Issue by italomaia** [miguelgrinberg/Flask-SocketIO#531]
I have tried to use socketio + eventlet + redis without success. message_queue just makes the whole thing hang. My test envolved chromium on ubuntu. Just set up a docker project to show the weird behavior. Just "docker-compose up" it.
[iohang.zip](https://github.com/miguelgrinberg/Flask-SocketIO/files/1237654/iohang.zip)

**Comment by miguelgrinberg** [comment]
You have to monkey patch the Python standard library so that all socket/threading/etc become cooperative. This is required when using Redis.

**Comment by imaia** [comment]
Just went through docs and found this:

Flask-SocketIO does not apply monkey patching when eventlet or gevent are used. But when working with a message queue, it is very likely that the Python package that talks to the message queue service will hang if the Python standard library is not monkey patched.

Thanks, @miguelgrinberg

**Comment by biggers** [comment]
Would be good to have a recipe to know just how to monkey-patch, in the situation described by @italomaia (assuming use of eventlet).  Trying to make a decision on whether to use flask+socketio, versus just going with Tornado.  Thank you.
