### ISSUE TITLE
Disconnect Issues

### ISSUE THREAD

**Issue by skortchmark9** [miguelgrinberg/Flask-SocketIO#533]
Hey Miguel, hope you're doing well.

I'm having an issue where clients aren't disconnecting properly. 
The code looks like this:
```python
        roomies = socketio.server.manager.rooms.get(namespace, {}).get(room, [])
        if roomies:
                    socketio.emit('ping',room=roomies[0])
                   raise RoomNotEmpty(room, roomies)
```

And the logs I get look like this:
```
29304eacace71c7b81af5de4: Received packet PING data None
INFO:engineio:4bed2e1a29304eacace71c7b81af5de4: Sending packet PONG data None
INFO:engineio:4bed2e1a29304eacace71c7b81af5de4: Received packet PING data None
INFO:engineio:4bed2e1a29304eacace71c7b81af5de4: Sending packet PONG data None
INFO:engineio:4bed2e1a29304eacace71c7b81af5de4: Unexpected error "[Errno 107] Transport endpoint is not connected", closing connection

...and later ...

INFO:socketio:received event "join" from 82ccb3faa4db4fa19525165cdc2118e0 [/]
INFO:socketio:emitting event "ping" to 4bed2e1a29304eacace71c7b81af5de4 [/]
WARNING:engineio:Cannot send to sid 4bed2e1a29304eacace71c7b81af5de4
ERROR:api:Room not empty: room_name. Occupied by: {'4bed2e1a29304eacace71c7b81af5de4': True}
```

So, sometimes the disconnect event doesn't fire properly, and the client doesn't get kicked from the room even though the connection gets marked as closed.

So I've got three questions:
1.) How should I debug these ```transport endpoint``` issues?
2.) Do you have ideas about why disconnect might not be fired after engineio closes the connection?
3.) As you can see, I'm already able to detect a stale room occupant by emitting an event at them - it will print ```Cannot send to sid ```. Is there any way to get this error out of python-socketio? (Ideally without reaching further into the internals than I already am?)

For reference, I'm using 
```
eventlet==20.0.0,
python-engineio==1.7.0
python-socketio==1.7.6
Flask-SocketIO==2.9.0
greenlet==0.4.12
gunicorn==19.7.1
```

**Comment by miguelgrinberg** [comment]
This should be addressed in the python-engineio package.
