### ISSUE TITLE
Update python-socketio to 1.8.0

### ISSUE THREAD

**Issue by BertrandBordage** [miguelgrinberg/Flask-SocketIO#534]
I’ve been through a lot of issues others also faced: 400 & 500 errors, “Invalid frame header”, “Opcode -1” and memory leak.

I also had an issue with one of the latest changes of this project: the `ignore_queue` argument that was passed to python-socketio, but since I was on an old version (1.6.0), it was not handled correctly, randomly triggering 500 errors.

After updating to python-socketio 1.8.0, all these issues were resolved.
So setup.py has to be updated to require at least python-socketio 1.8.0.

**Comment by miguelgrinberg** [comment]
I agree regarding `ignore_queue`, I should have bumped the requirements. But that came in the 1.6.1 release of the Socket.IO server. Were there any other issues that required going to 1.8, or was that the only release that you tested?

**Comment by BertrandBordage** [comment]
It’s the only version I tested.
