### ISSUE TITLE
Multiple uWSGI workers

### ISSUE THREAD

**Issue by EndenDragon** [miguelgrinberg/Flask-SocketIO#535]
I am currently loading my uWSGI under 1 worker process. May I use the `processes` flag in uWSGI and serve my flask app under multiple workers? If so, do I have to do anything special in making FlaskSocketIO work with multiple workers? (I have a redis messaging queue [going on](https://github.com/TitanEmbeds/Titan/blob/master/webapp/titanembeds/app.py#L34))

**Comment by miguelgrinberg** [comment]
@EndenDragon the way I work with multiple workers is by running several one-worker servers on different ports, all behind an nginx reverse-proxy configured with iphash load balancing which implements sticky sessions.

I have never tried this, but it looks like uWSGI supports the iphash load balancing algorithm since version 2.1. This combined with the redis queue may allow you to run multiple uWSGI workers from a single uWSGI instance. Give it a try and report back if it works.

**Comment by EndenDragon** [comment]
@miguelgrinberg I do not know how to setup the iphash load balancing technique for uwsgi. Where are you seeing that uwsgi 2.1 support this feature?

**Comment by miguelgrinberg** [comment]
Hmm. The reference that I found is this comment: https://github.com/unbit/uwsgi/issues/83. But I cannot find a single example that shows how to use it, and searching through the source code it appears that iphash is an option that is available for use with their fastrouter plugin, which is a load balancer.

I think my method is going to give you a lot less problems. Start a bunch of single-worker uWSGI instances, each on its own port, then configure nginx to do the load balancing.

**Comment by raushanraj** [comment]
@miguelgrinberg 

> the way I work with multiple workers is by running several one-worker servers on different ports, all behind an nginx reverse-proxy configured with iphash load balancing which implements sticky sessions.

Suppose i have n CPU cores. As you suggested the best approach would be to run multiple single-worker uWSGI instances(on different port). What you suggest to run n single workers or 2n+1 single-worker?. Will it work with context switching on CPU processors.

**Comment by miguelgrinberg** [comment]
There is no absolute rule about this, the number of workers you run depends on the load that you need to handle, and the amount of work each client generates on the server. If your server is going to be doing mostly I/O, then you can run multiple workers per CPU and everything will still work great.
