### ISSUE TITLE
Improvements on run CLI command

### ISSUE THREAD

**Issue by jxltom** [miguelgrinberg/Flask-SocketIO#537]
- The ```run``` command will override flask's original ```run``` command even though when it is not used in a flask application but is installed in the environment. Is it better to move the registration of ```run``` CLI command to SocketIO server initialization function such as ```__init__``` and ```init_app``` and register it by ```@app.cli.command```?

- The ```run_with_reloader``` function in Flask is actually not recommended since it is not a documented API and may be subject to change anytime. Is it better to reload socketio server by setting ```use_reloader``` to ```True``` and reload flask development server by flask's original command when socketio in not in flask's extensions? 

- flask-socketio's ```run``` command does not use ```DispatchingApp``` which making flask application can not reload again if there encounter exceptions. This does not respect flask original ```run``` command's behavior. This means user can not get the same reload function once they install flask-socketio as package even though they haven't use it in the application.

**Comment by miguelgrinberg** [comment]
Regarding your first item, back when I implemented the `run` feature, it was no possible to override flask's own `run` via a standard `@app.cli.command` decorated function. Not sure if the order of command registration has changed now, but I'm guessing not.

Your second point is valid. If the redefined run command detects that the extension was not installed, it should defer to the original run command from Flask.

The last one is also worth investigating.

**Comment by miguelgrinberg** [comment]
Starting with Flask-SocketIO 3.2.0 (just released), the `flask run` command can only be used with the threading mode. For all other async modes, the `socketio.run(app)` method should be used to start the server.
