### ISSUE TITLE
Connection refused when using gevent 

### ISSUE THREAD

**Issue by zappfinger** [miguelgrinberg/Flask-SocketIO#538]
I'm trying to connect to my flask socket io server from another computer. Here is part of the code:
`async_mode = gevent

app = Flask(__name__, static_url_path='')

app.config['SECRET_KEY'] = 'secret!'

socketio = SocketIO(app, async_mode='gevent')`

But when I try to connect from the other computer I get 'connection refused'
Do I also have to run a gevent server, or should this just work?

Richard

**Comment by zappfinger** [comment]
Sorry, my mistake, I forget to put host='0.0.0.0' in like this:
socketio.run(app, host='0.0.0.0', debug=False)

Now it works.

**Comment by avisrivastava254084** [comment]
I am unable to run with gevent even though I have written the aforementioned line.
