### ISSUE TITLE
How to handle [Errno 10053] when refresh page frequently on windows?

### ISSUE THREAD

**Issue by Nriver** [miguelgrinberg/Flask-SocketIO#539]
With the example provided in this repo, the server gets lots of [error 10053] when I refresh the index page very frequently in Chrome on my Windows. This causes problem cause this kind of operation will trigger the socket's on_connect event but never has a chance to trigger on_disconnect event where I need to do something( say unbind the user with current socket id) when the socket is closed. Any suggestion about this one? Like how to handle the error so I can manually run on_disconnect?

![image](https://user-images.githubusercontent.com/6752679/30049448-4b71fb9c-924d-11e7-9875-dac539bcf3f1.png)

**Comment by miguelgrinberg** [comment]
Have you tried if this also happens on Python 3? I've seen a lot of instances where this 10053 error appears with Python 2, but haven't seen it on Python 3.

**Comment by Nriver** [comment]
I installed python3 on a new windows computer and had a quick test, the problem seemed to be disappeared. Couldn't find better solution for windows, guess it's time for me to get a full upgrade for python3.
