### ISSUE TITLE
session.sid

### ISSUE THREAD

**Issue by mguijarr** [miguelgrinberg/Flask-SocketIO#540]
Hello,

I have code using `session.sid` that works fine for flask-socketio 2.2, but with the latest version it breaks:

`AttributeError: 'dict' object has no attribute 'sid'`

Does someone have an idea what changed ? And how to fix this error ?

Thanks in advance :)

**Comment by miguelgrinberg** [comment]
There was never a `session.sid`. Maybe you want `request.sid` instead?

**Comment by mguijarr** [comment]
Thanks for your answer.

Indeed, `session.sid` does not come from `Flask-SocketIO` sorry for the noise. My code also uses `flask-session`: this is where `session.sid` comes from.

However, with version <=2.8 (`pip install flask-socketio==2.8`) my code works whereas with version 2.9 it breaks as described in the issue.

I am currently trying to find which commit changed something for me...

**Comment by miguelgrinberg** [comment]
It's this one: https://github.com/miguelgrinberg/Flask-SocketIO/commit/742c5ba23e53b5bdaf0530ed483dd808e50dca08. If you are using Flask-Session for server-side stored sessions, I suggest you add `manage_session=False` to the `SocketIO()` constructor. That I think will let you use the session object without interference from this extension.

**Comment by mguijarr** [comment]
Wow... Impressive.

Thanks a lot - indeed this fixes the problem I had.

I am sorry I didn't read the documentation about this new argument.

**Comment by miguelgrinberg** [comment]
Yeah, no problem. I did not expect this change was going to affect anyone, sorry about that. I suppose your own application is adding a `sid` property to the session object? Wouldn't it make more sense to use the session properly and write `session['sid']` instead? That is more compatible.

**Comment by mguijarr** [comment]
Well, I am not sure... In fact I use `session.sid` just as described in Flask-Session documentation, look here: https://pythonhosted.org/Flask-Session/ in the description of `ServerSideSession` base class we can read:

>__sid__
>Session id, internally we use uuid.uuid4() to generate one session id. You can access it with session.sid.

They do not say we can use `session['sid']` ; in fact, the sid is maybe not even stored in the database? (I store my sessions in redis). I have the concept of master and slaves connections to my web application - "slaves" receive data from a "master", a special client that is allowed to do modifications on the web application data whereas slaves can just see the changes. Ideally I would use Web RTC for this but at the moment everything still passes through the server.

**Comment by miguelgrinberg** [comment]
Oh, okay, sorry, forget what I said.

The confusion comes from the fact that Flask-SocketIO also has a session ID that it calls `sid`. I did not realize that Flask-Session has its own `sid`. So yeah, with `manage_session=False` Flask-SocketIO will stay completely out of the way and let you use the session object from Flask-Session in any way you want. With `manage_session=True` the session object is actually a regular dictionary that is managed by this extension.

**Comment by mguijarr** [comment]
Ok. That's fine with me :)
