### ISSUE TITLE
Unable to modify html files on server after deployment

### ISSUE THREAD

**Issue by kyleabens** [miguelgrinberg/Flask-SocketIO#541]
Hello,

I can deploy my flask app which utilizes socketio no problem on my digitalocean droplet using nginx, gunicorn and eventlet.  However I notice that anytime I overwrite one of my html files in my templates folder the change is not reflected in the web browser when I visit that page.  Even if I delete the page entirely from the server I am still able to visit it in the browser.  I do not have this issue with my static files only templates and my app.py.  I have been in contact with DigitalOcean support and have read numerous posts surrounding server caching and have not found an answer.  I have also tried clearing my browser cache and changing 'sendfile on' to 'sendfile off' in the nginx.conf file.  No Luck.  Has anyone had this issue in the past?  Any help would be greatly appreciated!

**Comment by miguelgrinberg** [comment]
Are you restarting the server every time you make changes to your templates? Jinja2 caches templates, it is only going to read those files the first time they are needed and from then one it will reuse the copy it kept in memory.

**Comment by kyleabens** [comment]
I run **$ sudo systemctl restart nginx** everytime I make a change.  Am I not running the right command?  Where can I find jinja2 cache?  I searched for the specific html files as root after I deleted them hoping to see them in some cache directory but they were no where to be found on the server, yet were still being displayed when I visited the site.  Thanks for the quick response btw!

**Comment by miguelgrinberg** [comment]
To reset the template cache you need to restart your application. This is the gunicorn process. You do not need to touch nginx unless you make changes to the nginx configuration.

**Comment by kyleabens** [comment]
Would I be able to solve this by simply adding debug=True?

**Comment by miguelgrinberg** [comment]
@kyleabens that is a really bad idea. Debug mode is for development only. What's wrong with restarting gunicorn?

**Comment by kyleabens** [comment]
Yea I figured that was a bad idea.  I'm having trouble finding the proper way to restart gunicorn.

**Comment by kyleabens** [comment]
Scratch that I figured it out. Thanks so much for the help!

**Comment by kyleabens** [comment]
For those who encounter the same issue...run **$ pstree -ap|grep gunicorn** to get the masterpid then **$ kill -HUP <masterpid>**
