### ISSUE TITLE
"Server initialized" for out of band emits

### ISSUE THREAD

**Issue by gordol** [miguelgrinberg/Flask-SocketIO#542]
Hello,

I'm seeing instances of "Server initialized" in our worker processes when they spin up a new job off the queue. At first, I thought it was because the workers are importing our application, and it's setting app in the `__init__.py`instantiation of SocketIO.

Our `backend/__init__.py` had a line like this:

`socketio = SocketIO(app, **app.config['SOCKETIO'])` where the config['SOCKETIO'] dict has a message_queue kwarg.

I noticed this in the documentation:

> `socketio = SocketIO(message_queue='redis://')`
> `socketio.emit('my event', {'data': 'foo'}, namespace='/test')`
> When using the SocketIO instance in this way, the Flask application instance is not passed to the constructor.

Is the reason it's spinning up a server for every worker job due to the app arg being passed in? What's the best way to avoid this? Our workers need to access the Flask app, for config info, models, access to supporting methods, etc... but I don't want them to spin up a server per-se. It doesn't *hurt* anything, it seems, because everything does indeed work, but it's definitely a waste of resources, right?

I can think of a couple ways to mitigate this, like using an env var on our gunicorn process, that, when set, injects the app into the SocketIO instantiation, and sets it to None otherwise... Or we could even use the built-in SERVER_SOFTWARE env var...

FWIW, we use .run() in development, and use wsgi via server:app in production, via a server.py file like this:

```python
#!/usr/bin/env python
import sys
sys.dont_write_bytecode = True

from eventlet import monkey_patch
monkey_patch()

from backend import socketio, app

if __name__ == '__main__':
    app.auto_reload = True
    socketio.run(app, host='127.0.0.1', port=8082 )
```

Perhaps, the app being passed in in the `backend/__init__.py` is not necessary, in this case?

How then, would we pass it when the app is running via wsgi?

So, I tried something like this:

```python
if 'gunicorn' in os.environ.get('SERVER_SOFTWARE', ''):
    socketio = SocketIO(app=None, **app.config['SOCKETIO'])
else:
    socketio = SocketIO(app, **app.config['SOCKETIO'])
```

Thing is...

I tried, this, and I still see as many instances of "Server initialized" as I have "namespace" modules that use a SocketWrapper class like this:

`backend/namespaces/__init__.py`:
```python
from flask_socketio import SocketIO
from backend import app

class SocketWrapper():
    def __init__(self, namespace='/'):
        self.sio = SocketIO(app=None, **app.config['SOCKETIO'])
```

These are instantiated like:

`backend/namespaces/foobar.py`:
```python
from . import SocketWrapper
sio = SocketWrapper(namespace='/foobar')

@delayable('socketio')
def do_stuff_via_worker(broadcast=False):
    data = {'foobar': 123}
    sio.flush(data, broadcast)
```

Then the workers basically just pick up the do_stuff_via_worker() method, and its args, and should then use the SocketWrapper to push the data out via the main server process that is serving the web sockets to users. It does do all that, but it also spins up servers for every process and job, it seems...

To use an example you'll see below in the logs:

```python
@delayable('socketio')
def spawn_pubsub_greenlets(namespace, sid, user_id):
    sio = SocketWrapper(namespace=namespace)
```

As far as I can tell, it's setting app to None, so, why is it still spinning up a server every time a job runs?

```
» ./dev-workers.py
2017-09-07 19:13:20,926 - generic worker:  started worker
2017-09-07 19:13:20,926 - generic worker:  started worker
2017-09-07 19:13:20,926 - pipeline worker:  started worker
2017-09-07 19:13:20,926 - pipeline worker:  started worker
2017-09-07 19:13:20,926 - redis worker:  started worker
2017-09-07 19:13:20,927 - redis worker:  started worker
2017-09-07 19:13:20,927 - mail worker:  started worker
2017-09-07 19:13:20,927 - socketio worker:  started worker
2017-09-07 19:13:20,927 - socketio worker:  started worker
2017-09-07 19:13:20,927 - analytics worker:  started worker
2017-09-07 19:13:20,927 - analytics worker:  started worker


2017-09-07 19:14:30,086 - Uncaught exception raised in worker: socketio worker:
2017-09-07 19:14:30,088 - Traceback (most recent call last):
  File ".../worker.py", line 71, in run
    self.run_task()
  File ".../worker.py", line 89, in run_task
    func, task_id, args, kwargs = loads(msg[1])
  File ".../lib/python2.7/pickle.py", line 1388, in loads
    return Unpickler(file).load()
  File ".../2.7/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File ".../lib/python2.7/pickle.py", line 1096, in load_global
    klass = self.find_class(module, name)
  File ".../lib/python2.7/pickle.py", line 1130, in find_class
    __import__(module)
  File ".../namespaces/__init__.py", line 5, in <module>
    from backend import app
ImportError: cannot import name app

--------------------------------------------------------------------------------
INFO in __init__ [.../backend/__init__.py:36]:
Version: 2.9.11-38-g905989d8-dirty
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
INFO in __init__ [.../backend/__init__.py:37]:
Config: Dev
--------------------------------------------------------------------------------
.../lib/python2.7/site-packages/flask_cache/jinja2ext.py:33: ExtDeprecationWarning: Importing flask.ext.cache is deprecated, use flask_cache instead.
  from flask.ext.cache import make_template_fragment_key
2017-09-07 19:14:30,454 - Server initialized for eventlet.
2017-09-07 19:14:30,895 - Server initialized for eventlet.
2017-09-07 19:14:30,903 - Server initialized for eventlet.
2017-09-07 19:14:30,907 - Server initialized for eventlet.
2017-09-07 19:14:30,916 - Server initialized for eventlet.
2017-09-07 19:14:30,919 - Server initialized for eventlet.
2017-09-07 19:14:36,102 - socketio worker:  running: emit_bootstrap_data()
2017-09-07 19:14:36,103 - Server initialized for eventlet.

...

2017-09-07 19:20:09,204 - socketio worker:  running: emit_bootstrap_data()
2017-09-07 19:20:09,204 - Server initialized for eventlet.
2017-09-07 19:20:09,372 - socketio worker:  running: spawn_pubsub_greenlets()
2017-09-07 19:20:09,372 - Server initialized for eventlet.

```

Ignore that `ImportError: cannot import name app` that's because the worker has already imported the app before deserializing the job, and only happens the first time a worker handles a job.

I know there's a lot here, so, if I can clarify anything, please let me know. I know this setup deviates a bit from the norm...

**Comment by gordol** [comment]
UGH... I just noticed a stupid typo...

That little toggler is backwards...

It should be:

```python
if 'gunicorn' in os.environ.get('SERVER_SOFTWARE', ''):
    socketio = SocketIO(app=None, **app.config['SOCKETIO'])
else:
    socketio = SocketIO(app, **app.config['SOCKETIO'])
```

However, this may work now for production use, but then it breaks for development... Hmmm...

```
Traceback (most recent call last):
  File "./server.py", line 12, in <module>
    socketio.run(app, host='127.0.0.1', port=8082 )
  File "/Users/tinix/.virtualenvs/7g/lib/python2.7/site-packages/flask_socketio/__init__.py", line 460, in run
    self.sockio_mw.wsgi_app = DebuggedApplication(self.sockio_mw.wsgi_app,
AttributeError: 'SocketIO' object has no attribute 'sockio_mw'
```

**Comment by gordol** [comment]
```python
#ensure app is passed in for production server
if environ.get('IS_WORKER', False):
    print 'running from a worker, do not instantiate app to the SocketIO instance'
    socketio = SocketIO(app=None, **app.config['SOCKETIO'])

else:
    print 'running as a server'
    socketio = SocketIO(app, **app.config['SOCKETIO'])


```

So, I switched to using an env var, and am doing this the other way around now... 

```
running from a worker, do not instantiate app to the SocketIO instance
2017-09-07 19:38:45,590 - Server initialized for eventlet.
2017-09-07 19:38:45,996 - Server initialized for eventlet.
2017-09-07 19:38:46,008 - Server initialized for eventlet.
2017-09-07 19:38:46,013 - Server initialized for eventlet.
2017-09-07 19:38:46,029 - Server initialized for eventlet.
2017-09-07 19:38:46,033 - Server initialized for eventlet.
2017-09-07 19:38:51,240 - socketio worker:  running: emit_bootstrap_data()
2017-09-07 19:38:51,240 - Server initialized for eventlet.
```

It's not pushing the app arg now, but it's still spinning up servers???

**Comment by miguelgrinberg** [comment]
The server object is created in all cases. But only in the case of a real server it is used to listen for connections. The message could be improved, maybe it should say "SocketIO subsystem initialized for eventlet" so that it is more clear that this is necessary for main and auxiliary processes.

**Comment by gordol** [comment]
Hmm... I see. Thanks for the quick feedback.

So, assuming it *is* listening, as I had it originally configured... with the app context being passed in: what are the drawbacks?

Soon I will push that change to our production environment, and I will know first-hand, from looking at various metrics, but I was just curious, and wishing to know in advance.

Further, is there any drawback from using message_queue in the server config too? Or should I make sure message queue is *only* used when running from workers?

**Comment by miguelgrinberg** [comment]
If you don't call the run() method, then the server is not listening. Not passing the app configures "write-only" support in the message queue, which is a good idea, since receiving data on one of these auxiliary processes serves no purpose.

The message queue argument needs to be given in all processes. This is so that all these processes communicate with each other.

**Comment by gordol** [comment]
> Not passing the app configures "write-only" support in the message queue, which is a good idea, since receiving data on one of these auxiliary processes serves no purpose.

Thanks, that's indeed what I was trying to figure out...

I see now...

In [`__init__.py`](https://github.com/miguelgrinberg/Flask-SocketIO/blob/61c179d337428224b58f7c062b139db3df843152/flask_socketio/__init__.py#L212-L217):
```python
        if app is not None:
            # here we attach the SocketIO middlware to the SocketIO object so it
            # can be referenced later if debug middleware needs to be inserted
            self.sockio_mw = _SocketIOMiddleware(self.server, app,
                                                 socketio_path=resource)
            app.wsgi_app = self.sockio_mw
```

So it's still spinning up a "server" as in, the resources are allocated, a flask app is instantiated, etc... it's just not attaching it to the wsgi middleware, which wouldn't matter anyway, since these processes are not proxied via our web server anyway. 

So each backend worker is basically running its own socket.io server instance, but that server isn't "served". Am I understanding correctly?

Thanks!

**Comment by gordol** [comment]
I think I get it now...


In [`__init__.py`](https://github.com/miguelgrinberg/Flask-SocketIO/blob/61c179d337428224b58f7c062b139db3df843152/flask_socketio/__init__.py#L170-L180):
```python
            write_only = app is None
            if url:
                if url.startswith('redis://'):
                    queue_class = socketio.RedisManager
                elif url.startswith('zmq'):
                    queue_class = socketio.ZmqManager
                else:
                    queue_class = socketio.KombuManager
                queue = queue_class(url, channel=channel,
                                    write_only=write_only)
                self.server_options['client_manager'] = queue
```

Then over in [python-socketio, in the base pubsub_manager class, we have the _thread method at the bottom](https://github.com/miguelgrinberg/python-socketio/blob/b62e5e2a7a9577f07f2b634b44aab6348ae62849/socketio/pubsub_manager.py#L129):
```python
    def _thread(self):
        for message in self._listen():
            data = None
            if isinstance(message, dict):
                data = message
            else:
                if isinstance(message, six.binary_type):  # pragma: no cover
                    try:
                        data = pickle.loads(message)
                    except:
                        pass
                if data is None:
                    try:
                        data = json.loads(message)
                    except:
                        pass
            if data and 'method' in data:
                if data['method'] == 'emit':
                    self._handle_emit(data)
                elif data['method'] == 'callback':
                    self._handle_callback(data)
                elif data['method'] == 'close_room':
                    self._handle_close_room(data)
```

So that never runs if app is None. Got it!

**Comment by gordol** [comment]
Yep... 

So in the Redis implementation, `_listen()` is never called, just `_publish()`.

Thanks for the pointers!

**Comment by gordol** [comment]
So, one more question...

When the processes *are* listening... and aren't in read-only mode...

```python
    def _handle_callback(self, message):
        if self.host_id == message.get('host_id'):
            try:
                sid = message['sid']
                namespace = message['namespace']
                id = message['id']
                args = message['args']
            except KeyError:
                return
            self.trigger_callback(sid, namespace, id, args)
```

Basically, are all of them are receiving the emits, they just filter it based on the host ID...

So, if I spin up 5 "server" instances, are they all receiving every emit, then? Even if that client is not active in that process?

**Comment by miguelgrinberg** [comment]
All the server processes receive the emits. There is no way to know which server process(es) have the client(s) that are part of an emit. Each server searches its own client list to see if any of its clients is an addressee.

**Comment by gordol** [comment]
Fair enough... That's a simple way to do it, but I'm concerned about scalability.

Are you open to consider a PR that allows to optionally store and reference the clients along with their host assignment via kombu or redis or something to facilitate better scalability?

**Comment by miguelgrinberg** [comment]
I do not follow your reasoning about this solution not being scalable, but as a general principle, sure, if you think you can improve on anything the server does I'm open to a PR.

**Comment by gordol** [comment]
So, basically it's fanning out data to every server, then the server throws it away if it doesn't match.

So, if you spin up 50 server instances, and have a high throughput of data, it's going to blow up all your services, instead of intelligently routing messages to specific backends. 

Why can't we just store SID as key, with value being the host that SID lives on? Then each host can listen to a private channel, instead of a global one.

I think this could possibly be implemented just by hacking on top of the channel functionality using some hooks or something to store the client/host mappings, but it might be cleaner if this was supported natively.

Hmmm....

**Comment by gordol** [comment]
We're doing this already, but it's in-process, instead of in a shared state.

**Comment by miguelgrinberg** [comment]
I don't think you are making anything more scalable, you are just shifting things around. If you need to broadcast to 100 clients, now you need to run 100 db queries before you know which hosts to contact. And BTW, what kind of database do you need that does not become a bottleneck in your example scenario of having 50 hosts all using it at the same time? How efficient is this db going to be when you have millions of clients? What happens if a host crashes and is unable to remove its clients from the database?

As I said above, if you propose a realistic solution that improves some configurations without adversely affecting others, I'm more than willing to consider it.

**Comment by gordol** [comment]
> what kind of database do you need that does not become a bottleneck in your example scenario of having 50 hosts all using it at the same time?

Redis can handle this, easily, without breaking a sweat.

> How efficient is this db going to be when you have millions of clients?

Redis can handle millions of clients with no problem, especially if you shard it.

Anyway, it really just depends how you structure the pubsub, architecturally...

Perhaps a mapping of SID -> Host is not the best way to do it...

Regarding redis...

The amount of time to create the subscriptions for a client is O(number of subscriptions for that client), and the amount of time to send a message to a particular channel is O(number of subscribers to that channel).

So it's a simple matter of deciding, do you want to store hosts, and look up SID, or do you store SID to lookup the host? Or something totally different...

Every SID is unique, right? So what if you just have SID channels, and then the host subscribes to the SID channels for clients that are served by it. In that case, this will *always* be a 1->1 mapping, right? Then to emit to a given client, only on that host, you simply publish a message to that client's private SID channel, which the host is subscribed to.

> What happens if a host crashes and is unable to remove its clients from the database?

Just use a lock. If the lock breaks from the host disconnecting, be it intentional or a crash, the channel is closed.

As a tangent, you could even go further with that, and when a host crashes and doesn't close the room gracefully, the client reconnects from the other end, and, if you know what the SID was previously, and you queue messages to the old SID that had no host, and push them to the new SID channel, you are ensuring delivery. This also opens the door to things like doing hand-offs from host to host, so you can restart host processes sequentially and gracefully, by moving clients to a new host, but that's pretty far beyond the scope of this discussion, just where my brain goes when I start digging into stuff like this.

Thanks again for your time and input.

**Comment by miguelgrinberg** [comment]
I think you are oversimplifying this problem, but in any case, if you come up with an implementation that can be enabled as an alternative to the current one, I'm 👍

**Comment by gordol** [comment]
As for ensuring the hosts don't die and drop the clients... It's pretty trivial to implement [distributed locking with redis](https://redis.io/topics/distlock). That way, you can ensure, if a host dies, that one will come back around to setup the pubsub stuff again.

**Comment by miguelgrinberg** [comment]
Unfortunately I don't have time to review the above example and even less to make an implementation of this if it turns out to be a good solution. My offer still stands, if you can make a PR that does not break existing functionality and adds this as an option, I'm happy to consider it.
