### ISSUE TITLE
socketio.emit silently fails when given numpy nan data. 

### ISSUE THREAD

**Issue by trentkg** [miguelgrinberg/Flask-SocketIO#544]
Hey -

I found this bug while publishing large datasets that had a few nans here and there. If the dataset had any nans in any fields, the whole call to emit does nothing.  My guess is its a problem with serialization? Maybe it cannot handle nans? I have seen this problem in many other serialization protocols where nan values are not properly handled. 

Here is an example using python 2.7 and flask_socketio 2.9.7. Launch the script using python, and open the console in your browser to see the updates. 

```python
from flask import Flask
from flask_socketio import SocketIO
import sys
from numpy import nan
import eventlet
import time
import threading

socketio = SocketIO(async_mode='eventlet')
app = Flask(__name__)

app.config['SERVER_NAME'] =  None

assert app.config['SERVER_NAME'] is not None, "you need to change the server name"

socketio.init_app(app)

def publish(socket):
    index = 0
    while True:
        if (index % 2) == 0:
            print 'emitting nan update!'
            socket.emit('nanupdate', {'upd': nan })
        else:
            print 'emitting update!'
            socket.emit('update', {'upd': 1.0 })
        index += 1
        time.sleep(1)

eventlet.monkey_patch()
t = threading.Thread(target=publish, args=(socketio,), name="publisher thread")
t.daemon=True
t.start()

@app.route('/')
def index():
    sio_init =  """
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.0.3/socket.io.js"></script>
        <script>
                var socket = io.connect(window.location['href']);

        socket.on('update', function(data) {
                console.log('update recieved!');
                console.log(data);
        });
        socket.on('nanupdate', function(data){
            console.log('nanupdate recieved!');
            console.log(data);
        });
        </script> """
    return '   socket io test example ' + sio_init

socketio.run(app, host='0.0.0.0')

```

**Comment by miguelgrinberg** [comment]
Messages between Socket.IO server and client are encoded as JSON. The JSON spec does not define a valid value for "nan", but that is considered to be an omission, and JSON implementations usually do support it with the JavaScript syntax of `NaN`. Python is actually able to encode nan in a JSON payload:

```python
>>> import json
>>> from numpy import nan
>>> json.dumps({'foo': nan})
'{"foo": NaN}'
```

So from the Python's side, this is all fine. The packet is dropped by the Socket.IO client in the browser, which does not seem to like the `NaN`. Here is a snippet of client-side logs:

![screen shot 2017-09-08 at 2 57 16 pm](https://user-images.githubusercontent.com/2715854/30232757-997cab1a-94a6-11e7-9a59-db91780aaf92.png)

**Comment by trentkg** [comment]
Thanks for the quick response Miguel! I've added this case to my serverside function which ensures the data I send to the client is json serializable.  Here is a snippet, it takes a pandas dataframe as an input :
`    def make_json_serializable(df):
        '''Converts a pandas dataframe to a  json serializable object'''
        for col in df:
            if any(df[col].apply(lambda x: type(x) in (datetime, time,pd._libs.tslib.Timestamp))):
                df[col] = df[col].apply(str)
            else:
                try:
                    nans = isnan(df[col])
                    if any(nans):
                        df.loc[nans,col] = "NaN"
                except TypeError:
                    pass #isnan fails on non number types.
        return df.to_dict('records')
`

This function is not very robust though. I will have to keep adding cases for types as I find them - for instance, socketio.emit throws an error if I try to send nested lists to the client. 

Is there a more robust method of ensuring that data I send to the client is always json serializable? Can I call json.dumps on the data, and then socketio.emit, or will that just send a string?

-Trent

**Comment by miguelgrinberg** [comment]
Hmm. List of lists should work just fine. Can you show me an example of the data that fails, and the error that you get?

Regarding the serialization, one thing you can do is to use a custom JSON encoder that handles those invalid objects in some way. I found one possible implementation in the accepted answer for [this SO question](https://stackoverflow.com/questions/3768895/how-to-make-a-class-json-serializable). The custom encoder works as follows (copied from that answer):

```python
>>> f  = FileItem("/foo/bar")

>>> from json import JSONEncoder
>>> class MyEncoder(JSONEncoder):
        def default(self, o):
            return o.__dict__

>>> MyEncoder().encode(f)
'{"fname": "/foo/bar"}'
```
