### ISSUE TITLE
webpage only can get the latest state of background process by refresh the webpage 

### ISSUE THREAD

**Issue by IvyGongoogle** [miguelgrinberg/Flask-SocketIO#545]
hello, I have a painful problem. I use Flask-SocketIO to update the some states of background process onto webpage.
For my example, my app is put in machine A with IP 170.8.8.8 monitoring port 5000, and I put nginx in machine B with IP 170.8.8.9 also monitoring port 5000. So I want to visit IP:5000 in B which skip to IP:5000 in A. The below is my nginx config in machine B:

```
upstream cuitccol.com{ #the name of server cluster
		server 170.8.8.8:5000 max_fails=5 fail_timeout=50s; #for the first web server
		}

    server {
        listen       5000;
        server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
			proxy_pass http://cuitccol.com;
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
			proxy_set_header Host $host;
        } 
```
If I directly visit IP in A, the webpage of my browser can constantly updates the state of the background process. but if I visit B where nginx is put, the the webpage can not constantly updates the state, and I must refresh the webpage to get the next state. and the console of my browser has a mistake as below:

`WebSocket connection to 'ws://170.8.8.9:5000/socket.io/?EIO=3&transport=websocket&sid=4a2ec29f7f834a0bb289b21f03c3e47c' failed: Error during WebSocket handshake: Unexpected response code: 200`

I do not know where goes wrong. nginx or flask-socketio? Can you give some advises?
thank you very much~
looking forward to your reply

**Comment by miguelgrinberg** [comment]
See the documentation for an example nginx configuration for Socket.IO. Let me know if you continue to see failures with that configuration.

**Comment by IvyGongoogle** [comment]
@miguelgrinberg I follow the documentation and use the configuration below:

```
location / {
        proxy_pass http://cuitccol.com;
        proxy_http_version 1.1;
    } 

   location /socket.io {
        proxy_pass http://cuitccol.com/socket.io;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    } 
```
And it works for me.  Thank you very much~
