### ISSUE TITLE
Shutting the server down

### ISSUE THREAD

**Issue by egorf** [miguelgrinberg/Flask-SocketIO#546]
Hello,

I've been trying to make my app shutdown by catching a signal. Apart from the server, I need to perform some additional operations. So I created a handler in which I want to shutdown the server and the rest.

Docstring for SocketIO.stop() says it must be performed inside a HTTP/WebSocket handler, presumably for the context. So far I've tried two strategies:

* Try to call `stop()` with `app.context()`
* Try to register a special handler from which to call `stop()` and use a TestClient to trigger the event. Doesn't seem to work in production mode, though.

Both of these result in the app hanging.
Any advice on how work around this?

I am using eventlet, btw.

**Comment by jwg4** [comment]
Do you want to shutdown down in response to a SocketIO signal or an operating system signal?

**Comment by egorf** [comment]
@jwg4 Hi! I meant an OS signal.

**Comment by miguelgrinberg** [comment]
The `stop()` function is meant to be called from a real handler, dispatched by the web server. The use case I intended to solve with this functionality was not the Ctrl-C case, but handling a server that is started only to run tests on. The test script could start the server as a separate process or thread, do what it needs to do, then send a request to an endpoint such as `/stop` to make the server end gracefully.

**Comment by egorf** [comment]
@miguelgrinberg 
That is kind of what I am looking for. While I can perform an HTTP request from my code, I don't know if I can trigger a socket.io event. This question is more of curiosity.

**Comment by miguelgrinberg** [comment]
@egorf you can only send a socket.io event if you use a socket.io client such as [this one](https://pypi.python.org/pypi/socketIO-client-2). If you don't already use a socket.io client in your application, then I would not do this and send the stop request via HTTP, which is much easier.

**Comment by egorf** [comment]
@miguelgrinberg 
Definitely easier. One little aspect, though. I wanted to make my app exit cleanly by handling SIGINT in a nice way. However, seems like the signal handler takes away server's execution in some fundamental way(talking about the eventlet.monkey_patched runtime here). 

I can not make a request from a handler in a blocking manner. I also can not start a thread making a request. The whole thing simply hangs. One working solution is using subprocess.Popen to perform the request via wget or curl, but frankly it's a little to insane to use it :)

**Comment by miguelgrinberg** [comment]
> I can not make a request from a handler in a blocking manner

You can never make a request in a blocking manner. Eventlet gives you the illusion that your calls are blocking, but they are not. I don't know how much of the async scheduling is still up during the exit, but yeah, I don't think you can rely on that being available.

instead, what I would recommend is that you issue all your heavy weight exit actions before you call the `stop()` function.

**Comment by egorf** [comment]
@miguelgrinberg That's not what I meant exactly, but it's ok. Thank you for the clarifications!

**Comment by qwfy** [comment]
@miguelgrinberg 

> instead, what I would recommend is that you issue all your heavy weight exit actions before you call the `stop()` function.

When you stop a system, you usually shutdown the interface to the out world first, to stop further requests to enter the system, then your perform the cleanups.

**Comment by miguelgrinberg** [comment]
@qwfy you did not read the context of this problem apparently. The problem here is about stopping a server by sending a request to it. You can't shutdown the network interface and then send the stop request, can you?
