### ISSUE TITLE
502 Bad Gateway error with uWSGI, nginx, and SSL

### ISSUE THREAD

**Issue by najarvis** [miguelgrinberg/Flask-SocketIO#547]
Since incorporating sockets into our project I keep getting a 502 error, and I think it's coming somewhere from the nginx config file. 

This is the error I keep getting in my nginx/error.log file

    2017/09/11 18:40:33 [error] 2223#2223: *5 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.91.239.146, server: <sitename>.com, request: "GET /workout_status/Abs%20And%20Cond      itioning HTTP/1.1", upstream: "uwsgi://unix:/home/jarvis/<projname>/<projname>.sock:", host: "<sitename>.com", referrer: "https://<sitename>.com/vertical_view/tst/Abs%20And%20Conditioning/3/"

and this is my nginx/sites-available/<projname> file

```
server {
     listen 443 default_server ssl;
     listen [::]:443 default_server ssl;

     ssl_certificate /etc/letsencrypt/live/www.<sitename>.com/fullchain.pem;
     ssl_certificate_key /etc/letsencrypt/live/www.<sitename>.com/privkey.pem;

     server_name <sitename>.com www.<sitename>.com 45.55.166.246;

     location / {
         include uwsgi_params;
         include proxy_params;

         uwsgi_pass unix:/home/jarvis/<projname>/<projname>.sock;

         proxy_pass https://<sitename>.com:5000;
         proxy_redirect off;
     }

     location /socket.io {
         proxy_pass https://<sitename>.com:5000/socket.io;
         proxy_redirect off;
         proxy_buffering off;

         proxy_set_header Host $host;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

         proxy_http_version 1.1;
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection "Upgrade";
     }
 }

server {
     listen 80;
     listen [::]:80;

     server_name <sitename>.com www.<sitename>.com 45.55.166.246;

     return 301 https://$host$request_uri;
}```

<sitename> and <projname> is just replaced by the sitename or project name respectively

**Comment by miguelgrinberg** [comment]
Why do you have proxy_pass and uwsgi_pass together? Shouldn't you have just one of them?

**Comment by najarvis** [comment]
Got rid of wsgi like you recommended in the reddit post and it seems to be working now, thank you!
