### ISSUE TITLE
Artillery and flask-login

### ISSUE THREAD

**Issue by amiguet** [miguelgrinberg/Flask-SocketIO#549]
Hello,

I'm trying to use artillery to do load-testing on a flask-socketio server with artillery as suggested by @andmekaevur  in #548.

I'm using flask-login to handle authentication: first a traditional http authentication is done, then the socket.io event handlers check that `current_user.is_authenticated`. 

This works fine in many browsers, but when I try to run an artillery scenario, the http authentication works fine and `current_user.is_authenticated` is `True` in a traditional `@app.route`,  but still `False` in socket.io event handlers.

Any idea what's going wrong? or can someone suggest a load-testing tool that would play well with flask-socketio and flask-login?

Thanks,

Matthieu

**Comment by miguelgrinberg** [comment]
I don't use Artillery myself, but is it configured to honor cookies? If they are not sending cookies, then Flask-Login is not going to work.

**Comment by amiguet** [comment]
Artillery honors cookies: https://artillery.io/docs/http-reference/#cookies

As a matter of fact, it does work for http requests, it's only the socketio part that doesn't work. 

I'm not sure how cookies and socket.io play together, though... flask-socketio+flask-login make it just work, so I'm not sure how this works under the hood. Maybe there's some magic that isn't reproduced by artillery?

How do you guys load-test your flask-login apps? is there another tool that plays well with flask-socketio+flask-login?

**Comment by miguelgrinberg** [comment]
Right, what I meant is if Artillery sends cookies set through HTTP with the Socket.IO requests. Flask-Login is going to set a cookie on the HTTP side, and that cookie needs to be sent with the Socket.IO connection request for everything to work. I bet that is not being done.

**Comment by amiguet** [comment]
I see. With a quick search through artillery's documentation, I could not find a way to send the cookie along with the socket.io connection. I'll have to investigate and/or find another way to test. Thanks for your help!

**Comment by amiguet** [comment]
For the record, I seem to be able to simulate a few dozen users with python+selenium+PhantomJS. That should be enough for the first tests...
