### ISSUE TITLE
Catching exception raised by gevent

### ISSUE THREAD

**Issue by j-o-d-o** [miguelgrinberg/Flask-SocketIO#555]
To avoid multiple connections from the same user I check if the user already has an active connection on the "connect" event and if yes I disconnect the old connection like this:
`socketio.server.disconnect(sid)`

This raises this exception:
```
ConnectionAbortedError: [WinError 10053] Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen
Tue Sep 26 10:49:32 2017 {'REMOTE_ADDR': '127.0.0.1', 'HTTP_HOST': 'localhost:5000', 'REMOTE_PORT': '56075', (hidden keys: 24)} failed with ConnectionAbortedError
```

Translated: An open connection was closed by the host computer from code. Which is exactly what happend and intended. I just don't know how to catch the exception. I don't want to have this exception in my console every time this happens. 

A try/except around the disconnect() function does not work... 

How can I catch the exception?

EDIT: This is also not working:
```
@socketio.on_error()  # handles all namespaces without an explicit error handler
def another_error_handler(e):
    print("ERROR")
    pass
```

**Comment by miguelgrinberg** [comment]
Did you try returning `False` from the connect handler? And example of authenticating users in the connect event is shown here: https://flask-socketio.readthedocs.io/en/latest/#using-flask-login-with-flask-socketio

**Comment by j-o-d-o** [comment]
I don't have any authentication. All I want is, that a maximum number of 1 User can be connected via SocketIO and the most recent user is always the "active" user. This is the code for the connect handler:

```
@socketio.on('connect')
def connect_handler():
    print("Client connected")
    global connected_clients
    for sid in connected_clients:
        socketio.server.disconnect(sid)
    connected_clients = []
    connected_clients.append(request.sid)
```

**Comment by miguelgrinberg** [comment]
@j-o-d-o doesn't matter, the point I was trying to make is that if you want to reject a connection, you just need to return `False` from the connect handler. No need to explicitly disconnect, since the connection hasn't been fully established yet.

**Comment by j-o-d-o** [comment]
Okay, but I always want to have the most recent one to be "active". Therefor cancel all of the old connections.

**Comment by miguelgrinberg** [comment]
Oh, okay, I understand what you are trying to do now. I also just realized that you are using Windows. What version of Python are you using? I recall there is some sort if weird issue on Python 2 related to closing sockets. If you are using Py2, you may want to repeat the test with Py3 and see if that helps.

**Comment by j-o-d-o** [comment]
I am using python 3.5.4. I have tried some things and it turns out, that eventlet does not throw this exception and the connecting and disconnecting works fine. 
But the issue with eventlet is, that sometimes events don't fire until much later when there are some heavier calculations going on at the backend. With gevent this does not happen. But I guess this is a story for another issue.
Thanks for your help!

**Comment by miguelgrinberg** [comment]
@j-o-d-o Heavy calculations are the mortal enemy of async servers. You can't allow any thread to spend too much time using the CPU because that delays everything. You may want to sprinkle some `socketio.sleep(0)` inside the code that does these calculations so that periodically there is a chance for other tasks to run.

**Comment by j-o-d-o** [comment]
I can't / shouldn't access the code that does the calculations... But the current setup & performance satisfies my needs for now. Sadly there are more urgent things I have to deal with and I can't look into it further :(. Thanks a lot for your help and the effort you put into this project!
