### ISSUE TITLE
emit broadcast not reaching all clients

### ISSUE THREAD

**Issue by PrecisionWaveRF** [miguelgrinberg/Flask-SocketIO#560]
First, thank you for that nice piece of code. 

A little desperate I have a question regarding client types and what might go wrong with broadcasts. Some of the clients that connect to our webapp do not receive broadcasts sent by socketio.emit. 
Unfortunately on all my machines that I have tried to reproduce the problem (linux/win with browsers edge, chrome, firefox) the app works fine - so it is really hard for me to fix it. Some of our clients however regularly report that the app is not working/not showing any information that is sent by a broadcast emit.

Maybe you have an idea on what I could possibly have done wrong: 

**task/intention** 
send a struct of hardware status information to all clients connected - at relatively high pace (0.15sec).

**problem** 
some clients do not receive sent message, others do

**code**
the broadcast thread (spawned by `app.broadcastthread = Thread(target=broadcast_stats, daemon=True)`) we have: 
```
def broadcast_stats:
    loop=True
    while loop:
        dat = getStats()
        socketio.emit('statusmessage', {'data': dat}, namespace='/stats', broadcast=True)
        time.sleep(0.15)
```

our app looks more or less like:
```
import eventlet
eventlet.monkey_patch()
...
app = Flas(__name__)
socketio = SocketIO(app, async_mode='eventlet')
...
if __name__ == "__main__":
    socketio.run(app, host='0.0.0.0')

```
while on the client side tha javascript looks as follows:
```
$(document).ready(function(){
    var namespace = 'stats';
    var port = location.port ? ':'+location.port : '';
    var socket = io.connect('http://' + document.domain + port + '/' +namespace);
   ...
   socket.on('stats', function(msg) {
       parseMessage(ms, renderStats);
   });
}
```
**nxinx configuration**
```
upstream app_server {
    server unix:/pathto/webctrl.sock fail_timeout=0;
    keepalive 2;
}

server {
    listen 80;
    client_max_body_size 4G;
    server_name 0.0.0.0;
    keepalive_timeout 5;
    root /pathto/app/static;

    location / {
      try_files $uri @proxy_to_app;
      add_header Cache-Control no-cache;
    }

    location @proxy_to_app {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        add_header Cache-Control no-cache;
        proxy_redirect off;
        proxy_pass http://app_server;

    }
    location /socket.io {
        include proxy_params;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_read_timeout  3600;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass http://app_server/socket.io;
        add_header Cache-Control no-cache;
    }
}
```
and upstart is configured to start gunicorn with `exec venv/bin/gunicorn --worker-class eventlet -w 1 --bind unix:webctrl.sock -m 007 wsgi:application`

**setup** 
- Flask (0.12.2)
- Flask-SocketIO (2.9.0)
- gunicorn (19.7.1)
- eventlet (0.21.0)
- python 3.4
- proxy: nginx

***comment***
I appreciate if you find any misconfiguration or any hints towards what might go wrong when some clients just don't receive stats messages. Or what I could be seeking for? (I checked for unsupported browsers and enabled javascript). 
note: our app is not intended for more than 2-4 connections (actually 1 is default as it is a plain hardware configuration site).

**Comment by miguelgrinberg** [comment]
Nothing wrong that I can see in your code or configuration. You need to enable logging (add `logger=True, engineio_logger=True` to your `SocketIO()` constructor) so that you can see what happened when a client was not receiving the broadcasts.

Also it would be useful if you can ask your users to look at the web console to see if there are any errors there.

**Comment by PrecisionWaveRF** [comment]
Thanks for your message. 
I got a hand on a machine where things seem to go bad. What the debugger (Edge in this case) shows is the following:
![image](https://user-images.githubusercontent.com/20150643/31319487-5e62b486-ac64-11e7-8f20-6656112c7dac.png)
I'll be back with a log-report as you suggested.

**Comment by PrecisionWaveRF** [comment]
just to report back on the issue: the timeouts still appear and connections get re-established. We have not further investigated this as the actual reason for our application not working on all browsers is that we have been using the "log10" function in JavaScript which is not supported in all browsers and somehow led the socket connection to a crash. If there is time we'll get back on the websocket timout issue.

**Comment by miguelgrinberg** [comment]
Please reopen if you need help with this issue still.
