### ISSUE TITLE
How to leave all rooms?

### ISSUE THREAD

**Issue by netik25** [miguelgrinberg/Flask-SocketIO#562]
I'm joining rooms by sending some join messages to the server and passing alone some room id:

```
@socketio.on('join')
def on_join(data):
    join_room(data['room'])
```

but how I can make the client leave all rooms first, such that he will only be in one room afterwards?

**Comment by miguelgrinberg** [comment]
The `rooms()` function tells you what rooms the client is in. You can leave all rooms with the following code:

```
@socketio.on('join')
def on_join(data):
    for room in rooms():
        if room != request.sid:
            leave_room(room)
    join_room(data['room'])
```

**Comment by netik25** [comment]
Perfect! Thank you !
