### ISSUE TITLE
Is gunicorn 18.0 still preferred over 19.x?

### ISSUE THREAD

**Issue by nomadlogic** [miguelgrinberg/Flask-SocketIO#563]
Hi there - I'm debugging an issue where we are running flask-socketIO, gevent and gunicorn.  As part of our debugging process we are re-validating our dependencies and systems configuration against the docs.  I noticed this bit and was wondering if it was still valid.

(from https://flask-socketio.readthedocs.io/en/latest/)
`Gunicorn release 18.0 is the recommended release to use with Flask-SocketIO. The 19.x releases are known to have incompatibilities in certain deployment scenarios that include WebSocket.`

if this is still valid would someone be able to point me at a ticket or discussion as to what the issue with gunicorn 19.x is so that we can verify if we are running into it or not?

**Comment by miguelgrinberg** [comment]
No. I should actually remove that note, it is outdated. The problems with newer gunicorn releases have been resolved, at least I have been using the latest 19 version without problems.
