### ISSUE TITLE
@copy_current_request_context seems to break connections

### ISSUE THREAD

**Issue by SWIFTingAround** [miguelgrinberg/Flask-SocketIO#566]
In our project, `@current_request_context` seems to be causing problems. When this decorator is used, clients will no longer receive messages from the server. The connection can only be re-established after some time, which also has the disadvantage that the session ID changes.

We didn't find a solution to the problem, and therefore we don't use the decorator anymore.

**Comment by miguelgrinberg** [comment]
Were you using the decorator on a Socket.IO event handler? Can you show me an example?

**Comment by SWIFTingAround** [comment]
I don't have the code at the moment, because we don't use it anymore. It looked something like this from the principle:

```python
@socketio.on('event') 
def event_triggered(message): 
    @copy_current_request_context 
    def forward_event(message_):
        emit("forwarded_event", message_)
 
    g_timer = Timer(3.0, forward_event, (message)) ```

**Comment by miguelgrinberg** [comment]
@SWIFTingAround If you are using eventlet or gevent you have to monkey patch the standard library for `Timer` to work. With monkey patching, your example above works well for me.

**Comment by SWIFTingAround** [comment]
Ah, alright. We didn't monkey patched the library, maybe this were the error, thanks.
