### ISSUE TITLE
use_reloader hangs background task

### ISSUE THREAD

**Issue by ryanberthold** [miguelgrinberg/Flask-SocketIO#567]
Background tasks hang if `use_reloader=True` (or `debug=True`) is passed to socketio.run().  Example socketio_reload.py:

```python
#!/usr/bin/env python2
import sys
import time
import flask
import flask_socketio

app = flask.Flask(__name__)
socketio = flask_socketio.SocketIO(app)

def background():
    print 'background'
    while True:
        print time.time()
        socketio.sleep(1)

socketio.start_background_task(background)

if __name__ == '__main__':
    use_reloader = '--use_reloader' in sys.argv
    print 'use_reloader:', use_reloader
    socketio.run(app, host='0.0.0.0', port=5500, use_reloader=use_reloader)
```

Sample output:
```
$ ./socketio_reload.py
background
1508196843.42
use_reloader: False
1508196844.42
1508196845.43
1508196846.43
^C

$ ./socketio_reload.py --use_reloader
background
1508196855.79
use_reloader: True
 * Restarting with stat
background
1508196856.21
use_reloader: True
^C
```
In the last example there is no further output after the second 'use_reloader: True' line.  The app continues to serve requests, and less-minimal examples show that the background task never exits, so it seems that the eventlet scheduler has forgotten about the background task.  I've tried checking $WERKZEUG_RUN_MAIN to make sure the background task only starts once, either before or after the initial reload, but this doesn't seem to make any difference.

There's also the issue of what happens to existing background tasks on reload.  Is it possible to raise an exception in their execution context so they can clean up after themselves?

Python version:
```
Python 2.7.14 (default, Oct 16 2017, 13:26:08)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
```
Virtualenv pip freeze:
```
click==6.7
enum-compat==0.0.2
enum34==1.1.6
eventlet==0.21.0
Flask==0.12.2
Flask-SocketIO==2.9.2
greenlet==0.4.12
itsdangerous==0.24
Jinja2==2.9.6
MarkupSafe==1.0
python-engineio==1.7.0
python-socketio==1.8.1
six==1.11.0
Werkzeug==0.12.2
```

**Comment by miguelgrinberg** [comment]
It is possible that the reloader requires the Python standard library to be monkey patched so that it is compatible with eventlet. Try adding the following at the top of your script (above the imports):

```python
import eventlet
eventlet.monkey_patch()
```

**Comment by ryanberthold** [comment]
Thanks for the suggestion, I got it to work after dealing with the following issues:

 - Call `eventlet.sleep()` before `eventlet.monkey_patch()` to work around recent bugs (see  [https://github.com/eventlet/eventlet/issues/401](url) and [https://github.com/eventlet/eventlet/issues/428](url))

 - Check `os.environ.get("WERKZEUG_RUN_MAIN") == "true"` to avoid running background task in reloader process

 - Kill background task on exit, since the reloader waits for the old process to finish before it spawns a new one.  I did this using a `Queue`, but maybe there's a better way.

 - Reraise exceptions from `socketio.run`; the reloader looks for a particular exit code (3) or it bails out.

Updated example below.  I recommend updating the `start_background_task` documentation to warn users of these issues, with the suggestion that they simply pass `use_reloader=False` to the `socketio.run` function.

```python
#!/usr/bin/env python2

import eventlet
eventlet.sleep()
eventlet.monkey_patch()

import os
import sys
import flask
import flask_socketio
import Queue
import traceback

app = flask.Flask(__name__)
socketio = flask_socketio.SocketIO(app)

q = Queue.Queue()
count = 0
def background():
    global count
    print 'background start.'
    while True:
        count += 1
        print count
        try:
            q.get(timeout=5.0)
            break
        except:
            pass
    print 'background done.'
 
if os.environ.get("WERKZEUG_RUN_MAIN") == "true":
    socketio.start_background_task(background)

@app.route('/')
def index():
    return str(count)

if __name__ == '__main__':
    try:
        print 'main.'
        socketio.run(app, host='0.0.0.0', port=5500, debug=True)
    except:
        raise
    finally:
        q.put('x')
        socketio.sleep(0)
        print 'main done, count:', count


```

**Comment by miguelgrinberg** [comment]
This bit of code seems wrong to me:

```python
if os.environ.get("WERKZEUG_RUN_MAIN") == "true":
    socketio.start_background_task(background)
```

This is only going to start the background thread when you run inside the reloader. If you run w/o it, or with another web server that is not Werkzeug, your thread will not start.

An alternative to using a `Queue` would be to use the `Event` class, which has a true/false state, instead of having to push bogus data to a queue.

Regarding the eventlet bug, I tend to avoid the latest releases. This isn't the first time something breaks on the cutting edge versions. Better to be one or two releases behind.

**Comment by ryanberthold** [comment]
True, it ought to be something like:
```python
if (__name__ != '__main__'  # external server
        or not use_reloader  # from options
        or os.environ.get("WERKZEUG_RUN_MAIN") == "true"):  # reloaded subprocess
    bg = socketio.start_background_task(background)  # or other heavy init
```
Or could use the `before_first_request` decorator if we don't mind a long load for the first client.
