### ISSUE TITLE
(JWT-)Token based Authorisation

### ISSUE THREAD

**Issue by SebastianBerchtold** [miguelgrinberg/Flask-SocketIO#568]
Hello,

First of all, thanks for the great software.

I couldn't find anything how do an authorisation by JWT-tokens in flask-socketio on the net,
only a comment of Miguel at the very botton of [this post](https://blog.miguelgrinberg.com/post/flask-socketio-and-the-user-session), that it is possible,

So I'm basically asking for the proper way do this. Here's the rather long story of what I've tried so far:

After reading a bit on how to this with the default Javascript client/server,
I figured there are basically two ways to do it:

1. Sending the token as in event, e.g. `authorisation`.
2. Sending the Token in the header or as a query parameter.

For the first methods it seems a bit tricky, to ensure that nothing happens between `connect` and `authorisation`.
(Would it be enough, to just remove, the client from the default room (and or namespaces?) in the `connect` event and rejoin after authorization is confirmed?)

So I decided to go with the second method, as suggested in the [docs](https://flask-socketio.readthedocs.io/en/latest/#using-flask-login-with-flask-socketio).
(I assume if the `connect` event returns `False`, it is ensured, that the client can never send or recive any events from the server?)

So I just added the 'Authorization' token to the header, and checked by a code similar to:

```python
from flask_jwt import _jwt
def on_connect(self):
    token = _jwt.request_callback()
    if token is None:
        return False
    try:
        payload = _jwt.jwt_decode_callback(token)
    except jwt.InvalidTokenError as e:
        return False
```

This worked just fine with the [python socketio_client](https://github.com/invisibleroads/socketIO-client).

But the default JS socket.io client, cannot add extra headers in the browser.
Even if this is supposed to work, as described e.g. [here](https://stackoverflow.com/questions/23406163/socket-io-client-how-to-set-request-header-when-making-connection) and [here](https://github.com/socketio/engine.io-client/issues/554),
it didn't work for me even with version 2.0.3 (no extra headers sent at all).

So I decided to just send the token with the query parameters, as a fallback method (with quite a bit of hesitation, it really doesn't seem like good practice to do this, but the JS guys seem ok with this ...). 
This also worked just fine with the python socketio_client, connecting like this

```python
socketIO = SocketIO('127.0.0.1', 5000, params={'token': 'mytoken'})
```

But using the JS client, this doesn't work, which brings me to my actual issue:

```javascript
const socket = io('localhost:5000/mynamespace', {query: {token: 'mytoken'}});
```

Enabling the `engineio_logger`, the relevant bits seems to be

```
sidblabla: Received packet MESSAGE data 0/mynamespace?token=mytoken
```

from the JS client, compared to the folloging from python socketio client?

```
sidblabla: Received packet MESSAGE data 0/mynamespace
```

So the engineio `_websocket_handler` method of the `Socket` (in engineio/socket.py), never triggers `self.server._trigger_event` (via `self.receive`) with the correct namespace `/mynamespace` like the python socketio_client , but seemingly `/mynamespace?token=mytoken`, as is also reflected in the request payload ('polling' as well as 'websocket'), with `0/mynamespace?token=mytoken` compared to `0/mynamespace`.

Is there an incompatibllity, between flask-socketio and the JS socket.io-client, concerning query parameters?
What is the actual way of handling query parameters, according to the socket.io spec, should they really be part of the payload (query params in the payload ...)?
Is there any spec, that treats this at all? [This here](https://github.com/socketio/socket.io-protocol) seems not to.

Am I just doing something wrong?

Any suggestions, on how to do a proper JWT authentification with flask_socketio would be very welcome.
Thank you.
Sebastian

**Comment by miguelgrinberg** [comment]
> Is there an incompatibllity, between flask-socketio and the JS socket.io-client, concerning query parameters?

Yeah, this is actually a bug in the JS client, that sends the query string attached to the namespace. I actually put in a bit of code to "tolerate" this bug in the server a couple of weeks ago, and the fix should be in the latest official release of `python-socketio`. Make sure you upgrade and I think you should be fine.

Regarding your overall question about proper way to do authentication, the three options that I have found to be reliable (in my order of preference) are using a cookie, the query string or the payload of an event. Headers have worked on and off, and also create complications when the connection goes directly to websocket because websocket connections cannot have custom headers.

If your server can set a cookie with the token beforehand that is the ideal, because then the browser will send that cookie in the connection request, and you can validate it on the connect handler. For added security, you can set the httpOnly flag on this cookie, and also the secure flag if you are doing HTTPS.

If you decide to use the query string, the latest python-socketio release should be able to handle that extra query string sent in the payload by the JS client.

**Comment by SebastianBerchtold** [comment]
Thank you very much for your quick response! I works now.
I had the latest version of Flask-SocketIO (2.9.2), but since the requirements are still set to an older version of python-socketio (1.6.1), pip never pulled the required release (1.8.1). 

The cookies seem not really to be an option for me, so I'll go with the query string and won't bother to much with the headers anymore. I'm still not entirely sure, how to prevent any data-leaks between connection and authorization, in case of using an event, but I guess the query string will be fine.

So thanks again, for your great software and amazing support.

**Comment by miguelgrinberg** [comment]
> I'm still not entirely sure, how to prevent any data-leaks between connection and authorization

I've done this in two different ways. One is to require the token in all events. Any events that don't have the payload are discarded. The other is to set some value in `session` once you receive a valid token. If the session does not have this value, the events are not carried out by the server.
