### ISSUE TITLE
server broadcast not working

### ISSUE THREAD

**Issue by ttback** [miguelgrinberg/Flask-SocketIO#57]
Simply not seeing the emit on the client side, not sure if I am missing something. (Note, the client-initiated calls are working properly)

Server:

def broadcast(movie_id, gif_id):
    socketio.emit('event name', json)

Client:
````
var global_socket = io.connect('http://' + document.domain + ':' + location.port);
		global_socket.on('event name', function(msg) {
			console.log("event name");
		});
````

**Comment by BlackstoneEngineering** [comment]
I know this is a closed topic, but posting this here as I had a similar issue, found this post via google and then spent several days figuring this out. 

To get the socketio.emit to work I had to use `socketio = SocketIO(app,async_mode='threading')` even though I wasn't actually using threading.

**Comment by James-Gallagher** [comment]
The example app is working fine, yet I cannot copy the code and use it in my website. Nothing connects. Have any ideas?

**Comment by jdormit** [comment]
@BlackstoneEngineering did you ever find a fix for this that preserves the ability to use WebSockets rather than long polling? I've run into the same issue.
