### ISSUE TITLE
Document may be outdated: gevent-websocket now supports Python 3

### ISSUE THREAD

**Issue by Xdynix** [miguelgrinberg/Flask-SocketIO#570]
The document mentions that

> The gevent-websocket package adds WebSocket support to gevent, but unfortunately this package is current only available for Python 2.

But gevent-websocket is now available for Python 3 on PyPi and there is also [commit that mentions Python 3 support](https://gitlab.com/noppo/gevent-websocket/commit/9b87b850f50bdce99561a95c561c01395a87df7c).

And it also works in my code. (Just simple hello world, no full test on it)

So I wonder if the document should be updated about that.

**Comment by miguelgrinberg** [comment]
Thanks, I agree, it seems I should update my docs, it appears the project has been finally ported.

**Comment by miguelgrinberg** [comment]
Already updated in #599
