### ISSUE TITLE
Message received twice

### ISSUE THREAD

**Issue by Zygonie** [miguelgrinberg/Flask-SocketIO#572]
I experience an annoying behavior. When I load a page, a message is sent to the client. However, no message is displayed until another client connects too, and then I have two messages. Another client does not increase the number of messages, I got also two messages. I tried with werkzeug, with or without gevent but the behavior is the same. Also, I did try to use uWSGI but I always got a SegFault when I use gevent (and of cause socketio need to).

**Comment by miguelgrinberg** [comment]
@Zygonie I don't understand your problem. When a client connects, does the server send a message just to that client, or does it broadcast a message to all clients? Do you have the code somewhere I can see it?

**Comment by Zygonie** [comment]
Sorry it was my mistake... I tried to send a message before the `render_template` call : 

```
@app.route('/', methods=['GET', 'POST'])
def index():
    """Renders the home page."""
    global sp_process
    form = MainForm()
    if form.validate_on_submit():
        if form.data['start']:
            return redirect(url_for('start_sp'), code=307)
        elif form.data['stop']:
            return redirect(url_for('stop_sp'), code=307)
    socketio.emit('sp_message', {'data': 'Process running'})  # [1]
    return render_template('index.html', title='Main page', form=form)
```

The behavior is the following: When the page is loaded, I press the `start` button in the form. This starts a separate process that can emit socket messages. If the line `[1]` is present, the messages sent by the second process appear twice wherease if the line `[1]` is omitted, the messages appear only once.
