### ISSUE TITLE
Can this be used with react-native as client

### ISSUE THREAD

**Issue by Yashwanthv21** [miguelgrinberg/Flask-SocketIO#578]
I am using socket.io-client package in react-native and the socket is not able to connect to flask server.
Can anyone help me with this? 
I have even tried with react-native-socketio, it also fails to connect.

**Comment by miguelgrinberg** [comment]
Should work. Do you have logs or error messages to share?

**Comment by KunleMichaels** [comment]
Hi miguelgrinberg, thanks for helping me out with ibmdash db. do you have any tutorial or recommendation on using react.js on flask?

**Comment by miguelgrinberg** [comment]
@KunleMichaels I don't use react, so I don't have anything to recommend.

**Comment by bsdtux** [comment]
Hi Kunle we have both our iOS and Android app built using React Native and they connect to flask-socketio. We are using flask-socketio more as a one to one messaging platform than a chat room but it still works pretty good.
The only thing we have experienced is an edge case where every so often the connection drops and doesn't reconnect. But other than that it works great. We also have a dashboard piece to our app and it uses that same connection 
As for recommendations on React resources I would probably say start here https://reactjs.org/docs/hello-world.html this has helped me who is a backend person get up to speed pretty quickly. For react native I would look at https://facebook.github.io/react-native/docs/getting-started.html and https://egghead.io/browse/tools/react-native

**Comment by gayashanbc** [comment]
@bsdtux can you state the procedure  you followed to make the socket.io connection?
I'm able to connect to NodeJS socket.io servers but not with Flask socket.io servers from React Native.

@miguelgrinberg  Can you please re-open this issue?

**Comment by miguelgrinberg** [comment]
@gayashanbc please open a new issue and include the details of your connection problem.

**Comment by gayashanbc** [comment]
@miguelgrinberg OK
#716
