### ISSUE TITLE
ValueError: invalid payload

### ISSUE THREAD

**Issue by greyli** [miguelgrinberg/Flask-SocketIO#579]
Hi, Miguel.

I just create a chat application with Flask-SocketIO. Here is the event handler I created to send the message:

```python
@socketio.on('message')
def handleMessage(message_body):
    send({'msg': message_body}, broadcast=True)
```

**Everything is working fine** except I got the error output on the command line as below:

```pytb
post request handler error
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\engineio\server.py", line 285, in handle_request
    socket.handle_post_request(environ)
  File "C:\Python27\lib\site-packages\engineio\socket.py", line 104, in handle_post_request
    p = payload.Payload(encoded_payload=body)
  File "C:\Python27\lib\site-packages\engineio\payload.py", line 11, in __init__
    self.decode(encoded_payload)
  File "C:\Python27\lib\site-packages\engineio\payload.py", line 51, in decode
    raise ValueError('invalid payload')
ValueError: invalid payload
```

This error happens both in debug mode or not. Also, I tested it on Firefox and Chrome, same output.

P.S. In debug mode, the request log will be outputed on the command line, such as:
```
127.0.0.1 - - [31/Oct/2017 16:16:50] "GET /socket.io/?EIO=3&transport=polling&t=LznWIWE&sid=...accepted ('127.0.0.1', 8120)
```
However,  I got nothing except the error output in non-debug mode, and it's hard to abort the server with `Crtl + C`.

### Environment
* Python 2.7
* Windows 7
* python-engineio (1.7.0)
* python-socketio (1.8.1)
* Flask-SocketIO (2.9.2)
* eventlet (0.21.0)

Thanks!

**Comment by rhyspang** [comment]
got same exception in python3

**Comment by miguelgrinberg** [comment]
The `message` event is reserved by Socket.IO, and it expects a string argument. Try changing your `send()` to:

    send(message_body, broadcast=True)

**Comment by greyli** [comment]
Thanks! 
Does it mean we should use a custom event to handle data transfer, instead of `message`? In what circumstance we should use the built-in `message` event?

**Comment by miguelgrinberg** [comment]
@greyli Forgot to mention that when you start using custom events you need to use `emit()` and not `send()`.

**Comment by greyli** [comment]
You are very helpful!
