### ISSUE TITLE
Count the number of connected users

### ISSUE THREAD

**Issue by greyli** [miguelgrinberg/Flask-SocketIO#580]
Hi, Miguel.

In a chat application, I need to know the total amount of online user. I use the code below to get the number:
```python
count = 0

@socketio.on('connect')
def connect():
    global count
    if current_user.is_authenticated:
        count += 1
    emit('status', {'count': count}, broadcast=True)


@socketio.on('disconnect')
def disconnect():
    global count
    if current_user.is_authenticated:
        count -= 1
    emit('status', {'count': count}, broadcast=True)
```
The `count` variable will be accepted by all connected clients. Although the number seems right, I'm wondering is it the correct and ideal way to do it?

**Comment by miguelgrinberg** [comment]
Looks good to me, but you may also want to return `False` in the `connect()` handler for non-authenticated users, that way those will be allowed to connect.

**Comment by greyli** [comment]
Oh, I see. Thank you very much!

**Comment by RichardBaker3020** [comment]
@miguelgrinberg  Hi miguelgrinberg, since `count` is a global variable, I wonder if it is thread safe to store and modify a global variable in flask like this, is it necessary to use a data source like redis to hold global data?

**Comment by miguelgrinberg** [comment]
@RichardBaker3020 Normally you would not be using threads here, it would be greenlets, which do not have pre-emptive context-switches. So yes, under gevent/eventlet this is safe to do. For regular threads you would need to add a lock.

**Comment by atomtm** [comment]
So state should be kept in a global variable like this, and send it to the clients when needed ? Is there any other way, the prefered way, like the OP mentioned with Redis?

**Comment by miguelgrinberg** [comment]
@atomtm there are no absolutes, it really depends on your application. For a small application based on greenlets a global variable is okay to use. If you have multiple servers then a global variable would not work, then something like Redis will work.
