### ISSUE TITLE
Add a section to the documentation about decorator nesting.

### ISSUE THREAD

**Issue by kingdion** [miguelgrinberg/Flask-SocketIO#581]
As somebody who is rather new to the entire programming world, having documentation for simple tasks (even though they might be well known features) within the language can sometimes be important.

A certain feature which I was unaware about in Python is the ability to nest a decorator within a function and have access to variables defined within the function.

A pseudo representation of what I'm trying to say, where my_connect_event has access to my_variable and still uses the socketio protocol:
```python
def my_flask_route(my_variable):
    @socketio.on('connect')
     def my_connect_event():
    ....
```

I'd be happy to make a PR and add a short section about this to the documentation (just so people can see it is possible, doesn't hurt!) if you would like, or am open to discussion on the topic however I feel like it could be valuable knowledge to others like myself, despite being a very simple concept.

Regards,
/ Dion Misic

**Comment by miguelgrinberg** [comment]
Not sure this belongs here, since you are talking about a Python feature. I would prefer focused examples that solve a common problems.

**Comment by kingdion** [comment]
Thanks for the quick response Miguel, thought I'd raise it regardless!

**Comment by miguelgrinberg** [comment]
No problem, but as I said, I would accept additional examples for this repository that demonstrate useful solutions, so I'm open to PRs for those. Thanks!
