### ISSUE TITLE
Problem with background emit and gunicorn standalone app

### ISSUE THREAD

**Issue by blazeroot** [miguelgrinberg/Flask-SocketIO#583]
Hello,

I'm facing issue where I'm not receiving any error, but event is not emitted when function with `socketio.emit` is called from another thread. I've created small example to reproduce:

```python
import eventlet
eventlet.monkey_patch()

from flask import Flask
from flask_socketio import SocketIO, emit
import gunicorn.app.base
from gunicorn.six import iteritems
import time

app = Flask(__name__)

socketio = SocketIO(app, logger=True)

@socketio.on('message')
def test_message(message):
    emit('response', message)
    background_emit('background')

def background_emit(message):
    socketio.emit('background', message)

def notification_pusher():
    while True:
        time.sleep(1)
        background_emit('background_timer')

eventlet.spawn(notification_pusher)

class StandaloneApplication(gunicorn.app.base.BaseApplication):
    def __init__(self, app, options=None):
        self.options = options or {}
        self.application = app
        super(StandaloneApplication, self).__init__()

    def load_config(self):
        config = dict([(key, value) for key, value in iteritems(self.options)
                       if key in self.cfg.settings and value is not None])
        for key, value in iteritems(config):
            self.cfg.set(key.lower(), value)

        self.cfg.set('worker_class', 'eventlet')

    def load(self):
        return self.application


if __name__ == '__main__':
    options = {
        'bind': '%s:%s' % ('0.0.0.0', '5000'),
        'workers': 1
    }
    StandaloneApplication(app, options).run()

```

When the `background_emit` is called from `test_message` it works nice. But if it's called from the loop in `notification_pusher` the event is not emitted, event the logs says it is. I used http://amritb.github.io/socketio-client-tool/ as client.

Log fragment:
```
emitting event "background" to all [/]
emitting event "background" to all [/]
emitting event "background" to all [/]
received event "message" from 56a927e200ea45abb89989f8870488f5 [/]
emitting event "response" to 56a927e200ea45abb89989f8870488f5 [/]
emitting event "background" to all [/]
emitting event "background" to all [/]
emitting event "background" to all [/]
```

I can see `emitting event "background" to all [/]` but only `background` message was received. The `background_timer` is never emitted.

I'd really appreciate any help.

**Comment by miguelgrinberg** [comment]
Running your script and connecting with the Python Socket.IO client I get those background events just fine. Here is my test client:

```python
import logging
from socketIO_client import SocketIO

logging.getLogger('socketIO-client').setLevel(logging.DEBUG)
logging.basicConfig()

socketIO = SocketIO('localhost', 8000)
socketIO.wait()
```

Example debug output:

```
DEBUG:socketIO-client:localhost:8000/socket.io [engine.io transport selected] websocket
DEBUG:socketIO-client:localhost:8000/socket.io [engine.io heartbeat reset]
DEBUG:socketIO-client:localhost:8000/socket.io [socket.io packet received] b'2["background","background_timer"]'
DEBUG:socketIO-client:localhost:8000/socket.io [socket.io packet received] b'2["background","background_timer"]'
DEBUG:socketIO-client:localhost:8000/socket.io [socket.io packet received] b'2["background","background_timer"]'
DEBUG:socketIO-client:localhost:8000/socket.io [socket.io packet received] b'2["background","background_timer"]'
DEBUG:socketIO-client:localhost:8000/socket.io [socket.io packet received] b'2["background","background_timer"]'
DEBUG:socketIO-client:localhost:8000/socket.io [socket.io packet received] b'2["background","background_timer"]'
```

**Comment by blazeroot** [comment]
Hey @miguelgrinberg, thank you for looking at this! I've checked with your code but I'm still not receiving events. Could you share your environment info?

I'm currently running this on:
`Python 2.7.13`
`flask 0.12.2`
`Flask-SocketIO 2.9.2`
`eventlet 0.21.0`
`gunicorn 19.7.1`

The client connects to the server, but there're no events received:
```
❯ python client.py
DEBUG:socketIO-client:localhost:8000/socket.io [engine.io transport selected] websocket
DEBUG:socketIO-client:localhost:8000/socket.io [engine.io heartbeat reset]
```

**Comment by miguelgrinberg** [comment]
> If you're running server using: gunicorn --worker-class=eventlet -w 1 server:app it will work

This would have been kind of important to mention, don't you think? Yes, I did run gunicorn that way. So the problem is clearly on your class, there must be something that you are doing there that is affecting your application.

I think running gunicorn the way you want to is extremely rare, I wouldn't be surprised if that mode isn't well supported or tested. If you want to run your application as a script, you don't need gunicorn, try using `socketio.run(app)` to start your server directly through eventlet.

**Comment by blazeroot** [comment]
Yeah, I should mention that in the first message. Sorry! I think I'll modify the original app to run it using `gunicorn --worker-class=eventlet -w 1 server:app` so it will work as the extracted example.

Thank you for your help!

btw. the class code is from [gunicorn docs](http://docs.gunicorn.org/en/stable/custom.html)

**Comment by danielissac** [comment]
> > If you're running server using: gunicorn --worker-class=eventlet -w 1 server:app it will work
> 
> This would have been kind of important to mention, don't you think? Yes, I did run gunicorn that way. So the problem is clearly in your class, there must be something that you are doing there that is affecting your application.
> 
> I think running gunicorn the way you want to is extremely rare, I wouldn't be surprised if that mode isn't well supported or tested. If you want to run your application as a script, you don't need gunicorn, try using `socketio.run(app)` to start your server directly through eventlet.

Thanks finally It worked
