### ISSUE TITLE
When to use reserved events "message" and "json"?

### ISSUE THREAD

**Issue by greyli** [miguelgrinberg/Flask-SocketIO#584]
Hi, Miguel!

What's the general use case of the reserved events `message` and `json`? I can use `send()` on the client to trigger the `message` event on the server, so I guess maybe the `message` was used in very simple application. 

But for `json`, I don't know how to trigger it. When should we use it? And how?

**Comment by miguelgrinberg** [comment]
These two reserved messages are there for backwards compatibility wtih older versions of Socket.IO (at least that is what I believe). The `send()` function triggers both, depending on the value of the `json` keyword argument (defaults to `False`).

I don't think there is ever a reason to use these two events, I always roll my own.

**Comment by greyli** [comment]
I see, Thanks! 

As I think, if I want to trigger the `json` event on the sever, I have to use `send()` on the client:
```javascript
$('#test-button').on('click', function() {
    socket.send(JSON.stringify({'hello': 'world'}));
 });
```
But this will trigger `message` event on the server, and add `json` argument still not work. 

It seems that the `json` argument only exists in `flask_socketio.SocketIO.send()`, which *Send a server-generated SocketIO message*, the `send()` that in form of function doesn't have a `json` argument. 

So, what's the difference between these two `send()` and `emit()`? Does it mean we need to use a `SocketIO.send()` **on the server** to trigger the `json` event **on the server**?

**Comment by miguelgrinberg** [comment]
As I said, the `message` and `json` where used in a very old release of the Socket.IO server. For backwards compatibility I have keet them.

How the different Socket.IO clients deal with these old events is something I have no control of. From looking at the JavaScript client it appears the json event isn't supported in current versions.

I'm going to say it again, it's not a good idea to use `send()` for JSON, simply because all custom events support JSON as well.

**Comment by greyli** [comment]
Oh, Thanks! I'm writing something about Flask-SocketIO, so I have to make sure everything is accurate.

**Comment by greyli** [comment]
The code snippet in *[Sending Messages](https://github.com/miguelgrinberg/Flask-SocketIO/blob/master/docs/index.rst#sending-messages)* chapter of documentation seems incorrect, the `send()` in json event handler should be `socketio.send(json, json=True)`.

**Comment by miguelgrinberg** [comment]
No, that is correct. `send()` is a context-aware function specific to Flask. The `socketio.send()` function is the more basic send that comes from the `python-socketio` package.

**Comment by greyli** [comment]
But it appears the `json` argument doesn't pass to `socketio.send()` and [the end of `send()`](https://github.com/miguelgrinberg/Flask-SocketIO/blob/master/flask_socketio/__init__.py#L737)?

**Comment by greyli** [comment]
If it is missing, I'm pleased to submit a PR to fix it.
