### ISSUE TITLE
Delete queues on rolling updates

### ISSUE THREAD

**Issue by xarg** [miguelgrinberg/Flask-SocketIO#586]
I'm using Flask-SocketIO with Kombu (RMQ) in a kubernetes environment. 

During a rolling update (a k8s deployment in my case) each flask-socketio server is killed and spawned 1 by 1 to allow for a more smooth transition between deployments, the queues associated with each dying instance are not deleted though. As a result since new messages come in through the exchange they get into the old queues until the queues expire - this triggers a lot of our our alerts that monitor the number of ready messages in the queue.

Looking at how the queues are defined (from `kombu_manager.py`) it's not possible to specify any parameters to their creation or dumping the queue name for example somewhere so it can be cleaned after the socketio process died.

Here's the respective code of the queue declaration/creation:

```
    def _queue(self):
        queue_name = 'flask-socketio.' + str(uuid.uuid4())
        return kombu.Queue(queue_name, self._exchange(),
                           durable=False,
                           queue_arguments={'x-expires': 300000})
```

@miguelgrinberg would  you be open to passing some params all the way to the manager? Queue name and expiration for example would be great to be able to change.

**Comment by miguelgrinberg** [comment]
First of all, you should be able to easily address your problem if you create your own subclass of `KombuManager` and override the implementation of the `_queue()` method to meet your needs.

I could be okay with options to set the name and the expiration, either through `kwargs` or environment variables.

**Comment by xarg** [comment]
Once again thanks a lot for your help @miguelgrinberg. If you need anything for me to do please let me know. I'd love to give something back!

The final solution I came up with is based on Miguel's suggestion (subclassing the manager). In the example below I'm defining a static name for the queue based on the hostname (but it can be anything). I'm doing this because we run on kubernetes and the hostname is automatically generated and unique (at least if you run using deployments). 

`manager.py`:

```
import kombu
import socket
from socketio.kombu_manager import KombuManager


class StaticQueueKombuManager(KombuManager):
    """KombuManager with a static queue definition for flask socketio.

    We need this in order to cleanly delete the queues when we
    destroy the flask-socketio server.
    """

    def _queue(self):
        queue_name = 'flask-socketio.' + socket.gethostname()
        return kombu.Queue(
            queue_name,
            self._exchange(),
            durable=False,
            queue_arguments={'x-expires': 300000}
        )

    def stop(self):
        """Stop the manager - delete the queue"""

        connection = self._connection()
        queue = self._queue()(connection.channel())
        queue.delete()
```

You can use the above manager like this:
```
socketio = SocketIO(app, client_manager=StaticQueueKombuManager(url=BROKER_URL, channel='flask-socketio'))
```

And when you run the socketio server you can wrap it inside a `try/finally` like so:

```
if __name__ == '__main__':
    try:
        socketio.run(app, host='0.0.0.0', port=7777, debug=app.config['DEBUG'])
    finally:
        socketio.server.manager.stop()
```

This way when the server exists it will also delete the queue. Hope it helps.
