### ISSUE TITLE
Can I use socketio as normal socket server?

### ISSUE THREAD

**Issue by wiwengweng** [miguelgrinberg/Flask-SocketIO#588]
Hi, miguel. I am sorry to trouble you. I successfully integrated flask socketio with my flask web app, to make a web socket pipline for my html page, to get the back-end notifications. This works well, thanks.

Recently I review my project and finde that in my project, actually an 2-year-old project, we use gevent as the main framework, to start a thread for stream server as socket server to response to some clients, start a thread for flask-socketio as websocket server and also web server(I use socketio.run()). Now I want to kick the normal gevent server and start flask as the main framework. That is to start socket server too in flask. Is it ok to do that?

In my normal socket server, I can use socket.send() and process the response in clients. How can I get this kind of response if I use flask as socket server? TIA :)

**Comment by miguelgrinberg** [comment]
Not sure I understand, but if your socket server is a standard networking server and you want to merge it with the Socket.IO server, then you are going to need to adapt it to work with Flask-SocketIO events instead of plain socket calls.

**Comment by wiwengweng** [comment]
Thank you for the response. But I still don't know where to start. Is there any available libraries? Or can I try some other ways?

**Comment by miguelgrinberg** [comment]
I'm really not sure how to give you better advice. I haven't seen your code, but based on your description, you'll basically have to refactor your socket server to use the Socket.IO functions to read/write. Depending on the application this could be a fairly important change.

**Comment by wiwengweng** [comment]
Sorry not giving the details. My socket server is quite simple, to  process data received. For example:

````
# I use gevent StreamServer
from gevent.server import StreamServer

class ClassThread(gevent.greenlet.Greenlet):
    """
    # demo
    """

    def __init__(self, manager):
        super(ClassThread, self).__init__()

        self._complete = gevent.event.Event()

        self._ready = gevent.event.Event()

        self._manager = manager

        self._server = None

    def stop(self):
        self._complete.set()

    def publish(self, topic, message):
        self._ready.wait()

    def remote(self, conn, address):
        (ip, port) = address
        try:
            data = conn.recv(1024)
            while len(data) == 0 :
                data = conn.recv(1024)
                import time
                time.sleep(1)
            data = eval(data)
            
            if data['OPERATION'] == "query":
                # (process data)
				conn.sendall(data)
            elif data['OPERATION'] == "check_op":
				# (process data)
				conn.sendall(data)
            else:
                    a = {"DATA":"ERROR_300"}
                    conn.sendall(str(a))
        except Exception , e:
            self._manager._log.warn("%s connect port %s false.%s" % (ip, port, e))
            pass
        finally:
            conn.close()

    def _run(self):
        self._server = StreamServer(('0.0.0.0', 10003), self.remote)
        self._server.serve_forever()
````

I use this simple client to connect, send data and process data:

````
import socket


def web(ip, opt, classname):
    socket.setdefaulttimeout(3)
    address = (ip, 88)
    msg = {'OPERATION': opt, 'PARAMETER': classname}
    msg = repr(msg)
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.connect(address)
        s.send(msg)
        while 1:
            data=s.recv(1024)
            if data:
               print data
            else:
                break
        s.close()
    except socket.error, e:
        print e
    finally:
        s.close()

web("210.10.20.56", "check_op", "")
````

if all the operations in socket server should change to events, I think changes also need to be done in the client side, maybe  I should also use socketIO to 'listen' to the server too?

**Comment by miguelgrinberg** [comment]
For the server you will have to change the code to use an event handler instead of just reading from the socket with `recv`. And replace the `sendall()` calls with `emit()`.

For the client you will pretty much have to rewrite it using a Socket.IO client.

So yes, this isn't going to be a trivial change, Socket.IO is a high-level protocol, and what you have here is as low level as it gets.

**Comment by wiwengweng** [comment]
Yes, I think I am having better understand with your explanation. Will try some modification, to see how hard it is. Thank you. :-)
