### ISSUE TITLE
instant messaging

### ISSUE THREAD

**Issue by dashingspidy** [miguelgrinberg/Flask-SocketIO#590]
Hi,
i'm trying to build an instant messaging app using flask. I'm using Flask-login for user session and Peewee for db. I have conversation and message tables.
```
class conversation():
    recipient = user_id
    sender = user_id

class message():
    message = text
    user = user_id
    conversation = conversation_id
```
All messages are stored in db. I just want to make it realtime. what would be the best way to do it? 
Thank you in advance. Any example would be a great help though! 

and sorry for asking question in wrong place.

**Comment by miguelgrinberg** [comment]
Look at the [Flask-SocketIO-Chat](https://github.com/miguelgrinberg/Flask-SocketIO-Chat) application for guidance.
