### ISSUE TITLE
audio / video chat example

### ISSUE THREAD

**Issue by deounix** [miguelgrinberg/Flask-SocketIO#592]
Is there any idea or example for how to make audio / video chat with flask-socketio

(room - like if I'm user and broadcasting video or audio to all users that joined to specific room) ..etc

Is it a (good or bad) idea for making it with flask-socketio ? can this handel alot of traffic (alot of audio / video chat) ?

**Comment by miguelgrinberg** [comment]
Not exactly what you want, but I have written an example that records audio in the browser, and streams it real time to the server. Maybe that'll give you something to start from: https://github.com/miguelgrinberg/socketio-examples/tree/master/audio

**Comment by deounix** [comment]
thank u @miguelgrinberg for your GREAT WORK.
