### ISSUE TITLE
Allow passing ssl_context without files

### ISSUE THREAD

**Issue by FranciscoSilveira** [miguelgrinberg/Flask-SocketIO#606]
I understand that currently the method for using HTTPS with eventlet is to pass the private key file and the certificate file, however I think it would be good if the option to manually create a X509 object using the cryptography module existed. While this probably won't make sense for everyone's needs, the current state of affairs forces the certificate to be a physical file on the filesystem.

Going back to ssl_context= would solve this, or just passing a X509 object and a PKey object that implement the interfaces from the cryptography module.

**Comment by miguelgrinberg** [comment]
What do you mean by "going back to ssl_context"?

You can use four different servers with this package, each configures SSL its own way, this package simply passes the options through to the web server. With eventlet you have to use the `wrap_ssl()` function, which takes the certificate and key as files. I haven't inspected the source code to see if there is a non-file way to pass your SSL context, but if there is, it should be supported through this package.

**Comment by FranciscoSilveira** [comment]
Sorry if I mixed something up, let me try and explain myself:

With Flask alone, without socketIO, you could use HTTS by passing an SSL.Context object when running the server:

```
from OpenSSL import SSL
context = SSL.Context(SSL.SSLv23_METHOD)
context.use_privatekey_file('yourserver.key')
context.use_certificate_file('yourserver.crt')

app.run(
        host='0.0.0.0',
        port='5000', 
        ssl_context=context)
```

The thing is, I have a use case where the SSL.Context object is created without a file for the certificate, I can illustrate this point better if you want, but it boils down to this: I have a [X509 object] (https://cryptography.io/en/latest/x509/reference/#cryptography.x509.Certificate) and a [RSAPrivateKey object](https://cryptography.io/en/latest/hazmat/primitives/asymmetric/rsa/#cryptography.hazmat.primitives.asymmetric.rsa.RSAPrivateKey), both from the cryptography module, and I use this to create a valid SSL.Context. This works with Flask (I have an example where I use objects from the pyOpenSSL module instead, but they use the same interface).

Now with SocketIO, when wrapping the app and running the SocketIO object, the keyword argument "ssl_context" doesn't exist. If I understood [your answer here correctly](https://github.com/miguelgrinberg/Flask-SocketIO/issues/193#issuecomment-168752567), this is because it's not the way to do it with SocketIO, since it depends on the server. When using eventlet, SocketIO has to wrap a socket in a SSL transport (like what happens with a basic python socket), but as far as I can tell this is done from within the SocketIO code, there's no external way to do it. So we just pass 2 strings corresponding to paths for files for the certificate and private key, and SocketIO will have the trouble of finding those files and wrapping the socket in a valid SSL Context derived from them:

```
socketio.run(
        app,
        host='0.0.0.0',
        port=5000,
        certfile=CERT_FILE,
        keyfile=KEY_FILE
    )
```

But like I said, I don't necessarily have those files. I have objects representing them.
