### ISSUE TITLE
questions about interact with ws server from rabbitmq

### ISSUE THREAD

**Issue by njordr** [miguelgrinberg/Flask-SocketIO#607]
Hi.

I tried to setup everything as explained/found with google searches, but it not works and I'm trying to guess why.

ws server:

```
from gevent import monkey
monkey.patch_all()
...
async_mode = 'gevent'
...
app = flaskapi.FlaskAPI(config['app']['name'])
app.config['SECRET_KEY'] = config['app']['secret']
...
socketio = flaskws.SocketIO(
    app, async_mode=async_mode,
    message_queue=config['celery']['ws_broker_url'], channel='ws_server_chat',
    logger=True, engineio_logger=True
)
socketio.on_namespace(WebUI('/webui'))
```

Before start:
<img width="430" alt="image" src="https://user-images.githubusercontent.com/4282925/34050177-e303097a-e1b1-11e7-86e9-89489e047cc0.png">

```
FLASK_APP=run.py flask run -h 0.0.0.0 -p 5000 --debugger

 * Serving Flask-SocketIO app "run"
Server initialized for gevent.
```

After server start
<img width="367" alt="image" src="https://user-images.githubusercontent.com/4282925/34050223-1066fc14-e1b2-11e7-923b-aa31660c2f5b.png">

first question: I aspected to find the queue, why not?

CLI Client:

```
import os

from configparser import ConfigParser
from flask_socketio import SocketIO
from pprint import pprint


config_file=os.getenv('SPY_CONFIG', 'conf/spy-ws.ini')

config = ConfigParser()
config.read(config_file)

socketio = SocketIO(message_queue=config['celery']['ws_broker_url'], channel='ws_server_chat', logger=True, engineio_logger=True)
socketio.emit('spyws_status_panel', namespace='/webui')
```

Now run the client

```
python test_queue.py
Server initialized for eventlet.
emitting event "spyws_status_panel" to all [/webui]
```

No log from server and no queue in rabbit

Now start a "normal" ws client from the browser (html sample page found in the repo)
```
a7e9121bcd11473c9a4137c213c2ae7b: Received packet MESSAGE data 2/webui,["spyws_ping"]
received event "spyws_ping" from a7e9121bcd11473c9a4137c213c2ae7b [/webui]
emitting event "spyws_pong" to a7e9121bcd11473c9a4137c213c2ae7b [/webui]
10.0.2.2 - - [2017-12-15 16:13:12] "POST /socket.io/?EIO=3&transport=polling&t=1513354391972-10&sid=a7e9121bcd11473c9a4137c213c2ae7b HTTP/1.1" 200 175 0.003961
a7e9121bcd11473c9a4137c213c2ae7b: Sending packet MESSAGE data 2/webui,["spyws_pong",null]
10.0.2.2 - - [2017-12-15 16:13:12] "GET /socket.io/?EIO=3&transport=polling&t=1513354390990-9&sid=a7e9121bcd11473c9a4137c213c2ae7b HTTP/1.1" 200 220 1.033035
```
Logs from the server and the queue appears in rabbit
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/4282925/34050510-12892f0c-e1b3-11e7-8be6-1b63617c9fcd.png">

If I run again the cli client, no logs from the server, but something has been consumed on the queue
<img width="631" alt="image" src="https://user-images.githubusercontent.com/4282925/34050762-e99e16b0-e1b3-11e7-8ae2-485add9beb17.png">

What is weird is that sometimes the server replies with a message on the queue:
- why sometimes happens and sometimes not?
- how can I wait from the cli client to retrieve the reply from the server?

Flask-SocketIO==2.9.3
gevent==1.2.2
greenlet==0.4.12

Thanks

**Comment by miguelgrinberg** [comment]
What you call a "CLI client" is not a client. If you want to use a Socket.IO client in Python, you need to use `socketio-client`, which is a different package, not written by myself. My package is only a server.

What you are doing in your CLI client script is extending the server so that it can emit to clients from an external process. One problem I noticed with this script is that appears to be running on eventlet, but you are not monkey patching, which likely prevents accesses to the queue.

My recommendations:

- Uninstall eventlet from your virtualenv, since you are using gevent on your main server.
- Rewrite your CLI client with package `socketio-client`.

After that, let's discuss if there are any problems remaining.

**Comment by njordr** [comment]
Thanks for the info about the client, I'll move to socketio-client to do it.

What about the queue that is not created until flask-socketio receives some interaction from js library?

And what about using your use case "Emitting from an External Process" do not trigger the server?

**Comment by miguelgrinberg** [comment]
> What about the queue that is not created until flask-socketio receives some interaction from js library?

Why is this a problem? Everything works, right?

> And what about using your use case "Emitting from an External Process" do not trigger the server?

I explained my theory:

> One problem I noticed with this script is that appears to be running on eventlet, but you are not monkey patching, which likely prevents accesses to the queue.

So can you please follow my recommendations and then we can discuss any remaining problems, if they exist?

**Comment by njordr** [comment]
Ok, thank you
