### ISSUE TITLE
Session variable is missing when login to Flask-SocketIO outside of Flask application

### ISSUE THREAD

**Issue by KietnaQuTak** [miguelgrinberg/Flask-SocketIO#610]
Hello Miguel.

**Short version:** Session variable created after connecting to websocket is not available later when user is emitting events from different webpage (domain) than Flask application.

**Long version:**
I'm developing an application that uses websocket to enable chat functionalities with room support. According to [article written by You](https://blog.miguelgrinberg.com/post/flask-socketio-and-the-user-session) I have configured `SocketIO(manage_session=False, async_mode='eventlet')`, `SESSION_TYPE = 'filesystem'` (in config.py). Chat is working like a charm when using it over Flask application (locally and in our domain app-test.click2callme.pl), which is when both users are connected from the same domain.

Now we want to allow creating chat in external resources when user adds our application code to generate chat window on his/hers website. Chat is generated, SocketIO JS library is downloaded, user is successfully connected to our application (in JS: socket = io.connect(our_domain + '/chat/') so user can receive and send SocketIO events. **But there is a problem with user session variable which I'm creating for every user to identify returning users** (for example to recreate accidental closed chat window). This session variable is created when user is connected (I can see it in logs when simply doing `print('event_chat_user_create: ' + str(session['user_chat']))` ) but **later when user sends or receive events this session variable is not available.** I try to add `session.modified = True` after every session variable modification but with no luck.

I have no clue what may be the reason of such behavior. Is this something related to the Flask-SocketIO way of handling session variables? Is there anything You can advice me Miguel?

Best regards
Stromecki Jacek

**Comment by miguelgrinberg** [comment]
I don't think this is expected to work. The user session is supported by a cookie, if you send requests from other clients, then the cookie isn't going to be there, so the session will not be available. This has nothing to do with Flask-SocketIO, would happen with straight Flask as well.

**Comment by KietnaQuTak** [comment]
I think I didn't explain this correctly. We have two sides of conversation: user and consultant.

**Scenario A (working):** When user open chat from our domain (for example app-test.click2callme.pl/call/1) and consultant connects to chat from admin panel (app-test.click2callme.pl) then cookie exists all the time.

**Scenario B (not working):** When consultant is connected through admin panel and users opens chat from any other domain (for example locally file:///C:/c2cme_test.html or [remote website](https://test.click2callme.pl/show/_development/c2cme_test.html) - click remote link, it's my development version of loading chat outside of Flask application) then cookie exists only in websocket event that is creating it (in my case 'event_chat_user_create'). After that every other event that user is emitting says that this session variable is not created although user stays connected to chat and can receive and emit events.

PS. Please notice that this is development version that is fixed on my user so chat will be working only when I login to specific account.

**Comment by miguelgrinberg** [comment]
I think the problem comes a misunderstanding that you have on how cookies work with WebSocket. A WebSocket connection cannot create or modify cookies, there is simply no way for WebSocket to access the cookie storage in the browser. The only interaction between cookies and a WebSocket connection is that existing cookies that were previously set via HTTP are sent with the WebSocket connection request.

When you connect to your server from these other domains, you can't rely on a Flask managed user session, because Flask never gets a chance to create this session because there is no HTTP interaction.

Have you tried using `manage_session=True`? That may cause other problems for you, but it should give you a usable user session that is fully managed by Flask-SocketIO using a different mechanism, not based on cookies.

**Comment by KietnaQuTak** [comment]
Thank you Miguel for explanation.

I have figured out that I can manage cookies with JavaScript and pass their values with one of custom SocketIO events to inform that connected user has some chats previously opened.
