### ISSUE TITLE
support for volatile messages?

### ISSUE THREAD

**Issue by stephanelsmith** [miguelgrinberg/Flask-SocketIO#614]
Quick question, are there plans for volatile messages?
https://socket.io/docs/#sending-volatile-messages

**Comment by miguelgrinberg** [comment]
This was already brought up at some point, in one of the dependent repositories: https://github.com/miguelgrinberg/python-socketio/issues/115.

See my analysis there, I decided it isn't really an interesting feature to support, at least not in the way the JavaScript server implements it.
