### ISSUE TITLE
Setting up JSON logging

### ISSUE THREAD

**Issue by imdadahad** [miguelgrinberg/Flask-SocketIO#615]
I have recently setup and deployed a Flask Socket IO application to AWS running as an embedded server (gevent installed). Everything is working fine at the moment. 

I've setup as shown below:

```

    handler = RotatingFileHandler(current_app.config['LOG_PATH'], maxBytes=1000000, backupCount=1)
    logging.basicConfig(filename=current_app.config['LOG_PATH'], level=logging.INFO)
    app.logger.setLevel(logging.INFO)

    logging.getLogger('socketio').setLevel(logging.INFO)
    logging.getLogger('engineio').setLevel(logging.WARNING)
    logging.getLogger('werkzeug').setLevel(logging.INFO)

    app.logger.addHandler(handler)
```

Everything is logging correctly as expected:

![image](https://user-images.githubusercontent.com/5855115/34720983-cd21eeb0-f538-11e7-9e6b-fa311f02d5ee.png)

What I'd like to do however is log in JSON as these log streams will be pushed through to an elastic search instance.

**Comment by miguelgrinberg** [comment]
Have you considered using a structured logger package, like maybe `structlog`?
