### ISSUE TITLE
How to continue sending messages from the server

### ISSUE THREAD

**Issue by jianglijie** [miguelgrinberg/Flask-SocketIO#620]
i want to implement publish/subscribe with flask-socketio,but i can only find example that emit message once. when i use code
```
@socketio.on('msg')
def msg_event(data):
    room_name = 'test_info'

    join_room(room_name)
    while True:
        emit('server_response', {'time': time.time()}, broadcast=False, room=room_name)
        time.sleep(3)
```
it works. but i cannot leave the room, it receive the message until close connect

so how can i do with it,then i can publish message continuous until i unsubscribe channel

**Comment by miguelgrinberg** [comment]
I don't understand. You are showing only one side here, the side of the server. The "channels" are called "rooms" here, so entering a room is the same as subscribing to a channel.

Consider these two event handlers:

@socketio.on('subscribe')
def subscribe(channel):
    join_room(channel)

@socketio.on('unsubscribe')
def unsubscribe(channel):
    leave_room(channel)

Now the client can send these `subscribe` and `unsubscribe` events, and note that a single client can be in multiple rooms so you can have a client subscribed to many channels.

After this, anywhere in your server where you want to publish, just issue an emit with the room/channel name:

    emit('server_response', {'time': time.time()}, room=channel)
