### ISSUE TITLE
High CPU w/ Websockets

### ISSUE THREAD

**Issue by EndenDragon** [miguelgrinberg/Flask-SocketIO#622]
Hello, I noticed in my production environment that when using the websockets, it is causing a high cpu. I am running this with two instances of uWSGI. One would be handling only the AJAX/HTTP requests, the other only with Websocket connections. The websockets portion is running at high cpu if I don't constantly restart the service. 

This is htop with the websockets portion running. https://i.got-lost-in-hyper.space/7a53d0.png

If I disable the websockets uwsgi service, the cpu load lessened. https://i.got-lost-in-hyper.space/90dbc3.png

This is the uwsgi ini for my websockets portion (the http one is almost as identical): https://pastebin.com/AKBUV0Wj

I am running the websockets uwsgi portion using systemd with this command (http one is also almost as identical): `/usr/local/bin/uwsgi --die-on-term --gevent 1000 --http-websockets --master --ini /var/www/titanembeds_ws.ini --gevent-monkey-patch --listen=16000`

My repo is located here: https://github.com/TitanEmbeds/Titan
All websockets businesses are handled in this file https://github.com/TitanEmbeds/Titan/blob/master/webapp/titanembeds/blueprints/gateway/gateway.py

Any help at reducing the high cpu load for the websockets portion would be greatly appreciated!

**Comment by miguelgrinberg** [comment]
Have you measured where is the CPU being used? It's not really fair to blame the websocket server, which really doesn't do much besides delivering events to the application. Also note that you can't run multiple processes with SocketIO in this way, the SocketIO protocol has special requirements, so if you need multiple workers you have to run them as independent uwsgi processes, start a message queue for them to communicate, and put nginx in front with sticky sessions.

**Comment by EndenDragon** [comment]
How would I measure where the CPU is being used? I do not know where to start. I currently do have a messaging queue going on. Not sure how it all currently works despite the fact that I'm not using nginx's sticky sessions and running multiple uwsgi-websocket processes.

**Comment by miguelgrinberg** [comment]
You need to use a code profiler. See https://docs.python.org/3.6/library/profile.html.
