### ISSUE TITLE
Deployment questions

### ISSUE THREAD

**Issue by andresmrm** [miguelgrinberg/Flask-SocketIO#623]
First of all: thanks!

I have questions about deployment:

The docs says "Note that socketio.run(app) runs a production ready server when eventlet or gevent are installed." I have eventlet installed. Does this mean I don't need Nginx for a "safe" deploy?

I did a `curl http://127.0.0.1:5000/socket.io/` to test, and it seems to leave open connections that won't close even after hours, or at least the `on_disconnect` is not being called (tested locally and at production). Is this right? Would Nginx help with that?

**Comment by miguelgrinberg** [comment]
> Does this mean I don't need Nginx for a "safe" deploy?

You don't "need" nginx, but in many deployment situations it is still a good idea to have it in front of the eventlet based server. Like for example, if your application serves static files in addition to HTTP and Socket.IO endpoints, then it does make sense to have nginx take care of those and forward everything else to the server.

> I did a curl http://127.0.0.1:5000/socket.io/ to test, and it seems to leave open connections that won't close even after hours

What did you expect to happen in this case? The `/socket.io` endpoint requires a Socket.IO client, it is not a straight HTTP endpoint that you can invoke with a regular HTTP client. This is the long-polling endpoint, it manages parallel GET and POST requests.  I suggest you try again using a proper Socket.IO client, either the node.js one, or if yo prefer to keep things in the Python realm, the `socketio-client` package.

**Comment by andresmrm** [comment]
Thanks for the reply!

> What did you expect to happen in this case?

Sorry, I should have explained myself better. I did a curl at first place to see if it is possible to check if the service is up or down this way.
But then I saw that my player count (it's a `Namespace` class that adds a player `on_connect`, and removes it on `on_disconnect`) was only going up on each curl hit (never down).
Since the curl doesn't mantain the connection, I expected the server to call `on_connect` and `on_disconnect` straigthaway, or at least to call `on_disconnect` after some timeout. But `on_disconnect` wasn't called, even hours later.

Just to be clear, my project is already working (I'm using JS socket.io-client in a SPA to access the server). I just got woried that this behavior could be used for some kind of DOS.

**Comment by andresmrm** [comment]
I deployed my game ([play](https://coopera.ikotema.digital), [code](https://gitlab.com/andresmrm/coopera/)) using Nginx and eventlet. But the problem I reported above (when using `curl`), is randomly happening even on normal use (client using JS `socket.io-client`).

The client is connecting to `wss://coopera-server.ikotema.digital` (connection code [here](https://gitlab.com/andresmrm/coopera/blob/master/client/src/main.js#L18), and [here](https://gitlab.com/andresmrm/coopera/blob/master/client/src/socket.js)).

In the server this is the proxy config (full template config [here](https://gitlab.com/andresmrm/coopera/blob/master/server/deploy/nginx.conf.template)):

    location /socket.io {
        include proxy_params;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass http://127.0.0.1:5000/socket.io;
    }

But sometimes the `on_disconnect` ([code here](https://gitlab.com/andresmrm/coopera/blob/master/server/coopera_server/api.py#L57-58)) is never called. The player count ([bottom of page](https://coopera.ikotema.digital/#/rooms)) keeps going up until I restart the server. For example, now it counts 10 players, but there is no one playing. And I don't believe the count is correct, because if it was, after the restart the players would automatically reconnect.

I saw https://github.com/miguelgrinberg/Flask-SocketIO/issues/499 , and asked myself if I must set a `ping_timeout` or `ping_interval`, but, as far as I see in the docs, it should have reasonable defaults.

Everything seems to work well, except this player count problem.

**Comment by miguelgrinberg** [comment]
Do you have logs enabled? It would be useful to look for errors there, the clients that don't get the disconnect event could be crashing or having an unexpected error that is not handled properly.

**Comment by andresmrm** [comment]
Thanks for the quick reply. I set `engineio_logger=True` and waited one day trying to log the problem. It seems to have happened once again (because player count was 2 and I think only I was online).
What should I search the logs for? I searched "upgrade to websocket failed", but found none. Only upgrade to websocket successful".

**Comment by miguelgrinberg** [comment]
I'm not sure exactly what you should search for, I guess I would look for any stack traces or error messages that appear in the log. You can send the logfile to me if you want me to take a look.

**Comment by andresmrm** [comment]
Sorry for the long delay, @miguelgrinberg . I was trying to collect more logs and info about the problem. Now I'm at least able to reproduce it: quickly reloading the page multiple times.

It seems the problem happens when the client leaves before the connection process is completed. This way the websocket upgrade fails.

I placed 2 prints to mark the logs:

    def on_connect(self):
        print('CCCCCCCCCCCCCCCCCCCCCCCCC')
        name = get_player_name()
        game.create_player(name)
        session['player_name'] = name

    def on_disconnect(self):
        print('DDDDDDDDDDDDDDDDDDDDDDDDD')
        game.remove_player(get_player_name())

Then:

1. Connected to the page and waited it finish.
2. Reloaded the page, but before it finished, reloaded again.

Got this log:

    (25414) wsgi starting up on http://0.0.0.0:5000
    (25414) accepted ('127.0.0.1', 34642)
    662342dc5de642dc861eb65ede9f47d0: Sending packet OPEN data {'sid': '662342dc5de642dc861eb65ede9f47d0', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
    CCCCCCCCCCCCCCCCCCCCCCCCC
    662342dc5de642dc861eb65ede9f47d0: Sending packet MESSAGE data 0
    127.0.0.1 - - [10/Mar/2018 16:56:54] "GET /socket.io/?EIO=3&transport=polling&t=M8HVClK HTTP/1.1" 200 401 0.001685
    (25414) accepted ('127.0.0.1', 34644)
    662342dc5de642dc861eb65ede9f47d0: Received request to upgrade to websocket
    (25414) accepted ('127.0.0.1', 34646)
    662342dc5de642dc861eb65ede9f47d0: Received packet MESSAGE data 2["join_rooms_list"]
    662342dc5de642dc861eb65ede9f47d0: Sending packet MESSAGE data 2["update_rooms_list",{"rooms":[],"num_players":1}]
    127.0.0.1 - - [10/Mar/2018 16:56:54] "POST /socket.io/?EIO=3&transport=polling&t=M8HVClK.1&sid=662342dc5de642dc861eb65ede9f47d0 HTTP/1.1" 200 219 0.001085
    662342dc5de642dc861eb65ede9f47d0: Sending packet NOOP data None
    127.0.0.1 - - [10/Mar/2018 16:56:54] "GET /socket.io/?EIO=3&transport=polling&t=M8HVClK.0&sid=662342dc5de642dc861eb65ede9f47d0 HTTP/1.1" 200 292 0.012646
    662342dc5de642dc861eb65ede9f47d0: Upgrade to websocket successful
    DDDDDDDDDDDDDDDDDDDDDDDDD
    662342dc5de642dc861eb65ede9f47d0: Sending packet MESSAGE data 2["update_rooms_list",{"rooms":[],"num_players":0}]
    71743c05e43647a8b6a8447adefb6711: Sending packet OPEN data {'sid': '71743c05e43647a8b6a8447adefb6711', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
    CCCCCCCCCCCCCCCCCCCCCCCCC
    71743c05e43647a8b6a8447adefb6711: Sending packet MESSAGE data 0
    127.0.0.1 - - [10/Mar/2018 16:56:58] "GET /socket.io/?EIO=3&transport=polling&t=M8HVDq4 HTTP/1.1" 200 401 0.001284
    (25414) accepted ('127.0.0.1', 34650)
    71743c05e43647a8b6a8447adefb6711: Received request to upgrade to websocket
    71743c05e43647a8b6a8447adefb6711: Received packet MESSAGE data 2["join_rooms_list"]
    71743c05e43647a8b6a8447adefb6711: Sending packet MESSAGE data 2["update_rooms_list",{"rooms":[],"num_players":1}]
    127.0.0.1 - - [10/Mar/2018 16:56:58] "POST /socket.io/?EIO=3&transport=polling&t=M8HVDq4.1&sid=71743c05e43647a8b6a8447adefb6711 HTTP/1.1" 200 219 0.000883
    127.0.0.1 - - [10/Mar/2018 16:56:58] "GET /socket.io/?EIO=3&transport=polling&t=M8HVDq4.0&sid=71743c05e43647a8b6a8447adefb6711 HTTP/1.1" 200 288 0.012789
    71743c05e43647a8b6a8447adefb6711: Sending packet NOOP data None
    71743c05e43647a8b6a8447adefb6711: Failed websocket upgrade, expected UPGRADE packet, received None instead.
    127.0.0.1 - - [10/Mar/2018 16:56:58] "GET /socket.io/?EIO=3&transport=websocket&sid=71743c05e43647a8b6a8447adefb6711 HTTP/1.1" 200 0 0.069719
    6f795141db094ae7990c580eb59546d4: Sending packet OPEN data {'sid': '6f795141db094ae7990c580eb59546d4', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
    CCCCCCCCCCCCCCCCCCCCCCCCC
    71743c05e43647a8b6a8447adefb6711: Sending packet MESSAGE data 2["update_rooms_list",{"rooms":[],"num_players":2}]
    6f795141db094ae7990c580eb59546d4: Sending packet MESSAGE data 0
    127.0.0.1 - - [10/Mar/2018 16:56:59] "GET /socket.io/?EIO=3&transport=polling&t=M8HVDxu HTTP/1.1" 200 401 0.001077
    (25414) accepted ('127.0.0.1', 34656)
    6f795141db094ae7990c580eb59546d4: Received request to upgrade to websocket
    6f795141db094ae7990c580eb59546d4: Received packet MESSAGE data 2["join_rooms_list"]
    6f795141db094ae7990c580eb59546d4: Sending packet MESSAGE data 2["update_rooms_list",{"rooms":[],"num_players":2}]
    127.0.0.1 - - [10/Mar/2018 16:56:59] "POST /socket.io/?EIO=3&transport=polling&t=M8HVDzS.0&sid=6f795141db094ae7990c580eb59546d4 HTTP/1.1" 200 219 0.001134
    127.0.0.1 - - [10/Mar/2018 16:56:59] "GET /socket.io/?EIO=3&transport=polling&t=M8HVDzS&sid=6f795141db094ae7990c580eb59546d4 HTTP/1.1" 200 288 0.007168
    6f795141db094ae7990c580eb59546d4: Sending packet NOOP data None
    127.0.0.1 - - [10/Mar/2018 16:56:59] "GET /socket.io/?EIO=3&transport=polling&t=M8HVD_0&sid=6f795141db094ae7990c580eb59546d4 HTTP/1.1" 200 235 0.000258
    6f795141db094ae7990c580eb59546d4: Upgrade to websocket successful
    6f795141db094ae7990c580eb59546d4: Received packet PING data None
    6f795141db094ae7990c580eb59546d4: Sending packet PONG data None

The first and last connection upgraded to websocket successfully. But the second failed because of the quick page reload. So no `on_disconnect` was called for it.

Is this expected? Any tips about how to avoid it?

**Comment by miguelgrinberg** [comment]
Not sure I follow your reasoning. The first connection was a websocket connection, which detects disconnects immediately. The second connection failed the websocket upgrade so it stayed on polling. To detect a polling disconnect some time needs to pass, did you want long enough to see if the disconnect arrived? It can take up to a minute.

**Comment by andresmrm** [comment]
> The second connection failed the websocket upgrade so it stayed on polling. To detect a polling disconnect some time needs to pass, did you wait long enough to see if the disconnect arrived? It can take up to a minute.

Yes, I waited more than a minute. Just to make sure I tested again and waited more than 30min. In the server, even after days, the `on_disconnect` is not being called.

**Comment by miguelgrinberg** [comment]
Are you using latest versions of flask-socketio, python-socketio and python-engineio packages?

**Comment by andresmrm** [comment]
Thanks for pointing out, they were outdated:

    Flask-SocketIO (2.9.3)
    python-socketio (1.8.4)
    python-engineio (2.0.2)

Updated to:

    Flask-SocketIO (2.9.6)
    python-engineio (2.0.3)
    python-socketio (1.9.0)

It seems to have helped. Now:
1. Sometimes it closes some of the lost connections (the ones left behind when the page quickly reloads) while the browser is still on the page, about 1min after they are lost. (good behavior)
2. And closes some other of the lost connections when the browser leaves the page. (ok behavior)
3. But some lost connections remain even after that. (bad behavior)

I would say that the stage the connection was stopped is what determines in which of the above three categories a connection will fall. And based on some tests, it seems a connection will be in the third category when it hadn't time even to request an upgrade to websocket.

In the log bellow one lost connection remained even after more than 1min and closing the page. (it seems to be the `67f543e3bd9e4e37ba512d9bef129e14` )

    (6596) wsgi starting up on http://0.0.0.0:5000
    (6596) accepted ('127.0.0.1', 40490)
    ac73a7a3c7b941898f52ec5cd1bc1033: Sending packet OPEN data {'sid': 'ac73a7a3c7b941898f52ec5cd1bc1033', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
    CCCCCCCCCCCCCCCCCCCCCCCCC
    ac73a7a3c7b941898f52ec5cd1bc1033: Sending packet MESSAGE data 0
    127.0.0.1 - - [12/Mar/2018 06:59:51] "GET /socket.io/?EIO=3&transport=polling&t=M8PfkQW HTTP/1.1" 200 401 0.001423
    (6596) accepted ('127.0.0.1', 40492)
    ac73a7a3c7b941898f52ec5cd1bc1033: Received request to upgrade to websocket
    ac73a7a3c7b941898f52ec5cd1bc1033: Sending packet NOOP data None
    127.0.0.1 - - [12/Mar/2018 06:59:51] "GET /socket.io/?EIO=3&transport=polling&t=M8PfkQW.0&sid=ac73a7a3c7b941898f52ec5cd1bc1033 HTTP/1.1" 200 235 0.000207
    ac73a7a3c7b941898f52ec5cd1bc1033: Upgrade to websocket successful
    ac73a7a3c7b941898f52ec5cd1bc1033: Received packet MESSAGE data 2["join_rooms_list"]
    ac73a7a3c7b941898f52ec5cd1bc1033: Sending packet MESSAGE data 2["update_rooms_list",{"rooms":[],"num_players":1}]
    DDDDDDDDDDDDDDDDDDDDDDDDD
    ac73a7a3c7b941898f52ec5cd1bc1033: Sending packet MESSAGE data 2["update_rooms_list",{"rooms":[],"num_players":0}]
    08ca2d7e9dad49dcac924ed57f5147c3: Sending packet OPEN data {'sid': '08ca2d7e9dad49dcac924ed57f5147c3', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
    CCCCCCCCCCCCCCCCCCCCCCCCC
    08ca2d7e9dad49dcac924ed57f5147c3: Sending packet MESSAGE data 0
    127.0.0.1 - - [12/Mar/2018 06:59:54] "GET /socket.io/?EIO=3&transport=polling&t=M8PflE4 HTTP/1.1" 200 401 0.001002
    (6596) accepted ('127.0.0.1', 40496)
    08ca2d7e9dad49dcac924ed57f5147c3: Received request to upgrade to websocket
    (6596) accepted ('127.0.0.1', 40498)
    08ca2d7e9dad49dcac924ed57f5147c3: Received packet MESSAGE data 2["join_rooms_list"]
    08ca2d7e9dad49dcac924ed57f5147c3: Sending packet MESSAGE data 2["update_rooms_list",{"rooms":[],"num_players":1}]
    127.0.0.1 - - [12/Mar/2018 06:59:54] "POST /socket.io/?EIO=3&transport=polling&t=M8PflFe.0&sid=08ca2d7e9dad49dcac924ed57f5147c3 HTTP/1.1" 200 219 0.001311
    127.0.0.1 - - [12/Mar/2018 06:59:54] "GET /socket.io/?EIO=3&transport=polling&t=M8PflFe&sid=08ca2d7e9dad49dcac924ed57f5147c3 HTTP/1.1" 200 288 0.010941
    08ca2d7e9dad49dcac924ed57f5147c3: Failed websocket upgrade, no PING packet
    127.0.0.1 - - [12/Mar/2018 06:59:54] "GET /socket.io/?EIO=3&transport=websocket&sid=08ca2d7e9dad49dcac924ed57f5147c3 HTTP/1.1" 200 0 0.021712
    a53cb4e21c4c41c580f8c0759567457f: Sending packet OPEN data {'sid': 'a53cb4e21c4c41c580f8c0759567457f', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
    CCCCCCCCCCCCCCCCCCCCCCCCC
    08ca2d7e9dad49dcac924ed57f5147c3: Sending packet MESSAGE data 2["update_rooms_list",{"rooms":[],"num_players":2}]
    a53cb4e21c4c41c580f8c0759567457f: Sending packet MESSAGE data 0
    127.0.0.1 - - [12/Mar/2018 06:59:55] "GET /socket.io/?EIO=3&transport=polling&t=M8PflLu HTTP/1.1" 200 401 0.000906
    (6596) accepted ('127.0.0.1', 40500)
    a53cb4e21c4c41c580f8c0759567457f: Received request to upgrade to websocket
    a53cb4e21c4c41c580f8c0759567457f: Received packet MESSAGE data 2["join_rooms_list"]
    a53cb4e21c4c41c580f8c0759567457f: Sending packet MESSAGE data 2["update_rooms_list",{"rooms":[],"num_players":2}]
    127.0.0.1 - - [12/Mar/2018 06:59:55] "POST /socket.io/?EIO=3&transport=polling&t=M8PflNS.0&sid=a53cb4e21c4c41c580f8c0759567457f HTTP/1.1" 200 219 0.001328
    127.0.0.1 - - [12/Mar/2018 06:59:55] "GET /socket.io/?EIO=3&transport=polling&t=M8PflNS&sid=a53cb4e21c4c41c580f8c0759567457f HTTP/1.1" 200 288 0.010479
    a53cb4e21c4c41c580f8c0759567457f: Sending packet NOOP data None
    a53cb4e21c4c41c580f8c0759567457f: Failed websocket upgrade, expected UPGRADE packet, received None instead.
    127.0.0.1 - - [12/Mar/2018 06:59:55] "GET /socket.io/?EIO=3&transport=websocket&sid=a53cb4e21c4c41c580f8c0759567457f HTTP/1.1" 200 0 0.062986
    67f543e3bd9e4e37ba512d9bef129e14: Sending packet OPEN data {'sid': '67f543e3bd9e4e37ba512d9bef129e14', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
    CCCCCCCCCCCCCCCCCCCCCCCCC
    08ca2d7e9dad49dcac924ed57f5147c3: Sending packet MESSAGE data 2["update_rooms_list",{"rooms":[],"num_players":3}]
    a53cb4e21c4c41c580f8c0759567457f: Sending packet MESSAGE data 2["update_rooms_list",{"rooms":[],"num_players":3}]
    67f543e3bd9e4e37ba512d9bef129e14: Sending packet MESSAGE data 0
    127.0.0.1 - - [12/Mar/2018 06:59:55] "GET /socket.io/?EIO=3&transport=polling&t=M8PflTi HTTP/1.1" 200 401 0.001171
    7e363c6647e241f7bfae1c333beb9491: Sending packet OPEN data {'sid': '7e363c6647e241f7bfae1c333beb9491', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
    CCCCCCCCCCCCCCCCCCCCCCCCC
    08ca2d7e9dad49dcac924ed57f5147c3: Sending packet MESSAGE data 2["update_rooms_list",{"rooms":[],"num_players":4}]
    a53cb4e21c4c41c580f8c0759567457f: Sending packet MESSAGE data 2["update_rooms_list",{"rooms":[],"num_players":4}]
    7e363c6647e241f7bfae1c333beb9491: Sending packet MESSAGE data 0
    127.0.0.1 - - [12/Mar/2018 06:59:56] "GET /socket.io/?EIO=3&transport=polling&t=M8PflbW HTTP/1.1" 200 401 0.001575
    (6596) accepted ('127.0.0.1', 40506)
    7e363c6647e241f7bfae1c333beb9491: Received request to upgrade to websocket
    7e363c6647e241f7bfae1c333beb9491: Sending packet NOOP data None
    127.0.0.1 - - [12/Mar/2018 06:59:56] "GET /socket.io/?EIO=3&transport=polling&t=M8PflbW.0&sid=7e363c6647e241f7bfae1c333beb9491 HTTP/1.1" 200 235 0.028422
    7e363c6647e241f7bfae1c333beb9491: Received packet MESSAGE data 2["join_rooms_list"]
    7e363c6647e241f7bfae1c333beb9491: Sending packet MESSAGE data 2["update_rooms_list",{"rooms":[],"num_players":4}]
    127.0.0.1 - - [12/Mar/2018 06:59:56] "POST /socket.io/?EIO=3&transport=polling&t=M8PflbW.1&sid=7e363c6647e241f7bfae1c333beb9491 HTTP/1.1" 200 219 0.001041
    7e363c6647e241f7bfae1c333beb9491: Upgrade to websocket successful
    7e363c6647e241f7bfae1c333beb9491: Received packet PING data None
    7e363c6647e241f7bfae1c333beb9491: Sending packet PONG data None
    7e363c6647e241f7bfae1c333beb9491: Received packet PING data None
    7e363c6647e241f7bfae1c333beb9491: Sending packet PONG data None
    7e363c6647e241f7bfae1c333beb9491: Received packet PING data None
    7e363c6647e241f7bfae1c333beb9491: Sending packet PONG data None
    7e363c6647e241f7bfae1c333beb9491: Received packet PING data None
    7e363c6647e241f7bfae1c333beb9491: Sending packet PONG data None
    7e363c6647e241f7bfae1c333beb9491: Received packet PING data None
    7e363c6647e241f7bfae1c333beb9491: Sending packet PONG data None
    7e363c6647e241f7bfae1c333beb9491: Received packet PING data None
    7e363c6647e241f7bfae1c333beb9491: Sending packet PONG data None
    7e363c6647e241f7bfae1c333beb9491: Received packet PING data None
    7e363c6647e241f7bfae1c333beb9491: Sending packet PONG data None
    7e363c6647e241f7bfae1c333beb9491: Received packet PING data None
    7e363c6647e241f7bfae1c333beb9491: Sending packet PONG data None
    7e363c6647e241f7bfae1c333beb9491: Received packet PING data None
    7e363c6647e241f7bfae1c333beb9491: Sending packet PONG data None
    7e363c6647e241f7bfae1c333beb9491: Received packet PING data None
    7e363c6647e241f7bfae1c333beb9491: Sending packet PONG data None
    7e363c6647e241f7bfae1c333beb9491: Received packet PING data None
    7e363c6647e241f7bfae1c333beb9491: Sending packet PONG data None
    7e363c6647e241f7bfae1c333beb9491: Received packet PING data None
    7e363c6647e241f7bfae1c333beb9491: Sending packet PONG data None
    7e363c6647e241f7bfae1c333beb9491: Received packet PING data None
    7e363c6647e241f7bfae1c333beb9491: Sending packet PONG data None

    DDDDDDDDDDDDDDDDDDDDDDDDD
    08ca2d7e9dad49dcac924ed57f5147c3: Client is gone, closing socket
    DDDDDDDDDDDDDDDDDDDDDDDDD
    08ca2d7e9dad49dcac924ed57f5147c3: Client is gone, closing socket
    a53cb4e21c4c41c580f8c0759567457f: Client is gone, closing socket
    DDDDDDDDDDDDDDDDDDDDDDDDD
    08ca2d7e9dad49dcac924ed57f5147c3: Client is gone, closing socket
    a53cb4e21c4c41c580f8c0759567457f: Client is gone, closing socket
    7e363c6647e241f7bfae1c333beb9491: Sending packet MESSAGE data 2["update_rooms_list",{"rooms":[],"num_players":1}]
    7e363c6647e241f7bfae1c333beb9491: Sending packet MESSAGE data 2["update_rooms_list",{"rooms":[],"num_players":2}]
    Cannot send to sid a53cb4e21c4c41c580f8c0759567457f
    7e363c6647e241f7bfae1c333beb9491: Sending packet MESSAGE data 2["update_rooms_list",{"rooms":[],"num_players":3}]

    (6596) accepted ('127.0.0.1', 40536)
    0a66668ba5274b33870040373d253dea: Sending packet OPEN data {'sid': '0a66668ba5274b33870040373d253dea', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
    CCCCCCCCCCCCCCCCCCCCCCCCC
    0a66668ba5274b33870040373d253dea: Sending packet MESSAGE data 0
    127.0.0.1 - - [12/Mar/2018 07:05:49] "GET /socket.io/?EIO=3&transport=polling&t=M8Ph5n8 HTTP/1.1" 200 401 0.001258
    (6596) accepted ('127.0.0.1', 40538)
    0a66668ba5274b33870040373d253dea: Received request to upgrade to websocket
    0a66668ba5274b33870040373d253dea: Sending packet NOOP data None
    127.0.0.1 - - [12/Mar/2018 07:05:49] "GET /socket.io/?EIO=3&transport=polling&t=M8Ph5oi&sid=0a66668ba5274b33870040373d253dea HTTP/1.1" 200 235 0.000266
    0a66668ba5274b33870040373d253dea: Upgrade to websocket successful
    0a66668ba5274b33870040373d253dea: Received packet MESSAGE data 2["join_rooms_list"]
    0a66668ba5274b33870040373d253dea: Sending packet MESSAGE data 2["update_rooms_list",{"rooms":[],"num_players":2}]

**Comment by miguelgrinberg** [comment]
Okay, this is useful. What the background thread is doing is a broadcast, which requires all connected clients to be sent a message. This is an opportunity where disconnected clients are detected. I'll test this with my example, removing the broadcast, maybe if a client just disappears and the server never tries to send anything to it, I'm not detecting it as gone.

**Comment by sreecodeslayer** [comment]
Hi miguel,

I have a VueJS app with Flask-SocketIO deployed behind Nginx, with a config like below:

```
server {
    listen       80;
    server_name  IP_HERE;
    access_log /home/deploy/projects/flask-socket/logs/nginx_access.log;
    error_log /home/deploy/projects/flask-socket/logs/nginx_error.log;

    location / {
        root    /home/deploy/projects/flask-socket/foog_ui/dist;
        try_files $uri $uri/ @rewrites;
    }
    location @rewrites {
        root    /home/deploy/projects/flask-socket/foog_ui/dist;
        rewrite ^(.+)$ /index.html last;
    }
    location /socket.io {
        include proxy_params;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass http://127.0.0.1:8000/socket.io;
    }
    location /api/ {
        rewrite ^/api^/ /$1 break;
        proxy_pass http://localhost:8000/api/;
    }
    location /auth/ {
        rewrite ^/auth^/ /$1 break;
        proxy_pass http://localhost:8000/auth/;
    }
}

```

This works in the dev and on my localhost and I believe this has something to do with the Nginx configuration.
I have the engineio_logger enabled, let me know if you need any other logs.

```
[2018-12-20 07:02:53 +0000] [26273] [DEBUG] GET /socket.io/
[2018-12-20 07:02:53 +0000] [26273] [DEBUG] GET /socket.io/
ce4afffa8a7349159b0d78e220ea80b0: Received request to upgrade to websocket
ce4afffa8a7349159b0d78e220ea80b0: Failed websocket upgrade, no PING packet
```

I see this as polling on the browser network section to confirm the upgrade does not happen.
![screenshot from 2018-12-20 12-40-24](https://user-images.githubusercontent.com/5737888/50269529-79e00800-0454-11e9-9467-3c41a81e2419.png)

**Comment by miguelgrinberg** [comment]
@sreecodeslayer what version of the JS socket.io client are you using?

**Comment by sreecodeslayer** [comment]
@andresmrm Let me see what changed in mine. Thanks! :+1: 

@miguelgrinberg Am using [Vue SocketIO](https://github.com/MetinSeylan/Vue-Socket.io) that depends on `socket.io-client: 2.1.1`

**Comment by miguelgrinberg** [comment]
The client is fine. Not sure if the Vue wrapper changes things, I have never used it, but according to the log the client isn't sending the correct thing during the upgrade. Using gunicorn should also be fine, that's what I use on many of my projects.

You can try to connect directly over websocket, maybe that works better. I know that the React wrapper had some sort of problem that was avoided by going directly to websocket.

**Comment by sreecodeslayer** [comment]
but am curious why would it then work on local dev via gunicorn itself and the Vue SPA server over http-server :thinking: 

I get the upgrade working and all the events work fine :thinking:

**Comment by miguelgrinberg** [comment]
Here is another thing you can test: run your gunicorn with `-b 0.0.0.0:8000` and then try to connect directly on port 8000, bypassing nginx. If that works, then we know for sure something in nginx is causing the problem.

**Comment by miguelgrinberg** [comment]
This issue has been addressed with the introduction of the service task in python-engineio.
