### ISSUE TITLE
Error when deploying Flask-SocketIO and Redis message_queue on AWS Elastic Beanstalk

### ISSUE THREAD

**Issue by uri-may** [miguelgrinberg/Flask-SocketIO#625]
I'm trying to create the following architecture work on Amazon:

**Publisher (EC2 Server) -> Redis (Elastic cache Cluster) -> Flask-SocketiO Auto Scaling Group (Elastic Beanstalk) -> Browser (Javascript Socket.IO library)**

I have the publisher server, Redis and the Flask-SocketIO talking to one another (Had to put them in a VPC and take care of seucrity groups) but I can't seem to have the Flask-SocketIO to work. It crashes on the first message it needs to emit.

Below is the error message from the Beanstalk environment logs followed by the application.py code and the requirements.txt. 

**Logs:**
https://gist.github.com/uri-may/62dcbb814b39c527795cac59f7e5206e

**application.py:**
https://gist.github.com/uri-may/616e1f9ae2356152a7abc0806bfd1fe5

**requirements.txt**
`
click==6.7
Flask==0.12.2
Flask-SocketIO==2.9.3
gevent==1.2.2
gevent-websocket==0.10.1
greenlet==0.4.12
itsdangerous==0.24
Jinja2==2.10
MarkupSafe==1.0
python-engineio==2.0.2
python-socketio==1.8.4
redis==2.10.6
six==1.11.0
Werkzeug==0.14.1
`

Would love to hear any inputs or suggestion I'm pretty stuck with this one.
It's all work locally on my development environment.

Best.

**Comment by uri-may** [comment]
I've ended up using Docker deployment on Elastic Beanstalk with Gunicorn server behind an ELB. Works perfectly.
Uri.

**Comment by philippkeller** [comment]
@uri-may can you describe how you created the docker container and configured ELB?
