### ISSUE TITLE
Getting the current endpoint from inside the function

### ISSUE THREAD

**Issue by adamczi** [miguelgrinberg/Flask-SocketIO#626]
Hi,
I'm running multiple socketio.on('xxx') endpoints, with a decorator wrapped around it. Is it possible to somehow get the value of current endpoint (eg. 'xxx') preferably from inside the decorator? In regular flask app it would be something like request.path, but I couldn't find a way. I guess it's possible, since on an error the traceback returns needed endpoint. Thanks in advance!
Adam

**Comment by miguelgrinberg** [comment]
Yes. Use `request.event['message']` to get the event name.

**Comment by adamczi** [comment]
Thanks for your help!
