### ISSUE TITLE
Persistent server-side session storage using sockets and HTTP routes

### ISSUE THREAD

**Issue by ethman** [miguelgrinberg/Flask-SocketIO#629]
Hello,

I'm not sure if this is the correct place to ask this, but Miguel seems to be a wealth of Flask knowledge (not to mention that he wrote this library), I figured I'd try here. Additionally, I'm working on my first webapp, so I'm still new to this world. Forgive me if this is the wrong forum.

I'm working on a flask app that uses Flask-SocketIO and Flask-Sessions. I know from the Flask-SocketIO documentation that when `session` is accessed it gets forked from the `session` object that regular HTTP request routes see. I have all of the logic and state information needed for a single user stored as one custom object that gets put into the Flask `session` when it exits a route (or `@socket.on` entry point). Because of the front end libraries I'm using, I will probably need to use a mix of sockets and HTTP requests. My question is, what is the best way to maintain an up-to-date state between both types of entry points?

Thanks!

**Comment by miguelgrinberg** [comment]
If you use server-side sessions, then things are much better, the forking behavior can be disabled by passing `manage_session=False` when you create your `SocketIO` instance. I wrote a blog article about this: https://blog.miguelgrinberg.com/post/flask-socketio-and-the-user-session.

**Comment by ethman** [comment]
Awesome! Thanks for all of your help! And thanks for all of the great tutorials!
