### ISSUE TITLE
My Flask socketio is too slow

### ISSUE THREAD

**Issue by rils** [miguelgrinberg/Flask-SocketIO#634]
I have python flask at server end and js on client side. I want to send some logs to client without a request from client. I am trying to implement it with flask socket.io plugin.Everything looks OK, thanks for below blogs. https://blog.miguelgrinberg.com/post/easy-websockets-with-flask-and-geventBut I can see regular polling going to server and it takes too long to respond. Each polling takes almost 5secs. This delays my other AJAX calls too. What could be the reason ?

https://stackoverflow.com/questions/48661706/flask-socketio-is-too-slow

server side-
`@socketio.on('connect', namespace='/test')
def connect():
    global thread
    with thread_lock:
        if thread is None:
            thread = socketio.start_background_task(target=background_thread)
    socketio.emit('server_msg', {'cause': 'connection', 'status': 'Success', 'count': len(CLIENT.keys())},
                  namespace='/test')

@socketio.on('client_msg', namespace='/test')
def client_msg(msg):
    print(msg)  # TODO: process this msg

def background_thread():
    count = 0
    while True:
        socketio.sleep(5)
        count += 1
        socketio.emit('server_msg',
                      {'cause': 'poll', 'status': 'count', count : len(CLIENT.keys())},
                      namespace='/test')`

Cleint JS-
`        var socket = io.connect(location.protocol + '//' + document.domain + ':' + location.port + namespace);
        socket.on('connect', function () {
            // we emit a connected message to let knwo the client that we are connected.
            socket.emit('client_msg', {cause: 'connection', details: location});
        });
        socket.on('server_msg', function (msg) {
            writeLog('log', 'Received ' + msg.cause + ' ' + msg.status, 'warning')
        });
        // socket.emit('client_msg', {cause: 'connection', details: location});`

network load-
[https://i.stack.imgur.com/XgD2z.jpg](url)

**Comment by AndCycle** [comment]
if you see regular polling there, that means things go wrong,
you shouldn't see any polling after connection upgrade to websocket,
it keeps polling because it failed to establish websocket,

the example you used isn't doing the right thing for server setup, 
it just run, without any underlay websocket server support.
