### ISSUE TITLE
flask socket io, eventlet, context problem

### ISSUE THREAD

**Issue by juntiedt2** [miguelgrinberg/Flask-SocketIO#636]
I developed a flaskserver application which gets input from different sensors through a callback function. This works great with flask development server.
Now I wanted to use web-sockets with my flask application. It works ok as long I do not register my call back function in the joiner class, which of course is the most important input. Doing this I am getting a context problem. 
How can solve this issue?
a) solve the context problem
b)or would it be possible to send these sensor data to Flask through websockets and then from flask to my web page

```
@socketio.on('change_R8',` namespace='/fl')
def change_Relay8(R8_stat):
    if R8_stat == 'on':
	    #print("Relay 8 on")
        ui.set_relay(8,1,0)
    elif R8_stat == 'off':
	    #print("Relay 8 off")
        ui.set_relay(8,0,0)	

# change analog output
       
@socketio.on('change_ao', namespace='/fl')
def change_ao(ao_value):
    #print("setze ao auf: ", ao_value)
    ui.set_ao(ao_value)	        
		
#- call back function from UniPi_joiner_class----------------------------

def unipi_change(event, data):
    #print("Webserver in: ",event,data)
    emit_to_all_clients(event, data)

if __name__ == "__main__":
    log.text("Flask Web-Server gestartet")
    print("Flask Web-Server gestartet")
    joiner = unipi_joiner("10.0.0.52",0)
    joiner.on_unipi_change(unipi_change)
    socketio.run(app, host='127.0.0.1', use_reloader=False, debug=False)
    log.text("Flask Web-Server beendet")
```

**Comment by miguelgrinberg** [comment]
Please include the stack trace of the error that you get. Also add information about the `unipi_joiner()` function. What kind of server it creates?
