### ISSUE TITLE
use Flask-SocketIO with Blueprints

### ISSUE THREAD

**Issue by yatishb** [miguelgrinberg/Flask-SocketIO#64]
Hi, I would like to know how I could use Blueprints with flask-socketio. I would like to keep all the socket handlers in a separate module and I believe this can be done using blueprints in flask. However, I haven't been able to accomplish this and there aren't sufficient resources to help me with this. Could you kindly help me how this can be achieved?

**Comment by zhuangchaoxi** [comment]
Thank you to miguelgrinberg.

**Comment by engmsilva** [comment]
> O exemplo de aplicativo a seguir demonstra como estruturar um aplicativo maior que possui projetos:
> 
> https://github.com/miguelgrinberg/Flask-SocketIO-Chat

How to add the COLORS configuration? Because using a single file without a blueprint, I configure it as follows:
`socketio = SocketIO(app, cors_allowed_origins="*")`

Taking advantage of the context, how do I make flask_socketio work together with pyngrok? The server runs normally when I'm on the local network, but when I try to connect to the public network the client is disconnected.

**Comment by miguelgrinberg** [comment]
@engmsilva the arguments that you pass to the `SocketIO` class can also  be passed on the `socketio.init_app()` call when you use an app factory function and blueprints.

I just tested an example app and can confirm that WebSocket does not appear to work. Not sure what I can do about it, but I'll see if I can find someone to discuss this with.

**Comment by yyyasmin** [comment]
Is it possible to use a package of flask_socekitio functions , as a blueprint inside a big flask project such as Miguel's mega tutorial microblog ?

**Comment by miguelgrinberg** [comment]
@yyyasmin Look at the [Flask-SocketIO-Chat](https://github.com/miguelgrinberg/Flask-SocketIO-Chat) project for an example of how to structure a large app with Socket.IO.

**Comment by yyyasmin** [comment]
Hi miguel
Thanks for your reply. I've Seen this project as an answer for somebody's
else's question. But would you please explain it as you did in your Mega
Tutorial?
Thankyou Yasmin



יסמין עמראן
תכנות , טיפול וחינוך מיוחד

**Comment by miguelgrinberg** [comment]
@yyyasmin the project I referenced is not part of a written tutorial, it is a standalone project intended for users to study on their own.

**Comment by yyyasmin** [comment]
can you shoe me an exampke of a sixjetio function insude a regular flask
project ( that is run by fkask and bot bu socketio )?

**Comment by miguelgrinberg** [comment]
@yyyasmin that is what the example I directed you to does.

**Comment by fili** [comment]
@miguelgrinberg This may help: https://github.com/kennethreitz/flask-sockets - here is an example of integrating blueprints. Integrating blueprints would be a major plus.

It might be good to get a working version of your code based on [this](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/appengine/flexible/websockets) so Google can update their example to an library which is more recently updated.

**Comment by miguelgrinberg** [comment]
@fili 

> Integrating blueprints would be a major plus

I'm not really sure you understand how Flask-SocketIO is different than this extension you referenced. What do you expect will be different if blueprints were supported? Did you see the example application I referenced above? How can you make it better with blueprints?

> It might be good to get a working version of your code based on this

You seem to be mixing up WebSocket with Socket.IO. They are not the same thing, you cannot swap out one for the other.

**Comment by fili** [comment]
@miguelgrinberg Thanks for the reply. I am well aware of the difference between websockets and socket.io. I was under the the apparently wrong impression that when I wanted to use socket.io integration with websockets in Flask on App Engine, this library might be useful. From your response I get the opposite, unexpected answer that this library is only working in one way (when the app structure set in stone and is based on the example mentioned above) and there is no flexibility in design to use this library with blueprints. **I very much appreciate the honest feedback**, saves me a few hours as my structure is very different and heavily blueprints dependent (luckily Flask is by design flexible for different app structures). I will try to use the other library then and integrate socket.io with that one. #staysafe!

**Comment by miguelgrinberg** [comment]
@fili 

> I was under the the apparently wrong impression that when I wanted to use socket.io integration with websockets in Flask on App Engine, this library might be useful

The example that you linked uses the abandoned Flask-Sockets extension. This extension uses gevent and gevent-websocket internally. Flask-SocketIO also includes support for gevent and gevent-websocket. This is why I really did not understand what you were asking. The underlying websocket implement is the same, so what do you think is missing?

> From your response I get the opposite, unexpected answer that this library is only working in one way

The contrary. I went out of my way to support the most commonly used websocket implementations.

> there is no flexibility in design to use this library with blueprints.

Blueprints would not help in any way with Socket.IO. From the Socket.IO point of view a blueprint is just a Python package. If you want to add your Socket.IO stuff in the same package as you are hosting a blueprint, feel free, but the blueprint itself does not provide any benefits to Socket.IO.

**Comment by yyyasmin** [comment]
thanks for updating me. Would you do a tutorial ( or extent of your mega
super gorges tutorial) about using flask with mediawiki ?




יסמין עמראן
תכנות , טיפול וחינוך מיוחד

**Comment by joch182** [comment]
Thank you @miguelgrinberg , i have been struggling to make it work, now it is working as expected

**Comment by yyyasmin** [comment]
Hello
Miguel you're the best as usual.
Do you have an example of using
Flask with blueprints + socket io + react all together?
I'll be grateful if you do




יסמין עמראן
תכנות , טיפול וחינוך מיוחד

**Comment by miguelgrinberg** [comment]
I don't. Sorry

**Comment by yyyasmin** [comment]
Do o you recommend using all 3 together to produce multiplayer s card games
?

**Comment by nmz787-intel** [comment]
@fili did you ever figure out how to use blueprints with `flask_sock`? I tried monkeypatching the `Sock` object over my existing blueprint objects (the object my blueprint modules call `.route()` on), but my server didn't hear my client's websocket requests.

**Comment by fili** [comment]
@nmz787-intel No, I went with other technology instead. Do share if you find a way to make this work.

**Comment by yyyasmin** [comment]
Hi,
would you write a post or  a video about combining flask and FastApi? I get
trouble with working asynchronously with a huge project that I based on
your microblog. On production ( railway, since heroku is no longer free) It
fails on timeout.




יסמין עמראן
תכנות , טיפול וחינוך מיוחד

**Comment by yyyasmin** [comment]
I think FastApi serves asynchronous functions better, And I have a function
that falls on timeout on production, which I want it to be
asynchronous within a huge synchronic flask project.




יסמין עמראן
תכנות , טיפול וחינוך מיוחד
