### ISSUE TITLE
call server generated functions

### ISSUE THREAD

**Issue by saisrinivas047** [miguelgrinberg/Flask-SocketIO#640]
hi @miguelgrinberg 

socketio = SocketIO(app,logger=True, engineio_logger=True)
@app.route('/transcribe', methods=['POST'])
def transcribe_audio():
    for i in range(0,count):
        filepath='/tmp/'+str(filePre)+'/'
        print filepath
        if not os.path.isdir(filepath):
            os.mkdir(filepath)
    	f="tmp/"+filePre+"-%03d.wav" % i
    	print f
        if os.path.isfile(f):
            trans=client.transcribe(f)
            **socketio.emit("msg1", trans)**
            text+=trans+"\n"

@socketio.on('connect', namespace='/transcribe')
def test():
    print 'aaaaaaaaaaaa'
    eventlet.spawn(transcribe_audio)

here eventlet.spawn() is calling before the route is triggered how to make ti wait for the route to get triggered and then run eventlet.spawn()

**Comment by miguelgrinberg** [comment]
You should move your `spawn()` call to a different event handler, not the connection one.
