### ISSUE TITLE
Heroku deployment issues

### ISSUE THREAD

**Issue by geraldsimms** [miguelgrinberg/Flask-SocketIO#641]
Hello,
I am experiencing an error after the deployment of the app in Heroku.

From the logs: 
```
File "/app/flask_socketio/namespace.py", line 1, in <module>
from socketio import Namespace as _Namespace
ImportError: cannot import name 'Namespace'
```

**Any idea how to solve this?**

What I did so far: 
- I proceeded as suggested in Issue #176.
- `Line 13` in `index.html`changed to: `var socket = io.connect('https://' + document.domain + ':' + location.port + namespace);`
- The `Procfile` and `requirements.txt` have been changed accordingly and the web dyno was set with `heroku ps:scale web=1`. 
- I copied the contents of the `example/` folder into the main folder (hope that wasn’t wrong, just got into Flask today)
- I tried changing the runtime in `runtime.txt` to `python-2.7` and afterwards to `python-3.6.4`, in both cases I get the same error.

Thanks in advance for any advice on this.

**Comment by miguelgrinberg** [comment]
Let me see your requirements.txt file please.

**Comment by Wombat1991** [comment]
Here:
```
anyjson==0.3.3
beautifulsoup4==4.4.1
billiard==3.3.0.21
blinker==1.4
celery==3.1.19
dominate==2.1.16
eventlet==0.17.4
Flask==0.10.1
Flask-Admin==1.3.0
Flask-Bootstrap==3.3.5.6
Flask-Login==0.3.1
Flask-Mail==0.9.1
flask-mongoengine==0.7.1
Flask-Principal==0.4.0
Flask-PyMongo==0.3.1
Flask-Security==1.7.4
Flask-SocketIO==1.1
Flask-SQLAlchemy==2.0
Flask-WTF==0.12
greenlet==0.4.9
gunicorn==18.0.0
itsdangerous==0.24
Jinja2==2.8
kombu==3.0.29
MarkupSafe==0.23
mongoengine==0.10.0
passlib==1.6.5
pep8==1.6.2
pymongo==2.9
python-engineio==0.8.0
python-socketio==0.7.0
pytz==2015.7
redis==2.10.5
requests==2.8.0
six==1.10.0
SQLAlchemy==1.0.8
Werkzeug==0.10.4
wheel==0.24.0
WTForms==2.0.2
```

**Comment by miguelgrinberg** [comment]
You are using a very old version of Flask-SocketIO. Please upgrade it by running `pip install --upgrade flask-socketio`.

**Comment by geraldsimms** [comment]
Works now. Thanks a lot for the help :)
