### ISSUE TITLE
Gunicorn fails to serve websockets after x number of clients

### ISSUE THREAD

**Issue by EndenDragon** [miguelgrinberg/Flask-SocketIO#642]
Hello, I am currently running my app on gunicorn with these settings:

Nginx:
```
upstream serv {
    server unix:/var/www/titanembeds.sock fail_timeout=0;
}

upstream servws {
    server unix:/var/www/titanembeds_ws.sock;
}

server {
    listen 80;
    server_name titanembeds.com;
    location / {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_buffering off;
        proxy_pass http://serv;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location /gateway/ {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_buffering off;
        proxy_pass http://servws;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
    listen 443 ssl;
    if ($scheme != "https") {
        return 301 https://$host$request_uri;
    }
}
```

gunicorn command: `/usr/bin/python3 /usr/bin/gunicorn3 --worker-class eventlet -w 1 -b unix:/var/www/titanembeds_ws.sock titanembeds.app:app`

I am not sure how why nginx is throwing 502 errors saying that gunicorn is busy.
Chrome: `WebSocket connection to 'wss://x.com/gateway/?EIO=3&transport=websocket' failed: Error during WebSocket handshake: Unexpected response code: 502`

nginx's error log: `2018/02/16 11:03:24 [error] 22247#22247: *1646 connect() to unix:/var/www/titanembeds_ws.sock failed (11: Resource temporarily unavailable) while connecting to upstream, client: 111.111.111.111, server: x.com, request: "GET /gateway/?EIO=3&transport=websocket HTTP/1.1", upstream: "http://unix:/var/www/titanembeds_ws.sock:/gateway/?EIO=3&transport=websocket", host: "x.com"`

The thing is, it works fine for about an hour or two after restarting both gunicorn and nginx in that order. Then it complains with 502s. Is there a way to run gunicorn without timing out some of my users?
This problem only happens to the gunicorn serving websockets as the one without websockets works no problem.

**Comment by miguelgrinberg** [comment]
Anything interesting in the gunicorn log?

**Comment by EndenDragon** [comment]
The gunicorn log outputs nothing interesting. The only output were the boot messages
```
root@endendragon:/home/endendragon# journalctl -u titanembedsws -f
-- Logs begin at Fri 2018-02-16 20:31:32 UTC. --
Feb 16 20:31:32 endendragon systemd[1]: titanembedsws.service: Failed to reset devices.list: Operation not permitted
Feb 16 20:31:32 endendragon systemd[1]: titanembedsws.service: Failed to set invocation ID on control group /system.slice/titanembedsws.service, ignoring: Operation not permitted
Feb 16 20:31:32 endendragon systemd[1]: Started gunicorn server instance configured to serve titanembeds.
Feb 16 20:31:32 endendragon gunicorn3[206]: [2018-02-16 20:31:32 +0000] [206] [INFO] Starting gunicorn 19.7.1
Feb 16 20:31:32 endendragon gunicorn3[206]: [2018-02-16 20:31:32 +0000] [206] [INFO] Listening at: unix:/var/www/titanembeds_ws.sock (206)
Feb 16 20:31:32 endendragon gunicorn3[206]: [2018-02-16 20:31:32 +0000] [206] [INFO] Using worker: eventlet
Feb 16 20:31:32 endendragon gunicorn3[206]: [2018-02-16 20:31:32 +0000] [441] [INFO] Booting worker with pid: 441

```

**Comment by miguelgrinberg** [comment]
Can't really think of anything that could cause this in a silent way. I suggest you scan your system logs and look for errors such as running out of memory, out of file handles, etc. You may also want to try using a regular socket and see if that makes any difference.

**Comment by EndenDragon** [comment]
I switched to gevent for a while and this is what it outputted http://termbin.com/4elr

**Comment by miguelgrinberg** [comment]
The stack trace in your logs is an error in your application:

```
   File "/home/titan/Titan/webapp/titanembeds/oauth.py", line 34, in discordrest_from_user
     req = discord.get("https://discordapp.com/api/v6{}".format(endpoint))
```

That request that you are sending is not working. As a side note, I assume you monkey patched the std library with gevent, right? You can't use the Python networking functions unless they are monkey patched to be compatible with gevent.

**Comment by EndenDragon** [comment]
It worked great for the first hour or so. But when about 50 websockets connections are made, it throws a "Device or resource busy" error. I can't think of a way for which the call to get an api would fail. Though if i restart the gunicorn process, it would work again and essentially reset the hour timer before going down again.
Yes I did monkey patch. It is done the moment gunicorn imports the app.py https://github.com/TitanEmbeds/Titan/blob/master/webapp/titanembeds/app.py

**Comment by miguelgrinberg** [comment]
Why is your request to discord is failing? Have you investigated that?

**Comment by EndenDragon** [comment]
That I am not sure. However, I'm not sure if you've considered me solving the problem when I setup a crontab to restart the gunicorn process every hour. It *seems* to have fixed the issue by doing that...

**Comment by miguelgrinberg** [comment]
Sure, I understand what the problem is, but so far you haven't found any indication of problems in any log files, which is odd. I was asking about the request error because it is simply the only thing that looks to be failing. Not sure if it has to do with the problem or not.

You may want to try adding more logging to the server. Add `engineio_logger=True` to your `SocketIO` class to see if that shows any useful information about the problem.

**Comment by EndenDragon** [comment]
I left it running w/ logging for about a few hours. The issue is reproduced, however there are no out of ordinary lines of log to be seen. http://termbin.com/ndpo

Curious to think, maybe theres too much users connecting into the websocket that it hungs up? Is that an issue? Otherwise, what is the problem you had in mind?

**Comment by miguelgrinberg** [comment]
The log snippet that you shared covers just three minutes, and I see no attempts from clients to getting a new connection in that period of time.  Can you share the entire log?

**Comment by EndenDragon** [comment]
Here is the entire log of when I switched on engineio logging to about two hours ago when I noticed that the issue has happened. https://titanembeds.com/public/twsjournalctl.log

**Comment by EndenDragon** [comment]
Hey @miguelgrinberg, revisiting this issue, could it be the issue from blocking functions? I currently use stuff like flask-sqlalchemy that takes a load on the webapp processes.

I noticed that might be the case ever since there was a similar problem on a different project I'm working on, which is a python bot. I had the whole bot on asyncio, however when adding sqlalchemy to the mix, the bot would just disconnect without any traces after a few hours. That is the equivalent to the flask webapp throwing the resource unavailable errors after a few hours (not after xx clients). I used asyncio's executor to run my db operations of my bot in a separate thread and the issue is resolved.

**Comment by miguelgrinberg** [comment]
Not sure if blocking functions are the source of this particular problem, but you can't have blocking functions in an async application anyway, so you should remove or fix those so that they are async.

SQLAlchemy by itself is not a problem. If you use a database server, then all communications with the server are done via sockets, and those are monkey patched to be async.

**Comment by miguelgrinberg** [comment]
Please reopen if you still need my help with this issue.
