### ISSUE TITLE
Issues running multiple workers with flask-socketio

### ISSUE THREAD

**Issue by edyirdaw** [miguelgrinberg/Flask-SocketIO#643]
Hello Miguel, nice work you doing for python in general :). I have two questions here

(1) can we use lighttpd to run mulitple workers with flask-socketio?

(2) here is myapp.fcgi that I use

```
#!/usr/bin/python3
import sys

from flup.server.fcgi import WSGIServer
from myapp import socketio

if __name__ == '__main__':
    WSGIServer(socketio).run()
```
and of course in myapp i have 
```
app = Flask(__name__)
socketio = SocketIO(app)
```
at the top followed by my codes and then at the bottom

```
if __name__ == '__main__':
    socketio.run(app)
```

But when i ran ./myapp.fcgi I get the following error below but the critical error seems to me "TypeError: 'SocketIO' object is not callable".  What am I doing wrong??

```
WSGIServer: missing FastCGI param REQUEST_METHOD required by WSGI!
WSGIServer: missing FastCGI param SERVER_NAME required by WSGI!
WSGIServer: missing FastCGI param SERVER_PORT required by WSGI!
WSGIServer: missing FastCGI param SERVER_PROTOCOL required by WSGI!
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flup/server/fcgi_base.py", line 576, in run
    protocolStatus, appStatus = self.server.handler(self)
  File "/usr/local/lib/python3.5/dist-packages/flup/server/fcgi_base.py", line 1175, in handler
    result = self.application(environ, start_response)
TypeError: 'SocketIO' object is not callable
Status: 500 Internal Server Error
Content-Type: text/html

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>Unhandled Exception</title>
</head><body>
<h1>Unhandled Exception</h1>
<p>An unhandled exception was thrown by the application.</p>
</body></html>
```

**Comment by miguelgrinberg** [comment]
First of all, does lighttpd/fcgi support WebSocket? I don't think it does, so right there you have a big problem. Also not sure if there are sticky sessions in lighttpd, which are required when working with multiple workers and Socket.IO.

The error that you are getting is actually your bug. The `socketio` instance is not a WSGI callable, so you cannot pass it to a WSGI server. You need to wrap it with the WSGI middleware that is provided, and then pass the middleware to the server.

**Comment by edyirdaw** [comment]
Thanks for the fast response.

Lets say I want to use nginx. Currently I have only one server. 
(1)
It seems that I dont need to setup fastcgi with flask-socketio. Flask needs a fastcgi setup to integrate it with nginx. But it seems that flask-socketio does not need that with nginx. Am I right?

(2)
My application requirements is that my flask-socketio app servers multiple users with many flask-socketio workers all in ONE server. It seems to me that the way to achieve this is start running myapp.py
```
if __name__ == '__main__':
    socketio.run(app)
```
and then use the config file for nginx as provided in the flask-socketio page which is
```
server {
    listen 80;
    server_name _;

    location / {
        include proxy_params;
        proxy_pass http://127.0.0.1:5000;
    }

    location /socket.io {
        include proxy_params;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass http://127.0.0.1:5000/socket.io;
    }
}
```
Does this mean nginx spawns multiple instances of myapp.py? I get the feeling that nginx would not spawn multiple instances of myapp.py and hence many flask-socketio workers.  What I need is that when i start myapp.py, I will have like 10 or 20 independent myapp.py applications serving multiple users in one server. Can flask-socketio do that?

**Comment by edyirdaw** [comment]
Thanks for the fast response. I experimented a little and succeeded in running nginx with flask-socketio!

I had no idea flask-socketio didnot need a fastcgi config. 

I have some remaining issues though. 

(1)
Is this nginx config file correct for many flask-socketio workers? I got it from the flask-socketio website. What I am worried is only the port 5000 is listed in the "proxy_pass" parameter and the other ports are not listed. Would nginx be able to get the other ones still?

```
upstream socketio_nodes {
    ip_hash;

    server 127.0.0.1:5000;
    server 127.0.0.1:5001;
    server 127.0.0.1:5002;
    # to scale the app, just add more nodes here!
}

server {
    listen 7865;
    server_name _;

    location / {
        include proxy_params;
        proxy_pass http://127.0.0.1:5000;

    }

    location /socket.io {
        include proxy_params;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass http://127.0.0.1:5000/socket.io;

    }
}

```
(2) In the above example there are three flask-socketio servers. What is ur prefered way of running all three ?
```
if __name__ == '__main__':
    socketio.run(app, port)
```
```
if __name__ == '__main__':
    socketio.run(app, port=5001)
```
```
if __name__ == '__main__':
    socketio.run(app, port=5002)
```

Do u open a terminal and run each or you write a script and ran them say using some bash command? This becomes important in case
u have so many flask-socketio workers and opening too much terminal might not be convinient.

(3) It seems to me that nginx does load balancing just by ip address. So two requests that come from a single pc would still be assigned
to the same flask-socketio worker i guess. Is that so? I guess this is not the problem of flask-socketio but that of nginx load balancing strategy.

Thanks for your time :)

**Comment by miguelgrinberg** [comment]
(1) No, your config is wrong. Change the two `proxy_pass` lines to:

    proxy_pass http://socketio_nodes;
    proxy_pass http://socketio_nodes/socket.io

(2) To run multiple servers what I would do is set the port in a `PORT` environment variable, then you can have a single starter file that does `socketio.run(app, port=int(os.environ['PORT']))`.

(3) the `ip_hash` directive in your upstream block makes nginx use sticky sessions, which are required for Socket.IO. That means that a given client will always be assigned the same server instance. Without this, Socket.IO does not work.

**Comment by edyirdaw** [comment]
Thanks. Answers (1) and (2) have worked.

>(3) the ip_hash directive in your upstream block makes nginx use sticky sessions, which are required for Socket.IO. That means that a given client will always be assigned the same server instance. Without this, >Socket.IO does not work.

Yes I know that. My problem is when I use the ip_hash directive, nginx uses the ip address of the client to stick the client with one of the servers. But this is not good enough when both clients come from the same pc since they both have the same ip address. Are there other sticky session directives than ip_hash that use finer ways of hashing? And if so, an example configuration would be very helpful.  Although this is out of the discussion of flask-socketio and is a discussion of nginx, feel free not to answer it :). I just wanted to make myself clear regarding the question.

But with timing of starting the servers and loading the two clients, I was able to assign the two clients that come from same ip address the different servers available. What happens sometimes is both clients are assigned to the same flask-socketio server leaving one of the two servers idle. 

Overall thank you very much! You solved a major road-block for my app development problems. Really hard to get it done when you don't have much experience and you have little time. Much appreciated a high-end developer gives time to answer such questions.

**Comment by miguelgrinberg** [comment]
There a few custom modules for nginx that implement other forms of sticky sessions ([here is one](https://bitbucket.org/nginx-goodies/nginx-sticky-module-ng)). If you are willing to spend money, then Nginx Plus will also do that. Another alternative is to is [HAProxy](http://www.haproxy.org/) instead of nginx, which does have support for cookie-based sticky sessions in the open source version.

**Comment by edyirdaw** [comment]
Yes cookie based ones might help. Thanks so much for your suggestions and help! Wonderful experience overall. Keep it up.

**Comment by kazitanvirahsan** [comment]
I was reading this thread to learn how to scale socket.io even before starting implementing it. Simply brilliant.
