### ISSUE TITLE
Multiprocessing Queue implementation to Flask-SocketIO server

### ISSUE THREAD

**Issue by Sarillus** [miguelgrinberg/Flask-SocketIO#645]
I run server using Gevent and Im using websockets to get data from sliders on web page.
I need to take message I receive in Python program, write it into multiprocessing queue and then use it in another process. 
I figured that I can read from queue  in message receive functions, but I cant put anything there. 
Im complete begginer to server programing and multiprocessing. Is there any way to do it?

Code example. 

```
reverseQ.Queue(1)

app = Flask(__name__)
socketio = SocketIO(app, engineio_logger=True, async_mode="gevent")

@app.route('/')
def index():
    return render_template('main.html')

@socketio.on('reverse', namespace="/")
def reverse_function(data):
	reverseQ.put(data)
	return

def reverseCheck():
	while True:
           print(reverseQ.get())
	
	return

if __name__ == '__main__':	
	print("Server is running")
	app.debug = True
	process0 = Process(target=reverseCheck, args=())
	process0.start()
	socketio.run(app, debug=True, host='0.0.0.0',use_reloader=False)
```

**Comment by miguelgrinberg** [comment]
The queue that you use must be compatible with gevent. You don't show how you initialize this queue, so you'll need to check that yourself.

**Comment by Sarillus** [comment]
Thank you very much! I have used Gevent Queues and everything works now!
