### ISSUE TITLE
Unexpected error "timed out", closing connection

### ISSUE THREAD

**Issue by saisrinivas047** [miguelgrinberg/Flask-SocketIO#646]
Hi @miguelgrinberg getting this error while trying to emit from flask to javascript client

cdd4a54e2b28495bb074aa8c95e35ce9: Unexpected error "timed out", closing connection
emitting event "msg1" to cdd4a54e2b28495bb074aa8c95e35ce9 [/]
cdd4a54e2b28495bb074aa8c95e35ce9: Client is gone, closing socket
Client disconnected

**Comment by miguelgrinberg** [comment]
Your client stopped sending heartbeats. Can't tell you much more than that from the snippet of logs that you included in your report.
