### ISSUE TITLE
Accessing to application context in a background task

### ISSUE THREAD

**Issue by j2logo** [miguelgrinberg/Flask-SocketIO#651]
Hi @miguelgrinberg!

Firstly, congratulations for Flask SocketIO.
I have followed the example in https://github.com/miguelgrinberg/Flask-SocketIO/blob/master/example/app.py and it runs ok but I need to access to my database inside the background task and I don't know how to achieve it.

This is the connect event:

```python
@socketio.on('connect', namespace='/rt/notifications/')
def start_notifications_thread():
    logger.info('entra a start')
    global thread
    with thread_lock:
        if thread is None:
            thread = socketio.start_background_task(target=notifications_job)
```

And this the "notifications_job":

```python
def notifications_job():
    last_alert_id = None
    while True:
        socketio.sleep(60)
        last_id = Alert.get_last_alert_id()  # Flask-SQLAlchemy model
        if last_alert_id is not None and last_id != last_alert_id:
            socketio.emit('new_alerts', {'msg': 'New alert', 'id': last_id}, namespace='/rt/notifications/')
        last_alert_id = last_id
```

If I execute the previous code then I receive the next error message:

"No application found. Either work inside a view function or push"

**Comment by j2logo** [comment]
I think I have found a solution. Simply I have created an instance of app inside the *notifications_job* method and push the application context:

```python
def notifications_job():
    last_alert_id = None
    while True:
            socketio.sleep(60)
            last_id = Alert.get_last_alert_id()  # Flask-SQLAlchemy model
            if last_alert_id is not None and last_id != last_alert_id:
                socketio.emit('new_alerts', {'msg': 'New alert', 'id': last_id}, namespace='/rt/notifications/')
            last_alert_id = last_id
```

Is this the best approach?

**Comment by miguelgrinberg** [comment]
Yes, this is actually the correct approach. You can consider swapping the `while` and the `with`, so that a single application context is used, instead of a new one for each while loop iteration, but other than that this looks good.

**Comment by j2logo** [comment]
OK! Thank you very much :-)
