### ISSUE TITLE
ImportError: cannot import name Namespace

### ISSUE THREAD

**Issue by rishadfb** [miguelgrinberg/Flask-SocketIO#652]
I am trying to run the `app.py` from the examples folder inside a virtual environment with Python 2.7. 

This is my output for running `app.py`:

```
$ python scripts/python/app.py
Traceback (most recent call last):
  File "scripts/python/app.py", line 4, in <module>
    from flask_socketio import SocketIO, emit, join_room, leave_room, \
  File "/home/username/.local/lib/python2.7/site-packages/flask_socketio/__init__.py", line 23, in <module>
    from .namespace import Namespace
  File "/home/username/.local/lib/python2.7/site-packages/flask_socketio/namespace.py", line 1, in <module>
    from socketio import Namespace as _Namespace
ImportError: cannot import name Namespace
```

I saw some comments suggesting a manual upgrade but that didn't work for me:

```
pip install --upgrade flask-socketio                                                                                                                                                                       feature/pythonSocketServer [bac96ba] modified untracked
Requirement already up-to-date: flask-socketio in /home/username/.local/lib/python2.7/site-packages
Requirement already up-to-date: python-socketio>=1.6.1 in /home/username/.local/lib/python2.7/site-packages (from flask-socketio)
Requirement already up-to-date: Flask>=0.9 in /home/username/.local/lib/python2.7/site-packages (from flask-socketio)
Requirement already up-to-date: six>=1.9.0 in /usr/lib/python2.7/site-packages (from python-socketio>=1.6.1->flask-socketio)
Requirement already up-to-date: python-engineio>=1.2.1 in /home/username/.local/lib/python2.7/site-packages (from python-socketio>=1.6.1->flask-socketio)
Requirement already up-to-date: Jinja2>=2.4 in /usr/lib/python2.7/site-packages (from Flask>=0.9->flask-socketio)
Requirement already up-to-date: Werkzeug>=0.7 in /home/username/.local/lib/python2.7/site-packages (from Flask>=0.9->flask-socketio)
Requirement already up-to-date: click>=2.0 in /home/username/.local/lib/python2.7/site-packages (from Flask>=0.9->flask-socketio)
Requirement already up-to-date: itsdangerous>=0.21 in /home/username/.local/lib/python2.7/site-packages (from Flask>=0.9->flask-socketio)
Requirement already up-to-date: MarkupSafe>=0.23 in /usr/lib/python2.7/site-packages (from Jinja2>=2.4->Flask>=0.9->flask-socketio)
```

I have a `setup.py` file for my project which includes the following line:

```
install_requires=['pybluez', 'flask-socketio']
```

I also tried replacing my `setup.py` with the `requirements.txt` from [here](https://github.com/miguelgrinberg/Flask-SocketIO/blob/master/example/requirements.txt).

**Comment by rishadfb** [comment]
I had a folder called `socketio` in my project directory that was causing this.

**Comment by minusplusminus** [comment]
Hi,
i'm having the same issue, but I don't have an folder named `socketio`

```

Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/martijnmellema/Documents/Development/Projecten/Minusplusminus/research/ThermOS/__main__.py", line 1, in <module>
    import thermostat_web
  File "/Users/martijnmellema/Documents/Development/Projecten/Minusplusminus/research/ThermOS/thermostat_web.py", line 11, in <module>
    from flask_socketio import SocketIO
  File "/usr/local/lib/python2.7/site-packages/flask_socketio/__init__.py", line 23, in <module>
    from .namespace import Namespace
  File "/usr/local/lib/python2.7/site-packages/flask_socketio/namespace.py", line 1, in <module>
    from socketio import Namespace as _Namespace
ImportError: cannot import name Namespace
```

running on python 2.7.15 on the latest version of flask-socketio

**Comment by diptopratyaksa** [comment]
Same story with me. I looked into my /usr/local/lib/python3.5/site-packages/flask_socketio/
and guess what.. there is no file called namespace!

**Comment by miguelgrinberg** [comment]
are you doing `from flask_socketio import Namespace` or `from socketio import Namespace`? If the latter, then you need to look in the `socketio` package, right?

**Comment by HaoYang0000** [comment]
@minusplusminus @diptopratyaksa I was having the same issue, by re-install python-socketio
`pip uninstall python-socketio`
`pip install python-socketio`

Ref: https://github.com/miguelgrinberg/Flask-SocketIO/issues/164#issuecomment-228199584

**Comment by sungeunbae** [comment]
Before re-installing `python-socketio`, I had to do this: `pip uninstall socketio`. This one interferes with `python-socketio`....

**Comment by iamarunchauhan** [comment]
@miguelgrinberg I'm not able to deploy my flask-socketio application on ubuntu ec2 server. For deployment I'm using nginx server and gunicorn service. My whole application along with socket-io is working great without any problem on my local system.

Even the application working on cloud but **socket-io not working** & the functionality of socket-io gets remain **unimplemented**. 

Can you please guide me to resolve this problem & how can I proceed further. This would be a great help to me. Thanks 

![image](https://user-images.githubusercontent.com/37152406/85103346-1ccd3a00-b224-11ea-9136-85f89ff19d13.png)

**Comment by imeetsanghvi** [comment]
hello I have an import 
_from socketio import Namespace as _Namespace_

but I am still getting this error - _ImportError: cannot import name 'Namespace' from 'socketio' (unknown location)_

i tried uninstalling and reinstalling (@sungeunbae), and also did the step mentioned by @HaoYang0000 

am I required to add more lines of error code or main code?

**Comment by pachypo3** [comment]
I faced the same issue but
python3 -m pip install flask_socketio then it works on my end.
