### ISSUE TITLE
How to run Flash-SocketIo in production

### ISSUE THREAD

**Issue by ddehghan** [miguelgrinberg/Flask-SocketIO#653]
After many hours of battling various setup issues I came a cross this little gem of info which should be absolutely in the documentation in the deployment section. 

https://www.reddit.com/r/flask/comments/4uqp9y/i_host_production_flask_apps_under_uwsgi_it_is/

'''
The problem with uwsgi is that (a) does not support eventlet; (b) supports gevent, but with its own async loop that is incompatible with gevent's own loop; and (c) supports websocket, but with its own implementation, incompatible with gevent and eventlet. So there are really a lot of cons to this approach. In the same way I have code that supports eventlet and gevent I at some point intend to write another bunch of code for uwsgi (so basically you would say async_mode='uwsgi' or something like that).

Something that a lot of people don't realize is that while app.run() is a development server that almost never is a good choice for running your application on production, socketio.run() is in fact a production ready web server, as long as you use it alongside eventlet or gevent, and with app.debug=False.

So you could drop uwsgi and run a Flask+Flask-SocketIO server using eventlet or gevent, and you would have a production level stack. And if you need to scale, run more than one, and let nginx load balance your http and websocket.

I have nothing against gunicorn, by the way, that is also a good choice.
'''

Thanks

**Comment by miguelgrinberg** [comment]
I suggest you refer to the official documentation instead of posts that I or others made at different points in time.

> So there are really a lot of cons to this approach (with regards to uWSGI)

The current version of Flask-SocketIO officially supports uWSGI + gevent deployments, and this is covered in the documentation. A lot of people are using this option.

The option to use `socketio.run()` for production (along with eventlet or gevent) is also covered, as is using gunicorn. All are valid options.

**Comment by ddehghan** [comment]
Thank you for your answer. 

I ended up using socket.io.run() with gevent.
