### ISSUE TITLE
How to pass value from user to background task?

### ISSUE THREAD

**Issue by katarina02** [miguelgrinberg/Flask-SocketIO#656]
Hello! I just started with Flask and SocketIO. I tried to follow your example that I reduced to following code:

**app.py**

```
from threading import Lock
from flask import Flask, render_template, session, request
from flask_socketio import SocketIO, emit, disconnect
import math

async_mode = None

app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app, async_mode=async_mode)
thread = None
thread_lock = Lock() 

def background_thread():
    count = 0                   
    while True:
        socketio.sleep(2)
        count += 1
        socketio.emit('my_response',
                      {'data': math.sin(math.radians(count)), 'count': count},
                      namespace='/test')

@app.route('/')
def index():
    return render_template('index.html', async_mode=socketio.async_mode)
    
@socketio.on('my_event', namespace='/test')
def test_message(message):   
    session['receive_count'] = session.get('receive_count', 0) + 1
    emit('my_response',
         {'data': message['data'], 'count': session['receive_count']})

@socketio.on('disconnect_request', namespace='/test')
def disconnect_request():
    session['receive_count'] = session.get('receive_count', 0) + 1
    emit('my_response',
         {'data': 'Disconnected!', 'count': session['receive_count']})
    disconnect()

@socketio.on('connect', namespace='/test')
def test_connect():
    global thread
    with thread_lock:
        if thread is None:
            thread = socketio.start_background_task(target=background_thread)
    emit('my_response', {'data': 'Connected', 'count': 0})

@socketio.on('disconnect', namespace='/test')
def test_disconnect():
    print('Client disconnected', request.sid)

if __name__ == '__main__':
    socketio.run(app, host="0.0.0.0", port=80, debug=True)
```

**index.html**

     $(document).ready(function() {
      namespace = '/test';
      var socket = io.connect(location.protocol + '//' + document.domain + ':' + location.port + namespace);

      socket.on('connect', function() {
        socket.emit('my_event', {data: 'I\'m connected!'}); });

      socket.on('my_response', function(msg) {
        console.log(msg.data);
        $('#log').append('Received #'+msg.count+': '+msg.data+'<br>').html(); });

      $('form#emit').submit(function(event) {
          socket.emit('my_event', {data: $('#emit_value').val()});
          return false; });
      $('form#disconnect').submit(function(event) {
          socket.emit('disconnect_request');
          return false; });         
      });

I want to calculate  `A*math.sin(math.radians(count))` in the background task where A is entered by user via form input that is processed by Javascript (`$('#emit_value').val()` in my code). How can I realise it? Or have you already answered this question somewhere? Thank you in advance for your help.

**Comment by miguelgrinberg** [comment]
Using a background thread is not the best solution to run calculations in the background.  You can start a thread specifically to perform your calculation, or you can use a thread pool of workers, or maybe a job queue such as Celery. The implementation of these solutions is not trivial, and it varies depending on the async framework that you use.
