### ISSUE TITLE
How to disconnect a namespace outside the handler？

### ISSUE THREAD

**Issue by betterRunner** [miguelgrinberg/Flask-SocketIO#657]
Dear author, my question is how to disconnect one namespace forwardly (not in handler), I try to use disconnect() outside the handler but raise the exception "Working outside of application context". 
The stragedy on [#262 ](https://github.com/miguelgrinberg/Flask-SocketIO/issues/262) seems not reasonable enough so I am wondering a better solution.
By the way, if calling disconnect() is not allowed outside the handler, then is there any handler about timeout? Such as I want the client to send back some specific message within 5 seconds, if not, call a timeout handler?
Thank you very much.

**Comment by miguelgrinberg** [comment]
Sorry, but I don't understand what you are asking. The `disconnect()` part I do understand, that can be expanded to support disconnections outside of a request context, as long as you know the client's `sid` and `namespace`. I will add that.

You are also asking about timeouts, and that part I don't understand. You are free to implement timeouts as part of the application, what does the extension have to do with your own application's logic?

**Comment by betterRunner** [comment]
@miguelgrinberg  Thank you for your rely.
Sorry for my unclear description, I try to explain it with your answer:
As you are working on supporting disconnections outside of a request context, my question about timeout is actually not necessnary anymore, but I want to explain why I ask it in order not to confuse others: 
The goal I want to achieve is: Server sends some data to client, client must response it (send data back to server) within 5 seconds, if not, the server disconnect it forwardly.
If disconnection can only be called inside the handler, then server can not disconnect the client in above condition because no handler will be called (the client does not response), so my understanding is either disconnect the client outside the handler nor disconnect the client in a 'timeout handler' (the timeout made by myself is not working because it is still outside the request context), that why I asked about timeout, thank you very much.

**Comment by miguelgrinberg** [comment]
@betterRunner the current release does not require a request context on the disconnect call, as long as you provide the `namespace` and `sid` arguments.

**Comment by betterRunner** [comment]
Got it, thank your very much!
