### ISSUE TITLE
Any event handlers for every 'socket.on()' server-side event?

### ISSUE THREAD

**Issue by DanielTimLee** [miguelgrinberg/Flask-SocketIO#658]
In Flask-SocketIO server side, Is there any event handler or `before_function` for **every** `socket.on()` event?

Actually, I want to do some works on every `event` calls. 

`@socketio.on_error_default` is one example of **every** error event handler.
Is there any global function for **every** event handler?

**Comment by miguelgrinberg** [comment]
You can use a class-based namespace, which has a `trigger_event()` method that you can override. This method is invoked for all events, as it is there where the dispatching to the appropriate handler is made.
