### ISSUE TITLE
Running in debug mode requires monkey patching

### ISSUE THREAD

**Issue by miguelgrinberg** [miguelgrinberg/Flask-SocketIO#66]
In #55 I have removed monkey patching. But based on #65 it appears Flask needs monkey patching when it runs the reloader.

I need to investigate how can the reloader be used without monkey patching.

**Comment by lukeyeager** [comment]
Actually, for me I only needed monkey patching when flask was ***not*** running the reloader. When I ran with `app.debug=False`, all of my HTTP requests just stalled out. This surprised me enough that I thought I'd let you know.

But adding patch_all() fixed it anyway. Thanks!

**Comment by miguelgrinberg** [comment]
@lukeyeager are you doing anything out of the ordinary in your routes? There are certain libraries that may require monkey patching to work well with the gevent server.
