### ISSUE TITLE
Messages emitted from Python function not displayed on web page

### ISSUE THREAD

**Issue by andsouth44** [miguelgrinberg/Flask-SocketIO#660]
I have a very simple Flask UI that I want to use to select and run python scripts. I want to display python status messages to the users in the UI as the scripts run. I think SocketIO is the right way to do this but I cannot quite make it work.
I have created a Git repo with the whole set up. (https://github.com/andsouth44/SocketIO_Test)
Would you be able to take a quick look? I'm sure it is something very simple.

**Comment by miguelgrinberg** [comment]
Can you describe what doesn't work?

**Comment by andsouth44** [comment]
Thanks for your prompt response!
I appreciate your help with this.

The python function "test_sio.py" represents a long-running python
function. It contains a series of socket IO emit statements.
I want to display the message text from these emit statements on the web
page "test_sio_msg.html" so that the user has status updates.
The "test_sio_msg.html" page contains some jQuery to handle and display the
messages from the "test_sio.py" function.

The messages are not displayed on "test_sio_msg.html".

Thx

**Comment by miguelgrinberg** [comment]
Did you look at how I handle web forms in my example here in this repo? You can't use the standard form handling, as that makes the browser load a new page, which breaks the SocketIO connection. The form needs to be handled from JavaScript, so that the page does not reload.

Not sure what else to comment on, if you still have problems after fixing that, I suggest you enable logging on the SocketIO client and server so that you can see the flow of messages and where they get lost.

**Comment by andsouth44** [comment]
Thanks a lot for the advice, I will give it a try.

**Comment by andsouth44** [comment]
I fixed the web form to match what you have in this repo.
I also turned on logging on the server and client.
I added some more features to my project to help isolate the problem.
I added an emit message inside the main.py file and this does display on the client.
I also added a feature on the client to emit a message and a handler on the server to echo back. Using this I am able to emit a message from the client and then see it come back from the server.
So the only messages I do not see are the messages emitted in the test_sio.py python function.
I see these being emitted in the logs on the server but don't see anything on the client.
The messages that do get through I see in the logs on the server and the client so I know the logging is working.
I have updated my Github project to reflect all this (https://github.com/andsouth44/SocketIO_Test)
Question:
If I have a route on my main Flask/Python server that calls another python function, how can I emit messages from the other python function?

Thanks

**Comment by miguelgrinberg** [comment]
I don't see anywhere in your code where `py_func()` is called. You have only one reference in the Flask route that handles the form POST request, but you are not sending a POST request anymore.

I honestly don't understand what you are trying to achieve. Emitting from another file is really no different. I think you are just never calling this external function.

**Comment by andsouth44** [comment]
py_func() is called in line 27 of main.py

When py_func() runs, I want the emit messages in py_func() to display in
test_sio_msg.html

BTW - The emit message on line 26 of main.py is displayed in
test_sio_msg.html just fine.
It's just the emit messages in py_func() that are not displayed in
test_sio_msg.html, although I can see them being emitted in the log on the
server side.

I hope that helps clarify.

**Comment by miguelgrinberg** [comment]
Sorry, I thought you said you removed the POST request? Quick look at your project shows that you did not, so I don't see what's different in this version of your project. As I said at the start, you can't issue a POST request with your form, that removes the page, and with that your Socket.IO connection goes away.

You can submit the form as an Ajax request, or else you can also submit the data through a Socket.IO event. Anything that does not make the browser load another HTML page.

**Comment by andsouth44** [comment]
OK, sorry. In your previous message you mentioned form handling so I searched the repo for form handling and changed my forms.py file to match what you had in the repo. I did not realize I had to remove the POST as well. I will give that a try.
Still, I'm curious why the socketio.emit on line 26 of main.py is working ok? That is after the POST.

Thanks

**Comment by miguelgrinberg** [comment]
I have not tested the application. Think about my explanation though. You click the form button, which sends a POST request to the server. The server is now handling the POST request and starts making SocketIO emits, while the browser is getting rid of the current page and waiting for the POST request to return with a new page. Maybe one emit goes through before the browser starts dismantling the page. Asking why the other messages don't make it does not really matter, even if they made it to the other side, the browser would clear the page and load something else. The way you designed your solution is the problem, I think.

**Comment by andsouth44** [comment]
Thanks for the great explanation, it makes total sense.
I have modified my project and removed the POST as you suggested and now trigger the python function via an AJAX call from the client.
The client AJAX call calls a URL which has a corresponding route in main.py on the server that then calls py_func.
py_func runs and from the log I see the emit messages leaving the server but I still don't see them displayed on the client or in the client side log.
The client does not disconnect at any point.
BTW - I do see emit messages that originate in main.py displayed on the client and in the log so I think the client is set up ok.
The application at (https://github.com/andsouth44/SocketIO_Test) is updated if you have time to take a look.
Thanks!

**Comment by miguelgrinberg** [comment]
Please reopen if you still need my help with this issue, it appears that you have resolved it, but I'm not completely sure.
