### ISSUE TITLE
systemd script

### ISSUE THREAD

**Issue by ivanfdez** [miguelgrinberg/Flask-SocketIO#662]
I am new to web programming with python, I have doubts that in the documentation and forums I have not been able to clarify.

I want to make a start and stop script with systemd, I'm using gevent + gevent-websocket. You can make a script to start and stop with gevent? or do I need for example gunicorn? I still have not understood what advantage  offers me.

The idea is to use nginx or apache for the reverse proxy and implement the ssl and virtualhost.

Nor do I find documentation to activate the access and error logs.

**Comment by miguelgrinberg** [comment]
You can write a systemd script that starts/stop your server however you want. If you want to use the gevent web server, or the gunicorn web server it does not matter. All systemd cares about is that you provide the command that starts the server.

**Comment by ivanfdez** [comment]
I already have a script running with gunicorn.
What advantages does gunicorn offer? if I use gunicorn I have to use gevent equally.
