### ISSUE TITLE
How to stop the background loop in the example

### ISSUE THREAD

**Issue by hardy4yooz** [miguelgrinberg/Flask-SocketIO#664]
```
def background_thread():
    """Example of how to send server generated events to clients."""
    count = 0
    while True:
        socketio.sleep(10)
        count += 1
        socketio.emit('my_response',
                      {'data': 'Server generated event', 'count': count},
                      namespace='/test')
```

the loop in  `background_thread` will run forever, right?
how to stop it when I shutdown my broswer? 
Thank you.

**Comment by miguelgrinberg** [comment]
The server knows nothing about the browser. If you keep track of how many users are connected by updating a counter in the connect and disconnect handlers, you can then change the while loop condition to exit when the count goes to zero.
