### ISSUE TITLE
Push notifications from a background process on the server 

### ISSUE THREAD

**Issue by jbevan4** [miguelgrinberg/Flask-SocketIO#665]
I am not sure of the best way to create a push notification from a background service on my server to notify the client. This background service (run from within a flask_script) runs between 08:00 and 16:30 Monday to Friday. This service polls an API and does some machine learning to predict future stock values. At the moment, I am slightly confused as to how I would notify the running app that this process has completed and that a socket needs to emit a message to the client.  I have the current implementation of my repository under flask_react_app on the branch flask_socketio_sql_alchemy_intergration.

**Comment by miguelgrinberg** [comment]
Emitting events from an external process is covered in the documentation: https://flask-socketio.readthedocs.io/en/latest/#emitting-from-an-external-process.

If you want an actual example, my [Flack](https://github.com/miguelgrinberg/flack) example emits from a Celery worker. The same idea can be applied to other types of processes.

**Comment by jbevan4** [comment]
Thanks for the reply. I will look into the way your Flack example uses the Celery worker. Hopefully I should be able to apply this idea to my own process. 👍

**Comment by jbevan4** [comment]
I have implemented a celery background task which emits, however, my client side appear to not receive any sort of update. 

`https://github.com/jbevan4/flask_react_app/tree/flask_socketio_sql_alchemy_intergation`
Here is what I currently have. I believe the problem is within the flask_react_app where I instantiate the application.

**Comment by miguelgrinberg** [comment]
Are you running a message queue?

**Comment by jbevan4** [comment]
Thanks for your quick reply! I believe so. I am running the redis-server.

**Comment by miguelgrinberg** [comment]
What I mean is that I don't see anywhere in your code that you have configured the queue. Did you see the docs on how to run an external process emitter?

**Comment by jbevan4** [comment]
I'll have another look. Thanks for your help btw.

**Comment by miguelgrinberg** [comment]
I suggest you look at the docs, plus the Flack application I referenced earlier. You need to configure the message queue on the server and the external process.

**Comment by jbevan4** [comment]
Okay. I'll keep at it. If I run into anymore problems I'll post within this issue. Again, thanks for the help.

**Comment by jbevan4** [comment]
I think I'm getting there. I have recently committed some new changes which are more inline with the way the flack application operates. I have attached the message queue in both external process and the server (I think). I am now getting an error within the celery worker as follows: 
```
ImportError: import_string() failed for 'config.DevelopmentConfig'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'config' not found.

Original exception:

ImportStringError: import_string() failed for 'config'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;
```

**Comment by miguelgrinberg** [comment]
That seems unrelated to the change that you made. Sounds like an import for `config` is failing. Not sure how I can help with this, you have to locate the import and figure out why it is incorrect.

**Comment by jbevan4** [comment]
Thanks for all your help!  I have now been able to emit through an external process!

I do however have an issue now with emitting through my javascript. 

In my Main.js I call the function
`this.socket.emit("get initial data", {data: ticker});`
when the socket initially connects

in my flask_react_app I have the function:
```
@socketio.on("get initial data")
def on_initial_data(ticker):
    print(ticker)
```
This doesn't appear to print the passed in ticker.
