### ISSUE TITLE
Can I get Traceback in the default_error_handler?

### ISSUE THREAD

**Issue by Nriver** [miguelgrinberg/Flask-SocketIO#667]
I got the default_error_handler from other issue like this:

@socketio.on_error_default  # handles all namespaces without an explicit error handler
def default_error_handler(e):
    print 'ERROR!:', (e)
    print(request.event["message"])  # "my error event"
    print(request.event["args"])  # (data,)

This works, however sometimes I find the message only tells me about what function is wrong without telling me the cause. Is it possible to modify this handler to get more detailed error info like the Traceback in the handler?

**Comment by miguelgrinberg** [comment]
Have you tried not setting an error handler? That lets the exception bubble all the way up.

**Comment by Nriver** [comment]
Removing the handler does make the exception bubbles up. But I am seeking a way to get the 
I find the format_exc function in traceback module and this seems to be woking in the handler.

'''
import traceback

@socketio.on_error_default  # handles all namespaces without an explicit error handler
def default_error_handler(e):
    print 'ERROR!:', (e)
    print(request.event["message"])  # "my error event"
    print(request.event["args"])  # (data,)
    traceback_message = traceback.format_exc()
    print 'traceback_message\n', traceback_message
    # write error log with traceback_message and so on...
    pass
'''
