### ISSUE TITLE
How to get websocket transport working with gevent + uwsgi?

### ISSUE THREAD

**Issue by jrestifo** [miguelgrinberg/Flask-SocketIO#669]
I have my application structured as follows:
uWSGI with gevent, communicating over redis to celery, also with redis as the message broker for SocketIO so I could emit from my celery tasks.

SocketIO is working, but it looks like its falling back to polling transport unexpectedly. Not sure what I need to do. I have monkey patched manually w gevent because of the redis message queue, and am using the gevent plugin with uWSGI.

Everything seems fine except I am seeing GET requests with transport=websocket but then followed by transport=polling in Chrome, and from Firefox I only see transport=polling. Both browsers are up to date.

Python is 3.6
uWSGI is 2.0.17 which I understand has websocket support compiled in natively (there was no plugin for it in my source tree, but the websocket code was in the core source tree)

gevent==1.2.2
gevent-websocket==0.10.1
Flask-SocketIO==2.9.4
websocket-client==0.46.0

I should note, I am not fronting it with nginx yet, I have http protocol in uWSGI on port 5000. I am actually communicating over an SSH tunnel on that port, so is it possible that is the problem? Will websockets go over the port set in uwsgi or will they still need port 80 to be open?

**Comment by miguelgrinberg** [comment]
Did your compare your uWSGI start up configuration against the recommended one in the documentation? Have you enabled logging on the server to see if that shows any more clues? Add `engineio_logger=True` to your `SocketIO` constructor to enable verbose logging.

**Comment by jrestifo** [comment]
My current command line is:

uwsgi --plugin python36 -H /home/coindraw/lotto/venv --enable-threads --plugin gevent --gevent 100 --socket 0.0.0.0:5000 --master --processes 1 --protocol=http -w wsgi:app

I didn't know about the engineio_logger=True, I will try that as well, thanks.

**Comment by miguelgrinberg** [comment]
Check the documentation: https://flask-socketio.readthedocs.io/en/latest/#uwsgi-web-server

I would start with my recommended settings, which I verified to work, and then work from that to your ideal configuration. You are definitely not enabling websocket, so that is probably your main problem.

**Comment by jrestifo** [comment]
I am a little confused, my understanding is I don't need to enable websockets explicitly. As I mentioned, 2.0.17 has no websocket plugin as far as I can tell. And my help has websocket parameters, but nothing like --http-websockets to enable or disable. Seems it should be enabled by default.

https://uwsgi-docs.readthedocs.io/en/latest/WebSockets.html

"The uWSGI websockets implementation is compiled in by default."

**Comment by jrestifo** [comment]
```
$ ./uwsgi --help | grep -i websocket
    --websockets-ping-freq                set the frequency (in seconds) of websockets automatic ping packets
    --websocket-ping-freq                 set the frequency (in seconds) of websockets automatic ping packets
    --websockets-pong-tolerance           set the tolerance (in seconds) of websockets ping/pong subsystem
    --websocket-pong-tolerance            set the tolerance (in seconds) of websockets ping/pong subsystem
    --websockets-max-size                 set the max allowed size of websocket messages (in Kbytes, default 1024)
    --websocket-max-size                  set the max allowed size of websocket messages (in Kbytes, default 1024)

```

Is it possible Flask-SocketIO isn't compatible with the later versions of uWSGI?

**Comment by miguelgrinberg** [comment]
Are you suggesting `--http-websockets` was removed? It's still [documented](http://uwsgi-docs.readthedocs.io/en/latest/Options.html?highlight=--http-websockets#http-websockets), so I doubt it. This is more likely a result of the compilation options that you used.

**Comment by jrestifo** [comment]
Hmm, strange, I will go back and try and recompile again, I must have missed something then. Thanks.

**Comment by jrestifo** [comment]
I needed to add the http plugin (and corerouter) to uWSGI for http-websockets. However, I still am only getting polling. I'll continue to investigate on my own with the engineio_logger though I guess.
