### ISSUE TITLE
Using aws redis elasticache with multiple servers with flask-socketio

### ISSUE THREAD

**Issue by stevepaul-alonso** [miguelgrinberg/Flask-SocketIO#671]
Hi
Thank you very much for your work on flask-socketio. 
I'm developing a chat application. Currently I'm running in a single server (aws ec2) (nginx + gunicorn + eventlet), like how its mentioned in the flask-socketio documentation with 1 eventlet worker. I want to scale my app with multiple servers, so I decided to use aws elasticache redis as a pub-sub server. I followed the flask-socketio documentation for connecting to redis. The problem is that, the websocket is not working when I run two servers and when I use more than 1 worker for eventlet. Is there anything else I need to do other than just connecting to redis as mentioned in the flask-socketio documentation.
Also should I enable sticky-sessions in nginx?

Hoping for a response.

Thanks,
Steve

**Comment by miguelgrinberg** [comment]
What is the problem? Are you getting 400 errors? The most likely cause of that is not using sticky sessions.

**Comment by stevepaul-alonso** [comment]
Yes. Its a 400 error. [HTTP/2.0 400 Bad Request 32ms]

**Comment by miguelgrinberg** [comment]
Sticky sessions are required any time you have more than one server, so yes, this is required in your case. It is not required if you have one server and one or more external processes that only emit but are not servers themselves.

**Comment by stevepaul-alonso** [comment]
Thanks you so much. I did try  with sticky sessions and it is working fine. 
Even when using a single server when I use more than 1 eventlet worker, its giving me the 400 error. 
How many connections can a single worker handle? And if I need to enable more than 1 worker, what should I do to enable it to work with redis?

**Comment by miguelgrinberg** [comment]
I think what you call "worker" is the same thing I call "server". Absolutely, any time you have two or more "things that listen for requests" be them threads or processes, running on same or different physical server, then you need sticky sessions and a message queue for them to coordinate efforts.

The number of connections per server/worker depends on the web server, it is not limited by Flask-SocketIO. Gunicorn, for example, defaults to 1000 connections if I remember correctly.

**Comment by stevepaul-alonso** [comment]
Thank you very much. Now I am able to run multiple threads successfully and the websocket is working well.
I really appreciate  that you are taking your precious time for this.

Regards,
Steve
