### ISSUE TITLE
Problems with receiving 'utf-8' from client

### ISSUE THREAD

**Issue by bstojkovic** [miguelgrinberg/Flask-SocketIO#674]
I am trying to create a 2-way communication between server and client using Flask and socket.io.

Everything works fine until server receives utf-8 string from client, which gets garbled. Sending from server to client works fine, and prior to sending from client to server, the client prints the message correctly.

Here is some code that reproduces the problem:

app.py:
```
import flask
from flask_socketio import SocketIO, emit, disconnect

import json

app = flask.Flask(__name__)
socket_io = SocketIO(app)

@socket_io.on('pull')
def socket_io_handle_pull():
    json_msg = {
        'msg': "abcćčddžđefghijklmnnjoprsštuvzž"
    }
    print("Pushing", json_msg)

    socket_io.emit('response', json_msg)

@socket_io.on('push')
def socket_io_handle_push(json_msg):
    print("Pushed:", json_msg)

@socket_io.on('disconnect')
def socket_io_handle_disconnect():
    disconnect()

@app.route('/')
def root():
    return flask.render_template(
        'index.html'
    )

if __name__ == '__main__':
    socket_io.run(app)
```

index.html:
```
<!DOCTYPE html>
<html>
  <head>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js"></script>
  </head>
  <body>
    <script type="text/javascript">
      var socket = io.connect('http://' + document.domain + ':' + location.port);

      socket.on('response', json => {
        socket.emit('push', json);
      })

      socket.emit('pull');
    </script>
  </body>
</html>
```

Output:
```
Pushing {'msg': 'abcćčddžđefghijklmnnjoprsštuvzž'}
Pushed: {'msg': 'abcÄ\x87Ä\x8dddA3Ä\x91efghijklmnnjoprsA!tuvzA3'}
```

[From SO question.](https://stackoverflow.com/questions/49475762/problems-with-receiving-utf-8-from-client)

**Comment by bstojkovic** [comment]
Socket.IO version:

```
> pip3 show flask-socketio
Name: Flask-SocketIO
Version: 2.9.3
```

**Comment by bstojkovic** [comment]
> [Miguel](https://stackoverflow.com/questions/49475762/problems-with-receiving-utf-8-from-client#comment86046236_49475762):
> Does this still happen on a more recent Socket.IO client? They had bugs regarding utf-8 encoding in those old releases, try a 2.x

I updated to socket.io `2.0.4` and it works fine now! Thank you so much.

**Comment by arduinka55055** [comment]
hello, i have the same problem with version 4.2.0
server file .py
`
from flask import Flask, render_template
from flask_socketio import SocketIO
app = Flask(__name__)
hostIP='localhost'
socketio = SocketIO(app)

@socketio.on('my event')
def newRoom(json, methods=['GET', 'POST']):
    print('received my event: ' + json['name'])
    socketio.emit('my response', json)
@app.route('/' ,methods=['GET', 'POST'])
def index():
    return render_template('index.html')
if __name__ == '__main__':
    socketio.run(app, debug=True, host=hostIP,port=80)
`
<!DOCTYPE html>
<html>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.7.3/socket.io.min.js"></script>
</head>
<body>
    <script>
        var socket = io.connect('http://' + document.domain + ':' + location.port);
        var testing='йцукен' //i am using russian letters
        socket.emit( 'my event', {name: testing,hello: 'hello world'} )
        socket.on( 'my response', function( msg ) {
        console.log( msg )
        })
    </script>
</body>
</html>
`
i am getting in console:
received my event: Ð¹ÑÑÐºÐµÐ½

and in mozilla console Object { name: "Ð¹Ñ\u0086Ñ\u0083ÐºÐµÐ½", hello: "hello world" }
