### ISSUE TITLE
race condition with threads and Flask socketIO?

### ISSUE THREAD

**Issue by fsofras** [miguelgrinberg/Flask-SocketIO#677]
I am trying to reduce latency times in a web controlled robot car. When the app starts everything seems fine but a while later only the server thread seems to be running and my threaded loop degrades and stops. Peculiarly, running the app from my desktop seems to work much better than running it from a phone or tablet browser
My code is in https://gist.github.com/fsofras/471a6b12873da69c243c5678c4df0aa3  and I would appreciate a comment

**Comment by miguelgrinberg** [comment]
You seem to be doing a lot of sleeping in your thread. Is that necessary? Could that be what makes your server seem unresponsive?

**Comment by fsofras** [comment]
Dear Miguel,
Should I assume that there is no solution to the problem?

**Comment by miguelgrinberg** [comment]
Unfortunately I can't test your application here, so I'm not sure how I can help with this problem. Please reopen if you can provide additional information, or an example application that does not depend on your hardware so that I can test it here.
