### ISSUE TITLE
how to config uwsgi？I have poor performance in my own preparation.

### ISSUE THREAD

**Issue by Toudaozhe** [miguelgrinberg/Flask-SocketIO#679]
flask async_mode config:
        async_mode = 'gevent'
        socketio = SocketIO(app, async_mode=async_mode)

uwsgi config:
        [uwsgi] http=0.0.0.0:8888  
        chdir=/www/web/www_zhuhui_shop/public_html/zhuhui.store/flask/
        wsgi-file=/www/web/www_zhuhui_shop/public_html/zhuhui.store/flask/run.py
        callable=app
       master=true
       processes=1
      #threads=2
      http-websockets = true
      gevent = 1000
      async = 30
      py-autoreload=1 
      vacuum=true                                  
      socket=/www/web/www_zhuhui_shop/public_html/zhuhui.store/flask/uwsgi/uwsgi.sock          
      stats=/www/web/www_zhuhui_shop/public_html/zhuhui.store/flask/uwsgi/uwsgi.status          
      pidfile=/www/web/www_zhuhui_shop/public_html/zhuhui.store/flask/uwsgi/uwsgi.pid             
     daemonize=/www/web/www_zhuhui_shop/public_html/zhuhui.store/flask/uwsgi/uwsgi.log       

processes only one, lt always delay，l can.t use it at production

**Comment by Toudaozhe** [comment]
I think i need to uwsgi,nginx,redis website.
thanks
author

**Comment by miguelgrinberg** [comment]
See if removing the `async_mode` argument helps. You are using it incorrectly, the `gevent` async mode is supposed to be used with the gevent web server, not with uWSGI. Better to not set this argument, so that the correct mode is selected automatically for you.
