### ISSUE TITLE
how to close a socket connection

### ISSUE THREAD

**Issue by buptmuye** [miguelgrinberg/Flask-SocketIO#68]
For client, how to disconnect the websocket.
For server, is it right to use socket.disconnect()?

**Comment by jrbdeveloper** [comment]
@miguelgrinberg so what you're saying is that I shouldn't expect to open a connection on a button click, carry out some routine and then disconnect the socket? Meaning, when I click a button a request for some action occurs and then when it gets a response I shouldn't disconnect the socket?

**Comment by miguelgrinberg** [comment]
@jrbdeveloper no, that is the use case for HTTP requests. When a button is clicked, you send an Ajax HTTP request to the server, get the response, then the connection is closed.

WebSocket and Socket.IO are for long, uninterrupted connections where server and client exchange data frequently.

**Comment by jrbdeveloper** [comment]
Sounds good, @miguelgrinberg thanks for the reply

**Comment by ej23lee** [comment]
@miguelgrinberg Am I suppose to connect each time I navigate to a different page?

**Comment by miguelgrinberg** [comment]
@ej23lee The connection is not going to survive a page change, so yes, each page will have to start a connection (and ideally close it when it is going away, though abandoned connection time out if not explicitly closed).

The typical use case for WebSocket and Socket.IO application is single-page apps, or pages where the user stays a long time.

**Comment by jrbdeveloper** [comment]
To share my experience, I ended up creating a JS app library that would be persistent across pages. so for example: 
var app = {};

Set the following values in a Layout Page/Master Page/Route Index etc.
app.socketUri = "<serverUrl>";
app.socket = io.connect(app.socketUri);

then inside my specific libraries I can do the following:
app.socket.emit("some-method", function(response){
});

**Comment by ej23lee** [comment]
@miguelgrinberg How do I properly disconnect and close a room when a client changes to a new page. I noticed that if I constantly just refresh the page, it will keep making a new connection (thus a new room with the sid) and the room list just keeps growing.

**Comment by jrbdeveloper** [comment]
@ej23lee socket.disconnect(true); will do it, but the connection will automatically be closed after 30 seconds I believe.

**Comment by miguelgrinberg** [comment]
@ej23lee Yes, you can call `socket.disconnect` in an unload event handler for your page.

**Comment by ej23lee** [comment]
@miguelgrinberg @jrbdeveloper Ok, thanks, I'll give that a try and see how it goes.

**Comment by ej23lee** [comment]
@miguelgrinberg I'm trying to emit on page unload (also tried beforeunload bind) but that doesn't seem to work.

**Comment by miguelgrinberg** [comment]
In which way it does not work? Are you calling `socket.disconnect`? Does the server receive the call?

**Comment by ej23lee** [comment]
The server does not receive the call (using flask that just prints some text under the disconnect handler).

**Comment by miguelgrinberg** [comment]
I'm closing this issue. I have opened #249 to add documentation on properly disconnecting when the page is closed.

**Comment by mariohmol** [comment]
Hi there, this fixed for me:  `socket = io.connect("https://"+ document.domain + ':' + location.port ,{'sync disconnect on unload':false);`

**Comment by miguelgrinberg** [comment]
@mariohmol Don't you want the sync disconnect option set to `true`?

**Comment by mariohmol** [comment]
@miguelgrinberg  Thats true.. i just tested here and is weird.. now is working with or without this option... with true or false... i will leave true as that makes more sense =)
