### ISSUE TITLE
Reset self.server_options on init_app

### ISSUE THREAD

**Issue by bundabrg** [miguelgrinberg/Flask-SocketIO#680]
If I create a flask app multiple times (using different configurations), which calls the socketio init_app multiple times, the server_options is updated with all the previous config items.

This means if I run a flask instance with a message queue, the server_options is updated with 'client_manager'. If I then run a new flask_instance without a message_queue that re-runs the socketio init_app, it inherits this previous setting.

This is more apparent when using testing, and when using a global socketio instance (possibly bad practice but seems to be pretty common).

ie:

```
from socketio import SocketIO
socketio = SocketIO()

def init_app(app):
    socketio.init_app(app, message_queue=app.config.get('REDIS_URL') if not app.config.get('TESTING') else None)
```

My fix is to save the original server_options in __init__ to a variable original_server_options, and then set server_options to original_server_options in init_app.

ie:
```
class SocketIO(SocketIOOriginal):
    """
    A SocketIO implementation with state
    """

    def __init__(self, app=None, **kwargs):
        super().__init__(app, **kwargs)

        self.original_server_options = self.server_options.copy()

    def init_app(self, app, **kwargs):
        # Reset server options to original
        self.server_options = self.original_server_options.copy()

        # Call our super
        super(SocketIO,self).init_app(app, **kwargs)
```

**Comment by miguelgrinberg** [comment]
Reusing the same SocketIO instance on multiple runs of the application is not really something that I think is worth supporting. The class creates a web server that is assumed to run forever, so stopping the server, reconfiguring it and restarting it is definitely not supported. And if you are not starting the server, then does it matter if the settings are not correct?

**Comment by bundabrg** [comment]
Quite possibly not worth supporting but I thought I'd post it as an issue in case it comes up for someone else.

I've only had the issue during my testing where I'm effectively creating and destroying flask apps a lot and using the socketio test_client.

**Comment by miguelgrinberg** [comment]
Why would you pass the `message_queue` option if you are using the test client?

**Comment by bundabrg** [comment]
One of my tests (unrelated to the client) is to test multiple configurations of flask apps. This includes one with a message_queue set to redis. All it does is create it, and ensure no error, then destroy it. However in the process of creating it, it indirectly also runs the socketio init_app which leaves it with a redis config. When the tests go to the socketio testing it loads a flask_app without a message_queue but of course the socketio instance will still have the queue config and re-create self.server with that config.

I suspect my main issue is that I'm using a global instance of socketio (IE, from app.extensions import socketio) instead of using the current_app.extensions['socketio'] which would be bound to a private one for that specific app instance.

**Comment by bundabrg** [comment]
As I mentioned in the previous link, I'll close this as I think its probably more to do with how I'm dealing with it and its specific case of calling new app instances in a test. My fix works for my case fine and doesn't really require upstream fix.
