### ISSUE TITLE
Connections are not closed

### ISSUE THREAD

**Issue by paredesivan** [miguelgrinberg/Flask-SocketIO#681]
Miguel. We are an Argentine company that is dedicated to software development and we have a problem a long time ago. we have a server with UBUNTU 16 in which runs a FLASK service, and there are clients that connect by cell phone through SOCKETIO. The problem is that several connections are generated per client and never close, generating that the amount of generated files grow exponentially over time and never be reduced.

I give you the information about the problem.

y en castellano:
Miguel. somos una empresa Argentina que se dedica al desarrollo de software y tenemos un problema hace ya MUCHO tiempo. nosotros tenemos un servidor con UBUNTU 16 en el cual corre un servicio de FLASK, y hay clientes que se conectan por celular por medio de SOCKETIO. el problema es que se generan varias conexiones por cliente y nunca se cierran, generando que la cantidad de archivos generados crezca exponencialmente con el tiempo y nunca se reduzca.

te paso la información del problema.

```
from flask import Flask
from flask_socketio import SocketIO
from gevent.pywsgi import WSGIServer
from geventwebsocket.handler import WebSocketHandler
app = Flask(__name__)
app.debug = False
socketio = SocketIO(
    app,
    ping_timeout=30,
    ping_interval=10,
    async_mode='gevent'
)

def run():
    http_server = WSGIServer(
        (HOST, PORT), app, handler_class=WebSocketHandler
    )
    http_server.serve_forever()
```

LIBRERIAS:
```
gevent==1.2.2
greenlet==0.4.12
Flask==0.12.2
python-engineio==2.0.4
gevent-websocket==0.10.1
python-socketio==1.8.0
eventlet==0.21.0
```

example
```
comando: lsof -p numero_dE_proceso

srvweb-cp 15677 ubuntu 1047u     IPv4 31629146       0t0      TCP ip-10-166-113-32.ec2.internal:3001->host69.170-51-43.claro.com.py:6219 (CLOSE_WAIT)
srvweb-cp 15677 ubuntu 1048u     IPv4 31686949       0t0      TCP ip-10-166-113-32.ec2.internal:3001->host69.170-51-43.claro.com.py:52427 (CLOSE_WAIT)
srvweb-cp 15677 ubuntu 1049u     IPv4 31766609       0t0      TCP ip-10-166-113-32.ec2.internal:3001->host69.170-51-43.claro.com.py:24395 (CLOSE_WAIT)
srvweb-cp 15677 ubuntu 1050u     IPv4 31634033       0t0      TCP ip-10-166-113-32.ec2.internal:3001->host196.181-9-168.telecom.net.ar:42865 (ESTABLISHED)
srvweb-cp 15677 ubuntu 1051u     sock      0,9       0t0 31635564 protocol: TCP
srvweb-cp 15677 ubuntu 1052u     IPv4 31635908       0t0      TCP ip-10-166-113-32.ec2.internal:3001->host69.170-51-43.claro.com.py:22146 (CLOSE_WAIT)
srvweb-cp 15677 ubuntu 1053u     sock      0,9       0t0 31655449 protocol: TCP
srvweb-cp 15677 ubuntu 1054u     sock      0,9       0t0 31639842 protocol: TCP
srvweb-cp 15677 ubuntu 1055u     IPv4 31643835       0t0      TCP ip-10-166-113-32.ec2.internal:3001->host69.170-51-43.claro.com.py:35045 (CLOSE_WAIT)
srvweb-cp 15677 ubuntu 1056u     IPv4 31669115       0t0      TCP ip-10-166-113-32.ec2.internal:3001->55-117-168-152.fibertel.com.ar:53442 (ESTABLISHED)
```

look for the one of claro.com.ar that remains in close_wait and repeats a lot
fijate el de claro.com.ar que queda en close_wait y se repite mucho

seria de grandisima utilidad tu ayuda. 

saludos

**Comment by paredesivan** [comment]
gracias. nos vamos a fijar y te avisamos, no cierres la issue por favor

**Comment by miguelgrinberg** [comment]
Ya paso un mes. Por favor reabri esta issue cuando tengas mas informacion de este problema.
