### ISSUE TITLE
SocketIO emit problem

### ISSUE THREAD

**Issue by softwarengineer2** [miguelgrinberg/Flask-SocketIO#686]
I am using SocketIO with eventlet on docker container (Debian container). My config and setup are below. Current infrastructure works with elastic load balancer and nginx (using stick sessions too, for 2 docker containers). In my socketio communication, there is unexpected behaviour, it is not doing it frequently (Generally it works very well) but cause problem for authentication on client side. Normally it works like "when a user connects to the SocketIO server, server emits "initial" message and client starts to authenticate after it gets this message. Problem is sometimes server doesn't send this message. Like something blocks this message. Could the blocker be another process that is sync? or what  could be  the problem? Even if it wont emit this message, client side can continue to message like i did in my logs. (Hi Message). Client side looks connected . I am using 
https://github.com/socketio/socket.io-client-cpp/  on client side.

Server Logs:
```
Server initialized for eventlet.
Server initialized for eventlet.
(1) wsgi starting up on http://0.0.0.0:8000
(1) accepted ('10.40.0.6', 56890)
d3386fedb15e469abe74f3361657be21: Sending packet OPEN data {'upgrades': [], 'pingTimeout': 60000, 'sid': 'd3386fedb15e469abe74f3361657be21', 'pingInterval': 25000}
d3386fedb15e469abe74f3361657be21: Sending packet MESSAGE data 2["initial",{"random":"test"}]
d3386fedb15e469abe74f3361657be21: Sending packet MESSAGE data 0
d3386fedb15e469abe74f3361657be21: Received request to upgrade to websocket
[2018-04-09 22:41:43.012355] emitting event "initial" to d3386fedb15e469abe74f3361657be21 [/]
[2018-04-09 22:41:43.012428] Client Connected: d3386fedb15e469abe74f3361657be21
d3386fedb15e469abe74f3361657be21: Upgrade to websocket successful
d3386fedb15e469abe74f3361657be21: Received packet PING data None
d3386fedb15e469abe74f3361657be21: Sending packet PONG data None
d3386fedb15e469abe74f3361657be21: Received packet PING data None
d3386fedb15e469abe74f3361657be21: Sending packet PONG data None
d3386fedb15e469abe74f3361657be21: Received packet PING data None
d3386fedb15e469abe74f3361657be21: Sending packet PONG data None
d3386fedb15e469abe74f3361657be21: Received packet PING data None
d3386fedb15e469abe74f3361657be21: Sending packet PONG data None
[2018-04-09 23:17:12.198759] received event "hi" from d3386fedb15e469abe74f3361657be21[/]
[2018-04-09 23:17:12.198846] hi
```

NGINX Logs:
`127.0.0.1 - [127.0.0.1] - - [09/Apr/2018:22:40:04 +0000] "GET /socket.io/?EIO=4&transport=websocket&t=1523313514 HTTP/1.1" 101 889 "-" "WebSocket++/0.7.0" 242 87.130 [web-8000] 10.32.0.5:8000 0 87.130 101`

Python Code (com.py):
```
import eventlet, time, requests
from flask import Blueprint, request
from flask_socketio import SocketIO, emit

eventlet.monkey_patch()

import json, os

from api.common import utils
from common.logging import LOG

from datetime import datetime
from math import ceil

class ConnectedUser:

    def __init__(self, sid):
        self.sid = sid
        self.connected = True

class Communication:
    socketio = None
    request = None
    connected_users = {}
    main_app = None

    def __init__(self, app):
        main_app = app
        Communication.socketio = SocketIO(app,logger=LOG,engineio_logger=True)
        Communication.io_setup()

    def io_setup():

        @Communication.socketio.on('connect')
        def connected():
            sid = request.sid
            Communication.connected_users[sid] = ConnectedUser(sid)
            Communication.socketio.emit("initial",{'random': 'test'},room=sid)
            LOG.info("Client Connected: " + sid)
```			
```		
Python Code (__init__.py):
import os, sys, eventlet
eventlet.monkey_patch()

sys.path.append(os.path.realpath('.'))

from flask import Flask

from com.com import Communication
from com.session import RedisSessionInterface

# Define the WSGI application object
app = Flask(__name__)

# Configurations
app.config.from_object('allconfig.configs')

# Session Configuration
app.session_interface = RedisSessionInterface()
app.config['DEBUG'] = False

# Setup socketio for client-server communication
comm = Communication(app)

if __name__ == "__main__":
    comm.socketio.run(app, host=config.WEB_HOST, port=config.WEB_PORT)
```
	

Python Code (configs.py)

```
WEB_HOST = os.getenv('IP', '0.0.0.0')
WEB_PORT = 8000
```

**Comment by miguelgrinberg** [comment]
I'm not sure I understand. The emit that you say did not go through is in the logs, right?

**Comment by softwarengineer2** [comment]
`[2018-04-09 22:41:43.012355] emitting event "initial" to d3386fedb15e469abe74f3361657be21 [/]`
In server logs, it looks it is emitting "initial" event but client sometimes doesn't get this message like it is never sent (and in this above log, it didnt receive too)

**Comment by miguelgrinberg** [comment]
Right, and your function immediately returns after doing that emit. Which means that it isn't blocking. So something else is blocking at about the time this emit went out, or the client is receiving and losing some of these emits.

To check for blocking code you could add a background task that writes a log entry every second, and see if when one of these trouble connections appear you have logs from this task. My assumption is that if the problem is due to blocking, then all tasks will be blocked.

I think it would also be useful to monitor more closely what the client receives, and in particular if it discards anything.

**Comment by softwarengineer2** [comment]
As you see, i am using eventlet with socketIO. If i use async or different threadpools in my code, would it cause any problem with eventlet threads? and when i tried to use socketio.sleep(5) in connect like

```@Communication.socketio.on('connect')
        def connected():
            sid = request.sid
            Communication.connected_users[sid] = ConnectedUser(sid)
            Communication.socketio.emit("initial",{'random': 'test'},room=sid)
            Communicateion.socketio.sleep(5)
            LOG.info("Client Connected: " + sid)
```
it blocked "initial" event and client disconnected immediately in this time. I thought it would just wait 5 second asnychoronous

**Comment by miguelgrinberg** [comment]
The connection is not going to be fully established until you return from the connect handler, so sleeping there is almost always a bad idea.

I don't quite understand what you are thinking with regards to thread pools, but ideally you should stay within the functionality offered by eventlet for any async needs. Using something else is likely to give you problems.

**Comment by softwarengineer2** [comment]
For instance I am using aiobotocore for my s3bucket processes and it is based on aiohttp and asyncio and i had event loop with asyncio. I just didn't get used to use eventlet all functionality for asynchronous purposes.

**Comment by miguelgrinberg** [comment]
Sorry, but now I'm more confused than before. You can't really mix asyncio with Flask. If you want to use asyncio, then you have to drop Flask, and also replace Flask-SocketIO with python-socketio, a more basic package that does have support for asyncio. I still fail to see what all this has to do with your problem.

**Comment by softwarengineer2** [comment]
Sorry for confusion, i use flask for web and SocketIO together. That is why i am using flask instead of python directly. I use asyncio to upload a file to s3bucket, what would be the alternative to do it async with eventlet in flask? I didn't find a async way to do it without blocking other thread, that is why i started to use asyncio because it was easier for me to integrate it . would i seperate to project or use Celery for this kind of task?

**Comment by sunilthakur5** [comment]
@miguelgrinberg I am also facing the same same issue When i am emitting any message from connect method it is received by client but when i am emitting something outside that connect event it is not being received b the client.

Logs when emitting outside the connect event.
emitting event "post_message" to all [/]
a51452ee3172407483e273d60647d56c: Sending packet MESSAGE data 2["post_message",{"data":"test"}]

**Comment by miguelgrinberg** [comment]
@sunilthakur5 you are not providing enough information for me to give you a more complete answer. As I said above, either your server is blocking (which prevents delivery of the Socket.IO packets) or your client is receiving but then for some reason dropping these events.
