### ISSUE TITLE
socketio.emit not sending info out of function

### ISSUE THREAD

**Issue by SimplySynced** [miguelgrinberg/Flask-SocketIO#688]
Hello, so I had posted on stackexchange and was able to get the issue resolved with the errors and that is no longer an issue.  I've decided just create everything within one file instead of 2 just to try and simplify.  Here is my file now.

```
import RPi.GPIO as GPIO
from pushbullet import Pushbullet
from flask import Flask, render_template, request
from flask_socketio import SocketIO, emit

simplyfishy = Flask(__name__)

simplyfishy.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(simplyfishy)


# Routes
@simplyfishy.route('/')
def index():
    return render_template('home.html')


@socketio.on('my_message')
def mymessage(message):
    print('received message: ' + message)
    # emit('my_response', 'test')

# GPIO setup
# Set the GPIO mode to Broadcom
GPIO.setmode(GPIO.BCM)

# Set the Pushbullet API key
pb = Pushbullet('o.lulz')

# Create a dictionary for the outlets and their status:
outlets = {
    4: {'name': 'Outlet 1', 'state': GPIO.LOW},
    14: {'name': 'Outlet 2', 'state': GPIO.LOW},
    15: {'name': 'Outlet 3', 'state': GPIO.LOW},
    17: {'name': 'Outlet 4', 'state': GPIO.LOW},
    18: {'name': 'Outlet 5', 'state': GPIO.LOW},
    27: {'name': 'Outlet 6', 'state': GPIO.LOW},
    22: {'name': 'Outlet 7', 'state': GPIO.LOW},
    23: {'name': 'Outlet 8', 'state': GPIO.LOW}
}

# Set each pin as an output and make it low:
for outlet in outlets:
   GPIO.setup(outlet, GPIO.OUT)
   GPIO.output(outlet, GPIO.LOW)


# Define functions for turning outlets on and off
def outlet_on(out_num):
    GPIO.output(out_num, GPIO.HIGH)
    outlets[out_num]['state'] = GPIO.HIGH
    print(outlets[out_num]['name'] + " is now on!")


def outlet_off(out_num):
    GPIO.output(out_num, GPIO.LOW)
    outlets[out_num]['state'] = GPIO.LOW
    print(outlets[out_num]['name'] + " is now off!")

# Create a dictionary for sensors ans their status
float_switches = {
    24: {'name': 'Float Switch 1', 'state': GPIO.LOW},
    25: {'name': 'Float Switch 2', 'state': GPIO.LOW}
}

# Setup float switches
for float_switch in float_switches:
    GPIO.setup(float_switch, GPIO.IN, pull_up_down=GPIO.PUD_UP)


# Define callback function for event detection
def floatsw(channel):
    with simplyfishy.app_context():
        if GPIO.input(channel):
            print(float_switches[channel]['name'] + " deactivated!")
            socketio.emit('float_sw', {'data': 'deactivated!'})
        else:
            print(float_switches[channel]['name'] + " activated!")
            # pb.push_note("Simply Fishy", "Sump water level is low")
            socketio.emit('float_sw', {'data': 'activated!'})


GPIO.add_event_detect(24, GPIO.BOTH, callback=floatsw, bouncetime=1000)
GPIO.add_event_detect(25, GPIO.BOTH, callback=floatsw, bouncetime=1000)


if __name__ == '__main__':
    socketio.run(simplyfishy, debug=True, host='0.0.0.0')
```

Here is the javascript.  

```
<script type="text/javascript">
    //$(document).ready( addNoteData() );

    $(document).ready(function(){
        //connect to the socket server.
        var socket = io.connect('http://' + document.domain + ':' + location.port)
        socket.on('connect', function() {
            socket.emit('my_message', 'I\'m connected!');
        });

        socket.on('float_sw', function(msg) {
             console.log(msg);
             console.log('test on socket.');
         });

        socket.on('my_response', function(msg) {
            console.log(msg);
        });

    })
</script>
```

On connect I can see in the console the I'm connected message show, I also tested a ping back to the page within the @socket.on route as you can see with the #emit and it worked fine.  However the section of the function floatsw does not work.  I get the print in the console saying the switch activated.  So that I know the if statement is running correctly.  However the socketio.emit is not sending back to the page.

**Comment by miguelgrinberg** [comment]
Okay, I think the next step would be to rule out an incompatibility between eventlet and the `GPIO` module that you are using. Remove the `eventlet.monkey_patch()` call and any references to eventlet that you have in your Python script, and then set `async_mode='threading'`. Try the application in this mode and let me know if there is any difference.

If the emits go through, that means that the monkey patching that eventlet does to make the Python library async friendly is insufficient for the type of work that `GPIO` does. The `threading` mode is based on regular threads, which should be very compatible, but not as efficient as eventlet. You will notice that in threading mode there is no support for WebSocket, for example, and instead the connection is emulated with long-polling.

**Comment by SimplySynced** [comment]
Hello Miguel,

Thank you, it does work changing it to threading and I was able to get it to do exactly what I needed.  I even was able to split this back into the 2 files as originally shown on the stackoverflow question.  However the reason I was trying to use eventlet was because I am looking to serve this app over nginx and gunicorn.  Switching to the threading did not seem to work.  I am now trying to use gevent to see if I can get it but I seem to be running into a circular dependency issue.  I started the app using gunicorn --bind 0.0.0.0:5000 -k gevent wsgi:simplyfishy and when I trigger the switch it gives me ImportError: cannot import name simplyfishy.

**Comment by miguelgrinberg** [comment]
If threading works that means that the GPIO package isn't compatible with eventlet.

You can use gunicorn with [threads](http://docs.gunicorn.org/en/stable/settings.html#threads) if you like, without having to use eventlet/gevent. As long as you use a single worker you should be fine. The problem with the threading mode is that it does not support websocket.

**Comment by SimplySynced** [comment]
Hey Miguel,

I started testing with gevent and it looks like that is working just fine.  The issue i was getting with the import was a circular issue due to a bad tutorial.  I believe I'm good to go now.  I'm just reading the documentation now on the best way to manage the application using multiple files.

**Comment by andres-root** [comment]
I found this question while trying to solve the same problem. I wanted to add that this issue only appeared on a new raspberry pi I bought. I don't know why, maybe it has to do with the older raspberry having a lot of other Python libraries installed. But my code works without messing with gevent or threading in the older raspberry, but not in the new ones.
