### ISSUE TITLE
Flask-Login + iOS Client

### ISSUE THREAD

**Issue by tommypacker** [miguelgrinberg/Flask-SocketIO#689]
So I was wondering how exactly flask-socketio retrieves the `current_user` object. Currently I have an iOS app that is able to authenticate with my server using the `login_user` function, but any messages it sends to `authenticated_only` routes don't seem to work. Thanks!

**Comment by miguelgrinberg** [comment]
Flask-SocketIO does not do anything special regarding Flask-Login's `current_user`.

If you have Flask-Login properly set up, your user session should have your user stored in it, so `current_user` should just get the user from the session. Are you testing Flask routes or Flask-SocketIO events? Maybe you need to show me some code.

**Comment by tommypacker** [comment]
Yeah, so Flask-Login works perfectly with my web client. I'm working with SocketIO events, and I was wondering how flask-socketio determines the current user session. Is there a cookie attached to each socket message?

**Comment by miguelgrinberg** [comment]
No, the cookie is the same one from Flask's user session. The Socket.IO client running in the browser normally sends that cookie when it connects to Flask-SocketIO. Do you have an unusual structure where the Socket.IO server is on a different domain than the Flask app? That would be one reason why the browser would not send the Flask session cookie to Socket.IO.

**Comment by tommypacker** [comment]
My web client version works properly, I'm just trying to get my swift app to work actually. So the iOS app will post to my `/login` route which will call `login_user`. From there, I'm not quite sure the necessary steps to get my iOS app to work the `authenticated_only` decorator. It seems like every request sent from my iOS app is sent via an anonymous user, leading me to believe flask isn't finding the right user session. My server code is here: https://github.com/acm-uiuc/concert/blob/master/app.py

**Comment by tommypacker** [comment]
So is this the correct workflow: POST to login, get the cookie from that response, and then send that cookie when connecting to the server?

**Comment by miguelgrinberg** [comment]
Sorry, should have been paying more attention to what you were saying. You are doing this from iOS, so yes, you will need to capture the cookie that comes from the login request, and then make sure the Swift Socket.IO client sends that cookie when it connects. I'm not familiar with the iOS client, hopefully it does offer a way to insert custom headers.

**Comment by tommypacker** [comment]
Got everything working, thanks a bunch!

**Comment by jadhavmanoj** [comment]
@miguelgrinberg Does IOS client work smoothly with socket.io? I am facing the similar issue.

**Comment by miguelgrinberg** [comment]
@jadhavmanoj it should work, but as I said above, if you have a Flask-Login cookie, that cookie needs to be passed in the Socket.IO connection call.
