### ISSUE TITLE
message is not translated by socketIO from flask_babel

### ISSUE THREAD

**Issue by wiwengweng** [miguelgrinberg/Flask-SocketIO#690]
Hi, all. I am working with socketIO and flask right now. My translation is done by flask-babel, and it always working for me, until message is emit.

when message emit from backend, using the method:
````
sio = SocketIO(async_mode=async_mode, message_queue='redis://')
sio.emit('loading', {'data': _("The cloud desktops are closing.")})
````

html code:
````
<script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
        var socket = io.connect('http://' + document.domain + ':' + location.port);
        socket.on('loading', function (msg) {
            $.cookie('socket_cookie', '<div id="hide" class="bubble_ok">' +msg.data+ '</div>');
        });
    });
</script>
````

and I catch the msg.data response, it looks like this:
````
ÿ42["loading",{"data":"The cloud desktops are closing."}]
````
which is not translated by flask-babel.

Is there a way to solve this problem, or did I miss something? Please any advise is appreciated. TIA :)

**Comment by miguelgrinberg** [comment]
I need to see more of your code. Where is the `sio.emit()` with the translatable text located?

**Comment by wiwengweng** [comment]
thanks for your response. 
I have a main() function starts 2 subprocesses, one is flask web:

````
app = Flask(__name__, static_url_path='', template_folder='templates')
babel = Babel(app)
socketio.run(app, host='0.0.0.0')
````
the other is a task queue with redis:
I have a route method, when I want to shutdown virtual machines, I call this API and API will put some info into Redis. The task queue wil loop forever to get info from Redis. Once 'shutdown_vm' is called, message will be emit through SocketIO, then html page will show this up.
````
async_mode = 'gevent'
sio = SocketIO(async_mode=async_mode, message_queue='redis://')

def task_queue(q):
    try:
        r = InitRedis()
        rp = r.pool
        rp = redis.StrictRedis(connection_pool=rp)
        rdp = rp.pubsub()
        rdp.subscribe(**{'my:channel': my_handler})
        while True:
            rdp.get_message() # trigger handler
            if not q.empty():
                t = q.get()
                if 'shutdown_vm' in t.keys():
                    try:
                        restore = t.get('restore')
                        if restore == 1: 
                            sio.emit('loading', {'data': _('The cloud desktops are closing.')})
````
Yes, my local language is Chinese, so then I also try to put some Chineses directly like this:
````
sio.emit('loading', {'data':  u'云桌面关闭'})
````
this Chinese message shows up right in the html page. So, I think is it something wrong with flask babel handling some UTF-8 coding languages??

**Comment by miguelgrinberg** [comment]
Does your `tasq_queue` run inside a request context? That is required for Flask-Babel to know what language to serve to the client.

**Comment by wiwengweng** [comment]
Thanks, Miguel. I am afraid you are right, and I just thinking about the same thing! task_queue is just running like a zombie outside the request context. Because the two subprocesses are actually running with redis to change info only. So we though of this separately before.  Can I add the request context to the task_queue subprocess?

**Comment by miguelgrinberg** [comment]
@wiwengweng do you run one of these tasks per client? If you have just one task, then you can't really get Flask-Babel to customize that single emit so that each clients gets their own language, Flask-Babel simply does not work that way, it is designed to work with one client/request context at a time. You may need to implement your own broadcasting loop, where you iterate over all your clients and manually request a translation for each client. You will also need to store the selected language for each client, maybe in your user database.

**Comment by wiwengweng** [comment]
Thanks, then. In fact I try to import socketio object from flask web like this:
 
flask web.py
````
from flask_socketio import SocketIO
async_mode = 'gevent'
socketio = SocketIO(app, async_mode=async_mode, message_queue='redis://')
....
socketio.run(app)
````

task.py

````
from web import socketio as sio
....
sio.emit('message', {'data': _('The cloud desktops close successfully.')})
````

But this doesn't work either. Did you mean I need to implement i18n in `socketio.emit()` ?

**Comment by miguelgrinberg** [comment]
You can't broadcast to all your users like you are doing with `sio.emit` if you want each user to receive the text in their own selected language.

What you need to do is store the language selected by each of your users in your user database, then when you need to broadcast, implement a loop in your application, where you force Flask-Babel to use the language of each user. It woud be something like this:

```python
from flask_babel import force_locale

for user in all_active_users:
    with force_locale(user.locale):
        sio.emit('message', {'data': _('The cloud desktops close successfully.')}, room=user.sid)
```

Hope this makes it clear. The `all_active_users` is something that you'll need to implement to get the list of connected users. Your user database will need to store the locale selected by each user, and the `sid` that was assigned to each Socket.IO connection.

The alternative to this is to implement the translations in the browser, that is something you may also want to research.

**Comment by wiwengweng** [comment]
ok, let me try first. Thanks and regards.

**Comment by wiwengweng** [comment]
Hi, miguel. I didn't have many clients, but just one(the browser socket client). so right now I use a method to import the web app into the task queue, and create a test request context, so when emitting messages, flask babel may know what I want to translated. This works too. However I don't know if this is a 'flask babel way'.

**Comment by miguelgrinberg** [comment]
That is good for a quick test, but it's not going to work for 2 or more clients, so it's not something I would recommend.
