### ISSUE TITLE
Event handlers in external process?

### ISSUE THREAD

**Issue by djlambert** [miguelgrinberg/Flask-SocketIO#691]
I'm trying to access the connect event for a namespace in an external process (Celery task) and can't determine how this would be done.

I'm using SocketIO to stream task logging to a client. Each task has one or more services that perform the task's operation(s). When the task starts up I create a ```logging.Logger``` named with the task id, and add a ```logging.Handler``` to it which opens up the socket and emits the log messages as they are received. I pass this logger into each service to capture the logging.

```python
import logging
from flask_socketio import SocketIO


class TaskLogHandler(logging.Handler):
    def __init__(self, app, task):
        self.messages   = []
        self._task      = task
        self._app       = app
        self._socket_io = SocketIO(message_queue=app.config['CELERY']['broker_url'])

        super().__init__()

    def emit(self, record):
        message = self.format(record)

        try:
            self.messages.append(message)
            self._socket_io.emit('log_message', {'message': message, 'state': 'progress'}, namespace=f'/{self._task.request.id}')

        except Exception:
            self.handleError(record)
```
After the socket is opened on the client, frequently the task has already started running and a number of log messages are not received. What I'm hoping to do is add an ```on_connect``` event handler to my logging handler that will emit any log messages which have been spooled up (in ```self.messages```).

If there's a way to capture the connect event per client/sid it'd be even better, but I don't anticipate there'll be multiple clients connecting to the same socket.

**Comment by miguelgrinberg** [comment]
Event handlers can only be in the main server, but you can start a Celery task from your `on_connect` handler that triggers the logic that you need in your worker. Would that approach work?

**Comment by djlambert** [comment]
That makes sense. Probably the better place to do it anyway, and I'll be able to disconnect it from the server side. Thanks! I'll post the solution when I have it :)
