### ISSUE TITLE
Running Flask-SocketIO on AWS Elastic Beanstalk

### ISSUE THREAD

**Issue by Qinusty** [miguelgrinberg/Flask-SocketIO#695]
Hi,

I can't quite get Flask-SocketIO working with my instance on AWS Elastic Beanstalk (ELB), with the requirement of running Flask-SocketIO with `socketio.run(application)`, ELB appears to make the calls to the global application object itself.

The [ELB documentation](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create-deploy-python-flask.html) states `Using application.py as the filename and providing a callable application object (the Flask object, in this case) allows Elastic Beanstalk to easily find your application's code.`

My ELB instance logs show the error `RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.`

Is there any way to approach this problem assuming that AWS calls application.run()?

Thanks in advance

**Comment by golharam** [comment]
@miguelgrinberg - Would you say using the solution here, https://github.com/miguelgrinberg/Flask-SocketIO/issues/625, would be good?   Basically, running the Flask app in a Docker in order to use ElasticBeanStalk?

**Comment by miguelgrinberg** [comment]
@golharam I have never tested this type of deployment, but I think it could work. Flask-SocketIO is 100% compatible with Docker, but if you plan on deployment multiple workers you will need to set sticky sessions for the load balancer.
