### ISSUE TITLE
CORS not working

### ISSUE THREAD

**Issue by alexpana** [miguelgrinberg/Flask-SocketIO#697]
I'm trying to connect to socketio from the create-react-app dev server, but the flask server isn't returning `Access-Control-Allow-Origin: *`.

Here is the request from the create-react-app server (running on port 3000):

![request from react](https://i.imgur.com/md9uYxd.png)

And here is the request from a html file served by flask:

![request from flask](https://i.imgur.com/fUt4w1k.png)

Opening the html file locally (with `file:///.../index.html`) doesn't work either.

Is this the intended behavior? How can I get flask to play nice with other servers?

**Comment by miguelgrinberg** [comment]
The two screenshots that you shared are for Socket.IO requests, I don't see any being for a HTML file. Note that both show a URL that begins with `http://localhost:5000/socket.io/...`.

How did you initialize the `SocketIO` extension? The lack of CORS headers in the first screenshot make me think you are using a non-default configuration for CORS.

**Comment by alexpana** [comment]
Thank you for the reply, I'll do my best to clarify.

> The two screenshots that you shared are for Socket.IO requests, I don't see any being for a HTML file.

The second screenshot is a Socket.IO request **from** a html file served by flask. The first is being made from a html file served by a node dev server. Notice the difference in the `Host` header.

> How did you initialize the SocketIO extension? 

```
socketio = SocketIO()
def create_app():
    ...
    socketio.init_app(app, cors_allowed_origins="*")
```

and the, from another script:
```

**Comment by miguelgrinberg** [comment]
This is the documentation for the `cors_allowed_origins` setting:

> **cors_allowed_origins** – List of origins that are allowed to connect to this server. All origins are allowed by default.

If you want to allow all origins, do not include this setting, or set it to `None`. If you want to allow specific origins, provide a list of those origins in this argument. You are setting the argument to `*`, which is not an allowed value.

**Comment by miguelgrinberg** [comment]
@alexpana I actually followed your advice and expanded the `cors_allowed_origins` a bit. You can now set it to `'*'` or `None` (or omit it) to allow all origins. You can also set it to a string to allow a single origin, or set it to a list of strings if you have more than one allowed origin. Thanks!

**Comment by alexpana** [comment]
That's awesome, thank you!

**Comment by EDario333** [comment]
> @alexpana I actually followed your advice and expanded the `cors_allowed_origins` a bit. You can now set it to `'*'` or `None` (or omit it) to allow all origins. You can also set it to a string to allow a single origin, or set it to a list of strings if you have more than one allowed origin. Thanks!
> 
> Commit: [miguelgrinberg/python-engineio@8f3d6ec](https://github.com/miguelgrinberg/python-engineio/commit/8f3d6ecff45d474da1a407d654d06fd3f8f882a8)

_"You can now set it to `'*'` or `None` (or omit it) to allow all origins"_

Still working on this way? I got _"Not an accepted origin."_ for:

1. `cors_allowed_origins = None`
2. Omit `cors_allowed_origins`

The only working is when set to `*` (`cors_allowed_origins = '*'`).

Dev env:

```
Python 3.9.14
Flask 2.2.2
Flask-SocketIO 5.3.2
python-engineio 4.3.4
python-socketio 5.7.2
```

**Comment by miguelgrinberg** [comment]
@EDario333 when there is any doubt, please consult the documentation. You are reading something that is almost 5 years old. The documentation is always kept up to date.

**Comment by n1lby73** [comment]
please a quick question does cfbm cookie has anything to do with flask cors, cus i keep having this error and unable to find a fix for it yet

**Comment by miguelgrinberg** [comment]
@n1lby73 wrong repo, this is Flask-SocketIO, not Flask-CORS.

**Comment by n1lby73** [comment]
> @n1lby73 wrong repo, this is Flask-SocketIO, not Flask-CORS.

i'm using socket io to implement cors 

socketio = SocketIO(app, cors_allowed_origins='*')

**Comment by miguelgrinberg** [comment]
@n1lby73 I don't see what is the relation between your question and Flask-SocketIO. You mentioned Flask-CORS. And I have no idea what that cookie you referenced is.
