### ISSUE TITLE
Flask-SocketIO connections always using polling

### ISSUE THREAD

**Issue by leematthewshome** [miguelgrinberg/Flask-SocketIO#699]
Hi Miguel

Fantastic work on all the blogs, book and also this library! I have begun testing Flask-SocketIO with the view to adding some web socket capability to an existing Flask REST API I have developed. I have a simple example where connections are being established, but the server always indicates that they are polling connections. I have tested this from every angle I can think of and the result is always the same. I think I have eliminated the browser and network as I have used 4 different browsers, 2 servers and 2 networks (home and AWS). It seems the server is the issue, but the code is so simple I dont know why. What are the conditions on which it will fall over to polling? Can I debug this?

The details are posted in StackOverflow at the link below. Would you be able to assist?
https://stackoverflow.com/questions/50062070/flask-socketio-app-keeps-using-polling

**Comment by miguelgrinberg** [comment]
As I asked in the SO question, please provide the output of `pip freeze` for your environment.

**Comment by leematthewshome** [comment]
Hi Miguel. Thank you very much for the prompt response. It is greatly appreciated. I just tried accessing my cloud server from another network on which I know there are no web socket issues on routers/proxies etc and it still resulted in the repetitive polling messages.

I will post the results here, as its a pretty long list for SO. Note that I am not using a virtual environment. Output is below. 

aws-cfn-bootstrap==1.4
awscli==1.14.9
Babel==0.9.4
backports.ssl-match-hostname==3.4.0.2
boto==2.48.0
botocore==1.8.13
cachetools==2.0.1
certifi==2018.4.16
chardet==3.0.4
click==6.7
cloud-init==0.7.6
colorama==0.2.5
configobj==4.7.2
dill==0.2.7.1
docutils==0.11
ecdsa==0.11
enum34==1.1.6
Flask==0.12.2
Flask-SocketIO==2.9.6
future==0.16.0
futures==3.0.3
gapic-google-cloud-speech-v1==0.15.3
gax-google-logging-v2==0.8.3
gax-google-pubsub-v1==0.8.3
gcloud==0.18.3
gevent==1.2.2
google-api-python-client==1.6.6
google-auth==1.4.1
google-auth-httplib2==0.0.3
google-cloud-core==0.24.1
google-cloud-speech==0.25.1
google-gax==0.12.5
googleapis-common-protos==1.5.3
greenlet==0.4.13
grpc-google-logging-v2==0.8.1
grpc-google-pubsub-v1==0.8.1
grpcio==1.11.0
hibagent==1.0.0
httplib2==0.11.3
idna==2.6
inflect==0.2.5
iniparse==0.3.1
itsdangerous==0.24
jaraco.itertools==2.2
Jinja2==2.7.2
jmespath==0.9.2
jsonpatch==1.2
jsonpointer==1.0
kitchen==1.1.1
lockfile==0.8
MarkupSafe==0.11
more-itertools==4.1.0
oauth2client==3.0.0
paramiko==1.15.1
PIL==1.1.6
ply==3.8
proto-google-cloud-speech-v1==0.15.3
protobuf==3.5.2.post1
pyasn1==0.1.7
pyasn1-modules==0.2.1
pycrypto==2.6.1
pycurl==7.19.0
pygpgme==0.3
pyliblzma==0.5.3
PyMySQL==0.8.0
pystache==0.5.3
python-daemon==1.5.2
python-dateutil==2.1
python-engineio==2.1.0
python-socketio==1.9.0
pyxattr==0.5.0
PyYAML==3.10
redis==2.10.6
requests==2.18.4
rsa==3.4.1
simplejson==3.6.5
six==1.11.0
uritemplate==3.0.0
urlgrabber==3.10
urllib3==1.22
virtualenv==15.1.0
Werkzeug==0.14.1
wolframalpha==3.0.1
xmltodict==0.11.0
yum-metadata-parser==1.1.4

**Comment by miguelgrinberg** [comment]
You don't have a websocket implementation. If you are using gevent, you also need to install gevent-websocket.

**Comment by leematthewshome** [comment]
Sorry Miguel, I must be missing something in my understanding of the various dependencies. At this stage on my test server I am relying on the Flask WSGI development server. Will that not provide web socket capabilities? 

If I simply install gevent and gevent-websocket using pip should that then resolve things?

My existing JSON API is using gunicorn. I was reading that is not so scalable when used with Flask-SocketIO, so I was going to review that setup down the track when I had things working.

**Comment by miguelgrinberg** [comment]
Well, if you are using the Flask development server it is even worse, because that server does not support websocket at all.

I assumed you were using gevent, because it is installed in your virtual environment. So, if you are using gevent, and also install gevent-websocket, then you should have websocket enabled. To make sure that gevent is used, just make sure your `SocketIO()` class constructor does not have the `async_mode` argument, or if it does, that it is set to `async_mode='gevent'`. It is best to just not include this argument, and then Flask-SocketIO is going to look for supported libraries in your virtual environment.

**Comment by leematthewshome** [comment]
Brilliant. I will try that and let you know the outcome. Thanks again for the quick reply. And apologies once again for what was a RTFM answerable question. 
Do you want me to update SO with an answer once I test it?

**Comment by miguelgrinberg** [comment]
Yes, that's good, so that others will see how you solved the problem.

**Comment by leematthewshome** [comment]
Having installed gevent-socket I no longer see the recurring message about transport=polling. But then again I now see no messages, as I assume the serving of content is now handled by gevent rather than the development server. I will do a bit of research into how to trigger logging from gevent.

**Comment by miguelgrinberg** [comment]
@leematthewshome if you set your app in debug mode you will get logging enabled, but yes, the logging strategy and format is different, because it is controlled by each web server.

**Comment by tahir80** [comment]
Hi Miguel, 
I can also see this message where transport = polling: 
2018-11-26T10:18:32.196918+00:00 heroku[router]: at=info method=GET path= "/socket.io/?EIO= 3&transport= polling

My procfile is:
web: gunicorn -k eventlet run:flask_app

My requirements are (sorry for long list):
asn1crypto==0.24.0
attrs==18.1.0
autobahn==18.6.1
Automat==0.7.0
bcrypt==3.1.4
certifi==2018.4.16
cffi==1.11.5
chardet==3.0.4
click==6.7
constantly==15.1.0
cryptography==2.2.2
dominate==2.3.1
enum34==1.1.6
Flask==1.0.2
Flask-Bcrypt==0.7.1
Flask-Bootstrap==3.3.7.1
Flask-Login==0.4.1
Flask-SQLAlchemy==2.3.2
Flask-WTF==0.14.2
gunicorn==18.0
hyperlink==18.0.0
idna==2.7
incremental==17.5.0
ipaddress==1.0.22
itsdangerous==0.24
Jinja2==2.10
MarkupSafe==1.0
oocsi==0.4
Pillow==5.1.0
psycopg2==2.7.5
pyasn1==0.4.3
pyasn1-modules==0.2.2
pycparser==2.18
pyOpenSSL==18.0.0
python-dateutil==2.7.3
requests==2.19.1
scipy==1.0.0
service-identity==17.0.0
six==1.11.0
SQLAlchemy==1.2.10
Twisted==18.4.0
txaio==2.10.0
Unidecode==1.0.22
urllib3==1.23
virtualenv==16.0.0
visitor==0.1.3
Werkzeug==0.14.1
ws4py==0.5.1
WTForms==2.2.1
zope.interface==4.5.0
watson-developer-cloud==1.4.1
boto==2.49.0
Flask-SocketIO==3.0.2
gevent==1.3.6
eventlet==0.24.1
Flask-Script==2.0.6
Flask-Migrate==2.3.0
boto3==1.9.42
gevent-websocket==0.10.1

**Comment by miguelgrinberg** [comment]
@tahir that message in itself is not indicatory of a problem. All connections start with polling and then upgrade to websocket. Have you confirmed that your application stays in polling after it connects?
