### ISSUE TITLE
Running Flask-socketIO via systemd

### ISSUE THREAD

**Issue by vmanikes** [miguelgrinberg/Flask-SocketIO#701]
Hello 
I am having an issue while running flask socketio via systemd. In my flask application when I run normally using `python3 app.py` flask socketio works great by sending events from backend. But when I try to launch my flask app via systemd with gunicorn, it does not throw any events. When I checked the console log, it is showing bad request. Can someone help me how to fix this ?

**Comment by miguelgrinberg** [comment]
Can you provide the systemd script that you wrote and the complete error, including the stack trace?

**Comment by vmanikes** [comment]
This is my systemd script
```
[Unit]
Description=Gunicorn NGINX
After=network.target

[Service]
User=root
Group=root
WorkingDirectory=/home/pi/RaspberryPI-Prototype
ExecStart=/bin/bash -c '/usr/local/bin/gunicorn --workers 3 --bind 127.0.0.1:5000 -m 777 app:app'
Restart=always

[Install]
WantedBy=multi-user.target
```

This is what I am getting on the browser
![img_3796](https://user-images.githubusercontent.com/16039325/39478184-ab4be454-4d2f-11e8-8738-da6b7ab6a3d2.jpg)
![img_3797](https://user-images.githubusercontent.com/16039325/39478185-ab54d974-4d2f-11e8-9a98-6e1e491cb96e.jpg)

**Comment by miguelgrinberg** [comment]
See the [documentation](https://flask-socketio.readthedocs.io/en/latest/#gunicorn-web-server) for instructions on the command to use with Gunicorn. In particular, you can't use more than one worker.

**Comment by vmanikes** [comment]
So you mean Flask-Socket IO would not work for more than 1 worker if I am using Gunicorn?

**Comment by miguelgrinberg** [comment]
Did you read the documentation I pointed you at? The answer is really not that simple, that is why I sent you to the place you can learn what the problem is and how it can be addressed. If you just want the short answer, then yes, gunicorn must run with a single worker. Check the documentation for instructions on how to run multiple server processes with Socket.IO.
