### ISSUE TITLE
Room Deletion

### ISSUE THREAD

**Issue by adityosnrost** [miguelgrinberg/Flask-SocketIO#702]
Hi,

I just would like to know if the room will be deleted automatically when a client / user is no longer on the room / room is empty ?

If not, how can I cleaned up empty rooms ?

Thank You

**Comment by miguelgrinberg** [comment]
Rooms are not automatically deleted. You can use the `close_room()` function for that. This function removes all the clients from that room, and then deletes the room.

**Comment by adityosnrost** [comment]
@miguelgrinberg Thank you so much for your reply.

So, I need to close the room manually. I have some thought on implementing this manual way, like close room when user disconnecting and room is empty.

How do I check if the room is empty ? I see there is no function for that in the documentation.

Regarding to the default room when user connected, I have read that a connected client have socket#id as their default room. is this default room need to close manually like room that we made manually ?

Thank You

**Comment by adityosnrost** [comment]
@miguelgrinberg thank you for your explanation.

Maybe I can use the message queue feature from multi worker documentation to track room and user connection. While I am planning to use multi worker and using Redis as message queue, maybe Redis got that information, right ?

May I know what Flask-Socketio store to message queue such as Redis ?

**Comment by adityosnrost** [comment]
Alright, I see. I understand know, thank you for your amazing explanation. I am building user tracking now.
Thank you so much

**Comment by valentin-ballester** [comment]
What about server restarts ? Because o keep track using a counter when user connects/disconnect, should i reset the value to 0 when server restart ?
