### ISSUE TITLE
flask run command with flask-socketio application doesn't seem to work with flask 1.0 verison

### ISSUE THREAD

**Issue by AlaaKho** [miguelgrinberg/Flask-SocketIO#707]
I was trying to use the `flask run `command to start my flask server that utilises flask-socketio extension. only when I reverted back to flask version 0.12.2 was I able to use this.  

my application.py code is as follows (was very simple example for testing):
<img width="340" alt="screen shot 2018-05-10 at 12 58 07" src="https://user-images.githubusercontent.com/26281273/39866668-d3745e10-5451-11e8-860c-f5b4d6caddab.png">

and the terminal output that I used to get (which seemed as if my server was stuck and I couldn't reach 127.0.0.1:5000)
<img width="690" alt="screen shot 2018-05-10 at 10 37 29" src="https://user-images.githubusercontent.com/26281273/39866703-fbacdf9c-5451-11e8-9bbb-6da6b2826b12.png">

**Comment by miguelgrinberg** [comment]
So this happens with Flask 1.0 only?

**Comment by AlaaKho** [comment]
as I said when I revert back to flask 0.12.2 the problem is solved.
