### ISSUE TITLE
Deployment on IIS server

### ISSUE THREAD

**Issue by ionspicica** [miguelgrinberg/Flask-SocketIO#709]
Hello. Everything works perfectly in development but when I went in production server IIS receive 500 "Can not establish a connection to the server". Maybe someone has encountered the issue of integrating with IIS ?

**Comment by miguelgrinberg** [comment]
I'm not familiar with IIS to help you, but I know of a few people who tried to do this and were unsuccessful. The SocketIO protocol imposes certain requirements on the web server that are not standard. Asynchronous support with gevent or eventlet is one of them that I believe IIS does not support. Sticky sessions is another.
