### ISSUE TITLE
Unable to push messages flask socketio

### ISSUE THREAD

**Issue by Toudaozhe** [miguelgrinberg/Flask-SocketIO#711]
@socketio.on('Virtual', namespace="/VirtualCoin")
def Virtual(message):
    CoinName = message['coinName']
    while True:
        socketio.sleep(2)
        VirtualCoinData = VirtualCoin().getWsContent(CoinName)
        emit('Virtual', {'data': VirtualCoinData})

//连接
window.socket = io.connect('http://127.0.0.1:501/VirtualCoin',{"force new connection":true});
 //断开
socket.socket.disconnect();
window.socket.emit('Virtual', { 'data': 'test' ,'coinName':'BTC'});
//监听回复的消息
var that = this;
window.socket.on('Virtual', function (data) {
	console.log(data);
	that.resList = data.data.Body.Items
});

After 20-30Return messages，it can’t work， no messages return

**Comment by miguelgrinberg** [comment]
Try moving the registration of your `Virtual` event handler in the client side outside of the `emit()` callback.

**Comment by Toudaozhe** [comment]
@miguelgrinberg  
def background_thread():
    """Example of how to send server generated events to clients.
       增加一个线程处理后台程序，这里需要自己设置条件关闭，或者一直作为生产者
       每次返回消息会增加一个线程，这个还需要看下websocket底层实现
    """
    count = 0
    while True:
        socketio.sleep(1)
        count += 1
        socketio.emit(
            'my_request', {'data': 'Server generated event',
                           'count': count},
            namespace='/test')


''' 后台异步执行推送开线程法
    对应view层的system_response.html 
'''


@socketio.on('my_request', namespace='/test')
def test_connect(message):
    #value = message.get('param')
    global thread
    with thread_lock:
        if thread is None:
            thread = socketio.start_background_task(
                target=background_thread)
  
    emit('my_request', {'data': 'Connected', 'count': 0})

how to stop this thread?  I want to the thread ends when the client stops connecting。

**Comment by miguelgrinberg** [comment]
You can use an `Event` object that the thread watches to know when you exit. The disconnect handler can signal this event.

**Comment by Toudaozhe** [comment]
thanks @miguelgrinberg
