### ISSUE TITLE
i can‘t use https on ubuntu,but it can work on win10;

### ISSUE THREAD

**Issue by Gaoyongxian666** [miguelgrinberg/Flask-SocketIO#714]

**Comment by Gaoyongxian666** [comment]
[uwsgi]
socket = 127.0.0.1:8001
buffer-size=32768
gevent = 100  
chdir = /home/ubuntu/xiaochengxu
wsgi-file = xiaochengxu.py
callable = app
processes = 4
threads = 2
stats = 127.0.0.1:9191
pidfile=/home/ubuntu/xiaochengxu/uwsgi.pid
daemonize=/home/ubuntu/xiaochengxu/uwsgi.log
master=true
harakiri= 1000
home=/home/ubuntu/.virtualenvs/pdf/



server {
listen 443;
        server_name pdfchange.cn; 
        ssl on;
        ssl_certificate /home/ubuntu/xiaochengxu/1_pdfchange.cn_bundle.crt;
        ssl_certificate_key  /home/ubuntu/xiaochengxu/2_pdfchange.cn.key;
        ssl_session_timeout 5m;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2; 
     ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
 ssl_prefer_server_ciphers on;
access_log /home/ubuntu/xiaochengxu/logs/access.log; 
error_log /home/ubuntu/xiaochengxu/logs/error.log;

location / {
include uwsgi_params;
uwsgi_pass 127.0.0.1:8001; 
}
location /socket.io {      
        proxy_http_version 1.1;
        proxy_redirect off;
        proxy_buffering off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";            
        proxy_pass http://127.0.0.1:8001/socket.io;
        
}


location /zip/ {
alias
/home/ubuntu/xiaochengxu/download_flask/;
}
location /file/ {
alias
/home/ubuntu/xiaochengxu/uploads_flask/FILE/;
}
location /screenshoot/ {
alias
/home/ubuntu/xiaochengxu/download_flask/;
}
}

**Comment by Gaoyongxian666** [comment]
![2018-06-01_214214](https://user-images.githubusercontent.com/35163802/40843841-e062de90-65e4-11e8-80a7-93026dd71115.jpg)



![2018-06-01_214246](https://user-images.githubusercontent.com/35163802/40843842-e0a58402-65e4-11e8-90c8-26db65656584.jpg)

**Comment by Gaoyongxian666** [comment]
I need help.......

**Comment by miguelgrinberg** [comment]
Have you read the deployment section of the documentation? I'm not sure what you are trying to do here, but uwsgi with multiple processes or threads is not a supported configuration. Also, the `uwsgi_pass` method of reverse proxying does not support WebSocket, if I remember correctly.

**Comment by Gaoyongxian666** [comment]
thanks for your answer, I see your deployment section of the documentation.your example is http ,but I want to deploy https. can you give me a example.

**Comment by Gaoyongxian666** [comment]
or How to write my uwsgi configuration

**Comment by miguelgrinberg** [comment]
Get it to work on HTTP, then add HTTPS to nginx. If you need help with HTTPS setup for nginx, see my blog post on the topic: https://blog.miguelgrinberg.com/post/running-your-flask-application-over-https
