### ISSUE TITLE
docs: Add an index

### ISSUE THREAD

**Issue by meetmangukiya** [miguelgrinberg/Flask-SocketIO#724]
Currently, it is a very long page that'd be easier to navigate and search with an index. Also, maybe split up docs in small consumable amount by using different pages?

**Comment by miguelgrinberg** [comment]
Yes, the docs started short and simple, but over the years there were a lot of new features added. I agree that splitting the docs into multiple files/pages makes sense at this point.

**Comment by shrey27tri01** [comment]
@miguelgrinberg, if it's not done yet, I would like to index the docs...

**Comment by miguelgrinberg** [comment]
@shrey27tri01 sure, if you want to add an index please go ahead. Thanks!
