### ISSUE TITLE
Access to background threads

### ISSUE THREAD

**Issue by fretchen** [miguelgrinberg/Flask-SocketIO#726]
You have the beautiful example of how to start background threads. Now I would love to have way of getting the thread and seee if it is still running through its _ident_ or its _name_ ? I just cannot find a way to get it...
The idea would be to implement something like in your great tutorial on the redis queue, but this seems non-trivial from within flask-socketio.

**Comment by miguelgrinberg** [comment]
You can use the facilities in Python or the async framework that you are using (eventlet, gevent, asyncio) to keep track of your threads, or you can also add a state variable in your thread and handle this yourself. For example:

```python
thread_is_running = False

def my_thread_function():
    thread_is_running = True
    try:
        # do thread stuff here ...
    except:
        # handle errors here ...
    thread_is_running = False

**Comment by fretchen** [comment]
The problem with your example is IMHO that it is a global variable. I would like to associate the thread to some object, like device. The properties of the object are stored in a database, amongst them most likely the thread_is_running. 
What happens now if the thread closes without me knowing, e.g. there is another error and the server has to be restarted etc. It would be great to be able to have something like

t = get_thread_by_id(thread_id);
t.is_alive()

However, I simply cannot find any way to do this with eventlet and socketio.
Sorry for the trouble.

-- Fred

**Comment by miguelgrinberg** [comment]
If you monkey patch the standard library, then you can use the Python `threading` module to do this in the usual way.

**Comment by fretchen** [comment]
Ok. I think that I found an okayish solution. Sorry for bothering.
