### ISSUE TITLE
With celery and rabbitmq,socketio.emit works only for 6 times ,then client received no message 

### ISSUE THREAD

**Issue by GitKKg** [miguelgrinberg/Flask-SocketIO#728]
hi,Miguel
in my codes,  UpdateScanerProgress() will called in thread Scaner_main() for 100 times to emit percent progress to client by message que, the first 6 times all are ok, ,in client could receive progress,but after nothing received, if i do this again in the same client html page ,even previous 6 messages can't be received,check rabbitmq's queue,socketio's queue is never created this round
 (browser log:
app.171680e0.js:1 ScanerProgress
app.171680e0.js:1 10
app.171680e0.js:1 ScanerProgress
app.171680e0.js:1 10
app.171680e0.js:1 ScanerProgress
app.171680e0.js:1 11
app.171680e0.js:1 ScanerProgress
app.171680e0.js:1 12
app.171680e0.js:1 ScanerProgress
app.171680e0.js:1 13
app.171680e0.js:1 ScanerProgress
app.171680e0.js:1 14
app.171680e0.js:1 ScanerProgress
app.171680e0.js:1 15
)

the code is like this:

`from eventlet import monkey_patch
monkey_patch(socket=True)
static_folder="C:\WebProgramming\quasar_init1\dist\spa-mat"
app = Flask(__name__,static_folder=static_folder, static_url_path='')
app.config['SECRET_KEY'] = 'secret!'
app.config.update(
    CELERY_BROKER_URL='amqp://localhost//',
    #CELERY_RESULT_BACKEND='amqp://localhost//',
    #CELERY_ACKS_LATE=True,
    #CELERYD_PREFETCH_MULTIPLIER = 0
)
socketio = SocketIO(app,async_mode='eventlet',message_queue='amqp://')#when no debug ,async_mode='eventlet' is actually default
celery = Celery('my_task',broker=app.config['CELERY_BROKER_URL'])
celery.conf.update(app.config)
.............

def UpdateScanerProgress(percent,sid):
    print('UpdateScanerProgress')
    socketio = SocketIO(message_queue='amqp://')
    socketio.emit('ScanerProgress', percent, room=sid)

def UpdatedScanMatch(data_array,sid):
    print('UpdatedScanMatch')
    socketio = SocketIO(message_queue='amqp://')
    print(data_array)
    socketio.emit('ScanMatch', data_array, room=sid)

##UpdateScanerProgress will called in thread Scaner_main() for 100 times
@socketio.on('scan')
def start_scan(ScanParameter,sid):#scan should be forked by self,emit be handed over to celery
    print('ws start_scan')
    print(ScanParameter)
    print(sid)
    print(request.sid)#should be same
    socketio = SocketIO(message_queue='amqp://')
    socketio.emit('array', [1,2,'hello',3], room=request.sid)
    # multiprocessing.Process #first use thread test ,easy for debug
    scan_async = threading.Thread(
        target=StockModal.Scanner.Scaner_main,
        kwargs={'ScanParameter': ScanParameter,
                'sid': request.sid
                }
    )
    scan_async.setDaemon(True)
    #scan_async.daemon=True
    scan_async.start()

`

**Comment by GitKKg** [comment]
it seems related to data volume size.
when emit progress, some time get a big array to emit ,just first time to emit this big array,the event receiving of client is broken,so ,is there any data size limit on emit or data type limit?pickle?

relevant code:
 websocket.UpdatedScanMatch(
                        [code, name, np.array(dates), np.array(values),
                         np.array(shares), np.array(factors), np.array(averages),
                         np.array(fuquan_averages), np.array(topSeq), np.array(bottomSeq), graphs],
                                     self.sid)
def UpdatedScanMatch(data_array,sid):
print('UpdatedScanMatch')
socketio = SocketIO(message_queue='amqp://')
print(data_array)
socketio.emit('ScanMatch', data_array, room=sid)

**Comment by GitKKg** [comment]
found the solution,but cant't understand:
**not OK:**
websocket.UpdatedScanMatch(
                        [code, name, dates, values.tolist(),
                         shares.tolist(), factors.tolist(), averages.tolist(),
                         fuquan_averages.tolist(), topSeq.tolist(), bottomSeq.tolist(), **graphs**],
                                     self.sid)
**OK:** websocket.UpdatedScanMatch(
                        [code, name, dates, values.tolist(),
                         shares.tolist(), factors.tolist(), averages.tolist(),
                         fuquan_averages.tolist(), topSeq.tolist(), bottomSeq.tolist(), **repr(graphs)**],
                                     self.sid)

print(graphs)
[['rect', **56**, 89, 19.41946436588902, 17.374500569026804, [59, 71], [66, 80]]]
socketio.emit except to say 56 is not json  serializable

why graph not json  serializable? but repr(graphs) is ?

**Comment by miguelgrinberg** [comment]
Print the type of that object to see what is it. Try `print("the type of", graphs[0][1], "is", type(graphs[0][1]))` or something similar.

**Comment by GitKKg** [comment]
the type of 56 is <class 'numpy.int32'>

i see...
i handled the array list,but let number type slipped through the net

Thank you,you always get the point quickly
