### ISSUE TITLE
404 Error With gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 server:app    

### ISSUE THREAD

**Issue by Aniket965** [miguelgrinberg/Flask-SocketIO#729]
my server.py contains
```sh
    socketio.init_app(app)
    from geventwebsocket.handler import WebSocketHandler
    http_server = WSGIServer(('', 5000),app.wsgi_app,handler_class=WebSocketHandler)
    srv_greenlet = gevent.spawn(http_server.serve_forever)
    notify_greenlet = gevent.spawn(listen_thread)
    gevent.joinall([srv_greenlet, notify_greenlet])
```

i am using 

```sh
gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 server:app    
```

getting 404s from this http://localhost:8000/socket.io/?EIO=3&transport=polling&t=MHdK5js
it works fine if i start with normal python shell, i am trying to deploy it on heroku
any help will be appreciated

**Comment by miguelgrinberg** [comment]
you can't have gunicorn and gevent's WSGI server at the same time, you have to pick one or the other. Both should work with Heroku. If you go with gevent's own server, make sure you replace the 5000 port with `int(os.environ.get('PORT'))`.

**Comment by Aniket965** [comment]
thanks Solved
