### ISSUE TITLE
Streaming Video and Audio

### ISSUE THREAD

**Issue by pudg** [miguelgrinberg/Flask-SocketIO#733]
I'm trying to stream a webcam feed captured using OpenCV, and audio captured using PyAudio that's used as input to a waveform visualizer. I've followed miguels guide on [streaming video](https://blog.miguelgrinberg.com/post/video-streaming-with-flask) but the issue is when i'm trying to stream the audio at the same time. Off the bat when I start my server, app.py the webcam feed works fine, and after i refresh, the audio thread gets started and I can see that it's running since refreshing prints "emitting audio bytes: 0", "emitting audio bytes: 57", and so on.
`        socket_io.emit('audio_bytes', {'data': frames})
`
 My issue seems to be that my client (javascript) can't seem to communicate with my audio_thread. I've noticed that if I stop my server (app.py) and don't close my browswer tab, then restart the server the browser actually renders the audio, waveforms visuals appear, and console logs also, but the webcam feed is frozen. Refreshing my browser starts the webcam feed, but I loose the audio visualizer and console logs.

**Comment by miguelgrinberg** [comment]
What web server are you using? Sounds like it can handle one client at a time. If you are using the Flask development web server, make sure you run it in multithreaded mode.

**Comment by miguelgrinberg** [comment]
Okay, if you are using `socketio.run()` then your web server should be correctly configured. Did you install eventlet or gevent in your virtualenv? I'm not sure if these frameworks are compatible with pyaudio and opencv. If you have any of these packages installed, try removing them to see if things work better. The performance will drop because without an async framework there is no websocket support, but at least we'll confirm that the problem is there.

**Comment by pudg** [comment]
Uninstalled 

> eventlet, and redis
Ran my app.py and got 
`WebSocket transport not available. Install eventlet or gevent and gevent-websocket for improved performance.
`
And now it works! Yo, thanks for the help!

**Comment by miguelgrinberg** [comment]
When you run the app without eventlet, Flask-SocketIO uses operating system threads, so all these packages can do what they need to do without blocking the other threads. When using eventlet, there is only one thread, so anything that blocks affects the entire application. Either PyAudio or OpenCV or both are causing eventlet to block.

The drawback of not using eventlet is that you've lost websocket support. Just want you to be aware that while you've got the app to work, this configuration isn't great in terms of performance.

**Comment by miguelgrinberg** [comment]
The only performant option is to use websocket and for that you need to use an async framework, either gevent or eventlet.
