### ISSUE TITLE
pika blocks updates

### ISSUE THREAD

**Issue by m8man** [miguelgrinberg/Flask-SocketIO#734]
When I run my code using pika (to read a RabbitMQ queue) is seems to block the socketIO connection between the python program and the html file. More specifically; the `on_message` function below receives a message body every few seconds, a body which contains a random number "c". The web page (index.html) does not load until the first message has arrived. Even when it has arrived, it takes a few cycles before `socket_io.emit` actually emits the data to index.html. And finally, even when it has started emitting it will skip the first messages (those will be gone and not sent to index.html).

If I uncomment the part below where it says "This works!!:" (and comment out the pika part above), it works as I want it to work when I use pika. The page loads immediately, all emits works. 

I start the program using "python app.py"

Does anyone have any suggestion to what I have done wrong?

**app.py:**
```
from flask import Flask, render_template, session
from flask_socketio import SocketIO, emit
import eventlet
from threading import Lock
import pika
import json
import time

eventlet.monkey_patch()
async_mode = None
app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret_key'
socket_io = SocketIO(app, async_mode=async_mode)
thread = None
thread_lock = Lock()


@app.route('/')
def index():
    return render_template('index.html', async_mode=socket_io.async_mode)


@socket_io.on('connect', namespace='/test')
def test_connect():
    print("New client connected")
    emit('my_response', {'data': 'Connected', 'count': 0})


@socket_io.on('my_event', namespace='/test')
def test_message(message):
    emit('my_response', {'data': message['data'], 'count': 1})


def start_background_thread():
    # This does not work:
    socket_io.sleep(0)
    connection = pika.BlockingConnection(pika.ConnectionParameters(host='localhost'))
    channel = connection.channel()
    channel.queue_declare(queue='hello') 
    channel.basic_consume(on_message,
                          queue='hello',
                          no_ack=True)
    print(' [*] Waiting for messages:')
    channel.start_consuming()
    # This works!!:
    # for i in range(100):
    #     socket_io.sleep(0)
    #     print('Number: ' + str(i))
    #     socket_io.emit('my_response', {'data': 'Server generated event', 'count': i},namespace='/test')
    #     time.sleep(5)


def on_message(channel, method, properties, body):
    print(" [x] Received %r" % body)
    socket_io.sleep(0)
    body = json.loads(body)
    count = body[0]["c"]
    socket_io.emit('my_response', {'data': 'Server generated event', 'count': count}, namespace='/test')
    print('Data emitted')


def my_background():
    global thread
    with thread_lock:
        if thread is None:
            thread = socket_io.start_background_task(target=start_background_thread)
    print('Background thread started')


my_background()

if __name__ == '__main__':
    socket_io.run(app)
```

**index.html:**

```
<h1>Test Flask scocketIO</h1>
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.1.1/socket.io.slim.js"></script>
<p id="insert"></p>
    <h2>Receive:</h2>
    <div id="log"></div>
</body>

<script>
    $(document).ready(function() {
    namespace = '/test';
    var socket = io.connect(location.protocol + '//' + document.domain + ':' + location.port + namespace);

    socket.on('connect', function() {
                socket.emit('my_event', {data: 'I\'m connected!'});
            });
    socket.on('my_response', function(msg) {
                $('#log').append('<br>' + $('<div/>').text('Received #' + msg.count + ': ' + msg.data).html());
            });
    });
</script>
```

**Comment by miguelgrinberg** [comment]
Try moving the monkey patching above all other imports.

**Comment by m8man** [comment]
I moved 
```
import eventlet
eventlet.monkey_patch()
```
aboved all code. The problems are still there. 

If i run the code without sending any message (so the page never loads, just continue saying "waiting for 127.0.0.1..."), and press Ctrl+C, then the page loads and I get the following output in the shell where I started the program:

> KeyboardInterrupt
> 
> (42968) accepted ('127.0.0.1', 34252)
> (42968) accepted ('127.0.0.1', 34254)
> (42968) accepted ('127.0.0.1', 34256)
> New client connected
> (42968) accepted ('127.0.0.1', 34258)

**Comment by m8man** [comment]
Thanks for the help, it now works using gevent.
With your information I made the following changes:

Removed:
```
import
eventlet.monkey_patch()
```
Added
```
from gevent import monkey
monkey.patch_all()
```

Thanks again!

**Comment by miguelgrinberg** [comment]
Oh interesting, thanks for the update!

**Comment by tim-ireland** [comment]
Posting for other folks who may find this thread in the future, I ran into this issue while using `eventlet` with `pika` (on centos 7.5), and the following worked for me, YMMV.  

I believe the blocking behavior has to do with the way the pika implementation wraps `select.poll.poll()` in the `PollPoller` class (in pika/adapters/select_connection.py).  I was clued into this by using `eventlet.debug` module's [blocking detection](http://eventlet.net/doc/modules/debug.html), which alarmed in the `poll` method at the following line:
```python
    events = self._poll.poll(deadline)
```

The following import strategy resolved the blocking behavior.

```python
# Import and patch stdlib first
import eventlet
eventlet.monkey_patch()

# Import and patch pika itself
pika = eventlet.import_patched('pika')
```
