### ISSUE TITLE
Cant make it work (the example)

### ISSUE THREAD

**Issue by jediborre** [miguelgrinberg/Flask-SocketIO#735]
I dont know if I a dumb, but I cant make it work 

@MARK-IV:/mnt/volume-sfo2-01/html/chat# python3.6 chat.py
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 535-969-569
(31115) wsgi starting up on http://127.0.0.1:5000

When I go to chrome and point to http://domain:5000 or http://ip:5000 
Chrome says ERR_CONNECTION_REFUSED

Im on Ubuntu 14.04.5 LTS (GNU/Linux 4.4.0-116-generic x86_64)

@MARK-IV:/mnt/volume-sfo2-01/html/chat/bin# pip freeze
click==6.7
eventlet==0.23.0
Flask==1.0.2
Flask-SocketIO==3.0.1
Flask-WTF==0.14.2
greenlet==0.4.13
itsdangerous==0.24
Jinja2==2.10
MarkupSafe==1.0
python-engineio==2.1.1
python-socketio==1.9.0
six==1.11.0
Werkzeug==0.14.1
WTForms==2.2.1

t@MARK-IV:/mnt/volume-sfo2-01/html/chat/bin# ufw status
Status: active

To                         Action      From
--                         ------      ----
22                         LIMIT       Anywhere
443                        ALLOW       Anywhere
80                         ALLOW       Anywhere
3306                       ALLOW       Anywhere
23                         ALLOW       Anywhere
10000                      ALLOW       Anywhere
465/tcp                    ALLOW       Anywhere
587/tcp                    ALLOW       Anywhere
5000                       ALLOW       Anywhere
22 (v6)                    LIMIT       Anywhere (v6)
443 (v6)                   ALLOW       Anywhere (v6)
80 (v6)                    ALLOW       Anywhere (v6)
3306 (v6)                  ALLOW       Anywhere (v6)
23 (v6)                    ALLOW       Anywhere (v6)
10000 (v6)                 ALLOW       Anywhere (v6)
465/tcp (v6)               ALLOW       Anywhere (v6)
587/tcp (v6)               ALLOW       Anywhere (v6)
5000 (v6)                  ALLOW       Anywhere (v6)

**Comment by miguelgrinberg** [comment]
You don't say from where you obtained the chat application that you are using. The application is configured to listen on `localhost` only, which is the default for Flask. You need to add `host='0.0.0.0'` on the `socketio.run()` call to make it listen on the public network interface.
