### ISSUE TITLE
Consider supporting the `skip_sid` parameter for `emit`

### ISSUE THREAD

**Issue by Hendrikto** [miguelgrinberg/Flask-SocketIO#736]
The `emit` function currently only supports the `include_self` parameter. I had to use `socketio.emit` because the client I want to exclude is not the originator of the event, so `include_self` does not fit my use case. It is of course easily possible to work around this by using `socketio.emit` instead, but it is not context-aware, so using it is a bit inconvenient.

**Comment by StoneMoe** [comment]
Also consider supporting `list` type for `skip_sid` parameter please

**Comment by miguelgrinberg** [comment]
This has been done a while ago and I forgot to close.
