### ISSUE TITLE
nginx not load balancing

### ISSUE THREAD

**Issue by JesseChua94** [miguelgrinberg/Flask-SocketIO#742]
Hi Miguel,

First off just want to thank you for all your hard work. The amount of activity and speed you have in helping others is insane. Second, I was wondering if you knew what the issue was here. I'm trying to configure nginx as a load balancer over gunicorn and flask with flask-socketio. Nginx as a reverse proxy worked fine with flask and we've already tested the sockets and they worked all fine. Now i'm trying to make use of nginx load balancing but when i ran three gunicorn servers and started connecting clients they only streamed to one server. I followed the nginx.conf as specified in the docs:

```
upstream socketio_nodes {
    ip_hash;

    server 127.0.0.1:8000;
    server 127.0.0.1:8001;
    server 127.0.0.1:8002;
    # to scale the app, just add more nodes here!
}
server {
    listen 5001;
    server_name localhost;

    location / {
        include proxy_params;
        proxy_pass  http://socketio_nodes;
    }

    location /socket.io {
        include proxy_params;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass http://socketio_nodes/socket.io;
    }
}
```

I made a small change in the first proxy_pass as seen on one of your comments to another issue. I started the servers by running the gunicorn command three times specifying the port as `-b :8000` * 3 for each different port. Thanks in advance!

**Comment by miguelgrinberg** [comment]
Are you connecting from different IP addresses? The `ip_hash` mechanism of load balancing selects a server from the pool based on the IP address. If all your clients come from the same IP address then they are all going to end up in the same server.

**Comment by JesseChua94** [comment]
We are streaming from ipods that have our app so they should all have different ip addresses.

**Comment by miguelgrinberg** [comment]
Are you sure these ipods don't all show up with the IP address of a router? I really see nothing wrong in your config, the server selection algorithm is very simple, maybe you should take a look at the nginx logs to see what those client IP addresses are.

**Comment by JesseChua94** [comment]
Okay will do and will get back to you when I find out.

**Comment by JesseChua94** [comment]
I just checked, they all show up with different ip addresses but have the same router ip address.

**Comment by miguelgrinberg** [comment]
If your clients are in one network, and your server is in another, then you are using the router as a bridge between the two networks. On the application side, all the clients are behind the router, so they'll all have the IP address that the router was assigned in the application's network. You can't have IP addresses from two networks mixed up.

The solution (which may or may not be possible in your case) would be to make sure that the application and the clients are all in the same network and talk to each other directly instead of having a router between them.

**Comment by JesseChua94** [comment]
Hm so I just checked and both the client and server are under the same router. To make sure the client ip addresses were different, I printed the ip addresses coming in to my application (removed nginx to test). I tried it again with nginx load balancing and no errors showed up in the error log.

**Comment by JesseChua94** [comment]
Hey there I believe we just found the error (not tested yet). I missed the part where ip_hash is described as using the first three octets of IPv4 addresses which are all the same for our ip addresses.

**Comment by miguelgrinberg** [comment]
Ah, that's right, they don't use the last part. On the other side, if all your addresses have the first three octets, that means that you have at most 256 clients, which is a number for which you probably don't need more one server anyway.

**Comment by JesseChua94** [comment]
We're concerned with the load if we have too many clients connected to one server since gunicorn only supports one worker and this will be simultaneous data streaming through socketio

**Comment by JesseChua94** [comment]
Yes, sorry. I forgot to mention that the data is constantly being streamed and we are processing it in the backend which takes up CPU. We found that, without load balancing on a local server, the processing can already be taxing with a handful of clients. We have been looking for a work around to hash with the full client IP.
