### ISSUE TITLE
With socketio.init_app Debug mode broken: it won't reload on file changes, app doesn't show any logs at all.

### ISSUE THREAD

**Issue by idchlife** [miguelgrinberg/Flask-SocketIO#743]
Here is a repository to reproduce.

gevent & gevent-websocket

(mind - for usage with pipenv)

https://github.com/idchlife/flask-socketio-repro

**Comment by idchlife** [comment]
I noticed the same behaviour when using gevent with gunicorn.

Unfortunately, eventlet is kinda broken to work with gunicorn.
But with flask run - eventlet works fine.

It seems exactly gevent causes silence and no debug-reload

**Comment by miguelgrinberg** [comment]
I mentioned this before, you realize that gevent is a different web server than Flask's, and so is eventlet? Each has its own options and defaults for logging.

Also "eventlet is kinda broken with gunicorn" is not something I head about. I actually have a few projects that use that combination and never saw a problem.

**Comment by idchlife** [comment]
Sorry, I did not know about this. New to the python ecosystem. I thought since flask views, extensions etc work with gunicorn server, flask server - it was like php-fpm and any php-framework. Each will
have their logs etc.
I thought gevent blocks flask logging or something.

About eventlet - for me fresh installation gave several issues on startup including ‘module socket has no attribute socket’, which stopped me from trying to use it further.

Thanks!
