### ISSUE TITLE
cannot run socketio on ubuntu 16.04

### ISSUE THREAD

**Issue by nexthor** [miguelgrinberg/Flask-SocketIO#745]
Hi @miguelgrinberg , i am trying to set up a socket server in a ubuntu 16.04 completly new, i am following this tutorial:

https://www.digitalocean.com/community/tutorials/how-to-serve-flask-applications-with-uwsgi-and-nginx-on-ubuntu-16-04

But i can't make that work, i already try every configuration that i found but nothing seems to work, this are my files:

**run.py**

`from flask import Flask, session, request
from flask_socketio import SocketIO, emit, disconnect
app = Flask(__name__)

...

socketio = SocketIO(app, async_mode='gevent')

@socketio.on('list_event', namespace='/list')
def list(data):
    emit('list_response', {'data': 'data'}, broadcast=True)

if __name__ == '__main__':
    socketio.run(app)`

**list of packages:**

`Package            Version
------------------ --------
alembic            1.0.0
aniso8601          3.0.2
asn1crypto         0.24.0
blinker            1.4
cffi               1.11.5
click              6.7
cryptography       2.3
Flask              1.0.2
Flask-Cors         3.0.6
Flask-JWT-Extended 3.11.0
Flask-Mail         0.9.1
Flask-Migrate      2.2.1
Flask-RESTful      0.3.6
Flask-SocketIO     3.0.1
Flask-SQLAlchemy   2.3.2
gevent             1.3.5
gevent-websocket   0.10.1
greenlet           0.4.14
idna               2.7
itsdangerous       0.24
Jinja2             2.10
Mako               1.0.7
MarkupSafe         1.0
passlib            1.7.1
pip                10.0.1
pkg-resources      0.0.0
pycparser          2.18
PyJWT              1.6.4
PyMySQL            0.9.2
python-dateutil    2.7.3
python-editor      1.0.3
python-engineio    2.2.0
python-socketio    2.0.0
pytz               2018.5
setuptools         40.0.0
six                1.11.0
SQLAlchemy         1.2.10
uWSGI              2.0.17.1
Werkzeug           0.14.1
wheel              0.31.1`

**/etc/nginx/sites-availeble/site:**

`server {
    listen 8080;
    server_name 70.32.30.196;
    # return 301 $scheme://70.32.30.196:8080$request_uri;

    location / {
        include proxy_params;
        include uwsgi_params;

        uwsgi_pass http://70.32.30.196:8080;
    }

    location /socket.io/ {
        include proxy_params;
        try_files $uri $uri/ =404;
        proxy_http_version 1.1;
        proxy_redirect off;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        # proxy_pass http://70.32.30.196:8080/socket.io;
    }
}`

**site.ini**

`[uwsgi]
module = run:app

master = true
processes = 5

socket = site.sock
chmod-socket = 660
vacuum = true
http-timeout = 3600000
buffer-size=32768

die-on-term = true

logto = /var/log/nginx/%n.log
`

**/etc/systemd/system/site.service:**

`[Unit]
Description=uWSGI instance to serve site
After=network.target

[Service]
User=root
Group=www-data
WorkingDirectory=/var/www/html/site
Environment="PATH=/var/www/html/site/site/bin"
ExecStart=/var/www/html/site/site/bin/uwsgi --ini /var/www/html/site/site.ini

[Install]
WantedBy=multi-user.target`

This all configuration always response **404** error, or **301** or **invalid host in upstream**.

As i said, i can't make it work and i can't find any guide anywhere, please, can you help me?

Thanks

**Comment by miguelgrinberg** [comment]
I believe you can't proxy WebSocket connections using the uwsgi protocol. You can use uWSGI, but it needs to be configured to talk HTTP with nginx. Also no idea what that `try_files` in the socket.io block is about, that should be a proxy_pass.
