### ISSUE TITLE
How can I run my flask-socketio server asynchronously

### ISSUE THREAD

**Issue by sbqsbqsbq** [miguelgrinberg/Flask-SocketIO#746]
Hi, I'm running my server via executing the below code.

```
# run.py
from app import app, socketio
from gevent.pywsgi import WSGIServer
from gevent.monkey import patch_all


if __name__ == '__main__':
    # app.run(host="0.0.0.0", use_reloader=False)
    socketio.run(app, host="0.0.0.0", use_reloader=False, certfile="~~~", keyfile="~~~")
    patch_all()

```

```
#__init__.py

import os
from flask import Flask, session
from flask_cors import CORS
import app.core.respond as respond
import logging

from flask_jwt_extended import JWTManager
from flask_socketio import SocketIO, emit
from flask_mongoengine import MongoEngine
from raven.contrib.flask import Sentry

import datetime

async_mode = None

socketio = SocketIO(async_mode="eventlet")
app = Flask(__name__)
db = MongoEngine()

app.config['SECRET_KEY'] = ''
app.config['JWT_SECRET_KEY'] = ''
app.config['JWT_ACCESS_TOKEN_EXPIRES'] = datetime.timedelta(seconds=24*60*60)
app.config['MONGODB_SETTINGS'] = {
    'db': '',
    'host': '',
    'port': ,
    'username': '',
    'password': ''
}

jwt = JWTManager(app)
cors = CORS(app)
db.init_app(app)

try:
    env = os.environ['APPLICATION_ENV']
except KeyError as e:
    env = "Development"

app.config.from_object("config.%s" % env)
app.config.update(
    DEBUG=False,
    TESTING=False,
    TEPLATES_AUTO_RELOAD=True,
    JWT_ACCESS_TOKEN_EXPIRES=datetime.timedelta(seconds=24*60*60),
    JWT_SECRET_KEY='jwt-secret-key',
    SECRET_KEY='MySecretKey'
)


@app.errorhandler(404)
def not_found(error):
    return "Not Found.", 404


from app.core.controllers import core as core
from app.endpoint.controllers import endpoint as endpoint
from app.chat.controllers import chat as chat

app.register_blueprint(core)
app.register_blueprint(endpoint)
app.register_blueprint(chat)

socketio.init_app(app)

```

It runs correctly, but when the users concurrently request HTTP methods, It causes an error.
I use the eventlet as the async mode. How can I solve this problem?

**Comment by miguelgrinberg** [comment]
First of all, you are confusing eventlet and gevent, which are two different async frameworks. Which one do you want to use? If you want to use eventlet, then remove all the gevent monkey patching and add the eventlet monkey patching instead.

Also, monkey patching needs to be done at the top of the script, above all other imports.

**Comment by sbqsbqsbq** [comment]
@miguelgrinberg I want to use eventlet. then, Do I have to remove all of codes which is relevant to 'gevent'?

**Comment by miguelgrinberg** [comment]
In run.py you need to monkey patch using eventlet, not gevent. Also move the monkey patching call to the top of the script, above all other imports. This ensures that the application imports monkey patched functions.

**Comment by sbqsbqsbq** [comment]
@miguelgrinberg Thank you for answering :) I will apply it immediately. Thanks

**Comment by miguelgrinberg** [comment]
This could be an issue with eventlet, try a more recent version or look at their issue board.

**Comment by humba4git** [comment]
> Also move the monkey patching call to the top of the script, above all other imports.

Thank You SO MUCH!!! I spent alot of time to make my code works in async mode and now it is!
