### ISSUE TITLE
Can't quiet understand how to receive messages. Maybe I'm missing something? on('message') not working on client

### ISSUE THREAD

**Issue by idchlife** [miguelgrinberg/Flask-SocketIO#747]
It seems that I'm doing something wrong. Here is repro repository:

https://github.com/idchlife/flask-socketio-repro

it can be checked via ./run.sh

access localhost:5004 and open console, you can see message about connecting is ok.

But server sent "message" is not received by client.

Any event or message sent by server is not being received by client.

Thanks!

**Comment by miguelgrinberg** [comment]
You are mixing up `emit()` and `send()`. You should use `emit()` in your server and your client, the `send()` function is there for compatibility with older versions of the Socket.IO protocol.

**Comment by idchlife** [comment]
Just updated repro repository with using emit, same situation

Maybe I'm using wrong version of socketio client library?

**Comment by miguelgrinberg** [comment]
You are using a somewhat old version, but that shouldn't be a problem, I think.

Have you tried starting from the example application in this repository? The `message` event name is part of that legacy part of the protocol associated with the `send()` function. The reserved event names are `connect` and `disconnect`, which are both okay as handlers, but should not be emitted and then `message` and `json`, which are predefined events associated with the `send()` function. Try using a different name for your custom event than `message`.

Also, it might be easier to start from a working application, such as the example in this repository.

**Comment by idchlife** [comment]
Hmm... I tried newer version also new event named "custom".
Still no luck.

If indeed I am doing something wrong, I will use example.
Now I'm just trying to understand why won't simplest case work.

I updated repository to reproduce with newest additions:

https://github.com/idchlife/flask-socketio-repro

It just confuses me that simplest code with socketio doesn't work and I can't understand why, since there are no errors or something, warnings etc. Server says it sent event and client says nothing about event.

**Comment by miguelgrinberg** [comment]
Well, I'm 100% sure you have a mistake somewhere in there, but today I don't have time to debug it for you. Sorry.

**Comment by idchlife** [comment]
I'm sorry if it seems that I'm asking to debug it for me. I tried to create as thin reproduce repository as possible so it can be very quickly checked what's seems to be the problem.

I just finished working with your example folder, compared, stripped and changed to check what is wrong.

It seems the problem with "/socket.io" in my url (can be see in reproduce repository here: 
https://github.com/idchlife/flask-socketio-repro/blob/master/templates/test-socket.html#L3 )

I read in your code about this:

<img width="336" alt="default" src="https://user-images.githubusercontent.com/4563032/43040875-daa9f8f8-8d58-11e8-8b5e-9302e376dd74.png">

It's in constructor of SocketIO

So I guessed that if it's written in the doc about default value - also since there is this in documentation:

<img width="370" alt="default" src="https://user-images.githubusercontent.com/4563032/43040885-f88e0382-8d58-11e8-9be8-2797d6a4252e.png">

I assumed that /socket.io should be in my url.

When I removed it, I started receiving messages from server.

**Comment by miguelgrinberg** [comment]
Oh I see, I missed that when I looked at your code. So this was a client-side issue. Socket.IO connection URLs are a bit weird, so I can see how this can be confusing. See the official Socket.IO client docs: https://socket.io/docs/client-api#io-url-options. The path in the connection URL is used for the namespace. The path is usually set to `/socket.io` and is not specified. If you want to use a path that is not `/socket.io` for your socket.io endpoint then you need to pass it in the `path` argument, both in the client and the server.

**Comment by idchlife** [comment]
I think it would be nice to add this to documentation or docblock at some point. (maybe even url pointing to socketio documentation). For people like me, new to socketio, it can be "obvious" that this should be in url, when it is not.

Thanks for helping with issue!
