### ISSUE TITLE
Client does not receive custom events with message_queue in constructor, or in constructor + .init_app. Repro inside 

### ISSUE THREAD

**Issue by idchlife** [miguelgrinberg/Flask-SocketIO#748]
Hi! It's me again 😄 

I think I stumbled upon real case this time. Actually, this case was the first one, but I did not reproduce it when using your example, since redis needed just for my working app (several processes, threads, etc), so I totally missed the real problem that time.

I updated repository with code to reproduce, will try to give as more info as possible to quickly find what is the problem:

https://github.com/idchlife/flask-socketio-repro

- There are 3 scenarios in app.py file:

https://github.com/idchlife/flask-socketio-repro/blob/master/app.py#L11

As usual, to start app:

pipenv install
./run.sh

I discovered that when `message_queue` specified inside constructor (SocketIO(message_queue=)) and then .init_app() used without it (or even with it, .init_app(message_queue=)) - client does not receive custom events. But server claims it is sending them.

That issue was the main mindbreaker, because no logs, no errors, server says it is sending something and client keeps silent.

For now I am using message_queue only in .init_app, but I hope this issue can help solve this mystery (or maybe it is known issue and I missed it).

Thanks!

**Comment by miguelgrinberg** [comment]
Why do you need to pass arguments in both places? With flask extensions you either initialize the extensions in the constructor, or else in `init_app()`. No need to do it on both.

**Comment by idchlife** [comment]
Of course, both - it was just a test case. I often pass in constructor or .init_app

But I can sometimes find myself passing specific configuration inside constructor, and then making .init_app just with app as argument (if method allows passing only app, some extensions explicitly require arguments in .init_app, then I do not pass anything in constructor, since I will need to pass arguments twice)

You mean this is expected behaviour and only one of both should be used? (constructor or .init_app)

```python
s = SocketIO(message_queue=URL)

s.init_app(app)

# Client can't catch events
```

**Comment by miguelgrinberg** [comment]
Only one should be used, I honestly did not expect that the initialization arguments would be given in two groups. I don't think there are any extensions that support that.

**Comment by idchlife** [comment]
Ok thanks for the answer!
