### ISSUE TITLE
Broadcast message to all users except for sender

### ISSUE THREAD

**Issue by machow** [miguelgrinberg/Flask-SocketIO#75]
Hello,
You mentioned to a user [on your blog](http://blog.miguelgrinberg.com/post/easy-websockets-with-flask-and-gevent/page/5) that they should submit this issue on github, but I couldn't find it--so just wanted to submit it for them ;). 

The third snippet of [this SO post](http://stackoverflow.com/a/10099325/1144523) shows how it can be done using the original socket.io server:

```
// sending to all clients, include sender
io.sockets.emit('message', "this is a test");

// sending to all clients except sender
socket.broadcast.emit('message', "this is a test");
```

Would this be possible to implement here? I'm not sure if this falls in the domain of this flask extension or gevent-socketio, as my websocket skills are fairly poor--but I'm happy to try to implement it if you have a sense for where it should go.

**Comment by miguelgrinberg** [comment]
In release 1.0, the `emit` and `send` functions have a `include_self` argument that can be set to `False` to skip the sender when broadcasting a message.

**Comment by comountainclimber** [comment]
I am very interested in this functionality can you paste a copy of the emit method with this syntax included? why isnt this anywhere in the socket docs haha

**Comment by comountainclimber** [comment]
<pre> socketServer.to(data.destination).emit(include_self=false,'keyPressEmission', data) </pre>

so this worked perfectly thank you!
