### ISSUE TITLE
Problem for using emit() to send message to clients of different namespace

### ISSUE THREAD

**Issue by suyeH** [miguelgrinberg/Flask-SocketIO#752]
I have two namespace in two different clients: '/' and '/123', I want both clients of namespace in  '/' and '/123' connected to the server will emit a message to the clients of namespace '/123'. The server-side code is as below.

```
@socketio.on('connect')
def test_connect():
        emit('OK', {'data': 'hello word!'}, broadcast=True, namespace='/123')
        print('Client connect')
        print(request.sid)
        print(request.namespace)
```

But it doesn't work when a '/123' clients connected to the server. the client-side is as below:

```
$(document).ready(function() {
      namespace = '/123';
      var socket = io.connect(location.protocol + '//' + document.domain + ':' + location.port + namespace);
      socket.on('OK', function(data) {
        console.log('#=> receive server data', data.data);
        alert(data.data);
      });


  });
```

This doesn't work as I thought, and I can't figure out the reason.

**Comment by miguelgrinberg** [comment]
You need a connect event for each namespace.
