### ISSUE TITLE
emit inside on_disconnect result in websocket file-descriptor leak

### ISSUE THREAD

**Issue by AndCycle** [miguelgrinberg/Flask-SocketIO#753]
sorry I don't have a proper minimal example to demonstrate this for now as I am debugging a prod server,
which use gevent.pywsgi/gevent-websocket

here is a simplified pseudo code related

```
class custom_namespace(flask_socketio.Namespace):
    def on_disconnect(self):
        flask_socketio.emit('update_room_user_list', room=disconnect_client_in_this_room)
       
        # also have issue
        # flask_socketio.emit('update_room_user_list', room=disconnect_client_in_this_room, skip_sids=request.sid)
```
after I close the browser result in leaked socket report by `lsof`,
`python    10662     root   14u     sock                0,8       0t0      98321 can't identify protocol`

I am not really sure is this a bug in flask-socketio or I use flask-socketio incorrect,
as I don't see any example explain correct way to do this.

**Comment by AndCycle** [comment]
I think I found the correct way to do so,

```
class custom_namespace(flask_socketio.Namespace):
    def on_disconnect(self):
        sid = request.sid
        for room in self.rooms(sid):
            flask_socketio.leave_room(room, sid)
        flask_socketio.emit('what_ever_i_want')
````
I have to very specific kick out that client from every room before emit to prevent this issue,

didn't expect I have to so, as `socket.io` server is dead simple on this

**Comment by miguelgrinberg** [comment]
Hmm, the disconnecting client should have been skipped for those emits. I need to investigate this, thanks for all the details.

**Comment by AndCycle** [comment]
after a day of running there are much fewer leakage, but still leak somewhere, 
so simply skip client on disconnecting state is probably not the correct solution.

**Comment by miguelgrinberg** [comment]
I believe this has been addressed as part of the recent changes to eliminate file descriptor leaks. Try the latest versions of Flask-SocketIO, python-socketio and python-engineio and reopen if you still have issues.

**Comment by AndCycle** [comment]
fix confirmed, online for a month and no fd leak.

**Comment by miguelgrinberg** [comment]
@AndCycle thank you so much for coming back to report good news. :)
