### ISSUE TITLE
Buffer/Queue fills up when client is not consuming socketio emit

### ISSUE THREAD

**Issue by maximillion90** [miguelgrinberg/Flask-SocketIO#754]
I have a flask-socketio server which when the client is connected emits log messages. The intention is for real time log viewing. I noticed the application was leaking memory (occasionally) so after some investigation I found that on occasion the disconnect message from the client was getting lost and therefore the server was unaware that the client was no longer listening and this was causing memory to be eaten up.
After some more research I found a reference that said that the client MUST be consuming or the buffer/queue would fill up rather than the messages be silently dropped (like they are if no client is connected). So the memory is leaked in the gap between the client disconnecting and the ping timeout closing the connection on the server side. 
While I understand I need to fix the lost disconnect message it is clear that it can be the case that the client silently disconnects and so I wonder if there is a way to reset/clear this buffer/queue it and get that memory back?

Sorry if the answer is out there but I did try my best.

Thanks
Max

**Comment by miguelgrinberg** [comment]
What Socket.IO client are you using? I believe that "client did not consume events" was a specific issue when using the Python Socket.IO client. That may not apply to other clients.

There is an open issue with disconnects that are missed when using the polling transport. This could be the issue you are having. You may want to test forcing a websocket transport from the start to see if that takes care of the problem. This is a tricky issue that I haven't had time to fully debug yet, sorry about that.

**Comment by maximillion90** [comment]
Firstly thanks for basically fixing my disconnect issue. I am sure that would of taken me a fair amount of google time to find that answer.

I have tested with socketIO-client  0.7.2 but the client i found the issue with was js socketIO client (sorry not my bit of code to bit vague). I will recheck this but i can definitely see memory usage rising when the js client disconnects (but flask-socketio does not know it has gone) and things are being emitted. 
It is not so much an issue now that the disconnect problem is fixed but i am still interested in why.

Thanks for your help.

Max

**Comment by miguelgrinberg** [comment]
I believe this is related to disconnected socket leaks, an issue that is already fixed.
