### ISSUE TITLE
uwsgi deployment got 404 error.

### ISSUE THREAD

**Issue by michael172849** [miguelgrinberg/Flask-SocketIO#757]
I got 404 when I try to connect to the socket from the client side.
This is the client side code, just like in the documentation:
```
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js"></script>
<script type="text/javascript" charset="utf-8">
    var socket = io.connect('http://' + document.domain + ':' + location.port);
    socket.on('connect', function() {
        socket.emit('my event', {data: 'I\'m connected!'});
    });
</script>
```
And this is the uwsgi configuration file. 
```
[uwsgi]
if-env = VIRTUAL_ENV
virtualenv = %(_)
endif =

module = wsgi
master = true
processes = 5
http-websockets= true
http= :5000
gevent= 1000

die-on-term = true
```

**Comment by michael172849** [comment]
And this is the client side error:

> http://127.0.0.1:5000/socket.io/?EIO=3&transport=polling&t=1533614761782-15
> [Error] Failed to load resource: the server responded with a status of 404 (NOT FOUND) (socket.io, line 0)

**Comment by miguelgrinberg** [comment]
Read the documentation for information on how to deploy with uwsgi.
