### ISSUE TITLE
How to detect user disconnection in "room"

### ISSUE THREAD

**Issue by zhangatao** [miguelgrinberg/Flask-SocketIO#758]
My question is, when I create a "room" via flask_socketio, I do not know how to get the statuses of users in this "room" , i.e. whether a user is connected or not.
For instance, when a user in this "room" is disconnected, how to get the the session_ID of this user?

**Comment by miguelgrinberg** [comment]
You get the `disconnect` event when a user disconnects. Inside this handler, `request.sid` will give you the session id of the client.

**Comment by zhangatao** [comment]
thank you very much,i have other question：
first,what situation can trigger disconnect event? 
second,how can i know what everybody's condition in 'room'.for example,who is alive,and who is disconnect?

**Comment by miguelgrinberg** [comment]
The disconnect event happens when the user closes the browser or client application. A user that disconnects is removed from all the rooms, so really if a user is in a room, that user is still connected.

**Comment by zhangatao** [comment]
thanks so much.
