### ISSUE TITLE
[Query] Error after 500+ client connections

### ISSUE THREAD

**Issue by swathins079** [miguelgrinberg/Flask-SocketIO#759]
Hi Miguel,

I am seeing the server is not accepting any new connection when it reaches 500+ client connections. After 500+ connections, I am seeing socket error and the server is not accepting any new connections after that.
I am using the server in evenlet mode.

Thanks,
Swathin

**Comment by miguelgrinberg** [comment]
Maybe you have reached the maximum number of file handles available to your process? This is likely an external configuration problem, neither eventlet nor Flask-SocketIO have any maximums.
