### ISSUE TITLE
getting socketio work on cpanel (Apache+passenger)

### ISSUE THREAD

**Issue by hunterfred** [miguelgrinberg/Flask-SocketIO#760]
Hi Miguel,

Thanks for the good work! I currently have a shared host with cpanel installed, I followed the tutorial found online and had successfully get the flask app working. I'm new to the web world, but it seems like it's way of working is passenger treat flask app as an wsgi callable.

The problem raised when I tried to get the socketio working, it seems like passenger doesn't like the socketio wrapper of flask app. What I've tried:
```
application=socketio(app)
```
This will give an error like "Incomplete response received from application"
if I just let
```
application=app
```
the app will run, but it seems like the initial connection is success, then the socket is disconnected, and the connection to the server is lost.
Then I tried the example code you gave in the python-socketio page:
```
sio = socketio.Server()
app = socketio.Middleware(sio, app)
application = app
```
still no luck (getting some 404, 302, 500 errors in the console log, given by the socketio.js, which I assume this means connection is not success).

I'm wondering if there is any correct way of doing socketio when using cpanel+passenger (as an wsgi app), I've been desperately searching for answers, yet no single works... :(, please help me.

**Comment by hunterfred** [comment]
Thanks for the quick reply! By deployment configurations you mean the command line deployment like the ones for gunicorn or uwsgi?

**Comment by miguelgrinberg** [comment]
Yes, there are a few combinations of servers and reverse proxies that are documented. Other options might work too, but these are the ones that have been tested.
