### ISSUE TITLE
emit is not working when called from a thread

### ISSUE THREAD

**Issue by swathins079** [miguelgrinberg/Flask-SocketIO#761]
Hi Miguel,

I am seeing some weird results when emit is called from a thread that I have created. Sometimes in the log message, I can see the log saying sending data to the device and sometimes the device is getting the message. It is not consistent. I am using eventlet.

Regrads,
Swathin

EDIT: When I changed the async_mode to gevent, it is working.

**Comment by miguelgrinberg** [comment]
You could be using functions that are incompatible with eventlet. Gevent is a little better at monkey patching, maybe that is what makes it work while eventlet does not.
