### ISSUE TITLE
socketio.emit() not working

### ISSUE THREAD

**Issue by Dobermensch** [miguelgrinberg/Flask-SocketIO#762]
hey I need the server to be the originator of a message when an entry is inserted into the database. I have this line in my app.py file
```
@app.route('/pet', methods=['GET'])
def insertPet():
...conducting insert in database...
socketio.emit('inserted_pet', {details: details}, broadcast=True)
return render_template('index.html')
```

on subscribe.html (using angularjs) where I have registered a listener as follows:
`socket.on('inserted_pet', function(results){
	console.log(results);
});`
All I see are some http 400 errors in the browser console.
Nothing shows up... now the thing is... on connect works so this means I have things correctly set up:  
```
@socketio.on('connect')
def on_connect():
    emit('test', {"test": "lmao"}, broadcast=True) 
    pass
```
in subscribe.html: 
```
socket.on('connect', function() {
	socket.emit('connect');
});
socket.on('test', function(results){
	console.log(results);
});
```

**Comment by miguelgrinberg** [comment]
If you are seeing 400 errors, then you don't have a good connection. How are you running the app? Check the documentation and make sure you are using a supported deployment method.

**Comment by Dobermensch** [comment]
Hey, I'm running the app locally.

**Comment by miguelgrinberg** [comment]
Locally how? Are you using an async framework? Gunicorn? uWSGI? Multiple or single processes? Please provide all the details.

**Comment by Dobermensch** [comment]
Hey, I'm using Gunicorn. I don't know what you mean by async framework and multiple or single processes. Could you give me some options or examples? Anyways here's a screen shot of my browser console:
![socketioerrors](https://user-images.githubusercontent.com/25876962/43990772-ba602ca8-9d92-11e8-8491-0410f1765b5e.PNG)

I added the following to further test it out:
```
@socketio.on('pet_added')
def petAdded(args):
    print("pet added called")
```
However there is not output when emitting 'pet_added'.

**Comment by miguelgrinberg** [comment]
Your problem is in how you are running your service, not in the application itself. What command line do you use to run it? I mentioned earlier that you should check the documentation for the supported deployment options. I still think you should check that out, because those 400s suggest you are using an invalid deployment solution.

**Comment by Dobermensch** [comment]
I'm using 'python manage.py runserver' to run the application. I've seen the documentation. I'm using socketio.run(app) in app.py and interestingly, I have not installed either eventlet or gevent so according to the documentation, the app is running on Flask’s development web server. I'll try installing eventlet and seeing if this works.

**Comment by Dobermensch** [comment]
Okay, I'll give it a go. Let's see what happens!

**Comment by Dobermensch** [comment]
It works! I used `python app.py` to run the app and everything is working now! Thanks!
