### ISSUE TITLE
Is there any way to suppress PING/PONG logs?

### ISSUE THREAD

**Issue by swathins079** [miguelgrinberg/Flask-SocketIO#763]
Hi Miguel,

The following log is logged everytime a client gets connected. Is there any way to suppress these logs?

`[INFO] 2018-08-14 18:31:53,685 cbd5051b885940f990d53728c042ff5f: Received packet PING data None`

Thanks for this awesome project.

Regards,
Swathin

**Comment by miguelgrinberg** [comment]
You can suppress all INFO logs by raising the level in your logger. To suppress only the PING lines while leaving other INFO logs intact you'll need to implement some sort of filter, so it is a non-trivial task.

**Comment by theahura** [comment]
For posterity, this worked for me:
```
import logging

class NoPingPongFilter(logging.Filter):

  def filter(self, record):
    return not ('Received packet PONG' in record.getMessage() or
                'Sending packet PING' in record.getMessage())


logging.getLogger('engineio').addFilter(NoPingPongFilter())

socketio = SocketIO(logger=False, engineio_logger=True)
