### ISSUE TITLE
Is it possible to use something like username instead of sid when specifying a room?

### ISSUE THREAD

**Issue by amirhb9472** [miguelgrinberg/Flask-SocketIO#765]
I'm creating a social network app and I'm going to add real time private chat feature to it using SocketIO but got a problem.
when I use sid to send messages, I face a problem when the recipient is not online or sid has changed.
is there any way to use something like username to send messages to instead of sid?
So when the recipient connects can see the message.

**Comment by miguelgrinberg** [comment]
Socket.IO does not have storage for events, when you call `emit()` the event is sent immediately. If you want your users to see messages they receive while they are offline you have to implement this as a feature of your application.
