### ISSUE TITLE
request test_client to throw an error when not authorized

### ISSUE THREAD

**Issue by BoWuGit** [miguelgrinberg/Flask-SocketIO#769]
Hi, miguelgrinberg, I write unit test just as follows:

> client = socketio.test_client(app)
//emit some message
received = client.get_received()

but as a result I can't receive any message, "received" is always an empty list. After much debugging I find that my socketio client hadn't got authorized, which is handled on the connect event, by returning false.

So for clarifying, I suppose "socketio.test_client" should return or throw something like 401 unauthorized error, which is friendly to first time users.

In the end, much thanks for your excellent work, best wishes.

**Comment by miguelgrinberg** [comment]
Oh, you are right, a `False` return isn't correctly handled in the test client. I'll look into that.

**Comment by miguelgrinberg** [comment]
Implemented in v3.3.1.

**Comment by niksauer** [comment]
Just came across the same issue. Here's my setup:

**setup.py**
```
socketio = SocketIO(cors_allowed_origins=CORS_ORIGIN_WHITELIST)

@socketio.on("connect")
def on_connect():
    api_key = request.headers.get("X-API-KEY", None)

    if api_key is not None:
        return api_key == API_KEY
    else:
        try:
            verify_jwt_in_request()
        except JWTExtendedException:
            return False


@socketio.on("message")
def on_message(msg):
    log.info(msg)
```

**test.py**
```
socket_client = socketio.test_client(self.app,
                                        flask_test_client=self.client)

socket_client.send("hello")

log.info(socket_client.is_connected())
```

The logs make it pretty clear that the server doesn't accept any message but the client continues to believe it's connected and doesn't encounter any errors while sending:

```
INFO:socketio.server:received event "message" from 72556c185ed8488290ce594694a0f334 [/]
WARNING:socketio.server:72556c185ed8488290ce594694a0f334 is not connected to namespace /
INFO:/app/src/app/tests/test_security.py:True
```

**Comment by miguelgrinberg** [comment]
This is already fixed, but somehow I forgot to cut a release with this fix. I just pushed this release, please upgrade the package to get the fix.

**Comment by niksauer** [comment]
Works like a charm. Thanks a lot!
