### ISSUE TITLE
sending message to certain user ?

### ISSUE THREAD

**Issue by rupesh2017** [miguelgrinberg/Flask-SocketIO#773]
I have 3 tab open ,

(index.html has 1 user name , 1 message input tag)
when i am running code in console for each tab socket.id . 

when using this , it transmit to all tab
 **emit("announce text",{"selection":selection,"user":user},broadcast=True)**

now i want to transmit message only b/w 1 and 3rd tab

i tried    to get socket.id and use it but does not work? 

**emit("announce text",{"selection":selection,"user":user},socket.id)**

but does not work?
https://gist.github.com/rupesh2017/1551c56e39759b412624f0202073b931

https://gist.github.com/rupesh2017/9590be8621b2899caed70a534a00b1f1

is room and channel same or channel and namespace same thing.
i think channel and namespace is same and a channel.
if channel does group what is further need of room ?

**Comment by miguelgrinberg** [comment]
You need to pass `room=sid` in your emit call, where `sid` is the value of `request.sid` for the target user.

**Comment by rupesh2017** [comment]
thanks it worked.
