### ISSUE TITLE
Is there any API to disconnect the client from the server?

### ISSUE THREAD

**Issue by swathins079** [miguelgrinberg/Flask-SocketIO#774]
Hi Miguel,

I have a use case in which the server disconnects the client. The server needs to disconnect individual clients. Is there any API that can do this?

Thanks,
Swathin

**Comment by miguelgrinberg** [comment]
Officially you can only disconnect a client in the context of an event sent by that client. There is no way to disconnect a random client for who you know the `sid`.

Unofficially, you can look at how the above disconnect is implemented and you'll find an easy way to disconnect any client by their `sid`.
