### ISSUE TITLE
How to write handle for any type of message?

### ISSUE THREAD

**Issue by ragymorkos** [miguelgrinberg/Flask-SocketIO#775]
Hey Miguel, first off thanks a bunch for your work on the Flask SocketIO module. It's proven invaluable!

My question is fairly simple but I haven't found it in the documentation or the issues that were already started on Github. I want to write an event handler that would be the one activated when any message comes in. The reason for doing that is if the message header is unsupported I want to do some error catching or send an error message to the client among other things.

Right now the only non-custom methods I can see would use `@socketio.on('message')` and `@socketio.on('json')` but these ones are for messages with payload of string or json blob, respectively. Is there a handler name for messages with payload of _any_ type? For example, floats, lists, dictionaries, etc.? If there isn't, can you recommend how I can go about implementing this? I basically need to catch any incoming message then decide if it's one I pre-defined, do error testing, then address it.

Thanks in advance, Miguel, your work is amazing!

**Comment by miguelgrinberg** [comment]
There are no pre-defined messages other than the two that you mentioned.

The socket.io protocol is designed around the pub/sub concept. The idea is that one party subscribes to receive certain events from the other by registering an event handler, but sending an event does not imply that the other side should be listening to it.

There is currently no direct way to implement a catch-all event handler, but I have considered adding that, you are not the first to ask about it.

**Comment by ragymorkos** [comment]
Ok, for now, I'll just try to stringify all the messages and use the `@socketio.on('message')` handler. Thanks Miguel!
