### ISSUE TITLE
what's the return value of emit?

### ISSUE THREAD

**Issue by swathins079** [miguelgrinberg/Flask-SocketIO#777]
Hi Miguel,

I am getting "None" as the return value of emit. Is it correct or is it like emit will return "None" for success and some integer in case of error.

Regards,
Swathin

**Comment by miguelgrinberg** [comment]
Emit does not have a return value. The operation is asynchronous, so at the time the emit function returns back to you it is still unknown if the operation will succeed or not.

**Comment by swathins079** [comment]
I have one more doubt, then how will I synchronize the events? say I have a rest api in which i will call the websocket client but the return (success or failure) will be in another event say "response", is there any way to synchronize this events and send the output in the same rest api call?

Thanks,
Swathin

**Comment by miguelgrinberg** [comment]
@swathins079 I don't understand why you are mixing HTTP/REST with Socket.IO. What's the benefit? If you need blocking requests and responses why not stick to HTTP?

If you want more details, the `emit()` accepts a `callback` argument. If you pass a function or callable there, that will be invoked after the client acknowledges the event. You may want to consult the JavaScript socket.io documentation to have a better idea of how callbacks work.

**Comment by swathins079** [comment]
Thanks, Miguel. I will make use of the callback that the `emit()` is providing.
