### ISSUE TITLE
does room need event function in JavaScript file

### ISSUE THREAD

**Issue by rupesh2017** [miguelgrinberg/Flask-SocketIO#779]
```python
import os
import requests

from flask import Flask,jsonify,render_template,request
from flask_socketio import SocketIO,emit,join_room,leave_room

from werkzeug import secure_filename



app = Flask(__name__)
app.config["SECRET_KEY"] = os.getenv("SECRET_KEY")
socketio=SocketIO(app)

#we don't need userlist or roomlist to maintain list of user within a room 


@app.route("/")
def index():
    return render_template("index.html")


    
@socketio.on('join')
def on_join(data):
    username = data['user']
    room = data['room']
    join_room(room)
    send(username + ' has entered the room.', room=room)

@socketio.on('leave')
def on_leave(data):
    username = data['user']
    room = data['room']
    leave_room(room)
    send(username + ' has left the room.', room=room)
```
    
#since there is no emit function to generate event so do we do not create event function in javascript file     

    

#here is javaScript file
https://gist.github.com/rupesh2017/29d0bcf165e0c1a39338717e323e7222

#here is html
https://gist.github.com/rupesh2017/b15c237986086e101e37f6730d11ad43

#**write now , no output is displayed on index.html**

#is emit () not used with room like private chat or broadcast

**Comment by chenyuan53618** [comment]
emit() *uses* rooms. By default, every connection has its own room whose room name is 'session id'. If not specified, emit will use this room.

**Comment by rupesh2017** [comment]
i have posted javascript file , and the socketio code as in documentation but it does not seem to work

**Comment by rupesh2017** [comment]
document.addEventListener('DOMContentLoaded',()=>{
    var socket = io.connect(location.protocol + '//' + document.domain + ':' + location.port);

    socket.on('connect',()=>{
        document.querySelector('#submit').onclick= ()=>{
        
         const user = document.querySelector('#user').value;
         const room = document.querySelector('#room').value;
          socket.emit('join',{'user':user,'room':room});
    
          return false;
        
        };

        
    
});




import os
import requests

from flask import Flask,jsonify,render_template,request
from flask_socketio import SocketIO,emit,join_room,leave_room

from werkzeug import secure_filename



app = Flask(__name__)
app.config["SECRET_KEY"] = os.getenv("SECRET_KEY")
socketio=SocketIO(app)

#we don't need userlist or roomlist to maintain list of user within a room 


@app.route("/")
def index():
    return render_template("index.html")


    
@socketio.on('join')
def on_join(data):
    username = data['user']
    room = data['room']
    join_room(room)
    emit(username + ' has entered the room.', room=room)


 **this also does not work**

**Comment by rupesh2017** [comment]
send(username + ' has entered the room.', room=room)

display message where? 

and how to get list of user connected to room, since i don't see any global variable in example taken from 
https://flask-socketio.readthedocs.io/en/latest/#connection-events
