### ISSUE TITLE
namespace  with socketio 

### ISSUE THREAD

**Issue by rupesh2017** [miguelgrinberg/Flask-SocketIO#780]
```python
import os
import requests

from flask import Flask,jsonify,render_template,request
from flask_socketio import SocketIO,emit,join_room,leave_room

from werkzeug import secure_filename

app = Flask(__name__)
app.config["SECRET_KEY"] = os.getenv("SECRET_KEY")
socketio=SocketIO(app)

userlist ={}

@app.route("/")
def index():
    return render_template("index.html")



@socketio.on("submit text",namespace='/chat')
def text(data):
    
    selection = data["selection"]
    user = data["user"]
    userlist[user]=request.sid
    
        
    

    emit("announce text",{"selection":selection,"user":user,"userlist":userlist},broadcast=True)
```

#without namespace program was working, but with namespace it is  not
when i went to 
http://localhost:5000/chat

i got this message-
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

so what is the purpose of namespace
**#Namespaces allow a client to open multiple connections to the server that are multiplexed on a single socket.**

**Comment by miguelgrinberg** [comment]
The namespace is used with Socket.IO, it is not a URL that you can access from your browser. If you add a `/chat` namespace, you would then connect to Socket.IO using `http://localhost:5000/chat`, but this isn't a URL that you can visit directly.

**Comment by rupesh2017** [comment]
sorry but i don't understand
if that route does exist what is the meaning of  connect to Socket.IO using http://localhost:5000/chat

and please check above code
@socketio.on("submit text",namespace='/chat')
it is not working,why (message is not broadcasting)
but 

@socketio.on("submit text")
this is working

**Comment by miguelgrinberg** [comment]
SocketIO connection URLs are not regular URLs. The format is `http[s]://{server}:{port}{/namespace}`. The Socket.IO client takes this URL, removes the namespace and adds `/socket.io` and issues a connection to that URL. This is probably more than you wanted to know, but I mention it so that you don't continue to see the Socket.IO connection URL as a standard URL.

**Comment by rupesh2017** [comment]
in case of default too  / is replaced by /socket.io
and no matter what the namespace it will mean same thing right.

**Comment by rupesh2017** [comment]
https://blog.miguelgrinberg.com/post/easy-websockets-with-flask-and-gevent

@socketio.on('my broadcast event', namespace='/test')
def test_message(message):
    emit('my response', {'data': message['data']}, broadcast=True)

your code is working .
why mine

@socketio.on("submit text",namespace='/chat')
def text(data):
    
    selection = data["selection"]
    user = data["user"]
    userlist[user]=request.sid
    
        
    

    emit("announce text",{"selection":selection,"user":user,"userlist":userlist},broadcast=True)


is not
