### ISSUE TITLE
example of sending binary data using socketio

### ISSUE THREAD

**Issue by rupesh2017** [miguelgrinberg/Flask-SocketIO#781]
can we send any kind of data (image, PDF, audio,video ) any size
please give one generic example that explain how to send file on socket

**Comment by miguelgrinberg** [comment]
[this example app](https://github.com/miguelgrinberg/socketio-examples/tree/master/audio) records audio in the browser and then sends it to the server in binary chunks.

**Comment by rupesh2017** [comment]
send other file like image , pdf or other file using socketio

**Comment by rupesh2017** [comment]
send image , pdf , any type of file  using socketio

**Comment by rupesh2017** [comment]
how to send local file stored on disk ( image , pdf , epub, mobi ) to chat
should i convert them to blob , arraybuffer , is there any documentation

**Comment by miguelgrinberg** [comment]
This depends on the client that you are using. I assume you want to do this through the JavaScript client? You can emit ArrayBuffer or Blob, both are received as a bytes object in the server.

**Comment by rupesh2017** [comment]
document.addEventListener('DOMContentLoaded',()=>{
    var socket = io.connect(location.protocol + '//' + document.domain + ':' + location.port);

    socket.on('connect',()=>{
        document.querySelector('#submit-user').onclick= ()=>{
         const user = document.querySelector('#user').value;
        
          socket.emit('submit user',{'user':user});
          return false;       
        };
    
            document.querySelector('#myfiles').onchange=function(){
                var file = document.querySelector('#myfiles').files[0];
                var file_type = "text/plain";
                var myblob =  new Blob(file);
    
                if(file.type.match(file_type))
                {
                    socket.emit('submit file',{'selection':myblob,'senduser':senduser});
                }
                else
                {
                    socket.emit('submit file',{'selection':'file not supported','senduser':senduser});
                }    
            }        
    });

    socket.on('announce user',(data)=>{
        const option = document.createElement('option');
        
        console.log(data.user)

       option.innerHTML=`${data.user}`;

        console.log(data.userlist) 
        
        document.querySelector('#add-user').append(option);

    });


    socket.on('annonce file',(data)=>{
        const div = document.createElement('div');
        var reader = new FileReader();
        reader.addEventListener('loadend',function(){

        div.innerHTML = reader.result;

        });
        reader.readAsText(file);  
    })     
});

# Uncaught TypeError: Failed to construct 'Blob': Iterator getter is not callable.

**Comment by rupesh2017** [comment]
when i am sending blob to server i am print content directly to cmd
but when i am sending it back to client using emit() it is converted to ArrayBuffer(2563)

[[Int8Array]]
:
Int8Array(2563) [100, 105, 115, 116, 114, 105, 98, 117, 116, 105, 111, 110, 32, 118, 115, 32, 118, 97, 114, 97, 98, 108, 105, 116, 121, 32, 32, 111, 114, 32, 115, 116, 97, 110, 100, 97, 114, 100, 32, 100, 101, 118, 105, 97, 116, 105, 111, 110, 13, 10, 13, 10, 13, 10, 115, 99, 97, 108, 101, 32, 111, 102, 32, 115, 99, 97, 116, 116, 101, 114, 32, 112, 108, 111, 116, 13, 10, 108, 105, 110, 110, 101, 114, 32, 112, 97, 116, 116, 101, 114, 32, 111, 102, 32, 108, 105, 110, 101, 32, 105, …]

[[Uint8Array]]
:
Uint8Array(2563) [100, 105, 115, 116, 114, 105, 98, 117, 116, 105, 111, 110, 32, 118, 115, 32, 118, 97, 114, 97, 98, 108, 105, 116, 121, 32, 32, 111, 114, 32, 115, 116, 97, 110, 100, 97, 114, 100, 32, 100, 101, 118, 105, 97, 116, 105, 111, 110, 13, 10, 13, 10, 13, 10, 115, 99, 97, 108, 101, 32, 111, 102, 32, 115, 99, 97, 116, 116, 101, 114, 32, 112, 108, 111, 116, 13, 10, 108, 105, 110, 110, 101, 114, 32, 112, 97, 116, 116, 101, 114, 32, 111, 102, 32, 108, 105, 110, 101, 32, 105, …]
byteLength
:
(...)

how to deal with this

**Comment by miguelgrinberg** [comment]
This is really outside of the server's control. There is only one way to send binary packets, each client and each server decide how to represent those binary payloads. In the server, they are presented as bytes.
