### ISSUE TITLE
Issue while running the app second time!!

### ISSUE THREAD

**Issue by nitin-sharma5** [miguelgrinberg/Flask-SocketIO#783]
Seems a strange issue -
1.I replicated your app.py module and it ran successfully. But, surprisingly, it got stuck on the index.html page for the second time. That is, I stopped the server and then ran it again and there were just polling requests in the logs, but a static index.html page with no output from the server.

2. Also, I had a question for understanding purposes, that if i am loading a web page(say, index.html) and on a button click, i move to some other webpage and on this second webpage, i create a websocket connection on a button click. is it possible? are websockets created only on webpage load? or can be created on any event/function call in my HTML script?

**Comment by miguelgrinberg** [comment]
Regarding #1, I don’t really understand what you are testing. It would be useful to see the output that you get on your console to help me understand.

On #2, you can create a connection by calling a JavaScript function, so you can do this as a response to any event that occurs in your web page. You can do it on load, on button click, mouse hover, etc. Doesn’t really matter. The connection will break as soon as you click on a link that takes you to another page, though.

**Comment by nitin-sharma5** [comment]
Thanks for your reply about #2.
about #1. I managed to correct my issue and it works. Sorry for the trouble. 
At the moment, The output I get in my logs is - 

 * Debugger PIN: 888-904-628
149.204.107.26 - - [2018-09-06 13:10:25] "GET / HTTP/1.1" 200 6003 0.016577
149.204.107.26 - - [2018-09-06 13:10:25] "GET /socket.io/?EIO=3&transport=polling&t=1536232225652-0 HTTP/1.1" 200 345 0.001408
149.204.107.26 - - [2018-09-06 13:10:25] "GET /favicon.ico HTTP/1.1" 404 342 0.002085
149.204.107.26 - - [2018-09-06 13:10:25] "POST /socket.io/?EIO=3&transport=polling&t=1536232225866-1&sid=23c4a2d9028044ecbbe84b438578bcfc HTTP/1.1" 200 219 0.002390
149.204.107.26 - - [2018-09-06 13:10:25] "GET /socket.io/?EIO=3&transport=polling&t=1536232225866-2&sid=23c4a2d9028044ecbbe84b438578bcfc HTTP/1.1" 200 256 0.000413
149.204.107.26 - - [2018-09-06 13:10:26] "POST /socket.io/?EIO=3&transport=polling&t=1536232226085-3&sid=23c4a2d9028044ecbbe84b438578bcfc HTTP/1.1" 200 219 0.002078
149.204.107.26 - - [2018-09-06 13:10:26] "GET /socket.io/?EIO=3&transport=polling&t=1536232226101-4&sid=23c4a2d9028044ecbbe84b438578bcfc HTTP/1.1" 200 251 0.000383
149.204.107.26 - - [2018-09-06 13:10:26] "POST /socket.io/?EIO=3&transport=polling&t=1536232226655-6&sid=23c4a2d9028044ecbbe84b438578bcfc HTTP/1.1" 200 219 0.002148
149.204.107.26 - - [2018-09-06 13:10:26] "GET /socket.io/?EIO=3&transport=polling&t=1536232226316-5&sid=23c4a2d9028044ecbbe84b438578bcfc HTTP/1.1" 200 216 0.342659
149.204.107.26 - - [2018-09-06 13:10:27] "POST /socket.io/?EIO=3&transport=polling&t=1536232227655-8&sid=23c4a2d9028044ecbbe84b438578bcfc HTTP/1.1" 200 219 0.002362
149.204.107.26 - - [2018-09-06 13:10:27] "GET /socket.io/?EIO=3&transport=polling&t=1536232226882-7&sid=23c4a2d9028044ecbbe84b438578bcfc HTTP/1.1" 200 216 0.773505
149.204.107.26 - - [2018-09-06 13:10:28] "POST /socket.io/?EIO=3&transport=polling&t=1536232228667-10&sid=23c4a2d9028044ecbbe84b438578bcfc HTTP/1.1" 200 219 0.002085
149.204.107.26 - - [2018-09-06 13:10:28] "GET /socket.io/?EIO=3&transport=polling&t=1536232227875-9&sid=23c4a2d9028044ecbbe84b438578bcfc HTTP/1.1" 200 216 0.790556
149.204.107.26 - - [2018-09-06 13:10:29] "POST /socket.io/?EIO=3&transport=polling&t=1536232229668-12&sid=23c4a2d9028044ecbbe84b438578bcfc HTTP/1.1" 200 219 0.002062
149.204.107.26 - - [2018-09-06 13:10:29] "GET /socket.io/?EIO=3&transport=polling&t=1536232228885-11&sid=23c4a2d9028044ecbbe84b438578bcfc HTTP/1.1" 200 216 0.776452

Continuous, Get and Post requests. It seems socketio downgrades to polling and doesnt use web sockets. is this correct?? how do i make it to use websockets?

**Comment by nitin-sharma5** [comment]
Thanks again Miguel !! Found the answer to the above in your previous issue : https://github.com/miguelgrinberg/Flask-SocketIO/issues/699 !
