### ISSUE TITLE
disconnect event is emitted longer after  user is disconnected

### ISSUE THREAD

**Issue by rupesh2017** [miguelgrinberg/Flask-SocketIO#785]
text is here from Connected at Fri Sep 07 2018 20:06:00 GMT+0530 (India Standard Time)
text is here from Disconnected at Fri Sep 07 2018 20:07:00 GMT+0530 (India Standard Time)

from flask import Flask, render_template
from flask_socketio import SocketIO, emit
    
app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app)

@app.route('/')
def index():
    return render_template('index.html')

@socketio.on('connect')
def test_connect():
    emit('my response', {'data': 'Connected'},broadcast=True)

@socketio.on('disconnect')
def test_disconnect():
     emit('my response', {'data': 'Disconnected'}, broadcast=True)
    

tab was opened and closed after 5 sec but reply was 1 minute delay.

**Comment by miguelgrinberg** [comment]
The disconnect event for clients that use long-polling takes about a minute to be issued. This is because the server waits for a while until it declares the client as gone. If the client is connected over WebSocket, the disconnection happens immediately.

**Comment by rupesh2017** [comment]
I am using socketio then why  1 minute wait is there during disconnect

**Comment by miguelgrinberg** [comment]
Socket.IO can work with long-polling and with WebSocket. Your client must be connecting with long-polling. See the documentation to make sure you are configured in way that supports WebSocket.
