### ISSUE TITLE
Issue with start_background_task when using eventlet or gevent, i'm using gunicorn3 

### ISSUE THREAD

**Issue by leond08** [miguelgrinberg/Flask-SocketIO#787]
**[2018-09-10 22:12:54 +0800] [14598] [CRITICAL] WORKER TIMEOUT (pid:14605)
[2018-09-10 22:12:54 +0800] [14605] [INFO] Worker exiting (pid: 14605)
[2018-09-10 22:12:55 +0800] [14709] [INFO] Booting worker with pid: 14709**

I initiate the background task after a user clicked the button
My background task function is to listen to an event,
after clicking the "DONE" button the background task must stop
then send an emit message to all the users
it works if i use async_mode="threading" but when i use eventlet and gevent i got an error..

**Comment by miguelgrinberg** [comment]
What command are you using to start the gunicorn server?

**Comment by leond08** [comment]
@miguelgrinberg 

I'm using this command 
gunicorn3 -k eventlet -w 2 -b 0.0.0.0:5000 main:app
same with gevent

**Comment by miguelgrinberg** [comment]
First thing is that you cannot use multiple workers with gunicorn when using eventlet or gevent. See if switching to `-w 1` helps.

The other potential problem that you may have is that some of the things that you do in your background thread are blocking. Eventlet and gevent provide non-blocking alternatives for many functions in the Python standard library, but not for everything, so if you happen to be using one of the unsupported functions then it's a problem.
