### ISSUE TITLE
webrtc  in flask with socketio 

### ISSUE THREAD

**Issue by rupesh2017** [miguelgrinberg/Flask-SocketIO#788]
import os
import requests

from flask import Flask,jsonify,render_template,request
from flask_socketio import SocketIO,emit,join_room,leave_room,send

from werkzeug import secure_filename

app = Flask(__name__)
app.config["SECRET_KEY"] = os.getenv("SECRET_KEY")
socketio=SocketIO(app)

@app.route("/")
def index():
    return render_template("index.html")

#1st function

#2nd function

@socketio.on('message')
def on_message():
    emit('message',{'message':message},broadcast=True)

numClients = 0

#3rd function

@socketio.on('join')
def on_join(data):
    username = data['user']
    room = data['room']
    if(numClients == 0):
        join_room(room)
        emit('chat',{'username':username},room=room)
    elif(numClients == 1):
        join_room(room)
        emit('chat',{'username':username},room=room)
    else:
        
        emit('full',room=room)
    
    numClients =numClients + 1
    
    

@socketio.on('ipaddr')
def ipaddr():
   ifaces = os.networkInterfaces();
   for  dev in ifaces:
       #error here i tried to comment this website  is run
       **if (details.family === 'IPv4' && details.address !== '127.0.0.1'):**
           emit('ipaddr',{'details.address':details.address})

# https://github.com/googlecodelabs/webrtc-web/blob/master/step-04/index.js
this code is written in nodejs i am trying to change to python

# is the python code corresponding to above link correct

this is main.js code
# https://github.com/googlecodelabs/webrtc-web/blob/master/step-04/js/main.js

'use strict';

var isInitiator;

window.room = prompt("Enter room name:");

var socket = io.connect(location.protocol + '//' + document.domain + ':' + location.port);

if (room !== "") {
  console.log('Message from client: Asking to join room ' + room);
  socket.emit('create or join', room);
}

socket.on('created', function(room, clientId) {
  isInitiator = true;
});

socket.on('full', function(room) {
  console.log('Message from client: Room ' + room + ' is full :^(');
});

socket.on('ipaddr', function(ipaddr) {
  console.log('Message from client: Server IP address is ' + ipaddr);
});

socket.on('joined', function(room, clientId) {
  isInitiator = false;
});

socket.on('log', function(array) {
  console.log.apply(console, array);
});

    
# if any documentation or link is there please provide.

**Comment by miguelgrinberg** [comment]
I'm not sure what you are asking. I'm not familiar with any of this, so I don't think I can help you. Sorry.
