### ISSUE TITLE
socket.emit from background task does not work when arg is a multiprocessing.Value

### ISSUE THREAD

**Issue by CAReeser** [miguelgrinberg/Flask-SocketIO#789]
I am trying to pass a multiprocessing Value into a thread that contains a socketio.emit. When I remove the Value as an arg, the emit works. When I pass the Value as an arg, the emit fails. I know the Value is being received in the background task as I print that out.  I have tried all the Miguel suggestions for async threads, monkey patch etc.

So, the emit in a thread does not work with a passed in Value?
``
```
import eventlet
eventlet.monkey_patch()

app = Flask(__name__)
socketio = SocketIO(app)

++++++++++++++++++++++++++++++++++++

def handletimemsg(mp_et_time):  #thread
    utc_et = 0.0
    while True:
        try:
            utc_et = mp_et_time.val
            print ('in handletimemsg ' + str(utc_et))
            if  isinstance(utc_et, float) and utc_et != 0.0:
                local_et = utc_et - float(time.timezone) 
                sutc_date = spice.et2utc(utc_et,'C',0) + ' UTC' 
                slocal_date = spice.et2utc(local_et,'C',0) + ' Local'
                print (slocal_date + '  ' + sutc_date)
                socketio.emit('msg_time', {'utc_date': sutc_date, 'local_date': slocal_date})  
        except: 
            pass
        eventlet.sleep(5)
    return True
+++++++++++++++++++++++++++++++++++++++++++++++++++

if __name__ == '__main__':
        mp_et_time = Value('d',0.0)
    mp_cur_pos = Array('i',25)
    t=socketio.start_background_task(handletimemsg, mp_et_time)         
    if t.isAlive():
        print ('Thread is alive: ') 
    else: 
        print ('Thread is not alive')

Results+++++++++++++++++++

in handletimemsg 7.0
2000 JAN 01 06:59:03 Local  2000 JAN 01 11:59:03 UTC
in handletimemsg 8.0
2000 JAN 01 06:59:04 Local  2000 JAN 01 11:59:04 UTC
```

**Comment by miguelgrinberg** [comment]
Multiprocessing is not compatible with Eventlet. Not sure specifically about `Value`, but I bet that is the problem.

Do you get an error? It would be useful to see what happens when you pass the `Value` instance into the other thread.

**Comment by CAReeser** [comment]
I would like to use mp.Value;  should I be using Gevent or something else?  If not, I will use a pipe for the Value as it worked before but pipe was extremely slow passing an mp.Array.  

I received no errors. If you will tell me what to enable to view the errors I will attempt it and send you results.  I have been using mp with Eventlet for several months with only one other issue:  It would not let me read from different pyserial usb ports in multiple threads. 

Interesting, but frustrating trade-offs in this game.... rewarding in the end.

Cliff

**Comment by CAReeser** [comment]
Using an mp.Array works with socketio.emit() in a thread, whereas mp.Value does not.
Interesting.  I'll close this thread. Thanks.
Cliff
