### ISSUE TITLE
Flask Socket IO server not detecting changes to file

### ISSUE THREAD

**Issue by holistudio** [miguelgrinberg/Flask-SocketIO#790]
Changes made to the main application.py file don't seem to be detected by the server after I save the file, even though debug mode is on. The only way I've been able to see changes is by exiting the server and restarting with flask run

Here is the code for application.py:

```
import os
import requests

from flask import Flask, session, render_template, request, url_for, flash, redirect, jsonify
from flask_socketio import SocketIO, emit

app = Flask(__name__)
app.config["SECRET_KEY"] = 'secret!'
socketio = SocketIO(app)

@app.route("/")
def index():
    print('hello world')
    return 'hello!'

if __name__ == '__main__':
    socketio.run(app, debug=True)
```

And here's the command line/terminal:
```
flask run
 * Serving Flask-SocketIO app "application.py"
 * Forcing debug mode on
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 156-884-244
(3824) wsgi starting up on http://127.0.0.1:5000
(3824) accepted ('127.0.0.1', 50569)
127.0.0.1 - - [10/Sep/2018 20:07:40] "GET /socket.io/?EIO=3&transport=polling&t=1536624459432-5 HTTP/1.1" 200 381 0.000000
(3824) accepted ('127.0.0.1', 50571)
127.0.0.1 - - [10/Sep/2018 20:07:40] "GET /socket.io/?EIO=3&transport=polling&t=1536624460314-6&sid=79eb8e587f664e3383c946bb046717ca HTTP/1.1" 200 215 0.000000
(3824) accepted ('127.0.0.1', 50568)
127.0.0.1 - - [10/Sep/2018 20:07:44] "GET /socket.io/?EIO=3&transport=websocket&sid=79eb8e587f664e3383c946bb046717ca HTTP/1.1" 200 0 4.610168
hello world
127.0.0.1 - - [10/Sep/2018 20:07:44] "GET / HTTP/1.1" 200 152 0.000000
hello world
127.0.0.1 - - [10/Sep/2018 20:07:58] "GET / HTTP/1.1" 200 152 0.000000
hello world
127.0.0.1 - - [10/Sep/2018 20:08:06] "GET / HTTP/1.1" 200 152 0.000000
wsgi exiting
(3824) wsgi exited, is_accepting=True
```

Those `hello world`'s in command line show up every time I change the text in `print('hello world')` and refresh the browser. Regardless of what I change it to, I always get the original version of the code's print argument.

When I worked on a previous project with just Flask, I notice the command line would detect a file has been changed after saving. I don't see any similar signs with Flask-SocketIO. Any guidance would be appreciated.

**Comment by miguelgrinberg** [comment]
Are you using eventlet or gevent by any chance? The Flask reloader is a complex subsystem that doesn't work well with async frameworks. You may get it to work better if you apply the monkey patching that these two frameworks provide for the Python standard library.

**Comment by holistudio** [comment]
thanks for getting back to me. yes I'm using eventlet. Do you mind elaborating on monkey patching the standard library? I've read the eventlet documentation on this but still can't get automatic updates to work. Is it just a matter of adding `import eventlet` and `eventlet.monkey_patch()` to the top of the application python file?

**Comment by miguelgrinberg** [comment]
Yes, that's all that is required to do the monkey patching. If that does not work, then you can disable eventlet when you run the reloader. You can do that by adding `async_mode='threading'` to your `SocketIO` class constructor. You will not have websocket, but the reloader will work just fine.

**Comment by holistudio** [comment]
Monkey patching doesn't seem to work. For clarity, the application.py file is now: 
```
import os
import requests
import eventlet
eventlet.monkey_patch()

from flask import Flask, session, render_template, request, url_for, flash, redirect, jsonify
from flask_socketio import SocketIO, emit

app = Flask(__name__)
app.config["SECRET_KEY"] = 'secret!'
socketio = SocketIO(app)

@app.route("/")
def index():
    print('hello world')
    return 'hello!'

if __name__ == '__main__':
    socketio.run(app, debug=True)
```

If I change SocketIO constructor line to `socketio = SocketIO(app, async_mode='threading')` then when I run flask, I get the error `WebSocket transport not available. Install eventlet or gevent and gevent-websocket for improved performance.` and can't test out the code anyway.

Would using gevent and gevent-websocket be a better alternative? Or would I run into the same issues anyway?

Overall, I'm not concerned with functionality. It's just getting a bit tedious to restart the server every time I make changes to the code. If you have any suggestions on making that workflow smoother, I'd really appreciate it.

**Comment by miguelgrinberg** [comment]
The "websocket transport not available" message is not an error, it is just a warning. You should be able to use the library in long-polling mode, and the reloader should work fine in that mode.

You can try gevent, the monkey patchers in these two frameworks are not identical, maybe gevent provides better support for the functions that the reloader needs.

I'll investigate if there is anything that can be done when I have some time, but this hasn't been a priority because running in threading mode is a decent workaround.

**Comment by holistudio** [comment]
I'm not sure what you mean by using the library in long-polling mode. After I get the warning message "WebSocket transport not available", flask stops running. 
```
flask run
 * Serving Flask-SocketIO app "application.py"
 * Forcing debug mode on
 * Restarting with stat
WebSocket transport not available. Install eventlet or gevent and gevent-websocket for improved performance.
```
What additional code do I need to include to get flask to run in threading mode?

**Comment by miguelgrinberg** [comment]
It should not stop running, the server should start and run normally, but without websocket support. Did you remove all the eventlet stuff, including the monkey patching?

**Comment by miguelgrinberg** [comment]
I've been testing this today a bit and have interesting findings. The problem appears to occur when starting the application via the `flask run` command. The reloader works fine when running via `socketio.run()`, or in other words, when executing your main application script directly. Give that a try and let me know if it also works for you.

I'll keep this issue open to track the problem with `flask run`.

**Comment by holistudio** [comment]
Thanks Miguel. If I run with `python application.py` instead of flask run, everything automatically reloads after saving file changes. SocketIO's async_mode doesn't seem to matter in that case. The problem does seem related to using `flask run`. This does resolve my issues with seeing the effect file changes, but let me know what you find.

**Comment by miguelgrinberg** [comment]
@holistudio this is now fixed, you should be able to use the reloader through `flask run` as well.

**Comment by ldariva** [comment]
Hi Miguel. I know that the topic is closed but I was facing this problems and tested this solution of starting the application using `python app.py` instead of `flask run` and the automatic reload just works with the first option. I am using the latest version of flask-socketio module.

**Comment by miguelgrinberg** [comment]
@ldariva this issue is very old, it isn't relevant anymore. Using flask run to start a Socket.IO server is currently not a supported option. Always use socketio.run.
