### ISSUE TITLE
Create lifecycle connections.

### ISSUE THREAD

**Issue by bruno-siqueira-simples** [miguelgrinberg/Flask-SocketIO#791]
is it possible to create lifecycle connections? for example, a connection lasts only 30 seconds.

**Comment by miguelgrinberg** [comment]
I don't understand what you mean by "lifecycle". Can you explain?

**Comment by bruno-siqueira-simples** [comment]
For example, when a connection is created, this connection will have a life time of thirty seconds or one minute

**Comment by miguelgrinberg** [comment]
What would be the purpose of such a short connection? The client can connect and then disconnect after any amount of time, but I don't see why this is useful.
