### ISSUE TITLE
socket with route to redirect message to another page

### ISSUE THREAD

**Issue by rupesh2017** [miguelgrinberg/Flask-SocketIO#792]
import os
import requests

from flask import Flask,jsonify,render_template,request
from flask_socketio import SocketIO,emit,join_room,leave_room,send

from werkzeug import secure_filename

app = Flask(__name__)
app.config["SECRET_KEY"] = os.getenv("SECRET_KEY")
socketio=SocketIO(app)

@app.route("/")
def index():
    return render_template("index.html")

@app.route("/chat")    
@socketio.on('join')
def on_join(data):
    username = data['user']
    room = data['room']
    join_room(room)
    emit('chat',{'username':username},room=room)
    return render_template("chat.html")
    

# I have 2 html ( one user name and room name to join) and other for message(chat.html)
# when I **click on join** on index.html i like to _go to chat route_ with  message emitted

but it is not redirecting

**Comment by miguelgrinberg** [comment]
You can't have the same function decorated as a route and a socket event. Use separate functions for your HTTP and Socket.IO handlers please.

**Comment by rupesh2017** [comment]
let say i have 2 route ( / ) and other (/main) how to pass socketio emit to  (/main) right now it it emitted to ( 
 ( / ) route

**Comment by miguelgrinberg** [comment]
I don't understand what you are saying. If the clients emits, then you get an event in the server, none of your HTTP routes are invoked. The socket.io events are completely separate from the HTTP routes.

**Comment by rupesh2017** [comment]
when i have  one page in application  i get emit on http://localhost:5000

but when i have 2 page and i want to send emit to desired page( 1st page for login ) (2nd page for chat)
then how message will reach second page.

**Comment by miguelgrinberg** [comment]
It doesn't work like that. A Socket.IO connection does not persist across pages, and you can't send Socket.IO events across pages. In a chat application typically the login page does not use Socket.IO. After the user logs in, a redirect sends him/her to the chat page, where the Socket.IO connection is established.

**Comment by rupesh2017** [comment]
yes login page does not use socketio , other page does so _**how to do  establish socketio on chat page.**_
do we need to change  something here

    var socket = io.connect('http://' + document.domain + ':' + location.port);

**Comment by miguelgrinberg** [comment]
Depends on your needs I guess, but that connection statement looks fine to me.

**Comment by rupesh2017** [comment]
say i want message at /chat (2nd page)  then what need to be changed in it
so that all message are being emit at chat.html not at index.html

**Comment by rupesh2017** [comment]
<!DOCTYPE html>
<html>
    <head>
        <title>Login</title>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js"></script>
   
   <script>
        document.addEventListener('DOMContentLoaded',()=>{

            var socket = io.connect(location.protocol + '//' + document.domain + ':' + location.port);

            socket.on('connect',()=>{
               document.querySelector('#submit').onclick =() =>{
                const user= document.querySelector('#user').value;
                const room = document.querySelector('#room').value;
                socket.emit('join',{'user':user,'room':room});
                return false;
               };

            });

        });
        
    </script>
        
    </head>
    <body>
    <form id="new-task" action="{{ url_for('chat') }}" method="post">
        <input type="text" autocomplete="off" autofocus id="user" placeholder="username"> 
        <input type="text" autocomplete="off" autofocus id="room" placeholder="room">
        <input type="submit" id="submit" value="join">     
    </form> 
    </body>
</html>


# what i am trying to do is on click submit , user join room as well go to another route , but this is not working

**Comment by rupesh2017** [comment]
<!DOCTYPE html>
    <html>
    <head>
        <title>Login</title>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js"> 
     </script>

       <script>
        document.addEventListener('DOMContentLoaded',()=>{

            var socket = io.connect(location.protocol + '//' + document.domain + ':' + location.port);

            socket.on('connect',()=>{
                console.log('connected');
               document.querySelector('#submit').onclick =() =>{
                const user= document.querySelector('#user').value;
                const room = document.querySelector('#room').value;
                socket.emit('join',{'user':user,'room':room});
                console.log('emitted');
                return false;
               };

            });

        });

      </script>

      </head>
      <body>
      <form id="new-task" action="{{ url_for('chat') }}" method="post">
        <input type="text" autocomplete="off" autofocus id="user" placeholder="username"> 
        <input type="text" autocomplete="off" autofocus id="room" placeholder="room">
        <input type="submit" id="submit" value="join">     
      </form> 
      </body>
      </html>
localhost:5000 open index.html page , when i click on submit only socketio is working but url is not being changed .

import os
import requests

from flask import Flask,jsonify,render_template,request
from flask_socketio import SocketIO,emit,join_room,leave_room,send

from werkzeug import secure_filename



app = Flask(__name__)
app.config["SECRET_KEY"] = os.getenv("SECRET_KEY")
socketio=SocketIO(app)



@app.route("/")
def index():
    return render_template("index.html")


@app.route("/chat" ,methods=["POST"])
def chat():
    print("running chat")
    return render_template("chat.html")


@socketio.on('join')
def on_join(data):
    username = data['user']
    room = data['room']
    join_room(room)
    emit('chat',{'username':username},room=room)
    print("room has been allocated")



when i did only url_for without socketio i was able to change route but now it does not seem to work. in console and cmd i am able to see socketio working but chat route is not working

**Comment by miguelgrinberg** [comment]
Please reopen if you still have this problem and can provide more details.
