### ISSUE TITLE
Emit from server (with server only sender of messages) not reaching client

### ISSUE THREAD

**Issue by Zanobos** [miguelgrinberg/Flask-SocketIO#795]
Dear Miguel,
first of all thank you very much for your awesome introduction to the flask world.

I am actually stuck with a problem I have not been yet able to overcome, so I'm here looking for wisdom (and solution, if possible!)

The problem is the following: I need the server to be the originator of messages to the webclient (basically, the client connnect/disconnect and the server streams the data).
If I use the magic function 

`socketio.emit('json', body, namespace='/api/climbs')`

inside (for example) a standard flask-annotated endpoint (in this way, the function is the non-context aware), everything works and the client receives the message.

However, if I use this function inside another thread, the client does not receive anything (I am using another thread because I am listening to messages on a RabbitMQ queue, as soon as I arrive, I send them on the websocket. I read on the docs that should exists also other integrations using multiple processes, but at the moment I am just using multiple threads).

To give you more context, the project is the following:
https://github.com/Zanobos/macloc

the interesting snippet of codes are:

- socketio connect and disconnects is at app/api/climbs (lines 84 to 98)

- the thread is at app/utils/worker (lines 59 to 84)

- a web client test is at app/doc/test_ws.html

Sorry to bother you,
have a great day,
Andrea

**Comment by Zanobos** [comment]
@miguelgrinberg I checked in this list of issues and I saw that with gevent everything emitting from a different thread is supported. It could be helpful to add that indication in the docs!
Have a great ay,
Andrea

**Comment by Zanobos** [comment]
I forgot to add that in my first try, I was using eventlet. Could that be the souce of the problem?

**Comment by miguelgrinberg** [comment]
Yes, in your case you are required to monkey patch, since you are using rabbitmq.
