### ISSUE TITLE
ws http

### ISSUE THREAD

**Issue by zhangatao** [miguelgrinberg/Flask-SocketIO#800]
Excuse me, does flask socket.io support ws protocol?

**Comment by miguelgrinberg** [comment]
Yes, but you can't use a plan websocket client, you have to use a Socket.IO client.

**Comment by zhangatao** [comment]
thank you very much 




            
            
                
                    
                            
                                
                            
                            
                                1634644550
                            
                    
                        
                            
                                    邮箱：1634644550@qq.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


On 09/25/2018 16:52, Miguel Grinberg wrote: Yes, but you can't use a plan websocket client, you have to use a Socket.IO client.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/miguelgrinberg/Flask-SocketIO","title":"miguelgrinberg/Flask-SocketIO","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/miguelgrinberg/Flask-SocketIO"}},"updates":{"snippets":[{"icon":"PERSON","message":"@miguelgrinberg in #800: Yes, but you can't use a plan websocket client, you have to use a Socket.IO client."}],"action":{"name":"View Issue","url":"https://github.com/miguelgrinberg/Flask-SocketIO/issues/800#issuecomment-424259363"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/miguelgrinberg/Flask-SocketIO/issues/800#issuecomment-424259363",
"url": "https://github.com/miguelgrinberg/Flask-SocketIO/issues/800#issuecomment-424259363",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [miguelgrinberg/Flask-SocketIO] ws http (#800)",
"sections": [
{
"text": "",
"activityTitle": "**Miguel Grinberg**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@miguelgrinberg",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"miguelgrinberg/Flask-SocketIO\",\n\"issueId\": 800,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"miguelgrinberg/Flask-SocketIO\",\n\"issueId\": 800\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/miguelgrinberg/Flask-SocketIO/issues/800#issuecomment-424259363"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 383783243\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by zhangatao** [comment]
Hello, I have some questions. “you can't use a plan websocket client”，Can you explain this sentence specifically?

**Comment by zhangatao** [comment]
Is it possible to understand this:
The server uses the async_mode:eventlet method to start the service. The client terminal implements the Socket.IO client. In this way, the ws protocol can be implemented.

**Comment by miguelgrinberg** [comment]
I didn't write that. I suggest you read the official documentation if you want to learn about Socket.IO.

**Comment by zhangatao** [comment]
Excuse me, how does flask socket.io implement the ws protocol?
eventlet is the best performant option, with support for long-polling and WebSocket transports？？？

**Comment by miguelgrinberg** [comment]
For generic information about the Socket.IO protocol I suggest you visit the official site: https://socket.io/. This project is a Python implementation of the Socket.IO server.
