### ISSUE TITLE
how can i receiver message in http request

### ISSUE THREAD

**Issue by Trick93** [miguelgrinberg/Flask-SocketIO#803]
hello！i have a question

i am using flask_restful to provide api, and use eventlet for flask-socketio

now the quesion is : when i send a http request to flask, the flask socketio would send message to client, then in the request it will sleep few seconds to wait client message, but the function on_message be called after http request finish! how can i handle it! my code like this

http requesr get:
```
from flask_restful import request, Resource
from flask_socketio import send
from lib import common
import globalvar as gl
import json
import uuid
import time

def send_to_device(msg, room):
  message = dict()
  id = str(uuid.uuid1())
  message["id"] = id
  message["cmd"] = msg
  send_data = json.dumps(message)
  send(send_data, namespace='/', room=room)
  return id

class Test(Resource):
  def get(self):
    mac = request.args.get('mac')
    msg = request.args.get('msg')
    u_id = send_to_device(msg, mac)
    result = ''
    sleep_time_count = 0
    while sleep_time_count < 3:
      print(gl.get_value(u_id))
      if gl.get_value(u_id) != None:
        result = gl.get_value(u_id)
        gl.remove_value(u_id)
        break
      time.sleep(0.1)
      sleep_time_count += 0.1
    time.sleep(3)
    if result == '':
      return common.falseReturn('', 'fail')
    else:
      return common.trueReturn(result)
```

on_message
```
def on_message(self, msg):
  try:
      if isinstance(msg,dict):
        msg = json.dumps(msg)
      current_app.logger.info(u'recv:%s' % (msg))
      message = json.loads(msg)
      msg_type = message["cmd"]
    except:
      self.send_error('unknow message!')
      return
```

main
```
from app import create_app, socketio

app = create_app("app.config")
if __name__ == "__main__":
  socketio.run(app, host='0.0.0.0')
```

__init__.py
```
from flask import Flask
from flask_socketio import SocketIO

socketio = SocketIO()

def create_app(config_name):
  app = Flask(__name__)
  app.config.from_object(config_name)

  from app.url import api_bp
  app.register_blueprint(api_bp, url_prefix='/api')

  from app.websocket.websocket import MyCustomNamespace

  socketio.init_app(app)
  socketio.on_namespace(MyCustomNamespace('/'))

  return app
```
thank you!

**Comment by miguelgrinberg** [comment]
It's really hard for me to know since I have very little details about your application and how you are running it.

Why are you mixing HTTP and Socket.IO? Doesn't it make more sense to do everything via Socket.IO events? Blocking and waiting in a HTTP route is not really a good practice anyway.

**Comment by Trick93** [comment]
Sorry for my unclear display

so i draw a picture 

![image](https://user-images.githubusercontent.com/13232291/46252075-28982c00-c496-11e8-9a9b-97671b4e5ed6.png)

my fontend want to get the device status, my operation like this:

1.fontend send http request to flask
2.in the request,flask would send message to device client by websocket and wait client return data
3.then i would return data to fontend

but i find that the message would send after http request finish,it cause i can't return data to the fontend,i think socketio is asynchronous,it can send message to client background! 

I don't know if there is a solution

thank you!!

**Comment by miguelgrinberg** [comment]
Thanks. Try using `socketio.sleep()` instead of `time.sleep()`, which is a blocking function.

**Comment by Trick93** [comment]
thanks a lot!

use `socketio.sleep()`  solve my problem! now i know `time.sleep()` would block function!

thank you again

i close this issue
