### ISSUE TITLE
Can no longer run pytest after monkey patching eventlet so socket messages can be sent from celery

### ISSUE THREAD

**Issue by dtamez** [miguelgrinberg/Flask-SocketIO#806]
Because I needed to send messages from celery I am initializing socketio as follows:
import eventlet
eventlet.monkey_patch() 
def create_app(config_name):
...
socketio.init_app(app, async_mode='eventlet', message_queue=app.config['BROKER_URL'])
...
return app

pytest used to run tests for the application but now it hangs on start.  
It seems to be stuck at:
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 347, in <genexpr>                                         
    return (item for chunk in result for item in chunk)                                                             
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 724, in next                                              
    self._cond.wait(timeout)                                                                                        
  File "/usr/lib/python3.6/threading.py", line 295, in wait                                                         
    waiter.acquire()        

Is there a known workaround for this?  Do I need to switch to a different test package?

**Comment by miguelgrinberg** [comment]
Does things work if you disable the monkey patching and don't use eventlet at all during testing? I don't think I have ever tried pytest alongside eventlet, but it is possible that there are incompatibilities.

**Comment by dtamez** [comment]
Trying to work around this by:
    if app.config['TESTING']:
        socketio.init_app(app)
    else:
        import eventlet
        eventlet.monkey_patch()
        socketio.init_app(app, async_mode='eventlet', message_queue=app.config['BROKER_URL'])

and that gets the tests to run again.  But it appears the application is no longer working correctly. 
Will update.

**Comment by dtamez** [comment]
It seems that moving the monkey patching into the create_app function is too late.  It enables the tests to run but it is too late for celery and the app to have the monkey patching take effect.  I'll see if there's some way to satisfy both conditions.

**Comment by miguelgrinberg** [comment]
Yes, you have to monkey patch very early for it to be effective. You can use a separate module to monkey patch and run the app. For example, if your current main module is called run.py, you can add another one called run_eventlet.py as follows:

```python
import eventlet
eventlet.monkey_patch()

from run import app
```

Then you need to make sure that this new run_eventlet.py module is not imported when you run the tests.

**Comment by dtamez** [comment]
cool, this worked.  I appreciate the help, the insight and the fab work you've done with flask flask-socketio and many others!

**Comment by eelkevdbos** [comment]
Alternatively, for anyone stumbling on this, the way pytest was messing with our imports, made it so that the monkey patching was done too late.

We solved it by placing a `conftest.py` in the root of our project with the same monkey_patch statement otherwise used in our app entry point.

```python
# conftest.py
import eventlet

eventlet.monkey_patch()
```

You can also use something like [pytest-eventlet](https://pypi.org/project/pytest-eventlet/) that does this by hooking into the conftest loading procedure.
