### ISSUE TITLE
[Question] Deploying socketIO in distributed environments like kubernetes

### ISSUE THREAD

**Issue by akhilputhiry** [miguelgrinberg/Flask-SocketIO#808]
I was trying to deploy my app in kubernetes. while the K8 scales up and down, it's creating problem
What I did is I monkey patched the `KombuManager` to use the same `queue` for all instances of my app. Is this is right way to solve this problem? 

```
import kombu
from socketio import KombuManager


class CustomKombuManager(KombuManager):

    def _queue(self):
        queue_name = 'flask-socketio.flask-socketio'
        return kombu.Queue(
            queue_name,
            self._exchange(),
            durable=False,
            queue_arguments={'x-expires': 300000}
        )
```

It would be nice if we can have an option to specify the queue as well

**Comment by miguelgrinberg** [comment]
Hmm. Does that even work? Each consumer has to have its own queue.

**Comment by akhilputhiry** [comment]
I didn't test it in kubernetes, how will the flask-socketio handle horizontal scaling in environments like kubernetes?

**Comment by miguelgrinberg** [comment]
Well, first of all, dynamically scaling up or down is going to generate lots of broken connections. Socket.IO is a stateful protocol that requires sticky sessions on the load balancer. Each time you add or remove a worker some connections will move and that will break those connections. The clients that are affected will reconnect, so it is not a fatal issue, but if you are constant scaling you will be disconnecting clients frequently.

Other than that there shouldn't be any issues running on Kubernetes. Why are the queues giving you problems?

**Comment by akhilputhiry** [comment]
Problem is with sticky sessions. The ingress controller I am using do not support sticky connections.

**Comment by miguelgrinberg** [comment]
Oh, the queue has nothing to do with the sticky session requirement. That's so that the same worker always handles a given client. Each worker stores data about its clients, if the requests go randomly to another worker then the client would not be recognized. If you can't do sticky sessions, then you have to use a single server.

I've done Socket.IO on Kubernetes deploying my own load balancer, BTW. Both nginx and haproxy have worked well with the proper configuration.

**Comment by akhilputhiry** [comment]
Thank you @miguelgrinberg. Closing this issue.
