### ISSUE TITLE
Using "DON'T PANIC" werkzeug traceback interpreter

### ISSUE THREAD

**Issue by eleweek** [miguelgrinberg/Flask-SocketIO#81]
It is mildly annoying to see "Internal Server Error" instead of nice web page with a stack trace.
Question: is it possible to somehow use DON'T PANIC? I would be willing to contribute if it requires not too much work.

**Comment by miguelgrinberg** [comment]
@eleweek I'm unable to reproduce this problem. I have added an intentional error to the `/` route in the example app and the Werkzeug debugger pops up just fine.

Can you share a complete example that demonstrates the problem you are seeing?

**Comment by eleweek** [comment]
I took the example app from README file and modified it a bit(removed ```socketio.on``` stuff), and added ```app.debug = True```

Here is the full code:

```
from flask import Flask, render_template
from flask.ext.socketio import SocketIO, emit

app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app)
app.debug = True

@app.route('/')
def index():
    raise Exception()
    return "test"

if __name__ == '__main__':
    socketio.run(app)
    #app.run()
```

Compare ```socketio.run(app) vs ```app.run()```.

here is the full ```pip freeze``` output:

```
Flask==0.10.1
Flask-SocketIO==0.4.3
Jinja2==2.7.3
MarkupSafe==0.23
Werkzeug==0.9.6
gevent==1.0.1
gevent-socketio==0.3.6
gevent-websocket==0.9.3
greenlet==0.4.5
itsdangerous==0.24
wsgiref==0.1.2
```

**Comment by eleweek** [comment]
Ok, I figured it out. It turns out, that werkzeug wraps ```app``` into ```DebugApplication``` in ```run_simple()```, whereas Flask-SocketIO wraps ```app``` into ```DebugApplication``` in the constructor of ```_SocketIOMiddleWare```, which gets called in the constructor of ```SocketIO```. The fix appears to be simple(move two lines from constructor to ```run```), so I made a pull-request.

**Comment by miguelgrinberg** [comment]
Thanks, I’ll look at this change, hopefully that’ll help me figure out what was going on here, as I was unable to reproduce the problem on my end.

Miguel

**Comment by eleweek** [comment]
Thank you. If you want to reproduce the problem, try my exact code above.

Here are two relevant lines.

```socketio = SocketIO(app)
app.debug = True```

If you set ```app.debug``` to ```True``` after you created ```socketio``` object, then you won't see nice traces.

**Comment by miguelgrinberg** [comment]
This should be working correctly in the 1.0 release.

**Comment by eleweek** [comment]
Hi @miguelgrinberg , the code works now. Thank you, and sorry for the delay in response
