### ISSUE TITLE
'disconnect' event is not invoking while multiple refresh/reload of a page at a time

### ISSUE THREAD

**Issue by Rakin061** [miguelgrinberg/Flask-SocketIO#811]
What I actually intend to do is to calculate the number of users who are connected with the server in real time from their browsers.  And, I didn't miss the chance to obtain the help of the self invoked functions `'connect'` and '`disconnect'` which are  automatically called from the client side which contains a socket variable with _`io.connect()`_  for implementation.

### Here's the server side code:  

```
@socketio.on('connect', namespace='/chat')
def test_connect():
    global users_connected
    users_connected = users_connected + 1
    print("A user connected to the server.....")
    stat()

@socketio.on('disconnect', namespace='/chat')
def test_disconnect():
    global users_connected
    print('A user disconnected from our server...')
    users_connected= users_connected -1
    if stack:
        stack.pop()
    stat()
```
So, that's pretty much it how I could get real time record of users currently connected to the server. Even, when user refreshes the page then first the **disconnect** event has been invoked and after that shortly **connect** event will back the user connected again! 
So, in this case, the number of users connected will be the same in aggregate. 

Problem arises when the user reloads the page numerously at a time. What I've got from the print value for both of the events that in case of numerous refreshing of the page, **connect** event for all the reloads invokes properly but few **disconnect** event has been restricted from being invoked all together.

### So, in the log I'm getting surplus number of users while a single user refresh the page multiple time concurrently. 

As, things regarding connect and disconnect underlies in the mechanism of _**sokect.io**_ I couldn't control this specific scenario myself !!

**Relevant dependencies with versions of my virtual environment:-**

> Falsk:-   1.0.2
> Flask-SocketIO:-  3.0.2
> gevent:- 1.3.5
> gevent-websocket:- 0.10.1
> python:- 3.6.3

**Comment by miguelgrinberg** [comment]
Did you wait some time? The problem is likely related to how HTTP connections disconnect, which is different than WebSocket connections. WebSocket disconnections are immediate, but HTTP connections are disconnected after one minute of inactivity. All connections start as HTTP and then upgrade to WebSocket, my guess is that when you are quickly refreshing the page multiple times some of those connections do not get to upgrade to WebSocket, so they are going to be held for one minute before they are released.

**Comment by Rakin061** [comment]
> > Did you wait some time?

-- Well, You mean wait in between two or more concurrent page refresh ? Of course not, it's most likely keep pressing the F5 key for 20 seconds or so.

>> All connections start as HTTP and then upgrade to WebSocket, 

-- Yes, And, also based on the understanding I grasped from a long conversation with You in another issue, I feel certain that, it's all up to the browser to switch from HTTP to Websocket. Still, is there anything to do in my end ?? 

So, could you suggest me any mechanism to handle user's multiple refreshing the pages without sacrificing the disconnect event ? I tried with controlling the reload event in client side, but it prevents the socket variable to load which didn't work. 

One possible solution could be simulate a alert message using jQuery while user refreshes the page but it might not be an ideal solution anyway!!

**Comment by miguelgrinberg** [comment]
> -- Well, You mean wait in between two or more concurrent page refresh ? Of course not, it's most likely keep pressing the F5 key for 20 seconds or so.

I mean to wait for one minute for the disconnect handler to be invoked. That's how long it takes for HTTP connections. You can mash the F5 key all you want, but then you are going to have some duplicate connections that should clear on their one during the next minute.

**Comment by Rakin061** [comment]
Yes, after waiting for a minute of so the _**'diconnect'**_ started invoking sequentially. 
But, still I could notice a significant difference between the _**connect**_ and _**disconnect**_ from the server log.

Theoretically,  after waiting some time, the number of  _**connect**_ and _**disconnect**_ should be same regardless of how many times F5 key has pressed.

**Comment by miguelgrinberg** [comment]
Yes, the expected result is that after all the disconnects are processed the balance would be +1, or in other words, that there was one more connect than disconnects. Isn't that the case?

**Comment by Rakin061** [comment]
Yes, that's pretty much it !! 
But, sometimes I noticed a balance of more than +1. Even, I got +10 in some cases ? 

Could you please explain the root cause of the difference and any possible ways to handle it on my own ?

**Comment by miguelgrinberg** [comment]
There shouldn't be any difference, I can't explain why you see connections that are never disposed. Make sure you are using the latest version of Flask-SocketIO and its dependencies, I believe this is working correctly now, but it was an area where there were bugs in the past.

**Comment by Rakin061** [comment]
@miguelgrinberg 

Yes, You're correct! 

After further investigation, I discovered that the reason of invoking of the additional _**'connect'**_  event compared to _**'disconnect'**_ is intrinsic ot the **_gevent, gevent-websocket and greenlet_** dependencies in my application

I just removed those three dependencies and things started to running exactly what you described. After waiting for a minute or so, all the surplus _**'disconnect'**_ events has been invoked spontaneously. 

So, may be one of the three dependencies keep restricting the  _**'disconnect'**_ event to be called itself. 
I have also tested with eventlet, but it didn't help either! 

So, what could I do now ? I barely need one of the asynchronous services for production performances!!
 
Could you give me any light regarding this issue ??

**Comment by miguelgrinberg** [comment]
Removing dependencies is not the right solution. All you did with those uninstalls is to disable the use of WebSocket.

Did you upgrade everything to the latest versions? I asked about that and you haven't confirmed.

**Comment by Rakin061** [comment]
Here's all the dependencies after deleting gevent, gevent-websocket ...

![capture2](https://user-images.githubusercontent.com/27331118/46916023-72c0f780-cfd6-11e8-88a6-dcc4539d1eb7.PNG)

**Comment by Rakin061** [comment]
@miguelgrinberg 

Ok!! I will be upgrading python-engineio and python-socketio and let you know if that problem has been solved or not ..

**Comment by Rakin061** [comment]
@miguelgrinberg 

Oh!! It works like a charm after upgrading python-engineio and python-socketio to their newest versions. 
Now after waiting a minute, disconnect event has been invoked steadily and no difference in the balance as well. So, everything is  working pretty fine !!

Many thanks for your time and consideration !!
