### ISSUE TITLE
WebSocket connection is only established once the app is refreshed. 

### ISSUE THREAD

**Issue by mrsan22** [miguelgrinberg/Flask-SocketIO#812]
Hi Miguel,

I am posting couple of questions and not an issue.

**Question 1:**
I am setting up a Angular-Flask demo app with websocket support. Websocket connection is successfully established and I can see that in my `Network -> WS`. However, this connection is not established first time I open the app, I have to `refresh` the app and now I see the ws connection under `Network -> WS`. 

I am not sure, what exactly might be causing this issue. Can you please help me understand as what I might be missing here? Also, let me know if you need more information from my end. Thanks!

**Question:** 2
Also what is the difference between `single client with multiple connections` and `multiple client`. In a scenario, where I want the app to be opened may be in different tab of same browser or new browser window (same machine though) and send/receive data from there as well. Is this considered single client or it wil under multiple client?

App TechStack:
- Angular (Frontend)
- Nginx (Reverse Proxy)
- uWSGI
- Flask-SocketIO
- gevent
- Running via Docker

uWSGI config:
```
[uwsgi]
http-socket = 0.0.0.0:5000
module=wsgi
gevent = 1000
http-websockets=true
master = true
uid = 1
gid = 1
die-on-term = true
python-autoreload = 1
gevent-monkey-patch=true
```

Nginx config:
```     worker_processes 1;

events { worker_connections 1024; }

http {

    sendfile on;

    gzip              on;
    gzip_http_version 1.0;
    gzip_proxied      any;
    gzip_min_length   500;
    gzip_disable      "MSIE [1-6]\.";
    gzip_types        text/plain text/xml text/css
                      text/comma-separated-values
                      text/javascript
                      application/x-javascript
                      application/atom+xml;

    # List of application servers
    #upstream app_servers {
     #   server localhost:8080;
    #}

    # Configuration for the server
    server {
          listen 80;
          server_name localhost;
        # Enable below line to have https connection
        # listen 443 ssl;
        # ssl_certificate /etc/nginx/cert.pem ;
        # ssl_certificate_key /etc/nginx/key.pem;

      location / {
          root   /usr/share/nginx/html;
          index  index.html;
          proxy_http_version 1.1;
          expires -1;
          add_header Pragma "no-cache";
          add_header Cache-Control "no-store, no-cache, must-revalidate, post-check=0, pre-check=0";
          try_files $uri$args $uri$args/ $uri $uri/ /index.html =404;
      }

      location /api {
            proxy_pass          http://flask_demo:5000;
            proxy_set_header        Host $host;
      }

      location /socket.io {
            proxy_pass          http://flask_demo:5000/socket.io;
            proxy_http_version 1.1;
            proxy_set_header   Upgrade $http_upgrade;
            proxy_set_header   Connection "upgrade";
            proxy_set_header        Host $host;
      }
      # To allow POST on static pages
      error_page  405     =200 $uri;
	}
}

      }```

**Comment by miguelgrinberg** [comment]
I don't think I can answer any of your questions.

For the first question, does the client try to connect that first time? If it does, then how does it fail? The server is just there waiting for connections, it has no concept of refreshes or web browsers, so I don't understand what's the significance of a refresh in this context, unless your client application causes the problem.

For the second question I need more background. The way you worded your question suggests you've read something about this clients with multiple connections. I do not know what is this reference you are making.

**Comment by mrsan22** [comment]
Thanks for your quick response.

**For Question 1:**
This is resolved and you were right, it was client side issue. It was my `Chrome browser` caching issue. 

**For Question 2:**
Sorry, I did not use correct words for my question. Basically, I was referring to one of your response [here](https://github.com/miguelgrinberg/Flask-SocketIO/issues/118#issuecomment-110482840) 

I wanted to know as what do you mean by `multiple socket connections from the same client` or `different clients`?

The reason to know the difference is because, I have a use case where the app may be opened in a different tab of same browser or new browser window (same machine though) and send/receive data from there as well. So here does `each browser tab` act as different client. Or different client means, `request coming from different machines`?

I hope, I have made the question clear enough. Thanks!

**Comment by miguelgrinberg** [comment]
Each tab or window is going to have its own private connection. The server will see each as a separate client.

**Comment by mrsan22** [comment]
Thank you!

**Comment by fahmi-nugroho** [comment]
how to overcome chrome browser caching issue?
