### ISSUE TITLE
KeyError: 'Session is disconnected'

### ISSUE THREAD

**Issue by xnys** [miguelgrinberg/Flask-SocketIO#814]
hi,I don't know how to solve this problem.

<code>
Traceback (most recent call last):
File "/home/yibei/.local/lib/python3.6/site-packages/gevent/pywsgi.py", line 975, in handle_one_response
self.run_application()
File "/home/yibei/.local/lib/python3.6/site-packages/gevent/pywsgi.py", line 922, in run_application
self.result = self.application(self.environ, self.start_response)
File "/home/yibei/.local/lib/python3.6/site-packages/flask/app.py", line 2309, in call
return self.wsgi_app(environ, start_response)
File "/home/yibei/.local/lib/python3.6/site-packages/flask_socketio/init.py", line 43, in call
start_response)
File "/home/yibei/.local/lib/python3.6/site-packages/engineio/middleware.py", line 47, in call
return self.engineio_app.handle_request(environ, start_response)
File "/home/yibei/.local/lib/python3.6/site-packages/socketio/server.py", line 360, in handle_request
return self.eio.handle_request(environ, start_response)
File "/home/yibei/.local/lib/python3.6/site-packages/engineio/server.py", line 298, in handle_request
socket = self._get_socket(sid)
File "/home/yibei/.local/lib/python3.6/site-packages/engineio/server.py", line 439, in _get_socket
raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'
</code>

Flask                  1.0.2    
Flask-SocketIO         3.0.2
gevent                 1.3.6
python-engineio        2.3.2

**Comment by miguelgrinberg** [comment]
This error occurs when a client take too long to send its ping messages. If the server does not receive a ping for a client in one minute, then it assumes the client is gone and removes it. If after the client was removed it finally sends a ping, then this error is generated.

**Comment by xnys** [comment]
> This error occurs when a client take too long to send its ping messages. If the server does not receive a ping for a client in one minute, then it assumes the client is gone and removes it. If after the client was removed it finally sends a ping, then this error is generated.

Thank you!

**Comment by xnys** [comment]
I'm sorry,but can you tell me how to solve it?
I don't know why？
Code is same as sample.

**Comment by xnys** [comment]
> This error occurs when a client take too long to send its ping messages. If the server does not receive a ping for a client in one minute, then it assumes the client is gone and removes it. If after the client was removed it finally sends a ping, then this error is generated.

I'm sorry,but can you tell me how to solve it?
I don't know why？
Code is same as sample.

**Comment by harrypotter90** [comment]
Hi, I am getting this error and struggling with this issue for days now without any clue.

Can I change the server configuration so that it can wait for client ping for a longer period?

Thanks

**Comment by miguelgrinberg** [comment]
@harrypotter90 wouldn't it make more sense to fix the client to send pings at the correct interval? You can set the interval to anything you want when you create the `SocketIO()` object, but I'm not sure that is the problem.

**Comment by harrypotter90** [comment]
Correct.
I have a strange problem. This problem doesnt happen when it is high load, if it is 1-3 clients then it works fine.

As soon as i increase the load, after some 20-30 seconds, i get error stating:

`W0918 07:25:45.227649 129050147877248 server.py:216] Cannot send to sid 4422a5b7d2694ccf9fbf96ace4bd4f05`


I debugged more in the code, and found that in **socketio** library we get event "handle_disconnect" (why will client send disconnect, if its not finished, quite strange)


So first i can see print that "socketio disconnecting here " with some sid
```
    def _handle_disconnect(self, sid, namespace):
        """Handle a client disconnect."""
        namespace = namespace or '/'
        print("socketio disconnecting here : " + str(sid) + " - " + str(namespace))
```

and then get print of 
"print("session not found in get socket" " for the same sid


```
    def _get_socket(self, sid):
        """Return the socket object for a given session."""
        try:
            s = self.sockets[sid]
        except KeyError:
            print("session not found in get socket" + str(sid) + "--" + str(self.sockets))
            raise KeyError('Session not found')
        if s.closed:
            print("session not found in get socket ee")
            del self.sockets[sid]
            raise KeyError('Session is disconnected')
        return s
```



Any thoughts / suggestions are welcome, quite strange

**Comment by harrypotter90** [comment]
Yes, it seems client is sending disconnect flag somehow (but still trying to send a packet to that sid). And not a fault of server , seems like.

I know you cannot comment on the client, Its. a Java client library which i am using for load-testing, "socket.io-client-1.0.0.jar" .

Can you think of any possible reason that in a load client close the connection.

**Comment by miguelgrinberg** [comment]
I am not familiar with the Java client, so I really don't know. The only potential issue I can think if is that if the server does too much CPU work then it is going to become unresponsive under high load. Not sure if that is your case or not, but with asynchronous servers you always have to watch for CPU use.

**Comment by harrypotter90** [comment]
Thank you @miguelgrinberg for the quick response and tips.

I am investigating more, will update here, so that it can help for others.
