### ISSUE TITLE
Send_File() throws an error when running with flask-socketio

### ISSUE THREAD

**Issue by mntolia** [miguelgrinberg/Flask-SocketIO#815]
Hi Miguel,

Your library has been working great so far. 
When I run a send_file function in flask it throws this error:
```
Traceback (most recent call last):
  File "/home/maxwell/Desktop/python/aqua/lib/python3.6/site-packages/eventlet/wsgi.py", line 572, in handle_one_response
    write(b''.join(towrite))
  File "/home/maxwell/Desktop/python/aqua/lib/python3.6/site-packages/eventlet/wsgi.py", line 519, in write
    wfile.flush()
  File "/usr/lib/python3.6/socket.py", line 604, in write
    return self._sock.send(b)
  File "/home/maxwell/Desktop/python/aqua/lib/python3.6/site-packages/eventlet/greenio/base.py", line 395, in send
    return self._send_loop(self.fd.send, data, flags)
  File "/home/maxwell/Desktop/python/aqua/lib/python3.6/site-packages/eventlet/greenio/base.py", line 382, in _send_loop
    return send_method(data, *args)
BrokenPipeError: [Errno 32] Broken pipe

```
I am not sure if this error is because of socketio or something else.

When I run the app with the normal `app.run()` the `send_file()` works perfectly. But only with socketio.run() this issue occurs.

Thank you for creating this library!

**Comment by miguelgrinberg** [comment]
You need to monkey patch the Python standard library to make it compatible with eventlet. Add the following at the top of your main script:

````python
import eventlet
eventlet.monkey_patch()
```

**Comment by mntolia** [comment]
Thanks for the prompt reply.

I had already added it in the file where I run the app:
```
import eventlet
eventlet.monkey_patch()
from app import app
from app import socketio

if __name__ == "__main__":
    #app.run(host = "localhost", port = 8000)
    socketio.run(app, host = "localhost", port = 8000)
```

The issue still occurs.

**Comment by miguelgrinberg** [comment]
Can you show me the code that makes the `send_file()` call?

**Comment by mntolia** [comment]
This view makes the call:
`@bp.route('/<farm_id>/<device_id>/update', methods = ['GET'])
def version_checker(farm_id, device_id):
    try:
        device = DeviceList.query.filter(and_(DeviceList.farm_id == farm_id, DeviceList.mqtt_id == device_id)).first()
        if device is not None:
            print(request.headers)
            if request.headers['X-Esp8266-Version'] < device.version_number:
                response = make_response(send_file(
                    'arduino.bin', 
                    mimetype='application/octet-stream',
                    as_attachment=True
                    ))
                response.headers['x-MD5'] = md5('arduino.bin')
                print(response.headers)
                return response
            else:
                return "304: Not Modified", 304
        else:
            return   "404: Not Found", 404
    except Exception as e:
        print(e)
        return "502 Bad Gateway", 406`

**Comment by miguelgrinberg** [comment]
How big is the arduino.bin file?

**Comment by mntolia** [comment]
It is 351 kb

**Comment by mntolia** [comment]
It worked. I updated both flask and the extensions.
