### ISSUE TITLE
eventlet gevent

### ISSUE THREAD

**Issue by zhangatao** [miguelgrinberg/Flask-SocketIO#816]
Hello, when using flask_socketio, if I use eventlet, I must uninstall gevent. If I don't uninstall gevent, what happens?

**Comment by zhangatao** [comment]
Thank you, on the same server, if another file uses gevent, but flask_socketio uses eventlet, will there be a conflict in this case?

**Comment by miguelgrinberg** [comment]
@zhangatao yes, very likely that is going to give you problems. You should pick one of the two and only use that one.

**Comment by zhangatao** [comment]
Ok, thank you very much for your answer.
