### ISSUE TITLE
how to get thread ID from the return value of start_background_task?

### ISSUE THREAD

**Issue by sodynamic** [miguelgrinberg/Flask-SocketIO#820]
Hi @miguelgrinberg

for example the code is like:
job_thread = socketio.start_background_task(target=target_function)

is it possible to get the thread id of this background task from "job_thread"? The type of 'job_thread' is 'Thread', and it seems that it's quite different from threading or threading.thread, of which you can try get_ident() or ident.

Thanks!

**Comment by miguelgrinberg** [comment]
The thread object that you get depends on the async framework that you are using. If you are using eventlet or gevent then there is only one thread, all these tasks run within the context of the main thread. You may be able to get an id that identifies the task, but there is going to be only one thread id for the entire application.

**Comment by sodynamic** [comment]
> The thread object that you get depends on the async framework that you are using. If you are using eventlet or gevent then there is only one thread, all these tasks run within the context of the main thread. You may be able to get an id that identifies the task, but there is going to be only one thread id for the entire application.

Thank you @miguelgrinberg ! I have tried different options to set "async_mode". If the option is "eventlet" or "threading", the thread id can be get by job_thread.ident. If the option is "gevent", I don't know how to get the thread id.

Anyway, my current problem is solved. Thank you!

**Comment by miguelgrinberg** [comment]
This is how Flask does it: https://github.com/pallets/werkzeug/blob/master/werkzeug/local.py#L16-L25. This works for eventlet, gevent and regular threads.

But once again, keep in mind that eventlet and gevent run in a single thread, the identifiers that you are getting are not for threads in the regular sense.
