### ISSUE TITLE
How to emit multiple data to the client by using socket.io

### ISSUE THREAD

**Issue by hanisyuhada** [miguelgrinberg/Flask-SocketIO#822]
**main.py**
`@socketio.on('message')`
`def message(data):`
` with app.test_request_context('/'):`
`socketio.emit('message', {"data":data})`

`if __name__ == "__main__":`
`def print_callback(pkt):`
`if 'TCP' in pkt:`
`print('Just arrived:', pkt['TCP'])`
`message(pkt['TCP'].port)` _//this line will only emit ports captured and insert in the table_

**profile.html**
`socket.on('message', function(data) {`
`console.log(data);`
`var test ='<tr><td>'+data.data+'</td><td>test1</td><td>test2</td><td>test3</td></tr>';`
`$("#addRows").append(test);`
`});`

above are my code in my **main.py** and **profile.html**. i am not very familiar with socket.io, unfortunately i have to used it in my project. i've got problem in how to insert any other information captured from the packets such as ip address and many more in the table..  `message(pkt['TCP'].port)`  only emit ports in the table.. any idea on how to insert other information in the table?

**Comment by miguelgrinberg** [comment]
You can convert all the data that you want to emit to the client to a dictionary, and then emit it as follows:

    socketio.emit('tcp_data', {'data': data})

Then on the client:

    socket.on('tcp_data', function(data) {
        console.log(data);
        // insert all the keys in data in the proper places!
    });

**Comment by hanisyuhada** [comment]
it works.. thank you :)

So basically, '+data.data+' will only emit port into the first column. How to emit different data from the server into different column on the client side? if i put the '+data.data' at the second column, all the data including the port data will be in the first and second column?

`if __name__ == "__main__":`
`def print_callback(pkt):`
`if 'TCP' in pkt:`
`print('Just arrived:' pkt['TCP'])`
` message(pkt['TCP'].port)`
`message(pkt['TCP'].checksum)`

### profile.html

` var test ='<tr><td>'+data.data+'</td><td>'+data.data+'</td><td>testt</td><td>test3</td><td>test4</td></tr>';`

any idea how to separate the port and checksum into different column?

**Comment by miguelgrinberg** [comment]
Emit both values in a single operation:

     emit("my_tcp_data", {'port': pkt['TCP'].port, 'checksum': pkt['TCP'].checksum})
