### ISSUE TITLE
Logging Issues

### ISSUE THREAD

**Issue by jslay88** [miguelgrinberg/Flask-SocketIO#823]
I am quite aware of the logging around this project and that is logs to the different servers and how they are set up after perusing through the numerous issues that have been opened regarding logging and this project. So I guess its my turn to get berated for not understanding how this is actually supposed to work.

I have tried everything to get a normal python logger to work with flask_socketio and am about to throw in the towel.

I have tried setting DEBUG to true on the flask app, log_output=True, and setting logger and engineio_logger to a logger object, and cannot seem to get any sort of logging out of this thing, even with just a default python logger `logger = logging.getLogger(__name__)`

I am honestly quite surprised there is not some sort of stdout python logger that we can just use out of the box with flask_socketio, beyond print string, that is at least properly documented somewhere.

Using flask_socketio 3.0.2, Python3.7 and the Flask 1.0.2.

Here is a truncated bit of code and output from my project. Keeping in mind these lines of code come from separate files and are properly imported. I have a working server and client, just cant get logging working.

```
logger = logging.getLogger(__name__)  # Tried both of these
logger = logging.getLogger('flask.app') # and made sure they were valid
print(logger)

<Logger flask.app (WARNING)>

sio = SocketIO(logger=logger,
               engineio_logger=logger)

sio.init_app(flask_app, log_output=True,logger=flask_app.logger,
               engineio_logger=flask_app.logger)
```

**Comment by miguelgrinberg** [comment]
> I am honestly quite surprised there is not some sort of stdout python logger that we can just use out of the box with flask_socketio, beyond print string, that is at least properly documented somewhere.

You are incorrect, there are easy options for logging that are documented:

```
logger – To enable logging set to True or pass a logger object to use. To disable logging set to False. The default is False.
engineio_logger – To enable Engine.IO logging set to True or pass a logger object to use. To disable logging set to False. The default is False.
```

All you need to do to get Socket.IO logs to stdout is:

```python
sio.init_app(flask_app, logger=True, engineio_logger=True)
```

Are these not sufficient?

**Comment by jslay88** [comment]
No, as they only provide the logs for the SocketIO modules. It’s still ignores all of my modules loggers. 

As stated initially, even passing a basicConfig logger object produces no logs, even from SocketIO.

Normally in a flask app, I can grab the logger with logging.getLogger and start logging right away in my own modules with logger.info yada yada. 

I have yet to successfully produce logs when passing any sort of logger object to socketio, with log_output and debug both set to true.

**Comment by miguelgrinberg** [comment]
> No, as they only provide the logs for the SocketIO modules. It’s still ignores all of my modules loggers.

I don't follow your logic. Why does Flask-SocketIO logs have to do with logs from other subsystems or your app? That is actually a feature and done this way by design, because you may not want Socket.IO logs mixed with everything else. This is why Python's logging module supports multiple loggers, each with a different and independent configuration.

When you pass `True` as a `engineio_logger` this is the logger that you get (from the python-engineio source code):

```python
default_logger = logging.getLogger('engineio')
```

For the `logger` option you get:

```python
default_logger = logging.getLogger('socketio')
```

In both cases if you don't set a default logging level in your application, the level is set to `INFO`.

The logging for other libraries or your application is separate, Flask-SocketIO does not participate on that.

**Comment by jslay88** [comment]
So what is causing me to not be able to get a stdout log from a logger object as such?

```
import logging

logger = logging.getLogger(__name__)

logger.info('This will never make it to stdout when SocketIO is enabled.')
```

**Comment by jslay88** [comment]
How about this, can we get an example of how to use our own custom loggers in the Flask-SocketIO documentation that follows whatever method you are using? As the documentation is obviously not clear enough on how to achieve this (hence the numerous issues that have been opened around logging on this project).

**Comment by miguelgrinberg** [comment]
I copied the above snippet to a logtest.py file and ran it as `python logtest.py`. I also got nothing, even though Flask-SocketIO is not even installed. So I'm at a loss why you claim it works without Socket.IO. Your example does not configure the root logger, and does not set up any handlers for your logger, or a logging level. It cannot work.

> can we get an example of how to use our own custom loggers in the Flask-SocketIO documentation that follows whatever method you are using?

Sorry but I don't understand. The documentation is clear, you either pass `True` to get a default logger configured with sane defaults chosen by the library, or pass your own logger object, configured any way you like. 

> hence the numerous issues that have been opened around logging on this project

I need references to the "numerous" issues with logging.

**Comment by jslay88** [comment]
Well Google produces those results easily enough, I found at least 15 issues within the first 4 pages.

Having said, that, you did just make me realize what was actually happening rereading your previous comment.

For some reason, my log level is being overridden somewhere when I enable Flask-SocketIO. I think this is something to do with another piece of my code, as I have hardcoded against that bit and it appears to be working now. I should have realized it when I posted the initial snippet and it showed the logger at WARNING.

Appreciate your patience and willingness to help me.

**Comment by NarayanAdithya** [comment]
Have same doubt , whenever there is a print('Hey') it never shows up as it is a stdout stream, only stderr is logged

**Comment by ItsMichal** [comment]
> ```python
> logger=True, engineio_logger=True
> ```

Note for anyone coming here from google, that the new syntax to simply enable logging is-

```python
log_output=True
```

See [the docs on this in case it changes again](https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.SocketIO.run)

**Comment by miguelgrinberg** [comment]
@ItsMichal you are confusing two different levels of logging. `logger` and `engineio_logger` are for logging in the Socket.IO subsystem. The `log_output` option is for logging at the web server level. Different logs.

**Comment by ItsMichal** [comment]
You're right- thanks.
