### ISSUE TITLE
Question: upgrade HTTP GET to websocket?

### ISSUE THREAD

**Issue by andy00ff00** [miguelgrinberg/Flask-SocketIO#824]
Hi,
I'm trying to use flask to create a mock server to test an already-existing client. 
I've managed to create a REST API using flask, but am stuck where the client issues a GET with an upgrade request to websocket. I've create a route for the GET, can return sensible-looking 101, the client subsequently sends websocket text (confirmed in tcpdump/wireshark), but I don't think that TCP connection is being served by the websocket API. If I understand the examples correctly, they show the socketio server listening for connections and handling a connect event. 
Is it possible to hand an existing connection over to socketio, or have I missed some important concept somewhere?

    from flask import Flask, request
    from flask import make_response
    from flask import session
    from flask_restful import Resource, Api
    from flask_socketio import SocketIO

    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'secret!'
    api = Api(app)
    socketio = SocketIO(app)

    WS_MAGIC_STRING = "258EAFA5-E914-47DA-95CA-C5AB0DC85B11"
    def handshake(request):
        # see RFC6455
        try:
            if (request.headers['connection'].lower() == 'upgrade'
                    and request.headers['upgrade'].lower() == 'websocket'
                    and request.headers['sec-websocket-key']
                    and request.headers['sec-websocket-version']):
                key = request.headers['sec-websocket-key'].strip() + WS_MAGIC_STRING
                return base64.standard_b64encode(hashlib.sha1(key).digest())
        except KeyError:
            return None

    @app.route('/myhttppath')
    def monitoringLogApi():
        respkey = handshake(request)
        ret = make_response('', 101)
        ret.headers['Upgrade'] = 'websocket'
        ret.headers['Connection'] = 'upgrade'
        ret.headers['Sec-WebSocket-Accept'] = respkey
        # WHAT DO I PUT HERE TO HAND OVER TO SOCKETIO SERVER????
        return ret

    @socketio.on('message')
    def handle_message(message):
        print 'received msg: %r' % message

    @socketio.on('connect')
    def test_connect():
        print 'got conn'

    if __name__ == '__main__':
        socketio.run(app, port=9000, debug=True)

**Comment by miguelgrinberg** [comment]
It does not work like that. You can't handle a Websocket upgrade request through Flask, since Flask will treat it as an HTTP request. The upgraded connection does not go away, your entire Websocket server needs to be implemented inside the route because as soon as you return the connection will be closed.

Why don't you let the Socket.IO server handle your Websocket upgrade?

**Comment by andy00ff00** [comment]
Thanks for the quick response. 
I'm using flask just because it was quick and easy to create the REST interface that the client expects, I have various other routes which work, but they're simple HTTP.
For the websocket part, the client expects to connect to http://server:host/a/specific/path. I'm not wedded to flask for that, just haven't yet discovered how to hook up a server to it - the flask route was the only way I've found so far to get anything other than 404.

> Why don't you let the Socket.IO server handle your Websocket upgrade?

Do you mean something like this
    @app.route('/myhttppath')
    def monitoringLogApi():
        sio.handle_request(ummm.... arguments?)

or don't use flask for that route at all?

**Comment by miguelgrinberg** [comment]
No, what I mean is that Flask-SocketIO uses a fully fledged Websocket server (when paired with eventlet for example), so you don't need to create a fake endpoint, just create a real websocket server. The other options are very painful.

**Comment by andy00ff00** [comment]
I'm sorry, I don't understand how to connect the websocket server to that URI. I must be missing some key concept somewhere. 
The examples show an @app.route('/') which returns an html file containing javascript telling the browser to io.connect(...). I don't *THINK* I need that - that client has already connected. Then the just have @socketio.on(<message>) hookpoints. 
I think you're suggesting that socketio will handle the GET, handshake etc. for me without a flask route - but I just can't see how to connect up handlers to a URI with a path. The client just gets a 404.

**Comment by miguelgrinberg** [comment]
First of all, do you need WebSocket or Socket.IO? This is a Socket.IO package, it does not do plain WebSocket.

All I'm saying is that you don't need to fake a Socket.IO connection, just use the package in the intended way and you'll have a Socket.IO server that isn't a fake. So forget about creating a WebSocket endpoint, and see the documentation and examples if you need help setting up the server properly.

**Comment by andy00ff00** [comment]
Hmmm. That was the important concept I'd missed - I hadn't realised websocket and socket.io are not the same thing. I now have this working using flask-sockets. 
Thanks for your support and patience.
