### ISSUE TITLE
Implementation of equivalents to Flask signals for handling

### ISSUE THREAD

**Issue by bpengu1n** [miguelgrinberg/Flask-SocketIO#825]
Flask provides signals such as request_started and request_finished, enabling methods to be hooked to each of these events via the blinker library. It would be immensely useful to provide the equivalents to these in flask-SocketIO, recognizing, of course, that "request" takes on a different context, as the traditional request in SocketIO spans the length of the connection; so the equivalent for each 'request' sent during that connection would be very useful to have, in order to set up or tear down environments both for an entire request/connection context, and for each individual event.

**Comment by miguelgrinberg** [comment]
It is fairly easy to implement common behaviors at start or end of a Socket.IO event by using a class-based namespace and overriding the `trigger_event` method, so I'm currently not planning to implement another way to do that.
