### ISSUE TITLE
Can't get socket.io to work with nginx and uwsgi

### ISSUE THREAD

**Issue by Funktiona** [miguelgrinberg/Flask-SocketIO#826]
I have tried for over 10h getting socket.io to work nothing seemes to work

my nginx config look like this

    `
    server {

    listen 80;

    server_name cuveer.com www.cuveer.com;

    proxy_connect_timeout       605;
    proxy_send_timeout          605;
    proxy_read_timeout          605;
    send_timeout                605;
    keepalive_timeout           605;

    location / {
        include uwsgi_params;
        #add_header "Access-Control-Allow-Origin" $http_origin;
        add_header 'Access-Control-Allow-Origin' 'https://www.cuveer.com';
        add_header 'Access-Control-Allow-Credentials' 'true';
        uwsgi_pass unix:/home/webserver/webserver.sock;

        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_read_timeout 86400s;
        #proxy_read_timeout      120s;
    }

    }`

![screenshot from 2018-11-07 05-24-19](https://user-images.githubusercontent.com/5854510/48110631-823a0600-e24d-11e8-8f9e-63312fab9705.png)

![screenshot from 2018-11-07 05-24-36](https://user-images.githubusercontent.com/5854510/48110645-89f9aa80-e24d-11e8-9ffa-43a56404b0fc.png)

![screenshot from 2018-11-07 05-26-04](https://user-images.githubusercontent.com/5854510/48110664-a695e280-e24d-11e8-97c4-308af8b4c072.png)

**Comment by miguelgrinberg** [comment]
Flask-SocketIO handles CORS, you do not need to add CORS headers in the nginx config. But if you do, then add the correct headers. It looks like you are accessing the site at https://cuveer.com` and the access control header you added in nginx only allows `https://www.cuveer.com`.

Secondary problem is that the uwsgi module in nginx I believe does not support proxying websocket, only HTTP. You can switch to the HTTP proxy module to get WebSocket to work as well.

**Comment by Funktiona** [comment]
Thank you a million!! I finally got it to work. I changed my nginx setting and started my flask server manual and did not use wsgi. Is this the correct way? Does uwsgi not help with load, will flask handle this by itself. Or is there something else I can do/use?   

Nginx.conf :
 
`

    server {

    listen 80;

    server_name cuveer.com www.cuveer.com;

    proxy_connect_timeout       605;
    proxy_send_timeout          605;
    proxy_read_timeout          605;
    send_timeout                605;
    keepalive_timeout           605;

    location / {

        proxy_pass http://127.0.0.1:5000;

        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_read_timeout 86400s;
    }
`

**Comment by Funktiona** [comment]
You say "slightly better performance" how important do you say this is. Will it be a significant  difference. Or will it go by Ok. 
I think I read somewere that if I use socket.io with uwsgi I can only have 1 process is this true?

**Comment by miguelgrinberg** [comment]
Yes and No. The limitation of using a single process is not only for uwsgi, it applies to all supported web servers including what you are doing now.

You can run multiple processes in all cases, but the set up is more complex. You can read about it in the documentation.
