### ISSUE TITLE
Unable to run the example code

### ISSUE THREAD

**Issue by jldiaz** [miguelgrinberg/Flask-SocketIO#829]
I must be doing something fundamentally wrong, but I'm unable to see what. I just tried the example in the documentation, and for some reason, the server keeps answering `200 Ok` instead of `101 Switching protocols`.

I did the following:

1. Copied the example code from the documentation:

    ```python
    from flask import Flask, render_template
    from flask_socketio import SocketIO

    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'secret!'
    socketio = SocketIO(app)

    if __name__ == '__main__':
        socketio.run(app, host="0.0.0.0")
    ```

2. Ran the code directly from python (3.6.6):

    ```
    $ python example.py
    ```

3. Tried to connect from <http://www.websocket.org/echo.html>, to `ws://<My_IP>:5000/socket.io/` (my server has a public IP, and the port 5000 is not firewalled). The `ws` connection was inmediatly closed. Chrome complained (in the error console) that the response was 200 Ok, which was indeed,as I could see in the network inspector.

4. Just in case, I also tried the following command on the same machine than the flask server is running:

    ```
    curl --include \
        --no-buffer \
        --header "Connection: Upgrade" \
        --header "Upgrade: websocket" \
        --header "Host: mysite.com:5000" \
        --header "Origin: http://mysite.com:80" \
        --header "Sec-WebSocket-Key: SGVsbG8sIHdvcmxkIQ==" \
        --header "Sec-WebSocket-Version: 13" \
        --output OUT.txt \
        http://localhost:5000/socket.io/
    ```

   The resulting `OUT.txt`  also showed the response `200 Ok` (and two first websocket frames, by the way, the first one with some metadata like `{"sid":"303bf7a7abd4470784d70607c86e084a","upgrades":["websocket"],"pingTimeout":60000,"pingInterval":25000}`, and the next one with the bytes `00 02 ff 34 30`. Then the connection is closed).

5. Tried several different ways to start the server, such as the following ones:

    ```
    $ FLASK_APP=example.py flask run --host 0.0.0.0 --port 5000
    $ gunicorn --worker-class eventlet -w 1 example:app --bind 0.0.0.0:5000
    $ gunicorn -k gevent -w 1 example:app --bind 0.0.0.0:5000
    ```

    In all these cases the result is the same. `200 Ok` instead of `101`.

Finally, the closest to success I was, was when the server was launched with:

```
$ gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 example:app --bind 0.0.0.0:5000
```

In this case, the `curl` command receives a response `400 Bad request`, and causes one exception in the server (" a bytes-like object is required, not 'str'") which aborts the transfer. But the site <http://www.websocket.org/echo.html> shows a successful connection (`101` at least), followed by a disconnection. Google chrome inspector shows no fames.

These are my versions (ouput of `pip freeze`):

```txt
Click==7.0
dnspython==1.15.0
eventlet==0.24.1
Flask==1.0.2
Flask-SocketIO==3.0.2
gevent==1.3.7
gevent-websocket==0.10.1
greenlet==0.4.15
gunicorn==19.9.0
itsdangerous==1.1.0
Jinja2==2.10
MarkupSafe==1.1.0
monotonic==1.5
pkg-resources==0.0.0
python-engineio==2.3.2
python-socketio==2.0.0
redis==2.10.6
six==1.11.0
Werkzeug==0.14.1
```

```

**Comment by miguelgrinberg** [comment]
This is a Socket.IO server, not a WebSocket server. Socket.IO is a protocol built on top of WebSocket and HTTP. You can't connect with a plain websocket client.

**Comment by jldiaz** [comment]
Thank you! This was the missing piece of the puzzle. Sorry for the confusion. I just saw your excellent talk "Fun with WebSocket and flask" in pycon 2017, which perfectly explains the difference. If I had seen the talk before, this issue/question would not be open.

The confusion arose because I was (obviously) unaware of the SocketIO protocol (I thought that it was only a js client library to simplify the use of WebSockets), and that all my google searches about python, flask and WebSockets landed on flask-socketio, so I assumed it was the same.

Is there any way to use "pure" websockets with flask-socketio? Or with any other flask extension?

**Comment by miguelgrinberg** [comment]
Try [Flask-Sockets](https://github.com/heroku-python/flask-sockets).
