### ISSUE TITLE
Celery with Flask Socketio

### ISSUE THREAD

**Issue by EndenDragon** [miguelgrinberg/Flask-SocketIO#831]
Is it possible to run Flask SocketIO with celery? I am looking at the sample code from http://flask.pocoo.org/docs/1.0/patterns/celery/ and wondering if I could utilize it along with flask socketio event handlers.

From that example, let's say `add_together` is an event handler... `on_add_together`. `on_add_together` could be a long function and potentially be blocking calls (not necessarily async). In the end, it would emit back to the user the addition of the two numbers. Would it be possible? Do I need to know anything/watch out for when I integrate celery into the stack?

**Comment by miguelgrinberg** [comment]
I have an example app that uses Socket.IO and Celery: https://github.com/miguelgrinberg/flack. Hopefully that'll give you a starting point!
