### ISSUE TITLE
SocketIO-client cant connect to Flask-SocketIO Sever ! (Help ! )

### ISSUE THREAD

**Issue by tranvinhphuc111996** [miguelgrinberg/Flask-SocketIO#833]
Hi Miguel Grinberg ! 
Im using Flask and Flask SocketIO  to make sever . it run well , but when im using socketIO_client (python) to connect to sever , it cant connect to the sever ! . please check this code help me ! Thanks .

my sever have ip :104.131.98.89
sever:
```python
from flask import Flask, request, jsonify, render_template, session, redirect, escape
from werkzeug.utils import secure_filename
from datetime import datetime
import os
import sqlite3
from flask_socketio import SocketIO, emit
import json
import threading
DATABASE_FILE = 'database.db'
app = Flask(__name__, static_url_path='/static')
app.secret_key = os.urandom(12)
ALLOWED_EXTENSIONS = set(['txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'])
app.config['UPLOAD_FOLDER'] = './static/image'
socketio = SocketIO(app, async_mode=None)
def connectdb():
	conn = sqlite3.connect(DATABASE_FILE, isolation_level = None)
	return conn
def querydb(conn, query, v = tuple()):
	c = conn.cursor()
	c.execute(query, v)
	return c.fetchall()

def logged_in():
	if not session.get('logged_in'):
		return 0
	return 1

@app.route('/')
def index():
	if logged_in():
		return render_template('index.html')
	else:
		return redirect('/dang_nhap')
@app.route('/dang_nhap', methods=['GET', 'POST'])
def dang_nhap():
	if request.method == 'GET':
		return render_template('dang_nhap.html')
	else:
		username = request.form.get('username')
		password = request.form.get('password')
		conn = connectdb()
		r = querydb(conn, r"SELECT * FROM Administrator WHERE username=? AND password=?", (username, password))
		if r:
			session['logged_in'] = True
			return redirect('/')
		else:
			return render_template('dang_nhap.html')
@app.route('/static/<filename>')
def static_file(filename):
	return app.send_static_file(filename)

@app.route('/json/scan_the', methods=['POST'])
def scan_the():
	json_post_data 	= request.get_json()
	CardID 			= json_post_data['CardID']
	DeviceID 		= json_post_data['DeviceID']
	FingerID		= json_post_data['FingerID']
	ImageID			= json_post_data['ImageID']
	EntryTime 		= json_post_data['EntryTime']
	conn = connectdb()
	r = querydb(conn, r"SELECT * FROM Employee WHERE CardID=?", (CardID, ))
	if len(r) > 0:
		respone = {'status': 1}
		querydb(conn, r"INSERT INTO Work(DeviceID,CardID,FingerID,ImageID,EntryTime) VALUES (?,?,?,?,?)", (DeviceID,CardID,FingerID,ImageID,EntryTime, ))
		name_string = querydb(conn, r"SELECT EmployeeName FROM Employee WHERE CardID=?",(CardID,))

		post_web_data = json.dumps({"NameEmploy": name_string,"EntryTime": EntryTime,"ImageID": ImageID})
		print 'post_web_data:', post_web_data
		socketio.emit('my_response', post_web_data , namespace='/tracking')
	else:
		respone = {'status': 0}
		try:
			querydb(conn, r"INSERT INTO UnRegistered(CardID) VALUES (?)", (CardID, ))
		except:
			pass
	conn.commit()
	conn.close()
	return jsonify(respone)



@app.route('/Tracking', methods=['POST', 'GET'])
def tracking():
	return render_template('Tracking.html')
def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@app.route('/rev_image', methods=['POST', 'GET'])
def upload_file():
    if request.method == 'POST':
        file = request.files['file']
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            file.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))
            post_web_data = json.dumps({"Image_status":"true"})
            socketio.emit('image_response', post_web_data , namespace='/tracking')
            return 'Success'
    return 'Success'


@app.route('/them_nhan_vien', methods=['POST', 'GET'])
def them_nhan_vien():
	if not logged_in():
		return redirect('/dang_nhap')

	if request.method == 'GET':
		return render_template('them_nhan_vien.html')
	else:
		post_data 			= request.form
		CardID 				= post_data['mathe'] 
		EmployeeName 		= escape(post_data['hoten'])
		EmployeeBirthDate 	= datetime.strptime(post_data['ngaysinh'], '%d-%m-%Y')
		print(post_data)
		conn 				= connectdb()
		r 					= querydb(conn, r"INSERT INTO Employee(EmployeeName, CardID, EmployeeBirthDate) VALUES(?,?,?)", (EmployeeName, CardID, EmployeeBirthDate))
		return render_template('them_nhan_vien.html')

@app.route('/json/xoa_nhan_vien', methods=['POST'])
def xoa_nhan_vien():
	if not logged_in():
		return redirect('/dang_nhap')

	json_post_data 		= request.get_json()
	CardID 				= json_post_data['mathe']
	conn 				= connectdb()
	r 					= querydb(conn, r"DELETE FROM Employee WHERE CardID=?", (CardID,))
	return jsonify({'status': 1})

@app.route('/json/sua_thong_tin_nhan_vien', methods=['POST'])
def sua_thong_tin_nhan_vien():
	if not logged_in():
		return redirect('/dang_nhap')

	json_post_data 		= request.get_json()
	CardID 				= json_post_data['mathe'] 
	EmployeeName 		= escape(json_post_data['hoten'])
	EmployeeBirthDate 	= datetime.strptime(json_post_data['ngaysinh'], '%d-%m-%Y')
	conn 				= connectdb()
	r 					= querydb(conn, r"UPDATE Employee SET EmployeeName=?,EmployeeBirthDate=? WHERE CardID=?", (EmployeeName, EmployeeBirthDate, CardID))
	return jsonify({'status': 1})

@app.route('/them_thiet_bi', methods=['POST', 'GET'])
def them_thiet_bi():
	if not logged_in():
		return redirect('/dang_nhap')

	if request.method == 'GET':
		return render_template('them_thiet_bi.html')
	else:
		post_data 	= request.form
		DeviceID  	= post_data['deviceid']
		description = escape(post_data['description'])
		conn 		= connectdb()
		r 			= querydb(conn, r"INSERT INTO Device(DeviceID, Description) VALUES(?,?)", (DeviceID, description))
		return render_template('them_thiet_bi.html')
@socketio.on('Ping')
def handle_ping():
	print('Ping !!!')
```

im using this to run sever ! 
```
export FLASK_ENV=development
export FLASK_APP=main.py
flask run --host=0.0.0.0
```

in client 

```
from socketIO_client import SocketIO, LoggingNamespace
import time
socket = SocketIO('http://104.131.98.89',5000,LoggingNamespace)
socket.emit('Ping')'
```

sometimes it connect , sometimes not 

this is my pip freezes :
asn1crypto==0.24.0
bcrypt==3.1.4
beautifulsoup4==4.4.1
capstone==3.0.4
certifi==2018.4.16
cffi==1.11.5
chardet==3.0.4
click==6.7
cryptography==2.2.2
dnspython==1.15.0
enum34==1.1.6
eventlet==0.24.1
Flask==1.0.2
Flask-SocketIO==3.0.1
gevent==1.3.6
greenlet==0.4.14
html5lib==0.999
idna==2.6
intervaltree==2.1.0
ipaddress==1.0.22
itsdangerous==0.24
Jinja2==2.10
lxml==3.5.0
Mako==1.0.7
MarkupSafe==1.0
monotonic==1.5
packaging==17.1
paramiko==2.4.1
pluggy==0.6.0
psutil==5.4.5
pwntools==3.12.0
py==1.5.3
pyasn1==0.4.2
pycparser==2.18
pyelftools==0.24
Pygments==2.2.0
PyNaCl==1.2.1
pypandoc==1.4
pyparsing==2.2.0
pyserial==3.4
PySocks==1.6.8
python-dateutil==2.7.3
python-engineio==2.2.0
python-socketio==2.0.0
requests==2.18.4
ROPGadget==5.4
six==1.11.0
sortedcontainers==1.5.10
tox==3.0.0
unicorn==1.0.1
urllib3==1.22
virtualenv==15.2.0
Werkzeug==0.14.1

**Comment by tranvinhphuc111996** [comment]
But when im using SocketIO connect on JS it run well

**Comment by tranvinhphuc111996** [comment]
This is log:
![image](https://user-images.githubusercontent.com/22383911/48492868-51fdf300-e85d-11e8-900f-8532bce7a6f9.png)

**Comment by miguelgrinberg** [comment]
You haven't said what happens when it does not work, so I can't really help you. In any case, if the problem is with the client, why are you writing an issue on the server?

**Comment by tranvinhphuc111996** [comment]
ok ! sorry sir , i think this problem from sever because . in many example i was saw it run well ^^ ... sorry im not good at backend

**Comment by miguelgrinberg** [comment]
Sorry, maybe I misunderstood. Which combination works? Python client and JS server, or JS client and Python server?

**Comment by tranvinhphuc111996** [comment]
no, my sever is flask + flask-socketio , my client using socketio-client python and web . in HTML im using socketio to connect to my sever it run well , but when im using in  socketio-client python it not work :(

**Comment by tranvinhphuc111996** [comment]
This is code in HTML , it run well . i connect to sever `<!DOCTYPE html>
<html>
<head>
    <title>Flask-SocketIO Test</title>
    <script type="text/javascript" src="//code.jquery.com/jquery-1.4.2.min.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.5/socket.io.min.js"></script>
    <link rel="stylesheet" href="/static/style.css" type="text/css" media="all" />
    <script type="text/javascript" charset="utf-8">
        $(document).ready(function() {
         var res = "";
         var NameEmploy ;
         var EntryTime
         namespace = '/tracking';
         var socket = io.connect(location.protocol + '//' + '104.131.98.89' + ':' + location.port + namespace);
         
         socket.on('my_response', function(msg) {
            obj = JSON.parse(msg);
            NameEmploy = obj.NameEmploy; // EmployName
            EntryTime = obj.EntryTime;
            var str1 = "/static/image/";
            var str2 = String(obj.ImageID);
            var str3 = ".jpg";
            res = str1.concat(str2, str3);
        });
         socket.on('image_response', function(msg) {
            obj = JSON.parse(msg);
            if(obj.Image_status == "true"){
                var table = document.getElementById("myTable");
                var row = table.insertRow(1);
                var cell1 = row.insertCell(0);
                var cell2 = row.insertCell(1);
                var cell3 = row.insertCell(2);
                cell1.innerHTML = NameEmploy;
                cell2.innerHTML = EntryTime;
                var img = document.createElement('img');
                img.src = res; 
                img.setAttribute("width", "300");
                img.setAttribute("height", "400");
                cell3.appendChild(img);
                res = "";
                NameEmploy = null;
                EntryTime = null;

            }
        });
     });
 </script>
</head>
<body>
    <div style="width: 100%;height:2000px;overflow-y: scroll">
        <table id="myTable", style="width:100%;height:auto;">
        <tr>
            <th class="centerText">Tên Nhân Viên</th> 
            <th class="centerText">Thời Gian</th> 
            <th class="centerText">Hình</th>
        </tr>
    </table>

    </div>

</body>
</html>`

**Comment by miguelgrinberg** [comment]
So why is this a server issue, if your server works fine with the JS client?

**Comment by tranvinhphuc111996** [comment]
Haha , because i think if js client work well and i saw many example using socketio-client python with flask socketio . sometimes socketio-client python  connect , i think i missing something in sever

**Comment by ShanChuangxin** [comment]
Hello, i had a similar problem too. beside using socketio-client test, i also online test..
http://www.blue-zero.com/WebSocket/
sorry,i am come from china, my english is very poor...
i hope you can understand

**Comment by miguelgrinberg** [comment]
@ShanChuangxin I understand, but you have provided no details regarding your problem.

**Comment by tranvinhphuc111996** [comment]
Oh @miguelgrinberg , i found out. My network have some trouble with socketio-client library. When im try to change another network. it work well ! . Thank for your help @miguelgrinberg
