### ISSUE TITLE
Error for all of flask when installed

### ISSUE THREAD

**Issue by FFORCE-INFO** [miguelgrinberg/Flask-SocketIO#835]
When trying to use Socket IO it causes a whole load of errors even when just trying to run a basic flask app with no Sockets in it.
Here is what the console dumps: https://gist.github.com/fr2955/d0e3c8d117cd8210d68199bb2d2ddd4e
I also tried running PyCharm as admin and it returns the same response. 
I know that this is isolated to Socket IO because when running a code without Sockets installed it will work but when installed it will crash all of flask.

**Comment by miguelgrinberg** [comment]
This is likely a problem in your app. Did you name your application `code.py`, or have a module of that name? Rename it to something else and you will likely avoid this error.
