### ISSUE TITLE
emmiting mousedown event

### ISSUE THREAD

**Issue by fsofras** [miguelgrinberg/Flask-SocketIO#836]
jQuery code:
```
var intervalId;
$("#goL").mousedown(function() {
       intervalId = setInterval(emit_this, 1000);
}).mouseup(function() {
  clearInterval(intervalId);
}).mouseleave(function() {
//this should help solve the problem that occurs when the mouse leaves the button while pressed down
  clearInterval(intervalId);
});

function emit_this() {
            $('form#goL').submit(function(event) {
               socket.emit('L', 'data':'L');
               return false;
           });

}
```

I expect the mousedown event to emit continuous "L"s  but one at the time to the server while the mouse is held down and the server to process each one separately. Instead a number of "L"s is emited and are processed together.
Is there a fault in jQuery or an issue with Flask-socket.io ?
Thank you

**Comment by miguelgrinberg** [comment]
Are you using websocket or polling? with polling things may not work as smoothly.

You can add logging on both sides to see when emits are sent and received, the bug could be in your application if it does anything blocking.

**Comment by fsofras** [comment]
sorry, I should have added more info.
I am using Flash, Flash-socket.io, eventlet.  On client side jQuery and socket.io as per your example in [Flask-SocketIO/example/templates/index.html](url). Here is a simle snippet from python code:

```
@socketio.on('AC')
def way(message):
    global ways_dict
    if ways_dict['newway']=='F' or ways_dict['newway']=='B':
        dc = ways_dict['dc'] + 10
        if dc>100:
            dc=100
        ways_dict['dc'] = dc
        driveit()
        #Motor_dc(0, ways_dict['dc'])
    print( ways_dict['dc'] )
```

I did use logging and it seems that instead of emitting one "L" at a time and repeating this action while the mouse is held down, JS emits all instances of "L" together and when they are received they are executed one by one.
Thank you for taking the time to reply

**Comment by miguelgrinberg** [comment]
Maybe emit directly, instead of emitting in a callback to a form submission?

**Comment by fsofras** [comment]
Thank you
Considering that the app needs a web interface to work, can you suggest how this should be done?

**Comment by miguelgrinberg** [comment]
I don't understand what you are doing. You are artificially triggering a form submission every second. Why submit a form? Can't you just emit the data from the form directly in the Socket.IO event?

**Comment by fsofras** [comment]
Sorry to be a nuisance, but I am rather new to the game.
What I am trying to do is continuously send to the server a value so that will slowly increment and thus gradually continuously (?linearly) increase the speed of an engine.
I am following your code but there maybe another way of doing what I want
thanks again

**Comment by miguelgrinberg** [comment]
Just emit what you want to send to the server then, don't fake a form submission.

**Comment by fsofras** [comment]
thank you for taking the time to assist, although I am not sure what you mean
Maybe we should close this thread

**Comment by miguelgrinberg** [comment]
I'm going to close it per your suggestion, but note that I gave you an alternative implementation of your `emit_this()` function to try instead of your version.
