### ISSUE TITLE
Firefox Issue: The connection to wss://web_page_address was interrupted while the page was loading.

### ISSUE THREAD

**Issue by ragymorkos** [miguelgrinberg/Flask-SocketIO#837]
Hi Miguel,

I am getting the above error on Firefox 63 on Ubuntu 16.04. On Chrome, everything works perfectly. It _sometimes_ works as it should, but most of the time, when I load the page, the websocket transportation between the server and client doesn't happen, then I get the above error in the console after about a minute. I don't refresh or do anything--I just load my application normally in Firefox.

I'm running my Flask-SocketIO as socketio.run(app) on a CentOS server with eventlet installed for concurrency. I pass in my host IP address and run it on port 443, passing in a self-signed certificate and associated key. I see in the network tab that a GET 101 is made, marking the switch to the websocket protocol, so it seems to be working well.

Let me know if you can point me in the right direction. Thanks!

**Comment by miguelgrinberg** [comment]
Does it happen if you remove TLS from your test?

**Comment by ragymorkos** [comment]
It still doesn't work if I remove TLS from my test, and I get the same message. When running my app on localhost, it does work perfectly fine, however.

**Comment by miguelgrinberg** [comment]
Did you ever figure this out? Sorry I dropped the ball.

**Comment by ragymorkos** [comment]
Hi Miguel,

I have postponed tackling this problem as I am addressing other stuff with the web app. For now, it works perfectly fine on Chromium-based web browsers. Feel free to close this issue or leave it open for anyone else who might have the problem in the future, since I still wasn't able to solve it. I'll come back and post my findings once I get to it. Thanks!
