### ISSUE TITLE
Emitting from background thread to the second room blocks the first room 

### ISSUE THREAD

**Issue by Fizmath** [miguelgrinberg/Flask-SocketIO#838]
Hello dear Miguel
changes in ``app.py``

```python3
i = 0 

def background_thread():
    """Example of how to send server generated events to clients."""
    #count = 0
    global i
    while True:
        socketio.sleep(10)
        #count += 1
        socketio.emit('my_response',
                      {'data': 'Server generated event', 'count': count},
                      namespace='/test' , room = i)


@socketio.on('connect', namespace='/test')
def test_connect():
    global thread
    global i
    i += 1
    join_room(i)
    with thread_lock:
        if thread is None:
            thread = socketio.start_background_task(target=background_thread)
    emit('my_response', {'data': 'Connected', 'count': 0})
````

These are the only changes in you example code , client A connects and automatically gets his room and the background thread keeps emitting to  his room , when B connects it get the thread event but  it blocks thread generated event to A and so  on   .. C blocks B ...

**Comment by Fizmath** [comment]
This is a conflicting issue between ``eventlet`` and ``threading```

**Comment by miguelgrinberg** [comment]
I think the confusion here is on your part. There is one one thread, you are not starting a different thread for each client. But even if you were, each thread would be sending events to the room stored in the `i` global variable, so all your threads would then be sending events to the last client. My code is not the right starting point for what you want to do, I'm afraid.

**Comment by Fizmath** [comment]
Yes , that is right . I uncommitted 
```python3
         # if thread is None:
```
what is did it just doubled the thread flow the the latest client .

So , do i need to evade global room variable ?

**Comment by miguelgrinberg** [comment]
Yes, pass the room as an argument to your thread.

**Comment by Fizmath** [comment]
Adding args gives and error

```python3
         thread = socketio.start_background_task(target=background_thread , args = (i,) )
````
![dd](https://user-images.githubusercontent.com/40030502/48899334-61ce9600-ee60-11e8-8e3a-1be95423fab5.JPG)

**Comment by miguelgrinberg** [comment]
Do it like this:

    thread = socketio.start_background_task(background_thread , i)

**Comment by miguelgrinberg** [comment]
If this is a robust application that you are building (i.e. not a quick test) you will need to keep track of those threads and stop them when their respective clients disconnect. The return value from the `start_background_task` function is the thread object, which you can store in a dictionary or similar data structure.

If you want to learn more about how green threads work, I recommend an excellent talk by Dave Beazley titled "concurrency from the ground up". It's on youtube.

**Comment by Fizmath** [comment]
I have learnt python from Dave Beazley's vidoe courses . He taught me not only how to code but also what is like to be a coding expert .

**Comment by miguelgrinberg** [comment]
The implementation is here: https://github.com/miguelgrinberg/python-engineio/blob/master/engineio/server.py#L332

Unfortunately you are not going to find straightforward code there, because starting a thread is different in regular Python vs eventlet vs gevent, so my solution is based on configuration variables that are set different for each of these, but in all cases there is a `Thread` class that creates the thread object, then you call `start()` on this object to start the background thread.

**Comment by Fizmath** [comment]
Ok , Thank you .

I want to start second independent function besides  ```def background_thread():```  , say ```def background_thread_2():```   with just in a single thread object , but the ```target``` gets just one function .
any idea ?

**Comment by miguelgrinberg** [comment]
That's not how threads work. If you need two independent lines of execution, then that's two threads, can't make it one. So you'll need to call `start_background_task()` for each background task.

**Comment by miguelgrinberg** [comment]
No, you seem to be trying to do something that this library doesn't do. Emits go to clients, not to other parts of the server. If you need your threads to pass data around, you need to use threading synchronization primitives and possibly also global variables.

**Comment by Fizmath** [comment]
Ok , thank you very much .

**Comment by srianbury** [comment]
Is there a way to set the max number of workers with socketio.start_background_task?  I believe I have seen it with thread or another concurrency library.

**Comment by miguelgrinberg** [comment]
@srianbury no, I think what you refer is a thread pool, which something more sophisticated than this function. You should look within the concurrency library that you are using to see what options for pools of workers they offer.

**Comment by srianbury** [comment]
Okay will do!

p.s. I see you actively answer questions and issues and I very much appreciate it.  I have resolved many problems by reading a lot of your comments.
