### ISSUE TITLE
Client disconnects 

### ISSUE THREAD

**Issue by sirc-yuv** [miguelgrinberg/Flask-SocketIO#839]
Hello,
I am using Flask 0.12 ,Flask-socketIO 3.0.1, enventlet (I get "Upgrade to websocket successful")
The server receiving text commands from a client using  WebSockets and sending back text messages, with the results of the command. 
A command runs some python code.

When the operations became a bit long, say 1 minunte,  the client dropped the connection and the server's 'emit' with the status failed and client got an error.
I moved the lengthy operation to a thread, and waited on that thread with a socketio backgroud_thread,
and still the connection is dropped.
Getting in with debugger shows that there is PING PONG packets, until the longer/heavier operations, and then on call to emit I get .
"Client is gone, closing socket"
Any help is appreciated!
Thanks,

**Comment by sirc-yuv** [comment]
Thanks for the prompt response.
I call another library which is probably doing some heavy job.
What would you reccomend for best practice for this?

Samsung Semiconductor Israel R&D Center Ltd

-------- הודעה מקורית --------
מאת: Miguel Grinberg <notifications@github.com<mailto:notifications@github.com>>
תאריך: יום ה׳, 22 בנוב׳ 2018, 18:26
עד: miguelgrinberg/Flask-SocketIO <Flask-SocketIO@noreply.github.com<mailto:Flask-SocketIO@noreply.github.com>>
עותק: Yuval Nahmany <yuval.n@samsung.com<mailto:yuval.n@samsung.com>>,Author <author@noreply.github.com<mailto:author@noreply.github.com>>
נושא: Re: [miguelgrinberg/Flask-SocketIO] Client disconnects  (#839)

What are you doing on these lengthy Python commands? If those make blocking calls, then that's a problem.

**Comment by miguelgrinberg** [comment]
It really depends on the exact nature of the work, I cannot give you a general response. For certain things monkey patching the standard library for eventlet compatibility is all it takes. If the work involves heavy CPU calculation, then maybe offloading to a separate process via Celery or similar might be necessary to prevent blocking in the server process.

**Comment by sirc-yuv** [comment]
Thanks.
This python library I am calling holds large objects with their state.
Seems that I have to call function separately in a process. Not sure how much is this possible.
If I try so, Celery would be the choice?
Can I emit messages from the separate process, or I can run it and wait/sleep in a thread on the Flask app, on an event on that process?

Kind Regards,

**Comment by miguelgrinberg** [comment]
The setup required to be able to emit Socket.IO events from a secondary process such as a Celery worker is more complex, but this is possible. You'll need to set up a job queue such as Redis or RabbitMQ (which you will also need to use Celery). The documentation has the details on how to configure this.

**Comment by sirc-yuv** [comment]
Thanks Miguel.
So, if I understand this correctly, this is the only way to run a heavy op’ from the server? (I would like to communicate the results of the process to the client.)

**Comment by miguelgrinberg** [comment]
No, it's not the only way. I told you the solution would be different depending on what you are doing in those tasks. You didn't say what they do, so take this just as options in general. You may want to read up on green threads and asynchronous programming to have a better idea of how to proceed.

**Comment by sirc-yuv** [comment]
It is a library with some init’ , and functions that may load the cpu or take longer than the connection timeout. It involves image processing, but I don’t know about the implementation.
The server is meant for decoupling the UI tech from the python library.
So if threads (that I cannot control their priority) with heavy calc’ will anyway disable the PING/PONG on the connection and it drops, I’ll be happy to consider something else.

Thanks!

**Comment by miguelgrinberg** [comment]
I can't really change my answer, based on the little information you are giving me. If you don't have control or understanding of this library that you are using then offloading it to a separate process will definitely help. But if you do have control of the code in this library then maybe there are other less drastic options.

One thing I'm telling you with certainty: not understanding how asynchronous systems work, and in particular how green threads are used in them, is going to make everything look much harder.

**Comment by sirc-yuv** [comment]
That’s ok.
Sometimes you don’t have control over all the code, and sometimes you have a black box.
I am not familiar with green threads, but I will take your advice.
Thanks,
I will update on this email thread.

**Comment by sposs** [comment]
Funny, I'm experiencing similar issues: I start a background thread with `socketio.start_background_task` and see that blocking calls in the function started with the bkg thread need to be 'fast'. In my case, I'm 'POST'ing data using `requests` (can take > 1 minute). 
So, if I understand properly the above: I need to make sure that whatever I run in the bkg task is faster than the ping_timeout, otherwise I may end up with a lost connection. Is that correct? I thought the point of the `start_background_task` was to allow parallel running, irrespective of the time taken to run the background task... I guess I misunderstood something.

**Comment by sposs** [comment]
Actually, I have the global monkey patch at the top of my flask code... I read from https://stackoverflow.com/questions/28315657/celery-eventlet-non-blocking-requests that it should be enough...

**Comment by sposs** [comment]
It appears, finally, that the problem I have is not with requests. There is a `for row in c.execute("SELECT id, data FROM %s;" % table_to_use):` in my code. This table contains > 1 million rows so of course it takes a long time to get the content, and blocks the whole time. :-(

**Comment by miguelgrinberg** [comment]
@sposs monkey patching the standard library for Eventlet might help in your case. See http://eventlet.net/doc/patching.html.

**Comment by sposs** [comment]
As stated above, I already monkey patch globally. But, now that I've added print lines, it looks like the connection is closed before the code reaches the SQLite interactions. This is very strange... I used to have a time.sleep(10) which I replaced by socketio.sleep(). Still, the connection is closed eventually. I'll produce a 'short' version of my code and report back here, as maybe I'm missing something.

**Comment by sposs** [comment]
I have found a 'problem' with the sqlite3 python lib: it is not monkey_patchable... Moreover, I had in my code
```python
c.execute("SELECT something;")
r = c.fetchone()
while r:
    # do something with r
    r = c.fetchone()
```
But that also is blocking. To sort it out, I have now
```python
c.execute("SELECT something;")
r = c.fetchone()
while r:
    # do something with r
    socketio.sleep(0.001)
    r = c.fetchone()
```
This way the pings are replied to, and the connection is not lost.

I don't know how to address this, maybe it could be worth documenting in this project's doc..

**Comment by miguelgrinberg** [comment]
SQLite uses file I/O which in most operating systems is blocking. Adding a sleep like you did is actually a good solution. For this type of thing a `sleep(0)` call is used instead of a positive number.

**Comment by sposs** [comment]
Thanks for the clarification! I figured that DB servers would be suitable, unfortunately, I cannot use those. 
I have changed the sleep time. Looks like this works like a charm now!

**Comment by mohanboda** [comment]
I have a Flask web app. It has simple web page which accepts file as input . Once i receive file input from user , i am loading the excel file to workbook using python , based on the file size it takes more than 1 minute, during this time client gets disconnected (because pong is not received ). What is the solution for this problem ?. How can i keep client connected ? . I tried **sleep(0)** also, it did not work.

`from openpyxl import load_workbook
 external_report_wb=load_workbook(external_report_file)`

**Comment by miguelgrinberg** [comment]
@mohanboda unfortunately you cannot have code that blocks for so long. If this library has the option to read the file one row at a time, for example, then you can add `sleep(0)` statements after each row, and that should help. If that is not an option, then another option to consider is putting this call in a separate thread. If you are using eventlet, the [tpool](https://eventlet.net/doc/threading.html) module manages a thread pool that can be used to launch blocking operations.

**Comment by mohanboda** [comment]
Thanks for the quick reply . I will explore the options on the suggested solution. I have another query.
Client re-connects to the  same namespace and room  , is there any way to resend the lost messages to the client ?

**Comment by miguelgrinberg** [comment]
> Client re-connects to the same namespace and room , is there any way to resend the lost messages to the client ?

Messages are delivered immediately and are not cached, so no, this package cannot resend past messages.
