### ISSUE TITLE
Example files result in error

### ISSUE THREAD

**Issue by throwaway556** [miguelgrinberg/Flask-SocketIO#843]
When I run a git clone on the repo and do a 'pip install -r requirements.txt' in a virtualenv on the requirements.txt in the examples file and run the app.py I get this error message.

127.0.0.1 - - [25/Nov/2018 19:37:45] "GET /socket.io/?EIO=3&transport=polling&t=1543192665198-0 HTTP/1.1" 404 -
127.0.0.1 - - [25/Nov/2018 19:37:46] "GET /socket.io/?EIO=3&transport=polling&t=1543192666298-1 HTTP/1.1" 404 -
127.0.0.1 - - [25/Nov/2018 19:37:47] "GET /socket.io/?EIO=3&transport=polling&t=1543192667657-2 HTTP/1.1" 404 -
127.0.0.1 - - [25/Nov/2018 19:37:49] "GET /socket.io/?EIO=3&transport=polling&t=1543192669968-3 HTTP/1.1" 404 -

I am running this on Ubuntu 18.04 using python3.6.6 and a fresh virtualenv. None of the files have been tampered with and I am running on the master branch.
The pip freeze is below:
Click==7.0
Flask==0.12.2
Flask-Login==0.4.0
Flask-Session==0.3.1
Flask-SocketIO==3.0.2
itsdangerous==0.24
Jinja2==2.7.3
MarkupSafe==0.23
python-engineio==3.0.0
python-socketio==2.0.0
six==1.9.0
Werkzeug==0.12.2

Thanks for your support

**Comment by bkolbeck** [comment]
Experiencing the same on Windows and MacOS.

**Comment by lovelyzhang** [comment]
Same problem

**Comment by miguelgrinberg** [comment]
My bad. I've made some changes in a dependency that inadvertently affected this package. Please upgrade flask-socketio and python-socketio and I think you will be fine.

**Comment by throwaway556** [comment]
appears to work now.
Thanks
