### ISSUE TITLE
I observed Transport = polling in the request

### ISSUE THREAD

**Issue by tahir80** [miguelgrinberg/Flask-SocketIO#844]
Hi Miguel,

I can also see that my transport  = polling despite the fact that I am using flask-socketio
**at=info method=POST path= "/socket.io/?EIO= 3&transport= polling**

I am using flask-socketio 

Procfile is:
web: gunicorn -k eventlet run:flask_app

Requirements are (sorry for long list):
asn1crypto==0.24.0
attrs==18.1.0
autobahn==18.6.1
Automat==0.7.0
bcrypt==3.1.4
certifi==2018.4.16
cffi==1.11.5
chardet==3.0.4
click==6.7
constantly==15.1.0
cryptography==2.2.2
dominate==2.3.1
enum34==1.1.6
Flask==1.0.2
Flask-Bcrypt==0.7.1
Flask-Bootstrap==3.3.7.1
Flask-Login==0.4.1
Flask-SQLAlchemy==2.3.2
Flask-WTF==0.14.2
gunicorn==18.0
hyperlink==18.0.0
idna==2.7
incremental==17.5.0
ipaddress==1.0.22
itsdangerous==0.24
Jinja2==2.10
MarkupSafe==1.0
oocsi==0.4
Pillow==5.1.0
psycopg2==2.7.5
pyasn1==0.4.3
pyasn1-modules==0.2.2
pycparser==2.18
pyOpenSSL==18.0.0
python-dateutil==2.7.3
requests==2.19.1
scipy==1.0.0
service-identity==17.0.0
six==1.11.0
SQLAlchemy==1.2.10
Twisted==18.4.0
txaio==2.10.0
Unidecode==1.0.22
urllib3==1.23
virtualenv==16.0.0
visitor==0.1.3
Werkzeug==0.14.1
ws4py==0.5.1
WTForms==2.2.1
zope.interface==4.5.0
watson-developer-cloud==1.4.1
boto==2.49.0
Flask-SocketIO==3.0.2
gevent==1.3.6
eventlet==0.24.1
Flask-Script==2.0.6
Flask-Migrate==2.3.0
boto3==1.9.42
gevent-websocket==0.10.1

**Comment by miguelgrinberg** [comment]
All connections start as polling, and later upgrade to websocket. Seeing a polling request in the logs does not indicate any problem. If you see constant HTTP requests flying by in the logs, then maybe you do have a problem, but normally that is not the case, after a handful of HTTP requests the websocket connection is established and the polling transport is not used anymore.
