### ISSUE TITLE
Hiding emit in @app.route and shared lists of in-out data

### ISSUE THREAD

**Issue by Fizmath** [miguelgrinberg/Flask-SocketIO#846]
Dear miguel 

Let's say that we have dummy code like this :  
```python3
roo = ["a","b" , "c","d"]
i =0

input = []
output = []

@socketio.on('input', namespace='/test')
def test_message(inp):
    if inp:
        input.append(inp)
        output = input.pop(0)

@socketio.on('connect', namespace='/test')
def test_connect():
    global i
    i += 1
    print(roo[i])
    join_room(roo[i])   # join to the newly created room automatically

@app.route('/show')
def ff():
    for data in output:
            socketio.emit('from_flask', {'data': data }, namespace='/test', room=roo[i])
````
1  - We have hided all socketio inside a button in javascript side so after loading the server we push this buttun to start socketio ,  here is an issue :  ``@app.route('/show')``  loaded immediately and does't wait for the socket button  so ``i = 0`` but when clicking start socket button ``i +=`` so we emit to the wrong room , how can we hide the ```from_flask``` event on http until initializing socket ? 

 2 - While the server running , the lists ``` input , output ``` gets data from  client A , but when client B connects these lists get mixture of both client's data : how can we allocate individual  data lists for any newly connected clients (we run the server in gunicorn and eventlet )?

or , are there better implementations for these purposes ?

**Comment by miguelgrinberg** [comment]
Isn't your client sending the `/show` request too early? If you want to wait until the socket.io button is pressed, then make your client wait to send this request until then. Maybe I'm missing something, but you seem to imply that the `/show` request happens automatically at the start, but it must be your client sending the request, right? So you can fix your client to send the request at the proper time.

For the second question, you can use independent lists for each client. Something like this:

```python
input = {}
output = {}

@socketio.on('input', namespace='/test')
def test_message(inp):
    if request.sid not in input:
        input[request.sid] = []
    if request.sid not in output:
        output[request.sid] = []
    if inp:
        input.append(inp)
        output = input.pop(0)
```

**Comment by Fizmath** [comment]
Here is a more general problem  , 

We receive streaming data ``inp`` from JavaScript :   

```python3
socketio = SocketIO(app, manage_session=False, async_mode=async_mode)

clients = ["O","A","B","C","D"]
i =0
input = {}
output = {}

@socketio.on('input', namespace='/test')
def test_message(inp):    
    if inp:
        input[clients[i]].append(inp)
        output = input[clients[i]].pop(0)


@socketio.on('connect', namespace='/test')
def test_connect():
    global i 
    i += 1	
    join_room(clients[i])
    if clients[i] not in input:    #  register new clients on-fly  get empty lists for them
        input[clients[i]] = []
    if clients[i] not in output:
        output[clients[i]] = []
		
def gen(j):
    while True:
        fin = stream(j)
        yield fin

def stream(j):
    while not output[clients[j]]:   # if output [] is empty sleep 1 second 
          sleep(1)
    return output[clients[j]].pop(0)    # return what is inside output whilst emptying the list		

@app.route('/show')
def ff():
    global i
    while i==0:    #  first page loaded , avoiding "unknown i " error
         sleep(0.05)
    for data in gen(i):
            socketio.emit('from_flask', {'data': data }, namespace='/test', room=clients[i])
```

as i said before there is a connect button on JavaScript side ,  after running Gunicorn-Eventlet server ``@app.route('/show')`` waits until first client "A" connects  , he gets his own lists and the ``output`` fills then empties .  But when second client "B" connects  ``i=2``  the problem would appear in ``@app.route('/show')`` , it seems that it does not change into ``client[2]`` whiles keeping ``client[1]`` on process .  Every thing is OK in `` input event ``  , the problem is synchronization with ``@app.route('/show')`` for simultaneous clients 
i wish i could describe the problem , anyway , is everything OK with above code ?

**Comment by Fizmath** [comment]
I didn't close the issues , it closed by it's own !!

**Comment by Fizmath** [comment]
Ok , thank you
