### ISSUE TITLE
Broken dependencies

### ISSUE THREAD

**Issue by olii** [miguelgrinberg/Flask-SocketIO#848]
Latest release of `flask-socketio` requires the `python-socketio` in version `2.1.0`.

When I updated the module in my project with `pip` I got this error:
```
AttributeError: module 'socketio' has no attribute 'WSGIApp'
```
After some investigation I found out the `python-socketio` was not updated. 

I think you should reflect it in the setup file. 
https://github.com/miguelgrinberg/Flask-SocketIO/blob/06026993cc11b3ec532c4aecb3cab504a7a261ca/setup.py#L34

**Comment by miguelgrinberg** [comment]
Ah, yes, sorry about that. I'll correct the dependencies.

**Comment by miguelgrinberg** [comment]
This should be fixed now. Sorry for the error.
