### ISSUE TITLE
SocketIsClosedError after a while on AWS EC2

### ISSUE THREAD

**Issue by kllr** [miguelgrinberg/Flask-SocketIO#850]
Hi,

I'm running a flask-socketio on my ubuntu ec2 server. It uses a apache2 webserver.
Installation goes well and it works for a couple of days but then this error occurs.
After the error the sockets are down. No disconnect is triggered so i can't act on it it seems.
The client is an iPad2 with safari.

Any suggestions how to fix this?

the error
----------------------------
15:29:00,490 engineio ERROR service task exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/engineio/server.py", line 528, in _service_task
    s.check_ping_timeout()
  File "/usr/local/lib/python2.7/dist-packages/engineio/socket.py", line 72, in check_ping_timeout
    raise exceptions.SocketIsClosedError()
SocketIsClosedError

**Comment by miguelgrinberg** [comment]
Does this happen with the latest version of the python-engineio package? I believe I fixed this already.

**Comment by kllr** [comment]
python-engineio==2.3.2

**Comment by miguelgrinberg** [comment]
First of all, as I said above, you need to upgrade to the latest version. Second, even if you get this error, there shouldn't be an interruption, everything should continue to work. All the error is saying is that some client unexpectedly disappeared. The disconnect handler should have been invoked for this client by the time this error is shown in the logs.

**Comment by kllr** [comment]
Hi, i've upgraded the code to Quart with websockets instead of Flask and Socket-io. The disconnects are gone now. 
Thanks for your help anyway, this was for now the fastest option to do.
