### ISSUE TITLE
Gevent MonkeyPatch error

### ISSUE THREAD

**Issue by kllr** [miguelgrinberg/Flask-SocketIO#851]
Hi Miguel,

As of today this warning comes up. Before this didn't show. As far as i know i didn't change anything that could set this off. (but i could be wrong :) ) 

C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flask_socketio\__init__.py:549: 
MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. It may also silently lead to incorrect behaviour on Python 3.7. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016. 

Modules that had direct imports (NOT patched): ['urllib3.util (C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\site-packages\\urllib3\\util\\__init__.py)', 'urllib3.contrib.pyopenssl (C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\site-packages\\urllib3\\contrib\\pyopenssl.py)']. 
  monkey.patch_all()
```

#!/usr/bin/env python
from flask import Flask, redirect, request, render_template, Response, url_for, session, abort, flash
# from flask_uploads import UploadSet, configure_uploads, IMAGES
from flask_socketio import SocketIO, emit, join_room, leave_room, close_room, rooms, disconnect
from flask_login import LoginManager, UserMixin, login_required, login_user, logout_user, current_user
import traceback
from threading import Lock
import time
import pandas as pd
from pandas import Grouper
import xlsxwriter
from datetime import datetime
from helpers import SurveyScore, Survey, SurveyScoreBreakdown
from raven import Client
from passlib.hash import pbkdf2_sha256
import uuid
import datetime
import time
from math import isnan

async_mode = None
app = Flask(__name__)
socketio = SocketIO(app, async_mode=async_mode)
thread = None
thread_lock = Lock()

# flask-login
login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = "login"

if __name__ == "__main__":
    socketio.run(app, host='0.0.0.0', port=443)

```

**Comment by miguelgrinberg** [comment]
Shouldn't you be asking the Gevent people about this? How is it related to Flask-SocketIO, which does not even need monkey patching?

**Comment by kllr** [comment]
Hi,
Thanks for your reply. I'll go look into that. 
I'm new to socketIO (and monkeypatching). 
The log said that the error was coming from Flask-SocketIO, that's why i opened the issue. If this was incorrect i'm sorry :)

The error was in line 549 of flask_socketio/__init__.py:
``
            if use_reloader:
                # monkey patching is required by the reloader
                from gevent import monkey
                monkey.patch_all()

**Comment by miguelgrinberg** [comment]
It's not a problem. Typically an application that uses threads, locks, or sockets needs to be monkey patched to work with Gevent. Flask-SocketIO does not require monkey patching itself, but Flask's reloader does. In your case, since you are using locks and threads, you should monkey patch before you import those affected modules. The error that you are getting is related to monkey patching too late in the life of the application. See http://www.gevent.org/api/gevent.monkey.html for more information on Gevent's monkey patching.
