### ISSUE TITLE
Handling incoming streaming data

### ISSUE THREAD

**Issue by Fizmath** [miguelgrinberg/Flask-SocketIO#856]
Hello ;

Imagine that we are receiving steaming data ``inp``  coming every 1 second  and feed them into time consuming process which take say ,for example 3 seconds to complete depending on CPU or ... , so . while these proceeding are going on we are still receiving ``inp`` and they are just piling up and waiting until the processes are done , here is a question :  is it possible to DELETE these incoming ``inp`` until the processes are done and then feed the newest ``inp`` into the process ? 

```python3



@socketio.on('input', namespace='/test')
def test_message(inp):
    if inp:
        input.append(inp)
        #  here do time consuming proceess longer than incoming inp
        return input.pop(0)
        

```

**Comment by miguelgrinberg** [comment]
> and feed them into time consuming process which take say ,for example 3 seconds to complete depending on CPU

This is a red flag. You can't have CPU heavy processes in an asynchronous application. Consider offloading the CPU work to another process, or if you must keep it in the same process, make sure it yields the CPU often by calling `socketio.sleep(0)`.

With that caveat, yes, you should be able to do what you want. It could be something like this:

```python
background_task_running = False

@socketio.on('input', namespace='/test')
def test_message(inp):
    if not backgroup_task_running:
        background_task_running = True
        socketio.stack_background_task(bg_task, inp)
    else:
        print('ignoring input while bg task is running...')

def bg_task(inp):
    #  here do time consuming proceess longer than incoming inp
    background_task_running = False
```

**Comment by Fizmath** [comment]
Ok , thank you 
Where do these ``inp`` piling up inside Socket Io  while the function is delaying to consume them   ?  is there any internal  evanescent data saving system in Socket Io ? so we could ``empty`` it  .

**Comment by miguelgrinberg** [comment]
@Fizmath not sure I understand what you are asking. There is nothing getting queued, all the inputs are consumed the moment they arrive. Some are thrown away, while others are used, but all are processed immediately.

**Comment by Fizmath** [comment]
Yes  , that is the answer to my question  , there is no on-fly data saving in Socket Io, incoming data either consumed by a function or other way deleted spontaneously .   

Thank you very much for you quick response .

**Comment by Fizmath** [comment]
> > and feed them into time consuming process which take say ,for example 3 seconds to complete depending on CPU
> 
> This is a red flag. You can't have CPU heavy processes in an asynchronous application. Consider offloading the CPU work to another process, or if you must keep it in the same process, make sure it yields the CPU often by calling `socketio.sleep(0)`.
> 
> With that caveat, yes, you should be able to do what you want. It could be something like this:
> 
> ```python
> background_task_running = False
> 
> @socketio.on('input', namespace='/test')
> def test_message(inp):
>     if not backgroup_task_running:
>         background_task_running = True
>         socketio.stack_background_task(bg_task, inp)
>     else:
>         print('ignoring input while bg task is running...')
> 
> def bg_task(inp):
>     #  here do time consuming proceess longer than incoming inp
>     background_task_running = False
> ```

```socketio.start_background_task(bg_task, inp)```  no documnets on ```stack_background_task```
