### ISSUE TITLE
Async_mode Eventlet on Gunicorn  and  Lock from threading 

### ISSUE THREAD

**Issue by Fizmath** [miguelgrinberg/Flask-SocketIO#857]
Hello : 
From your example ``app.py``
```python3

from threading import Lock

#  eventlet installed 
async_mode = None

socketio = SocketIO(app, async_mode=async_mode)
thread = None
thread_lock = Lock()

@socketio.on('connect', namespace='/test')
def test_connect():
    global thread
    with thread_lock:    #  which thread lock ,  while everything running on eventlet ?
        if thread is None:
            thread = socketio.start_background_task(background_thread)


```
running this  shows ``async_mode = eventlet``  , but , wait a minute !  the socketio async mode chosen to be `` eventlet ``  so the ``socketio.start_background_task(background_thread)`` also runs on ``eventlet`` right ? since it uses `` eventlet `` shouldn't we use `` LOCK()`` object  form  ``eventlet`` instead of ```from threading import Lock``` ?  or there is no difference between them ?

**Comment by miguelgrinberg** [comment]
Yes, it would be better to use an eventlet lock, or monkey patch the standard library, so that the threading lock is replaced with the eventlet lock.
