### ISSUE TITLE
how many socketio concurrent connection? 

### ISSUE THREAD

**Issue by sm-b** [miguelgrinberg/Flask-SocketIO#859]
hi .i'm using the amazing micro-framework(flask + flask-socketio) .... i have server which code is

```python
from flask import  request
from flask_socketio import SocketIO, Namespace


import eventlet
eventlet.monkey_patch()


class Chat(Namespace):
    def on_connect(self):
        print(request.sid, "on address ", request.remote_addr, " has connected")

    def on_disconnect(self):
        print(request.sid," has disconnected")

def init_chat(app):
    socket_io = SocketIO(app)
    socket_io.on_namespace(Chat("/chat"))
    socket_io.run(app, host="0.0.0.0", port=5000)




```

**and the client is** 

```python
from socketIO_client import SocketIO, BaseNamespace


class MyClass(BaseNamespace):
    def on_connect(self):
        print("connected")

    def on_new_msg(self, msg):
        print(msg)



for i in range(0,10000):
    socketIO = SocketIO("localhost", 5000)
    chat_instance = socketIO.define(MyClass,"/chat")

    print(i)

```
in the client the for loop will not go more than 510 ...i think the server does not accept more than 510 concurrent connection . how can increase this number?. Am i doing anything wrong?

**Comment by miguelgrinberg** [comment]
This really depends on the web server that you are using. The SocketIO code does not have a limitation on clients. It looks like you are using the Eventlet web server, so check out the documentation: http://eventlet.net/doc/modules/wsgi.html#wsgi-wsgi-server. The `max_size` argument defines the maximum number of connections.

**Comment by sm-b** [comment]
> This really depends on the web server that you are using. The SocketIO code does not have a limitation on clients. It looks like you are using the Eventlet web server, so check out the documentation: http://eventlet.net/doc/modules/wsgi.html#wsgi-wsgi-server. The `max_size` argument defines the maximum number of connections.

**Comment by sm-b** [comment]
> This really depends on the web server that you are using. The SocketIO code does not have a limitation on clients. It looks like you are using the Eventlet web server, so check out the documentation: http://eventlet.net/doc/modules/wsgi.html#wsgi-wsgi-server. The `max_size` argument defines the maximum number of connections.

thanks for your help...i got an another question ...i wanna subscribe on channels (redis) in flask-socketio when user connect ...is it good to use threading.Thread ?

**Comment by miguelgrinberg** [comment]
You monkey patched the standard library, so yes, threading is safe to use within your Eventlet web server.
