### ISSUE TITLE
close sockeio connection with response body

### ISSUE THREAD

**Issue by sm-b** [miguelgrinberg/Flask-SocketIO#861]
how can i disconnect socket with response body ...
```python
@socket.on("auth")
def on_auth():
    #
    #
    #
    response ={
        "code": 401
    }
    disconnect()
    return json.dumps(response)
```
does it work ....i mean i first disconnect the connection and then send response

**Comment by miguelgrinberg** [comment]
No, you can't customize the HTTP response codes with Socket.IO. You can probably do it by intercepting the request in a WSGI middleware.
