### ISSUE TITLE
How to emit message from module

### ISSUE THREAD

**Issue by M1CK431** [miguelgrinberg/Flask-SocketIO#862]
Hi,

I'm build my first Python app (which is also my first backend app). I'm using Flask and Connexion.
Now I'm trying to add realtime support using Flask-SocketIO.

Here is (part of) my `server.py` file:
```python
import connexion
from flask_socketio import SocketIO

app = connexion.App(__name__, specification_dir='./')
app.add_api('swagger.yml')

flask_app = app.app
socketio = SocketIO(flask_app)

if __name__ == '__main__':
    socketio.run(
        flask_app,
        host=0.0.0.0,
        port=5000,
        debug=True
    )
```

If in this file I add something like this:
```python
@app.route("/event", methods=['GET'])
def event():
    socketio.emit('alive', {'alive': True})
    print('alive')
    return ''
```
It works perfectly.

Now because I use Connexion, I have also some other files with functions which will be called depending on the route. My goal is to be able to emit message from one of them.

Here is a trivial example of what I have try (but doesn't works):
```python
from __future__ import unicode_literals
from flask import current_app
from flask_socketio import SocketIO

def socketio_emit(name, message):
    socketio = SocketIO(current_app._get_current_object())
    socketio.emit(name, message)

def version():
    socketio_emit('version', {'api': '0.1'})
    return { 'api': '0.1'}
```

I don't understand why it doesn't work. I haven't any error message.
I'm absolutely sorry if I'm asking for something which is probably very easy but I have search during 3 days in documentation and/or example without finding any way to solve this issue.

**Comment by miguelgrinberg** [comment]
You are creating a different `SocketIO` object, so your emits are not routed through the server process that is running. You need to import the `socketio` instance that you created in your server.py and emit through that object.

**Comment by M1CK431** [comment]
Hi @miguelgrinberg and thanks for this quick reply :+1: 

I well understand your point but I don't know how to import the `socketio` instance from `server.py`?

**Comment by miguelgrinberg** [comment]
Well, I don't know either because I don't know how your project is structured. Try this:

```python
def socketio_emit(name, message):
    from server import socketio
    socketio.emit(name, message)
```

You can also move the import to the top of the module and see if it works there (you may get circular dependency errors).

**Comment by M1CK431** [comment]
I have just modify my code following your advise and now I have:
in `server.py`:
```
import connexion
from flask_socketio import SocketIO

app = connexion.App(__name__, specification_dir='./')
app.add_api('swagger.yml')

flask_app = app.app
socketio = SocketIO(flask_app)

# test
@app.route("/event", methods=['GET'])
def event():
    socketio.emit('alive', {'alive': True})
    print('alive')
    return ''


if __name__ == '__main__':
    socketio.run(
        flask_app,
        host=0.0.0.0,
        port=5000,
        debug=True
    )

```

in `version.py`:
```
from __future__ import unicode_literals


def socketio_emit(name, message):
    from server import socketio
    socketio.emit(name, message)


def version():
    socketio_emit('version', {'api': '0.1'})
    return {'api': '0.1'}

```

But it doesn't work :disappointed: 
I haven't any error but I don't receive the emitted message.

About my project structure (because I know it's very difficult to help someone without enough context):
src/
  |_ server.py
  |_ swagger.yml
  |_ modules/
            |_ version.py
Of course I have other files but here are only the file concerned by my problem.

A last thing which can be useful (perhaps), is (part of) the content of `swagger.yml`:
```
paths:
  /version:
    get:
      operationId: "modules.version.version"
      tags:
        - "Information"
      summary: "Version of API"
      description: "Get the version of this API"
      responses:
        200:
          description: "Successful read version operation"
          schema:
            type: "object"
            properties:
              api:
                type: "string"
```

**Comment by miguelgrinberg** [comment]
Who cals your `version()` function? It does not appear to be called anywhere.

**Comment by M1CK431** [comment]
In swagger.yml there is an operationId which is used to call the version function on /version GET route. Connexion do the link between route/method and the logic behind the route this way.

**Comment by miguelgrinberg** [comment]
Ah, okay. You may want to add logging to see if the function is called and the emit is processed. Just add `logger=True` to your `SocketIO` constructor. Then add logging on your client to see if the emit is being received.

**Comment by M1CK431** [comment]
I have successfully enable the logger in `server.py` this way:
```python
flask_app = app.app
socketio = SocketIO(flask_app, logger=True)
```
And now when I'm calling `/version` GET route, I have this in the console output of the API:
```bash
$ python src/server.py 
socketio in server: <flask_socketio.SocketIO object at 0x7fa38cb56518>
 * Restarting with stat
socketio in server: <flask_socketio.SocketIO object at 0x7f3ff1285630>
 * Debugger is active!
 * Debugger PIN: 256-773-169
(12336) wsgi starting up on http://0.0.0.0:5000
(12336) accepted ('127.0.0.1', 36458)
socketio in server: <flask_socketio.SocketIO object at 0x7f3fefe20128>
socketio in version: <flask_socketio.SocketIO object at 0x7f3fefe20128>
emitting event "version" to all [/]
127.0.0.1 - - [26/Dec/2018 13:43:47] "GET /version HTTP/1.1" 200 157 0.068987
```

If I have well understand there is also a logger to enable at socketio client side. I'm using `socket.io.slim.dev.js` from https://github.com/socketio/socket.io-client. I will search in the documentation.

**Comment by M1CK431** [comment]
I just discover something. As you probably remember, I have a `/event` GET route for test purpose in my `server.py` file. I have just modify it this way:
```python
@app.route("/event", methods=['GET'])
def event():
    socketio.emit('alive', {'alive': True})
    print('socketio in server (event route)', socketio)
    print('alive')
    return ''
```

Now I have try to call `/version` (define in my `swagger.yml`) then `/event` route (define directly in `server.py` using `@app.route`) and here is the output in the console of my API:
```bash
$ python src/server.py 
socketio in server: <flask_socketio.SocketIO object at 0x7f009bfe8b00>
 * Restarting with stat
socketio in server: <flask_socketio.SocketIO object at 0x7f05c4c93588>
 * Debugger is active!
 * Debugger PIN: 256-773-169
(12580) wsgi starting up on http://0.0.0.0:5000
(12580) accepted ('127.0.0.1', 37068)
socketio in server: <flask_socketio.SocketIO object at 0x7f05c382f080>
socketio in version: <flask_socketio.SocketIO object at 0x7f05c382f080>
emitting event "version" to all [/]
127.0.0.1 - - [26/Dec/2018 13:50:36] "GET /version HTTP/1.1" 200 157 0.066981
(12580) accepted ('127.0.0.1', 37092)
emitting event "alive" to all [/]
socketio in server (event route) <flask_socketio.SocketIO object at 0x7f05c4c93588>
alive
127.0.0.1 - - [26/Dec/2018 13:50:40] "GET /event HTTP/1.1" 200 115 0.001125
```

It seems that when I'm calling a route defined using `Connexion` my `server.py` is re-run (don't know why) and so a new `socketio` object is created. It's this object which is then imported in my `version` function.

But, the good (working) `socketio` object is the one created just after the line ` * Restarting with stat`:
```bash
 * Restarting with stat
socketio in server: <flask_socketio.SocketIO object at 0x7f05c4c93588>
```
because it's this one which is used in my `/event` test route and it works.

I'm not sure but it seems that there is a strange behavior when using Connexion (re-run `server.py`) and that's the root cause of this issue. Is Connexion (kind of) conflict with Flask-SocketIO? WDYT?
