### ISSUE TITLE
message_queue isn't working

### ISSUE THREAD

**Issue by ericman93** [miguelgrinberg/Flask-SocketIO#864]
Hey 

When adding `message_queue="redis://"` to socketio, client's `on` method is never fired. 
I tried embedded,  gunicon and uwsgi deployment. 
Same when num of workers is 1.

**server**
```
app = Flask(__name__)
socketio = SocketIO(app, message_queue='redis://') # tried redis://localhost:6379/2 too but it isn't working
```

**client (socketio-client)**
```
session = io('/', {
    reconnection: true,
    reconnectionDelay: 500,
    reconnectionAttempts: 10
});

session.on('connect', () => {
    alert('connected');
})
```

And another question :)
I'm running flask-socketio over gunicron with 1 worker.
My app is using only rooms and I never send a message to a single user, should it be ok to use gunicron and not uwsgi with load balancer?

**Comment by miguelgrinberg** [comment]
Any error messages in the server's log? Please enable verbose logging by adding `logger=True, engineio_logger=True` to your `SocketIO` constructor.

**Comment by miguelgrinberg** [comment]
That's really not possible, once you enable logging you should see some new stuff in the terminal. Can you show me what you see right after you start the server?

**Comment by ericman93** [comment]
those are the log right after I start the server
```
DEBUG:passlib.registry:registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
INFO:werkzeug: * Restarting with stat
pydev debugger: process 5582 is connecting

DEBUG:passlib.registry:registered 'pbkdf2_sha256' handler: <class 'passlib.handlers.pbkdf2.pbkdf2_sha256'>
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 111-760-464
(5582) wsgi starting up on http://0.0.0.0:1337
(5582) accepted ('127.0.0.1', 59805)
```

I just updated the version from `2.9.3` to the newest one
When adding `message_queue` all requests to the server got stuck and after a while I'm getting
```
Error occured while trying to proxy to: localhost:8080/user
```
I'm working with webpack and this is how the proxy look like
```
proxy: {
      '/api/': {
        target: 'http://127.0.0.1:1337',
        pathRewrite: { '^/api': '' }
      },
      '/socket.io/': {
        target: 'http://127.0.0.1:1337',
        ws: true
      }
    }
```

**Comment by miguelgrinberg** [comment]
There must be something else that prevents the logs from showing. Without the logs it is really going to be hard to figure out what's going on.

**Comment by ericman93** [comment]
Just noticed that I disabled those specific logs
where no message queue:
```
INFO:engineio.server:fc012f910e504d4682b0d695d982791c: Sending packet OPEN data {'sid': 'fc012f910e504d4682b0d695d982791c', 'upgrades': [], 'pingTimeout': 60000, 'pingInterval': 25000}
INFO:engineio.server:fc012f910e504d4682b0d695d982791c: Sending packet MESSAGE data 0
INFO:engineio.server:fc012f910e504d4682b0d695d982791c: Received request to upgrade to websocket
INFO:engineio.server:fc012f910e504d4682b0d695d982791c: Upgrade to websocket successful
INFO:engineio.server:fc012f910e504d4682b0d695d982791c: Received packet MESSAGE data 2["join","project@8433cc887e944de58497b3e57d4a02ac"]
```

when the message queue is given only when log appeare and then the server stuck, and donsen't responds
```
INFO:engineio.server:c77e2ddce1eb4f78bb866ec10d131467: Sending packet OPEN data {'sid': 'c77e2ddce1eb4f78bb866ec10d131467', 'upgrades': [], 'pingTimeout': 60000, 'pingInterval': 25000}
```

**Comment by miguelgrinberg** [comment]
Did you check from Redis if a connection is being made? All seems to indicate your are not running Redis in `localhost:6369`. Are you?

**Comment by ericman93** [comment]
running redis in docker
![image](https://user-images.githubusercontent.com/5768348/50564529-39bf3600-0d2e-11e9-916c-164636d11ad1.png)
and celery is able to connect to celery without any problems via
```
redis://localhost:6379/0
```

**Comment by miguelgrinberg** [comment]
Did you monkey patch the Python standard library? Eventlet does not support Redis natively, you have to monkey patch.

**Comment by miguelgrinberg** [comment]
That is a postgres error. You need to make sure each thread uses a different session. Flask-SQLAlchemy's `db.session` makes it easy, if you are managing your own sessions it is harder to do, but necessary in a multi-threaded application.

**Comment by ericman93** [comment]
After adding the mokey patching I can't debug anymore
Should I use message queue only when not in debug?
```
Traceback (most recent call last):
  File "/Users/eric/.pyenv/versions/romee/lib/python3.6/site-packages/eventlet/hubs/hub.py", line 458, in fire_timers
    timer()
  File "/Users/eric/.pyenv/versions/romee/lib/python3.6/site-packages/eventlet/hubs/timer.py", line 58, in __call__
    cb(*args, **kw)
  File "/Users/eric/.pyenv/versions/romee/lib/python3.6/site-packages/eventlet/semaphore.py", line 147, in _do_acquire
    waiter.switch()
greenlet.error: cannot switch to a different thread
```

**Comment by eshao731** [comment]
I have a problem with consent. It really can't be solved.
![image](https://user-images.githubusercontent.com/31184871/54589574-f3da5a00-4a60-11e9-9621-cd52142985c3.png)

**Comment by miguelgrinberg** [comment]
@eshao731 you are monkey patching for gevent, yet you are using the eventlet web server. You may want to uninstall eventlet from your virtualenv, or else force the use of gevent by doing `SocketIO(async_mode='gevent')`.

**Comment by eshao731** [comment]
@miguelgrinberg Thank you for your answer.  It work now!
Because I'm not familiar with eventlet or  gevent . I wasted a lot of time looking for this solution.  Thank you.
![image](https://user-images.githubusercontent.com/31184871/54594189-1d987e80-4a6b-11e9-995d-a6f1748197c1.png)
