### ISSUE TITLE
Gunicorn restart on falsk-socketio

### ISSUE THREAD

**Issue by mohamad171** [miguelgrinberg/Flask-SocketIO#865]
Hi , i use gunicorn to run Flask-SocketIo in CentOs but after 15 seconds gunicorn got timeout error and the socket restart 
my pip list:
```
eventlet               0.24.1   
Flask                  1.0.2    
Flask-SocketIO         3.0.1    
gevent                 1.3.6    
gevent-socketio        0.2.1    
gevent-websocket       0.10.1   
greenlet               0.4.14   
gunicorn               19.9.0
```

and i run script with this command:
`gunicorn --worker-class eventlet -w 1 runfile`

my file name is **runfile.py**

How can i fix the problem?

**Comment by miguelgrinberg** [comment]
You must be doing something that blocks the server in your application, I doubt this is related to Flask-SocketIO.
