### ISSUE TITLE
Flask-SocketIO with celery

### ISSUE THREAD

**Issue by ericman93** [miguelgrinberg/Flask-SocketIO#867]
Every thing is working great when my celery tasks contains only `chain`
```
run_task('151743ed2e70402c93b69c4387c230e9') | pre_processes_task('151743ed2e70402c93b69c4387c230e9') | run_task('9d99a307f0ba428bb60ea79b9fdd695f')
```
The problem is when I have `group` in my tasks
```
run_task('151743ed2e70402c93b69c4387c230e9') | pre_processes_task('151743ed2e70402c93b69c4387c230e9') | group([run_task('9d99a307f0ba428bb60ea79b9fdd695f'), run_task('821f955f9f224ec0a9e335381bfc3b22')])
```

Calling `apply_async` (from flask server) got stuck
When removing `message_queue` group still isn't working, it is start working only when I remove eventlet's monkey patching. I ran mokey patching at the first line of the first file being called my code
```
import eventlet
eventlet.monkey_patch(socket=True)
```

**Comment by miguelgrinberg** [comment]
Pretty sure for redis you also need to monkey patch threading, which covers locks, queues, etc.

**Comment by ericman93** [comment]
moving monkey patching without any parameters to `on_starting` fix everything :)
