### ISSUE TITLE
How to convert Node app into Flask-SocketIO app?

### ISSUE THREAD

**Issue by Sasha-P** [miguelgrinberg/Flask-SocketIO#872]
This is the Node app that I try to convert:
```node
const app = require('express')();
const http = require('http').Server(app);
const io = require('socket.io')(http);

const documents = {};

io.on('connection', socket => {
    let previousId;
    const safeJoin = currentId => {
        socket.leave(previousId);
        socket.join(currentId, () => console.log(`Socket ${socket.id} joined room ${currentId}`));
        previousId = currentId;
    };

    socket.on('getDoc', docId => {
        safeJoin(docId);
        socket.emit('document', documents[docId]);
    });

    socket.on('addDoc', doc => {
        documents[doc.id] = doc;
        safeJoin(doc.id);
        io.emit('documents', Object.keys(documents));
        socket.emit('document', doc);
    });

    socket.on('editDoc', doc => {
        documents[doc.id] = doc;
        socket.to(doc.id).emit('document', doc);
    });

    io.emit('documents', Object.keys(documents));

    console.log(`Socket ${socket.id} has connected`);
});

http.listen(4444, () => {
    console.log('Listening on port 4444');
});
```
[source](https://github.com/gwartnes/socket-example/blob/master/socket-server/src/app.js)

1. How to convert Node app into Flask-SocketIO app?
2. Is all Node functionality will be preserved after conversion?

**Comment by miguelgrinberg** [comment]
This `safeJoin` thing that you are doing is unnecessary in the Python server. All clients are placed in a room that is named after the session id automatically for you, and if they disconnect and reconnect the rooms are updated.

The `getDoc`, `addDoc` and `editDoc` events are pretty simple and should translate into Python without any trouble.

So yes, totally doable and easy to translate this to Python. :)

**Comment by miguelgrinberg** [comment]
It's odd that you get the disconnect twice. What client are you using?

**Comment by Sasha-P** [comment]
I use client from here https://github.com/gwartnes/socket-example/tree/master/socket-app.
I try to use `flask-socketio` with angular.

**Comment by miguelgrinberg** [comment]
The code that you pasted does not match the output. Not sure this matters, but there is nothing that prints `doc_connect` in your code.

In any case, can you repeat your test but this time enable verbose logging? Use this:

    socketio = SocketIO(app, async_mode=async_mode, logger=True, engineio_logger=True)

**Comment by Sasha-P** [comment]
Sorry I change code a little bit after posting locally
```python
...
def doc_connect():
    print(session)     #-->   print('doc_connect')
...
```
The logs after enabling logging:
[console.log](https://github.com/miguelgrinberg/Flask-SocketIO/files/2751909/console.log)

I notice in logs that during editing happens next:
```
185a008bf7b746aa87de2cbc9af698f2 is leaving room hrQgC [/]
185a008bf7b746aa87de2cbc9af698f2 is entering room hrQgC [/]
```

**Comment by Sasha-P** [comment]
Thank you!

So to sum up:
1. `safe_join` is not necessary. But  can be used to be sure that client connected only to one room (specific of this case).
2. `@socketio.on('disconnect')` already contain `disconnect()` 
3. And returning to question of this topic. My version more or less can replace original node version.

**Comment by miguelgrinberg** [comment]
1) On the `safe_join` function, you may want to do this instead:

```python
def safe_join(current_id):
    previous_id = session.get('current_id')
    if previous_id != current_id:
        if previous_id:
            leave_room(previous_id)
        join_room(current_id)
        session['current_id'] = current_id
```

This will be more efficient, since you don't need to exit and rejoin the room if it is the same.

2) your disconnect event handler is invoked when the client already disconnected, no need to disconnect a second time
3) I think so!

**Comment by Sasha-P** [comment]
Thank you, sensei! )
