### ISSUE TITLE
Integrar SocketIo con RQ

### ISSUE THREAD

**Issue by valentin-ballester** [miguelgrinberg/Flask-SocketIO#873]
Hola Miguel, Entiendo que hablas español asi que te hablo en español porque me queda mas comodo. 
Resulta que gracias a tus instructivos y a mucho esfuerzo estoy por terminar la 1.0 de mi app. Estoy trabado porque mi app tiene un motor de busqueda que corre como job de rq y funciona sin ningun problema. 
El tema es que ahora necesito mandar un emit desde el job, investigue como hacerlo porque ovbiamente no me mandaba el emit pero cuando trate de hacer lo del patch monkey (estoy usando eventlet) no funciono, claramente tampoco entendi muy bien porque hay que hacer eso del patch (si es que hay que hacer eso) porque lo que encontre investigando no sentia que aplicaba tan bien a mi caso. 
La pregunta mia es simple, **como se integra redis queue con socket io ?** te paso basicamente lo que tengo hasta ahora y si podrias decirme como sumar lo necesario para hacerlo funcionar. Inclusive, si se te ocurre otra alternativa para mi situacion decimela, es una de las pocas cosas que me quedan completar, muchas gracias.

**codigo actual** 

_init.py_
`app = Flask(__name__)
app.config.from_object(Config)
socketio = SocketIO(app)`

_searchengine.py_
`from app import app, db, socketio`
`socketio.emit('Open Order Popup', {'id': order.id}, namespace='/consumers')`

**en su momento cuando quise hacer lo del patch**

_init.py_

`import eventlet`
`eventlet.monkey_patch()`
`app = Flask(__name__)`
`app.config.from_object(Config)`
`socketio = SocketIO(app)`

**Comment by miguelgrinberg** [comment]
Te falta indicar el URL de redis:

    socketio = SocketIO(app, message_queue='redis://...')
