### ISSUE TITLE
Broadcast images from one user to another

### ISSUE THREAD

**Issue by pandailing** [miguelgrinberg/Flask-SocketIO#875]
simply i want to know how can i send data from one client to another client,
i use ajax jquery

i made this html script to get the image file from client:

```
<form class="chat-form" action="" method="POST" id="SendImage" enctype="multipart/form-data">
     <input type="file" class="theImage" id="filenya">
     <button type="submit"><span class="glyphicon glyphicon-send"></span> Send</button>
</form>
```

i know how to send text data and then broadcast it. but i dont know how to send images or files. please help me

**Comment by miguelgrinberg** [comment]
Binary data is given as a byte sequence. For example, you can read a jpeg file and send it to the client as follows:

    file_data = open(filename, 'rb').read()
    emit('my_image', {'filename': filename, 'data': file_data})

**Comment by pandailing** [comment]
wow, thanks @miguelgrinberg  i think i will try it on my server.py
btw, do you know how to do it in the front end that will send data with file_data format to my server? thanks

**Comment by miguelgrinberg** [comment]
It works in the same way in the frontend, just use a `ByteArray` for the image data. This is what you get if you read a file using the FileReader API. Here is a small demo that uploads files via Socket.IO: https://github.com/miguelgrinberg/socketio-examples/tree/master/uploads.

**Comment by pandailing** [comment]
ok @miguelgrinberg  i try to download the whole folder to try all the examples, but when i try to run the python file:

`python socketio_examples.py`

i got this following error

```
Traceback (most recent call last):
  File "socketio_examples.py", line 14, in <module>
    from chat import bp as chat_bp
  File "D:\ProjectGallery\python\socket io\miguelgrinberg\socketio-examples-master\socketio-examples-master\chat\__init__.py", line 1, in <module>
    from .chat import bp
  File "D:\ProjectGallery\python\socket io\miguelgrinberg\socketio-examples-master\socketio-examples-master\chat\chat.py", line 8, in <module>
    from socketio_examples import socketio
  File "D:\ProjectGallery\python\socket io\miguelgrinberg\socketio-examples-master\socketio-examples-master\socketio_examples.py", line 14, in <module>
    from chat import bp as chat_bp
ImportError: cannot import name 'bp'
```

i see the folder was correct, but why did this problem happen??

**Comment by miguelgrinberg** [comment]
The `flask run` command is broken in the latest version of Flask. If you use the versions of the requirements from this repo I think `flask run` will work.

The warning message is correct, by the way. You may want to install eventlet so that you get websocket functionality. This is an optional install, that is why it isn't automatically installed. But if you work with the requirements file in that repo you will get the right dependencies.

**Comment by pandailing** [comment]
thanks @miguelgrinberg 
i try to make the standalone client-server from the upload folder, anything i should do? or do you have the stand alone version? thanks for all the support bro, i hope other people will be helped by our conversation

**Comment by miguelgrinberg** [comment]
If you are just doing this as a test then the easiest would be to run the entire app. The second easiest would be to run the entire app, but comment out the blueprints for the sub-examples that you are not interested in [in this file](https://github.com/miguelgrinberg/socketio-examples/blob/master/socketio_examples.py).
