### ISSUE TITLE
client disconnects at around 25 seconds

### ISSUE THREAD

**Issue by gwh-cpnet** [miguelgrinberg/Flask-SocketIO#880]
I am trying to build a shell output indicator with flask-socketio.

I got an app factory in `app/__init__.py`. 
```python
import eventlet
eventlet.monkey_patch()

from flask import Flask, jsonify
from flask_socketio import SocketIO, emit
import shlex
from eventlet.green import subprocess


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'secret!'
    socketio = SocketIO(app)

    def execute(cmd):
        worker = subprocess.Popen(shlex.split(cmd), stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=False)
        while worker.poll() is None:
            line = worker.stdout.readline()
            if line:
                line = line.decode().rstrip()
                if line:
                    socketio.emit('stdout', line)
        print(worker.returncode)

    @app.route('/api/ping')
    def ping():
        execute("ping -c 100 192.168.1.1")
        return '', 204

    @socketio.on('connect')
    def connect():
        emit('notify', 'Connected')

    @socketio.on('disconnect')
    def disconnect():
        print('Client disconnected')

    @socketio.on('stdin')
    def handle_stdin(payload):
        execute("ping -c 100 192.168.1.1")

    return app

```

and I got server run with command `FLASK_ENV=development FLASK_APP=app flask run`

`pip list` result:
```
Package         Version
--------------- -------
aniso8601       4.1.0  
ansible         2.7.5  
asn1crypto      0.24.0 
bcrypt          3.1.6  
cffi            1.11.5 
Click           7.0    
cryptography    2.4.2  
dnspython       1.16.0 
eventlet        0.24.1 
Flask           1.0.2  
Flask-SocketIO  3.1.2  
greenlet        0.4.15 
idna            2.8    
itsdangerous    1.1.0  
Jinja2          2.10   
MarkupSafe      1.1.0  
monotonic       1.5    
paramiko        2.4.2  
pip             18.1   
pyasn1          0.4.5  
pycparser       2.19   
PyNaCl          1.3.0  
python-engineio 3.2.3  
python-socketio 3.1.1  
pytz            2018.9 
PyYAML          3.13   
setuptools      40.6.2 
six             1.12.0 
Werkzeug        0.14.1
```

The interesting thing is that the `execute` function is the same. When I trigger it by the route
```
curl http://localhost:5000/api/ping
```
I can get the full output, 100 icmp_seq with summary, line by line on my socket.io client. Well, the problem with the route approach is that I have to [return a Response after the execution is done](https://stackoverflow.com/a/48994441/1764290), which will not meet my needs, as most of the  commands would raise timeout exceptions. So I tried to run the `execute` function in socketio receive message handler, `stdin` in this case. 

But this time my frontend client only get the first around 28-30 (icmp_seq) lines of output from socketio server. The disconnect handler was triggered by then. 

Am I miss anything?

**Comment by miguelgrinberg** [comment]
Try running your loop in a background task:

```python
    @socketio.on('stdin')
    def handle_stdin(payload):
        socketio.start_background_task(execute, "ping -c 100 192.168.1.1")
```

**Comment by gwh-cpnet** [comment]
Thank you, @miguelgrinberg . Problem solved. Somehow it is related to the blocking subprocess pipe reading.

**Comment by gwh-cpnet** [comment]
After switching to nodejs/es7 for quite a while, I am thinking about maybe I can try python3 asyncio a little bit. But I am afraid the timing is not right yet.

**Comment by miguelgrinberg** [comment]
@gwh-cpnet this package works under asyncio as well, in case you didn't know. Or more exactly, you would be using python-socketio, which is the main dependency of this package, without the Flask stuff.

**Comment by aguegu** [comment]
Good to know that. :+1:
