### ISSUE TITLE
gevent long-polling with multiple gunicorn workers with redis

### ISSUE THREAD

**Issue by ColdHeat** [miguelgrinberg/Flask-SocketIO#881]
I'm trying to better understand how long-polling works under multiple gunicorn workers. My initial assumption was that by having a message queue, long-polling would work even under multiple gunicorn workers because the message could be passed between the workers. 

However in practice it seems like using the threading async mode doesn't work well using multiple gunicorn workers
![image](https://user-images.githubusercontent.com/166333/51491670-14e23f80-1d7d-11e9-92e8-cd231608a658.png)

Do you still need to run sticky sessions or 1 worker under long polling?

**Comment by miguelgrinberg** [comment]
Yes, One worker is still required. You can run multiple gunicorn processes, each with one worker, all behind a sticky session load balancer.

**Comment by ColdHeat** [comment]
Thanks for the input! I kind of think this should overall be possible... Would it be possible to work around this problem by specifying `client_manager` to SocketIO? Perhaps to store the client list in Redis?

**Comment by ColdHeat** [comment]
I guess this is ultimately related to https://github.com/abourget/gevent-socketio/issues/112?

**Comment by miguelgrinberg** [comment]
My responses are based on what's possible today. If you are willing to write new code (possibly new client manager classes) then sure, you can do anything you want.

This is a discussion on the topic that you may find interesting: https://github.com/miguelgrinberg/python-socketio/issues/216
