### ISSUE TITLE
Apache mod_proxy_WS_tunnel

### ISSUE THREAD

**Issue by giriannamalai** [miguelgrinberg/Flask-SocketIO#887]
I m having flask+apache mod_wsgi.
Is thee any way to integrate it into mod_WS_ proxy tunnel? 
To show realtime progress I want to integrate it...

**Comment by miguelgrinberg** [comment]
Unfortunately mod_wsgi isn't a good match for Flask-SocketIO, I have never figured out a way to configure it appropriately. I suggest you switch to nginx if you need to use Socket.IO.

**Comment by giriannamalai** [comment]
OK.
