### ISSUE TITLE
client not receiving emit from socketio.emit at a certain part of code

### ISSUE THREAD

**Issue by witchapong** [miguelgrinberg/Flask-SocketIO#889]
socketio.emit('my_response',
                          {'message':'First emit'},
                          namespace='/test') # saw 'SENDING' on the log and received by client
            '''
            CODE FOR SOME LONG RUNNNIG PROCESS (> 1 min)
            '''
            socketio.emit('my_response',
                          {'message':'Second emit'},
                          namespace='/test') # saw 'SENDING' on the log but not received by client

Hi! I've come across this kind of weird error where the message from socketio.emit within my background process (using Thread) can be received at one part of the code (before the process) but not the other (after the process) as shown above. I saw in the log that the server side tried to send the message. (I need to send some response regarding the finished process to trigger some action on a client side)

Any idea how to fix or any more information?

Thanks!

**Comment by miguelgrinberg** [comment]
Is the long running process blocking? If it is, then in one minute the server is going to think the clients drop out. Basically you can't block the server with a long process, you need to allow the server's background tasks to run and keep everything going. If you have a loop in that long section of code, try adding `socketio.sleep(0)` calls, which will release the CPU and allow other tasks to run.
