### ISSUE TITLE
Cannot received ASCII data

### ISSUE THREAD

**Issue by RizkaOMG** [miguelgrinberg/Flask-SocketIO#890]
I have trouble when send data ascii from Packet Sender and show error bad request. Error like this **<socket fileno=7 sock=1.1.1.1:5000 peer=36.90.177.245:58136>: Invalid HTTP method: 'xx\n'** How can Socket IO can receive ascii data? My code same as your example

```
from flask import Flask, render_template
from flask_socketio import SocketIO, emit

app = Flask(__name__)
socketio = SocketIO(app)

values = {
    'slider1': 25,
    'slider2': 0,
}

@app.route('/')
def index():
    return render_template('index.html',**values)

@socketio.on('connect')
def test_connect():
    emit('after connect',  {'data':'Lets dance'})

@socketio.on('Slider value changed')
def value_changed(message):
    values[message['who']] = message['data']
    emit('update value', message, broadcast=True)

if __name__ == '__main__':
    socketio.run(app, host='1.1.1.1')
```

**Comment by RizkaOMG** [comment]
logger error like this **<socket fileno=7 sock=178.128.117.240:5000 peer=36.90.177.245:61647>: Invalid HTTP method: '\x90\x90\x90\x90\x90'**
And the data what I send **\x90\x90\x90\x90\x90**

**Comment by miguelgrinberg** [comment]
Sorry, but I'm still lost. Who is printing this log? Also, the `\x90` character is not in the ASCII range.

**Comment by RizkaOMG** [comment]
I'm sure it ascii, but this another ascii send from packet sender **'xx\x0e\x80\x08\x00\x00\x00\x00sos#\x00\x01mj\r\n'** and still same error `socket fileno=8 sock=1.1.1.1:5000 peer=36.90.177.245:49950: Invalid HTTP method`

How to can socket.io can receive ascii data?

**Comment by miguelgrinberg** [comment]
I repeat my question: Who is printing this log? The log that you are showing has nothing to do with this package.

Also relevant is if you are using Python 2, where binary data needs to be explicitly reported.
