### ISSUE TITLE
How do you run Flask-SocketIO as Larger Application (package format)

### ISSUE THREAD

**Issue by Dracio** [miguelgrinberg/Flask-SocketIO#893]
My flask application is setup as a package. Since the "flask run" has been removed from flask-socketio, then I have not been able to run the application without it freezing. Is there any way to provide some documentation on how to run flask-socketio as a package?

**Comment by miguelgrinberg** [comment]
Here is a complete example: https://github.com/miguelgrinberg/Flask-SocketIO-Chat.
