### ISSUE TITLE
Question: Does start_background_task have to be used for background threads if no message queue is used?

### ISSUE THREAD

**Issue by aharrah** [miguelgrinberg/Flask-SocketIO#895]
Hi,

Can I call `socketio.emit` from a traditionally started background thread that blocks (ex: blocks waiting for input from TCP/IP socket) w/o using an external message queue?

`app.py` in `examples` uses `start_background_task` to start the background thread. I assume the thread has to call `socketio.sleep()` (perhaps with 0) on a regular basis.

On the other hand the docs (https://flask-socketio.readthedocs.io/en/latest/) mention using `emit` like this:
```
def some_function():
    socketio.emit('some event', {'data': 42})
```

but do not mention using `start_background_task`

**Comment by miguelgrinberg** [comment]
You can use `emit` from any thread, background or not. If you have any blocking in your thread, you need to make sure the blocking is async-friendly. For eventlet or gevent, this means you probably have to monkey patch the Python standard library.

**Comment by aharrah** [comment]
Thank you for your quick reply.
