### ISSUE TITLE
Concurrency / handling multiple requests not working

### ISSUE THREAD

**Issue by SimonNick** [miguelgrinberg/Flask-SocketIO#896]
Hi @miguelgrinberg,

I am trying to handle multiple concurrent requests using `flask_socketio` and `eventlet`. However, it does not work as expected: When function `test1()` is running, it blocks the execution of function `test2()` as seen in the output log.

How can I achieve that the server handles both requests simultaneously?

**Server (Python):**

```lang-py
import eventlet
eventlet.monkey_patch()

from flask import Flask
from flask_socketio import SocketIO

app = Flask(__name__)
socketio = SocketIO(app, async_mode='eventlet')

@socketio.on('test1')
def test1():
    print('test1 started')
    do_complicated_calculation() # takes some time
    print('test1 done')

@socketio.on('test2')
def test2():
    print('test2')

if __name__ == '__main__':
    socketio.run(app)
```

**Client (JavaScript):**

```lang-js
import io from 'socket.io-client';

socket = io('http://localhost:5000');
socket.emit('test1');
socket.emit('test2');
```

**Expected Output:**

```
test1 started
test2
test1 done
```

**Actual Output:**

```
test1 started
test1 done
test2
```

**Comment by miguelgrinberg** [comment]
Neither Python nor eventlet support running two or more things concurrently, so what you want cannot be done.

The closest you can get is to allow these two functions to yield the CPU from time to time, and in that way they can take turns with the CPU and both make progress on their tasks in parallel. To do this, all you need to do is insert a `socket.sleep(0)` inside a loop in your calculations. Each time the sleep call runs the scheduler will pass the CPU to another waiting task.

**Comment by SimonNick** [comment]
Thanks for your answer! I am a little bit confused ... when I used `Flask` together with `@app.route('/test1', methods = ['POST'])` I was able to process several request at the same time. So why does socketio not support handling several request at the same time?

**Comment by miguelgrinberg** [comment]
Flask uses multiple threads to handle concurrent requests, but as I said above, it gives you the illusion of concurrency. When one thread is running the other is paused due to the global interpreter lock. Essentially each thread runs for a little bit of time while the other waits, and then the switch. This is done automatically when you use regular Python.

But you are using eventlet, which uses a completely different concurrency model. If you want to have the same type of concurrency what you need to do is issue the sleep calls I indicated above. With eventlet concurrency is cooperative, each task needs to indicate when it wants to yield the CPU to allow other tasks to run.

**Comment by SimonNick** [comment]
Thank you for the clarification and your help! The problem is that for the calculation I simply invoke a function of an external library, so I cannot insert a `socket.sleep(0)` anywhere. What would be the best solution for my problem? Should I use different threads?

Also, I noticed that if my calculation takes too long (usually > 40s), I get a '400 Bad request' error. Is it because the calculation is blocking so that after some time the client thinks the server went down?

**Comment by miguelgrinberg** [comment]
If you don't have control over the code in the long calculation then that calculation cannot be used with eventlet. Blocking code is the mortal enemy of async frameworks such as eventlet, asyncio, etc.

**Comment by SimonNick** [comment]
Okay ... so the only alternative in this case is threading?

**Comment by miguelgrinberg** [comment]
If you can do without websocket, then running with regular threads will work. You can also consider moving your long calculation to a separate process so that it does not interfere with eventlet.

**Comment by SimonNick** [comment]
Ok thanks for the adivce. Would celery also make sense in this case?

**Comment by roocell** [comment]
thanks Miguel.  (following https://github.com/miguelgrinberg/flask-video-streaming).
in my case putting socket.sleep(0) in the gen(camera) video feed route allowed other routes to be served.  (also removed the time.sleep(1) in camera.py.
