### ISSUE TITLE
Example app not running on Yocto

### ISSUE THREAD

**Issue by xeguiluz** [miguelgrinberg/Flask-SocketIO#899]
Hi,
I'm trying to run the example app on a Yocto image in a BeagleBoneBlack without success.
Apparently, I 've loaded all the required python packages correctly (I have checked their addition using the help ("modules") command. 
The app.py seems to launch correctly too, and in a browser of another computer, I have connected to the net address of the BBB but it only loads the index.html file without updating the receive messages periodically. However it takes some data from the system, as it shows "gevent" in the "Async mode is:" section
I don't know what can I check or do to find what I missing.
Thanks in advance!

**Comment by miguelgrinberg** [comment]
Can you look in your browser console if there are any error messages? And can you capture the output of the application running in your device? These two should help figure out what's happening.

**Comment by xeguiluz** [comment]
I kept on looking for related problems/solutions and I found [this ](https://stackoverflow.com/questions/29921671/flask-socketio-not-working-on-apache-wsgi)thread, so I realized about the problem. Changed to gunicorn, and that did the trick!
