### ISSUE TITLE
Any plans to support socket.io 2.x?

### ISSUE THREAD

**Issue by ramazanpolat** [miguelgrinberg/Flask-SocketIO#903]
Thank for this great work.

From examples, I see you use socket.io 1.3.5 and I've tried 2.x clients with no luck.

Is there any plan to support socket.io 2.x?

**Comment by miguelgrinberg** [comment]
I've been using the 2.x clients for a long time w/o problem. Can you describe the problem in detail?

**Comment by ramazanpolat** [comment]
Ok just updated to 3.2.2 and there seems no problem when using a 2.x client to connect to server.

One think got my attention, why client uses polling as transport?

(I am running app.py in examples folder)

```
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 180-943-531
(5912) wsgi starting up on http://127.0.0.1:5000
(5912) accepted ('127.0.0.1', 59309)
127.0.0.1 - - [15/Feb/2019 01:39:10] "GET / HTTP/1.1" 200 6022 0.007000
127.0.0.1 - - [15/Feb/2019 01:39:10] "GET /socket.io/?EIO=3&transport=polling&t=1550194750889-0 HTTP/1.1" 200 381 0.001000
127.0.0.1 - - [15/Feb/2019 01:39:10] "POST /socket.io/?EIO=3&transport=polling&t=1550194750930-1&sid=72745df8a6f3460e9dc8f6205b5a4641 HTTP/1.1" 200 219 0.002000
(5912) accepted ('127.0.0.1', 59311)
127.0.0.1 - - [15/Feb/2019 01:39:10] "GET /socket.io/?EIO=3&transport=polling&t=1550194750932-2&sid=72745df8a6f3460e9dc8f6205b5a4641 HTTP/1.1" 200 280 0.000000
```

And when I refresh the page, I see a connection attempt with websocket:

```
127.0.0.1 - - [15/Feb/2019 01:43:03] "GET / HTTP/1.1" 200 6022 0.000000
127.0.0.1 - - [15/Feb/2019 01:43:03] "GET /socket.io/?EIO=3&transport=websocket&sid=72745df8a6f3460e9dc8f6205b5a4641 HTTP/1.1" 200 0 232.256284
Client disconnected 72745df8a6f3460e9dc8f6205b5a4641
127.0.0.1 - - [15/Feb/2019 01:43:03] "GET /socket.io/?EIO=3&transport=polling&t=1550194983280-0 HTTP/1.1" 200 381 0.000000
(5912) accepted ('127.0.0.1', 59511)
127.0.0.1 - - [15/Feb/2019 01:43:03] "POST /socket.io/?EIO=3&transport=polling&t=1550194983293-1&sid=f1c7f79d38ec488aa5923217ec359582 HTTP/1.1" 200 219 0.001000
(5912) accepted ('127.0.0.1', 59512)
127.0.0.1 - - [15/Feb/2019 01:43:03] "GET /socket.io/?EIO=3&transport=polling&t=1550194983295-2&sid=f1c7f79d38ec488aa5923217ec359582 HTTP/1.1" 200 280 0.000000
```
BTW, async mode = eventlet

**Comment by miguelgrinberg** [comment]
Great. The logs that you see in your terminal are expected. Requests are logged when the end. The first three are for the long-polling handshake, which happens at the beginning. The connection then is upgraded to websocket and from that point on you shouldn't see any more HTTP requests. But the websocket request is only going to appear in your log when the connection ends, which in your case is when you refresh the page. So that one websocket request that you see there is the one that was active throughout your first session. Hope that clears it!

**Comment by ramazanpolat** [comment]
That's a great explanation.
Thank you.
