### ISSUE TITLE
nginx + uwsgi + Flask-SQLAlchemy + socketio

### ISSUE THREAD

**Issue by chenyuan53618** [miguelgrinberg/Flask-SocketIO#904]
Ubuntu 16.04 LTS
Flask==1.0.2
Flask-SocketIO==3.0.1
Flask-SQLAlchemy==2.3.2

After applying monkey_patch to our backend (couple months already), things work fine. However, after trying to fix the database transaction problem, backend *stuck*.

Problem description:
what I am doing is to move away session commit from *update* and *create* operation. For example:
```
def create_element(dict):
    element = Model()
    element.foo = bar
    db.session.add(element)
  #  db.session.commit()  

def update_element(dict):
    element = Model()
    element.foo = bar
   # db.session.commit()  
```
and put them at the hook @app.after_request
```
@app.after_request
def after_clean(resp, *args, **kwargs):
    db.session.commit()
    db.session.remove()
    return resp
```
After running couple requests, the whole backend stuck forever (event if I hit Ctrl + C, it takes a while to stop). I put tons of log commands, and finally find out the *stuck* line is:
`Model.query.get(value_of_primary_key)`

I tried a lot including session.remove in @app.before_request、session.remove in @app.after_request. None of them works. 

What do you think or is there anything I could do to dig into more?

**Comment by miguelgrinberg** [comment]
You are not providing enough information for me to understand the problem. Try to see if you can create a small and complete example that you can share that reproduces this problem.

I also don't see what's the relevance of Flask-SocketIO in this problem.
