### ISSUE TITLE
socketio.emit() does not work sometimes . 

### ISSUE THREAD

**Issue by Prateek327** [miguelgrinberg/Flask-SocketIO#908]
Hello , I am new to socketio . I have been building a chat application with flask as backend and using flask-socketio . Everything is working fine except sometimes socketio.emit() does not work as expected . 
In the server side code , if i give a post request to '/get_online_users'  , I expect a alert on my client side using socketio library and also a server response which I am passing on the return statement . But sometimes I receive only server response and no alerts on the client side page . 

Server side code : 

```
from flask import Flask,render_template,request,url_for,redirect
from flask import escape , session ,jsonify
from flask_pymongo import PyMongo
from flaskext.uploads import UploadSet,configure_uploads,IMAGES
from flask_socketio import SocketIO, send, emit
from flask_socketio import SocketIO, Namespace, emit, join_room, leave_room, close_room, rooms, disconnect
import bcrypt , os
import time
import json

localtime =  time.asctime(time.localtime(time.time()))

dirName = "static/imgdir"
if not os.path.exists(dirName):
    os.mkdir(dirName)

app = Flask(__name__)

photos = UploadSet("photos",IMAGES)

app.secret_key = ""
app.config["MONGO_URI"] = ""
app.config["UPLOADED_PHOTOS_DEST"] = "static/img"
configure_uploads(app,photos)

app.config['DEBUG'] = True

mongo = PyMongo(app)
socketio = SocketIO(app)

//skipping some code here . 
//socketio.emit() sometimes doesnot work on the following code 

@app.route("/get_online_users",methods=["GET","POST"])
def get_online_users():
    online_users = users.find({"status":0,"disabled":0});
    if request.method =="POST":
        if online_users.count()==0:
            return jsonify({"agent_id": "UNAVAILABLE"})
        else:
            chatreqs.insert({"id":autoinc(),"timestamp":time.asctime(time.localtime(time.time())),"browser_id": request.json["browser_id"],"client_name":request.json["name"],"prev_messages":request.json["prev_messages"]})
            socketio.emit("alert",{"message":"Client wants to talk to you"},namespace = "/private",room="online_agents")
            return "Agents are available . Let me find some for you."
```

client side code : 

```
var private_socket = io('http://0.0.0.0:5000/private');

  private_socket.on("alert", function(data) {
      var alert = alertify.alert('Client Call',data["message"]);
      alert.set('label','Got it');
      alert.show();
      var id = document.getElementsByClassName("content")[0].id;
      if (id=="chat_page"){
        $.ajax({url: "/chat", success: function(result){
        $(".content-wrapper").html(result);
  }});
      }
  });
```
I do not know if the following error is associated with this issue but I get it some times 

![image](https://user-images.githubusercontent.com/25716955/53176719-ac54df80-3614-11e9-8d67-6eae51c135dc.png)

Please tell me what I am doing wrong .

**Comment by miguelgrinberg** [comment]
I'm not sure what can be the problem. I suggest you obtain logs from the server and client sides to see where are these lost emits actually being dropped.

**Comment by Prateek327** [comment]
Thank you for your time . I have made following changes at the beginning of my  code after looking for similar issues . 
```
import eventlet 
eventlet.monkey_patch() 
socketio = SocketIO(app,async_mode = 'eventlet')
```
Till now it is working fine and socketio.emit() is working as expected  . I have two questions now .
1. Do we need to import eventlet as i did in above code to use its functionality or it should get automatically detected if pip installed . ?
2. Is it necessary to use threading for emit operations . ?

**Comment by Prateek327** [comment]
I faced this issue once again now . I  checked my logs could not find much from it . One thing i need to mention here is if i refresh the client side page and try again I am getting alerts on post request to 'get_online_users' . So on refreshing it works but still not clear on why it does not happen on the initial request.

**Comment by Prateek327** [comment]
I think it was because the client page was transitioning from long polling to web sockets and in the same time server was emitting event , therefore its behaviour was analogous . Long time since I had faced this issue , I am closing it for now . Thank you .
