### ISSUE TITLE
flask-socketIO + eventlet + celery "Cannot send to sid..."

### ISSUE THREAD

**Issue by Asmayra** [miguelgrinberg/Flask-SocketIO#911]
Hi, 
my app has an Api endpoint which starts another program and then triggers a celery background task.  The background task gets logs from the program and then sends them via websocket to the user. This was working, but some recent changes, seemingly unrelated to socketio, seem to have broken something. I don't receive any message over websocket anymore. 

I enabled logger and engineio_logger:
`Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 597, in _terminate_pool
    cls._help_stuff_finish(inqueue, task_handler, len(pool))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 826, in _help_stuff_finish
    with inqueue.not_empty:
AttributeError: 'Queue' object has no attribute 'not_empty'
dc7ad4226923482ba3eaa2a37d254fb6: Sending packet OPEN data {'sid': 'dc7ad4226923482ba3eaa2a37d254fb6', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
dc7ad4226923482ba3eaa2a37d254fb6: Sending packet MESSAGE data 0
dc7ad4226923482ba3eaa2a37d254fb6: Received packet MESSAGE data 0/websocketlog-gilf,
dc7ad4226923482ba3eaa2a37d254fb6: Sending packet MESSAGE data 0/websocketlog-gilf
dc7ad4226923482ba3eaa2a37d254fb6: Received request to upgrade to websocket
dc7ad4226923482ba3eaa2a37d254fb6: Received packet MESSAGE data 2/websocketlog-gilf,["message","User has connected!"]
received event "message" from dc7ad4226923482ba3eaa2a37d254fb6 [/websocketlog-gilf]
dc7ad4226923482ba3eaa2a37d254fb6: Upgrade to websocket successful
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
dc7ad4226923482ba3eaa2a37d254fb6: Received packet PING data None
dc7ad4226923482ba3eaa2a37d254fb6: Sending packet PONG data None
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
Cannot send to sid dc7ad4226923482ba3eaa2a37d254fb6
dc7ad4226923482ba3eaa2a37d254fb6: Received packet PING data None
dc7ad4226923482ba3eaa2a37d254fb6: Sending packet PONG data None
dc7ad4226923482ba3eaa2a37d254fb6: Received packet PING data None
dc7ad4226923482ba3eaa2a37d254fb6: Sending packet PONG data None
dc7ad4226923482ba3eaa2a37d254fb6: Received packet PING data None`

My configuration is as follows:

```
# webapi.py
#!/bin/env python3
import eventlet

eventlet.monkey_patch()

from app import create_app, socketio

app = create_app()

if __name__ == "__main__":
    socketio.run(app, port=8000)
```

```
# app/__init__.py 

from celery import Celery
from flask import Flask
from flask_socketio import SocketIO
from flask_sqlalchemy import SQLAlchemy

from . import celeryconfig
from .config import Config

socketio = SocketIO()
db = SQLAlchemy()
celery = Celery(
    __name__, broker="redis://localhost:6379/0", backend="redis://localhost:6379/0"
)
celery.config_from_object(celeryconfig)

from . import models

from .celery_task.task import job_background_task
from .celery_task.crontab import delete_old_jobs

def create_app(main=True):
    app = Flask(__name__)

    app.config.from_object(Config)

    db.init_app(app)

    celery.conf.update(app.config)

    if main:
        socketio.init_app(app, message_queue="redis://")
    else:
        socketio.init_app(None, message_queue="redis://", async_mode="threading")

    # Register API Routes
    from .api import api as api_bp

    app.register_blueprint(api_bp, url_prefix="/api")

    # Register Celery Support
    from .celery_task import celery_task as celery_task_bp

    app.register_blueprint(celery_task_bp)

    # Register log routes
    from .routes import routes as routes_bp

    app.register_blueprint(routes_bp, url_prefix="/logs")

    return app
```

```
# app/aux_context.py

from . import create_app

# Create an application instance that Celery workers can use
app = create_app(main=False)

```

```
# app/celery_task/task.py

from .. import celery, db, socketio
from ..models import BuildOrder


@celery.task
def job_background_task(jobname):
    # Some Imports...

    from ..aux_context import app

    with app.app_context():

        print(logger(jobname, "Celery Task started"))
        socketio_namespace = "/" + jobname
        socketio.send("Jobstart", namespace=socketio_namespace, broadcast=True)
        ...
```
I'm not sure if this is relevant, but if I leave the client test script open in firefox after a while I get this warning:
` Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://<ip>/socket.io/?EIO=3&transport=polling&t=Mave5kD. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).` 

Any help is highly appreciated.

**Comment by Asmayra** [comment]
I am still trying to solve this. From what i learned "Cannot send to sid ..." comes from python-engineio not finding the socket belonging to the corresponding sid. Is this a python-engineio issue or can the issue still come from the way I setup Flask and flask-socketIO?

One of the changes i made prior to it stopping working was sorting my imports and cleaning up my celery task by moving parts of the code into separate functions for readability. If this broke the eventlet monkey patch, could this be the cause of the socket issue?

**Comment by miguelgrinberg** [comment]
I don't think `multiprocessing` is compatible with eventlet. Has that worked before?

**Comment by Asmayra** [comment]
It did work until I reworked the celery task. Don't you use the same kind of setup in the Flack App or am i missing something?

**Comment by miguelgrinberg** [comment]
I don't use the multiprocessing package, just Celery. What do you use that package for?

**Comment by Asmayra** [comment]
I don't use the multiprocessing package directly. It must be used by another package. Maybe the Kubernetes Python Client I use. I have seen that error before, but it never had any effects.

**Comment by miguelgrinberg** [comment]
I'm not sure what else I can tell you, the code looks fine outside of the multiprocessing problem, but obviously a problem must exist in code that you haven't shown. If you can create a small self-contained example that demonstrates the issue I'm happy to investigate in more detail.

**Comment by Asmayra** [comment]
It is indeed used by the Kubernetes Python Client. But besides the error message everything worked fine. 

I am currently retracing the changes I made to see where it stops working. Will update this when I know more. Thank you for your time and work!

**Comment by miguelgrinberg** [comment]
@Asmayra you may want to consider start using git or other source control, so that you don't lose older versions of your code.

**Comment by Asmayra** [comment]
I do use git with gitlab for this project. But when I rewrote the code I only checked what was logged and not what was actually send over websocket. I catch exceptions from the socketio.send() function, but this error wasn't catched. But yes - I should take more time for testing in the future.
