### ISSUE TITLE
flask-socketio: 400 bad request/ Cors issue

### ISSUE THREAD

**Issue by akapit** [miguelgrinberg/Flask-SocketIO#913]
Hi
I'm getting this error at the client:

```
VM15520:1 GET http://localhost:5000/socket.io/?EIO=3&transport=polling&t=Mb2_LpO 400 (Bad Request)
Access to XMLHttpRequest at 'http://localhost:5000/socket.io/?EIO=3&transport=polling&t=Mb2_LpO' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
I'm actually starting my app with gunicorn as follows:

`gunicorn --workers=1 --worker-class eventlet --certfile=keys/key.crt --keyfile=keys/key.key --bind 0.0.0.0:5000 myapp.run:app`
and this is my run.py:

```
import eventlet
from myapp import create_app
eventlet.monkey_patch()
app, celery = create_app('config_prod.py')
```
I'm also using CORS(app) in my app factory.

I also tried adding this in one of my blueprints:

```
@api.after_request
def after_request(response):
    response.headers.add('Access-Control-Allow-Origin', 'http://localhost:8080')
    response.headers.add('Access-Control-Allow-Headers',
                         'Origin, X-Requested-With, Content-Type, Accept, Authorization')
    response.headers.add('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE,OPTIONS')
    response.headers.add('Access-Control-Allow-Credentials', 'false')
    return response
```
I'm using nginx as a reverse proxy, and so I tried adding the corresponding configuration I've seen at flask-socketio's docs:

```
location /socket.io {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    proxy_http_version 1.1;
    proxy_buffering off;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_pass https://my_backend_host/socket.io;
}
```
Just in case it's useful, this is my app factory method:

```
socketio = SocketIO()
(...)
def create_app(config_file=None):
    app = Flask(__name__)
    app.config.from_pyfile(config_file, silent=True)

    CORS(app)
    jwt.init_app(app)
    socketio.init_app(app, message_queue='redis://redis:6379/2', async_mode='threading')

    app.register_blueprint(companies.companies_service)
    app.register_blueprint(modules.modules)
    app.register_blueprint(auth.auth)
    app.register_blueprint(api.api)

    celery.conf.update(app.config)

    from outflink.tasks import tasks
    app.register_blueprint(tasks.tasks)

    return app, celery

```

Any help will be appreciated,
Thanks!

**Comment by miguelgrinberg** [comment]
What kind of client are you using? Is it a browser or something else?

**Comment by akapit** [comment]
It's a browser

**Comment by miguelgrinberg** [comment]
How do you initialize your `SocketIO` object? Do you pass any of the CORS options to it?

**Comment by akapit** [comment]
I've just added my create_app method to the original post

**Comment by akapit** [comment]
btw the @api.after_request annotated method is in the "api" blueprint.

**Comment by miguelgrinberg** [comment]
Any change if you temporarily remove the Flask-CORS extension? What I want to know is if removing that extension makes the Socket.IO server accept the connection from your client. Obviously other HTTP routes that you have in your app will not work due to not having CORS, so this isn't a definitive solution. Just trying to see if Flask-CORS somehow collides with the CORS support in Socket.IO.

**Comment by akapit** [comment]
Just tried that but there is no change, the issue persist.
Btw I just try from another browser to perform a get request to an entrypoint which emits a message, and the logs show that's apparently working `INFO:socketio.server:emitting event "update_reports" to all [/test]
`   however the client is still screaming.

**Comment by miguelgrinberg** [comment]
I assume your client runs on port 8080? Can you show me a screenshot of the 400 request in the browser, including all the headers for the request and the response?

**Comment by akapit** [comment]
Sure

![image](https://user-images.githubusercontent.com/642571/53694910-91752e80-3dbd-11e9-9921-c93d00b18791.png)

![image](https://user-images.githubusercontent.com/642571/53694916-9fc34a80-3dbd-11e9-943c-448f6a12e530.png)

**Comment by miguelgrinberg** [comment]
@akapit I need to see the response headers as well.

**Comment by akapit** [comment]
Miguel, my bad, I've just found I was pointing to http instead of https from my client.
I'm happy that there is no bug, and I'm so sorry!

**Comment by jkam273** [comment]
I'm Getting the same error and Here are the headers in my case 
![image](https://user-images.githubusercontent.com/22021007/69767535-8b846200-1131-11ea-95a6-f0ac369c6bb5.png)

**Comment by kmtnck** [comment]
Hello friends, I discover just yesterday this fantastic plugin, and ,in general, the magic world of websocket and this implementation socket.io on python (I chooice just on the fly python to develope fastly). My compliments!

I have a well build app python that have a well work server flask with this plugin socket.io. 

All run very very well on classic development deploy, templates ok, events ok, routing ok, also besided nginx over https work well.
This server is deployed into a docker compose environment,  and its all ok.!!

Thought I have a compose docker dedicated for production and I have a canonical run of server using gunicorn. 
The client receive a persistent **cors error**. 
There is not nginx proxy. The error is directly on uri of host that is called http://devlocale:5100

The situation is:

`gunicorn -k eventlet -w 1 -b 0.0.0.0:5100 mymodule:app`

There is
`eventlet.monkey_patch()`
before to run server socketio

There is **not** flask-cors 

There is **not** nginx

There is **not** ssl tier

There is this istance
```
async_mode = None
socketio = SocketIO(async_mode=async_mode, cors_allowed_origins="*")
```

I read a lot of documentation, forum, and I find this issue of 2019 now.
I hope that is usefull to understand what is my mistake and so I write this comment :)

The clients that I tested are very much and ALL work very well on development mode , but error cors beside gunicorn is persistent:

Chrome browser (like a route template html)

Estension plugin chrome to test socket.io

Another extension plugin that I dont remember name

My personal portfolio (https://alessandromodica.com) in a component angular work well when connect into server on development mode (wow cool!), but not beside gunicorn (i hate unicorn ahah)

Postman with template socket.io

Others random clients, I try with everyone things.

My target is to develope a game, and gunicorn is the last problem of my analysis!

I hope that is usefull to understand what is my mistake. Anyway I will continue to investigate to resolve.

Thanks in advance 

Ale

**Comment by miguelgrinberg** [comment]
@kmtnck you have omitted the most important piece of information: the details about the request that is failing. If you don't provide the request details (URL, method, body if available), response details (status code, body) and error details (exact error message) it is impossible to diagnose the problem.

**Comment by kmtnck** [comment]
Good morning @miguelgrinberg , ok the situation of request and response, is this:

The command on docker that start gunicorn is 

`CMD ["gunicorn","--access-logfile","-", "--error-logfile","-","--log-level", "debug ", "-k", "eventlet", "-w", "4", "-b", "0.0.0.0:5100", "kinkoapp:app"]`


The error happen during session connect and, if I use postman like client and I try to connect at uri

![image](https://github.com/miguelgrinberg/Flask-SocketIO/assets/11504148/0724170d-65e0-45b9-a7d1-732cfa8dbf41)

The log of gunicorn after connect is
```
kinko-websocket-collaudo  | [2024-03-10 09:41:42 +0000] [9] [DEBUG] Closing connection. 
kinko-websocket-collaudo  | [2024-03-10 09:42:28 +0000] [10] [DEBUG] GET /socket.io/
kinko-websocket-collaudo  | 192.168.1.7 - - [10/Mar/2024:09:42:28 +0000] "GET /socket.io/?EIO=4&transport=websocket HTTP/1.1" 404 207 "-" "-"
kinko-websocket-collaudo  | [2024-03-10 09:42:28 +0000] [10] [DEBUG] Closing connection. 
```

I use also the extension chrome called Socket.io Test Client and this screeshoot explain the error
![image](https://github.com/miguelgrinberg/Flask-SocketIO/assets/11504148/7d8ec413-66f7-49b1-84fa-c100edb20145)

```
URL Di Richiesta:
http://devlocale:5100/socket.io/?EIO=4&transport=polling&t=OudmY_Z
Metodo Di Richiesta:
GET
Codice Di Stato:
404 NOT FOUND
Norme Sui Referrer:
strict-origin-when-cross-origin

Connection:
keep-alive
Content-Length:
207
Content-Type:
text/html; charset=utf-8
Date:
Sun, 10 Mar 2024 09:47:15 GMT
Server:
gunicorn

Accept:
*/*
Accept-Encoding:
gzip, deflate
Accept-Language:
it-IT,it;q=0.9,en;q=0.8,ru;q=0.7,en-US;q=0.6,pl;q=0.5
Connection:
keep-alive
Host:
devlocale:5100
Origin:
chrome-extension://ophmdkgfcjapomjdpfobjfbihojchbko
User-Agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

```

and the log of gunicorn of this response is

```
kinko-websocket-collaudo  | [2024-03-10 09:47:15 +0000] [9] [DEBUG] GET /socket.io/
kinko-websocket-collaudo  | 192.168.1.7 - - [10/Mar/2024:09:47:15 +0000] "GET /socket.io/?EIO=4&transport=polling&t=OudmY_Z HTTP/1.1" 404 207 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"

```

The configuration of gunicorn when started is:
```
kinko-websocket-collaudo  | [2024-03-10 09:38:23 +0000] [1] [DEBUG] Current configuration:
kinko-websocket-collaudo  |   config: ./gunicorn.conf.py
kinko-websocket-collaudo  |   wsgi_app: None
kinko-websocket-collaudo  |   bind: ['0.0.0.0:5100']
kinko-websocket-collaudo  |   backlog: 2048
kinko-websocket-collaudo  |   workers: 4
kinko-websocket-collaudo  |   worker_class: eventlet
kinko-websocket-collaudo  |   threads: 1
kinko-websocket-collaudo  |   worker_connections: 1000
kinko-websocket-collaudo  |   max_requests: 0
kinko-websocket-collaudo  |   max_requests_jitter: 0
kinko-websocket-collaudo  |   timeout: 30
kinko-websocket-collaudo  |   graceful_timeout: 30
kinko-websocket-collaudo  |   keepalive: 2
kinko-websocket-collaudo  |   limit_request_line: 4094
kinko-websocket-collaudo  |   limit_request_fields: 100
kinko-websocket-collaudo  |   limit_request_field_size: 8190
kinko-websocket-collaudo  |   reload: False
kinko-websocket-collaudo  |   reload_engine: auto
kinko-websocket-collaudo  |   reload_extra_files: []
kinko-websocket-collaudo  |   spew: False
kinko-websocket-collaudo  |   check_config: False
kinko-websocket-collaudo  |   print_config: False
kinko-websocket-collaudo  |   preload_app: False
kinko-websocket-collaudo  |   sendfile: None
kinko-websocket-collaudo  |   reuse_port: False
kinko-websocket-collaudo  |   chdir: /app
kinko-websocket-collaudo  |   daemon: False
kinko-websocket-collaudo  |   raw_env: []
kinko-websocket-collaudo  |   pidfile: None
kinko-websocket-collaudo  |   worker_tmp_dir: None
kinko-websocket-collaudo  |   user: 1000
kinko-websocket-collaudo  |   group: 1000
kinko-websocket-collaudo  |   umask: 0
kinko-websocket-collaudo  |   initgroups: False
kinko-websocket-collaudo  |   tmp_upload_dir: None
kinko-websocket-collaudo  |   secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
kinko-websocket-collaudo  |   forwarded_allow_ips: ['127.0.0.1']
kinko-websocket-collaudo  |   accesslog: -
kinko-websocket-collaudo  |   disable_redirect_access_to_syslog: False
kinko-websocket-collaudo  |   access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
kinko-websocket-collaudo  |   errorlog: -
kinko-websocket-collaudo  |   loglevel: debug
kinko-websocket-collaudo  |   capture_output: False
kinko-websocket-collaudo  |   logger_class: gunicorn.glogging.Logger
kinko-websocket-collaudo  |   logconfig: None
kinko-websocket-collaudo  |   logconfig_dict: {}
kinko-websocket-collaudo  |   logconfig_json: None
kinko-websocket-collaudo  |   syslog_addr: udp://localhost:514
kinko-websocket-collaudo  |   syslog: False
kinko-websocket-collaudo  |   syslog_prefix: None
kinko-websocket-collaudo  |   syslog_facility: user
kinko-websocket-collaudo  |   enable_stdio_inheritance: False
kinko-websocket-collaudo  |   statsd_host: None
kinko-websocket-collaudo  |   dogstatsd_tags: 
kinko-websocket-collaudo  |   statsd_prefix: 
kinko-websocket-collaudo  |   proc_name: None
kinko-websocket-collaudo  |   default_proc_name: kinkoapp:app
kinko-websocket-collaudo  |   pythonpath: None
kinko-websocket-collaudo  |   paste: None
kinko-websocket-collaudo  |   on_starting: <function OnStarting.on_starting at 0x7f11f341aa60>
kinko-websocket-collaudo  |   on_reload: <function OnReload.on_reload at 0x7f11f341ab80>
kinko-websocket-collaudo  |   when_ready: <function WhenReady.when_ready at 0x7f11f341aca0>
kinko-websocket-collaudo  |   pre_fork: <function Prefork.pre_fork at 0x7f11f341adc0>
kinko-websocket-collaudo  |   post_fork: <function Postfork.post_fork at 0x7f11f341aee0>
kinko-websocket-collaudo  |   post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f11f3433040>
kinko-websocket-collaudo  |   worker_int: <function WorkerInt.worker_int at 0x7f11f3433160>
kinko-websocket-collaudo  |   worker_abort: <function WorkerAbort.worker_abort at 0x7f11f3433280>
kinko-websocket-collaudo  |   pre_exec: <function PreExec.pre_exec at 0x7f11f34333a0>
kinko-websocket-collaudo  |   pre_request: <function PreRequest.pre_request at 0x7f11f34334c0>
kinko-websocket-collaudo  |   post_request: <function PostRequest.post_request at 0x7f11f3433550>
kinko-websocket-collaudo  |   child_exit: <function ChildExit.child_exit at 0x7f11f3433670>
kinko-websocket-collaudo  |   worker_exit: <function WorkerExit.worker_exit at 0x7f11f3433790>
kinko-websocket-collaudo  |   nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f11f34338b0>
kinko-websocket-collaudo  |   on_exit: <function OnExit.on_exit at 0x7f11f34339d0>
kinko-websocket-collaudo  |   ssl_context: <function NewSSLContext.ssl_context at 0x7f11f3433af0>
kinko-websocket-collaudo  |   proxy_protocol: False
kinko-websocket-collaudo  |   proxy_allow_ips: ['127.0.0.1']
kinko-websocket-collaudo  |   keyfile: None
kinko-websocket-collaudo  |   certfile: None
kinko-websocket-collaudo  |   ssl_version: 2
kinko-websocket-collaudo  |   cert_reqs: 0
kinko-websocket-collaudo  |   ca_certs: None
kinko-websocket-collaudo  |   suppress_ragged_eofs: True
kinko-websocket-collaudo  |   do_handshake_on_connect: False
kinko-websocket-collaudo  |   ciphers: None
kinko-websocket-collaudo  |   raw_paste_global_conf: []
kinko-websocket-collaudo  |   strip_header_spaces: False

```

The response that I watch its always a not found

```
index.html:1 Access to XMLHttpRequest at 'http://devlocale:5100/socket.io/?EIO=4&transport=polling&t=OudmY_Z' from origin 'chrome-extension://ophmdkgfcjapomjdpfobjfbihojchbko' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
index-8b620077.js:36 
       GET http://devlocale:5100/socket.io/?EIO=4&transport=polling&t=OudmY_Z net::ERR_FAILED 404 (NOT FOUND)

```

Only on gunicorn I have this problem, otherwise the connect is ok by this uri.

I hope that is usefull this logs and response tracking.
Sure there is a my mistake, but I dont understand what is it.
I will investigate again.

**Comment by miguelgrinberg** [comment]
@kmtnck you are getting 404 errors, this is not related to CORS. The Flask-SocketIO extension isn't properly installed on your application, so all the Socket.IO URLs are returning a 404. The 404 responses by your application do not have CORS configuration, but that is not the main problem here, the CORS problem is a side effect of not having Socket.IO properly set up.

**Comment by kmtnck** [comment]
ok, its a side effect. I notice that if I run server on development debug mode like this
CMD ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "flask", "run", "--host=0.0.0.0"]

its all ok, and the connection is corretly hangon, and all phase of connect and disconnect is ok.

But beside gunicorn, there is a not found 404 and the side effect cors. 
So if all run outside gunicorn, I dont understand what is not properly installed .

ok thanks u , I will investigate to try to understand this why gunicorn give me problem.

thanks anyway

see u

**Comment by kmtnck** [comment]
hello @miguelgrinberg  I resolve!!!!

Your feedback was very important, I check better the configuration of app, and I notice a very strange behaviour on python.
I try to explain the troubleshoot:

During the test with error on gunicorn I had a method on __init__.py of main module that was 

```
import logging
from flask import Flask, request, render_template, session, copy_current_request_context
from flask_socketio import SocketIO, emit, join_room, leave_room, close_room, rooms,disconnect

app = Flask(__name__)

def create_app():

    async_mode = None
    app.config['SECRET_KEY'] = 'secret!'
    app.register_blueprint(main)
    socketio = SocketIO(app, async_mode=async_mode, cors_allowed_origins="*")
    socketio.init_app(app)
    return app
```
I notice that gunicorn run without problem, but raise this not found error. So I notice that gunicorn want a name instance like app and this instance must be builded outside the method, otherwise gunicorn raise an error of AttributeNotFound called app.

After your feedback, I analyze unique part of application that have problem during run of gunicorn and I following the lateral thinking I think that maybe all inizialitation of socketio needed to be execute outside the method createApp

```
import logging
from flask import Flask, request, render_template, session, copy_current_request_context
from flask_socketio import SocketIO, emit, join_room, leave_room, close_room, rooms,disconnect

app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
app.register_blueprint(main)
socketio.init_app(app)

def create_app():
    socketio.init_app(app)
    return app

```

with this source code , where app and init app socketio are defined outside the method create_app()

I can run the app with this snippet code

```
import eventlet
from kinkoapp import create_app, socketio

if __name__ == '__main__':
    app = create_app()
    eventlet.monkey_patch()
    socketio.run(app, allow_unsafe_werkzeug=True)
```

and all work well!
gunicorn want that the instance and configuration of application must be outside a method python? really?

So with this configuration I can run server on gunicorn and I can conquer the world :)

thanks
