### ISSUE TITLE
Ping packages causes connection error on already open connection

### ISSUE THREAD

**Issue by necil** [miguelgrinberg/Flask-SocketIO#914]
Hello I am having some problems with keeping websocket connection open on SocketIO. Short time after client sends ping it gives `connection to ws://.... failed: Invalid frame header` error. Connection's last frame is ` (Opcode -1)`. I tested it with higher ping interval and observed that connection stays stable until first ping (tested it with 30, 60 and 120 seconds). This issue causes a data loss whenever client disconnects and reconnects and corresponds to nearly 15 datapoints in my application. 

server side code test.py

```
from flask import Flask, render_template
from flask_socketio import SocketIO, emit
from time import sleep
import threading
count = 0

app = Flask(__name__)
app.config["APPLICATION_ROOT"]="/testapp"
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app, async_mode="eventlet", http_compression=False, ping_interval=10, ping_timeout=60)


@app.route('/')
def index():
    return render_template('test.html')

def keep_sending():
    global count
    while True:
        print("sent " + str(count))
        socketio.emit("response", {'data':count})
        count+=1
        sleep(0.5)

t = threading.Thread(target=keep_sending)

@socketio.on('connect')
def test_message2():
    print("client connected")
    if not t.is_alive():
        t.start()
    socketio.emit("response")

@socketio.on('event')
def test_message(message):
    for i in range(7):
        emit('response', {'data': 'got it!'})

if __name__ == '__main__':
    socketio.run(app)
```

my client side code is as follows. Here my port is 5001 bacause I use application over reverse proxy.

```
script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.0.3/socket.io.js"></script>

<script type="text/javascript" charset="utf-8">
    var socket = io.connect('http://' + location.hostname + ':5001',{
        'path': window.location.pathname + '/socket.io',
        'transports': ['websocket']
    });
    socket.on('connect', function() {
        console.log("connected")
        socket.emit('event', {data: 'I\'m connected!'});
    });

    socket.on('disconnect', function (reason) {
        console.log('Socket disconnected because of ' + reason);
    });

    socket.on('response', function(data) {
      console.log(data);
    });
</script>
```

And finally I run it with command: `gunicorn -b 0.0.0.0:5000 --worker-class eventlet --workers 1 test:app`

**Comment by miguelgrinberg** [comment]
Does it work better without the reverse proxy? It would be good to eliminate it as a suspect/

**Comment by necil** [comment]
I checked now. It works fine without reverse proxy. I observed that I don't get pong after ping on the one with reverse proxy. Without it, both ping and pongs are fine. I am not sure why it behaves this way.

**Comment by miguelgrinberg** [comment]
Probably a bad WebSocket proxying configuration. Maybe you have a request timeout? That usually needs to be disabled for WebSocket routes. Some proxy servers do not do that on their own.

**Comment by necil** [comment]
Ok thanks a lot for your quick response I will try to fix it via configuration as you said.
