### ISSUE TITLE
Socketio doesn't work properly when Flask is streaming video

### ISSUE THREAD

**Issue by hyansuper** [miguelgrinberg/Flask-SocketIO#916]
I am trying to build a RPi zero controlled toy car with camera and stream video to web page.

I found your project [flask-video-streaming](https://github.com/miguelgrinberg/flask-video-streaming/blob/master/base_camera.py) which works great, and I try to combine it with the [ZeroBot project](https://github.com/CoretechR/ZeroBot), the ZeroBot project runs Node.js on server side, I basically just rewrite the server side in python.

Here is [my project](https://github.com/hyansuper/FPV_RPi_Car), camera streaming works great, but socketio seems to be very slow or not responding: If I click the "light" button on the web page, the server side should print "on_light" and a LED connected on RPi zero should light up, but it didn't.
In the file app.py, if I comment out the video_feed function, then the rest code works fine. print and LED works as expected.

I don't know what's wrong, can you help?
Thanks!

**Comment by miguelgrinberg** [comment]
The video traffic must be saturating the network. Try reducing the video frame rate and/or frame dimensions.

**Comment by hyansuper** [comment]
Thanks for your reply
In my project，I actually use the fake camera driver from your example，which loops 3 pictures，and framerate is 1 fps.
I don't think the network is saturated. Could it be some sort of multithreading problem?

**Comment by miguelgrinberg** [comment]
I still think it is that your network cannot take so much traffic. Add a sleep in the `gen()` function, inside the frame generator while loop. That will put less strain on the network and allow your other stuff to be more responsive.

**Comment by hyansuper** [comment]
The problem is not satrurated network. I think it's because the server is running in single threaded mode by default, so when the the browser request for the image path, the sever will get stuck in the line:
`return response(gen(Camera())...)`
Althong I have added `sleep(1)` in the generator, somehow it does not help. And now the server  can't handle websocket connections.

I managed a workaround, I set async_mode in the line: 
`socketio = SocketIO(app, async_mode='threading')` 
Now the problem is partially solved. the server can handle websocket connections, but in debug mode I can see that it's using polling instead of websockets (but it works fine for my little project anyway).

Setting `async_mode='eventlet'` does not solve the problem
A quick search on the web, I found that Flask can be set with `app.run(threaded=True)`, but when I tried `socketio.run(app,threaded=True)`, an error occurred.

**Comment by miguelgrinberg** [comment]
The threading async mode is intended for development only, as it does not support WebSocket, and also it is based on the Flask development web server, which is not production ready. You should use the eventlet async mode if you want WebSocket support.

> I think it's because the server is running in single threaded mode by default,

Eventlet is asynchronous. It uses cooperative tasks within the context of a single thread. 

> Althong I have added sleep(1) in the generator, somehow it does not help.

Which sleep function did you use? It needs to be the one from eventlet, which you can access as `socketio.sleep()`. The normal sleep function blocks the eventlet server.

> A quick search on the web, I found that Flask can be set with app.run(threaded=True)

This flag is already set when you run in threading mode.

Your project appears to have been removed so I can't take another look. My guess is that you are using GPIO, and this is done in a way that blocks eventlet.

Please reopen if you need more help with this.
