### ISSUE TITLE
C++ client connection

### ISSUE THREAD

**Issue by eric-tc** [miguelgrinberg/Flask-SocketIO#917]
Hi,
 
i am able to send message form a c++ client to flask using this code below, using this repository https://github.com/socketio/socket.io-client-cpp

```
sio::client h;
string test;
test="test";
h.connect("http:://172.31.1.29:5000");
h.socket()-emit("client1",test);

h.socket()->on("test2", [&](sio::event& ev)
{
    cout<<"message received"<<endl;
});
```

but i cannot receive message back from this function

h.socket()->on("test2",sio::event &OnMessage)

I am emit a value from my python flask  

```
from flask_socketio import SocketIO,emit

emit("test2")

if __name__ =='__main__':
      socketio.run(app,host="172.31.1.29",port=5000)
```

i cannot see my cout when i call emit("test2")

If someone was able to send and receive message from a c++ script using flask-SocketIO can explain me how can i do this?

Thanks

**Comment by miguelgrinberg** [comment]
You can't just emit from the global scope in the server. That runs well before any clients are connected.  Try adding the emit in the event handler for the client1 event that you are sending from your C++ client.
