### ISSUE TITLE
Segmentation Fault with requirements installed via pypi

### ISSUE THREAD

**Issue by ingwinlu** [miguelgrinberg/Flask-SocketIO#92]
Hi,

If I install flask-socketio via pip i end up with the following requirements, which segfault the example app after a few moments:
```
Flask==0.10.1
Flask-SocketIO==0.5.0
gevent==1.0.1
gevent-socketio==0.3.6
gevent-websocket==0.9.3
greenlet==0.4.5
itsdangerous==0.24
Jinja2==2.7.3
MarkupSafe==0.23
Werkzeug==0.10
```

If I install the ones from requirements.txt it works fine
```
Flask-SocketIO==0.5.0
Flask==0.10.1
Jinja2==2.7.2
MarkupSafe==0.18
Werkzeug==0.9.4
gevent==1.0
gevent-socketio==0.3.6
gevent-websocket==0.9.2
greenlet==0.4.2
itsdangerous==0.23
ujson==1.33
```

This is probably an 'upstream' issue, but posting here for visibility.

**Comment by miguelgrinberg** [comment]
Yes, I think this is expected. As far as I know, gevent does not support pypy.

**Comment by miguelgrinberg** [comment]
I'm closing this, as it is outdated now that release 1.0 is out.
