### ISSUE TITLE
Flask-SocketIO does not upgarade to websockets

### ISSUE THREAD

**Issue by 1ghost1** [miguelgrinberg/Flask-SocketIO#920]
Hello!

I have a server that re-streams video from ip camera to the web-page with websockets.

Everything works correctly and as intended, but for some reason when I run flask app with socketio on Python 3 the client doesn't upgrade to websockets and instead does long polling. When I try to force client to connect via websocket it returns error during handshake: 400

![image](https://user-images.githubusercontent.com/9949274/54230279-79e42700-44dc-11e9-8a40-b8ac0e300f47.png)

Here is my stream class:

````
from flask_socketio import Namespace, emit,send, join_room, leave_room
from flask import session
from .camera_module import Camera
import time
import json

class StreamServer(Namespace):

    active_cameras = dict()

    def on_probe(self):
        print("Probe incomming")
        emit('status', {'status': "Probed"})


    def on_connect(self):
        emit("status", {'status':  "Test!"})

    def on_disconnect(self):
        # print(self.rooms())
        print("Disconnected!")



    def on_get_stream(self, data):

        print("request to join: " + data)
        join_room(data)
        emit("stream_joined", {"status": "stream_joined_" + data})

    def on_stream_req(self, data):
        # print(data)
        stream = None

        if data in self.active_cameras:
            stream = self.active_cameras[data]['stream']
        else:
            camera = Camera(data)
            self.active_cameras[data] = {"camera_obj": camera, "stream": camera.stream_()}
            stream = self.active_cameras[data]['stream']

        #for frame in stream:
        try:
            if self.active_cameras[data]['camera_obj'].streaming:
                emit("new_frame", next(stream), room=data)
            else:
                emit("camera_not_streaming", {"error": "stream_suspended"})
        except Exception as e:
            self.active_cameras[data]['camera_obj'].kill_stream()
            print(e);
            emit("stream_error", {"stream_status": "stream_killed", "error": str(e)})

        # send(stream.next()['payload'])
        # sleep(0.03333333333)

    def on_still_alive(self, data):
        emit("stay_alive", {"status": "ok"})


```
I dont think you will find anything super wrong with it since it works with python2. I would use python2 but it is pain in the ass to transmit binary data and encoding into base64 adds overhead both network and cpu.

My launcher:

```
app = Flask(__name__)
app.config['SECRET_KEY'] = "TEEEST"
socketio = SocketIO(app, message_queue='redis://')

#SocketIO
socketio.on_namespace(StreamServer("/socket.io/stream_service"));

# Blueprints here
app.register_blueprint(vidos)
app.register_blueprint(vidAPI)


if __name__ == "__main__":
    #app.run(port=8080, debug=True)
    socketio.run(app, port=8080, debug=True)
```
```

**Note: I am not running this with the server in front, this is strictly localhost**

(I know key is insecure, this is not a production server)

**Comment by 1ghost1** [comment]
Oh also this sometimes happens:
![image](https://user-images.githubusercontent.com/9949274/54230646-39d17400-44dd-11e9-9daa-6e3a3f9610d7.png)

**Comment by miguelgrinberg** [comment]
What do you have on your virtualenv? Show me the output of `pip freeze` please.

**Comment by 1ghost1** [comment]
Morning, here is the screenshot:
![image](https://user-images.githubusercontent.com/9949274/54285855-2542b980-4579-11e9-9e69-a8b12be79399.png)

**Comment by miguelgrinberg** [comment]
Nothing jumps out at me as being wrong. Do you get any error messages in the terminal? The 400 errors must be there I assume.

**Comment by 1ghost1** [comment]
Absolutely nothing on the console, at all.

4xx is a client issue, I have read, but it is strange that this happens only when I run this on Python3

**Comment by miguelgrinberg** [comment]
Enable logging and try again please. You should see something in the console, at the very least you should see the 400 status codes in the request logs. To enable logs add `engineio_logger=True, logger=True` arguments to your `SocketIO()` constructor.

**Comment by 1ghost1** [comment]
Hi, for some reason when I moved my image retrieval subroutine to a separate thread websockets started to work.

Are websockets blocking in any way?
