### ISSUE TITLE
Emit from server in while loop only emits once

### ISSUE THREAD

**Issue by DougSauve** [miguelgrinberg/Flask-SocketIO#921]
Hey,
I'm trying to set up a client-controlled data flow from the server. The idea is that the user clicks the start button, and data is pushed from the server until they click the stop button. I've got it mostly working, except for one thing - the server only emits the data once. This is my server code:

```
import eventlet
eventlet.monkey_patch()
import socketio
import time
import multiprocessing
from flask import Flask, render_template, session, request
from flask_socketio import SocketIO, emit, join_room, disconnect

sio = socketio.Server(async_mode='threading')
app = Flask(__name__)
app.wsgi_app = socketio.Middleware(sio, app.wsgi_app)

# state
switch=False
count = 0

@app.route('/')
def index():  
    return render_template('index.html')

@app.route('/dog/')
def bark():
    return 'woof!'

@sio.on('connect')
def connect(sid, environ):
    print('connecting', sid)

@sio.on('message')
def print_message(sid, message):
    print("Socket ID: ", sid)
    print(message)
    sio.emit('message', 'hello client')

@sio.on('disconnect')
def disconnect(sid):
    print('disconnecting', sid)

@sio.on('stop')
def stop(sid):
    sio.emit('message', 'stopping')
    jobs[1].terminate()

@sio.on('start')
def start(sid):
    runProcess(sid)

def runProcess(sid):
  global jobs
  # start outputting switch
  sio.emit('message', 'starting' + sid)

  j1 = multiprocessing.Process(target=startProcess, args=(sid,))
  jobs.append(j1)
  j1.start()


def startProcess(sid):
  a = 0
  while(True):
      time.sleep(1)
      sio.emit('message', 'hi dude ' + str(sid))
      print('hi dude', sid)
      a+=1


def worker():
    a = 0
    while(switch==True):
        time.sleep(1)
        print(a)
        sio.emit('message', a)
        a+=1

        

jobs = []

t = multiprocessing.Process(target=worker)
jobs.append(t)
t.start()

if __name__ == '__main__':
    app.run(threaded=True)
```

I know that the while loop is behaving itself because it continues faithfully printing the message to the console - just the emit falls off the bandwagon after the first time. Is it getting blocked somehow? How can I get around this?

client code:

```
<!DOCTYPE html>
<html>
  <head>
    <title>
      Python Server
    </title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.5/socket.io.min.js"></script>
  </head>
  
  <body>
    MouseGlove
    <div id="app">

    <script>
      const socket = io('http://localhost:5000/');

// connect sockets
socket.on('connect', () => {
  console.log('connected!');
});

socket.on('message', (message) => {
  console.log(message)
  // document.getElementById('app').innnerHTML = message;
});


// create HTML
const startButton = document.createElement('BUTTON');
startButton.innerHTML = 'start';
startButton.onclick = () => {
  socket.emit('start');
}
document.getElementById('app').appendChild(startButton);

const stopButton = document.createElement('BUTTON');
stopButton.innerHTML = 'stop';
stopButton.onclick = () => {
  socket.emit('stop');
}

document.getElementById('app').appendChild(stopButton);

socket.emit('message', 'hello server!');

    </script>
  </body>
</html>
```

**Comment by miguelgrinberg** [comment]
Start the server with `socketio.run(app)` and try again. You are using eventlet, but starting a Flask server. This needs to run on the eventlet server.

**Comment by DougSauve** [comment]
I gave that a shot but it didn't work - it came back saying socketio has no attribute 'run'. I tried changing socketio to sio but that errored saying 'Server object has no attribute run'.
I'm pretty new to Python in general, I'm primarily a JavaScript guy - possibly I'm not doing something in a way you would expect in this file? I'm trying to run two separate servers - one to serve up the actual page (the Flask one) and one to handle the websockets. I'm open to doing that a different way if it's going to cause me problems. :/

**Comment by miguelgrinberg** [comment]
@DougSauve oh, okay. You are using python-socketio, yet, you wrote this issue in the Flask-SocketIO project. I assumed you were using the latter.

For python-socketio, go to the documentation and see how the eventlet server needs to be started: https://python-socketio.readthedocs.io/en/latest/server.html#eventlet.
