### ISSUE TITLE
Gunicorn : eventlet number of workers and threads ....

### ISSUE THREAD

**Issue by Fizmath** [miguelgrinberg/Flask-SocketIO#924]
Hello dear Miguel:

We know that Gunicorn runs with just one worker on SocketIO, i wish we could run with more according to the law `(2*CPU)+1` .Anyway we set `-workers=1` and worker class `-k eventlet` . we also monkeypathced the module .  There is yet another speed up consideration , number of threads, for example `--threads=5`.
Does this number affect the socketio and the speed of background thread processing while many clients connect simultaneously ? 
`gunicorn -k eventlet   -w 1 --threads=5  app:app `

i also went through : 

https://github.com/benoitc/gunicorn/issues/1045

My program runs a heavy processing thread so i want to get the most out of threads .
Thanks

**Comment by miguelgrinberg** [comment]
I'm not sure the `--threads` option has an effect when using the eventlet worker, but if it does it unlikely to be compatible. The problem is that gunicorn does not support sticky sessions, once they add that feature this limitation will disappear.

You know you can run multiple gunicorns as a workaround, right? Instead of a single gunicorn with 2*cpu+1 workers, run 2*cpu+1 gunicorns, each with one worker.

**Comment by Fizmath** [comment]
Ok , shall we Dockerize Flask SocketIo App and then deploy with Kubernetes ? : 

https://cloud.google.com/kubernetes-engine/docs/tutorials/hello-app

which takes care of load-balacing and nodes of instances .

**Comment by miguelgrinberg** [comment]
Load balancing is not a good idea because of the sticky session requirement. If you are going to be starting and stopping nodes constantly then you can't have sticky sessions. Using Kubernetes is okay I guess, it is completely unrelated to the problem and doesn't make the problem better or worse.

**Comment by Fizmath** [comment]
I didn't scorch the web for the following  questions , but , is it possible to run the SocketIO eventlet threads on GPU , say , PyCuda ?  and what are possible ways of spawning  multiple Gunicorns ?for example here on  Google Cloud  :

https://cloud.google.com/appengine/docs/flexible/python/using-websockets-and-session-affinity

**Comment by miguelgrinberg** [comment]
No idea about PyCUDA support, really more of a question for the intended web server, so Eventlet, Gevent, etc. This package would probably not care as long as the web server is happy.

I'm not sure what's the difficult in having multiple Gunicorn instances. Can't you just run them? If you enable session affinity Socket.IO should work just fine.
