### ISSUE TITLE
question: how to use multiple workers

### ISSUE THREAD

**Issue by chendongxtu** [miguelgrinberg/Flask-SocketIO#927]
Hi,  miguelgrinberg,
      i have read the flask_socketio document, according to my own needs，i need "Using Multiple Workers", .
      now  there are two problems confused me, please help me.
      1、in the documents, it said "The load balancer must be configured to forward all HTTP 
            requests from a given client always to the same worker",  in the demo, use ip_hash.
           but just  suppose such a scenario： if the network is bad, then i change it to wireless, then 
           its  ip changed,  if use ip_hash, it may be router to other worker cause of  its ip changed, 
           how can i guarantee the same client always to the same worker?
      2、when  i use it like this:
       ```python
                  socketio = SocketIO(app, message_queue='redis://')
       ```
      when a message arrives（someone write a message to redis）, can it automatically perceive 
      the message?
      for example:
       there are two websockt servers A and B ,  one flask app server C. Now Server A and B are listen 
       to  redis D. Then server C write a message to redis D, how it can tell the socket 
       server A and B knows that  redis D has a message arrived? does it have already use the redis
      pub-sub model?
                                                                                                  look forward to your reply, thanks!

**Comment by miguelgrinberg** [comment]
>  it may be router to other worker cause of its ip changed,how can i guarantee the same client always to the same worker?

You can't guarantee it. In this situation the client will lose the connection, and will reconnect immediately after. Not a big problem if it happens occasionally, but not something you want to happen constantly.

I don't understand your second question. Flask-SocketIO handles the redis connection, you do not need to read or write from redis, just tell Flask-SocketIO where redis is running. And yes, the communication is done through the pub/sub feature of redis.

**Comment by chendongxtu** [comment]
thanks,
 to the second question,  suppose such a case :
     there is a flask app named online_auction， which connect a redis server on port 6379 , suppose it has deployed on two servers(S1, S2) , bidder A, B located in S1, bidder C, D located in S2. There has a websocket server S3, which connect the same redis as the  flask app connected, and bidder A, B, C, D connect S3.  suppose bidder A has given the current maximium price,  then the flask app will write an price message to redis on port 6379, the socketio server must capture the latest price message  immediately and send it to B,C,D through the websocket to let B,C,D know the current price. 

so after read the document, i do not know how to achive it.
1、 does the flask app server and socket server need connect redis same port(i.e 6379)?
2、when flask app write a meesage to redis, how the socketio server fecth and process it?

simply to say, flask app server write a message to redis, how does the socketio server know there has a meesage comming and then fecth it to process.
is there any demo?  maybe my description is not very clear， i'm sorry for that.

**Comment by miguelgrinberg** [comment]
@chendongxtu I think you are overthinking this problem. Consider a single server set up, where all your bidders are in the same process. When your application receives a bid, it broadcasts it to all the other bidders. No problems with this approach, right?

Now let's go back to your example with 3 servers and the bidders spread among them. The only change you need to make is to point each server to the redis instance. That's it. If any of the servers broadcasts a message, all the bidders will get it, just like in the single server example. You do not need to think about redis, just have it running and configured for all the servers.

**Comment by chendongxtu** [comment]
the main problem is i can not describle my demands clearly.
please take some time looking at this picture:
![企业微信截图_15531703429553](https://user-images.githubusercontent.com/32007225/54751398-d00c4500-4c15-11e9-9711-ef801475ab1a.png)

**Comment by miguelgrinberg** [comment]
The socket.io server is not a separate entity. You will have a socket.io server inside S1 and another inside S2.

If you want to broadcast to all your connected bidders, you just do `sio.emit('event-name', event_data)`. You can do this from S1 or from S2, it does not matter, all bidders will get the event.

**Comment by chendongxtu** [comment]
because i want to seprate websocket server from flask app application. because i don't want to let the flask app and the socket io  server listen to the same port.  a[https://github.com/miguelgrinberg/python-socketio/issues/270](url).
so can not i use the flask socket_io server sepratelly?

**Comment by miguelgrinberg** [comment]
You can, but then we are back at the beginning, you need to do all the pub/sub stuff yourself. I was giving you a solution that is all done.

If you want to pass data between a couple of Flask servers and a Socket.IO server through redis of course you can, but this needs to be done in your application. What is the problem them? Just use the pub/sub functions in the Python redis client.

**Comment by chendongxtu** [comment]
umm, thanks for your relpy, i will try to use the pub/sub in the python redis client. thanks again

**Comment by chendongxtu** [comment]
Hi, miguelgrinberg, thanks very much!
   I have successfully seprate  Flask servers and a Socket.IO server, and after my dedug, i know how to publish a message to redis, just using the following format:
```
    event_msg = {
        'method': 'emit',
        'event': UsedCarAuctionStatus.code_of(auction.status),
        'namespace': '/auction_car',
        'skip_sid': None, # 广播时不发送的客户端ID
        'host_id': None, # 调用回调函数时需要设置
        'callback': None, # 回调函数
        'room_id': auction.id,
        'room_name': 'auction_car_{}'.format(auction.id),
        'data': _build_auction_detail_brief(auction) or {}
    }

    try:
        redis.publish('auction_info_broadcast', pickle.dumps(event_msg))
    except Exception as e:
        ..........
```
then the sockertio_server listen to the channel auction_info_broadcast will publish the message to all cilents, thanks.

now i have some problems on how to tell the clients specific  error msgs . for example:
when the client connect to socketio server, if the access token is  invaild, i will refuse the connection,
in the document, is says just return False to refuse the connection, but at the sametime, i wanna tell the
cilent the reason why i refused connection. i have tried like this, but it takes no effect:
```
@socketio.on('connect', namespace='/test')
def test_connect(msg):
    print('------client{},  trying connect-------',.format(request.sid))
    
    access_token = message['access_token']
    if not access_token:
        return False, 'access_token_lacked'  # here i want to tell the client why connect failed

    try:
        data = jwt.decode(access_token, current_app.config.get('SECRET_KEY'))
    except Exception as e:
        current_app.logger.error(
            'fail to decode access_token: %s. \nerro_info: %s', access_token, e)
        return False, 'decode access token failed'  # here i want to tell the client why connect failed

    else:
        user_id = data.get('user_id')

    if AuctionUser.query.get(int(user_id)) is None:
        return False, 'auction user not exisits'  # here i want to tell the client why connect failed
```
then i tried like this, it takes no effect too:
```
@socketio.on('connect', namespace='/test')
def test_connect(msg):
    print('------client{},  trying connect-------',.format(request.sid))
    
    access_token = message['access_token']
    if not access_token:
        emit('my_resonse',   {'data': 'not connected', 'reason': 'access_token lost'})
        return False

```
if i use callback, it is the client tell the server., not the server tell the client.
so how can i tell the client some hint info when error occurs? thks

**Comment by miguelgrinberg** [comment]
First of all, you do not need to write directly to Redis. You can create a `SocketIO()` object and use its `emit()` method, just like you do on the server process. The only difference is that you don't pass the `app` instance when you create it:

    socketio = SocketIO(message_queue='redis://')
    # ...
    socketio.emit('auction_start', data)

The current version of this package does not support returning data with a connection refusal. One way you can do this is by having the client disconnect after it is told the reason why the connection was not accepted. So your connection handler will emit an event with the error information without returning `False`. The connection will be established and then the client can issue a disconnect after it receives the error message.

**Comment by chendongxtu** [comment]
hi,miguelgrinberg:
   with your help,  i have developed an simple websocket server, when i use commnad:
```
python ./manage.py runerver -h 0.0.0.0 -p 5000
```
in my development env , everything works well. 

when i push the project to gitlab, i'm useing this way to start the project:
```
gunicorn -b :5000 -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 wsgi:application
```
then problems are coming:
1、the param -w , when i give an value lager than 1, for exapmle 2, some case it will give me 400 error,
     when i use 1, no 400 probems ocurred. does it to say it is only can be one worker(one pod)?
2、when the projects is runing, it is very stranges that it can only transfer data from the server, and the cilent can not receive the data. i don't know how to fix it, can you help me? thanks.

![企业微信截图_15546948181553](https://user-images.githubusercontent.com/32007225/55697265-33a6b880-59f3-11e9-98b5-f95956b78110.png)

here is my demo code:
https://github.com/chendongxtu/auction-ws-web.git

**Comment by chendongxtu** [comment]
hi, miguelgrinberg:
   with your help,  i have developed an simple websocket server, when i use command:
```
python ./manage.py runerver -h 0.0.0.0 -p 5000
```
in my development env , everything works well. 

when i pushed the project to gitlab and used this way to start the project:
```
gunicorn -b :5000 -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 wsgi:application
```
everything works well too(if not sepcify the -w param, it works well too). 
but when i give the param -w value 2, things are out of control. much of disconnect and connect event happend.
this is the info when give -w value 2（three client from three differnet ip）：
```
++++++++-----test-----++++++++++
Client disconnected 02903d799f4f4e918af2efca1a9595b3
++++++++-----test-----++++++++++
Client disconnected 920a63c725574e70980cf5e58a24a033
++++++++-----test-----++++++++++
Client disconnected f5b55aaf42a642a18519b6173fb3e283
Client disconnected 2c2a18b338f04fc085fcc3e18ef2cd39
++++++++-----test-----++++++++++
Client disconnected 9cfdae9c8dc145c984bdd687f537bf65
++++++++-----test-----++++++++++
++++++++-----test-----++++++++++
Client disconnected 85e02e0fc5204986bb48f486b13f46cf
++++++++-----test-----++++++++++
Client disconnected 76c96ef59a0e48d2b2c9216a1a826411
++++++++-----test-----++++++++++
Client disconnected 773b4a624bf9421c99aaf597404ecac2
++++++++-----test-----++++++++++
Client disconnected 14e30eb4913244868694fccb5bbaae00
++++++++-----test-----++++++++++
Client disconnected f8026cc16c10411f8d22759c73fad9fc
++++++++-----test-----++++++++++
++++++++-----test-----++++++++++

```

question1:
does it to say -w can only have the value 1? if so, why?


in my docker file,  when i try to run more than one pods(eg: 4  TEST_KUBE_REPLICAS=4),
lots of 400 connect happend. following is the snapshot:

![企业微信截图_1554711144845](https://user-images.githubusercontent.com/32007225/55708994-dd00a500-5a19-11e9-9bc7-d3016f483b54.png)

questions2:
if this project will have some of pods(i can not specify the ip_hash paramter. because if any of pod restarted, its ip might changed)
if i not specify the ip_hash in nginx conf, what's will happend ?
does it to say i just can use one kube replicas?

please help me thanks.

so only one worker and one pod can work well, if num of worker larger than 1 or num of pods larger than 1, it can not work correctly.
here is my code link:
https://github.com/chendongxtu/auction-ws-web.git

**Comment by miguelgrinberg** [comment]
This is covered in the deployment section of the documentation, along with a solution to support multiple workers when you add a message queue.

**Comment by chendongxtu** [comment]
i have used the websocket server as a standalone server in order to use different port

**Comment by chendongxtu** [comment]
Hi, miguelgrinberg !
   i've use sessionAffinity=CilentIp in sevice.yml file.  this is similar like to use ip_hash on nginx.
   and i have use redis as the message_queue in my demo. when k8s pod replicas num=1, everything works well, include the demo from example/app.py and my own demo.
   but when i sepcify the replicas=2 or more, the demo example/app.py will encouter many 400 error as mentioned above, but my own demo works correctly. i can not fix why this occurs, i have use tcpdump to track the package but can find any usefull informations.
   does the demo exampe/app.py(include index.html) can only work in a single pod? if so, why? can u tell me, thks.
