### ISSUE TITLE
incompatible with python-socketio 4.0.0

### ISSUE THREAD

**Issue by neox387** [miguelgrinberg/Flask-SocketIO#929]
'python-socketio>=2.1.0,<4'

Not ready yet to use python-socketio 4.0.0 ?

**Comment by miguelgrinberg** [comment]
Not at this time. There's going to be a version bump on this side before I allow the socketio v4 as a dependency.

There is actually no major incompatibility, but some defaults were changed in v4. To avoid the risk of apps starting to fail in weird ways due to this change I currently stay on v3.
