### ISSUE TITLE
502 bad gateway error with Gunicorn Nginx configuration

### ISSUE THREAD

**Issue by tcvandongen** [miguelgrinberg/Flask-SocketIO#930]

**Comment by miguelgrinberg** [comment]
Nothing to do with this project, check your nginx and/or gunicorn configuration.

**Comment by tcvandongen** [comment]
Hi Miguel,

Indeed. However, I have no clue how to proceed here.

Hopefully you can see by quick inspection where I am taking a wrong turn?

Kind regards, Thijs

**Comment by tcvandongen** [comment]
Hi Miguel

You are right but I am completely stuck and have spend days on it now!

Could you please have a quick look and hopefully point me in the right
direction?

Thijs

Op wo 20 mrt. 2019 22:32 schreef Miguel Grinberg <notifications@github.com>:

**Comment by miguelgrinberg** [comment]
502 means that nginx is not able to communicate with gunicorn, you need to check the configuration and make sure the settings you put in the nginx config are consistent with the gunicorn config.
