### ISSUE TITLE
Eventlet is blocking when calling non-python functions

### ISSUE THREAD

**Issue by bjschwarz** [miguelgrinberg/Flask-SocketIO#933]
I am developing a flask-socketio based server which calls functions within a swig wrapped c++ api. The swig-api has been compiled with the CMAKE "-threads" option to unlock the python GIL while executing internal C++ code. 

All of the swig-api functions are executed within a socketio.start_background_task(), this keeps them out of the main thread..

If I run the server using the async_mode = "eventlet" / "gevent" socketio blocks when executing swig-api functions. This is especially noticeable with longer functions 1-10 seconds. I have tried monkey_patching eventlet and gevent with no change. I am unsure if the eventlet "greenthreads" would work correctly calling c++ wrapped functions?

If I run the server using the async_mode = "threading" the server works correctly with no blocking. The problem I am facing with this option is that some critical functionality within the server depends on the socketio.on('disconnect') being called immediately when a client is disconnected (like for example on a page refresh). With the threading option the disconnect callback is not triggered for ~60 seconds.

Is there a work around which would allow me to use eventlet/gevent with a swig-c++ api? Or a way to immediately be notified of a client disconnect while using threading?

**Comment by miguelgrinberg** [comment]
C++ code is not friendly to green threads. What I think you may be missing is that the entire eventlet process with all of its green threads runs in a single physical thread. So the GIL is never a problem for eventlet because there is never a thread switch.

My recommendation is that you separate the C++ code from the server code. Use separate processes and have them communicate by some IPC method, maybe through a message queue.

**Comment by bjschwarz** [comment]
Thanks for the suggestion @miguelgrinberg. I spent some time trying out celery + redis as a solution to this. In the hope that celery's separate processes would fix the problem.

The issue I ran in to is the inability to serialize non JSON objects. This makes sense since it must pass communications over redis. Currently I have a large dictionary map which manages the swig-c++ objects and I can call functions on these objects within the server.

Since I cannot move these objects into redis I would have to create these objects in the other process.  As far as I know there is no ability to create an object and call subsequent methods on it with celery? Or can celery processes share the servers memory?

**Comment by bjschwarz** [comment]
From @miguelgrinberg 's suggestion I am going to move to a cluster type architecture. The main server will handle requests and push them onto a redis queue. This queue will be subscribed to by custom worker processes which have the ability to create and hold these c++ objects. The workers will then emit back to the client using a message_broker socket instance. This will allow eventlet to manage requests within the main server process and be uninterrupted by the threads spawned in the workers.
