### ISSUE TITLE
Flask socket io works only locally and not with an ip

### ISSUE THREAD

**Issue by vibss2397** [miguelgrinberg/Flask-SocketIO#935]
Hi, I am working on an app on react native and to test out and build app i first connected it to a node.js server and then shift to flask, but the problem is that with flask, connections only from the web side work but, when i try to connect from my react native app using the ip address it does not work, i changed the address to the ip address on the html side too and it didn't work there either

Flask code:
```
    app = Flask(__name__)  
    app.config['SECRET_KEY'] = 'secret!'  
    io = SocketIO(app)  
    clients = []  
    @io.on('connect')  
    def connected():  
        print ("connected")  
        clients.append(request.sid) 
```

for the react native side, it uses simple: 
```
window.navigator.userAgent='react-native'  
import io from 'socket.io-client/dist/socket.io'  
    constructor(props) {  
        super(props);  
          this.socket: io('http://192.168.1.7:5000',{jsonp: false}),  
        this.socket.on('connect', () => {  
            console.log('connected');  
         });  
      }  
```

for web it was the example code only:
``` var socket = io.connect('http://' + document.domain + ':' + location.port);
                socket.on('connect', function() {
                    socket.emit('my event', {data: 'I\'m connected!'});
                });
```

yet only the web examoke works and not my react native code

**Comment by miguelgrinberg** [comment]
How are you running your server? Did you set the host address to `0.0.0.0` so that the server listens on the public IP interfaces?

**Comment by vibss2397** [comment]
hey, i am sorry, i noticed that a few minutes ago, i was about to come here to respond that. Thanks anyway

**Comment by skillgamer** [comment]
> hey, i am sorry, i noticed that a few minutes ago, i was about to come here to respond that. Thanks anyway 💯

how did you changed that ?
