### ISSUE TITLE
Gunicorn : RuntimeError: You need to use a gevent-socketio server.

### ISSUE THREAD

**Issue by yoyoprs** [miguelgrinberg/Flask-SocketIO#94]
__Configuration__:
Flask==0.10.1
Flask-HTTPAuth==2.3.0
Flask-Login==0.2.11
Flask-SocketIO==0.5.0
Flask-SQLAlchemy==2.0
Flask-Triangle==0.5.4
Flask-WTF==0.11
gevent==1.0.1
gevent-socketio==0.3.6
gevent-websocket==0.9.3
greenlet==0.4.5
gunicorn==18.0
itsdangerous==0.24
Werkzeug==0.10.1

__command__:
gunicorn --worker-class socketio.sgunicorn.GeventSocketIOWorker  -b 127.0.0.1:5000 run:app -w 1

__conf_nginx__:
Pasted from documentation

__case__:
I tested behind two proxy servers (Squid proxy and another at work).
Negotiation between socketio is well done, xhr-polling is taking place after about thirty seconds (it is really long) but before that, socketio trying to get http://domain.com/socket.io/static/flashsocket/WebSocketMain.swf (flashsocket solution) .
And an error (non-blocking) is logged:

Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/gevent/pywsgi.py", line 508, in handle_one_response
    self.run_application()
  File "/usr/lib64/python2.7/site-packages/gevent/pywsgi.py", line 494, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask_socketio/__init__.py", line 27, in __call__
    raise RuntimeError('You need to use a gevent-socketio server.')
RuntimeError: You need to use a gevent-socketio server.
{'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'fr,fr-fr;q=0.8,en-us;q=0.5,en;q=0.3',
 'HTTP_CACHE_CONTROL': 'max-age=259200',
 'HTTP_CONNECTION': 'Upgrade',
 'HTTP_COOKIE': 'remember_token=eyJhbGciOiJIUzI1NiIsImV4cCI6MTQyMzEwNDY4OCwiaWF0IjoxNDIzMTA0MDg4fQ.eyJpZCI6MX0.Zy2fzpuyng6OD0gljIgnJnASVvQEhvTJeldgBrJwwGE; session=.eJw9zj0LgzAUheG_Uu7soCVdBLeIZLi3dCgSF6E1ts1HC1FJG_G_1zp0OvAOD2eGtvdquEM--kkl0D46yGfYXSAHjJ1BXmbrWqwFk_rEqBaBnDgQLxnGu5XaBOSmgCWB6-D7dnwZ9fwTxDFtKnIUZUravI81fn5NauuoQiajdTKuLL-xphJ7iueAodi4aVB-uwMZLF_0zjZA.B7Rp2g.kvPeov3zbij6Z3KYujOHNeMV7HM',
 'HTTP_DNT': '1',
 'HTTP_HOST': 'domain.com',
 'HTTP_REFERER': 'http://domain.com/apps/',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:10.0.7) Gecko/20100101 Firefox/10.0.7',
 'HTTP_VIA': '1.1 domain.com (squid/3.3.8)',
 'HTTP_X_FORWARDED_FOR': '127.0.0.1, X.X.X.X',
 'HTTP_X_REAL_IP': 'X.X.X.X',
 'PATH_INFO': '/socket.io/static/flashsocket/WebSocketMain.swf',
 'QUERY_STRING': '',
 'RAW_URI': '/socket.io/static/flashsocket/WebSocketMain.swf',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_PORT': '56292',
 'REQUEST_METHOD': 'GET',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'localhost.localdomain',
 'SERVER_PORT': '5000',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'gevent/1.0 Python/2.7',
 'gunicorn.sock': <socket at 0x3807350 fileno=12 sock=127.0.0.1:5000 peer=127.0.0.1:56292>,
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7ffc597721e0>,
 'wsgi.input': <gevent.pywsgi.Input object at 0x37f9a90>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)} failed with RuntimeError

I think it would be nice to change the order of used transports (websocket, xhr multipart, htmlfile, jsonp-polling, flashsocket, xhr-polling) or activate those we want.
Because between the first (websocket) and the last (xhr-polling which seems to cross all proxies), the timeout on the web interface is really too big

ps: I like to annoy you these days Miguel (it's John from your blog)

**Comment by miguelgrinberg** [comment]
So SocketIO was downgrading the connection to the alternative transports, so that means WebSocket was not available. What browser are you using? Is it expected that WebSocket would not be available?

> ps: I like to annoy you these days Miguel (it's John from your blog)

Hah, not at all. So far all your questions and now bug reports have been totally reasonable, you clearly do your own homework. Not annoying in my book :)

**Comment by yoyoprs** [comment]
I have a standard browser, the latest version of Firefox (see trace).
Yes it is expected that websocket is not supported on many proxy (the proof: SQUID is the most common proxy server).
What I want to highlight:
- If FlaskSocketIO does not support FlashSocket, so turn off the transport by default. This will avoid the error.
- Or leave the choice to select transport (it is possible in many libraries)

The last point and this is my feedback, the only transport that passes without problem from different proxy is xhr-polling => then it would be interesting to prioritize the list of transport because the time to switch between other transport is very very long.

**Comment by miguelgrinberg** [comment]
@yoyoprs as far as I remember, the only requirement for the Flash transport is that the application serves the swf file from the Socket.IO Javascript client.

You bring up a good point, the extension could look for this file and if not found the flash transport should be disabled.

**Comment by yoyoprs** [comment]
And do you think it would be possible to disable the transports we do not want to use?

**Comment by miguelgrinberg** [comment]
That is currently possible. Add `policy_server=False` to the `socketio.run()` call. The entire list of allowed arguments to `run()` is in the documentation. See http://flask-socketio.readthedocs.org/en/latest/#flask.ext.socketio.SocketIO.run.

**Comment by yoyoprs** [comment]
Sorry I missed that part Thank's !!!!

**Comment by yoyoprs** [comment]
You confirm the call : 
socketio.run(app, host='127.0.0.1', port=5000, policy_server=False, transports='websocket, xhr-polling, xhr-multipart')
Because i've no errors, and FlashSocket is still called

**Comment by aj07mm** [comment]
i had the same issue, the strange thou is that the socket works fine

**Comment by miguelgrinberg** [comment]
Unfortunately I've been busy, did not have time to look into this and other pending issues yet. But I do intend to figure out why the Flash transport is requested even though the server is saying it doesn't have it. It might be a client issue, in which case there is nothing I can do.

**Comment by ktoh** [comment]
I ran into this issue last week and yes, it was because the transport was being downgraded.
Thought I'd share my experience because I suspect others might run into the same problem:

* In my case, I was deploying something on Amazon Web Services and the client was not able to upgrade the connection to WebSockets.
* This turned out to be a [known issue](https://forums.aws.amazon.com/thread.jspa?messageID=402895) with AWS load balancers (ELB's)  which for some disappointing reasons still do not support websockets.
* By fixing the upstream issue and unblocking the transport problem, this issue disappeared.

My recommendation to others running into this is to check to make sure your browser/client<->server architecture isn't blocking websocket transport (both the initial socket connection and subsequent socket comms and reconnects). 

My case does look different from what some others on this thread are experiencing, but thought I'd share it in case it helps someone.

**Comment by lukeyeager** [comment]
I see these errors in my log when running my server on EC2:
```
Traceback (most recent call last):
  File "venv/lib/python2.7/site-packages/gevent/pywsgi.py", line 508, in handle_one_response
    self.run_application()
  File "venv/lib/python2.7/site-packages/geventwebsocket/handler.py", line 88, in run_application
    return super(WebSocketHandler, self).run_application()
  File "venv/lib/python2.7/site-packages/gevent/pywsgi.py", line 494, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "venv/lib/python2.7/site-packages/flask_socketio/__init__.py", line 27, in __call__
    raise RuntimeError('You need to use a gevent-socketio server.')
RuntimeError: You need to use a gevent-socketio server.
{'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': '*/*',
 'HTTP_HOST': 'xxx:5000',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.1) Gecko/2008070208 Firefox/3.0.1',
 'PATH_INFO': '/socket.io/1/websocket/337339783727',
 'QUERY_STRING': '',
 'REMOTE_ADDR': 'xxx',
 'REMOTE_PORT': 'xxx',
 'REQUEST_METHOD': 'GET',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'xxx',
 'SERVER_PORT': '5000',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'gevent/1.0 Python/2.7',
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7fcc38ecd1e0>,
 'wsgi.input': <gevent.pywsgi.Input object at 0x7fcbfcbcbb90>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)} failed with RuntimeError

Traceback (most recent call last):
  File "venv/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "venv/lib/python2.7/site-packages/socketio/server.py", line 124, in handle
    handler.handle()
  File "venv/lib/python2.7/site-packages/gevent/pywsgi.py", line 184, in handle
    result = self.handle_one_request()
  File "venv/lib/python2.7/site-packages/gevent/pywsgi.py", line 321, in handle_one_request
    self.handle_one_response()
  File "venv/lib/python2.7/site-packages/socketio/handler.py", line 170, in handle_one_response
    self.transport.do_exchange(socket, request_method)
  File "venv/lib/python2.7/site-packages/socketio/transports.py", line 241, in do_exchange
    websocket = self.handler.environ['wsgi.websocket']
KeyError: 'wsgi.websocket'
```

Oddly, most of the SocketIO messages are still getting through. It's as if the first message causes an exception, and then the rest of them go through without a hitch. Maybe that's what @aj07mm is reporting, too.

Also, `'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7fcc38ecd1e0>,` isn't very helpful. That should be an easy bug to fix somewhere.

**Comment by miguelgrinberg** [comment]
Closing, as this issue only applies to pre-1.0 releases.
