### ISSUE TITLE
How to reconnect to socket after I force to disconnect on button click

### ISSUE THREAD

**Issue by bumbumpaw07** [miguelgrinberg/Flask-SocketIO#942]
How to reconnect to socket after I force to disconnect on click in my start button, I used to disconnect it  if `if condition` is `true` on purpose but what I need now is able to reconnect to call the `open_room` function in python even `socket.disconnect()` was already run through in start button event. Thanks in advance.

```
var socket;
$('#start').click(function () {
        socket = io.connect(location.protocol + '//' + document.domain + ':' + location.port + '/test', {forceNew:true});

        socket.on('my_response', function(msg) {

            if (msg.data === 'stopped') {
               socket.disconnect();
            }
        }
    };

    $('form#close').submit(function(event) {
        socket.emit('open_room', {name: $('#name').val()}); // this not called if the `socket.disconnect()` is run through already
        return false; 
    });

    @socketio.on('open_room', namespace='/test')
        def open(message):
            print 'open'
    `
```

**Comment by miguelgrinberg** [comment]
Can't you just call `close_room` in the disconnect handler?

**Comment by bumbumpaw07** [comment]
> Can't you just call `close_room` in the disconnect handler?

Thanks for the reply. No, I need a UI event for the `close_room` or `open_room` function.

**Comment by miguelgrinberg** [comment]
I don't understand why you want to reconnect only to call close_room, but in any case, what is the problem with doing that? If the client connects again, it should work as you want. Or am I missing something?
