### ISSUE TITLE
Question: send an event from repl or worker to the server

### ISSUE THREAD

**Issue by edelvalle** [miguelgrinberg/Flask-SocketIO#944]
I want to send and event inside the server, so having a receiver like this one:

```python
@socketio.on('eventname')
def got_it():
    print('the event is here')
```

I want to do go in the repl and do:

```python
s = SocketIO(message_queue='redis://', async_mode='threading')
s.emit('eventname')
```

And see how the ruining server gets the event. But what happens instead is that the event gets published to the connected JavaScript clients. 

When I emit on the JavaScript side I can see the server receive the message, which is ok and how it suppose to work. So no problem there... but just as additional information.

Why the server does not get the event?

**Comment by miguelgrinberg** [comment]
You are trying to emit and receive on the server? That's not what this library is for, why would you want to do that? Isn't it easier to just call the function that you want?

**Comment by edelvalle** [comment]
Ok, if the library is not intended for that it's ok.
I'm trying to replicate Phoenix LivewView in Flask :dancer: 

I succeeded already, will publish it soon.

I just wanted do some extra improvements... Will see how to do them any way, in another way.

And Miguel, this is an amazing library thank you for your work!
