### ISSUE TITLE
Unable to use new IBM socket-io library

### ISSUE THREAD

**Issue by ajmcateer** [miguelgrinberg/Flask-SocketIO#945]
I am working with a new .NET socket.io library, the old one is depreciated.

[IBM Socket-io](https://github.com/IBM/socket-io)

It currently only supports rooms without a namespace. Which is fine for my needs for now. The only issue is I keep getting 

`OSError: [WinError 10038] An operation was attempted on something that is not a socket`

during the initial connection, despite this error it appears to be making a connection. as I will see shortly after the error.
 
`Client disconnected 3e07982a3f3740548a4ad70d4866cc47`

The problem is this is preventing the library from using the established connection. I found a work around but it doesn't seem to fix it in this case, it just gives me a new error instead

work around
```
  <system.net>
    <settings>
      <httpWebRequest useUnsafeHeaderParsing="true" />
    </settings>
  </system.net>
```
new error
`System.Net.WebException: The underlying connection was closed: The connection was closed unexpectedly.`

I still see the same error in the flask socketio example app

My Code

```
using IBM.SocketIO.Impl;
using IBM.Webclient;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace socketioPOC
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            var mediator = new SocketMediator("ws://127.0.0.1:5000/test");
            var task = mediator.InitConnection(new SampleHttpClientFactory(), new ClientSocketFactory());
            var awaiter = task.GetAwaiter();

            awaiter.OnCompleted(() =>
            {
                if (task.IsFaulted)
                {
                    Console.WriteLine("Failed");
                }
                else
                {
                    Console.WriteLine("Success");
                }
            });
        }
    }

    public class SampleHttpClientFactory : IHttpClientFactory
    {
        public IHttpClient CreateHttpClient()
        {
            return new IBMHttpClient();
        }
    }
}
```

**Comment by miguelgrinberg** [comment]
Shouldn't you be asking your question on the project that is giving you these errors? I don't know anything about this library, sorry.

**Comment by ajmcateer** [comment]
Hi @miguelgrinberg,

I should have been a bit more clear, This library works with another Socketio server not using your library. I opened a ticket here because I noticed there were other issues raised 

https://github.com/miguelgrinberg/Flask-SocketIO/issues/160
https://github.com/miguelgrinberg/Flask-SocketIO/issues/200
https://github.com/miguelgrinberg/Flask-SocketIO/issues/350

In the past they seemed to be benign and not causing any real issues. With the new library which implements Microsoft's HttpClient it doesn't seem to be benign anymore. I am pretty new to networking but from what I can tell HttpClient doesn't like the error that other people are able to ignore and it fails to establish a connection.

**Comment by miguelgrinberg** [comment]
I'm still confused, because you are reporting client errors you get for the C# library. This:

    OSError: [WinError 10038] An operation was attempted on something that is not a socket

can't possibly be caused by the server.

Do you get any errors on the server? Run the server with logging for additional details.

**Comment by ajmcateer** [comment]
`OSError: [WinError 10038] An operation was attempted on something that is not a socket`

That error is from the server.

**Comment by miguelgrinberg** [comment]
Okay, do you have Python stacktrace for it then?

**Comment by ajmcateer** [comment]
```
Traceback (most recent call last):
  File "C:\Users\AjMcateer\AppData\Local\Programs\Python\Python37-32\lib\site-packages\eventlet\greenpool.py", line 82, in _spawn_n_impl
    func(*args, **kwargs)
  File "C:\Users\AjMcateer\AppData\Local\Programs\Python\Python37-32\lib\site-packages\eventlet\wsgi.py", line 686, in process_request
    proto.__init__(sock, address, self)
  File "C:\Users\AjMcateer\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 719, in __init__
    self.finish()
  File "C:\Users\AjMcateer\AppData\Local\Programs\Python\Python37-32\lib\site-packages\eventlet\wsgi.py", line 603, in finish
    greenio.shutdown_safe(self.connection)
  File "C:\Users\AjMcateer\AppData\Local\Programs\Python\Python37-32\lib\site-packages\eventlet\greenio\base.py", line 469, in shutdown_safe
    return sock.shutdown(socket.SHUT_RDWR)
OSError: [WinError 10038] An operation was attempted on something that is not a socket
```

**Comment by miguelgrinberg** [comment]
Eventlet and gevent are not that well supported under Windows, this isn't really something I have control of. If you want to use one of these libraries on Windows I suggest you try running your server under WSL or maybe Cygwin. These will likely give you better results.

**Comment by ajmcateer** [comment]
Thanks @miguelgrinberg, I switched async_mode to threading and its getting past the error but I keep getting a bad request when the library tries to upgrade to the websocket. My guess is the library is doing something wrong but I can't really tell what is the server sends back just 

Bad Request

no error or stack trace, is there anyway to enable more logging to see what part of the request it doesn't like.

**Comment by miguelgrinberg** [comment]
The threading mode does not support WebSocket.
