### ISSUE TITLE
KeyError on attempt to reconnect a disconnected socket

### ISSUE THREAD

**Issue by ffleandro** [miguelgrinberg/Flask-SocketIO#946]
Using `socket.io-client-swift` version 15.0.0 and `Flask-SocketIO` version 3.3.2, I always get the following error after attempting to recconect on a socket that has been previously called `.disconnect()`:

```
Server initialized for eventlet.
513d5ca73cfd443d8ff3e0edb3e04724: Sending packet OPEN data {'pingTimeout': 60000, 'sid': '513d5ca73cfd443d8ff3e0edb3e04724', 'pingInterval': 25000, 'upgrades': []}
DEBUG 2019-04-13 20:31:41,148 MainThread controllers.py::on_connect (23): Client connected
513d5ca73cfd443d8ff3e0edb3e04724: Sending packet MESSAGE data 0
513d5ca73cfd443d8ff3e0edb3e04724: Received request to upgrade to websocket
513d5ca73cfd443d8ff3e0edb3e04724: Upgrade to websocket successful
513d5ca73cfd443d8ff3e0edb3e04724: Received packet PING data None
513d5ca73cfd443d8ff3e0edb3e04724: Sending packet PONG data None
513d5ca73cfd443d8ff3e0edb3e04724: Received packet MESSAGE data 1/,
DEBUG 2019-04-13 20:31:42,597 MainThread controllers.py::on_disconnect (27): Client disconnected
513d5ca73cfd443d8ff3e0edb3e04724: Received packet MESSAGE data 0/,
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/engineio/server.py", line 505, in _trigger_event
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.5/dist-packages/socketio/server.py", line 586, in _handle_eio_message
    self._handle_connect(sid, pkt.namespace)
  File "/usr/local/lib/python3.5/dist-packages/socketio/server.py", line 489, in _handle_connect
    self.environ[sid]) is False:
KeyError: '513d5ca73cfd443d8ff3e0edb3e04724'
```

This doesn't happen when using the [socket.io-client-java](https://github.com/socketio/socket.io-client-java) connecting/disconnecting to the same server.

My question is, should the [socket.io-client-swift](https://github.com/socketio/socket.io-client-swift) library be sending the same `sid` on a new connection on the same socket, or is this a bug in Flask-SocketIO related to #574 ?

**Comment by miguelgrinberg** [comment]
It's odd that the client is attempting to connect on a socket that was previously disconnected. I can avoid the crash, but the connection will still fail. I'm not sure what they expect to achieve in this way, I need to try this against a Node server to see if the behavior is different.

**Comment by ffleandro** [comment]
Well, I manually call `disconnect` when leaving the app and `connect` when coming back again to foreground.

I solved by setting the property `forceNew` on the client library, when reconnecting.

However, I don't think this is the correct behaviour for the server, it shouldn't crash on connect if `sid` is not valid, it should fail gracefully and create a new `sid`.

**Comment by miguelgrinberg** [comment]
@ffleandro Interesting, there must be an undocumented option in the node server that allows the client to resend an already used session id. I wasn't aware this was possible.

**Comment by miguelgrinberg** [comment]
@ffleandro would you have a moment to test the master branch in this repository against your iOS client? Obviously you will need to remove the `forceNew` option that you are using as a workaround. I believe I have fixed this problem now. The disconnects issued by iOS should not cause a full disconnect, so when a reconnection is attempted I think it will work just fine.

**Comment by miguelgrinberg** [comment]
Release in python-socketio 4.0.2.
