### ISSUE TITLE
How many namespaces?

### ISSUE THREAD

**Issue by valentin-ballester** [miguelgrinberg/Flask-SocketIO#947]
In my app i have a live table with 2 parts:

the live table and also the system overload variable. Lets say i want to update the live table using the user room and the system overload making a broadcast to all users in namespace. Is it bad to have a namespace for every client ? lets say i plan to scale up to 200 300 clients. 

Also, given i want a user admin with his table to get all user tables updates and append in one table, can i get all the emits from the room of a single name space ? or would i have to join to every user room to that admin ?

**Comment by miguelgrinberg** [comment]
Namespaces are not built for this purpose. Use custom rooms instead.

Each client is initialized with a room of its own. You can create additional rooms as needed, and assigned clients to them. A room can have as many participants as you need, so for admins you can have them added to all the client rooms.

**Comment by valentin-ballester** [comment]
Yes i will do that, now if i want to have 3 namespaces:

one where i have all the clients room and another where i have all the user rooms, is that a correct design ? my main issue is to connect to the socket in the client namespace and to the socket of the user namespace so a user recieves his new orders and also client updates as system overload for example.

**Comment by miguelgrinberg** [comment]
Why do you need two namespaces? Isn't it enough to keep two sets of rooms?

**Comment by valentin-ballester** [comment]
I will just create a room for every user, my app is very specific with the data i need to send at any moment. i have 2 doubts:

1) i have a order table and a order page. the order table doesn't need all the data that the order page does, the first one just need to know when a order close and the second one needs data about the user that takes the order and so on...
    if i just use user rooms i have to validate on every particular order page that the data update belongs to the order of that page (a simple if validator solves this problem but i want to be sure before doing this is the correct way). should i split into user room and order room? seems to me that it isn't practical because i split essential data too much and if i ever have to access that critical data from the table or from other user page i would have to joining to the specific order room and also i would have to make multiple emits to abort an order  (one that close the order on the table and another that disable the abort button on the order page) so maybe just use user rooms for the moment and just dont listen to the specific order events in the table page, how would you personally solve this type of problems ? in general terms. 

2) some buttons in my app that are shown in pages where i have sockets have an href to a url that performs a action such as abort an order, is it better to use the socket connection to do certain actions like aborting better than using a href ?

**Comment by miguelgrinberg** [comment]
1. Sorry but I have trouble following the logic that you are using. I'm not sure you understand what a room is. You seem to want to separate classes of communications in rooms, but that doesn't really make much sense. A room is just a place where clients can be grouped, so that you can send an event to all of them. That's really all there is to it. If you are addressing individual users, then you don't need to create any rooms, since each client gets a room assign when they connect. Also, any data sent by the client needs to be validated before it is used.

2. If you use a normal button then the page in your browser will change, and that will break your Socket.IO connection. In most cases Socket.IO applications are single-page apps to prevent the connection from being interrupted on a page change.

**Comment by valentin-ballester** [comment]
Ok, yeah that button is the abort and i dont want to keep the connection open when the user aborts because i just reload the order page without all the socket things because the order is closed so i don't need to receive any data after that. About the first response, i talk about database users that is what i mean by targeting specific users. Shouldn't i have a room for every user on my db ? because otherwise i would have to keep track of every individual sid of every user in my db. i understand my error of trying to do more that sockets are mean to but i think a room per user solves me a lot of problems.

**Comment by miguelgrinberg** [comment]
I don't really see the problem in tracking session ids, but in any case if you want to create a new room for each user you can do that. I really don't understand what you are asking me, it seems you already know what you want to do.
