### ISSUE TITLE
Under uwsgi getting continual connect and disconnect events

### ISSUE THREAD

**Issue by dtamez** [miguelgrinberg/Flask-SocketIO#948]
High Level Configuration:
using gevent,  and monkey patching
socketio object created using redis,
using nginx as reverse proxy,

Observed Behavior:
starting without uwsgi (socketio.run(app,..)) - clients connect and there is no disconnect event until they close the browser or mobile device
starting with uwsgi (uwsgi --http :5000 --gevent 1000 --http-websockets --master --wsgi-file run.py --callable application --processes 4) - clients continually connect and disconnect

Question:  
Do I need to make changes to the nginx configuration for load balancing even though there is only one port (5000) on which uwsgi is listening?  Is there some other configuration I've missed?

If I use gunicorn instead of uwsgi, I understand I need to start multiple gunicorn processes each with one worker at different IP addresses and then configure nginx to see each of those as an upstream.  Is the same thing somehow necessary for uwsgi?

**Comment by miguelgrinberg** [comment]
You can't use multiple processes, change to `--processes 1`.

**Comment by dtamez** [comment]
Thanks Miguel!  If both are limited to 1 process/worker I think I'll go with gunicorn instead.

**Comment by miguelgrinberg** [comment]
you can use multiple processes, that's not a problem, the issue is that the load balancer needs to support sticky sessions. For both gunicorn and uwsgi sticky sessions are not supported, so the workaround is to start a bunch of single-process servers and put them behind nginx or similar which can do sticky sessions.

**Comment by dtamez** [comment]
yes, that's what I'm going to do.  I thought I could skip listing every server/IP in nginx by using uwsgi but since it's the same either way I'll just use gunicorn.  I'll start several gunicorn processes each at their own IP. Then (as per your docs) list each server as an upstream (with ip_hash) in nginx and point to them in location section with proxy_pass.

**Comment by miguelgrinberg** [comment]
Yes, unfortunately this is the best/only option at this time.
