### ISSUE TITLE
AttributeError: 'SocketIOTestClient' object has no attribute 'is_connected'

### ISSUE THREAD

**Issue by NathanWailes** [miguelgrinberg/Flask-SocketIO#950]
Hi Miguel,

I'm trying to create some tests for a Flask-SocketIO websocket server and I'm hitting the error in the title of this issue while trying to do `self.assertTrue(client.is_connected())`.

Here's the test file:
```
import unittest

from src.playbackWS import socketio, app


class TestWebsocketServer(unittest.TestCase):
    def test_connect(self):
        client = socketio.test_client(app)
        self.assertTrue(client.is_connected())
        received = client.get_received()
        client.disconnect()
        self.assertFalse(client.is_connected())
```

Here's the beginning of the server file:
```
import eventlet
eventlet.monkey_patch()

import json

from src import logger

from threading import Lock
from flask import Flask, render_template, session, request
from flask_socketio import SocketIO, emit, join_room, leave_room, \
    close_room, rooms, disconnect

async_mode = None

app = Flask(__name__, static_folder='../../public', static_url_path='/public', template_folder='../../public/')
# app.debug = True
app.config['SECRET_KEY'] = 'XXXXXXXXXXXXXXXXXXXXXX'
socketio = SocketIO(app, async_mode=async_mode)
thread = None
thread_lock = Lock()

(...)
```

The full stack trace:
```
Error
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/vagrant/src/playbackWS/test/test_websocket_server.py", line 12, in test_connect
    self.assertTrue(client.is_connected())
AttributeError: 'SocketIOTestClient' object has no attribute 'is_connected'
```

**Comment by miguelgrinberg** [comment]
There is no `is_connected()` method in this package, where did you see that this was something you can use?

**Comment by NathanWailes** [comment]
https://github.com/miguelgrinberg/Flask-SocketIO/blob/master/test_socketio.py

**Comment by miguelgrinberg** [comment]
@NathanWailes oh, okay! So this is functionality that exists in the test client, I would not have expected that you want to test how the test client works in your own tests!

In any case, I think one possible reason for your error is that you have an older version of Flask-SocketIO that does not have this method in the test client. It is fairly recent.

**Comment by NathanWailes** [comment]
>I would not have expected that you want to test how the test client works in your own tests!

Hmm, maybe I'm confused then.  I'm just trying to test my websocket server, and I thought that the way to do that would be to create a mock client.  I am testing code that I did not write, so I'm not as familiar with how Flask-SocketIO works as the person who originally wrote the code (who is no longer available for me to ask questions of).

Where can I see an example of testing a Flask-SocketIO websocket server?

**Comment by miguelgrinberg** [comment]
> Where can I see an example of testing a Flask-SocketIO websocket server?

Some of the other tests in that file are actually testing an example application that is defined near the top of that same module and those are good examples. Testing that `is_connected()` does what's expected is not, in my opinion something you should do on your side, since this is functionality that is part of the test client itself.

**Comment by NathanWailes** [comment]
Ah, I understand now!  Thank you so much for your generosity with your time!
