### ISSUE TITLE
How to use block function with set_background_task?

### ISSUE THREAD

**Issue by StartAt24** [miguelgrinberg/Flask-SocketIO#951]
Hi, I‘m using flask-socketio with zmq.
Here is my code:

```python
def recv_thread():
	print('thread starting')
	while True:				
	        data = zmq.recv()
		socketio.emit("frame", data)		


if __name__ == '__main__':
	init_zmq()
	with thread_lock:
		if thread is None:
			thread = socketio.start_background_task(target=recv_thread)
	socketio.run(app, host='0.0.0.0', port=5000)

```

The zmq.recv() is a block function， and it block the whole socketio.
How can i fix this problem?
Thanks a lot!

**Comment by miguelgrinberg** [comment]
If you are using eventlet or gevent, you need to monkey patch the standard library so that those socket functions are replaced with non-blocking versions. For eventlet, add this at the top of your main script (above other imports):

```python
import eventlet
eventlet.monkey_patch()
```

For gevent:

```python
from gevent import monkey
monkey.patch_all()
```

**Comment by StartAt24** [comment]
> If you are using eventlet or gevent, you need to monkey patch the standard library so that those socket functions are replaced with non-blocking versions. For eventlet, add this at the top of your main script (above other imports):
> 
> ```python
> import eventlet
> eventlet.monkey_patch()
> ```
> 
> For gevent:
> 
> ```python
> from gevent import monkey
> monkey.patch_all()
> ```

It doesn't work.
By  "monkey patch" , Do you mean change zmq.recv() to Non-blocking or something else ?
The zmq.recv() is always a block function. I don't want to change it to Non-blocking.

**Comment by miguelgrinberg** [comment]
You need it to be non-blocking. That does not mean that the function will return, in this context "non-blocking" means that the function will still block, but while it is blocked waiting for the socket other tasks in the system will run.

It looks like eventlet comes with explicit support for zmq: https://eventlet.net/doc/zeromq.html, so you can follow the documentation to set it up appropriately.

**Comment by StartAt24** [comment]
> You need it to be non-blocking. That does not mean that the function will return, in this context "non-blocking" means that the function will still block, but while it is blocked waiting for the socket other tasks in the system will run.
> 
> It looks like eventlet comes with explicit support for zmq: https://eventlet.net/doc/zeromq.html, so you can follow the documentation to set it up appropriately.

Do you mean change pyzmq to eventlet.green.zmq? 
Then use 
`
import eventlet
eventlet.monkey_patch()
`

**Comment by miguelgrinberg** [comment]
I don't use zeromq myself, so I can't give you specific advice. I assume if you import `eventlet.green.zmq` you do not need to monkey patch, this module is already written to be compatible with eventlet. You would need to also monkey patch if you are doing other blocking things outside of zeromq.

If you want to see some example code using this module, have a look at https://github.com/miguelgrinberg/python-socketio/blob/master/socketio/zmq_manager.py. (note that while this code is in a repository of mine, it was contributed by someone else, I'm not the original author).

**Comment by StartAt24** [comment]
> I don't use zeromq myself, so I can't give you specific advice. I assume if you import `eventlet.green.zmq` you do not need to monkey patch, this module is already written to be compatible with eventlet. You would need to also monkey patch if you are doing other blocking things outside of zeromq.
> 
> If you want to see some example code using this module, have a look at https://github.com/miguelgrinberg/python-socketio/blob/master/socketio/zmq_manager.py. (note that while this code is in a repository of mine, it was contributed by someone else, I'm not the original author).

Thanks a lot! 
It solved my problem!
