### ISSUE TITLE
Can I customize the timeout interval in SocketIO's heartbeat mechanism?

### ISSUE THREAD

**Issue by tianshanghong** [miguelgrinberg/Flask-SocketIO#952]
I see the official documentation describe Socket.IO has a [heartbeat mechanism implementation](https://socket.io/docs/#Disconnection-detection). Also, there is an approach to modifying the timeout interval for this heartbeat mechanism ([link](https://stackoverflow.com/questions/12815231/controlling-the-heartbeat-timeout-from-the-client-in-socket-io)). However, I checked the documentation of Flask-SocketIO but find nothing about this interval controlling. Thus, I wonder is it possible to control this interval in the server-end using Flask-SocketIO? If yes, how can I do that?
Thanks very much.

**Comment by miguelgrinberg** [comment]
Yes, there are two parameters that you can configure in the class constructor: https://flask-socketio.readthedocs.io/en/latest/#flask_socketio.SocketIO. Look for `ping_interval` and `ping_timeout`.

**Comment by tianshanghong** [comment]
Thanks very much! That's very helpful.
