### ISSUE TITLE
Background task not emitting to room

### ISSUE THREAD

**Issue by JoshuaFry** [miguelgrinberg/Flask-SocketIO#954]
In my code all flask socket functions that are decorated with `@socket.on` work just fine. But when I try to emit from a background process I get no response at all. I am currently building an app that streams JSON data changes from Firebase to the server. This function works just fine too, I even got the stream to send data back to the client when I initialized it through `socketio.start_background_task`.  The issue with this though is I can't stop the stream if I initialize it this way, and the amount of emits seems limited. Here is what I've been trying to get to work for a few days now.

```
# Stream json changes from Firebase Real-Time DB path
def begin_data_stream(path):
    global my_stream
    my_stream = db.child(path).stream(stream_put)
    # With the below background call I was limited in the amount emit calls
    # that would make it through in the stream_put function. The data can
    # change multiple times per second
    # socketio.start_background_task(db.child(path).stream, stream_put)
    return


def end_data_stream():
    my_stream.close()
    return
```
The below function worked just fine when I was testing on my local machine server, at that time I just called `socketio.emit` from within `stream_put(message)` and I succesful received the data via js. Then I sent it up to heroku and now I'm in an endless debugging state. 
```
def stream_put(message):
    with app.app_context():
        print(message)
        path = str(message["path"][1:]).split('/')
        if path[0] == 'seats':
            if path[2] == 'name':
                data = {'seat': path[1], 'name': message['data']}
                socketio.start_background_task(stream_seat_changed, data)
                # stream_seat_changed(data)
            elif path[2] == 'bet':
                data = {'seat': path[1], 'bet': message['data']}
                socketio.start_background_task(stream_bet_update, data)
                # stream_bet_update(data)
            elif path[2] == 'balance':
                data = {'seat': path[1], 'balance': message['data']}
                socketio.start_background_task(stream_balance_update, data)
                # stream_balance_update(data)
            elif path[2] == 'hand':
                data = {'seat': path[1], 'hand': message['data']}
                socketio.start_background_task(stream_hand_update, data)
                # stream_hand_update(data)
        if path[0] == 'state':
            socketio.start_background_task(stream_state_changed, message['data'])
            # stream_state_changed(message['data'])
        if path[0] == 'dealer':
            data = {'seat': 7, 'hand': message['data']}
            socketio.start_background_task(stream_hand_update, data)
            #  stream_hand_update(data)
```

I've tried making the emit call in the stream_put function, I've tried not using `with app.app_contex():` 

```
def stream_seat_changed(data):
    with app.app_context():
        table_id = get_user_data()['tableId']
        socketio.emit('seat_changed', data,  room=table_id, json=True)

def stream_bet_update(data):
    with app.app_context():
        table_id = get_user_data()['tableId']
        socketio.emit('bet_update', data,  room=table_id, json=True)

def stream_balance_update(data):
    with app.app_context():
        table_id = get_user_data()['tableId']
        socketio.emit('balance_update', data,  room=table_id, json=True)

def stream_hand_update(data):
    with app.app_context():
        table_id = get_user_data()['tableId']
        socketio.emit('hand_update', data,  room=table_id, json=True)

def stream_state_changed(data):
    with app.app_context():
        table_id = get_user_data()['tableId']
        socketio.emit('state_changed', data,  room=table_id)
```

I tried monkey patching as well but this prevented a connection to my database thus users could not sign in. Please help.

**Comment by miguelgrinberg** [comment]
If you can't use monkey patching the only other viable option is to use a database package that is designed to work with eventlet/gevent natively. I'm doubtful such package exists for Firebase, so unfortunately if you can't drop firebase then you'll have to drop eventlet/gevent.

**Comment by JoshuaFry** [comment]
To be fair I just used 'eventlet.monkey_patch()' at the top of my program without looking up what this would do. After reading some of the docs on eventlet.green it seems like I have more to try before opting for another database. Any suggestions or links on implementing evenlet.green would be helpful. Thanks.

**Comment by miguelgrinberg** [comment]
I don't think there is a lot to say about it. The monkey patching replaces the functions that are incompatible with eventlet with versions that are compatible. It's better to use packages that support greenlets natively, but for the vast majority of applications monkey patching is the only way, since there aren't a lot of packages written specifically for greenlets.
