### ISSUE TITLE
Cannot modify session on a Flask Socketio event

### ISSUE THREAD

**Issue by NotChampion** [miguelgrinberg/Flask-SocketIO#956]
I tried modifying a Flask session in a Flask Socketio event. It doesn't work though.

```py
@socketio.on("signup req")
def signup_req(json):
    print(f"Response! {json}")
    socketio.emit("signup res", "RECEIVED!")
    session["user"] = {"name": json["name"]}
```

**Comment by miguelgrinberg** [comment]
This is a limitation related to how Flask sessions are implemented using cookies. See the [documentation](https://flask-socketio.readthedocs.io/en/latest/#access-to-flask-s-context-globals) and this [blog post](https://blog.miguelgrinberg.com/post/flask-socketio-and-the-user-session).
