### ISSUE TITLE
SocketIO Flask transmits messages only occasionally

### ISSUE THREAD

**Issue by eranartzi** [miguelgrinberg/Flask-SocketIO#959]
I'm running a SocketIO-Flask web server locally and testing it with a short JS SocketIO code that I am also running locally. I have a rather strange problem where my client is getting the responses from the server only about 20% of the time. I'm running the same script, without changing anything, so I really have no idea why that is happening.

This is the code on the server side:

```
from flask import Flask, request, jsonify
from flask_cors import CORS, cross_origin
from flask_socketio import SocketIO


app = Flask(__name__)
sio = SocketIO(app, async_mode="threading")
// sio = SocketIO(app)
cors = CORS(app)


@sio.on('message', namespace='/get_read')
def handle_read(msg):
    print(f'received {msg} at /get_read')
    # Retrieve information from DB
    sio.send('received msg')


@sio.on('message')
def handle_msg(msg):
    print(f'received message without namespace')
    sio.send('global message received')
```

This is the client side:

```
io = require('socket.io-client')

reads = io('http://127.0.0.1:5000/get_read')

reads.on('connect', () => {
    console.log('connected to server')
})

reads.on('message', (data) => {
    console.log(data)
})


reads.send({'sender' : 'eranartzi@gmail.com'})
```

I get the same behavior trying to ping both the endpoint with the ```/get_read``` namespace and the second endpoint that only send back ```global message received```. I do get the calls on the server side, and I do get the  ```connect``` event firing every time, just not always getting the messages back from the server on the client side.

I also included all the libraries that I think might be relevant in the import.

Would really appreciate the help

Thank you

**Comment by miguelgrinberg** [comment]
What kind of client is this? Are you running in the browser or something else?

**Comment by eranartzi** [comment]
Right now I'm just running it as a script in Visual Studio Code with NPM. But eventually, the client will be in a Chrome Extension. What kind of issue can cause such erratic behavior?

**Comment by miguelgrinberg** [comment]
The event that uses a namespace should also respond on the namespace:

```python
@sio.on('message', namespace='/get_read')
def handle_read(msg):
    print(f'received {msg} at /get_read')
    # Retrieve information from DB
    sio.send('received msg', namespace='/get_read')
```

With that change I don't see any problem here.

**Comment by eranartzi** [comment]
Hi @miguelgrinberg.

It works perfectly now. Thank you!

Do you know why, when I did not specify the namespace in the response I still got the message to go through sometimes? What's the logic driving that behavior?

Thank you

**Comment by miguelgrinberg** [comment]
@eranartzi I did not see that message getting delivered at all, so I don't know. My guess is that you are mistaken. Maybe you were using the `send()` function instead of `sio.send()`. The `send()` function is context aware, so it will respond on the same namespace. You are using the lower level non-Flask specific `sio.send()` which does not know anything about the Flask context.
