### ISSUE TITLE
How to list all rooms available? Is there a way to identify the user that disconnected?

### ISSUE THREAD

**Issue by titogarrido** [miguelgrinberg/Flask-SocketIO#96]
Hey folks 2 dummy questions...

Is there anyway to list all rooms available?

Is there a way to identify the user that disconnected?

**Comment by miguelgrinberg** [comment]
> Is there anyway to list all rooms available?
There is no high-level API to obtain the room list, but you can find it accessing the internal variables of the extension. Use `socketio.rooms[namespace].keys()` to get the rooms for a given namespace.

When a user disconnects you get the `'disconnect'` event. You can create an event for it.

**Comment by titogarrido** [comment]
Thanks!

**Comment by ShermanMorrison** [comment]
What causes the 'disconnect' event, exactly? Is there a timeout that is very short? I have found that I get disconnect for clients while they are still on my page- and only a few seconds after they originally navigate to my page.

**Comment by miguelgrinberg** [comment]
@ShermanMorrison the client and server exchange heart beat messages while the connection is active. When the server stops receiving these messages it will declare the client disconnected. The client can also disconnect explicitly.

What you are experiencing though is probably the first case. The client has a retry logic so whenever the connection is dropped it'll try to reconnect. I'm not sure why this is happen, you may want to look at the network tab in your browser's console to see what's happening at the request/response level.

**Comment by anuprulez** [comment]
In this code ` socketio.rooms[namespace].keys() `, socketio is which object? 
When I am writing
```
socketio = flask.current_app.extensions['socketio']
print(socketio.server.rooms['/chat'].keys())
```
in app.py, it is not working

**Comment by miguelgrinberg** [comment]
Note that `socketio.server` and `socketio.server.rooms` are not variables you are supposed to access from the outside. They are internal variables of the server, and they can change at any time without notice. Not a good idea to do what you are doing. Besides, that will not give you the complete list of rooms when multiple servers are used.

**Comment by anuprulez** [comment]
Thanks a lot!
Actually in my application I need to show the list of available chat rooms to any user who has just joined.
So is there any way to get the list of rooms through Python library?

**Comment by miguelgrinberg** [comment]
@anuprulez your application knows what rooms it creates, so you should be able to come up with that list on your own, maybe from your database. As I said above, considering that Socket.IO is a distributed server, it is not possible to have the complete list of rooms that exist, since rooms may not exist in all servers.

**Comment by anuprulez** [comment]
@miguelgrinberg Thanks a lot for your answer. We will find some way :)

**Comment by MichealReed** [comment]
@miguelgrinberg We have intentionally created a situation where the client hits a timeout, but the server does not seem to be triggering the disconnect event. Do you know what could be causing this?

**Comment by miguelgrinberg** [comment]
@MichealReed can you be more specific? What timeout is the client hitting? How do you know it hit it?

**Comment by MichealReed** [comment]
@miguelgrinberg Two scenarios, the device loses power, or the device loses internet connection making it unable to facilitate the heartbeat to/from the server. The server never actually triggers the disconnect event from a lack of heartbeat from the unavailable client.

**Comment by miguelgrinberg** [comment]
@MichealReed if your client is connected via long-polling, then the heartbeat is the only thing that the server can use to detect the client is gone. A WebSocket connection, on the other side, is detected the moment the client drops. Any chance you are using long-polling instead of WebSocket?

**Comment by MichealReed** [comment]
@miguelgrinberg Seems we are using http longpolling at the moment and that makes total sense. Thanks a ton for the quick reply!

**Comment by kamelaouad** [comment]
Hello All,
How can I find issue to problem like " error: [Errno 98] Address already in use " with flask socketIO app.
I didn't find SO_REUSE_ADDRESS ?
regards

**Comment by ardikabs** [comment]
@miguelgrinberg talking about rooms, if there is so many room created and not be used, is the server will automatically delete that or not ? thanks!

**Comment by miguelgrinberg** [comment]
@ardikabs yes, rooms are automatically deleted when the last person leaves.

**Comment by ardikabs** [comment]
@miguelgrinberg thanks for the quick reply !!

**Comment by acnebs** [comment]
@miguelgrinberg is there a way to fire a callback when that happens? I want to update my db when rooms are created / destroyed.

**Comment by miguelgrinberg** [comment]
@acnebs unfortunately there is no facility to notify the application when rooms are created or destroyed at this time. You can do this if you track the participants in each of your rooms in the application.

**Comment by acnebs** [comment]
@miguelgrinberg Thank you! As I plan to have multiple API servers behind a load-balancer anyway, I would've needed to persist such data outside of the application anyway. I'm already using Postgres, but obviously I'm thinking it makes more sense to use an in-memory db like Redis to store live connection details. Have you done this kind of thing before with `flask-socketio`? Do you think Redis would be a good pick, or do you have any other suggestions?

**Comment by miguelgrinberg** [comment]
@acnebs yes, I also use Redis for this type of short-lived data, so that is my recommendation as well. Postgres would work too, but to me it feels too heavy weight for storing temporary data that depends on clients coming and going.
