### ISSUE TITLE
Update docs to remove reference to `flask run`

### ISSUE THREAD

**Issue by willthames** [miguelgrinberg/Flask-SocketIO#960]
According to #894, `flask run` no longer works with this library.

However, the docs still say

> The command line interface based on click introduced in Flask 0.11 is also supported. This extension provides a new version of the flask run command that is appropriate for starting the Socket.IO server. Example usage:

```
$ FLASK_APP=my_app.py flask run
```

**Comment by miguelgrinberg** [comment]
The `flask run` command is still available and functional. The difference is that it cannot be used to start a production server anymore, so it is now fully aligned with Flask on this respect. So yes, the docs are a bit misleading, but not exactly like you are describing, I think it should be noted clearly that `flask run` runs the development web server.

**Comment by willthames** [comment]
It's not just that, but that you don't get any websocket features at all with `flask run` (at least that was my understanding from the message printed out when I started my app). I'd be happy with the development server

**Comment by miguelgrinberg** [comment]
Yes, that is correct. The development server from Flask does not support WebSocket at this time. This is already mentioned in the docs elsewhere, but should also be noted where `flask run` is discussed, agreed.

**Comment by willthames** [comment]
Thanks @miguelgrinberg - I just found it a little confusing.

BTW I've reused your example for my docker-debug application, it's super helpful
https://github.com/willthames/docker-debug#websockets

Yours was one of the few examples I found with an open source license, I've reused the same license and tried to give you appropriate credit in the docs and source code
