### ISSUE TITLE
getting timely - 400 bad requests with transport=polling

### ISSUE THREAD

**Issue by neostarsky97** [miguelgrinberg/Flask-SocketIO#963]
I've been trying to solve this issue for a long time but I can't seem to get my head around it. Basically, I am making a log viewer application where the application is tailing a log file and any updates are sent to the web page via flask-socketio. The problem is it works but it has these timely 400 bad requests. Here is the error: 
```
socket.io.min.js:1 GET http://127.0.0.1:5000/socket.io/?EIO=3&transport=polling&t=1556616838639-3&sid=52822d37bed54bdf9b09b78cca934f0f 400 (BAD REQUEST)
socket.io.min.js:1 POST http://127.0.0.1:5000/socket.io/?EIO=3&transport=polling&t=1556616838650-4&sid=52822d37bed54bdf9b09b78cca934f0f 400 (BAD REQUEST)
```

I am using gevent as the coroutine and gunicorn as the WSGI server. Here is how I am running the application: 

`gunicorn flasklogreader:app --worker-class gevent --bind 0.0.0.0:5000
`
Here is the relevant part of the code that interacts with socket io:

Python: 
```
app = Flask(__name__)
socketio = SocketIO(app)

@socketio.on('stream')
def stream_tail():
	import tailer
	base_file = request.cookies.get('file')
	print(os.path.join(BASE_DIR,str(base_file)))
	log_file=os.path.join(BASE_DIR,str(base_file))
	f = open(log_file, 'r')
	for line in tailer.follow(f):
		emit('logstream', json.loads(line))
```

JavaScript:
```
var socket = io.connect('http://' + document.domain + ':' + location.port);
                    socket.on('connect', function() {
                        socket.emit('stream');
                    });

socket.on('logstream', function(data) {
                        //do operations with data 
                    });
```

Any help is appreciated. Thank you.

**Comment by neostarsky97** [comment]
Also as an added comment, the browser doesn't switch to websocket transport.

**Comment by miguelgrinberg** [comment]
How many workers are you running on your gunicorn? Add a `-w 1` to ensure you are running only one. That is the only configuration that is supported, see the docs for details and for ways to overcome this limitation in gunicorn.

**Comment by neostarsky97** [comment]
Hey, thankyou for the quick reply.
I did try adding one worker but the problem still persists.
`gunicorn --workers=1 flasklogreader:app --worker-class gevent --bind 0.0.0.0:5000`

**Comment by miguelgrinberg** [comment]
Are you doing any type of load balancing across multiple containers? The 400 errors are seen when you run multiple servers with a load balancer that does not have sticky session support.

**Comment by neostarsky97** [comment]
I'm not explicitly doing any load balancing but I'm not aware if gunicorn does that. Is there anyway to find that out? How do I ensure for sticky sessions?

**Comment by miguelgrinberg** [comment]
How do you start your Docker container? If you are starting one container then there shouldn't be any load balancing, but the errors that you get in the log suggest that you may have more than one.

You can try running the application without Docker to rule out any weird problems introduced by the container. Does that work better?

**Comment by neostarsky97** [comment]
I was running a docker-compose with this web application and redis which I was just using for testing, I removed it and checked, it's still the same.
However, I ran it without docker and was greeted by a new error. 

On the browser: 
`socket.io.min.js:2 WebSocket connection to 'ws://127.0.0.1:5000/socket.io/?EIO=3&transport=websocket&sid=316d31a08e9f4fbcb6c424dc37b8a22e' failed: Error during WebSocket handshake: Unexpected response code: 500`

In the python output:
```
316d31a08e9f4fbcb6c424dc37b8a22e: Sending packet MESSAGE data 0
316d31a08e9f4fbcb6c424dc37b8a22e: Received request to upgrade to websocket
[2019-04-30 11:42:12 +0000] [10081] [ERROR] Error handling request /socket.io/?E                      IO=3&transport=websocket&sid=316d31a08e9f4fbcb6c424dc37b8a22e
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/gunicorn/workers/base_async.py",                       line 56, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/local/lib/python3.4/dist-packages/gunicorn/workers/ggevent.py", lin                      e 160, in handle_request
    addr)
  File "/usr/local/lib/python3.4/dist-packages/gunicorn/workers/base_async.py",                       line 107, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 2309, in __ca                      ll__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.4/dist-packages/flask_socketio/__init__.py", line                       44, in __call__
    start_response)
  File "/usr/local/lib/python3.4/dist-packages/engineio/middleware.py", line 59,                       in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/usr/local/lib/python3.4/dist-packages/socketio/server.py", line 428, in                       handle_request
    return self.eio.handle_request(environ, start_response)
  File "/usr/local/lib/python3.4/dist-packages/engineio/server.py", line 340, in                       handle_request
    environ, start_response)
  File "/usr/local/lib/python3.4/dist-packages/engineio/socket.py", line 106, in                       handle_get_request
    start_response)
  File "/usr/local/lib/python3.4/dist-packages/engineio/socket.py", line 146, in                       _upgrade_websocket
    return ws(environ, start_response)
  File "/usr/local/lib/python3.4/dist-packages/engineio/async_drivers/gevent.py"                      , line 35, in __call__
    raise RuntimeError('You need to use the gevent-websocket server. '
RuntimeError: You need to use the gevent-websocket server. See the Deployment se                      ction of the documentation for more information.
316d31a08e9f4fbcb6c424dc37b8a22e: Received packet MESSAGE data 2["stream"]

```

**Comment by miguelgrinberg** [comment]
Check the documentation, you need to use a different worker type of you
intend to use websocket with gevent. The docs have the gunicorn command
that you need to use.

**Comment by neostarsky97** [comment]
I changed to the gevent-websocket worker type. 

`gunicorn --workers=1 flasklogreader:app --worker-class geventwebsocket.gunicorn.workers.GeventWebSocketWorker --bind 0.0.0.0:5000
`
The request for the upgrade to websocket takes place without switching back to polling, but now I do not receive any updates on my page. These are the errors in my console.

```
db6f4d9b15ae4b3e91c2a4a43e328d63: Sending packet MESSAGE data 0
db6f4d9b15ae4b3e91c2a4a43e328d63: Received request to upgrade to websocket
db6f4d9b15ae4b3e91c2a4a43e328d63: Received packet MESSAGE data 2["stream"]
/home/phoenix-log-monitor/log_files/phoenix-server-log.log
db6f4d9b15ae4b3e91c2a4a43e328d63: Client is gone, closing socket
db6f4d9b15ae4b3e91c2a4a43e328d63: Client is gone, closing socket
```

**Comment by neostarsky97** [comment]
Thread bump

**Comment by miguelgrinberg** [comment]
I don't have sufficient information to help you unfortunately. The "client is gone" message indicates that the client isn't sending the PING packets at the correct time, or else that the server is too busy or blocked and is unable to process these PINGs in a timely manner. So basically my guess is that some other part of your application is affecting this.

**Comment by neostarsky97** [comment]
Okay, thanks for the help Miguel. I'll post back if I find a solution for this.
