### ISSUE TITLE
Question: Does get_participants work differently when running multiple servers?

### ISSUE THREAD

**Issue by dtamez** [miguelgrinberg/Flask-SocketIO#965]
The following call returns the correct number of people in the room when running only one instance:
socketio.server.manager.get_participants('/', room)

However, when running multiple instances and people are connected to different instances it returns too few participants.
Running multiple instances via gunicorn as per documentation as follows:
gunicorn -b 0.0.0.0:5000 --worker-class eventlet -w 1 run:app
gunicorn -b 0.0.0.0:5001 --worker-class eventlet -w 1 run:app
etc.
and in nginx:
upstream api_nodes {
    ip_hash;
    server api:5000;
    server api2:5001;
    server api3:5002;
    server api4:5003;
}
and later...
    location /socket.io {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass http://api_nodes/socket.io;
    }

socketio is started as follows:
        socketio.init_app(
            app,
            async_mode='eventlet',
            message_queue=app.config['BROKER_URL'],
        )

Is the above method (get_participants) known to work when using more than one server instance?

**Comment by dtamez** [comment]
Found this in the underlying socketio library:
class BaseManager(object):
    """Manage client connections.

    This class keeps track of all the clients and the rooms they are in, to
    support the broadcasting of messages. The data used by this class is
    stored in a memory structure, making it appropriate only for single process
    services. More sophisticated storage backends can be implemented by
    subclasses.
    """
    def __init__(self):
        self.server = None
        self.rooms = {}
        self.callbacks = {}
        self.pending_disconnect = {}

    def set_server(self, server):
        self.server = server

    def initialize(self):
        """Invoked before the first request is received. Subclasses can add
        their initialization code here.
        """
        pass

    def get_namespaces(self):
        """Return an iterable with the active namespace names."""
        return six.iterkeys(self.rooms)

    def get_participants(self, namespace, room):
        """Return an iterable with the active participants in a room."""
        for sid, active in six.iteritems(self.rooms[namespace][room].copy()):
            yield sid


Based on the above it looks like rooms and participants are stored not in the common redis server but directly by each python process.  So each process would have no knowledge of participants added in another process.  How can this possibly work?

**Comment by miguelgrinberg** [comment]
This is by design. This package does not keep track of a complete list of users and there are no functions that provide any lists. The `get_participants()` function that you found in the code is used internally as a helper to broadcast messages out to clients.

The application can do user tracking much better, since presumably it has access to a database, something this package does not have. You can claim redis can be used, but redis (or rabbit and a few others) are used as a message queue, not as storage.

**Comment by dtamez** [comment]
In that case I'll redo that section of code that was relying on get_participants.  Thanks so much for the response!
