### ISSUE TITLE
Use gunicorn or not?

### ISSUE THREAD

**Issue by tb2johm** [miguelgrinberg/Flask-SocketIO#968]
Hi!

We run a web that serves both Flask pages and a websocket. Today the setup looks like this:
_nginx > Flask-SocketIO (with eventlet, monkeypatched) > Flask_
Now we have read on several places that we shouldn't use Flask development server for production, so now we set out to add Gunicorn to the stack. However, upon reading up a bit more in the SocketIO docs I suddenly get a bit confused. It says that if we already have Eventlet installed (which we most definitely have), then we already use the a "production ready server" (_Deployment > Embedded server_).

So now the question is; do we actually gain anything by adding Gunicorn? At least it seems like the SocketIO is served by a production ready server. Does that include all traffic to that same Flask app?

**Comment by miguelgrinberg** [comment]
You are not using the Flask web server. You are using Eventlet's, which is actually production ready. This server is used both for the Socket.IO portion and for the flask portion.

Gunicorn is another option that some people prefer over Eventlet, but both are great choices for a production deployment. If you have no issues with Eventlet, then I see no reason to switch.

**Comment by tb2johm** [comment]
Ok!

Thanks alot!
