### ISSUE TITLE
[BUG] Serialisation is skipped in test client

### ISSUE THREAD

**Issue by mclate** [miguelgrinberg/Flask-SocketIO#969]
Looks like json serialisation is skipped when app is emitting to test client. Below is an example patch of how to test it. As you can see, we're emitting native python object and receiving it in test client. While tests will work, this behaviour will result in errors when app is transmitting data over the network. This behaviour remains if one explicitly set json handler: `SocketIO(app, json=custom_json)`

```patch
Index: test_socketio.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- test_socketio.py	(revision 1db923ae97a83ef913fb04941be79b06ad64a2f1)
+++ test_socketio.py	(date 1557327071000)
@@ -14,6 +14,8 @@
 socketio = SocketIO(app)
 disconnected = None
 
+failed_object = object()
+
 
 @socketio.on('connect')
 def on_connect():
@@ -224,6 +226,9 @@
         if not data.get('noackargs'):
             return data
 
+    def on_emit_failed_object(self, data):
+        emit('failed_object', failed_object)
+
     def on_other_custom_event(self, data):
         global request_event_data
         request_event_data = request.event
@@ -619,6 +624,15 @@
         with self.assertRaises(RuntimeError):
             client.emit('hello', {}, namespace='/ns')
 
+    @unittest.expectedFailure
+    def test_emit_object(self):
+        """ This test should fail due to jsonification error."""
+        client = socketio.test_client(app, namespace='/ns')
+        client.get_received('/ns')
+        client.emit('emit_failed_object', {'a': 'b'}, namespace='/ns')
+        received = client.get_received('/ns')
+        self.assertEqual(received[0]['args'][0], failed_object)
+
     def test_emit_class_based(self):
         client = socketio.test_client(app, namespace='/ns')
         client.get_received('/ns')
```

**Comment by miguelgrinberg** [comment]
The test client bypasses a lot of the lower level protocol logic including serialization and networking. Is this causing problems? Why would you pass an invalid object in your test? The point if these tests are to ensure your application works as expected, you seem to be testing the Socket.IO server itself here, not your application.

If you need an accurate server to test against, then you can always run the server for real and use a real client.

**Comment by mclate** [comment]
In this case i was testing serialisation of my response and noticed that it doesn't match the expectations. I'm pretty sure that it would happen very often that one would pass ORM objects directly into `emit` method, assuming that serialiser will do the rest. However, it now becomes quite tricky to test it properly.

**Comment by miguelgrinberg** [comment]
As I said, the client is not a real client, it is a mock client that just captures what you emit in your application so that you can make sure it is what you expect.

If you want to create end-to-end tests, you can always fire up a server and a client and make them talk for real.
