### ISSUE TITLE
websocket using single browser tab

### ISSUE THREAD

**Issue by AyliD** [miguelgrinberg/Flask-SocketIO#97]
Hi,

i'm newbie using websocket io.

one of my socketio event function may take few minutes (contains while function...), in that scenario when i try to perform new connection to socketio to perform similar operation on the same namespace (different message) it hangs till first function ends.

When i use to browsers tabs all works great!
Can you give me any suggestion?

import sys
import os
import threading
from flask.ext.socketio import SocketIO, emit
from flask import Flask
import gipc
import ansi2html
import json

# TODO - Should be covered by sysu environment.
if not '/opt/sysu/settings.d/' in sys.path:
    sys.path.append('/opt/sysu/settings.d/')
if not '/opt/sysu/libs/' in sys.path:
    sys.path.append('/opt/sysu/libs/')
if not '/opt/sysu/ui/' in sys.path:
    sys.path.append('/opt/sysu/ui/')
if not '/opt/sysu/saf/' in sys.path:
    sys.path.append('/opt/sysu/saf/')

import warnings
warnings.simplefilter("ignore")
os.environ["SYSULIB_SETTINGS_MODULE"] = "sysuwebui_config"

import settings
from contrib.decorators import load_persistency
import flows
from flows.tailf import Tailer
from utils.core import format_exception
import sysulib

#from flask.ext.cors import cross_origin

WEBSOCKETIO_LOCK_FILE = 'websocketio.lock'

# Mask main thread name to sysu
main_thread = threading.currentThread()
main_thread.setName(settings.WEBSOCKETIO_TITLE)

# Load modules and create logger
sysulib.gui.create_logger()

app = Flask(__name__)
sysulib.app = app
socketio = SocketIO(app)
sysulib.socketio = socketio

#@app.after_request
#@cross_origin(headers='Origin, X-Requested-With, Content-Type, Accept, Access-Control-Allow-Origin')
#def after(response):
#   return response

@socketio.on('leave_tail_active_flow')
def on_leave(message, namespace='/flow'):
    
    flow_name = '_undefine_'
    group = '_undefine_'
    try:
        flow_name = message['flowName']
        group = message['groupName']
    except:
        error = format_exception(sys.exc_info(), footer='Failed to leave tail flow: %s' % message)
        sysulib.gui.logger.error(error)
        emit('flow_error', {'error' : error, 'flowName' : flow_name, 'groupName' : group}, broadcast=True)

@socketio.on('tail_active_flow', namespace='/flow')
@load_persistency
def join_tail_active_flow(message):

    flow_name = '_undefine_'
    group = '_undefine_'
    try:
        sysulib.gui.logger.info('SOCKETgevent.SocketIO/flow: %s' % message) 
        flow_name = message['flowName']
        group = message['groupName']
        flow_obj = flows.flo.get_flow(group, flow_name)
        websocketio_lock_file = os.path.join(flow_obj.flow_active_dir, WEBSOCKETIO_LOCK_FILE)
        flow_obj.root.shared_lock()
        if not flow_obj.is_active():
            flow_obj.root.unlock_fh()
            emit('flow_not_active', {"flowName" : flow_name, "groupName" : group}, broadcast=True)
            return
        elif os.path.isfile(websocketio_lock_file):
            sysulib.gui.logger.info('Tailing flow %s::%s is already active, joining the tail' % (group, flow_name))    
            text = 'INFO: Flow %s::%s was activated on other session, Joining the real time logs.' % (group, flow_name)
            text_with_color = '\033[1;46m%s\033[1;m' % text
            log_to_html = ansi2html.Ansi2HTMLConverter()
            data = log_to_html.convert(text_with_color, full=False)
            emit('tailf', {"key" : 'Flow Log', 
                                   "data": data,
                                   "flowName" : flow_name,
                                   "groupName" : group,
                                   })
            flow_obj.root.unlock_fh()
            return
        sysulib.gui.logger.info('Spawning new flow %s::%s tailer' % (group, flow_name))
        open(websocketio_lock_file, 'w').close()
        log_to_html = ansi2html.Ansi2HTMLConverter()
        flow_obj.root.unlock_fh()
        with gipc.pipe() as (rpipe, wpipe):
            spawn = gipc.start_process(target=Tailer, args=(flow_obj, wpipe))
            while True:
                data = rpipe.get()
                if data is None:
                    break
                for elem in data:
                    if not elem in ('Shared Data', 'Result File'):
                        sysulib.gui.logger.debug('Ansi2Html convertor was invoked on %s element' % elem)
                        data[elem] = log_to_html.convert(data[elem], full=False)
                    else:
                        data[elem] = json.loads(data[elem])
                        sysulib.gui.logger.debug('Ansi2Html %s' % (data[elem]))
                    emit('tailf', {"key" : elem, 
                                   "data": data[elem],
                                   "flowName" : flow_name,
                                   "groupName" : group,
                                   },
                                   broadcast=True)

            spawn.join()  
        sysulib.gui.logger.info('SOCKETgevent.SocketIO/flow_utils/Tailer flow %s::%s ended' % (group, flow_name))
    except:
        error = format_exception(sys.exc_info(), footer='Failed to tail flow: %s' % message)
        sysulib.gui.logger.error(error)
        emit('flow_error', {'error' : error, 'flowName' : flow_name, 'groupName' : group}, broadcast=True)
        return
    emit('flow_ended', {"flowName" : flow_name, "groupName" : group}, broadcast=True)

if __name__ == "__main__":
    from gevent import monkey
    monkey.patch_all()
    app.debug = True
    # TODO - Add support for cleaning and credating the chache directory: settings.TOPOLOGY_CACHE_FILE
    socketio.run(app, host='0.0.0.0')

**Comment by miguelgrinberg** [comment]
When you work with Flask-SocketIO the handlers run in coroutines. To ensure that all the threads get a chance to run, your handlers must be short, or if the are long they need to release the CPU often, by doing a `time.sleep(0)`. This will ensure that new connections and other tasks get their share of CPU.
