### ISSUE TITLE
Issue with socketio.emit and multithreading

### ISSUE THREAD

**Issue by owenkealey** [miguelgrinberg/Flask-SocketIO#973]
Hi,

It seems that whenever I send messages to the client with `socketio.emit("event", {})` the client's event handler either never receives it or receives it minutes after it was sent. This seems to ONLY occur when the socket.io server is `.run` in a different thread than the `socketio.emit` command. 

Heres some example code:

https://hastebin.com/jecedulolu.py

with the client side html file being 

In the context of this code, pressing enter on the server's terminal should send the message to the client and the client(in chrome dev tools) should print out "yes! Received!" but it never does...

I tried all different versions of the client side socket.io library to no avail. Using the latest version of flask-socketio

**Comment by miguelgrinberg** [comment]
Are you using eventlet or gevent? If yes, then you can't use the threading module unless you monkey patch the standard library so that it becomes green-thread compatible.

**Comment by owenkealey** [comment]
I am using gevent, but start_background_task seems to be a suitable replacement for threading.Thread so that's what I am using now

**Comment by miguelgrinberg** [comment]
@owenkealey Yes, that should be fine. But there are a few other areas of the Python standard library that cannot be used in a gevent application unless you monkey patch, so keep that present if you run into more trouble.

**Comment by owenkealey** [comment]
now i am concerned, do you know of a list of things that require monkey patching?

**Comment by miguelgrinberg** [comment]
It's anything that is blocking. Reading or writing to a network socket, threads, processes, sleeping. This is actually pretty standard stuff for async frameworks, you'll find the information in the documentation for gevent.
