### ISSUE TITLE
Dockerized socketio app freezes on Docker for Mac

### ISSUE THREAD

**Issue by Kamforka** [miguelgrinberg/Flask-SocketIO#975]
**System specs:**
OS: MacOS Mojave 10.14.4
Docker for desktop 2.0.0.3
Docker engine: 18.09.2
Flask-SocketIO: 2.9.2 (also tested with 3.3.2)

I have a socketio flask app, it works fine locally but after containerizing the execution hangs and cannot be terminated in an easy way.

Minimal code to reproduce the issue:

**Dockerfile**:
```docker
FROM python:3.6
WORKDIR /app
RUN pip install Flask Flask-SocketIO eventlet
COPY app.py .
EXPOSE 5000
CMD python app.py
```

**app.py**
```python
from flask import Flask, jsonify
from flask_socketio import SocketIO

app = Flask(__name__)


@app.route('/', methods=['GET'])
def index():
    return jsonify({'hello': 'world'})


if __name__ == '__main__':
    socketio = SocketIO()
    socketio.init_app(app)
    socketio.run(
        app, host='0.0.0.0', port=5000, use_reloader=False, debug=False, log_output=True
    )

```

After building and running it like this:
```
docker build -t socketio-app .
docker run socketio-app
```

It just hangs and not showing the expected `(29353) wsgi starting up on http://0.0.0.0:5000` log.

On the other hand if I run the container in an interactive mode it works:
```
docker run -it socketio-app sh
# python app.py
(6) wsgi starting up on http://0.0.0.0:5000
```

Why is that?

**Comment by miguelgrinberg** [comment]
I tested your container image here and it works perfectly fine. The server does not hang for me. The logs work, but they don't immediately because stderr is buffered. Use the following command to get logs right away:

    CMD python -u app.py
