### ISSUE TITLE
Question clearing data from emit/send buffer

### ISSUE THREAD

**Issue by stingram** [miguelgrinberg/Flask-SocketIO#976]
Question: How can I clear the data from the emit/send buffer on client disconnect?

Context:
I have a flask server to handle communications between instances of a desktop application client, and I need a proper way of handling an arbitrary amount of emit events that could go to a client who is offline.

My approach is the following:
1. Store relevant data for emit in a database
2. On client connect, emit data from database, removing data from database only when ack is received
3. On client disconnect, clear all data from emit/send buffer.

**Comment by miguelgrinberg** [comment]
What do you mean by "emit/send buffer"? If you mean the send queue, that disappears when the socket connection breaks. No need to do anything explicit.

**Comment by stingram** [comment]
Think I got it figured out. Thanks!
