### ISSUE TITLE
Issue with socketio.run(app) vs app.run()

### ISSUE THREAD

**Issue by owenkealey** [miguelgrinberg/Flask-SocketIO#977]
Hi,

I am trying to make a proxy server in Flask(which also doubles as a socketio server for other purposes unrelated to the proxy server part) and it seems that whenever I make requests to my server(using the requests module with it's address specified as a proxy in the request), it works fine and it returns what I expect but ONLY if I run it with the normal way of running a standard Flask server. 

Heres an example.

https://hastebin.com/inedeciyah.py

If you start that server on localhost and then make a request to it like so 

https://hastebin.com/eyivicawiz.coffeescript

It will return the contents of test.html(In production the server should be making a request to google.com and returning that to the client instead of test.html but I am doing this to make sure my clients can connect). 

Now, if you run this very same localhost webserver with flask-socketio capabilities like so:

https://hastebin.com/matigalire.py

The same request(from https://hastebin.com/eyivicawiz.coffeescript) receives 404 not found from our web server. I did some debugging and if it helps at all it seems that when run with flask-socket.io the server gets a `request.url` of double whatever you sent it. So if you made a request to `http://127.0.0.1:5000` the flask-socketio webserver registers that as `http://127.0.0.1:5000/http://127.0.0.1:5000` and thus 404. 

Only happens when you use the server as a proxy. 

I am using eventlet.

**Comment by miguelgrinberg** [comment]
There is no code in the links that you provided.

**Comment by owenkealey** [comment]
hastebin took them down fro some reason, 

heres new links

normal server: https://ghostbin.com/paste/o7so8

request: https://ghostbin.com/paste/yuh4x

flask-socketio server: https://ghostbin.com/paste/8sxkv

**Comment by miguelgrinberg** [comment]
The problem appears to be that the eventlet server that you are using does not honor proxied requests. If you switch to the Werkzeug server by forcing the `threading` async_mode, the proxying works fine:

    socketio = SocketIO(app, async_mode='threading')

**Comment by owenkealey** [comment]
I am concerned that this will degrade performance for the socketio side of the server. Maybe Ill just start two seperate servers.

**Comment by miguelgrinberg** [comment]
Yes, it is a problem, but there is nothing I can do from this side to solve the problem. Starting two separate servers is a good solution if that works for you.

**Comment by owenkealey** [comment]
Thanks miguel, closing this now.
