### ISSUE TITLE
Which version of SocketIO client should I be using for with Flask-SocketIO?

### ISSUE THREAD

**Issue by markmnl** [miguelgrinberg/Flask-SocketIO#980]
Unclear which version of client side socket io libraries I can use with Flask-SocketIO..

Can I use npm socket.io-client 2.2.0 with Flask-SocketIO 3.0.2 ??

**Comment by miguelgrinberg** [comment]
To my knowledge, all JS client releases since 1.3.x all the way to the 2.2.x line work fine with this server.
