### ISSUE TITLE
Does Flask-SocketIO use Semantic Versioning?

### ISSUE THREAD

**Issue by dbanty** [miguelgrinberg/Flask-SocketIO#986]
I ask because with 4.0.0 just released I worry that upgrading might break some existing functionality.  I read through the commit messages and CHANGES.md and couldn't see anything that was obviously compatibility breaking.  Near as I can tell you picked 4.0.0 to sync with python-socketio.

**Comment by miguelgrinberg** [comment]
Yes, I do use semantic versioning for this project.

The reason for the jump to v4 is that the python-socketio dependency used to be pinned to the 3.x line and in v4 I removed the pin. The breaking change between python-socketio v3 and v4 is that the default for the `async_handlers` setting changed from `False` in v3 to `True` in v4.

**Comment by dbanty** [comment]
Okay good to know, thanks for responding so quickly!
