### ISSUE TITLE
why the client can not receive the emit data  during connecting?

### ISSUE THREAD

**Issue by chendongxtu** [miguelgrinberg/Flask-SocketIO#989]
```python
@socketio.on("connect", namespace="/test")
def test_connect():
emit("my_response", {"data": "Connected", "count":0})
```
in the test demo, this works well, and i can see the data  {"data": "Connected", "count":0} in the webbrowser.

but if i use it like following:
```python
@socketio.on("connect", namespace="/test")
def test_connect():
emit("my_response", {"data": "Connected", "count":0})
## add here ##
return False
```
then in the browser, it will try to connect, but the strange place is that i can not see the data  {"data": "Connected", "count":0} in the webbrowser console, i have used ipdb to trace, and it really has sent the data. so i am confused why client can not recieve the response data?
can you help me? thanks

this is the pic without return False
![企业微信截图_15591241442631](https://user-images.githubusercontent.com/32007225/58548640-480d7180-823c-11e9-9325-2e4a8be076f2.png)

this is the pic with return False:
![企业微信截图_15591240067634](https://user-images.githubusercontent.com/32007225/58548675-59567e00-823c-11e9-90e5-afc41b7083d5.png)

**Comment by miguelgrinberg** [comment]
What do you return `False`? That has special significance, it's saying that you are rejecting the connection.

**Comment by chendongxtu** [comment]
because i wanna to tell somesthing to the client why i refused the connection before i return False

**Comment by miguelgrinberg** [comment]
Okay, then this is wrong. You have two options to do that:

1. Add the `always_connect=True` setting in the `SocketIO` constructor. This will fully accept the connection before the connect handler is invoked, so you can emit freely. If you return `False`, then a `disconnect()` will be issued to close the connection.

2. Instead of returning `False`, raise a `ConnectionRefusedError` exception, which takes an argument where you can pass an error message back to the client:

```python
from socketio import ConnectionRefusedError

@sio.on('connect')
def connect(sid, environ):
    raise ConnectionRefusedError('authentication failed')
```

**Comment by miguelgrinberg** [comment]
I'm going to leave this issue open as a reminder that I need to properly export the `ConnectionRefusedError` exception from this package, and also to document it here (it is currently only documented in the python-socketio package).

**Comment by chendongxtu** [comment]
okay, thanks very much

**Comment by chendongxtu** [comment]
emm, in fact, the ConnectionRefusedError class is not exported in the socketio/__init__.py,
and the class SocketIo in flask_sockeet does not have the param always_connect in ins' constuctor.
is my flask_socketio version too low?

**Comment by miguelgrinberg** [comment]
@chendongxtu you need to upgrade flask-socketio and all of its dependencies to the latest. As I said above, this package does not have the exception, it is in the python-socketio package, which is a dependency.

**Comment by sirlada** [comment]
hi @miguelgrinberg, sorry to interrupt:
updated Flask-SocketIO to 4.1 and got this error:
_ImportError: cannot import name 'ConnectionRefusedError'_

resolved error through updating python-socketio to latest version.
so i guess the dependencies for python-socketio have to be updated in setup.py
```
install_requires=[
        'Flask>=0.9',
        'python-socketio>=2.1.0'
    ],
```

**Comment by YuqiaoS** [comment]
@miguelgrinberg  When I raise the error, on the client side I get undefined when I console.log the error argument from my 'connect_error' handler. The event seems to be invoked but how do I get the message?

**Comment by miguelgrinberg** [comment]
@YuqiaoS can I see your code?

**Comment by YuqiaoS** [comment]
@miguelgrinberg So the frontend is not printing the error seems to be an error from the https://github.com/MetinSeylan/Vue-Socket.io lib I'm using, as I do get an xhr error when not using that.

But the xhr itself for the io connect returns 401 Unauthorized, with the response of "Unauthorized". It's supposed to return the message passed into the exception right? So is this because maybe some thing is catching exception and handling it? I'm using flask_login as well.

**Comment by miguelgrinberg** [comment]
You are not showing code nor logs, so I cannot say. Get logging enabled in the server and you will see what the server is sending back.

**Comment by YuqiaoS** [comment]
Here's the log. The message seems to be sent.
```
INFO:engineio.server:1b2ab86e02da4cd2a7fef1a3992750b1: Sending packet MESSAGE data 4"i deny u"
WARNING:engineio.server:Application rejected connection
```

**Comment by miguelgrinberg** [comment]
The server is sending a normal message with the string "i deny u". This isn't what I expect would be sent when you raise a connection refused exception. Are you sure you are raising an exception? I just don't see how that could translate to a normal message.

**Comment by YuqiaoS** [comment]
```
from flask_socketio import ConnectionRefusedError

@socketio.on('connect')
def connect():
if not current_user.is_authenticated:
        raise ConnectionRefusedError('i deny u')
```

**Comment by Grkmus** [comment]
This maybe should be seperate topic but `ConnectionRefusedError` is not passing positional arguments to the client in the error packet as it is mentioned in the [documentation](https://flask-socketio.readthedocs.io/en/latest/getting_started.html?highlight=exception#connection-events). It is only sending one string nothing else.
