### ISSUE TITLE
log_file parameter is not logging to file

### ISSUE THREAD

**Issue by davoclavo** [miguelgrinberg/Flask-SocketIO#99]
I am trying to add an access log to my app running a Flask-SocketIO with the following call 

~~~py
log_filename = 'access.log'
socketio.run(app, host='0.0.0.0', port=80, log_file=log_filename)
~~~

It is creating the file but the file is blank. I digged a little bit and found that the `log_file` parameter is passed to the WSGIServer instance as a File object, which is never closed.

This is a valid workaround:

~~~py
logger = logging.getLogger('werkzeug')
handler = logging.FileHandler(log_filename)
logger.addHandler(handler)
~~~

**Comment by miguelgrinberg** [comment]
The start up options have changed in release 1.0, so I'm closing this as it is outdated.
