### ISSUE TITLE
How to use python-socketio AsyncNamespace in flask-socketio?

### ISSUE THREAD

**Issue by gitavi** [miguelgrinberg/Flask-SocketIO#991]
I am looking to asynchronously send messages to a Kafka broker after a `socket.io` event is triggered and also want to maintain the readability of class based namespaces. For example it would look like this:
```python
class CustomAsyncNamespace(AsyncNamespace):
    async on_event(self):
        await ...  # send to broker
```
I noticed that `python-socketio` includes an `AsyncNamespace` class that could accomplish this but `flask-socketio` doesn't. I know that the latter just wraps the former but I'm not sure exactly how `flask-socketio` makes it play better with `Flask`. Surely this is not as simple as doing `socketio.on_namespace(CustomAsyncNamespace('/namespace'))` where `socketio` is an instance of `flask_socketio.SocketIO`? What else would I need to do to make `AsyncNamespace` work with `flask-socketio` as one would expect? Thanks!

**Comment by miguelgrinberg** [comment]
I haven't tested this, but the python-socketio server can be accessed as `socketio.server`. So you may be able to include a class based namespace by doing this:

    socketio.server.on_namespace(CustomAsyncNamespace('/namespace'))

I should note that the `server` attribute is not publicly documented, so it can change in future releases. Give it a try and let me know if this works.

**Comment by gitavi** [comment]
Getting `ValueError: Not a valid namespace class for this server` from [here](https://github.com/miguelgrinberg/python-socketio/blob/61034bb92200e0ed48cef307a6f9e982a802d9cf/socketio/server.py#L224-L237) since the `flask-socketio` `server` is not asyncio based. Would making the server the server an `socketio.AsyncServer` cause any issues with `Flask`? Thanks again.

**Comment by miguelgrinberg** [comment]
Oh, wow. I missed this when you first asked. Why would you use the AsyncNamespace here? Flask is not compatible with asyncio, that's never going to work. For some reason I assumed you were asking about the regular class-based namespace, not the asyncio one.
