### ISSUE TITLE
python-engineio 3.8.0 dep doesn't seem to work with Py2?

### ISSUE THREAD

**Issue by datadidit** [miguelgrinberg/Flask-SocketIO#995]
Started seeing this error when installing Flask-SocketIO. Looks like latest version of that middleware doesn't work with python2? Haven't dug too deep but installing 3.7.0 fixes issue.

![Screen Shot 2019-06-03 at 4 12 24 PM](https://user-images.githubusercontent.com/10933169/58831903-b7f47100-861b-11e9-8447-3032db71bb4e.png)

**Comment by miguelgrinberg** [comment]
Duplicate. See https://github.com/miguelgrinberg/python-engineio/issues/115.
