### ISSUE TITLE
AttributeError: module 'select' has no attribute 'poll'

### ISSUE THREAD

**Issue by neuronflow** [miguelgrinberg/Flask-SocketIO#996]
I am trying to migrate from Flask-SocketIO==3.3.2
 to the newest version 4.0.

I am using python rq for background tasks...the following code crashes when trying to emit a msg to the client:

```
from flask_socketio import SocketIO
import json


def clientID_json_generator(hid):
    socketio = SocketIO(message_queue='redis://')

    with open('cfg/static/elephant_client_version.json') as EcVersionFile:
        EcVersion = json.load(EcVersionFile)

    if hid["elephant_client"] != EcVersion:
        print(hid["elephant_client"])
        print(EcVersion)
        socketio.emit('client_outdated', EcVersion)

    with open('cfg/session/clientidentification.json', 'w') as outfile:
        json.dump(hid, outfile, indent=4)
    socketio.emit('status', {'code': 202, 'message': 'client ID json generation finished!'})

```

the error msg:

```
20:15:00 AttributeError: module 'select' has no attribute 'poll'
Traceback (most recent call last):
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/rq/worker.py", line 812, in perform_job
    rv = job.perform()
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/rq/job.py", line 588, in perform
    self._result = self._execute()
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/rq/job.py", line 594, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/app/elephant/clientidentification.py", line 18, in clientID_json_generator
    socketio.emit('status', {'code': 202, 'message': 'client ID json generation finished!'})
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/flask_socketio/__init__.py", line 400, in emit
    skip_sid=skip_sid, callback=callback, **kwargs)
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/socketio/server.py", line 278, in emit
    skip_sid=skip_sid, callback=callback, **kwargs)
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/socketio/pubsub_manager.py", line 68, in emit
    'host_id': self.host_id})
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/socketio/redis_manager.py", line 76, in _publish
    return self.redis.publish(self.channel, pickle.dumps(data))
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/redis/client.py", line 2716, in publish
    return self.execute_command('PUBLISH', channel, message)
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/redis/client.py", line 772, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/redis/connection.py", line 994, in get_connection
    connection.connect()
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/redis/connection.py", line 500, in connect
    self._selector = DefaultSelector(sock)
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/redis/selector.py", line 196, in DefaultSelector
    return _DEFAULT_SELECTOR(sock)
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/redis/selector.py", line 123, in __init__
    self.read_poller = select.poll()
AttributeError: module 'select' has no attribute 'poll'
Traceback (most recent call last):
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/rq/worker.py", line 812, in perform_job
    rv = job.perform()
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/rq/job.py", line 588, in perform
    self._result = self._execute()
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/rq/job.py", line 594, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/app/elephant/clientidentification.py", line 18, in clientID_json_generator
    socketio.emit('status', {'code': 202, 'message': 'client ID json generation finished!'})
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/flask_socketio/__init__.py", line 400, in emit
    skip_sid=skip_sid, callback=callback, **kwargs)
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/socketio/server.py", line 278, in emit
    skip_sid=skip_sid, callback=callback, **kwargs)
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/socketio/pubsub_manager.py", line 68, in emit
    'host_id': self.host_id})
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/socketio/redis_manager.py", line 76, in _publish
    return self.redis.publish(self.channel, pickle.dumps(data))
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/redis/client.py", line 2716, in publish
    return self.execute_command('PUBLISH', channel, message)
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/redis/client.py", line 772, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/redis/connection.py", line 994, in get_connection
    connection.connect()
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/redis/connection.py", line 500, in connect
    self._selector = DefaultSelector(sock)
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/redis/selector.py", line 196, in DefaultSelector
    return _DEFAULT_SELECTOR(sock)
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/redis/selector.py", line 123, in __init__
    self.read_poller = select.poll()
AttributeError: module 'select' has no attribute 'poll'
```

What am I doing wrong? The code works just fine with the old version.

**Comment by miguelgrinberg** [comment]
Did you use Redis with your previous version? This is an error instantiating a redis connection. It could be lack of monkey patching, or doing it too late.

**Comment by meowlz** [comment]
yes, no changes except for the new flask socketio version. I tried to monkey patch in the very first line without success.

**Comment by miguelgrinberg** [comment]
Do you recall what version of the python-socketio package you had before and after? The problem is in code that is in this package, not flask-socketio.

**Comment by meowlz** [comment]
before: python-socketio==3.1.2

after: 4.1.0

you are right...rolling python-socketio back to 3.1.2 seems to solve the issue for the moment...will do some further testing

**Comment by meowlz** [comment]
Okay...it seems the issue was resolved because I also downgraded rq back to 0.12

as soon as I update I get the above error, my current requirements.txt:
`arrow==0.13.1
Click==7.0
cycler==0.10.0
dnspython==1.16.0
eventlet==0.24.1
Flask==1.0.2
Flask-SocketIO==4.0.0
graphviz==0.10.1
greenlet==0.4.15
itsdangerous==1.1.0
Jinja2==2.10.1
kiwisolver==1.0.1
MarkupSafe==1.1.1
matplotlib==3.0.3
monotonic==1.5
nibabel==2.4.0
nilearn==0.4.2
numpy==1.15.2
pipdeptree==0.13.2
pyparsing==2.4.0
python-dateutil==2.8.0
python-engineio==3.5.1
python-socketio==3.1.2
redis==3.2.1
rq==1.0
rq-dashboard==0.5.1
scikit-learn==0.20.3
scipy==1.2.1
six==1.12.0
sklearn==0.0
Werkzeug==0.14.1
`

dependencies according to pipdeptree:
`eventlet==0.24.1
  - dnspython [required: >=1.15.0, installed: 1.16.0]
  - greenlet [required: >=0.3, installed: 0.4.15]
  - monotonic [required: >=1.4, installed: 1.5]
  - six [required: >=1.10.0, installed: 1.12.0]
Flask-SocketIO==4.0.0
  - Flask [required: >=0.9, installed: 1.0.2]
    - click [required: >=5.1, installed: 7.0]
    - itsdangerous [required: >=0.24, installed: 1.1.0]
    - Jinja2 [required: >=2.10, installed: 2.10.1]
      - MarkupSafe [required: >=0.23, installed: 1.1.1]
    - Werkzeug [required: >=0.14, installed: 0.14.1]
  - python-socketio [required: >=2.1.0, installed: 3.1.2]
    - python-engineio [required: >=3.2.0, installed: 3.5.1]
      - six [required: >=1.9.0, installed: 1.12.0]
    - six [required: >=1.9.0, installed: 1.12.0]
graphviz==0.10.1
matplotlib==3.0.3
  - cycler [required: >=0.10, installed: 0.10.0]
    - six [required: Any, installed: 1.12.0]
  - kiwisolver [required: >=1.0.1, installed: 1.0.1]
    - setuptools [required: Any, installed: 41.0.0]
  - numpy [required: >=1.10.0, installed: 1.15.2]
  - pyparsing [required: >=2.0.1,!=2.1.6,!=2.1.2,!=2.0.4, installed: 2.4.0]
  - python-dateutil [required: >=2.1, installed: 2.8.0]
    - six [required: >=1.5, installed: 1.12.0]
nilearn==0.4.2
  - nibabel [required: >=2.0.2, installed: 2.4.0]
    - numpy [required: >=1.8, installed: 1.15.2]
    - six [required: >=1.3, installed: 1.12.0]
pipdeptree==0.13.2
  - pip [required: >=6.0.0, installed: 19.0.3]
rq-dashboard==0.5.1
  - arrow [required: Any, installed: 0.13.1]
    - python-dateutil [required: Any, installed: 2.8.0]
      - six [required: >=1.5, installed: 1.12.0]
  - Flask [required: Any, installed: 1.0.2]
    - click [required: >=5.1, installed: 7.0]
    - itsdangerous [required: >=0.24, installed: 1.1.0]
    - Jinja2 [required: >=2.10, installed: 2.10.1]
      - MarkupSafe [required: >=0.23, installed: 1.1.1]
    - Werkzeug [required: >=0.14, installed: 0.14.1]
  - redis [required: Any, installed: 3.2.1]
  - rq [required: >=0.3.8, installed: 1.0]
    - click [required: >=5.0, installed: 7.0]
    - redis [required: >=3.0.0, installed: 3.2.1]
sklearn==0.0
  - scikit-learn [required: Any, installed: 0.20.3]
    - numpy [required: >=1.8.2, installed: 1.15.2]
    - scipy [required: >=0.13.3, installed: 1.2.1]
      - numpy [required: >=1.8.2, installed: 1.15.2]
`

**Comment by meowlz** [comment]
So it seems like there is some incompatibility with rq 1.0?

**Comment by miguelgrinberg** [comment]
@meowlz you said that you are monkey patching early, but really the facts contradict what you are saying. Clearly there must be some side effect of switching the RQ version that I believe must be affecting when the monkey patching is done.

I have seen this problem in the past. The Redis client checks if there is a `select.poll` function available, and if it is, then it enables some code that uses it. This choice is made [here](https://github.com/andymccurdy/redis-py/blob/master/redis/selector.py#L108). Eventlet monkey patches the select module and as part of that removes the `poll` function, since it does not provide an implementation of it for greenlets. Your problem is that the select module is not monkey patched at the time redis is imported, and that makes it enable the code that uses `select.poll`. A bit later the monkey patching happens, and `poll` goes away, so the first time it is used you get this error.

**Comment by meowlz** [comment]
Hmmm maybe I am doing the monkey patching wrong?

I experimentally moved it to the very top of my code. I have two python files...one start script:
`from eventlet import monkey_patch as monkey_patch

monkey_patch()

import argparse
from app import create_app, socketio
import json

parser = argparse.ArgumentParser()
parser.add_argument("-d", "--development", help="development mode")

args = parser.parse_args()
print("***************************")
if args.development:
    print("running in development mode")
    mode = "development"
    with open('cfg/session/mode.json', 'w') as outfile:
        json.dump(mode, outfile, indent=4)

else:
    print("running in production mode")
    mode = "production"
    with open('cfg/session/mode.json', 'w') as outfile:
        json.dump(mode, outfile, indent=4)
print("***************************")

with open('cfg/session/mode.json') as json_data_file:
    mode = json.load(json_data_file)

if mode == "development":
    app = create_app(debug=True)

    if __name__ == '__main__':
        socketio.run(app)

else:
    app = create_app(debug=False)

    if __name__ == '__main__':
        socketio.run(app, host="0.0.0.0")
`

here the init file of my app:

`from flask import Flask
from flask_socketio import SocketIO
from eventlet import monkey_patch as monkey_patch

monkey_patch()

from redis import Redis
from rq import Queue

async_mode = "eventlet"
# ping_timeout = 10000000

socketio = SocketIO()


def create_app(debug=False):
    """Create an application."""
    app = Flask(__name__)
    app.debug = debug
    app.config['SECRET_KEY'] = 'secret!'

    # general plugins
    from .elephant import elephant as elephant_blueprint
    app.register_blueprint(elephant_blueprint)

    # nifti conversion
    from app.nifti_conversion.dicom_inspection import dicom_inspection as dicom_inspection_blueprint
    app.register_blueprint(dicom_inspection_blueprint)

    from app.nifti_conversion.nifti_converter import nifti as nifti_blueprint
    app.register_blueprint(nifti_blueprint)

    # project elephant
    from app.project_e.input_inspection import input_inspection as input_inspection_blueprint
    app.register_blueprint(input_inspection_blueprint)

    from app.project_e.image_processing import imageprocessing as imageprocessing_blueprint
    app.register_blueprint(imageprocessing_blueprint)

    from app.project_e.metadata_processing import metadata as metadata_blueprint
    app.register_blueprint(metadata_blueprint)

    from app.project_e.export_archiving import exportarchiving as exportarchiving_blueprint
    app.register_blueprint(exportarchiving_blueprint)

    # BRATS
    from .BRATS import brats as brats_blueprint
    app.register_blueprint(brats_blueprint)

    # t-rex
    from app.trex_standalone.trex_inspection import trex_inspection as trex_inspection_blueprint
    app.register_blueprint(trex_inspection_blueprint)

    from .trex_standalone import trex_standalone as trex_standalone_blueprint
    app.register_blueprint(trex_standalone_blueprint)

    # init the app
    # socketio.init_app(app, message_queue='redis://', ping_timeout=ping_timeout, async_mode=async_mode)
    socketio.init_app(app, message_queue='redis://', async_mode=async_mode)

    return app


# generate rq_queue
redisqueue = Queue(connection=Redis())
heavy_redisqueue = Queue('heavy', connection=Redis())
`

With the old rq version I only have to monkey patch after the imports at the init file and it works:
`from flask import Flask
from flask_socketio import SocketIO
from redis import Redis
from rq import Queue
from eventlet import monkey_patch as monkey_patch
monkey_patch()
`

I also updated eventlet to 0.15 and tried different versions of python-socketio and engineio now.

Thanks for your time!

**Comment by meowlz** [comment]
Do I need to monkey patch not only in the main script but also in every subfile now?

**Comment by miguelgrinberg** [comment]
What command do you use to start the server?

**Comment by meowlz** [comment]
For development the version one in production the second one. In production it resides in a docker therefore providing the host becomes necessary.
```
if mode == "development":
    app = create_app(debug=True)

    if __name__ == '__main__':
        socketio.run(app)

else:
    app = create_app(debug=False)

    if __name__ == '__main__':
        socketio.run(app, host="0.0.0.0")
```

**Comment by meowlz** [comment]
Hmmm I don't see anything that might cause this in the rq 1.0 change log:
https://github.com/rq/rq/releases/tag/v1.0

**Comment by miguelgrinberg** [comment]
Which mode is it failing? Or are both dev and prod having the same problem? Can you provide the output of `pip freeze` for the working and non-working cases?

**Comment by meowlz** [comment]
only tried dev so far...will try prod too!
not working:
```
arrow==0.13.1
Click==7.0
cycler==0.10.0
dnspython==1.16.0
eventlet==0.25.0
Flask==1.0.2
Flask-SocketIO==4.0.0
graphviz==0.10.1
greenlet==0.4.15
itsdangerous==1.1.0
Jinja2==2.10.1
kiwisolver==1.0.1
MarkupSafe==1.1.1
matplotlib==3.0.3
monotonic==1.5
nibabel==2.4.0
nilearn==0.4.2
numpy==1.15.2
pipdeptree==0.13.2
pyparsing==2.4.0
python-dateutil==2.8.0
python-engineio==3.8.0
python-socketio==4.1.0
redis==3.2.1
rq==1.0
rq-dashboard==0.5.1
scikit-learn==0.20.3
scipy==1.2.1
six==1.12.0
sklearn==0.0
Werkzeug==0.14.1
```

working:
```
arrow==0.13.1
Click==7.0
cycler==0.10.0
dnspython==1.16.0
eventlet==0.24.1
Flask==1.0.2
Flask-SocketIO==4.0.0
graphviz==0.10.1
greenlet==0.4.15
itsdangerous==1.1.0
Jinja2==2.10.1
kiwisolver==1.0.1
MarkupSafe==1.1.1
matplotlib==3.0.3
monotonic==1.5
nibabel==2.4.0
nilearn==0.4.2
numpy==1.15.2
pipdeptree==0.13.2
pyparsing==2.4.0
python-dateutil==2.8.0
python-engineio==3.5.1
python-socketio==3.1.2
redis==2.10.6
rq==0.12.0
rq-dashboard==0.4.0
scikit-learn==0.20.3
scipy==1.2.1
six==1.12.0
sklearn==0.0
Werkzeug==0.14.1
```

**Comment by meowlz** [comment]
production version has the same problem:
```
    self.read_poller = select.poll()
AttributeError: module 'select' has no attribute 'poll'
```

**Comment by miguelgrinberg** [comment]
Redis 3.2.0 introduced the use of `select.poll`, but it first checks if this method is available. When not available the `select.select` method is used instead, and this method is compatible with eventlet.

I can use Redis 3.2.0 with the example code in this repository and a monkey-patched standard library. So while I have not enough information to tell you what's wrong on your side, the facts keep indicating that the monkey patching that you are doing is ineffective.

**Comment by meowlz** [comment]
So following this...I start my workers using individual python scripts which are run separately:

```
from eventlet import monkey_patch as monkey_patch

monkey_patch()

import os
import redis
from rq import Worker, Queue, Connection

listen = ['heavy', 'default']

redis_url = os.getenv('REDISTOGO_URL', 'redis://localhost:6379')

conn = redis.from_url(redis_url)

if __name__ == '__main__':
    with Connection(conn):
        worker = Worker(map(Queue, listen))
        worker.work()
```

I also added monkey patching on top there now, with this I get the following error:

```
11:31:03 Worker f82df49ecb524bf98309fc171b0bf0c7: found an unhandled exception, quitting...
Traceback (most recent call last):
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/redis/connection.py", line 492, in connect
    sock = self._connect()
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/redis/connection.py", line 550, in _connect
    raise err
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/redis/connection.py", line 538, in _connect
    sock.connect(socket_address)
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/eventlet/greenio/base.py", line 250, in connect
    self._trampoline(fd, write=True)
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/eventlet/greenio/base.py", line 210, in _trampoline
    mark_as_closed=self._mark_as_closed)
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/eventlet/hubs/__init__.py", line 157, in trampoline
    listener = hub.add(hub.WRITE, fileno, current.switch, current.throw, mark_as_closed)
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/eventlet/hubs/kqueue.py", line 53, in add
    self._control([event], 0, 0)
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/eventlet/hubs/kqueue.py", line 39, in _control
    return self.kqueue.control(events, max_events, timeout)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/rq/worker.py", line 477, in work
    self.execute_job(job, queue)
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/rq/worker.py", line 664, in execute_job
    self.fork_work_horse(job, queue)
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/rq/worker.py", line 603, in fork_work_horse
    self.main_work_horse(job, queue)
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/rq/worker.py", line 681, in main_work_horse
    raise e
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/rq/worker.py", line 678, in main_work_horse
    self.perform_job(job, queue)
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/rq/worker.py", line 801, in perform_job
    self.prepare_job_execution(job, heartbeat_ttl)
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/rq/worker.py", line 716, in prepare_job_execution
    pipeline.execute()
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/redis/client.py", line 3514, in execute
    self.shard_hint)
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/redis/connection.py", line 994, in get_connection
    connection.connect()
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/redis/connection.py", line 497, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 9 connecting to localhost:6379. Bad file descriptor.
```

**Comment by miguelgrinberg** [comment]
Your workers very likely do not need eventlet at all. This is only required for concurrency in the web server.

**Comment by meowlz** [comment]
I find it interesting to note that socketio.emit works in the normal events....only for the functions i enqueue via rq and define a new socketio instance along the lines of 'Emitting from an External Process' from the docs it crashes:
[https://flask-socketio.readthedocs.io/en/latest/](url)

**Comment by miguelgrinberg** [comment]
Well, then it's even more important that you remove eventlet from the RQ worker. If it's only the worker that crashes, then that should fix it. So why did you focus so much on showing me code from the server if it is the worker that is crashing?

**Comment by meowlz** [comment]
I am very sorry, it seems I did not communicate this clear enough. Yes only the worker crashes. From my understanding I have no eventlet in my workers I just tried to monkey patch also there.

events.py: ( this emit arrives at the frontend)
```
from .. import socketio, redisqueue
from .clientidentification import clientID_json_generator

@socketio.on('clientidentification')
def schedule_hid_json(hid):
    socketio.emit('status', {'code': 201, 'message': 'clientID json generation queued!'})
    jsongeneration = redisqueue.enqueue(clientID_json_generator, hid, job_timeout=100)
```

clientidentification.py (this emit crashes the worker):
```
from flask_socketio import SocketIO
import json


def clientID_json_generator(hid):
    socketio = SocketIO(message_queue='redis://')
    ...
    unrelated code
    ...

    socketio.emit('status', {'code': 202, 'message': 'client ID json generation finished!'})
```

the worker is started with this script, however a worker started from terminal with "rq worker" crashes with the same error:

```
import os
import redis
from rq import Worker, Queue, Connection

listen = ['heavy', 'default']

redis_url = os.getenv('REDISTOGO_URL', 'redis://localhost:6379')

conn = redis.from_url(redis_url)

if __name__ == '__main__':
    with Connection(conn):
        worker = Worker(map(Queue, listen))
        worker.work()
```

**Comment by miguelgrinberg** [comment]
As I said before, the workers do not need eventlet at all. Create your Socket.IO object with the `threading` async_mode and do not monkey patch.

**Comment by meowlz** [comment]
Not sure if I understood you correctly...so I tried this:


clientidentification.py (the code running on the worker)
```
 def clientID_json_generator(hid):
    socketio = SocketIO(message_queue='redis://', async_mode='threading')
```

I also tried to remove the monkey patching and eventlet completely from my program  but then the websockets will not even connect.

**Comment by miguelgrinberg** [comment]
No, I think you are mixing up the server and the workers.

For the server you want `async_mode='evenlet'` (the default) and monkey patching.
For the workers you want `async_mode='threading'` and no monkey patching.

**Comment by meowlz** [comment]
Okay, this is what I have then. The server is fired up with eventlet (see this post here: https://github.com/miguelgrinberg/Flask-SocketIO/issues/996#issuecomment-498882228 )

and I added the threading parameter for the code running on the workers (like clientidentification.py ) but no success.

**Comment by miguelgrinberg** [comment]
> but no success

I need exact details of what's not working in this last test.

**Comment by meowlz** [comment]
Okay, I uninstalled everything and reinstalled every dependency. Then updated one app after the other to the most recent version except for scikit-learn checking if it still works after every update...my last steps was to update rq to 1.0 and for some reason it is working now. I did not change any code and I still do not understand what is different now.

Thank you for investing so much time to help me and for making such a great app Miguel!

if anyone wonders, my working configuration now:

```
eventlet==0.25.0
  - dnspython [required: >=1.15.0, installed: 1.16.0]
  - greenlet [required: >=0.3, installed: 0.4.15]
  - monotonic [required: >=1.4, installed: 1.5]
  - six [required: >=1.10.0, installed: 1.12.0]
Flask-SocketIO==4.0.0
  - Flask [required: >=0.9, installed: 1.0.3]
    - click [required: >=5.1, installed: 7.0]
    - itsdangerous [required: >=0.24, installed: 1.1.0]
    - Jinja2 [required: >=2.10, installed: 2.10.1]
      - MarkupSafe [required: >=0.23, installed: 1.1.1]
    - Werkzeug [required: >=0.14, installed: 0.15.4]
  - python-socketio [required: >=2.1.0, installed: 4.1.0]
    - python-engineio [required: >=3.8.0, installed: 3.8.0]
      - six [required: >=1.9.0, installed: 1.12.0]
    - six [required: >=1.9.0, installed: 1.12.0]
graphviz==0.11
joblib==0.13.2
matplotlib==3.1.0
  - cycler [required: >=0.10, installed: 0.10.0]
    - six [required: Any, installed: 1.12.0]
  - kiwisolver [required: >=1.0.1, installed: 1.1.0]
    - setuptools [required: Any, installed: 41.0.1]
  - numpy [required: >=1.11, installed: 1.16.4]
  - pyparsing [required: >=2.0.1,!=2.1.6,!=2.1.2,!=2.0.4, installed: 2.4.0]
  - python-dateutil [required: >=2.1, installed: 2.8.0]
    - six [required: >=1.5, installed: 1.12.0]
nilearn==0.5.2
  - nibabel [required: >=2.0.2, installed: 2.4.1]
    - numpy [required: >=1.8, installed: 1.16.4]
    - six [required: >=1.3, installed: 1.12.0]
pipdeptree==0.13.2
  - pip [required: >=6.0.0, installed: 19.1.1]
rq-dashboard==0.5.1
  - arrow [required: Any, installed: 0.14.2]
    - python-dateutil [required: Any, installed: 2.8.0]
      - six [required: >=1.5, installed: 1.12.0]
  - Flask [required: Any, installed: 1.0.3]
    - click [required: >=5.1, installed: 7.0]
    - itsdangerous [required: >=0.24, installed: 1.1.0]
    - Jinja2 [required: >=2.10, installed: 2.10.1]
      - MarkupSafe [required: >=0.23, installed: 1.1.1]
    - Werkzeug [required: >=0.14, installed: 0.15.4]
  - redis [required: Any, installed: 3.2.1]
  - rq [required: >=0.3.8, installed: 1.0]
    - click [required: >=5.0, installed: 7.0]
    - redis [required: >=3.0.0, installed: 3.2.1]
sklearn==0.0
  - scikit-learn [required: Any, installed: 0.20.3]
    - numpy [required: >=1.8.2, installed: 1.16.4]
    - scipy [required: >=0.13.3, installed: 1.3.0]
      - numpy [required: >=1.13.3, installed: 1.16.4]
```
