### ISSUE TITLE
problem with "many requests"

### ISSUE THREAD

**Issue by ChristianYeah** [miguelgrinberg/Flask-SocketIO#997]
I tested on the demo code,
My huey jobs will pre-connect the socketio server, there will be 74 established connections, then the code losts the capability to deal with any new income request(actually it stopped responding), 400 bad request will show up in the browser side.

I tried eventlet + gunicorn but it doesnt work

browser side
```
POST http://xxx.com/socket.io/?EIO=3&transport=polling&t=1559731661963-105&sid=59c8ff609c874981abededef6e9b6a93 400 (BAD REQUEST)

WebSocket connection to 'ws://xxx.com/socket.io/?EIO=3&transport=websocket&sid=59c8ff609c874981abededef6e9b6a93' failed: WebSocket is closed before the connection is established.
```

I start another python session and try to connect to the service, it raises the error after a long time waiting
```
socketio.exceptions.ConnectionError: Connection refused by the server
```

**Comment by miguelgrinberg** [comment]
This package does not have a limit on the number of connections, so the limit that you are reaching must be somewhere else. Can you enable logging in the server? That should provide additional information. To enable logs add `logger=True, engineio_logger=True` to the `SocketIO` class.

**Comment by ChristianYeah** [comment]
@miguelgrinberg I believe so. I'm checking through everything, it is more likely to be the problem of loading balancer currently

**Comment by ChristianYeah** [comment]
@miguelgrinberg I did a local test, the problem solved by adding ```ip_hash;``` to local nginx upstream config. I don't quite understand the session in socket, is that the problem of sharing session among backend servers? may I ask if there is any solution to this(I tried some but none of them works)

**Comment by miguelgrinberg** [comment]
The solution is what you did, ensure that clients are always sent to the same backend server. REST servers are stateless so this isn't a problem. Socket.IO servers are stateful, so session affinity is required at this time. Moving the session data to shared storage is complicated and inefficient.

**Comment by ChristianYeah** [comment]
I got it. thank you @miguelgrinberg
