### ISSUE TITLE
Problem when training pytorch model

### ISSUE THREAD

**Issue by Sotatek-HoangTran** [miguelgrinberg/Flask-SocketIO#998]
I'm making a real-time facial recognition web app. It works fine in the prediction stage. But when I want to train to add a new face
`@socketio.on("train")
def start_train(message):
	print(message['message'])
	_train()`
i got this error:
`AssertionError:
Exception ignored in: <function _after_fork at 0x7fbe881b4730>
Traceback (most recent call last):
  File "/home/sotatek/anaconda2/envs/hoangtran/lib/python3.7/threading.py", line 1335, in _after_fork
    assert len(_active) == 1
AssertionError:`
I really need your help to solve this problem. Thanks for your reading!

**Comment by miguelgrinberg** [comment]
This isn't related to this package, I think. Are you doing anything with processes like forking?

**Comment by Sotatek-HoangTran** [comment]
No, I don't. My idea is when getting a message from the client after click a button. The server starts train model with a new face. When it done send another message to the client through socketio. Maybe I got this problem cause training pytorch model and flask-socketio same time but don't know exactly why.

**Comment by miguelgrinberg** [comment]
Do you have a more complete stack trace of this error, or is the above the only information you get on your console?

**Comment by Sotatek-HoangTran** [comment]
This all I got.

**Comment by miguelgrinberg** [comment]
Are you using eventlet or gevent in your project?

I'm not very knowledgeable in the pytorch area, but based on the fact that it is a CPU heavy area, and an implementation that uses C native code my bet is that it is incompatible with async frameworks. So if you are using one of these, you should test uninstalling them from your virtualenv and see if that improves things. You'll lose the ability to use WebSocket, but at least we'll know what the problem is.

**Comment by Sotatek-HoangTran** [comment]
I'm using eventlet.

**Comment by Sotatek-HoangTran** [comment]
When I try with other flask server and send the message by json, it's work. But it's kind of inconvenience when need 2 server: 1 for real-time prediction and 1 for training.

**Comment by miguelgrinberg** [comment]
You cannot use CPU intensive tasks in an Eventlet server.

**Comment by Sotatek-HoangTran** [comment]
OK. Thanks for your help.
