### ISSUE TITLE
how to send binary data to the client

### ISSUE THREAD

**Issue by rmundkowsky** [miguelgrinberg/Flask-SocketIO#999]
I am able to send binary data from web browser (the client) to the python server, But can you explain how to send binary data back to the client?

I am able to send binary data to the client like this:

emit('to-client',{'data': bytes(bufferArray) } )

But when I try to convert it back to a Blob, it fails.  The client code looks like:

g_socket.on('to-client', function(json) {
var blob = new Blob(json.data, { 'type' : 'audio/ogg; codecs=opus' });
...
}

**Comment by miguelgrinberg** [comment]
Don't you need to pass an array of things to the Blob constructor? You are passing just the bytes.

**Comment by rmundkowsky** [comment]
thanks for the help.  This seems to work:

g_socket.on('to-client', function(json) {
var b = [new Uint8Array(json.data)];
var blob = new Blob(b, { 'type' : 'audio/ogg; codecs=opus' });
...
}
